### ISSUE TITLE
Sequence Images Case

### ISSUE THREAD

**Issue by lizhengning** [colmap/colmap#10]
Hi
I used the colmap for some sequence images, like KITTI dataset, it results in **Could not find good initial pair.** even I put in some stereo images. And I wonder how the first pairwise images are found, if the first pair are stereo images, I think it's a good initial.

**Comment by ahojnnes** [comment]
Did you perform matching? I suggest to use sequential matching with loop detection. I am not sure about the frame rate in KITTI, but if the initialization fails, you should try to increase matching overlap. Otherwise, you could try to reduce the thresholds for initializing the reconstruction in ``Reconstruction Options > Init > ...``. Let me know if that helps, otherwise you could share the database file with me and I can have a look.

**Comment by lizhengning** [comment]
Yes, I perform the matching, and tried to set a lower init_min_tri_angle, then the colmap go exhaustively initialize with pairwise images but return a result of   Termination : No convergence in BA. I thinks it might because the frame rate is too high(10 frames/sec), and the motion is too small for triangulation, and when the motion is good, the two images couldn't see much in common. And I am gonna select some keyframes from the dataset and try again.
FYI the datatset is http://www.cvlibs.net/datasets/kitti/eval_odometry.php here

**Comment by lizhengning** [comment]
Actually, I think SFM for sequence images especially the monocular sequence with small rotation is quite difficult, and according to my experience, it may be better to perform visual odometry in the first place, since initialize with pairwise frames can't get very good 3D point clouds to present a PNP in the following.

**Comment by lizhengning** [comment]
And I just tried stereo case, it works good!

**Comment by ahojnnes** [comment]
You should be able to get a good reconstruction with COLMAP for KITTI, just the initialization might be tricky. Try to manually select a good image pair and make sure to set or fix the calibration.

**Comment by ahojnnes** [comment]
@lizhengning To follow up on this issue, do you have any other questions or it worked as you wanted? Otherwise, I'll close this issue.

**Comment by lizhengning** [comment]
Ok，thanks！
