### ISSUE TITLE
Error when calling PBA

### ISSUE THREAD

**Issue by xianggao1989** [colmap/colmap#100]
Hi,
I am using the Windows binary version of COLMAP and benefit a lot from it. By defaut parameter setting, the system will call the PBA instead of Ceres after a few cameras have been calibrated. However, with the same parameter setting and input, COLMAP crashed in one of my PC with the error report "ComputeProjection:   invalid device function(8)". Can you help me to deal with it?
Thank you very much!
Best regards,
Xiang Gao from NLPR, CASIA

**Comment by ahojnnes** [comment]
Did you try the latest version or are you by chance using an outdated version? If possible try to download the "unstable" version?

**Comment by xianggao1989** [comment]
Thanks for your reply!
I tried the "unstable" version and it works now.
