### ISSUE TITLE
How to access COLMAP-optimised intrinsics?

### ISSUE THREAD

**Issue by adizhol** [colmap/colmap#1008]
Hello,
I want to use an initial guess for the camera intrinsics and distortion, and access the optimised values after sparse or dense reconstruction.
I can only see the pinhole intrinsics in the camera.bin file.

**Comment by tsattler** [comment]
For dense reconstruction, Colmap undistorts the images (resulting in images that are modeled by the pinhole camera model). Please look at the intrinsics in the sparse reconstruction before the dense reconstruction step.

**Comment by adizhol** [comment]
hmm... in the sparse model folder, the camera file has only a pinhole camera, but I set SIMPLE_RADIAL for the pipeline.
At least I think I did...

**Comment by tsattler** [comment]
Are you looking at the sparse model in the folder with the dense reconstruction? This is the model with undistorted images. You should have a look at the sparse model that was computed initially before dense reconstruction.

**Comment by adizhol** [comment]
oh.... yeah... that's probably the cause.
Thank you!
closing this issue
