### ISSUE TITLE
I found that this code could cause bugs when the visual index with indexed images was read

### ISSUE THREAD

**Issue by wjbKimberly** [colmap/colmap#101]
When I use colmap to read an existing visual index, I found that "image_id" has always been -1.

In `colmap/src/retrieval/inverted_file_entry.h:53`
`  image_id = static_cast<int>(image_id);`

Whether this code will produce ambiguity, resulting in the value is not assigned to "this-> image_id", but assigned to the local variable "image_id".

I change the L - Value to"this->image_id" and avoid the issue successfully.

`this->image_id = static_cast<int>(image_id);`

Or the running result of the code is different on different C++ versions?
( ◕‿‿◕ )

**Comment by ahojnnes** [comment]
Fixed here: https://github.com/colmap/colmap/commit/13feaea22ae8cea8fa6fae542f90dedcb1e4998b

Thanks very much!
