### ISSUE TITLE
Random behaviour of sparse reconstruction

### ISSUE THREAD

**Issue by vinayver198** [colmap/colmap#1010]
Hi ,

I am getting random result by running same pipeline.
These are commands that I am running for sparse reconstruction.

colmap feature_extractor --ImageReader.single_camera_per_folder=1   --database_path $DATASET_PATH/database.db    --image_path $DATASET_PATH/$IMAGES_FOLDER    --SiftExtraction.use_gpu 1 --SiftExtraction.max_image_size 960

colmap spatial_matcher --database_path $DATASET_PATH/database.db --SpatialMatching.max_num_neighbors=30

colmap mapper --database_path $DATASET_PATH/database.db --image_path $DATASET_PATH/$IMAGES_FOLDER --output_path $DATASET_PATH/sparse --Mapper.ignore_watermarks=1 --Mapper.multiple_models=1 --Mapper.ba_local_max_num_iterations=5 --Mapper.ba_global_use_pba=1 --Mapper.ba_global_max_num_iterations=5

Number of images : 900 
Also I have 3 cameras so they are arranged in separate folders.
Results after 1st run : 
Number of sparse models  = 2
Number of images in 0th sparse reconstruction : 11  and also of same camera 
Number of images in 1st sparse reconstruction : 900  and 900 images belong to 3 cameras for eg 300 for 1st,300 for 2nd and 300 for 3rd.
 
Results after 2nd run : 
Number of sparse models :  1
Number of images in 0th sparse reconstruction : 900  and 900 images belong to 3 cameras for eg 300 for 1st,300 for 2nd and 300 for 3rd.

I am unable to understand why this random behaviour is com tried to use database of 1st run and re produce the results but was unable to do so.

Help needed related to this query

**Comment by vinayver198** [comment]
Hi @tsattler , thanks for the reply. One more question in this matter. In mapper function can I increase parameter for "**finding initial pairs** " . I found **--Mapper.max_reg_trials** relevant to this. Am I right in this direction. ?

**Comment by tsattler** [comment]
The parameters named `init_` are related to the initialization.

**Comment by vinayver198** [comment]
@tsattler Thanks
