### ISSUE TITLE
Dense reconstruction uses only a subset of images from sparse reconstruction ?

### ISSUE THREAD

**Issue by szx0112** [colmap/colmap#1012]
Hi, colmap is a great project. Currently, all input images are used in the SFM and MVS steps.  I wonder if I can use only a subset of images for dense reconstruction (sparse reconstruction still uses all images) ?

For example, 100 images are used for sparse reconstruction (i.e. feature_extractor, exhaustive_matcher and mapper).
Then, I'd like to chose only 60 of those 100 images for (partial) dense reconstruction (i.e. patch_match_stereo, stereo_fusion).

The reason is that I need the 100 images to find the correct camera poses and point correspondences (avoids the dis-connected models), but I'd like to see what is the dense reconstruction result only from those 60 images.

Is it possible to enable such feature? If yes, which step should I modify and how? Any comment is appreciated.

**Comment by tsattler** [comment]
You can use the `image_deleter` to remove images from a sparse model before starting the dense reconstruction process.
