### ISSUE TITLE
Freeze camera parameters

### ISSUE THREAD

**Issue by Dawars** [colmap/colmap#1013]
**Is your feature request related to a problem? Please describe.**
I have created a reconstruction using high quality photos I had taken, I would like to extend the reconstruction (register new images) from an internet photo collection. I would not like the new photos to mess up the existing cameras.

**Describe the solution you'd like**
On option to freeze camera parameters (intrinsics/extrinscs) so that they do not change during bundle adjustment

**Describe alternatives you've considered**
Can't think of an alternative

**Additional context**
I haven't been able to take aerial photos / photos from windows, therefore the reconstruction has holes which I would like to fill with the internet photo collection.

![image](https://user-images.githubusercontent.com/1162980/96333485-7e82a100-106a-11eb-93ab-3e695290ae20.png)

**Comment by tsattler** [comment]
The `--Mapper.fix_existing_images` option of the `mapper` should implement exactly this (but you can check the source code for details).

**Comment by Dawars** [comment]
Thank you, this is what I've been looking for

**Comment by xuxumiao777** [comment]
@Dawars @tsattler This is what I am looking for. However, after I add --Mapper.fix_existing_images 1, the translation has been modified. Does this happen when you use it?
