### ISSUE TITLE
how to use "mask path"

### ISSUE THREAD

**Issue by TheRustlessSummer** [colmap/colmap#1016]
Hello , thanks for your code , I have a question about how to use mask path.
When I want to extract only part of the feature points and reconstruct based on these points , how should I use "mask_path"? And what should I put in this folder ?

**Comment by tsattler** [comment]
Masking of image regions before feature extraction is documented here: #522

**Comment by TheRustlessSummer** [comment]
> Masking of image regions before feature extraction is documented here: #522

Thanks for your reply.
Is the mask image have the same size with image ? And how to deal with the unmasked block of the image ? Keep original image or do some other operation？

**Comment by prasadvagdargi** [comment]
Mask images (with image regions set as 1) have to be the same size as the image. You can pad the rest of the image (background) with 0 to ignore it.

The unmasked image(background, where the mask values are 0, I assume) are automatically ignored, you do not need to perform any operation on it.

**Comment by TheRustlessSummer** [comment]
> Mask images (with image regions set as 1) have to be the same size as the image. You can pad the rest of the image (background) with 0 to ignore it.
> 
> The unmasked image(background, where the mask values are 0, I assume) are automatically ignored, you do not need to perform any operation on it.

OK , thanks for your reply. >.<
