### ISSUE TITLE
if I want to resize the image

### ISSUE THREAD

**Issue by TheRustlessSummer** [colmap/colmap#1018]
Hello, thanks for your code, I have a question when I run this code.
The image I got is 1920*1080 , but the speed is too slow, and some question will happen when do dense reconstruction. So I want to reduce image size from 1920*1080 to 920*540. What should I do? Resample before feature extraction? Will this operation influence the reconstruction?

**Comment by prasadvagdargi** [comment]
Please read https://colmap.github.io/faq.html#speedup-dense-reconstruction

You could resample and extract features if you do not have priors on camera intrinsics I suppose.

**Comment by TheRustlessSummer** [comment]
> Please read https://colmap.github.io/faq.html#speedup-dense-reconstruction
> 
> You could resample and extract features if you do not have priors on camera intrinsics I suppose.

thanks for your reply and I will have a try
