### ISSUE TITLE
Rome model

### ISSUE THREAD

**Issue by HUSTyanchao** [colmap/colmap#102]
Hi，Could you please share the Rome model mentioned in your paper Structure-from-Motion Revisited. I would like to use the model in my research experiment, but there are too many images, my machine can not handle that many images. Thanks a lot!

**Comment by ahojnnes** [comment]
Is this still relevant? I can share a similar model with more registered images but not the same as produced in the "Structure-from-Motion Revisited" paper.

**Comment by HUSTyanchao** [comment]
A similar one is okay. It is very kind of you to do that. I would like to have fun with the model.

**Comment by ahojnnes** [comment]
Can you send me a private email and I will send you the model. Thanks.
