### ISSUE TITLE
Point cloud fusion

### ISSUE THREAD

**Issue by TheRustlessSummer** [colmap/colmap#1021]
Hello, thanks for your excellent code.
I have a question of point cloud fusion. I shoot around an object and use the captured pictures as my own data set to reconstruct. But I found that using the entire data set image for reconstruction is not good, so I divide the data set into several parts to reconstruct. And I want to fusion these point cloud to a whole.
I wonder how to fusion these point cloud? If I want to fusion the point cloud and camera poses before dense reconstruction , what should I do?

**Comment by tsattler** [comment]
You could first do a sparse reconstruction from all images and then remove a subset of the images before dense reconstruction (see #1012 ).

**Comment by TheRustlessSummer** [comment]
> You could first do a sparse reconstruction from all images and then remove a subset of the images before dense reconstruction (see #1012 ).

OK, I will have a try. 
And there is another question, how should I see the camera's intrinsics parameters after reconstruction? And how can I see the data in `.bin` file? Or how can I change this file from `.bin` to `.txt` ?

**Comment by tsattler** [comment]
Please see here (https://colmap.github.io/format.html) for a description of the file format and how to convert from binary to text files.

**Comment by TheRustlessSummer** [comment]
> Please see here (https://colmap.github.io/format.html) for a description of the file format and how to convert from binary to text files.

Thanks a lot for your reply
