### ISSUE TITLE
Is duplicate image a big problem?

### ISSUE THREAD

**Issue by tgxs002** [colmap/colmap#1022]
Hi,

Thank you for developing such a great tool for automatic reconstruction! I'm doing a project using large scale image dataset collected from the internet. After checking the images, I found there are a lot of duplicated ones in the data. Will that have a big impact on the reconstruction quality or introduce a big bias?

Thank you for your time and patience!

Regards,
Blakey Wu

**Comment by ahojnnes** [comment]
Duplicate images will significantly slow down the reconstruction process. They might also add additional noise. If it's easy to filter them as a preprocessing step, then I highly recommend doing that.

**Comment by tgxs002** [comment]
Thank you!
