### ISSUE TITLE
Find the image ids/names not successfully registered in the sparse model

### ISSUE THREAD

**Issue by szx0112** [colmap/colmap#1024]
Hi, Colmap is great software. I found sometime not all imported images get registered in the sparse reconstruction (can be caused by insufficient overlap or scaling problem I think), then those images are skipped at the dense reconstruction step. I wonder if we can view or export the id/filename of those skipped images so I can adjust them for better reconstruction result.

Any comment is appreciated.

**Comment by tsattler** [comment]
The sparse 3D model stores the names and image ids of the images that are contained in the reconstruction. If you want to determine which images are not in the sparse reconstruction, you could compare a list of images in the database (i.e., the images that you are trying to reconstruct) and the images in the model.

**Comment by szx0112** [comment]
Got it. THanks.
