### ISSUE TITLE
How to use colmap depth image to get point clouds?

### ISSUE THREAD

**Issue by ZhixiongSun** [colmap/colmap#1028]
I want to use colmap to get the depth images of the imges, and then reproject them into point clouds.
I used the eth3d dataset to test this idea and successfully reconstructed the scene.
But when I use the depth map generated by colmap to get the point cloud, there is a problem, the point cloud obtained from the depth map seems to be wrong. 
I used the depth map reading script read_write_dense.py provided by the github colmap project.
Then use the camera internal parameters to reproject the point cloud using following code:

```
def depth_img_to_pointcld(depth_img):
    f=3724.800000
    cx=1552.000000
    cy=1034.500000
    points=[]
    for u in range(0,depth_img.shape[0]):#x coordinate in image
            for v in range(0,depth_img.shape[1]):#y coordinate in image
                zw=depth_img[u,v]
                xw=(u-cx)*zw/f
                yw=(v-cy)*zw/f
                point=[xw,yw,zw]
                if not(xw==0 and yw==0 and zw==0):
                     points.append(point)
    points=np.array(points)
    return points
```
The camera internal parameters are directly copied from the colmap software,
But the obtained point cloud is wrong. Did I miss something, or I need to use external parameters to convert the point cloud to the world coordinate system to get the correct point cloud？
![Screenshot_2](https://user-images.githubusercontent.com/45487039/97053902-14935b80-1584-11eb-8139-239d409e1fa0.png)
![Screenshot_3](https://user-images.githubusercontent.com/45487039/97053906-165d1f00-1584-11eb-9fa7-14bb684a99b6.png)
![Screenshot_1](https://user-images.githubusercontent.com/45487039/97053915-18bf7900-1584-11eb-9bf5-6049fe0b39e6.png)

**Comment by ahojnnes** [comment]
You have to swap the u/v variables. The first dimension of the depth map is y, the second one is x.

**Comment by ZhixiongSun** [comment]
> You have to swap the u/v variables. The first dimension of the depth map is y, the second one is x.

Thanks a lot for your fast repond.
I swap u/v like this, 
```
def depth_img_to_pointcld(depth_img):
    f=3724.800000
    cx=1552.000000
    cy=1034.500000
    points=[]
    for v in range(0,depth_img.shape[0]):#x coordinate in image
            for u in range(0,depth_img.shape[1]):#y coordinate in image
                zw=depth_img[v,u]
                xw=(u-cx)*zw/f
                yw=(v-cy)*zw/f
                point=[xw,yw,zw]
                if not(xw==0 and yw==0 and zw==0):
                     points.append(point)
    points=np.array(points)
    return points
```
but get the same result. It just swap the x,y coordinates, the angel still looks wrong.

**Comment by duanqg** [comment]
深度图（depthmap）的分辨率与color的分辨率不同，fx，fy，cx，cy需要乘分辨率的比率
