### ISSUE TITLE
Same illegal memory access issue from #79

### ISSUE THREAD

**Issue by sbarkby** [colmap/colmap#103]
Hi Johannes

I'm now experiencing a similar issue to #79 .

Up until now I have been using a previous commit (0a25983) from the 16th January. In this commit I use the default MatchOptions.max_num_matches of 32768 and it works fine.

Now that I have updated to the most current commit I get the following error message when running the exhaustive feature matcher:

MultiplyDescriptor:	out of memory
MultiplyDescriptor:	an illegal memory access was encountered

MultiplyDescriptor:	an illegal memory access was encountered
*** Aborted at 1491578639 (unix time) try "date -d @1491578" if you are using GNU date ***
MultiplyDescriptor:	an illegal memory access was encountered
PC: @ 0xc2a87b SiftMatchCU::GetBestMatch()
MultiplyDescriptor:	an illegal memory access was encountered
MultiplyDescriptor:	an illegal memory access was encountered
MultiplyDescriptor:	an illegal memory access was encountered
MultiplyDescriptor:	an illegal memory access was encountered
*** SIGSEGV (@0x7f5f37af95a0) received by PID 10285 (TID 0x7f5e367fc700) from PID 934253984; stack trace: ***
MultiplyDescriptor:	an illegal memory access was encountered
@ 0x7f5e87d7b390 (unknown)
MultiplyDescriptor:	an illegal memory access was encountered
@ 0xc2a87b SiftMatchCU::GetBestMatch()
@ 0xc230d6 SiftMatchGPU::GetGuidedSiftMatch()
@ 0x6eabd6 colmap::MatchGuidedSiftFeaturesGPU()
@ 0x6f2a77 colmap::GuidedSiftGPUFeatureMatcher::Run()
MultiplyDescriptor:	an illegal memory access was encountered
@ 0x78393c colmap::Thread::RunFunc()
MultiplyDescriptor:	an illegal memory access was encountered
@ 0x7f5e85224c80 (unknown)
@ 0x7f5e87d716ba start_thread
MultiplyDescriptor:	an illegal memory access was encountered
@ 0x7f5e8498a82d clone
MultiplyDescriptor:	an illegal memory access was encountered
@ 0x0 (unknown)
Segmentation fault (core dumped)

As you recommended I restricted MatchOptions.max_num_matches to 12400 and this does prevent colmap from breaking. However in doing so I now get warning messages about my maximum being too small! saying that the matches are being "clamped". The density of the resulting point cloud is also reduced.

Is there any other option you recommend tweaking so that I can still run colmap with my gpu at a max num match of 32768? Until then I'm forced to remain at commit 856ae5ad92bbe1eaa8a629048d0cd9079d1dfecf (Create methods to clear and reset job queue), which is the last working commit that doesn't break at the 32768 max.

Cheers

**Comment by ahojnnes** [comment]
The older commit behaves just the same as now, with the difference that it doesn't warn you about the features being clamped. It just silently did it. There is no way around this other than buying a better GPU with more memory or using CPU matching, which will be very slow. Let me know if you have other questions.

**Comment by ahojnnes** [comment]
This is documented here now: https://colmap.github.io/faq.html#feature-matching-fails-due-to-illegal-memory-access

**Comment by sbarkby** [comment]
Hi Johannes

Thanks for the speedy response. 

Just to clarify the older commit can handle a  MatchOptions.max_num_matches of 32768 whereas the new commit runs out of memory at this setting  (at least with the resources on my machine). Are you saying that the old commit used to automatically and silently clamp features below the 32768 match limit to avoid running out of memory whereas the new commit doesn't?

**Comment by ahojnnes** [comment]
Can you try the latest commit but undoing the change here: https://github.com/colmap/colmap/commit/ac3e24dc3282d7c152068617adc9c3bf8631be12 ?

**Comment by ahojnnes** [comment]
Can you also report the CUDA version and GPU model on your system?

**Comment by sbarkby** [comment]
I tried undoing the change contained in the ac3e24d commit but after rebuilding and running I still get the same MultiplyDescriptor memory error. I'm on a Linux machine running Ubuntu 16.04.1 LTS. nvidia-smi output is shown below:

Tue Apr 11 13:46:54 2017       
+-------------------------------------------------------------------------------------------------------------------------+
| NVIDIA-SMI 375.39                                                                 Driver Version: 375.39                    |
|--------------------------------------------------+----------------------------------+-----------------------------------+
| GPU  Name                 Persistence-M   | Bus-Id               Disp.A       | Volatile Uncorr. ECC            |
| Fan   Temp      Perf    Pwr:Usage/Cap  |                 Memory-Usage  | GPU-Util  Compute M.         |
|===============================+======================+======================|
|   0     Quadro K620         Off                  | 0000:02:00.0                On |                                       N/A |
| 34%   38C          P8        1W /  30W      |              229MiB /  1999MiB |      0%                      Default |
+-------------------------------------------------+-----------------------------------+-----------------------------------+
