### ISSUE TITLE
Error while executing automatic reconstructor in colmap

### ISSUE THREAD

**Issue by zalakb14** [colmap/colmap#1032]
It crashes when I run from colmap gui and gets the following error while executing from command prompt:

Check failed: num_cuda_devices > 0 (0 vs. 0)
*** Check failure stack trace: ***
    @   00007FFEA1415FCB  public: void __cdecl google::LogMessage::Flush(void) __ptr64
    @   00007FFEA1414B29  public: __cdecl google::LogMessageFatal::~LogMessageFatal(void) __ptr64
    @   00007FF66DFCD216  (unknown)
    @   00007FF66DFCC301  (unknown)
    @   00007FF66DF56944  (unknown)
    @   00007FF66DEC40C7  (unknown)
    @   00007FF66DEB7A16  (unknown)
    @   00007FF66DEFB81C  (unknown)
    @   00007FF66E4DE924  (unknown)
    @   00007FFEB3AB7034  BaseThreadInitThunk
    @   00007FFEB48DCEC1  RtlUserThreadStart

Please help me to solve this issue. Thanks in advance.

**Comment by tsattler** [comment]
The problem is that Colmap cannot find a GPU that is able to run CUDA. CUDA is required for the dense part of the reconstruction process, i.e., you need an NVidia GPU to generate dense point clouds. The sparse reconstruction part does not require CUDA.

**Comment by zalakb14** [comment]
Okay. I got it now. Thanks a lot for your response :)

**Comment by tsattler** [comment]
@zalakb14 Does this resolve your issue?

**Comment by zalakb14** [comment]
yes, I have started using colmap without cuda and it's working. Thanks a lot for your response so I could understand the reason behind getting errors.
