### ISSUE TITLE
Strange behavior in `manual specification of source images during dense reconstruction`

### ISSUE THREAD

**Issue by DaniilSNikulin** [colmap/colmap#1034]
If specify `__all__` in `patch_match.cfg`, then not all images will be as source, but only subset of reference images.

https://github.com/colmap/colmap/blob/c4714b2c6856d0e2afd3a993ff224f2f00634ebc/src/mvs/patch_match.cc#L314-L321

Is this ok? I can provide PR for code changes.

**Comment by ahojnnes** [comment]
A PR with the fix would be great. Thanks.
