### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_30' with Manjaro Linux

### ISSUE THREAD

**Issue by thilo-adk** [colmap/colmap#1035]
I am trying to compile colmap-git 3.6.r28.g94badd0-1 from the Archlinux AUR with CUDA support. Unfortunately this fails with the message

`nvcc fatal : Unsupported gpu architecture 'compute_30'.`

missing. If I disable CUDA in PKGBUILD, then colmap can be compiled. 

- OS: Manjaro Linux 20.1.2
- Kernel: 5.8.16-2-MANJARO

nvcc --version:
`nvcc: NVIDIA (R) Cuda compiler driver`
`Copyright (c) 2005-2020 NVIDIA Corporation`
`Built on Wed_Jul_22_19:09:09_PDT_2020`
`Cuda compilation tools, release 11.0, V11.0.221`
`Build cuda_11.0_bu.TC445_37.28845127_0`

nvidia-smi:
`Fri Oct 30 22:30:00 2020       `
`+-----------------------------------------------------------------------------+`
`| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |`
`|-------------------------------+----------------------+----------------------+`
`| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |`
`| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |`
`|                               |                      |               MIG M. |`
`|===============================+======================+======================|`
`|   0  GeForce GTX 760     Off  | 00000000:01:00.0 N/A |                  N/A |`
`| 20%   34C    P8    N/A /  N/A |    597MiB /  1991MiB |     N/A      Default |`
`|                               |                      |                  N/A |`
`+-------------------------------+----------------------+----------------------+`
`                                                                                `
`+-----------------------------------------------------------------------------+`
`| Processes:                                                                  |`
`|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |`
`|        ID   ID                                                   Usage      |`
`|=============================================================================|`
`|  No running processes found                                                 |`
`+-----------------------------------------------------------------------------+`

**Comment by Killfrra** [comment]
Try using CUDA version 10. You have an ancient video card. Just like mine

**Comment by thilo-adk** [comment]
> Try using CUDA version 10. You have an ancient video card. Just like mine

Thanks.

**Comment by hasanzfdn** [comment]
> > Try using CUDA version 10. You have an ancient video card. Just like mine
> 
> Thanks.
did it work??

**Comment by thilo-adk** [comment]
> > > Try using CUDA version 10. You have an ancient video card. Just like mine
> > 
> > 
> > Thanks.
> > did it work??

Hello. Sorry for the late reply. Yes, it work.
