### ISSUE TITLE
Compiling instructions for linux and custom GCC version

### ISSUE THREAD

**Issue by dasaki** [colmap/colmap#1043]
The following command (described in https://colmap.github.io/install.html#installation) to compile colmap doesn't work in my Ubuntu 20.04:

`CC=/usr/bin/gcc-6 CXX=/usr/bin/g++-6 cmake ..`

instead I used:

`cmake -DCMAKE_C_COMPILER=$(which gcc-8) -DCMAKE_CXX_COMPILER=$(which g++-8) ..`

**Comment by ahojnnes** [comment]
I updated the documentation and removed this comment.
