### ISSUE TITLE
Multi camera shooting problem

### ISSUE THREAD

**Issue by qingjiuling** [colmap/colmap#1048]
How to deal with pictures taken by different cameras when using multiple cameras? Put it directly under the same folder?

**Comment by tsattler** [comment]
If you put all images taken by the same camera into the same subfolder, you can easily get Colmap to use the same intrinsics for all images in the same subfolder.

**Comment by qingjiuling** [comment]
If I take an object from different directions with different cameras, can the photos taken by different cameras be put in the same folder

**Comment by tsattler** [comment]
Yes, you can put all images into the same folder.

**Comment by qingjiuling** [comment]
Thanks
