### ISSUE TITLE
an illegal memory access was encountered

### ISSUE THREAD

**Issue by mingliangfu** [colmap/colmap#1049]
Environment: Ubuntu 18.04 + CUDA 10.1 + colmap 3.6-dev.3(build from source)

(base) xxx@PC:~/workspace/colmap/build$ colmap patch_match_stereo \
> --workspace_path ~/workspace/colmap/test_dir/dense \
> --workspace_format COLMAP \
> --PatchMatchStereo.geom_consistency true \
> --PatchMatchStereo.gpu_index 0
Reading workspace...
Reading configuration...
Configuration has 30 problems...

==============================================================================
Processing view 1 / 30
==============================================================================

Reading inputs...

PatchMatch::Problem
-------------------
ref_image_idx: 18
src_image_idxs: 15 19 22 6 4 14 5 27 23 2 25 3 20 1 24 12 29 11 21 0

PatchMatchOptions
-----------------
max_image_size: -1
gpu_index: 0
depth_min: 5.05746
depth_max: 13.6081
window_radius: 5
window_step: 1
sigma_spatial: 5
sigma_color: 0.2
num_samples: 15
ncc_sigma: 0.6
min_triangulation_angle: 1
incident_angle_sigma: 0.9
num_iterations: 5
geom_consistency: 0
geom_consistency_regularizer: 0.3
geom_consistency_max_cost: 3
filter: 0
filter_min_ncc: 0.1
filter_min_triangulation_angle: 3
filter_min_num_consistent: 2
filter_geom_consistency_max_cost: 1
write_consistency_graph: 0

PatchMatch::Run
---------------
Initialization: 0.1785s
 Sweep 1: 0.5783s
CUDA error at /home/xxx/workspace/colmap/src/mvs/gpu_mat.h:348 - an illegal memory access was encountered
This error is likely caused by the graphics card timeout detection mechanism of your operating system. Please refer to the FAQ in      the documentation on how to solve this problem.

**Comment by tsattler** [comment]
Did you try what is suggested in the FAQ?

**Comment by mingliangfu** [comment]
> Did you try what is suggested in the FAQ?

Thanks for your fast reply.  Listed tricks such as fixing GPU freezes and timeouts and reducing memory in FAQ have been tested, but I got the same logs. BTW, my machine has a RTX 2080 Ti  GPU with 11GB, which is sufficient for dense reconstruction from a small set of images.

**Comment by mingliangfu** [comment]
Similar issue has been opened in [#1020](https://github.com/colmap/colmap/issues/1020) and [#980](https://github.com/colmap/colmap/issues/980).

**Comment by mingliangfu** [comment]
Upgrading CUDA version is all my need. Just replace cuda 10.1 with 10.2, everything is ok.

**Comment by reutazaria** [comment]
I have just upgraded CUDA to 11.2 and I'm still facing the same problem. Should I downgrade?

**Comment by mingliangfu** [comment]
> I have just upgraded CUDA to 11.2 and I'm still facing the same problem. Should I downgrade?

Check the FAQ first as @tsattler suggested.
