### ISSUE TITLE
Tests failure 

### ISSUE THREAD

**Issue by alexsmartens** [colmap/colmap#105]
I have the following tests failure after building Colmap on Ubuntu 16.04:
base/feature_matching_test  &  optim/bundle_adjustment_test 

```
97% tests passed, 2 tests failed out of 60

Total Test time (real) =  19.12 sec

The following tests FAILED:
	 11 - base/feature_matching_test (Failed)
	 43 - optim/bundle_adjustment_test (Failed)
Errors while running CTest
Makefile:105: recipe for target 'test' failed
make: *** [test] Error 8
```

What can be done to fix it?

**Comment by ahojnnes** [comment]
Can you check if defining ``EIGEN_DONT_ALIGN_STATICALLY`` and ``EIGEN_DONT_ALIGN`` in COLMAP solves the problem? (You can add a ``add_definitions("-DEIGEN_DONT_ALIGN_STATICALLY -DEIGEN_DONT_ALIGN")`` near the top of the ``CMakeLists.txt`` file in the top folder of COLMAP). Then recompile and see if the tests still fail. That would be very helpful. Thanks!

**Comment by alexsmartens** [comment]
Getting better, the changes helped with the optim/bundle_adjustment_test (#43)

```
98% tests passed, 1 tests failed out of 60

Total Test time (real) =  20.98 sec

The following tests FAILED:
	 11 - base/feature_matching_test (Failed)
Errors while running CTest
Makefile:105: recipe for target 'test' failed
make: *** [test] Error 8
```

**Comment by ahojnnes** [comment]
The feature_matching_test should be fixed now. The bundle_adjustment_test fails only under Ubuntu 16.04 which has a beta version of Eigen in its repositories. It can be solved by upgrading to the latest stable Eigen version. Thanks!
