### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_86' CMake Error at pba_generated_ProgramCU.cu.o.Release.cmake:219 (message):   Error generating

### ISSUE THREAD

**Issue by Aiteee** [colmap/colmap#1055]
I am trying to compile colmap with CUDA support. Unfortunately this fails with the message
nvcc fatal   : Unsupported gpu architecture 'compute_86' 
CMake Error at pba_generated_ProgramCU.cu.o.Release.cmake:219 (message):   Error generating

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Thu_Jun_11_22:26:38_PDT_2020
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0

 nvidia-smi
Sun Nov 15 13:49:06 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.38       Driver Version: 455.38       CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3090    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   54C    P8    36W / 350W |    102MiB / 24265MiB |      8%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 3090    Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   41C    P8    18W / 350W |      1MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1243      G   /usr/lib/xorg/Xorg                100MiB |
|    1   N/A  N/A      1243      G   /usr/lib/xorg/Xorg                  0MiB |
+-----------------------------------------------------------------------------+

**Comment by ahojnnes** [comment]
Thanks, should be fixed with latest commit in the dev branch.

**Comment by HuangBugWei** [comment]
@Aiteee 
Excuse me, could you tell me your OS version?
I have difficulty to build colmap and the error point that is related to CUDA.
However my OS is Ubuntu 22.04 and only support CUDA 11.7.
Wondering is OS/CUDA version problem or is not support 3090 card (and I found that it does work for you so error might not related to GPU.)

**Comment by kartikeyporwal** [comment]
@HuangBugWei Try with CUDA 11.7 and Ubuntu 20.04. There is docker image `nvidia/cuda:11.7.0-devel-ubuntu20.04`. This worked in my case but Ubuntu 22.04.

**Comment by kartikeyporwal** [comment]
@HuangBugWei Try with CUDA 11.7 and Ubuntu 20.04. There is docker image `nvidia/cuda:11.7.0-devel-ubuntu20.04`. This worked in my case but Ubuntu 22.04.
