### ISSUE TITLE
New citation for COLMAP software is necessary

### ISSUE THREAD

**Issue by chuong** [colmap/colmap#1056]
**Describe the bug**
Current way of citation requires references to 3 papers. These academic citations are inconvenient when we just want to refer to this software without going to the detail of the implementations.

**Expected behavior**
A single citation is needed to cite COLMAP software to allows a consistent way to cite the software for usage purpose and to keep track of it.  For example:

```
@Misc{COLMAP,
  Title                    = {{COLMAP: a general-purpose Structure-from-Motion (SfM) and Multi-View Stereo (MVS) pipeline}},
  Author                   = {Sch\"{o}nberger, Johannes Lutz and contributors},
  Year                     = {2020},
  License                  = {BSD},
  Copyright                = {{ETH Zurich and UNC Chapel Hill}}
  url                      = {https://github.com/colmap}
}
```
The original citations to the 3 papers can be kept for research purpose.

**Additional context**
As the software becomes more commonly used as a practical tool, a single non-academic citation is needed.

**Comment by ahojnnes** [comment]
Thank you for your proposal. I would like to continue referring people to the actual scientific papers underlying COLMAP instead of a generic citation to a website.
