### ISSUE TITLE
Shared intrinsic over sequential data

### ISSUE THREAD

**Issue by koz7** [colmap/colmap#1059]
Thank you for your great project.
I am trying to reconstruct a scene from sequential images captured by a camera.
The intrinsic parameter is roughly known, but not reliable.
I want to estimate the intrinsic parameter as shared over the sequence.
Especially, I need the principal point to be refined accurately (your tutorial says it is not refined in the default setting).
Your tutorial kindly provides information so as to using GUI, but I need to use CUI instead.

So, what I want to do is:
1) Initialize the intrinsic manually
2) Load a sequence of images captured by the single camera
3) Reconstruct the scene and the extrinsics, and simultaneously estimate the shared intrinsic (except for principal point)
4) Refine the whole parameters including principal point by final global bundle adjustment.
5) Output the reconstructed points, the extrinsics, and the single intrinsic (refined by global BA)

Is this procedure correct in geometric sense?
If so, how can I manipulate it from CUI command line?

Thank you in advance for your support.

**Comment by tsattler** [comment]
For 1 and 2: when you call the feature_extractor on the command line, you can specify the type of camera model to be used, set initial parameters, and specify whether all cameras should use the same intrinsics or not.

For 3: per default, Colmap will optimize the extrinsics and intrinsics (except the principal point). You can also use a flag of the mapper to optimize the principal point, but this might get unstable.

For 4 and 5: the bundle_adjuster has a flag that can be used to refine the principal point and it will write out the refined model to a file.

If you have access to the camera with which the sequences were captured, you would probably get better results calibrating it beforehand, e.g., using one of the freely available calibration toolboxes out there.

**Comment by koz7** [comment]
Thank you very much @tsattler for your kind reply.
Your advice is of great help for me!
I will try it again in reference of your suggestion:)
