### ISSUE TITLE
Question about the unit of the Strecha benchmark reported in the 2016mvs paper

### ISSUE THREAD

**Issue by jianweike** [colmap/colmap#1060]
I am not sure if here is the right place to ask this question. 

In the 2016mvs paper, the ratio of pixels with an error less than 2 cm and 10 cm on the Strecha benchmark were reported. I was wondering how you figured out the specific unit "cm". After the depthmap is estimated by PatchMatch, what should be the specific threshold for the depth difference (between the estimate and the ground true) that maps to 2cm (is it 0.02?) and where to find that information? 

Thank you in advance. 

-JianweiKe

**Comment by ahojnnes** [comment]
The stretcha benchmark comes with ground truth camera poses. We used these poses as input for MVS. In this case, the depths are scaled to meters.

**Comment by yinghuasha** [comment]
I used the Release Version provided on the website https://demuc.de/colmap/#download to run MVS. But with all default parameters of MVS , I cannot get the precision reported in the paper using the strecha benchmark. How should I set the right parameters?
