### ISSUE TITLE
Unable to perform dense stereo matching in Colmap

### ISSUE THREAD

**Issue by zalakb14** [colmap/colmap#1061]
Hi,

Is that mandatory to have Nvidia graphics card & cuda in your system to perform dense reconstruction in Colmap? 
As my system doesn't have Nvidia graphics card & so I get error while running dense reconstrution.
Please let me know if there is any possibility to perform dense reconstruction without cuda.

**Comment by tsattler** [comment]
The dense reconstruction approach implemented in Colmap requires Cuda.
You could try out PMVS / CMVS, see for example https://github.com/pmoulon/CMVS-PMVS, which is another approach to dense reconstruction that only uses the CPU. Colmap can export files into the format of PMVS / CMVS. Please see the Colmap documentation for details.

**Comment by zalakb14** [comment]
Thanks a lot for your suggestion. I tried working on PMVS/CMVS. 
I have exported undistorted output from Colmap & tried to run CMVS but I got error "Bundle file not found".
However, I am getting the results when I run PMVS.

**Comment by ahojnnes** [comment]
Did you have a look at the pre generated PMVS/CMVS shell scripts in the output folder of the undistortion step?

**Comment by zalakb14** [comment]
Yes, I had checked it but still I had missed a '/' in my command. Thanks for your comment so I rechecked those scripts and corrected my mistakes. 
It's working for me now, thanks everyone for your support.
