### ISSUE TITLE
Sequential matcher with non-uniform filenames

### ISSUE THREAD

**Issue by koz7** [colmap/colmap#1063]
Hi, thank you always for your help.
I need to reconstruct a scene from a sequence of images.
A single camera recorded a scene in sequence, but the filenames are not well arranged:
like [0001, 0003, 0005, 0009, 0010, 0013, 0016, 0017, 0020, ...]
not like [0001, 0002, 0003, 0004, ...]

Since two or three images with neighboring filenames overlap well, it seems better to use the "sequential_matcher".
There, I am not sure whether "sequential_matcher" will match an image e.g. "0010" to "0009" or "0013", even if they are not sequential rigorously.
So, my question is: should I rename the files of sequential images as they are numbered stepped by one like [0001, 0002, 0003, ...] or does the algorithm automatically find the most nearest numbered files?

Thank you in advance.

**Comment by ahojnnes** [comment]
The image names will be alphabetically sorted and then matched sequentially in this order. The matcher does not care about missing images in the sequences. In your case, [0001, 0003, 0005, 0009, 0010, 0013, 0016, 0017, 0020, ...] should work fine.

**Comment by koz7** [comment]
@ahojnnes
Thank you for your kind reply. I got it!
It is really a great functionality and helpful for me! :)
