### ISSUE TITLE
some questions about this software

### ISSUE THREAD

**Issue by HeadReaper-hc** [colmap/colmap#1064]
Hi
    Great work!
    I have some questions about reconstructing video image.
    1. except radtan distortion model, any other distortion model support?
    2. Can I manually provide intrinscis and distortion coefficients and not optimize them in the program?

**Comment by tsattler** [comment]
1. yes. You can find a description of the camera models supported by colmap (and a pointer to the code providing details) here: https://colmap.github.io/cameras.html
2. yes, this can be done through flags on the command line and options in the gui.

**Comment by HeadReaper-hc** [comment]
@tsattler That's really helpful, thank you very much.
