### ISSUE TITLE
use colmap as a library problem

### ISSUE THREAD

**Issue by qingjiuling** [colmap/colmap#1065]
Hello, thank you very much for your great work.I've used colmap directly on GUI and command line, and all ther have achieved good results.
But when I followed [(https://colmap.github.io/install.html#library)],I met the problem ,I have been looking for a long time and haven't found a suitable method. Where is the problem?(my CMakeLists.txt and hello_world.cc just the same as the [(https://colmap.github.io/install.html#library)])
Here is the error log.

```
(base) magus@magus:~/zxp_workspace/test2/build$ make
Scanning dependencies of target hello_world
[ 50%] Building CXX object CMakeFiles/hello_world.dir/hello_world.cc.o
[100%] Linking CXX executable hello_world
/usr/local/share/colmap/../../lib/colmap/libcolmap.a(matching.cc.o)：in function‘colmap::SiftFeatureMatcher::SiftFeatureMatcher(colmap::SiftMatchingOptions const&, colmap::Database*, colmap::FeatureMatcherCache*)’：
matching.cc:(.text+0x4d11)：‘colmap::GetNumCudaDevices()’Undefined reference
collect2: error: ld returned 1 exit status
CMakeFiles/hello_world.dir/build.make:136: recipe for target 'hello_world' failed
make[2]: *** [hello_world] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/hello_world.dir/all' failed
make[1]: *** [CMakeFiles/hello_world.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by qingjiuling** [comment]
The getnumcudadevices() function mentioned in the error message has been found in the source code. The two files involved are colmap/src/feature/matching.cc And colmap/src/util/cuda.cc 。It seems to be an internal problem. How can I solve this problem when colmap is alerady installed (and works correctly)?

**Comment by ClementPinard** [comment]
Hi,

got the same error.
suggested Hot fix : you can see that in the folder "/usr/local/lib/colmap" you have `libcolmap.a` but also `libcolmap_cuda.a`
The key is then to add `colmap_cuda`to your libraries in the CMakeLists.txt :

change last line 
```
target_link_libraries(hello_world ${COLMAP_LIBRARIES})
```

to 
```
target_link_libraries(hello_world ${COLMAP_LIBRARIES} colmap_cuda)
```

The right fix should probably to add this library to the `COLMAP_LIBRARIES` variable. See the incriminated source file : https://github.com/colmap/colmap/blob/ec6c2aa8637743cba35924a74d9657bb13b5f69c/cmake/CMakeConfig.cmake.in#L190-L194
