### ISSUE TITLE
colmap cmake error "CUDA LIMIT_GPU ARCHITECTURE" "AND" "ITEM" "VERSION_GREATER_EQUAL" "CUDA_LIMIT_GPU ARCHITECTURE"

### ISSUE THREAD

**Issue by Abraham423** [colmap/colmap#1066]
**Describe the bug**
I pulled down the latest version, and built with cmake,  but It doesn't work with the following error:

(base) root@30fb1150341b:/home/njfh/wh/colmap/build# cmake ..
-- Found required Ceres dependency: Eigen version 3.3.90 in /usr/local/include/eigen3
-- Found required Ceres dependency: glog
-- Found Ceres version: 2.0.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, Suise, CXSparse, SchurSpecializations, Multithreading]
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   graph
--   system
--   unit_test_framework
-- Found Eigen
--   Includes : /usr/local/include/eigen3
-- Found FreeImage
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
-- Found Glog
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
-- Found Glew
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
-- Found Qt
--   Module : /root/anaconda3/lib/cmake/Qt5Core
--   Module : /root/anaconda3/lib/cmake/Qt5OpenGL
--   Module : /root/anaconda3/lib/cmake/Qt5Widgets
-- Found CGAL
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libCGAL.so.11.0.1
-- Build type not specified, using Release
-- Enabling SIMD support
-- Enabling OpenMP support
-- Disabling interprocedural optimization
CMake Error at cmake/SelectCudaComputeArch.cmake:199 (if):
  if given arguments:

    "CUDA_LIMIT_GPU_ARCHITECTURE" "AND" "ITEM" "VERSION_GREATER_EQUAL" "CUDA_LIMIT_GPU_ARCHITECTURE"

  Unknown arguments specified
Call Stack (most recent call first):
  cmake/SelectCudaComputeArch.cmake:231 (CUDA_DETECT_INSTALLED_GPUS)
  CMakeLists.txt:198 (CUDA_SELECT_NVCC_ARCH_FLAGS)

I'm on Ubuntu16.4;
cmake version 3.5.1;
cuda version 10.1;
And ceres-solver-2.0.0 has been successfully installed;

It seems there's something wrong with cmake and cuda, but got no idea how to fix that problem, can anyone help me , thanks in advance ~

**Comment by Guocode** [comment]
the same problem

**Comment by Guocode** [comment]
on ubuntu 18.06,tesla v100*8, cuda 10.2,driver version 440.95.01

**Comment by ahojnnes** [comment]
Fixed, thanks.
