### ISSUE TITLE
No good initial image pair

### ISSUE THREAD

**Issue by koz7** [colmap/colmap#1072]
Thank you always for your help. Forgive me to disturb many times.

I am trying to reconstruct a video scene taken with a camera.
I follow the procedure:
(1) Create a new database.db and select image folder
(2) Feature extraction as using the OPENCV model and initialize values with some reasonable ones. They are not so apart from the truth we expect.
(3) Feature matching as using sequential
(4) Then set the Bundle option as refine all the camera parameters (focal length, principal point, extra params)
The COLMAP says
"Finding good initial image pair" but
"No good initial image pair found"
many times.

We relaxed the initial parameter "init_min_tri_angle" to 2, 4, 8 deg. for example, but they do not solve the message.
Is there any suggestion what parameters we should relax?

Thank you in advance.

**Comment by koz7** [comment]
We resolved the issue by setting another parameter!
Thank you.

**Comment by A1ecm** [comment]
> We resolved the issue by setting another parameter!
> Thank you.

Mind telling what parameter you changed to make it work? Having some issues as well
