### ISSUE TITLE
some output types of model_converter not working

### ISSUE THREAD

**Issue by reallingchen** [colmap/colmap#1073]
Hi there,

When working in the CLI, I tried command like this:

colmap model_converter \
--input_path ./sparseModel \
--output_path ./convertedModel \
--output_type PLY

But looks like my machine can only support BIN and TXT output types.

1. When choose NVM, the CLI shows:
F1202 16:31:33.787714 415366656 reconstruction.cc:882] Check failed: file.is_open() ./convertedModel
*** Check failure stack trace: ***
    @        0x10e07e953  google::LogMessage::Flush()
    @        0x10e081d21  google::LogMessageFatal::~LogMessageFatal()
    @        0x10e07f275  google::LogMessageFatal::~LogMessageFatal()
    @        0x10cdff028  colmap::Reconstruction::ExportNVM()
    @        0x10cd27743  RunModelConverter()
    @        0x10cd3928d  main
zsh: abort      colmap model_converter --input_path ./sparseModel --output_path  --output_typ

2. When choose Bundler or VRML, looks like nothing happens.

3. When choose PLY, the CLI shows:
F1202 16:34:43.645809 58154496 ply.cc:334] Check failed: text_file.is_open() ./convertedModel
*** Check failure stack trace: ***
    @        0x103528953  google::LogMessage::Flush()
    @        0x10352bd21  google::LogMessageFatal::~LogMessageFatal()
    @        0x103529275  google::LogMessageFatal::~LogMessageFatal()
    @        0x102d9a6ee  colmap::WriteBinaryPlyPoints()
    @        0x102ac0dcf  colmap::Reconstruction::ExportPLY()
    @        0x1029e77bb  RunModelConverter()
    @        0x1029f928d  main

The machine I'm using is a MacBook Pro (MacOS Big Sur).

In fact what I really intend to do is viewing the sparse model in COLMAP GUI. Pls also advise how to achieve this goal. Currently I can only create BIN and TXT files. Is there a way to visualize image poses and 3D points in COLMAP GUI?

Thanks a lot for the helps.

**Comment by tsattler** [comment]
For both NVM and PLY, you get the same error `Check failed: file.is_open() ./convertedModel`. I assume that `convertedModel` is a directory. In the case of NVM and PLY, Colmap expects the file name of the output file as input. Since you pass a directory name instead of a file name, Colmap cannot open the file for writing, resulting in the error messages from above.

**Comment by reallingchen** [comment]
Hi tsattler,

Thanks for the quick responses.

Yes 'convertedModel' in my earlier comment is just output folder name. Per your clarification, I tried to add a file name after it, as below:

colmap model_converter \
--input_path ./sparseModel \
--output_path ./convertedModel/sparseModel.ply \
--output_type PLY

Indeed this time the PLY file is created. So is it correct that all info is embedded into one PLY file? I am not sure if the created file is correct as its size is much much smaller comparing to files in BIN format.

BTW, can I use COLMAP GUI to visualize the content of images.bin/txt and pionts3D.bin/txt. This is exactly what I need. I tried the matlab script provided by COLMAP for visualization purposes, the overall experience of inspecting the data in MATLAB is not so pleasant.

Thank you.

**Comment by reallingchen** [comment]
Pls ignore my earlier comment on how to visualize the content of the created sparse model in COLMAP. I figured out how to do it per COLMAP's documentation in section 'Output format -> Sparse Reconstruction'.

**Comment by tsattler** [comment]
The PLY file only stores the 3D points but not any of the camera information.

**Comment by reallingchen** [comment]
Thanks, appreciated.
