### ISSUE TITLE
Pause/resume for dense reconstruction fusion

### ISSUE THREAD

**Issue by fb82** [colmap/colmap#1076]
Hi,
I'm just wondering if there is some way to pause/resume the dense reconstruction fusion process...

Thanks!

**Comment by ahojnnes** [comment]
You can just cancel and continue during the patch match stereo step. It will just continue from where you cancelled. There is no option to pause the fusion.

**Comment by fb82** [comment]
Ok, thanks!

**Comment by ClaudioCimarelli** [comment]
> You can just cancel and continue during the patch match stereo step. It will just continue from where you cancelled. There is no option to pause the fusion.

Dear @ahojnnes, I had to rerun a patch match stereo step, and I noticed that each time it started by cleaning the depth_maps folder instead of continuing from the last point or maybe creating just the missing depths. Is it possible to do otherwise?
Thank you.
