### ISSUE TITLE
feature extraction, matching and reconstruction in only one thread

### ISSUE THREAD

**Issue by json87** [colmap/colmap#108]
hi, thanks for providing the excellent SfM toolkit. Recently, I have utilized it to process some images. However, after each step, I must wait tens of minutes to move to the next step, especially for feature extraction and matching. Therefore, I think if I could pack the three operations into one thread to simplify the procedure. 

wait for your reply!

**Comment by ahojnnes** [comment]
I am currently working on a end-to-end reconstruction tool. Thanks for the feedback!

**Comment by xiaofeiwu** [comment]
It seems to me that a simple way to do this is a shell script.

**Comment by ahojnnes** [comment]
I implemented an "automatic reconstruction" tool. It is still experimental but you can find some info about it here: https://colmap.github.io/tutorial.html#quickstart

**Comment by json87** [comment]
thanks very much! I will have a test.

**Comment by ahojnnes** [comment]
Closing this as resolved. Thanks for the feedback!
