### ISSUE TITLE
StereoFusion Performance / resource utilisation

### ISSUE THREAD

**Issue by robin-gdwl** [colmap/colmap#1083]
I am currently running an automatic reconstruction on around 350 images using the GUI on a windows machine. 
During most of the process (sparse reconstruction, patch match) my system was running at max capacity either on CPU or GPU while the used memory was often above 80%.

Now the StereoFusion process is running and the resources of the system dont seem to be utilised at all (see attached image): 
**CPU usage by COLMAP is aroung 10%** (on a 6-Core Processor)
Overall CPU usage (entire system) stays between 10 and 25%
**GPU stays below 2%** 
**Memory** stays between **60 to 80%** (32 GB Ram available)

Is this process a single core-operation or in other ways restriceted in performance? 
Is there a way to let COLMAP use more of the available resources or am I missing something? 
I would love to better understand what the performance bottlenecks in COLMAP might be. 

![image](https://user-images.githubusercontent.com/25942644/103359855-f3397900-4ab8-11eb-83d8-5163cb628f79.png)

Thank you very much for providing such an excellent tool for photogrammetry as well as detailed documentation. I hope I did not miss an obvious answer to my question. I have been searching the docs and Github issues, but did not find any information related to it.

**Comment by ahojnnes** [comment]
The current implementation is single threaded. It’s not trivial to turn this into a multi threaded implementation, as the fused poking cloud is a single global state.

**Comment by robin-gdwl** [comment]
Thank you for your answer. 
closing
