### ISSUE TITLE
No .ply file?

### ISSUE THREAD

**Issue by DillFrescott** [colmap/colmap#1087]
**Describe the bug**
When I select dense model using the no cuda windows version, and automatically process the sample hall dataset, I get no .ply file in the output folder. Just two .sh files. I watched tutorials and followed what they did step by step using the same images and I am not getting the .ply files under dense --> 0 folders. Am I doing something incorrectly?

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit
 - Browser Firefox
 - Version: 3.6

**Comment by Ggs1mida** [comment]
hi @DillFrescott  i met the same problem, how did you solve it?

**Comment by DillFrescott** [comment]
@Ggs1mida I don't remember sorry. If anything, I think I didn't figure it out.

**Comment by taperlaptop** [comment]
Same problem but no solutions.

**Comment by TTDmon** [comment]
I find where the problem lies. I used the cuda version and i got the ply files under the same folder!
