### ISSUE TITLE
Reconstruction seems to give different results with the same data and parameters

### ISSUE THREAD

**Issue by xiaofeiwu** [colmap/colmap#109]
I run colmap for the same dataset and configuration parameters, but the results seems to be different. Would this be possible that this is because one is run with colmap windows binary (with GPU), and another is run under ubuntu compiled version (without GPU)?

**Comment by ahojnnes** [comment]
This is due to randomized algorithms, such as RANSAC. If you want to avoid this behavior, you could manually recompile COLMAP and set the random seed at the beginning of the main function using `SetPRNGSeed`.
