### ISSUE TITLE
Different behavior between bundle adjustment run from GUI and from CLI

### ISSUE THREAD

**Issue by kondela** [colmap/colmap#1094]
**Describe the bug**
When I run bundle adjustment using CLI on a model I get different result when the same bundle adjustment is run from GUI. 

Although log is very similar/same in both cases, it appears that camera poses are adjusted only when GUI is used. This is verified both by comparing `images.bin`/`images.txt` files and using GUI's rendering window. 

**To Reproduce**
1. Download this [sample scene](https://we.tl/t-C69B3SiXcJ) and upack the zip file for demo purposes. 
2. Open COLMAP GUI and import the model (File -> Import model -> find `sample_scene/model`)
3. Click "No" on COLMAP pop-up "Directory does not contain project.ini..."
4. Verify that the model was loaded correctly, you should see something like this:
![image (9)](https://user-images.githubusercontent.com/34348494/104181512-3841a180-540f-11eb-8cea-e5b83a34312f.png)
5. Click on Bundle adjustment, add checkmark to `refine_principal_point`, and click on run
6. Verify that bundle adjustment was ran and that camera poses were adjusted, you should see them change in rendering window:
![image (10)](https://user-images.githubusercontent.com/34348494/104181911-e0576a80-540f-11eb-9e9a-506e78b1c722.png)
7. Redo step 6 multiple times (usually 1-2x is enough) until camera poses are not changing.
8. Create `gui_model` folder and export model to it by clicking on File -> Export model and locating `gui_model`. Careful not to overwrite `sample_scene/model`. This newly exported model in `gui_model` folder serves as a "GUI model" that will be compared with "CLI model". 
9. Create `cli_model` folder.
10. Run bundle adjustment from CLI by running
```
colmap bundle_adjuster --input_path path/to/sample_scene/model --output_path path/to/cli_model --BundleAdjustment.refine_principal_point 1
```
11. Redo step 10 multiple times, ideally same amount of times as in step 7. However, you need change `--input_path` from `sample_scene/model`to your `path/to/cli_model`, as seen below
```
colmap bundle_adjuster --input_path path/to/cli_model --output_path path/to/cli_model --BundleAdjustment.refine_principal_point 1
```
12. Now both GUI and CLI models should have roughly the same poses and running bundle adjustment from GUI on CLI model should have no effect.
13. Open COLMAP GUI as in step 2 and import CLI model (File -> Import model -> find `path/to/cli_model`
14. Just as in step 3. Click "No" on COLMAP pop-up "Directory does not contain project.ini..."
15. Once again, verify that your CLI model was loaded correctly, you should see something like this
![image (11)](https://user-images.githubusercontent.com/34348494/104185340-1ea35880-5415-11eb-9e92-fc1b7ae7e5e2.png)
16. Now, in theory running bundle adjustment on this model should have no effect. Do the same process as in step 5, i.e click on Bundle adjustment, add checkmark to `refine_principal_point`, and click on run.
17. You can see that camera poses got adjusted even though we run bundle adjustment using CLI in step 11 multiple times. 
![image (12)](https://user-images.githubusercontent.com/34348494/104185558-7215a680-5415-11eb-82f2-2de7b2cd32a3.png)

Optionally, you can export this model (ideally as text), for example to a folder called 'cli_model_after_gui' save it and do:
```diff path/to/cli_model/images.txt cli_model_after_gui/images.txt```
This additionally confirms that poses indeed changed.

**Expected behavior**
Bundle adjustment run from GUI and CLI lead to same result.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: COLMAP 3.7 -- Structure-from-Motion and Multi-View Stereo (Commit 081272b on 2020-12-30 with CUDA)

**Additional information:**
I tried this on different scenes, i.e. this does not appear to be model specific. Both GUI and CLI logs show same convergence and final cost - GUI model convergence and final cost can be seen in screenshot as step 6, I am adding bundle adjustment report after step 11 (i.e. running CLI bundle adjustment on CLI model multiple times) here:
```
Bundle adjustment report
------------------------
    Residuals : 278884
   Parameters : 177849
   Iterations : 2
         Time : 0.946735 [s]
 Initial cost : 0.974031 [px]
   Final cost : 0.974031 [px]
  Termination : Convergence

Elapsed time: 0.020 [minutes]
```

**Comment by kondela** [comment]
After digging a bit in the code I noticed that GUI bundle adjustment normalizes the scene every time it is run.
https://github.com/colmap/colmap/blob/ff9a463067a2656d1f59d12109fe2931e29e3ca0/src/ui/bundle_adjustment_widget.cc#L100

I don't see any kind of normalization in CLI bundle adjustment:
https://github.com/colmap/colmap/blob/ff9a463067a2656d1f59d12109fe2931e29e3ca0/src/exe/colmap.cc#L199-L204

Adding  `reconstruction.Normalize();` after reading the model in CLI seemed to fix the issue although there is still some minor camera poses adjustment when GUI is used afterwards.

I will leave this open for now. @ahojnnes can you confirm that this might be the cause? If so I can shoot a PR your way.

**Comment by ahojnnes** [comment]
Yes, from your description, this appears to be the issue. Normalization has two purposes in COLMAP: (1) reduce numerical errors by keeping magnitudes of floating point values small, (2) ensure that the model fits into the field of view in the GUI viewer.

**Comment by kondela** [comment]
> Yes, from your description, this appears to be the issue. Normalization has two purposes in COLMAP: (1) reduce numerical errors by keeping magnitudes of floating point values small, (2) ensure that the model fits into the field of view in the GUI viewer. Since the absolute scale/orientation of reconstructions in SFM are up to an unknown 3D similarity, this is not an issue for most applications.

Thanks for such a quick reply. I assume that this is not a bug then but rather a lack of documentation. I will close this issue :).
