### ISSUE TITLE
Easiest way to extract covariance of camera poses and 3D points from COLMAP

### ISSUE THREAD

**Issue by lixx2938** [colmap/colmap#110]
Hi,

I am wondering if there is any easy and simple way to get covariance matrix (i.e. inverse Hessian) of camera poses and 3D points from SfM of COLMAP.

**Comment by ahojnnes** [comment]
This should be easily possible with ceres-solver by computing the covariance of the parameters, see http://ceres-solver.org/nnls_solving.html#covariance-estimation
