### ISSUE TITLE
SiftExtraction parameters command asking

### ISSUE THREAD

**Issue by HuangBugWei** [colmap/colmap#1105]
I saw that you recommend applying --SiftExtraction.estimate_affine_shape=true this option from your FAQ page. But when I applied this, GPU can't work any more. It seems only run on CPU and I just want to know why. 
Below are my command lines: 
colmap feature_extractor \
   --database_path $DATASET_PATH/database.db \
   --image_path $DATASET_PATH/../Input \
   --ImageReader.camera_model SIMPLE_RADIAL \
   --ImageReader.single_camera 1\
   --SiftExtraction.max_image_size 2400\
   --SiftExtraction.max_num_features 8192 \
   --SiftExtraction.first_octave -1 \
   --SiftExtraction.num_octave 4 \
   --SiftExtraction.octave_resolution 3 \
   --SiftExtraction.peak_threshold 0.00667 \
   --SiftExtraction.edge_threshold 10 \
   --SiftExtraction.estimate_affine_shape 0 \
   --SiftExtraction.max_num_orientations 2 \
   --SiftExtraction.upright 0 \
   --SiftExtraction.domain_size_pooling 1 \
   --SiftExtraction.dsp_min_scale 0.16667 \
   --SiftExtraction.dsp_max_scale 3 \
   --SiftExtraction.dsp_num_scales 10 \
   --SiftExtraction.num_threads -1 \
   --SiftExtraction.use_gpu 1 \
   --SiftExtraction.gpu_index -1 \

and when I set --SiftExtraction.estimate_affine_shape 1 \, then GPU won't work.
I just wanna knowing why.

**Comment by tsattler** [comment]
The GPU implementation of SIFT simply does not support estimating affine shapes. Thus, Colmap falls back to a CPU implementation of SIFT that supports this feature.

**Comment by HuangBugWei** [comment]
So GPU doesn't support this feature?
I just want to figure out is my command problem or something else like the feature need multiple GPU.

**Comment by tsattler** [comment]
The GPU implementation of SIFT used by Colmap does not support this feature.

**Comment by HuangBugWei** [comment]
OK, I see.
Thanks.
