### ISSUE TITLE
Cameras sizes unusually large in model viewer?

### ISSUE THREAD

**Issue by alexs7** [colmap/colmap#1107]
Hello!

I have reconstructed a model with ~1500 images and resulting point cloud 180k points.

It looks like this in the viewer:

<img width="756" alt="Screenshot 2021-02-03 at 21 18 59" src="https://user-images.githubusercontent.com/1533281/106797863-d8cd5f00-6665-11eb-90e3-90e855bfbc55.png">

Now as you can see, the frames/cameras sizes are extremely large. I am not sure why this happens ??

The scene is a street. The camera I am using is an ARCore device the frames are all 640 by 480.

My mapper parameters are these: 

```
[Mapper]
ignore_watermarks=0
multiple_models=0
extract_colors=1
ba_refine_focal_length=1
ba_refine_principal_point=1
ba_refine_extra_params=1
```

**Comment by ahojnnes** [comment]
You can change the camera size using ALT+SCROLL in the viewer. See here: http://colmap.github.io/gui.html#model-viewer-controls

**Comment by alexs7** [comment]
Oh great!  it Looks cool too! Thanks!
