### ISSUE TITLE
Using COLMAP for reconstruction at Scale with known camera intrinsics and per frame pose

### ISSUE THREAD

**Issue by chinmaychinara91** [colmap/colmap#1112]
Hi,

So I have a defined set of intrinsics and per frame transformation matrix of a KITTI monocular odometry data (which I decompose to qw, qx, qy, qz, tx, ty, tz). I created a database using these values and ran feature extraction, matching, and sparse reconstruction (making sure refine all camera parameters is unchecked in bundle adjustment). Yet after the reconstruction when I save the images.txt, file shows differerent qw, qx, qw, qz, tx, ty, tz even though the database still shows GT qw, qx, qw, qz, tx, ty, tz. 

Is there something that I am missing to understand or is this something related to default colmap scaling?

**Comment by tsattler** [comment]
Colmap does not use the poses stored in the database during the reconstruction process. This explains why your poses are different (as it reconstructs the scene from scratch).

If you have known poses and intrinsics that are accurate, you can follow this description for re-triangulating the scene from known poses: https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses

**Comment by chinmaychinara91** [comment]
Thanks that did clarify a lot of things !!!
