### ISSUE TITLE
Blending map

### ISSUE THREAD

**Issue by tmac1002** [colmap/colmap#112]
Hi, I used some UAV images to generate sparse point. However, the result map seemed blending. I am very confused. I just have no idea why this happened. Could you help me explain this situation or what exactly reasons caused this results. Thank you very much!
![blend_image](https://cloud.githubusercontent.com/assets/11924213/25466076/c09953ba-2b38-11e7-9469-f3ee65cf524b.JPG)

**Comment by ahojnnes** [comment]
I assume you do not have a calibration for your images? This problem is, for example, described in "Critical Configurations for Radial Distortion Self-Calibration" by Wu C.

You should be able to solve the problem by fixing the intrinsic parameters to values obtained from an offline calibration.
