### ISSUE TITLE
How to properly setup input for RigBundleAdjuster for scene with one camera?

### ISSUE THREAD

**Issue by kondela** [colmap/colmap#1120]
Hello, I am trying to use `rig_bundle_adjuster` for my scene which was captured using a rig consisting of three cameras, however, I need them to be registered as a single camera in COLMAP. (For more details on the scene you can check https://github.com/colmap/colmap/issues/1086). 

I came across https://github.com/colmap/colmap/issues/54, https://github.com/colmap/colmap/issues/891 and I also read the documentation [in colmap.cc](https://github.com/colmap/colmap/blob/ff9a463067a2656d1f59d12109fe2931e29e3ca0/src/exe/colmap.cc#L1623).

My `--input_path` points to a folder containing `cameras.txt,` `images.txt` and `points3D.txt` after sparse reconstruction. My `cameras.txt` contains a single entry (`1 SIMPLE_RADIAL 4256 4256 5107.2 2128 2128 0`) and my `images.txt` consists of 108 images - 36 images starting with `e020_xxx.png`, 36 images starting `e045_xxx.png` and 36 images starting `e075_xxx.png`, where `xxx` is a number. Each image is associated with `camera_id 1` (number right before image filename in `images.txt`).

Based on this I created a JSON file that `--rig_config_path` points to. This file looks following:

```json
[
  {
    "ref_camera_id": 1,
    "cameras":
    [
      {
          "camera_id": 1,
          "image_prefix": "e020_"
      },
      {
          "camera_id": 1,
          "image_prefix": "e045_"
      },
      {
          "camera_id": 1,
          "image_prefix": "e075_"
      }
    ]
  }
] 
```

However, when I run `colmap rig_bundle_adjuster` I'm getting following error:

```bash
F0214 16:45:36.439599 4008645 camera_rig.cc:71] Check failed: !HasCamera(camera_id) 
*** Check failure stack trace: ***
    @     0x7f5ce88d41c3  google::LogMessage::Fail()
    @     0x7f5ce88d925b  google::LogMessage::SendToLog()
    @     0x7f5ce88d3ebf  google::LogMessage::Flush()
    @     0x7f5ce88d46ef  google::LogMessageFatal::~LogMessageFatal()
    @     0x55b08b942515  colmap::CameraRig::AddCamera()
    @     0x55b08b8d0bdb  ReadCameraRigConfig()
    @     0x55b08b8d1afe  RunRigBundleAdjuster()
    @     0x55b08b8b66d2  main
    @     0x7f5ce68860b3  __libc_start_main
    @     0x55b08b8c07ae  _start
Aborted (core dumped)
```

I guess I must be doing something incorrectly. I also tried to manually create three equal cameras in `cameras.txt` with camera ids `1`, `2`, `3` and manually change `images.txt` so each image with different prefix has different camera id but I got the same error.

**Comment by kondela** [comment]
After a bit experimentation I came up with a messy solution that somewhat works. If you want all images to share same camera intrinsics but still want to use `rig_bundle_adjuster` you have to manually create three separate cameras in `cameras.txt`, each with different camera id, then manually rewrite `images.txt` to assign different camera ids based on your cameras in JSON config (one camera id equals one camera in rig). This on its own, however, will lead to different camera intrinsics after running `rig_bundle_adjuster`. If you want to keep intrinsics same you have to basically revert what you did to `cameras.txt` and `images.txt` in previous step and run another regular `bundle_adjuster` to find suitable intrinsics that will be shared by all images.

**Comment by shubham-monarch** [comment]
> After a bit experimentation I came up with a messy solution that somewhat works. If you want all images to share same camera intrinsics but still want to use `rig_bundle_adjuster` you have to manually create three separate cameras in `cameras.txt`, each with different camera id, then manually rewrite `images.txt` to assign different camera ids based on your cameras in JSON config (one camera id equals one camera in rig). This on its own, however, will lead to different camera intrinsics after running `rig_bundle_adjuster`. If you want to keep intrinsics same you have to basically revert what you did to `cameras.txt` and `images.txt` in previous step and run another regular `bundle_adjuster` to find suitable intrinsics that will be shared by all images.

You need to provide different `camera_ids` because otherwise it becomes impossible for colmap to figure out which image was captured by which particular camera.
