### ISSUE TITLE
Is it possible to get the odometry result from the reconstruction result of a sequence of images

### ISSUE THREAD

**Issue by xiaofeiwu** [colmap/colmap#113]
I reconstructed a 3D model for a sequence of images such as Kitti Mono. The reconstruction looks nice. However, when I tried to get the odometry of the cameras from the tvec of the images, it is totally wrong. Could anyone give me some hint why?

**Comment by ahojnnes** [comment]
tvec defines the translation from world to camera coordinate system. To obtain the camera trajectory you need to compute ``R^T * T`` while `R` is the 3x3 rotation matrix composed from the `qvec` and `T` is the `tvec`.
