### ISSUE TITLE
Does COLMAP use SIFTGPU only when the use_gpu flag is set to true ?

### ISSUE THREAD

**Issue by alexs7** [colmap/colmap#1149]
I am not sure in feature extraction when these flags are set:

```
[SiftExtraction]
use_gpu=true
gpu_index=0
```

Does that use SIFTGPU as opposed to a non-sift based implementation? Or it simple just returns the same result but from running it on a GPU ?

**Comment by revisionarian** [comment]
COLMAP can extract SIFT features either on the GPU or the CPU. If `use_gpu` is true, then feature extraction is done on the GPU using the SiftGPU library. If `use_gpu` is false, then the VLFeat library is used on the CPU.  The resulting SIFT features may differ between the two versions.

Some feature extraction options are not available in the GPU version (`domain_size_pooling` and `estimate_affine_shape`), so COLMAP falls back to the CPU version if they are enabled.

**Comment by alexs7** [comment]
@revisionarian Ok this helps a lot! Thanks!
