### ISSUE TITLE
error on running the colmap functions

### ISSUE THREAD

**Issue by dineshreddy91** [colmap/colmap#115]
successfully compiled but keep getting the above error

The output of cmake

-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   regex
--   system
--   unit_test_framework
-- Found Eigen3
--   Includes : /usr/include/eigen3
-- Found FreeImage
--   Includes : /usr/include
--   Libraries : /usr/lib/libfreeimage.so
-- Found Glog
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
-- Found required Ceres dependency: Eigen version 3.2.0 in /usr/include/eigen3
-- Found required Ceres dependency: Glog in /usr/include
-- Found Ceres version: 1.11.0 installed in: /usr/local
-- Found Glew
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
-- Found Qt 5.2.1
-- Build type not specified, using RelWithDebInfo
-- Enabling OpenMP support
-- Disabling link-time optimization (-flto)
-- Enabling CUDA support (Version 8.0)
-- Disabling profiling support
-- Configuring done
-- Generating done

QOpenGLFunctions created with non-current context 
*** Aborted at 1493778755 (unix time) try "date -d @1493778755" if you are using GNU date ***
PC: @     0x7f82888aafa1 (unknown)
*** SIGSEGV (@0x8) received by PID 48425 (TID 0x7f828b15a800) from PID 8; stack trace: ***
    @     0x7f828a606330 (unknown)
    @     0x7f82888aafa1 (unknown)
    @     0x7f8288ab525a (unknown)
    @     0x7f8288ab8493 (unknown)
    @           0x5d4c1f (unknown)
    @           0x599350 (unknown)
    @           0x599798 (unknown)
    @           0x59eb8c (unknown)
    @           0x58a5ec (unknown)
    @           0x591ce8 (unknown)
    @           0x57f9e9 (unknown)
    @     0x7f8286cc2f45 (unknown)
    @           0x587537 (unknown)
    @                0x0 (unknown)
Segmentation fault (core dumped)

**Comment by ahojnnes** [comment]
Are you running the GUI without an attached display?

**Comment by ahojnnes** [comment]
Closing this for now due to lack of feedback. Feel free to reopen if you still have problems.
