### ISSUE TITLE
Image preview in model_viewer

### ISSUE THREAD

**Issue by Dawars** [colmap/colmap#1151]
**Is your feature request related to a problem? Please describe.**
It'd be easier to check whether there are incorrectly registered images if the cameras displayed a thumbnail of the image.
This happens to me quite often since I'm working on limited a mount of data.
Now I have to double click every camera one-by-one and some of them even overlap.

Here is what I mean viually:
![colmap_preview](https://user-images.githubusercontent.com/1162980/109177992-ac01f880-7788-11eb-851d-f31f7ba66d2a.png)

**Describe the solution you'd like**
Render a small image as the camera plane

**Additional context**
I'd like to implement this and I've looked into triangle_painter and model_viewer_widget so far.

How should I go about it? 
- Should I generate separate small textures from the images? Should I create a texture atlas and index by the image id?
- Should I add the uv/texture data to triangle_painter/shader or create a new class for that?

**Comment by prasadvagdargi** [comment]
Try https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer along with docs here https://blender-addon-photogrammetry-importer.readthedocs.io/en/latest/ for visualizing COLMAP reconstructions. I've found it to be immensely helpful and has the feature you requested where the image is visualized as a plane.

**Comment by Dawars** [comment]
Thanks, this is very useful. (Often crashes blender though)

**Comment by SBCV** [comment]
If it crashes, open a bug report, and I'll see, if we can fix it ;)

**Comment by SBCV** [comment]
Btw: the latest version should not
