### ISSUE TITLE
How to get the intrinsics/extrinsics and the depth map of each input view?

### ISSUE THREAD

**Issue by 07hyx06** [colmap/colmap#1153]

**Comment by tsattler** [comment]
Run the sparse and dense reconstruction pipelines implemented in Colmap.

**Comment by 07hyx06** [comment]
> Run the sparse and dense reconstruction pipelines implemented in Colmap.

Sorry...The question is confusing. I mean where to get the intrinsics/extrinsics and the depth map of each input view after running the dense reconstruction.

**Comment by tsattler** [comment]
You can get the intrinsics and extrinsics from the sparse reconstruction (sparse/ folder in the folder with the dense reconstruction) and the depth maps from the depth maps written to the stereo/ folder in the dense reconstruction folder.

**Comment by 07hyx06** [comment]
> You can get the intrinsics and extrinsics from the sparse reconstruction (sparse/ folder in the folder with the dense reconstruction) and the depth maps from the depth maps written to the stereo/ folder in the dense reconstruction folder.

Thanks for your patience and quick reply. How to read the .bin (e.g. camera.bin) file using python scripts? What's the data structure of these .bin files?

**Comment by tsattler** [comment]
Did you had a look at the tutorial (https://colmap.github.io/tutorial.html) and the python scripts for these tasks provided by Colmap?

**Comment by 07hyx06** [comment]
I have found the description. Thanks!
