### ISSUE TITLE
sfm reconstruction: significant slow down for more than 1000 images

### ISSUE THREAD

**Issue by JanQuenzel** [colmap/colmap#116]
Hi, first thank you very much for the excellent pipeline.

I tried multiple times to reconstruct textured scenes with sufficient overlap (1/2 between consecutive fhd images).
For less than 1k images the sfm reconstruction works fine within 2-4 hours.
For less than 2k images the sfm reconstruction slows down somewhere above 1k images. E.g. after 1.2k images,  to add the next 100 images takes more than a day. 99% of the time is spend within bundle adjustment using ceres-solver. 

This happened on a Laptop (i7-6700HQ, 16GB RAM) as well as on a server (Xeon E5-2640, 128GB RAM), Linux 14.04, build on Release with a recent ceres-solver version.

I also tried: reconstruction with approx. 1k images, than adding the other 1k images (following "Register/localize new images into an existing reconstruction"). Afterwards I ran bundle_adjuster until convergence, which took 3 days to finish on the server.

Any thoughts on what the problem could be? Thank you very much!

**Comment by ahojnnes** [comment]
Which camera model are you using? Are you sharing intrinsics?

**Comment by JanQuenzel** [comment]
I am using the simple radial with shared intrinsics across all images and without custom parameters. Images were captured by a global shutter camera.

**Comment by ahojnnes** [comment]
You could speedup the reconstruction if you don't share the intrinsics across all images, since this would allow you to use PBA instead of Ceres Solver.

The default COLMAP parameters are tuned for best results, which might make it slow for larger datasets. Hence, I suggest to modify the following settings for faster speed: ``--Mapper.ba_global_images_ratio 1.2 --Mapper.ba_global_points_ratio 1.2 --Mapper.ba_global_max_num_iterations 20 --Mapper.ba_global_max_refinement 3 --Mapper.ba_global_points_freq 200000``. You can also play around with these parameters if you want a larger speedup (potentially, at the cost of less accurate results). Some of the options are defined here: https://github.com/colmap/colmap/blob/master/src/controllers/incremental_mapper.h#L31

Let me know if this works for you or if you have any other questions.

**Comment by JanQuenzel** [comment]
Hi, thanks for the quick response. I followed your first advice and reconstruction was done within 6 hours for the whole image set.
I will try out the other options later and give you feedback. Thanks again!

**Comment by ahojnnes** [comment]
Closing this issue for now as resolved. Would be interested to hear back from you about the other options. Thanks for the feedback!

**Comment by JanQuenzel** [comment]
Hi, 
I finally had some time to retry the ceres-solver Bundle Adjustment and also looked into the code.  In [optim/bundle_adjustment.cc]( https://github.com/colmap/colmap/blob/30b094616ecf7b2c2fd31c6f7d10adee2b685671/src/optim/bundle_adjustment.cc#L250 ) there are some "empirical choices". I am not sure how these switching points were determined with respect to each method. I assume you followed the advices within [FAQ for solving](http://ceres-solver.org/solving_faqs.htmll). 

I used again a stereo setup, approx. each camera had 1.2k images, 2.5k Images in total. 
I activated shared intrinsics between images for each camera and changed the ITERATIVE_SCHUR to SPARSE_SCHUR. The preconditioner stayed the same as SCHUR_JACOBI. It took 12 hours to finish the whole sparse reconstruction and not a couple of days as before with ITERATIVE_SCHUR for only one GBA.

In contrast to that, using pba without shared intrinsics kinda works, but if I refine the principal point it tends to produce unsatisfactory results ( multiple models, multiple walls, cameras that have a way too high focal length etc. ). 

Since most time previously spend was on the BA, I did not modify the other parameters you suggested. The break even point for switching from SPARSE_SCHUR to ITERATIVE_SCHUR is probably further above than 1k images.

Greetings, Jan

**Comment by ahojnnes** [comment]
Thanks for the feedback. Indeed, this is a empirical choice and mostly depends on the type/structure of problem you are solving. In general, I found that 1000 cameras is a good threshold for switching from SPARSE_SCHUR to ITERATIVE_SCHUR, but as in your example this might not be the best in all cases.

**Comment by CassieMai** [comment]
@JanQuenzel  Hello, how did you change ITERATIVE_SCHUR to SPARSE_SCHUR? I don't find the parameter ITERATIVE_SCHUR on colmap gui tool. Did you use the command version? Thank you a lot!

**Comment by isht7** [comment]
@CassieMai I believe you will have modify it in the code and then compile the code again to get the updated binary. There still wouldn't be any option in the gui or command line version.
