### ISSUE TITLE
Build COLMAP in VS2013

### ISSUE THREAD

**Issue by wusdfcd** [colmap/colmap#117]
Hi,
Thanks for your contribution and your wonderful project. When I generate the project by Cmake in windows, it reported an error like this:

CMake Error at cmake/CMakeHelper.cmake:183 (add_library):
  Cannot find source file:
    float.th
  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  src/ext/VLFeat/CMakeLists.txt:90 (COLMAP_ADD_LIBRARY)

CMake Error: CMake can not determine linker language for target: vlfeat

I do not understand the extensions .th. Is this some kind of same files like .h or what type of file it is.

Hope you can help me. Thanks very much.

**Comment by ahojnnes** [comment]
What version of CMake are you using?

**Comment by wusdfcd** [comment]
Cmake 3.7.0

**Comment by ahojnnes** [comment]
What happens if you rename the file ``src/ext/VLFeat/float.th`` to ``src/ext/VLFeat/float.th`` and accordingly change the file name in ``src/ext/VLFeat/CMakeLists.txt`` as well?

**Comment by wusdfcd** [comment]
It worked! No error has been reported. Does this means I should change all "include<float.th>" in your code to "include<float.h>"?

**Comment by ahojnnes** [comment]
I will quickly fix it and push the changes.

**Comment by wusdfcd** [comment]
Thanks a lot.

**Comment by ahojnnes** [comment]
Should be fixed now. Thanks for reporting.
