### ISSUE TITLE
Segmentation fault when "fusion" step in dense reconstruction

### ISSUE THREAD

**Issue by ShinYwings** [colmap/colmap#1171]
Is it a problem of time setting?

Here's the log
\==========================================================================
Environment 
OS : Ubuntu 20.04(focal fossa)
CUDA version : 11.2
\==========================================================================
*** Aborted at 1615446960 (unix time) try "date -d @1615446960" if you are using GNU date ***
PC: @     0x55dc10e904ae colmap::mvs::Workspace::GetDepthMap()
*** SIGSEGV (@0x458) received by PID 2413 (TID 0x7f7e49136000) from PID 1112; stack trace: ***
    @     0x7f7e8fc33631 (unknown)
    @     0x7f7e8e1583c0 (unknown)
    @     0x55dc10e904ae colmap::mvs::Workspace::GetDepthMap()
    @     0x55dc10e3d669 colmap::mvs::StereoFusion::Run()
    @     0x55dc10fb49f1 colmap::Thread::RunFunc()
    @     0x7f7e8e027d84 (unknown)
    @     0x7f7e8e14c609 start_thread
    @     0x7f7e8dcd3293 clone
Segmentation fault (core dumped)

**Comment by ahojnnes** [comment]
@anmatako Another issue reported on the fusion. Seems like we introduced a bug there? :-|

**Comment by anmatako** [comment]
@ahojnnes I can think of a case where things can go wrong with parallel fusion when it's attempted to fuse only a subset of the images, but I'm not sure if that's the case here. In any event, I'll download the repro data from #1175 and work it out on my end. I'll try to provide a fix ASAP.

**Comment by anmatako** [comment]
@ahojnnes I think the issue was due to a merge conflict that did a re-initialization of the workspace after it was already loaded. Sorry about that I should have looked more thoroughly after completing the merge.

https://github.com/colmap/colmap/blob/5cba5d18d2877e589e3ce56579f18796432a05b0/src/mvs/fusion.cc#L177

I'll submit the PR for the fix.

**Comment by anmatako** [comment]
PR for the fix #1176

**Comment by ShinYwings** [comment]
> PR for the fix #1176

Thank you! It successfully works for me too!
