### ISSUE TITLE
Unknown bug in stereo_fusion step

### ISSUE THREAD

**Issue by xshuai1996** [colmap/colmap#1175]
**Describe the bug**
It crashed during the step of "Reading configuration..." in stereo_fusion. 
![Screenshot from 2021-03-11 21-51-57](https://user-images.githubusercontent.com/56774512/110898804-c671c100-82b4-11eb-90b2-9685c092b7dd.png)

**To Reproduce**
Use this dataset (also tested on 2 others but got same trouble) https://github.com/openMVG/ImageDataset_SceauxCastle, and simply run 
-> colmap feature_extractor --database_path ./database.db --image_path ./images
-> colmap exhaustive_matcher --database_path ./database.db
-> colmap mapper --database_path ./daabase.db --image_path ./images --output_path ./sparse
-> colmap image_undistorter --image_path ./images --input_path ./sparse/0 --output_path ./dense --output_type COLMAP --max_image_size 2000 
-> colmap patch_match_stereo --workspace_path ./dense --workspace_format COLMAP --PatchMatchStereo.geom_consistency true 
-> colmap stereo_fusion --workspace_path ./dense --workspace_format COLMAP --input_type geometric --output_path ./dense/fused.ply

**Desktop (please complete the following information):**
Ubuntu 18.04
Eigen was downgraded to 3.3.3 as instructed by previous post (but didn't help)
About CUDA: I'm not pretty sure. I installed pytorch-gpu and at that time the log showed it automatically downloaded cudatoolkit 11.1 and gpu is available verified by code, but I got no reaction using e.g. nvcc -V or nvidia -smi. For COLMAP, feature_extractor amd matcher (use gpu = true) runs successfully

I have no idea where I goes wrong. Anyone help me out please?

**Comment by anmatako** [comment]
PR for the fix PR for the fix #1176

**Comment by xshuai1996** [comment]
Sorry for delay. I deleted line 177 instructed by #1176 and it works now :) Thank you guys

**Comment by anmatako** [comment]
@xshuai1996 The fix should have been already merged normally but something seems to be stuck in the checks for the PR. All the pipeline completed successfully but the status in #1176 is not updating. @ahojnnes There must be a way to fix this and complete the merge, right?
