### ISSUE TITLE
I attempt to Flatpak Colmap 3.6, got some error. libceres.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kevinsmia1939** [colmap/colmap#1180]
Hello,

I create Flatpak for COLMAP.
Flatpak is a packaging and distributing desktop software on Linux.
https://www.flatpak.org/

I would like it to be submit to Flathub, an app store for Flatpak apps. Many Linux distros supported Flatpak. So I think it would be beneficial to package large software like COLMAP into Flatpak, it will make installing quick and easy.
https://flathub.org/home

This is what I have been working on so far.
https://github.com/kevinsmia1939/com.github.colmap.colmap

It does build but does not run. 
When I try to run I got the error below.

```
flatpak run io.github.colmap.colmap
colmap: error while loading shared libraries: libceres.so.2: cannot open shared object file: No such file or directory
```

It does not find libceres.so.2 but I install ceres and libceres.so.2 it exist in lib64.

The build flags are list below, you can find complete Flatpak manifest file in my repo above.
```
ceres-solver 2.0.0
      - -DCXSPARSE=ON 
      - -DSUITESPARSE=ON 
      - -DEIGENSPARSE=ON 
      - -DGFLAGS=OFF 
      - -DMINIGLOG=OFF 
      - -DBUILD_SHARED_LIBS=ON
      - -DBUILD_TESTING=OFF
      - -DBUILD_EXAMPLES=OFF
      - -DOPENMP=ON
      - -DCXX11=ON
```

```
COLMAP 3.6
      - -DCMAKE_BUILD_TYPE:STRING=Release
      - -DBOOST_STATIC=OFF
      - -DOpenGL_GL_PREFERENCE=LEGACY
      - -DEIGEN3_VERSION=3.3.9
```

Please build Flatpak with instructions below, to see if you have the same issue.

1. Create new working folder.
2. Install flatpak-builder, for Ubuntu, ``sudo apt install flatpak-builder``
3. Install KDE Sdk, choose version 5.15 (system), ``flatpak install org.kde.Platform org.kde.Sdk``
4. Clone sumodules, ``git clone git://github.com/flathub/shared-modules.git``
5. Download io.github.colmap.colmap.yaml and suitesparse-reduce-build.patch
6. ``flatpak-builder --install --user build io.github.colmap.colmap.yaml --force-clean``
7. Wait until finish and run with, ``flatpak run io.github.colmap.colmap``

Let me know if you know how to fix it.

**Comment by kevinsmia1939** [comment]
I fix it by manually copying libceres.so.2 to /lib

**Comment by zimingzhong** [comment]
Hi, I have a similar problem with yours. I got `error while loading shared libraries: libceres.so.1 `. I have install ceres-sovler and colmap successfully without error. And I can not find the file libceres.so.1.
