### ISSUE TITLE
Registration of new frames on a model

### ISSUE THREAD

**Issue by thesigmaguy** [colmap/colmap#1183]
Hello, we see a slight shift in the case of registering set of frames(SET A) to the reconstruction from the Subset of frames of (SET A). All the images are from sequences of video. Sequentially matched with shared intrinsic and reconstructed.

We got convergence on while registering and still we have a slight shift from ply projected onto canvas vs Ground truth frames.

We use the exhaustive matcher, image registrator, and bundle adjuster for registering SET-A frames on the reconstruction made on a subset of images.

Do we have to undistort or something?

**Comment by xuxumiao777** [comment]
@dhawal1939 I meet the same problem. Have you solved it?
