### ISSUE TITLE
Build errors - pba::NewSparseBundleCPU : function does not take 1 arguments

### ISSUE THREAD

**Issue by json87** [colmap/colmap#12]
hi, 
thanks for releasing this great software. but I have come across  a build error with the latest source code as described in title. 

the error lies in pba.cpp in line 40
_optimizer = NewSparseBundleCPU(false);

waitting your reply! thanks!

**Comment by ahojnnes** [comment]
Thanks for the bug report. Which compiler and OS do you use?

**Comment by json87** [comment]
vs 2013 on windows 7  x64

**Comment by ahojnnes** [comment]
Thanks, I'll look into it later today!

**Comment by ahojnnes** [comment]
Fixed with https://github.com/colmap/colmap/commit/2612c25d02a8bf554d775504aeb354435976ada2

Thanks for the bug report.
