### ISSUE TITLE
panoramic camera model

### ISSUE THREAD

**Issue by Dorothy-2016** [colmap/colmap#120]
Hi,@ahojnnes Can this method now be used with panoramic camera model,like the images taked by theta s?

**Comment by Dorothy-2016** [comment]
Hi ! @ahojnnes  ,  apart the first question ,I have another question now,when I run this method on the step of reconstruction, I found that there is a "reconstruct next image" button there,How should I understand this,does it means that i can do the reconstruct function one by one ,which not like some methods that should first give all images that are needed,by the way,you are really doing a great job!

**Comment by ahojnnes** [comment]
No, this is not integrated but you can check out this branch here: https://github.com/colmap/colmap/pull/9 - I am still planning to integrate this feature eventually but I don't have a specific timeline for this. Regarding your second question: the "reconstruct next image" simply performs the reconstruction step by step - it will produce the same results as if you were just clicking the "start reconstruction" button. It is mostly there for more fine-grain control during reconstruction (in case you want to change options while reconstructing).

Closing this issue for now as answered but feel free to reopen.

**Comment by gnool** [comment]
Hi @ahojnnes , is the fine-grain control available in command line mode too? Or is this currently only available in the GUI mode? I have been using colmap mapper only so far and did not see an option to add image by image there.

**Comment by ahojnnes** [comment]
@gnool The fine-grain control is only available in the GUI and it is not programmable from the command-line interface. Of course, you could easily modify the C++ code directly, if you need step by step control over the reconstruction process.
