### ISSUE TITLE
point_triangulator use image poses priors get bad results compared to colmap GUI

### ISSUE THREAD

**Issue by hughyoung85** [colmap/colmap#1202]
I'm trying to use the known camera pose(get from arcore/lidar) to improve sparse reconstruction accuracy. but get few 3D points
The steps is:
1、colmap feature_extractor --image_path E:\WORK\Dataset\ARcore\colmap\images --database_path E:\WORK\Dataset\ARcore\colmap\colmap_db.db --SiftExtraction.estimate_affine_shape 1  --SiftExtraction.domain_size_pooling 1 --ImageReader.camera_model PINHOLE --ImageReader.single_camera 1 --ImageReader.camera_params "497.720612,499.147339,319.460693,242.168503" --SiftExtraction.max_num_orientations 1 --SiftExtraction.upright 1
2、colmap exhaustive_matcher  --database_path E:\WORK\Dataset\ARcore\colmap\colmap_database.db --SiftMatching.guided_matching 1
3、colmap point_triangulator --database_path E:\WORK\Dataset\ARcore\colmap\colmap_database.db --image_path E:\WORK\Dataset\ARcore\colmap\images --input_path E:\WORK\Dataset\ARcore\colmap\colmap --output_path E:\WORK\Dataset\ARcore\colmap\colmap_point_triangulator --Mapper.ba_refine_focal_length 0 --Mapper.ba_refine_extra_params 0

Is something wrong in my step?

**Comment by kondela** [comment]
It appears that you are using different DB in each step, i.e.  `--database_path E:\WORK\Dataset\ARcore\colmap\colmap_db.db` vs `--database_path E:\WORK\Dataset\ARcore\colmap\colmap_database.db`

**Comment by hughyoung85** [comment]
@kondela , that's my mistake, in fact I used the same DB. my problem is I want to use panorama image to mapping. so I converted the panorama image to pinhole image, and also to the pose.  if I used the converted pinhole image to mapping with Colmap GUI.  it successed. But add the camera pose priors with colmap CLI. it failed. so I don't know where the problem is
