### ISSUE TITLE
Use two different camera models in one project

### ISSUE THREAD

**Issue by PPPPeterpan** [colmap/colmap#1207]
Thanks for the amazing work!
I want to ask: is it possible to use two different camera models in one project? (I want to use OPENCV and OPENCV_FISHEYE)

I set` --ImageReader.single_camera_per_folder 1 `
and put images captured by two cameras in two directories. 

Can I choose camera model specifically for each directory?
Thanks so much!

**Comment by tsattler** [comment]
Yes, this is possible.

The easiest way is probably to use the feature_extractor from the command line, as this allows you to specify a text file of the images in the image directory that should be used for extraction (all others are ignored). You can then call feature_extractor twice, once for the images with the OPENCV model and once for those that should use the OPENCV_FISHEYE model.

**Comment by PPPPeterpan** [comment]
thanks so much it solves my problem!

**Comment by ahojnnes** [comment]
Yes, that is possible. You can modify the cameras in the GUI when you open the database and then enter "database management". Otherwise, you can achieve the same by modifying the SQLite database directly. See for example scripts/python/database.py for reference.
