### ISSUE TITLE
writing features directly into the database?

### ISSUE THREAD

**Issue by Helaly96** [colmap/colmap#1208]
making 1000 files with atleast 20k lines in each of them is a time consuming process that could be directly solved by enabling directly writing into the database?

can this be done?

**Comment by tsattler** [comment]
Yes, this is possible. You can have a look at database.py under scripts/python or the C++ source code for examples.

**Comment by Helaly96** [comment]
Thank you so much

**Comment by Helaly96** [comment]
Sorry, after reading the code, i didn't find any example of writing the describtor
so i managed to write the keypoints but each point should have a SIFT (or similar) describtor for each point.

but the functions add_describtor only takes the image id

**Comment by tsattler** [comment]
Here is a code snipped in python for writing descriptors: https://github.com/colmap/colmap/blob/dev/scripts/python/database.py#L192
Here is code to write keypoints in C++: https://github.com/colmap/colmap/blob/9f3a75ae9c72188244f2403eb085e51ecf4397a8/src/base/database.cc#L665
Here is code to write descriptors in C++: https://github.com/colmap/colmap/blob/9f3a75ae9c72188244f2403eb085e51ecf4397a8/src/base/database.cc#L676
