### ISSUE TITLE
Difference between SIMPLE_PINHOLE and PINHOLE

### ISSUE THREAD

**Issue by xianggao1989** [colmap/colmap#121]
Hi,
I am using the Windows binary version of COLMAP and benefit a lot from it. Could you tell me the difference between the camera model of SIMPLE_PINHOLE and PINHOLE?
Thank you very much!
Best regards,
Xiang Gao from NLPR, CASIA

**Comment by ahojnnes** [comment]
One vs two focal length parameters, which is useful if you have non-square pixels/shear. Always stick to the most simple model if it is sufficient.

**Comment by xianggao1989** [comment]
Get it and thanks for your reply!
