### ISSUE TITLE
Detecting cameras with incorrect pose after Bundle Adjustment or rejecting them during processing

### ISSUE THREAD

**Issue by matteoTaiana** [colmap/colmap#1215]
Hi everyone,
I performed the sparse reconstruction of a few outdoors scenes and, upon inspection, I realised that some of the estimated poses  for the cameras are not correct. I can they are not correct by looking at the estimated poses and at the images. Plus, I reconstruct some 3D objects in the scene and, for the images that have an incorrect pose, the 3D objects are projected onto the wrong part of the image.
If this helps, the incorrect poses seem to form a "cluster": they are located in a small area of the 3D scene and they seem to be coherent with one another, but not with the rest of the pose graph. 
In some other cases (possibly a sequence of poses in which the camera was moving forward in the direction of image capture), the poses have collapsed in a small location, so the poses are not even coherent among themselves.

For what I am doing, I would need to select only the cameras which have a good pose estimate for further processing. Is there a way to do that?

Alternatively, are there some settings I can use to make the COLMAP mapper "pickier", so that it will discard the images which would result in incorrect poses?
 
This is how I perform the sparse reconstruction (on Ubuntu/Bash):
```
DATASET_PATH=/MyDataset/
mkdir $DATASET_PATH/sparse

colmap feature_extractor --image_path $DATASET_PATH/images \
--SiftExtraction.estimate_affine_shape=true \
--SiftExtraction.domain_size_pooling=true \
--ImageReader.mask_path $DATASET_PATH/masks \
--database_path $DATASET_PATH/database.db

colmap exhaustive_matcher --SiftMatching.guided_matching=true \
--database_path $DATASET_PATH/database.db

colmap mapper \
--database_path $DATASET_PATH/database.db \
--image_path $DATASET_PATH/images \
--output_path $DATASET_PATH/sparse
```

Thank you in advance.

**Comment by tsattler** [comment]
You could try to adjust the `--Mapper.min_num_matches`, `--Mapper.abs_pose_min_num_inliers`, and `--Mapper.abs_pose_min_inlier_ratio` parameters to see whether this helps in avoiding to register these images.

**Comment by matteoTaiana** [comment]
Hi @tsattler, 
thank you for your quick answer, it was very helpful.

I did try a few combinations of values for the parameters you mentioned. 
When I use the default matching settings, I get one large model as output, with a few cameras with incorrect poses.
When I use "strong" matching settings (high ```min_num_matches```, high ```abs_pose_min_num_inliers```, high ```abs_pose_min_inlier_ratio```), I get a few disconnected models, whose camera poses are all correct.
 
 I suppose I am pushing COLMAP to the limit: if I really want to get one large model with all correct poses, I will probably need to acquire more images.
