### ISSUE TITLE
Disable DSP-SIFT feature extraction

### ISSUE THREAD

**Issue by farhadinima75** [colmap/colmap#1219]
Hi everyone.
Is there a way to disable DSP-SIFT?

I want to do this for two reasons:
1. a part of my project must complete on SIFT features.
2. keypoints format is in the shape of [N, 6] (Affine features) and I wanna [N, 4] format of keypoints (conventional SIFT format with x, y, scale, angle).

After a lot of searches, I found that after adding DSP-SIFT to version 3.3, keypoints format changes from [N, 4] to [N, 6]. 
If I'm wrong plz tell me.

Any help would be appreciated. thanks in advance.

**Comment by tsattler** [comment]
If I remember correctly, DSP-SIFT is not used per default. Rather, the GPU implementation of SIFT is used. If you want to have DSP-SIFT features, you need to enable them explicitly.

That being said, all features are stored using an affine shape. If you look at the implementation of the SIFT feature extractor, you should find the code that maps the scale and orientation of the keypoints to the corresponding affine parameters, which you can then use to recover these values.

**Comment by farhadinima75** [comment]
thanks for your response @tsattler 
yes, today I found them in feature extractor file. but the problem is I'm not an expert in C and if there is a python alternative would be great.

**Comment by tsattler** [comment]
This part is implemented in C++ and there is no python implementation of it that I am aware of.

**Comment by farhadinima75** [comment]
Can you provide me a code/semi code to recover scale and angle?

**Comment by tsattler** [comment]
This function maps the keypoint orientation and scale to affine parameters: https://github.com/colmap/colmap/blob/9f3a75ae9c72188244f2403eb085e51ecf4397a8/src/feature/types.cc#L43
I would assume that you can implement the inverse procedure to recover both parameters.

**Comment by farhadinima75** [comment]
tnx, closing issue.

**Comment by farhadinima75** [comment]
Hi again @tsattler 
I think I've found a bug, or maybe I'm wrong.

the following numbers are first 4 extracted keypoints in one of my datasets:

> 
             x              y            a11            a12            a21            a22
    0  646.9909057617  5.8259654045  2.1989517212   -0.048708152   0.048708152    2.1989517212
    1  763.1506958008  5.8988099098  0.8509112597   1.8682333231  -1.8682333231   0.8509112597
    2  956.5690917969  5.7540082932  -0.6544747353  -1.9470323324  1.9470323324  -0.6544747353
    3  956.5690917969  5.7540082932  -0.6591399312  1.9454579353  -1.9454579353  -0.6591399312


According to [colmap/src/feature/types.cc](https://github.com/colmap/colmap/blob/9f3a75ae9c72188244f2403eb085e51ecf4397a8/src/feature/types.cc#L43) you've mentioned:
`  a22 = scale * cos(orientation)
`

To my best knowledge, the scale parameter cant be a negative number. On another hand, cos(angel) is always a positive number. SO:
why some rows of a22 column is negative? Have I forgotten something?

**Comment by tsattler** [comment]
cos(angle) is in the range [-1,1], i.e., the cosine function can take on negative values.

**Comment by farhadinima75** [comment]
yes, your right. I have forgotten that. closing issue.

**Comment by alexs7** [comment]
> If I remember correctly, DSP-SIFT is not used per default. Rather, the GPU implementation of SIFT is used. If you want to have DSP-SIFT features, you need to enable them explicitly.
> 
> That being said, all features are stored using an affine shape. If you look at the implementation of the SIFT feature extractor, you should find the code that maps the scale and orientation of the keypoints to the corresponding affine parameters, which you can then use to recover these values.

Hello, so whatever option we use we will always get 6 cols ? 
I was reading this: https://colmap.github.io/faq.html#increase-number-of-matches-sparse-3d-points

Then came across this issue.

**Comment by ahojnnes** [comment]
Yes, you will always get 6 columns.
________________________________

**Comment by alexs7** [comment]
> Yes, you will always get 6 columns.
> […](#)

Thanks!

**Comment by alexs7** [comment]
> Yes, you will always get 6 columns.
> […](#)

Just wondering, when do we get 4 ?

**Comment by ahojnnes** [comment]
You always get 6 columns. See https://github.com/colmap/colmap/blob/dev/src/base/database.cc#L54

Only exception would be if you run a very old colmap version or have an existing database created by a very old version.
________________________________

**Comment by alexs7** [comment]
Ok ! Thanks again!
