### ISSUE TITLE
The usage of bundle_adjuster.exe

### ISSUE THREAD

**Issue by xianggao1989** [colmap/colmap#122]
Hi,
I am using the Windows binary version of COLMAP and benefit a lot from it. Could you tell me the input of the bundle_adjuster.exe, i.e. what should I put in the --input_path. In addition, I wonder if the bundle_adjuster.exe has some advanced functions such as set the camera model (PINHOLE or RADIAL) and group the camera intrinsic parameters.
Thank you very much!
Best regards,
Xiang Gao from NLPR, CASIA

**Comment by ahojnnes** [comment]
`--input_path`` should point to the sparse reconstruction folder containing the images.txt, cameras.txt and points3D.txt. The intrinsics are taken as specified in images.txt and cameras.txt. If you want to share intrinsics, images should have the same camera ID.

**Comment by xianggao1989** [comment]
Get it. Thanks a lot!
