### ISSUE TITLE
build colmap failed for CUDA 11.2, Ubuntu 20.04

### ISSUE THREAD

**Issue by SherryXTChen** [colmap/colmap#1223]
**Describe the bug**
- OS: [Ubuntu 20.04]
- Compiler: GCC 9.3.0
- CUDA 11.2

**To Reproduce**
I have followed the Linux Build from Source instruction step by step as shown in https://colmap.github.io/install.html, where the last several steps are:
```shell
git clone https://github.com/colmap/colmap.git
cd colmap
git checkout dev
mkdir build
cd build
cmake ..
```

but I got errors like

```shell
-- Found Boost: /lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.48")  
-- Boost include dirs: /include
-- Boost libraries:    
-- Using gcc version 4 or later. Adding -frounding-math
-- Found Qt
--   Module : /lib/x86_64-linux-gnu/cmake/Qt5Core
--   Module : /lib/x86_64-linux-gnu/cmake/Qt5OpenGL
--   Module : /lib/x86_64-linux-gnu/cmake/Qt5Widgets
-- Found CGAL
--   Includes : /usr/include
--   Libraries : CGAL
-- Build type not specified, using Release
-- Enabling SIMD support
-- Enabling OpenMP support
-- Disabling interprocedural optimization
-- Disabling CUDA support (found version 10.1 but >= 7.0 required)
-- Enabling OpenGL support
-- Disabling profiling support
-- Enabling CGAL support
-- Configuring done
CMake Error in src/CMakeLists.txt:
  Imported target "Boost::filesystem" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in src/CMakeLists.txt:
  Imported target "Boost::filesystem" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

```

It looks like the problem has to do with the wrong Boost::filesystem path, but I am not sure what should be the fix. There is indeed no '/include' in the filesystem. I think boost's include path should be /usr/include/boost which exists (not /include/boost).

**Comment by SherryXTChen** [comment]
Here is a temporary workaround I use
```shell
sudo mkdir /include
sudo ln -s /usr/include/boost /include/boost
```
Is there better options? Thanks

**Comment by SherryXTChen** [comment]
Thanks @ishipachev. I re-installed boost and everything is working right now. It turned out that I don't have -dev versions installed before.

**Comment by ishipachev** [comment]
@SherryXTChen 
Do you want to keep this issue open? Or it's solved?

**Comment by SherryXTChen** [comment]
The problem is solved.I am closing the issue. Thank you!

**Comment by vinayak-pathak** [comment]
Hi, Apart from the above error I have another error System, mine system has CUDA 10.1 installed but it's not being detected during building. here is the output when I run cmake.cmake ..
-- Found required Ceres dependency: Eigen version 3.3.7 in /usr/include/eigen3
-- Found required Ceres dependency: glog
-- Found required Ceres dependency: gflags
-- Found Ceres version: 2.0.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, Multithreading]
-- Found Boost: /lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: program_options filesystem graph system unit_test_framework 
-- Found Eigen
--   Includes : /usr/include/eigen3
-- Found FreeImage
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
-- Found Glog
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
-- Found Glew
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /bin/c++ compiler.
-- Found Boost: /lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.48")  
-- Boost include dirs: /include
-- Boost libraries:    
-- Using gcc version 4 or later. Adding -frounding-math
-- Found Qt
--   Module : /lib/x86_64-linux-gnu/cmake/Qt5Core
--   Module : /lib/x86_64-linux-gnu/cmake/Qt5OpenGL
--   Module : /lib/x86_64-linux-gnu/cmake/Qt5Widgets
-- Found CGAL
--   Includes : /usr/include
--   Libraries : CGAL
-- Build type not specified, using Release
-- Enabling SIMD support
-- Enabling OpenMP support
-- Disabling interprocedural optimization
-- **Disabling CUDA support (found version 10.1 but >= 7.0 required)**
-- Enabling GUI support
-- Enabling OpenGL support
-- Disabling profiling support
-- Enabling CGAL support
-- Configuring done
CMake Error in src/CMakeLists.txt:
  Imported target "Boost::filesystem" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in src/CMakeLists.txt:
  Imported target "Boost::filesystem" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
