### ISSUE TITLE
Compare the camera positions and orientations of two different models/reconstruction

### ISSUE THREAD

**Issue by tudipffmgt** [colmap/colmap#1224]
I am using COLMAP to generate a reference model of ~20 cameras from clicked tie points. I do not have world coordinates for these points so all my cameras are oriented in a local coordinate system.
Then, I am using some feature detection method to orient the 20 images automatically in another project file (so a different local coordinate system). I call it source model.
How could I compare the camera positions and orientations of the 20 cameras from source model to reference model?
What I am doing right now is to calculate a Helmert Transformation of the translations tx_source, ty_source, tz_source (from images.txt) to tx_reference, ty_reference, tz_reference and use the resulting scaled rotation matrix to transform every camera from source to reference. The euclidean distance between the camera positions is quite good but the angles or the angle error (https://arxiv.org/abs/1707.09092v3) seems to be quite off.
I think I am missing something about how to handle the angles/quaternions.

Is there already a feature which I can use to compare two different reconstructions of the same cameras?
Edit: I just saw that there is the option of using `model_aligner`. Would it work if the automatic method generates outliers? Are these e.g. removed via RANSAC?

**Comment by tsattler** [comment]
The `model_aligner` uses RANSAC to handle outliers.

Using the `model_aligner` to compute the similarity transformation between the two models and then comparing the poses is the way I would approach the problem.

Note though that you will need to specify the threshold used to distinguish between inliers and outliers.

**Comment by tudipffmgt** [comment]
Thank you for the fast reply! My first big mistake was that I was not dealing with the actual camera centers but I used the TVEC. Now I have calculated the actual positions using the provided equation https://colmap.github.io/format.html#images-txt.
I get a result using the model_aligner like this:

> Aligning reconstruction
> -----------------------
>  => Using 19 reference images
>  => Alignment succeeded
>  => Alignment error: 0.274565 (mean), 0.217662 (median)

Is it possible to get more statistics like e.g. the angle error? Is the alignment error the mean (resp. median) euclidean distance of the camera centers? Would I get a note if some of the images are not used due to the threshold?

**Comment by tsattler** [comment]
I recommend looking directly at the source code of the method (you can start from `src/exe/colmap.cc` and find the relevant function calls). This will also allow you to figure out how to get the additional information you are interested in.
