### ISSUE TITLE
Format of the normal map.

### ISSUE THREAD

**Issue by Martincho07** [colmap/colmap#1226]
Hi.

I´m interesting in know the used format of the normal map in the version 3.7.

**Comment by tsattler** [comment]
You can have a look at the definition of the normal map here: https://github.com/colmap/colmap/blob/master/src/mvs/normal_map.h

The function to write it to disc should be this one: https://github.com/colmap/colmap/blob/master/src/mvs/mat.h#L180

**Comment by Martincho07** [comment]
Okey thanks for the help. Can you tell me what is the map legend for normal map ?

**Comment by tsattler** [comment]
What do you mean by "map legend"?

**Comment by Martincho07** [comment]
A sphere as Map Key / Map Legend to help understand the normal direction
in the generated normal map. 

This is one example:
[https://download.blender.org/documentation/bc2004/Roy_Schulz/images/NormalMap.jpg](url)

**Comment by tsattler** [comment]
I see. Thanks for the clarification.

You can have a look at the visualization code for the normal maps, which will contain the mapping from normal directions to colors.

**Comment by Martincho07** [comment]
Okey.

Thank you for everything!. :)

**Comment by EliCDavis** [comment]
For those wondering about the specific code for visualization, it can be found here:

https://github.com/colmap/colmap/blob/e924f0f825c6033a0cf2b89fa79c585236d4bf3a/src/colmap/mvs/normal_map.cc#L112-L114

Take note the z component's range is assumed to be between -1 and 0, where as the other components are assumed to be between -1 and 1
