### ISSUE TITLE
Crash on Fusion when some dense reconstruction images are 0 bytes

### ISSUE THREAD

**Issue by boarpig** [colmap/colmap#1227]
**Describe the bug**
I'm getting a crash when running fusion on my rather large dataset. During fusion I get this error

```
F0526 16:13:18.131356 358182 mat.h:167] Check failed: width_ > 0 (0 vs. 0) 
*** Check failure stack trace: ***
F0526 16:13:18.152509 358181 mat.h:167] Check failed: width_ > 0 (0 vs. 0) 
*** Check failure stack trace: ***
    @     0x7fd3b686081d  google::LogMessage::Fail()
    @     0x7fd3b686081d  google::LogMessage::Fail()
    @     0x7fd3b6862ce9  google::LogMessage::SendToLog()
    @     0x7fd3b6862ce9  google::LogMessage::SendToLog()
    @     0x7fd3b68603ea  google::LogMessage::Flush()
    @     0x7fd3b686326a  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fd3b68603ea  google::LogMessage::Flush()
    @     0x5571200f0250  colmap::mvs::Mat<>::Read()
    @     0x5571200edb2e  (unknown)
    @     0x5571200edf65  (unknown)
    @     0x55711ff26b2d  std::__future_base::_State_baseV2::_M_do_set()
    @     0x7fd3b686326a  google::LogMessageFatal::~LogMessageFatal()
    @     0x5571200f0250  colmap::mvs::Mat<>::Read()
    @     0x5571200edb2e  (unknown)
    @     0x5571200edf65  (unknown)
    @     0x55711ff26b2d  std::__future_base::_State_baseV2::_M_do_set()
    @     0x7fd3b5469c9f  __pthread_once_slow
    @     0x5571200e9579  (unknown)
    @     0x5571201ed866  colmap::ThreadPool::WorkerFunc()
    @     0x7fd3b5469c9f  __pthread_once_slow
    @     0x5571200e9579  (unknown)
    @     0x5571201ed866  colmap::ThreadPool::WorkerFunc()
    @     0x7fd3b5337bc4  execute_native_thread_routine
    @     0x7fd3b5337bc4  execute_native_thread_routine
    @     0x7fd3b5462299  start_thread
    @     0x7fd3b5462299  start_thread
    @     0x7fd3b4ff8053  __GI___clone
Aborted (core dumped)
```

**To Reproduce**
1. After sparce construction
2. Click on 'Reconstruction->Dense Reconstruction'
3. Run Undistortion (with selected destination folder)
4. Run Stereo
5. Run Fusion
6. F0526 16:13:18.152509 358181 mat.h:167] Check failed: width_ > 0 (0 vs. 0)

**Additional context**
 I checked issue tracker for width keyword and came upon  [issue 553](https://github.com/colmap/colmap/issues/553), but one that happens on stereo reconstruction step. It was recommended to check dense reconstruction images for zero size files, and I indeed had two files that were 0 bytes. I deleted those files, ran dense reconstruction again and fusion after that and it worked fine.

I don't know why my dense image directory had few 0 byte files but instead of crashing I think it should maybe prompt for removing those files and rerun dense reconstruction which fixes this issue.

**Comment by ishipachev** [comment]
Have you tried to monitor your RAM memory?
Are you sure that you are not running out of memory? It is quite common the reason of crashes.

**Comment by boarpig** [comment]
At first I ran out of memory, then I adjusted the cache size and ran again and I got the crash. I will check this again tomorrow and update or close this issue.

**Comment by ishipachev** [comment]
Try to lower cache size further. In my experience with 6Gb video card cache size around 2Gb is something which I can work with without crashes for my 4k x 3k pixels pictures. Probably you won't hit upper bound of cache size memory until you start working with big pictures so their depth maps after undistortion got even bigger and stoped fit into the actual memory.

**Comment by boarpig** [comment]
For me Fusion is using CPU, not GPU and I see no option to change that. I have 16GB of ram on my computer and it seems Fusion still maxes out all that as well as all my Swap space even if I set it to something small, such as 4GB

**Comment by boarpig** [comment]
I think you may be right and my data might be too large. I ran reconstruction with 60 images and everything worked fine. I still suspect there is a memory leak of sorts when doing fusion with big enough data since it doesn't seem to respect cache size, but that is unrelated issue.
