### ISSUE TITLE
Resuming Sparse reconstruction

### ISSUE THREAD

**Issue by ClaudioCimarelli** [colmap/colmap#1228]
Hello,

I have a question about stopping and resuming a sparse reconstruction. I have a very long sparse reconstruction step going on and I would like to know if this can be resumed in case it gets stopped before it finishes and if there a way to save an intermediate output. Up to now, there is nothing saved in the output folder, so I don't know if all the computations get lost after an interrupt signal or what happens.
 The only related issue I could find is #1076 and not many other mentions about the problem. Still, I have not clear about what I should be doing to safely save an intermediate state.
 I am using colmap command-line interface, and for running the sparse mapping the mapper command.

Thanks for your help.

**Comment by tsattler** [comment]
You can use the `--input_path` option to resume the reconstruction from a given model (see also https://colmap.github.io/faq.html#register-localize-new-images-into-an-existing-reconstruction).

You can use the `--Mapper.snapshot_images_freq` and `--Mapper.snapshot_path` options to store intermediate models during the reconstruction process.

**Comment by ClaudioCimarelli** [comment]
Okay, many thanks. I think I wasted two days pf HPC computation and will start from scratch :man_facepalming:. I should have looked better into the param options before :)

Thanks again as always.
