### ISSUE TITLE
Is there any constraints in the process of SFM to avoid bending the poses along tracks

### ISSUE THREAD

**Issue by riyueshi** [colmap/colmap#123]
Hi,
  When I perform the structure from motion process using some software ( e.g. openMVG  and visualSFM) the recovered poses bend along the direction of flight which present in the paper "Critical Configurations for Radial Distortion Self- Calibration" (this happens frequently when using the UAV image which has distortion).  But this problem didn't happens when using colmap for some data set (and this problem happened with openMVG using the same data set). I am curious is there any constraints colmap applied to avoid this problem.

Miller.

**Comment by ahojnnes** [comment]
Hi, no there is no special handling of this case. COLMAP uses a different initialization/registration algorithm and uses more aggressive retriangulation/filtering/refinement, which might lead to better results if the initial intrinsics are not good. Please refer to my "Structure-from-Motion Revisited" paper for more details. Let me know if you have another question. Closing this issue for now, but feel free to reopen. Thanks!
