### ISSUE TITLE
ld: library not found for -lcolmap

### ISSUE THREAD

**Issue by cfiore-jpg** [colmap/colmap#1231]
![image](https://user-images.githubusercontent.com/77872473/121628816-fe210e00-ca47-11eb-8442-347c89c697d5.png)
I get the above error when attempting to run code that includes the colmap library. I am on mac running Big Sur. Below is my CMakeLists.txt. Any idea what is going wrong?
![image](https://user-images.githubusercontent.com/77872473/121629018-5c4df100-ca48-11eb-842d-399dd4945efc.png)

**Comment by tsattler** [comment]
Is the directory containing the Colmap library in the set of paths where the compiler looks for libraries? Seems that the linker cannot find the library file.

**Comment by cfiore-jpg** [comment]
I fixed the issue by rearranging my CMakeLists.txt in the following way. Couldn't tell you why this works, but anyone who knows why, please let me know. Would be interested. Thanks.
![image](https://user-images.githubusercontent.com/77872473/121690247-9c869100-ca93-11eb-820b-817606a6fdf6.png)
