### ISSUE TITLE
The indexes of images associated with meshes (mesh.visible_image_idxs) are not consistent with indexes within sparse/images.bin

### ISSUE THREAD

**Issue by MahdiHajibabaei** [colmap/colmap#1232]
Hi,

After importing meshes (from *.ply and *.ply.vis) using Python script provided at colmap/scripts/python/read_write_fused_vis.py, the indexes of images associated with each mesh (mesh.visible_image_idxs) seems not to be identical to index of images within sparse/images.bin. I was wondering whether in any part of stereo fusion indexes are changed and saved into the *.ply and *.ply.vis and if there is any way we could find the correspondences between indexes.

**Comment by tsattler** [comment]
Have you looked at the code that generates the visibility files?

**Comment by MahdiHajibabaei** [comment]
Found it (https://github.com/colmap/colmap/blob/9f3a75ae9c72188244f2403eb085e51ecf4397a8/src/mvs/fusion.h#L180 ). Thanks a lot!
