### ISSUE TITLE
Incorrect camera focal length estimation

### ISSUE THREAD

**Issue by brans-cere** [colmap/colmap#1233]
1. I have a set of simple synthetic images with a checkboard pattern generated with an unreal engine default camera (FOV = 90 degrees). 
[Rendered imaged with checkboard pattern](https://github.com/colmap/colmap/files/6640128/renders.zip)

2. I am making automatic reconstruction using a colmap and (shared intrinsics , simple_pinhole camera model)

3. I am expecting to get camera focal length  fx=fy=f=imageWidth /(2 * tan(CameraFOV * π / 360)) = 1280 /(2 * tan(90 * 3.14 / 360)) = 640.5 px (?).  Using Matlab calibration toolbox I am getting 630 from the same set of images.

4.  After the reconstruction in the COLMAP I see Focal Length 1536.0  
![Untitled](https://user-images.githubusercontent.com/83638268/121727452-98d72680-caf4-11eb-8ac3-8d36f465b480.jpg)

Why do I get such a large result with the COLMAP?  What is wrong here?

**Comment by tsattler** [comment]
Colmap does not store the results of the reconstruction in the database. They are only stored in the model that you export / store. The value in the database is an initial guess by Colmap.

**Comment by ishipachev** [comment]
@brans-cere 
Try to export model in text format: In COLMAP go to **File** -> export in text format.
You will see the file "cameras.txt" where all parameters estimated during reconstruction will be printed.
