### ISSUE TITLE
exhaustive feature matching crashes

### ISSUE THREAD

**Issue by alavona** [colmap/colmap#1237]
Hi,
after a successful experience on windows, I am now trying to reconstruct using the command line on linux.
The feature Extraction works just fine, but when it ends and Exhaustive Feature Matching starts this is what I see:

![Capture](https://user-images.githubusercontent.com/86189118/122671901-723e7d00-d1d1-11eb-850c-cf2a3106ed4a.PNG)

and then the last two lines are printed to the screen repeatedly until it exits with the message "core dumped".
has it ever happened to anyone?

thank you

**Comment by alavona** [comment]
it seems like it can't detect CUDA, though I do have a GPU, and CUDA installed.

**Comment by ishipachev** [comment]
Do you build COLMAP from source? Which system do you use?
Do you properly installed CUDA, including adding it to PATH and LD_LIBRARY_PATH  system variables as it is written in the extraction?
May you run in console this command:
**nvidia-smi** 
Does it works? Do you see any output?

**Comment by alavona** [comment]
the problem was that CUDA wasn't properly installed, thank you!
