### ISSUE TITLE
Getting the position of each image using [ Tx,Ty,Tz ] of images.txt

### ISSUE THREAD

**Issue by Helaly96** [colmap/colmap#1238]
![image](https://user-images.githubusercontent.com/30905312/122675418-9d2ccf00-d1d9-11eb-8bd8-21f1ed26e16d.png)
Given the image shown above, i expected the Y values of all images to be almost the same.
i read from alot of issues here that to get the 'real' x,y,z position of an image
you would have to 
**`- tranpose(R) * t`**
so i did the following
After reading the text file of images.txt, i got:
```
from scipy.spatial.transform import Rotation as R
qw= val[1]; qx=val[2]; qy=val[3]; qz=val[4]; x=val[5]; y=val[6]; z=val[7];
r = R.from_quat([qx,qy,qz,qw])
r = r.as_matrix()
r_transpose= -np.transpose(r)
T=  np.matmul(r_transpose,np.array( [[x],[y],[z]] ))
x= T[0]; y=T[1];Z=T[2]
```

but when plotting the Ys of all frames, i ended up with a rising curve that doesnot express the info i wanted (expected)

![image](https://user-images.githubusercontent.com/30905312/122675557-3e1b8a00-d1da-11eb-9263-93383f9c379f.png)

so can you tell me the correct way to get the X,Y,Z location of each image, if i made a mistake?

**Comment by Helaly96** [comment]
![image](https://user-images.githubusercontent.com/30905312/122675828-7e2f3c80-d1db-11eb-92ae-55f99b6dce37.png)
is this the issue? the Y is consistent in their own coordiantes, but compared to the original
it's going down?

**Comment by yuancaimaiyi** [comment]
@Helaly96  Your calculation is correct！！！！！！C= -R.T*tvec

**Comment by ahojnnes** [comment]
The math above looks correct. Closing this as resolved.
