### ISSUE TITLE
COLMAP model aligner not working properly

### ISSUE THREAD

**Issue by andreas-at-talon** [colmap/colmap#1239]
Hello. COLMAP has been working perfectly on old VM but we are trying to install on new VM. Every part from feature extraction to dense reconstruction works perfectly on new VM apart from model aligner. On the old VM we have generated a .ply Point Cloud that is perfect and perfectly alligned. However when I run same script with colmap Linux commands everything works apart from model aligner. I can see this because of comparing final .plys between OLD and NEW VM, seeing the differences is only the orientation and position of the two point clouds. Something weird is happening with colmap model aligner command. I can also see this by comparing the images.bin of the OLD and NEW georefenced directory by looking at the tvec of each image.

Another thing to note is the output of 'colmap aligner' command. On OLD VM when it worked perfectly, output of model aligner looked like this:

Aligning reconstruction
-----------------------
 => Using 86 reference images
 => Alignment succeeded
 => Alignment error: 0.353243 (mean), 0.318907 (median)

However when I run same command on NEW VM we get this:

Aligning reconstruction to principal plane
------------------------------------------
 => Alignment succeeded

This is either a problem of not being able to find georefenced_images.txt, or having an issue reading the .txt file. Even if I take .txt file from OLD VM to NEW VM and run colmap aligner it returns same problem. I know for a fact .txt file is in correct format with no difference in image names, so I am not sure what the problem is, and output of colmap model aligner does not help with any info. Just to make sure, I have even same COLMAP version and commit as old VM and same gcc g++ compilers as well. Any insight into this would be extremely appreciated.

Another note:
Just to test, I made georefenced_images.txt file completely empty, and ran same command, and it produecs same output as NEW VM above which is weird. I have even set .txt file permissions to 0777 so there is no permission error either. 

Thank you.

**Comment by tsattler** [comment]
It seems that the latest version of Colmap introduced different types of alignment (see https://github.com/colmap/colmap/blob/e25479aaced4aef517c109c61e5343ae5126eddf/src/exe/model.cc#L214) and that the default type is aligning the model with the dominant plane. I believe setting the `--alignment_type` flag to `custom` will go to the previous behavior.

**Comment by tsattler** [comment]
The problem should be fixed and I think we can close this issue.
