### ISSUE TITLE
Error in Points3D.txt file

### ISSUE THREAD

**Issue by xianggao1989** [colmap/colmap#124]
Hi,
I am trying to construct the input of the  bundle_adjuster.exe. However, I meet a question when writing the Points3D.txt. In the documentation, you said **the error is given in pixels of reprojection error**. However, one 3D point would get several reprojection errors as it has several visible images. Then what is the **error** exactly defined here? mean, median or root-mean-square error?
Thank you very much!
Best regards,
Xiang Gao from NLPR, CASIA

**Comment by ahojnnes** [comment]
It is the mean error.

**Comment by xianggao1989** [comment]
Thanks for your reply. I am trying to use the bundle_adjuster.exe currently. Only cameras.txt, images.txt and Points3D.txt are enough for --input_path of the bundle_adjuster.exe? I notice that the image folder is not provided when only the above three files are put into the --input_path.

**Comment by ahojnnes** [comment]
There is no need for the images in geometric bundle adjustment, since the reprojection error is minimized.

**Comment by xianggao1989** [comment]
OK, I am trying to give the right input for the bundle_adjuster.exe. Currently the program crashed with my input but probably there are some mistakes in my input. I will check and perhaps ask for your help later. Thanks a lot!

**Comment by xianggao1989** [comment]
Hi, I am trying the model_converter.exe (the latest development version) with the command line: **D:/COLMAP-dev-windows/bin/model_converter.exe --input_path D:/COLMAP-dev-windows/bin/Input --output_path D:/COLMAP-dev-windows/bin/Output --output_type PLY**. The three files (cameras.txt, images.txt and Points3D.txt) have been put into --input_path which are exported from COLMAP. However, the program crashed with error: F0523 time 9000 reconstruction.cc:1223] Check failed: file.is_open()
*** Check failure stack trace: ***. Can you help me with that? Many thanks!

**Comment by ahojnnes** [comment]
Does the output folder exist?

**Comment by xianggao1989** [comment]
Yes

**Comment by ahojnnes** [comment]
For PLY, you need to specify a file path and not the directory path.

**Comment by xianggao1989** [comment]
I have tried and it works. Thanks a lot!
