### ISSUE TITLE
 spatial feature matching based on bundle adjustment results

### ISSUE THREAD

**Issue by noamholz** [colmap/colmap#1242]
I'd like to make use of the spatial feature matching even with no a priory knowledge of the cameras positions.
In cases where the reconstruction does give a reasonable result (based, say, on sequential feature matching), it'd be nice to be able to perform feature matching again, this time using the spatial information retrieved from the 3d reconstruction. This improved matching could then be used to perform an additional 3d reconstruction iteration to refine the results.
Am I making sense? Is this already happening behind the scene?

**Comment by whuaegeanse** [comment]
@noamholz 
There is a paper that uses a similar idea. Please refer to the paper Progressive Large-Scale Structure-from-Motion with Orthogonal MSTs.

But I think that SfM cannot reconstruct a complete model using the result of sequential feature matching. With uncomplete model, spatial  feature matching cannot match all connected images from the model.
For unordered images, it is inevitable to quey similar images during image matching.

**Comment by noamholz** [comment]
Thanks @whuaegeanse for your reply.
Being new to this field, I now see I might have used the wrong terms - In "reconstruction" I should've said "bundle".
So to be clear - I wish to use a **sequential** feature matching, then the bundle, and then use the inferred camera positions to run the **spatial** feature matching (to relax the requirement for images to be chronologically near each other).
I'm that it may prove useful to enhance the sequential matching method this way, but I guess this approach should be experimented with before being integrated in the software...

By the way, to my understanding, the paper you referred me to discusses an iterative approach for feature matching & camera calibration (rather than using position information from the bundle). From its abstract:
> "The outer loop is a feature matching loop, where the orthogonal MSTs (maximum spanning trees) of the image similarity graph is iteratively selected to perform the image matching. The inner loop is an incremental camera calibration loop, where the initial camera poses in each iteration are inherited from those calibrated in the last one."

**Comment by noamholz** [comment]
Thanks for your reply. 
I see that the paper describes a similar approach. I would expect the sequential feature matching would be able to position all the cameras in some cases (=complete model?). In such cases, I'd expect an additional spatial feature matching to allow making a more robust model. I agree that a dataset of unordered images isn't relevant here.
There are my speculation anyway, maybe I should get back to this issue with some first hand evidence.

**Comment by nnop** [comment]
What do you mean by *spatial matching*? Is it to match features guided by triangulated points? @noamholz
