### ISSUE TITLE
install failed on remote headless server

### ISSUE THREAD

**Issue by endeleze** [colmap/colmap#1244]
Hi,

I want to install colmap on a remote server using gcc/g++ 8.4.0, but it shows bug:

[ 39%] Building C object lib/Graclus/CMakeFiles/graclus.dir/metisLib/refine.c.o
In file included from /usr/include/host_config.h:50,
                 from /usr/include/cuda_runtime.h:78,
                 from <command-line>:
/usr/include/crt/host_config.h:121:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!
 #error -- unsupported GNU version! gcc versions later than 6 are not supported!
  ^~~~~
[ 43%] Building C object lib/Graclus/CMakeFiles/graclus.dir/metisLib/timing.c.o
CMake Error at pba_generated_ProgramCU.cu.o.Release.cmake:219 (message):
  Error generating
  /data_2/AnbangYang/Colmap/colmap/build/lib/PBA/CMakeFiles/pba.dir//./pba_generated_ProgramCU.cu.o

lib/PBA/CMakeFiles/pba.dir/build.make:63: recipe for target 'lib/PBA/CMakeFiles/pba.dir/pba_generated_ProgramCU.cu.o' failed
make[2]: *** [lib/PBA/CMakeFiles/pba.dir/pba_generated_ProgramCU.cu.o] Error 1
CMakeFiles/Makefile2:485: recipe for target 'lib/PBA/CMakeFiles/pba.dir/all' failed
make[1]: *** [lib/PBA/CMakeFiles/pba.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMake Error at sift_gpu_generated_ProgramCU.cu.o.Release.cmake:219 (message):
  Error generating
  /data_2/AnbangYang/Colmap/colmap/build/lib/SiftGPU/CMakeFiles/sift_gpu.dir//./sift_gpu_generated_ProgramCU.cu.o

lib/SiftGPU/CMakeFiles/sift_gpu.dir/build.make:63: recipe for target 'lib/SiftGPU/CMakeFiles/sift_gpu.dir/sift_gpu_generated_ProgramCU.cu.o' failed
make[2]: *** [lib/SiftGPU/CMakeFiles/sift_gpu.dir/sift_gpu_generated_ProgramCU.cu.o] Error 1
CMakeFiles/Makefile2:661: recipe for target 'lib/SiftGPU/CMakeFiles/sift_gpu.dir/all' failed
make[1]: *** [lib/SiftGPU/CMakeFiles/sift_gpu.dir/all] Error 2
[ 43%] Linking C static library liblsd.a
[ 43%] Built target lsd
[ 43%] Linking C static library libgraclus.a
[ 43%] Built target graclus
[ 43%] Linking C static library libvlfeat.a
[ 43%] Built target vlfeat
[ 43%] Linking C static library libsqlite3.a
[ 43%] Built target sqlite3
[ 43%] Linking CXX static library libpoisson_recon.a
[ 43%] Built target poisson_recon
[ 43%] Linking CXX static library libflann.a
[ 43%] Built target flann
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

My server is Ubuntu 18.04 with cuda 10.1

How to solve this problem?

Thanks!

**Comment by endeleze** [comment]
Wrong gcc version

**Comment by Eckert-ZJB** [comment]
@endeleze I have the same issue, which gcc version is right?

**Comment by endeleze** [comment]
Hi Eckert, I used gcc 11.2 and it solved my problem.
