### ISSUE TITLE
 point_triangulator work in wrong way

### ISSUE THREAD

**Issue by 891991457** [colmap/colmap#1246]
After feature_extractor and exhaustive_matcher, I write this in cmd:

 colmap  point_triangulator \
    --database_path %PROJECT_PATH%/database.db \
    --image_path %PROJECT_PATH%/images \
    --input_path %PROJECT_PATH%/created/sparse\
    --output_path %PROJECT_PATH%/triangulated/sparse\

The result is:
**

> ==============================================================================
> Loading database
> ==============================================================================
> 
> Loading cameras... 49 in 0.000s
> Loading matches... 1154 in 0.005s
> Loading images... 49 in 0.018s (connected 49)
> Building correspondence graph... in 0.048s (ignored 0)
> 
> Elapsed time: 0.001 [minutes]

**

It's over...???!!!
I can't figure out why  feature_extractor doesn't work in right way. It seems the code just runs for a while and stops for no reason.

Thanks for your help and advice.

**Comment by tsattler** [comment]
If you are running the point_triangulator on a 3D model that already has 3D points, it will not run the triangulation (there might be a corner case where some images do not have 3D points yet and these might lead to new 3D points, but I never tried this). There is a flag `clear_points` that you can use to enforce that the 3D points already in the model are ignored.
In general, I recommend having a look at the code when having questions about what is happening. Here is the code for the point_triangulator: https://github.com/colmap/colmap/blob/9f3a75ae9c72188244f2403eb085e51ecf4397a8/src/exe/sfm.cc#L339

**Comment by 891991457** [comment]
> If you are running the point_triangulator on a 3D model that already has 3D points, it will not run the triangulation (there might be a corner case where some images do not have 3D points yet and these might lead to new 3D points, but I never tried this). There is a flag `clear_points` that you can use to enforce that the 3D points already in the model are ignored.
> In general, I recommend having a look at the code when having questions about what is happening. Here is the code for the point_triangulator:
> 
> https://github.com/colmap/colmap/blob/9f3a75ae9c72188244f2403eb085e51ecf4397a8/src/exe/sfm.cc#L339

Thanks for your reply. Maybe I should explain the problem more clear.
I prepare 3 text files as cameras.txt , images.txt, points.txt(empty) and a folder with images.
here is the link:  https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses


After running  feature_extractor and exhaustive_matcher ,I try to run point_triangulator. It  stops after loading database. I check the  code and can't find the reason. But if I run mapper, it exports the result  successfully.

Look forward to your reply.

**Comment by tsattler** [comment]
How does the images.txt file look like?

**Comment by 891991457** [comment]
@tsattler 

Hi, here is  part of the images.txt file
```
1 0.9924258814942094 -0.014906506293475303 0.12180856814853899 -0.0055980832583147466 -191.02 3.28832 22.5401  1 00000000.jpg

2 0.9491866126874576 -0.013137553782149695 0.21606940911704742 0.22844296754188143 -291.419 -77.0495 71.2762  1 00000001.jpg

3 0.8435936081532562 -0.00984655118224845 0.29664072428255367 0.4475010060434586 -334.56 -194.157 129.344  1 00000002.jpg

4 0.682147866362529 -0.005419750831672799 0.3579919895230572 0.637563055826869 -309.024 -318.429 181.594  1 00000003.jpg

5 0.4762943225240641 -0.00038690040873116374 0.3947547603658654 0.7856922093338483 -220.056 -417.088 213.217  1 00000004.jpg
```

I'm confused that if there is some mistake in my data , I can't run mapper or  point_triangulator successfully. But it just meets some trouble when running point_triangulator.

Thanks for your attention!

**Comment by tsattler** [comment]
What is the full output on the console? Any errors?

**Comment by 891991457** [comment]
![11](https://user-images.githubusercontent.com/62783303/123961085-9294e580-d9e2-11eb-814f-4ee744a16f98.png)

@tsattler 
Here is the .bat file and the result in console. The code stops without any error.
Look forward to your reply.

**Comment by tsattler** [comment]
Have you tried using a more recent version of Colmap?

**Comment by Saixiaoma** [comment]
> ![11](https://user-images.githubusercontent.com/62783303/123961085-9294e580-d9e2-11eb-814f-4ee744a16f98.png)
> 您这个问题解决了吗？
> @tsattler
> Here is the .bat file and the result in console. The code stops without any error.
> Look forward to your reply.



> ![11](https://user-images.githubusercontent.com/62783303/123961085-9294e580-d9e2-11eb-814f-4ee744a16f98.png)
> 
> @tsattler
> Here is the .bat file and the result in console. The code stops without any error.
> Look forward to your reply.

您这会问题解决了吗？

**Comment by harveyyang66** [comment]
> > ![11](https://user-images.githubusercontent.com/62783303/123961085-9294e580-d9e2-11eb-814f-4ee744a16f98.png)
> > 您这个问题解决了吗？
> > @tsattler
> > Here is the .bat file and the result in console. The code stops without any error.
> > Look forward to your reply.
> 
> > ![11](https://user-images.githubusercontent.com/62783303/123961085-9294e580-d9e2-11eb-814f-4ee744a16f98.png)
> > @tsattler
> > Here is the .bat file and the result in console. The code stops without any error.
> > Look forward to your reply.
> 
> 您这会问题解决了吗？

Hi @Saixiaoma , 我也遇到了同样的问题，请问您现在解决了吗？
