### ISSUE TITLE
Reconstruction from known extrinsics (cam rotation + translation)

### ISSUE THREAD

**Issue by mokrueger** [colmap/colmap#1248]
Hi everyone, 

I am currently struggling to implement a pipeline that uses known camera poses (extrinsics) from an AR Application.

Firstly I extract the features and match them using the
feature_extractor and
exhaustive_matcher

Then I create the images.txt, blank points3D.txt and copy the camera.txt (intrinsics) from what the feature_extractor created in the db. I am guessing thats what the problem is.

I have decent matches in the images:
![grafik](https://user-images.githubusercontent.com/59337243/124359258-73859600-dc24-11eb-8fdd-205be66ca8fb.png)

And the camera poses visualized make a lot of sense (after adjusting the rendering):
![grafik](https://user-images.githubusercontent.com/59337243/124359292-99ab3600-dc24-11eb-94f2-e7f65e179bff.png)

However I don't get any triangulation results using the point triangulator:

> ==============================================================================
Triangulating image #1 (0)
==============================================================================

>    => Image sees 0 / 567 points
>    => Triangulated 242 points

> ==============================================================================
Triangulating image #2 (1)
==============================================================================

>  => Image sees 0 / 704 points
>  => Triangulated 0 points

>  ==============================================================================
Triangulating image #3 (2)
==============================================================================

>    => Image sees 4 / 56 points
>    => Triangulated 5 points

>  ==============================================================================
Triangulating image #4 (3)
==============================================================================

>    => Image sees 282 / 637 points
>    => Triangulated 26 points

>  ==============================================================================
Triangulating image #5 (4)
==============================================================================

>    => Image sees 115 / 299 points
>    => Triangulated 1 points

>  ==============================================================================
Triangulating image #6 (5)
==============================================================================

 >   => Image sees 265 / 525 points
 >   => Triangulated 1 points

>  ==============================================================================
Triangulating image #7 (6)
==============================================================================

 >   => Image sees 1 / 50 points
 >   => Triangulated 0 points

>  ==============================================================================
Triangulating image #8 (7)
==============================================================================

>    => Image sees 5 / 76 points
>    => Triangulated 0 points

>  ==============================================================================
Triangulating image #9 (8)
==============================================================================

>    => Image sees 0 / 17 points
>    => Triangulated 0 points

>  ==============================================================================
Triangulating image #10 (9)
==============================================================================

>    => Image sees 0 / 0 points
>    => Triangulated 0 points

>  ==============================================================================
Triangulating image #11 (10)
==============================================================================

>    => Image sees 1 / 16 points
>    => Triangulated 0 points

>  ==============================================================================
Triangulating image #12 (11)
==============================================================================

>    => Image sees 0 / 38 points
>    => Triangulated 0 points

>  ==============================================================================
Retriangulation
==============================================================================

>    => Completed observations: 0
>    => Merged observations: 0

I am guessing thats due to the automatically created intrinsics (from the feature_extractor) that I just copy.
Loading the manually created sparse model without adjusting the rendering looks like this:

![grafik](https://user-images.githubusercontent.com/59337243/124359486-96fd1080-dc25-11eb-8c23-bf714df75853.png)

So i am guessing the extrinsics and intrinsics don't match in scale which results in the problem (could this be correct?)

Is there a way i can fix the intrinsics or manually create them properly?
Or am I doing something else wrong.
Or generally speaking, how can I use the extrinsic poses to get a 3d model.

(This is an attemt to use the known camera positions and rotations to get a more 'robust' result)

**Comment by tsattler** [comment]
In order to work, the `point_triangulator` needs rather precise estimates for the camera extrinsics and intrinsics. Can you get the intrinsics from the method you are using to obtain the poses? Or can you calibrate the camera?

Yes, you can fix the intrinsics (by specifying them either before feature extraction or by modifying the intrinsics in the database, e.g., using the gui).

Using known extrinsics to get a 3D model is described in the colmap documentation and there is an issue on this github (I don't remember whether it is still open or closed) that explains how to refine the camera poses and intrinsics starting from a 3D model.

**Comment by mokrueger** [comment]
Hi,
Thanks for your answer.
I think I'll also look into the camera calibration. 


Do you have a link to that mentioned documentation?
I searched quite a lot but only found issues that used extrinsics and intrinsic information. 
I'm trying only to only use position and rotation info (for now) to get a better model. (basically the images.txt) 
I didn't find anything in the documentation yet. 

I'd be happy if you could help :) 

Kind regards

**Comment by tsattler** [comment]
This is the documentation I was referring to: https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses

For this to work, you need to know the camera intrinsics well enough.

**Comment by mokrueger** [comment]
Ah okay. 
That means it's not possible (yet) to use COLMAP with only the extrinsics, right?

**Comment by ahojnnes** [comment]
You need reasonably accurate intrinsics and extrinsics for it to work. There are no plans and also no easy solutions to make it work when either of them are missing. You should consider running SfM from scratch instead in this case.

**Comment by mokrueger** [comment]
Okay, perfect.
Thanks again for your clarification.
