### ISSUE TITLE
Bad quality model got after applying bundle adjust to merged model

### ISSUE THREAD

**Issue by is03wlei** [colmap/colmap#125]
I have two models which have 10 common registered images.
Model 2(336 images, 85129 points):
![model-2](https://cloud.githubusercontent.com/assets/4695442/26442949/29346068-4169-11e7-8082-60bcbf670984.png)

Model 47(38 images, 8360 points):
![model-47](https://cloud.githubusercontent.com/assets/4695442/26443063/84df0968-4169-11e7-9f3d-6838cae589c1.png)

After running "model_merger --input_path1 ./2 --input_path2 ./47 --output_path ./2-47", I got model 2-47(364 images, 91470 points):
![2-47](https://cloud.githubusercontent.com/assets/4695442/26443202/fee76e76-4169-11e7-911b-bafc118bd80b.png)

Then I ran "bundle_adjuster --input_path ./2-47/ --output_path ./refined-2-47/", got refined model(364 images, 90060 points):
![refined-2-47](https://cloud.githubusercontent.com/assets/4695442/26443312/641cd51a-416a-11e7-89a8-16d44279ac79.png)

Why does the refined model contain so many noisy points?

**Comment by ahojnnes** [comment]
It seems like the larger model is not reconstructed well. The estimated focal lengths between the two models seem totally different? Do you have calibration parameters for the camera that you can use to initialize the reconstruction?

**Comment by is03wlei** [comment]
All the images are taken from my iphone7. 
Referenced from this page:https://9to5mac.com/2016/09/12/iphone-7-plus-sensor-size/,
I passed 4/7.21 to --ImageReader.default_focal_length_factor. Why did you say the larger model is not reconstructed well. I want to verify it by dense points cloud. But dense_fuser generated point-cloud.ply with 0 points.

But in another way, 35mm equivalent focal length is 28mm for iphone7. So focal_length_factor should be 28/35 which is totally different from 4/7.21. I also experimented for 28/35.  It seems the reconstruction is well. And dense_fuser generated good result. See following picture.
![software_park](https://cloud.githubusercontent.com/assets/4695442/26503034/bd6f2d72-4271-11e7-8f82-eae81e98d905.png)

I have calibration parameters but I didn't use them in above reconstructions.
<image_Width>4032</image_Width>
<image_Height>3024</image_Height>
<board_Width>9</board_Width>
<board_Height>6</board_Height>
<square_Size>50.</square_Size>
<FixAspectRatio>1.</FixAspectRatio>

<flagValue>14</flagValue>
<Camera_Matrix type_id="opencv-matrix">
  <rows>3</rows>
  <cols>3</cols>
  <dt>d</dt>
  <data>
    3.3118580162250869e+03 0. 2.0155000000000000e+03 0.
    3.3118580162250869e+03 1.5115000000000000e+03 0. 0. 1.</data></Camera_Matrix>

No matter I use 28/35 or 4/7.21, the reconstruction seems well.
Which focal_length_factor should I use?

**Comment by ahojnnes** [comment]
28/35 would be the correct value. Since the reconstruction works in both cases, it seems that COLMAP can successfully self-calibrate the images in your dataset. Let me know if you have other questions. I'll close this issue as resolved for now, but feel free to reopen. Thanks.
