### ISSUE TITLE
Can't specify parameter num_threads for dense_mesher

### ISSUE THREAD

**Issue by is03wlei** [colmap/colmap#126]
Running command "dense_mesher --input_path ./dense/point-cloud.ply --output_path ./dense/mesh-trim-12.ply --DenseMeshing.trim 12 --DenseMeshing.num_threads 20"

Output:
invalid option: --num_threads
possible options are:
  in
  degree
  depth
  out
  xForm
  scale
  verbose
  cgAccuracy
  noComments
  double
  kernelDepth
  samplesPerNode
  confidence
  nWeights
  nonManifold
  polygonMesh
  ascii
  showResidual
  voxelDepth
  pointWeight
  voxel
  threads
  maxSolveDepth
  adaptiveExp
  dirichlet
  density
  fullDepth
  minDepth
  cgDepth
  iters
  complete
  color
  linearFit
  primalVoxel
invalid option: 20
  options must start with a '--'

But the program didn't exit.

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
  777 xxx  20   0 1964576 358712   9248 R  1873  0.1  87:21.72 dense_+

**Comment by ahojnnes** [comment]
Thanks, this should be fixed with the latest commit.
