### ISSUE TITLE
Using known camera poses for reconstruction

### ISSUE THREAD

**Issue by y-zheng18** [colmap/colmap#1260]
If part of  (not all) the images is provided with known camera poses, how can I use those pose information for reconstruction? for example, which command line should I use to import those camera poses and run reconstruction? It seems --point_triangulator
 needs all the camera poses.

**Comment by tsattler** [comment]
You can use the `point_triangulator` to build a model for those images for which you know the intrinsics and extrinsics and then use the resulting model as input to the `mapper` to continue the reconstruction process.

**Comment by y-zheng18** [comment]
Thanks! But using mapper to continue the reconstruction can change the known camera parameters since global bundle adjustment can influence those camera poses. How can I fix the models and camera poses when using mapper to continue the reconstruction?

**Comment by tsattler** [comment]
There is a parameter for the mapper where you can fix the existing camera poses.

**Comment by y-zheng18** [comment]
Thanks a lot. But when I use command **_colmap mapper --database_path xxx --image_path xxx --output_path xxx --input_path xxx --Mapper.fix_existing_images 1_**, the reconstruction camera rotation remains fixed but translation changed. Did I miss something?

**Comment by Jentuuh** [comment]
I have the same issue, my rotations remain fixed but my translations keep being updated. Does this happen due to the bundle adjustment? Is there a way to keep both the translation and rotation fixed for the existing camera poses?

**Comment by lkskstlr** [comment]
@y-zheng18, @Jentuuh this could be due to normalization, see here: https://github.com/colmap/colmap/issues/664#issuecomment-526578328

**Comment by xuxumiao777** [comment]
> @y-zheng18, @Jentuuh this could be due to normalization, see here: [#664 (comment)](https://github.com/colmap/colmap/issues/664#issuecomment-526578328)
@lkskstlr @tsattler @Jentuuh @y-zheng18 
Have you found a solution to keep both the translation and rotation fixed?
