### ISSUE TITLE
Difference in rotation matrix in *.txt export vs. bundler export

### ISSUE THREAD

**Issue by tudipffmgt** [colmap/colmap#1262]
I noticed a strange behaviour when exporting camera positions and orientations in .txt files.
I wanted to share the poses of my reconstruction with a colleague but after calculating and plotting the camera positions and directions in MatLab the direction was wrong.
I exported a model in .txt file and picked one image:
`IMAGE_ID, QW, QX, QY, QZ, TX, TY, TZ, CAMERA_ID, NAME
19 0.996775 -0.0783083 -0.0174556 0.00165122 -0.820392 -0.746655 -0.6239 19 1.jpg`

I calculated the rotation matrix and the projection center using the provided EIGEN functions and retrieved:
```
ID 
R 
T
1.jpg  
0.999385 -0.000557953   -0.0350572
0.00602563      0.98773     0.156054
0.03454    -0.156169     0.987126  
-0.845936 0.639602 0.703626`
```
I did the same in Matlab with my own function for retrieving the rotation matrix from quaternions and got the same result.
Plotting the camera showed me that it was pointing in the wrong direction so I tried the bundler export and there the rotation matrix is given as:
```
0.999385 -0.000557953 -0.0350572
-0.00602563 -0.98773 -0.156054
-0.03454 0.156169 -0.987126
```
I am very confused why the signs are switched only in the second and third line but when I plotted this I retrieved the correct solution.
Why is the bundler rotation matrix different from the Eigen solution and where could be the error?

**Comment by tsattler** [comment]
You get the difference because Bundler uses a different local camera coordinate system than Colmap, see 
* https://github.com/colmap/colmap/blob/513fef3e39f99b50279bf5aee1c5b597cba53c3b/src/base/reconstruction.cc#L1133
* https://github.com/snavely/bundler_sfm#output-format
* https://colmap.github.io/format.html#images-txt
