### ISSUE TITLE
Where are the executables on Mac?

### ISSUE THREAD

**Issue by APCoding** [colmap/colmap#128]
Hi! I love the software, thanks for sharing it! I have a dumb question: where can I find the executables for the command line on Mac? The src folder doesn't exist, but that's where the documentation says to look for it. Should I just create one and reinstall? Or are they somewhere else? Thanks!

**Comment by ahojnnes** [comment]
If you followed the installation instructions here: https://colmap.github.io/install.html
1) You can find them in the build/src/exe folder
2) If you downloaded the pre-built binaries, only the GUI app is included. For the command-line version, you have to build the library manually and see 1)
