### ISSUE TITLE
Point cloud contains feature coordinates and descriptors

### ISSUE THREAD

**Issue by zhoux121** [colmap/colmap#1285]
Hi,
When colmap generated a point cloud, how to have the corresponding descriptors with the point cloud coordinates?
Thanks

**Comment by tsattler** [comment]
You can get the 3D point positions from the `images.txt` / `images.bin` file. For each 3D point, the file stores a track, which consists of `image_id`, `point2d_idx` pairs (see https://colmap.github.io/format.html). Each pair corresponds to an image and a feature extracted from the image that were used to generate the point. You can then load the corresponding descriptors from the database.

**Comment by zhoux121** [comment]
The problem is solved. Thanks!

**Comment by zhoux121** [comment]
> You can get the 3D point positions from the `images.txt` / `images.bin` file. For each 3D point, the file stores a track, which consists of `image_id,` `point2d_idx` pairs (see https://colmap.github.io/format.html). Each pair corresponds to an image and a feature extracted from the image that were used to generate the point. You can then load the corresponding descriptors from the database.

https://github.com/colmap/colmap/issues/1285#issuecomment-908635844


Hi, 
Sorry for open the issues again. after tracking from image.txt with point3D_ids, I can find relate 3Dpoints information in points3D.txt. I can find image_ids in the database.db, but I am not sure where is the location of point2D_idxs.  Also, without considering the point2Didxs, I am not sure the keypoint data format, the length of the data col is over 10000+ in my case. 
![Screenshot from 2021-09-04 11-50-13](https://user-images.githubusercontent.com/21269237/132100890-1ed927a3-7c9a-43a1-9a3e-28fa1fec8b88.png)

I checked the documents "If the keypoints have 6 columns, then the feature geometry is an affinity, and the last 4 columns encode its affine shape."  what is this meaning? If I need the keypoints and the descriptor format to be the regular SIFT format, how should I do or find them? 
Thank you so much.

**Comment by tsattler** [comment]
point2D_idxs are 0-based indices into the list of keypoints stored for an image in the database, i.e., a point2D_idx of 10 means the 11-th feature for that image.

Affinity means that the feature geometry is described by an affine transformation. You can check the source file mentioned in the part of the tutorial you quoted for code on how to convert from an affine shape to the standard SIFT feature geometry.

**Comment by zhoux121** [comment]
Hi,
Thank you for your kind reply.
For example, from points3D.txt "image_ids=array([749, 860]), point2D_idxs=array([335, 116])" 
track image_ids[749] in image.txt, the xys array is related to point2D_idxs.

refer to the code(src/feature/types.h)

My next step is to convert the affine shape to SIFT, as you mentioned above. 
![Screenshot from 2021-09-07 16-44-59](https://user-images.githubusercontent.com/21269237/132408516-db0d16d1-9eb7-48a7-8e7c-050cd2f8b275.png)
If x,y represents the point from points2D_indx, the scale_x and scale_y can be set as the image scale (example 1080x1920). What are the orientation and shear represent? The database. db keypoint "data" is the parameter of the orientation? What about the shear?
![Screenshot from 2021-09-07 16-49-58](https://user-images.githubusercontent.com/21269237/132409060-6410b6dd-1712-4d1a-9e99-e93d35b81896.png)

I'm still a little confused...
Thanks for your help, I am very appreciative!
