### ISSUE TITLE
Inquiries about Colmap Multiprocessing 

### ISSUE THREAD

**Issue by KyuminHwang** [colmap/colmap#1288]
First of all, thank you for sharing this wonderful research.

I am trying to get the depth map result of Colmap using DeMoN Dataset.
However, since the number of datasets is large, I am trying to run the colmap at the same time by creating multiple input batches with python multiprocessing. 
`(os.system(colmap automatic_reconstructor)).`

However, when I run it, the operation not released gpu resources after finished when several colmaps are running at the same time. Only one colmap should be used to restart after release.

**Is it possible to run multiple colmap at the same time?**

**If there is a way to download the results of DeMoN Dataset with colmap or an efficient way to process large datasets, please introduce them.**

And I want to get the **"Filtered" depth map** in Fig.3 of the paper **"Pixelwise View Selection for Unstructured Multi-View Stereo"** do you know how?
```
$colmap patch_match_stereo\
    --workspace_path $DATASET_PATH/dense \
    --workspace_format COLMAP\
    --PatchMatchStereo.geom_consistency true
    --PatchMatchStereo.filter true
```
Even if the option is given as above, the filtered depth map is not created.

**Comment by tsattler** [comment]
Did you contact the authors of DeMoN regarding the dataset? They are the ones to ask.

You can run multiple Colmap instances at the same time (I regularly do this from the command line). Note that these instances will be competing for resources though.

**Comment by KyuminHwang** [comment]
@tsattler Thank you for your comment.

i solved this problem through individual command (https://colmap.github.io/cli.html).
If you use the command for each step as os.system , you can use it with python's multiprocesssing (apply_async).
