### ISSUE TITLE
Points appear in points3D.txt can't be found from images.txt

### ISSUE THREAD

**Issue by is03wlei** [colmap/colmap#129]
This is one line from points3D.txt:
412488 0.129821 -1.77618 0.350493 17 27 14 1.01081 3770 10589 3785 10128 3769 9577 3784 10928 3768 7923 3767 7890 3766 3514 3765 8416 3764 3515 3786 6871 3787 7842 3793 6252 3785 3456 3784 3256 3783 3374 3782 3291 3781 7257 3780 3442 3776 3444 3777 3412 3774 3344 3773 3662 3771 3509 3763 3365 3761 3356 3759 3751 3758 3495 3756 3646 3752 3578 3751 3721 3753 3439 3749 3478 3748 3732 3750 3426 3747 3454 3743 3712 3741 3444 3739 3467 3740 3676 3738 3432 3742 3345 3737 3742 3731 3556 3729 3671 3728 3451 3727 3464 3726 8037 3724 7598 3723 7697 3722 7055 3719 3420 3718 3681 3715 3806 3713 3447 3714 3333 3712 3741 3710 3490 3709 7595 3708 3410 3705 3394 3702 3559 3704 3776 3700 3383 3699 3589 3697 3353 3695 7087 3694 3597 3692 7152 3690 7403 3686 3466 3691 2714 3675 7398 3677 7203 3674 3387 3672 3729 3671 3422 3669 7810 3666 7389 3665 3515 3664 2521 3660 7667 3653 3929 3657 3993

It contains image id 3345.

But I couldn't find point id 412488 in the line starts with 3345 from images.txt.
Does it make sense or some points are omitted due to parameter limits?

**Comment by ahojnnes** [comment]
As documented here https://colmap.github.io/format.html, the ``image_id`` is unordered and not contiguous. Instead of looking at line 3345 in ``images.txt``, you would have to find the line that has that specific ``image_id``. Please, refer to the documentation for more details. Also, there are example scripts for loading the data in Python and Matlab in the ``scripts`` folder.

**Comment by is03wlei** [comment]
Sorry, there was something wrong with my previous description.
I did search the line following 3345 but couldn't find it.

I reconstruct the contents as follows(-1 for point3D_id removed): 
key_id point3D_id
3439 573301
3440 573302
3502 573082
3526 573119
3533 573306
3534 573307
3535 573303
3536 575596
3539 573305
3549 573178
3562 573179
3566 573345
3574 573346
3577 572939
3584 573347
3590 573309
3593 572944
3603 572936
3608 573348
3609 573421
3611 573310
3612 572947
3613 572937
3618 572991
3627 572948
3660 572942
3680 573085
3681 573086
3692 573092
3693 573093
6002 572935
6023 572994
6029 572932
6031 573120
6035 572995
6056 573422
6078 573325
6079 573354
7535 573025
7536 573331
7558 573217
8583 573149
8584 573150
8588 573165
8589 573166
8600 573143
8610 573041
9707 573154
9712 573155
9724 573059
9977 573228
9984 573158
9985 573229

**Comment by ahojnnes** [comment]
Can you please share the entire files?

**Comment by is03wlei** [comment]
[3344_3345.txt](https://github.com/colmap/colmap/files/1040660/3344_3345.txt)
[top10_images.txt](https://github.com/colmap/colmap/files/1040665/top10_images.txt)

**Comment by ahojnnes** [comment]
You are accessing the lists in the ``points3D.txt`` incorrectly. 3345 is not referring to an image but it is the ``point2D_idx``. You are accessing the list by an incorrect shift of 1.
