### ISSUE TITLE
Question for how to convert affine shape to SIFT

### ISSUE THREAD

**Issue by zhoux121** [colmap/colmap#1295]
Hi,
Tracking from the database and do the reshape.
![image](https://user-images.githubusercontent.com/21269237/132997750-d5693574-866e-44d0-a756-3018f2633399.png)
"data" is from the descriptor database, and "keypoint" is from the keypoint database. After we reshaped the "data and keypoints,"  each keypoints corresponding to four affine shapes.  I read the document and the src/feature/type.h, but I am still confused about converting the affine shape to SIFT. can somebody help me out? 
Thank you so much

**Comment by tsattler** [comment]
Each keypoint has 6 parameters (2 coordinates and 4 parameters defining the rest of an affine transformation). Code to convert to the standard SIFT coordinate frame (2 coordinates, 1 scale, 1 orientation) is provided here: https://github.com/colmap/colmap/blob/dev/src/feature/types.cc

**Comment by zhoux121** [comment]
Hi,
I understand there is a 6 parameter for each keypoint, for example [x, y , a11,a12,a21,a22]
But there is a problem that confused me for a while. When I reshape the keypoint and descriptor from the database, the length of the keypoint and descriptor list is different.
In my case, the descriptor from the database after reshaping by 128, the length is 363. The keypoint from the database after reshaping by 6, the size is 1452. which means the keypoint is four times the descriptor.

**Comment by tsattler** [comment]
Are you using float instead of uint8 when extracting the descriptors? That might explain the factor 4 difference.

**Comment by zhoux121** [comment]
I use automatic reconstruction to generate the point cloud from images.  Is there an option to select the extract mode?  I checked the Processing -> Feature extraction, and I didn’t see an option to choose float or uin8. Did I miss it somewhere? Would you mind pointing out its location?
Thank you

**Comment by tsattler** [comment]
I meant when you were extracting the descriptors from the database. The features are stored as uint8 in the database. If you load features as float, then this could explain the factor 4 difference.

Please have a look at the data loading functionality provided by Colmap (c++ and python).

**Comment by zhoux121** [comment]
I see, I forgot the keypoint are storage by float36, thanks for point out. 
Thank you
