### ISSUE TITLE
command-line for sparse reconstruction

### ISSUE THREAD

**Issue by YanhaoZhang** [colmap/colmap#1296]
Hi, thanks a lot for this SOTA SfM and MVS project. I am trying to understand the basic blocks of the SfM and MVS. May I know what's the command-line or the 'main function' for sparse reconstruction, after the feature extraction and matching? Now, I have save the feature, and the matching results `database.db`. When using GUI, I know the next step is reconstruction. I am wondering what is the command-line for this? Thx.

**Comment by tsattler** [comment]
Did you had a look at https://colmap.github.io/cli.html ?

**Comment by YanhaoZhang** [comment]
Thanks for your prompt reply! Really appreciate this. Now I know this.
