### ISSUE TITLE
How to set rig bundle adjuster for 3 cameras

### ISSUE THREAD

**Issue by vinayver198** [colmap/colmap#1297]
Hi,
I am facing this issue 
F0916 12:05:43.673682 10028 camera_rig.cc:81] Check failed: image_ids.size() <= NumCameras() (14 vs. 3) 

colmap rig_bundle_adjuster --input_path sparse/0/ --output_path rig/ --rig_config_path camera_rig.json

In sparse/0/ , i have points cameras and images in txt format. 

Any idea , what this issue is all about .

**Comment by ahojnnes** [comment]
You have specified more images for a single snapshot/rig exposure than there are cameras defined in the calibration/config.

**Comment by vinayver198** [comment]
Hi , this how my set up looks like, 3 cameras and each camera having 200 images .

[
	{
		"ref_camera_id": 1,
		"cameras":
		[
			{
				"camera_id": 1,
				"image_prefix": "cam1/",
				"rel_tvec": [0, 0.2, 0.5],
				"rel_qvec": [0.9998477,0,-0.01745241,0]
			},
			{
				"camera_id": 2,
				"image_prefix": "cam2/",
				"rel_tvec": [0.5, 0.2, 0.5],
				"rel_qvec": [ 0.98480775,0,0, -0.17364818]
			},
			{
				"camera_id": 3,
				"image_prefix": "cam3/",
				"rel_tvec": [-0.5, 0.2, 0.5],
				"rel_qvec": [0.98480775, 0, 0, 0.17364818]
			}
		]
	}
]

Any suggestions on this setup
