### ISSUE TITLE
ColMap wants qt5 but brew installs Qt6 by default

### ISSUE THREAD

**Issue by wealthychef1** [colmap/colmap#1299]
**Describe the bug**
ColMap builds successfully on OS X Big Sur.  However, it fails to find QT because brew uses qt6 by default. 

Error:  
```
rcook@Richs-Macbook (build (dev)): colmap gui
ERROR: Cannot start colmap GUI; colmap was built without GUI support or QT dependency is missing.

```

During build:
```
CMake Warning at CMakeLists.txt:119 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" (requested
  version 5.4) with any of the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
```
The solution is to tell brew to install Qt5.  See below. 

**To Reproduce**
Build colmap on Mac OS following the instructions at https://colmap.github.io/install.html:  
```
brew install 
    git \
    cmake \
    boost \
    eigen \
    freeimage \
    glog \
    gflags \
    suite-sparse \
    ceres-solver \
    qt \
    glew \
    cgal

git clone https://github.com/colmap/colmap.git
cd colmap
git checkout dev
mkdir build
cd build
cmake .. -DQt5_DIR=/usr/local/opt/qt/lib/cmake/Qt5
make
sudo make install
```

**Expected behavior**
Should launch gui

**Screenshots**
Not needed.

**Desktop (please complete the following information):**
 - OS: Mac OS X Big Sur 11.6, with XQuartz
 - Browser [e.g. chrome, safari] :safari

**Additional context**
SOLUTION
To tell brew to use qt5: 
```

rcook@Richs-Macbook (build (dev)): brew install qt5
==> Downloading https://ghcr.io/v2/homebrew/core/qt/5/manifests/5.15.2-1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/qt/5/blobs/sha256:a11186f808f81ccae91a1b79d14a1014428
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:a11186f808f81ccae
######################################################################## 100.0%
==> Pouring qt@5--5.15.2.big_sur.bottle.1.tar.gz
==> Caveats
We agreed to the Qt open source license for you.
If this is unacceptable you should uninstall.

qt@5 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have qt@5 first in your PATH, run:
  echo 'export PATH="/usr/local/opt/qt@5/bin:$PATH"' >> ~/.profile

For compilers to find qt@5 you may need to set:
  export LDFLAGS="-L/usr/local/opt/qt@5/lib"
  export CPPFLAGS="-I/usr/local/opt/qt@5/include"

For pkg-config to find qt@5 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/qt@5/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/qt@5/5.15.2: 10,688 files, 366.5MB
```

If you already installed qt, you need to unlink it and ink qt5 for the build:
```
brew unlink qt
brew link qt5
```

And then it's (NOTE THE CHANGE TO qt5 path)
``` 
rcook@Richs-Macbook (build (dev)): cmake .. -DQt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5
...
-- Found Qt
--   Module : /usr/local/opt/qt5/lib/cmake/Qt5Core
--   Module : /usr/local/opt/qt5/lib/cmake/Qt5OpenGL
--   Module : /usr/local/opt/qt5/lib/cmake/Qt5Widgets
-- Found CGAL
... 

rcook@Richs-Macbook (build (dev)): make
rcook@Richs-Macbook (build (dev)): sudo make install
rcook@Richs-Macbook (build (dev)): colmap gui # runs fine now (I think, I have not yet had a chance to test it, LOL)

```

**Comment by wealthychef1** [comment]
I feel like the right thing is to build against a newer Qt but if that's not possible then provide instructions for having both Qt5 and Qt6 installed under Brew.  Temporarily unlinking Qt6 was a workaround for me but might be not good for others...

**Comment by wealthychef1** [comment]
Oh and of course the build instructions should be updated.  :-). Cheers

**Comment by ahojnnes** [comment]
The latest commit in master has some new notes in the documentation about the issue. Unfortunately, I don't have time or access to mac at the moment to look into making COLMAP compatible with Qt6. Thanks for your help.

**Comment by wealthychef1** [comment]
I'm imagining that Qt6 compatibility is a huge port anyhow and probably not worth it.  I actually think that temporarily unlinking and then relinking would be a solution for most if not all people.  Have a nice day!

**Comment by datasith** [comment]
Hey @wealthychef1 and @ahojnnes, any chance we can make a note of this in the [installation docs](https://colmap.github.io/install.html#pre-built-binaries)? Changing the `brew install` command to explicitly go for `qt5` (instead of `qt`) does the trick. Thanks so much for all your efforts!

**Comment by algology** [comment]
Is this qt5 workaround still required? Has qt6 been implemented into COLMAP yet?

**Comment by zhouzq-thu** [comment]
@algology #3597 support both Qt5 and Qt6.
