### ISSUE TITLE
Reconstruction crashes on Windows (V1.1)

### ISSUE THREAD

**Issue by bjornpiltz** [colmap/colmap#13]
> F0608 10:43:16.701477 20040 local_parameterization.cc:104] Check failed: constant_parameters.size() < size (3 vs. 3) Number of parameters held constant should be less than the size of the parameter block. If you wish to hold the entire parameter block constant, then a efficient way is to directly mark it as constant instead of using a LocalParameterization to do so.
> *** Check failure stack trace: ***

**Comment by ahojnnes** [comment]
Could you provide some more details on the kind of matching etc.? In theory, the matching should not make use of Ceres-Solver, which is where this check comes from.

**Comment by bjornpiltz** [comment]
My bad, I meant *reconstruction*. Apparently RefineAbsolutePose() sets all 3 camera parameters as const(I am using SIMPLE_PINHOLE model).

**Comment by ahojnnes** [comment]
Thanks, would you be able to share the database file for debugging purposes?

**Comment by ahojnnes** [comment]
@bjornpiltz Thanks for the bug report! This is fixed in https://github.com/colmap/colmap/commit/5546ab0d95352d1db6806671ecc4d3b95dd349c8
