### ISSUE TITLE
Colmap crashed when starting reconstruction

### ISSUE THREAD

**Issue by xianggao1989** [colmap/colmap#130]
The features and matches are given according to the colmap documentation and I am quite sure they are organized properly. The binary code I use is the latest development version. However, the program crashed when starting reconstruction with the error: **Unhandled exception at 0x000007FEE3952270 (Qt5Gui.dll) in colmap.exe: 0xC0000005: Access violation reading location 0x0000000000000000.**
Can you help me with that?
Thanks a lot!
Xiang Gao from NLPR, CASIA

**Comment by ahojnnes** [comment]
I need more information than what you provide. Did you import your own features and matches? Can you provide the data?

**Comment by xianggao1989** [comment]
Yes, I imported mine and generated the .db file. How can I provide you the data?

**Comment by ahojnnes** [comment]
Email with link?

**Comment by xianggao1989** [comment]
I sent my data.db to your E-mail (jsch@inf.ethz.ch). The file is large (about 150MB). I am not sure you can download it. Thanks!

**Comment by xianggao1989** [comment]
Note that only inlier matches are provided.

**Comment by xianggao1989** [comment]
What is more, I do not think the crash happens because of my input. As sometimes the crash happens just after I open the colmap.exe. The error seems related to Qt as shown above.

**Comment by xianggao1989** [comment]
I tried another PC with the same input and the same colmap binary code and it works well...

**Comment by xianggao1989** [comment]
I restarted my PC and the program works well now (the same input and binary code)... Can you help me to deal with that? Thanks!

**Comment by ahojnnes** [comment]
Thanks for reporting this and for sharing the data. There was a bug in the rendering pipeline that should be fixed now.

**Comment by xianggao1989** [comment]
OK, please let me know when the bug is fixed and the new version is released. Thank you!

**Comment by ahojnnes** [comment]
The bug is fixed and you can recompile the latest master/dev branch. Binaries are updated as well.

**Comment by xianggao1989** [comment]
Thanks for your efficient relpy. I have downloaded the latest binary code in https://demuc.de/colmap/. However, the program crashed again with the same error.
