### ISSUE TITLE
Questions about the local camera coordinate system

### ISSUE THREAD

**Issue by 07hyx06** [colmap/colmap#1300]
The [document](https://colmap.github.io/format.html) says

> The local camera coordinate system of an image is defined in a way that the X axis points to the right, the Y axis to the bottom, and the Z axis to the front as seen from the image.

Is it means the camera is looking at the -Z direction, e.g. increase the Z value of the camera from 0 to 5, the same object would be smaller on the image?

**Comment by tsattler** [comment]
The camera is looking down the Z direction, i.e., objects farther away from the camera have a larger Z value in the local coordinate system of the camera.

**Comment by 07hyx06** [comment]
Hi! I run COLMAP with default options on the [flower dataset](https://drive.google.com/drive/folders/14boI-o5hGO9srnWaaogTU5_ji7wkX2S7). 

The image#1 is shown as below with the extrinsics of  ```tensor([[ 0.9992, -0.0188,  0.0364,  5.5054], [ 0.0183,  0.9997,  0.0147,  2.2734], [-0.0366, -0.0140,  0.9992, -1.3859]])```
![image000](https://user-images.githubusercontent.com/52267384/134344706-ba4223a5-6301-4d99-a5fe-a5e89dd14829.png)



The image#2 is shown as below with the extrinsics of  ```tensor([[ 0.9991, -0.0188,  0.0391,  4.2773], [ 0.0184,  0.9998,  0.0107,  2.2785], [-0.0393, -0.0100,  0.9992, -1.3882]])```
![image001](https://user-images.githubusercontent.com/52267384/134344752-3dda7ac7-a1fb-4b54-8c45-7cb123ec4c5f.png)

From the two images, it seems that the camera is shift right from image#1 to image#2. However, the COLMAP solved extrinsic of image#1 is 5.5054 (on x-axis) and the extrinsic of image#2 is 4.2773 (on x-axis). In the document, it mentioned that ```the X-axis points to the right```. It seems that the COLMAP results are not consistent with the visual effect. Did I miss something?

**Comment by 07hyx06** [comment]
Hi! I run COLMAP with GUI again. For the left camera, the tx is 5.52; for the right camera, the tx is 4.29. If the x-axis points to the right then the right camera's tx should be larger than the left camera's tx, am I right? 

![image](https://user-images.githubusercontent.com/52267384/134349300-57f88750-9b1d-47cd-ab4b-0b070ab09e60.png)
![image](https://user-images.githubusercontent.com/52267384/134349462-752612cf-31ec-4763-be15-e8bf4c7e6faa.png)

**Comment by tsattler** [comment]
The documentation talks about the local camera / image coordinate system. The extrinsics define the mapping from the world coordinate system to the local coordinate systems of the images as `X_local = R * X_world + t`, where `X_local` and `X_global` are 3D point coordinates in the local and world coordinate systems, respectively, `R` is the rotation from world to camera coordinates (which Colmap represents as a quaternion) and `t` is the translation from world to camera coordinates. The axes in the world coordinate system have no meaning as Structure-from-Motion scenes are defined up to an arbitrary rotation, translation, and scale (rotating, translating, and scaling the scene does not affect reprojections).
If the definition of the terms is unclear, please have a look at a computer vision textbook (I recommend Richard Szeliski's book, which is freely available in draft form on his website).

If you want to determine whether an image is to the left / right / top / down of another, you can do the following:
* Let `R_1, t_1` and `R_2, t_2` be the corresponding extrinsics.
* Compute the position of the second camera in the world coordinate system as `c_2 = - transpose(R_2) * t_2`.
* Transform `c_2` into the local coordinate system of the first image via `R_1 * c_2 + t_1`. 
* Check whether the corresponding point is to the left / right / top / down / in front of / behind the camera by looking at the signs of the x-, y-, and z-coordinates.

**Comment by 07hyx06** [comment]
Got it. Thanks for your kind reply!
