### ISSUE TITLE
The output  .ply file is missing.

### ISSUE THREAD

**Issue by RawTerm** [colmap/colmap#1301]
So I’ve  downloaded colmap on my non-cuda pc placed the images in and start the automatic reconstruction but after it finished the .ply file was missing.

I’ve read about someone who had the same problem and fixing it but there was no telling how.

Please help if you know how to fix it.

Edit: I’ve run colmap on win 10
Edit2: I’ve found more people with same problem but no solutions.

**Comment by tsattler** [comment]
The dense reconstruction part of Colmap, which generates the ply files, requires cuda. Without a cuda-capable GPU, the part will not be run.

**Comment by revisionarian** [comment]
If your PC has a GPU that supports OpenCL acceleration (most AMD and Intel GPUs do), you could try COLMAP-CL, which doesn't require CUDA. Windows binaries for COLMAP-CL are available here:

   https://github.com/openphotogrammetry/colmap-cl/releases

**Comment by RawTerm** [comment]
I’ve somehow made it work thanks for help.

**Comment by JavierUrenaPhDProjects** [comment]
> I’ve somehow made it work thanks for help.

hello, how?
