### ISSUE TITLE
Low performance for sparse reconstruction on large dataset

### ISSUE THREAD

**Issue by is03wlei** [colmap/colmap#131]
The dataset contains 28742 images which are extracted from a video taken by one mobile phone.

Performance data:
feature extraction Elapsed time: 173.226 [minutes]
vocab_tree_match Elapsed time: 1614.621 [minutes]
Mapper has been running for more than five days.

Cpu and mem info:
Tasks:  36 total,   1 running,  35 sleeping,   0 stopped,   0 zombie
%Cpu(s):  5.3 us,  0.3 sy,  0.0 ni, 94.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 26390022+total, 27246512 free, 13569824+used, 10095547+buff/cache
KiB Swap:        0 total,        0 free,        0 used. 12319003+avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND      
 1453 xxx  20   0  0.124t 0.109t  92812 S 100.0 44.4  48802:37 mapper  

Elapsed time for mapper:
ps -p "1453" -o etime=
 5-15:37:01

Running script:
feature_extractor \
   --database_path $PROJECT_PATH/database.db \
   --image_path $PROJECT_PATH/images \
   --ImageReader.default_focal_length_factor 0.8 \
   --SiftExtraction.max_image_size 4000 \
   --SiftGPUExtraction.index 0 \
   --SiftCPUExtraction.num_threads 20 > feature_extractor.log

vocab_tree_matcher \
   --database_path $PROJECT_PATH/database.db \
   --SiftMatching.gpu_index 0 \
   --VocabTreeMatching.vocab_tree_path ./vocab_tree-1048576.bin \
   --SiftMatching.num_threads 20 > vocab_tree_matcher.log

mkdir $PROJECT_PATH/sparse

mapper \
    --database_path $PROJECT_PATH/database.db \
    --image_path $PROJECT_PATH/images \
    --export_path $PROJECT_PATH/sparse \
    --Mapper.num_threads 20 > mapper.log

It seems that most of time mapper does bundle adjust.
It takes about 5 seconds to register one image.

One bundle adjustment statistics is as follows.

==============================================================================
Global bundle adjustment
==============================================================================

CPU double-precision solver; 20 cores.
WARNING: 3 camera moved to avoid degeneracy.
Memory for Motion/Structure/Jacobian:	22099MB
Memory for Conjugate Gradient Solver:	1874MB
Initial mean squared error = 1.69592
----------------------------------------------
#0   10 2 e=1.67389  u=0.001     r=0.998  g=0 0.013     0.525     t=20
#1   33 N e=1.67354  u=0.000333  r=0.891  g=0 0.00021   0.59      t=51
#2   27 N e=1.67344  u=0.000173  r=0.678  g=0 5.79e-05  0.553     t=76
#3   12 N e=1.6734   u=0.000165  r=0.817  g=0 2.71e-05  0.3       t=90
#4   50 N e=1.67335  u=0.000123  r=0.511  g=0 2.55e-05  0.654     t=134
#5   10 2 e=1.67332  u=0.000123  r=0.836  g=0 2.15e-05  0.281     t=146
#6   62 N e=1.6733   u=8.56e-05  r=0.261  g=0 1.02e-05  0.76      t=201
#7   10 2 e=1.67326  u=9.49e-05  r=0.865  g=0 2.23e-05  0.314     t=212
#8   72 N e=1.67326  u=5.77e-05  r=0.099  g=0 4.17e-06  0.861     t=274
#9   10 2 e=1.67321  u=8.75e-05  r=0.888  g=0 2.61e-05  0.313     t=285
#10  28 N e=1.67321  u=4.64e-05  r=0.061  g=0 1.73e-06  0.758     t=310
#11  10 2 e=1.67318  u=7.76e-05  r=0.899  g=0 1.74e-05  0.325     t=321
#12  34 5 e=1.67318  u=3.79e-05  r=0.034  g=0 1.19e-06  0.961     t=352
#13  10 2 e=1.67314  u=6.85e-05  r=0.923  g=0 2.05e-05  0.349     t=363
#14  37 5 e=1.67314  u=2.7e-05   r=-----  g=0 --------- 1.25      t=397
#15  31 5 e=1.67314  u=5.4e-05   r=0.147  g=0 3.46e-06  0.666     t=424
#16  10 3 e=1.67312  u=7.3e-05   r=0.876  g=0 1.19e-05  0.322     t=436
#17  34 5 e=1.67311  u=4.17e-05  r=0.141  g=0 3.99e-06  0.832     t=466
#18  10 3 e=1.67309  u=5.7e-05   r=0.908  g=0 1.49e-05  0.393     t=478
#19  39 5 e=1.67308  u=2.58e-05  r=0.03   g=0 1.19e-06  1.25      t=513
#20  10 2 e=1.67305  u=4.73e-05  r=0.941  g=0 2.32e-05  0.452     t=524
#21  45 5 e=1.67305  u=1.58e-05  r=-----  g=0 --------- 1.87      t=565
#22  38 5 e=1.67304  u=3.15e-05  r=0.109  g=0 3.46e-06  1.01      t=597
#23  10 3 e=1.67301  u=4.65e-05  r=0.924  g=0 1.69e-05  0.445     t=609
#24  52 5 e=1.67301  u=1.8e-05   r=-----  g=0 --------- 1.66      t=653
#25  97 5 e=1.67299  u=3.59e-05  r=0.225  g=0 1.04e-05  1.12      t=735
#26  10 2 e=1.67295  u=4.19e-05  r=0.922  g=0 2.68e-05  0.483     t=746
#27  46 6 e=1.67297  u=1.66e-05  r=-----  g=0 --------- 1.54      t=787
#28  37 N e=1.67295  u=3.32e-05  r=-----  g=0 --------- 0.832     t=819
#29  84 N e=1.67294  u=0.000133  r=0.431  g=0 6.68e-06  0.353     t=889
#30  18 2 e=1.67293  u=0.000133  r=0.354  g=0 2.98e-06  0.212     t=908
#31  22 N e=1.67293  u=0.000136  r=0.232  g=0 1.73e-06  0.222     t=930
#32  22 N e=1.67293  u=0.000157  r=0.209  g=0 1.37e-06  0.195     t=952
#33  22 N e=1.67293  u=0.000188  r=0.282  g=0 1.61e-06  0.168     t=972
#34  50 N e=1.67292  u=0.000203  r=0.53   g=0 4.53e-06  0.201     t=1019
#35  18 N e=1.67292  u=0.000203  r=0.33   g=0 1.61e-06  0.142     t=1036
#36  60 N e=1.67291  u=0.000211  r=0.55   g=0 4.83e-06  0.205     t=1094
#37  18 N e=1.6729   u=0.000211  r=0.276  g=0 1.31e-06  0.137     t=1112
#38  62 N e=1.6729   u=0.00023   r=0.55   g=0 4.41e-06  0.187     t=1172
#39  18 N e=1.6729   u=0.00023   r=0.25   g=0 1.07e-06  0.128     t=1189
#40  21 N e=1.67289  u=0.000258  r=0.192  g=0 7.75e-07  0.121     t=1211
#41  48 N e=1.67289  u=0.000318  r=0.548  g=0 2.98e-06  0.13      t=1254
#42  19 N e=1.67289  u=0.000318  r=0.271  g=0 8.34e-07  0.0958    t=1274
#43  56 N e=1.67288  u=0.000349  r=0.588  g=0 3.1e-06   0.124     t=1322
#44  20 N e=1.67288  u=0.000347  r=0.182  g=0 5.36e-07  0.0906    t=1342
#45  53 N e=1.67288  u=0.000436  r=0.603  g=0 2.56e-06  0.0993    t=1388
#46  53 N e=1.67287  u=0.000432  r=0.557  g=0 2.38e-06  0.102     t=1437
#47  20 N e=1.67287  u=0.000431  r=0.175  g=0 4.17e-07  0.0744    t=1456
#48  48 N e=1.67287  u=0.000549  r=0.558  g=0 1.85e-06  0.0776    t=1501
#49  48 N e=1.67287  u=0.000548  r=0.556  g=0 1.85e-06  0.0796    t=1544

---------------------------------------
45        	 successful iterations;
50        	 linear systems solved;
1664      	 conjugated gradient steps;
1550.05   	 seconds used overall;
0.420225  	 seconds on allocation;
3.22733   	 seconds on pre-processing;
0         	 seconds on upload;
1546.36   	 seconds on optimization;
50.1 (3.2%)	 seconds on jacobians;
6.66 (0.3%)	 seconds on projections;
502.73(32.4%)	 seconds on JX;
731.39(47.2%)	 seconds on JtE;
22.36(1.4%)	 seconds to compute preconditioner;
18.79(1.1%)	 seconds to apply preconditioner;
10.32(0.6%)	 seconds to update parameters;
---------------------------------------
mse = 1.69592 -> 1.67287  (1.66743U)
---------------------------------------

Bundle adjustment report
------------------------
    Residuals : 124573464
   Parameters : 13389258
   Iterations : 50
         Time : 1550.05 [s]
 Initial cost : 0.651137 [px]
   Final cost : 0.646697 [px]
  Termination : User success

  => Merged observations: 39219
  => Completed observations: 20154
  => Filtered observations: 12658
  => Changed observations: 0.001156

**Comment by ahojnnes** [comment]
Yes, for very large datasets, bundle adjustment in incremental SFM gets very slow. I am currently implementing a hierarchical mapper, which is functional but not very robust at this point. The model merging breaks easily if cameras are mis-registered in one of the hierarchical sub models. You can try it out by adding ``COLMAP_ADD_EXECUTABLE(hierarchical_mapper hierarchical_mapper.cc)`` to the ``src/exe/CMakeLists.txt`` and then executing the corresponding executable from the command line. I'd be curious to hear wether it works for you.

**Comment by is03wlei** [comment]
==============================================================================
Partitioning the scene
==============================================================================

Reading images...
Reading scene graph...
Partitioning scene graph...
  Cluster 1 with 632 images
  Cluster 2 with 746 images
  Cluster 3 with 704 images
  Cluster 4 with 778 images
  Cluster 5 with 713 images
  Cluster 6 with 787 images
  Cluster 7 with 787 images
  Cluster 8 with 742 images
  Cluster 9 with 747 images
  Cluster 10 with 661 images
  Cluster 11 with 656 images
  Cluster 12 with 592 images
  Cluster 13 with 640 images
  Cluster 14 with 689 images
  Cluster 15 with 736 images
  Cluster 16 with 691 images
  Cluster 17 with 622 images
  Cluster 18 with 581 images
  Cluster 19 with 605 images
  Cluster 20 with 651 images
  Cluster 21 with 721 images
  Cluster 22 with 685 images
  Cluster 23 with 678 images
  Cluster 24 with 567 images
  Cluster 25 with 677 images
  Cluster 26 with 789 images
  Cluster 27 with 697 images
  Cluster 28 with 722 images
  Cluster 29 with 623 images
  Cluster 30 with 578 images
  Cluster 31 with 764 images
  Cluster 32 with 748 images
  Cluster 33 with 689 images
  Cluster 34 with 584 images
  Cluster 35 with 664 images
  Cluster 36 with 715 images
  Cluster 37 with 543 images
  Cluster 38 with 630 images
  Cluster 39 with 603 images
  Cluster 40 with 753 images
  Cluster 41 with 800 images
  Cluster 42 with 735 images
  Cluster 43 with 647 images
  Cluster 44 with 704 images
  Cluster 45 with 773 images
  Cluster 46 with 775 images
  Cluster 47 with 589 images
  Cluster 48 with 632 images
  Cluster 49 with 645 images
  Cluster 50 with 692 images
  Cluster 51 with 606 images
  Cluster 52 with 610 images
  Cluster 53 with 594 images
  Cluster 54 with 635 images
  Cluster 55 with 645 images
  Cluster 56 with 692 images
  Cluster 57 with 653 images
  Cluster 58 with 719 images
  Cluster 59 with 671 images
  Cluster 60 with 690 images
  Cluster 61 with 660 images
  Cluster 62 with 706 images
  Cluster 63 with 614 images
  Cluster 64 with 545 images
  Cluster 65 with 705 images
  Cluster 66 with 683 images
  Cluster 67 with 726 images
  Cluster 68 with 670 images
  Cluster 69 with 612 images
  Cluster 70 with 734 images
  Cluster 71 with 730 images
  Cluster 72 with 767 images
Clusters have 48849 images

==============================================================================
Reconstructing clusters
==============================================================================


==============================================================================
Loading database
==============================================================================


==============================================================================
Loading database
==============================================================================


==============================================================================
Loading database
==============================================================================


==============================================================================

==============================================================================
Loading database
==============================================================================


==============================================================================
Loading databaseLoading database
==============================================================================

==============================================================================

Loading database
==============================================================================

==============================================================================



==============================================================================
Loading database
==============================================================================

SQLite error [/home/wangleikidding/git/colmap/src/base/database.cc, line 194]: database is locked
Loading cameras...Loading cameras...Loading cameras...Loading cameras...Loading cameras...Loading cameras...Loading cameras...Loading cameras... 27092 in 0.076s
Loading matches... 27092 in 0.076s
 27092 in 0.076s
Loading matches...Loading matches... 27092 in 0.076s
Loading matches... 27092 in 0.076s
Loading matches... 27092 in 0.076s
Loading matches... 27092 in 0.077s
Loading matches... 27092 in 0.076s
