### ISSUE TITLE
Is it possible to support multi GPU for feature extractor and mapper?

### ISSUE THREAD

**Issue by is03wlei** [colmap/colmap#132]
For feature extractor, I think we just need to add mutex lock in ImageReader::Next().

**Comment by ahojnnes** [comment]
It is possible and it makes sense to do so, but I currently don't have time to implement this, since feature extraction is typically not the bottleneck.

**Comment by is03wlei** [comment]
I almost finish multi GPU support for feature exactor.  Hope to pull request on weekends.

**Comment by ahojnnes** [comment]
Multi GPU bundle adjustment will be very non trivial. But feel free to explore PBA and implement it :-)

**Comment by is03wlei** [comment]
I think it's implemented in VisualSFM. Maybe we can borrow something.

**Comment by ahojnnes** [comment]
No, there is no multi-GPU support in VisualSFM for bundle adjustment. Also, the GPU is not used for larger bundle adjustment problems anyway, since I am switching to the double precision solver for numerical precision reasons. I don't think it makes sense to spend time on this.

**Comment by ahojnnes** [comment]
The latest commits in the dev branch implement multi-GPU feature extraction. Implementing the bundle adjustment using multiple GPUs will be very hard and hence I will close this issue. Thanks for your feedback!
