### ISSUE TITLE
Question regarding points3D

### ISSUE THREAD

**Issue by thatbrguy** [colmap/colmap#1321]
Hello, I have a small question regarding the points3D file. I would like to verify if my understanding is correct.

The [docs](https://colmap.github.io/format.html#sparse-reconstruction) mention that the format of `points3D.txt` is as follows:

```
# 3D point list with one line of data per point:
#   POINT3D_ID, X, Y, Z, R, G, B, ERROR, TRACK[] as (IMAGE_ID, POINT2D_IDX)
```
For a given `POINT3D_ID`, can I assume that the `IMAGE_ID` values in `TRACK[]` are all the images in which `POINT3D_ID` is "visible"? (since `POINT3D_ID` corresponds to the keypoint `POINT2D_IDX` in the image `IMAGE_ID`) 

Is my above understanding correct? Thanks!

**Comment by tsattler** [comment]
Yes.

**Comment by thatbrguy** [comment]
Thanks! Will close this issue now.
