### ISSUE TITLE
COLMAP could not run [Ubuntu 18.04, CUDA 11.1]

### ISSUE THREAD

**Issue by Charlotte0592** [colmap/colmap#1324]
After building COLMAP from source, I ran `colmap gui`. But a black screen was displayed. And the terminal showed these messages.

``` 
QXcbConnection: Failed initialize XRandr 
Qt: XKEYBOARD extension not present on the X server
Unsupported screen format: depth: 16, red mask: 3f, blue mask: f800
Using RGB16 fallback, if this works your X11 server is reporting a bad screen format.
QOpenGLWidget: Failed to make context current QOpenGLWidget: Failed to make context current
QOpenGLShaderProgram: could not create shader program QOpenGLShader: could not create shader 
Could not link shader program:
QXcbConnection: XCB error: 157 (Unknown), sequence: 335, resource id: 4, major c ode: 148 (Unknown), minor code: 1
QXcbConnection: XCB error: 157 (Unknown), sequence: 351, resource id: 4, major c ode: 148 (Unknown), minor code: 1
```

What can I do? How to deal with this bug?

Device: Ubuntu 18.04
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:10:02_PDT_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0

---
When I was building colmap, I had the same CUDA problem as #1303 . But I couldn't even run the colmap. Is there anybody can help me?

**Comment by Charlotte0592** [comment]
> After built COLMAP from source, I ran `colmap gui`. But a black screen was displayed. And terminal showed these messages.
> 
> ```
> QXcbConnection: Failed initialize XRandr 
> Qt: XKEYBOARD extension not present on the X server
> Unsupported screen format: depth: 16, red mask: 3f, blue mask: f800
> Using RGB16 fallback, if this works your X11 server is reporting a bad screen format.
> QOpenGLWidget: Failed to make context current QOpenGLWidget: Failed to make context current
> QOpenGLShaderProgram: could not create shader program QOpenGLShader: could not create shader 
> Could not link shader program:
> QXcbConnection: XCB error: 157 (Unknown), sequence: 335, resource id: 4, major c ode: 148 (Unknown), minor code: 1
> QXcbConnection: XCB error: 157 (Unknown), sequence: 351, resource id: 4, major c ode: 148 (Unknown), minor code: 1
> ```
> 
> What can I do? How to deal with this bug?

**Comment by alexmyczko** [comment]
are you running it locally, or remotely (x11, vnc, rdp)?

**Comment by Charlotte0592** [comment]
> 

I run it on vnc remotely. Thanks for your reminder! When I run it locally, it works well.

**Comment by noamholz** [comment]
> are you running it locally, or remotely (x11, vnc, rdp)?
@alexmyczko , I'm having this problem when using tightvnc. It did work for me before when I ran it remotely.. Can you give me a hint of causes the problem and how to make it work again?
Thanks!
