### ISSUE TITLE
SQLite error "database is locked" when working on network mount

### ISSUE THREAD

**Issue by adizhol** [colmap/colmap#1325]
Created new project. 
Created new db file on mounted network (cifs) drive.
Set image folder on the same mounted drive.
Open extract features. Click on extract features.
Colamp crashes 

* When doing the same steps from local files, colmap runs normally.

- OS: ubuntu 16.04
- Version: 3.7, compiled with cuda
```
SQLite error [/home/azholkover/code/colmap/src/base/database.cc, line 270]: database is locked
SQLite error [/home/azholkover/code/colmap/src/base/database.cc, line 1168]: database is locked
SQLite error [/home/azholkover/code/colmap/src/base/database.cc, line 1189]: database is locked
SQLite error [/home/azholkover/code/colmap/src/base/database.cc, line 1201]: database is locked
SQLite error [/home/azholkover/code/colmap/src/base/database.cc, line 1213]: database is locked
SQLite error [/home/azholkover/code/colmap/src/base/database.cc, line 1224]: database is locked
SQLite error [/home/azholkover/code/colmap/src/base/database.cc, line 1243]: database is locked
SQLite error [/home/azholkover/code/colmap/src/base/database.cc, line 1250]: no such table: two_view_geometries
SQLite error [/home/azholkover/code/colmap/src/base/database.cc, line 1255]: no such table: two_view_geometries
SQLite error [/home/azholkover/code/colmap/src/base/database.cc, line 1260]: no such table: two_view_geometries
SQLite error [/home/azholkover/code/colmap/src/base/database.cc, line 1267]: database is locked
SQLite error [/home/azholkover/code/colmap/src/base/database.cc, line 942]: SQL logic error
```

**Comment by ahojnnes** [comment]
Using SQLite over a network share is known to be a fragile experience, especially with the current settings of the SQLite library compiled inside COLMAP. I'll close this issue, because it's known and there are no plans to address it. Thanks for the report.

**Comment by minim1ner** [comment]
If database is not shared among processes - it is possible to add nolock=1 query parameter to sql connecion uri to make it work on cifs.

You just need to 
- add SQLITE_OPEN_URI open flag besides SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE
- escape '?' characters (change them to "%3f") in the file path, prepend "file:" and append "?nolock=1" to it.
