### ISSUE TITLE
Syntax error when building?

### ISSUE THREAD

**Issue by APCoding** [colmap/colmap#133]
After setting up all the dependencies using Homebrew, I tried to run the command `set(Qt5_CMAKE_DIR "/usr/local/opt/qt5/lib/cmake")`. I ran it from the COLMAP directory (src is a file in the directory I ran it from). It returns `-bash: syntax error near unexpected token `Qt5_CMAKE_DIR'`. I think my terminal somehow doesn't like the space after DIR, but I'm really not sure. Surrounding the command with single quotes, which are supposed to ignore spaces, returned directory not found, even though I could navigate to the directory using CD. Thoughts? Thanks!

**Comment by ahojnnes** [comment]
Hi,

Please follow the installation instructions in the documentation. The command you are running on the command line is a CMake command and should go into the LocalConfig.cmake. Let me know if that solves your problem. 

Best,
Johannes

**Comment by APCoding** [comment]
Yes, that works. Thanks for your help, I didn't read the documentation correctly. I thought it meant those commands created the LocalConfig file. If anyone else reads it like me, consider changing "Create LocalConfig.cmake in COLMAP base directory with:" to "Create LocalConfig.cmake in COLMAP base directory, then insert the following into it:"

**Comment by ahojnnes** [comment]
I will reformulate this sentence to avoid confusion in the future. Thanks for the feedback.

**Comment by APCoding** [comment]
OK, thank you!
