### ISSUE TITLE
Build stops around 50%

### ISSUE THREAD

**Issue by PeterEckmann** [colmap/colmap#134]
Hi, I can't seem to build COLMAP on my Mac Sierra. After typing `make -j`, as given by the documentation, it starts and usually gets around 50% (although it varies) through. Then, at a seemingly random time, it stops building. For example, last time I tried to run it (overnight), it came up with:
`[ 49%] Built target pba`,
 and stopped doing anything else. How can I solve this? Thanks!

**Comment by ahojnnes** [comment]
Do you have CUDA? Are you building in Release mode?

**Comment by PeterEckmann** [comment]
I'm building it without CUDA, do I need to specify that somewhere?

**Comment by PeterEckmann** [comment]
I also tried to use
`cmake -D CMAKE_BUILD_TYPE=Release ..`,
in place of
`cmake ..`
but that didn't make a difference.

**Comment by ahojnnes** [comment]
Instead of make -j, can you run just make and send me the last lines of the terminal where it got stuck?

Another idea could be that your disk filled up or you're running out of RAM. How much memory do you have?

**Comment by PeterEckmann** [comment]
Looks like not using parallel (using `make` instead of `make -j`) worked, so it might have been a memory issue. Thanks!

**Comment by PeterEckmann** [comment]
It looks like the build didn't work. The executables in ./src/exe are still .cc files, so they are not compiled yet. There should be executables in this location, no?

**Comment by ahojnnes** [comment]
If you followed the installation instructions in the documentation, then they executables should be on build/src/exe.
