### ISSUE TITLE
Transform camera poses to world coordinate system

### ISSUE THREAD

**Issue by tudipffmgt** [colmap/colmap#1341]
I am using COLMAP to register old images where I am not able to provide world coordinates for the cameras.
Thus, I created a sparse cloud up to scale using the standard workflow in COLMAP.

![Model](https://user-images.githubusercontent.com/46675239/143433118-77face68-f20f-439f-8732-14803cddea86.jpg)

We are now trying to transform the cameras positions and orientations (angles) into our world coordinate system but are not able to solve the problem of **incorrect camera angles.**

The idea was to use homologue points in a 3D model (world coordinate system) and sparse cloud (local coordinate system) and calculate a seven-parameter transform (Helmert transformation) to be used on the local cameras positions. We followed multiple steps.
1. In a quite time-consuming process I clicked a minimum of 15 points distributed all over the model and not only in one plane and hand-picked the coordinates in the COLMAP sparse cloud.

![CloudCompare](https://user-images.githubusercontent.com/46675239/143433226-6e8f1d8d-9032-4d9d-aa88-bba69d65099a.jpg)
I did this for several models to ensure that no errors happen here.

2. Now I calculate the 4x4 transformation matrix using `Eigen::umeyama` and I cross-checked the result using a Matlab implementation of a colleague. The result is similar.

3. I import the images.txt of my sparse model and use `ProjectionCenterFromPose(qvec, tvec)` to get the camera center coordinates and `QuaternionToRotationMatrix(qvec)` to retrieve the rotation matrix. I flip the second and third row to match OpenGLs coordinate system in our world coordinate model. The 4x4 pose matrix is composed by the rotation matrix, camera center and the fourth row is [0, 0, 0, 1]. I visualized these poses in Matlab and they are like the poses in COLMAP.

4. Now I just multiply my transformation_matrix with my pose and assumed that I get the transformed poses into our world coordinate system. 
EDIT begin:
`new_pose[4x4]=transformation_matrix[4x4]*old_pose[4x4]`. I just recognized that maybe an error occurs at this point. I was directly exporting the `rotation_matrix = new_pose.topLeftCorner(3, 3)`. Is this correct or do I have to transpose/invert the new_pose? 
EDIT end:
When we visualize the results, the positions of the cameras (X,Y,Z) is always correct but the angles are always off. 

![01](https://user-images.githubusercontent.com/46675239/143433547-89b81cbf-524b-4cca-860a-e3f93e409bc2.png)

These are no constant errors, but the angles are sometimes slightly shifted to the left or to the top (see attached images). The OpenGL model uses also the cameras inner orientation (calibrated in the BA) which I provide with cameras.txt
![02](https://user-images.githubusercontent.com/46675239/143433607-b832f1a5-5a55-458e-8a60-8643bf77bcd4.png)
![03](https://user-images.githubusercontent.com/46675239/143433639-42572f06-fded-4abd-ab87-873417d78476.png)
![03_2](https://user-images.githubusercontent.com/46675239/143433796-125e1864-3ee0-4b90-8808-62df91ee8130.png)
![TBP](https://user-images.githubusercontent.com/46675239/143433950-95d8593e-eb5d-47ff-89a2-1927c8875b78.png)

What are we doing wrong or does it just simply not work like this? We tried to change and verify every step of our workflow but are not achieving better results for the angles while the positions stay correct.

**Comment by tsattler** [comment]
When you generate the transformation matrix, do you transpose the rotation to get the rotation from camera to world coordinates.

**Comment by tudipffmgt** [comment]
Hi Torsten, thank you for the fast reply. No I didn't do that.
So I just transpose the top-left corner 3x3 of my transformation matrix?
That would make sense. I will check and report.

**Comment by tudipffmgt** [comment]
We could track down the error. The transformation matrix was already correct. Our error was in step 3:

> I import the images.txt of my sparse model and use ProjectionCenterFromPose(qvec, tvec) to get the camera center coordinates and QuaternionToRotationMatrix(qvec) to retrieve the rotation matrix. I flip the second and third row to match OpenGLs coordinate system in our world coordinate model. The 4x4 pose matrix is composed by the rotation matrix, camera center and the fourth row is [0, 0, 0, 1]. I visualized these poses in Matlab and they are like the poses in COLMAP.

We had to invert the rotation matrix in our pose. It seems that the error occured because OpenCV rotation matrix is row-major and OpenGL is column-major. After that, we did the multiplication and retrieved the correct poses. Maybe it will help others.
