### ISSUE TITLE
Stopping in 'Finding good initial image pair' with no response.

### ISSUE THREAD

**Issue by MrIsland** [colmap/colmap#1345]
**Describe the bug**
Under ubuntu18.04.
The program was always stop in 'Finding good initial image pair'(include import the feature and matched or Automatic reconstruction), and don't know where the problem was.
I followed the official tutorial to install colmap. Are there some dependencies I haven't installed?
Did anyone meet the problem as this？
Many thanks!

**Screenshots**
![image](https://user-images.githubusercontent.com/53335803/144192280-73dd32c5-b2fd-4b72-a36c-5e6f45f1894a.png)

**Desktop (please complete the following information):**
 - OS: [ubuntu18.04]

**Comment by MrIsland** [comment]
The problem was solved by installing the stable version or selecting the initial image pair.  The former is better.

**Comment by sunshineywz123** [comment]
> selecting the initial image pair.

Please tell me which version is the stable version and how to proceed to select the initial image pair?thanks very much
