### ISSUE TITLE
Reconstruction with partly-accurately-known camera poses, the transition is accurate but there is some error in rotation, how to deal with it?

### ISSUE THREAD

**Issue by luoyin500** [colmap/colmap#1346]
Reconstruction with **partly-accurately-known** camera poses:
1. the intrinsics of the camera is accurate.
2. the transition of the camera is accurate.
**3. some error in camera rotation matrix. (because the object itself has a rotational motion)**

How to deal with this kind of problem? Thanks~~

**Comment by tsattler** [comment]
I guess this really depends on the accuracy of the camera orientations. If they are good enough, you could use the point triangulator to obtain initial 3D structure and then iteratively bundle adjust the reconstruction (you could fix the camera positions and intrinsics and only optimize the rotations) and merge tracks. There is an issue discussing the second step.

If the orientations are not accurate enough, you will need to re-estimate them or refine them. To the best of my knowledge, there currently is no code for this in Colmap.

**Comment by luoyin500** [comment]
Thanks~

**Comment by mattiasmar** [comment]
@luoyin500 what was the best approach that you found to tackle this problem?
