### ISSUE TITLE
Reconstruction of a single image to an existing reconstruction with known orientation and custom feature matching

### ISSUE THREAD

**Issue by tudipffmgt** [colmap/colmap#1350]
I use custom feature matching (SuperGlue and this pipeline https://github.com/cvg/Hierarchical-Localization) for estimating the pose of images.
I reconstruct 20 images in a local coordinate system using the COLMAP reconstruction pipeline.
Now I want to fix the intrinsics and extrinsics and add another image to the reconstruction using COLMAP.
I know that this is possible using the implemented feature extractor: https://colmap.github.io/faq.html#register-localize-new-images-into-an-existing-reconstruction

But how can I do it with SuperGlue?

**Comment by tsattler** [comment]
If you import the SuperGlue features for the new image and matches between the new image and the existing ones into the database, you can use the image_registrator to find the pose of the new image while fixing the poses of the existing ones.

**Comment by tudipffmgt** [comment]
I got a little bit confused by your answer.
So I have my existing database with 20 images and a sparse_model.
Then, I create a new_database with 21 images using hloc/reconstruction.main (reconstruction.py) and import the images, features and matches.
I use `image_registrator --database_path new_database --input_path sparse_model --output_path new_model` and I get an error that `F1209 13:59:22.303509 18936 reconstruction.cc:81] Check failed: existing_image.Name() == image.second.Name()` which is clear because my new database has an additional image.
Is it possible to only import features and matches without the image or how should I proceed?
What would be the smartest way to import the SuperGlue features into my database?

SuperGlue uses the image_id to import features so I assumed that the image has to be in the database:
```
def import_features(image_ids, database_path, features_path):
    logging.info('Importing features into the database...')
    hfile = h5py.File(str(features_path), 'r')
    db = COLMAPDatabase.connect(database_path)

    for image_name, image_id in tqdm(image_ids.items()):
        keypoints = hfile[image_name]['keypoints'].__array__()
        keypoints += 0.5  # COLMAP origin
        db.add_keypoints(image_id, keypoints)

    hfile.close()
    db.commit()
    db.close()
```

**Comment by tsattler** [comment]
You could have a look at how things are done here: https://github.com/tsattler/visuallocalizationbenchmark/tree/master/local_feature_evaluation
As far as I understand, you are trying to solve the same / a similar problem.

**Comment by tudipffmgt** [comment]
Thanks, I looked in to it and I am confident it should be here: https://github.com/tsattler/visuallocalizationbenchmark/blob/master/local_feature_evaluation/reconstruction_pipeline.py#L331-L340
I will try to adapt it to SuperGlue tomorrow.

**Comment by tudipffmgt** [comment]
It finally worked using this pipeline https://nbviewer.org/github/cvg/Hierarchical-Localization/blob/master/pipeline_Aachen.ipynb. I modified it locally according to my use-case.
I think it should also work using the local_feature_evaluation but since I am using SuperGlue I used the other one.
