### ISSUE TITLE
Is there a way to constrain all camera positions to be co-planar?

### ISSUE THREAD

**Issue by noamholz** [colmap/colmap#1351]
**Is your feature request related to a problem? Please describe.**
I have a sequence of images taken from a camera, but little knowledge of the cameras real world locations throughout the sequence.
However, I do know the camera's movement is confined to a plane, and that its orientation is always up-right WRT that plane.
When trying the sparse reconstruction, it goes astray, resulting with camera positions that are far from being co-planar (usually it results with a mix of 2-3 planes for the cameras positions)

**Describe the solution you'd like**
Is there a way to constrain all camera positions to be co-planar?
Is there a way to constrain all camera orientations to share the same z-axis component?
Or generally, is it possible to provide *partial* real-world camera positions? 
(so I could define z=0 for all images, and v_orient = (?, ?, 0))

**Comment by tsattler** [comment]
Colmap is not using position and orientation priors in the reconstruction process (to the best of my knowledge), only to determine which images to match. It can use precise position and orientation estimates via the `point_triangulator`, but as I understand your setup, you do not have them.

Some parts of the existing implementation can be specialized, e.g., the bundle adjustment process. Some others, namely the minimal solvers used for relative and absolute pose estimation, would need to be implemented from scratch.

**Comment by noamholz** [comment]
Right, thanks a lot for your answers!
