### ISSUE TITLE
BA collapses poses and 3D Points

### ISSUE THREAD

**Issue by h12sawhney** [colmap/colmap#1353]
Hullo

I use quite good pre-computed poses and initialize triangulation after feature extraction and matching and adjusting the image IDs appropriately. I check both the camera poses and 3D (sparse) points computed by triangulation and they look good. I use only one iteration for triangulation to not have it drift away too much from the initial poses.

But next when I use BA, BA simply collapses all the poses and 3D points into the same (more or less) estimate?

Is there an obvious reason behind this? Is there a fix to this by changing any BA parameters?

Thanks,
Harpreet

**Comment by tsattler** [comment]
Can you be more specific how you do the bundle adjustment? Do you call the `bundle_adjuster` from the command line? Or do you do it in the GUI?

**Comment by h12sawhney** [comment]
Thanks Torsten for your response.
I execute via command line.

It seems to be working now with some changes in my inputs. Will investigate more but for now I am all set.
