### ISSUE TITLE
Which parameter will have an influence on the num of point in the `fused.ply` file?

### ISSUE THREAD

**Issue by HsiangYangChu** [colmap/colmap#1356]
I am doing mesh reconstruction using `colmap`! I find that the mesh reconstructed by Poisson method has too many points, I think the reason is that there are so many points in the dense point cloud. Is my thought right? If so, could you tell me Which parameter will have an influence on the num of point in the `fused.ply` file?
Looking forward to you insights! :)

**Comment by tsattler** [comment]
Decreasing `max_image_size` or increasing `min_num_pixels` should result in fewer 3D points.

**Comment by HsiangYangChu** [comment]
> Decreasing `max_image_size` or increasing `min_num_pixels` should result in fewer 3D points.

I appreciate it!

**Comment by HsiangYangChu** [comment]
Hi @tsattler,
Did you mean `--SiftExtraction.max_image_size` for `max_image_size `?
What is the `min_num_pixels`?
Could you provide some details?
Looking forward to your reply!

**Comment by HsiangYangChu** [comment]
Thanks
