### ISSUE TITLE
Fusion: cmvs-colmap - Stuck

### ISSUE THREAD

**Issue by pogilon** [colmap/colmap#136]
Hello @ahojnnes, I am trying to run the "run-cmvs-colmap-photometric.sh" script on a PMVS workspace folder. However, the procedure gets stuck during the fusion process. Please see below. Thanks.

StereoFusion::Options
---------------------
min_num_pixels: 5
max_num_pixels: 1000
max_traversal_depth: 100
max_reproj_error: 2
max_depth_error: 0.01
max_normal_error: 10
cache_size: 32

Reading workspace...
Reading configuration...

**Comment by ahojnnes** [comment]
If you compiled more than a few days ago or if you haven't downloaded the latest version over the last days, please update to the latest development version and retry. I fixed several bugs and performance regressions in the fusion. Let me know if this was successful. Thanks.

**Comment by ahojnnes** [comment]
Closing this issu due to lack of feedback. Feel free to reopen if you have other questions.
