### ISSUE TITLE
compile error error: no matching function for call to ...

### ISSUE THREAD

**Issue by archgeek45** [colmap/colmap#137]
While trying to compile on Arch Linux I get the following error:

[ 32%] Building CXX object src/ext/PoissonRecon/CMakeFiles/poisson_recon.dir/PoissonRecon.cpp.o
In file included from /home/me/Desktop/ColmapStuff/colmap/colmap/src/ext/PoissonRecon/MultiGridOctreeData.h:667:0,
                 from /home/me/Desktop/ColmapStuff/colmap/colmap/src/ext/PoissonRecon/PoissonRecon.cpp:54:
/home/me/Desktop/ColmapStuff/colmap/colmap/src/ext/PoissonRecon/MultiGridOctreeData.WeightedSamples.inl: In member function 'V {anonymous}::Octree<Real>::_Evaluate(const {anonymous}::DenseNodeData<C, FEMDegree>&, Point3D<Real>, const {anonymous}::BSplineData<DataDegree>&, const {anonymous}::ConstPointSupportKey<DataDegree>&) const':
/home/me/Desktop/ColmapStuff/colmap/colmap/src/ext/PoissonRecon/MultiGridOctreeData.WeightedSamples.inl:360:28: error: no matching function for call to '{anonymous}::Octree<Real>::FunctionIndex(const TreeOctNode*&, int [3]) const'
    FunctionIndex( n , fIdx );
                            ^
In file included from /home/me/Desktop/ColmapStuff/colmap/colmap/src/ext/PoissonRecon/PoissonRecon.cpp:54:0:
/home/me/Desktop/ColmapStuff/colmap/colmap/src/ext/PoissonRecon/MultiGridOctreeData.h:308:40: note: candidate: template<class Real> template<int FEMDegree> static void {anonymous}::Octree<Real>::FunctionIndex(const TreeOctNode*, int*)
  template< int FEMDegree > static void FunctionIndex( const TreeOctNode* node , int idx[3] );
                                        ^~~~~~~~~~~~~
/home/me/Desktop/ColmapStuff/colmap/colmap/src/ext/PoissonRecon/MultiGridOctreeData.h:308:40: note:   template argument deduction/substitution failed:
In file included from /home/me/Desktop/ColmapStuff/colmap/colmap/src/ext/PoissonRecon/MultiGridOctreeData.h:667:0,
                 from /home/me/Desktop/ColmapStuff/colmap/colmap/src/ext/PoissonRecon/PoissonRecon.cpp:54:
/home/me/Desktop/ColmapStuff/colmap/colmap/src/ext/PoissonRecon/MultiGridOctreeData.WeightedSamples.inl:360:28: note:   couldn't deduce template parameter 'FEMDegree'
    FunctionIndex( n , fIdx );
                            ^
make[2]: *** [src/ext/PoissonRecon/CMakeFiles/poisson_recon.dir/build.make:183: src/ext/PoissonRecon/CMakeFiles/poisson_recon.dir/PoissonRecon.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:4382: src/ext/PoissonRecon/CMakeFiles/poisson_recon.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

Arch Linux 64-bit
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc-multilib/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 7.1.1 20170528 (GCC)

**Comment by ahojnnes** [comment]
I don't have access to GCC 7.X.

Can you try and change ``FunctionIndex( n , fIdx );`` to ``FunctionIndex< DataDegree >( n , fIdx );`` in ``src/ext/PoissonRecon/MultiGridOctreeData.WeightedSamples.inl`` line 360?

**Comment by ahojnnes** [comment]
I went ahead and added change, assuming that it fixes your issue.

**Comment by archgeek45** [comment]
Sorry so late in replying, but I just got a chance to try compiling it today. It compiled 100% without error, and installed successfully and started up with the "colmap" command in bash. I now have to find an image set and primer so I can explore colmap further. Thank you.
