### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by alexmyczko** [colmap/colmap#1380]
The 3.6 release dates a few years back. Is there a plan to tag a new release (preferably before middle February, so it can be part of Ubuntu 22.04 LTS)?

**Comment by ahojnnes** [comment]
Yes, can do that. If I have not done so by the end of this week, please ping me again. Thanks for the reminder!

**Comment by ahojnnes** [comment]
I guess it does still build under 22.04? Would you have time to confirm, so we can incorporate any necessary build fixes? Thanks.

**Comment by alexmyczko** [comment]
The build is running on Debian sid (and another on 22.04 LTS (unreleased)):
https://sid.ethz.ch/debian/colmap/2022/

if it builds, the .build should look good (it's still building as of now)

**Comment by ahojnnes** [comment]
@alexmyczko Thanks for the link. It seems to have succeeded after looking at the logs. I did a bunch of small fixes in the kast two days. Could you kick off another build and then I'll release a 3.7 version.

**Comment by alexmyczko** [comment]
@ahojnnes https://sid.ethz.ch/debian/colmap/2022/2/ also builds on sid+jammy

**Comment by ahojnnes** [comment]
Here you go: https://github.com/colmap/colmap/releases/tag/3.7

**Comment by Superharz** [comment]
Will there also be new Pre-built Binaries for Windows?

**Comment by ahojnnes** [comment]
Yes, but I need to find some time to do the compilation on my machine.

**Comment by Superharz** [comment]
Sounds good, take all the time you need.

**Comment by ahojnnes** [comment]
@alexmyczko There is one new commit after the 3.7 tag, which might be worth pulling into the ubuntu package. It's a fix for the GUI that would be good to have.

**Comment by ahojnnes** [comment]
@alexmyczko There is another commit. Sorry for the noise.

**Comment by ahojnnes** [comment]
@Superharz I uploaded prebuilt binaries for Windows.

**Comment by Superharz** [comment]
Great, thanks a lot!

**Comment by alexmyczko** [comment]
@ahojnnes wait you kept overwriting the 3.7 release? (with changes, twice?) mind making a 3.7.1 or 3.7.0.1 one?

**Comment by ahojnnes** [comment]
Yes, I intended to do that but my git client messed something up horribly yesterday and did a git push -f. Nothing I can do at this point anymore. I already set the branch policies to prevent that in the future.

**Comment by alexmyczko** [comment]
Sorry missed that, but Debian will freeze in January maybe a 3.8 release is possible within 6 months? Can also be 3.7.1.
