### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by msd-mohit** [colmap/colmap#1399]
I am installing the colmap on google colab, it was working fine till yesterday and today its not.

The code used for installation is:
!git clone https://github.com/colmap/colmap
%cd colmap
!git checkout dev
%mkdir build
%cd build
!cmake ..
!make
!sudo make install
!CC=/usr/bin/gcc-6 CXX=/usr/bin/g++-6 cmake ..

The error is:
[ 50%] Automatic RCC for ui/resources.qrc
Scanning dependencies of target colmap
[ 50%] Building CXX object src/CMakeFiles/colmap.dir/base/camera.cc.o
In file included from /usr/local/include/ceres/ceres.h:40:0,
                 from /content/ceres-solver/build/colmap/src/base/camera_models.h:42,
                 from /content/ceres-solver/build/colmap/src/base/camera.cc:36:
/usr/local/include/ceres/autodiff_manifold.h: In member function ‘bool ceres::AutoDiffManifold<Functor, kAmbientSize, kTangentSize>::PlusJacobian(const double*, double*) const’:
/usr/local/include/ceres/autodiff_manifold.h:227:28: error: missing template arguments before ‘(’ token
       internal::PlusWrapper(*functor_),
                            ^
/usr/local/include/ceres/autodiff_manifold.h: In member function ‘bool ceres::AutoDiffManifold<Functor, kAmbientSize, kTangentSize>::MinusJacobian(const double*, double*) const’:
/usr/local/include/ceres/autodiff_manifold.h:250:29: error: missing template arguments before ‘(’ token
       internal::MinusWrapper(*functor_),
                             ^
src/CMakeFiles/colmap.dir/build.make:107: recipe for target 'src/CMakeFiles/colmap.dir/base/camera.cc.o' failed
make[2]: *** [src/CMakeFiles/colmap.dir/base/camera.cc.o] Error 1
CMakeFiles/Makefile2:714: recipe for target 'src/CMakeFiles/colmap.dir/all' failed
make[1]: *** [src/CMakeFiles/colmap.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
-- Found required Ceres dependency: Eigen version 3.3.4 in /usr/lib/cmake/eigen3
-- Found required Ceres dependency: glog
-- Found required Ceres dependency: gflags
-- Found Ceres version: 2.1.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, Multithreading]
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   graph
--   system
--   unit_test_framework
-- Found Eigen
--   Includes : /usr/include/eigen3
-- Found FreeImage
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
-- Found Glog
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
-- Found Glew
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
-- Found Qt
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Core
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5OpenGL
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets
-- Found CGAL
--   Includes : /usr//include
--   Libraries : /usr/lib/x86_64-linux-gnu/libCGAL.so.13.0.1
-- Build type not specified, using Release
-- Enabling SIMD support
-- Enabling OpenMP support
-- Disabling interprocedural optimization
-- Autodetected CUDA architecture(s):  3.7
-- Enabling CUDA support (version: 11.1, archs: sm_37)
-- Enabling GUI support
-- Enabling OpenGL support
-- Disabling ccache support
-- Disabling profiling support
-- Enabling CGAL support
-- Configuring done
-- Generating done
-- Build files have been written to: /content/ceres-solver/build/colmap/build
[  2%] Built target flann
[ 22%] Built target graclus
[ 24%] Built target lsd
[ 24%] Linking CXX static library libpba.a
[ 26%] Built target pba
[ 30%] Built target poisson_recon
[ 30%] Linking CXX static library libsift_gpu.a
[ 34%] Built target sift_gpu
[ 36%] Built target sqlite3
[ 50%] Built target vlfeat
[ 50%] Building CXX object src/CMakeFiles/colmap.dir/base/camera.cc.o
In file included from /usr/local/include/ceres/ceres.h:40:0,
                 from /content/ceres-solver/build/colmap/src/base/camera_models.h:42,
                 from /content/ceres-solver/build/colmap/src/base/camera.cc:36:
/usr/local/include/ceres/autodiff_manifold.h: In member function ‘bool ceres::AutoDiffManifold<Functor, kAmbientSize, kTangentSize>::PlusJacobian(const double*, double*) const’:
/usr/local/include/ceres/autodiff_manifold.h:227:28: error: missing template arguments before ‘(’ token
       internal::PlusWrapper(*functor_),
                            ^
/usr/local/include/ceres/autodiff_manifold.h: In member function ‘bool ceres::AutoDiffManifold<Functor, kAmbientSize, kTangentSize>::MinusJacobian(const double*, double*) const’:
/usr/local/include/ceres/autodiff_manifold.h:250:29: error: missing template arguments before ‘(’ token
       internal::MinusWrapper(*functor_),
                             ^
src/CMakeFiles/colmap.dir/build.make:107: recipe for target 'src/CMakeFiles/colmap.dir/base/camera.cc.o' failed
make[2]: *** [src/CMakeFiles/colmap.dir/base/camera.cc.o] Error 1
CMakeFiles/Makefile2:714: recipe for target 'src/CMakeFiles/colmap.dir/all' failed
make[1]: *** [src/CMakeFiles/colmap.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
-- Found required Ceres dependency: Eigen version 3.3.4 in /usr/lib/cmake/eigen3
-- Found required Ceres dependency: glog
-- Found required Ceres dependency: gflags
-- Found Ceres version: 2.1.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, Multithreading]
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   graph
--   system
--   unit_test_framework
-- Found Eigen
--   Includes : /usr/include/eigen3
-- Found FreeImage
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
-- Found Glog
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
-- Found Glew
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
-- Found Qt
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Core
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5OpenGL
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets
-- Found CGAL
--   Includes : /usr//include
--   Libraries : /usr/lib/x86_64-linux-gnu/libCGAL.so.13.0.1
-- Build type not specified, using Release
-- Enabling SIMD support
-- Enabling OpenMP support
-- Disabling interprocedural optimization
-- Autodetected CUDA architecture(s):  3.7
-- Enabling CUDA support (version: 11.1, archs: sm_37)
-- Enabling GUI support
-- Enabling OpenGL support
-- Disabling ccache support
-- Disabling profiling support
-- Enabling CGAL support
-- Configuring done
-- Generating done
-- Build files have been written to: /content/ceres-solver/build/colmap/build

It does not reach 100%, but it was yesterday.
Thankyou in advance

**Comment by ferreram** [comment]
Same issue as #1394
