### ISSUE TITLE
Specifying images coming from the same panorama as prior

### ISSUE THREAD

**Issue by kvuong2711** [colmap/colmap#1411]
**Is your feature request related to a problem? Please describe.**
From a set of panoramic images, I extracted/sampled the corresponding perspective images and use them for COLMAP reconstruction. A set of perspective images extract from a panoramic image is the pure rotation cameras. It works well in general since I know COLMAP does check for this case as mentioned in the paper, but it's not perfect (the camera centers of purely-rotational-perspective cameras don't perfectly align after reconstruction). Is there a straightforward way to impose this constraint in order to improve the reconstruction quality?

**Describe the solution you'd like**
It probably requires tinkering with bypassing the triangulation angle check. I'm not sure how straightforward it is.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by tsattler** [comment]
This should be possible via the `rig_bundle_adjuster` as a postprocessing step after reconstruction.
