### ISSUE TITLE
Does adding --SiftExtraction.estimate_affine_shape, -SiftExtraction.domain_size_pooling, --SiftMatching.guided_matching do any harm to the accuracy of reconstruction?

### ISSUE THREAD

**Issue by hengfei-wang** [colmap/colmap#1412]
Hi,

I am now to colmap. I want ask 'Does adding --SiftExtraction.estimate_affine_shape, -SiftExtraction.domain_size_pooling, --SiftMatching.guided_matching do any harm to the accuracy of reconstruction?'. I want to use some images to do reconstruction, but it does not work untill i add --SiftExtraction.estimate_affine_shape, -SiftExtraction.domain_size_pooling, --SiftMatching.guided_matching. So i want to know how they influence the performance.

Thanks

**Comment by ahojnnes** [comment]
It should generally improve accuracy/recall but will be slower.

**Comment by hengfei-wang** [comment]
Thank you for your reply. I will close this issue.
