### ISSUE TITLE
Libboost No suitable build variant has been found

### ISSUE THREAD

**Issue by Medoalmasry** [colmap/colmap#1420]
**Describe the bug**
Despite the fact that libboost is properly installed and linked by several other libraries. I can't seem to get it to work here.

Stackoverflow questions usually suggest converting Boost_USE_STATIC_LIBS to ON instead of OFF
but my current default setting is already ON

**To Reproduce**
cmake ..
-- The C compiler identification is GNU 11.2.1
-- The CXX compiler identification is GNU 11.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found required Ceres dependency: Eigen version 3.4.0 in /usr/include/eigen3
-- Found required Ceres dependency: glog
-- Found Ceres version: 2.0.0 installed in: /usr with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, Multithreading]
**CMake Error at /usr/lib64/cmake/Boost-1.78.0/BoostConfig.cmake:141 (find_package):
  Found package configuration file:

    /usr/lib64/cmake/boost_system-1.78.0/boost_system-config.cmake

  but it set boost_system_FOUND to FALSE so package "boost_system" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_system.so.1.78.0 (shared, Boost_USE_STATIC_LIBS=ON)

Call Stack (most recent call first):
  /usr/lib64/cmake/Boost-1.78.0/BoostConfig.cmake:262 (boost_find_component)
  /usr/share/cmake/Modules/FindBoost.cmake:594 (find_package)
  CMakeLists.txt:92 (find_package)**

**Desktop (please complete the following information):**
 - OpenSuse

**Additional context**
Libboost + all devels are installed.

**Comment by Medoalmasry** [comment]
Made an edit to /usr/lib64/cmake/Boost-1.78.0/BoostConfig.cmake
set(Boost_USE_STATIC_LIBS OFF)

**Comment by otzelpov** [comment]
Thank you so much! I also encountered this issue on openSuse

**Comment by SsNiPeR1** [comment]
Error generating file (it has 14 gb ram left, what's the problem?)
