### ISSUE TITLE
Back projecting a 2D pixel from an image to its corresponding 3D point.

### ISSUE THREAD

**Issue by marsarCV** [colmap/colmap#1424]
I have been trying to understand how to project a 3D point to 2D image and vice versa. I had images of a building taken by a drone, I reconstructed the building using COLMAP GUI. So, after running it through COLMAP, I have the following things available to me:
 1. A scaled point cloud of the scene.
 2. Transformations(R, t) from the world coordinate system to each camera coordinate system.

I wanted to play around and I tried the following:

To go from 3D world to camera image plane, I use the following equation:
For camera intrinsic parameters defined in calibration matrix K(3,3), Transformation matrix, M = [R | t] (3,4), I can get the location of a world 3D point P([X, Y, Z, 1].T) (4,1) in the image plane as:

    [u, v, w] = K M P
    u = u / w
    v = v / w

  This works fine. I am confused in the part where I project the point(u, v) back to the 3D world coordinate system. I am not worried about the scale, hence I just need a unit vector in the right direction to the 3D point.

Here is my current understanding of the approach:

    R_inv = R.T
    M_inv = [R_inv | -R_inv*t]
    # also augment M_inv with horizontal vector [0 0 0 1] so it's size is (4,4)
    p= [u, v, 1]
    p_camera = K_inv * p
    p_camera_homogeneous = [p_camera[0], p_camera[1], p_camera[2], 1]
    P = M_inv * p_camera_homogeneous

Here P = [X, Y, Z, W], so, Point in 3D is : (X/W, Y/W, Z/W). But when I plot the points in 3D graph, I don't get the correct structure. I understand I am missing something fundamental in my approach as I do not have a scale parameter in my equations too.

Please let me know what I am doing wrong. I can share the code, but the problem is with my understanding of the concept.

**Comment by eyildiz-ugoe** [comment]
I have exactly the same concern. I'd like to get the projection matrix, having ran Colmap successfuly, but using the GUI it seems it's not possible. Isn't there like a build-in function to get the camera matrices?

**Comment by marsarCV** [comment]
Yes, there is a built-in function in the scripts/python : https://github.com/colmap/colmap/blob/30521f19de45c1cb2df8809728e780bf95fc8836/scripts/python/read_write_model.py#L101

Depending on whether reading from Binary/TXT file you can choose the function accordingly. Make sure that if you have done a dense reconstruction then the cameras.txt is a refined one, located in the dense/sparse folder.

**Comment by marsarCV** [comment]
This issue is exactly the one here: https://github.com/colmap/colmap/issues/1476. Its closed.

**Comment by hedeya1980** [comment]
> Yes, there is a built-in function in the scripts/python :
> 
> https://github.com/colmap/colmap/blob/30521f19de45c1cb2df8809728e780bf95fc8836/scripts/python/read_write_model.py#L101
> 
> Depending on whether reading from Binary/TXT file you can choose the function accordingly. Make sure that if you have done a dense reconstruction then the cameras.txt is a refined one, located in the dense/sparse folder.

Are there similar functions for C++? I look forward to receiving your advice.

**Comment by bw4sz** [comment]
@marsarCV, can you 1) post your final code for confirmation, I think there are lot of users watching this and in need of a good gist, and just complete the example by showing the step before to confirm how you extracted the camera matrices. I am assuming you had a reconstruction model object.

```
intrinsic = model.cameras[1].params
extrinsic = image.cam_from_world.inverse()
```

but maybe you just took cam_from_world and then inverse it, judging by 

```
R_inv = R.T
```
