### ISSUE TITLE
Not all points are recorded in points3D.txt?

### ISSUE THREAD

**Issue by PeterEckmann** [colmap/colmap#143]
Hi! For some reason `points3D.txt` from my sparse reconstruction (after exporting model from the GUI, although the command line showed similar results) does not contain all points from the reconstruction in the GUI. The maximum point number in the file is 1433, while the actual number of lines is 1227. The numbers seem to be ordered in the beginning of the file, but become more unordered later in. The first image is the reconstructed model from the GUI (it's a water bottle) and the second is from a Python program I wrote to read the `points3D.txt` file and plot the points.
![screen shot 2017-06-07 at 8 19 05 pm](https://user-images.githubusercontent.com/29179992/26910934-e8d5f49a-4bbe-11e7-83c5-86aaba085a9c.png)
![screen shot 2017-06-07 at 8 21 25 pm](https://user-images.githubusercontent.com/29179992/26910937-eaa0ae1e-4bbe-11e7-9f2f-c781f909eb81.png)
So what is happening here? Thanks!

**Comment by ahojnnes** [comment]
Please see https://colmap.github.io/format.html

The identifiers of points are unordered. COLMAP filters points during reconstruction, hence some points are removed and their identifiers are missing.

**Comment by PeterEckmann** [comment]
Is there a way I can remove that filter or recover the points that were removed? The actual points in points3D are essentially useless compared to the version in the GUI.

**Comment by ahojnnes** [comment]
No, you misunderstood. All points in the GUI will be exported when you export the model.

**Comment by PeterEckmann** [comment]
OK, I will look at my visualization code some more. Thanks!
