### ISSUE TITLE
Program abort when reconstruction

### ISSUE THREAD

**Issue by lizhengning** [colmap/colmap#144]
*** Aborted at 1496915083 (unix time) try "date -d @1496915083" if you are using GNU date ***
PC: @           0x80fb40 Eigen::internal::call_assignment_no_alias<>()
*** SIGSEGV (@0x0) received by PID 13312 (TID 0x7fcaf4d68700) from PID 0; stack trace: ***
    @     0x7fcb11759390 (unknown)
    @           0x80fb40 Eigen::internal::call_assignment_no_alias<>()
    @           0xd20629 ceres::internal::DenseSparseMatrix::DenseSparseMatrix()
    @           0xcf6a4d ceres::internal::ProgramEvaluator<>::CreateJacobian()
    @           0xd0dd1c ceres::internal::TrustRegionPreprocessor::Preprocess()
    @           0xce3c40 ceres::Solver::Solve()
    @           0xce4d29 ceres::Solve()
    @           0x79115c colmap::RefineAbsolutePose()
    @           0x7868da colmap::IncrementalMapper::RegisterNextImage()
    @           0x6c3eec colmap::IncrementalMapperController::Reconstruct()
    @           0x6c553b colmap::IncrementalMapperController::Run()
    @           0x77dd8c colmap::Thread::RunFunc()
    @     0x7fcb0ebdcc80 (unknown)
    @     0x7fcb1174f6ba start_thread
    @     0x7fcb0e34282d clone
    @                0x0 (unknown)
Segmentation fault (core dumped)

On ubuntu 16.04

**Comment by ahojnnes** [comment]
Please do not use the Eigen library from the Ubuntu 16.04 repository. They ship a beta version. Any other version should work.
