### ISSUE TITLE
Creating a sparse Model without Bundle Adjustment

### ISSUE THREAD

**Issue by basit-7** [colmap/colmap#1443]
Is it possible to create a sparse model only until the triangulation process? I want to extract poses without performing Bundle Adjustment and Re-triangulation.

**Comment by tsattler** [comment]
Yes, but the quality of the camera poses and estimated intrinsics will be (potentially significantly) worse.

**Comment by basit-7** [comment]
The quality does not matter, I want to compare the poses before and after BA.

Could you please briefly guide me through the steps that I need to follow to achieve the mentioned task?

**Comment by tsattler** [comment]
There should be flags where you can set the number of bundle adjustment to 0. Otherwise, you will need to edit the code.

**Comment by basit-7** [comment]
https://github.com/colmap/colmap/blob/ba0aa468cecafe7f72ad190d9b8ba91c0251b6d0/src/optim/bundle_adjustment.h#L67

Changing it to 'false' did it for me.
