### ISSUE TITLE
about the meaning of parameters in command 'colmap mapper'

### ISSUE THREAD

**Issue by zhywanna** [colmap/colmap#1450]
Dear author, I saw someone use a command like this
```
colmap mapper \
    --database_path $DATASET_PATH/database.db \
    --image_path $DATASET_PATH/images_colmap \
    --output_path $DATASET_PATH/sparse \
    --Mapper.num_threads 16 \
    --Mapper.init_min_tri_angle 4 \
    --Mapper.multiple_models 0 \
    --Mapper.extract_colors 0
```
I have some difficult to understand what does these 
`Mapper.num_threads` `Mapper.init_min_tri_angle` `Mapper.multiple_models` `Mapper.extract_colors`
parameters mean ? And where can I search some explain about parameters in colmap's commands because i didn't see in colmap's website. 

Thanks!

**Comment by tsattler** [comment]
`num_threads` is the number of threads that are used when parts of the pipeline are parallelized. `init_min_tri_angle` is the minimum triangulation angle when initializing a 3D point, `multiple_models` specifies whether multiple 3D models (if possible / necessary), `extract_colors` specifies whether the sparse 3D point cloud should be colored from the images or not. Many of the parameters are explained in the code, see for example https://github.com/colmap/colmap/blob/dev/src/sfm/incremental_mapper.h#L78 . Searching for the parameter names on github will get you there.

**Comment by zhywanna** [comment]
Thank you, it really helps a lot ! 
Actually, I still have a question that I use that command to register my images and got lots of them couldn't register showed like this
![355d17c61712147ea7347bda2010a02](https://user-images.githubusercontent.com/47680024/156890777-45e5dd95-09d6-46b2-aa07-02403b2b093f.jpg)

But if  I removed the last 4 parameters, things go well and successfully got my `camera.bin`. I followed your lead and checked the link about those meanings, I wonder if set `Mapper.multiple_models = 0` or `Mapper.init_min_tri_angle = 4`matters ? 
I still don't know what does `reconstruct multiple sub-models` and `Minimum triangulation angle for initial image pair` means and how those affect the result. And i'm worry about whether the extrinsic camera poses are accurate without those parameters.
I'm a beginner, maybe got some stupid questions and sorry about that.

**Comment by zhywanna** [comment]
Thank you, it really helps a lot ! 
Actually, I still have a question that I use that command to register my images and got lots of them couldn't register showed like this
![355d17c61712147ea7347bda2010a02](https://user-images.githubusercontent.com/47680024/156890777-45e5dd95-09d6-46b2-aa07-02403b2b093f.jpg)

But if  I removed the last 4 parameters, things go well and successfully got my `camera.bin`. I followed your lead and checked the link about those meanings, I wonder if set `Mapper.multiple_models = 0` or `Mapper.init_min_tri_angle = 4`matters ? 
I still don't know what does `reconstruct multiple sub-models` and `Minimum triangulation angle for initial image pair` means and how those affect the result. And i'm worry about whether the extrinsic camera poses are still accurate without those parameters or not ？

**Comment by zhywanna** [comment]
Thanks
