### ISSUE TITLE
Colmap cmake .. error

### ISSUE THREAD

**Issue by HandsomeFYM** [colmap/colmap#1451]
Hello,
I want to install the colmap and I follow the tutorials at https://colmap.github.io/install.html.
It seems to successfully install the ceres-solver. 
And then, in the colmap install part, when I run the "cmake .. ", the following error occurred.

fan@fan-System-Product-Name:~/workspace/colmap/build$ cmake ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CXSparse: /usr/include/suitesparse (found suitable version "3.2.0", minimum required is "3.2.0") 
CMake Warning (dev) at /usr/local/lib/cmake/Ceres/FindSuiteSparse.cmake:115 (if):
  Policy CMP0057 is not set: Support new IN_LIST if() operator.  Run "cmake
  --help-policy CMP0057" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  IN_LIST will be interpreted as an operator when the policy is set to NEW.
  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/local/lib/cmake/Ceres/CeresConfig.cmake:183 (find_dependency)
  CMakeLists.txt:90 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at /usr/local/lib/cmake/Ceres/FindSuiteSparse.cmake:115 (if):
  if given arguments:

    "CHOLMOD" "IN_LIST" "SuiteSparse_FIND_COMPONENTS"

  Unknown arguments specified
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/local/lib/cmake/Ceres/CeresConfig.cmake:183 (find_dependency)
  CMakeLists.txt:90 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/fan/workspace/colmap/build/CMakeFiles/CMakeOutput.log".
See also "/home/fan/workspace/colmap/build/CMakeFiles/CMakeError.log".

My os: Ubuntu20.04, cuda-11.6
Can anyone help me with this problem?

**Comment by Haian-Jin** [comment]
I have met the same problem and we have the same os environment

**Comment by ahojnnes** [comment]
Sounds like an issue of Ceres. Did you install Ceres from source or from the ubuntu apt repo?

**Comment by prajwalchidananda** [comment]
Same issue. Ceres installation steps:
`
git clone https://ceres-solver.googlesource.com/ceres-solver
cd ceres-solver
mkdir build
cd build
cmake .. -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF
make -j
make install
`

**Comment by brentyi** [comment]
I ran into the same thing and it's definitely a Ceres issue; the root cause is that `IN_LIST` is [only introduced in cmake 3.30](https://cmake.org/cmake/help/latest/policy/CMP0057.html).

Ended up just forking and patching (https://github.com/brentyi/ceres-solver), but upgrading cmake should also make the error disappear.

**Comment by kzykmyzw** [comment]
I installed the latest CMake ([3.23.0-rc2](https://cmake.org/download/)), but the same error occurred. So I used @prajwalchidananda 's patched version of ceres-solver, and that worked. Thank you so much!

**Comment by brentyi** [comment]
Oops yes, to correct the record on my initial diagnosis: the problem is that the `cmake_minimum_required()` version is set to 3.0 for colmap, but 3.10 in the Ceres repository. So features introduced in cmake 3.3 break without explicit tweaking policies (in this case `cmake_policy(SET CMP0057 NEW)` would work).

Made a pull request to the Ceres repository, but perhaps the right fix is actually bumping colmap's required cmake version?

**Comment by kzykmyzw** [comment]
I could resolve the error by adding `cmake_policy(SET CMP0057 NEW)` in CMakeLists.txt as follows (with original ceres-solver).
```
cmake_minimum_required(VERSION 3.0)
cmake_policy(SET CMP0057 NEW)

project(COLMAP)

set(COLMAP_VERSION "3.8")
set(COLMAP_VERSION_NUMBER "3800")
...
```

**Comment by HandsomeFYM** [comment]
Thanks very much, guys,
I also used @brentyi 's patched version of ceres-solver.
But when I run the "cmake .. " in colmap/build, there is a new error I got as follows.

fan@fan-System-Product-Name:~/workspace/colmap/build$ cmake ..
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CXSparse: /usr/include/suitesparse (found suitable version "3.2.0", minimum required is "3.2.0") 
-- Found BLAS: /usr/lib/x86_64-linux-gnu/libf77blas.so;/usr/lib/x86_64-linux-gnu/libatlas.so  
-- Found AMD headers in: /usr/include/suitesparse
-- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
-- Found CAMD headers in: /usr/include/suitesparse
-- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
-- Found CCOLAMD headers in: /usr/include/suitesparse
-- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
-- Found CHOLMOD headers in: /usr/include/suitesparse
-- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
-- Found COLAMD headers in: /usr/include/suitesparse
-- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
-- Found SPQR headers in: /usr/include/suitesparse
-- Found SPQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
-- Did not find Intel TBB library, assuming SuiteSparseQR was not compiled with TBB.
-- Found Config headers in: /usr/include/suitesparse
-- Found Config library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
-- Looking for shm_open in rt
-- Looking for shm_open in rt - found
-- Adding librt to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Could NOT find METIS (missing: METIS_INCLUDE_DIR METIS_LIBRARY) 
-- Found SuiteSparse: TRUE (Required is at least version "5.7.1") found components: AMD CAMD CCOLAMD CHOLMOD COLAMD SPQR 
-- Found required Ceres dependency: Eigen version 3.3.7 in /usr/lib/cmake/eigen3
-- Found required Ceres dependency: glog
-- Found required Ceres dependency: gflags
-- Found Ceres version: 2.1.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, Multithreading]
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: program_options filesystem graph system unit_test_framework 
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0") 
-- Found Eigen
--   Includes : /usr/include/eigen3
-- Found FreeImage
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
-- Found Glog
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so   
-- Found Glew
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmp.so  
-- Found MPFR: /usr/lib/x86_64-linux-gnu/libmpfr.so  
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.48")  
-- Boost include dirs: /usr/include
-- Boost libraries:    
-- Using gcc version 4 or later. Adding -frounding-math
-- Found Qt
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Core
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5OpenGL
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets
-- Found CGAL
--   Includes : /usr/include
--   Libraries : CGAL
-- Build type not specified, using Release
-- Enabling SIMD support
-- Enabling OpenMP support
-- Disabling interprocedural optimization
-- Autodetected CUDA architecture(s):  8.6
-- Enabling CUDA support (version: 11.6, archs: sm_86)
-- Enabling GUI support
-- Enabling OpenGL support
-- Disabling ccache support
-- Disabling profiling support
-- Enabling CGAL support
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
METIS_INCLUDE_DIRS
   used as include directory in directory /home/fan/workspace/colmap
   used as include directory in directory /home/fan/workspace/colmap
   used as include directory in directory /home/fan/workspace/colmap
   used as include directory in directory /home/fan/workspace/colmap
   used as include directory in directory /home/fan/workspace/colmap
   used as include directory in directory /home/fan/workspace/colmap
   used as include directory in directory /home/fan/workspace/colmap
   used as include directory in directory /home/fan/workspace/colmap
   used as include directory in directory /home/fan/workspace/colmap/lib
   used as include directory in directory /home/fan/workspace/colmap/lib
   used as include directory in directory /home/fan/workspace/colmap/lib
   used as include directory in directory /home/fan/workspace/colmap/lib
   used as include directory in directory /home/fan/workspace/colmap/lib
   used as include directory in directory /home/fan/workspace/colmap/lib
   used as include directory in directory /home/fan/workspace/colmap/lib/FLANN
   used as include directory in directory /home/fan/workspace/colmap/lib/FLANN
   used as include directory in directory /home/fan/workspace/colmap/lib/FLANN
   used as include directory in directory /home/fan/workspace/colmap/lib/FLANN
   used as include directory in directory /home/fan/workspace/colmap/lib/FLANN
   used as include directory in directory /home/fan/workspace/colmap/lib/FLANN
   used as include directory in directory /home/fan/workspace/colmap/lib/FLANN
   used as include directory in directory /home/fan/workspace/colmap/lib/LSD
   used as include directory in directory /home/fan/workspace/colmap/lib/LSD
   used as include directory in directory /home/fan/workspace/colmap/lib/LSD
   used as include directory in directory /home/fan/workspace/colmap/lib/LSD
   used as include directory in directory /home/fan/workspace/colmap/lib/LSD
   used as include directory in directory /home/fan/workspace/colmap/lib/LSD
   used as include directory in directory /home/fan/workspace/colmap/lib/LSD
   used as include directory in directory /home/fan/workspace/colmap/lib/PBA
   used as include directory in directory /home/fan/workspace/colmap/lib/PBA
   used as include directory in directory /home/fan/workspace/colmap/lib/PBA
   used as include directory in directory /home/fan/workspace/colmap/lib/PBA
   used as include directory in directory /home/fan/workspace/colmap/lib/PBA
   used as include directory in directory /home/fan/workspace/colmap/lib/PBA
   used as include directory in directory /home/fan/workspace/colmap/lib/PBA
   used as include directory in directory /home/fan/workspace/colmap/lib/PoissonRecon
   used as include directory in directory /home/fan/workspace/colmap/lib/PoissonRecon
   used as include directory in directory /home/fan/workspace/colmap/lib/PoissonRecon
   used as include directory in directory /home/fan/workspace/colmap/lib/PoissonRecon
   used as include directory in directory /home/fan/workspace/colmap/lib/PoissonRecon
   used as include directory in directory /home/fan/workspace/colmap/lib/PoissonRecon
   used as include directory in directory /home/fan/workspace/colmap/lib/PoissonRecon
   used as include directory in directory /home/fan/workspace/colmap/lib/SiftGPU
   used as include directory in directory /home/fan/workspace/colmap/lib/SiftGPU
   used as include directory in directory /home/fan/workspace/colmap/lib/SiftGPU
   used as include directory in directory /home/fan/workspace/colmap/lib/SiftGPU
   used as include directory in directory /home/fan/workspace/colmap/lib/SiftGPU
   used as include directory in directory /home/fan/workspace/colmap/lib/SiftGPU
   used as include directory in directory /home/fan/workspace/colmap/lib/SiftGPU
   used as include directory in directory /home/fan/workspace/colmap/lib/SQLite
   used as include directory in directory /home/fan/workspace/colmap/lib/SQLite
   used as include directory in directory /home/fan/workspace/colmap/lib/SQLite
   used as include directory in directory /home/fan/workspace/colmap/lib/SQLite
   used as include directory in directory /home/fan/workspace/colmap/lib/SQLite
   used as include directory in directory /home/fan/workspace/colmap/lib/SQLite
   used as include directory in directory /home/fan/workspace/colmap/lib/SQLite
   used as include directory in directory /home/fan/workspace/colmap/lib/VLFeat
   used as include directory in directory /home/fan/workspace/colmap/lib/VLFeat
   used as include directory in directory /home/fan/workspace/colmap/lib/VLFeat
   used as include directory in directory /home/fan/workspace/colmap/lib/VLFeat
   used as include directory in directory /home/fan/workspace/colmap/lib/VLFeat
   used as include directory in directory /home/fan/workspace/colmap/lib/VLFeat
   used as include directory in directory /home/fan/workspace/colmap/lib/VLFeat
   used as include directory in directory /home/fan/workspace/colmap/src
   used as include directory in directory /home/fan/workspace/colmap/src
   used as include directory in directory /home/fan/workspace/colmap/src
   used as include directory in directory /home/fan/workspace/colmap/src
   used as include directory in directory /home/fan/workspace/colmap/src
   used as include directory in directory /home/fan/workspace/colmap/src
   used as include directory in directory /home/fan/workspace/colmap/src
   used as include directory in directory /home/fan/workspace/colmap/src
   used as include directory in directory /home/fan/workspace/colmap/src/base
   used as include directory in directory /home/fan/workspace/colmap/src/base
   used as include directory in directory /home/fan/workspace/colmap/src/base
   used as include directory in directory /home/fan/workspace/colmap/src/base
   used as include directory in directory /home/fan/workspace/colmap/src/base
   used as include directory in directory /home/fan/workspace/colmap/src/base
   used as include directory in directory /home/fan/workspace/colmap/src/controllers
   used as include directory in directory /home/fan/workspace/colmap/src/controllers
   used as include directory in directory /home/fan/workspace/colmap/src/controllers
   used as include directory in directory /home/fan/workspace/colmap/src/controllers
   used as include directory in directory /home/fan/workspace/colmap/src/controllers
   used as include directory in directory /home/fan/workspace/colmap/src/controllers
   used as include directory in directory /home/fan/workspace/colmap/src/estimators
   used as include directory in directory /home/fan/workspace/colmap/src/estimators
   used as include directory in directory /home/fan/workspace/colmap/src/estimators
   used as include directory in directory /home/fan/workspace/colmap/src/estimators
   used as include directory in directory /home/fan/workspace/colmap/src/estimators
   used as include directory in directory /home/fan/workspace/colmap/src/estimators
   used as include directory in directory /home/fan/workspace/colmap/src/exe
   used as include directory in directory /home/fan/workspace/colmap/src/exe
   used as include directory in directory /home/fan/workspace/colmap/src/exe
   used as include directory in directory /home/fan/workspace/colmap/src/exe
   used as include directory in directory /home/fan/workspace/colmap/src/exe
   used as include directory in directory /home/fan/workspace/colmap/src/exe
   used as include directory in directory /home/fan/workspace/colmap/src/exe
   used as include directory in directory /home/fan/workspace/colmap/src/feature
   used as include directory in directory /home/fan/workspace/colmap/src/feature
   used as include directory in directory /home/fan/workspace/colmap/src/feature
   used as include directory in directory /home/fan/workspace/colmap/src/feature
   used as include directory in directory /home/fan/workspace/colmap/src/feature
   used as include directory in directory /home/fan/workspace/colmap/src/feature
   used as include directory in directory /home/fan/workspace/colmap/src/mvs
   used as include directory in directory /home/fan/workspace/colmap/src/mvs
   used as include directory in directory /home/fan/workspace/colmap/src/mvs
   used as include directory in directory /home/fan/workspace/colmap/src/mvs
   used as include directory in directory /home/fan/workspace/colmap/src/mvs
   used as include directory in directory /home/fan/workspace/colmap/src/mvs
   used as include directory in directory /home/fan/workspace/colmap/src/optim
   used as include directory in directory /home/fan/workspace/colmap/src/optim
   used as include directory in directory /home/fan/workspace/colmap/src/optim
   used as include directory in directory /home/fan/workspace/colmap/src/optim
   used as include directory in directory /home/fan/workspace/colmap/src/optim
   used as include directory in directory /home/fan/workspace/colmap/src/optim
   used as include directory in directory /home/fan/workspace/colmap/src/retrieval
   used as include directory in directory /home/fan/workspace/colmap/src/retrieval
   used as include directory in directory /home/fan/workspace/colmap/src/retrieval
   used as include directory in directory /home/fan/workspace/colmap/src/retrieval
   used as include directory in directory /home/fan/workspace/colmap/src/retrieval
   used as include directory in directory /home/fan/workspace/colmap/src/retrieval
   used as include directory in directory /home/fan/workspace/colmap/src/sfm
   used as include directory in directory /home/fan/workspace/colmap/src/sfm
   used as include directory in directory /home/fan/workspace/colmap/src/sfm
   used as include directory in directory /home/fan/workspace/colmap/src/sfm
   used as include directory in directory /home/fan/workspace/colmap/src/sfm
   used as include directory in directory /home/fan/workspace/colmap/src/sfm
   used as include directory in directory /home/fan/workspace/colmap/src/tools
   used as include directory in directory /home/fan/workspace/colmap/src/tools
   used as include directory in directory /home/fan/workspace/colmap/src/tools
   used as include directory in directory /home/fan/workspace/colmap/src/tools
   used as include directory in directory /home/fan/workspace/colmap/src/tools
   used as include directory in directory /home/fan/workspace/colmap/src/tools
   used as include directory in directory /home/fan/workspace/colmap/src/util
   used as include directory in directory /home/fan/workspace/colmap/src/util
   used as include directory in directory /home/fan/workspace/colmap/src/util
   used as include directory in directory /home/fan/workspace/colmap/src/util
   used as include directory in directory /home/fan/workspace/colmap/src/util
   used as include directory in directory /home/fan/workspace/colmap/src/util
   used as include directory in directory /home/fan/workspace/colmap/src/ui
   used as include directory in directory /home/fan/workspace/colmap/src/ui
   used as include directory in directory /home/fan/workspace/colmap/src/ui
   used as include directory in directory /home/fan/workspace/colmap/src/ui
   used as include directory in directory /home/fan/workspace/colmap/src/ui
   used as include directory in directory /home/fan/workspace/colmap/src/ui
METIS_LIBRARIES
    linked by target "colmap" in directory /home/fan/workspace/colmap/src

-- Configuring incomplete, errors occurred!
See also "/home/fan/workspace/colmap/build/CMakeFiles/CMakeOutput.log".
See also "/home/fan/workspace/colmap/build/CMakeFiles/CMakeError.log".

I also test it with the ceres-solver 2.0.0 from http://github.com/ceres-solver/ceres-solver/tags.
It comes with the same error.
Is there something wrong with CMake files of colmap?

**Comment by brentyi** [comment]
Can you confirm you have libmetis installed?
`sudo apt-get install libmetis-dev`

**Comment by HandsomeFYM** [comment]
@brentyi  as you say, I forget to install the libmtis-dev.
The colmap can be installed now. 

Thanks very much, guys.
I will close this issue.

**Comment by ahojnnes** [comment]
Does this https://github.com/colmap/colmap/pull/1454 fix the issues?

**Comment by brentyi** [comment]
It would! Though a fix in ceres was also just merged: https://github.com/ceres-solver/ceres-solver/commit/d3612c12c089d6c83bc07037ed7bb4b0e4119d28
