### ISSUE TITLE
Question about the point_triangulator command

### ISSUE THREAD

**Issue by XYZ-qiyh** [colmap/colmap#1459]
Hello, thanks for your amazing project.
Now I'm using the _point_triangulator_ command to reconstruct the sparse model from posed images. The command could work properly. I wonder about the relationship between the **Triangulation** and the **Bundle Adjustment**. Is there any tutorial to understand Triangulation?

Thank you!

**Comment by tsattler** [comment]
Triangulation creates 3D points from a set of correspondences between pixels in images and the camera intrinsics and extrinsics for these images. Bundle adjustment can be used to refine 3D point positions, camera intrinsics, or camera extrinsics (or all of them together). 

Most textbook on Computer Vision should provide more details. I recommend Rick Szeliski's book (https://szeliski.org/Book/).

**Comment by XYZ-qiyh** [comment]
Thanks for your reply. Szeliski's book is really useful!
