### ISSUE TITLE
crash during stereo step of dense reconstruction

### ISSUE THREAD

**Issue by marek999** [colmap/colmap#146]
using all the defaults the work flow goes well until the stereo step of dense reconstruction. Soon after starting that step the application crashes, reporting:

Initialization: 1.0967s
cudaCheckError() with sync failed at C:/Users/jschoenb/Development/colmap/src/mvs/patch_match_cuda.cu:1327 : unknown error
QObject::~QObject: Timers cannot be stopped from another thread

My system consists of:
Windows 10
4.0 GHz AMD FX-8350 8 Core processor
32GB RAM
NVIDIA GeForce GTX 980

**Comment by ahojnnes** [comment]
This is a known issue under all systems and is related to GPU timeouts. It can be solved by following the instructions here: https://colmap.github.io/faq.html#fix-gpu-freezes-and-timeouts-during-dense-reconstruction

**Comment by csiki** [comment]
Hey, I disabled TDR in Nvidia Nsight options, and ran the commands to update the two registry entries as written in the doc you linked. I still get freezing, no difference.
I'm on Win10, GTX 980m, 16GB RAM, colmap version is 3.7, nvidia driver is uptodate.
Is there anything else I can do? Thanks!
