### ISSUE TITLE
Image masks not working?

### ISSUE THREAD

**Issue by noamholz** [colmap/colmap#1460]
Hi,

I wish to use per-image masks, to ignore keypoints that appear within the mask=0 regions.
However, I have no indication that these keypoints are ignored, and I get the impression that they actually aren't.
The GUI "Database Management" shows that the keypoints-to-be-ignored are matched to points in corresponding images:
![image](https://user-images.githubusercontent.com/10523035/158353290-82a62781-f7e0-48cb-952e-f10444e273a5.png)
whereas the mask is:
![image](https://user-images.githubusercontent.com/10523035/158353714-6c0fdbe2-ae4b-432e-a006-7b7546f5fe3a.png)

Here are the steps I followed up to this point:
1. created a directory for the masks
2. for each image I created a corresponding mask, and saved it in the masks directory as a png file with the same file name as the imag. The filenames have the form "out001234.png".
3. each mask file is a png with zero values for the pixels to ignore, where I tried using 255 or 1 for the rest of the pixels, and I tried saving the png as a 3-channel, or single channel.
4. I made sure that each image file has its correct mask counterpart.

Am I doing anything wrong, or am I wrong in thinking that colmap uses these keypoints?

Would appreciate any advice!
Thanks!

**Comment by hummat** [comment]
>> The filenames have the form "out001234.png".

Hi @noamholz, it think the filename needs to have the form `out001234.jpg.png` if your image is named `out001234.jpg`. See e.g. https://colmap.github.io/faq.html#mask-image-regions

**Comment by noamholz** [comment]
@hummat , I somehow missed it.
Thanks a lot!

**Comment by JokerYan** [comment]
> Hello, I've met exactly the same problem except that my mask filenames were in the correct form as '0000.jpg.png'. But my running result seems that masks are not working, exactly like your pictures shown, the 'database management' shows that the keypoints-to-be-ignored are matched. I'm using 0 for ignored pixels and 255 for the rest, neither 3-channel nor single channel works. May I have some advice? Thanks a lot!

I had the same issue just now. In my case, the problem is that I did not clear out the existing feature extracted before I add in the mask. Removing the database and project.ini file in the project folder before creating a new project solves the issue. I hope that this could be helpful.

**Comment by amughrabi** [comment]
> I had the same issue just now. In my case, the problem is that I did not clear out the existing feature extracted before I add in the mask. Removing the database and project.ini file in the project folder before creating a new project solves the issue. I hope that this could be helpful.

I started it from scratch, and I still have the same problem.

**Comment by amughrabi** [comment]
> I had the same issue just now. In my case, the problem is that I did not clear out the existing feature extracted before I add in the mask. Removing the database and project.ini file in the project folder before creating a new project solves the issue. I hope that this could be helpful.

I started it from scratch, and I still have the same problem.

**Comment by Fungungun** [comment]
> > I had the same issue just now. In my case, the problem is that I did not clear out the existing feature extracted before I add in the mask. Removing the database and project.ini file in the project folder before creating a new project solves the issue. I hope that this could be helpful.
> 
> I started it from scratch, and I still have the same problem.

did you solve the problem. I seem to encounter the same issue that mask are not working

**Comment by Fungungun** [comment]
> > > > I had the same issue just now. In my case, the problem is that I did not clear out the existing feature extracted before I add in the mask. Removing the database and project.ini file in the project folder before creating a new project solves the issue. I hope that this could be helpful.
> > > 
> > > 
> > > I started it from scratch, and I still have the same problem.
> > 
> > 
> > did you solve the problem. I seem to encounter the same issue that mask are not working
> 
> The graphical user interface seems to be malfunctioning. It may be better to utilize the command-line interface instead.

I just solved the problem which was caused by the way I saved mask images. So here's what I experienced on macOS. I created masks for each image and save in a folder A and then when I tried to create a colmap project I created a folder B and using os.symlink(folderA/xx.jpg.png, folderB/xx.jpg.png). However the masks in folderB did not work. Then I used os.system("cp folderA/xx.jpg.png folderB/xx.jpg.png") to created the mask images again and it works. 

Anyway problem solved. Thanks
