### ISSUE TITLE
Error for colmap poisson_mesher

### ISSUE THREAD

**Issue by Haian-Jin** [colmap/colmap#1463]
I have followed the instructions on https://colmap.github.io/faq.html to do sparse/dense reconstruction with known camera intrinsics and extrinsics. Thanks for your great work, I got good dense point cloud(fused.ply) as follows.
![image](https://user-images.githubusercontent.com/79512936/158534843-625e7ca4-e551-4d2c-8845-c264656b4fda.png)
 But when I did the poission reconstruction to get the mesh, one strange problem occured: After running on my server for about 5 minitues, I got a very small "meshed-poisson.ply" file(only 2kB size) and it had no mesh when I opened it.
My instruction and output are:
![image](https://user-images.githubusercontent.com/79512936/158535411-6f9d8543-9c8f-4ba2-9a31-288643b9da6c.png)
 
When I used delaunay reconstruction, I can get a mesh file successfully, but it looks very rough. So I want to use the poission reconstruction to test whether I can get a better mesh file.
![image](https://user-images.githubusercontent.com/79512936/158535703-7520e90f-88c4-48fe-9969-a897b5248373.png)

Do you know why I got an uncorrect  "meshed-poisson.ply" file? Thanks you very much for your help.

**Comment by tsattler** [comment]
You could play around with the parameters of the poisson reconstruction process, specifically the `depth` and `trim` parameters (see here for details: https://www.cs.jhu.edu/~misha/Code/PoissonRecon/Version5/).

**Comment by Haian-Jin** [comment]
> You could play around with the parameters of the poisson reconstruction process, specifically the `depth` and `trim` parameters (see here for details: https://www.cs.jhu.edu/~misha/Code/PoissonRecon/Version5/).

Thanks for your reply!
After adjusting some parameters mentioned about, I still can not get the correct output. However, I found I could use the Poission Reconstrution function from Open3D to get a mesh file a few hours ago. Why Colmap can not construct a mesh from the dense point cloud with posion_mesher still confused me.

**Comment by tsattler** [comment]
I'd assume that there are either some different parameters or different post processing steps. As far as I know, both use the same code for the poisson reconstruction step. If you want to know why the results differ, you could have a look at how both programs call the poisson reconstruction algorithm.

**Comment by Haian-Jin** [comment]
> I'd assume that there are either some different parameters or different post processing steps. As far as I know, both use the same code for the poisson reconstruction step. If you want to know why the results differ, you could have a look at how both programs call the poisson reconstruction algorithm.

Thanks. I will have a look on their algorithms.
