### ISSUE TITLE
Using known camera pose information from Blender.

### ISSUE THREAD

**Issue by ciarancoady98** [colmap/colmap#1467]
I am trying to reconstruct a synthetic scene from blender using COLMAP. The goal is to compare the reconstructed model to the original blender model and assess the reconstruction quality. I intend to then vary different environmental factors such as lighting and measure their impact on the reconstruction quality.

Object of interest:
![image](https://user-images.githubusercontent.com/46931188/158570106-617e6e39-6b56-42db-91a4-a0a467a87684.png)

I have captured a small number of images (54) from cameras placed in a circular pattern around the object of interest (with the object centred on the origin in blender). To ensure the reconstruction uses the same coordinate setup as Blender, I have supplied camera pose information directly from blender following this guide - https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses. However, this results in very poor reconstruction results and incorrect camera placement when compared to the automatic reconstruction. I believe this is due to the camera pose information I supply to the images.txt file.

Automatic reconstruction : 
![image](https://user-images.githubusercontent.com/46931188/158567302-a2dd4574-4d7a-4db5-979f-b5bc0fd23c5c.png)
Manually supplied pose reconstruction : 
![image](https://user-images.githubusercontent.com/46931188/158567403-8de1fc7a-cfd5-4210-b223-052f8d77c6df.png)

I am outputting quaternion pose information from blender to the images.txt file using the same ordering as found in the COLMAP database. Example entry `0 0.5673067569732666 0.4220936596393585 0.42209362983703613 0.5673067569732666 20.0 0.0 6.0 1 progcam0.png`. From reading the COLMAP documentation I know that the images.txt file contains the camera space rotation (R) and translation (T) vectors. To get world space coordinates we must perform `-R^t * T` to those values.

**My question :**
What must I do to the Blender world space translation and rotation vectors to have them in the correct form for COLMAP?

**Comment by tsattler** [comment]
First thing to figure out is probably whether Blender uses the same camera coordinate system as Colmap (camera is looking down the z-axis, with the x-axis pointing right and the y-axis pointing down) or not. In the latter case, you will need to adjust the transformations. I'd suspect that Blender uses the camera coordinate system typically used in Computer Graphics (camera is looking down the -z-axis, the x-axis is pointing to the right and the y-axis is pointing up). I am sure there is an issue describing the transformation.

Can you describe which information you get from Blender and how you derive the Colmap poses from that information?

**Comment by ciarancoady98** [comment]
@tsattler Thanks so much for your response! This has been driving me mad for the last couple of days xD

From what I can find, Blender uses the right hand coordinate system with the z axis pointing up. Which is shown by this indicator in the editor. 

![image](https://user-images.githubusercontent.com/46931188/159226447-f84cf765-859f-4e36-ab3c-d72e007e729c.png)

Below is a screenshot of my capture setup. I have a model of interest centred on the origin and a number of cameras placed in a circular pattern around it.

![image](https://user-images.githubusercontent.com/46931188/159225007-9f053d53-add8-42c9-890d-53d62589c8a3.png)

To output the translation and rotation of a camera, I am using the x, y, z coordinates and rotation quaternion shown on the right. 

![image](https://user-images.githubusercontent.com/46931188/159225242-f71aa8fa-04f6-4c70-bc15-4664c9c1cdd6.png)

I have a little script which takes these values and populates the `images.txt` file for COLMAP. The first code snippet shows the function which takes a camera as a parameter and extracts its translation and quaternion. The second code snippet shows my file writing code which takes a list of cameras and populates `images.txt`.

```python
def get_position_details_json(object):
        world_matrix = object.matrix_world
        blender_translation, blender_rotation, blender_scale = world_matrix.decompose()
        return {
            "name" : object.name,
            "x_pos" : blender_translation[0],
            "y_pos" : blender_translation[1],
            "z_pos" : blender_translation[2],
            "w_rotation" : blender_rotation.w,
            "x_rotation" : blender_rotation.x,
            "y_rotation" : blender_rotation.y,
            "z_rotation" : blender_rotation.z
        }
```

```python
def write_camera_poses_to_text_file(file_path, camera_details):
    try:
        write_file = open(file_path,'w')
        camera_details.sort(key=lambda x : x['name'].strip('progcam'))
        for i, camera in enumerate(camera_details): 
            # TODO : string formatting
            write_file.writelines(str(i + 1) + " " + str(camera['w_rotation']) + " " + str(camera['x_rotation']) + " " + str(camera['y_rotation']) + " " + str(camera['z_rotation']) + " " + str(camera['x_pos']) + " " + str(camera['y_pos']) + " " + str(camera['z_pos']) + " 1 " + camera['name'] + ".png\n")    
            write_file.writelines("\n")
        write_file.close()
    except Exception as e:
        print(e)
```

After reading your response I dug deeper into the coordinate system being used by Blender and noticed if we apply a 90 degree rotation around the x axis, it should result in the same setup as COLMAP expects (I've included my scribbles).

![image](https://user-images.githubusercontent.com/46931188/159225482-39bee5c7-3f8e-4014-aa34-c45b84c98914.png)

I then updated my code to perform this rotation, as given below.

```python
def get_position_details_json(object):
        world_matrix = object.matrix_world
        # Rotate by 90 degrees around the x axis
        rotation_around_x_axis = mathutils.Matrix.Rotation(math.radians(90.0), 4, 'X')
        new_world_matrix = rotation_around_x_axis @ world_matrix
        blender_translation, blender_rotation, blender_scale = new_world_matrix.decompose()
        return {
            "name" : object.name,
            "x_pos" : blender_translation[0],
            "y_pos" : blender_translation[1],
            "z_pos" : blender_translation[2],
            "w_rotation" : blender_rotation.w,
            "x_rotation" : blender_rotation.x,
            "y_rotation" : blender_rotation.y,
            "z_rotation" : blender_rotation.z
        }
```

However, with this change COLMAP is still not happy.

![image](https://user-images.githubusercontent.com/46931188/159230507-f1d92325-db3c-42bf-98ef-10531ad3ffd2.png)
![image](https://user-images.githubusercontent.com/46931188/159230540-7c831076-db5b-4831-97e1-5833c3a7bb1a.png)

I have fiddled around further with the coordinates, swapping z with -y and swapping y with z etc but still no dice.

I think there is a gap in my understanding of the coordinate system setup. I believe what I am outputting at the moment from Blender are the world space coordinates and pose of each camera, but I know COLMAP outputs to `images.txt` in camera space? So should I be doing something here differently right?

Thanks for your help!

**Comment by simogasp** [comment]
maybe this can help you
https://medium.com/check-visit-computer-vision/converting-camera-poses-from-opencv-to-opengl-can-be-easy-27ff6c413bdb

**Comment by ciarancoady98** [comment]
> maybe this can help you
> https://medium.com/check-visit-computer-vision/converting-camera-poses-from-opencv-to-opengl-can-be-easy-27ff6c413bdb

Thanks for your response @simogasp! That link was what I needed to fill in the gaps in my knowledge. I also found some additional info and code snippets here : https://blog.expertise.dev/2021-06-28-Transforming-coordinates-from-Blender-To-OpenCV/.

With these resources I was able to get my code working and understand the previous errors in what I was doing. The coordinates I was retrieving in blender were indeed world space and I was not correctly transforming them into COLMAP's view space as needed. To get it working you must transform the blender world space coordinates & rotation into blender view space, then transform them into COLMAP's view space.

For anyone interested, here's the code I am now using:
```python
def get_position_details_json(object):
    world_matrix = object.matrix_world
    blender_to_colmap_rotation = np.diag([1,-1,-1])
    # Convert from blender world space to view space
    blender_world_translation, blender_world_rotation, blender_world_scale = world_matrix.decompose()
    blender_view_rotation = blender_world_rotation.to_matrix().transposed()
    blender_view_translation = -1.0 * blender_view_rotation @ blender_world_translation
    # Convert from blender view space to colmap view space
    colmap_view_rotation = blender_to_colmap_rotation @ blender_view_rotation
    colmap_view_rotation_quaternion = mathutils.Matrix(colmap_view_rotation).to_quaternion()
    colmap_view_translation = blender_to_colmap_rotation @ blender_view_translation
    return {
            "name" : object.name,
            "x_pos" : colmap_view_translation[0],
            "y_pos" : colmap_view_translation[1],
            "z_pos" : colmap_view_translation[2],
            "w_rotation" : colmap_view_rotation_quaternion.w,
            "x_rotation" : colmap_view_rotation_quaternion.x,
            "y_rotation" : colmap_view_rotation_quaternion.y,
            "z_rotation" : colmap_view_rotation_quaternion.z
        }
```

With this COLMAP was able to successfully read in the supplied cameras and perform a sparse reconstruction!
![image](https://user-images.githubusercontent.com/46931188/159275408-05a22ba6-b84f-4c81-a440-286ab9a793e4.png)

Thanks so much @tsattler @simogasp for your help!!

**Comment by SBCV** [comment]
You might be interested in https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer

**Comment by ThomasParistech** [comment]
> maybe this can help you https://medium.com/check-visit-computer-vision/converting-camera-poses-from-opencv-to-opengl-can-be-easy-27ff6c413bdb

@ciarancoady98
You might find this follow-up Medium article interesting as well.
The goal is to implement a class in Python that handles/eases the conversion of camera matrices between different axes conventions, e.g. from Colmap to Blender

https://medium.com/check-visit-computer-vision/convert-camera-poses-in-python-35debb8460ec
