### ISSUE TITLE
Colmap Dependency Addition:

### ISSUE THREAD

**Issue by asad-ak** [colmap/colmap#1469]
While installing colmap recently I faced a lot of issues related to CMAKE, I got a huge error (summarizing it) saying: 
**CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
METIS_INCLUDE_DIRS**

This error came about on the step "Configuring and Compiling Colmap" on the line:
`cmake .. `
I searched for this error on google to look for a solution, I found nothing really helpful other than the fact that in some other repositories like colmap the` METIS_INCLUDE_DIRS` was named something else, this is a package that is needed by the repository to install.

The fix for this solution after looking at the colmap files on github was to install a package as mentioned above "Metis". The command that got me through this problem was:
`sudo apt-get install libmetis-dev  ` 

This command before invoking the cmake command helped me solve this issue! I hope everyone who has trouble with this refers to this message and I would like the creators to put this in the list of dependencies for colmap.

Thank you!

I was using 
Ubuntu 20.04 (WSL2)

**Comment by orsveri** [comment]
@asad-ak Thank you so much! You saved my day!
I encountered the same error, and your fix worked like a charm.
(Ubuntu 20.04.2 LTS)

**Comment by ahojnnes** [comment]
It's already documented as such in the markdown files in the git repository, but I have not had time to compile these into an HTML and push them to colmap.github.io. Will do now...
