### ISSUE TITLE
Colmap error: No good initial pair found at reconstruction

### ISSUE THREAD

**Issue by asad-ak** [colmap/colmap#1472]
I tried using colmap firstly on my own dataset but got the same error as mentioned above. I searched the web and found that probably my images are not up to par with the requirements of colmap. So I tried using it on a Lego dataset that was used in NERF (Neural Radiance Fields) but I got the same error 
![image](https://user-images.githubusercontent.com/99788403/160339781-0e17f7a5-a207-412d-a0f7-e94bee946430.png)

I tried using both the GUI of colmap and also the LLFF repository for getting the dimesions and poses of my images for it to be trained on the NERF model.
Tried on both Ubuntu and Windows.

Can someone please help me with what is going on?

**Comment by ferreram** [comment]
Colmap will create multiple 3D models if it cannot register every images into a single model.  Hence, if a few of images cannot be registered into the current model, Colmap is going to try to initialize a new 3D model.  The fact that it ends up with "No good initial pair found." simply means that it could not initialize a new 3D model from the remaining images (i.e. the ones not registered in the already reconstructed models).

**Comment by tsattler** [comment]
Reducing the number of feature matches required to initialize a model could help here. Also, reducing the number of matches / inliers required to add a new camera can help to prevent having multiple models in the first place.

**Comment by asad-ak** [comment]
The same program is running on my colleagues laptop, that calculates the depths with the same dataset but is not working on mine. I do not think there is any problem in the installation since the gui and headers show up on their respective commands. What do you recommend me doing other than reducing the number of features and number of matches/inliers?

**Comment by asad-ak** [comment]
> Reducing the number of feature matches required to initialize a model could help here. Also, reducing the number of matches / inliers required to add a new camera can help to prevent having multiple models in the first place.

I tried doing this but to no avail

**Comment by tsattler** [comment]
Hard to say without knowing anything about both machines. I assume you have a weaker GPU and get less features extracted? The number of features extracted by the GPU implementation of SIFT depends on the GPU (more specifically, which image size still fits into the memory of the GPU). You can try using the CPU implementation of feature extraction (and maybe matching).

**Comment by asad-ak** [comment]
I am always using the CPU I do not have a GPU.

**Comment by asad-ak** [comment]
> Hard to say without knowing anything about both machines. I assume you have a weaker GPU and get less features extracted? The number of features extracted by the GPU implementation of SIFT depends on the GPU (more specifically, which image size still fits into the memory of the GPU). You can try using the CPU implementation of feature extraction (and maybe matching).

I am always using the CPU I do not have a GPU.

**Comment by asad-ak** [comment]
> Hard to say without knowing anything about both machines. I assume you have a weaker GPU and get less features extracted? The number of features extracted by the GPU implementation of SIFT depends on the GPU (more specifically, which image size still fits into the memory of the GPU). You can try using the CPU implementation of feature extraction (and maybe matching).

Ok so the issue that I am facing is with spherical (360) inward-facing images. When I run colmap on these images/scenes it does not calculate the relevant poses for me. Do I need to pass in some special argument or a parameter for the poses to be generated for these spherical scenes?

**Comment by tsattler** [comment]
Colmap currently does not support spherical (360) images. They are not compatible to the currently available camera models.

**Comment by ynma-hanvo** [comment]
> Colmap currently does not support spherical (360) images. They are not compatible to the currently available camera models.

so do you have any suggestions for how to generate the poses for training such 360 inward facing scene. [ by the way, if it is able to work for 360 outward facing scene like turn around  in a room ]

**Comment by kashyappiyush1998** [comment]
Solved by increasing images fps from video for instant-ngp use case

**Comment by bfalchuk** [comment]
So basically it means take more photos. ?  I'm getting this error as well... I'll try to take a more dense set, i guess?

**Comment by muye1202** [comment]
> Reducing the number of feature matches required to initialize a model could help here. Also, reducing the number of matches / inliers required to add a new camera can help to prevent having multiple models in the first place.

May I ask where are these parameters defined? It seems I could not change them when calling `colmap mapper` from cmd line

**Comment by hhhjjy** [comment]
you can try to find the parameter min_model_size.It is the min pictures that a model have.
