### ISSUE TITLE
LocalParameterizations are deprecated in Ceres Solver 2.1.0

### ISSUE THREAD

**Issue by sandwichmaker** [colmap/colmap#1475]
``ceres::LocalParameterization`` has been deprecated in the latest version of Ceres Solver (v 2.1.0) and will be removed going forward. ColMap only uses standard local parameterizations that ship with Ceres Solver for which the corresponding new ``ceres::Manifold`` objects are available and are drop in replacements.

**Comment by ahojnnes** [comment]
Done here: https://github.com/colmap/colmap/pull/1477
