### ISSUE TITLE
Understanding COLMAP's Camera Poses and Depth Data

### ISSUE THREAD

**Issue by ThakurSarveshGit** [colmap/colmap#1476]
Hi all,

I have a dataset containing building images and I have performed both sparse and dense reconstruction from it. Thus, I have access to the depth data and all camera poses and camera intrinsic.

**Goal**: I want to select few pixels of interest from some of the images and project only those points in the world frame.

**Motivation**: I have similar looking patterns in the dataset and COLMAP mismatches the structure when I build the entire dataset. Hence, I selected few good camera poses(which reconstructed well) and wanted to create the building roof structure using those camera poses only.

**Progress/Algorithm**: I take a pixel of interest from one of the image, compute a ray from that camera center to the 3D point in the world and scale that ray using the corresponding depth value from the geometric depth file of that image. This leads to correct structure representation in the world frame for the current camera pose.

For better understanding, I have attached one of the building image, a mask of the roof(pixel of interest are the contour points of the red mask) and the projected structure in 3D. The structure looks correct to me. (Even though I realized that I might be using incorrect intrinsic from sparse reconstruction rather than dense reconstruction).

![00399](https://user-images.githubusercontent.com/46443179/161126924-20df89d5-6fc0-470d-af3e-e20c0a93eddd.jpg)
![00399](https://user-images.githubusercontent.com/46443179/161126939-54bc68fa-6566-4ad2-a1f6-1f3cf72bc928.png)
![00399-3D](https://user-images.githubusercontent.com/46443179/161126955-6ee9cb37-162b-4490-b9f9-d5832752f077.PNG)

**Issue**: For individual images, everything looks right but when I combine these individual point clouds from different poses, they are misaligned! I have attached point cloud image from two camera poses 3D points combined:

![Misaligned](https://user-images.githubusercontent.com/46443179/161127364-ebeab9ae-9310-4c08-b415-d36b7a56e976.png)

**Current understanding of Issue**: My understanding of the problem is that I am not starting with the correct location of the camera in the world frame to begin with. Hence the ray connecting the camera origin to the world point is in the wrong direction. Here is the part of my code which generates the world points for camera's pixel of interest. In the code **R** and **t** are passed from images.txt file (converting quaternion to rotation matrix).

```       
def Get3Dfrom2D_DepthMaps(List2D, K, R, t, depth_map, scale=1, debug=False, dataFolder=r"data/img"):
	
        # List2D : n x 2 array of pixel locations in an image
	# K : Intrinsic matrix for camera
	# R : Rotation matrix describing rotation of camera frame
	# 	  w.r.t world frame.
	# t : translation vector describing the translation of camera frame
	# 	  w.r.t world frame
	# [R t] combined is known as the Camera Pose.
	# depth_map : depth map obtained from bin file corresponding to that image
	List2D = np.array(List2D)
	List3D = []
	# t.shape = (3,1)
	print('depth_map: ', depth_map.shape)
	depth_map_copy = depth_map
	min_depth, max_depth = np.percentile(depth_map, [5, 95])

	for p in List2D:
		# skip if index is out of bound
		if p[1] >= depth_map.shape[0] or p[0] >= depth_map.shape[1]:
			continue

		# Homogeneous pixel coordinate
		p = np.array([p[0], p[1], 1]).T; p.shape = (3,1)
		# print("pixel: \n", p)

		# Transform pixel in Camera coordinate frame
		pc = np.linalg.inv(K) @ p
		# print("pc : \n", pc, pc.shape)

		# Transform pixel in World coordinate frame
		pw = t + (R@pc)
		# print("pw : \n", pw, t.shape, R.shape, pc.shape)

		# Transform camera origin in World coordinate frame
		cam = np.array([0,0,0]).T; cam.shape = (3,1)
		cam_world = t + R @ cam
		# print("cam_world : \n", cam_world)

		# Find a ray from camera to 3d point
		vector = pw - cam_world
		unit_vector = vector / np.linalg.norm(vector)
		# print("unit_vector : \n", unit_vector)
		
		# Point scaled along this ray
		p3D = cam_world + scale*depth_map[p[1], p[0]] * unit_vector
		if debug:
			depth_map_copy[p[1],p[0]] = max_depth + (max_depth+min_depth)/2

		# print("p3D : \n", p3D)
		List3D.append(p3D)

	if debug:
		plt.imshow(depth_map_copy)
		plt.savefig(dataFolder + '_depth_map_points.png')
		plt.show()

	return List3D
```

**Code Walkdown**:

*Camera Pose* is the camera's location/orientation w.r.t the world whereas its *Extrinsics* are inverse of Camera Pose Transformation. What COLMAP provides is the Camera Pose for each of the images taken by the camera. For projecting a 3D point in the camera plane, one would use *Camera Extrinsics* whereas for projecting pixels out to the world, one needs *Camera Pose*. Here is how I approached the problem:

 1. I manually(later automated) selected the pixels of interest and stored them in a list, *List2D*.
 2. Augmented the *List2D* (*nx2* array) for homogeneous coordinates(*nx3* array).
 3. Tranform each pixel coordinate, *p* in Camera frame using inverse of camera intrinsic matrix, *K*.

    > p<sub>c</sub> = K<sup>-1</sup> p

 4. Transform the point, p<sub>c</sub> from camera frame to world frame, using the Camera Pose, T = [R | t]
    > p<sub>w</sub> = T p<sub>c</sub>

 5. Transform the camera origin, *cam_origin = (0,0,0)* from camera frame to world frame
    > cam_origin<sub>w</sub> = T cam_origin

 6. Get a unit vector, *v* along the ray passing from the camera origin to the 3D point. Our 3D point of interest lies along this ray. To traverse on this ray, we can parametrize the vector and move along this ray.

**_Can someone point out what I am doing wrong? Looks like some fundamental misunderstanding either how COLMAP camera poses work or math behind the finding of ray connecting camera center to world 3D point._**

**Comment by tsattler** [comment]
Colmap's camera poses transform from world to camera coordinates, not the other way around, see https://colmap.github.io/format.html#images-txt .

**Comment by ThakurSarveshGit** [comment]
@tsattler oh okay, I will post my results with that in few hours. Thanks for clarifying.

**Comment by ThakurSarveshGit** [comment]
@tsattler Thanks for the clarification.

Here is what I tried:

1) I took two consecutive images in the sequence. Instead of using [R, t] as transformations from camera coordinates to world, I used [R.T, -t] as the transformations. Previous results are on the left while the new results are on the right.

![63-64](https://user-images.githubusercontent.com/46443179/161180172-d005183f-7894-497e-930f-1cd58c080433.jpg)

2) I took two images from the dataset(with considerable motion in between camera poses) as well:

![63-394](https://user-images.githubusercontent.com/46443179/161180299-4021f9e9-dd38-4461-bc11-bd06c44b7dd1.jpg)


First image definitely looks aligned, second sequence's also aligned a lot more than before but it seems they still have some translation offset. Both sequences look correctly oriented.

Any thoughts why this is happening?

**Comment by ferreram** [comment]
The inverse transformation is [R.T, - R.T.dot(t)] and not [R.T, -t].

**Comment by ThakurSarveshGit** [comment]
Thank you @tsattler @ferreram! That fixed my mis-alignment issue, I now have an aligned point cloud. Though alignment will be improved further, I hope, when I use intrinsics for each camera pose from cameras.txt in the dense reconstruction.

For consecutive camera poses: 

![63-64-Aligned](https://user-images.githubusercontent.com/46443179/161611472-d7484208-267f-4aed-b590-620bd3485707.PNG)

For far-away camera poses:

![63-399-Aligned](https://user-images.githubusercontent.com/46443179/161611612-927d5601-1de2-4c13-9ebc-15feb8fb641b.PNG)

**Comment by alexs7** [comment]
@ThakurSarveshGit 
Do you have the maths source for this: 

```
# Point scaled along this ray
p3D = cam_world + scale*depth_map[p[1], p[0]] * unit_vector
```

The `cam_world` is added to offset the unit vector ?

**Comment by ThakurSarveshGit** [comment]
> @ThakurSarveshGit Do you have the maths source for this:
> 
> ```
> # Point scaled along this ray
> p3D = cam_world + scale*depth_map[p[1], p[0]] * unit_vector
> ```
> 
> The `cam_world` is added to offset the unit vector ?

Hi @alexs7 ,sorry for the late reply.

```scale*depth_map[p[1], p[0]] * unit_vector``` represents the ray vector from cam origin in the world frame to the 3d point (again in the world frame)

```cam_world``` is the position of the camera origin in the world frame. Adding this vector to the above results in a vector from cam_origin to 3d point in world frame.

For a single image, not adding ```cam_world``` is fine as well but when you have a moving camera, you need to update the position of the camera to align the the rays coming out of it.

**Comment by alexs7** [comment]
Ok thanks. Not adding ```cam_world``` will only make sense if the camera is at the world origin right ?
The rotation component is contained in the unit vector I assume ?

**Comment by ThakurSarveshGit** [comment]
> Ok thanks. Not adding `cam_world` will only make sense if the camera is at the world origin right ?

Yes

> The rotation component is contained in the unit vector I assume ?
So, rotation component is actually contained both in the ```cam_world``` and ```pw```(and thus ```unit_vector```) computation. Of course, this is not required if I have only a single instance where I am converting a 2D pixel to 3D point. But since I wanted to merge point clouds from all images, I had to take into account that the ray(```unit_vector```) is in the correct direction.

**Comment by alexs7** [comment]
Just to get a better understanding, by ```depth``` here you mean you have value in metric scale ?
For example for pixel [3,4] from frame 1 has a depth value of 5, that is 5 meters ?

Reason I am asking is because if you already have the points in 3D and the camera centre in 3D; the depth should just be the Euclidean distance between both, but  that won't make much sense if is not in metric ?

**Comment by ThakurSarveshGit** [comment]
We lose the actual depth when image is formed. So, if I do not use COLMAP's provided depth, I can only project the points into the 3d world but at a scale.
> Reason I am asking is because if you already have the points in 3D and the camera centre in 3D; the depth should just be the Euclidean distance between both, but that won't make much sense if is not in metric ?

Yes, only if we have the true 3d point and camera center, the euclidean distance is the depth.

**Comment by ThakurSarveshGit** [comment]
My reason for performing this task was this:
I had a noisy reconstruction from COLMAP(camera poses were correct for only few of the images in the sequence) and I was interested in only outlining the building structure in the scene. So, I selected the correct poses, took transformation information from ```cameras.txt```, selecting few pixels of interest in the image and projected them in 3D. Initially, I didn't use the depth information provided, as it worked fine for my case. To do that, I used a constant scale factor(```d```), which was essentially selecting a point along the unit ray to the 3d point, but at a euclidean distance of ```d```. But this will result in warping the points further from the camera(scene farther away from the camera). Hence, to check if everything was working correctly, i used the depth information provided from COLMAP.

Alternatively, you can directly project the point cloud from depth information. For sequence of depth images, you will need to align the point clouds using the odometry information(```cameras.txt```).

**Comment by alexs7** [comment]
Ok thanks. I am working on enhancing Reality Capture models, for localisation. I take the models from Reality Capture, as fbx, and the camera poses it provides and load them all in Open3D. Open3D can generate depth maps, but that value again makes not much sense. For example a depth value for a pixel can be 1000. I am in the process of adding metric info to the model. If you are interested I can email you.

**Comment by ThakurSarveshGit** [comment]
Sure, I would be interested in knowing more ([contact](thakursarvesh89@gmail.com)). I think Open3D might be scaling the depth images. But just curious, what method are you using to create depth images?

> I take the models from Reality Capture, as fbx, and the camera poses it provides and load them all in Open3D, add features etc.

Will something like [this](http://www.open3d.org/docs/0.7.0/tutorial/Advanced/customized_visualization.html) be helpful?

**Comment by alexs7** [comment]
Ok emailed you!

**Comment by hplegend** [comment]
@ThakurSarveshGit Following you great idea, I can't align different view successfully.  This is my result:
![image](https://user-images.githubusercontent.com/24842574/205443990-2e4bc57e-1c0d-4482-8419-5a72e84661e8.png)

And my code as follow:
`def Get3Dfrom2D_DepthMaps(rgb_array, K, R, t, depth_map, scale=1, debug=False, dataFolder=r"data/img"):
    # List2D : n x 2 array of pixel locations in an image
    # K : Intrinsic matrix for camera
    # R : Rotation matrix describing rotation of camera frame
    # 	  w.r.t world frame.
    # t : translation vector describing the translation of camera frame
    # 	  w.r.t world frame
    # [R t] combined is known as the Camera Pose.
    # depth_map : depth map obtained from bin file corresponding to that image
    List3D = []
    # t.shape = (3,1)
    print('depth_map: ', depth_map.shape)
    print('image: ', depth_map.shape)
    depth_map_copy = depth_map
    min_depth, max_depth = np.percentile(depth_map, [0, 100])

    for v in range(depth_map.shape[0]):
        for u in range(depth_map.shape[1]):
            # if rgb_array[v, u, 0] < 1 or rgb_array[v, u, 1] < 1 or rgb_array[v, u, 2] < 1:
            #     continue
            p = [u, v]
            # skip if index is out of bound
            # if p[1] >= depth_map.shape[0] or p[0] >= depth_map.shape[1]:
            #     continue

            # Homogeneous pixel coordinate
            p = np.array([p[0], p[1], 1])
            # p.shape = (3, 1)
            # print("pixel: \n", p)

            # Transform pixel in Camera coordinate frame
            pc = np.linalg.inv(K) @ p
            # print("pc : \n", pc, pc.shape)

            # Transform pixel in World coordinate frame
            # pw = -R.T @ t + (R.T @ pc)
            # pw = -t + (R.T @ pc)
            pw = R.T @ (-t + pc)
            # print("pw : \n", pw, t.shape, R.shape, pc.shape)

            # Transform camera origin in World coordinate frame
            cam = np.array([0, 0, 0])
            # cam.shape = (3, 1)
            cam_world = R.T @ (-t + cam)
            # print("cam_world : \n", cam_world)

            # Find a ray from camera to 3d point
            vector = pw - cam_world
            unit_vector = vector / np.linalg.norm(vector)
            # print("unit_vector : \n", unit_vector)

            # Point scaled along this ray
            p3D = cam_world + scale * depth_map[p[1], p[0]] * unit_vector
            if debug:
                depth_map_copy[p[1], p[0]] = max_depth + (max_depth + min_depth) / 2

            # print("p3D : \n", p3D)
            List3D.append(p3D)

    if debug:
        plt.imshow(depth_map_copy)
        plt.savefig(dataFolder + '_depth_map_points.png')
        plt.show()

    return List3D`

Any wrong with my code?

**Comment by yuanjie0217** [comment]
Hello, my data set is SAR image data. The camera posture is a fixed distance from the target building and a fixed height surround imaging method, and the center of the camera can be regarded as unchanged. I have imaged a total of 72 images, every 5 degrees. Imaging once, and then I want to customize the camera posture, which is the content of colmap's image.txt file, but I don't know how to convert my known posture into the values of the seven parameters of the quaternion and translation vector in this file , please help me understand the specific implementation process of the parameters in the image.txt file in colmap, thank you!

**Comment by alexs7** [comment]
If you have world camera poses I guess you can convert those into camera coordinate  and insert them into the images.txt file.

**Comment by bw4sz** [comment]
@hplegend were you able to confirm this piece of code. I have the same issue, but I don't need to multiply by the depth map since my images are taken from far away and are basically 2D reconstructions. Can you paste your final attempt?

**Comment by Abbsalehi** [comment]
> Hi all,
> 
> I have a dataset containing building images and I have performed both sparse and dense reconstruction from it. Thus, I have access to the depth data and all camera poses and camera intrinsic.
> 
> **Goal**: I want to select few pixels of interest from some of the images and project only those points in the world frame.
> 
> **Motivation**: I have similar looking patterns in the dataset and COLMAP mismatches the structure when I build the entire dataset. Hence, I selected few good camera poses(which reconstructed well) and wanted to create the building roof structure using those camera poses only.
> 
> **Progress/Algorithm**: I take a pixel of interest from one of the image, compute a ray from that camera center to the 3D point in the world and scale that ray using the corresponding depth value from the geometric depth file of that image. This leads to correct structure representation in the world frame for the current camera pose.
> 
> For better understanding, I have attached one of the building image, a mask of the roof(pixel of interest are the contour points of the red mask) and the projected structure in 3D. The structure looks correct to me. (Even though I realized that I might be using incorrect intrinsic from sparse reconstruction rather than dense reconstruction).
> 
> ![00399](https://user-images.githubusercontent.com/46443179/161126924-20df89d5-6fc0-470d-af3e-e20c0a93eddd.jpg) ![00399](https://user-images.githubusercontent.com/46443179/161126939-54bc68fa-6566-4ad2-a1f6-1f3cf72bc928.png) ![00399-3D](https://user-images.githubusercontent.com/46443179/161126955-6ee9cb37-162b-4490-b9f9-d5832752f077.PNG)
> 
> **Issue**: For individual images, everything looks right but when I combine these individual point clouds from different poses, they are misaligned! I have attached point cloud image from two camera poses 3D points combined:
> 
> ![Misaligned](https://user-images.githubusercontent.com/46443179/161127364-ebeab9ae-9310-4c08-b415-d36b7a56e976.png)
> 
> **Current understanding of Issue**: My understanding of the problem is that I am not starting with the correct location of the camera in the world frame to begin with. Hence the ray connecting the camera origin to the world point is in the wrong direction. Here is the part of my code which generates the world points for camera's pixel of interest. In the code **R** and **t** are passed from images.txt file (converting quaternion to rotation matrix).
> 
> ```
> def Get3Dfrom2D_DepthMaps(List2D, K, R, t, depth_map, scale=1, debug=False, dataFolder=r"data/img"):
> 	
>         # List2D : n x 2 array of pixel locations in an image
> 	# K : Intrinsic matrix for camera
> 	# R : Rotation matrix describing rotation of camera frame
> 	# 	  w.r.t world frame.
> 	# t : translation vector describing the translation of camera frame
> 	# 	  w.r.t world frame
> 	# [R t] combined is known as the Camera Pose.
> 	# depth_map : depth map obtained from bin file corresponding to that image
> 	List2D = np.array(List2D)
> 	List3D = []
> 	# t.shape = (3,1)
> 	print('depth_map: ', depth_map.shape)
> 	depth_map_copy = depth_map
> 	min_depth, max_depth = np.percentile(depth_map, [5, 95])
> 
> 	for p in List2D:
> 		# skip if index is out of bound
> 		if p[1] >= depth_map.shape[0] or p[0] >= depth_map.shape[1]:
> 			continue
> 
> 		# Homogeneous pixel coordinate
> 		p = np.array([p[0], p[1], 1]).T; p.shape = (3,1)
> 		# print("pixel: \n", p)
> 
> 		# Transform pixel in Camera coordinate frame
> 		pc = np.linalg.inv(K) @ p
> 		# print("pc : \n", pc, pc.shape)
> 
> 		# Transform pixel in World coordinate frame
> 		pw = t + (R@pc)
> 		# print("pw : \n", pw, t.shape, R.shape, pc.shape)
> 
> 		# Transform camera origin in World coordinate frame
> 		cam = np.array([0,0,0]).T; cam.shape = (3,1)
> 		cam_world = t + R @ cam
> 		# print("cam_world : \n", cam_world)
> 
> 		# Find a ray from camera to 3d point
> 		vector = pw - cam_world
> 		unit_vector = vector / np.linalg.norm(vector)
> 		# print("unit_vector : \n", unit_vector)
> 		
> 		# Point scaled along this ray
> 		p3D = cam_world + scale*depth_map[p[1], p[0]] * unit_vector
> 		if debug:
> 			depth_map_copy[p[1],p[0]] = max_depth + (max_depth+min_depth)/2
> 
> 		# print("p3D : \n", p3D)
> 		List3D.append(p3D)
> 
> 	if debug:
> 		plt.imshow(depth_map_copy)
> 		plt.savefig(dataFolder + '_depth_map_points.png')
> 		plt.show()
> 
> 	return List3D
> ```
> 
> **Code Walkdown**:
> 
> _Camera Pose_ is the camera's location/orientation w.r.t the world whereas its _Extrinsics_ are inverse of Camera Pose Transformation. What COLMAP provides is the Camera Pose for each of the images taken by the camera. For projecting a 3D point in the camera plane, one would use _Camera Extrinsics_ whereas for projecting pixels out to the world, one needs _Camera Pose_. Here is how I approached the problem:
> 
> 1. I manually(later automated) selected the pixels of interest and stored them in a list, _List2D_.
> 2. Augmented the _List2D_ (_nx2_ array) for homogeneous coordinates(_nx3_ array).
> 3. Tranform each pixel coordinate, _p_ in Camera frame using inverse of camera intrinsic matrix, _K_.
>    > pc = K-1 p
> 4. Transform the point, pc from camera frame to world frame, using the Camera Pose, T = [R | t]
>    > pw = T pc
> 5. Transform the camera origin, _cam_origin = (0,0,0)_ from camera frame to world frame
>    > cam_originw = T cam_origin
> 6. Get a unit vector, _v_ along the ray passing from the camera origin to the 3D point. Our 3D point of interest lies along this ray. To traverse on this ray, we can parametrize the vector and move along this ray.
> 
> **_Can someone point out what I am doing wrong? Looks like some fundamental misunderstanding either how COLMAP camera poses work or math behind the finding of ray connecting camera center to world 3D point._**

Should the shape of the depth map be the same as the original image you manually selected for your 2D-pixel points?

**Comment by Abbsalehi** [comment]
@ThakurSarveshGit, I still have a little bit of a shift in the Z component of the 3D point. Is there something I have missed?

**Comment by 2cu-1001** [comment]
> The inverse transformation is [R.T, - R.T.dot(t)] and not [R.T, -t].

you just saved me 
thanks a lot

**Comment by Jaykumaran** [comment]
Thanks! The inverse transformation is [R.T, - R.T.dot(t)] and not [R.T, -t].

Before:

<img width="898" height="432" alt="Image" src="https://github.com/user-attachments/assets/20b62066-5906-41be-b75c-c7b04daa716f" />



<img width="645" height="869" alt="Image" src="https://github.com/user-attachments/assets/ea998e06-03a9-4180-87cc-5ffe4bfca556" />


----------------------------------------------

After:

<img width="1011" height="845" alt="Image" src="https://github.com/user-attachments/assets/304e94b5-ef38-4f68-8a83-85ec8640c2d4" />

<img width="683" height="921" alt="Image" src="https://github.com/user-attachments/assets/a20454f0-fa54-4ac5-9781-165cd2113867" />
