### ISSUE TITLE
Is it possible to use the Windows 10 Linux bash in order to test Colmap?

### ISSUE THREAD

**Issue by martidi** [colmap/colmap#148]
Hi!

I'm trying to use Colmap on the Linux bash available in Windows 10, but I get thew error below:

./src/exe/feature_extractor.cc --database_path $PROJECT_PATH/database.db --image_path $PROJECT_PATH/images --SiftGPUExtraction.index 0                                                ./src/exe/feature_extractor.cc: line 1: //: Is a directory                                                         ./src/exe/feature_extractor.cc: line 2: syntax error near unexpected token `('                                     ./src/exe/feature_extractor.cc: line 2: `// Copyright (C) 2017  Johannes L. Schoenberger <jsch at inf.ethz.ch>'

Do you have some idea why? Or do you have some more advice in order to try to install it on Windows? I tried but I didn't get how to use the LocalConfigExample.config. file...

Thank you for your support, 

Martina

**Comment by ahojnnes** [comment]
Hi,

You are trying to execute the source code directly, but you must compile it first. Please, follow the instructions at https://colmap.github.io/install.html

I am not sure whether this works under WSL at the moment, but I'd be curious to see whether it works. I don't have access to a Windows 10 machine at the moment.

Cheers,
Johannes

**Comment by martidi** [comment]
Hi Johannes, 

actually I followed those instructions, and I assumed to have installed it... for this I've asked you. Probably it's a WSL issue. Anyway I installed it on Windows through bin and now is working via GUI.

Just another question: it's not clear to me how to georeference the images: I've found these instructions, but they seem for Linux OS

image_name1.jpg X1 Y1 Z1
image_name2.jpg X2 Y2 Z2
image_name3.jpg X3 Y3 Z3
...
Note that at least 3 images must be specified to estimate a 3D similarity transformation. Then, the model can be geo-registered using:

./src/exe/model_aligner \
    --input_path /path/to/model \
    --output_path /path/to/geo-registered-model \
    --ref_images_path /path/to/text-file

Is it correct? How can I handle this on Win? 

Moreover, is there a way to use GCPs to georeference the model? Or at the moment this is not available?

Thank you for your support, 

Martina

**Comment by ahojnnes** [comment]
I guess, you are not in the build directory when executing ``./src/exe/feature_extractor.cc``, since the compiled binaries do not have the file extension ``.cc``. To run ``./src/exe/feature_extractor``, do a ``cd build`` first and then do ``./src/exe/feature_extractor``.

**Comment by ahojnnes** [comment]
Regarding your second question: You can find the ``model_aligner`` binary in the ``bin`` folder that you downloaded from the website.
