### ISSUE TITLE
I encountered this error at the Feature extraction stage

### ISSUE THREAD

**Issue by MIMNSI** [colmap/colmap#1480]
I'm running COLMAP via the terminal on Ubuntu 20.04
GPU: Nvidia GTX 1080

During the feature extraction stage, this error comes up. I searched about it online but couldn't find any similar issues.

I'm running this script: https://github.com/NVlabs/instant-ngp/blob/master/scripts/colmap2nerf.py 
from Nvidia's Instant Neural Graphics Primitives repo.
Link: https://github.com/NVlabs/instant-ngp
It is meant to calculate the camera positions from given photos and generate a transforms.json file.

Here's the stack trace
---------------------------------------------------------------------------------
F20220402 11:31:06.884990 22536 sift.cc:656] Check failed: octave_scale_idx <= prev_octave_scale_idx (-1689112243 vs. -1873862397)
*** Check failure stack trace: ***
@ 0x7fbd4207fc0d google::LogMessage::Fail()
@ 0x7fbd420827a6 google::LogMessage::SendToLog()
@ 0x7fbd4207f705 google::LogMessage::Flush()
@ 0x7fbd42082d6a google::LogMessageFatal::~LogMessageFatal()
@ 0x55b9adab03c9 colmap::ExtractCovariantSiftFeaturesCPU()
@ 0x55b9ada8a4dc colmap::internal::SiftFeatureExtractorThread::Run()
@ 0x55b9adc2602e colmap::Thread::RunFunc()
@ 0x7fbd4021f039 execute_native_thread_routine
@ 0x7fbd41c99609 start_thread
@ 0x7fbd3fef3163 clone
Aborted (core dumped)
FATAL: command failed
---------------------------------------------------------------------------------

**Comment by MIMNSI** [comment]
This code block from the above mentioned script is responsible for running COLMAP. Please take a look at it.
--------------------------------------------------------------------------------------------------------------------------

def run_colmap(args):
	db=args.colmap_db
	images=args.images
	db_noext=str(Path(db).with_suffix(""))

	if args.text=="text":
		args.text=db_noext+"_text"
	text=args.text
	sparse=db_noext+"_sparse"
	print(f"running colmap with:\n\tdb={db}\n\timages={images}\n\tsparse={sparse}\n\ttext={text}")
	if (input(f"warning! folders '{sparse}' and '{text}' will be deleted/replaced. continue? (Y/n)").lower().strip()+"y")[:1] != "y":
		sys.exit(1)
	if os.path.exists(db):
		os.remove(db)
	do_system(f"colmap feature_extractor --ImageReader.camera_model OPENCV --SiftExtraction.estimate_affine_shape=true --SiftExtraction.domain_size_pooling=true --ImageReader.single_camera 1 --database_path {db} --image_path {images}")
	do_system(f"colmap {args.colmap_matcher}_matcher --SiftMatching.guided_matching=true --database_path {db}")
	try:
		shutil.rmtree(sparse)
	except:
		pass
	do_system(f"mkdir {sparse}")
	do_system(f"colmap mapper --database_path {db} --image_path {images} --output_path {sparse}")
	do_system(f"colmap bundle_adjuster --input_path {sparse}/0 --output_path {sparse}/0 --BundleAdjustment.refine_principal_point 1")
	try:
		shutil.rmtree(text)
	except:
		pass
	do_system(f"mkdir {text}")
	do_system(f"colmap model_converter --input_path {sparse}/0 --output_path {text} --output_type TXT")

-------------------------------------------------------------------------------------------------------------------------------------------

**Comment by MIMNSI** [comment]
I solved the problem by installing COLMAP from source.

**Comment by DavidParamo** [comment]
I've also encountered this error but I have been able to solve it by installing 
`sudo apt-get install libcgal-qt5-dev
`
Hope that helps someone

**Comment by paujar** [comment]
I got it to work; it was something that got installed when I wrote `apt-get install libeigen3-dev \
    libflann-dev \
    libfreeimage-dev \
    libmetis-dev \
    libgoogle-glog-dev \
    libgflags-dev \
    libsqlite3-dev \
    libglew-dev \
    qtbase5-dev \
    libqt5opengl5-dev \
    libcgal-dev \
    libceres-dev`

**Comment by Daheer** [comment]
--SiftExtraction.estimate_affine_shape=true --SiftExtraction.domain_size_pooling=true
Disabling these by setting them to false solved it for me. Check if they're necessary for your use
