### ISSUE TITLE
ERROR: the correct camera poses for current points cannot be accessed

### ISSUE THREAD

**Issue by asad-ak** [colmap/colmap#1481]
What actually does this error mean? And also, how do I work my way around it?

**Comment by tsattler** [comment]
Is this ERROR generated by Colmap? It does not seem that there is any such error message in Colmap's code (based on a quick search through the repository). Seem more related to this https://github.com/Fyusion/LLFF/issues/36 than to Colmap.

**Comment by asad-ak** [comment]
> Is this ERROR generated by Colmap? It does not seem that there is any such error message in Colmap's code (based on a quick search through the repository). Seem more related to this [Fyusion/LLFF#36](https://github.com/Fyusion/LLFF/issues/36) than to Colmap.

Yes sir you are right, I apologize for posting this issue here but do you have a solution for this or should I open this issue on the LLFF repo?

**Comment by asad-ak** [comment]
I apologize for the inconvenience and thank you very much for your help!

**Comment by shreyk25** [comment]
Hi @asad-ak , were you able to find a work around for your issue?
