### ISSUE TITLE
Failure when using dense_stereo via command line

### ISSUE THREAD

**Issue by heimsi** [colmap/colmap#149]
When using the dense_stereo executable (after a successful sparse reconstruction, and after image_undistorter) with these options (the same as used in the CLI documentation) :
`
$COLMAP_EXE_PATH/dense_stereo --workspace_path $PROJECT_PATH/dense --workspace_format COLMAP --DenseStereo.max_image_size 0 --DenseStereo.geom_consistency true
`

I get the following error:

```

F0612 14:42:26.929672 10547 mat.h:136] Check failed: text_file.is_open() /home/silvan/colmap-tests/test3/dense/stereo/depth_maps/IMG_6501.JPG.photometric.bin
*** Check failure stack trace: ***
    @     0x7f50bcfe75cd  google::LogMessage::Fail()
    @     0x7f50bcfe9433  google::LogMessage::SendToLog()
    @     0x7f50bcfe715b  google::LogMessage::Flush()
    @     0x7f50bcfe9e1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x5684fb  colmap::mvs::Mat<>::Read()
    @           0x55f526  colmap::mvs::(anonymous namespace)::ReadPatchMatchProblems()
    @           0x562045  colmap::mvs::PatchMatchController::Run()
    @           0x66a18c  colmap::Thread::RunFunc()
    @     0x7f50b9b0dc80  (unknown)
    @     0x7f50bc8836ba  start_thread
    @     0x7f50b927382d  clone
    @              (nil)  (unknown)
denseRecon.sh: line 21: 10543 Aborted                 (core dumped) $COLMAP_EXE_PATH/dense_stereo --workspace_path $PROJECT_PATH/dense --workspace_format COLMAP --DenseStereo.max_image_size 0 --DenseStereo.geom_consistency true
```
What could be the problem here? Any help would be very appreciated. :)

**Comment by heimsi** [comment]
The problem seems to be the option
`--DenseStereo.geom_consistency true`, because after setting this to false, the excutable works. But why is that?

**Comment by ahojnnes** [comment]
It seems you are using an old version of COLMAP. Can you pull the latest code from Github or download the latest pre-built binaries from the website and re-run everything with a new workspace etc. ?

Thanks.

**Comment by heimsi** [comment]
I'm working on it, but as you may have seen in the other issue thread, while updating to the newest version of the repository I got an error already with the mapper.... :( So I'm still on it... :)

**Comment by heimsi** [comment]
After an update to the most recent revision of the master branch, the problem no longer occurs. Thank you for your help!!
