### ISSUE TITLE
No good initial image pair found

### ISSUE THREAD

**Issue by lfxx** [colmap/colmap#1490]
Hi,thanks for your excellent work.I use your repo to do reconstruction.But i get error above during feature matching.Some pictures in datasets are below:
![1](https://user-images.githubusercontent.com/27956643/163166437-9b1ed81c-231f-4773-bbb5-e4a318099dd4.jpg)
![3](https://user-images.githubusercontent.com/27956643/163166454-f4a54ad2-01e3-4156-b84f-eaac2bc084cc.jpg)
![5](https://user-images.githubusercontent.com/27956643/163166468-8556d838-00bb-4872-a802-1a44dbf671bf.jpg)
![7](https://user-images.githubusercontent.com/27956643/163166478-e5af5e72-366b-4a65-8a78-5bfa02b53295.jpg)
These pictures are from camera which are installed on car.Could you give me some advice about how to do reconstruction on these pictures which are forward motion condition?
Any advice will be appreciated.I have struggled with this several days.

**Comment by tsattler** [comment]
Pure forward motion is problematic for structure-from-motion as it leads to instable (and degenerate) configurations.

There is a parameter (`init_max_forward_motion`) that you can set to define the maximum amount of forward motion that is still considered when trying to find an initial pair. Setting it to 1.0 should allow all forward motion.

You will probably get better results though if you also have turning in your dataset.

**Comment by lfxx** [comment]
> 

Even if i set init_max_forward_motion=1,i still get the above error.If you need,i can set a mini-datasets to you to find out the reason.

**Comment by lfxx** [comment]
> Pure forward motion is problematic for structure-from-motion as it leads to instable (and degenerate) configurations.
> 
> There is a parameter (`init_max_forward_motion`) that you can set to define the maximum amount of forward motion that is still considered when trying to find an initial pair. Setting it to 1.0 should allow all forward motion.
> 
> You will probably get better results though if you also have turning in your dataset.

Even if i set init_max_forward_motion=1,i still get the above error.If you need,i can set a mini-datasets to you to find out the reason.

**Comment by tsattler** [comment]
As I mentioned, forward motion is problematic for structure-from-motion (same for SLAM) as it leads to unstable results.
Capturing sequences that do not only contain forward motion, but also for example driving around corners, could solve the problem.

**Comment by whuaegeanse** [comment]
@tsattler @lfxx 
Try to increase init_max_forward_motion from 0.95 to 1.0 and  reduce init_min_tri_angle from 2 to 0.5 .

Here is the setting of my test.
![image](https://user-images.githubusercontent.com/8711991/163439305-00355517-5a70-41f2-bd7b-12d5b880c42d.png)
![image](https://user-images.githubusercontent.com/8711991/163437726-7c4cb7c8-5cce-4ea4-b1f5-a5969c0561d6.png)
![image](https://user-images.githubusercontent.com/8711991/163437785-b1edd470-8a36-443f-8568-498516f2742a.png)

The sparse reconstrction
![image](https://user-images.githubusercontent.com/8711991/163437010-7eb095aa-b0eb-42ae-940c-eed3d60ea25d.png)

Forwar motion means that the z value of relative pose is larger, the triangulation angle is smaller. So the key to process images in  such scene is to change the two thresholds.

**Comment by lfxx** [comment]
> As I mentioned, forward motion is problematic for structure-from-motion (same for SLAM) as it leads to unstable results. Capturing sequences that do not only contain forward motion, but also for example driving around corners, could solve the problem.

Is that saying i need to use multi-camera to get more pictures around car?or use one camera to get more pictures around car?

**Comment by lfxx** [comment]
> @lfxx Try to increase init_max_forward_motion from 0.95 to 1.0 (as @tsattler mentioned) and reduce init_min_tri_angle from 2 to 0.5 .
> 
> Here is the setting of my test. ![image](https://user-images.githubusercontent.com/8711991/163439305-00355517-5a70-41f2-bd7b-12d5b880c42d.png) ![image](https://user-images.githubusercontent.com/8711991/163437726-7c4cb7c8-5cce-4ea4-b1f5-a5969c0561d6.png) ![image](https://user-images.githubusercontent.com/8711991/163437785-b1edd470-8a36-443f-8568-498516f2742a.png)
> 
> The sparse reconstrction ![image](https://user-images.githubusercontent.com/8711991/163437010-7eb095aa-b0eb-42ae-940c-eed3d60ea25d.png)
> 
> Forwar motion means that the z value of relative pose is larger, the triangulation angle is smaller. So the key to process images in such scene is to change the two thresholds.

I use your setting get pretty good results.Thanks!

**Comment by lfxx** [comment]
> @lfxx Try to increase init_max_forward_motion from 0.95 to 1.0 (as @tsattler mentioned) and reduce init_min_tri_angle from 2 to 0.5 .
> 
> Here is the setting of my test. ![image](https://user-images.githubusercontent.com/8711991/163439305-00355517-5a70-41f2-bd7b-12d5b880c42d.png) ![image](https://user-images.githubusercontent.com/8711991/163437726-7c4cb7c8-5cce-4ea4-b1f5-a5969c0561d6.png) ![image](https://user-images.githubusercontent.com/8711991/163437785-b1edd470-8a36-443f-8568-498516f2742a.png)
> 
> The sparse reconstrction ![image](https://user-images.githubusercontent.com/8711991/163437010-7eb095aa-b0eb-42ae-940c-eed3d60ea25d.png)
> 
> Forwar motion means that the z value of relative pose is larger, the triangulation angle is smaller. So the key to process images in such scene is to change the two thresholds.

Hello.Now i want to use deep learning based method to predict depth since the default method in colmap is not good enough.How can i apply this depth to colmap?

**Comment by lfxx** [comment]
> > @lfxx Try to increase init_max_forward_motion from 0.95 to 1.0 (as @tsattler mentioned) and reduce init_min_tri_angle from 2 to 0.5 .
> > Here is the setting of my test. ![image](https://user-images.githubusercontent.com/8711991/163439305-00355517-5a70-41f2-bd7b-12d5b880c42d.png) ![image](https://user-images.githubusercontent.com/8711991/163437726-7c4cb7c8-5cce-4ea4-b1f5-a5969c0561d6.png) ![image](https://user-images.githubusercontent.com/8711991/163437785-b1edd470-8a36-443f-8568-498516f2742a.png)
> > The sparse reconstrction ![image](https://user-images.githubusercontent.com/8711991/163437010-7eb095aa-b0eb-42ae-940c-eed3d60ea25d.png)
> > Forwar motion means that the z value of relative pose is larger, the triangulation angle is smaller. So the key to process images in such scene is to change the two thresholds.
> 
> Hello.Now i want to use deep learning based method such as manydepth to predict depth since the default method in colmap is not good enough.How can i apply this depth to colmap? Can i have your wechat ID for convnience of communicating?

**Comment by sysu17363087** [comment]
> > As I mentioned, forward motion is problematic for structure-from-motion (same for SLAM) as it leads to unstable results. Capturing sequences that do not only contain forward motion, but also for example driving around corners, could solve the problem.
> 
> Is that saying i need to use multi-camera to get more pictures around car?or use one camera to get more pictures around car?

hi，i have the same problem as yours. I try to do 3D reconstruction on several kitti images which is alse the pure forward motion. I would like to know how you solve the problem at last. Appreciate for your help.

**Comment by shubham-monarch** [comment]
> Pure forward motion is problematic for structure-from-motion as it leads to instable (and degenerate) configurations.
> 
> There is a parameter (`init_max_forward_motion`) that you can set to define the maximum amount of forward motion that is still considered when trying to find an initial pair. Setting it to 1.0 should allow all forward motion.
> 
> You will probably get better results though if you also have turning in your dataset.

Why are we setting it to 1.0?

**Comment by tsattler** [comment]
> Why are we setting it to 1.0?

Because that is the maximum value.

**Comment by shubham-monarch** [comment]
Oh. Because everything is on a relative scale?

**Comment by bendanpuppy** [comment]
> @lfxx 尝试将 init_max_forward_motion 从 0.95 增加到 1.0（如@tsattler前面提到）把 init_min_tri_angle 从 2 减少到 0.5 。
> 
> 这是我的测试设置。 ![图像](https://user-images.githubusercontent.com/8711991/163439305-00355517-5a70-41f2-bd7b-12d5b880c42d.png) ![图像](https://user-images.githubusercontent.com/8711991/163437726-7c4cb7c8-5cce-4ea4-b1f5-a5969c0561d6.png) ![图像](https://user-images.githubusercontent.com/8711991/163437785-b1edd470-8a36-443f-8568-498516f2742a.png)
> 
> 稀疏重建 ![图像](https://user-images.githubusercontent.com/8711991/163437010-7eb095aa-b0eb-42ae-940c-eed3d60ea25d.png)
> 
> 前运动向是指相对位姿的z值越大，三角测量角度越小因此。处理此类场景图像的关键是改变这两个阈值。
Hello, I've also encountered a similar issue while using COLMAP. My dataset consists of endoscopic images capturing the interior of the intestine, including forward movement. Despite attempting the suggested configurations, I haven't been able to resolve the problem. I notice that you have a good understanding of this issue. Could you please share your contact information?  I would greatly appreciate your advice. 
[input.zip](https://github.com/colmap/colmap/files/13931630/input.zip)
