### ISSUE TITLE
GUI New Reconstruction Bug

### ISSUE THREAD

**Issue by meder411** [colmap/colmap#15]
When I try to start a new reconstruction after completing an old one (i.e. after selecting yes to the alert "Do you really want to overwrite the existing reconstruction?"), I get a 'colmap.exe has stopped working' error, and the program needs to close. This occurs after feature extraction and matching have been successful. It only happens when trying to actually start the reconstruction.

In my case, this occurs with a new DB and different image path than the existing reconstruction. When I restart colmap and try the same parameters and DB, path, etc it works just fine. It appears to just be an issue in overwriting the existing reconstruction. It struck me as strange because it's a different DB, but perhaps there's something stored in colmap?

I have been about to repeat this error multiple times with different datasets. I am using the 1.1 Windows binary from the docs on Windows 8.1.

**Comment by ahojnnes** [comment]
Hi Marc,

Thanks for reporting this bug. This was a tricky one and it should be fixed with https://github.com/colmap/colmap/commit/783e6661235047aa775ab9dd7c6479179b523229.

You can download the latest binaries with the fix from the website or recompile.

Cheers,
Johannes
