### ISSUE TITLE
"The launch timed out and was terminated"

### ISSUE THREAD

**Issue by ecerrillo** [colmap/colmap#150]
Hi,

I am experiencing an error when running `dense_stereo`

```
dense_stereo    --workspace_path $PROJECT_PATH/dense     --workspace_format COLMAP     --DenseStereo.max_image_size 0 
Reading workspace...
Reading configuration...
==============================================================================
Processing view 1 / 32
==============================================================================

Reading inputs...

PatchMatch::Problem
-------------------
ref_image_id: 0
src_image_ids: 30 31 1 29 2 3 28 4 27 5 26 6 25 24 7 23 22 21 8 20

PatchMatch::Options
-------------------
max_image_size: 0
gpu_index: 0
depth_min: 2.07461
depth_max: 19.8083
window_radius: 5
sigma_spatial: 5
sigma_color: 0.2
num_samples: 15
ncc_sigma: 0.6
min_triangulation_angle: 1
incident_angle_sigma: 0.9
num_iterations: 5
geom_consistency: 0
geom_consistency_regularizer: 0.3
geom_consistency_max_cost: 3
filter: 0
filter_min_ncc: 0.1
filter_min_triangulation_angle: 3
filter_min_num_consistent: 2
filter_geom_consistency_max_cost: 1
write_consistency_graph: 0

PatchMatch::Run
---------------
Initialization: 1.8972s
cudaCheckError() with sync failed at /opt/colmap/src/mvs/patch_match_cuda.cu:1327 : the launch timed out and was terminated`
```

The command hangs after an apparently intense calculation, which freezes the computer for a few seconds. I have tested the following:

-1) The installed version have been downloaded from GitHub during the last week. 
-2) I have tested different datasets with different number of images
-3) I have installed COLMAP in Mac OS X/Ubuntu machine with a NVIDIA graphic card. I'm getting the error in both systems with `--DenseStereo.geom_consistency`set to `true` and `false`.
-4) I'm getting a similar error when I build the binaries without CUDA.
-5) I have get the same errors on a Ubuntu Machine and a MacBook Pro, both with no NVIDIA graphic card and compiled without CUDA.

What I'm doing wrong? Thank you!

Enrique

**Comment by ahojnnes** [comment]
See https://colmap.github.io/faq.html#fix-gpu-freezes-and-timeouts-during-dense-reconstruction

**Comment by ecerrillo** [comment]
That might work for Ubuntu (and I'll give it a try), but certainly not for Mac OS X.

If I buld the binaries with  `CUDA_ENABLED OFF` I get:

```
dense_stereo     --workspace_path $PROJECT_PATH/dense     --workspace_format COLMAP     --DenseStereo.max_image_size 0  
Reading workspace...
Reading configuration...

==============================================================================
Processing view 1 / 32
==============================================================================

Reading inputs...

PatchMatch::Problem
-------------------
ref_image_id: 0
src_image_ids: 30 31 1 29 2 3 28 4 27 5 26 6 25 24 7 23 22 21 8 20

PatchMatch::Options
-------------------
max_image_size: 0
gpu_index: 0
depth_min: 2.07461
depth_max: 19.8083
window_radius: 5
sigma_spatial: 5
sigma_color: 0.2
num_samples: 15
ncc_sigma: 0.6
min_triangulation_angle: 1
incident_angle_sigma: 0.9
num_iterations: 5
geom_consistency: 0
geom_consistency_regularizer: 0.3
geom_consistency_max_cost: 3
filter: 0
filter_min_ncc: 0.1
filter_min_triangulation_angle: 3
filter_min_num_consistent: 2
filter_geom_consistency_max_cost: 1
write_consistency_graph: 0

PatchMatch::Run
---------------
out of memory in /opt/colmap/src/./mvs/gpu_mat.h at line 151
```
And that seems also be related to CUDA.

**Comment by ahojnnes** [comment]
You get a pretty clear error message here: ``out of memory in /opt/colmap/src/./mvs/gpu_mat.h at line 151``. See https://colmap.github.io/faq.html#reduce-memory-usage-during-dense-reconstruction

**Comment by ecerrillo** [comment]
Thanks! But it doesn't work either. I have tried that before, sorry for not mentioning it. I have set `-DenseStereo.max_image_size 1500` and changed `__auto__, 30` to `__auto__, 10 ` for all images. 

```
PatchMatch::Run
---------------
Initialization: 0.9779s
cudaCheckError() with sync failed at /opt/colmap/src/mvs/patch_match_cuda.cu:1327 : the launch timed out and was terminated 
```

**Comment by ahojnnes** [comment]
This is not trivial since I don't know a way to run OSX in command line mode. The only option you have is to use a dedicated GPU that is not connected to your display. Or to further decrease the image size or window radius in the options.
