### ISSUE TITLE
[Question] Adding new images to existing point cloud

### ISSUE THREAD

**Issue by Camilochiang** [colmap/colmap#1500]
Good day. 
Given the following Input: An existent pointcloud (RGB) and a set of high resolution images with known poses and orientation, Is it possible to add images (hopefully one by one) to enrich/extend the existing point cloud using colmap? I have not been able to find a projec with that capacity so far .

Thanks!

**Comment by tsattler** [comment]
Does this answer your question: https://colmap.github.io/faq.html#register-localize-new-images-into-an-existing-reconstruction ?

**Comment by Camilochiang** [comment]
hei @tsattler, thanks for your quick answer! But no. Im thinking about a pointcloud comming from LiDAR (SLAM), so I dont  have a previus database nor images to match.

**Comment by tsattler** [comment]
Colmap does not provide a mechanism for this case. You could try to render the point cloud to generate images though.

Since you know the poses, you could also use Colmap to generate a point cloud from the images and then combine both point clouds somehow.
