### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by wanhch** [colmap/colmap#1503]
Segmentation fault when execute "make -j". 
Ceres 2.1 is used.
Has tried "make clean“ and "make -j2" .

[  0%] Built target lsd
[  0%] Building CXX object lib/FLANN/CMakeFiles/flann.dir/flann.cpp.o
[  2%] Built target poisson_recon
[  4%] Built target sqlite3
[ 26%] Built target graclus
[ 40%] Built target vlfeat
[ 40%] Building CXX object lib/SiftGPU/CMakeFiles/sift_gpu.dir/SiftPyramid.cpp.o
[ 40%] Linking CXX static library libpba.a
[ 44%] Built target pba
[ 44%] Linking CXX static library libsift_gpu.a
[ 50%] Built target sift_gpu
during IPA pass: icf
/home/vsp/Downloads/colmap/lib/FLANN/flann.cpp:1319:1: internal compiler error: Segmentation fault
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-8/README.Bugs> for instructions.
make[2]: *** [lib/FLANN/CMakeFiles/flann.dir/build.make:63: lib/FLANN/CMakeFiles/flann.dir/flann.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:589: lib/FLANN/CMakeFiles/flann.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

OS: ubuntu 20.04
Version: master branch

**Comment by wanhch** [comment]
Solved

**Comment by Asherchi** [comment]
how to solve this problem?
