### ISSUE TITLE
Broken geometry for large scale street video

### ISSUE THREAD

**Issue by is03wlei** [colmap/colmap#151]
My dataset is from a 15mins street video(covers 6km road). The camera(iPhone7) is bound on the right window of a car and faced to right.

The frame rate is 30fps and there are 29372 images.
There are 28603 images registered into the model.

Spare reconstructions from different view points are as follows:
![software-park-right-1](https://user-images.githubusercontent.com/4695442/27123317-11f72b94-5120-11e7-99d6-1e5d2587e83a.png)
![software-park-right-2](https://user-images.githubusercontent.com/4695442/27123342-2099569a-5120-11e7-885e-2e90d5f4f7d3.png)
![software-park-right-3](https://user-images.githubusercontent.com/4695442/27123362-37912be8-5120-11e7-8ce1-3285314f1864.png)
![software-park-right-4](https://user-images.githubusercontent.com/4695442/27123371-3f557d98-5120-11e7-9c5f-f2e8f2ef245f.png)

While the route is(Sequence is marked by numbers):
![crop](https://user-images.githubusercontent.com/4695442/27124003-33acd494-5122-11e7-8221-ea1565c665a3.png)

The estimated camera poses differ a lot from the route.

**Comment by ahojnnes** [comment]
The iPhone 7 has a rolling shutter camera and COLMAP does not account for rolling shutter geometry. This might cause the significant drift you see in the reconstructed models. Otherwise, which camera model do you use and do you share intrinsics?

**Comment by is03wlei** [comment]
This is the script I used.

PROJECT_PATH=$1

feature_extractor \
   --database_path $PROJECT_PATH/database.db \
   --image_path $PROJECT_PATH/images \
   --ImageReader.default_focal_length_factor 0.8 \
   --SiftExtraction.max_image_size 4000 \
   --SiftGPUExtraction.index 0 \
   --SiftCPUExtraction.num_threads 20 > feature_extractor.log

vocab_tree_matcher \
   --database_path $PROJECT_PATH/database.db \
   --SiftMatching.gpu_index=0,1,2,3 \
   --VocabTreeMatching.vocab_tree_path ./vocab_tree-1048576.bin \
   --SiftMatching.num_threads 20 > vocab_tree_matcher.log

mkdir $PROJECT_PATH/sparse

mapper \
    --database_path $PROJECT_PATH/database.db \
    --image_path $PROJECT_PATH/images \
    --export_path $PROJECT_PATH/sparse \
    --Mapper.ba_global_pba_gpu_index 0 \
    --Mapper.num_threads 20 > mapper.log

mkdir $PROJECT_PATH/dense

image_undistorter \
    --image_path $PROJECT_PATH/images \
    --input_path $PROJECT_PATH/sparse/0 \
    --output_path $PROJECT_PATH/dense \
    --output_type COLMAP \
    --max_image_size 4000 > image_undistorer.log

dense_stereo \
    --workspace_path $PROJECT_PATH/dense \
    --workspace_format COLMAP \
    --DenseStereo.max_image_size 0 \
    --DenseStereo.filter false \
    --DenseStereo.geom_consistency false \
    --DenseStereo.num_iterations 4 \
    --DenseStereo.gpu_index=0,1,2,3 > dense_stereo.log

dense_stereo \
    --workspace_path $PROJECT_PATH/dense \
    --workspace_format COLMAP \
    --DenseStereo.max_image_size 0 \
    --DenseStereo.filter true \
    --DenseStereo.geom_consistency true \
    --DenseStereo.gpu_index=0,1,2,3 >> dense_stereo.log

dense_fuser \
    --workspace_path $PROJECT_PATH/dense \
    --workspace_format COLMAP \
    --input_type geometric \
    --output_path $PROJECT_PATH/dense/point-cloud.ply > dense_fuser.log

dense_mesher \
    --input_path $PROJECT_PATH/dense/point-cloud.ply \
    --output_path $PROJECT_PATH/dense/mesh.ply \
    --DenseMeshing.num_threads 20 > dense_mesher.log

**Comment by is03wlei** [comment]
This is partial result of cameras.txt generated by colmap.
The focal lengths differ a lot. They should be the same value.

# Camera list with one line of data per camera:
#   CAMERA_ID, MODEL, WIDTH, HEIGHT, PARAMS[]
# Number of cameras: 28603
305 SIMPLE_RADIAL 3840 2160 3507.97 1920 1080 -0.00173049
676 SIMPLE_RADIAL 3840 2160 3962.06 1920 1080 -0.0122845
1071 SIMPLE_RADIAL 3840 2160 2365.02 1920 1080 0.0743993
1371 SIMPLE_RADIAL 3840 2160 2142.83 1920 1080 0.142708
1671 SIMPLE_RADIAL 3840 2160 3196.15 1920 1080 0.0236303
2002 SIMPLE_RADIAL 3840 2160 1125.38 1920 1080 0.0585975
2303 SIMPLE_RADIAL 3840 2160 3242.26 1920 1080 0.0351487
2603 SIMPLE_RADIAL 3840 2160 3610.29 1920 1080 0.0301899
2903 SIMPLE_RADIAL 3840 2160 3422.9 1920 1080 0.0134973
3203 SIMPLE_RADIAL 3840 2160 3180.12 1920 1080 -0.122785
3508 SIMPLE_RADIAL 3840 2160 3456.57 1920 1080 0.0177293
3808 SIMPLE_RADIAL 3840 2160 3476.51 1920 1080 0.0195422
4108 SIMPLE_RADIAL 3840 2160 3477.96 1920 1080 0.0310691
4408 SIMPLE_RADIAL 3840 2160 3486.11 1920 1080 0.0293228
4708 SIMPLE_RADIAL 3840 2160 3476.87 1920 1080 0.0245639
5008 SIMPLE_RADIAL 3840 2160 3401.5 1920 1080 0.129762
5308 SIMPLE_RADIAL 3840 2160 3616.09 1920 1080 0.0113557
5608 SIMPLE_RADIAL 3840 2160 3406.23 1920 1080 0.0278694
5924 SIMPLE_RADIAL 3840 2160 4051.08 1920 1080 0.0398154
6224 SIMPLE_RADIAL 3840 2160 3218.94 1920 1080 -0.0409989
6524 SIMPLE_RADIAL 3840 2160 3245.16 1920 1080 -0.0134815
6824 SIMPLE_RADIAL 3840 2160 832.013 1920 1080 0.00130099
7124 SIMPLE_RADIAL 3840 2160 3835.26 1920 1080 -0.100294
7424 SIMPLE_RADIAL 3840 2160 5551.49 1920 1080 -0.124082
7749 SIMPLE_RADIAL 3840 2160 3369.88 1920 1080 0.00859453
8049 SIMPLE_RADIAL 3840 2160 2699.86 1920 1080 0.00529896
8349 SIMPLE_RADIAL 3840 2160 2755.81 1920 1080 -0.00562842
8649 SIMPLE_RADIAL 3840 2160 3680.42 1920 1080 0.0296054
8949 SIMPLE_RADIAL 3840 2160 2948.43 1920 1080 -0.0112842
9249 SIMPLE_RADIAL 3840 2160 2326.1 1920 1080 0.0340549
9551 SIMPLE_RADIAL 3840 2160 3432.73 1920 1080 0.0327183
9851 SIMPLE_RADIAL 3840 2160 3370.05 1920 1080 -0.0618917
10156 SIMPLE_RADIAL 3840 2160 3424.77 1920 1080 0.0377349
10621 SIMPLE_RADIAL 3840 2160 3352.22 1920 1080 -0.0126028
10921 SIMPLE_RADIAL 3840 2160 2164.13 1920 1080 0.135877
11221 SIMPLE_RADIAL 3840 2160 2163.75 1920 1080 0.174401
11521 SIMPLE_RADIAL 3840 2160 3062.34 1920 1080 0.0588909
11853 SIMPLE_RADIAL 3840 2160 3456.66 1920 1080 0.0167782
12153 SIMPLE_RADIAL 3840 2160 3318.81 1920 1080 0.0486884
12453 SIMPLE_RADIAL 3840 2160 3582.54 1920 1080 0.0177907
12753 SIMPLE_RADIAL 3840 2160 3435.03 1920 1080 0.0223927
13061 SIMPLE_RADIAL 3840 2160 3652.76 1920 1080 -0.00169575
13361 SIMPLE_RADIAL 3840 2160 3479.07 1920 1080 0.024884
13661 SIMPLE_RADIAL 3840 2160 3469.67 1920 1080 0.0347091
13961 SIMPLE_RADIAL 3840 2160 3476.38 1920 1080 0.0262599
14261 SIMPLE_RADIAL 3840 2160 3466.08 1920 1080 0.0290158
14561 SIMPLE_RADIAL 3840 2160 3478.07 1920 1080 0.0258216
14861 SIMPLE_RADIAL 3840 2160 3314.5 1920 1080 0.0883883
15161 SIMPLE_RADIAL 3840 2160 3712.36 1920 1080 0.0484685
15461 SIMPLE_RADIAL 3840 2160 3410.25 1920 1080 0.0282714
15778 SIMPLE_RADIAL 3840 2160 3734.36 1920 1080 0.0455018
16078 SIMPLE_RADIAL 3840 2160 3256.91 1920 1080 -0.0495131
16378 SIMPLE_RADIAL 3840 2160 3257.89 1920 1080 -0.00382738
16678 SIMPLE_RADIAL 3840 2160 2069.72 1920 1080 0.0209351
16978 SIMPLE_RADIAL 3840 2160 1117.49 1920 1080 0.013854
17278 SIMPLE_RADIAL 3840 2160 3496.94 1920 1080 0.20263
17602 SIMPLE_RADIAL 3840 2160 3028.78 1920 1080 0.00334691
17902 SIMPLE_RADIAL 3840 2160 2709.73 1920 1080 0.00281574
18202 SIMPLE_RADIAL 3840 2160 2468.44 1920 1080 -0.00189412
18502 SIMPLE_RADIAL 3840 2160 3148.05 1920 1080 0.0167277
18802 SIMPLE_RADIAL 3840 2160 2877.78 1920 1080 -0.00903213
19102 SIMPLE_RADIAL 3840 2160 3434.84 1920 1080 0.025671
19405 SIMPLE_RADIAL 3840 2160 3424.09 1920 1080 0.03186
19705 SIMPLE_RADIAL 3840 2160 2875.42 1920 1080 -0.0121893
20010 SIMPLE_RADIAL 3840 2160 3424.16 1920 1080 0.0443611
20480 SIMPLE_RADIAL 3840 2160 3384.19 1920 1080 0.0214783
20780 SIMPLE_RADIAL 3840 2160 2160.12 1920 1080 0.137865
21080 SIMPLE_RADIAL 3840 2160 2181.21 1920 1080 0.0268546
21411 SIMPLE_RADIAL 3840 2160 3245.58 1920 1080 0.0909671
21713 SIMPLE_RADIAL 3840 2160 3466.66 1920 1080 0.0309325
22013 SIMPLE_RADIAL 3840 2160 3361.57 1920 1080 0.116523
22313 SIMPLE_RADIAL 3840 2160 3706.46 1920 1080 0.0670121
22613 SIMPLE_RADIAL 3840 2160 3431.26 1920 1080 0.0269803
22918 SIMPLE_RADIAL 3840 2160 3471.95 1920 1080 0.00649606
23218 SIMPLE_RADIAL 3840 2160 3486.62 1920 1080 0.0185752
23518 SIMPLE_RADIAL 3840 2160 3475.05 1920 1080 0.0279476
23818 SIMPLE_RADIAL 3840 2160 3469.09 1920 1080 0.0334152
24118 SIMPLE_RADIAL 3840 2160 3484.96 1920 1080 0.0159137
24418 SIMPLE_RADIAL 3840 2160 3473.19 1920 1080 0.0298947
24718 SIMPLE_RADIAL 3840 2160 3288.21 1920 1080 0.061265
25018 SIMPLE_RADIAL 3840 2160 3662.93 1920 1080 0.0911871
25318 SIMPLE_RADIAL 3840 2160 3429.48 1920 1080 0.0215716
25636 SIMPLE_RADIAL 3840 2160 2086.71 1920 1080 0.00494103
25936 SIMPLE_RADIAL 3840 2160 3273.35 1920 1080 0.0278522
26236 SIMPLE_RADIAL 3840 2160 3806.09 1920 1080 0.012014
26536 SIMPLE_RADIAL 3840 2160 3597.77 1920 1080 -0.000912174
26837 SIMPLE_RADIAL 3840 2160 5224.09 1920 1080 0.0984966
27139 SIMPLE_RADIAL 3840 2160 3638.58 1920 1080 0.024181
27464 SIMPLE_RADIAL 3840 2160 2973.8 1920 1080 0.00697226
27764 SIMPLE_RADIAL 3840 2160 2712.37 1920 1080 0.00755845
28064 SIMPLE_RADIAL 3840 2160 2235.67 1920 1080 -0.0017527
28364 SIMPLE_RADIAL 3840 2160 2921.9 1920 1080 0.0150556
28664 SIMPLE_RADIAL 3840 2160 2007.05 1920 1080 -0.0236768
28967 SIMPLE_RADIAL 3840 2160 3499.98 1920 1080 -0.0343066
29267 SIMPLE_RADIAL 3840 2160 3436.52 1920 1080 0.019099
