### ISSUE TITLE
Obtaining the calibration matrix

### ISSUE THREAD

**Issue by eyildiz-ugoe** [colmap/colmap#1510]
**Is your feature request related to a problem? Please describe.**
I'm often required to work with the calibration matrices after the 3D reconstruction phase. A feature to enable that would be nice. 

**Describe the solution you'd like**
Simple a function such as `colmap calib_info` where calibration info of the 3D reconstruction would be returned. So far I could not find this feature on the command line or the GUI.

**Comment by tsattler** [comment]
The intrinsic calibration is stored in the `cameras.bin` respectively `cameras.txt` files that are created when you save a reconstruction. You can also obtain the intrinsic calibration of an image by double-clicking on the corresponding camera in the reconstruction shown in the gui.
