### ISSUE TITLE
[Windows] Build error

### ISSUE THREAD

**Issue by Hyunkil76** [colmap/colmap#1511]
I'm trying to build colmap through vcpkg. But, this error countinuously occur.

C:\src\vcpkg>.\vcpkg install colmap[cuda,tests]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    colmap[core,cuda,tests]:x64-windows -> 2022-03-14
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\Hyunkil\AppData\Local\vcpkg\archives in 256.1 us. Use --debug to see more details.
Starting package 1/1: colmap:x64-windows
Building package colmap[core,cuda,tests]:x64-windows...
-- Using cached colmap-colmap-29a1e3642a3b00734a52b21e597ea4d576485fe6.tar.gz.
-- Cleaning sources at C:/src/vcpkg/buildtrees/colmap/src/d576485fe6-7dd36362d1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg/downloads/colmap-colmap-29a1e3642a3b00734a52b21e597ea4d576485fe6.tar.gz
-- Applying patch fix-dependencies.patch
-- Using source at C:/src/vcpkg/buildtrees/colmap/src/d576485fe6-7dd36362d1.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j17
    Working Directory: C:/src/vcpkg/buildtrees/colmap/x64-windows-dbg
    See logs for more information:
      C:\src\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:53 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)

error: building colmap:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+colmap
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[colmap]+Build+error
including:
  package: colmap[core,cuda,tests]:x64-windows -> 2022-03-14
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: b98afc9f1 2022-05-02 (10 hours ago)

Additionally, attach any relevant sections from the log files above.

**Expected behavior**
I don't know why this problem occur... Can someone help me?

**Desktop (please complete the following information):**
 - OS: Windows
 - Version Window 10, MSVC19

**Additional context**
[install-x64-windows-dbg-out.log](https://github.com/colmap/colmap/files/8610993/install-x64-windows-dbg-out.log)

**Comment by ZZWang21** [comment]
Same here. Any expert got any ideas? Thank you.

**Comment by whuaegeanse** [comment]
@ZZWang21  This is an import bug because of using glog 0.5 via vcpkg
Comment macro NOGDI in glog/logging.h
```
#ifdef HAVE_CXX11_ATOMIC
#include <atomic>
#elif defined(GLOG_OS_WINDOWS)
# ifndef WIN32_LEAN_AND_MEAN
#  define WIN32_LEAN_AND_MEAN  // We only need minimal includes
# endif
// To avoid macro definition of ERROR.
//# ifndef NOGDI
//#  define NOGDI
//# endif
// To avoid macro definition of min/max.
# ifndef NOMINMAX
#  define NOMINMAX
# endif
```

**Comment by Hyunkil76** [comment]
> 

Oh... I'll have to wait for their reply.
Thanks so much for your help :)

**Comment by ZZWang21** [comment]
> @ZZWang21 This is an import bug because of using glog 0.5 via vcpkg Comment macro NOGDI in glog/logging.h
> 
> ```
> #ifdef HAVE_CXX11_ATOMIC
> #include <atomic>
> #elif defined(GLOG_OS_WINDOWS)
> # ifndef WIN32_LEAN_AND_MEAN
> #  define WIN32_LEAN_AND_MEAN  // We only need minimal includes
> # endif
> // To avoid macro definition of ERROR.
> //# ifndef NOGDI
> //#  define NOGDI
> //# endif
> // To avoid macro definition of min/max.
> # ifndef NOMINMAX
> #  define NOMINMAX
> # endif
> ```

But I did not find "glog/logging.h". Should I find a way to generate one?

**Comment by whuaegeanse** [comment]
> > @ZZWang21 This is an import bug because of using glog 0.5 via vcpkg Comment macro NOGDI in glog/logging.h
> > ```
> > #ifdef HAVE_CXX11_ATOMIC
> > #include <atomic>
> > #elif defined(GLOG_OS_WINDOWS)
> > # ifndef WIN32_LEAN_AND_MEAN
> > #  define WIN32_LEAN_AND_MEAN  // We only need minimal includes
> > # endif
> > // To avoid macro definition of ERROR.
> > //# ifndef NOGDI
> > //#  define NOGDI
> > //# endif
> > // To avoid macro definition of min/max.
> > # ifndef NOMINMAX
> > #  define NOMINMAX
> > # endif
> > ```
> 
> But I did not find "glog/logging.h". Should I find a way to generate one? @whuaegeanse Thank you very much.
logging.h is located in "your directory"\vcpkg\installed\x64-windows\include\glog

**Comment by wbw24** [comment]
> @ZZWang21 这是一个导入错误，因为 在 glog/logging.h 中通过 vcpkg 注释宏 NOGDI使用 glog 0.5
> 
> ```
> #ifdef HAVE_CXX11_ATOMIC
> #include <atomic>
> #elif defined(GLOG_OS_WINDOWS)
> # ifndef WIN32_LEAN_AND_MEAN
> #  define WIN32_LEAN_AND_MEAN  // We only need minimal includes
> # endif
> // To avoid macro definition of ERROR.
> //# ifndef NOGDI
> //#  define NOGDI
> //# endif
> // To avoid macro definition of min/max.
> # ifndef NOMINMAX
> #  define NOMINMAX
> # endif
> ```
I have the same question
Sorry，I can not understand what this meaning.
I find glog/logging.h and It looks like the code you posted.
Here is the code in logging.h.
```
#ifdef HAVE_CXX11_ATOMIC
#include <atomic>
#elif defined(GLOG_OS_WINDOWS)
# ifndef WIN32_LEAN_AND_MEAN
#  define WIN32_LEAN_AND_MEAN  // We only need minimal includes
# endif
// To avoid macro definition of ERROR.
# ifndef NOGDI
#  define NOGDI
# endif
// To avoid macro definition of min/max.
# ifndef NOMINMAX
#  define NOMINMAX
# endif

#include <Windows.h>
#endiff
```
What should I do to this code.

**Comment by JackBoosY** [comment]
@wbw24 Just waiting for merge https://github.com/microsoft/vcpkg/pull/24538

**Comment by whuaegeanse** [comment]
@wbw24 @ZZWang21 @Hyunkil76
Try again.
- Update & upgrade vcpkg. 
- Install colmap via vcpkg.
