### ISSUE TITLE
Feature Matching fail on nvidia driver 510.68.02 with RTX 3090 ti

### ISSUE THREAD

**Issue by jhurlbut** [colmap/colmap#1517]
I'm unable to run gpu feature matching with this card. The error is:
ERROR: Feature matching failed. This is probably caused by insufficient GPU memory. Consider reducing the maximum number of features and/or matches.

I believe this to be a false error though because the same training worked fine on a gpu with less memory and if I limit the number of features to something really small like 1 I still get the same error. I'm not sure if the cause of the issue is the driver version or the gpu version. The 3090 ti only supports driver version 510 though.

Is there a way to get a more detailed error report from the gpu to identify the issue?

**Comment by jhurlbut** [comment]
rebuilding from source after updating CUDA version fixed it

**Comment by AndreiBarsan** [comment]
Just curious, what CUDA version did you end up using?
