### ISSUE TITLE
Size limit for single images

### ISSUE THREAD

**Issue by tudipffmgt** [colmap/colmap#1518]
I wanted to ask if there is a size limit for single images?
I have three aerial images of size **25455 x 24403 pixels**.
I found around 2000 - 8000 okayish looking feature matches between every image pair but if I run the reconstruction the bundle adjustment terminates with: 'No convergence'.
I set reconstruction options to min_model_size 3 and unticked ignore_two_view_tracks

In earlier experiments I was already able to produce a sparse point cloud but I originally used downsampled images.
If I want to look at my feature matches I get a visual bug so I assumed that maybe the size is too large? 
(The attached image is also downsampled because of the original resolution of 50k x 24k pixels)

![aerial_test_downsampled](https://user-images.githubusercontent.com/46675239/167567568-b20548b1-988c-45e2-a1e4-89d39396c89e.png)

**Comment by ahojnnes** [comment]
Aerial imagery can be tricky to initialize due to typically large focal lengths and possible small baselines depending on the exposure frequency of the camera.

**Comment by ahojnnes** [comment]
It is hard to give any advice without seeing the actual images.

**Comment by tudipffmgt** [comment]
I tried again with the standard workflow, big images and custom focal length and was able to do a reconstruction.
Thanks.
