### ISSUE TITLE
Model georeferecing with GCPs

### ISSUE THREAD

**Issue by martidi** [colmap/colmap#152]
Hi, 

I opened a new issue about georeferencing, since it could be useful for someone else. I report here our previous discussion:

**Q: Is there a way to use GCPs to georeference the model? Or at the moment this is not available?
A: You can find the model_aligner binary in the bin folder that you downloaded from the website.**

My new question is:
Do you mean that the use of GCPs to georeference the model is possible only via command-line? Anyway, this model_aligner you mentioned seems to be usable only with camera position (model_aligner: Align/geo-register model to coordinate system of given camera centers), am I right? Instead I would need to use some Ground Control Points in order to georeference my model. Is there any way to do that?

Furthermore, as for the model_aligner, is the -ref_images_path the option to be used for the file containing cameras coordinates? I don't find any explanation for the options...

Thank you,

Martina

**Comment by ahojnnes** [comment]
At the moment, you can only geo-register with camera locations. ``--ref_images_path`` is the correct argument to which you supply the text file with the camera locations.

**Comment by martidi** [comment]
Do I have to run it after the reconstruction step? Is it correct that it creates 3 .bin files? How can I use them in order to obtain a geo-referenced model?

**Comment by KommandorKeen** [comment]
I echo @martidi.
I can successfully run model_aligner, but unsure where and how the results fit into a workflow.
