### ISSUE TITLE
CMake on colmap fails to find Qt5 package 

### ISSUE THREAD

**Issue by LenaSailor** [colmap/colmap#153]
Hi Johannes.

Have decided to carry out all further work on Linux (Mint18) and have struck a brick wall. Having spent a couple of days I've narrowed the problem down to within the **_FindQt5.cmake_** component.  I tweaked lines 6&7 to:

find_package(Qt5Core REQUIRED)
find_package(Qt5OpenGL REQUIRED)

It finds Qt5Core but not Qt5OpenGL despite the fact that  'location Qt5OpenGL' produces a positive result.

A package configuration problem I suspect but don't know how to proceed.  Any ideas?

Thanks in advance

Stuart

**Comment by ahojnnes** [comment]
Hi,

Can you try to follow the instructions for Mac:

	https://colmap.github.io/install.html#mac

Specifically, setting:

	set(Qt5_CMAKE_DIR "/usr/local/opt/qt5/lib/cmake")
	set(Qt5Core_DIR ${Qt5_CMAKE_DIR}/Qt5Core)
	set(Qt5OpenGL_DIR ${Qt5_CMAKE_DIR}/Qt5OpenGL)

And make sure to set ``Qt5_CMAKE_DIR`` correctly.

And report back whether this solves your problem?

Cheers,
Johannes

**Comment by LenaSailor** [comment]
Hi

 

Thanks for your prompt response.

 

As question stated I'm using Linux.  Are the Mac instructions relevant?

 

Stuart

**Comment by ahojnnes** [comment]
I am just referring to this:

	set(Qt5_CMAKE_DIR "/usr/local/opt/qt5/lib/cmake")
	set(Qt5Core_DIR ${Qt5_CMAKE_DIR}/Qt5Core)
	set(Qt5OpenGL_DIR ${Qt5_CMAKE_DIR}/Qt5OpenGL)

The rest should be as done in the regular Linux instructions. But replace "/usr/local/opt/qt5/lib/cmake" with wherever your Qt5 is located.

**Comment by LenaSailor** [comment]
Great. CMake completes OK.  Now waiting for compile to complete.

Will advise.

**Comment by LenaSailor** [comment]
So far so good.  Story so far:

Compiles without error.
GUI launches OK.
Create db and load images OK. (only 34 2000 x 1333  in set which I used before in Windows).
Feature extraction OK.
Feature matching OK.  Can see them via db.
Start reconstruction.  Almost instant termination. GUI disappears.

Any ideas?

**Comment by Boinet** [comment]
Hi everyone, 
I had the same issue. In my case the problem came from a conflict between anaconda's version of qt5 and ubuntu's. In my case the problem was solved by simply deactivating anaconda before building and installing Colmap.

**Comment by ishipachev** [comment]
> Hi everyone,
> I had the same issue. In my case the problem came from a conflict between anaconda's version of qt5 and ubuntu's. In my case the problem was solved by simply deactivating anaconda before building and installing Colmap.

Thank you @Boinet , was surprised why my build stopped working when I loaded conda in the server. Disabling Anaconda helped.
