### ISSUE TITLE
Rendering image reconstruction

### ISSUE THREAD

**Issue by Jintopia** [colmap/colmap#1532]
Hello, I'm trying to reconstruct a rendering view of a VolumeData such as [NiFti](https://nifti.nimh.nih.gov) or nii

I got the rendering image in [Voreen](https://www.uni-muenster.de/Voreen/)
This is because data is rendered only when a technique called Direct volume rendering is used due to the nature of image data.

My rendering image format is "png" but in metadata doesn't have camera postion or focal length ,metadata only consist of image size (H x W)

When I run `colmap feature_extractor`, the `colmap_output.txt` file save like below.

<img width="609" alt="image" src="https://user-images.githubusercontent.com/39505929/171344171-6242da6d-68c2-4c3a-8d20-224132404c8f.png">

The camera information file such as the camera.bin file is not generated while executing the code.

**As a result, I would like to ask you what kind of data should exist on the metadata of the image in order to create a file such as the camera.bin file?**

**Comment by tsattler** [comment]
Looking at the error message, it looks like Colmap fails to open the images, not that meta data is missing. Are the png files in some special format?

**Comment by Jintopia** [comment]
Thanks for reply! No, it just a png image which looks like below
This is just a rendering image captured in PNG format
![image](https://user-images.githubusercontent.com/39505929/172159736-9894c6e7-9947-412f-ae76-7be717f06cf0.png)

**Comment by tsattler** [comment]
Hm... I think the problem is that the image uses 64 bits while Colmap assumes 8 bits (see #284).

**Comment by Jintopia** [comment]
thanks i will check reference!

**Comment by ani0075saha** [comment]
@tsattler How does COLMAP fill in the focal length parameter for intrinsics from png files?

From what I read, png files do not contain focal length information, even in metadata. I tried reading metadata for my png files and I didn't find the information.

COLMAP docs says here (https://colmap.github.io/tutorial.html#feature-detection-and-extraction)
"You can either automatically extract focal length information from the embedded EXIF information or manually specify intrinsic parameters, e.g., as obtained in a lab calibration. If an image has partial EXIF information, COLMAP tries to find the missing camera specifications in a large database of camera models automatically."

I am using COLMAP GUI on Windows.
When I load in a set of png images, COLMAP automatically fills in a number for focal length after the feature extraction phase with the flag ```prior_focal_length``` set to 0. 

I am curious to know how COLMAP arrives at that number.
