### ISSUE TITLE
Exhaustive feature matching

### ISSUE THREAD

**Issue by l-janzen** [colmap/colmap#1546]
Hello, which algorithm is used in the Exhaustive feature matching?

**Comment by tsattler** [comment]
You can find implementation details for the exhaustive feature matcher here: https://github.com/colmap/colmap/blob/dev/src/feature/matching.h#L378 and here: https://github.com/colmap/colmap/blob/dev/src/feature/matching.cc#L886

You can find details on the used matching algorithm here: https://github.com/colmap/colmap/blob/dev/src/feature/matching.h#L342

**Comment by l-janzen** [comment]
Is it Brute Force?

**Comment by tsattler** [comment]
Yes, it is.

**Comment by l-janzen** [comment]
Thank you very much!
