### ISSUE TITLE
Without calling `FreeImage_Initialise()`, the result from `FreeImage_GetFileType` always becomes `FIF_UNKNOWN` 

### ISSUE THREAD

**Issue by jasjuang** [colmap/colmap#1548]
**Describe the bug**
Colmap is unable to read common `.png` or `.jpg` images. E.g.
```
==============================================================================
Feature extraction
==============================================================================

Processed file [1/50]
  Name:            0001.jpg
  ERROR: Failed to read image file format.
```

After some debugging, I realize this line `https://github.com/colmap/colmap/blob/dev/src/util/bitmap.cc#L466` results in `FIF_UNKNOWN` no matter what kind of images I input. After some research, I realize `FreeImage_Initialise()` and `FreeImage_DeInitialise()` calls are absent from colmap. After I added `FreeImage_Initialise()` into the constructor of bitmap and created a destructor for bitmap with `FreeImage_DeInitialise()` in it. The feature extraction starts to work as expected. 

It is unclear to me why other users are not observing this issue. I tried installing freeimage from apt (`sudo apt install libfreeimage-dev`) and installing freeimage from vcpkg (`./vcpkg install freeimage`) but both requires `FreeImage_Initialise()` in order for colmap to function normally. 

**Desktop**
 - OS: Ubuntu 20.04
 - Compiler: GCC 9

**Comment by ahojnnes** [comment]
Are you linking against statically built freeimage? Could you please verify whether the following fixes the issue: https://github.com/colmap/colmap/pull/1549. Thank you.

**Comment by jasjuang** [comment]
Yes, I am linking to statically built freeimage and I can verify that #1549 solves the issue. Looking forward to the merge.

**Comment by ahojnnes** [comment]
Thanks for the bug report and verifying the fix.
