### ISSUE TITLE
GUI- timer is allways 00:00:00:00

### ISSUE THREAD

**Issue by TokyoWarfare** [colmap/colmap#1550]
**Describe the bug**
GUI- timer is allways 00:00:00:00 on the lower left bar. In the console, at the end it displays correct total time tho.

**To Reproduce**
Run a reconstruction and see how it stays 00

**Expected behavior**
 to cound the time of the total procesing time

**Screenshots**
not needed

**Desktop (please complete the following information):**
 - OS:  win 10
 - Version 3.8

**Comment by ahojnnes** [comment]
Cannot reproduce. Not reported by anybody else. Please feel free to reopen in case it comes up again.
