### ISSUE TITLE
entry point not found colmap.exe

### ISSUE THREAD

**Issue by FabianSchick1** [colmap/colmap#1556]
Hi, 

i still get the problem of "entry point not found"

Error:
Entry Point "?hitButton@QPushButton@@MEBA_NAEBVQPoint@@@Z" was not found in the dll "SomePath/colmap.exe"

I tried different solutions like installing different versions of colmap, make a scannow and so on. But nothing helped.

It is also strange that it is a .exe file and no .dll file.

Thanks in advance
![PXL_20220628_140230758 MP](https://user-images.githubusercontent.com/51674496/177011437-326fd815-8d98-4c78-9256-3c14f69fa0e4.jpg)

**Comment by ChinaShrimp** [comment]
The same issue with COLMAP 3.7: not found entry point inflateValidate in libpng16.dll
