### ISSUE TITLE
Dense reconstruction is distorted after specifying the shared intrinsics

### ISSUE THREAD

**Issue by TWang1017** [colmap/colmap#1559]
Hi, I use Colmap to do a dense reconstruction, I specified the shared intrinsics and extracted from EXIF

If i understand correctly, all images are collected from the same camera without modifying the focal length during practice, all intrinsics should be the same.

The reconstruted model looks good and complete but kind of distorted. please see the screenshot

![image](https://user-images.githubusercontent.com/47421732/177741601-df6dacec-e1ae-4923-bdee-c36590031b54.png)
![image](https://user-images.githubusercontent.com/47421732/177741654-5826f12f-bfb8-4be6-91d4-4a67a9bf3ac8.png)

**Desktop (please complete the following information):**
 - OS: WINDOWS
 - Version: Colmap 3.7

Appreciate any help thanks

**Comment by ahojnnes** [comment]
If you really selected pinhole as the camera model, then that might explain the issue, unless you undistorted your images before giving them to colmap. Otherwise, what happens when you just select the default and do not share the intrinsics?

**Comment by TWang1017** [comment]
> If you really selected pinhole as the camera model, then that might explain the issue, unless you undistorted your images before giving them to colmap. Otherwise, what happens when you just select the default and do not share the intrinsics?

when i do not select the shared intrinsics as prior knowledge and use default, the SFM failed and only half imgs are registered. I actually resolved the distortion by fixing the manually input intrinsics. Thansk
