### ISSUE TITLE
Ignore features of dynamic object in static scene

### ISSUE THREAD

**Issue by alex-klimov** [colmap/colmap#1563]
In our setup we use colmap to estimate the camera positions around the scene. The scene is static with the exception of dynamic object moving through the scene.

Dynamic object is sometimes ignored by colmap, which relies on static features for the reconstruction, but sometimes it leads to some pictures being dropped, as they cannot be matched. We want to avoid dropping pictures and we need the most pictures from all possible angles, while ignoring dynamic object.

To avoid the noise created by dynamic object during camera position estimation - is that possible to ignore the features of dynamic object? Is that possible to evaluate SIFT features of dynamic object and then configure colmap to ignore features of a given subset?

**Comment by tsattler** [comment]
It is possible to specify a mask for each image that defines in which regions features should and should not be extracted.

**Comment by alex-klimov** [comment]
Ah! I was looking for something like this. I will look closer into feature extraction parameters. Thank you!

Setting a mask would require creating mask detection for dynamic object. That is doable. I was also considering an alternative: cleaning up SIFT features from colmap database with known SIFT features after the extraction, which we would manually mark for given dynamic object.

**Comment by alex-klimov** [comment]
Dynamic object can be filtered out with the mask option explained in FAQ:
https://colmap.github.io/faq.html#mask-image-regions
