### ISSUE TITLE
Using OpenMVS ReconstructMesh to create a mesh from colmap dense reconstruction

### ISSUE THREAD

**Issue by rennu** [colmap/colmap#157]
Hi,

I'd like to use openmvs to create a mesh from a colmap created dense reconstruction. I'm able to create a nvm file from the dense reconstruction in colmap but apparently openmvs InterfaceVisualSFM doesn't know how to access a list of views for each point needed by openmvs. As you have the best knowledge about colmap's inner workings, can you help with the matter? I created a issue under openmvs issues [here](https://github.com/cdcseacave/openMVS/issues/226).

Thanks!

**Comment by ahojnnes** [comment]
Just to make sure I understand correctly. You want to use the dense depth and normal maps or the dense point cloud from Colmap to use the meshing of OpenMVS?

**Comment by rennu** [comment]
To put it short: I want to use openmvs ReconstructMesh to create a mesh from colmap dense reconstruction. I guess it needs both pointcloud and maps?

**Comment by ahojnnes** [comment]
I actually don't know about what information is needed by OpenMVS but most meshing algorithms only require the point cloud (+normals) as input. Did you try the ``dense_mesher`` in COLMAP?

**Comment by rennu** [comment]
I figured you two could maybe discuss about that?

I've done some comparing between the solutions. Colmap's end result tend to have more noise (extra floating mesh) than when done in openmvs. However, I've noticed that colmaps densified pointclouds seem a bit cleaner than openmvs'. That is why I figured it would be nice to use colmap densified pointclouds and openmvs for meshing.

**Comment by ahojnnes** [comment]
Can you some of the results? There several parameters in the Poisson meshing library that is shipped with COLMAP. If I see some output, I can give some recommendations.

**Comment by Ntweat** [comment]
I agree with @rennu . The meshing of COLMAP is very noisy, I tried playing with the parameters used default parameters, but there was no major improvement. 
The meshing and mesh reconstruction of openMVS is better.

**Comment by ManishSahu53** [comment]
@Ntweat  Can you tell me how dense point cloud of openMVS and Colmaps  are compared. Can you comment of accuracy, completness and time taken from both the methods?

**Comment by ahojnnes** [comment]
@ManishSahu53 I never used openMVS, but from user feedback I heard that the final meshing and mesh texturing is better in openMVS, while the dense point cloud reconstruction is better in COLMAP.

**Comment by Ntweat** [comment]
@ManishSahu53 I have stopped working with 3D reconstruction.

**Comment by oryxlynx** [comment]
For those who have the same issue as mine and in this topic to use dense point cloud of Colmap and then do the meshing in OpenMVS, 
To sum up for you, the function "InterfaceCOLMAP" from OpenMVS is able to import the dense point cloud of Colmap and convert it to .mvs format
Method and command are the same as when you import and convert the sparse point cloud but after finish densifying.

The main difference is that after you finish the densify in Colmap, fuse.ply and fuse.ply.vis (output of densifying) will be created. The function "InterfaceCOLMAP" will automatically check and do its work.
if there is no fuse.ply and fuse.ply.vis , it will import and convert out the sparse points
However, if there are fuse.ply and fuse.ply.vis , it will import and convert out the dense points

Thank you all contributors of Colmap and OpenMVS


I have quote the reply of cdcseacave here
> 
> 
> after COLMAP undistorts the images, it saves a new scene with PINHOLE cameras, you have to use that one instead
> 
> InterfaceCOLMAP is already able to import dense point cloud from COLMAP, exactly the same way as you do it for sparse, but once the dense one computed and saved

Relate issues
https://github.com/cdcseacave/openMVS/issues/360
https://github.com/colmap/colmap/issues/557
https://github.com/colmap/colmap/issues/157

**Comment by joschi1212** [comment]
To avoid unnecessary headaches, it is worth noting that interfaceCOLMAP will only search within the /dense folder and specifically for fused.ply and fused.ply.vis files. The file names are crucial; otherwise, only the sparse point cloud will be converted.
