### ISSUE TITLE
model_aligner does not work properly

### ISSUE THREAD

**Issue by TWang1017** [colmap/colmap#1571]
Hi, i use Realsense D455 to collect rosbag file and reconstructed it with open3d.

I realised there is a trajectory file looks like below which i suppose is the pose for each image
![image](https://user-images.githubusercontent.com/47421732/179757216-8e1f34aa-8a16-47b3-bb3d-ecf0bab03197.png)

After some research, these are poses (i.e., camera to world transformation) and extrinsics are their inverse (i.e., world to camera transformation).

I extracted rgb imgs from rosbag and tried to reconstruct with colmap to make some comparisons with the reconstruction from open3d pipeline. I use the normal colmap pipeline to produce sparse model and then use model_alinger to hopefully align the two models but no success.

The coordinates file is created as follows:

1. inverting the transformation matrix, extracting Tx Ty Tz to align, failed.
2. inverting the transformation matrix,  use -R^t * T to obtain the camera centers Tx Ty Tz as described in output format images.txt, failed.
3. no inversion, extracting Tx Ty Tz to align, failed.
4. no inversion, use -R^t * T to obtain the camera centers Tx Ty Tz, failed.
It looks something like the below, the circled are sparse models produced by colmap
![image](https://user-images.githubusercontent.com/47421732/179758896-fc17a4f7-cc90-486e-9b32-1bb09b3e2842.png)

Any help is much appreciated. Thanks

**Comment by xinchen-cx** [comment]
Hi，have you solved this problem? I have encountered similar questions.

**Comment by TWang1017** [comment]
> Hi，have you solved this problem? I have encountered similar questions.

The problem is associated with data acquisition, not the COLMAP in my case.
