### ISSUE TITLE
how to recompile with -fPIC

### ISSUE THREAD

**Issue by dodgaga** [colmap/colmap#1577]
since my ubuntu is 16.04, the newest version related is too higher for my system. So, I use the version 3.6[https://github.com/colmap/colmap/tree/3.6](url) to build. I occured the error with bitmap.cpp, and i solve it as [https://github.com/colmap/colmap/commit/1f19e61a57caf3f01c0add8ff7bc5d43c14e84be](url)

However, in the end, there is still some error that i can't understand:

-- Found installed version of Eigen: /usr/lib/cmake/eigen3
-- Found required Ceres dependency: Eigen version 3.2.92 in /usr/include/eigen3
-- Found required Ceres dependency: glog
-- Found required Ceres dependency: gflags
-- Found Ceres version: 1.14.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, OpenMP, Multithreading]
-- Found Eigen
--   Includes : /usr/include/eigen3
-- Found FreeImage
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
-- Found Glog
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
-- Found Glew
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
-- Found Qt
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Core
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5OpenGL
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets
-- Found CGAL
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libCGAL.so.11.0.1
-- Build type not specified, using Release
-- Enabling SIMD support
-- Enabling OpenMP support
-- Disabling interprocedural optimization
-- Autodetected CUDA architecture(s):  8.6
-- Enabling CUDA support (version: 11.2, archs: sm_86)
-- Enabling OpenGL support
-- Disabling profiling support
-- Enabling CGAL support
-- Configuring done
-- Generating done
-- Build files have been written to: /media/cmb/data1/colmap-3.6/build
Consolidate compiler generated dependencies of target lsd
Consolidate compiler generated dependencies of target sqlite3
Consolidate compiler generated dependencies of target flann
Consolidate compiler generated dependencies of target poisson_recon
Consolidate compiler generated dependencies of target pba
[  0%] Built target lsd
Consolidate compiler generated dependencies of target vlfeat
[  2%] Built target sqlite3
Consolidate compiler generated dependencies of target sift_gpu
Consolidate compiler generated dependencies of target graclus
[  4%] Built target flann
[  6%] Built target poisson_recon
[  6%] Linking CXX static library libpba.a
[ 20%] Built target vlfeat
[ 20%] Linking CXX static library libsift_gpu.a
[ 42%] Built target graclus
[ 46%] Built target pba
[ 52%] Built target sift_gpu
Consolidate compiler generated dependencies of target colmap_cuda
[ 54%] Linking CXX static library libcolmap_cuda.a
[ 56%] Built target colmap_cuda
Consolidate compiler generated dependencies of target colmap
[100%] Built target colmap
Consolidate compiler generated dependencies of target colmap_exe
[100%] Linking CXX executable colmap
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libboost_filesystem.a(operations.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libboost_filesystem.a(path.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libboost_program_options.a(cmdline.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libboost_program_options.a(options_description.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libboost_program_options.a(parsers.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libboost_program_options.a(variables_map.o): relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libboost_program_options.a(value_semantic.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libboost_program_options.a(positional_options.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libboost_program_options.a(convert.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libboost_program_options.a(config_file.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libboost_program_options.a(utf8_codecvt_facet.o): relocation R_X86_64_32S against symbol `_ZNK5boost15program_options6detail18utf8_codecvt_facet9do_lengthERK11__mbstate_tPKcS7_m' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libboost_system.a(error_code.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: 最后的链结失败: 输出不可表示的节
collect2: error: ld returned 1 exit status
src/exe/CMakeFiles/colmap_exe.dir/build.make:140: recipe for target 'src/exe/colmap' failed
make[2]: *** [src/exe/colmap] Error 1
CMakeFiles/Makefile2:802: recipe for target 'src/exe/CMakeFiles/colmap_exe.dir/all' failed
make[1]: *** [src/exe/CMakeFiles/colmap_exe.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ahojnnes** [comment]
Since nobody else answered so far, I am not sure anybody in the community can help with this specific request. If you cannot upgrade to a higher base system version, maybe you can run colmap in a VM/container with a newer OS version to avoid the problems.

**Comment by ahojnnes** [comment]
Since nobody else answered so far, I am not sure anybody in the community can help with this specific request. If you cannot upgrade to a higher base system version, maybe you can run colmap in a VM/container with a newer OS version to avoid the problems.
