### ISSUE TITLE
How to use point_triangulator

### ISSUE THREAD

**Issue by ArthurWuzh** [colmap/colmap#1579]
I have some question of the command below:
colmap point_triangulator --database_path build_withinfo/database.db --image_path images --input_path created/sparse --output_path build_withinfo/triangulated/sparse

![image](https://user-images.githubusercontent.com/43443127/180611981-6dd39fad-84b3-4645-b789-311c06ac7647.png)

There is no loading database, why?

**Comment by ahojnnes** [comment]
I guess there is no log statement in the code. Closing this thread. Feel free to submit a PR to add the respective log statement, if needed for your use case.
