### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by dodgaga** [colmap/colmap#1580]
CMAKE info:
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found METIS: /usr/include (found suitable version "5.1.0", minimum required is "5.1.0") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found required Ceres dependency: Eigen version 3.3.8 in /usr/local/share/eigen3/cmake
-- Found required Ceres dependency: glog
-- Found Ceres version: 2.2.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SchurSpecializations, Multithreading]
-- Found Boost: /usr/include (found version "1.58.0") found components: program_options filesystem graph system unit_test_framework 
-- Found Eigen3: /usr/local/include/eigen3 (Required is at least version "2.91.0") 
-- Found Eigen
--   Includes : /usr/local/include/eigen3
-- Found FreeImage
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
-- Found Metis
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libmetis.so
-- Found Glog
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so   
-- Found Glew
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- Found Qt
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Core
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5OpenGL
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets
-- Found CGAL
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libCGAL.so.11.0.1
-- Build type not specified, using Release
-- Enabling SIMD support
-- Enabling OpenMP support
-- Disabling interprocedural optimization
-- Autodetected CUDA architecture(s):  8.6
-- Enabling CUDA support (version: 11.2, archs: sm_86)
-- Enabling GUI support
-- Enabling OpenGL support
-- Disabling ccache support
-- Disabling profiling support
-- Enabling CGAL support
-- Configuring done
-- Generating done

make error:

[ 92%] Building CXX object src/CMakeFiles/colmap.dir/util/misc.cc.o
/media/cmb/data1/colmap/src/feature/sift.cc: In function ‘bool colmap::ExtractSiftFeaturesGPU(const colmap::SiftExtractionOptions&, const colmap::Bitmap&, SiftGPU*, colmap::FeatureKeypoints*, colmap::FeatureDescriptors*)’:
/media/cmb/data1/colmap/src/feature/sift.cc:870:49: error: ‘GL_LUMINANCE’ was not declared in this scope
                         bitmap_raw_bits.data(), GL_LUMINANCE, GL_UNSIGNED_BYTE);
                                                 ^~~~~~~~~~~~
/media/cmb/data1/colmap/src/feature/sift.cc:870:63: error: ‘GL_UNSIGNED_BYTE’ was not declared in this scope
                         bitmap_raw_bits.data(), GL_LUMINANCE, GL_UNSIGNED_BYTE);
                                                               ^~~~~~~~~~~~~~~~
src/CMakeFiles/colmap.dir/build.make:761: recipe for target 'src/CMakeFiles/colmap.dir/feature/sift.cc.o' failed
make[2]: *** [src/CMakeFiles/colmap.dir/feature/sift.cc.o] Error 1
make[2]: *** 正在等待未完成的任务....
CMakeFiles/Makefile2:673: recipe for target 'src/CMakeFiles/colmap.dir/all' failed
make[1]: *** [src/CMakeFiles/colmap.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by whuaegeanse** [comment]
Replace
 ```
 const int code = sift_gpu->RunSIFT(bitmap.ScanWidth(), bitmap.Height(),
                                     bitmap_raw_bits.data(), GL_LUMINANCE, GL_UNSIGNED_BYTE)
```
 by
 ```
 const int code = sift_gpu->RunSIFT(bitmap.ScanWidth(), bitmap.Height(),
                                     bitmap_raw_bits.data(), 0x1909, 0x1401)
```
