### ISSUE TITLE
MacOS failed to reconstruction

### ISSUE THREAD

**Issue by Evader233** [colmap/colmap#1581]
MacOS with M1 max and 64G RAM, medium quality reconstruction successfully, but choose high quality above the gui crash immediately.
F20220725 17:24:22.559476 1989655 sift.cc:659] Check failed: octave_scale_idx <= prev_octave_scale_idx (2136981259 vs. -2070937891) 
*** Check failure stack trace: ***
    @        0x104cd3d50  google::LogMessageFatal::~LogMessageFatal()
    @        0x104ccff3c  google::LogMessageFatal::~LogMessageFatal()
    @        0x10437ce70  colmap::ExtractCovariantSiftFeaturesCPU()
    @        0x10435c440  colmap::internal::SiftFeatureExtractorThread::Run()
    @        0x1044e2264  colmap::Thread::RunFunc()
    @        0x1044e2404  std::__1::__thread_proxy<>()
    @        0x1abca826c  _pthread_start
zsh: abort      colmap gui

**Comment by basit-7** [comment]
@Evader233 Hi, how did you compile COLMAP on MacOS M1?

**Comment by Evader233** [comment]
@basit-7 I install Colman in anaconda, you can look at this link https://anaconda.org/conda-forge/colmap

**Comment by DWhettam** [comment]
@zhefujin Were you able to solve this?
