### ISSUE TITLE
COLMAP SfM camera poses are not in relation with reconstructed object

### ISSUE THREAD

**Issue by McHoody** [colmap/colmap#1583]
Recently I was using COLMAP and to evaluate results I needed to align final point cloud with ground truth. I decided to align camera poses to get initial transformation matrix, but it turned out, that COLMAP camera poses are not in any relation with final model (first image). This is weird to me, because both COLMAP and deep MVS methods, that were using this SfM camera poses achived decent results and it is hard to belive that this camera poses are correct. 

Ground truth camera poses and target model (I was using rendered images) and are shown at the second picture.

**COLMAP** reconstruction and its camera poses (red points in the left bottom corner).
![obraz](https://user-images.githubusercontent.com/53352763/181071928-ac616867-1fc1-4973-9c00-7e94158ac126.png)

**Ground truth** model and camera poses (green points around object).
![obraz](https://user-images.githubusercontent.com/53352763/181072657-52f67776-e916-40cc-bad3-4517f66182d0.png)

**Comment by tsattler** [comment]
Are you sure you are doing the alignment correctly?

**Comment by McHoody** [comment]
These positions on the red image are direct output from **COLMAP** SfM pipeline.
If anybody want to reproduce that behaviour I upload camera poses from file _images.txt_ (**camera_poses.txt**), final dense cloud (**colmap_dense_fused.zip**) and code to reproduce red cloud (_Open3D_ is necessary).

[camera_poses.txt](https://github.com/colmap/colmap/files/9197647/camera_poses.txt)
[colmap_dense_fused.zip](https://github.com/colmap/colmap/files/9197667/colmap_dense_fused.zip)
```python
import open3d as o3d
import numpy as np


def load_points(file):
    with open(file) as f:
        lines = [line.rstrip().split(" ") for line in f.readlines()]

    points = np.asarray(lines[4:])[:, 5:8]
    cloud = o3d.geometry.PointCloud()
    cloud.points = o3d.utility.Vector3dVector(points)
    return cloud

cloud = o3d.io.read_point_cloud("./colmap_dense_fused.ply")
positions_cloud = load_points("./camera_poses.txt")

cloud.paint_uniform_color([1,0,0])
positions_cloud.paint_uniform_color([1,0,0])

o3d.visualization.draw_geometries([cloud, positions_cloud])
```

**Comment by tsattler** [comment]
This will not properly visualize the image poses. The `images.txt` file stores the translation part of the pose, not the position of the image in the scene (see https://colmap.github.io/format.html#images-txt). You will need to compute the coordinates of the camera center from the rotation and the translation and visualize this. Directly visualizing the translation part does not lead to meaningful results.

**Comment by ahojnnes** [comment]
Maybe the explanations here help: https://colmap.github.io/format.html#images-txt
