### ISSUE TITLE
Keypoint Coordinates are unexpected values

### ISSUE THREAD

**Issue by joerowelll** [colmap/colmap#1585]
I have run a sparse reconstruction and extracted the keypoints using (a slightly modified) databases.py python script, see below.
Some of the keypoint pixel positions identified are -ve, decimal, or larger than the dimensions of the input images. How can a pixel coordinate take these values?
** To Reproduce **
See databases.py modification to reproduce below.
```
def extract_keypoints(filename):
    '''
    Function to extract SIFT keypoints from colmap database sparse reconstruction
    INPUT: Path to CSV
    OUTPUT: CSV file with imageId, Keypoints X, Keypoints Y, Semantic Label (blank)
    
    '''
    import os
    import argparse
    import csv
    import pandas as pd

    #Avoid np array truncation, comment this out if debugging
    np.set_printoptions(threshold=sys.maxsize) 

    parser = argparse.ArgumentParser()
    parser.add_argument("--database_path", default="database.db")
    args = parser.parse_args()

    # if os.path.exists(args.database_path):
    #     print("Database path exists.")
        

    # Open the database.

    db = COLMAPDatabase.connect(args.database_path)

    # Read and check keypoints.
 
    keypoints = dict(
        (image_id, blob_to_array(data, np.float32, (-1, 2)))
        for image_id, data in db.execute(
            "SELECT image_id, data FROM keypoints"))
    #print(keypoints[1])
    #assert np.allclose(keypoints[image_id1], keypoints1)

    # write to csv
    with open(filename, 'w') as f:
        for key in keypoints.keys():
            for i in range(len(keypoints[key])):
                # imageId, X, Y, Semantic Label
                f.write("%s, %s, %s ,%s\n" % (key, keypoints[key][i,:][0], keypoints[key][i,:][1], semanticLabel(key,keypoints[key][i,:][0],keypoints[key][i,:][1])))
                #print(key, keypoints[key][:][0],keypoints[key][:][1])

    assert os.path.exists(filename)

    if os.path.exists(filename):
        print("Written keypoints to .csv successfully.")
    #np.savetxt('keypoints.csv', keypoints, delimiter=',')

    db.close()

    file = pd.read_csv(filename)
    # adding headers
    headerlist = ["imageId", "keypoints X", "keypoints Y", "semantic label"]

    # converting data frame to csv
    file.to_csv(filename, header=headerlist, index=False)



def semanticLabel(imageId, X, Y):
    '''
    Function to determine semantic label of colmap identified keypoints using DeepLab 
    semantic segmentation as a reference
    INPUT: csvPath path to csv file that holds keypoint location data
    OUTPUT: append a column of semantic label on to csv file
    '''
    from PIL import Image
    im = Image.open(r"/home/joerowelll/COMP0132/brighton_workspace/segmentation/out" + str(imageId) +".png")
    px = im.load()
    coordinate = (int(float(X)), int(float(Y))) # 
    semLabel = im.getpixel(coordinate)

    return semLabel

if __name__ == "__main__":
    extract_keypoints("/home/joerowelll/COMP0132/brighton_workspace/brightonKeypoints.csv")


```
If the script is run without semanticLabel column in csv, the output X,Y image cooridnates are as described.

**Expected behavior**
I expected the keypoint coordinates to be integer values between 0-255
![Screenshot from 2022-07-26 22-11-14](https://user-images.githubusercontent.com/79405074/181112787-6ba21394-66f4-428a-ae59-3286eca39c64.png)

**Desktop:**
 - OS: Ubuntu 18.04

**Comment by tsattler** [comment]
Each keypoint is represented by 6 values, namely 2 pixel coordinates and 4 values defining the shape of the features (see https://github.com/colmap/colmap/blob/dev/src/base/database.cc#L54). `blob_to_array(data, np.float32, (-1, 2))` should thus be `blob_to_array(data, np.float32, (-1, 6))` if you do not want to create meaningless keypoints.

Note that SIFT features are sub-pixel accurate and keypoint coordinates are thus not integer values.

**Comment by joerowelll** [comment]
Thank you, I have made this change and the XY coordinates are no longer -ve. 

However, they are still larger than the dimensions of the input image. I am writing the 0th and 1st column (X and Y) of the Keypoints to csv, is this correct?

I didn't realise SIFT features have sub pixel accuracy, that's brilliant.

**Comment by ahojnnes** [comment]
1. Keypoints coordinates being slightly outside the image boundaries is expected with the SIFTGPU implementation due to rounding errors from higher scale levels and subpixel refinement of the positions.
2. I wouldn't necessarily call it subpixel accuracy that is repeatable across different views even though you get floating point coordinates. Depending on the scale at which the keypoints are detected, the actual position of the keypoint can have quite high standard deviations when seen from multiple views.
