### ISSUE TITLE
images.txt

### ISSUE THREAD

**Issue by basit-7** [colmap/colmap#1587]
I wanted to make sure that I am interpreting images.txt correctly. According to my understanding, the quaternion and translation (RT/pose) for all the images is relative to one image. So all the poses are relative to one of the pose, is that right?

**Comment by tsattler** [comment]
The poses are defined relative to a global coordinate system of the 3D model. This global coordinate system is initialized to coincide with the coordinate system of one of the images, but diverges from this image coordinate system during the reconstruction process (see the various open and closed issues discussing this behavior). As such, all poses are not relative to one of the poses.

**Comment by basit-7** [comment]
@tsattler Hi, Thanks for the quick response. 

If we perform reconstruction using our own poses, are we suppose to give absolute poses in images.txt?

**Comment by tsattler** [comment]
Yes, see the Colmap documentation.
