### ISSUE TITLE
Z axis of Dense Cloud

### ISSUE THREAD

**Issue by hayatuabdul** [colmap/colmap#1588]
Hello, I’m undertaking a project where I manipulate the depth of a 3D reconstruction (Colmap Dense Cloud). I've successfully figured out how to do that by accessing and modifying the Z axis of the point cloud. 

However, I noticed that the Z axis is rather inconsistent in regard to the direction towards the environment. My question is, how does Colmap compute the direction of the Z axis towards the environment? And how do I change it?

For example, I’m trying to remove the depth of the below scene so only the shoe is visible(bottle and cup removed). 
![image](https://user-images.githubusercontent.com/72262907/182219349-0804d96f-5224-4ea4-a28b-d1f2201d5257.png)

But as you can see, the depth reduction started from the left of the shoe instead of the front.
![image](https://user-images.githubusercontent.com/72262907/182219575-034b7f91-e94e-4b95-969b-82c136308c22.png)

Any help would be appreciated

**Comment by ahojnnes** [comment]
The scale, orientation and origin of the reconstructed scene is completely arbitrary, which is an inherent problem of pure image-based 3D reconstruction. COLMAP has a built-in tool that allows you to align the orientation of a reconstruction based on a manhattan world assumption using vanishing point estimation. You can try using the `model_orientation_aligner` for that. Alternatively, if your camera has a built-in IMU, you could do a gravity alignment manually with some Python scripts.
