### ISSUE TITLE
Processing time taken to reconstruct an object

### ISSUE THREAD

**Issue by l-janzen** [colmap/colmap#1589]
Hello, where can I find the processing time taken to reconstruct an object?

**Comment by tsattler** [comment]
The time needed for the individual stages is printed on the command line respectively the text output field in the GUI.

**Comment by tsattler** [comment]
The reconstruction time is not saved and it is not possible to determine precisely how much time was used without running the reconstruction.

**Comment by l-janzen** [comment]
Good. Thank you very much for your reply!
