### ISSUE TITLE
ReconstructMesh crashes with a segfault while weighting points - Mac

### ISSUE THREAD

**Issue by cdavietei** [colmap/colmap#1597]
I'm trying to run ReconstructMesh on points extracted from the [Gerrad Hall](https://onedrive.live.com/?authkey=%21AAQumsDDwZBIW3w&id=C58A258D760E1B58%2146879&cid=C58A258D760E1B58) sample data set from ColMap. I followed [this guide](https://www.instructables.com/Free-Photogrammetry-on-Mac-OS-From-Photos-to-3D-Mo/) to use ColMap to extract the points and then Densify and construct the mesh from the points. However when I run ReconstructMesh, I get a vague Seg fault once the script starts weighting the points.

I tried deletion my build and rebuilding clean following [the build wiki](https://github.com/cdcseacave/openMVS/wiki/Building#mac-os-x-compilation) but still no luck.

```
% ReconstructMesh proj_dense.mvs -v 3
```
I am running this with:
* OS: MacOS 12.3.1
* Processor: 2.3 GHz 8-Core Intel Core i9
* Memory: 16 GB 2667 MHz DDR4
* Graphics: Intel UHD Graphics 630 1536 MB

I'm not sure what else to debug as I can't seem to get the script to output where the segmentation fault happened. I'm also not sure what else I can upload to help with identifying the issue as the `.mvs` file I am using is 1.68 GB, but happy to upload to Drive or something if that helps other reproduce this.

Any further debugging tips are greatly appreciated!

Terminal output
```
% ReconstructMesh proj_dense.mvs -v 3       
21:47:46 [App     ] Build date: Aug 15 2022, 21:44:05
21:47:46 [App     ] CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 cores)
21:47:46 [App     ] RAM: 16.00GB Physical Memory 16.00GB Virtual Memory
21:47:46 [App     ] OS: Darwin 21.4.0 (x86_64)
21:47:46 [App     ] Disk: 
21:47:46 [App     ] SSE & AVX compatible CPU & OS detected
21:47:46 [App     ] Command line: ReconstructMesh proj_dense.mvs -v 3
21:48:09 [App     ] Scene loaded (23s166ms):
	100 images (100 calibrated) with a total of 406.49 MPixels (4.06 MPixels/image)
	35411375 points, 0 vertices, 0 faces
Points inserted 35411375 (100%, 2m48s570ms)           D
21:51:53 [App     ] Delaunay tetrahedralization completed: 35411375 points -> 15856319 vertices, 101088074 (+104) cells, 202176200 (+156) faces (3m41s780ms)
Points weighted 361056 (2.28%, 2m8s, ETA 1h31m)...zsh: segmentation fault  $oMVS/ReconstructMesh proj_dense.mvs -v 3
```

**Comment by tsattler** [comment]
This question seems more appropriate for the openMVS github as ReconstructMesh is part of openMVS and not part of Colmap.

**Comment by cdavietei** [comment]
You're totally right, I thought I was in the OpenMVS repo but I had the wrong tab open.

I'll post it there but thanks for the hypothesis, I'll investigate that!

**Comment by tsattler** [comment]
Do you want to close this issue then?
