### ISSUE TITLE
patch_match_stereo killed without reporting why

### ISSUE THREAD

**Issue by Camilochiang** [colmap/colmap#1599]
After running ```patch_match_stereo```  in ubuntu 18.04 /colmap 3.8 / with Cuda support (10.2), with:
```
        colmap patch_match_stereo \
            --workspace_path $DATASET_PATH/dense \
            --workspace_format COLMAP \
            --PatchMatchStereo.gpu_index 0 \
            --PatchMatchStereo.geom_consistency true
```
and iterating along all the pictures (Around 280), it re start from image 1 and get killed around image 82.

```
./bash_processing_colmap.sh: line 16: 18878 Killed                  colmap patch_match_stereo --workspace_path $DATASET_PATH/dense --workspace_format COLMAP --PatchMatchStereo.gpu_index 0 --PatchMatchStereo.geom_consistency true
```
I suspect that this is coming from a timeout from CUDA, where  the [documentation](https://colmap.github.io/faq.html#faq-dense-manual-source) recommend turning off lightdm service, which is not present. I guess that the recommendation in #823 is the best actual solution

After this process get kill, the following step (```stereo_fusion```, called with this command:
```
        colmap stereo_fusion \
            --workspace_path $DATASET_PATH/dense \
            --workspace_format COLMAP \
            --input_type geometric \
            --output_path $DATASET_PATH/dense/fused.ply
```
works, but the following error show up:
```
WARNING: Ignoring image DJI_0345.JPG, because input does not exist.
WARNING: Ignoring image DJI_0346.JPG, because input does not exist.
....
```
This warning is repeated for all images that are exactly after the ```patch_match_stereo``` die

I have repeat these steps in 3 different datasets, from the same place with the same amount of images (drone), and i get this problem in all of them.

Bug:
- Not sure if is expected to run several times along the images during patch_match_stereo. Could anyone please confirm?
- Is it normal that the images are ignored? even though the patch_match_stereo run once along them, I do not get why they are ignored or say that they do not exist

**Comment by Camilochiang** [comment]
So after checking the code on ```patch_match.cc``` i can answer my first question. (Please correct me if i'm wrong:
- No. It should only go once along the images
code in patch_match.cc lines 220-223:
```
  for (size_t problem_idx = 0; problem_idx < problems_.size(); ++problem_idx) {
    thread_pool_->AddTask(&PatchMatchController::ProcessProblem, this, options_,
                          problem_idx);
  }
```
Where previusly I have the output:
```
Reading workspace...
Reading configuration...
Configuration has 289 problems...
```

Where ```problems_.size() = 289```, comming from line 395 -397 in the same file:
```
  std::cout << StringPrintf("Configuration has %d problems...",
                            problems_.size())
            << std::endl;
```

**Comment by tsattler** [comment]
Patch match stereo will go up to two times over the images, depending on the configuration. The first pass is photometric, the second pass is geometric (which will be done by default unless configured otherwise) and builds on the depth maps from the previous stage if I remember correctly.

**Comment by Camilochiang** [comment]
Oh, interesting. Why is the reason then that is been killed? timeout from cuda?

**Comment by tsattler** [comment]
I am not sure why this happens. I have had crashes in the patch match part, but very infrequently.
