### ISSUE TITLE
Generated a .sln project from colmap by CMake, but failed to build colmap_exe project

### ISSUE THREAD

**Issue by citystrawman** [colmap/colmap#1600]
I tried to build colmap from source code and used CMake, by setting its dependencies(I followed the trick [here](https://thatonegamedev.com/cpp/how-to-manage-dependencies-with-cmake-and-vcpkg/)) I successfully built the vs 2019 solution (see my screenshots)
![image](https://user-images.githubusercontent.com/9004748/185359055-206f3f04-b297-4e62-96be-3a35507f05d2.png)
![image](https://user-images.githubusercontent.com/9004748/185359272-a827b052-ca06-476b-908f-eb90e9f415fc.png)

And I could build **colmap colmap_cuda** as well as **all projects in lib** folder. Howerver I could not build **colmap_exe** project (I assume it is the project to run)and the error messages are as follows:
![image](https://user-images.githubusercontent.com/9004748/185359576-a137708e-2033-42a2-8aab-623f76e37e57.png)

can anyone help me solve this issue?

**Comment by ahojnnes** [comment]
Try with the latest commit in the dev branch. There were some fixes for Metis merged recently that should hopefully help.

**Comment by citystrawman** [comment]
> 
I redownloaded the colmap from git and use 
`D:\software\colmap-build> cmake ..\colmap\ -DCMAKE_TOOLCHAIN_FILE=D:\software\vcpkg\scripts\buildsystems\vcpkg.cmake`
and then ` cmake --build .`  
after that, open the .sln and set colmap_exe as startup project and run it successfully.
