### ISSUE TITLE
Visualization of feature correspondence between query image to mapping image

### ISSUE THREAD

**Issue by thealchemist89** [colmap/colmap#1601]
Hi,

I am interested to see the keypoints' feature correspondences between query image and the associated mapping image from the top image retrieval entry after performing a localization.

Is there a way in which I could visualize the above using colmap gui?

Thank you for your guidance and help in advance!

**Comment by tsattler** [comment]
The feature matches can be visualized in the gui (under database management).

**Comment by thealchemist89** [comment]
Thank you for pointing me to what I was searching for @tsattler!

Deeply appreciated,
Kenny
