### ISSUE TITLE
Are the image poses relative to the previous one ?

### ISSUE THREAD

**Issue by alexs7** [colmap/colmap#1602]
Hello,

I wanted to ask about how COLMAP generates the image poses, found here:
https://colmap.github.io/format.html#images-txt

I know from the paper that is starts off by two images, and if they are good enough then more images are appended in an incremental fashion. 

But each generated image pose is the relative pose to the previous image? So if I pick image with id = 3 then its pose is the relative pose from image with id = 2 ? Also the first pose should be placed in the origin always ?

Thanks for clarifying !

**Comment by tsattler** [comment]
Camera poses are defined wrt. a global coordinate system (see https://colmap.github.io/format.html#images-txt). The global coordinate system is initialized to coincide with the coordinate system of the first image that gets reconstructed, but diverges during the reconstruction process (there should be multiple issues discussing this behavior).

**Comment by alexs7** [comment]
Ok makes sense. Thanks!
