### ISSUE TITLE
Avoid reconstruction bending 

### ISSUE THREAD

**Issue by Camilochiang** [colmap/colmap#1603]
Hei! Simple question

Is there any way / setting / recommendation to avoid 3D reconstruction to bend (see image)?

I'm using drone images of a flat surface with GPS coordinates, so not sure if for example:
- colmap use the gps coordinates for helping the matching process by default? and if yes
- if  this can be changed  to maybe avoid bending ? I had a look to the documentation but I didn't find too much

![Screenshot from 2022-08-25 09-45-57](https://user-images.githubusercontent.com/48471579/186606167-8cb97b04-62c8-49b5-a24e-c496747e2d46.png)

**Comment by tsattler** [comment]
Are you calibrating the cameras as part of the reconstruction process. There are some configurations where the bending occurs together with the calibration, see https://openaccess.thecvf.com/content_cvpr_2014/papers/Wu_Critical_Configurations_For_2014_CVPR_paper.pdf .

**Comment by Camilochiang** [comment]
Im using the following configuration
```
        colmap feature_extractor --database_path $DATASET_PATH/database.db \
            --image_path $DATASET_PATH"/100MEDIA" \
            --SiftExtraction.use_gpu 1 \
            --SiftExtraction.gpu_index=0\
            --SiftExtraction.max_image_size 4000 \
            --SiftExtraction.max_num_features 80000 \
            --ImageReader.single_camera 1 \
            --ImageReader.camera_model OPENCV
```
I will try with other camera_model or giving the already known ImageReader.camera_params! Thanks

**Comment by Camilochiang** [comment]
Problem solve chaning camera_model to ```RADIAL```
![Screenshot from 2022-08-26 10-34-32](https://user-images.githubusercontent.com/48471579/186860146-fc6b2785-f77e-46f1-a9aa-39a3adebaa4a.png)
