### ISSUE TITLE
Where's the original point of the world coordinate?

### ISSUE THREAD

**Issue by wtishere** [colmap/colmap#1608]
Thanks for your awesome work! I'm just wondering where the original point (0, 0, 0) of the world space locates after reconstruction. Thank you so much.

**Comment by ahojnnes** [comment]
The origin is arbitrary. It will be roughly at the median location of all registered images.

**Comment by delaprada** [comment]
> The origin is arbitrary. It will be roughly at the median location of all registered images.

May I ask whether the median location of all registered images is the median location of the 3D scene?
