### ISSUE TITLE
Model aligner fails

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [colmap/colmap#1612]
**Describe the bug**
When trying to use the colmap `model_aligner` using simulated images that are geotagged in the enu frame, the model aligner fails

The alignment itself seems to succeed, but colmap checks whether a file is open in the output path, which doesn't exist

**To Reproduce**
1. Run colmap `model_alinger`
```
colmap model_aligner \
    --input_path $DATASET_PATH/sparse/0/ \
    --output_path ./sparse/1 \
    --ref_images_path $DATASET_PATH/camera.txt \
    --alignment_type enu \
    --robust_alignment 1 \
    --robust_alignment_max_error 3
```

**Expected behavior**

**Screenshots**
```
Aligning reconstruction to ECEF
-------------------------------
 => Using 100 reference images
 => Alignment error: 0.075301 (mean), 0.054303 (median)

Aligning reconstruction to ENU
------------------------------
 => Alignment succeeded
F0830 18:19:28.084539 25396 reconstruction.cc:1999] Check failed: file.is_open() ./sparse/1/cameras.bin
*** Check failure stack trace: ***
    @     0x7ff42f4270cd  google::LogMessage::Fail()
    @     0x7ff42f428f33  google::LogMessage::SendToLog()
    @     0x7ff42f426c28  google::LogMessage::Flush()
    @     0x7ff42f429999  google::LogMessageFatal::~LogMessageFatal()
    @     0x555c45f1337e  (unknown)
    @     0x555c45f13bab  (unknown)
    @     0x555c45e6add9  (unknown)
    @     0x555c45e37733  (unknown)
    @     0x7ff42aed6c87  __libc_start_main
    @     0x555c45e4164a  (unknown)
./scripts/register.sh: line 16: 25396 Aborted                 (core dumped) colmap model_aligner --input_path $DATASET_PATH/sparse/0/ --output_path ./sparse/1 --ref_images_path $DATASET_PATH/camera.txt --alignment_type enu --robust_alignment 1 --robust_alignment_max_error 3
Makefile:14: recipe for target 'register' failed
make: *** [register] Error 134
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by tsattler** [comment]
Does the folder `./sparse/1` exist? Seems to me that Colmap can't write to the folder.

**Comment by Jaeyoung-Lim** [comment]
@tsattler Yes, it does (I have also tried with something like `$DATASET_PATH/sparse/1/`) 

What I am a bit confused is whether if the folder is empty, the model aligner would write to that folder? Because in the `reconstructions.cc` it seems to only check whether the file is already open: https://github.com/colmap/colmap/blob/5879f41fb89d9ac71d977ae6cf898350c77cd59f/src/base/reconstruction.cc#L1964

Is it assuming that the input path and output path are always the same?
