### ISSUE TITLE
SFM pipeline crashes with an SQLite error

### ISSUE THREAD

**Issue by saunair** [colmap/colmap#1613]
**Describe the bug**
While creating the colmap database, a diskio error gets thrown by sqlite.
<img width="1016" alt="Screen Shot 2022-08-30 at 6 06 26 PM" src="https://user-images.githubusercontent.com/9517734/187570633-994157f3-de92-4411-a286-80d75e1e43c7.png">

I have run sfm on this dataset before, so this is something new with my machine. Any clues on why this might be happening? 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tsattler** [comment]
It seems to be a problem of writing to the disk. Are you running out of space on the disk?

**Comment by saunair** [comment]
It was due to a disk partition. Changing the location of the database to another disk fixed it

**Comment by wariot221zjsru** [comment]
I also meet this problem! Why close the issue? I think that it has not solved completely yet!

**Comment by wariot221zjsru** [comment]
My problem:

············
I20251106 21:45:10.660866 17528 database_cache.cc:76]  3249 in 0.015s
I20251106 21:45:10.661213 15280 database_cache.cc:84] Loading matches...
I20251106 21:45:10.661396 17528 database_cache.cc:84] Loading matches...
E20251106 21:47:51.253105  2776 database.cc:600] SQLite error: disk I/O error
E20251106 21:47:53.242161  4544 database.cc:600] SQLite error: disk I/O error
E20251106 21:48:01.821386 11228 database.cc:600] SQLite error: disk I/O error
E20251106 21:48:01.826378 11416 database.cc:600] SQLite error: disk I/O error
E20251106 21:48:01.826449 17528 database.cc:600] SQLite error: disk I/O error
E20251106 21:48:01.929978 15280 database.cc:600] SQLite error: disk I/O error
E20251106 21:48:01.939568 10860 database.cc:600] SQLite error: disk I/O error
E20251106 21:48:02.045605 17536 database.cc:600] SQLite error: disk I/O error
E20251106 21:51:45.629129  4544 database.cc:1331] SQLite error: disk I/O error
E20251106 21:51:49.064778  2776 database.cc:1331] SQLite error: disk I/O error
E20251106 21:51:50.910924 11228 database.cc:1331] SQLite error: disk I/O error
E20251106 21:51:51.156904 17536 database.cc:1331] SQLite error: disk I/O error
E20251106 21:51:53.544510 11416 database.cc:1331] SQLite error: disk I/O error
E20251106 21:51:53.580466 10860 database.cc:1331] SQLite error: disk I/O error
E20251106 21:51:53.672907 17528 database.cc:1331] SQLite error: disk I/O error
E20251106 21:51:53.727180 15280 database.cc:1331] SQLite error: disk I/O error
I20251106 21:51:53.774287  8744 misc.cc:44]
==============================================================================
Merging clusters
==============================================================================
PS F:\Drone_Project_2025_F\colmap_datasets\zjsru_gcq_combine_all_F_9>

I use power shell to run colmap and also meet sqlite io problem.

**Comment by wariot221zjsru** [comment]
Can this issue reopen?
