### ISSUE TITLE
Backprojecting 3D points onto 2D image plane

### ISSUE THREAD

**Issue by eyildiz-ugoe** [colmap/colmap#1623]
I have a Python script where I feed my stereo image pair into a Colmap process and I end up with a model. So far, all good.

I'd like to, however, be able to backproject the points in 3D onto these stereo images I had fed in (in total 328 images), to see where they actually fall on the image. Given that Colmap figures out the camera parameters, this should be doable. I've seen that there is a file that is called Points3D.bin (https://colmap.github.io/format.html#images-txt)  and it contains the points in the fused point cloud. Wouldn't I get my pixel points if I read this file and used the camera matrix to backproject them?

![Untitled Diagram drawio](https://user-images.githubusercontent.com/35396058/188600472-8438739c-8e2b-41c7-9f83-9494bb27816c.png)

So, given PointA's 3D coordinates, can't I obtain the 2D pixel coordinates of the same PointA in both images?

For clarification, here is my colmap folder structure with eleven directories:

```
.
├── ./dense
│   ├── ./dense/images
│   ├── ./dense/sparse
│   └── ./dense/stereo
│       ├── ./dense/stereo/consistency_graphs
│       ├── ./dense/stereo/depth_maps
│       └── ./dense/stereo/normal_maps
├── ./images
├── ./masked_images
└── ./sparse
    └── ./sparse/0
```

So, my idea is to read the file Points3D.bin that is found under the location `/sparse/0` using the built-in function of Colmap, that is: 

```
def read_cameras_text(path):
    """
    see: src/base/reconstruction.cc
        void Reconstruction::WriteCamerasText(const std::string& path)
        void Reconstruction::ReadCamerasText(const std::string& path)
    """
    cameras = {}
    with open(path, "r") as fid:
        while True:
            line = fid.readline()
            if not line:
                break
            line = line.strip()
            if len(line) > 0 and line[0] != "#":
                elems = line.split()
                camera_id = int(elems[0])
                model = elems[1]
                width = int(elems[2])
                height = int(elems[3])
                params = np.array(tuple(map(float, elems[4:])))
                cameras[camera_id] = Camera(id=camera_id, model=model,
                                            width=width, height=height,
                                            params=params)
    return cameras
```
which is found at scripts/python/read_write_model.py#L101 of the repo. This should return me the camera matrices, which then should allow me to go from 3D world to 2D world. 

Am I on the correct track, or is this not really possible? I just want to get some expert opinion on this before I invest my time. If it is impossible, then I'd like to know.

**Comment by ahojnnes** [comment]
All of this is possible. Note that unless you first undistort your 3D model/images, you will have to account for lens distortion as well and the transformation is not a simple projection matrix but might need a non-linear operation in the end. In other words, to make your life easier, you want to first run the image_undistorter and then you can operate on a simple pinhole camera model.

**Comment by eyildiz-ugoe** [comment]
Thanks for the reply.
