### ISSUE TITLE
Can distance between images calculated from image metadata GPS coordinates be used to get absolute measurements from the reconstruction?

### ISSUE THREAD

**Issue by Kirang96** [colmap/colmap#1628]
@placeforyiming Please note that the units in a Colmap model have no physical meaning (i.e., they do not correspond to meters, centimeters, etc.). Without any additional information, e.g., the distance between two cameras or points in a scene, the absolute scale of a scene cannot be recovered from images alone as scaling the scene does not change the reprojection error that is minimized during the reconstruction process.

_Originally posted by @tsattler in https://github.com/colmap/colmap/issues/674#issuecomment-528977698_

If I'm capturing images using my mobile device, then using the GPS latitude and longitude information to calculate the distance between the captured images in meters and if I'm using those in Colmap for reconstruction, will I be able to get absolute measurements of the object that I captured in meters?
If it works, how do I use the distance between the images in colmap?

**Comment by tsattler** [comment]
You can check out whether you can use the`model_aligner` for this. Note that GPS measurements will be noisy.

**Comment by Kirang96** [comment]
@tsattler I tried to use `model_aligner `with the sparse reconstruction files that I have created using CLI.
I've completed feature_extraction, exhaustive_matching and point_triangulation to get those files.

When I try to align this sparse model with `model_aligner` with the database as the ref_image_path it gives me this error:


```
Converting Alignment Coordinates from GPS (lat/lon/alt) to ECEF.

Aligning reconstruction to custom
---------------------------------
 => Using 3 reference images
F0919 16:56:34.236671  4488 math.h:213] Check failed: !elems.empty()
*** Check failure stack trace: ***
    @   00007FF99BAC5FFB  public: void __cdecl google::LogMessage::Flush(void) __ptr64
    @   00007FF99BAC4B49  public: __cdecl google::LogMessageFatal::~LogMessageFatal(void) __ptr64
    @   00007FF64DEA26DA  (unknown)
    @   00007FF64DEB139C  (unknown)
    @   00007FF64DE84B16  (unknown)
    @   00007FF64DE8631B  (unknown)
    @   00007FF64E42F674  (unknown)
    @   00007FF9ACF47034  BaseThreadInitThunk
    @   00007FF9AD1426A1  RtlUserThreadStart
```

This is the code that I'm using to run the `model_aligner`:

` colmap model_aligner --input_path path/to/model/folder --output_path path/to/output/folder --ref_images_path path/to/database/file --robust_alignment_max_error 3.0`

1. How do I fix this?
2. Also does the model_aligner automatically use the GPS coordinates in the database for the alignment?

**Comment by tsattler** [comment]
Did you have a look at the documentation on the Colmap website (https://colmap.github.io/faq.html#geo-registration) and the code (https://github.com/colmap/colmap/blob/dev/src/exe/model.cc#L223-L263)?
