### ISSUE TITLE
What is k in ImageReader.camera_params?

### ISSUE THREAD

**Issue by is03wlei** [colmap/colmap#163]
My distortion coefficients has 5 numbers: 
<Distortion_Coefficients type_id="opencv-matrix">
  <data>
    2.9717157478222633e-01 -2.4931471522485045e+00 0. 0.
    7.0091780164034398e+00</data></Distortion_Coefficients>

**Comment by ahojnnes** [comment]
The order should be ``k1, k2, p1, p2, k3`` in the ``FULL_OPENCV_MODEL``. Set the rest to zero.
