### ISSUE TITLE
Problems with custom matching

### ISSUE THREAD

**Issue by Ale-Pinto** [colmap/colmap#1630]
Hello,
I am getting stuck while importing feature matching.
I have features and matches for those images, i have created the database and imported both features and matches in the tables.
Now i wanna run the command matches_importer. I created a match_list.txt file in which i have written image pairs to be matched and raw feature matches. The problem is that when i run the command, the feature matches are read as images and i keep getting errors.
Is there something i am missing in the match_list.txt?
![example](https://user-images.githubusercontent.com/107609187/189305400-36dddf58-1d22-4c3b-bd5d-e1f3a11ca1e5.JPG)

**Comment by tsattler** [comment]
Hard to help without any details on what the errors are.

Does your match_list.txt file have the right structure (see https://colmap.github.io/tutorial.html#feature-matching-and-geometric-verification)?

When running the `matches_importer`, do you set the `match_type` to `raw`?

**Comment by Ale-Pinto** [comment]
Thanks for your reply, i didn't noticed that possible parameter to set. 
I have now used matches_importer with the match_type raw but i am getting a new kind of error.
Seems something related to the database, i will attach a screen for help.
![error](https://user-images.githubusercontent.com/107609187/189597290-eeb8d806-f76b-40df-8f85-65ee99507c5a.JPG)

**Comment by tsattler** [comment]
Maybe you are trying to write an empty match list into the database?

**Comment by Ale-Pinto** [comment]
I created the match_list.txt following the example in the tutorial, so first line the images to be matched and below the features ids
[match_list_2.txt](https://github.com/colmap/colmap/files/9546993/match_list_2.txt)

**Comment by Ale-Pinto** [comment]
Hello,
i solved the problem was related to my database.
Thanks i will close the issue

**Comment by MvWouden** [comment]
> Hello, i solved the problem was related to my database. Thanks i will close the issue

I know this is some time ago, but do you happen to still recall what the issue was for you? It may help me.

**Comment by wtq523424999** [comment]
> I created the match_list.txt following the example in the tutorial, so first line the images to be matched and below the features ids [match_list_2.txt](https://github.com/colmap/colmap/files/9546993/match_list_2.txt)
Hello, I am a beginner and I would like to know how you created a match_list.txt . Looking forward to your reply, thank   you.  @Ale-Pinto

**Comment by paidiakileswar** [comment]
Hai @Ale-Pinto ,,

Can you tell me how can we get features and matches from images ! Is there any way other than default methods in colmap ! So that i will use for my custom matching
