### ISSUE TITLE
Reconstruction using pose priors stuck at loading model in model triangulation

### ISSUE THREAD

**Issue by Kirang96** [colmap/colmap#1633]
I'm trying to use the set of images with pose priors for reconstruction.
I do not get any errors when I run point_triangulator. It says loading model and ends:

```
==============================================================================
Loading model
==============================================================================
```

I've created the images.txt file as mentioned in the documentation. I've left every other line blank. It looks like this:

```
1  0.39964881 -0.24483059 -0.03971661  0.88247459 0.236693 -0.969321 -0.473446 1 000000.png

2  0.39846929 -0.25009968 -0.0398796   0.88152254 0.237343 -0.969224 -0.476806 1 000001.png

3  0.39836556 -0.26294141 -0.03936728  0.87784789 0.235755 -0.969554 -0.488945 1 000002.png

4  0.39654579 -0.27767237 -0.03919752  0.8741356  0.235549 -0.969633 -0.489875 1 000003.png

5  0.39201589 -0.29918597 -0.03766597  0.86913323 0.235410 -0.969282 -0.488228 1 000004.png
```
I was able to run feature extractor and exhaustive matcher successfully. Database was created in the mentioned folder. The image names and image id's in the images.txt match with those in the database file.

This is what I've understood and done after reading the documentation:
Created a folder called model and created 3 text files. One of them is images.txt file in the above mentioned format, points3D.txt file is a blank text file. cameras.txt file looks like this:
`1 SIMPLE_RADIAL 1920 1080 1521.98819966308 1085.05483334174 499.600985601034 -0.10740780530811946`

For running the point_triangulator, the input path is the folder containing only the 3 text files I've mentioned above and output_path is a blank folder to save the output. 

I tried running the same images in colmap gui without pose priors and was able to get a sparse model. Then I saved the sparse model as text files. I then tried copying over this images.txt file generated from colmap gui to the above mentioned to the model replacing my pose priors images.txt file. Then I was able to run the points_triangulator and got this result:

```
==============================================================================
Loading database
==============================================================================

Loading cameras... 1 in 0.000s
Loading matches... 76327 in 1.703s
Loading images... 393 in 0.223s (connected 393)
Building correspondence graph... in 1.772s (ignored 0)

Elapsed time: 0.063 [minutes]

F0914 12:00:46.313719 18684 reconstruction.cc:83] Check failed: image.second.NumPoints2D() == existing_image.NumPoints2D() (1041 vs. 1039)
*** Check failure stack trace: ***
    @   00007FFAC0D45FFB  public: void __cdecl google::LogMessage::Flush(void) __ptr64
    @   00007FFAC0D44B49  public: __cdecl google::LogMessageFatal::~LogMessageFatal(void) __ptr64
    @   00007FF6FE9A121F  (unknown)
    @   00007FF6FE9C0BAE  (unknown)
    @   00007FF6FE8ECB25  (unknown)
    @   00007FF6FE8EC78C  (unknown)
    @   00007FF6FE8A4B16  (unknown)
    @   00007FF6FE8A631B  (unknown)
    @   00007FF6FEE4F674  (unknown)
    @   00007FFAD7037034  BaseThreadInitThunk
    @   00007FFAD7202651  RtlUserThreadStart
```

So I think I'm having some issue with the images.txt file I've created. But it is of the same format as mentioned in the documentation. 
Please help me figure out what I'm doing wrong here.

@tsattler please help if you could.

**Comment by tsattler** [comment]
It looks like your image ids in the reconstruction files might not be consistent with those in the database. Try running the `point_triangulator` with the option `--clear_points 1` to force Colmap to use the image ids from the database.

**Comment by Kirang96** [comment]
@tsattler thanks for the reply.
I reduced to my dataset to 10 images. The image ids in the reconstruction files and database seems to be consistent. I've tried using `--clear_points 1` on `point_triangulator` as well. But it no changes.

This is the images.txt file that I'm using right now:
```
1  0.39964881 -0.24483059 -0.03971661  0.88247459 0.236693 -0.969321 -0.473446 1 000000.png

2  0.39846929 -0.25009968 -0.0398796   0.88152254 0.237343 -0.969224 -0.476806 1 000001.png

3  0.39836556 -0.26294141 -0.03936728  0.87784789 0.235755 -0.969554 -0.488945 1 000002.png

4  0.39654579 -0.27767237 -0.03919752  0.8741356  0.235549 -0.969633 -0.489875 1 000003.png

5  0.39201589 -0.29918597 -0.03766597  0.86913323 0.235410 -0.969282 -0.488228 1 000004.png

6  0.38910202 -0.31849154 -0.03574427  0.8636464  0.232340 -0.969656 -0.476036 1 000005.png

7  0.8680677   0.05990347 -0.30527831  0.38687878 0.237221 -0.967517 -0.487741 1 000006.png

8  0.86398276  0.06178434 -0.31958403  0.38416472 0.239449 -0.965914 -0.451121 1 000007.png

9  0.85565899  0.06283417 -0.34207566  0.38325424 0.237535 -0.965403 -0.385355 1 000008.png

10  0.84624885  0.06439361 -0.36870369  0.37917535 0.236402 -0.963855 -0.309134 1 000009.png
```

And the database images table looks like this:

![image](https://user-images.githubusercontent.com/29313141/190131461-456a68ba-99b1-4250-b3b5-24ca03bdedf1.png)

**Comment by ahojnnes** [comment]
Did you run feature extraction and matching before triangulation?

**Comment by Kirang96** [comment]
Hi @ahojnnes , Yes, I ran both feature_extraction and exhaustive_mapper before triangulation.

**Comment by ahojnnes** [comment]
When you compare the camera model parameters estimated by colmap and your prior parameters, do they match?

**Comment by ahojnnes** [comment]
Sorry, seems like I got confused with your initial problem description and my questions won't really help with debugging. Didn't see that you got a crash. Sorry, looking at this from my phone.

**Comment by Kirang96** [comment]
prior camera data and the one estimated by colmap are similar yet not the same. But I also tried replacing the prior camera file with the one estimated by colmap and it gave the same error.

**Comment by Kirang96** [comment]
@ahojnnes @tsattler I was able to fix the issue. It was because I had double spaces instead of single space in the images.txt file I created. 
Still the reconstructed sparse model points are all distorted and at random positions, but I guess it's because of the improper formatting of the images.txt file. Thanks for helping out.
