### ISSUE TITLE
How to use colmap Gui to reconstruct sparse/dense model from known camera poses

### ISSUE THREAD

**Issue by BoMingZhao** [colmap/colmap#1638]
Hi, I read the documentation [Reconstruct sparse/dense model from known camera poses](https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses) and I am confused how to add input path in Gui as below.
`colmap point_triangulator \
    --database_path $PROJECT_PATH/database.db \
    --image_path $PROJECT_PATH/images
    --input_path path/to/manually/created/sparse/model \
    --output_path path/to/triangulated/sparse/model`

**Comment by tsattler** [comment]
It is currently not possible to reconstruct the scene from known poses within the gui. You will need to do this from the command line.

**Comment by BoMingZhao** [comment]
Thanks for your reply
