### ISSUE TITLE
Scale ambiguity in SfM with calibrated camera

### ISSUE THREAD

**Issue by lucaBartolomei** [colmap/colmap#1653]
Hi, 

Thanks a lot for this amazing project!

I would have a general question about scale ambiguity in SfM with a single camera, and how to deal with it when using Colmap.
When running SfM using images from an uncalibrated camera, the camera poses and the 3D reconstruction suffer from scale ambiguity, i.e. we cannot recover the actual "ground-truth" scale of the scene.

What would the expected outcome be from a scale perspective, when running SfM with a **calibrated** camera? In this case, I would expect that the real scale could be recovered (up to noise and detection errors), since the focal lengths of the camera (as well as principal point and other distortion parameters) are known. 

However, when running the standard Colmap pipeline with _fixed camera intrinsics_ (feature extraction - feature matching - mapper) with an additional final bundle adjustment step, the scale of the camera poses are off when compared to ground-truth poses. Is this outcome expected and my reasoning wrong, or am I using Colmap wrongly?

Thank you in advance for you help!

**Comment by tsattler** [comment]
Even if the camera is calibrated, you cannot recover the scale of the scene. The reason is that due to the dehomogenization during the projection, scaling the scene by any non-0 factor will have no impact on the projections.

**Comment by lucaBartolomei** [comment]
Thanks for your answer @tsattler , it makes sense now.

As far as I understood, the same should also happen even if I use multiple calibrated cameras. The scale should then be enforced as a post-processing step on the initial reconstruction and camera poses using the rig_bundle_adjuster. Is this reasoning correct?

**Comment by tsattler** [comment]
If you have a multi-camera rig and you know the distances between the cameras in meters / centimeters / ..., then scale becomes observable. Colmap does not support directly using a rig, you will first have to reconstruct the scene using individual images and then use the rig_bundle_adjuster to enforce the rig constraints.

**Comment by lucaBartolomei** [comment]
Perfect, thanks for the clarifications.
