### ISSUE TITLE
 Check failed: bundle_adjuster.Solve(&reconstruction) during point triangulation step of reconstruction with known camera poses

### ISSUE THREAD

**Issue by Kirang96** [colmap/colmap#1657]
I'm trying to do reconstruction with known camera poses. The model files, images, camera and points3D are created as per the documentation. All the images are in png format. 
I can run the feature extraction and exhaustive matching processes without any errors. But when I run point triangulator it gives me this:
```

==============================================================================
Loading database
==============================================================================

Loading cameras... 1 in 0.000s
Loading matches... 45 in 0.002s
Loading images... 10 in 0.003s (connected 10)
Building correspondence graph... in 0.010s (ignored 0)

Elapsed time: 0.000 [minutes]

==============================================================================
Triangulating image #1 (0)
==============================================================================

  => Image sees 0 / 3145 points
  => Triangulated 0 points

==============================================================================
Bundle adjustment
==============================================================================

F1013 12:15:52.150756  6340 sfm.cc:473] Check failed: bundle_adjuster.Solve(&reconstruction)
*** Check failure stack trace: ***
    @   00007FF84F585FFB  public: void __cdecl google::LogMessage::Flush(void) __ptr64
    @   00007FF84F584B49  public: __cdecl google::LogMessageFatal::~LogMessageFatal(void) __ptr64
    @   00007FF6F84ED257  (unknown)
    @   00007FF6F84EC78C  (unknown)
    @   00007FF6F84A4B16  (unknown)
    @   00007FF6F84A631B  (unknown)
    @   00007FF6F8A4F674  (unknown)
    @   00007FF857A67034  BaseThreadInitThunk
    @   00007FF8598E26A1  RtlUserThreadStart
(base) PS C:\COLMAP\COLMAP-3.7-windows-no-cuda\COLMAP-3.7-windows-no-cuda>
```

This is what my images.txt looks like:
```
1 -0.12084346260043173 0.9909516815889837 -0.05172321662292644 0.027135422695830975 1.489779 3.369063 0.436111 1 000000.png

2 -0.12114956441959392 0.9909273880711714 -0.051720465068596094 0.026658734112425496 1.521964 3.376873 0.437624 1 000001.png
```
and this is the camera.txt looks like:

`1 SIMPLE_RADIAL 1920 1080 1383.5543 1383.4469 960.61115 538.9626`

Points3D.txt file is left blank.

Camera ID is same (1) for all the images.
Image names in the images.txt file and the images in the folder matches.

Please help.
@tsattler please take a look if you could

**Comment by Kirang96** [comment]
I've used about 400 images. I just copied over log of just one image. Sorry about that.
This is what I tried just now:
Created a sparse reconstruction in the GUI using the same images. Then saved the model as text file.
Copied over just the pose from that images.txt file to a new images.txt file. And also used the cameras.txt file data to do a reconstruction using those as priors. I did this thinking that the priors I was giving was not proper. 
I still got the same error with this as well.

This is the images.txt file that I just used:
```
1 0.99981197094549945 0.00089435086537275655 -0.019227238274626288 -0.0023529128619897213 4.0156863690036326 -3.0422536458135903 3.8513444317292542 1 000001.png

2 0.99981838570273363 0.00068686063064575542 -0.018796339451043378 -0.0030694391173412498 4.0104944776946141 -3.0524825293771087 3.8506589724015625 2 000002.png
```

This is the cameras.txt file:
```
# Camera list with one line of data per camera:
#   CAMERA_ID, MODEL, WIDTH, HEIGHT, PARAMS[]
# Number of cameras: 398
1 SIMPLE_RADIAL 2308 1036 1672.4968976532632 1154 518 0.011674400120946738

```

I got this from the colmap generated file. Still got the same error.

**Comment by Kirang96** [comment]
Also when I tried to open a point in GUI, I'm not able to see any. It says error -1

![image](https://user-images.githubusercontent.com/29313141/195569295-08c4efc1-0f2d-468b-8d4e-bd5f3f62b514.png)

**Comment by tsattler** [comment]
Are you using the correct database? Based on your original output, there seem to be only 10 images in the database.

**Comment by Kirang96** [comment]
@tsattler, I figured out that the cameras.txt file was the one causing the issue.
From the documentation I read the format of the cameras file as this:
`3 SIMPLE_RADIAL 3072 2304 2559.69 1536 1152 -0.0218531`

Here it is of format:
[ CAMERA_ID, MODEL, WIDTH, HEIGHT, PARAMS[] ]

Could you tell me what the parameters are in here?

**Comment by tsattler** [comment]
You can find information about available camera models and their parameters here: https://colmap.github.io/cameras.html and here: https://github.com/colmap/colmap/blob/master/src/base/camera_models.h

**Comment by Kirang96** [comment]
Thanks @tsattler, forgot to check the code. I'll use the pinhole model as I have two focal lengths and the principal axis.
I'm also facing another issue as well. The pose data that I have is in OpenGL format as I got it from Arcore, and colmap requires it in OpenCV format. Is there any chance you know how to make that conversion?

**Comment by tsattler** [comment]
I think there should be a few issues in this repository explaining how to convert the poses.

**Comment by Kirang96** [comment]
Hi @tsattler, I looked at several issues regarding pose conversion, but none of them mentions an openGL pose.
I've got Arcore poses in OpenGL format (x-right, y-up, z-outward). These are the steps that I did to try and convert it to OpenCV format:

1. Arcore outputs poses in quaternions (x,y,z,w) and translation vector. So I converted the quaternions to (w,x,y,z) and then to rotation matrices.
2. Transposed the rotation matrix as OpenGL poses are row major and OpenCV's are in column major format.
3. Created a homogeneous transformation matrix by concatenating the translation vector to it and adding 0's to create a [4x4] matrix.
4. Since colmap requires world2Camera coordinates, I inverted the transformation matrix. 
5. Then I inverted the signs of the 2nd and 3rd row of the transformation matrix as these rows are the y and z axis of the rotation (OpenCV and OpenGL coordinate system difference).
6. Convert this transformation matrix back to the quaternion (w,x,y,z) and translation vector.

Even after doing this the camera locations in the colmap are not correct and it does not reconstruct many points.

**Comment by rakshith95** [comment]
@Kirang96 were you able to solve this? If so, how did you get it to work?

**Comment by Kirang96** [comment]
> @Kirang96 were you able to solve this? If so, how did you get it to work?

Hi @rakshith95, the error mentioned in the title of the issue was due to improper formatting of the cameras.txt file. The camera parameters I had mentioned were wrong. Also, I had a few extra spaces in the images.txt file as well. Fixing these helped me get rid of the error.
But for the camera coordinates, I wasn't able to make the conversion properly to OpenCV format. But instead of doing it, I did the reconstruction without the priors and then did geo_registration with model_aligner to scale the model to real world coordinates. For doing the geo_registration, you can refer to [this](https://colmap.github.io/faq.html#geo-registration) part in the documentation. You can use the translations that you have here. It does not require any conversion and the resulting model will be scaled.

**Comment by rakshith95** [comment]
I was interested in the first part, i.e. wrt the error mentioned in the title. Thanks for letting me know where you errors were; I probably made similar mistakes in mine as well and will take a look now.

**Comment by rakshith95** [comment]
Btw @Kirang96 I noticed in your earlier comment you mention 

> Created a homogeneous transformation matrix by concatenating the translation vector to it and adding 0's to create a [4x4] matrix.

Not sure if this is what you meant, but the homogeneous transformation matrix is of the form `[R | t;0 0 0 1]`,  not all 0s

**Comment by HarshaMupparaju** [comment]
@rakshith95 @Kirang96 @tsattler , I have the same issue as mentioned in the title, 
`==============================================================================
Feature extraction
==============================================================================

Processed file [1/3]
  Name:            0001.jpg
  Dimensions:      2704 x 2028
  Camera:          #1 - SIMPLE_RADIAL
  Focal Length:    3244.80px
  Features:        1836
Processed file [2/3]
  Name:            0002.jpg
  Dimensions:      2704 x 2028
  Camera:          #1 - SIMPLE_RADIAL
  Focal Length:    3244.80px
  Features:        1877
Processed file [3/3]
  Name:            0003.jpg
  Dimensions:      2704 x 2028
  Camera:          #1 - SIMPLE_RADIAL
  Focal Length:    3244.80px
  Features:        2923
Elapsed time: 0.004 [minutes]
colmap exhaustive_matcher --database_path ../../../tmp/database.db

==============================================================================
Exhaustive feature matching
==============================================================================

Matching block [1/1, 1/1] in 0.077s
Elapsed time: 0.002 [minutes]
colmap point_triangulator --database_path ../../../tmp/database.db --image_path ../../../tmp/images --input_path ../../../tmp/sparse/0 --output_path ../../../tmp/sparse/0 --Mapper.tri_ignore_two_view_tracks 0 --Mapper.num_threads 16 --Mapper.init_min_tri_angle 4 --Mapper.multiple_models 0 --Mapper.extract_colors 0

==============================================================================
Loading model
==============================================================================


==============================================================================
Loading database
==============================================================================

Loading cameras... 1 in 0.000s
Loading matches... 2 in 0.000s
Loading images... 3 in 0.000s (connected 3)
Building correspondence graph... in 0.000s (ignored 0)

Elapsed time: 0.000 [minutes]


==============================================================================
Triangulating image #0 (0)
==============================================================================

  => Image sees 0 / 0 points
  => Triangulated 0 points

==============================================================================
Triangulating image #1 (1)
==============================================================================

  => Image sees 0 / 48 points
  => Triangulated 0 points

==============================================================================
Triangulating image #2 (2)
==============================================================================

  => Image sees 0 / 108 points
  => Triangulated 0 points

==============================================================================
Retriangulation
==============================================================================

  => Completed observations: 0
  => Merged observations: 0

==============================================================================
Bundle adjustment
==============================================================================

F0810 15:57:35.477456 2272894 sfm.cc:473] Check failed: bundle_adjuster.Solve(&reconstruction) 
*** Check failure stack trace: ***
    @     0x7f1b276d7b03  google::LogMessage::Fail()
    @     0x7f1b276df9d1  google::LogMessage::SendToLog()
    @     0x7f1b276d77c2  google::LogMessage::Flush()
    @     0x7f1b276d978f  google::LogMessageFatal::~LogMessageFatal()
    @     0x55ddebc1f0b0  colmap::RunPointTriangulatorImpl()
    @     0x55ddebc14acc  colmap::RunPointTriangulator()
    @     0x55ddebbdb499  main
    @     0x7f1b25429d90  (unknown)
    @     0x7f1b25429e40  __libc_start_main
    @     0x55ddebbde3e5  _start
Aborted (core dumped)`

This is the contents of cameras.txt file 
`1 FULL_OPENCV 2704 2028 731.3691627864987 731.3691627864987 676.0 507.0 0 0 0 0 0 0 0 0 `

and this is what's there in images.txt file
`0 -0.04589858745133139 0.9573113835789684 0.028740899845485723 0.2839404782981205 -5.068010824121289 -1.3012192130074425 -2.1138844709373803 1 0000.jpg

1 -0.050892069433813296 0.9615592318019909 -0.012773632782978593 -0.2695378921610741 3.4895918839319537 -1.354012583370535 -1.2195196405459783 1 0001.jpg

2 -0.021734547771511594 0.9985325003016441 0.0017843407944345157 -0.04957087252050525 0.19529270686515762 1.4237902150744526 -0.4349119352814836 1 0002.jpg`

and the points3D.txt is empty as mentioned in the documentation. 

Theses are the contents of database.db file, I don't understand why the sparse reconstruction doesn't work even though there are matches present in the database.db file as shown below.

![Screenshot from 2023-08-10 16-19-12](https://github.com/colmap/colmap/assets/58979824/e20beba6-43c8-4745-9316-e9656fb1eab3)

![Screenshot from 2023-08-10 16-20-57](https://github.com/colmap/colmap/assets/58979824/cff82edb-2aec-45ba-ac65-74a1450a9c25)

![Screenshot from 2023-08-10 16-20-00](https://github.com/colmap/colmap/assets/58979824/29d010fa-a65d-4fe4-be5c-0e1f7cf29acd)

Any help to get past this error?

**Comment by tsattler** [comment]
Have you looked at the matches to see whether they look meaningful?
Are your camera extrinsics and intrinsics accurate?

**Comment by lsrrrrrrrrr** [comment]
remove colmap use, colmap is not necessary
