### ISSUE TITLE
Entire system locks up during installation (Debian 9)

### ISSUE THREAD

**Issue by jameshazen91** [colmap/colmap#166]
I apologize if this is the wrong place to ask about this, I couldn't really find any other contact information for colmap.  I'm also fairly new to GNU/Linux so I apologize if the way I ask about this is "wrong" or something.

This is happening on a totally fresh installation of Debian.  The only changes I've made since installing the OS is installing and configuring the latest nvidia drivers and nvidia CUDA.

I've been following the procedure outlined here:
https://colmap.github.io/install.html#linux

Everything was going smoothly until I got to the section "Configure and compile COLMAP".  When I enter "make -j", the terminal does a little work, then starts spitting out a few errors that seem related to CUDA.  After about 5-10 seconds, my entire computer locks up and is unresponsive.  Keyboard commands do not work, the cursor does not respond.  Even the power button on the case does not seem to work, I had to physically pull the plug out of the wall to get my computer to restart.

I have no idea what is happening or how to go about troubleshooting it.  I wasn't able to copy or screen capture any of the errors it was spitting at me as the system was locked up, but I did take a shot with my phone.  This is what the terminal was giving me at the time my computer locked up.

![1498845184917](https://user-images.githubusercontent.com/29803181/27748702-373811cc-5d85-11e7-8ff7-a4611db4076c.jpg)

Again I apologize if I've gone about this the wrong way.  This is all fairly new to me.

**Comment by ahojnnes** [comment]
The "-j" option uses multiple processes to compile the code. Maybe this causes your system to run out of memory. Try to run "make" without the "-j" option and let me know if this solves your problem.

**Comment by jameshazen91** [comment]
Seems to have worked!  Also it appears the CUDA errors were from myself improperly installing CUDA.  I had used the instructions on the Debian wiki instead of the nvidia website.  I made a fresh Ubuntu 16.04 LTS install (Debian was giving me unrelated problems and I just wanted to stick with something I knew), then installed nvidia drives and CUDA according to the nvidia website, then followed all of the instructions on how to install colmap except for just using "make" instead of "make -j".

So yeah, the issue seems to be 100% an inexperienced Linux user.  Nothing wrong with the software.  THANK YOU!

**Comment by ahojnnes** [comment]
Glad to hear, perfect!

**Comment by ahojnnes** [comment]
The binaries are in the build folder. Assuming you cd'd to the build directory, you can run "./src/exe/colmap" to run the GUI version. The command line version are in the same folder.

**Comment by jameshazen91** [comment]
Yeah sorry I just read that on the website.  Must have missed it earlier.  Thank you so much!
