### ISSUE TITLE
Spherical Poses Visualization Issues in COLMAP

### ISSUE THREAD

**Issue by ahmad-bashir9** [colmap/colmap#1664]
Hello, 

I am working on generating 360 degrees camera poses from a single reference pose. I have generated the poses using the following script.

```
trans_t = lambda t : tf.convert_to_tensor([
    [1,0,0,0],
    [0,1,0,0],
    [0,0,1,t],
    [0,0,0,1],
], dtype=tf.float32)

rot_phi = lambda phi : tf.convert_to_tensor([
    [1,0,0,0],
    [0,tf.cos(phi),-tf.sin(phi),0],
    [0,tf.sin(phi), tf.cos(phi),0],
    [0,0,0,1],
], dtype=tf.float32)

rot_theta = lambda th : tf.convert_to_tensor([
    [tf.cos(th),0,-tf.sin(th),0],
    [0,1,0,0],
    [tf.sin(th),0, tf.cos(th),0],
    [0,0,0,1],
], dtype=tf.float32)

def pose_spherical(theta, phi):
    c2w = trans_t(290.)
    c2w = np.matmul(rot_phi(phi/180.*np.pi) ,c2w)
    c2w = np.matmul(rot_theta(theta/180.*np.pi) ,c2w)
    c2w = np.matmul(np.array([[-1,0,0,0],[0,0,1,0],[0,1,0,0],[0,0,0,1]]),c2w)
    return c2w

def get_poses(th):
    poses=np.zeros((24,4,4))
    y=0
    for th in tqdm(np.linspace(0., 360., 24, endpoint=False)):
      c2w = pose_spherical(th, -23.3160)
      poses[y]=c2w
      y=y+1
    return poses
```

When I visualize these poses using open3d, the output looks like this,

![open3d poses](https://user-images.githubusercontent.com/110457033/196619167-08f45934-2dda-4d39-9ef9-7168774e74a2.png)

But when I visualize the same poses in COLMAP it gives a strange output that looks like this 

![colmap1](https://user-images.githubusercontent.com/110457033/196619505-bcd58b8e-6168-4cb3-81f7-b07f30eeb785.png)

I am taking care of wxyz and xyzw format of quaternion during the colmap format conversion. 

Can you please help me sort out this problem?

**Comment by tsattler** [comment]
Looks to me like you would get a very similar visualization if you scale down the size of the camera frustra in the viewer.

**Comment by tsattler** [comment]
Colmap defines poses as a transformation from world to camera coordinates. Is `c2w` camera-to-world or world-to-camera, i.e., do you read it from left to right or right to left?

**Comment by ahmad-bashir9** [comment]
I got the point. Thank you, I resolved the issue by transforming the camera poses to the world to camera coordinates.

**Comment by hardikdava** [comment]
@ahmad-bashir9 were able to get the camera poses around the object? I am struggling with the same idea.
