### ISSUE TITLE
Does colmap support refining camera poses from coarse initialization in command line?

### ISSUE THREAD

**Issue by f1shel** [colmap/colmap#1665]
colmap has already provided a way to reconstruct sparse model from known camera poses (from [FAQ](https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses)). My question is, will this process refine the camera poses that I provide in `manually/images.txt`?

Sorry for this question here. The 3d reconstruction pipeline of colmap is quite long and I am a little confused about what happends in point_triangulator. Do I need to run `colmap bundle_adjuster` after I run `colmap point_triangulator`,  if I want to refine coarse camera poses?

Thanks in advance!

**Comment by tsattler** [comment]
The point_triangulator does not refine the camera parameters. For this, you will need to run the bundle_adjuster.

There is also a thread somewhere among the issues that discusses how to do the refinement.
