### ISSUE TITLE
Does using single camera make the reconstruction even slower?

### ISSUE THREAD

**Issue by is03wlei** [colmap/colmap#167]
When I set ImageReader.single_camera to 1, the mapper process becomes much slower than before.
Does it make sense?

**Comment by ahojnnes** [comment]
Yes, since this will change from PBA bundle adjustment to Ceres Solver. You can alway make the reconstruction faster by reducing the number of bundle adjustment iterations, iterative refinements and the frequency at which global bundle adjustments are performed. Please have a look at the documentation and all the available options.

**Comment by is03wlei** [comment]
Can I reconstruct without sharing intrinsic parameters first then run bundle_adjuster with single camera?
Actually I'm doing it right now. Hope it produces good result.

**Comment by ahojnnes** [comment]
Yes, you can but you would have to manually edit the images.txt and cameras.txt files before running the bundle adjuster.

**Comment by is03wlei** [comment]
Yes, I did so.
==============================================================================
Global bundle adjustment
==============================================================================

iter      cost      cost_change  |gradient|   |step|    tr_ratio  tr_radius  ls_iter  iter_time  total_time
   0  7.972835e+12    0.00e+00    3.80e+13   0.00e+00   0.00e+00  1.00e+04        0    6.91e+01    6.74e+02
   1  4.612412e+33   -4.61e+33    0.00e+00   5.72e+06  -5.79e+20  5.00e+03        7    2.89e+02    9.64e+02
   2  1.801791e+31   -1.80e+31    0.00e+00   4.87e+06  -2.26e+18  1.25e+03        8    2.34e+02    1.20e+03
   3  1.465008e+33   -1.47e+33    0.00e+00   1.59e+06  -1.84e+20  1.56e+02       26    4.46e+02    1.64e+03
   4  8.250420e+42   -8.25e+42    0.00e+00   2.67e+05  -1.04e+30  9.77e+00       18    3.44e+02    1.99e+03
   5  3.229731e+33   -3.23e+33    0.00e+00   1.19e+04  -4.06e+20  3.05e-01        5    1.99e+02    2.19e+03
   6  1.288071e+16   -1.29e+16    0.00e+00   1.09e+03  -2.02e+03  4.77e-03        2    1.61e+02    2.35e+03
   7  7.611012e+12    3.62e+11    3.56e+13   2.99e+01   9.86e-01  1.43e-02        2    1.98e+02    2.54e+03
   8  6.680448e+12    9.31e+11    2.96e+13   8.59e+01   9.63e-01  4.29e-02        2    1.93e+02    2.74e+03
   9  4.793232e+12    1.89e+12    1.88e+13   2.31e+02   9.23e-01  1.09e-01        2    1.94e+02    2.93e+03
  10  1.719806e+20   -1.72e+20    0.00e+00   4.70e+02  -6.79e+07  5.45e-02        2    1.60e+02    3.09e+03
  11  3.251827e+12    1.54e+12    1.11e+13   2.64e+02   9.22e-01  1.37e-01        2    1.87e+02    3.28e+03
  12  1.608152e+12    1.64e+12    3.11e+13   5.15e+02   8.89e-01  2.58e-01        2    1.94e+02    3.47e+03
  13  1.065713e+14   -1.05e+14    0.00e+00   7.24e+02  -9.90e+01  1.29e-01        2    1.68e+02    3.64e+03
  14  1.624666e+12   -1.65e+10    0.00e+00   4.29e+02  -2.15e-02  3.23e-02        2    1.65e+02    3.80e+03
  15  1.328175e+12    2.80e+11    2.07e+13   1.26e+02   9.72e-01  9.68e-02        2    1.93e+02    4.00e+03
  16  8.366044e+11    4.92e+11    8.91e+12   3.21e+02   9.48e-01  2.90e-01        2    2.02e+02    4.20e+03
  17  2.446554e+15   -2.45e+15    0.00e+00   6.58e+02  -4.56e+03  1.45e-01        2    1.59e+02    4.36e+03
  18  4.705544e+11    3.66e+11    3.43e+12   3.91e+02   9.49e-01  4.36e-01        2    2.18e+02    4.58e+03
  19  2.673735e+11    2.03e+11    2.52e+14   7.17e+02   6.26e-01  4.43e-01        2    1.95e+02    4.77e+03
  20  9.249646e+10    1.75e+11    4.74e+13   4.91e+02   8.95e-01  8.76e-01        2    1.97e+02    4.97e+03
  21  3.724912e+24   -3.72e+24    0.00e+00   6.52e+02  -6.02e+13  4.38e-01        2    1.60e+02    5.13e+03
  22  2.043369e+13   -2.03e+13    0.00e+00   3.81e+02  -3.92e+02  1.09e-01        2    1.68e+02    5.30e+03
  23  6.584034e+10    2.67e+10    1.71e+13   1.14e+02   9.13e-01  2.50e-01        2    1.97e+02    5.49e+03
  24  4.326379e+10    2.26e+10    4.23e+12   2.20e+02   9.44e-01  7.51e-01        2    2.02e+02    5.70e+03
  25  2.584878e+10    1.74e+10    7.66e+11   5.14e+02   9.58e-01  2.25e+00        2    2.00e+02    5.90e+03
  26  1.582163e+10    1.00e+10    1.33e+11   1.00e+03   9.55e-01  6.76e+00        3    2.05e+02    6.10e+03
  27  7.220888e+12   -7.21e+12    0.00e+00   1.28e+03  -1.03e+03  3.38e+00        4    1.80e+02    6.28e+03
  28  1.143823e+10    4.38e+09    9.23e+10   8.54e+02   8.82e-01  6.11e+00        3    1.98e+02    6.48e+03
  29  7.107539e+12   -7.10e+12    0.00e+00   9.07e+02  -1.80e+03  3.06e+00        4    1.74e+02    6.65e+03
  30  9.012631e+09    2.43e+09    1.01e+11   5.65e+02   9.01e-01  6.30e+00        3    2.03e+02    6.86e+03
  31  9.971552e+09   -9.59e+08    0.00e+00   9.95e+02  -3.70e-01  3.15e+00        5    1.94e+02    7.05e+03
  32  1.114582e+10   -2.13e+09    0.00e+00   5.38e+02  -1.25e+00  7.87e-01        4    1.78e+02    7.23e+03
  33  8.446643e+09    5.66e+08    5.34e+10   2.26e+02   8.62e-01  1.27e+00        2    1.95e+02    7.42e+03
  34  7.729690e+09    7.17e+08    4.62e+10   2.98e+02   9.60e-01  3.81e+00        2    1.94e+02    7.62e+03
  35  8.613713e+09   -8.84e+08    0.00e+00   6.16e+02  -6.78e-01  1.91e+00        4    1.80e+02    7.80e+03
  36  7.052008e+09    6.78e+08    3.97e+10   3.48e+02   8.92e-01  3.68e+00        3    1.99e+02    7.99e+03
  37  5.994333e+09    1.06e+09    4.69e+10   4.18e+02   9.67e-01  1.10e+01        3    2.08e+02    8.20e+03
  38  4.429182e+09    1.57e+09    3.21e+11   1.93e+03   9.79e-01  3.31e+01        6    2.48e+02    8.45e+03
  39  2.803015e+09    1.63e+09    3.16e+11   2.87e+03   9.64e-01  9.93e+01        9    2.68e+02    8.72e+03
  40  1.736761e+09    1.07e+09    2.60e+11   1.40e+04   8.61e-01  1.59e+02       14    3.24e+02    9.04e+03
  41  1.117490e+09    6.19e+08    6.09e+12   1.83e+04   9.20e-01  3.89e+02       16    3.43e+02    9.39e+03
  42  7.839150e+08    3.34e+08    1.27e+12   5.45e+04   8.37e-01  5.60e+02       24    4.30e+02    9.82e+03
  43  6.064215e+08    1.77e+08    2.26e+11   1.05e+05   7.96e-01  7.07e+02       24    4.26e+02    1.02e+04
  44  6.319122e+08   -2.55e+07    0.00e+00   1.21e+05  -3.15e-01  3.54e+02        2    1.59e+02    1.04e+04

**Comment by ahojnnes** [comment]
Okay, I assume that means it worked. Let me know for you have other questions.

**Comment by is03wlei** [comment]
Is it possible to specify a narrow range of focal length in order to use PBA?

**Comment by ahojnnes** [comment]
What do you mean by a narrow range? A prior that you have about the focal length?

**Comment by is03wlei** [comment]
Yes. Like [minimum_focal_length, maximum_focal_length]

**Comment by ahojnnes** [comment]
If you do not deactive the refine_focal_length option, then the focal length prior is not strict anyway and will be refined during the reconstruction. So if you have a min-max range, then e.g. Simply set it to the average of those two values?

**Comment by is03wlei** [comment]
Yes. That's what I mean.

**Comment by is03wlei** [comment]
Could you please upgrade PBA to version 1.05 to support single camera?

https://grail.cs.washington.edu/projects/mcba/History.txt
1.0.5
Fixed a bug (rarely happens) in CUDA kernel configuration
	* Symptom: ComputeJtE<Point>: invalid configuration argument(9)
	  Triggers when npoint is within (2 * n * 65505 ~ 2 * n * 65535) for n >= 2
Changed the CUDA error handling
	* from exit(0) to throw "error location string"
Added Support for constraints of camera clusters having equal focal lengths
	* Call ParallelBA::SetFocalMask(reference_camera_index_for_each_camera, weight);
	* For example, a vector of 0 means all camera should have the same focal length.
	* For example, <0,0,2,2,2> gives two groups (0,1) and (2, 3,4) for the constraint.
Improved memory allocation
	* Reset device and deallocate all data when ReserveStorage(0, 0, 0);

**Comment by is03wlei** [comment]
I noticed the version of PBA used in COLMAP is already 1.0.5, but the code is still different from official code. It seems PBA can support single camera mode by calling ParallelBA::SetFocalMask.

**Comment by ahojnnes** [comment]
This only works if the radial distortion is set to constant. As in COLMAP radial distortion parameters are also shared across cameras.

**Comment by is03wlei** [comment]
I didn't know exactly why COLMAP doesn't use PBA under single camera mode. I'm not sure what is going to happen when share focal length only across cameras.

**Comment by RoboRoboRoboRobo** [comment]
@is03wlei @ahojnnes 
so is there any way to use pba with single camera?
