### ISSUE TITLE
Pausing Feature Matching

### ISSUE THREAD

**Issue by ardaxz99** [colmap/colmap#1676]
Hi, I am trying to do feature matching with 16k images, which takes too long(about four days with exhaustive_matcher). Can I stop the matching at some point, then load the matches and unpause the process? İf yes, could you explain to me how to do it?

**Comment by ahojnnes** [comment]
You can just cancel the processing and the next time you start (by using the same database file again), the matching will skip any previously computed results.

**Comment by ardaxz99** [comment]
> You can just cancel the processing and the next time you start (by using the same database file again), the matching will skip any previously computed results.

Thank you very much!
