### ISSUE TITLE
Can you provide codes used in VS2013?

### ISSUE THREAD

**Issue by 5kyfly** [colmap/colmap#168]
I'm a beginner.I am very interested in your work. But I fail to  build the library manually as described in the documentation.  I hope you can provide codes generated by CMake which can be used in VS2013. Thank you.

**Comment by ahojnnes** [comment]
This is unfortunately not possible. However, I recommend setting up a Linux machine if you cannot manage to build the library under Windows. It is much easier there. Thanks, Johannes
