### ISSUE TITLE
The difference between `refine_extra_params` and `refine_extrinsics`

### ISSUE THREAD

**Issue by MaxChanger** [colmap/colmap#1680]
Hi, I found that there are two similar parameters in the parameter list of `colmap bundle_adjuster`. 
I want to confirm if `refine_extrinsics` is the flag to control and optimize the camera poses?

In addition, I would like to ask, what parameters are refine_extra_params mainly used to control? I can't seem to find any relevant information.

https://github.com/colmap/colmap/blob/9be18603720ba71d91b79abcdb6b409f3a6243be/src/optim/bundle_adjustment.h#L63-L67

In addition, I selected some kitti sequences of 30~70 frames, set the trajectory poses as the initial value to the colmap, and performed `feature_extractor`, `exhaustive_matcher` , `point_triangulator`, `bundle_adjuster`.

I found that if I use the following command.
After BA, there is a certain probability that the camera pose will drift a lot. 
I have encountered two situations, one is the scale of camera pose translation has changed a lot, such as jumping from 50 to ~40000, so when visualizing, only the point cloud can be seen, but there is no camera. The other is that I can only see a lot of overlapping cameras, but there is no point. If I don't run BA with the parameters below, everything looks fine. 

```shell
colmap point_triangulator \
    --database_path $DATASET_PATH/database.db \
    --image_path $DATASET_PATH/images \
    --input_path $DATASET_PATH/pose_init/model \
    --output_path $DATASET_PATH/sparse/0 \
    --Mapper.ba_refine_focal_length 0 \
    --Mapper.ba_refine_principal_point 0 \
    --Mapper.ba_refine_extra_params 0

colmap bundle_adjuster \
    --input_path $DATASET_PATH/sparse/0 \
    --output_path $DATASET_PATH/sparse/0 \
    --BundleAdjustment.max_num_iterations 300 \
    --BundleAdjustment.max_linear_solver_iterations 600 \
    --BundleAdjustment.refine_focal_length 0 \
    --BundleAdjustment.refine_principal_point 0 \
    --BundleAdjustment.refine_extra_params 0 \
    --BundleAdjustment.refine_extrinsics 1
```

**Comment by ahojnnes** [comment]
Yes, `refine_extrinsics` allows you to set camera poses as fixed/variable during the optimization.

**Comment by ahojnnes** [comment]
extra_params are all intrinsic camera parameters other than focal length and principal point. For example, for the OpenCV camera models, these would be any radial/tangential distortion parameters.

**Comment by MaxChanger** [comment]
Thanks for your reply, so further, if I use `Pinhole` or `Simple_Pinhole`, there is no distortion parameter in the camera model, so only `refine_focal_length` and `refine_principal_point` are needed and useful, `refine_extra_params` doesn't work or doesn't need for these camera models  because there is no corresponding controllable parameter?

**Comment by ahojnnes** [comment]
Yes, for models without extra distortion parameters, this option has no effect.

**Comment by MaxChanger** [comment]
OK, Thank you very much for your prompt reply!
