### ISSUE TITLE
Command 'colmap' not found after installed by vcpkg

### ISSUE THREAD

**Issue by JuntingLee** [colmap/colmap#1690]
**Describe the bug**
I installed colmap:64-linux by vcpkg. But the terminal don't recongnize it.

**To Reproduce**
1. I make sure that colmap is installed by` ./vcpkg install colmap[cuda,tests]:x64-linux` and it shows:
```
Computing installation plan...
The following packages are already installed:
    colmap[core,cuda,tests]:x64-linux -> 2022-03-14#1
colmap:x64-linux is already installed
Restored 0 package(s) from /home/mikeli/.cache/vcpkg/archives in 3.619 us. Use --debug to see more details.
Total install time: 35.57 us
```
2. I use `colmap -h` to test in terminal and it shows:
```

Command 'colmap' not found, but can be installed with:

sudo apt install colmap
```

**Expected behavior**
I want to use Command-line Interface in terminal.

**Desktop:**
 - OS: Ubuntu20.04

**Comment by dadwadw233** [comment]
same problem

**Comment by dadwadw233** [comment]
You can add the location of the executable files installed by vcpkg to the environment variables of your terminal. The location of the 'colmap' is /home/xxx/vcpkg/packages/colmap_x64-linux/tools/colmap

**Comment by JuntingLee** [comment]
>
