### ISSUE TITLE
COLMAP coordinate system right-handed or left-handed?

### ISSUE THREAD

**Issue by treder** [colmap/colmap#1694]
Very basic question! The documentation states

> The local camera coordinate system of an image is defined in a way that the X axis points to the right, the Y axis to the bottom, and the Z axis to the front as seen from the image. (https://colmap.github.io/format.html)

X and Y are clear but the description of the Z-axis as "front as seen from the image" is not clear to me. What's the front as seen from the image? Concretely, does COLMAP use a

- right-handed coordinate system with positive z-axis pointing away from the camera (along with the viewing direction)
- left-handed coordinate system with positive z-axis pointing towards the camera (opposite to viewing direction)

**Comment by tsattler** [comment]
Colmap uses the same coordinate system typically used in computer vision textbooks for the local coordinate system of each image, which is a right-handed coordinate system.

**Comment by treder** [comment]
Thanks a lot for the very quick answer! Closing the issue.
