### ISSUE TITLE
Geo registration

### ISSUE THREAD

**Issue by mrKornWij** [colmap/colmap#1695]
I've used model_aligner function on enu plane. I've these images position in text file below. But after running 'colmap model_aligner', model still be the same. Nothing changed. What is happened?  
names x y z
db/p000-d3-f00076.jpg 0.00 0.00 0.00
db/p001-d3-f00088.jpg 3.00 0.00 0.00
db/p002-d3-f00100.jpg 0.00 -3.00 0.00
db/p003-d3-f00112.jpg -1.50 -6.00 0.00
db/p004-d3-f00124.jpg -3.00 -4.50 0.00
db/p005-d3-f00136.jpg -4.50 -6.00 0.00

**Comment by tsattler** [comment]
It is impossible to say what happened without more details. What is the output of the `model_aligner`?
