### ISSUE TITLE
"No images with matches found in the database" , after importing custom matches to the database.

### ISSUE THREAD

**Issue by ipapap** [colmap/colmap#1697]
I am trying to use external (binary) features with a custom matching method.
After importing the keypoints and their matches to the database using the database.py, I get the "No images with matches found in the database" warning during reconstruction.
But the database management shows that there are stored features, matched keypoints and overlapping images.
Did I miss something? 
Thanks in advance!

![image](https://user-images.githubusercontent.com/19208543/203392636-2b0e5c8e-6850-43c6-9331-e7d7a7c59dab.png)
![image](https://user-images.githubusercontent.com/19208543/203392883-67e3a09c-c80c-40fd-89b3-98b4b4eae471.png)

**Comment by tsattler** [comment]
Did you compute two-view relations from the imported matches? If I remember correctly, Colmap only uses the matches that "survive" the two-view geometry estimation stage for the reconstruction stage.

**Comment by ipapap** [comment]
Thanks for your reply! I did not run the colmap's two-view geometry estimator to filter the computed matches, but the used matching method computes the essential matrix among the matched images and discards the outliers. As far as I can tell, the two-view geometry estimator simply returns an inlier mask, so the used procedure should produce a quite similar outcome. 
Is there a 'place' in the database (or elsewhere) where I should explicitly state this outcome? Otherwise shouldn't those unfiltered keypoints just be treated by colmap as 'bad measurments' and simply 'degrade' the reconstruction instead of preventing moving on to the reconstruction stage?
Furthermore when visualizing the produced matches, they seem good.

**Comment by tsattler** [comment]
Colmap actually needs the estimated two-view geometries to initialize the reconstruction.

There are fields in the database for verified matches and the related two-view geometries. E.g., see the python examples that come with Colmap (under scripts/).

**Comment by ipapap** [comment]
Indeed, there is a dedicated function (in scripts/python/database.py) for that. Thanks!

**Comment by Davidyao99** [comment]
@ipapap Hi, I am facing the same issue here. Could you elaborate slightly on how you resolved it? Which function did you use and how did you use it to make things work? Thank you so much!

**Comment by ipapap** [comment]
Hello, the function is implemented inside the COLMAPDatabase class. 
You will need to create a database object from the COLMAPDatabase class, within the scripts/python/database.py file.

```
from database import COLMAPDatabase
db = database.COLMAPDatabase.connect(database_path)
db.create_tables()
```

Then you need to populate the database
First create a camera:
`camera_id=db.add_camera(model,width,height,params)`

Then add the two view geometries between the image that you want to add and the rest of the matched images.
Assuming you want to add image1:
```
db.add_two_view_geometry(image_id1,image_id2,matches)
db.add_two_view_geometry(image_id1,image_id3,matches)
db.add_two_view_geometry(image_id1,image_id4,matches)
```

Add image1 to the database :

`db.add_image(image1_name,camera_id,image_id1)`

Now you can add the keypoints and dectriptors as well as their matches:

```
db.add_keypoints(image_id1,image1_keypoints)
db.add_descriptors(image_id1, image1_descriptors)

db.add_matches(image_id1,image_id2,matches)
db.add_matches(image_id1,image_id3,matches)
db.add_matches(image_id1,image_id4,matches)

```
Finally commit the data to the file:
```
db.commit()
db.close()

```


It’s been a while, so hopefully I haven’t missed anything. Good luck!
