### ISSUE TITLE
License for Image Datasets?

### ISSUE THREAD

**Issue by pogilon** [colmap/colmap#170]
Hello @ahojnnes,

What is the license for the image data sets provided at (https://colmap.github.io/datasets.html), especially the South Building dataset? Thanks.

**Comment by ahojnnes** [comment]
What is your use case?

**Comment by ahojnnes** [comment]
With appropriate citation, you can use the data for scientific/research purposes.

**Comment by pogilon** [comment]
@ahojnnes thank you.
