### ISSUE TITLE
How to visualize matches between two images for large database?

### ISSUE THREAD

**Issue by is03wlei** [colmap/colmap#171]
My database is too large to be loaded in GUI.

**Comment by ahojnnes** [comment]
The database management widget is currently not built for very large databases. How many images do you have? Alternatively, you could visualize the matches yourself by loading the SQLite database with Python and using e.g. the scikit-image functions skimage.feature.draw_matches. There should be an example for how to read matches from the database in the scripts/python folder (e.g. export_inlier_matches.py or export_to_bundler.py).

**Comment by ahojnnes** [comment]
Closing this issue as resolved. Feel free to reopen if you have a question regarding my description.
