### ISSUE TITLE
Command line does nothing at all in windows 10

### ISSUE THREAD

**Issue by mpizenberg** [colmap/colmap#1716]
I’ve downloaded colmap 3.7 for windows with cuda from the release pages, and trying to be able to call the executable in the command line without success.

After extracting the archive, I’ve checked that the program works as expected by launching the GUI thanks to `COLMAP.bat`. This seems to be working fine. However, I’d like to be able to use colmap from the command line, because I need it to try [nerfstudio](https://docs.nerf.studio).

So I’ve added the `bin/` and `lib/` dirs to my path. This seems to work, since now I can call `colmap` from anywhere. The issue is it returns nothing at all. For example you can see the empty output of `colmap help` in the following screenshot.

![image](https://user-images.githubusercontent.com/2905865/206198441-2322b26a-0b88-4a7b-8411-6cd999688c47.png)

**To Reproduce**

1. Download the windows cuda zip for colmap 3.7 from the [release page](https://github.com/colmap/colmap/releases/tag/3.7).
2. Extract it and add the `bin/` and `lib/` subfolders to you path
3. Run `colmap help` from anywhere
4. See empty output

**Expected behavior**
I was expecting to see the help message.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by tsattler** [comment]
I can't replicate this. With version 3.8, if I go into the folder that contains COLMAP.bat, typing `colmap help` provides me with the list of possible options, as expected.

**Comment by mpizenberg** [comment]
Hum, ok so it I may have been biased by my linux experience. As said in my previous comment, I had added the `bin/` and `lib/` directories to my path, and not the parent one which contains the `COLMAP.bat` file. Once I add that directory instead, the command line now works.

I suppose I was confuse by the fact that there is a `bin/colmap.exe` and I thought this was the one that needed to be launched via command line. But it seems that even in the command line, `colmap` must refer to `COLMAP.bat` instead.

Could you confirm the correct way?

**Comment by tsattler** [comment]
I am not using the windows command line typically, but rather run an Ubuntu installation via WSL.
