### ISSUE TITLE
GUI feature, toggle registered cams visibility

### ISSUE THREAD

**Issue by polarathene** [colmap/colmap#172]
I can't seem to find this functionality. Just got colmap and gave it images around a small object, the reconstruction briefly had some detail I could see but by completion was covered in many red planes and lines. It's rather difficult to see the results.

Supposedly this would not be a difficult feature to support?

**Comment by ahojnnes** [comment]
You can change the size of cameras with ``ALT + SCROLL``. Does this solve your issue?

**Comment by polarathene** [comment]
Yes, that seems to work. Would it be too much to ask fo a UI option like apop up dialog from a menu that provides a slider component or something to do the same? Or is there a way to change shortcuts?

**Comment by ahojnnes** [comment]
The shortcuts are documented in the documentation. I am currently not planning to implement a slider for this but I will keep it in mind.

**Comment by polarathene** [comment]
@ahojnnes I understand that, but that'd require discovering it by reaching that part of the documentation. Is it mentioned anywhere else in the documentation beyond as a shortcut?(which btw isn't obvious where those are located from the sidebar and entering into search field `shortcut`(`s`) produces no results)

I do remember going to the GUI section of the docs and seeing the shortcuts but for some reason `Change camera size: <ALT>-scroll.` didn't sound like what I wanted. I think I assumed it referred to the viewport camera(it is under a header of `Model Viewer Controls`). As I couldn't find any actual way to adjust it via the menu/UI, I assumed it wasn't possible....shortcuts are usually shortcuts to something, you know?

---

So uhh, what is presumably a small simple UI addition or improved documentation would help. This issue exists on it now, so if anyone else gets confused trying to figure out how to do it, they might stumble upon this and chime in :) 

Thanks for the great project btw, overall a pretty good experience!

**Comment by ahojnnes** [comment]
Thanks for the feedback again. I will keep it in mind but currently I have too many other things to do with higher priority.

**Comment by ahojnnes** [comment]
With the latest commit in the dev branch, there are now explicit buttons in the render options to change the point/camera size. Thanks again for the feedback.
