### ISSUE TITLE
Question Regarding Volume Rendering with COLMAP Reconstructed Point Cloud

### ISSUE THREAD

**Issue by aditya-vora** [colmap/colmap#1720]
Hello, I had a query regarding using COLMAP reconstructed point cloud in the volume rendering task. For this, I have ground-truth poses with respect to which I would like to reconstruct the point cloud. I have the following questions: 

1) What is the recommended way of doing the reconstruction? Is [triangulation with known camera poses](https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses) the right way of doing this? 

2) If we use triangulation, is the point cloud guaranteed to be within the scene bounds? I have different scenes with different scene bounds and I want my reconstructed point cloud to be within the scene bounds and aligned with the images so that I can do some processing over it. Would this be possible? 

Any help in these regards would be highly appreciated as I am relatively new to using COLMAP,
Thanks.

**Comment by tsattler** [comment]
1. If the poses are accurate, then the `point_triangulator` is the most convenient way to get 3D points.
2. No, since Colmap has by default no notion of scene bounds. You can use the `model_cropper` to remove 3D points outside a 3D bounding box.

**Comment by aditya-vora** [comment]
Thanks for the response. 

1. Currently, I am using `point_triangulator` to reconstruct 3D points from the DTU scenes. For this, as explained in the following [instructions ](https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses) I am creating a `cameras.txt` file which contains the camera intrinsic, an empty `points3D.txt` file and `images.txt` containing the `[image_id, quaternions, camera center, camera_id, image_name]`. For converting the camera extrinsic provided by DTU to quaternion I am using the `rotmat2qvec` function provided [here](https://github.com/colmap/colmap/blob/0fed789f2a638c70f49e188e07e8cb6202fa3749/scripts/python/read_write_model.py#L466). Once dumping these quaternions and camera center to `images.txt` I run the `feature_extractor`, `exhaustive_matcher` and `point_triangulator`. However, on running the `point_triangulator` I get the following error: 

```
*** Check failure stack trace: ***
    @   00007FF9321C5FFB  public: void __cdecl google::LogMessage::Flush(void) __ptr64
    @   00007FF9321C4B49  public: __cdecl google::LogMessageFatal::~LogMessageFatal(void) __ptr64
    @   00007FF7CFDDD257  (unknown)
    @   00007FF7CFDDC78C  (unknown)
    @   00007FF7CFD94B16  (unknown)
    @   00007FF7CFD9631B  (unknown)
    @   00007FF7D033F674  (unknown)
    @   00007FF94CCC244D  BaseThreadInitThunk
    @   00007FF94DF4DFB8  RtlUserThreadStart
```
Do you have any idea what would be the issue? I checked the database if the `image_ids` are the same as I saw in some of the issues here in the repo, but found that the `image_ids` are also the same and I am also getting the feature matches. Following is the snapshot of the database. However, the quaternions and camera centers are `nan`. Is this normal? 

![Screenshot 2022-12-11 140854](https://user-images.githubusercontent.com/11326081/206923780-5a119ee5-1376-47c6-8243-d7d252279190.png)

2. So, in the case of scene bounds will the reconstructed point cloud on triangulation have completely different depth ranges?  You mentioned `model_cropper` from colmap, will it not just filter the outliers which does not belong to a bounding box? What will happen if the scene bounds of the reconstructed point cloud are completely different from the desired scene bound? 

Thanks for the help in advance.

**Comment by aditya-vora** [comment]
> Are you sure that the images.txt (and the other files) has the correct structure? 

I think so. Following is the snap of the `images.txt` file. I am using the `write_images_text` function available in the sample python code of colmap.

```
1 0.9924258814942094 -0.014906506293475313 0.12180856814853891 -0.005598083258314686 -0.9551 0.0164416 0.1127005 1 rect_001_3_r5000.png

2 0.9491866126874573 -0.0131375537821497 0.21606940911704742 0.22844296754188137 -1.457095 -0.3852475 0.356381 1 rect_002_3_r5000.png

3 0.8435936081532563 -0.009846551182248447 0.2966407242825536 0.4475010060434587 -1.6728 -0.97078496 0.64671993 1 rect_003_3_r5000.png

4 0.6821478663625291 -0.005419750831672797 0.3579919895230572 0.637563055826869 -1.5451199 -1.5921448 0.90796995 1 rect_004_3_r5000.png

5 0.4762943225240643 -0.00038690040873116374 0.39475476036586576 0.7856922093338485 -1.1002799 -2.08544 1.066085 1 rect_005_3_r5000.png

```

Also, my poses seem to be correct, as I just load the sparse model which I create in the colmap GUI to check the poses. Following is the screenshot of the colmap GUI. 

<img width="320" alt="Screenshot 2022-12-12 100133" src="https://user-images.githubusercontent.com/11326081/207078823-460d2135-0a69-46bf-98cc-4f6c7983eb1f.png">

Also, the following is the logic that I am using the create the `images.txt` file. Is this how I should be dumping the data in the `images.txt` file? The `extrinsic` is the `world_to_camera` transformation matrix. 

```
def write_images_text_dtu(view_ids, path):    
    with open(path, "w") as fid:         
        for view_id in view_ids: 
            img_filename = f'rect_{view_id:03d}_{3}_r5000.png'
            cam_filename = os.path.join(root, f'cameras/{view_id-1:08d}_cam.txt')
            intrinsics, extrinsics = read_cam_file(cam_filename, scale_factor=1.0/200) 

            R = extrinsics[:3, :3]  # (3, 3)
            t = extrinsics[:3, 3:]  # (3, 1)
            
            Rt_flat = R.flatten()

            qvec = rotmat2qvec(Rt_flat)
            qvec = np.array(tuple(qvec))
            tvec = np.array(tuple(np.squeeze(t)))

            image_header = [view_id, *qvec, *tvec, 1, img_filename]        
            first_line = " ".join(map(str, image_header))
            fid.write(first_line + "\n")

            points_strings = []  
            fid.write(" ".join(points_strings) + "\n")
```

Apart from this, I am manually writing the camera intrinsics in the `cameras.txt` file which is the following: 

`1 PINHOLE 640 512 1,446.165 1441.59 320 256`

> Where exactly does the crash happen?

It seems the `feature_extractor` and `feature_matching` works fine. However, while running `point_triangulator` it crashes.

```
PS C:\Users\ADITYA\Desktop\COLMAP-3.7-windows-no-cuda> .\COLMAP.bat point_triangulator --database_path ..\scan_3_train_recon\database.db --image_path ..\scan_3_train_recon\images\ --input_path ..\scan_3_train_recon\sparse\ --output_path ..\scan_3_train_recon\

==============================================================================
Loading model
==============================================================================


==============================================================================
Loading database
==============================================================================

Loading cameras... 49 in 0.001s
Loading matches... 860 in 0.023s
Loading images... 49 in 0.033s (connected 49)
Building correspondence graph... in 0.104s (ignored 0)

Elapsed time: 0.003 [minutes]


==============================================================================
Triangulating image #1 (0)
==============================================================================

  => Image sees 0 / 1356 points
  => Triangulated 0 points

==============================================================================
Triangulating image #2 (1)
==============================================================================

  => Image sees 0 / 1947 points
  => Triangulated 0 points

==============================================================================
Triangulating image #3 (2)
==============================================================================

  => Image sees 0 / 1707 points
  => Triangulated 0 points

==============================================================================
Triangulating image #4 (3)
==============================================================================

  => Image sees 0 / 1181 points
  => Triangulated 0 points

==============================================================================
Triangulating image #5 (4)
==============================================================================

  => Image sees 0 / 669 points
  => Triangulated 0 points

==============================================================================
Triangulating image #6 (5)
==============================================================================

  => Image sees 0 / 704 points
  => Triangulated 0 points

==============================================================================
Triangulating image #7 (6)
==============================================================================

  => Image sees 0 / 1218 points
  => Triangulated 0 points

==============================================================================
Triangulating image #8 (7)
==============================================================================

  => Image sees 0 / 1992 points
  => Triangulated 0 points

==============================================================================
Triangulating image #9 (8)
==============================================================================

  => Image sees 0 / 2439 points
  => Triangulated 0 points

==============================================================================
Triangulating image #10 (9)
==============================================================================

  => Image sees 0 / 2457 points
  => Triangulated 0 points
```

It seems none of the images is able to find any points.

**Comment by aditya-vora** [comment]
A snapshot of the exact location of the crash. 

```
==============================================================================
Bundle adjustment
==============================================================================

F1211 14:03:20.479573 12264 sfm.cc:473] Check failed: bundle_adjuster.Solve(&reconstruction)
*** Check failure stack trace: ***
    @   00007FF9321C5FFB  public: void __cdecl google::LogMessage::Flush(void) __ptr64
    @   00007FF9321C4B49  public: __cdecl google::LogMessageFatal::~LogMessageFatal(void) __ptr64
    @   00007FF7CFDDD257  (unknown)
    @   00007FF7CFDDC78C  (unknown)
    @   00007FF7CFD94B16  (unknown)
    @   00007FF7CFD9631B  (unknown)
    @   00007FF7D033F674  (unknown)
    @   00007FF94CCC244D  BaseThreadInitThunk
    @   00007FF94DF4DFB8  RtlUserThreadStart
```

**Comment by tsattler** [comment]
The crash happens because Colmap is not able to triangulate any 3D points, but assumes that 3D points are available during bundle adjustment. 

Are you sure that the poses are correct? Colmap expects that the poses transform from world to camera coordinates. Did you check whether the poses you read do the same?

**Comment by aditya-vora** [comment]
Yes, the poses which I read from the dataset are by default world to camera transformation. Here is the snapshot of the code which I use to create the `images.txt` file. 

```
def write_images_text_dtu(view_ids, path):    
    with open(path, "w") as fid:         
        for view_id in view_ids: 
            img_filename = f'rect_{view_id:03d}_{3}_r5000.png'
            cam_filename = os.path.join(root, f'cameras/{view_id-1:08d}_cam.txt')
            intrinsics, extrinsics = read_cam_file(cam_filename, scale_factor=1.0/200) 

            R = extrinsics[:3, :3]  # (3, 3)
            t = extrinsics[:3, 3:]  # (3, 1)
            
            Rt_flat = R.flatten()

            qvec = rotmat2qvec(Rt_flat)
            qvec = np.array(tuple(qvec))
            tvec = np.array(tuple(np.squeeze(t)))

            image_header = [view_id, *qvec, *tvec, 1, img_filename]        
            first_line = " ".join(map(str, image_header))
            fid.write(first_line + "\n")

            points_strings = []  
            fid.write(" ".join(points_strings) + "\n")
```
Also, as per the loaded poses in the colmap GUI they look correct to me (as expected for DTU dataset). 

<img width="256" alt="Screenshot 2022-12-12 100133" src="https://user-images.githubusercontent.com/11326081/207108031-3dc98787-a644-4015-a065-dfce149a40c8.png">

One thing which I observed, the rotation matrices which I obtained from the dataset are not orthogonal. I am sharing a sample extrinsic values from the DTU dataset. Could that be the reason? 

```
0.802256 -0.439347 0.404178
0.427993 0.895282 0.123659  
-0.416183 0.073779 0.906283 
```

**Comment by aditya-vora** [comment]
@tsattler I was able to figure out the problem. The issue was in the camera intrinsics. Thanks :-)

**Comment by Gaozihui** [comment]
@aditya-vora  hi, so what's the problem with camera intrinsics? Also if it is ok that the extrinsic matrix are not orthogonal? Thanks~

**Comment by 1ssb** [comment]
I am trying an alternate version of this where I am simply evaluating the NeRF output which is within a predefine depth range vs the COLMAP which is returning a different scale for the triangulated points. First of all, if I am using two track points in the triangulation, how is this plausible (using the exact same camera poses) and secondly is there any process to systematically study this. I note that the NeRF model has performed scene triangulation from photometric error reduction which is of course prone to some error but the error should never be in the scene scale. What am I missing here? @tsattler any suggestion/advice?
