### ISSUE TITLE
How to use custom normal maps for dense reconstruction?

### ISSUE THREAD

**Issue by CriusFission** [colmap/colmap#1727]
Hi,

I'm running COLMAP using command line. I've completed running the sparse reconstruction and undistortion step. 
I have about 100 images. Is it possible to use custom normal and depth maps that I have, instead of the COLMAP generated depth and normals. I'm generating depth and normals using a different repo for the same 100 images. 
  The depth and normals I have is in PNG format. I understand COLMAP generates it in BIN format. I want to use COLMAP to fuse the depth and normals to the point cloud.

Is it possible to convert the depth and normals to BIN format and run the fusion step so that the COLMAP fuses this custom depth and normals to the point cloud? How do I do this?

**Comment by StepMan91** [comment]
Hi,

what is the advantage/ disaventage to have it on BIN or PNG format  ? for normals and depth ?

**Comment by CriusFission** [comment]
@StepMan91, I do not know anything about the advantages or disadvantages. I'm trying to use my own normal maps and depth maps instead of the colmap generated ones. But colmap takes only normal and depth maps in BIN format. I'm asking how I would go about converting those normals and depths to BIN format.

**Comment by tsattler** [comment]
I would look at the code where normal maps and depth maps are written to figure out the format. Then it should be fairly simple to convert from your format to Colmap's format.

**Comment by CriusFission** [comment]
Thanks @tsattler, will look into the code.

**Comment by CriusFission** [comment]
@tsattler I see that there are two files for each depth and normal maps: geometric and photometric. 
What does they do?  Should the maps exist in both these formats to do reconstruction with my custom converted maps? I'm trying to convert my PNG maps to BIN files for COLMAP to read.

**Comment by tsattler** [comment]
@CriusFission you can specify which type of depth maps should be used during fusion using the `--input_type` argument of the `colmap stereo_fusion` command. It should thus be sufficient to create one type of depth / normal maps.

**Comment by CriusFission** [comment]
@tsattler I'm now able to convert the normal and depth map from image format to BIN format using:https://github.com/colmap/colmap/blob/c41b36c7cc84b4df61413a486c1c00ab598793a4/scripts/python/read_write_dense.py#L58 in the python scripts. But when I fuse those with the point cloud, the point cloud is very noisy.
The input images that I'm using is 2308x1036 and the normal map of the same image that I'm using is 640x480 with 32bit depth. Could this be causing the issue?

**Comment by tsattler** [comment]
I guess it could be one reason. Others could be noise in the depth maps, not adjusting the parameters of the fusion process, and probably many more that I currently can't think of. I'd recommend to carefully look through the code for the fusion step and see whether you provide all data it uses.

**Comment by qingzhengzhuma** [comment]
when you fuse depth map and normap, you should take care of the image undistortion method. colmap provide two different ways to do image undistortion, so i think you need check the undistortion method your dense reconstruction pipeline used and the that of colmap used. and you still need check the intrinsic/extrinsic for your dense reconstruction and that generated from colmap, please make sure they are the same.

**Comment by CriusFission** [comment]
Hi @qingzhengzhuma, I'm using colmap for the dense re-construction as well. I'm doing the undistortion step first using the command line. But I'm skipping the patch_match_stereo step which generates the depth and normals and instead using a custom normal and depth. After that I'm continuing the stereo fusion step which fuses the depth and normals to the point cloud.

**Comment by tsattler** [comment]
>  These two differ in color. Why would that be happening

The gui and python might use different color maps? Did you look into this?

**Comment by CriusFission** [comment]
python uses matplotlib to plot the image and matplotlib uses its default colormap. Not sure which colormap colmap uses. But that should explain the difference in the color. Thanks.

**Comment by CriusFission** [comment]
python uses matplotlib to plot the image and matplotlib uses its default colormap. Not sure which colormap colmap uses. But that should explain the difference in the color. Thanks for helping out @tsattler . I'll mark the issue as closed.

**Comment by tanjunyao7** [comment]
hi, I have the same need. Did you figure it out how to use custom depth and normal map?

**Comment by tanjunyao7** [comment]
thanks I’ll try it.

**Comment by Mehi44** [comment]
@CriusFission Thanks for posing the issue, I have tried your method and it works indeed.
 Also I think the reason why you have noise in your point cloud is because you have your depth maps in .png format which only carries integer values. I had the same issue. I solved it by saving my custom depth maps in .npy which preserved the floating point values and it worked fine.

**Comment by CriusFission** [comment]
That's great @Mehi44, and thanks for that! I'll try it out!

**Comment by mahadyRayhan** [comment]
Hi
I tried the process of converting png to bin file using "read_write_dense.py"
but I got this error. 

File "read_write_dense.py", line 144, in <module>
    main()
  File "read_write_dense.py", line 120, in main
    depth_map = read_array(args.depth_map)
  File "read_write_dense.py", line 43, in read_array
    width, height, channels = np.genfromtxt(fid, delimiter="&", max_rows=1, usecols=(0, 1, 2), dtype=int)
  File "/home/ubuntu-20/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 2124, in genfromtxt
    raise ValueError(errmsg)
ValueError: Some errors were detected !
    Line #1 (got 1 columns instead of 3)
    Line #2 (got 1 columns instead of 3)
    Line #3 (got 2 columns instead of 3)
    Line #4 (got 1 columns instead of 3)
    Line #5 (got 1 columns instead of 3)
    Line #6 (got 1 columns instead of 3)
    Line #7 (got 1 columns instead of 3)
    Line #8 (got 2 columns instead of 3)
    Line #9 (got 1 columns instead of 3)
    Line #10 (got 1 columns instead of 3)

am I missing something?

**Comment by CriusFission** [comment]
Hi @mahadyRayhan, Try using the write_array function inside the read_write_dense.py file instead of using the CLI. Using the CLI will only help you visualize the depth and normal map bin files. write_array function is independent and will take arrays of shape 2 or 3.
Please take a look at the [source code.](https://github.com/colmap/colmap/blob/dev/scripts/python/read_write_dense.py)

**Comment by Mehi44** [comment]
Hi @CriusFission, If possible, I would like to use the method by which you extracted normal  and depth maps from your images.

**Comment by CriusFission** [comment]
@Mehi44 I'm using [this ](https://github.com/baegwangbin/surface_normal_uncertainty)repo for getting the normal and depth maps.
