### ISSUE TITLE
UI Bug - New Project fields cleared by file chooser cancel

### ISSUE THREAD

**Issue by polarathene** [colmap/colmap#173]
When creating a new project, for the Project dialog, I click `New` and select a location and file name, this gets filled in. As the file is not created until `Save` if I click `Open` and then cancel that file chooser dialog, the Database field clears itself to be blank. It should not reset that field to be empty because of a cancel operation for `Open`.

This same behaviour happens with `Select` for the Images field. If you click the `Select` button again after choosing a location, but choose to cancel the dialog, the `Images` field is cleared. 

In the event these buttons are clicked by accident the fields need to avoid clearing themselves upon canceling a file chooser dialog. The dialog itself feels like it could be improved, rather than `Save`, `Create might be a more useful word? Or `Create Project`.

**Comment by ahojnnes** [comment]
This should be fixed with the latest commit in the dev branch. Thanks for your feedback.
