### ISSUE TITLE
COLMAP run patch matching very slow

### ISSUE THREAD

**Issue by XiongFenghhh** [colmap/colmap#1734]
I run COLMAP on a server with a 32g v100 GPU. In the patch matching step(command is shown below), COLMAP run very slow. It runs 4.25s~6s per image( I have 92 images), and needs to run two rounds( one for photometric and one for geometric).

`colmap patch_match_stereo \
    --workspace_path $1/dense \
    --workspace_format COLMAP \
    --PatchMatchStereo.geom_consistency true \
    --PatchMatchStereo.num_iterations 2 \
    --PatchMatchStereo.window_radius 3 \
    --PatchMatchStereo.window_step 2 \
    --PatchMatchStereo.cache_size 8`

If I use openMVS to do dense reconstruction( with its DensifyPointCloud command) instead of COLMAP, the total process takes a very short time, about 3min. Is there a way to speed up COLMAP's patch matching ?

**Comment by ahojnnes** [comment]
You can try to reduce the image size, if you don't need full resolution depth/normal maps. That might also allow you to reduce the window_radius. Another option would be to disable geom_consistency, which should cut the time roughly in half.
