### ISSUE TITLE
UI Bug - File chooser dialog inconsistency

### ISSUE THREAD

**Issue by polarathene** [colmap/colmap#174]
In the `New Project` dialog, the `New` and `Open` buttons open a native KDE/Qt dialog for file choosing. This doesn't seem to be the case for the Images `Select` button. I'm not used to seeing this dialog on my OS even for other applications where a directory selection is performed. It looks a bit like GTK3 file chooser dialog?

I think this happens elsewhere with other dialogs for navigating users file system. It's minor but would be nice if it could be addressed at some point.

**Comment by ahojnnes** [comment]
I am using the standard Qt functions for opening the file chooser dialogs. Maybe upgrading to a newer Qt version on your system might fix the issue. Otherwise, I am not intending to address this minor cosmetic issue. But thanks for the feedback anyway.

**Comment by polarathene** [comment]
I'm using 5.9 so I'd doubt that. No worries.
