### ISSUE TITLE
Build from Source fails with CUDA 12 due to deprecated CUDA module

### ISSUE THREAD

**Issue by Skaggio** [colmap/colmap#1742]
**Environment:**
 - OS: wsl2 - Ubuntu
 - CUDA: 12.0(.76)
 - COLMAP Version : last checkout (commit c41b36c7cc84b4df61413a486c1c00ab598793a4, dated Sat Dec 31 12:40:38 2022 +0100)
 
 

**Describe the bug**

Build from Source fails with CUDA 12 due to deprecated CUDA module
Since the Texture Reference Management module (see https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__TEXREF__DEPRECATED.html ) has been deprecated for quite a while now and has been removed completely in version 12 of CUDA but colmap still refers to it, the compilation fails 

**To Reproduce**
Simply build from source as described here:
https://colmap.github.io/install.html#linux
The "make -j" command fails with this output

[  0%] Building C object lib/LSD/CMakeFiles/lsd.dir/lsd.c.o
[  2%] Building CXX object lib/PoissonRecon/CMakeFiles/poisson_recon.dir/CmdLineParser.cpp.o
[...]
[ 29%] Building C object lib/VLFeat/CMakeFiles/vlfeat.dir/mathop_sse2.c.o
/mnt/c/Data-Work/CodeTest/Head/NeRF/instant-ngp/colmap/lib/PBA/ProgramCU.cu(42): error: incomplete class type "textureReference" is not allowed

/mnt/c/Data-Work/CodeTest/Head/NeRF/instant-ngp/colmap/lib/PBA/ProgramCU.cu(42): error: identifier "cudaBindTexture" is undefined

/mnt/c/Data-Work/CodeTest/Head/NeRF/instant-ngp/colmap/lib/PBA/ProgramCU.cu(48): error: incomplete class type "textureReference" is not allowed

/mnt/c/Data-Work/CodeTest/Head/NeRF/instant-ngp/colmap/lib/PBA/ProgramCU.cu(47): error: identifier "cudaBindTexture" is undefined

/mnt/c/Data-Work/CodeTest/Head/NeRF/instant-ngp/colmap/lib/PBA/ProgramCU.cu(585): error: texture is not a template

[...]

**Comment by ahojnnes** [comment]
Thanks for reporting the issue. I was afraid of this happening at some point. It's going to be quite a bit of effort to migrate to the new texture object API. If anybody reading this, has the cycles to tackle this, the help would be much appreciated.

**Comment by johnnynunez** [comment]
Same error here

**Comment by ahojnnes** [comment]
Until we update the deprecated API calls, the workaround is to use a CUDA version < 12.

**Comment by agz321** [comment]
I have the same error. My cuda version is 12.1.

**Comment by nepfaff** [comment]
Same here

**Comment by ahojnnes** [comment]
This is a known issue. Please downgrade to CUDA 11.x until the API calls are upgraded.

**Comment by ahojnnes** [comment]
The latest commit in the dev branch should now be compabile with CUDA 12.

**Comment by flydragon2018** [comment]
I failed to build with cuda 12.0.   It complains about  cuda architecture

**Comment by sumitsarkar1** [comment]
@ahojnnes which dev branch u r referring to coz i am facing the same issues with CUDA 12
