### ISSUE TITLE
nvcc fatal   : Unknown option 'fPIC'

### ISSUE THREAD

**Issue by yyspyysp** [colmap/colmap#1753]
When I use  make command I get this error

`[ 90%] Building CXX object src/CMakeFiles/colmap.dir/colmap_autogen/UYX5XTB5RZ/qrc_resources.cpp.o
[ 90%] Linking CXX static library libcolmap.a
[ 90%] Built target colmap
[ 90%] Building CUDA object src/CMakeFiles/colmap_cuda.dir/mvs/gpu_mat_prng.cu.o
nvcc fatal   : Unknown option 'fPIC'
make[2]: *** [src/CMakeFiles/colmap_cuda.dir/mvs/gpu_mat_prng.cu.o] Error 1
make[1]: *** [src/CMakeFiles/colmap_cuda.dir/all] Error 2
make: *** [all] Error 2
`
How can I fix this error?Thanks

**Comment by yyspyysp** [comment]
No. I have tried some online methods but still no solution, what is the problem you are experiencing?




尹一帆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "colmap/colmap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月11日(星期三) 下午4:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [colmap/colmap] nvcc fatal   : Unknown option 'fPIC' (Issue #1753)





 
@yyspyysp
 Hi, I got the same problem with you. Do you solve this problem?

**Comment by spicy-dog** [comment]
@ahojnnes hello, could you give some suggestions to fix this error? Thanks!

**Comment by rmadan2** [comment]
Hi, I am facing the same issue as well. Can the -fPIC flag be removed from CMakeLists.txt?

**Comment by spicy-dog** [comment]
您好，您的邮件我已经收到了，谢谢

**Comment by ahojnnes** [comment]
Which version of CUDA/GCC are you using to compile colmap?

**Comment by rmadan2** [comment]
CUDA: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

**Comment by rmadan2** [comment]
P.S: I tried removing the -fPIC flag, and it compiled all the way to 96%, (sift_gpu compiles as well), but then it crashes with errors arising here: 
```
nvcc fatal   : Unknown option 'fPIC'
nvcc fatal   : Unknown option 'fPIC'
make[2]: *** [src/CMakeFiles/colmap_cuda.dir/build.make:63: src/CMakeFiles/colmap_cuda.dir/mvs/gpu_mat_prng.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/CMakeFiles/colmap_cuda.dir/build.make:76: src/CMakeFiles/colmap_cuda.dir/mvs/gpu_mat_ref_image.cu.o] Error 1
nvcc fatal   : Unknown option 'fPIC'
make[2]: *** [src/CMakeFiles/colmap_cuda.dir/build.make:102: src/CMakeFiles/colmap_cuda.dir/mvs/patch_match_cuda.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:661: src/CMakeFiles/colmap_cuda.dir/all] Error 2
```

**Comment by spicy-dog** [comment]
> P.S: I tried removing the -fPIC flag, and it compiled all the way to 93%, (sift_gpu compiles as well), but then it crashes with errors arising here:
> 
> ```
> nvcc fatal   : Unknown option 'fPIC'
> nvcc fatal   : Unknown option 'fPIC'
> make[2]: *** [src/CMakeFiles/colmap_cuda.dir/build.make:63: src/CMakeFiles/colmap_cuda.dir/mvs/gpu_mat_prng.cu.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[2]: *** [src/CMakeFiles/colmap_cuda.dir/build.make:76: src/CMakeFiles/colmap_cuda.dir/mvs/gpu_mat_ref_image.cu.o] Error 1
> nvcc fatal   : Unknown option 'fPIC'
> make[2]: *** [src/CMakeFiles/colmap_cuda.dir/build.make:102: src/CMakeFiles/colmap_cuda.dir/mvs/patch_match_cuda.cu.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:661: src/CMakeFiles/colmap_cuda.dir/all] Error 2
> ```

hi, do you know how to remove -fPIC flag now?

**Comment by rmadan2** [comment]
You can comment it out in CMakeLists.txt

**Comment by cheylong** [comment]
I solve it by update cmake version to 3.25.X

**Comment by yyspyysp** [comment]
@cheylong i update cmake to 3.25.2，but i still have this error
[ 34%] Building CUDA object src/CMakeFiles/colmap_cuda.dir/mvs/gpu_mat_ref_image.cu.o
[ 34%] Building CUDA object src/CMakeFiles/colmap_cuda.dir/mvs/gpu_mat_prng.cu.o
[ 34%] Building CUDA object src/CMakeFiles/colmap_cuda.dir/mvs/patch_match_cuda.cu.o
[ 34%] Building CXX object src/CMakeFiles/colmap_cuda.dir/mvs/patch_match.cc.o
nvcc fatal   : Unknown option 'fPIC'
make[2]: *** [src/CMakeFiles/colmap_cuda.dir/mvs/gpu_mat_prng.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
nvcc fatal   : Unknown option 'fPIC'
make[2]: *** [src/CMakeFiles/colmap_cuda.dir/mvs/gpu_mat_ref_image.cu.o] Error 1
nvcc fatal   : Unknown option 'fPIC'
make[2]: *** [src/CMakeFiles/colmap_cuda.dir/mvs/patch_match_cuda.cu.o] Error 1

**Comment by yyspyysp** [comment]
@ahojnnes i update cmake to 3.25.2，but i still have this error
[ 34%] Building CUDA object src/CMakeFiles/colmap_cuda.dir/mvs/gpu_mat_ref_image.cu.o
[ 34%] Building CUDA object src/CMakeFiles/colmap_cuda.dir/mvs/gpu_mat_prng.cu.o
[ 34%] Building CUDA object src/CMakeFiles/colmap_cuda.dir/mvs/patch_match_cuda.cu.o
[ 34%] Building CXX object src/CMakeFiles/colmap_cuda.dir/mvs/patch_match.cc.o
nvcc fatal : Unknown option 'fPIC'
make[2]: *** [src/CMakeFiles/colmap_cuda.dir/mvs/gpu_mat_prng.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
nvcc fatal : Unknown option 'fPIC'
make[2]: *** [src/CMakeFiles/colmap_cuda.dir/mvs/gpu_mat_ref_image.cu.o] Error 1
nvcc fatal : Unknown option 'fPIC'
make[2]: *** [src/CMakeFiles/colmap_cuda.dir/mvs/patch_match_cuda.cu.o] Error 1

**Comment by novasky0709** [comment]
i have the same error with cmake 3.25 and 3.16

**Comment by bobododosjl** [comment]
I have the same problem with cmake 3.25.2

**Comment by dadwadw233** [comment]
I have the same problem with cmake 3.16.3 and Cuda 11.7

**Comment by yhz0614** [comment]
I have the same problem,Do you solve this problem now?

**Comment by XiaoHaoPan** [comment]
I have the same problem with cmake 3.25.2

**Comment by SudoShutdownNow** [comment]
I solve this by installing cmake 3.26.3.

**Comment by spicy-dog** [comment]
您好，您的邮件我已经收到了，谢谢

**Comment by mch0dmin** [comment]
i solve this issue by update cuda version to 11.3

environment : ubuntu18.04  cuda11.3 gcc7.5.9 cmake3.26.4

```
export CUDA_HOME="/usr/local/cuda-11.3"
export LD_LIBRARY_PATH="/usr/local/cuda-11.3/lib64:${LD_LIBRARY_PATH}"
export PATH="/usr/local/cuda-11.3/bin:${PATH}"

cd colmap
mkdir build
cd build
cmake .. -GNinja -DCMAKE_CUDA_ARCHITECTURES=native
ninja
sudo ninja install
```

i hope it can help you.

**Comment by everRoc** [comment]
您好，您的邮件我已经收到了，谢谢

**Comment by yujianing0210** [comment]
> I solve this by installing cmake 3.26.3.

This worked for me as well, thx!!

**Comment by everRoc** [comment]
您好，您的邮件我已经收到了，谢谢

**Comment by AlbertHuyb** [comment]
For my case, it is because cmake find Qt5 libraries under the anaconda directory. 

When I modify the paths to those libraries under `/usr/lib/x86_64-linux-gnu/cmake/`, everything works.

If you want to modify it, try to use the ccmake tool, which provides a GUI to modify the configurations.


<img width="800" alt="image" src="https://github.com/colmap/colmap/assets/29257247/81b93ad0-8b02-4aa0-893f-e98e75b218d7">
