### ISSUE TITLE
SIFT_TEST can not pass

### ISSUE THREAD

**Issue by changhaonan** [colmap/colmap#1754]
**Describe the bug**
When run src/feature/sift_test, I got the error.

**To Reproduce**
1. Check to the latest dev branch
2. Set TESTS_ENABLED to "ON"
3. Build it
4. Run  src/feature/sift_test

**Expected behavior**
Get the following output.
`Running 14 test cases...
/home/robot-learning/Projects/ws_Haonan/colmap/src/feature/sift_test.cc(285): error: in "TestCreateSiftGPUMatcherOpenGL": check CreateSiftGPUMatcher(create_options, &sift_match_gpu) has failed
/home/robot-learning/Projects/ws_Haonan/colmap/src/feature/sift_test.cc(300): error: in "TestCreateSiftGPUMatcherCUDA": check CreateSiftGPUMatcher(create_options, &sift_match_gpu) has failed
/home/robot-learning/Projects/ws_Haonan/colmap/src/feature/sift_test.cc(501): error: in "TestMatchSiftFeaturesGPU": check CreateSiftGPUMatcher(create_options, &sift_match_gpu) has failed
terminate called after throwing an instance of 'std::system_error'
  what():  Operation not permitted
unknown location(0): fatal error: in "TestMatchSiftFeaturesGPU": signal: SIGABRT (application abort requested)
/home/robot-learning/Projects/ws_Haonan/colmap/src/feature/sift_test.cc(501): last checkpoint
WARNING: QApplication was not created in the main() thread.

(sift_test:3210969): GLib-CRITICAL **: 16:31:08.077: g_main_context_push_thread_default: assertion 'acquired_context' failed
malloc(): invalid size (unsorted)
terminate called recursively
unknown location(0): fatal error: in "TestMatchSiftFeaturesCPUvsGPU": signal: SIGABRT (application abort requested)
/home/robot-learning/Projects/ws_Haonan/colmap/src/feature/sift_test.cc(559): last checkpoint: "TestMatchSiftFeaturesCPUvsGPU" test entry`

**Screenshots**
![image](https://user-images.githubusercontent.com/16898838/211666775-71f9500e-1e16-4a01-a613-7eb2d6bb118b.png)

**Environment:**
 - OS: Ubuntu 20.04
 - COLMAP Version 3.8
 - CUDA 11.8

**Comment by changhaonan** [comment]
After debug, I feel in src/feature/sift.cc line 1126 should change to `sift_match_gpu->VerifyContextGL() !=0`, otherwise, this checking will never pass when CUDA is enabled.

**Comment by ahojnnes** [comment]
@changhaonan I believe you are right. Should be fixed here: https://github.com/colmap/colmap/pull/1757 Thanks.
