### ISSUE TITLE
can not download Windows version 。always  note need  authority

### ISSUE THREAD

**Issue by epicgzs1112** [colmap/colmap#1755]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Input images and/or output reconstructions are usually helpful.

**Environment:**
 - OS: [e.g. Windows 11]
 - COLMAP Version [e.g. 3.8 or git commit hash]
 - Capture Device [e.g. iPhone X]

**Comment by tsattler** [comment]
Can't replicate this. The pre-release (https://github.com/colmap/colmap/releases) and release (https://github.com/colmap/colmap/releases/tag/3.7) versions download just fine for me.
