### ISSUE TITLE
COLMAP feature_extractor on GCP GPU VM

### ISSUE THREAD

**Issue by dmoham1476** [colmap/colmap#1756]
**Describe the bug**
I am running the following command provided in nvdia instant NERF repo
!python /home/jupyter/instant-ngp/scripts/colmap2nerf.py --video_in /home/jupyter/instant-ngp/data/nerf/chair/IMG_0555.MOV --video_fps 2 --run_colmap --aabb_scale 16

But it fails due to 
==== running: colmap feature_extractor --ImageReader.camera_model OPENCV --ImageReader.camera_params "" --SiftExtraction.estimate_affine_shape=true --SiftExtraction.domain_size_pooling=true --ImageReader.single_camera 1 --database_path colmap.db --image_path "/home/jupyter/instant-ngp/data/nerf/chair/images"
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
FATAL: command failed

I have a V100 GPU VM on GCP cloud with display enabled in the VM.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Input images and/or output reconstructions are usually helpful.

**Environment:**
 - OS: [e.g. Windows 11]
 - COLMAP Version [e.g. 3.8 or git commit hash]
 - Capture Device [e.g. iPhone X]

**Comment by dmoham1476** [comment]
==== running: colmap feature_extractor --ImageReader.camera_model OPENCV --ImageReader.camera_params "" --SiftExtraction.estimate_affine_shape=true --SiftExtraction.domain_size_pooling=true --ImageReader.single_camera 1 --database_path colmap.db --image_path "/home/jupyter/instant-ngp/data/nerf/chair/images"
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.
FATAL: command failed

**Comment by tsattler** [comment]
Colmap tries to create an OpenGL context for feature extraction and this process requires a screen, which you do not seem to have in the VM. There should be multiple issues discussing this in the Colmap repository.
