### ISSUE TITLE
Colmap docker build fail

### ISSUE THREAD

**Issue by thomas-graphopti** [colmap/colmap#1759]
**Environment:**
 - OS: Ubunut 22.04
 - COLMAP Version: latest dev branch
 - Cuda version: 11.7.99
 - Cmake version: 3.25.0
 - GPU: Nvidia RTX 2080Ti
 - Nvidia-smi: 515.86.01
 

**To Reproduce**
1. Git clone colmap from github
2. Switch to latest dev branch
3. cd docker directory
4. build docker image with command "docker build -t colmap . "

**Describe the bug**
It outputs the following fail log:
Your branch is up to date with 'origin/dev'.
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found METIS: /usr/include (found suitable version "5.1.0", minimum required is "5.1.0") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found BLAS: /usr/lib/x86_64-linux-gnu/libblas.so  
-- Found AMD headers in: /usr/include/suitesparse
-- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
-- Found CAMD headers in: /usr/include/suitesparse
-- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
-- Found CCOLAMD headers in: /usr/include/suitesparse
-- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
-- Found CHOLMOD headers in: /usr/include/suitesparse
-- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
-- Found COLAMD headers in: /usr/include/suitesparse
-- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
-- Found SPQR headers in: /usr/include/suitesparse
-- Found SPQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
-- Found Config headers in: /usr/include/suitesparse
-- Found Config library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
-- Did not find Intel TBB library, assuming SuiteSparseQR was not compiled with TBB.
-- Looking for shm_open in rt
-- Looking for shm_open in rt - found
-- Adding librt to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Found METIS: /usr/include (found version "5.1.0") 
-- Looking for cholmod_metis
-- Looking for cholmod_metis - found
-- Found SuiteSparse: /usr/include/suitesparse (found suitable version "5.7.1", minimum required is "5.7.1") found components: AMD CAMD CCOLAMD CHOLMOD COLAMD SPQR Config 
-- Found required Ceres dependency: Eigen version 3.3.7 in /usr/lib/cmake/eigen3
-- Found required Ceres dependency: glog
-- Found required Ceres dependency: gflags
-- Found Ceres version: 2.2.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, SchurSpecializations]
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: program_options filesystem graph system unit_test_framework 
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0") 
-- Found Eigen
--   Includes : /usr/include/eigen3
-- Found FreeImage
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
-- Found Glog
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so   
-- Found Glew
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmp.so  
-- Found MPFR: /usr/lib/x86_64-linux-gnu/libmpfr.so  
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.48")  
-- Boost include dirs: /usr/include
-- Boost libraries:    
-- Using gcc version 4 or later. Adding -frounding-math
-- Found Qt
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Core
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5OpenGL
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets
-- Found CGAL
--   Includes : /usr/include
--   Libraries : CGAL
-- Build type not specified, using Release
-- Enabling SIMD support
-- Enabling OpenMP support
-- Disabling interprocedural optimization
-- Enabling CUDA support (version: 11.6, archs: sm_50)
-- Enabling GUI support
-- Enabling OpenGL support
-- Disabling ccache support
-- Disabling profiling support
-- Enabling CGAL support
-- Configuring done
CMake Error at /usr/share/cmake-3.16/Modules/FindCUDA.cmake:1825 (add_library):
  Target "colmap_cuda" links to target "CUDA::cublas" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  cmake/CMakeHelper.cmake:148 (cuda_add_library)
  src/CMakeLists.txt:82 (COLMAP_ADD_STATIC_CUDA_LIBRARY)

CMake Error at /usr/share/cmake-3.16/Modules/FindCUDA.cmake:1825 (add_library):
  Target "colmap_cuda" links to target "CUDA::cudart" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  cmake/CMakeHelper.cmake:148 (cuda_add_library)
  src/CMakeLists.txt:82 (COLMAP_ADD_STATIC_CUDA_LIBRARY)

CMake Error at /usr/share/cmake-3.16/Modules/FindCUDA.cmake:1825 (add_library):
  Target "colmap_cuda" links to target "CUDA::cusolver" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  cmake/CMakeHelper.cmake:148 (cuda_add_library)
  src/CMakeLists.txt:82 (COLMAP_ADD_STATIC_CUDA_LIBRARY)

CMake Error at /usr/share/cmake-3.16/Modules/FindCUDA.cmake:1825 (add_library):
  Target "colmap_cuda" links to target "CUDA::cusparse" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  cmake/CMakeHelper.cmake:148 (cuda_add_library)
  src/CMakeLists.txt:82 (COLMAP_ADD_STATIC_CUDA_LIBRARY)

CMake Error at cmake/CMakeHelper.cmake:121 (add_library):
  Target "colmap" links to target "CUDA::cublas" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:65 (COLMAP_ADD_STATIC_LIBRARY)

CMake Error at cmake/CMakeHelper.cmake:121 (add_library):
  Target "colmap" links to target "CUDA::cudart" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:65 (COLMAP_ADD_STATIC_LIBRARY)

CMake Error at cmake/CMakeHelper.cmake:121 (add_library):
  Target "colmap" links to target "CUDA::cusolver" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:65 (COLMAP_ADD_STATIC_LIBRARY)

CMake Error at cmake/CMakeHelper.cmake:121 (add_library):
  Target "colmap" links to target "CUDA::cusparse" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:65 (COLMAP_ADD_STATIC_LIBRARY)

CMake Error at cmake/CMakeHelper.cmake:160 (add_executable):
  Target "colmap_exe" links to target "CUDA::cublas" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  src/exe/CMakeLists.txt:38 (COLMAP_ADD_EXECUTABLE)

CMake Error at cmake/CMakeHelper.cmake:160 (add_executable):
  Target "colmap_exe" links to target "CUDA::cudart" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  src/exe/CMakeLists.txt:38 (COLMAP_ADD_EXECUTABLE)

CMake Error at cmake/CMakeHelper.cmake:160 (add_executable):
  Target "colmap_exe" links to target "CUDA::cusolver" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  src/exe/CMakeLists.txt:38 (COLMAP_ADD_EXECUTABLE)

CMake Error at cmake/CMakeHelper.cmake:160 (add_executable):
  Target "colmap_exe" links to target "CUDA::cusparse" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  src/exe/CMakeLists.txt:38 (COLMAP_ADD_EXECUTABLE)

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
The command '/bin/sh -c cd colmap &&     git checkout dev &&     mkdir build &&     cd build &&     cmake .. &&     make -j4 &&     make install' returned a non-zero code: 1

**Potential solution**
 It is probably failed for the cmake version. The nvidia/cuda:11.6.0-devel-ubuntu20.04 image contains the cmake with version 3.16.3, while it seems the latest colmap-dev requires a higher version cmake for compiling with GPU/CUDA. I am not sure is this a universal problem, there are two issues that reports same fail log [#1117](https://github.com/colmap/colmap/issues/1117#issuecomment-778624504) [#1699 ](https://github.com/colmap/colmap/issues/1699#issue-1460996310). There are two potential solutions
1. Update the nvidia/cuda:11.6.0-devel-ubuntu20.04 to nvidia/cuda:11.7.1-devel-ubuntu22.04, that updates both ubuntu and cuda, the cmake version is 3.25.
2. Update the cmake manually with python-pip.

I also suggest add a azure-pipeline for the docker part, it is simple to test with docker. 
I am not sure about the solution here, is there any suggestion? I am willing to create a PR to solve this problem.

**Comment by ahojnnes** [comment]
Thanks for reporting the issue. A fix for the docker config and an additional docker pipeline would be very much appreciated. Thank you!

**Comment by ahojnnes** [comment]
OK, I did the work. There is now a dedicated CI pipeline that validates that the docker image works with the latest code.
