### ISSUE TITLE
commit d5b424203ff exists bug under ubuntu 20.04, cuda 11.5+

### ISSUE THREAD

**Issue by shoeychi** [colmap/colmap#1760]
sift_gpu not match

**Comment by shoeychi** [comment]
ERROR: SiftGPU not fully supported

**Comment by ahojnnes** [comment]
I hope this is fixed in the latest commit in the "dev" branch. Please report back if this works for you again. Thanks.

**Comment by ahojnnes** [comment]
Closing this issue, assuming this was fixed. Please reopen otherwise. Thanks
