### ISSUE TITLE
ERROR: SiftGPU not fully supported

### ISSUE THREAD

**Issue by harshsingh-24** [colmap/colmap#1761]
Hey everyone. I am getting this error when I am trying to run `colmap sequential_matcher --database_path $DATABASE_PATH/database.db` command in Command Line in Ubuntu operating system. Can you please help me figure out the problem? 

```
==============================================================================
Sequential feature matching
==============================================================================

ERROR: SiftGPU not fully supported

```

I have Nvidia tesla V100 on my system and I know that CUDA is enabled because I am able to do other tasks which involved usage of CUDA.

**Comment by ahojnnes** [comment]
I hope this is fixed in the latest commit in the "dev" branch. Please report back if this works for you again. Thanks.

**Comment by ahojnnes** [comment]
OK, I assume the thumbs up means this works again. Thanks. Otherwise please reopen.
