### ISSUE TITLE
Sift GPU is not fully supported

### ISSUE THREAD

**Issue by ShreyashSinha** [colmap/colmap#1767]
### Problem Description
I am facing this issue in the exhaustive feature matching stage when opting for automatic reconstruction while running a given set of images on COLMAP gui.

```
Sift GPU is not fully supported
```

I have built COLMAPv3.8-dev from source for CUDA support

### Environment:

1. OS: Ubuntu 20.04
2. COLMAP version: 3.8-dev
3. GPU: Nvidia GeForce RTX 3070 Ti
4. Capture Device: iPhone 13 Pro Max

PS: It is working with COLMAP v3.7

**Comment by ahojnnes** [comment]
There were some recent fixes in the "dev" branch related to this. Can you try with the latest and report back whether it still doesn't work? Thanks!

**Comment by ahojnnes** [comment]
I assume this is fixed based on the lack of feedback. Please reopen if that is not the case. Thanks.
