### ISSUE TITLE
Do the generated depth maps contain the distance along Z Axis or the Euclidean distance?

### ISSUE THREAD

**Issue by hrflr** [colmap/colmap#1768]
Hello! I want to make sure I am using the depth maps generated in the dense reconstruction step correctly. Searching the docs, scripts and discussions I couldn't find a definitive specification for whether the depth maps contain the distance on the Z axis (yielding values  referred to as Planar Depth or Z-Buffer depth) or the Euclidean distance along the projection ray from the optical center to the 3D point.   

From my experience, I would expect the former case, in which values represent the Z axis distance, but I would appreciate a confirmation. The best discussion I found, which supports this assumption can be found here: https://github.com/colmap/colmap/issues/1476#issuecomment-1235217023_

**Comment by ahojnnes** [comment]
Distance along z axis.

**Comment by hrflr** [comment]
Thank you very much!

**Comment by CriusFission** [comment]
Hi @hrfl, I've been trying to read the depth values in my depth images. I've converted the depth maps from bin files to image files. When I try to read depth values at some pixel locations, I get 3 values other than x and y pixel location. Could you tell me what those might be? I thought the depth values would be a single value.
