### ISSUE TITLE
Build with openGV support

### ISSUE THREAD

**Issue by mandelyoni** [colmap/colmap#1769]
Dear Sir,

Is there an easy way to build Colmap with openGV support (similar to ceres support)? 

Thanks,  Yoni

**Comment by ahojnnes** [comment]
No and there are no plans to support this scenario. Thanks for your question.

**Comment by mandelyoni** [comment]
Can you please explain why? 
Can you please estimate the time it would take me to do the change? 
Thank you

**Comment by mandelyoni** [comment]
Dear sir,

Can you please estimate the time it would take me to do the change?

Thank you for all your hard work!
