### ISSUE TITLE
Reconstruction options for low overlap datasets

### ISSUE THREAD

**Issue by LenaSailor** [colmap/colmap#177]
Hi Johannes

Which reconstruction options should I be paying attention to to improve the probability of convergence for  a relatively small dataset (<100)  where image overlap is limited?

Thanks in advance

Stuart

**Comment by ahojnnes** [comment]
Sparse or dense reconstruction? Or both?

**Comment by LenaSailor** [comment]
Both.

Thanks

**Comment by ahojnnes** [comment]
Use exhaustive matching:
```
SiftMatching.guided_matching=true
Mapper.tri_ignore_two_view_tracks=false
DenseStereo.filter_min_num_consistent 1
DenseFusion.min_num_pixels 3
```

**Comment by LenaSailor** [comment]
Thanks for this
