### ISSUE TITLE
Building script failed, Target "ceres" links to target "SuiteSparse::xxxx" but the target was not found

### ISSUE THREAD

**Issue by user11209** [colmap/colmap#1771]
**Describe the bug**
Building from building script failed, CMake Error occur when `ceres` linking to `SuiteSparse`. Part of the messages are as follows:
```
...
SuiteSparse/UMFPACK/CMakeFiles/umfpack.dir/SourceWrappers/umfpack_zl_report_triplet.o.c.o
[ 99%] Building C object SuiteSparse/UMFPACK/CMakeFiles/umfpack.dir/SourceWrappers/umfpack_zl_save_numeric.o.c.o
...
[ 99%] Building C object SuiteSparse/UMFPACK/CMakeFiles/umfpack.dir/SourceWrappers/umfpack_zl_wsolve.o.c.o
[ 99%] Linking CXX static library ../../lib/libspqr.a
[ 99%] Built target spqr
[100%] Linking C static library ../../lib/libumfpack.a
[100%] Built target umfpack
Install the project...
-- Install configuration: "Release"
-- Installing: /home/zhangjw/colmap/build/__install__/lib/cmake/suitesparse-4.5.0/SuiteSparse-targets.cmake
...
-- Installing: /home/zhangjw/colmap/build/__install__/include/suitesparse/spqrgpu.hpp
-- The C compiler identification is GNU 9.4.0
...
-- Found SuiteSparse 4.5.0, building with SuiteSparse.
-- Found CXSparse: /home/zhangjw/colmap/build/__install__/include/suitesparse (found version "3.1.7")
-- Found CXSparse version: 3.1.7, building with CXSparse.
-- Building without Apple's Accelerate sparse support.
...
CMake Error at internal/ceres/CMakeLists.txt:283 (add_library):
  Target "ceres" links to target "SuiteSparse::CHOLMOD" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at internal/ceres/CMakeLists.txt:283 (add_library):
  Target "ceres" links to target "SuiteSparse::SPQR" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at internal/ceres/CMakeLists.txt:283 (add_library):
  Target "ceres" links to target "SuiteSparse::CHOLMOD" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at internal/ceres/CMakeLists.txt:283 (add_library):
  Target "ceres" links to target "SuiteSparse::SPQR" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
Command failed: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/home/zhangjw/colmap/build/__install__ -DCMAKE_INSTALL_PREFIX=/home/zhangjw/colmap/build/__install__ -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DLAPACK=ON -DSUITESPARSE=ON ..
```

**To Reproduce**
There's problem accessing the internet directly in the server environment, so I downloaded all packages locally and uploaded them.
To reproduce the issue:
1. Download packages according to urls provided in `scripts/python/build.py`, as follows:
```
http://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.zip
http://downloads.sourceforge.net/freeimage/FreeImage3180.zip
https://github.com/nigels-com/glew/releases/download/glew-2.1.0/glew-2.1.0.zip
https://github.com/gflags/gflags/archive/v2.2.2.zip
https://github.com/google/glog/archive/v0.3.5.zip
https://codeload.github.com/jlblancoc/suitesparse-metis-for-windows/zip/7bc503bfa2c4f1be9176147d36daf9e18340780a
https://github.com/ceres-solver/ceres-solver/archive/2.1.0.zip
```
2. Rename `suitesparse-metis-for-windows-7bc503bfa2c4f1be9176147d36daf9e18340780a.zip` to `suite-sparse.zip`
3. `mkdir build` & `mkdir build/__download__` in colmap's root directory
4. Upload all packages from step 1&2 to `build/__download__`
5. Execute `python3 scripts/python/build.py --build_path ./build --colmap_path .` in colmap's root directory

**Expected Behavior**
I noted `SuiteSparse` installed and later found according to the message, but not found when linking to `ceres`. Can't understand why this would happen... 

**Environment:**
 - OS: Ubuntu 20.04
 - COLMAP Version: commit id `5d3b028`, Jan 16. 2023, 5:04 PM GMT+8

**Comment by ahojnnes** [comment]
If you are compiling COLMAP under Ubuntu, then I suggest you don't use the build script but follow the regular build instructions under `doc/install.rst`.

**Comment by jx-99321** [comment]
请问解决了吗？我遇到了相同的问题

**Comment by user11209** [comment]
@jx-99321 没有解决，不过应该可以绕过去。

本地电脑如果是windows很容易就可以安装gui版本的colmap，如果你只需要做sparse重建的话停在这一步就够了，点点鼠标比写命令行方便多了，仅这一步重建速度还是相当快的。

如果你需要借助服务器的GPU做dense重建，可以考虑在ubuntu上直接用apt（还是pip来着，我有点忘了）安装colmap，这是没有gui的colmap，我在尝试的时候没有办法做sparse重建；但是它似乎可以从已有的sparse中间文件开始继续做dense重建，因此你可以试试现在本地电脑上做sparse重建，导出为.bin文件之后再把整个目录传到服务器上做dense重建。

如果你不清楚怎么做，或许可以参考这些：在命令行里的指令参考https://www.cnblogs.com/phillee/p/14335034.html，导出深度图的方法参考https://zhuanlan.zhihu.com/p/584386128。

不过我们最后放弃了这套麻烦到爆的流程，所以以上这些我也不敢保证完全正确，只是做个参考哈。

**Comment by jx-99321** [comment]
@user11209 我们使用的Paddle框架，在ai studio中安装GPU版本的命令行ColMap，其实最简单的就是用apt，但这个需要sudo权限，paddle是不给开发者sudo权限的，只能出此下策，还遇见bug了，难受死

**Comment by jx-99321** [comment]
上面的情况 换个SuiteSparse的版本似乎可以行得通，我的是编译到ColMap出现的ceres问题
