### ISSUE TITLE
Release of colmap 3.8

### ISSUE THREAD

**Issue by Tobias-Fischer** [colmap/colmap#1772]
Hi @ahojnnes, it's been exactly one year since the release of colmap 3.7 (https://github.com/colmap/colmap/issues/1380). Would it be possible to create a new release, please? E.g. pycolmap relies on the latest version on the dev branch rather than an official release. It would also help getting a newer version of colmap on conda-forge (https://github.com/conda-forge/colmap-feedstock/tree/main/recipe) (I am the maintainer of colmap on conda-forge).

Many thanks!

**Comment by ahojnnes** [comment]
Yes, I was planning to do that this month, but there were some issues related to cuda/sift gpu that I wanted to stabilize and also fully validate myself on a local machine before doing that.

**Comment by Tobias-Fischer** [comment]
Thanks @ahojnnes - please let me know if I can help.

**Comment by alexmyczko** [comment]
please notify @me when it happens, debian transition freeze already started, maybe there's still a chance to get it built and in for Debian 12...

**Comment by ahojnnes** [comment]
@alexmyczko @Tobias-Fischer Here you go: https://github.com/colmap/colmap/releases/tag/3.8

**Comment by ahojnnes** [comment]
I'll probably need a few more days to also publish some pre-compiled binaries for Windows/Mac.

**Comment by Tobias-Fischer** [comment]
Awesome thanks a lot!

**Comment by alexmyczko** [comment]
Also thanks! https://buildd.debian.org/status/package.php?p=colmap&suite=sid

**Comment by ahojnnes** [comment]
Thanks to you for maintaining those packages. Much appreciated 🙏

**Comment by Dawars** [comment]
> I'll probably need a few more days to also publish some pre-compiled binaries for Windows/Mac.

Thanks for the great work as always.

Are you still planning to release binaries for Mac?

**Comment by Tobias-Fischer** [comment]
We’ve got them on conda-forge. 

conda install colmap is all you need on Linux/MacOS/Windows :)

**Comment by ahojnnes** [comment]
@Tobias-Fischer Would you mind adding instructions about condo forge installation to the documentation? I wasn't aware of this option and it sounds like a very convenient alternative. Thanks for maintaining the build there.

**Comment by Chamud** [comment]
Has this been fixed for cuda 3.12.5?
I found that the version i have been running in my linux with ```sudo apt install colmap -y``` is 3.7. I was wondering if I should update to 3.8 or latest
