### ISSUE TITLE
Geo-registering succeeded but something went wrong

### ISSUE THREAD

**Issue by Alive59** [colmap/colmap#1784]
Hello, thanks for your great project. I worked everything well in the modules except the geo-registration part. I received the success message but it seems that the program cannot visit some parts of my model. 
Here is what I've received: 

> Converting Alignment Coordinates from GPS (lat/lon/alt) to ECEF.
> 
> Aligning reconstruction to ecef
> -------------------------------
>  => Using 9 reference images
> => Alignment error: 5.782689 (mean), 1.811900 (median)
> => Alignment succeeded
> F0131 17:35:20.767204  4074 reconstruction.cc:2001] Check failed: file.is_open() numazu_station/numazu_station_model_registered/cameras.bin
> *** Check failure stack trace: ***
>     @     0x7f787cfe51c3  google::LogMessage::Fail()
>     @     0x7f787cfea25b  google::LogMessage::SendToLog()
>     @     0x7f787cfe4ebf  google::LogMessage::Flush()
>     @     0x7f787cfe56ef  google::LogMessageFatal::~LogMessageFatal()
>     @     0x55ee5b32ac81  colmap::Reconstruction::WriteCamerasBinary()
>     @     0x55ee5b32b508  colmap::Reconstruction::WriteBinary()
>     @     0x55ee5b275aa4  colmap::RunModelAligner()
>     @     0x55ee5b23c447  main
>     @     0x7f787b768083  __libc_start_main
>     @     0x55ee5b2466ae  _start
> Aborted

Thanks for the help in advance.

**Comment by tsattler** [comment]
It looks like the model_aligner is not able to write to the output file / path.

**Comment by Alive59** [comment]
> 

I got it done. Failed to create the empty folder in advance. It looks like the module would not create it automatically if not detected. 
Thanks!

**Comment by tsattler** [comment]
Good. Can you close the issue?
