### ISSUE TITLE
Creating database.db form manually written cameras.txt, images.txt and points3D.txt

### ISSUE THREAD

**Issue by Zador-Pataki** [colmap/colmap#1786]
Hi, 
I had an existing database with images, poses, camera intrinsics, keypoints and corresponding depth values. From this information, I manually wrote cameras.txt, images.txt and points3D.txt files. How can I write a colmap database.db file?

**Comment by ahojnnes** [comment]
I don't understand the question, as the database.db is the input to the "colmap mapper" while the cameras/images/points3D is its output. They cannot be easily converted from one into another, as they contain mostly different information.
