### ISSUE TITLE
Not able to open colmap.bat on windows

### ISSUE THREAD

**Issue by EricJi150** [colmap/colmap#1787]
I am trying to use the pre-compiled binaries but am running into an issue where I am not able to open up the GUI. I have tried from command terminal and by simply double clicking the file. A screen briefly pops up when double clicking before crashing.

**To Reproduce**
1. First I downloaded the zip file from https://github.com/colmap/colmap/releases
2. I then extracted it to my desktop scripts folder then shell and then double click on colmap.batch
4. No GUI shows up just a quick glimpse of a new window

 - OS: [Windows 10]
 - COLMAP Version [3.8]

**Comment by ahojnnes** [comment]
Can you run the colmap.bat script from the commandline and get back with any console output?

**Comment by dennisfgardner** [comment]
I am having the same problem. Running `.\colmap.bat`  in PowerShell returns "The system cannot find the path specified." 

This makes sense because inside the *.bat file, it's looking for `\bin\colmap` and there is no `bin` folder in the download.

**Comment by dennisfgardner** [comment]
I noticed version 3.7 has 5 assets including windows-cuda.zip. The 3.8 version only has 2 assets: the source files. Looks like the complied binaries are not available at the moment. (note, the 3.7 colmap.bat is working fine and launches the GUI).

**Comment by ahojnnes** [comment]
This is expected. I still have to publish the pre-compiled binaries. You are attempting to the batch script from the source code, which obviously won't work. Please have patience for another day or two until I have the time to upload pre-compiled binaries. Thanks.

**Comment by ahojnnes** [comment]
I uploaded pre-compiled binaries for Windows today. The mac ones are going to take a few more days.
