### ISSUE TITLE
Flann is required to compile

### ISSUE THREAD

**Issue by johnnynunez** [colmap/colmap#1789]
-- Found required Ceres dependency: Eigen version 3.3.9 in //eigen-3.3.9/build
-- Found required Ceres dependency: glog
-- Found Ceres version: 2.2.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SchurSpecializations]
-- Found Boost: /usr/local/include (found version "1.65.1") found components: program_options filesystem graph system unit_test_framework 
-- Found Eigen
--   Includes : //eigen-3.3.9
-- Found FreeImage
--   Includes : /usr/include
--   Libraries : /usr/lib64/libfreeimage.so
CMake Error at cmake/FindFLANN.cmake:91 (message):
  Could not find FLANN
Call Stack (most recent call first):
  CMakeLists.txt:104 (find_package)

-- Configuring incomplete, errors occurred!
See also "/colmap/build/CMakeFiles/CMakeOutput.log".
See also "/colmap/build/CMakeFiles/CMakeError.log".
/io/package/build-wheels-linux.sh: line 131: [: -ne: unary operator expected
++ nproc
+ make -j2 install
make: *** No rule to make target `install'.  Stop.
Error: Process completed with exit code 2.

**Comment by ahojnnes** [comment]
sudo apt install libflann-dev in case you work on a debian based system.

**Comment by tsattler** [comment]
@ahojnnes Wasn't FLANN previously part of the external libraries included with Colmap? This does not seem to be the case anymore. Maybe it makes sense to update the installation instructions to include the installation of FLANN?

**Comment by johnnynunez** [comment]
> sudo apt install libflann-dev in case you work on a debian based system.

this error is on pycolmap that clone this repo

**Comment by johnnynunez** [comment]
> @ahojnnes Wasn't FLANN previously part of the external libraries included with Colmap? This does not seem to be the case anymore. Maybe it makes sense to update the installation instructions to include the installation of FLANN?

Exactly and the https://colmap.github.io/install.html is deprecated. Nowhere is Flann.
The error appears here https://github.com/johnnynunez/pycolmap/actions/runs/4068203695/jobs/7006477711

**Comment by ahojnnes** [comment]
The documentation is updated in the source code here but I didn't get around updating the generated html on the webpage. Thanks, will do that today.

**Comment by johnnynunez** [comment]
> The documentation is updated in the source code here but I didn't get around updating the generated html on the webpage. Thanks, will do that today.

do you have for centos to compile pycolmap that their CI is on centos?

**Comment by johnnynunez** [comment]
> libflann-dev

it's centos 7 from pycolmap
