### ISSUE TITLE
How do mismatches affect geometric structure?

### ISSUE THREAD

**Issue by is03wlei** [colmap/colmap#179]
![m_8995_18794](https://user-images.githubusercontent.com/4695442/28202842-b5f53844-68a9-11e7-9544-fa805652c1c3.png)
Tree matches to grass.

![m_19238_19254](https://user-images.githubusercontent.com/4695442/28202861-c922ac4e-68a9-11e7-9b43-eae549297e94.png)
Car matches to motorcycle.

They are inlier matches already.
Are mismatches going to be filtered in later reconstruction or not?

**Comment by ahojnnes** [comment]
Why are the key points of the matches outside the images? Did you import your own features or matches? There seems to be something wrong. In any case, they will be filtered in the reconstruction stage.

**Comment by is03wlei** [comment]
They are not out of images. I cropped a part of the matches.
I didn't import my own features or matches.

**Comment by ahojnnes** [comment]
Okay, just wanted to make sure. In any case, they should be filtered out in the reconstruction. Closing this, but feel free to reopen if questions remain.
