### ISSUE TITLE
Why is my computer GPU utilization almost 0 when rebuilding in 3D by colmap

### ISSUE THREAD

**Issue by MysteryNull** [colmap/colmap#1793]
Why is my computer GPU utilization almost 0 when rebuilding in 3D by colmap.

**Comment by ahojnnes** [comment]
Only during feature extraction, matching and dense reconstruction, colmap may use the GPU.

**Comment by tsattler** [comment]
The following stages are using the GPU: feature extraction, feature matching, and depth map estimation. All other stages, including the mapping stage, only use the CPU.

**Comment by MysteryNull** [comment]
Thank you for your reply.
