### ISSUE TITLE
Build Failed: building colmap:x64-windows (windows 11, CUDA 12.0)

### ISSUE THREAD

**Issue by monadical** [colmap/colmap#1795]
**Describe the bug**
The vcpkg build procedure, .\vcpkg install colmap[cuda-redist]:x64-windows, fails when run in Windows 11 with CUDA 12.0. The error log is attached. I'm guessing this may be a CUDA version incompatibility, but don't know. I've also filed an issue with vcpkg #29486

**To Reproduce**
Steps to reproduce the behavior (via instructions from https://colmap.github.io/install.html
1. Install vcpkg
2. install colmap (via .\vcpkg install colmap[cuda-redist]:x64-window)
3. See error produced in shell
4. See error in associated log file (install-x64-windows-dbg-out.log)

**Expected behavior**
Should build without errors.

**Environment:**
 - OS: Windows 11
 - COLMAP Version 3.8 dev branch
 - CUDA: 12.0

**Text clipping from PowerShell**
...
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j21
    Working Directory: C:/dev/vcpkg/buildtrees/colmap/x64-windows-dbg
    See logs for more information:
      C:\dev\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:59 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building colmap:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+colmap
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[colmap]+Build+error
Include '[colmap] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 71d3fa60b 2023-02-02 (4 days ago)

Please use the prefilled template from C:\dev\vcpkg\installed\vcpkg\issue_body.md when reporting your issue.

**Text clipping from Error log**
cmd.exe /C "cd /D C:\dev\vcpkg\buildtrees\colmap\x64-windows-dbg\lib\SiftGPU\CMakeFiles\sift_gpu.dir && "C:\Program Files\CMake\bin\cmake.exe" -E make_directory C:/dev/vcpkg/buildtrees/colmap/x64-windows-dbg/lib/SiftGPU/CMakeFiles/sift_gpu.dir//. && "C:\Program Files\CMake\bin\cmake.exe" -D verbose:BOOL=OFF -D build_configuration:STRING=Debug -D generated_file:STRING=C:/dev/vcpkg/buildtrees/colmap/x64-windows-dbg/lib/SiftGPU/CMakeFiles/sift_gpu.dir//./sift_gpu_generated_ProgramCU.cu.obj -D generated_cubin_file:STRING=C:/dev/vcpkg/buildtrees/colmap/x64-windows-dbg/lib/SiftGPU/CMakeFiles/sift_gpu.dir//./sift_gpu_generated_ProgramCU.cu.obj.cubin.txt -P C:/dev/vcpkg/buildtrees/colmap/x64-windows-dbg/lib/SiftGPU/CMakeFiles/sift_gpu.dir//sift_gpu_generated_ProgramCU.cu.obj.Debug.cmake"
ProgramCU.cu
C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(101): error: texture is not a template

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(102): error: texture is not a template

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(103): error: texture is not a template

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(104): error: texture is not a template

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(105): error: texture is not a template

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(106): error: texture is not a template

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(133): error: no instance of overloaded function "tex1Dfetch" matches the argument list
            argument types are: (<error-type>, int)

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(191): error: no instance of overloaded function "tex1Dfetch" matches the argument list
            argument types are: (<error-type>, int)

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(235): error: no instance of overloaded function "tex1Dfetch" matches the argument list
            argument types are: (<error-type>, int)

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(236): error: no instance of overloaded function "tex1Dfetch" matches the argument list
            argument types are: (<error-type>, int)

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(238): error: no instance of overloaded function "tex1Dfetch" matches the argument list
            argument types are: (<error-type>, int)

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(239): error: no instance of overloaded function "tex1Dfetch" matches the argument list
            argument types are: (<error-type>, int)

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(253): error: no instance of overloaded function "tex1Dfetch" matches the argument list
            argument types are: (<error-type>, int)
...

[install-x64-windows-dbg-out.log](https://github.com/colmap/colmap/files/10670918/install-x64-windows-dbg-out.log)

**Comment by ahojnnes** [comment]
There are probably two issues at play: 1. Visual Studio 2022 has abug and fails to compile colmap. Visual Studio 2019 (or msvc tolchain v141) should work. 2. Colmap doesn't compile anymore with cuda version 12 until we find time to replace the deprecated function calls. Version 11.X will work though.

**Comment by monadical** [comment]
Thanks for the update ahojnnes. Is there a pointer to the VS22 bug issue? It's not that hard to make cuda versions switchable. But if I switch to v11 to compile, I wonder if it would then run in v12? If so, then we can live with the deprecated function issues for a while. If not, then fixing is higher priority.

**Comment by ahojnnes** [comment]
The compilation fails due to an internal compiler error and the suggestion is to simplify the code. Resolving that is unfortunately a little bit of a trial and error story. 

Compiling with cuda 11.x requires you to have the same cuda runtime available on that machine. There might be problems for the very latest GPU architectures that are not supported by 11 but by 12.

**Comment by ahojnnes** [comment]
It appears that somebody already reported this as a bug to the Visual Studio compiler team and a bugfix is on its way with an upcoming release.

**Comment by ahojnnes** [comment]
See: https://developercommunity.visualstudio.com/t/Internal-compiler-error-when-install-col/10035653

**Comment by monadical** [comment]
Awesome. Then only CUDA work to do.

**Comment by ahojnnes** [comment]
As of latest commit in the dev branch, one should now be able to compile with cuda 12 again.

**Comment by ahojnnes** [comment]
Please reopen if that doesn't work.

**Comment by citystrawman** [comment]
> There are probably two issues at play: 1. Visual Studio 2022 has abug and fails to compile colmap. Visual Studio 2019 (or msvc tolchain v141) should work. 2. Colmap doesn't compile anymore with cuda version 12 until we find time to replace the deprecated function calls. Version 11.X will work though.

I use visual studio 2019 and cuda 11 but I still have build failed. Not sure how to solve it.
