### ISSUE TITLE
Colmap release 3.8 for windows cuda is missing cudart64_110.dll

### ISSUE THREAD

**Issue by atonalfreerider** [colmap/colmap#1797]
**Describe the bug**
Error when running colmap:
The code execution cannot proceed because cudart64_110.dll was not found. Reinstalling the program may fix this problem

**To Reproduce**
1. Download Colmap release 3.8 for Windows CUDA
2. Extract
3. Add to path (see issue #1796)
4. Run `colmap` from cmd promt, or run COLMAP.bat 

**Expected behavior**
Error will prompt:
The code execution cannot proceed because cudart64_110.dll was not found. Reinstalling the program may fix this problem

**Environment:**
 - OS: Windows 11
 - COLMAP Version 3.8
 - CUDA v12.0

**Workaround**
Copy cudart64_110.dll from Colmap 3.7 lib to Colmap 3.8 lib

**Comment by ahojnnes** [comment]
Thanks, please download the latest zip file. It should be fixed now.
