### ISSUE TITLE
Building from source on Google Colab doesn't work

### ISSUE THREAD

**Issue by mnbucher** [colmap/colmap#1799]
I tried to install Colmap from source on a Google Colab notebook with GPU support. We want to use this for a module next spring semester at ETH and I thought it might be great to run this in Colab as this would be independent on the available hardware and OS from the students. However, I don't manage to get the installation working as I always get the same exception when running CMake with `cmake ..`

```
You must set CMAKE_CUDA_ARCHITECTURES to e.g.  'native', 'all-major', '70'
```

I tried to define the environment variables as following:

```
export CUDA_ARCHITECTURES='native'
export CMAKE_CUDA_ARCHITECTURES='native'
```

No luck so far. I can't find a lot of information on these flag on the web, so I'm not sure how to fix this issue or if it even possible nowadays to install Colmap from source on Google Colab?

Many thanks.

Best,
Martin

**Comment by ahojnnes** [comment]
`cmake .. -DCMAKE_CUDA_ARCHITECTURES=native` doesn't work?

**Comment by mnbucher** [comment]
Using the flag directly with the native attribute gives me the error `nvcc fatal   : Unsupported gpu architecture 'compute_native'`. I just checked on Colab and got a Tesla T4 assigned for my current notebook, reading through the docs gave me the information that this would be `DCMAKE_CUDA_ARCHITECTURES=70`.

However, when running ninja aftewards, I get the following error:

`/usr/local/cuda/include/cuda_runtime_api.h(12843): error: attribute "__host__" does not apply here`

No idea how to fix this... Trying to use the non-GPU version of Colmap on Colab results in another exception during runtime when using the Dense Reconstruction pipeline from the README of pycolmap (something like "dense reconstruction needs CUDA support..."). This is why I'm currently trying to get the CUDA version running on Colab.

Any idea on your side how we could fix this?

**Comment by mihaidusmanu** [comment]
According to [CUDA-Enabled Datacenter Products](https://developer.nvidia.com/cuda-gpus#collapseOne), T4s are 7.5 not 7.0.

With `-DCMAKE_CUDA_ARCHITECTURES=75` it compiles successfully on my end (check notebook linked below).

https://colab.research.google.com/drive/1VduuEyiKzi3KO0jXgTBJRPyKSFHtFF1N

**Comment by mnbucher** [comment]
hi @mihaidusmanu thank you very much for sharing this colab notebook! i just tried that out on my machine and sadly i'm running into the same issue when using the dense reconstruction pipeline of pycolmap:

`ERROR: Dense stereo reconstruction requires CUDA, which is not available on your system.`

i then checked the building of the colmap package and there seems to be a weird error in the middle of the logs:
```

- Configuring done
-- Generating done
-- Build files have been written to: /content/colmap/build
[198/198] Linking CXX executable src/exe/colmap
FAILED: src/exe/colmap 
: && /usr/bin/c++ -Wno-maybe-uninitialized -fopenmp -Wall -std=c++14 -O3 -DNDEBUG -rdynamic src/exe/CMakeFiles/colmap_exe.dir/colmap.cc.o src/exe/CMakeFiles/colmap_exe.dir/database.cc.o src/exe/CMakeFiles/colmap_exe.dir/feature.cc.o src/exe/CMakeFiles/colmap_exe.dir/gui.cc.o src/exe/CMakeFiles/colmap_exe.dir/image.cc.o src/exe/CMakeFiles/colmap_exe.dir/model.cc.o src/exe/CMakeFiles/colmap_exe.dir/mvs.cc.o src/exe/CMakeFiles/colmap_exe.dir/sfm.cc.o src/exe/CMakeFiles/colmap_exe.dir/vocab_tree.cc.o -o src/exe/colmap -L/usr/local/cuda/targets/x86_64-linux/lib -Wl,-rpath,/usr/local/cuda/lib64:  src/libcolmap.a  src/libcolmap_cuda.a  src/libcolmap.a  src/libcolmap_cuda.a  lib/LSD/liblsd.a  lib/PBA/libpba.a  lib/PoissonRecon/libpoisson_recon.a  lib/SiftGPU/libsift_gpu.a  -lGLEW  lib/VLFeat/libvlfeat.a  -ldl  /usr/lib/x86_64-linux-gnu/libboost_filesystem.a  /usr/lib/x86_64-linux-gnu/libboost_program_options.a  /usr/lib/x86_64-linux-gnu/libboost_system.a  -lflann  -llz4  -lfreeimage  -lmetis  /usr/lib/libceres.so.1.14.0  -lglog  /usr/lib/x86_64-linux-gnu/libgflags.so.2.2.2  -lpthread  -lGL  -lGLU  -lsqlite3  /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5.12.8  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.12.8  /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.12.8  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.12.8  -lmpfr  -lgmp  -lpthread  /usr/local/cuda/lib64/libcudart.so  /usr/local/cuda/lib64/libcurand.so  -lcudadevrt  -lcudart_static  -lrt  -lpthread  -ldl && :
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libGL.so: undefined reference to `_glapi_tls_Current'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
[1/2] Install the project...
-- Install configuration: "Release"
```

so it seems that ninja installed something afterwards, although the linker throwed an error?

i installed pycolmap after building colmap, so does pycolmap back up to the CPU-version of colmap if no installation is found? it's weird that pycolmap could be installed without colmap (if the above build actually failed).

could you maybe verify that pycolmap indeed works with CUDA on your side in your colab notebook?

**Comment by mnbucher** [comment]
i could fix the above OpenGL issue in the meantime by using the approach of @yuguangxie [1] in a similar open issue here in the repo. first tried a few approaches with changing the symlinks but [1] seems to do the job on colab for me.

the subsequent installation of `pycolmap` from source solves the missing CUDA bindings, so the dense reconstruction pipeline is now working via colab!

however, as it hasn't been very stable yet i will leave this issue open for a few days and close it as soon as i can reproduce my results for a few other case studies with the same colab notebook. will share a colab template soon here, we could include this in the official REAMDE of this repository, this might help other folks trying to run this on a free GPU from the google cluster.

we're using this for a course in the spring semester starting next week at ETH, so i hope i can reproduce the current workflow!

[1] https://github.com/colmap/colmap/issues/1271#issuecomment-931900582

**Comment by ahojnnes** [comment]
If there is a fix to submit to colmap, please do so, otherwise I assume everything is correct on the colmap side. Thanks.

**Comment by mnbucher** [comment]
all fine so far. installation looked stable across multiple runs on colab with GPU bindings.
