### ISSUE TITLE
feature_extractor.exe error when no display available

### ISSUE THREAD

**Issue by meder411** [colmap/colmap#18]
Hi Johannes,

I am running the executables from the command line on a server with no GUI. Although it doesn't actually open a GUI to run, feature_extractor.exe aborts when a display is not available. I suspect it's the Qt dependency.

Command:
`/usr/local/bin/feature_extractor --General.database_path /playpen/projects/reconstructions/GOPR0297/GOPR0297.db --General.image_path /playpen/projects/data/images/GOPR0297 --ExtractionOptions.camera_model OPENCV --ExtractionOptions.single_camera 1 --ExtractionOptions.camera_params 1194.505955,1194.375495,639.754357,343.475637,-0.274884,0.113541,0.0,0.0`

Error output:
`QXcbConnection: Could not connect to display 
*** Aborted at 1468349147 (unix time) try "date -d @1468349147" if you are using GNU date ***
PC: @     0x7fed4270ec37 (unknown)
*** SIGABRT (@0x2c2000001e7e) received by PID 7806 (TID 0x7fed46db7840) from PID 7806; stack trace: ***
    @     0x7fed461c7330 (unknown)
    @     0x7fed4270ec37 (unknown)
    @     0x7fed42712028 (unknown)
    @     0x7fed45992655 (unknown)
    @     0x7fecc0b3a9f2 (unknown)
    @     0x7fecc0b3c401 (unknown)
    @     0x7fecc0b4bebb (unknown)
    @     0x7fed444353d1 (unknown)
    @     0x7fed4443e73d (unknown)
    @     0x7fed4443f2ed (unknown)
    @     0x7fed45b790d1 (unknown)
    @     0x7fed45b79146 (unknown)
    @     0x7fed44440119 (unknown)
    @     0x7fed45220edd (unknown)
    @           0x4e2037 main
    @     0x7fed426f9f45 (unknown)
    @           0x4e7417 (unknown)
    @                0x0 (unknown)
Aborted (core dumped)
`

For command line runs, is it possible to remove this dependency or catch/suppress this error?

**Comment by ahojnnes** [comment]
Without an attached display colmap cannot use SiftGPU for feature
extraction. Set "--use_gpu=false" as a command line option to use the
CPU version of Sift.

**Comment by meder411** [comment]
I had suspected SiftGPU to be the issue...

Okay, I'll try CPU-only.

**Comment by ahojnnes** [comment]
Closing this issue, reopen if problem still exists.
