### ISSUE TITLE
Possible Bug in Sequential Feature Matching 

### ISSUE THREAD

**Issue by SBCV** [colmap/colmap#180]
Hi Johannes,

when I use sequential feature matching with the latest Colmap version (b44473edb70704c5f82a5dd181015d7c5d767f1e) I observe a strange behaviour. (This also occurs using Colmap 3.0 and 3.1- but not 2.1)
Let's say I have 50 images and use an overlap of 5. 
Examining for example the matches of frame 20 lists the following image_ids: 21, 19, 22, 18, 24, 16, 28, 12, 36, 4. But I would rather expect to see: 21, 19, 22, 18, 23, 17, 24, 16

For image with index i the following neighbours are considered: i+1, i-1, i+2, i-2, i+4, i-4, i+8, i-8 instead of  i+1, i-1, i+2, i-2, i+3, i-3, i+4, i-4
Is this a new intended behaviour?

Best regards
Sebastian

**Comment by SBCV** [comment]
Hi again, 

I just found the corresponding lines (in feature_matching.cc):
    for (int i = 0; i < options_.overlap; ++i) {
      **const size_t image_idx2 = image_idx1 + (1 << i);**
      if (image_idx2 < image_ids.size()) {
        image_pairs.emplace_back(image_id1, image_ids.at(image_idx2));
      } else {
        break;
      }
    }

Regards
Sebastian

**Comment by ahojnnes** [comment]
@SBCV This was an intended feature and not a bug, since I noticed that the matching produces better results in this case. Especially, when the input is a video with small baseline. But I can see that this worsens the results in other cases. Did you see worse results with the new behavior? I will probably add a checkbox ``quadratic`` or similar to enable or disable this behavior.

**Comment by ahojnnes** [comment]
There is now an option to enable/disable this behavior in the ``dev`` branch. By default, the old and new behavior is enabled. See https://github.com/colmap/colmap/commit/d6d2c210c5c692d26328886430cd4207f20526ec

Thanks for the feedback.

**Comment by SBCV** [comment]
Hi,

I had a lot of repeating structures in my video sequence. Thus, a comparison of only the "real" neighbour frames gives better results

**Comment by ahojnnes** [comment]
Okay, thanks for the feedback. You can just disable the ``quadratic_overlap`` option then.
