### ISSUE TITLE
"No good initial image pair found." occurred when I use my own feature method.

### ISSUE THREAD

**Issue by RaneWouters** [colmap/colmap#1804]
I used the LoFTR method in Kornia to extract features, and then stored the matching information in database.db. Then I run `reconstruction -> start reconstruction` to sparse reconstruction in `colmap gui`. However, I did not get the sparse matching result, but the above error occurred. little part of the logs is as follows.

```
Finding good initial image pair
==============================================================================


==============================================================================
Initializing with image pair #10 and #8
==============================================================================


==============================================================================
Global bundle adjustment
==============================================================================

iter      cost      cost_change  |gradient|   |step|    tr_ratio  tr_radius  ls_iter  iter_time  total_time
  0  2.416078e+01    0.00e+00    1.28e+02   0.00e+00   0.00e+00  1.00e+04        0    2.24e-04    5.07e-04
Omitted here
 100  1.830655e+01    3.86e-03    2.95e+02   2.74e+00   4.38e-01  3.06e+05        1    4.35e-04    3.86e-02


Bundle adjustment report
------------------------
    Residuals : 520
   Parameters : 399
   Iterations : 101
         Time : 0.0386581 [s]
 Initial cost : 0.215553 [px]
   Final cost : 0.18763 [px]
  Termination : No convergence

  => Filtered observations: 0
  => Filtered images: 0

==============================================================================
Finding good initial image pair
==============================================================================

  => No good initial image pair found.
```
there are ten pictures in the data set, each of which is 640x480. When I use the SIFT method provided in OpenCV, the system can work normally. When LoFTR method is used, some of the image matching results are as follows:
<img width="1910" alt="image" src="https://user-images.githubusercontent.com/36663582/219255695-a9f2182a-606a-4c76-841f-0aefa1f13d8d.png">
<img width="1909" alt="image" src="https://user-images.githubusercontent.com/36663582/219255942-6b4562d9-caf4-4ef5-8fb2-dd5c1f93c362.png">

Which configuration can I modify to make the system work? BTW, does multiple very close points affect the system operation? Thanks for your help in advance.

**Comment by sunshineywz123** [comment]
> I used the LoFTR method in Kornia to extract features, and then stored the matching information in database.db. Then I run `reconstruction -> start reconstruction` to sparse reconstruction in `colmap gui`. However, I did not get the sparse matching result, but the above error occurred. little part of the logs is as follows.
> 
> ```
> Finding good initial image pair
> ==============================================================================
> 
> 
> ==============================================================================
> Initializing with image pair #10 and #8
> ==============================================================================
> 
> 
> ==============================================================================
> Global bundle adjustment
> ==============================================================================
> 
> iter      cost      cost_change  |gradient|   |step|    tr_ratio  tr_radius  ls_iter  iter_time  total_time
>   0  2.416078e+01    0.00e+00    1.28e+02   0.00e+00   0.00e+00  1.00e+04        0    2.24e-04    5.07e-04
> Omitted here
>  100  1.830655e+01    3.86e-03    2.95e+02   2.74e+00   4.38e-01  3.06e+05        1    4.35e-04    3.86e-02
> 
> 
> Bundle adjustment report
> ------------------------
>     Residuals : 520
>    Parameters : 399
>    Iterations : 101
>          Time : 0.0386581 [s]
>  Initial cost : 0.215553 [px]
>    Final cost : 0.18763 [px]
>   Termination : No convergence
> 
>   => Filtered observations: 0
>   => Filtered images: 0
> 
> ==============================================================================
> Finding good initial image pair
> ==============================================================================
> 
>   => No good initial image pair found.
> ```
> 
> there are ten pictures in the data set, each of which is 640x480. When I use the SIFT method provided in OpenCV, the system can work normally. When LoFTR method is used, some of the image matching results are as follows: <img alt="image" width="1910" src="https://user-images.githubusercontent.com/36663582/219255695-a9f2182a-606a-4c76-841f-0aefa1f13d8d.png"> <img alt="image" width="1909" src="https://user-images.githubusercontent.com/36663582/219255942-6b4562d9-caf4-4ef5-8fb2-dd5c1f93c362.png">
> 
> Which configuration can I modify to make the system work? BTW, does multiple very close points affect the system operation? Thanks for your help in advance.

please help me.I have the same problem.How did you solve this problem?

**Comment by RaneWouters** [comment]
> 

I achieve feature point repeatability by rounding feature points (`round()`), but this is not a long-term solution. I think you can get some inspiration from LoFTR's author's paper on IMC. Similarly, you can also refer to the paper "OnePose++", which optimizes the position of matching points on other images by fixing a point to achieve repeatability of feature points.

**Comment by RaneWouters** [comment]
@sunshineywz123 
I achieve feature point repeatability by rounding feature points (round()), but this is not a long-term solution. I think you can get some inspiration from LoFTR's author's paper on IMC. Similarly, you can also refer to the paper "OnePose++", which optimizes the position of matching points on other images by fixing a point to achieve repeatability of feature points. I hope this will help you.
