### ISSUE TITLE
Rapid Clearing/Resetting the Database

### ISSUE THREAD

**Issue by LenaSailor** [colmap/colmap#181]
Am experimenting with feature extraction tuning and have been attempting to use 'database_creator'.  Have checked the -h but no success and typically get 'ERROR: Failed to parse options unrecognised option 'log_to_stderr''.  Perhaps you could confirm the appropriate syntax.

Thanks

**Comment by LenaSailor** [comment]
Panic over! Have used some simple SQL to clear the database.

Thanks

**Comment by ahojnnes** [comment]
Rapid clearing of the matches or everything including features etc.?

**Comment by LenaSailor** [comment]
Anything you like.  I just wrote some SQL 'Delete' queries, one for each table.  They can be executed separately or as a block.

e.g. In 'DB Browser for SQLLite' , 'Execute SQL tab' 

"DELETE FROM matches" does just that (there are 7 tables)

Let me know if you need any further help on databases.

**Comment by ahojnnes** [comment]
I am familiar with SQL but I just wanted to hear about your use case. Note that your specific command is already implemented in the GUI under database management.

**Comment by LenaSailor** [comment]
Can't see it!  Perhaps you could give me a pointer.

**Comment by ahojnnes** [comment]
Processing > Database management > Clear matches (at the bottom)
