### ISSUE TITLE
Hello,I have the error with nvcc fatal : Unknown option 'fPIC'

### ISSUE THREAD

**Issue by bobododosjl** [colmap/colmap#1813]
sjl@sjl-System-Product-Name:~/GNC/colmap/build$ make -j8
[ 18%] Built target vlfeat
[ 20%] Built target lsd
[ 25%] Built target poisson_recon
[ 32%] Built target sift_gpu
[ 34%] Built target pba
[ 34%] Building CUDA object src/CMakeFiles/colmap_cuda.dir/mvs/gpu_mat_prng.cu.o
[ 34%] Building CUDA object src/CMakeFiles/colmap_cuda.dir/mvs/gpu_mat_ref_image.cu.o
nvcc fatal   : Unknown option 'fPIC'
nvcc fatal   : Unknown option 'fPIC'
[ 34%] Building CUDA object src/CMakeFiles/colmap_cuda.dir/mvs/patch_match_cuda.cu.o
src/CMakeFiles/colmap_cuda.dir/build.make:75: recipe for target 'src/CMakeFiles/colmap_cuda.dir/mvs/gpu_mat_prng.cu.o' failed
make[2]: *** [src/CMakeFiles/colmap_cuda.dir/mvs/gpu_mat_prng.cu.o] Error 1
make[2]: *** 正在等待未完成的任务....
src/CMakeFiles/colmap_cuda.dir/build.make:90: recipe for target 'src/CMakeFiles/colmap_cuda.dir/mvs/gpu_mat_ref_image.cu.o' failed
make[2]: *** [src/CMakeFiles/colmap_cuda.dir/mvs/gpu_mat_ref_image.cu.o] Error 1
nvcc fatal   : Unknown option 'fPIC'
src/CMakeFiles/colmap_cuda.dir/build.make:119: recipe for target 'src/CMakeFiles/colmap_cuda.dir/mvs/patch_match_cuda.cu.o' failed
make[2]: *** [src/CMakeFiles/colmap_cuda.dir/mvs/patch_match_cuda.cu.o] Error 1
CMakeFiles/Makefile2:633: recipe for target 'src/CMakeFiles/colmap_cuda.dir/all' failed
make[1]: *** [src/CMakeFiles/colmap_cuda.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
sjl@sjl-System-Product-Name:

**Comment by mmbannert** [comment]
I faced the same problem. I solved it by installing version 3.25 of CMake. The version that was installed through apt was 3.1x. I shared my Dockerfile that successfully installs CMake here: #1824 . HTH.
