### ISSUE TITLE
Docker build: nvcc fatal : Unsupported gpu architecture 'compute_'

### ISSUE THREAD

**Issue by yanxke** [colmap/colmap#1822]
CMake Error at /usr/share/cmake-3.22/Modules/CMakeDetermineCompilerId.cmake:726 (message):
  Compiling the CUDA compiler identification source file
  "CMakeCUDACompilerId.cu" failed.

  Compiler: /usr/local/cuda/bin/nvcc

  Build flags:

  Id flags: --keep;--keep-dir;tmp;-gencode=arch=compute_,code=sm_ -v

  The output was:

  1

  nvcc fatal : Unsupported gpu architecture 'compute_'

Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/CMakeDetermineCompilerId.cmake:6 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.22/Modules/CMakeDetermineCompilerId.cmake:48 (__determine_compiler_id_test)
  /usr/share/cmake-3.22/Modules/CMakeDetermineCUDACompiler.cmake:298 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:155 (enable_language)

What's strange is that if I change CUDA_ARCHITECTURES=86, it works fine.

**Comment by changh95** [comment]
It seems that the default settings of the Dockerfile 'CUDA_ARCHITECTURES=native' does not work for certain GPUs.
Mine is RTX 3080, with Driver Version: 510.108.03, CUDA Version: 11.6.

I changed the CUDA_ARCHITECTURES=86 in the Dockerfile and it worked as well.

cc: @ahojnnes

**Comment by ahojnnes** [comment]
It depends on your setup, in some cases, you will have to manually supply the correct architecture for your GPU.

**Comment by ahojnnes** [comment]
You can also do it like this: `docker build -t="colmap:latest" --build-arg CUDA_ARCHITECTURES=75 .`
