### ISSUE TITLE
Fusion runs very very slowly

### ISSUE THREAD

**Issue by ShengbinWei** [colmap/colmap#183]
Hi, ahojnnes,
I've built this project by VS2013, win7. And I also download your given pre-built binary executable file v3.1. All the pipeline before fusion runs and performs as same as your binary executable file. However when running "fusion", my project seems stuck. I debug and found this part in StereoFusion::run() in fusion.cc runs very slow:
for all fused_images
    ...;
    for all rows
        for all cols
            fusion_queue.push_back();
            fuse();
        end
    end
end
It takes more than several hours to run over all pixels of each image, and seems become slower and slower. I tried your given binary to runs the same workshop generated by my project, and it takes only 2~3 seconds per image, and the result seems good. Even I set the function StereoFusion::fuse() to be empty, my fusion runs about 7 seconds per image and finally return no fused points with no doubt. My dataset has 36 images with resolution of 1024*768.
So I wonder why this difference comes out?

**Comment by ahojnnes** [comment]
Did you compile in Release or Debug mode?

**Comment by ShengbinWei** [comment]
It's in release mode.

**Comment by ahojnnes** [comment]
Just to make sure, but did you enable release mode in CMake and/or in Visual Studio?

**Comment by ShengbinWei** [comment]
I'm sure its compile in release mode, and the performance of the previous steps are as the same as your pre-build executable.

**Comment by ahojnnes** [comment]
I have no idea why yours is running slower then. I also use VS2013 under Windows 7. Did you install all the latest updates to Visual Studio? I remember that the initial VS2013 versions had many bugs and problems.

**Comment by ahojnnes** [comment]
Closing this as resolved due to lack of feedback. Feel free to reopen.

**Comment by ahojnnes** [comment]
The fusion time of individual images depends on the view overlap with other images. For images where lots of other images see the same structure, it will be very slow but then these other images will be much faster.

**Comment by imnambis** [comment]
> The fusion time of individual images depends on the view overlap with other images. For images where lots of other images see the same structure, it will be very slow but then these other images will be much faster.


Thank you for you reply. I could work around that problem with Vocab Tree (100-1000). However, the final result still was not good.
