### ISSUE TITLE
How to use different camera models in the same database?

### ISSUE THREAD

**Issue by ItaloFan** [colmap/colmap#1832]
I'm reconstructing a combined dataset which includes images with two types of camera models (RADIAL_FISHEYE and SIMPLE_RADIAL), and it seems impossible to me because:
- database must includes all images to be reconstructed
- database is created by the "feature_extractor" commandline
- "feature_extractor" commandline can only specify one kind of camera model by the option "--ImageReader.camera_model"

Do I make some mistakes in the above thinking? Is there anyway to achieve my goal, for example, edit "database.db" file directly?

**Comment by tsattler** [comment]
There are a couple of options:
* If you want to automate things, you can use the `--image_list_path` option to specify a subset of images for which features should be extracted (via image names with path relative to the image path in a text file). This allows you to specify sets of images that should have the same intrinsics by running the feature extractor multiple times with different files and the corresponding intrinsics.
* Modify the database (either per script or in the gui) to create new cameras and assign them to images.

**Comment by ItaloFan** [comment]
I think option one solve my problem perfectly. I didn't try `feature_extractor` on the same database with different image list before. And now it can run sfm properly. Thanks a lot for your kind reply.
