### ISSUE TITLE
image_path in image_registrator

### ISSUE THREAD

**Issue by zw-ruan** [colmap/colmap#184]
Hi,
According to FAQ `Register/localize new images into an existing reconstruction`, `image_registrator` requires the parameter--`image_path`.  Why do we still need images in this step?

**Comment by ahojnnes** [comment]
It is not strictly needed. You can simply pass in a dummy path that doesn't exist. Missing images will only result in a warning.

**Comment by ahojnnes** [comment]
This is fixed in the latest commit in the dev branch. Thanks for reporting.
