### ISSUE TITLE
'std::bad_alloc' when I try to reconstruct sparse/dense model from known camera poses with more than 28 images

### ISSUE THREAD

**Issue by clmforgit** [colmap/colmap#1851]
I tried to reconstruct a model from known camera poses following the FAQ in colmap tutorial.
It was ok when the input image num is less than 28, but when I used 28 or more than 28 images,  error occurred during "colmap image_undistorter" like this:

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
*** Aborted at 1679138245 (unix time) try "date -d @1679138245" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x204d) received by PID 8269 (TID 0x7faa3e6d7000) from PID 8269; stack trace: ***
    @     0x7faa44722046 (unknown)
    @     0x7faa424bf520 (unknown)
    @     0x7faa42513a7c pthread_kill
    @     0x7faa424bf476 raise
    @     0x7faa424a57f3 abort
    @     0x7faa42878bbe (unknown)
    @     0x7faa4288424c (unknown)
    @     0x7faa428842b7 std::terminate()
    @     0x7faa42884518 __cxa_throw
    @     0x55bdef7a7ac4 Eigen::internal::throw_std_bad_alloc()
    @     0x55bdef7ad931 _ZN6colmap14Reconstruction16ReadImagesBinaryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE.cold
    @     0x55bdef8dcc05 colmap::Reconstruction::ReadBinary()
    @     0x55bdef7fec18 colmap::RunImageUndistorter()
    @     0x55bdef7dc603 main
    @     0x7faa424a6d90 (unknown)
    @     0x7faa424a6e40 __libc_start_main
    @     0x55bdef7e3a05 _start

I tried to visualize the generated sparse model after "colmap point_triangulator", using the script "visualize_model.py ",  and got this:

Detected model format: '.bin'
Traceback (most recent call last):
  File "/colmap/scripts/python/visualize_model.py", line 217, in <module>
    main()
  File "/colmap/scripts/python/visualize_model.py", line 203, in main
    model.read_model(args.input_model, ext=args.input_format)
  File "/colmap/scripts/python/visualize_model.py", line 45, in read_model
    self.cameras, self.images, self.points3D = read_model(path, ext)
  File "/colmap/scripts/python/read_write_model.py", line 436, in read_model
    images = read_images_binary(os.path.join(path, "images" + ext))
  File "/colmap/scripts/python/read_write_model.py", line 234, in read_images_binary
    binary_image_properties = read_next_bytes(
  File "/colmap/scripts/python/read_write_model.py", line 82, in read_next_bytes
    return struct.unpack(endian_character + format_char_sequence, data)
struct.error: unpack requires a buffer of 64 bytes

**Environment:**
 - OS: 20.04.1-Ubuntu
 - COLMAP Version 3.8-dev

**Comment by clmforgit** [comment]
It turns out that I forgot to leave an empty line at the end of images.txt

**Comment by XuHu0529** [comment]
Hi, how do you solve the first error during "colmap image_undistorter":

terminate called after throwing an instance of 'std::bad_alloc'
what(): std::bad_alloc
*** Aborted at 1679138245 (unix time) try "date -d @1679138245" if you are using GNU date ***
PC: @ 0x0 (unknown)
*** SIGABRT (@0x204d) received by PID 8269 (TID 0x7faa3e6d7000) from PID 8269; stack trace: ***
@ 0x7faa44722046 (unknown)
@ 0x7faa424bf520 (unknown)
@ 0x7faa42513a7c pthread_kill
@ 0x7faa424bf476 raise
@ 0x7faa424a57f3 abort
@ 0x7faa42878bbe (unknown)
@ 0x7faa4288424c (unknown)
@ 0x7faa428842b7 std::terminate()
@ 0x7faa42884518 __cxa_throw
@ 0x55bdef7a7ac4 Eigen::internal::throw_std_bad_alloc()
@ 0x55bdef7ad931 _ZN6colmap14Reconstruction16ReadImagesBinaryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE.cold
@ 0x55bdef8dcc05 colmap::Reconstruction::ReadBinary()
@ 0x55bdef7fec18 colmap::RunImageUndistorter()
@ 0x55bdef7dc603 main
@ 0x7faa424a6d90 (unknown)
@ 0x7faa424a6e40 __libc_start_main
@ 0x55bdef7e3a05 _start

Thank you very much!
