### ISSUE TITLE
Missing -fPIC in nvcc host compiler.

### ISSUE THREAD

**Issue by bartoszek** [colmap/colmap#186]
Enconture small problem while building _dense_stereo_ on linux `(arch_linux,gcc_7.1,cmake_3.8.1,cuda_8.0,cuda_host_compiler=gcc5_5.4.0)`
linker complains about missing `-fPIC` flag in libmvs.a
```
/usr/bin/ld: ../mvs/libmvs_cuda.a(mvs_cuda_generated_patch_match_cuda.cu.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../mvs/libmvs_cuda.a(mvs_cuda_generated_gpu_mat_prng.cu.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../mvs/libmvs_cuda.a(mvs_cuda_generated_gpu_mat_ref_image.cu.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [src/exe/CMakeFiles/dense_stereo.dir/build.make:163: src/exe/dense_stereo] Błąd 1
make[1]: *** [CMakeFiles/Makefile2:441: src/exe/CMakeFiles/dense_stereo.dir/all] Błąd 2
make[1]: *** Oczekiwanie na niezakończone zadania....
```
Adding `--compiler-options -fPIC` to `CUDA_NVCC_FLAGS` fixes the issue for me.

**Comment by ahojnnes** [comment]
Thanks for the feedback. Did you change anything in CMake or why are you building shared library objects?

**Comment by bartoszek** [comment]
I'm using default arch_linux build environment. The problem maybe related to CMake=3.8 FindCUDA appending -fPIC to CFLAGS globally.

**Comment by ahojnnes** [comment]
Can you check whether adding ``list(APPEND CUDA_NVCC_FLAGS "--compiler-options -fPIC")`` after line 175 in the ``CMakeLists.txt`` file resolves the problem? Thanks!

**Comment by bartoszek** [comment]
Works here.

**Comment by ahojnnes** [comment]
Thanks, fixed in the dev branch now.
