### ISSUE TITLE
Is it possible to calibrate the dense reconstructed model to real-world coordinates?

### ISSUE THREAD

**Issue by Alive59** [colmap/colmap#1864]
If COLMAP includes a model aligner for sparse geo-calibration, is it viable to calibrate every densified point to a global coordinate system?

**Comment by tsattler** [comment]
Why not first geo-register the sparse model before computing the dense reconstruction?

**Comment by Alive59** [comment]
> Why not first geo-register the sparse model before computing the dense reconstruction?

Yes, I've done it of course. but the densified points seem to be under an unknown coordinate system. Is it possible to register them to some global datums?
