### ISSUE TITLE
Check failed: IsPtrSupported(data)

### ISSUE THREAD

**Issue by DiLauro** [colmap/colmap#187]
Hello, first of all: thank you for your amazing work!

I tried a huge dataset (combining flickr, google, bing image results) ~7000 images.
Sparse reconstruction succeeded very well and undistortion for dense model reconstruction worked without any issue. But now I'm stuck to get a dense mesh.
 Everytime I try to use Multi-View Stereo (dense reconstruction) I'm getting this error:

Check failed: IsPtrSupported(data)
bitmap.cc:530 *** Check failure stack trace: ***

I'm using Windows 10 and your pre-built binary.

**Comment by ahojnnes** [comment]
Can you rerun the image undistortion and check again? Maybe there is one image that is corrupted?

**Comment by DiLauro** [comment]
I tried with different models and fewer images, but I got the same errors.

Is it possible that it has problems with images of different sizes?

**Comment by ahojnnes** [comment]
No, this shouldn't be a problem. What surprises me is that you didn't see this error during feature extraction but during dense reconstruction. Can you share the folder with the undistorted images with me? Thanks.

**Comment by DiLauro** [comment]
I've uploaded the full workspace folder:
[workspace](https://we.tl/4xqLCfRjXP)
Thanks for checking

**Comment by ahojnnes** [comment]
Can you share some information about your system (especially, the FreeImage version)? Because I cannot reproduce this issue on my machine.

**Comment by ahojnnes** [comment]
Closing this issue due to lack of feedback, feel free to reopen. Thanks.
