### ISSUE TITLE
Failed to register or localize new images

### ISSUE THREAD

**Issue by samuelyutt** [colmap/colmap#1873]
**Describe the bug**
I want to localize a new image to an exist model. I referred to https://colmap.github.io/faq.html#register-localize-new-images-into-an-existing-reconstruction but still cannot get the pose of the new image.
I am using CLI, so no screen shot is provided. Below is the command I used and the log shown. It seems that the `vocab_tree_matcher` has failed, but I have no idea what I was missing.
```
$ colmap feature_extractor --database_path database.db --image_path db_images/ --image_list_path extra_image_list.txt

==============================================================================
Feature extraction
==============================================================================

Processed file [1/1]
  Name:            e_000120.png
  SKIP: Features for image already extracted.
Elapsed time: 0.000 [minutes]

$ colmap vocab_tree_matcher --database_path database.db

==============================================================================
Vocabulary tree feature matching
==============================================================================

F0406 15:56:53.800261 10662 visual_index.h:551] Check failed: file.is_open() 
*** Check failure stack trace: ***
    @     0x7f164681d5cd  google::LogMessage::Fail()
    @     0x7f164681f433  google::LogMessage::SendToLog()
    @     0x7f164681d15b  google::LogMessage::Flush()
    @     0x7f164681fe1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x683471  colmap::retrieval::VisualIndex<>::Read()
    @           0x746a1f  colmap::VocabTreeFeatureMatcher::Run()
    @           0x87497c  colmap::Thread::RunFunc()
    @     0x7f164382bc80  (unknown)
    @     0x7f1643f086ba  start_thread
    @     0x7f1642d6f51d  clone
    @              (nil)  (unknown)
Aborted (core dumped)

$ colmap image_registrator --database_path database.db --input_path sparse/0/ --output_path sparse/extra/

==============================================================================
Loading database
==============================================================================

Loading cameras... 2 in 0.000s
Loading matches... 8888 in 0.033s
Loading images... 311 in 0.025s (connected 310)
Building correspondence graph... in 0.180s (ignored 0)

Elapsed time: 0.004 [minutes]
```

**To Reproduce**
```
colmap feature_extractor --database_path database.db --image_path db_images/ --image_list_path extra_image_list.txt
colmap vocab_tree_matcher --database_path database.db
colmap image_registrator --database_path database.db --input_path sparse/0/ --output_path sparse/extra/
```

**Expected behavior**
I should find the pose of the newly registered image in images.txt after I extract the new model as text.

**Environment:**
 - OS: Ubuntu 16.06 and Ubuntu 20.04 both tested
 - COLMAP Version 3.6

**Comment by samuelyutt** [comment]
Hi lcmrl,
Thanks for your reply! You are probably right that I shod pass the VocabTreeMatching.vocab_tree_path arg.
Just I forgot to mention that instead of using `vocab_tree_matcher`, I also tried `colmap exhaustive_matcher --database_path database.db`, since `exhaustive_matcher` did not require the extra argument and finished successfully. However, after running `image_registrator`, I am still not able to find the pose of the newly registered image in images.txt after I extract the new model as text.

**Comment by lcmrl** [comment]
If possible check in the new database if the new matches are correct. Eventually here an example with few open source images: https://github.com/lcmrl/colmap_example_image_registrator
1. Initial reconstruction in folder "reconstruction_5_images"
2. Copied the ./reconstruction_5_images/initial_db.db into ./reconstruction_6_images/final_db.db
3. ./reconstruction_6_images/imgs contain all images (also the new one)
4. ./reconstruction_6_images/new_images.txt contains the new image to be added to the reconstruction
5. colmap feature_extractor --database_path ./reconstruction_6_images/final_db.db --image_path ./reconstruction_6_images/imgs --image_list_path ./reconstruction_6_images/new_images.txt
6. colmap vocab_tree_matcher --database_path ./reconstruction_6_images/final_db.db --VocabTreeMatching.vocab_tree_path path_to_vocab_tree
7. colmap image_registrator --database_path ./reconstruction_6_images/final_db.db --input_path ./reconstruction_5_images/initial_sparse --output_path ./reconstruction_6_images/output_path

**Comment by samuelyutt** [comment]
Thank you for your example. My question is how to I get a vocab_tree? Should I build one myself by using `vocab_tree_builder`?
I tried to reproduce your example step by step. I have done the 5th step which is `feature_extractor`. Since step 6 require a vocal tree, I apply `vocab_tree_builder` but result in the following errors.
![image](https://user-images.githubusercontent.com/43903194/230347954-58cbee16-1996-4ef0-b504-d2cc11eabf9e.png)

**Comment by lcmrl** [comment]
You can download from here:
https://demuc.de/colmap/

**Comment by samuelyutt** [comment]
Hi lcmrl,
I really appreciate your help. I have successfully reproduced the result from your repo.
The output after a successfull `image_registrator` was 
![image](https://user-images.githubusercontent.com/43903194/230392005-48f5150b-8758-4f56-b456-33e74c7208f1.png)
However, when I tried the same procedures on my own dataset, the output was
![image](https://user-images.githubusercontent.com/43903194/230392289-7bd9a183-21b8-4955-ac65-006aa5d3d020.png)
where the connected images (364) was less than the loaded images (365), and no `Pose refinement report` was printed as well.
Does this mean `image_registrator` failed on my dataset? Are there any parameters that can be tuned to increase the opportunity for the new image to be registrated?

**Comment by lcmrl** [comment]
Are you sure there is enough overlap between your new image and the older images? Try with extensive matching.
And yes, there are many param you can tune. See ```colmap image_registrator --help```, all the options starting with "Mapper.something". But I think the problem is with the image content because in common scenarios they work fine.

**Comment by samuelyutt** [comment]
Did you mean exhaustive matching? I am sure that the newly added images do have overlap with the older ones.
After some tryings, I believe the problem happens during the matching step. I applied  `exhausted_matcher` and it finishes in about 1 second without any error shown. 
However if 
1. only one new image is added: in GUI `Database management` > select the newly added image > `Overlapping images`, there is no matches shown. 
2. two or more new image are added: in GUI `Database management` > select one of the newly added image > `Overlapping images`, the matches are only between other newly added images.
Therefore I guess the `exhausted_matcher` somehow didn't match the new and old images together (since I am pretty sure they DO have obvious and huge overlap between old and new images)
I'll try to decrease my dataset size and give it a try on more time. And again I pretty much appreciate your response and time.

**Comment by samuelyutt** [comment]
To reproduce my issue, I provided the dataset I'm using.
https://drive.google.com/file/d/1-tPSckONDRjYf4CKzmpLn9EswIRiZidY/view?usp=sharing

**Comment by KleinerE** [comment]
@samuelyutt I'm having exactly the same issue. sadly no response from the devs yet.

**Comment by ahojnnes** [comment]
Are you really on colmap 3.6, as described in the original message? If so, can you please try with the latest version and report whether the bug still exists?

**Comment by samuelyutt** [comment]
Hi ahojnnes,
I have tried again with colmap 3.8 and the problem remains.

**Comment by lcmrl** [comment]
Hi, I've quickly tried converting images to jpeg, it seems to work. Can you check if working with jpeg solves the problem?

**Comment by lcmrl** [comment]
Try with only ten jpeg images, then add one new jpeg. Try to see if it works and the problem is related to png format

**Comment by samuelyutt** [comment]
Hi,
I think I finally realize that the problem is caused by feature extraction, since I found the failure to the matching was because of the features in the newly added image were not enough.
Consequently, since I chose quality `High` for the automatic reconstruction, I reference to the following parameters written in  https://github.com/colmap/colmap/blob/dev/src/util/option_manager.cc and tuned them during the feature extraction and matching process for the new image.
```
void OptionManager::ModifyForHighQuality() {
  sift_extraction->estimate_affine_shape = true;
  sift_extraction->max_image_size = 2400;
  sift_matching->guided_matching = true;
  mapper->ba_local_max_num_iterations = 30;
  mapper->ba_local_max_refinements = 3;
  mapper->ba_global_max_num_iterations = 75;
  patch_match_stereo->max_image_size = 2400;
  stereo_fusion->max_image_size = 2400;
}
```
Eventually, here is the command that succeeded to localize a new image to an exist model.
```
colmap feature_extractor --database_path database.db --image_path images/ --image_list_path new-images-list.txt --SiftExtraction.estimate_affine_shape 1 --SiftExtraction.max_image_size 2400
colmap exhaustive_matcher --database_path database.db --SiftMatching.guided_matching 1
colmap image_registrator --database_path database.db --input_path sparse/0 --output_path sparse/extra/
```
Thankfully, now the features extracted were enough for the matching process, and the new image was able to be added and localized into the model. I pretty much appreciate all of your help.
My advice is that maybe some description about feature extraction and matching that could be helpful for matching and localizing can be considered to be added to the document here: https://colmap.github.io/faq.html#register-localize-new-images-into-an-existing-reconstruction

**Comment by oumsotheara** [comment]
Hi, can I ask some question here.
I try to register new image into the existing model with:
(1) database.db and the cameras.bin, images.bin, points3D.bin obtained from normal construction (the process in gui)
(2) database.db and the 3 bin files obtained from reconstruction with known camera poses.

the images used to build the model is the same, except the origin of the 2 models are different because in (1) colmap creates the origin in the middle of the images, but in (2) the origin of the reconstructed model is in the specified location.

when I register new image with (1) I can obtain the new registered image pose. 
but when I register with (2) I cannot obtain the new image pose.

Does anyone have any idea?
