### ISSUE TITLE
[Installation issue] CMake Warning at cmake/CMakeHelper.cmake:137 (add_executable)

### ISSUE THREAD

**Issue by chen9run** [colmap/colmap#1874]
CMake Warning at cmake/CMakeHelper.cmake:137 (add_executable):
  Cannot generate a safe linker search path for target colmap_exe because
  files in some directories may conflict with libraries in implicit
  directories:

    link library [libcurand.so] in /usr/local/cuda-10.2/lib64 may be hidden by files in:
      /usr/local/cuda-10.2/targets/x86_64-linux/lib/stubs

**Comment by BlarkLee** [comment]
How did you solve this?
