### ISSUE TITLE
Reconstruction fails with the input of 806 images due to out_of_range error.

### ISSUE THREAD

**Issue by myalos** [colmap/colmap#1876]
**Describe the bug**
start reconstruction of colmap gui collapes, and the program report out_of_range error

**To Reproduce**
1. use iphone to capture about 25 seconds video 360-degree around chair(small motion)
2. extract 25 seconds video into 806 photos
3. use colmap gui to extract features and do matching.
4. start reconstruction and program collapse after 90 minutes running.

**Expected behavior**
start reconstruction run successfully.

**Screenshots**
sorry i forget to take screenshot, if needed i can run the program again to reproduce the error.

**Environment:**
 - OS: [ubuntu 20.04]
 - COLMAP Version [3.8]
 - Capture Device [iPhone 11]

**Comment by tsattler** [comment]
Are you running out of memory?

**Comment by myalos** [comment]
I don't know if that's the reason. I run colmap on 1280x720 images with 32G memory and 12G GPU.

**Comment by tsattler** [comment]
Unless your machine is busy with other things, I'd assume that running out of memory is not an issue. Can you show the output?

**Comment by myalos** [comment]
sorry i can't, if i recounter this problem, i will record the information. Thanks for reply !
