### ISSUE TITLE
compile error with make_unique

### ISSUE THREAD

**Issue by XYvven** [colmap/colmap#1878]
**Describe the bug**
I compile this project in ubuntu 20.04 and then I get the error "namespace "std" has no member "make_unique"" and "type name is not allowed"

**this is my cmake out**
![image](https://user-images.githubusercontent.com/30431146/231341204-98e7bab8-787a-4ca2-909a-cf0336fd1c45.png)
![image](https://user-images.githubusercontent.com/30431146/231341295-4f7e23cb-953a-490e-843c-4ed73e2ea39e.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/30431146/231340755-2fed590f-f293-4ca7-8590-76e6ab443485.png)

**Environment:**
 - OS: [Ubuntu 20.04]
 - COLMAP Version [just git clone https://github.com/colmap/colmap.git]

**Comment by chuong98** [comment]
I have the same error with the newest commit

**Comment by simogasp** [comment]
Probably a missing `include <memory>` at the beginning of the `src/colmap/mvs/cuda_texture.h`

**Comment by agxbbx** [comment]
Were you able  to resolve this? Looks like cuda_texture.h was removed

**Comment by lucascassiano** [comment]
I'm encountering the same issue https://github.com/colmap/colmap/issues/2097
Anyone had luck with it?

**Comment by apurvaGodg** [comment]
You need to  specify the CUDA_ARCHITECTURES CMake variable when you run CMake. For example, to compile COLMAP with support for CUDA architecture 7.5, you would update the following command:

cmake .. -GNinja -DCMAKE_CUDA_ARCHITECTURES=75

Reboot your system once you follow all the remaining  steps. That worked for me.

**Comment by AmandineBtto** [comment]
Hello, 
I encountered the same issue in ubuntu 20.04 LTS with cuda 11.8 and colmap 3.8dev.

It seems that "make_unique" is available only for c++14 and above. In the cmake list it is specified to use c++14 but nvcc (cuda) is compiling in c++11. You can see that in the error message '-std=c++11'.

So the fix I found is to: 
1. Run the cmake command. For instance 'cmake .. -GNinja -D CMAKE_CUDA_ARCHITECTURES=native'. 
2. And then, find the 'build.ninja' file. It was generated by the previous command.
3. In this file replace all c++11 by c++14. 
4. Run ninja again and it should compile. 

I don't know if there is a cleaner way to fix the issue but it worked for me.

**Comment by ahojnnes** [comment]
The latest commit in the dev branch hopefully mitigates this issue. Thanks.
