### ISSUE TITLE
Undefined reference to libtiff4.0 on compile (Ubuntu 16.04)

### ISSUE THREAD

**Issue by toddnguyen** [colmap/colmap#188]
I have all the dependencies installed on Ubuntu 16.04 (cmake, build-essential, libboost-all-dev,  libeigen3-dev, libsuitesparse-dev, libfreeimage-dev, libgoogle-glog-dev, libgflags-dev, libglew-dev,  qt5-default, and ceres solver.

When I run 'make -j' in the build folder, I get this error and a few more repeated instances of this undefined reference.

Does anyone know of a solution? I found this thread:
[https://groups.google.com/forum/#!topic/colmap/Fjo3kQIpd_U](https://groups.google.com/forum/#!topic/colmap/Fjo3kQIpd_U
)
but no solution was suggested.

Thanks!

```
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFReadEncodedStrip@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFReadEXIFDirectory@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFFieldReadCount@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFSetTagExtender@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFCurrentDirectory@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFReadTile@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFSetDirectory@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFClientOpen@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFSetField@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFScanlineSize@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFWriteDirectory@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFTileRowSize@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFWriteScanline@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFGetFieldDefaulted@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFReadDirectory@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFIsTiled@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFFieldDataType@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFSwabArrayOfLong@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFMergeFieldInfo@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFLastDirectory@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `_TIFFDataSize@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFSetSubDirectory@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFFieldPassCount@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFFieldWithTag@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFReadRGBAImage@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFClose@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFGetTagListCount@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFDefaultStripSize@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFFieldTag@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFGetTagListEntry@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFComputeStrip@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFDataWidth@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFFieldName@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFIsByteSwapped@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFGetField@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFTileSize@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFStripSize@LIBTIFF_4.0'
collect2: error: ld returned 1 exit status
src/mvs/CMakeFiles/normal_map_test.dir/build.make:163: recipe for target 'src/mvs/normal_map_test' failed
make[2]: *** [src/mvs/normal_map_test] Error 1
```

**Comment by ahojnnes** [comment]
Do you have Anaconda installed? Or is there anything else added to your LD_LIBRARY_PATH that is not standard? I suspect you pull in some external libraries for building COLMAP.

**Comment by ahojnnes** [comment]
Closing this as resolved due to lack of feedback. Feel free to reopen.

**Comment by amonszpart** [comment]
I have a similar problem (empty LD_LIBRARY_PATH). Could it be an Ubuntu problem, the libfreeimage package was built with an older libtiff (e.g. v4) than what's installed with the libtiff5-dev package (e.g. v5)

**Comment by SBCV** [comment]
In my case colmap was automatically using qt5.6 in the anaconda3 paths. 
By manually installing qt5.7 following [http://wiki.qt.io/Install_Qt_5_on_Ubuntu](http://wiki.qt.io/Install_Qt_5_on_Ubuntu) for Ubuntu 14.04 and adjusting the paths the libfreeimage linking errors disappeared

**Comment by RuibinMa** [comment]
@SBCV Thanks for the solution. Do you know how to install Qt5.7 directly into the /usr directory? The approach in your link only installs qt into a self-contained folder in my home directory. To that end, I need to edit the cmake flags and also LD_LIBRARY_PATH. Although succeeded compiling colmap in this way, I'm still wondering whether there's a cleaner solution that can directly install Qt5.7 to the system directory. Thank you!

**Comment by dantkz** [comment]
A solution that worked for me is to do the installation with a terminal instance without anaconda defined in the path:
1. comment out anaconda path in ~/.bashrc:
`#export PATH="/home/daniyar/anaconda3/bin:$PATH"`
2. start a new terminal and proceed installation with 
`cmake ..` or `CC=/usr/bin/gcc-6 CXX=/usr/bin/g++-6 cmake ..`
3. put back anaconda path in ~/.bashrc:
`export PATH="/home/daniyar/anaconda3/bin:$PATH"`

In fact, running `cmake ..` with anaconda in the path throws a warnings like:
``runtime library [libGLU.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in: /home/daniyar/anaconda3/lib`

A solution to a similar link error with undefined references was suggested here: https://github.com/lagadic/visp/issues/109

**Comment by anubhavashok** [comment]
Tried all of the above what finally worked for me was 

```
conda uninstall libtiff
```

**Comment by shamangary** [comment]
@anubhavashok you save me

**Comment by silence401** [comment]
> Tried all of the above what finally worked for me was
> 
> ```
> conda uninstall libtiff
> ```

haha,thank you ,this problem realy confuse me.But you solution works ok  to me.

**Comment by bigeyesung** [comment]
> A solution that worked for me is to do the installation with a terminal instance without anaconda defined in the path:
> 
> 1. comment out anaconda path in ~/.bashrc:
>    `#export PATH="/home/daniyar/anaconda3/bin:$PATH"`
> 2. start a new terminal and proceed installation with
>    `cmake ..` or `CC=/usr/bin/gcc-6 CXX=/usr/bin/g++-6 cmake ..`
> 3. put back anaconda path in ~/.bashrc:
>    `export PATH="/home/daniyar/anaconda3/bin:$PATH"`
> 
> In fact, running `cmake ..` with anaconda in the path throws a warnings like:
> ``runtime library [libGLU.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in: /home/daniyar/anaconda3/lib`
> 
> A solution to a similar link error with undefined references was suggested here: [lagadic/visp#109](https://github.com/lagadic/visp/issues/109)

This works for me. Thanks.

**Comment by sunpeng981712364** [comment]
> Tried all of the above what finally worked for me was
> 
> ```
> conda uninstall libtiff
> ```
it works

**Comment by SwayKing** [comment]
> Tried all of the above what finally worked for me was
> 
> ```
> conda uninstall libtiff
> ```

Thank you so much.

**Comment by Vincentqyw** [comment]
The following solution works for me:
add the following lines in `CMakeLists.txt`
``` cmake
find_package( TIFF REQUIRED )
if ( TIFF_FOUND )
    include_directories( ${TIFF_INCLUDE_DIRS} )
    list(APPEND COLMAP_EXTERNAL_LIBRARIES ${TIFF_LIBRARIES})
endif( TIFF_FOUND )
```

**Comment by Abraham423** [comment]
> Tried all of the above what finally worked for me was
> 
> ```
> conda uninstall libtiff
> ```

Thx, you've saved my day

**Comment by darthgera123** [comment]
> Tried all of the above what finally worked for me was
> 
> ```
> conda uninstall libtiff
> ```

Thanks this worked like a charm

**Comment by xuus** [comment]
thanks @dantkz & @ktw361 so much, my problem is solved.
I am very grateful to you.


> A solution that worked for me is to do the installation with a terminal instance without anaconda defined in the path:
> 
> 1. comment out anaconda path in ~/.bashrc:
>    `#export PATH="/home/daniyar/anaconda3/bin:$PATH"`
> 2. start a new terminal and proceed installation with
>    `cmake ..` or `CC=/usr/bin/gcc-6 CXX=/usr/bin/g++-6 cmake ..`
> 3. put back anaconda path in ~/.bashrc:
>    `export PATH="/home/daniyar/anaconda3/bin:$PATH"`
> 
> In fact, running `cmake ..` with anaconda in the path throws a warnings like:
> ``runtime library [libGLU.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in: /home/daniyar/anaconda3/lib`
> 
> A solution to a similar link error with undefined references was suggested here: [lagadic/visp#109](https://github.com/lagadic/visp/issues/109)

**Comment by Elena-ssq** [comment]
> A solution that worked for me is to do the installation with a terminal instance without anaconda defined in the path:
> 
> 1. comment out anaconda path in ~/.bashrc:
>    `#export PATH="/home/daniyar/anaconda3/bin:$PATH"`
> 2. start a new terminal and proceed installation with
>    `cmake ..` or `CC=/usr/bin/gcc-6 CXX=/usr/bin/g++-6 cmake ..`
> 3. put back anaconda path in ~/.bashrc:
>    `export PATH="/home/daniyar/anaconda3/bin:$PATH"`
> 
> In fact, running `cmake ..` with anaconda in the path throws a warnings like:
> ``runtime library [libGLU.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in: /home/daniyar/anaconda3/lib`
> 
> A solution to a similar link error with undefined references was suggested here: [lagadic/visp#109](https://github.com/lagadic/visp/issues/109)

Thank you soooo much! This saved my day.
Just in case it helps:
Mine environment is Ubuntu16.04+cuda10.0+boost1.58+gcc-6
I solved the problem by seccessively doing:
1. comment out: #export PATH="/home/daniyar/anaconda3/bin:$PATH"
2. CC=/usr/bin/gcc-6 CXX=/usr/bin/g++-6 cmake -DBOOST_STATIC=OFF ..
3. make -j8
4. put back: export PATH="/home/daniyar/anaconda3/bin:$PATH"

**Comment by MoisesFelipe** [comment]
> 

No idea why, but that works beautifully. Thanks.

**Comment by ww-Jingle** [comment]
> > Tried all of the above what finally worked for me was
> > ```
> > conda uninstall libtiff
> > ```
> 
> it works

Tried lots of method! This works!

**Comment by githubwys** [comment]
> Thanks to @SBCV , I read my cmake output again carefully, and I realized that the error was due to incorrect Qt path found by cmake. The message it looks like this: ![ss](https://user-images.githubusercontent.com/23008175/49992426-05721880-ffbf-11e8-8e9e-64b9bf0f5e41.jpg)
> 
> In the circled part, cmake uses the Qt in anaconda directory, which suggest why I got the warnings mentioned by @dantkz : `runtime library [libgmp.so.10] in /usr/lib/x86_64-linux-gnu may be hidden by files in: /home/damon/anaconda2/lib`
> 
> So, I **added one line to `CMakeLists.txt` in top directory(in colmap folder), ` SET(CMAKE_PREFIX_PATH "/usr/lib/x86_64-linux-gnu/cmake")`** this forces cmake to use system's Qt. Then run `cmake ..` in build folder, warnings was gone, and `make` was fine after that.


it works !

also , remove conda pkg "conda uninstall libtiff " may disturb the conda env . i didnot try it.

**Comment by reyanshsolis** [comment]
> Tried all of the above what finally worked for me was
> 
> ```
> conda uninstall libtiff
> ```
works for me too! Thanks.

**Comment by SBCV** [comment]
I think if you run 
```
conda deactivate
cmake <some options>
``` 
it will build correctly - without the need to uninstall `libtiff`.

Make sure that you have removed all files generated by any previous cmake run

**Comment by wlc123** [comment]
I got a simple way, just `mv ~/anaconda3/lib/libtiff* $your_tmp_path`

**Comment by WiiliamC** [comment]
> Tried all of the above what finally worked for me was
> 
> ```
> conda uninstall libtiff
> ```

life saver!!

**Comment by DaddyWesker** [comment]
Well, i've already tried to disable anaconda in bashrc and re-source it, i've tried to `conda uninstall libtiff` and none of my envs have this libtiff installed. Nothing helped me with this strange 
`libfreeimage.so: undefined reference to TIFF...`

**Comment by RPFey** [comment]
I have a question.

`ldd /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libfreeimage.so` gives the following result:

```text
libtiff.so.5 => /lib/x86_64-linux-gnu/libtiff.so.5 (0x00007f8f2668b000)
```

and `objdump -tT /lib/x86_64-linux-gnu/libtiff.so.5 | grep TIFFTileRowSize` gives that

```text
0000000000047740 g    DF .text  0000000000000134  LIBTIFF_4.0 TIFFTileRowSize64
0000000000047880 g    DF .text  0000000000000020  LIBTIFF_4.0 TIFFTileRowSize
```

It seems that `TIFFTileRowSize@LIBTIFF_4.0` is defined in `/lib/x86_64-linux-gnu/libtiff.so.5` which was linked by `libfreeimage.so`. Why does it still show that `TIFFTileRowSize@LIBTIFF_4.0` is not defined in the build process

**Comment by perseverance123** [comment]
The following solution works for me (others won't work):

1. list out the dynamic dependency lib of libfreeimage.so:

 `ldd /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libfreeimage.so`

2. check soft link related to libtiff.so

![image](https://user-images.githubusercontent.com/33694969/224233609-0d422f2e-68bc-4850-b3d8-d2894128dda0.png)

3. replace it with:

```
sudo rm /usr/local/lib/libtiff.so.5
sudo ln -s /usr/lib/x86_64-linux-gnu/libtiff.so.5.5.0 /usr/local/lib/libtiff.so.5
``` 

4. then rebuild the colmap

It finally worked :) thx to this [blog](https://blog.csdn.net/Fucking_Code0916/article/details/121713303) !!!

**Comment by shuiyuejihua** [comment]
`sudo apt install colmap` 
works for me , ubuntu 18.04

**Comment by spicy-dog** [comment]
> Tried all of the above what finally worked for me was
> 
> ```
> conda uninstall libtiff
> ```

save me!!

**Comment by Thomas333333** [comment]
> The following solution works for me (others won't work):
> 
> 1. list out the dynamic dependency lib of libfreeimage.so:
> 
> `ldd /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libfreeimage.so`
> 
> 2. check soft link related to libtiff.so
> 
> ![image](https://user-images.githubusercontent.com/33694969/224233609-0d422f2e-68bc-4850-b3d8-d2894128dda0.png)
> 
> 3. replace it with:
> 
> ```
> sudo rm /usr/local/lib/libtiff.so.5
> sudo ln -s /usr/lib/x86_64-linux-gnu/libtiff.so.5.5.0 /usr/local/lib/libtiff.so.5
> ```
> 
> 4. then rebuild the colmap
> 
> It finally worked :) thx to this [blog](https://blog.csdn.net/Fucking_Code0916/article/details/121713303) !!!

It works！

**Comment by doubleZ0108** [comment]
> The following solution works for me (others won't work):
> 
> 1. list out the dynamic dependency lib of libfreeimage.so:
> 
> `ldd /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libfreeimage.so`
> 
> 2. check soft link related to libtiff.so
> 
> ![image](https://user-images.githubusercontent.com/33694969/224233609-0d422f2e-68bc-4850-b3d8-d2894128dda0.png)
> 
> 3. replace it with:
> 
> ```
> sudo rm /usr/local/lib/libtiff.so.5
> sudo ln -s /usr/lib/x86_64-linux-gnu/libtiff.so.5.5.0 /usr/local/lib/libtiff.so.5
> ```
> 
> 4. then rebuild the colmap
> 
> It finally worked :) thx to this [blog](https://blog.csdn.net/Fucking_Code0916/article/details/121713303) !!!

I have tried every methods above, but you save me finally.
Many thanks!!!

<img width="1134" alt="image" src="https://github.com/colmap/colmap/assets/39005525/9f1d77c4-933f-4eba-bee4-2c5df0852634">

**Comment by everRoc** [comment]
您好，您的邮件我已经收到了，谢谢

**Comment by dsvilarkovic** [comment]
Every time I reinstall colmap, I first waste 2 days before arriving to resolving this same issue with conda uninstall libtiff

**Comment by OrangeJuice3211** [comment]
> Tried all of the above what finally worked for me was
> 
> ```
> conda uninstall libtiff
> ```

you are my GOD！it works！

**Comment by everRoc** [comment]
您好，您的邮件我已经收到了，谢谢

**Comment by amughrabi** [comment]
This works for me:
```
export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:/usr/lib/x86_64-linux-gnu
```

**Comment by lakillsama** [comment]
> Tried all of the above what finally worked for me was
> 
> ```
> conda uninstall libtiff
> ```

you save me!!!!!

**Comment by everRoc** [comment]
您好，您的邮件我已经收到了，谢谢
