### ISSUE TITLE
Failure in the Spatial matcher

### ISSUE THREAD

**Issue by Alive59** [colmap/colmap#1888]
I tried to compile spatial matcher manually using the C++ library. However it seemed the cache setup failed. 

Here is what I received:

==============================================================================
Spatial feature matching
==============================================================================

F20230419 23:09:21.588981 34807811 cache.h:132] Check failed: max_num_elems > 0 (0 vs. 0) 
*** Check failure stack trace: ***
    @        0x10a14dbfb  google::LogMessage::Flush()
    @        0x10a15120d  google::LogMessageFatal::~LogMessageFatal()
    @        0x10a14e627  google::LogMessageFatal::~LogMessageFatal()
    @        0x1004c1a5f  colmap::LRUCache<>::LRUCache()
    @        0x10049452e  colmap::FeatureMatcherCache::Setup()
    @        0x1004a2b0d  colmap::SpatialFeatureMatcher::Run()
    @        0x10067f6dd  colmap::Thread::RunFunc()
    @        0x100681a9e  std::__1::__thread_proxy<>()
    @        0x1181d0c0d  _pthread_start
    

Here is the code part: 
```
*options.sift_matching = sift_matcher_options;
*options.spatial_matching = sift_spatial_matcher_options;
matcher matcher(*options.spatial_matching, *options.sift_matching, *options.database_path);
    
matcher.Start();
matcher.Wait();

matcher.Stop();
```

Can anyone figure out it?

**Comment by tsattler** [comment]
It seems that the cache is empty.

**Comment by Alive59** [comment]
> It seems that the cache is empty.

I thought the cache has been created automatically in the matcher object. So should I create it manually?

**Comment by tsattler** [comment]
This is the function that is called prior to the crash: https://github.com/colmap/colmap/blob/dev/src/feature/matching.cc#L221-L256

One of the `std::make_unique<LRUCache<` calls is causing problems as the first constructor element is 0. Unless you set the cache size to 0, I'd assume that one of these two calls causes problems: https://github.com/colmap/colmap/blob/dev/src/feature/matching.cc#L247-L255 Does your database contain images with keypoints?

**Comment by Alive59** [comment]
> This is the function that is called prior to the crash: https://github.com/colmap/colmap/blob/dev/src/feature/matching.cc#L221-L256
> 
> One of the `std::make_unique<LRUCache<` calls is causing problems as the first constructor element is 0. Unless you set the cache size to 0, I'd assume that one of these two calls causes problems: https://github.com/colmap/colmap/blob/dev/src/feature/matching.cc#L247-L255 Does your database contain images with keypoints?

Yes. I checked the number of keypoints and descriptors, both of them are not zero. Should I set the database object manually to the matcher?

**Comment by Alive59** [comment]
Well, I should have found out that the database was not successfully read by the constructor, since all the values are null in the object. 
<img width="1225" alt="Screen Shot 2023-04-21 at 15 53 05" src="https://user-images.githubusercontent.com/64267960/233562736-2f8f2dd3-b4ac-4a1a-a7eb-e76b9fcdd5d8.png">

Maybe I should figure out the reason first.
