### ISSUE TITLE
Crash on Windows 11

### ISSUE THREAD

**Issue by yoanyoo** [colmap/colmap#1889]
Hello, I am trying to run a data process of a couple of images for nerfstudio and it keeps crashing when it runs colmap feature gather. I tried with cuda and without cuda and nothing works, colmap just crashes. If anyone can give any tips that would be great!
Here is the line that is explaining the error: 
Error running command: colmap vocab_tree_matcher --database_path shoe\output\colmap\database.db --SiftMatching.use_gpu 1
--VocabTreeMatching.vocab_tree_path C:\Users\Yoan A\AppData\Local\nerfstudio\nerfstudio\vocab_tree.fbow
**Environment:**
 - Windows 11
 - COLMAP CUDA

**Comment by tsattler** [comment]
Best guess without seeing the error message: the " " in the vocab_tree_path causes problems.

**Comment by yoanyoo** [comment]
@tsattler what do you mean exactly with the " "? I am sorry, I am not very technical.

**Comment by tsattler** [comment]
Your user name ("Yoan A") contains a blank space and Colmap likely thinks that the file path is "C:\Users\Yoan". Try writing the path as 'C:\Users\Yoan A\AppData\Local\nerfstudio\nerfstudio\vocab_tree.fbow'.

**Comment by yoanyoo** [comment]
@tsattler hello, thank you so much for the tip, it is just that I am not sure where and how should I write the path.

**Comment by tsattler** [comment]
Did you try using 'C:\Users\Yoan A\AppData\Local\nerfstudio\nerfstudio\vocab_tree.fbow' instead of C:\Users\Yoan A\AppData\Local\nerfstudio\nerfstudio\vocab_tree.fbow in the call to colmap you showed above?
