### ISSUE TITLE
dense_stereo crash gpu driver

### ISSUE THREAD

**Issue by eggnot** [colmap/colmap#189]
with image size > 800px (or so) dense_stereo force videodriver to restart with a crash.
videomemory just before a crash as low as 300mb(of 2gb)

latest dev-windows on win7-64, gtx1050

![2017-07-29_17-00-09](https://user-images.githubusercontent.com/5466961/28743901-8c220cd6-747f-11e7-8f70-5c227592b518.png)

**Comment by ahojnnes** [comment]
Please refer to https://colmap.github.io/faq.html#reduce-memory-usage-during-dense-reconstruction and https://colmap.github.io/faq.html#fix-gpu-freezes-and-timeouts-during-dense-reconstruction on how to fix this issue. Thanks for the feedback.

**Comment by eggnot** [comment]
sorry, stupid me. was too focused on memory\driver issues...
`Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers]
"TdrLevel"=dword:00000001
"TdrDelay"=dword:00000030
`
worked for me.

thanks for great set of tools, anyway!
