### ISSUE TITLE
Scaling two separate models from known distance in one model

### ISSUE THREAD

**Issue by mc-barbour** [colmap/colmap#1897]
Hi. I'm using COLMAP to perform reconstructions from clinical endoscopy videos. The camera is the same in all images. The process generally works quite well except it is often difficult to get a single model from my image database. The lighting in one section of the video becomes quite poor and I often lose overlap between the reconstructed models. 

One model contains an object with a known 3D world dimension that I can use to scale that model to world coordinates. I'm wondering if there is any way to enforce this scaling on the second model which uses the same camera. The object does not appear in the second reconstruction.

I understand that the model scale is arbitrary and computed from the first images in that specific reconstruction. Is there any way to calculate the scaling used between two separate models if I only have world dimensions in one of the models?

**Comment by tsattler** [comment]
This is not possible. You need to know distances in the part of the scene that is contained in the second 3D model.

**Comment by mc-barbour** [comment]
Okay, thanks.
