### ISSUE TITLE
Fills up memory on feature extraction

### ISSUE THREAD

**Issue by ckochipm** [colmap/colmap#190]
I'm using COLMAP on CPU only on Ubuntu 16.04. I tried to open a dataset of 370 images, 12 MP each. In the feature extraction step the program just fills up memory completely with about 10 images and then crashes. Is there any way to limit the memory used? Shouldn't the feature descriptor data be saved in the database file on disk and the system memory be freed automatically?

**Comment by ahojnnes** [comment]
Reduce the number of threads from -1 to e.g. 1?

**Comment by ahojnnes** [comment]
The memory usage should be much reduced with the latest commit in the dev branch. If this still doesn't fix your issue, the only fix is to reduce the number of threads. Thanks for the feedback!
