### ISSUE TITLE
Pause/resume for sfm(mapper)

### ISSUE THREAD

**Issue by f1shel** [colmap/colmap#1900]
Will sfm(Mapper, in command line mode) store some intermediate results so that one can resume it after pause/interupt it? I notice that patch match MVS will store binary normal maps and depth maps for every single view, so I can stop and restart at any time. Does sfm have something similar to dense reconstruction?

**Comment by tsattler** [comment]
There is a command line flag for writing out intermediate results once a certain number of 3D points / images have been added.

**Comment by f1shel** [comment]
> There is a command line flag for writing out intermediate results once a certain number of 3D points / images have been added.

Really thanks! Also I found there actually exists a closed issue https://github.com/colmap/colmap/issues/1228, which solves my problem.
