### ISSUE TITLE
Dense stereo reconstruction requires CUDA, which is not available on your system

### ISSUE THREAD

**Issue by yanjiaqi03** [colmap/colmap#1905]
I use colmap to 3D reconstruction by Cpu-Mode(docker), but it throws the Error 'Dense stereo reconstruction requires CUDA, which is not available on your system' in patch_match_stereo step.  I refer to 'Available functionality without GPU/CUDA', but not work. So how can I fix it and execute follow up works(e.g stereo_fusion) ? Thanks !

**Comment by tsattler** [comment]
patch_match_stereo requires CUDA, i.e., you need to use a version of Colmap that was compiled with CUDA support and your system needs to have an NVidia GPU that supports the required CUDA version.
