### ISSUE TITLE
Build Colmap (cuda) on Windows size difference

### ISSUE THREAD

**Issue by nearshore-macedonia** [colmap/colmap#1918]
When i build the release version of the project i get the files but the colmap.exe is 15MB where the one that is downloaded is 78MB. This is not a problem as everything works but when i transfer the files to another computer Feature matching fails and the error is:

**ERROR: Feature matching failed. This is probably caused by insufficient GPU memory. Consider reducing the maximum number of features and/or matches.**

Of course i have nvidia gpu and i can run the downloaded version. I tried coping the cuda bin files from cuda installation but that did not helped. 

What can be the problem, can be that some libraries are not probably included in the build. The project is build as Multi-threaded DLL (/MD), i tried to build it as Multi-threaded (/MT) but i can't compile it successfully. I am not sure if that is the problem.

**Environment:**
 - Windows 10
 - COLMAP Version 3.8
 - CUDA version 11.6

**Comment by ahojnnes** [comment]
You probably compiled colmap only for one specific CUDA architecture. The one precompiled and hosted on Github is compiled for major CUDA compute architectures, which inflates the binary size a lot.

**Comment by nearshore-macedonia** [comment]
@ahojnnes you are right, cuda archs was set to auto, i added multiple architecture and it works now. Thanks!
