### ISSUE TITLE
Specify fixed intrinsics for some selected cameras

### ISSUE THREAD

**Issue by kvuong2711** [colmap/colmap#1919]
While running bundle adjustment with existing reconstruction, is it possible to specify fixed intrinsics **only** for some selected cameras? The only option I saw can only be applied to **all** the cameras, e.g., setting `ba_refine_focal_length`, `ba_refine_principal_point`, `ba_refine_extra_params` to False.

**Comment by tsattler** [comment]
This is currently not possible, you would need to modify the code to achieve this.
