### ISSUE TITLE
Dense reconstruction without CUDA

### ISSUE THREAD

**Issue by hy9be** [colmap/colmap#192]
Telling from the code: https://github.com/colmap/colmap/blob/master/src/controllers/automatic_reconstruction.cc#L237, it seems not possible to do dense reconstruction without CUDA. But my mac does not have a Nvidia graphic card. Any workaround?

**Comment by zhanlv600** [comment]
Hello, I also come across the problem like you. I compile the whole program successfully on my ubuntu (Parallel Desktop Virtue Machines without cuda), but I can just run sfm successfully and when I run mvs to get stereo maps, it will display cuda not found. I don't know where the problem is and I set the gpu index = -1 to only use cpu. But it doesnn't work.

**Comment by ahojnnes** [comment]
Dense reconstruction is only implemented on the GPU using CUDA. A CPU implementation would be too slow. If you do not have access to a CUDA-enabled GPU, you could use CMVS/PMVS as described in the documentation here https://colmap.github.io/tutorial.html#dense-reconstruction

Let me know if you have other questions.

**Comment by 10110111** [comment]
> A CPU implementation would be too slow.

But what about OpenCL? It's supported on much wider range of hardware, and seems a viable alternative to use on CUDA-less systems.

**Comment by metacollin** [comment]
OpenCL isn't going to be around much longer, it's being merged into Vulkan.  Beyond that, using OpenCL (or Vulkan) would require rewriting all of the compute kernel code and interfacing from scratch.  However, I'm sure colmap would happily accept @10110111's pull request with said rewrite completed.

**Comment by enzyme69** [comment]
@wavexx I am also a bit frustrated that my Mac cannot use its GPU for dense reconstruction... :( But curious about the OpenMVS, do you have article / vlog / tutorial to show how it is done?

So far, I collect only the sparse point cloud... they are ok, but I need to mesh them somewhat and would be nice to be able to process the dense data.

**Comment by ottokiksmaler** [comment]
Here you can find explanation on usign OpenMVS (dense+mesh+texture) with COLMAP
https://pfalkingham.wordpress.com/2018/04/01/colmap-openmvs-scripts-updated/

**Comment by s-wtnb** [comment]
CPU implementation of the MVS part of COLMAP
https://github.com/mitjap/pwmvs

**Comment by ahojnnes** [comment]
This is fantastic. How does it compare in terms of speed?

**Comment by balaclava9** [comment]
one more thought. it looks like openMVS just added support for COLMAPs sparse output.
https://github.com/cdcseacave/openMVS/releases/tag/v2.2.0

I will try it out when I have time. right now pmvs2 is crunching away.

**Comment by metacollin** [comment]
> This is fantastic. How does it compare in terms of speed?
 
Very slow. When @ahojnnes says a CPU implementation would be too slow... he isn't joking. 

I have dual Xeon Platinum 8360m CPUs. That gives me 48 physical cores. Xeon Gold and Platinum CPUs have 2 AVX512 FMA units per core, whereas all other intel CPUs with AVX512 have only one per core. Ultimately, I have 96 physical AVX512 units on my workstation capable of running at 2.6GHz (AVX cores run at a lower turbo speed, this is common to all intel CPUS).

With my 96 AVX512 FMA cores, I manage about 8% the performance of one AMD W5500 GPU (which is **NOT** a particularly beefy GPU) running OpenCL for a raytracing workload. A raytracing workload is much more forgiving to CPUs than colmap's dense reconstruction algorithm is.

Of course, the difference will be even more asymmetric if you don't have 96 AVX512 FMA units at your disposable. Any CPU that has an IGPU will have as many as you have cores (not threads).  So if you, say, have an 8 core cpu, even allowing for the higher turbo frequency, you should expect between 1-2% the performance of one not very good GPU. At best.
