### ISSUE TITLE
SiftExtraction.max_image_size

### ISSUE THREAD

**Issue by gunesevitan** [colmap/colmap#1920]
I couldn't find any documentation about this so I had to ask here. How does that work?

* Resize longest edge to max_image_size if any of the dimensions exceed max_image_size
* Resize both edges to max_image_size if any of them exceed max_image_size

**Comment by ahojnnes** [comment]
The following is correct:

> Resize longest edge to max_image_size if any of the dimensions exceed max_image_size

while the shorter edge is resized to maintain image aspect ratios.
