### ISSUE TITLE
Difference between the OPENCV, and the OPENCV_FISHEYE camera models?

### ISSUE THREAD

**Issue by rakshith95** [colmap/colmap#1921]
Hello, 
The camera model for 'OPENCV' is described in https://github.com/colmap/colmap/blob/dev/src/base/camera_models.h#L247, and the 'OPENCV_FISHEYE'  https://github.com/colmap/colmap/blob/dev/src/base/camera_models.h#L263

The comments under 'OPENCV' say: 

> // Parameter list is expected in the following order:
//
//    fx, fy, cx, cy, k1, k2, k3, k4

and for the 'OPENCV_FISHEYE' model:

> // Parameter list is expected in the following order:
//
//    fx, fy, cx, cy, k1, k2, p1, p2, k3, k4, k5, k6
 
with extra parameters (p1,p2) to model tangential distortion.

However, they're defined as: 
`CAMERA_MODEL_DEFINITIONS(4, "OPENCV", 8)` , and `CAMERA_MODEL_DEFINITIONS(5, "OPENCV_FISHEYE", 8)` , 
both with 8 parameters, and this is what I see when I use either as well.  Is this a bug or am I missing something?

**Comment by ahojnnes** [comment]
> fx, fy, cx, cy, k1, k2, p1, p2, k3, k4, k5, k6

These are for the FULL_OPENCV model. I think you may have mixed up the documentation?

**Comment by rakshith95** [comment]
> > fx, fy, cx, cy, k1, k2, p1, p2, k3, k4, k5, k6
> 
> These are for the FULL_OPENCV model. I think you may have mixed up the documentation?

Ah, you're right, thank you. I misread it, sorry!
