### ISSUE TITLE
Does Colmap really use Cosin Similarity for descriptor matching?

### ISSUE THREAD

**Issue by fanyuanyi** [colmap/colmap#1922]
When I read the origin code of Colmap, I was confused. We all know, the larger the cosine similarity is, the more similar the two points are. Thus, in the process of matching, we should set the minimum similarity value to guarantee the matching quality.

In the code of Colmap, the code is cosine similarity, as shown:
`dists(i1, i2) = descriptors1_int.row(i1).dot(descriptors2_int.row(i2));` // in the file **sift.cc**

This means that the larger the dists(i1, i2) is, the more similar the two points are. However, we need to set the max distance:
`// Maximum distance to best match. 
 double max_distance = 0.7;`//in the file **sift.h**
 

Do we need to set the max distance? Why? I think we should set the min distance rather than the max distance.

Could someone explain it? How does the author treat this?
While for Euler distance, the smaller the distance is, the more similar the two points are. It is completely opposite to cosine similarity. And we should set the max distance. 
Does the Colmap really use Cosin Similarity?

**Comment by ahojnnes** [comment]
Please refer to the code here: https://github.com/colmap/colmap/blob/dev/src/feature/sift.cc#L85

Before applying absolute distance or ratio thresholds, the distance is converted to L2.

**Comment by fanyuanyi** [comment]
Thank you very much. I understand it.

**Comment by fanyuanyi** [comment]
Thank you very much. I understand it.

Johannes Schönberger ***@***.***> 于2023年5月19日周五 03:18写道：
