### ISSUE TITLE
Could model_aligner handle different scales for axes?

### ISSUE THREAD

**Issue by is03wlei** [colmap/colmap#193]
For example, one unit along X axis is one meter while one unit along Y axis is 2 meters.

When I aligned model coordinates to GPS. I used both original GPS and (latitude, longitude*cos(latitude)). But generated the same results. So I guess colmap can handle different scale for axes.

But when I dug into code, I found only one scale factor.

Umeyama.h: line 145~line 159
  if (with_scaling)
  {
    // Eq. (42)
    const Scalar c = Scalar(1)/src_var * svd.singularValues().dot(S);

    // Eq. (41)
    Rt.col(m).head(m) = dst_mean;
    Rt.col(m).head(m).noalias() -= c*Rt.topLeftCorner(m,m)*src_mean;
    Rt.block(0,0,m,m) *= c;
  }
  else
  {
    Rt.col(m).head(m) = dst_mean;
    Rt.col(m).head(m).noalias() -= Rt.topLeftCorner(m,m)*src_mean;
  }

**Comment by ahojnnes** [comment]
How about just scaling the axes of your model after aligning it with the model aligner? That should be equivalent.

**Comment by is03wlei** [comment]
I think the answer for my question is no.
Previously I did something wrong in the experiment.
Scaling the axes before aligning works now.

**Comment by ahojnnes** [comment]
If you account for the scaling properly, it shouldn't matter whether you first scale the axes and then do the alignment or vice versa. I mark this as solved and I will not include an axis scaling feature into COLMAP as this seems a rather specific issue. If more people ask for it, I consider including such a feature. Thanks for the feedback.
