### ISSUE TITLE
updated docker image at the dockerhub

### ISSUE THREAD

**Issue by jubelsM** [colmap/colmap#1930]
**Is your feature request related to a problem? Please describe.**
currently, the image at the docker hub is of colmap 3.6
https://hub.docker.com/r/colmap/colmap/tags
**Describe the solution you'd like**
I would love to have an updated version at the docker hub.

**Comment by ahojnnes** [comment]
I am not sure what's the process to publish at docker hub. Ideally it would directly pull the latest version from GitHub here. If anyone wants to help with this, I'd be happy to accept a PR with a patch. Thanks.

**Comment by Parskatt** [comment]
@ahojnnes are you an owner of the colmap dockerhub org, or is it someone else? If you're the owner it should be as simple as
`docker login <your credentials>`
`docker push colmap/colmap:latest`

I'm also interested in having an up-to-date colmap on hub.

**Comment by Parskatt** [comment]
@jubelsM I built an up-to-date colmap docker at `parskatt/colmap`, let me know if it works for you.

**Comment by ahojnnes** [comment]
I am not the owner of this org. How can we find out who the owner is?

**Comment by Parskatt** [comment]
@ahojnnes there does not seem to be a way to find out. I can ask around a bit, otherwise I guess best option is making new org / under your profile which states its the official version.

**Comment by ahojnnes** [comment]
git blame on the docker file in this repo here could provide some hints. I remember not being the original author of the file. Currently on the phone, so cannot do it right now.

**Comment by Parskatt** [comment]
Good idea, I'm also unable to check now but can have a look tomorrow.

________________________________

**Comment by Parskatt** [comment]
https://github.com/colmap/colmap/commits?author=tjdahlke

Seems like TJ Dahlke https://github.com/tjdahlke made the first commit

**Comment by Parskatt** [comment]
@ahojnnes I got in touch with Taylor, and he can add you to the colmap docker hub org so that you can push. Do you have a preferred email there?

**Comment by ahojnnes** [comment]
Thanks for figuring that out. I have the same username “ahojnnes” on Dockerhub. Thank you.

**Comment by ahojnnes** [comment]
@Parskatt @tjdahlke Each commit to the main branch now automatically publishes the latest docker image to docker hub: https://github.com/colmap/colmap/pull/2195
