### ISSUE TITLE
Failed to create sparse model for rotating camera in SPECT

### ISSUE THREAD

**Issue by ManolisNikolakakis** [colmap/colmap#1931]
I'm trying to use the NeRF repository which applies COLMAP to generate the projection geometry files for my SPECT (nuclear imaging) images of a pair of kidneys.
Unfortunately, when I'm trying to generate the cameras, images and points3D files I'm encountering the following error:

========================
  => No good initial image pair found.
Elapsed time: 0.000 [minutes]
ERROR: failed to create sparse model

Do you have some advice on how to counter this issue? I've been unable to identify the cause of the issue. I'm happy to provide more information. 
Also, please find attached the dataset I am using. It represents 120 angular views of a rotating camera on a SPECT scanner.
https://drive.google.com/file/d/1HaPdUUtdYTn3mXDbXEZBU3IKkJ0IqOU-/view?usp=sharing

Kind regards

**Comment by tudipffmgt** [comment]
Looking at the images, I would think that the problem is finding correct distinctive keypoints between the different images (image pairs).
You can check/visualize the keypoints e.g. by using the GUI and checking the database (pair-wise matches).
