### ISSUE TITLE
Geo alignment faild

### ISSUE THREAD

**Issue by janryan6** [colmap/colmap#1935]
**Geo alignment faild**
The file and image are named correctly and exist, but it doesn't work, please help me！
![03c4ad87b9e2a9b61d3fc5ca04d4473](https://github.com/colmap/colmap/assets/108948633/2172cfb6-faf3-4ed2-a87b-f55caa4b8bab)

**Comment by janryan6** [comment]
The name of the image in the txt and the actual image name also correspond.
![95bc7f12224f4240061ea0e3b7bbf37](https://github.com/colmap/colmap/assets/108948633/7ccc063a-27a9-4121-9fe9-30ba7304700d)

**Comment by janryan6** [comment]
@tsattler  
Sorry to bother you , but can you help me to solve this question...
This is really important to me
I would really appreciate it

**Comment by tudipffmgt** [comment]
Did you try modifying the 'robust_alignment_max_error' to a larger value? 
Are your reference coordinates accurate so that the transformation can succeed?

**Comment by tsattler** [comment]
Looking at the text file, it seems that all images have the same coordinate. In this case, the alignment cannot succeed as it would mean that the reconstruction needs to be scaled to a single point.

**Comment by janryan6** [comment]
> Did you try modifying the 'robust_alignment_max_error' to a larger value? Are your reference coordinates accurate so that the transformation can succeed?

I tried adjusting the values to 5 and 10, but it still failed.

**Comment by janryan6** [comment]
> This is an experimental model with only two different points placed in . In the previous run, 57 different points were used and it still failed.Is there anything more I can provide you with in order for you to better understand this failed case of mine? thanks again!!

<img width="198" alt="微信图片_20230528192124" src="https://github.com/colmap/colmap/assets/108948633/053c9bf5-4638-448f-9438-9325ff888b96">

**Comment by janryan6** [comment]
> Did you try modifying the 'robust_alignment_max_error' to a larger value? Are your reference coordinates accurate so that the transformation can succeed?

Thank you for your reply! There may be a centimeter deviation, will such an error affect the alignment?

**Comment by tsattler** [comment]
> This is an experimental model with only two different points placed in . In the previous run, 57 different points were used and it still failed.Is there anything more I can provide you with in order for you to better understand this failed case of mine? thanks again!!

A necessary pre-condition for the alignment to succeed is that there are at least 3 images that are (relatively) accurately reconstructed and that are in general position (i.e., not on a single line or close to a single line).

**Comment by janryan6** [comment]
> > This is an experimental model with only two different points placed in . In the previous run, 57 different points were used and it still failed.Is there anything more I can provide you with in order for you to better understand this failed case of mine? thanks again!!
> 
> A necessary pre-condition for the alignment to succeed is that there are at least 3 images that are (relatively) accurately reconstructed and that are in general position (i.e., not on a single line or close to a single line).

Thank you very much for your guidance, I aligned using three points that are not in a straight line and it worked! Thank you again!
