### ISSUE TITLE
Feature Extraction fails for OpenCV camera model

### ISSUE THREAD

**Issue by ckochipm** [colmap/colmap#194]
When I select the OpenCV / Full OpenCV camera model the feature extraction step crashes. I'm using CPU only , I'm currently on the dev branch. The simple radial model works perfectly. The dump is the following:

F0804 10:18:07.742537  3453 camera.cc:93] Check failed: idxs.size() == 1 (2 vs. 1) 
*** Check failure stack trace: ***
    @     0x7faae174a5cd  google::LogMessage::Fail()
    @     0x7faae174c433  google::LogMessage::SendToLog()
    @     0x7faae174a15b  google::LogMessage::Flush()
    @     0x7faae174ce1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x6d515c  colmap::Camera::FocalLength()
    @           0x6ee2f2  colmap::internal::FeatureWriterThread::Run()
    @           0x60170c  colmap::Thread::RunFunc()
    @     0x7faadead9c80  (unknown)
    @     0x7faae0fd26ba  start_thread
    @     0x7faade23f3dd  clone
    @              (nil)  (unknown)

**Comment by ahojnnes** [comment]
Thanks, this was a recently introduced bug. Should be fixed with the last commit in master now.
