### ISSUE TITLE
Question about IncrementalMapper::findLocalBundle

### ISSUE THREAD

**Issue by coffeeancode** [colmap/colmap#1953]
Hi!

I got a bit confused when looking at the code in `IncrementalMapper::findLocalBundle`, line 1040, that loops over `image.Points2D()` to fill `shared_points3D`? Shouldn't it instead loop through the 2D-points in `overlapping_image.Points2D()`, to find the 3D-points shared with the reference image? As it is now (I might have missed something though), the vector `shared_points3D` will be filled with the same values every time it's computed.

**Comment by wesleyliwei** [comment]
fixed in latest code ,please check, and close the issue, if solved~

**Comment by coffeeancode** [comment]
Looks good to me, hopefully this doesn't cause any weird regressions, in which case I'd be even more confused.
