### ISSUE TITLE
Stereo process won't start for small datasets

### ISSUE THREAD

**Issue by LenaSailor** [colmap/colmap#196]
Hi Johannes

Good results from several datasets so far - thanks!  Have had some problems with Dense reconstruction/Stereo not starting for small datasets (10 or so).  Log shows  typically:

_**Reading workspace...
Reading configuration...
Elapsed time: 0.003 [minutes]**_

... and then nothing! (doesn't crash though)

Any ideas?

Thanks in advance

Stuart

**Comment by ahojnnes** [comment]
Can you share the model with me?

**Comment by ahojnnes** [comment]
Thanks for the report. This bug should be fixed in the latest dev commit. Can you try and report back? Thanks.

**Comment by ahojnnes** [comment]
This is confirmed to be solved. Thanks for the feedback.
