### ISSUE TITLE
Issue with translation and rotation from known camera intrinsics

### ISSUE THREAD

**Issue by leniumc** [colmap/colmap#1961]
I'm currently working with a dataset that specifies the camera extrinsics with a translation vector that is the position of the camera relative to the origin, and a rotation matrix that transforms rays pointing from the camera origin the z=-1 image plane to world coordinates. I'm trying to convert this data I have into the format that Colmap requires. 

It seems like the rotation matrix should be applied before the translation in the dataset I have, so I tried following the directions here #434. That kind of worked, but I'm sure if it is because my rotation matrices are somehow defined differently, my cameras are now all pointing outwards, although the locations seem to be correct. I'm wondering if there's a easy fix to this... Thanks!

![image](https://github.com/colmap/colmap/assets/22674006/8a776f09-8612-4571-ad01-196bfad9bac8)

**Comment by leniumc** [comment]
Hmm okay I think the main issue is that Colmap expects the camera to be facing the positive z direction in camera coordinates, while my dataset uses the negative z direction.

**Comment by pknmax** [comment]
@hanyucc how you solved this problem?

**Comment by CILT** [comment]
Could you be so kind to share your algorithm? I'm struggling to get something similar to work.

I have known camera poses and the "look at" point.

How could I retrieve COLMAP poses into images.txt?
