### ISSUE TITLE
two_view_tracks systematicely ignored ?

### ISSUE THREAD

**Issue by marinmarcillat** [colmap/colmap#1973]
**Describe the bug**
During the reconstruction of a 3D model of a deep underwater transect, I get only stripes of 3D model: the only features kept are those present on 3 different images. As told in the FAQ, I unchecked the ignore two_view_tracks in the reconstruction parameter, but this didn't change the end result. I also tried to change the minimal angle, no change. I've searched in all the other available parameters, I have no clue of what to change. Am I missing something ? Is this an expected behavior ? Any idea of other parameters that could help solve this issue ? 
The scene is 1200m deep, so unfortunately going back there and get images with more overlap is not possible for me.

Otherwise, thanks a lot for Colmap, it is very impressive !

**To Reproduce**
The dataset: https://filesender.renater.fr/?s=download&token=0e9488f5-ec7e-4f9b-b62e-be44f3c21923
camera parameters: OpenCV, 6600.000000, 6600.000000, 3000.000000, 2000.000000, 0.000000, 0.000000, 0.000000, 0.000000

**Expected behavior**
No more stripes, a complete model. Features on only 2 images are used in reconstruction

**Screenshots**
![image](https://github.com/colmap/colmap/assets/58145636/9eb94a00-874b-4049-b5a1-86f8197a74d9)
![image](https://github.com/colmap/colmap/assets/58145636/0a762719-8135-4119-a4f1-f147d53c2d79)

**Environment:**
 - OS: Windows 10
 - COLMAP Version 3.8
 - Capture Device: Nikon D5500, ROV Victor 6000

**Comment by ahojnnes** [comment]
You can disable the "ignore_two_view_tracks" option and also make sure to change the render options to show two view observations, by default only three view tracks are shown in the viewer.

**Comment by marinmarcillat** [comment]
Thanks for your help ! I thought the issue was in COLMAP because I couldn't see these two-view geometries (now I can with the render options). The real issue lies in openMVS and in the Densifypointcloud that I'm using for densification.
