### ISSUE TITLE
Can't make matching work

### ISSUE THREAD

**Issue by ckochipm** [colmap/colmap#198]
I'm trying to register / match aerial photos in Colmap. The feature extraction works fine, I'm not sure about the camera parameters (see second screenshot), if this is focal length maybe it shouldn't be so different for the two components? There are a lot of matches between the images (sequential matching mode) but no inliers. I tried it with different camera models (Radial, OpenCV, OpenCV full) but none worked.

![colmap0](https://user-images.githubusercontent.com/30599050/29111703-96d2e410-7ceb-11e7-87a1-f431506ccedb.png)
![colmap](https://user-images.githubusercontent.com/30599050/29111436-80463d60-7cea-11e7-9280-5bbfb4470871.png)
![colmap4](https://user-images.githubusercontent.com/30599050/29111522-e1273094-7cea-11e7-9ae1-9bd819ee5910.png)
![colmap2](https://user-images.githubusercontent.com/30599050/29111470-aac48cae-7cea-11e7-8c84-b57bb86ef785.png)
![colmap3](https://user-images.githubusercontent.com/30599050/29111471-acc4787a-7cea-11e7-90cb-826d6f793bfe.png)

**Comment by ahojnnes** [comment]
Are any of the matches correct? Can you share two of your images?

**Comment by ckochipm** [comment]
This is the screen I get:

![colmap_img](https://user-images.githubusercontent.com/30599050/29113227-c9c9d1da-7cf0-11e7-9227-df63b83b620a.png)

I'm not sure what I should see on there...

**Comment by ahojnnes** [comment]
I don't see any matches in that image. Please, send me the original images and I could have a look.

**Comment by ahojnnes** [comment]
Thanks, the latest commit in the dev branch fixes this. You have to start with an empty database, since the problem was already in the feature extraction. Thanks for reporting this bug.
