### ISSUE TITLE
Dev branch, Zero matches at reconstruction step.

### ISSUE THREAD

**Issue by szczepaniak-bartek** [colmap/colmap#199]
Have a weird problem with latest dev branch.
When starting reconstruction pass got this error.
```
==============================================================================
Exhaustive feature matching
==============================================================================

Matching block [1/1, 1/1] in 5.229s
Elapsed time: 0.087 [minutes]

==============================================================================
Loading database
==============================================================================

Loading cameras... 7 in 0.000s
Loading matches... 0 in 0.000s
Loading images... 7 in 0.000s (connected 0)
Building scene graph... in 0.000s (ignored 0)

Elapsed time: 0.000 [minutes]

WARNING: No images with matches found in the database.
```
Last commit that works for me was 4e5ffb6
`Sys spec:
ceres 1.13.0
eigen 3.3.4
gcc 7.1.1
cuda 8.0.61 (gcc5 5.4.0)
`
_Ps. I maintain the `colmap-git` package on archlinux user repository (AUR), in case of a problem with the package #161 please 'ping' me ;)_

**Comment by ahojnnes** [comment]
Can you share the images with me? Thanks.

**Comment by szczepaniak-bartek** [comment]
https://github.com/szczepaniak-bartek/colmap_image_test

**Comment by ahojnnes** [comment]
Thanks, the latest commit in the dev branch fixes this. You have to start with an empty database, since the problem was already in the feature extraction. Thanks for reporting this bug.

**Comment by bartoszek** [comment]
Yap, got through sparse reconstruction but stuck on a dense step.
```
==============================================================================
Image undistortion
==============================================================================

Undistorting image [1/23]
Undistorting image [2/23]
Undistorting image [3/23]
Undistorting image [4/23]
Undistorting image [5/23]
Undistorting image [6/23]
Undistorting image [7/23]
Undistorting image [8/23]
Undistorting image [9/23]
Undistorting image [10/23]
Undistorting image [11/23]
Undistorting image [12/23]
Undistorting image [13/23]
Undistorting image [14/23]
Undistorting image [15/23]
Undistorting image [16/23]
Undistorting image [17/23]
Undistorting image [18/23]
Undistorting image [19/23]
Undistorting image [20/23]
Undistorting image [21/23]
Undistorting image [22/23]
Undistorting image [23/23]
Writing reconstruction...
Writing configuration...
Writing scripts...
Elapsed time: 0.080 [minutes]
Reading workspace...
Reading configuration...
Elapsed time: 0.000 [minutes]

StereoFusion::Options
---------------------
max_image_size: 1000
min_num_pixels: 5
max_num_pixels: 10000
max_traversal_depth: 100
max_reproj_error: 2
max_depth_error: 0.01
max_normal_error: 10
check_num_images: 25
cache_size: 32

Reading workspace...
Reading configuration...
WARNING: Ignoring image DSC_5294.jpg, because input does not exist.
WARNING: Ignoring image DSC_5293.jpg, because input does not exist.
WARNING: Ignoring image DSC_5295.jpg, because input does not exist.
WARNING: Ignoring image DSC_5296.jpg, because input does not exist.
WARNING: Ignoring image DSC_5297.jpg, because input does not exist.
WARNING: Ignoring image DSC_5298.jpg, because input does not exist.
WARNING: Ignoring image DSC_5299.jpg, because input does not exist.
WARNING: Ignoring image DSC_5300.jpg, because input does not exist.
WARNING: Ignoring image DSC_5292.jpg, because input does not exist.
WARNING: Ignoring image DSC_5291.jpg, because input does not exist.
WARNING: Ignoring image DSC_5290.jpg, because input does not exist.
WARNING: Ignoring image DSC_5289.jpg, because input does not exist.
WARNING: Ignoring image DSC_5288.jpg, because input does not exist.
WARNING: Ignoring image DSC_5287.jpg, because input does not exist.
WARNING: Ignoring image DSC_5301.jpg, because input does not exist.
WARNING: Ignoring image DSC_5286.jpg, because input does not exist.
WARNING: Ignoring image DSC_5285.jpg, because input does not exist.
WARNING: Ignoring image DSC_5284.jpg, because input does not exist.
WARNING: Ignoring image DSC_5283.jpg, because input does not exist.
WARNING: Ignoring image DSC_5305.jpg, because input does not exist.
WARNING: Ignoring image DSC_5304.jpg, because input does not exist.
WARNING: Ignoring image DSC_5303.jpg, because input does not exist.
WARNING: Ignoring image DSC_5302.jpg, because input does not exist.
```
Have the same warning on master, after commit 9786c6e

**Comment by ahojnnes** [comment]
Can you send me the exact sequence of commands that you are executing?

**Comment by bartoszek** [comment]
'automatic_reconstructor --quality low --image_path colmap_image_test/ --workspace_path /tmp/test_colmap/'
Have the same error in the gui doing step by step reconstruction.

**Comment by ahojnnes** [comment]
Just ran the same command on your dataset and it works without a problem. Can you send me the data in ``/tmp/test_colmap/``?

**Comment by bartoszek** [comment]
https://www.dropbox.com/s/62djww0nqq1xmjs/test_colmap.7z?dl=0

**Comment by ahojnnes** [comment]
I get a checksum error for the file...

**Comment by bartoszek** [comment]
https://github.com/bartoszek/test_colmap

**Comment by ahojnnes** [comment]
I cannot reproduce the issue. Can you try to manually run the stereo step using ``dense_stereo --workspace_path /tmp/test_colmap/dense/0`` and report whether you are seeing the same issue?

**Comment by bartoszek** [comment]
`dense_stereo --workspace_path /tmp/test_colmap/dense/0/`
```
Reading workspace...
Reading configuration...
Elapsed time: 0.000 [minutes]
```
`dense_fuser --workspace_path /tmp/test_colmap/dense/0/ --output_path /tmp/test_colmap/dense/0/fused.ply`
```

StereoFusion::Options
---------------------
max_image_size: -1
min_num_pixels: 5
max_num_pixels: 10000
max_traversal_depth: 100
max_reproj_error: 2
max_depth_error: 0.01
max_normal_error: 10
check_num_images: 50
cache_size: 32

Reading workspace...
Reading configuration...
WARNING: Ignoring image DSC_5294.jpg, because input does not exist.
WARNING: Ignoring image DSC_5293.jpg, because input does not exist.
...
```

**Comment by ahojnnes** [comment]
How many GPUs do you have in your system? Does ``dense_stereo --workspace_path /tmp/test_colmap/dense/0/ --DenseStereo.gpu_index 0`` change the output?

**Comment by bartoszek** [comment]
Single gpu (gtx970, Driver Version: 384.59).
Same output with `gpu_index 0`.

**Comment by bartoszek** [comment]
`dense_stereo --workspace_path /tmp/test_colmap/dense/0/ --DenseStereo.gpu_index 0`
```
Reading workspace...
Reading configuration...
Configuration has 23 problems...
Elapsed time: 0.000 [minutes]
```

**Comment by bartoszek** [comment]
I can confirm that problem lays in commit b44473edb70704c5f82a5dd181015d7c5d767f1e
Alter `git revert b44473edb70704c5f82a5dd181015d7c5d767f1e` both dev and master branch works fine for me.

**Comment by bartoszek** [comment]
I can confirm that problem is related to commit b44473edb70704c5f82a5dd181015d7c5d767f1e
Alter `git revert b44473edb70704c5f82a5dd181015d7c5d767f1e` both dev and master branch works fine for me.

**Comment by ahojnnes** [comment]
Thanks for investigating this issue. Let me know whether the last commit fixes this issue. (In theory, it should fix the problem :-)) thanks again.

**Comment by bartoszek** [comment]
Works fine, thanks.

**Comment by ahojnnes** [comment]
Great, thanks for the help.

**Comment by GabbySuwichaya** [comment]
Hi, I have just started, and, at the moment, I have the same problem: 

`StereoFusion::Options
---------------------
max_image_size: -1
min_num_pixels: 5
max_num_pixels: 10000
max_traversal_depth: 100
max_reproj_error: 2
max_depth_error: 0.01
max_normal_error: 10
check_num_images: 50
cache_size: 32

Reading workspace...
Reading configuration...
WARNING: Ignoring image IMG_2387.JPG, because input does not exist.
WARNING: Ignoring image IMG_2401.JPG, because input does not exist.
WARNING: Ignoring image IMG_2383.JPG, because input does not exist.
WARNING: Ignoring image IMG_2341.JPG, because input does not exist.
WARNING: Ignoring image IMG_2336.JPG, because input does not exist.
WARNING: Ignoring image IMG_2422.JPG, because input does not exist.
WARNING: Ignoring image IMG_2402.JPG, because input does not exist.
 
...

WARNING: Ignoring image IMG_2403.JPG, because input does not exist.
WARNING: Ignoring image IMG_2407.JPG, because input does not exist.
WARNING: Ignoring image IMG_2390.JPG, because input does not exist.
WARNING: Ignoring image IMG_2348.JPG, because input does not exist.
Fusing image [1/100] in 0.000s (0 points)
WARNING: Could not fuse any points. This is likely caused by incorrect settings - filtering must be enabled for the last call to patch match stereo.
Number of fused points: 0
Elapsed time: 0.003 [minutes] 
`

PS. I run this over the Gerrard Hall dataset.

**Comment by bartoszek** [comment]
@GabbySuwichaya Perhaps you should consider creating separate Issue. It doesn't look the same as the original issue I've had.

**Comment by GabbySuwichaya** [comment]
I see. Will post a separate issue.
