### ISSUE TITLE
How to get the number of matched images

### ISSUE THREAD

**Issue by anterrrr** [colmap/colmap#1997]
if I use colmap GUI to get a sfm model with vocabTrees method,  how can I get the number of matched images?

**Comment by tsattler** [comment]
I am not sure I understand the question. Which number do you want? The number of image pairs that were compared to each other?

**Comment by anterrrr** [comment]
> I am not sure I understand the question. Which number do you want? The number of image pairs that were compared to each other?
Yes, I want get the number of image pairs that were compared to each other.
