### ISSUE TITLE
Compile success but run will meet a problem at global bundle adjustment

### ISSUE THREAD

**Issue by zhanlv600** [colmap/colmap#200]
I compile the whole program successfully as instruction says under vs2015 win10, however when I process images, the feature extraction and feature matching run no problem, the program will crash at global bundle adjustment, it says colmap.exe meet a win32 exception which has not been handled. Anyone meet this problem?

**Comment by ahojnnes** [comment]
Thanks for the feedback, but this report is a little too vague. Can you run in ``RelWithDeb`` mode and report back with a traceback from Visual Studio?

**Comment by zhanlv600** [comment]
Here is the pictures which illustrate the problem I meet. The first two pictures is I run automatic_reconstructor.exe under command line. It meet a problem at Global bundle adjustment.
The third picture is I run colmap using GUI, it also has the same problem. The visual studio says ***.exe occurs a win32 exception which has not been handled. However when I run the automaitc_reconstructior
under vs2015, using use_opengl = false, the SFM part will run no problem. 






在 2017-08-10 14:48:45，"Johannes Schönberger" <notifications@github.com> 写道：


Thanks for the feedback, but this report is a little too vague. Can you run in RelWithDeb mode and report back with a traceback from Visual Studio?

**Comment by ahojnnes** [comment]
I don't see any pictures in your text, but you are referring to them in your first sentence? This error seems very strange to me, since the sparse reconstruction part does not make use of the GPU at all apart from visualization. Can you try to just load an existing PLY point cloud file? Does the GUI crash? Do you see the coordinate axes in the empty 3D viewer?

**Comment by zhanlv600** [comment]
I find this problem is at the line 277:ceres.Slove(solver_options, problem_.get(),&summary); of the bundle_adjustment.cc file. I use the latest ceres to compile, and I test the ceres compilation no error. I think the error may be about the ceres version? I comment this line and make the program not optimize the initial pair, and the program will run no problem!

**Comment by ahojnnes** [comment]
Did you resolve the problem? I suspect that this has to do with an invalid Ceres-Solver compile. Can you try the new build script as described here: https://colmap.github.io/install.html#build-script

**Comment by ahojnnes** [comment]
Closing this due to lack of feedback, feel free to reopen. Thanks.
