### ISSUE TITLE
Building correspondence graph terminated without error message

### ISSUE THREAD

**Issue by xiyichen** [colmap/colmap#2003]
**Describe the bug**
I was running colmap on Google Colab on a video of 942 images (the link is provided below). When it got to mapper, the program terminated when it was "Building correspondence graph" but did not give any error message.

**To Reproduce**
```
!wget https://virtualhumans.mpi-inf.mpg.de/3DPW/imageFiles.zip
!unzip imageFiles.zip "*/outdoors_fencing_01/*" -d "./"
!mkdir /content/colmap_dir
!mkdir /content/colmap_dir/images
!mv /content/imageFiles/outdoors_fencing_01/* /content/colmap_dir/images

!colmap feature_extractor --database_path /content/colmap_dir/db.db --image_path /content/colmap_dir/images --SiftExtraction.use_gpu=true

!colmap exhaustive_matcher --database_path /content/colmap_dir/db.db --SiftMatching.use_gpu=true

!mkdir /content/colmap_dir/sparse

!colmap mapper --database_path /content/colmap_dir/db.db --image_path /content/colmap_dir/images --output_path /content/colmap_dir/sparse
```

**Expected behavior**
The correspondence graph should be built sucessfully and start mapping

**Screenshots**
<img width="1091" alt="Screenshot 2023-07-06 at 16 51 12" src="https://github.com/colmap/colmap/assets/50854238/d81cd462-29d3-4370-9f5c-293199dea89f">

**Environment:**
 - OS: Ubuntu 20.04.6 LTS (Focal Fossa)
 - COLMAP Version: 3.9
 - Device: Google Colab

**Comment by ahojnnes** [comment]
Depending on the structure of the graph or how busy your cloud machine in colab is, this may take a very long time. As long as it doesn't crash, I don't think anything went wrong. How long did you wait?

**Comment by xiyichen** [comment]
I did not terminate it myself. The program crashed itself shortly after it starts building correspondence graph. I also tried the same dataset on my own computer with the same OS and COLMAP version but also got "Building correspondence graph...Killed". Without error messages it's hard to tell what went wrong. Did it run out of memory or something?

**Comment by ahojnnes** [comment]
It could be an out of memory issue. If loading the matches took 10 minutes, then that's a lot of data. I don't know how much RAM colab machines have.
