### ISSUE TITLE
Can not use the colmap as lib with CUDA

### ISSUE THREAD

**Issue by ZhiboRao** [colmap/colmap#2008]
**Describe the bug**
We build our project with the colmap as lib. Following the example. We can compile the project. However, we find that the project can not use CUDA. Meanwhile, we test the project with the following code:

#ifdef CUDA_ENABLED
  bool is_using_cuda = true;
#else
  bool is_using_cuda = false;
#endif

The answer is false.

Moreover, we test the colmap command lines. we find it can use CUDA.

**To Reproduce**

We use the demo as:
https://colmap.github.io/install.html#library

**Expected behavior**
We want to use the colmap as lib with CUDA.

**Screenshots**
<img width="1920" alt="image" src="https://github.com/colmap/colmap/assets/11450518/b738671a-d529-4917-986d-09651810c922">

<img width="1920" alt="image" src="https://github.com/colmap/colmap/assets/11450518/34a44a67-d14d-4b3c-b60b-0a44f9a2d7cb">

**Environment:**
 - OS: ubuntu 22.04.2
 - COLMAP Version: 3.8
 - Capture Device: ubuntu 22.04.2

**Comment by ZhiboRao** [comment]
Hi, everyone.

I have solved this problem. You need to add CUDA in CMake. 

set(CUDA_MIN_VERSION "7.0")
if(CUDA_ENABLED)
    if(CMAKE_VERSION VERSION_LESS 3.17)
        find_package(CUDA QUIET)
        if(CUDA_FOUND)
            message(STATUS "Found CUDA version ${CUDA_VERSION} installed in "
                    "${CUDA_TOOLKIT_ROOT_DIR} via legacy CMake (<3.17) module. "
                    "Using the legacy CMake module means that any installation of "
                    "COLMAP will require that the CUDA libraries are "
                    "available under LD_LIBRARY_PATH.")
            enable_language(CUDA)

            macro(declare_imported_cuda_target module)
                add_library(CUDA::${module} INTERFACE IMPORTED)
                target_include_directories(
                    CUDA::${module} INTERFACE ${CUDA_INCLUDE_DIRS})
                target_link_libraries(
                    CUDA::${module} INTERFACE ${CUDA_${module}_LIBRARY} ${ARGN})
            endmacro()

            declare_imported_cuda_target(cudart ${CUDA_LIBRARIES})
            declare_imported_cuda_target(curand ${CUDA_LIBRARIES})
            
            set(CUDAToolkit_VERSION "${CUDA_VERSION_STRING}")
            set(CUDAToolkit_BIN_DIR "${CUDA_TOOLKIT_ROOT_DIR}/bin")
        endif()
    else()
        find_package(CUDAToolkit QUIET)
        if(CUDAToolkit_FOUND)
            set(CUDA_FOUND ON)
            enable_language(CUDA)
        endif()
    endif()
endif()

if(CUDA_ENABLED AND CUDA_FOUND)
    if(NOT DEFINED CMAKE_CUDA_ARCHITECTURES)
        message(
            FATAL_ERROR "You must set CMAKE_CUDA_ARCHITECTURES to e.g. 'native', 'all-major', '70', etc. "
            "More information at https://cmake.org/cmake/help/latest/prop_tgt/CUDA_ARCHITECTURES.html")
    endif()

    add_definitions("-DCUDA_ENABLED")

    # Fix for some combinations of CUDA and GCC (e.g. under Ubuntu 16.04).
    set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_FORCE_INLINES")
    # Do not show warnings if the architectures are deprecated.
    set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -Wno-deprecated-gpu-targets")
    # Explicitly set PIC flags for CUDA targets.
    if(NOT IS_MSVC)
        set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} --compiler-options -fPIC")
    endif()

    message(STATUS "Enabling CUDA support (version: ${CUDAToolkit_VERSION}, "
                    "archs: ${CMAKE_CUDA_ARCHITECTURES})")
else()
    set(CUDA_ENABLED OFF)
    message(STATUS "Disabling CUDA support")
endif()

**Comment by ahojnnes** [comment]
As of latest commits in the dev branch this should now also work when colmap is built as a library, even without the above fix.
