### ISSUE TITLE
Dev Branch uses lots of RAM (>30GB) for compilation

### ISSUE THREAD

**Issue by pogilon** [colmap/colmap#201]
Hello @ahojnnes.

The dev branch uses around 30GB of ram during compilation! Is this normal? I don't think that used to happen before. Thanks.

**Comment by ahojnnes** [comment]
Can you post the output of the CMake command? And with how many threads are you compiling?

**Comment by pogilon** [comment]
yes, I will let you know in a few hours.

**Comment by pogilon** [comment]
Hello @ahojnnes. The current dev version takes about 40 GB of Ram to compile with "make -j". I am using a 4 core processor with 8 threads capacity. Please see below the CMake output:

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAS_SSE_EXTENSION
-- Performing Test HAS_SSE_EXTENSION - Success
-- Performing Test HAS_SSE2_EXTENSION
-- Performing Test HAS_SSE2_EXTENSION - Success
-- Performing Test HAS_SSE3_EXTENSION
-- Performing Test HAS_SSE3_EXTENSION - Success
-- Performing Test HAS_SSE41_EXTENSION
-- Performing Test HAS_SSE41_EXTENSION - Success
-- Performing Test HAS_SSE42_EXTENSION
-- Performing Test HAS_SSE42_EXTENSION - Success
-- Performing Test HAS_AVX_EXTENSION
-- Performing Test HAS_AVX_EXTENSION - Success
-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   regex
--   system
--   unit_test_framework
-- Found Eigen3: /usr/local/include/eigen3 (Required is at least version "2.91.0") 
-- Found Eigen3
--   Includes : /usr/local/include/eigen3
-- Found FreeImage
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
-- Found Glog
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
-- Found required Ceres dependency: Eigen version 3.2.10 in /usr/local/include/eigen3
-- Found required Ceres dependency: glog
-- Performing Test GFLAGS_IN_GOOGLE_NAMESPACE
-- Performing Test GFLAGS_IN_GOOGLE_NAMESPACE - Success
-- Found required Ceres dependency: gflags
-- Found Ceres version: 1.12.0 installed in: /usr/local with components: [LAPACK, SuiteSparse, SparseLinearAlgebraLibrary, SchurSpecializations, OpenMP]
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found Glew
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- Found Threads: TRUE  
-- Found Qt 5.5.1
-- Build type not specified, using RelWithDebInfo
-- Enabling OpenMP support
-- Disabling link-time optimization (-flto)
-- Enabling CUDA support (version: 8.0, archs: sm_61)
-- Enabling OpenGL support
-- Disabling profiling support
-- Configuring done
-- Generating done
-- Build files have been written to: /path/to/directory

**Comment by ahojnnes** [comment]
make -j might use more than 8 threads in your case. Try running make -j4 or make -j8. Can you report back please?

**Comment by ahojnnes** [comment]
Closing this as resolved due to lack of feedback. Feel free to reopen.
