### ISSUE TITLE
Cmake fail

### ISSUE THREAD

**Issue by kaiyi98** [colmap/colmap#2036]
Hello！
Can you tell me why the cmake fail，and the error as following:
`-- Found LZ4
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/liblz4.so
-- Found Glog
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
CMake Error at cmake/FindGlog.cmake:117 (target_include_directories):
  Cannot specify include directories for imported target "glog::glog".
Call Stack (most recent call first):
  CMakeLists.txt:100 (find_package)

CMake Error at cmake/FindGlog.cmake:118 (target_link_libraries):
  Cannot specify link libraries for target "glog::glog" which is not built by
  this project.
Call Stack (most recent call first):
  CMakeLists.txt:100 (find_package)

-- Configuring incomplete, errors occurred!
`

**Comment by ahojnnes** [comment]
Which cmake version? Setting include directories on included targets might be a feature only supported in later versions. Thanks.
