### ISSUE TITLE
Masked Stereo

### ISSUE THREAD

**Issue by ShuangLiu1992** [colmap/colmap#204]
Hi there Johannes, is there any option to force the program to only considered a masked area of the image to save memory and computational cost?

**Comment by ShuangLiu1992** [comment]
or rather, after SFM is it possible to crop the images to only contain region-of-interests before passing to dense stereo?

**Comment by ahojnnes** [comment]
It is possible if you adapt the intrinsics accordingly. You could have to modify the output of the ``image_undistorter`` before running ``dense_stereo``.

**Comment by ShuangLiu1992** [comment]
Do you know if there is a easy way to limit the depth range to the sparse points within those regions?

**Comment by ahojnnes** [comment]
The depth range is automatically limited to the depth range of the sparse points +- some robust delta. To limit the depth range to the cropped region, you need to modify the sparse model accordingly. Makes sense?
