### ISSUE TITLE
Map pointcloud visibilities to input images

### ISSUE THREAD

**Issue by tobias-kirschstein** [colmap/colmap#2040]
The `.vis` created by `stereo_fusion` contains a list of IDs for every 3D point indicating from which of the original views the point can be seen.   
However, I did not find a way to map this ID back to the actual file name.  
From the output of the previous `patch_match_stereo` I could find out that the IDs seem to coincide with a `ref_image_idx` that is logged there:
```
==============================================================================
Processing view 1 / 16 for cam_222200043.png
==============================================================================

Reading inputs...

PatchMatch::Problem
-------------------
ref_image_idx: 3 <-- How can I get this mapping?
src_image_idxs: 4 2 6 9 12 1 7 5 10 8 11 14 0 13 15
```

The mapping between these IDs and input images does not follow the order defined in `images.txt` or alphanumeric or any other conceivable order.  
I could also not find any documentation on this and neither seems this mapping to be persisted in the database file.
In fact, it looks like the mapping of `ref_image_idx` is inferred from threading here:
https://github.com/colmap/colmap/blob/389405b210b5aa175909d469692678b5341d9af8/src/colmap/mvs/patch_match_cuda.cu#L475 
If that is the case, it is probably not possible to recover the mapping if it is not persisted elsewhere.

So, what is the intended use-case of the `.vis` file? How can I find the 3D points that are seen by a specific input view?

**Comment by ahojnnes** [comment]
Yes, the idx is zero-based and is ordered as the images are stored in the images.txt/.bin of the sparse model. See src/colmap/mvs/model.h -> Model::ReadFromCOLMAP
