### ISSUE TITLE
gp3p: Invalid average

### ISSUE THREAD

**Issue by nosleduc** [colmap/colmap#205]
At the line 179, it seems that there is a small typo
const double lambda_1 = (lambda_1_1 + lambda_1_1) / 2;

I think the correct solution is
const double lambda_1 = (lambda_1_1 + lambda_1_2) / 2;

**Comment by ahojnnes** [comment]
That is correct. Thanks for the fix.

**Comment by ahojnnes** [comment]
Btw., this shouldn't make a big difference, since the two lambda values are very similar. Anyway, thanks for the fix!

**Comment by nosleduc** [comment]
Yes you are right, it does not change the result
