### ISSUE TITLE
Blue screen with image sizes > 1024

### ISSUE THREAD

**Issue by davidmarianovak** [colmap/colmap#206]
I have setup a machine with windows 7 and a nVidia 970 (and afterwards a 1060) GPU. On both GPU's I received a BSOD when I tried to perform dense matching with image sizes larger than 1024 (set in the Colmap GUI). With image sizes of 1024 the dense matching works without problems. With i.e. 2048, it starts the process and crashes after ~4 seconds (this is 100% reproducable). This happens on the pre-built zip as well as on the self built binary. The BSOD itself indicates a problem with nvlddmkm.sys.

Additionally, there seems to be strange behaviour with the 3.1 binary. When I try to perform feature matching, it tells me that it fails, because it ran out of GPU memory. This behaviour does not happen on the develop branch.

Now I know that this might indicate a hardware failure, but I am still a bit confused, why it works without a hitch when running it on image sizes <= 1024. Does the GPU get more stressed with larger image sizes or is there something else happening when the image sizes get larger?

**Comment by ahojnnes** [comment]
See https://colmap.github.io/faq.html#fix-gpu-freezes-and-timeouts-during-dense-reconstruction

**Comment by davidmarianovak** [comment]
This doesn't help - it merely extends the time until the unavoidable blue screen. It's not just the program crashing / driver resetting, but the whole computer is rebooting. (Again - could be a hardware failure)

**Comment by ahojnnes** [comment]
To what value did you set the delay? Maybe it needs to be even bigger? Otherwise, maybe a hardware failure, overheating, etc.
