### ISSUE TITLE
`Failed to load libEGL` when started from command line

### ISSUE THREAD

**Issue by tantalate** [colmap/colmap#2060]
I have this program (let's call it server.exe)  that will call colmap with commands like `COLMAP.bat feature_extractor` etc. and it works when server.exe is started by user. However, if I install server.exe as a service, the colmap commands will generate errors like `Failed to load libEGL`, `Failed to load opengl32sw.dll`. It looks like colmap is trying to start the GUI. I have no idea why because the commands are all the same, and I think the only difference may be the user and the ENVs.

**Expected behavior**
Commands like  `COLMAP.bat feature_extractor`  should not start GUI.

**Environment:**
 - OS: Windows 10/11
 - COLMAP Version 3.8

**Comment by ahojnnes** [comment]
Unless you specify use_gpu=false or use the CUDA version, feature extraction/matching will use the OpenGL version of SiftGPU by default.

**Comment by tantalate** [comment]
The errors are like this. These functions are from QT and I think colmap is trying to show the GUI, which should not be the right action, because I am starting it with `COLMAP.bat feature_extractor ...`
      Failed to load libEGL 
      QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
      Failed to load opengl32sw.dll
      Failed to load and resolve WGL/OpenGL functions
      Failed to load libEGL
      QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions

**Comment by ZJL-0422** [comment]
Hello, I encountered the same problem as you when starting the GUI. Have you resolved it? Thank you.

`Failed to load libEGL (找不到指定的模块。)
QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
Failed to load opengl32sw.dll (找不到指定的模块。)
Failed to load and resolve WGL/OpenGL functions
Failed to load libEGL (找不到指定的模块。)
QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
Failed to load opengl32sw.dll (找不到指定的模块。)
Failed to load and resolve WGL/OpenGL functions
QOpenGLWidget: Failed to create context
Failed to load libEGL (找不到指定的模块。)
QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
Failed to load opengl32sw.dll (找不到指定的模块。)
Failed to load and resolve WGL/OpenGL functions
QOpenGLWidget: Failed to create context`

**Comment by tantalate** [comment]
> 

是不是通过远程桌面或者服务打开的？
试一下CUDA版本
