### ISSUE TITLE
fix the poses of a part of images(treat them as ground truth poses), while optimizing the poses of the remaining images 

### ISSUE THREAD

**Issue by xuxumiao777** [colmap/colmap#2061]
**_Servus!_**
Thank you for your excellent work. Now I have a set of images which are required to get poses. But in my experiment setting, a part of images' poses are already got, they are treated as ground truth, However the other images' poses are unknown. So, I am wondering if there is a way to optimize the unknown poses in this colmap framework while keep the ground truth poses unchanged. Thanks:)

**Comment by tsattler** [comment]
You can use the `point_triangulator` to build a 3D model for the images where you have known poses. You can then use the resulting 3D model as input to the `mapper` and use the command line option to fix the camera poses of the images already in the reconstruction.

**Comment by xuxumiao777** [comment]
@tsattler I tried to use option --Mapper.fix_existing_images 1 to fix the ground truth poses when using mapper. However, when I have done this, I found the ground truth poses have been optimized and modified. So how it happens?
Here is my whole procedure:
![image](https://github.com/colmap/colmap/assets/107257126/50485fad-6d0a-4750-9482-33e422b82137)
I have two dataset folders one called flowers_split1 and the other called flowers_split2. The poses of flowers_split1 are known and then fixed, the poses are also calculated by colmap, so it has database.db and sparse model. The poses of flowers_split2 are unknown and to be calculated by colmap.
## I run in the following procedure.
### feature extraction
`colmap feature_extractor --database_path ./dataset/flowers_split1/database.db --image_path ./dataset/flowers_split2/images --image_list_path ./dataset/flowers_split2/image-list.txt --ImageReader.single_camera 1`
###feature matching
`colmap vocab_tree_matcher --database_path ./dataset/flowers_split1/database.db --VocabTreeMatching.vocab_tree_path ./dataset/vocab_tree_flickr100K_words256K.bin --VocabTreeMatching.match_list_path ./dataset/flowers_split2/image-list.txt`
###mapping
`colmap mapper --database_path ./dataset/flowers_split1/database.db --image_path ./dataset/flowers_split2/images --input_path ./dataset/flowers_split1/sparse/0 --output_path ./dataset/new2 --Mapper.fix_existing_images 1`


After that, I found the poses of flowers_split1 have been modified and not fixed as expected.

**Comment by xuxumiao777** [comment]
## Update
I have checked why translation has been changed but rotation remain unchanged. 
### First Try
One possible reason is that, the base coordinate has a common translation. In this situation every corresponding image has a common translation after using colmap. I have checked that the relative translation is not same for every corresponding pair. 
### Second Try
the other possibility is that, this whole procedure goes wrong. So I load the model in GUI. 
![image](https://github.com/colmap/colmap/assets/107257126/b96952de-4642-4820-a2fa-2f5707052243)
This is the model only using flowers_split1.

And then after using the procedure above. I got the final model.
![image](https://github.com/colmap/colmap/assets/107257126/982be070-715f-47ca-b151-a8a4b9980085)
From the images, I can say the pose estimation is correct and the poses of images in folder flowers_split1 stay unchanged. However, when I check the generated images.txt files, strange thing happens.
![image](https://github.com/colmap/colmap/assets/107257126/3bb6e7c1-6bc5-4c32-a7a8-7f488d1b43d7)
Quanterions are same, but translation is not.  option --Mapper.fix_existing_images 1 seems only works for rotation. :(

**Comment by ferreram** [comment]
During the SfM pipeline, Colmap normalizes the reconstruction after each global bundle adjustment test to avoid any numerical stability issue.  That is, the reconstruction gets scaled and translated after each global bundle adjustment step.  That is why the rotations are not changed but the translations are for the fixed existing images.  However, the relative translation between these existing images should still be correct up to a scale factor.

**Comment by ahojnnes** [comment]
Thanks @ferreram, confirmed.

**Comment by xuxumiao777** [comment]
Yes, I have found the normalization during BA in another issue. I have figured the scale out and then align the translation. Thanks for your answers and have a nice day.

**Comment by LeiShenOS** [comment]
> Yes, I have found the normalization during BA in another issue. I have figured the scale out and then align the translation. Thanks for your answers and have a nice day.

If it is convenient for you, please tell me how you do it, thank you!
