### ISSUE TITLE
Import .nvm format, did nvm_to_colmap.py once exist?

### ISSUE THREAD

**Issue by henrypearce4D** [colmap/colmap#2062]
I'm looking for a way to import .nvm format,  did nvm_to_colmap.py once exist?

Using ChatGPT, it referenced this script that may or may not have existed at one point in time...
https://github.com/colmap/colmap/blob/dev/scripts/python/nvm_to_colmap.py

Looking into it there was already a request a while back with this response;

> No out of the box solution but it should be relatively straightforward to write an importer from NVM. You can get inspired by the Reconstruction::ExportNVM method on which fields have to be populated. If you wrote such a method, it would be great to contribute it back to the repository for the benefit of others.

https://github.com/colmap/colmap/issues/983#issuecomment-694175501

I have no experience in this so unfortunately cannot write a method myself.

Any help would be much appreciated.

**Comment by tsattler** [comment]
I don't think the script ever existed and, as far as I know, there are currently no ready-made solutions for this problem.

**Comment by henrypearce4D** [comment]
Thanks for the info.

So am I correct in saying the only import option is a colmap model files and the 'import model from' which is .ply?

**Comment by tsattler** [comment]
Yes.
