### ISSUE TITLE
Issue when execute model_converter in command line

### ISSUE THREAD

**Issue by zouh520sdo** [colmap/colmap#207]
I successfully executed feature_extractor, exhaustive_matcher, and mapper.

And now I want to use model_converter to convert Colmap into NVM format. 

My command line is 

model_converter --project_path test/sparse/0/project.in --input_path test/sparse/0 --output_path test/output --output_type 'NVM'

After executing this line, it throwed me an error,

ERROR: Failed to parse options unrecognised option 'database_path'.

So, what is the correct way to execute model_converter command?

**Comment by ahojnnes** [comment]
The model_converter does not take a "database_path" argument but you provided that in your project.ini. Just omit the --project_path argument and the command should run fine. Note, however, that converting to NVM only works for the SIMPLE_RADIAL camera model.

**Comment by zouh520sdo** [comment]
You are right. I works now. Thank you so much!
