### ISSUE TITLE
BundleAdjustmentConstantPoseCostFunction inconsistency

### ISSUE THREAD

**Issue by JanQuenzel** [colmap/colmap#209]
Hi, 
I found a small inconsistency in base/src/cost_function.h in BundleAdjustmentConstantPoseCostFunction.
This [line](https://github.com/colmap/colmap/blob/b44473edb70704c5f82a5dd181015d7c5d767f1e/src/base/cost_functions.h#L104) seems to be incorrect.
In [<ceres/rotation.h>](https://github.com/ceres-solver/ceres-solver/blob/cc73c77d50d0451646faa52a3922b8b85e963ad8/include/ceres/rotation.h#L36) it is said to be w,x,y,z or else the ceres rotate functions won't work correctly. 
This has probably skipped the test cases in [base/src/cost_function_test.cc](https://github.com/colmap/colmap/blob/b44473edb70704c5f82a5dd181015d7c5d767f1e/src/base/cost_functions_test.cc#L58), because the Eigen::Vector4d created by ComposeIdentityQuaternion() seems to contain [w,x,y,z] as opposed to a Eigen::Quaterniond which uses [x,y,z,w].

Greetings, Jan

**Comment by ahojnnes** [comment]
Thanks. I will have a look in a week when I return from my travels.

**Comment by ahojnnes** [comment]
It turns out this was not a bug but a confusing variable naming in the cost function source code. COLMAP uses W, X, Y, Z ordering everywhere and not the Eigen ordering X, Y, Z, W. Everything should work as expected and I fixed the variable names. Thanks for reporting this inconsistency.
