### ISSUE TITLE
Support special characters in the database path

### ISSUE THREAD

**Issue by MarwinSc** [colmap/colmap#2090]
**Describe the bug**
Using non ascii characters in the path to the database throws an SQLite error:
SQLite error [C:\dev\vcpkg-ahojnnes\buildtrees\colmap\src\6ae098620c-66eac7d3f9.clean\src\base\database.cc, line 264]: unable to open database file

Unfortunately I need to support non ascii characters, e.g. ä,ö,ü,ß contained in the path to the database and can't get it to work. All the other colmap related directories allow for special characters.

**To Reproduce**
I'm running colmap via the command-line interface using python 3.9, for instance: 
```python
colmap_environment = {'PATH': colmap_libs + ';' + os.environ['PATH'], 'QT_PLUGIN_PATH': colmap_plugins + ';'}
args = [colmap_exe, 'database_creator', '--database_path', database_path]
returncode = subprocess.run(args, env=colmap_environment).returncode
```
Where database_path can look like: "C:\path\to\colmap\directory\my ä dir\database.db"

I know this isn't a problem for most people but if someone got a hint what I could try I'd be super greatful!

**Environment:**
 - OS: Windows 10
 - COLMAP Version 3.8 (pre-build)

**Comment by whuaegeanse** [comment]
Only UTF8 is supported by colmap.
@MarwinSc

**Comment by MarwinSc** [comment]
I thought that utf-8 supports the mentioned special characters, as well as many more. Am I understanding something wrong here, could you ellaborate?
For the '--image_path' or '--output_path' paths containing special chracters like 'ä' seem to work fine.

**Comment by ahojnnes** [comment]
@MarwinSc In theory, this should be supported, but have never tried this explicitly. There may be an issue in how you represent the "database_path" in Python (bytes vs. str) and whether you use Python 2 or 3. You could double check whether supplying a database path with special characters from a console works to narrow down the problem.

**Comment by MarwinSc** [comment]
When I try to execute the database_creator via command promp with the following command, I get the same SQLite error as in the origional post: SQLite error [C:\dev\vcpkg-ahojnnes\buildtrees\colmap\src\6ae098620c-66eac7d3f9.clean\src\base\database.cc, line 264]: unable to open database file
```
colmap database_creator --database_path C:\path\to\colmap\directory\myädir\database.db
```
And again also from cl something like the following command where only the image_path contains special characters works fine.
```
colmap feature_extractor --image_path  C:\path\to\colmap\directory\myädir\images --database_path  C:\path\to\colmap\directory\mynormaldir\database.db
```
I've tried both bytes and str from Python 3, not sure what to try next. Could it be SQLite related? Thanks for the help!

**Comment by ahojnnes** [comment]
I am using the following function:
```
SQLITE_API int sqlite3_open_v2(
  const char *filename,   /* Database filename (UTF-8) */
  sqlite3 **ppDb,         /* OUT: SQLite db handle */
  int flags,              /* Flags */
  const char *zVfs        /* Name of VFS module to use */
);
```
... so I would expect this to just work. I am not sure if the bytes of the filename have to be piped in a special way. It would need some debugging, that is not up on my priority list, to be honest.

**Comment by MarwinSc** [comment]
That is understandable, but thanks anyway. Obviously it isn't hard to work around the problem for now, but I will have to get back to the issue later on. I guess this could be closed as not planned for now. 

Also thank you for the great work, really cool project! :)
