### ISSUE TITLE
Installation Error (Ubuntu 20.04)

### ISSUE THREAD

**Issue by lucascassiano** [colmap/colmap#2097]
**Describe the bug**
I'm trying to install COLMAP on a Linux server, 

**To Reproduce**

1. I followed the [Install steps]( https://colmap.github.io/install.html#linux) for Linux with CUDA
2. I installed `gcc-10` and included the environment variables 
```sh
sudo apt-get install gcc-10 g++-10
export CC=/usr/bin/gcc-10
export CXX=/usr/bin/g++-10
export CUDAHOSTCXX=/usr/bin/g++-10
```
3. All commands up to ```cmake .. -GNinja``` worked.
4. When running ```ninja```, I get the error:
```sh
../src/colmap/mvs/cuda_texture.h(93): error: namespace "std" has no member "make_unique"
    auto array = std::make_unique<CudaArrayLayeredTexture<T>>(
                      ^

../src/colmap/mvs/cuda_texture.h(93): error: type name is not allowed
    auto array = std::make_unique<CudaArrayLayeredTexture<T>>(
                                  ^

../src/colmap/mvs/cuda_texture.h(116): error: namespace "std" has no member "make_unique"
    auto array = std::make_unique<CudaArrayLayeredTexture<T>>(
                      ^

../src/colmap/mvs/cuda_texture.h(116): error: type name is not allowed
    auto array = std::make_unique<CudaArrayLayeredTexture<T>>(
                                  ^

../src/colmap/mvs/cuda_texture.h(117): warning #174-D: expression has no effect
        texture_desc, width, height, depth);
        ^

Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

4 errors detected in the compilation of "../src/colmap/mvs/patch_match_cuda.cu".
[50/205] Building CXX obje...ors.dir/absolute_pose.cc.o
ninja: build stopped: subcommand failed.
```

**Expected behavior**
Full installation

**Screenshots**
<img width="718" alt="image" src="https://github.com/colmap/colmap/assets/5508142/d849e909-2ece-4157-90cb-c8eb5cdc0f42">

**Environment:**
 - OS: Ubuntu 20.04
 - CUDA:  release 12.2, V12.2.91
 - COLMAP Version 3.8-dev

**Comment by JerryDeepl** [comment]
replace std::make_unique<T>(...) with std::unique_ptr<T>(new T(...))

**Comment by AmandineBtto** [comment]
Hello, 

Here I described a way to fix that I found out: https://github.com/colmap/colmap/issues/1878#issuecomment-1674458782

**Comment by lucascassiano** [comment]
Hi @AmandineBtto. I got a different error now: 
```
CMake Error at CMakeLists.txt:310 (install):
  install TARGETS given target "colmap_ui" which does not exist.
```

I'm installing this on a server, so no UI/Display is available. Any command I can add to the build to avoid compiling for a UI?

**Comment by AmandineBtto** [comment]
Hi @lucascassiano. 
I'm sorry but I'm not part of colmap dev team and I haven't encountered this issue so I can't really help you. Maybe you can modify the CMakeLists.txt file. I saw in line 70 the option GUI_ENABLED, but I don't know more. Good luck !
