### ISSUE TITLE
Questions about mapper from existing model

### ISSUE THREAD

**Issue by is03wlei** [colmap/colmap#210]
1. Should I get a model only including new images or including all images?
   When I imported a model of 4.3GB and registered 100 new images, I got a model of 17MB.

2. Why some images can't be found from model-with-new-images, while from mapper's log, they should be registered.

my script:

PROJECT_PATH=$1
IMAGE_PATH=$2
IMPORT_PATH=$3

feature_extractor \
   --database_path $PROJECT_PATH/database.db \
   --image_path $IMAGE_PATH \
   --ImageReader.single_camera 1 \
   --ImageReader.default_focal_length_factor 0.8941685 \
   --SiftExtraction.max_image_size 4100 \
   --SiftGPUExtraction.index 0 \
   --SiftCPUExtraction.num_threads 20 > feature_extractor.log

ls -1 $IMAGE_PATH > image_list.txt

vocab_tree_matcher \
   --database_path $PROJECT_PATH/database.db \
   --SiftMatching.gpu_index=0,1,2,3 \
   --SiftMatching.max_num_matches 8192 \
   --VocabTreeMatching.vocab_tree_path ./vocab_tree-1048576.bin \
   --VocabTreeMatching.match_list_path ./image_list.txt \
   --SiftMatching.num_threads 20 > vocab_tree_matcher.log

mkdir model-with-new-images

mapper \
    --database_path $PROJECT_PATH/database.db \
    --image_path $IMAGE_PATH \
    --import_path $IMPORT_PATH \
    --export_path $PROJECT_PATH/model_with_new_images \
    --Mapper.snapshot_images_freq 1000 \
    --Mapper.ba_global_images_ratio 1.2 \
    --Mapper.ba_global_points_ratio 1.2 \
    --Mapper.ba_global_max_num_iterations 20 \
    --Mapper.ba_global_max_refinements 3 \
    --Mapper.ba_global_points_freq 200000 \
    --Mapper.ba_global_pba_gpu_index 0 \
    --Mapper.num_threads 20 > mapper.log

**Comment by ahojnnes** [comment]
1. The new model should contain all images with old and new images. 

2. Could it be that they were filtered after global bundle adjustment? You can check that in the logs. To avoid this filtering, you can relax the filtering thresholds in the options, e.g. filter_min/max_focal_length_ratio and filter_max_extra_param.

Please report back whether this answers your questions. Thanks.

**Comment by is03wlei** [comment]
This time mapper registered previously registered images again. It has registered more than 7000 images.
I was so upset. The mapper has been running for several days. But I have only 100 new images.

**Comment by ahojnnes** [comment]
I cannot follow. If you provide me with the log, I can have a look.

**Comment by ahojnnes** [comment]
Closing this due to lack of feedback, feel free to reopen. Thanks.
