### ISSUE TITLE
About [JPEG_EXIFROTATE] in FreeImage

### ISSUE THREAD

**Issue by json87** [colmap/colmap#2104]
Thanks for sharing this SfM toolkit.

Recently, I tried to process one UAV dataset and found that the Bitmap::Read function uses the option [JPEG_EXIFROTAT] to load an image. I wonder whether or not this option is used to rotate the bitmap or just change the EXIF data.

FIBITMAP* fi_bitmap = FreeImage_Load(format, path.c_str(), JPEG_EXIFROTATE);

The dataset is captured by the same camera but rotated 90 degrees, which causes the dim error during feature detection.

![image](https://github.com/colmap/colmap/assets/17582213/14edab59-9126-4bcf-8156-f8446ec53e7f)

**Comment by ahojnnes** [comment]
This option is intentionally not used, otherwise it is difficult to share camera parameters across a dataset, just because you captured the image in different orientations wrt gravity. I hope that makes sense.

**Comment by json87** [comment]
Yes, as you mentioned, some images are captured by rotating the camera. Thus, the orientation in the EXIF is not normal. Using the flag JPEG_EXIFROTATE, FreeImage would rotate the image while reading it. This causes the dimension inconsistent error in ColMap. Thus, I think the flag should be removed to read the image as its actual size.

**Comment by ahojnnes** [comment]
I don't see the flag enabled anywhere in the codebase (dev branch). Please let me know, if I missed something. Thanks.

**Comment by json87** [comment]
Thanks for your reply.  I have not checked the updates for a long time, and I found that the JPEG_EXIFROTATE has been removed from the repository.

Sorry for the mistake.
