### ISSUE TITLE
 Check failed: bundle_adjuster.Solve(&reconstruction) 

### ISSUE THREAD

**Issue by HarshaMupparaju** [colmap/colmap#2106]
I'm trying to do sparse reconstruction using 3 images as input using COLMAP CLI, the terminal output is as below. The feature extraction and feature matching happens correctly, but the point_triangulator doesn't seem to be working 
```
Colmap feature_extractor --database_path ../../../tmp/database.db --image_path ../../../tmp/images --ImageReader.single_camera 1
==============================================================================
Feature extraction
==============================================================================

Processed file [1/3]
  Name:            0001.jpg
  Dimensions:      2704 x 2028
  Camera:          #1 - SIMPLE_RADIAL
  Focal Length:    3244.80px
  Features:        1836
Processed file [2/3]
  Name:            0002.jpg
  Dimensions:      2704 x 2028
  Camera:          #1 - SIMPLE_RADIAL
  Focal Length:    3244.80px
  Features:        1877
Processed file [3/3]
  Name:            0003.jpg
  Dimensions:      2704 x 2028
  Camera:          #1 - SIMPLE_RADIAL
  Focal Length:    3244.80px
  Features:        2923
Elapsed time: 0.004 [minutes]
colmap exhaustive_matcher --database_path ../../../tmp/database.db

==============================================================================
Exhaustive feature matching
==============================================================================

Matching block [1/1, 1/1] in 0.077s
Elapsed time: 0.002 [minutes]
colmap point_triangulator --database_path ../../../tmp/database.db --image_path ../../../tmp/images --input_path ../../../tmp/sparse/0 --output_path ../../../tmp/sparse/0 --Mapper.tri_ignore_two_view_tracks 0 --Mapper.num_threads 16 --Mapper.init_min_tri_angle 4 --Mapper.multiple_models 0 --Mapper.extract_colors 0

==============================================================================
Loading model
==============================================================================


==============================================================================
Loading database
==============================================================================

Loading cameras... 1 in 0.000s
Loading matches... 2 in 0.000s
Loading images... 3 in 0.000s (connected 3)
Building correspondence graph... in 0.000s (ignored 0)

Elapsed time: 0.000 [minutes]


==============================================================================
Triangulating image #0 (0)
==============================================================================

  => Image sees 0 / 0 points
  => Triangulated 0 points

==============================================================================
Triangulating image #1 (1)
==============================================================================

  => Image sees 0 / 48 points
  => Triangulated 0 points

==============================================================================
Triangulating image #2 (2)
==============================================================================

  => Image sees 0 / 108 points
  => Triangulated 0 points

==============================================================================
Retriangulation
==============================================================================

  => Completed observations: 0
  => Merged observations: 0

==============================================================================
Bundle adjustment
==============================================================================

F0810 15:57:35.477456 2272894 sfm.cc:473] Check failed: bundle_adjuster.Solve(&reconstruction) 
*** Check failure stack trace: ***
    @     0x7f1b276d7b03  google::LogMessage::Fail()
    @     0x7f1b276df9d1  google::LogMessage::SendToLog()
    @     0x7f1b276d77c2  google::LogMessage::Flush()
    @     0x7f1b276d978f  google::LogMessageFatal::~LogMessageFatal()
    @     0x55ddebc1f0b0  colmap::RunPointTriangulatorImpl()
    @     0x55ddebc14acc  colmap::RunPointTriangulator()
    @     0x55ddebbdb499  main
    @     0x7f1b25429d90  (unknown)
    @     0x7f1b25429e40  __libc_start_main
    @     0x55ddebbde3e5  _start
Aborted (core dumped)
```

This is the contents of cameras.txt file 
```1 FULL_OPENCV 2704 2028 731.3691627864987 731.3691627864987 676.0 507.0 0 0 0 0 0 0 0 0 ```

and this is what's there in images.txt file
```0 -0.04589858745133139 0.9573113835789684 0.028740899845485723 0.2839404782981205 -5.068010824121289 -1.3012192130074425 -2.1138844709373803 1 0000.jpg

1 -0.050892069433813296 0.9615592318019909 -0.012773632782978593 -0.2695378921610741 3.4895918839319537 -1.354012583370535 -1.2195196405459783 1 0001.jpg

2 -0.021734547771511594 0.9985325003016441 0.0017843407944345157 -0.04957087252050525 0.19529270686515762 1.4237902150744526 -0.4349119352814836 1 0002.jpg
```

and the points3D.txt is empty as mentioned in the documentation. 

Theses are the contents of database.db file, I don't understand why the sparse reconstruction doesn't work even though there are matches present in the database.db file as shown below.

![Screenshot from 2023-08-10 16-19-12](https://github.com/colmap/colmap/assets/58979824/e20beba6-43c8-4745-9316-e9656fb1eab3)

![Screenshot from 2023-08-10 16-20-57](https://github.com/colmap/colmap/assets/58979824/cff82edb-2aec-45ba-ac65-74a1450a9c25)

![Screenshot from 2023-08-16 12-12-49](https://github.com/colmap/colmap/assets/58979824/dc522a69-dc98-41f0-beca-67f19474bb2e)

@ahojnnes @tsattler Any help to get past this error?

**Comment by tsattler** [comment]
Did you look at the input model to see whether the camera poses are meaningful? Are the input poses accurate enough?

**Comment by vnmsklnk** [comment]
I have the same problem. I checked the poses with the GUI and they look quite correct. I attach the contents of the model
[sparse_manual.zip](https://github.com/colmap/colmap/files/12327608/sparse_manual.zip)

**Comment by json87** [comment]
The camera parameters or the pose of database images are not right as there are no 3D points triangulated.

**Comment by HarshaMupparaju** [comment]
Linking your comment on a closed issue where I have explained the same problem here #https://github.com/colmap/colmap/issues/1657#issuecomment-1679693488. The poses are accurate, they were provided with the dataset itself, they were of NeRF format [down, right, backwards] and I have converted them to COLMAP format [right, down, forwards]. My camera extrinsics and intrinsics are accurate I think. The matches are meaningful as seen below:

Matches:

![matches_1_2](https://github.com/colmap/colmap/assets/58979824/f1698f83-f6b7-4f95-bca8-e33aca4e9f71)
![matches_3_1](https://github.com/colmap/colmap/assets/58979824/60cefbc8-56e9-4ce8-9db4-20e218afa7dc)
![matches_3_2](https://github.com/colmap/colmap/assets/58979824/fbc64003-ae38-4897-a726-918a26fbf58f)

their corresponding Two-view-geometries respectively:
![two_view_geometries_1_2](https://github.com/colmap/colmap/assets/58979824/3c3048d1-a55a-4721-ac6a-4818fcc36e4d)
![two_view_geoemtries_3_1](https://github.com/colmap/colmap/assets/58979824/56cac512-7348-41d3-985a-cfd2a92f9ed2)
![two_view_geometries_3_2](https://github.com/colmap/colmap/assets/58979824/310b1895-6724-4b1c-881f-9733d49f7ee0)

The intrinsics shown in my original issue are wrong, now I have edited and fixed the uploaded the correct intrinsics in the original issue. 

I have tried giving the 3 images directly to COLMAP for automatic reconstruction, even i this case the sparse folder of the workspace is empty. Attaching the log of this for reference.
[log_automatic_reconstruction.txt](https://github.com/colmap/colmap/files/12356453/log_automatic_reconstruction.txt)

**Comment by tsattler** [comment]
The matches for the first image pair do not look that meaningful (see also what survives after geometry estimation). Looks like you only get good matches between the "middle" image and each of the other two, but not between the two "outer" views. If I remember correctly, Colmap ignores tracks consisting only of two images unless a corresponding flag is explicitly set.

Also, it looks like you have few matches. You might want to play around with the parameters specifying how many inliers are necessary.

**Comment by HarshaMupparaju** [comment]
The issue is solved, it was a camera poses and images mismatch. i haven't taken into consideration the downsampling of images when setting up the camera intrinsics.
