### ISSUE TITLE
Image::HasTvecPrior() and Image::HasQvecPrior() are incorrectly returning true

### ISSUE THREAD

**Issue by gpanders** [colmap/colmap#211]
With Eigen 3.3, the member variables `tvec_prior_` and `qvec_prior_`, which are initialized as `Eigen::Vector3d` and `Eigen::Vector4d` respectively, have values approximately equal to zero. The `HasTvecPrior()` and `HasQvecPrior()` methods check for the sum of the vectors to be not NaN, which is returning true when `tvec_prior_` and `qvec_prior_` are never initialized.

I verified this with the following test code:
```cpp
#include <Eigen/Core>
#include <iostream>

int main(int argc, char ** argv) {
  Eigen::Vector3d v;

  std::cout << v.sum() << std::endl;

  return 0;
}
```
```console
$ ./a.out
6.95272e-310
```

Could we instead use:

```cpp
bool Image::HasTvecPrior() { return tvec_prior_.sum() > 1e-15; }
```

or something similar?

The obvious drawback here is that if `tvec_prior_` is _supposed_ to be `[0, 0, 0]`, this will return false (not an issue for `qvec_prior_` since `[0, 0, 0, 0]` is an invalid quaternion).

**Comment by ahojnnes** [comment]
They should be initialized to NaN in the Image constructor and the feature extraction code. Where do you see that it gets initialized to zero?

**Comment by gpanders** [comment]
I saw the initialization in the constructor after I posted this issue; in fact, I don't think this is actually a problem (I think it was a bug elsewhere in the code I had written).

I'll close the issue. Thanks.

**Comment by gpanders** [comment]
Reopening because I think this does need to be addressed, I was just looking in the wrong place.

I see that the constructor in Image initializes `qvec_prior_` and `tvec_prior_` to NaN values; however, when the images are loaded from the database in `DatabaseCache::Load`, these values are being assigned to 0. Thus, `HasQvecPrior()` and `HasTvecPrior()` are returning true when they shouldn't be.

**Comment by ahojnnes** [comment]
Thanks for double checking. I will look into this when I get back to the office in a few days.

**Comment by ahojnnes** [comment]
This is fixed now. The underlying reason for the behavior was that SQLite stores NaNs as NULL and, when reading from the database, NULLs were loaded as 0. Checkout the latest commit in the `dev` branch.

**Comment by ahojnnes** [comment]
Thanks for reporting this issue.
