### ISSUE TITLE
Custom matcher not available from command line?

### ISSUE THREAD

**Issue by tfwittwer** [colmap/colmap#2119]
Am I right that the custom matcher (where one manually specifies images to be matched with each other in a text file) is not available from the command line, only from the GUI? Would it be possible to expose this as command line tool as well?

**Comment by tsattler** [comment]
It is available via the `matches_importer`.

**Comment by tfwittwer** [comment]
Thanks! I assume the --match_list_path argument should then refer to the text file containing the filenames to be matched against each other?

**Comment by tsattler** [comment]
Yes, indeed.
