### ISSUE TITLE
No convergence

### ISSUE THREAD

**Issue by ckochipm** [colmap/colmap#212]
I'm trying to register images from a sequential matching. The matches look good, but the registration process somehow doesn't succeed / converge. I attached a log file, can you figure out what happens there? Do I need more overlap between the images or more perspective variation?
Thanks in advance!
[log_registration_fails.txt](https://github.com/colmap/colmap/files/1257264/log_registration_fails.txt)

**Comment by ahojnnes** [comment]
Hi, I will need to see a few of the images to make a statement about this. Best, Johannes

**Comment by ckochipm** [comment]
Hi,
I already sent you data of this dataset in a past issue, don't know if you remember. In general it is all aerial photos for photogrammetry. One example here:
![screenshot_20170830_162433](https://user-images.githubusercontent.com/30599050/29877485-08c3ce80-8da0-11e7-8d8b-01d9ada02c26.png)

**Comment by ahojnnes** [comment]
I don't have the data anymore. If I should have a look, you would have to send it again. Thanks.

**Comment by ckochipm** [comment]
sent you a subset of 20 images to your eMail... any help would be appreciated. Thank you!

**Comment by ahojnnes** [comment]
I am not sure what you did but I get a perfectly fine reconstruction from those 20 images. See below. It seems you are using many more images when looking at the log file.

![screenshot](https://user-images.githubusercontent.com/134307/29970966-e093b00a-8f26-11e7-847a-c97d2f5d995a.png)

**Comment by ckochipm** [comment]
hey! I just sent you a subset as the pictures are already pretty large. it's all pretty regular sequential images, so I thought taking the full dataset or just a subset of subsequent images makes no big difference. In total it's 275 images, quite some more really. Could that make it harder? Or does it require any special settings?

**Comment by ahojnnes** [comment]
Maybe you can try to manually set the initial images in the reconstruction settings. Otherwise, try to increase the sequential match overlap?

**Comment by ahojnnes** [comment]
Closing this due to lack of feedback, feel free to reopen. Thanks.
