### ISSUE TITLE
Why DLT is not used to estimate camera intrinsics during image_registrator?

### ISSUE THREAD

**Issue by kvuong2711** [colmap/colmap#2128]
Dear authors,

Looking at the source code for [image_registrator](https://github.com/colmap/colmap/blob/main/src/colmap/estimators/pose.cc#L117-L154), it seems that the focal length and camera intrinsics are estimated using RANSAC given 2D-3D correspondences (e.g., with a list of candidates for different focal lengths and search for the best intrinsics candidate). However, I wonder why DLT + RANSAC is not being used to estimate the intrinsics directly (randomly sample at least 6 correspondence pairs, then estimate P matrix using DLT then decompose into intrinsics and extrinsics). Is this due to accuracy issue? Is there any related resources about this?

Thanks!

**Comment by tsattler** [comment]
The DLT algorithm requires more input correspondences than P3P (6 vs. 3), resulting in more RANSAC iterations (especially for low inlier ratios). Its solution is degenerate if all 6 points are on a plane. Furthermore, the estimated intrinsics can be quite off in some situations (e.g., matches in small area of image). In general, P3P seems more stable.

**Comment by kvuong2711** [comment]
Thank you!
