### ISSUE TITLE
how to use known poses for reconstruction

### ISSUE THREAD

**Issue by ForLoveandPeace** [colmap/colmap#2129]
Hi, I have read the FAQ and some issues. But I really cannot get how to do this. 
I have made my own images.txt and cameras.txt. But now how can I generate database.db? I use the script/python/database.py to generate db. But when I extract feature from images, it didn't use my camera param and then send error in matching. Could you give a more detailed step for reconstruction with known poses?
Thank you!

**Comment by tfwittwer** [comment]
You can use the database_creator command to create an empty database. To use known camera parameters you need to supply them during feature extraction as part of the --ImageReader.camera_params argument (enclosed between apostrophes, separated by commas). If you want to use the spatial matcher, you also need to write the pose information into the database and make sure that the image Ids match those in the images.txt file.

**Comment by ForLoveandPeace** [comment]
Thanks for your reply! I use the code below to create db. I don't know if I am right.    
    db = COLMAPDatabase.connect(args.database_path)

    db.create_tables()

    camera_data = []
    camera_txt = './cameras.txt'
    with open(camera_txt, 'r') as file:
        for line in file:
            if line[0] == '#':
                continue
            camera_data.append(line.strip().split())

    for camera_info in camera_data:
        camera_id = int(camera_info[0])
        model = camera_info[1]
        width = int(camera_info[2])
        height = int(camera_info[3])
        params = [float(param) for param in camera_info[4:]]
        
        camera_id = db.add_camera(model,width,height,np.array(params))

    images_data = []
    images_txt = './images.txt'
    with open(images_txt, 'r') as file:
        for line in file:
            images_data.append(line.strip().split())

    images = []
    for image_info in images_data:
        image_id = int(image_info[0])
        q = [float(value) for value in image_info[1:5]]
        p = [float(value) for value in image_info[5:8]]
        camera_id = int(image_info[8])
        image_path = image_info[9]
        image_id = db.add_image(image_path, camera_id, q, p)

    db.commit()
    db.close()

And the feature extractor didn't use the cameras.txt. It extract a image with a new id.

**Comment by ForLoveandPeace** [comment]
thanks for your help! I have known how to reconstruct(maybe I should call it triangulate) with known poses.

**Comment by mattiasmar** [comment]
@ForLoveandPeace can you share your skript on how to go from know camera poses and raw images to 3D reconstruction? 
Thanks!
