### ISSUE TITLE
{macOS} Link problem w/freeimage

### ISSUE THREAD

**Issue by asmaloney** [colmap/colmap#213]
Not sure what I'm doing differently from the previous version I built, but the latest release isn't linking freeimage properly for me anymore.

Here's my cmake (3.9.1) config output which (except the warnings) looks good:
```
CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:771 (message):
  Imported targets not available for Boost version 106500
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:875 (_Boost_COMPONENT_DEPENDENCIES)
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:1503 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:58 (find_package)

(...same warning several times...)

Boost version: 1.65.0
Found the following Boost libraries:
  program_options
  filesystem
  regex
  system
  unit_test_framework
Found Eigen3
  Includes : /Users/maloney/dev/include/eigen3
Found FreeImage
  Includes : /Users/maloney/dev/include
  Libraries : /Users/maloney/dev/lib
Found Glog
  Includes : /Users/maloney/dev/include/glog
  Libraries : /Users/maloney/dev/lib
Found installed version of Eigen: /Users/maloney/dev/share/eigen3/cmake
Found required Ceres dependency: Eigen version 3.3.4 in /Users/maloney/dev/include/eigen3
Found required Ceres dependency: glog
Found installed version of gflags: /Users/maloney/dev/lib/cmake/gflags
Detected gflags version: 2.2.1
Found required Ceres dependency: gflags
Found Ceres version: 1.13.0 installed in: /Users/maloney/dev with components: [LAPACK, SuiteSparse, SparseLinearAlgebraLibrary, CXSparse, SchurSpecializations]
Found Glew
  Includes : /Users/maloney/dev/include/
  Libraries : /Users/maloney/dev/lib
Found Qt 5.10.0
Build type not specified, using RelWithDebInfo
Disabling OpenMP support
Disabling link-time optimization (-flto)
Disabling CUDA support
Enabling OpenGL support
Disabling profiling support
Configuring done
```
(Despite having LTO_ENABLED on in the cmake config, I'm getting "Disabling link-time optimization (-flto)" - but that's another issue.)

When I generate I get this:
```
WARNING: Target "vocab_tree_retriever" requests linking to directory "/Users/maloney/dev/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "vocab_tree_builder" requests linking to directory "/Users/maloney/dev/lib".  Targets may link only to libraries.  CMake is dropping the item.
...
```

and when building it fails to link with freeimage:
```
...
[ 54%] Built target sfm
[ 60%] Built target ui
[ 62%] Linking CXX executable warp_test
Undefined symbols for architecture x86_64:
  "_FreeImage_Allocate", referenced from:
      colmap::Bitmap::Allocate(int, int, bool) in libutil.a(bitmap.cc.o)
...
```

I've looked through the generated Makefiles and don't see it trying to link with freeimage anywhere.

I've checked that I have all my paths set properly and the libs are in the right place.

Any ideas?

**Comment by ahojnnes** [comment]
I guess you are not linking against the FreeImage library. Can you double check the linked libraries by running ``make VERBOSE=1``?

**Comment by asmaloney** [comment]
> I guess you are not linking against the FreeImage library.

Yes that's the whole point of this report. :-)

The config thinks it's fine (see above), but when cmake generates the makefiles, they don't contain any linking to freeimage (or glew now that I look at it). So whatever part of the cmake files that is supposed to add the linkage for these libs isn't working.

(I'm using the same configuration I did with the previous release - which did work.)

Thanks Johannes.

**Comment by asmaloney** [comment]
(Using cmake 3.9.1 GUI)

I've found the two sources of confusion:

1) The options presented by default aren't guiding the user in the right direction.

When initially configuring it, it presents two things to configure: `FREEIMAGE_INCLUDE_DIRS` and `FREEIMAGE_LIBRARIES`.

In my experience when configuring 3rd party libs with cmake, you point at "where do I find the includes" and "where do I find the libraries" and the scripts figure everything out. That is what I thought these were. They aren't.

`FREEIMAGE_LIBRARIES` is supposed to be... what? A list of libraries? How do I know what files are required for freeimage?

Digging into the cmake scripts, I found `FREEIMAGE_LIBRARY_DIR_HINTS` which is what you actually use to configure this - you don't set `FREEIMAGE_LIBRARIES` - it will be generated by the Find*.cmake script.

2) Despite passing a path for `FREEIMAGE_LIBRARIES`, configuration succeeded.

It didn't actually find the library files, but it claimed that it did - `Found FreeImage`.

My suggestions:

1) Show `FREEIMAGE_LIBRARY_DIR_HINTS` by default. It's what anyone trying to configure something would expect.

2) In FindFreeImage.cmake make sure it has actually found the required library files.

**Note** that these confusions exist with all the libs that include their own Find*.cmake file: FreeImage, Glew, and Glog.

Thanks Johannes.

**Comment by ahojnnes** [comment]
Thanks for the valuable feedback, the variables are now displayed to the user with the latest commit.

**Comment by k05yra** [comment]
I've installed both homebrew and freimage on my macOS 14.2.1, ensuring that the paths are correct. I'm running Blender 4.2.1 with a topography API key. However, whenever I load a basemap, all I see is what's pictured below. Sometimes, the entire application freezes and crashes. Any tips on how to fix this?  
<img width="1440" alt="Screenshot 2024-08-21 at 4 13 05 AM" src="https://github.com/user-attachments/assets/7cc8824c-18d1-41a9-895e-c02a5356c90c">
