### ISSUE TITLE
Obtaining camera poses associated with point

### ISSUE THREAD

**Issue by leniumc** [colmap/colmap#2134]
After running the dense reconstruction in Colmap, I would like to estimate the normals at each point of the generated point cloud for downstream tasks. I'm currently doing this using the Open3D library which only requires taking the point cloud as input. However, in many cases, the normals are oriented incorrectly (pointing inwards). If we know which camera poses each point is visible from, we can reorient the normals towards the camera locations to correct them. In the Colmap GUI, it seems like we do have access to this data, since clicking on a camera pose highlights the points that it sees, but I'm not sure how I could easily extract this data (in a Python program for example). Any suggestions on where to look? Thanks!

**Comment by tsattler** [comment]
This information is stored in the `.vis` files, see https://github.com/colmap/colmap/blob/main/src/colmap/mvs/fusion.h#L166-L180

**Comment by leniumc** [comment]
Got it! Also, I read that the image indices in the `.vis` file correspond to the order of the images in the `image.bin` file, but how are the points ordered in the `.vis` file? Should I expect them to be in the same order as in the `.ply` files generated by the dense reconstruction? Thanks!

**Comment by leniumc** [comment]
Ah nvm I found the Python script for reading the files [here](https://github.com/colmap/colmap/blob/main/scripts/python/read_write_fused_vis.py). Should work fine!
