### ISSUE TITLE
Colmap GUI Database Management not Updating

### ISSUE THREAD

**Issue by quitmeyer** [colmap/colmap#2141]
**Describe the bug**
Updated camera information not appearing in the GUI's "Database Management" database viewer.
![image](https://github.com/colmap/colmap/assets/742627/2f35e2f8-890c-4b6b-bf6c-9bfa790c1c66)

 The GUI does not appear to be correctly showing the intrinsics parameters estimated for cameras a and b.  But when I export the model as text and open cameras.txt, the parameters look sane / good.

**To Reproduce**

I open the colmap GUI. 

I have two sets of images in a "camA" and "camB" folder

I run feature extraction with OPENCV model, and choose "shared per sub folder"

I then run Feature Extraction

At this point if i look in the "Database Management" and look at cameras, i will see two cameras with default parameters.

![image](https://github.com/colmap/colmap/assets/742627/ed7e80a4-c3e7-450f-b3e3-461a8dfe87e0)

Then i go to Reconstruction Options and tell it to refine the focal length, principal point, and extra params

![image](https://github.com/colmap/colmap/assets/742627/8e64b5e8-1469-43cd-a33f-de851612c8e6)

Then i run the reconstruction.

If i click on an individual camera, i can see its new parameters (cool!), but if i look back in the database, it still shows the old values. This is true even if i close and reload colmap

**Expected behavior**
The data to be updated in the database management viewer. I don't know if this information is saved properly in the database. 

**Screenshots**
If applicable, add screenshots to help explain your problem. Input images and/or output reconstructions are usually helpful.

**Environment:**
 - OS: Windows 10
 - COLMAP Version 3.8

**Comment by tsattler** [comment]
Not a bug, but standard behavior. The results from the reconstruction step (intrinsics, extrinsics) are not stored in the database.

**Comment by quitmeyer** [comment]
Ah thank you for letting me know! Is there anyway to save those intrinsics back into the database if we want?

**Comment by tsattler** [comment]
Yes, either manually through the gui (under database management), or by directly changing things in the database.

**Comment by quitmeyer** [comment]
awesome, thanks for your help!
