### ISSUE TITLE
`dev` branch is missing

### ISSUE THREAD

**Issue by amughrabi** [colmap/colmap#2148]
Hi, I am following the instructions on the documentation <https://colmap.github.io/install.html#linux>, and I found that the dev branch is missing. 

```bash
git clone https://github.com/colmap/colmap.git
cd colmap
git checkout dev
mkdir build
cd build
cmake .. -GNinja
ninja
sudo ninja install
```

Also, removing the `git checkout dev` makes the build work, but it sounds incomplete because I cannot build `pyceres` since it shows:
```
[ 50%] Building CXX object CMakeFiles/pyceres.dir/_pyceres/bindings.cc.o
10.96     In file included from /pyceres/_pyceres/factors/bindings.cc:6,
10.96                      from /pyceres/_pyceres/bindings.cc:8:
10.96     /pyceres/_pyceres/factors/bundle.cc:1:10: fatal error: colmap/camera/models.h: No such file or directory
```

Would you please advise what is the equivalent branch for the `dev` branch?

**Comment by tsattler** [comment]
Please see #2109

**Comment by amughrabi** [comment]
Thanks a ton for the reply! I would love to suggest updating the documentation to avoid the confusion. For a record, I solved my problem of downgrading the colmap version to match `pyceres` version. Simply:

```bash
git clone --branch 3.8 https://github.com/colmap/colmap.git --single-branch

cd colmap && \
	mkdir build && \
	cd build && \
	cmake .. -DCMAKE_CUDA_ARCHITECTURES=native && \
	make -j$(nproc) && \
	make install


git clone --branch v1.0 --recursive https://github.com/cvg/pyceres.git  /pyceres
cd /pyceres
pip3 install -e .
```

**Comment by Rurouni-z** [comment]
> Thanks a ton for the reply! I would love to suggest updating the documentation to avoid the confusion. For a record, I solved my problem of downgrading the colmap version to match `pyceres` version. Simply:
> 
> ```shell
> git clone --branch 3.8 https://github.com/colmap/colmap.git --single-branch
> 
> cd colmap && \
> 	mkdir build && \
> 	cd build && \
> 	cmake .. -DCMAKE_CUDA_ARCHITECTURES=native && \
> 	make -j$(nproc) && \
> 	make install
> 
> 
> git clone --branch v1.0 --recursive https://github.com/cvg/pyceres.git  /pyceres
> cd /pyceres
> pip3 install -e .
> ```

why install pyceres，is it as same as libceres-dev?

**Comment by amughrabi** [comment]
A Python package called `pyceres` has a dependency on the `colmap` package. However, the package is closely tied to a specific version of the `colmap` branch, which is `dev`. As a result, building `pyceres` without `colmap` is not possible. Although a temporary solution exists as a workaround, the better approach is to address the issue from the `pyceres` side, which will involve making changes to the code.

**Comment by Rurouni-z** [comment]
> A Python package called `pyceres` has a dependency on the `colmap` package. However, the package is closely tied to a specific version of the `colmap` branch, which is `dev`. As a result, building `pyceres` without `colmap` is not possible. Although a temporary solution exists as a workaround, the better approach is to address the issue from the `pyceres` side, which will involve making changes to the code.

thanku, i just use your bash to install colmap, and i dont carefully see your issue, sorry.
