### ISSUE TITLE
Undefined symbol colmap:SiftFeatureExtractor() is this expected?

### ISSUE THREAD

**Issue by Suicosmos** [colmap/colmap#2153]
`Environment:`

Ubuntu 20.04
Colmap 3.8

Hello, I have compiled Colmap successfully as a static library and have been using it in a headless server without issue. Whenever I try to run my code either the 
SiftFeatureExtractor or ExhaustiveFeatureMatcher I get a undefined symbol error. Is the constructor in "feature/extraction.h" not meant to be used? I also get confused because they are in the "feature/extraction.h" but if you check the git repo or src folder this is not a header in that location. It seems to only be in builds.

Is there something i'm missing? is this constructor not the way to gain access to a featureExtractor instance? The code looks similar to this.

```
//Unique_ptrs declared in h. file.
std::unique_ptr<colmap::Thread> featureExtractor;
std::unique_ptr<colmap::ImageReaderOptions> imageReaderOpts;
std::unique_ptr<colmap::SiftExtractionOptions> siftExtractorOpts;
```

```
//source file constructor. 
imageReaderOpts = std::make_unique<colmap::ImageReaderOptions>(colmap::ImageReaderOptions());
siftExtractorOpts = std::make_unique<colmap::SiftExtractionOptions>(colmap::SiftExtractionOptions());
featureExtractor = std::make_unique<colmap::SiftFeatureExtractor>(*imageReaderOpts, *siftExtractorOpts);
```

**Comment by ahojnnes** [comment]
Can you provide a complete example for how you link against colmap in your project? This sounds like you are not linking against the right targets.

**Comment by Suicosmos** [comment]
That's what I thought too. but I linked to all the libraries that colmap created. here are some screenshots.

![colmaplibs](https://github.com/colmap/colmap/assets/50228821/0e6db227-0aea-4545-936b-818b9d0aaf1d)

![cmakecolmap](https://github.com/colmap/colmap/assets/50228821/54b21160-1e45-49ff-9b92-6e4f5e8a5dca)

this colmap_module target is then linked to the main executable.
