### ISSUE TITLE
After pressed reconstruct button, the program exited immediately

### ISSUE THREAD

**Issue by SandW** [colmap/colmap#216]
F0908 16:29:39.126399 11157 reconstruction.cc:68] Check failed: image.second.NumPoints2D() == existing_image.NumPoints2D() (9917 vs. 9952) 
*** Check failure stack trace: ***
    @     0x7fbeccd585cd  google::LogMessage::Fail()
    @     0x7fbeccd5a433  google::LogMessage::SendToLog()
    @     0x7fbeccd5815b  google::LogMessage::Flush()
    @     0x7fbeccd5ae1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x7abdfe  colmap::Reconstruction::Load()
    @           0x66e9f0  colmap::IncrementalMapper::BeginReconstruction()
    @           0x64ef9f  colmap::IncrementalMapperController::Reconstruct()
    @           0x65095b  colmap::IncrementalMapperController::Run()
    @           0x63ffec  colmap::Thread::RunFunc()
    @     0x7fbec9cb5c80  (unknown)
    @     0x7fbecc5e06ba  start_thread
    @     0x7fbec941b3dd  clone
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by SandW** [comment]
After restarted the program, it ran normally.

**Comment by ahojnnes** [comment]
It seems you tried to resume the reconstruction from an existing model, but there was a discrepancy between the data in the existing model and the database you provided. This is a user error. Closing this as resolved, but feel free to reopen if the problem still exists. Thanks.

**Comment by SandW** [comment]
Thanks!
