### ISSUE TITLE
Question about images.txt for reconstructing model from known camera poses

### ISSUE THREAD

**Issue by monamourvert** [colmap/colmap#2160]
Hi, I have big confusion when I reconstruct a model from known camera poses. I have a camera that attached to robot as you can see below:
![frame](https://github.com/colmap/colmap/assets/121480926/69127c2d-fd8b-4158-aabe-831a4c951aef)

In the FAQ page, it is said if images.txt contain the 6DOF world-to-camera. I assume if my camera frame (in world coordinate) is already satisfied the COLMAP coordinate. So, to make the images.txt, I only perform the inverse calculation of my 6DOF pose. But strangely I got this result where the camera do not look to the scenery. Plus, the way it move in x axis is mirrored to the real trajectory in real world. Could you enlighten me in which part I got it wrong? Thanks!
![direct_w2c](https://github.com/colmap/colmap/assets/121480926/3861aba2-524b-40c8-bf07-a9901b544f5c)

**Comment by monamourvert** [comment]
Assuming I perform another 90 degree rotation to make the camera facing the scenery. It turns out like this 
![image](https://github.com/colmap/colmap/assets/121480926/5e382268-a931-4388-88aa-3c6287dd6256)
which is pretty good because I can say if that's the way the camera see the scenery in a real world. But, when I traced all the trajectory, it turns out only the yellow part that see into the inner of square (the part that I want). But the other part is facing to the reverse direction. 
![image](https://github.com/colmap/colmap/assets/121480926/129b68fc-1950-471b-bfe8-7cde778a3049)
Would you like to help me to understand this kind of situation?

**Comment by tsattler** [comment]
Are you sure the transformation that you get for the cameras is what Colmap expects (a transformation from the world coordinate system such that a point X_w in world coordinates is transformed to a 3D point X_c = R * X_w + t in local camera coordinates (with the z-axis pointing forward, the y-axis pointing downwards, and the x-axis pointing to the right))?

**Comment by monamourvert** [comment]
Would you enlighten me about that?

So basically this is my case
1. I’m having 6DOF lidar pose in world coordinate
2. Then I transformed the lidar pose to my camera coordinate in order to satisfied the Colmap coordinate. In this step I assume this kind of transformation already fulfilled the world-to-camera pose. Am I right?
3. But when I use this pose to my images.txt the result kinda strange so it didn’t look like the trajectory I captured in the real world.
4. When I inversed the pose, strangely it shows the trajectory I captured in real world but the x axis is mirrored and the way camera sees is downward (not into the scenery)
5. If I performed another 90 degree rotation as I attached above, it produced the result as I attached above also. Only some parts that looking right into the scenery but others looking into the reverse direction.

I do believe there is my mistake in the transformation process. I hope you can enlighten me where the part I should put more focus on. Thanks!

**Comment by tsattler** [comment]
Do you have the calibration between the lidar and the camera?

**Comment by tsattler** [comment]
If R_lidar, t_lidar is the transformation from world coordinates into lidar coordinates and R_cam, t_cam is the transformation from lidar to camera coordinates, then the poses you want to use for colmap are R = R_cam * R_lidar, t = R_cam * t_lidar + t_cam.

**Comment by monamourvert** [comment]
Thanks! I solved it! Something is wrong with the transformation process. Now I can reconstruct the model from my known camera poses! I'll close this issue
