### ISSUE TITLE
Reconstruction on AMD cards yields wrong results

### ISSUE THREAD

**Issue by MrMinimal** [colmap/colmap#218]
According to this [conversation on Google Groups](https://groups.google.com/forum/#!topic/colmap/pvSB8SxZ3b4) there is a problem with reconstruction in the current build.

The results with the provided south-building dataset look like this:

![broken](https://user-images.githubusercontent.com/8739690/30244150-a261f3da-95b8-11e7-867f-7eaf95834788.png)

The one thing all commenters seem to have in common is an AMD card (multiple architechtures).

I have a new Vega card as well in case I can be any help in finding the problem.

**Comment by ahojnnes** [comment]
Seems like the underlying reconstruction process succeeded but something is wrong with the visualization of the model in the GUI. Did you install the latest GPU drivers on your system?

**Comment by MrMinimal** [comment]
Yes, the drivers are up to date.

Looking at the output in Meshlab, I get the following
![image](https://user-images.githubusercontent.com/8739690/30387201-1b762994-98ac-11e7-8ae6-eb2eada098ab.png)

Whereas it should look more like this (Done via VisualSFM):
![image](https://user-images.githubusercontent.com/8739690/30387279-4cf9b562-98ac-11e7-9a65-04b28e16f992.png)

Granted, refining etc. is most likely not going to be enough. Any further help I can provide on this one?

**Comment by ahojnnes** [comment]
Unfortunately, I do not know what is going on in your case. Something is clearly wrong even with the reconstruction. How did you produce the dense reconstruction on your system with Colmap?

**Comment by MrMinimal** [comment]
The steps for the sparse reconstruction were

- Feature extraction
- Feature matching
- Start reconstruction

and tried automatic reconstruction as well, which yielded the same results.

For the dense reconstruction, I used openMVS.

**Good news:** Meshlab shows the correct sparse point cloud if exported from Colmap.
So you were right with the assumption that it is just a display error in AMD cards.

The next problem I have is dense reconstruction does not work in Colmap. When clicking "stereo" a "No CUDA available" dialog pops up. I am using the dev-windows-no-cuda build.

Any ideas or should I rather make a new issue with this one?

**Comment by ahojnnes** [comment]
COLMAP requires a CUDA-enabled GPU for dense reconstruction. Alternatives are to use PMVS/CMPMVS. The documentation describes how to do this. Let me know if you have questions.

**Comment by MrMinimal** [comment]
Will do, thanks for the help!

**Comment by MrMinimal** [comment]
The issue can be closed, the results on AMD work as well once exported:

![image](https://user-images.githubusercontent.com/8739690/30607553-c44495e2-9d75-11e7-99c7-b6514526b7e1.png)

**Comment by drkoller** [comment]
This issue has been fixed in PR #1079.
