### ISSUE TITLE
Import point correspondences from optical flow estimation

### ISSUE THREAD

**Issue by Szy-Young** [colmap/colmap#2187]
Hi, I would like to import point correspondences from dense optical flow estimations into Colmap. After some processing, now I am able to write "keypoints" of each frame and "matches" across frames into a Colmap-based database. But before reconstruction, "two-view geometry" is lacking. However, I do not have feature descriptors for these "keypoints", because they are manually given by myself rather than from Colmap feature extractor. And in Colmap, it seems the feature matching and geometric verification is bundled together. So even though I already have "matches", I don't know how to get "two-view geometry". 

To solve this problem, I have several ideas:

1. In Colmap, can I perform geometric verification only when "matches" are available? 
2. In Colmap, can I extract SIFT feature descriptors for given "keypoints"? If this is feasible, I will have the required inputs for Colmap matcher.

Could you help me enlighten me a correct path to solve the problem? Thanks!

**Comment by tsattler** [comment]
1. Yes. If matches exist, Colmap should load them instead of recomputing them.
2. No, this is not possible.

The easiest way to run matching is to write the matches into a text file and import them via the `matches_importer`.

**Comment by Szy-Young** [comment]
@tsattler Thx for your reply! 

I also find another simple solution: Just write 0s (or any other values) into feature descriptors, since they won't be used in geometric verification if "matches" are already given. Then we can simply load the ```database.db``` and call the ```matcher```.
