### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by SandW** [colmap/colmap#219]
*** Aborted at 1505209641 (unix time) try "date -d @1505209641" if you are using GNU date ***
terminate called recursively
terminate called after throwing an instance of 'std::bad_function_call'
  what():  bad_function_call
PC: @     0x7f9edca5e9b0 (unknown)
*** SIGSEGV (@0x7f9edca5e9b0) received by PID 22131 (TID 0x7f9ed9c0f700) from PID 18446744073116445104; stack trace: ***
    @     0x7f9f8025f390 (unknown)
    @     0x7f9edca5e9b0 (unknown)
    @     0x7f9ed9c0f901 (unknown)
Segmentation fault (core dumped)

**Comment by ahojnnes** [comment]
It would be helpful if you could run COLMAP with GDB/LLDB and report a traceback. Thanks.

**Comment by SandW** [comment]
This error occurred after several hours running.
I will try.
Thanks!

**Comment by ahojnnes** [comment]
Any outcome of this experiment?

**Comment by ahojnnes** [comment]
Closing this due to lack of feedback.
