### ISSUE TITLE
exported PLY file with error character encoding

### ISSUE THREAD

**Issue by juling2023** [colmap/colmap#2191]
I built colmap source code with ubuntu20.04LTS and CUDA 11.1 to do 3D renconstruction. 

After I done sparse renconstruction, I exported .PLY file. However, there is some invalid characters in the exported PLY file. When I opened it with MeshLab, it looks a bit strange.

![image](https://github.com/colmap/colmap/assets/136941415/a29a7c85-f664-4fe3-aa0b-5fb48ebac81d)

Then I done dense construction, also, anything else is ok except exporting .PLY file. Is there anyone can help me?

**Comment by tsattler** [comment]
The header of the ply files is in text format, but the rest is stored in binary format. If you open it in a text editor, it won't make sense.

I don't know what you mean by "When I opened it with MeshLab, it looks a bit strange."

**Comment by juling2023** [comment]
@tsattler Hi, thanks for your positive reply.
I mean that when I open the exported ply file in MeshLab, it looks like very different from colmap viewer. 

This is the reconstructioned scene in colmap viewer after doing dense resonstruction. It looks great.
![image](https://github.com/colmap/colmap/assets/136941415/98d98826-5871-4b89-8346-168ec9608683)

This is the scene using exported fused.ply opened with MeshLab. It looks a bit strange.
![image](https://github.com/colmap/colmap/assets/136941415/4cc3b6fd-427d-4224-801b-54bf755bb8bb)

Why is it, I am confused.

**Comment by tsattler** [comment]
It looks like the meshlab view is just upside down (likely because meshlab uses a different coordinate system than colmap). Have you rotated the scene?

**Comment by juling2023** [comment]
@tsattler yes, I have tried to rotated it to get  a view that sames to the colmap viewer, but failed. So I wonder if the exported ply file has something wrong (Because I have used other ply file before, it can be opened by ubuntu gedit editor, and shows right valid character encoding.) 
By the way, have you ever exported ply file in ubuntu? it is right when it is opened with MeshLab?

**Comment by juling2023** [comment]
@tsattler I changed the point size, now it can see basic shape, but why is it showed very difference from the scene of the colmap viewer? 
![image](https://github.com/colmap/colmap/assets/136941415/3b64ab84-2e7c-434d-ab25-f12e38c6cdaf)

**Comment by tsattler** [comment]
This looks very much like the same model as in Colmap. Note that Meshlab by default uses lighting. If you want to have the same colors, you will need to disable lighting in Meshlab.
I never had any issues with models under Ubuntu.

**Comment by juling2023** [comment]
Thanks for your help! Now, I set the shading to None in the MeshLab, the color looks like much right than before, but the model looks like low resolution. If I import the ply file from colmap software, it looks very great. Maybe I can use colmap to import file rather that meshLab to view my model.
![图片](https://github.com/colmap/colmap/assets/136941415/d212b2ac-3676-4c4d-9974-62e2cc96fe0c)
