### ISSUE TITLE
Bug of feature_extractor

### ISSUE THREAD

**Issue by massyzs** [colmap/colmap#2194]
It is said:
To increase the number of matches, you should use the more discriminative DSP-SIFT features instead of plain SIFT and also estimate the affine feature shape using the options: --SiftExtraction.estimate_affine_shape=true and --SiftExtraction.domain_size_pooling=true. In addition, you should enable guided feature matching using: --SiftMatching.guided_matching=true.

But when I set :
**colmap feature_extractor \
    --SiftExtraction.estimate_affine_shape=true \
    --SiftExtraction.domain_size_pooling=true \
    --SiftMatching.guided_matching=true \
    --database_path /home/caoxiao/code/data/nerf_llff_data/fern/colmap/database.db \
    --image_path /home/caoxiao/code/data/nerf_llff_data/fern/colmap/images**
    
   It told me ERROR: Failed to parse options - unrecognised option '--SiftMatching.guided_matching=true'.

**Comment by ahojnnes** [comment]
It is a mistake in the documentation. It is now part of the TwoViewGeometryOptions.

**Comment by ahojnnes** [comment]
Actually, no, this is still configured under "SiftMatching.guided_matching". You applied it to the wrong stage. It only applies to exhaustive_matcher or any other matcher but not the feature_extractor.
