### ISSUE TITLE
OS X version does not run

### ISSUE THREAD

**Issue by mankoff** [colmap/colmap#22]
> You can't open the application "COLMAP.app" because it may be damaged or incomplete

Version: OS X 10.11.6

**Comment by ahojnnes** [comment]
Hi Ken,

Just downloaded and tried on 11.10.6 again and it works just fine. Did
you try to download a second time? Maybe the download was corrupted?

Thanks,
Johannes


On Fri, Aug 12, 2016, at 10:01 PM, Ken Mankoff wrote:
>> You can't open the application "COLMAP.app" because it may be damaged
>> or incomplete
> Version: OS X 10.11.6
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
>


Links:

  1. https://github.com/colmap/colmap/issues/22

**Comment by mankoff** [comment]
I'm on an HSFX+ (case sensitive) OS X system. I think the issue is `COLMAP.app` v. `colmap` as the binary. It runs if I `cd COLMAP.app/Contents/MacOS; mv colmap COLMAP`.

**Comment by ahojnnes** [comment]
Great, thanks for figuring this out. I updated the binary online and also my build script for the future: https://github.com/colmap/colmap/commit/1b9a1c7e1a8c94b1e7bf79ad25c804f6af66d1f9
