### ISSUE TITLE
Question about camera poses in images.txt

### ISSUE THREAD

**Issue by sbarkby** [colmap/colmap#220]
Hi there

I just wanted to check the definition of the X,Y,Z axes for any given camera coordinate frame with corresponding pose  defined in images.txt. Am I right in saying that:

Positive X in the camera frame is in the **same** direction as +u in the image coordinate frame (pointing to the right of the image)
Positive Y in the camera frame is in the **same** direction as +v in the image coordinate frame  (pointing to the bottom of the image)
Positive Z points out of the image towards the image subject.

I ask this as I have seen other conventions where Positive Y in the camera frame is in the **opposite** direction to +ve v, so this has me a little confused

Cheers

Steve

**Comment by ahojnnes** [comment]
This is correct.
