### ISSUE TITLE
error while compiling colmap using python build script on system without root access

### ISSUE THREAD

**Issue by prakashknaikade** [colmap/colmap#2201]
`kade@wks-14-75 /HPS/ColorNeRF/work/colmapnerf/colmap ±main » python3 scripts/python/build.py \
    --build_path /HPS/ColorNeRF/work/colmapnerf/colmap/build \
    --colmap_path /HPS/ColorNeRF/work/colmapnerf/colmap

-- Found FreeImage
--   Includes : /HPS/ColorNeRF/work/colmapnerf/colmap/build/__install__/include
--   Libraries : /HPS/ColorNeRF/work/colmapnerf/colmap/build/__install__/lib/libfreeimage.a
-- Found FLANN
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libflann.so
-- Found LZ4
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/liblz4.so
-- Found Metis
--   Includes : /HPS/ColorNeRF/work/colmapnerf/colmap/build/__install__/include
--   Libraries : /HPS/ColorNeRF/work/colmapnerf/colmap/build/__install__/lib/libmetis.a
-- Found Glog
--   Target : glog::glog
CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find SQLite3 (missing: SQLite3_INCLUDE_DIR SQLite3_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.18/Modules/FindSQLite3.cmake:52 (find_package_handle_standard_args)
  cmake/FindDependencies.cmake:24 (find_package)
  CMakeLists.txt:87 (include)

-- Configuring incomplete, errors occurred!
See also "/HPS/ColorNeRF/work/colmapnerf/colmap/build/colmap/__build__/CMakeFiles/CMakeOutput.log".
Command failed: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/HPS/ColorNeRF/work/colmapnerf/colmap/build/__install__ -DCMAKE_INSTALL_PREFIX=/HPS/ColorNeRF/work/colmapnerf/colmap/build/__install__ -DCUDA_ENABLED=ON -DCMAKE_CUDA_ARCHITECTURES=Auto -DOPENGL_ENABLED=ON -DTESTS_ENABLED=ON /HPS/ColorNeRF/work/colmapnerf/colmap`

**Comment by ahojnnes** [comment]
I suggest to install colmap using vcpkg. The build script is not actively maintained or tested anymore.
