### ISSUE TITLE
nested model for large scale indoor scene

### ISSUE THREAD

**Issue by michael-r-zhang** [colmap/colmap#221]
I'm trying to reconstruction a large scale indoor scene from 3 videos of different views. 
However, the sparse reconstruction generates a fractal structure (a similar small pattern nested).
 
3 videos of different views
30 fps, 40 min of each video

1. Input:  
    extracted 2 images per second from each video, we get 1.4w images totally
2. Feature Extractor:
    sift gpu
3. Matcher：
    vocabulary tree matcher
4. Mapper:
    sparse reconstruction
5. Result:
    generate a single structure

The matches look good, estimated focal length (range from 900 to 1600) also seems good.
![model1](https://user-images.githubusercontent.com/17632731/30409615-dea69912-9938-11e7-9ca9-a8c389373836.png)
![model](https://user-images.githubusercontent.com/17632731/30409613-dcd30f44-9938-11e7-98cf-b23a80b28635.jpeg)

Thanks!

**Comment by ahojnnes** [comment]
I suggest to run the sequential matcher in addition. You can just run it again on your existing database. Then, since you said it is a video. Do you know whether the focus was constant during the video? Then, I suggest to share camera intrinsics.

**Comment by michael-r-zhang** [comment]
Hi,

**Comment by michael-r-zhang** [comment]
Hi, Johannes Schönberger

**Comment by michael-r-zhang** [comment]
Hi, Johannes
I tried different experiments during last days.

1) sequential matcher (not share intrinsics)
2) share camera intrinsics (using vocabulary tree matcher / sequential matcher)
3) set mapper.min_focal_length_ratio=0.5 and mapper.max_focal_length_ratio=2.0 (using vocabulary tree matcher / sequential matcher)

Howerver, all of these configurations cannot avoid the nesting model problem.
Do you have any other idea?

**Comment by ahojnnes** [comment]
You could try to increase `Mapper.abs_pose_min_num_inliers` from 30 to 50 or higher.

**Comment by ahojnnes** [comment]
Closing this due to lack of feedback.
