### ISSUE TITLE
Clangd: Eigen/Core not found error

### ISSUE THREAD

**Issue by abhiagg92** [colmap/colmap#2210]
**Is your feature request related to a problem? Please describe.**
Clangd cannot find `Eigen/Core` for some header files in VScode. Even though the build the successful but still clangd errors can still be quite frustrating and we should fix them.

**Describe the solution you'd like**
I raised this issue on the LLVM discord channel and they said that this issue is related to https://github.com/clangd/clangd/issues/123. Until this issue is resolved, we can create a `.clangd` file in the project root containing:
```
CompileFlags:
  Add: [-isystem, /usr/include/eigen3, -isystem, /usr/local/include/eigen3]
```
We should add `.clangd` file to fix this issue at least on UNIX-based systems.

**Comment by ahojnnes** [comment]
Thank you, but I don't think we want to work around this bug of clangd here manually with a fix that only works for specific install directories of Eigen. I suggest that you add this file on your machine locally to work around the issue.
