### ISSUE TITLE
Program crashed in sequential matching

### ISSUE THREAD

**Issue by SandW** [colmap/colmap#222]
SQLite error [/home/user/colmap-master/src/base/database.cc, line 382]: database disk image is malformed

**Comment by ahojnnes** [comment]
Seems like your database file got corrupted. Is this reproducible with multiple runs / disks?

**Comment by SandW** [comment]
We rebuilt the database, then it did not report. But it happened twice before.

**Comment by ahojnnes** [comment]
Is this still relevant or could you fix the issue?

**Comment by ahojnnes** [comment]
Closing this due to lack of feedback. Feel free to reopen at a later point.
