### ISSUE TITLE
Question regarding image_registrator and pose refinement

### ISSUE THREAD

**Issue by UriyMihailov** [colmap/colmap#2224]
I have some C++ code inside which I use the *system* command to call a python script. This script uses some of the colmap library. Problem is, each time I launch the code, the first time a script is called - everything runs fine. Then with the second, third, etc. script calls the colmap's image_registration starts working and then it simply skips the pose refinement completely. It goes on like that until the program is terminated and launched all over again.  
The proper output after first script call:  

==============================================================================
[image_localization-1] Registering image #538 (538)
[image_localization-1] ==============================================================================
[image_localization-1] 
[image_localization-1]   => Image sees 4 / 1865 points
[image_localization-1] 
[image_localization-1] Pose refinement report
[image_localization-1] ----------------------
[image_localization-1]     Residuals : 8
[image_localization-1]    Parameters : 6
[image_localization-1]    Iterations : 6
[image_localization-1]          Time : 0.000523492 [s]
[image_localization-1]  Initial cost : 0.197273 [px]
[image_localization-1]    Final cost : 0.156344 [px]
[image_localization-1]   Termination : Convergence
[image_localization-1] 
[image_localization-1] INFO    ::colmap_localize: Step 4: Export reconstruction results to txt

The output after next calls:  

==============================================================================
[image_localization-1] Registering image #538 (538)
[image_localization-1] ==============================================================================
[image_localization-1] 
[image_localization-1]   => Image sees 4 / 1865 points
[image_localization-1] INFO    ::colmap_localize: Step 4: Export reconstruction results to txt

**Comment by tsattler** [comment]
Can you share details, e.g., what does the script do, how do you call colmap, etc.? Without knowing what you are doing, it is hard to tell what is going on.

**Comment by UriyMihailov** [comment]
Whoops, sorry guys, my bad, the problem was on my side. I wasn't transforming the coordinates in the correct way.
