### ISSUE TITLE
Activation of multi-GPU reconstruction

### ISSUE THREAD

**Issue by alexsmartens** [colmap/colmap#223]
Hi. This is more a question than an issue.

How to check that the multi-GPU reconstruction is working properly?
I have two Nvidia GPUs in SLI. I run a test through all the COLMAP pipeline on this set up. From the computation time, it seems that only one GPU is working during reconstruction.  I would want to check whether there are really two GPUs are active during reconstruction or only one as it seems

**Comment by ahojnnes** [comment]
Which part of the reconstruction stage are you talking about? Extraction, matching, sparse, dense? You can observe GPU usage using ``nvidia-smi``.

**Comment by alexsmartens** [comment]
I'm majorly curious about dense reconstruction, because it takes the most of the time.
Do you mean that I can observe just how the GPUs are loaded? Something like Nvidia Server X will also do this trick

**Comment by alexsmartens** [comment]
Does it show that SLI is enabled?

```
 $nvidia-smi
Sat Sep 23 21:55:24 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.69                 Driver Version: 384.69                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 690     Off  | 00000000:04:00.0 N/A |                  N/A |
| 30%   38C    P8    N/A /  N/A |    506MiB /  1996MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 690     Off  | 00000000:05:00.0 N/A |                  N/A |
| 30%   33C    P8    N/A /  N/A |      2MiB /  1999MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0                  Not Supported                                         |
|    1                  Not Supported                                         |
+-----------------------------------------------------------------------------+
```

**Comment by ahojnnes** [comment]
It looks like your GPUs are not recognized properly in nvidia-smi. Even though it shows that both GPUs are activated, the second one does not allocate any memory on the GPU. If multiple GPUs are used, then the output of two processes should be interleaved. Are you sure your NVIDIA drivers and CUDA are installed correctly?

**Comment by alexsmartens** [comment]
I am quite sure that my Nvidia drivers and CUDA are installed correctly on  my PC. However, I found out that I had to tweak the SLI settings like this:

```
sudo nvidia-xconfig -sli=auto
sudo nvidia-xconfig -multigpu=on
```

Here's my updated `nvidia-smi`on idling PC:
```
 nvidia-smi
Mon Sep 25 11:14:59 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.69                 Driver Version: 384.69                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 690     Off  | 00000000:04:00.0 N/A |                  N/A |
| 37%   51C    P8    N/A /  N/A |    467MiB /  2044MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 690     Off  | 00000000:05:00.0 N/A |                  N/A |
| 37%   51C    P8    N/A /  N/A |    467MiB /  2044MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0                  Not Supported                                         |
|    1                  Not Supported                                         |
+-----------------------------------------------------------------------------+

```

Here is what it `nvidia-smi` showed during dense reconstruction:
```

 nvidia-smi
Mon Sep 25 11:10:00 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.69                 Driver Version: 384.69                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 690     Off  | 00000000:04:00.0 N/A |                  N/A |
| 52%   71C    P0    N/A /  N/A |    892MiB /  2044MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 690     Off  | 00000000:05:00.0 N/A |                  N/A |
| 48%   67C    P0    N/A /  N/A |    892MiB /  2044MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0                  Not Supported                                         |
|    1                  Not Supported                                         |
+-----------------------------------------------------------------------------+
```

Interestingly, it seems that multi-GPU computation worked out now, however it **did not change my computation time**

**Comment by ahojnnes** [comment]
How do you measure the computation time? Do you look at the total time spent per image or the total time for a complete dataset?

**Comment by alexsmartens** [comment]
I use the total time spent for a complete dataset

**Comment by ahojnnes** [comment]
The speedup should increase linearly with the number of GPUs, so I am not sure why this is not true for you...

**Comment by alexsmartens** [comment]
Well, I'm also kinda confused

**Comment by ahojnnes** [comment]
Looking at the output from above, something still seems broken if you cannot see the GPU utilization?

**Comment by alexsmartens** [comment]
Do you have an idea how to check whether everything is built and working properly?

From what I've found, `nvidia-smi` does not show utilization for all of GPUs:
[https://devtalk.nvidia.com/default/topic/528644/get-gpu-usage/](https://devtalk.nvidia.com/default/topic/528644/get-gpu-usage/)
[https://unix.stackexchange.com/questions/38560/gpu-usage-monitoring-cuda](https://unix.stackexchange.com/questions/38560/gpu-usage-monitoring-cuda)

I also tried using a simple [routine](https://github.com/mountassir/gmonitor) during dense reconstruction, and it shows that both GPUs are fully utilized:

![image](https://user-images.githubusercontent.com/26261714/30979847-32ad95b6-a43c-11e7-9e03-506bd000b76f.png)

**Comment by ahojnnes** [comment]
How do the times per Iteration/Sweep compare when running on 1 vs. 2 GPUs?

**Comment by alexsmartens** [comment]
Here is what I have after turning the `sli` and `multigpu` options off:
![image](https://user-images.githubusercontent.com/26261714/31060728-82b3619e-a6d5-11e7-97bf-c4ba0e2d9a7b.png)

I might be mistaken, but the results look really wired to me:
- significant difference in time per Iteration/Sweep
- in this scenario, two GPUs are still working together, however in different way: both GPUs are completely loaded, although they use VRAM completely differently
- total computation time in both cases is the same

**Comment by ahojnnes** [comment]
Something seems wrong with your setup, which is caused by SLI. On all systems that I tested the multi-GPU support works well. I cannot provide any more support in this case. If you are able to resolve the issue in the future, it would be great if you could let us know here. Thanks!
