### ISSUE TITLE
Ubuntu 22 and "Unsupported gpu architecture 'compute_native'"

### ISSUE THREAD

**Issue by AlexMorgand** [colmap/colmap#2232]
**What's the problem**
While compiling colmap on ubuntu 22 using CUDA 12.3 I got the error 

`Unsupported gpu architecture 'compute_native'"`

**To Reproduce**

1. cmake .. -GNinja  **(You will get  you must set CMAKE_CUDA_ARCHITECTURES to e.g.  'native', 'all-major', '70')**
3. cmake .. -GNinja -DCMAKE_CUDA_ARCHITECTURES=native 

**Temporary fix**
Replacing
`--generate-code=arch=compute_native,code=[compute_native,sm_native]`
by
`-arch=all`

Everything compiled after that.

**Environment:**
 - OS: Ubuntu 22
 - CMake: 3.22.1
 - NVCC: 12.3
 - G++: 11.4

**Comment by ahojnnes** [comment]
"native" is only supported in CMake 3.24+, see https://cmake.org/cmake/help/latest/prop_tgt/CUDA_ARCHITECTURES.html#prop_tgt:CUDA_ARCHITECTURES

**Comment by AlexMorgand** [comment]
Updated the cmake version and retested it. Fixed it right away. Thanks!

**Comment by TSoli** [comment]
https://github.com/colmap/colmap/issues/2464#issuecomment-2009050889 worked without updating cmake for me. Just note you do not include the decimal point in the number.
