### ISSUE TITLE
Dual GPU feature matching - hard crash

### ISSUE THREAD

**Issue by 4xle** [colmap/colmap#2243]
**Describe the bug**
While using two GPUs to perform feature matching, they run fine for a short period and then the system hard restarts.
This does not happen with only one GPU, which can successfully perform feature matching stably but slower.

**To Reproduce**
1. Manually injecting camera priors using a script and extracted metadata. Feature extraction also done in custom script. Descriptor is SIFT-like. 
    - However, behavior is consistent between script or using COLMAP feature extraction (allow for max num of features).
2. Run spatial matching with is_gps false and distance of 50, otherwise default options. (Begins and runs for some arbitrary amount of time).
3. Hard reboot occurs.

**Notes**
- Crash behavior is consistent between GUI and CLI tools.
- Monitoring programs don't indicate any straightforward suspects like being out of disk space, RAM, or thermal issues with GPUs causing hard restart. 
- System can run under full load on both GPUs for extended periods of time, so suspicion is with COLMAP or some part of the software stack.
- This is a research application so there are many more keypoints and descriptors than typical, however they still don't use more than 50% of GPU memory during spatial matching.
- No other software running while COLMAP runs aside from monitoring programs.

**Expected behavior**
Crash should crash with at least an error message, not a full hard restart. Not entirely sure where to start with debugging, can't find any useful system logs on host or from docker container. Strange thing is that it appears to run successfully for these short periods, if manually stopped system remains stable.

**Screenshots**
Hard to get a screenshot of a hard reboot crash.

**Environment:**
 - OS: Linux Mint 20.2
 - COLMAP Version: 3.9 (a7b50e4d) (in docker container with nvidia GPU passthrough)
 - Capture Device: Mapillary Metropolis Images Dataset with metadata.
 - Hardware: 
     - CPU Ryzen 3 3100
     - RAM: 128GB DDR4
     - GPUs: GTX 4090 x2, 24GB VRAM each

**Comment by ahojnnes** [comment]
By hard restart you literally mean that the machine shuts down and you have to reboot? If this is the case, then I suspect some issue with CUDA or docker. Did you try to install COLMAP on the host machine? Is the issue reproducible?

**Comment by ahojnnes** [comment]
Not sure if it fixes anything but here is an update to latest CUDA docker image: https://github.com/colmap/colmap/pull/2244

**Comment by 4xle** [comment]
Appreciate the prompt reply.

> By hard restart you literally mean that the machine shuts down and you have to reboot? If this is the case, then I suspect some issue with CUDA or docker. Did you try to install COLMAP on the host machine? Is the issue reproducible?

Yes, the machine literally hard restarts. I suspect some part of the stack eventually gets into a serious panic, and can't get out of it, though I've been unable to pinpoint it, frustratingly. Potentially something to do with the number of threads the matcher uses, if that is pinned at one thread it appears to run much slower but stabler with both GPUs (slower than one GPU with auto-threading).

I will give the updated docker container a try when I have a moment (and try a host install), but I have had to press on with just one GPU for now.

**Comment by 4xle** [comment]
@ahojnnes I have been able to replicate this behavior on a bare metal install with the same data. It doesn't seem to matter if I constrain the number of feature matches or specify the number of threads, it still occurs.

I'm unsure how to go about getting relevant traceback information for this issue, the crash seems really hard&trade; and lower level system logs don't seem to be picking anything up, which is very strange (thought I admit I am less familiar with Linux system logs, and may not be looking in the right places).

**Comment by 4xle** [comment]
Update: I've been able to reproduce this using just one 4090 with one thread using the spatial matcher in the CLI. Strangely, the GUI works under the same conditions.

Still not having any luck figuring out what exactly is happening though.

**Comment by 4xle** [comment]
@ahojnnes Turns out, COLMAPs spatial matcher is an excellent program to test a power supply's ability to handle transient spikes on big GPUs if its being used for research with 70-80k features per image.

**Comment by 1ssb** [comment]
Wen through this exact setting. Exact problem. Any fixes?
