### ISSUE TITLE
Simple radial camera parameters

### ISSUE THREAD

**Issue by messileonardo** [colmap/colmap#2245]
Hello, I would like to ask the meaning of the camera parameters.
![image](https://github.com/colmap/colmap/assets/148456260/eb8328a9-8e6c-4860-b4b8-8bc13a00f000)
If I am not wrong, in case of "simple radial" the 2nd and 3rd ones in the attached figure (i.e., 2016 and 1512) are the optical centers (i.e., cx, cy).
The 1st one (i.e., 3076.77) should be the focal length in just one direction (i.e., fx). Is it correct?
And the 4th one (i.e., 0.064735) is the radial distortion coefficient (i.e., k). Is it correct?
Any reference with additional information about these parameters (also about other camera models) would be very appreciated.
Many thanks in advance!

**Comment by tsattler** [comment]
Did you have a look here: https://colmap.github.io/cameras.html
and here: https://github.com/colmap/colmap/blob/main/src/colmap/sensor/models.h ?

**Comment by messileonardo** [comment]
Not yet the second one, really useful. Many thanks @tsattler !
