### ISSUE TITLE
Timeout Detection & Recovery fix makes app crash

### ISSUE THREAD

**Issue by roxima** [colmap/colmap#225]
I have a GTX 1080 installed on my PC now. Tried the automatic reconstruction tool. As expected I faced TDR issue and went along with FAQ guidelines, increasing the TDR through registry to values mentioned. I even tried with Nvidia NSight but whenever I create the `TdrLevel` key in registry, app totally fails to even start. When run from command line, it waits for a few seconds and finally crashes. Any other workaround?

**Comment by ahojnnes** [comment]
Did you restart your machine? The TDR configuration only takes effect after a restart.

**Comment by roxima** [comment]
Too much late to answer, but I guess the problem was that I had 2 displays connected to my graphics card. Disconnecting them helped fix the issue.
