### ISSUE TITLE
The images are ordered weirdly in the database.db after doing feature extraction

### ISSUE THREAD

**Issue by hjk0918** [colmap/colmap#2250]
**Describe the bug**
After feature extraction, the images in the database.db are organized in a weird order (see the screenshot below), making the name checking in the following triangulation failed.  

**To Reproduce**
I run the following to do sparse reconstruction with known poses:
1. Feature extraction
```
colmap feature_extractor \
    --database_path $PROJECT_PATH/database.db \
    --image_path $PROJECT_PATH/images
```
It goes well.
2. feature matching:
```
colmap exhaustive_matcher \
    --database_path $PROJECT_PATH/database.db
```
It goes well.
3. triangulation:
```
colmap point_triangulator \
    --database_path $PROJECT_PATH/database.db \
    --image_path $PROJECT_PATH/images \
    --input_path $PROJECT_PATH/sparse/0 \
    --output_path $PROJECT_PATH/sparse/0
```
I see the error:
```
==============================================================================
Loading model
==============================================================================


==============================================================================
Loading database
==============================================================================

Loading cameras... 89 in 0.000s
Loading matches... 3641 in 0.011s
Loading images... 89 in 0.027s (connected 89)
Building correspondence graph... in 0.091s (ignored 0)

Elapsed time: 0.002 [minutes]

F1102 21:48:34.782605 1128871 reconstruction.cc:79] Check failed: existing_image.Name() == image.second.Name() (0073.jpg vs. 0072.jpg) 
*** Check failure stack trace: ***
    @     0x7f3b2ffb21c3  google::LogMessage::Fail()
    @     0x7f3b2ffb725b  google::LogMessage::SendToLog()
    @     0x7f3b2ffb1ebf  google::LogMessage::Flush()
    @     0x7f3b2ffb26ef  google::LogMessageFatal::~LogMessageFatal()
    @     0x559e807611d6  colmap::Reconstruction::Load()
    @     0x559e80783b78  colmap::IncrementalMapper::BeginReconstruction()
    @     0x559e8063aafa  colmap::RunPointTriangulatorImpl()
    @     0x559e8063b9b1  colmap::RunPointTriangulator()
    @     0x559e80621be1  main
    @     0x7f3b2e797083  __libc_start_main
    @     0x559e806292ee  _start
Aborted (core dumped)
```

**Expected behavior**
I opened the database.db in the GUI and found that the images are organized in a weird order:
<img width="448" alt="Screenshot 2023-11-02 at 17 39 02" src="https://github.com/colmap/colmap/assets/35594962/702d5b9e-1419-45b5-abb4-5552331bfda5">
I think they should be organized in alphabetical order. 

**Environment:**
 - OS: Ubuntu 20.04.5 LTS
 - COLMAP Version 3.9

**Comment by tsattler** [comment]
This has been discussed in multiple issues. The image_ids are assigned in the order in which feature extraction is done. Since feature extraction is run in parallel on multiple images, whichever finishes first gets the next available image_id. 

The error you are running into comes from the image_ids in the 3D model not being consistent with those in the database. If you use the parameter `--clear_points 1` (or something like this), image_ids in the 3D model are ignored and image_ids are assigned to images based on matching image names between the 3D model and the database.

**Comment by hjk0918** [comment]
It works! Thanks a lot!
