### ISSUE TITLE
Exhaustive feature matching stopped working for imported matches

### ISSUE THREAD

**Issue by ducha-aiki** [colmap/colmap#2259]
**Describe the bug**

In version 3.8 and before, colmap could be used on top of imported features, such as DISK, SuperGlue, etc, given that the matches are imported. 
Then running `colmap exhaustive_matcher ` would result in ignoring the matching part and only 2-view geometry estimation.
However in 3.9 version it stopped working with error:

```
==============================================================================
Exhaustive feature matching
==============================================================================

[sift.cc:82] Check failed: max_num_matches > 0 (0 vs. 0)
F1108 22:03:29.695492 18771 sift.cc:1218] Check failed: options_.Check() 
*** Check failure stack trace: ***
    @     0x7f74ee396cad  google::LogMessage::Fail()
    @     0x7f74ee398b13  google::LogMessage::SendToLog()
    @     0x7f74ee396808  google::LogMessage::Flush()
    @     0x7f74ee399579  google::LogMessageFatal::~LogMessageFatal()
    @           0xc0034d  colmap::(anonymous namespace)::SiftGPUFeatureMatcher::Create()
    @           0xc003ed  colmap::CreateSiftFeatureMatcher()
    @           0x576531  colmap::FeatureMatcherWorker::Run()
    @           0x6085ad  colmap::Thread::RunFunc()
    @     0x7f74ac5908d3  execute_native_thread_routine
    @     0x7f74ee34afa3  start_thread
    @     0x7f74ac24e06f  clone
Aborted

```

## Reproduction

Run the notebook https://github.com/ducha-aiki/imc2023-kornia-starter-pack/blob/main/loftr-pycolmap-3dreconstruction.ipynb with colmap 3.9 and pycolmap 0.5.0 

The code above works at colmap 3.8 and pycolmap 0.4.0

**Comment by ahojnnes** [comment]
This looks like an issue with pycolmap, which seems to default to setting `max_num_matches` to 0?

Did you try specifying `matching_options.max_num_matches` to a large value when calling `pycolmap.match_exhaustive`?

**Comment by ducha-aiki** [comment]
@ahojnnes I am sorry for confusion, but that is reproducible with plain colmap, no python. 
Here is the colmap.db https://drive.google.com/file/d/17r898hG5_G6aR7fMkeYZlh_TJY84uIDQ/view?usp=sharing

When I run with colmap 3.9:
```bash
colmap exhaustive_matcher --database_path=colmap.db
```

I get:
```

==============================================================================
Exhaustive feature matching
==============================================================================

[sift.cc:82] Check failed: max_num_matches > 0 (0 vs. 0)
F1120 22:48:09.276485 17462 sift.cc:1218] Check failed: options_.Check() 
*** Check failure stack trace: ***
    @     0x7f064d0f1cad  google::LogMessage::Fail()
    @     0x7f064d0f3b13  google::LogMessage::SendToLog()
    @     0x7f064d0f1808  google::LogMessage::Flush()
    @     0x7f064d0f4579  google::LogMessageFatal::~LogMessageFatal()
    @           0xc0034d  colmap::(anonymous namespace)::SiftGPUFeatureMatcher::Create()
    @           0xc003ed  colmap::CreateSiftFeatureMatcher()
    @           0x576531  colmap::FeatureMatcherWorker::Run()
    @           0x6085ad  colmap::Thread::RunFunc()
    @     0x7f060b2eb8d3  execute_native_thread_routine
    @     0x7f064d0a5fa3  start_thread
    @     0x7f060afa906f  clone
Aborted
```

When I run  colmap 3.8

```bash
colmap exhaustive_matcher --database_path=colmap.db
```
I get:

```
==============================================================================
Exhaustive feature matching
==============================================================================

Matching block [1/1, 1/1] in 0.020s
Elapsed time: 0.001 [minutes]
```


Specifying `max_num_matches` via `--SiftMatching.max_num_matches=1000000` doesn't help, because we have 0 matches as the result, not input.

**Comment by ahojnnes** [comment]
I hope this fixes the issue: https://github.com/colmap/colmap/pull/2269

**Comment by ducha-aiki** [comment]
@ahojnnes indeed it does. Thank you a lot!

**Comment by wangyancongAC** [comment]
> `olmap exhaustive_matcher ` would result in ignoring the matching part and only 2-view geometry

I use colmap 3.10 with this, but the problem still happens.
