### ISSUE TITLE
OpenMVG with colmap?

### ISSUE THREAD

**Issue by ManishSahu53** [colmap/colmap#226]
I am using openMVG for SFM process. I want to use colmap for dense reconstruction. Can I do this?
Note- OpenMVG also option to export sfm data to visualsfm, PMVS,MVE, openMVS formats.

**Comment by alexsmartens** [comment]
Good question, I would also be interested in trying it out if it possible. 
@ManishSahu53 have you tried OpenMVS for MVS processing? According to my experiments, [OpenMVS](https://github.com/cdcseacave/openMVS) produces decent quality point clouds and extremely fast. Although, COLMAP reconstructs the best point clouds in terms of density and completes as well as COLMAP point clouds have considerably less noise

**Comment by ahojnnes** [comment]
If OpenMVG supports the PMVS format, you can use COLMAP for dense using the ``--workspace_format PMVS`` and ``--pmvs_option_name option-all`` (replace ``option-all`` with the option name file in the PMVS folder) options of the ``dense_stereo`` executable. Let me know if you have other questions.

**Comment by ManishSahu53** [comment]
@alexsmartens yes I have used openMVS also. It works very well. The only issue I have with openMVS is scalability. That why I am wondering to try colmap since number of large projects have been executed using colmaps. Have seen done large projects using openMVS?

**Comment by ManishSahu53** [comment]
@ahojnnes  Thanks. I want to process large dataset. So how colmap use clustering? Does it use overlapping clusters so as to ensure consistency between the clusters. Because I am facing this inconsistency problem in openMVS

**Comment by ahojnnes** [comment]
@alexsmartens You can make the dense reconstruction step of COLMAP also very fast. Just use lower resolution images (``--max_image_size N``) and disable the geometric consistency term (``--geom_consistency 0``). By default, COLMAP does not use clustering and COLMAP's dense reconstruction should be scalable even without clustering. In theory, you have the option to cluster the scene using CMVS when choosing the PMVS output. This is described in the documentation and sample scripts are in the workspace, e.g. ``run-cmvs-colmap-geometric.sh``

**Comment by ahojnnes** [comment]
Closing this issue as resolved. Feel free to reopen if questions remain.
