### ISSUE TITLE
About depth maps resolution

### ISSUE THREAD

**Issue by Eyoahz1243fei** [colmap/colmap#2272]
Why does the resolution of the estimated depth maps get smaller compared to the resolution of the corrected images? Is there a way to get depth maps without losing resolution?

**Comment by ahojnnes** [comment]
Images are undistorted after sparse reconstruction before multi view stereo. The depth maps correspond to the undistorted images. You can adjust the undistortion parameters, if you want a different trade off in terms of losing pixels vs some potential artifacts at the image boundaries.
