### ISSUE TITLE
Problem with generalized_absolute_pose

### ISSUE THREAD

**Issue by nosleduc** [colmap/colmap#229]
I'm trying to use this function to get the position of a single camera with 3 points.
The function does not return a solution for the given points.

My data are:

Camera
Internals:
fx = 12396.8
fy = 12396.8
cx = 1280
cy = 960
width = 2560
height = 1920
no distortion

RT (my solution)
0.53005 -0.0026095 -0.847962 0.925051
-0.0858555 -0.995022 -0.0506051 13.5825
-0.843609 0.0996254 -0.527635 394.787

Points
XYZ: 1.98017   13.7966   -1.97846
IJ: 1393.44   953.2

XYZ: 6.98866   11.3999   -7.39016
IJ: 1621.67   1023.33

XYZ: 3.62744   11.5429   0.310433
IJ: 1360.64   1015.75

K coefficients from your code for the 3 equations

k11, k12, k13, k14, k15, k16
1   -1.99963   0   1   0   -60.1157

k21, k22, k23, k24, k25, k26
1   -1.99997   0   1   0   -13.0317

k31, k32, k33, k34, k35, k36
1   -1.99956   0   1   0   -70.6174

No solution found for lambda1 with this system.

If I compute lambda1, lambda2, and lambda 3 from my solution for the camera I get

l1 = 395.551
l2 = 394.081
l3 = 392.725

Can you please try on your side ?

**Comment by ahojnnes** [comment]
@nosleduc I am afraid but I don't have time to play around with this at the moment. Since the polynomial roots are computed using numerical methods, the results might not be exact if the configuration of points is degenerate or close to degenerate.

**Comment by nosleduc** [comment]
I've also tested with two cameras and I'm also getting some issues.
Sometimes it finds a solution and sometimes it fails.
I'm pretty sure that the given points are not so bad.

I think the purpose of this function is to provide a guess that can be refined later. With no guess, I'm stucked.

By definition, real data contain noise. The 3 equations of the article will not be satisfied perfectly.
When I'm looking where the lambdas are computed, sometime I get a value about 0.3 for the imaginary part and 500 for the real part.  With the check kMaxRootImag, the solution is rejected. A value of 1e-10 for kMaxRootImag seems too low.

1) It can be interested to compare the magnitude of the imaginary part with the real part, something like this fabs(imaginary) < 0.01 * real

2) Lambda 1 can be computed by using the first equation or the second one.
The two possible solutions will be not equal. The check std::abs(lambda_1_1 - lambda_1_2) < 1e-3 seems too low

3) Normally the computed lambda must be positive. So you can check that lamda3 < 0.0

**Comment by ahojnnes** [comment]
Regarding (1), Would you mind doing some more tests and getting back to me with a good threshold? I can see that 1e-10 is a too small threshold.

Regarding (2), Similar to (1) I would like to see some more experimental evaluation before changing the thresholds. Why do you think this threshold is too low? This is totally dependent on the scale of the scene. Maybe a relative threshold ``abs(1 - lambda_1_1 / lambda_1_2)`` also makes more sense here?

Regarding (3), the function `ComputeLambdaValues` only returns values > 0.

**Comment by nosleduc** [comment]
1) I'm using 0.01 for the moment
2) I'm using abs(lambda_1_1 - lambda_1_2) < 0.1 * max(lambda_1_1, lambda_1_2)
3) Sorry for the error, you can check that lambda3 > 0.0. Lambda 3 is not computed from ComputeLambdaValues but from the companion matrix

For the moment, I have no good threshold to provide. I need to do more tests

**Comment by ahojnnes** [comment]
Addition: Regarding (3), I now see you are talking about lambda_3, so you are right that there should be a check to avoid negative depth.

**Comment by ahojnnes** [comment]
I am currently short on time, but I would appreciate your feedback on good values for the thresholds. Thanks!

**Comment by ahojnnes** [comment]
@nosleduc Is there any update on your side regarding the thresholds? Did you have time for some more tests? Thanks.

**Comment by nosleduc** [comment]
I didn't get time to estimate better thresholds
I'm using 0.01 for the first one and 0.1 for the second one.

I'm using this function in a ransac procedure and a refinement method.
I only need to have a guess not too far from the solution. The refinement method does the job.

**Comment by ahojnnes** [comment]
Thanks for the feedback!
