### ISSUE TITLE
Compilation errors in MVS code

### ISSUE THREAD

**Issue by sweeneychris** [colmap/colmap#23]
I'm getting a bunch of errors when I compile the latest commit from the master branch. I'm not experienced with CUDA at all, but I think there must be some error related to the NVCC compilation. I copy/pasted the output here for you to look at: http://pastebin.com/DTRESgNd

Looks like there are some c++ keywords (like nullptr) that NVCC can't handle?

Actually, now I'm realizing that I compile Ceres with C++11 enabled. This requires any libraries that link Ceres to also use c++11, so that is likely one source of trouble. Perhaps COLMAP can detect this and enable c++11? Or at least provide a cmake option to enable c++11.

**Comment by ahojnnes** [comment]
Hi Chris,

Can you share some system info, i.e. GCC/Clang version and OS version?

Thanks!
Johannes

**Comment by sweeneychris** [comment]
Ubuntu 14.04 and GCC 4.8.4

Btw I realized that when Ceres is compiled with c++11 it will actually append c++11 flags to anything that links the library. So this may be the cause of the errors. Not a big deal for me to recompile Ceres without c++11 support (though it is MUCH faster with c++11), but if the issue causing these errors is indeed c++11 then maybe CMake can detect this and tell the user they need to recompile Ceres without c++11

**Comment by ahojnnes** [comment]
Thanks Chris, I'll fix it tomorrow!

**Comment by ahojnnes** [comment]
@sweeneychris I failed to reproduce the issue. I pulled the latest Ceres code from Github and recompiled -- it says: `-- Enabling CERES_USE_CXX11 in Ceres config.h`. The latest COLMAP commit compiles without any issue under 14.04/4.8.4... Are you using an older Ceres version?

**Comment by sweeneychris** [comment]
Nope I'm using the master branch of Ceres and COLMAP

**Comment by ahojnnes** [comment]
What CUDA version? The default one from the Ubuntu repositories?

**Comment by sweeneychris** [comment]
nvcc --version gives me this:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17

**Comment by ahojnnes** [comment]
Exactly the same for me. Are you compiling in Debug/RelWithDebInfo/Release?

**Comment by sweeneychris** [comment]
Release

**Comment by ahojnnes** [comment]
Okay, no difference, still works on my side. Are you using a custom CMake version? Otherwise, I have no idea why you are seeing this and I am not...

**Comment by sweeneychris** [comment]
Nope, using Cmake 2.8.12.

I won't have time this week to dig into this more but I can try next week to see if some local configuration of mine is messing it up.

**Comment by ahojnnes** [comment]
I'll keep the issue open for now then, thanks for reporting!

**Comment by sweeneychris** [comment]
Hey Johannes, I realized I accidentally reported that this was from the "master" branch when really it was on the "dev" branch. I'm digging deeper into the errors now and hopefully will have more details (or a fix!) soon.

**Comment by sweeneychris** [comment]
It seems this issue has appeared in other CUDA projects as well: https://github.com/torch/torch7/issues/682

I simply added "-std=c++11 -Xcompiler -D__CORRECT_ISO_CPP11_MATH_H_PROTO" to L4 of src/mvs/CMakeLists.txt and everything compiles fine. So I guess the solution is just to detect c++11 availability and then supply the appropriate flags to NVCC.

**Comment by ahojnnes** [comment]
Hi Chris, thanks for the update. I am traveling at the moment and will look into it once I get back. Cheers, Johannes

**Comment by ahojnnes** [comment]
@sweeneychris Thanks again for reporting this problem. It should be fixed in the latest commit. Otherwise, feel free to reopen the issue. Cheers, Johannes
