### ISSUE TITLE
Possible bug using fixed intrinsic camera parameters and PBA 

### ISSUE THREAD

**Issue by SBCV** [colmap/colmap#230]
Hi Johannes,

while DESELECTING "Reconstruction / Reconstruction Options / refine_focal_length" works for the ceres solver (i.e.  SIMPLE_RADIAL and "Shared for all images") it does not work for PBA (i.e. SIMPLE_RADIAL without "Shared for all images").  
That means, in case of PBA the reconstruction contains cameras with a different focal length then the one provided in "Custom Parameters".
Is this really the intended behavior? 

However, when I add 
`pba.SetFixedIntrinsics(true);`
in front of 
```
pba.SetCameraData(cameras_.size(), cameras_.data());
pba.SetPointData(points3D_.size(), points3D_.data());
pba.SetProjection(measurements_.size(), measurements_.data(),
                    point3D_idxs_.data(), camera_idxs_.data());
```
in
`bool ParallelBundleAdjuster::Solve(Reconstruction* reconstruction) `
in 
`src/optim/bundle_adjustment.cc` 
the focal length is not modified (and the result is the one expected considering the gui parameters).

Cheers
Sebastian

**Comment by ahojnnes** [comment]
Thanks for reporting this bug. I guess, when using `pba.SetFixedIntrinsics(true);` then distortion parameter is also not optimized?

**Comment by SBCV** [comment]
I think so. I exported both results as nvm files. 
In the `pba.SetFixedIntrinsics(true)` case, the second last entry at the camera lines is always 0.
In the case without setting fixed intrisics, the second last entry varies.
According to http://ccwu.me/vsfm/doc.html#nvm this should describe the radial distortion.

**Comment by ahojnnes** [comment]
This should be fixed in https://github.com/colmap/colmap/commit/d96ed5314367f18704daf85c52b1867ecb1703dd

Thanks for the bug report. It would be great if you could test the behavior and get back to me. Thanks.

**Comment by SBCV** [comment]
Yes, d96ed5314367f18704daf85c52b1867ecb1703dd, fixed the problem. Thank you!
