### ISSUE TITLE
Import / Export Model Bug

### ISSUE THREAD

**Issue by SBCV** [colmap/colmap#231]
Hi Johannes,

I just discovered a bug, while exporting a reconstruction and importing it again.

When I import the model, the following error appears:
ERROR: Failed to parse options unrecognised option 'Render.log_level'.

After removing the line above from project.ini, the following error appears:
ERROR: Failed to parse options unrecognised option 'DenseMeshing.database_path'.

After removing the line above from project.ini, the following error appears:
ERROR: Failed to parse options unrecognised option 'DenseMeshing.image_path'.

After removing the line above from project.ini, the following error appears:
ERROR: Failed to parse options the option 'database_path' is required but missing.

Cheers
Sebastian

**Comment by ahojnnes** [comment]
It seems your project.ini is corrupt. If you do not rely on the options being restored when importing a model, just delete it and the error will go away. Otherwise, you will have to fix the project.ini and you can compare it to a correctly formatted project.ini by saving some project using ``File > Save project``.

**Comment by SBCV** [comment]
Hi Johannes,

even if I use File / Save Project and afterwards File / Open Project the same error appears. 
(ERROR: Failed to parse options unrecognised option 'Render.log_level'.)
To me, this really looks like a bug.

**Comment by SBCV** [comment]
Update: After comparing the ini file with an old one (generated using colmap 2.0) I realized that database_path, image_path and log_level are written to wrong sections. 
Using the current Colmap version (dev branch) and Ubuntu 14.04 database_path and image_path end up in the DenseMeshing section. Log_level is written to the Render section.

After moving these paths to the top (Default section), the error disappears

**Comment by ahojnnes** [comment]
Glad to hear you could resolve, that would have been my next question.

**Comment by SBCV** [comment]
Are you going to fix this? Or should I try and make a pull request?

**Comment by ahojnnes** [comment]
There is nothing to be fixed. I made a backwards incompatible change. In fact, the names of many options changed between the transition from version 2.x to 3.x and any project.ini will not be compatible anymore.

**Comment by ahojnnes** [comment]
But thanks for the offer!

**Comment by SBCV** [comment]
I think you misunderstood me, when I use the CURRENT colmap version, save the project file (.ini) and load it again with the CURRENT colmap version, then this error appears. That means saving and loading is not consistent.

**Comment by ahojnnes** [comment]
Are you on the dev or the master branch? Because I cannot reproduce this issue.

**Comment by SBCV** [comment]
dev branch, the latest commit b71d728c106cb9514563594c7dc37fbde36380e2.
Okay, if you can not reproduce it I ll have a look.

**Comment by SBCV** [comment]
Okay, I think it is a bug in `boost::property_tree::write_ini(path, pt)` in the boost version provided by ubuntu 14.04 (boost 1.54). I tested the behaviour on 2 different computers (Both ubuntu 14.04)

I iterated over the property tree in `void OptionManager::Write(const std::string& path) const` and printed the key value pairs. The result is shown below. As you can see, some of the key-value-pairs WITHOUT a section like  
"log_to_stderr": "false",
"log_level": "2",
 "database_path": "/home/sebastian/Desktop/TEST/images",
 "image_path": "/home/sebastian/Desktop/TEST/images"
are in between key-value pairs WITH a section.

`boost::property_tree::write_ini(path, pt)` in Boost 1.54 writes the key-value-pairs to the ini file maintaining the order of the key-value-pairs in the property tree. Therefore, some of the key-value-pairs WITHOUT a section can not be distinguished from key-value-pairs from the previous section (see ini file content below.)

One simple solution would be to add a default/general section for the 4 key-value-pairs mentioned above. 
What do you think?

 ============================== PropertyTree Structure ==============================
{
  "log_to_stderr": "false",
  "ImageReader": 
  {
    "single_camera": "false",
    "default_focal_length_factor": "1.2",
    "camera_model": "SIMPLE_RADIAL",
    "camera_params": ""
   },
  "SiftExtraction": 
  {
    "use_gpu": "true",
    "estimate_affine_shape": "false",
    "upright": "false",
    "domain_size_pooling": "false",
    "num_threads": "-1",
    "max_image_size": "3200",
    "max_num_features": "8192",
    "first_octave": "-1",
    "num_octaves": "4",
    "octave_resolution": "3",
    "max_num_orientations": "2",
    "dsp_num_scales": "10",
    "peak_threshold": "0.006666666666666667",
    "edge_threshold": "10",
    "dsp_min_scale": "0.1666666666666667",
    "dsp_max_scale": "3",
    "gpu_index": "-1"
   },
  "SiftMatching": 
  {
    "use_gpu": "true",
    "cross_check": "true",
    "multiple_models": "false",
    "guided_matching": "false",
    "num_threads": "-1",
    "max_num_matches": "32768",
    "max_num_trials": "10000",
    "min_num_inliers": "15",
    "max_ratio": "0.8",
    "max_distance": "0.7",
    "max_error": "4",
    "confidence": "0.999",
    "min_inlier_ratio": "0.25",
    "gpu_index": "-1"
   },
  "SequentialMatching": 
  {
    "quadratic_overlap": "true",
    "loop_detection": "false",
    "overlap": "5",
    "loop_detection_period": "10",
    "loop_detection_num_images": "30",
    "loop_detection_num_verifications": "0",
    "loop_detection_max_num_features": "-1",
    "vocab_tree_path": ""
   },
  "SpatialMatching": 
  {
    "is_gps": "true",
    "ignore_z": "true",
    "max_num_neighbors": "50",
    "max_distance": "100"
   },
  "BundleAdjustment": 
  {
    "refine_focal_length": "true",
    "refine_principal_point": "false",
    "refine_extra_params": "true",
    "max_num_iterations": "100",
    "max_linear_solver_iterations": "200",
    "function_tolerance": "0",
    "gradient_tolerance": "0",
    "parameter_tolerance": "0"
   },
  "Mapper": 
  {
    "ignore_watermarks": "false",
    "multiple_models": "true",
    "extract_colors": "true",
    "ba_refine_focal_length": "true",
    "ba_refine_principal_point": "false",
    "ba_refine_extra_params": "true",
    "ba_global_use_pba": "true",
    "tri_ignore_two_view_tracks": "true",
    "min_num_matches": "15",
    "max_num_models": "50",
    "max_model_overlap": "20",
    "min_model_size": "10",
    "init_image_id1": "-1",
    "init_image_id2": "-1",
    "init_num_trials": "200",
    "num_threads": "-1",
    "ba_local_num_images": "6",
    "ba_local_max_num_iterations": "25",
    "ba_global_pba_gpu_index": "-1",
    "ba_global_images_freq": "500",
    "ba_global_points_freq": "250000",
    "ba_global_max_num_iterations": "50",
    "ba_global_max_refinements": "5",
    "ba_local_max_refinements": "2",
    "snapshot_images_freq": "0",
    "init_min_num_inliers": "100",
    "init_max_reg_trials": "2",
    "abs_pose_min_num_inliers": "30",
    "max_reg_trials": "3",
    "tri_max_transitivity": "1",
    "tri_complete_max_transitivity": "5",
    "tri_re_max_trials": "1",
    "min_focal_length_ratio": "0.1",
    "max_focal_length_ratio": "10",
    "max_extra_param": "1",
    "ba_global_images_ratio": "1.1",
    "ba_global_points_ratio": "1.1",
    "ba_global_max_refinement_change": "0.0005",
    "ba_local_max_refinement_change": "0.001",
    "init_max_error": "4",
    "init_max_forward_motion": "0.95",
    "init_min_tri_angle": "16",
    "abs_pose_max_error": "12",
    "abs_pose_min_inlier_ratio": "0.25",
    "filter_max_reproj_error": "4",
    "filter_min_tri_angle": "1.5",
    "tri_create_max_angle_error": "2",
    "tri_continue_max_angle_error": "2",
    "tri_merge_max_reproj_error": "4",
    "tri_complete_max_reproj_error": "4",
    "tri_re_max_angle_error": "5",
    "tri_re_min_ratio": "0.2",
    "tri_min_angle": "1.5",
    "snapshot_path": ""
   },
  "DenseStereo": 
  {
    "geom_consistency": "true",
    "filter": "true",
    "write_consistency_graph": "false",
    "max_image_size": "2000",
    "window_radius": "5",
    "num_samples": "15",
    "num_iterations": "5",
    "filter_min_num_consistent": "2",
    "sigma_spatial": "5",
    "sigma_color": "0.2000000029802322",
    "ncc_sigma": "0.6000000238418579",
    "min_triangulation_angle": "1",
    "incident_angle_sigma": "0.8999999761581421",
    "geom_consistency_regularizer": "0.300000011920929",
    "geom_consistency_max_cost": "3",
    "filter_min_ncc": "0.1000000014901161",
    "filter_min_triangulation_angle": "3",
    "filter_geom_consistency_max_cost": "1",
    "cache_size": "32",
    "gpu_index": "-1"
   },
  "Render": 
  {
    "adapt_refresh_rate": "true",
    "image_connections": "false",
    "min_track_len": "3",
    "refresh_rate": "1",
    "projection_type": "0",
    "max_error": "2"
   },
  "log_level": "2",
  "ExhaustiveMatching": 
  {
    "block_size": "50"
   },
  "VocabTreeMatching": 
  {
    "num_images": "100",
    "num_verifications": "0",
    "max_num_features": "-1",
    "vocab_tree_path": "",
    "match_list_path": ""
   },
  "TransitiveMatching": 
  {
    "batch_size": "1000",
    "num_iterations": "3"
   },
  "DenseFusion": 
  {
    "max_image_size": "-1",
    "min_num_pixels": "5",
    "max_num_pixels": "10000",
    "max_traversal_depth": "100",
    "check_num_images": "50",
    "max_reproj_error": "2",
    "max_depth_error": "0.009999999776482582",
    "max_normal_error": "10",
    "cache_size": "32"
   },
  "DenseMeshing": 
  {
    "depth": "13",
    "num_threads": "-1",
    "point_weight": "1",
    "color": "32",
    "trim": "10"
   },
  "database_path": "/home/sebastian/Desktop/TEST/images",
  "image_path": "/home/sebastian/Desktop/TEST/images"
 }


 ============================== Ini File ==============================

log_to_stderr=false
[ImageReader]
single_camera=false
default_focal_length_factor=1.2
camera_model=SIMPLE_RADIAL
camera_params=
[SiftExtraction]
use_gpu=true
estimate_affine_shape=false
upright=false
domain_size_pooling=false
num_threads=-1
max_image_size=3200
max_num_features=8192
first_octave=-1
num_octaves=4
octave_resolution=3
max_num_orientations=2
dsp_num_scales=10
peak_threshold=0.006666666666666667
edge_threshold=10
dsp_min_scale=0.1666666666666667
dsp_max_scale=3
gpu_index=-1
[SiftMatching]
use_gpu=true
cross_check=true
multiple_models=false
guided_matching=false
num_threads=-1
max_num_matches=32768
max_num_trials=10000
min_num_inliers=15
max_ratio=0.8
max_distance=0.7
max_error=4
confidence=0.999
min_inlier_ratio=0.25
gpu_index=-1
[SequentialMatching]
quadratic_overlap=true
loop_detection=false
overlap=5
loop_detection_period=10
loop_detection_num_images=30
loop_detection_num_verifications=0
loop_detection_max_num_features=-1
vocab_tree_path=
[SpatialMatching]
is_gps=true
ignore_z=true
max_num_neighbors=50
max_distance=100
[BundleAdjustment]
refine_focal_length=true
refine_principal_point=false
refine_extra_params=true
max_num_iterations=100
max_linear_solver_iterations=200
function_tolerance=0
gradient_tolerance=0
parameter_tolerance=0
[Mapper]
ignore_watermarks=false
multiple_models=true
extract_colors=true
ba_refine_focal_length=true
ba_refine_principal_point=false
ba_refine_extra_params=true
ba_global_use_pba=true
tri_ignore_two_view_tracks=true
min_num_matches=15
max_num_models=50
max_model_overlap=20
min_model_size=10
init_image_id1=-1
init_image_id2=-1
init_num_trials=200
num_threads=-1
ba_local_num_images=6
ba_local_max_num_iterations=25
ba_global_pba_gpu_index=-1
ba_global_images_freq=500
ba_global_points_freq=250000
ba_global_max_num_iterations=50
ba_global_max_refinements=5
ba_local_max_refinements=2
snapshot_images_freq=0
init_min_num_inliers=100
init_max_reg_trials=2
abs_pose_min_num_inliers=30
max_reg_trials=3
tri_max_transitivity=1
tri_complete_max_transitivity=5
tri_re_max_trials=1
min_focal_length_ratio=0.1
max_focal_length_ratio=10
max_extra_param=1
ba_global_images_ratio=1.1
ba_global_points_ratio=1.1
ba_global_max_refinement_change=0.0005
ba_local_max_refinement_change=0.001
init_max_error=4
init_max_forward_motion=0.95
init_min_tri_angle=16
abs_pose_max_error=12
abs_pose_min_inlier_ratio=0.25
filter_max_reproj_error=4
filter_min_tri_angle=1.5
tri_create_max_angle_error=2
tri_continue_max_angle_error=2
tri_merge_max_reproj_error=4
tri_complete_max_reproj_error=4
tri_re_max_angle_error=5
tri_re_min_ratio=0.2
tri_min_angle=1.5
snapshot_path=
[DenseStereo]
geom_consistency=true
filter=true
write_consistency_graph=false
max_image_size=2000
window_radius=5
num_samples=15
num_iterations=5
filter_min_num_consistent=2
sigma_spatial=5
sigma_color=0.2000000029802322
ncc_sigma=0.6000000238418579
min_triangulation_angle=1
incident_angle_sigma=0.8999999761581421
geom_consistency_regularizer=0.300000011920929
geom_consistency_max_cost=3
filter_min_ncc=0.1000000014901161
filter_min_triangulation_angle=3
filter_geom_consistency_max_cost=1
cache_size=32
gpu_index=-1
[Render]
adapt_refresh_rate=true
image_connections=false
min_track_len=3
refresh_rate=1
projection_type=0
max_error=2
**log_level=2**
[ExhaustiveMatching]
block_size=50
[VocabTreeMatching]
num_images=100
num_verifications=0
max_num_features=-1
vocab_tree_path=
match_list_path=
[TransitiveMatching]
batch_size=1000
num_iterations=3
[DenseFusion]
max_image_size=-1
min_num_pixels=5
max_num_pixels=10000
max_traversal_depth=100
check_num_images=50
max_reproj_error=2
max_depth_error=0.009999999776482582
max_normal_error=10
cache_size=32
[DenseMeshing]
depth=13
num_threads=-1
point_weight=1
color=32
trim=10
database_path=/home/sebastian/Desktop/TEST/images
image_path=/home/sebastian/Desktop/TEST/images

**Comment by jbriales** [comment]
Hi,
I'm getting exactly this same error in the same circumstances (that is, using only COLMAP 3.2 for saving and loading). In my case I'm also using Ubuntu 14.04 at the moment, so this might be the issue as pointed by @SBCV above.
Any chances this will be fixed for Ubuntu 14.04 users?

**Comment by ahojnnes** [comment]
@jbriales @SBCV Could you please check whether the following change fixes the problem for you?

In ``src/util/option_manager.cc`` L710:
```
void OptionManager::Write(const std::string& path) const {
  boost::property_tree::ptree pt;

  for (const auto& option : options_bool_) {
    if (option.first.find(".") == std::string::npos) {
      pt.put(option.first, *option.second);
    }
  }

  for (const auto& option : options_int_) {
    if (option.first.find(".") == std::string::npos) {
      pt.put(option.first, *option.second);
    }
  }

  for (const auto& option : options_double_) {
    if (option.first.find(".") == std::string::npos) {
      pt.put(option.first, *option.second);
    }
  }

  for (const auto& option : options_string_) {
    if (option.first.find(".") == std::string::npos) {
      pt.put(option.first, *option.second);
    }
  }

  for (const auto& option : options_bool_) {
    if (option.first.find(".") != std::string::npos) {
      pt.put(option.first, *option.second);
    }
  }

  for (const auto& option : options_int_) {
    if (option.first.find(".") != std::string::npos) {
      pt.put(option.first, *option.second);
    }
  }

  for (const auto& option : options_double_) {
    if (option.first.find(".") != std::string::npos) {
      pt.put(option.first, *option.second);
    }
  }

  for (const auto& option : options_string_) {
    if (option.first.find(".") != std::string::npos) {
      pt.put(option.first, *option.second);
    }
  }

  boost::property_tree::write_ini(path, pt);
}
```

Thanks.

**Comment by SBCV** [comment]
Hi Johannes,

yes, this patch fixes the problem. Thanks!

Cheers,
Sebastian

**Comment by ahojnnes** [comment]
Great, thanks very much for the feedback!

**Comment by ahojnnes** [comment]
@SBCV This is now fixed in the dev branch.
