### ISSUE TITLE
How to switch from COLMAP format to TUM file format

### ISSUE THREAD

**Issue by Lee-JaeWon** [colmap/colmap#2313]
I want to check by changing the COLMAP format to the TUM format.
COLMAP has QW QX QY QX TX TY TZ, and TUM contains the same items only in different order.
If I just change the order of COLMAP results and make it into TUM format, it looks weird in TUM format. Do I need to do additional work?

**Comment by Leerw** [comment]
Have you found the solution? @Lee-JaeWon

**Comment by Lee-JaeWon** [comment]
@Leerw Just change the order. The problem was that the coordinate system was different between COLMAP and my quaternian. I figured out the dataset and matched the coordinate system of the two.
