### ISSUE TITLE
Linux - Problem with Feature Extraction/Matching

### ISSUE THREAD

**Issue by embed-3d** [colmap/colmap#232]
When I create a new project and run feature extraction, features are found. When I proceed now to matching, nothing really happens.. (The log displays: Matching block [1/2, 1/2] and I can wait hours and nothing happens) 

It looks like that the database has some issues:
![grafik](https://user-images.githubusercontent.com/17102789/31439588-ffe0c40e-ae8c-11e7-90e5-bf9d95ae8a1d.png)

When I compare it with the tutorial: https://youtu.be/P-EC0DzeVEU?t=1m33s the content of Database management is different

System:
Ubuntu 16.04.3 LTS
(no cuda graphics card)
installed with the build script

Feature extraction settings (default- only disabled gpu):
![grafik](https://user-images.githubusercontent.com/17102789/31439970-849e584a-ae8e-11e7-92c5-20962c57c19e.png)

Feature matching settings (default- only disabled gpu):
![grafik](https://user-images.githubusercontent.com/17102789/31440455-4423ede6-ae90-11e7-98fb-557df80f35e8.png)

Dataset:
https://1drv.ms/u/s!Am5GkbZS_98XqJcY7pZBjtpooG3AGQ

The Tutorial I'm trying to follow:
https://pfalkingham.wordpress.com/2017/04/04/photogrammetry-testing-8-colmap/

**Comment by ahojnnes** [comment]
Why did you disable the ``use_gpu`` option in matching? This will run matching on the CPU, which is very slow if you have many extracted features per image.

**Comment by embed-3d** [comment]
When I enable it get error messages similar to this thread https://groups.google.com/forum/#!topic/colmap/K1PdI3Q6nwA and at the beginning:
WARNING: OpenGL Version of SiftGPU only supports a maximum of 8192 matching - consider changing to CUDA-base ...
On my windows 7 computer with cuda-enabled gpu this runs in minutes, on the linux pc with use_gpu I cancled it after 8 Hours

**Comment by ahojnnes** [comment]
It's just a warning and might lead to slightly reduced matching results. In general, the matching still works and, to prevent this warning, you could set the maximum number of features in the extraction stage lower.

**Comment by embed-3d** [comment]
Thanks! Finally I was able to get it working.

**Comment by ericpan0513** [comment]
@ahojnnes : Hi, I've got a question.
if it shows the following warning, does that mean I'm not using GPU?
I've checked Nvidia-smi and shows my GPU has no process running.
I make sure that a make use_gpu = True `--SiftExtraction.use_gpu=true`
Do you know anything about this issue? Thanks

WARNING: Your current options use the maximum number of threads on the machine to extract features. Extracting SIFT features on the CPU can consume a lot of RAM per thread for large images. Consider reducing the maximum image size and/or the first octave or manually limit the number of extraction threads. Ignore this warning, if your machine has sufficient memory for the current settings.
