### ISSUE TITLE
Check failed: camera.ModelId() == PinholeCameraModel::model_id

### ISSUE THREAD

**Issue by cezarbabin** [colmap/colmap#233]
When trying to do a dense_stereo computation from the CLI on a Ubuntu 14.04 server, I get the following error: 
`Check failed: camera.ModelId() == PinholeCameraModel::model_id`

Has anyone encountered/solved this problem? It seems that the image_undistort function doesn't update the camera model in the database.

**Comment by ahojnnes** [comment]
Are you on the master or dev branch?

**Comment by cezarbabin** [comment]
master

**Comment by ahojnnes** [comment]
Can you show the exact command that you are running?

**Comment by cezarbabin** [comment]
`colmap/build/src/exe/dense_stereo  --workspace_path ./`

**Comment by ahojnnes** [comment]
And the contents of the folder "./" are? Do you see a "stereo", "sparse", "images" folder in there?

**Comment by ahojnnes** [comment]
Closing this due to lack of feedback. Feel free to reopen if needed.

**Comment by isolin** [comment]
Hi, I just encountered the very same error using the 3.5dev release. `heck failed: camera.ModelId() == PinholeCameraModel::model_id (2 vs. 1)` at model.cc:67. In my case the folder contains stereo, sparse and images subfolders. As far as I remember the sparse data is copied automatically, but this time I have to copy it by my self from the respective sparse folder.

**Comment by ahojnnes** [comment]
I suspect that you overwrote the sparse folder in the undistorted output (which is an undistorted sparse reconstruction) with the original sparse reconstruction (e.g. using the export model button in the GUI). The output of the i distortion stage will always produce a PINHOLE camera model for all cameras in a sparse reconstruction.
