### ISSUE TITLE
cudart64_12.dll missing on V3.9.1 for Windows

### ISSUE THREAD

**Issue by Begalov** [colmap/colmap#2342]
**Describe the bug**
On run COLMAP.bat I've got System error - cudart64_12.dll not found

**Screenshots**
![image](https://github.com/colmap/colmap/assets/437009/b1768550-a272-4024-99b5-3f785a40dc22)

**Fix**
Download dll from https://www.dllme.com/dll/files/cudart64_12 and put it to lib folder

**Environment:**
 - OS:  Windows 11
 - COLMAP Version 3.9.1

**Comment by ahojnnes** [comment]
Thanks, I added the missing file to the zip file.

**Comment by taxue-alfred** [comment]
The ".dll" file was released in CUDA-toolkit 12.x version.
