### ISSUE TITLE
pre-built app not work on apple silicon

### ISSUE THREAD

**Issue by YoohJH** [colmap/colmap#2343]
<img width="961" alt="截屏2024-01-10 17 10 53" src="https://github.com/colmap/colmap/assets/43691048/b28aa076-768a-42ca-9d76-36d4eb03d917">

**Comment by ahojnnes** [comment]
I don't have a recent enough mac myself anymore to build these binaries. I also don't have cycles to automate this through a CI build process. The recommended way to go is homebrew.

**Comment by justinTM** [comment]
@YoohJH here is a built binary on M1. let me know if this helps

[colmap-3.9.1-macos-arm64.tar.gz](https://github.com/colmap/colmap/files/14939143/colmap-3.9.1-macos-arm64.tar.gz)

**Comment by alexmyczko** [comment]
what about making a https://brew.sh?
