### ISSUE TITLE
Issue with Colmap poses visualization - visualize_model.py

### ISSUE THREAD

**Issue by pknmax** [colmap/colmap#2348]
I am using this script, https://github.com/colmap/colmap/blob/fb3fa6a6962f8fee299d03b895cac2e1dd052104/scripts/python/visualize_model.py#L132 
to visualize the colmap poses computed for gaussian-splatting using https://github.com/graphdeco-inria/gaussian-splatting/blob/main/convert.py

But it seems like X and Y axis are flipped, cameras should point downwards, why?

![Screenshot from 2024-01-12 09-57-14](https://github.com/colmap/colmap/assets/152391989/bafbe1ff-20d8-4bac-844c-d92dca6a94db)

SIBR viewer output:
![Screenshot from 2024-01-11 23-05-01](https://github.com/colmap/colmap/assets/152391989/f79a0a5f-1f97-4d26-91c6-4058e1a797e3)

**Comment by pknmax** [comment]
Hello @ahojnnes @UncleGene,
can you please look into this, I am facing this problem even when I am using colmap camera system?

**Comment by attilaolah** [comment]
I'm sorry I'm not a maintainer here, someone else who knows better might be able to help you. I'm just a user myself.
