### ISSUE TITLE
Warningmessage "GLSL 1.5 not supported"

### ISSUE THREAD

**Issue by Nos-** [colmap/colmap#235]
Hi

If I use Colmap some functions seems to be (nearly) nothing since the new installation of my PC.
According to some warnings in the terminal some Colmap-scripts complains about a missing GLSL-profile: "GLSL 1.5 is not supported" (but i have 1.1, 1.2, 1.3, 2, 3 etc. installed).

I am using the current Version of Fedora Linux on a Intel i5 Quadcore with an old NVidia-3D-Graphiccard.

**Comment by ahojnnes** [comment]
Note that GLSL has a weird version numbering system wrt. OpenGL, see https://en.wikipedia.org/wiki/OpenGL_Shading_Language#Versions 

Did you install the Mesa open source drivers or the proprietary drivers from NVIDIA? I know from own experience that the Mesa sometimes do not provide all OpenGL functionality. Try installing the proprietary drivers if not already done.

**Comment by ahojnnes** [comment]
I assume this is resolved? Feel free to reopen if not.
