### ISSUE TITLE
Low GPU usage during reconstruction

### ISSUE THREAD

**Issue by zaqxs123456** [colmap/colmap#2354]
It use near 0% GPU during reconstruction (according to nvidia-smi) and total usage around 25%, same as idle, but when in feature matching and dense reconstruction it fully utilize my GUI so I think it is not compile/CUDA problem, is it normal?

I compiled it from source, OS: Ubuntu 22.04, GPU: RTX3090, CUDA version: 12.3

Thank you very much!

**Comment by tsattler** [comment]
Feature extraction and matching are done on the GPU. Sparse reconstruction is done on the CPU.

**Comment by zaqxs123456** [comment]
Thank you very much!
