### ISSUE TITLE
colmap: error while loading shared libraries: libQt5Core.so.5

### ISSUE THREAD

**Issue by szhang963** [colmap/colmap#2357]
**Describe the bug**

**To Reproduce**
1. docker pull colmap/colmap:latest
2. go to docker container
3. run command 'colmap'
"colmap: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory"

**Environment:**
 - OS: Linux
 - COLMAP Version latest
- no physical display

**Comment by JiajieLi7012** [comment]
I also have this problem. Can anyone provide some help? Thanks in advance.

**Comment by szhang963** [comment]
hi, all
I solved this problem by running the following command.
`strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5`
