### ISSUE TITLE
How can I convert images.txt parameters into extrinsics matrix.

### ISSUE THREAD

**Issue by ypollet** [colmap/colmap#2358]
Hello, 
We are currently working on a 3D viewer of calibrated images and we need to convert the data that we get from the output of colmap (cameras.txt and images.txt) into intrinsic and extrinsic matrices.
My coordinate system is similar to Opencv : 
- X-axis right
- Y-axis down
- Z-axis forward

We thought we only needed to convert quaternions but I get weird results.

This is what colmap gui shows me after computation of the sparse point cloud :
![Screenshot from 2024-01-19 14-50-17](https://github.com/colmap/colmap/assets/37735022/cbb208fa-1804-4553-bcfa-5ce8d62d50e8)

This is what it should look like (it is from the same dataset of images, we did the calibration through an other software) : 
![Screenshot from 2024-01-19 15-10-06](https://github.com/colmap/colmap/assets/37735022/14e4bff9-9f23-4cce-984a-49aa50029610)

And this is what the calibration with Colmap looks like (after the conversion I am trying to do) :
![Uploading Screenshot from 2024-01-19 15-09-42.png…]()

The points in red are the horizontal "row" of pictures of the object.

This is the code, and I use scipy.Rotation to convert the quaternions to a rotation matrix
`
with open(ext_path) as f:
        while True:
            line = f.readline()
            
            if not line:
                # EOF
                break
            if line.startswith("#"):
                # Comment
                continue

            split = line.split()

            # IMAGE_ID, QW, QX, QY, QZ, TX, TY, TZ, CAMERA_ID, NAME
            index = split[0]
            quaternion = [float(split[1]), float(split[2]), float(split[3]), float(split[4])]
            trans = np.matrix([float(split[5]), float(split[6]), float(split[7])])

            
            #camera_id = split[8] not needed
            filename = split[9]

            r = R.from_quat(quaternion)
            rotation_mat = r.as_matrix()
            
            trans_vec = trans.T

            hola = np.hstack((rotation_mat, trans_vec))
            ext_mat = np.vstack((hola, [0,0,0,1]))

            extrinsics[filename] = {"matrix" : ext_mat.tolist()}

            # skip next line
            f.readline()
`

I couldn't find anyone showing a similar code on github.

Thank you in advance for your reply

**Comment by jaco001** [comment]
![image](https://github.com/colmap/colmap/assets/67650086/73a5b3c7-8f42-476a-8f1f-c60add11c340)
And scale down?

**Comment by ypollet** [comment]
@jaco001 First thank you for your reply

 Yes I will eventually need to scale down, but at the moment it isn't a requirement. All I want now is calibrated images to a scale factor. (I have the distance between 2 points of the model and also a prior calibration of the setup that I can use to approximate the scale factor).

I'll take your idea and here are the images with an emphasize on the axis to make it more clear.

This is the desired output (at least something similar) :
![metashape_with_axes](https://github.com/colmap/colmap/assets/37735022/84633f7a-be81-4bc6-94dc-3ca7eeea5a81)

This is what I get from colmap (and the conversion I make from quaternions to Extrinsics matrix) :
![colmap_with_axes](https://github.com/colmap/colmap/assets/37735022/1b870a51-31c5-4847-9a93-20f951a72781)

The green dot is the same image, the frontal view of the object.

I haven't look on how to rotate of the world (in relation with the rotation of the object) but atm, all I'd like to have is a sphere of cameras pointing to their center (as the first picture, and as what I see on colmap)

**Comment by jaco001** [comment]
Imho no need to rotate just multiple  axis by -1 like in your last pic
x(desired)= x (colmap)
y(desired)=-y (colmap)
z(desired)=-z (colmap)

And after that scale down like 20 times.

**Comment by ypollet** [comment]
sorry, I didn't show the rotation of the cameras (to not put to many info on the graph), but the cameras need to be directed at the center.
Without noise, the translation vector should be equals to (0,0,d) with d equals the distance between the camera and the object (and the center of that object is at the origin).

What I think I need is to transform the Rotation Matrix (or the quaternions) and to understand the math.

I think that there is a possibility that the trans vectors don't even need to be modified.

**Comment by ypollet** [comment]
Okok I found qvec2rotmat in [read_write_model.py](https://github.com/colmap/colmap/blob/main/scripts/python/read_write_model.py). I'd have to understand why scipy.Rotation didn't work here.
But here is the result : 
![Screenshot from 2024-01-23 16-44-35](https://github.com/colmap/colmap/assets/37735022/264a98ae-5bf2-4b57-967c-6ef075d7bf5b)
