### ISSUE TITLE
Very few points in dense point cloud

### ISSUE THREAD

**Issue by 10110111** [colmap/colmap#237]
I've checked out the `dev` branch as suggested in #236, and with it I do get to the end with nonzero point count. But the problem is that the "dense" `fused.ply` point cloud has only 351 points, and `meshed.ply` has no vertices at all. What could be a problem? For comparison, when trying the same two images in Agisoft's PhotoScan, it gave me 118961 points in the dense cloud, so I suppose COLMAP's figure should be somewhere near that order of magnitude on success.

P.S. I don't have any rights to re-open the issue I didn't close.

**Comment by ahojnnes** [comment]
Sorry, didn't know you couldn't reopen the issue. Checkout https://github.com/colmap/colmap/commit/6d64195aa8b3eb1423c30623c8cdd94e96beca24 which should further improve the situation for two-view reconstructions. Note that the filtering will not work very reliably in this case, so I still suggest to use more images :-)

**Comment by 10110111** [comment]
OK, so now I get 5417 points with 2 images on medium quality, but `meshed.ply` is still void of any vertices. With 3 images I do get much more points, namely 29619, but `meshed.ply` still has no vertices. When I try high quality with 2 images, `meshed.ply` gets some vertices, but the shape there is useless — it's just a slightly deformed sphere with a hole; I guess it's because there are very many outliers in the dense point cloud.
(High quality with 3 images results in `ResizePyramid:  out of memory` and lots of `FilterH:        an illegal memory access was encountered` errors.)

**Comment by ahojnnes** [comment]
There seems to be a problem with your GPU. How much GPU memory do you have? What's the resolution of your images?

**Comment by 10110111** [comment]
I have 1GiB of VRAM, and the images resolution is 4272x2848 (for those in the set of 3 images).

**Comment by ahojnnes** [comment]
1GB is not enough for this image resolution. You could try to set the `--max_image_size` parameter or use the low quality option in the automatic reconstructor. Please refer to https://colmap.github.io/faq.html#reduce-memory-usage-during-dense-reconstruction for more information.

**Comment by 10110111** [comment]
Yes, and then we come to the other problem: when `--quality medium` is in use, `automatic_reconstructor` does finish successfully, but then `meshed.ply` has no vertices.

**Comment by ahojnnes** [comment]
The meshing is using the Poisson Reconstruction library, where seemingly the default parameters are not tuned for low resolution. Please refer to https://github.com/colmap/colmap/blob/master/src/mvs/meshing.h#L25 for the available parameters.

**Comment by Kai-46** [comment]
Thanks @ahojnnes . I'm working on adding support for skew parameter in colmap. The sparse reconstruction has been successfully so far after I incorporated skew.

However,  the PMVS step in colmap failed because it assumes a PINHOLE model; eventually, the 'colmap image_undistorter' would encode every other camera model into the PINHOLE model, I guess. Do you have any suggestions regarding how to add skew support to the PMVS step?

Thanks in advance.

**Comment by ahojnnes** [comment]
It would be great if you could share the implementation of the slew parameter as a pull request to see if we can integrate it into COLMAP for other people as well. PMVS should work without a problem, or you run the image_undistorter on your reconstruction with skew. Either you remove the skew in the undistortion process or you modify the export to PMVS in a way that accounts for the skew to compose the projection matrix.
