### ISSUE TITLE
VisibilityPyramid questions

### ISSUE THREAD

**Issue by nosleduc** [colmap/colmap#24]
If the number of levels is equal to zero does it mean that there is only one cell, the image itself ?
If yes in this case, the maximum score is 1 and not 0?

Why for each level the maximum score is incremented by dim * dim *dim * dim and not dim * dim

**Comment by nosleduc** [comment]
I read your article and I see where it comes from

**Comment by ahojnnes** [comment]
Hi,

Thanks for your question. I'll close the issue then. Feel free to reopen, if you have any other questions.

Best,
Johannes
