### ISSUE TITLE
build.py - which python3?

### ISSUE THREAD

**Issue by Oberberg** [colmap/colmap#242]
I am trying to build Colmap 3.2 in Opensuse Leap 42.3, but I cannot run scripts/python/build.py:
`~/colmap/colmap-3.2> python3 scripts/python/build.py --help 
 File "scripts/python/build.py", line 136 
   *args.cmake_config_args, 
                       ^
SyntaxError: can use starred expression only as assignment target

~/colmap/colmap-3.2> python3 --version 
Python 3.4.6
`
I do not know enough python to understand this.

**Comment by ahojnnes** [comment]
Can you try to use the following function and report back whether this solved your problem:
```
def build_cmake_project(args, path, extra_config_args=[],
                        extra_build_args=[]):
    mkdir_if_not_exists(path)
    subprocess.call(["cmake"] + args.cmake_config_args
                     + extra_config_args + [".."], cwd=path)
    subprocess.call(["cmake",
                     "--build", ".",
                     "--target", "install",
                     "--config", args.build_type]
                     + args.cmake_build_args
                     + extra_build_args, cwd=path)
```

**Comment by Oberberg** [comment]
By substituting the above code into build.py the problem was solved. Thanks.
