### ISSUE TITLE
rig_bundle_adjuster converging but not constraining cam extrinsics

### ISSUE THREAD

**Issue by shubham-monarch** [colmap/colmap#2423]
I have a **stereo-camera** rig setup. The two cameras are placed parallel to each other and are separated by `13cm` in the x-direction.

Let me show the **relative poses** of the two cameras after performing `sparse_reconstruction` and **before** running the `rig_bundle_adjuster`  => 
![Screenshot from 2024-02-15 17-03-23](https://github.com/colmap/colmap/assets/135956656/89653015-c50c-4aef-9b7f-e1ccf17c5eb1)

Then, I ran the `rig_bundle_adjuster` through cli => 

`colmap rig_bundle_adjuster --input_path /home/skumar/pixel-perfect-sfm/outputs/monarch-demo/ref_locked/hloc/ --output_path /home/skumar/rig_stereo_colmap_cli_output --rig_config_path /home/skumar/rig_stereo_colmap_cli_output/rig.json --estimate_rig_relative_poses 0  
--BundleAdjustment.refine_focal_length 0 
--BundleAdjustment.refine_extra_params 0 
--BundleAdjustment.max_num_iterations 500` 

Let me share the **generated log** for the `rig_bundle_adjuster` => 
```
Cameras: 2
Snapshots: 42

==============================================================================
Rig bundle adjustment
==============================================================================

iter      cost      cost_change  |gradient|   |step|    tr_ratio  tr_radius  ls_iter  iter_time  total_time
   0  1.156823e+08    0.00e+00    1.92e+09   0.00e+00   0.00e+00  1.00e+04        0    1.48e-02    7.51e-02

CHOLMOD version 3.0.14, Oct 22, 2019: Symbolic Analysis: status: OK
  Architecture: Linux
    sizeof(int):      4
    sizeof(SuiteSparse_long):  8
    sizeof(void *):   8
    sizeof(double):   8
    sizeof(Int):      4 (CHOLMOD's basic integer)
    sizeof(BLAS_INT): 4 (integer used in the BLAS)
  Results from most recent analysis:
    Cholesky flop count: 2.0583e+06
    Nonzeros in L:       21423
  memory blocks in use:          11
  memory in use (MB):           0.0
  peak memory usage (MB):       0.1
  maxrank:    update/downdate rank:   8
  supernodal control: 1 40 (supernodal if flops/lnz >= 40)
  nmethods:   number of ordering methods to try: 1
    method 0: natural
        flop count: 2.0583e+06
        nnz(L):     21423
  OK
   1  4.059793e+04    1.16e+08    3.84e+06   6.19e+00   1.00e+00  3.00e+04        1    9.10e-02    1.66e-01
   2  3.429620e+04    6.30e+03    2.90e+05   4.34e+00   9.94e-01  9.00e+04        1    2.34e-01    4.00e-01
   3  3.415487e+04    1.41e+02    5.46e+04   1.56e+00   9.86e-01  2.70e+05        1    1.34e-01    5.34e-01
   4  3.413280e+04    2.21e+01    2.46e+04   1.48e+00   9.99e-01  8.10e+05        1    2.44e-01    7.78e-01
   5  3.412925e+04    3.55e+00    2.49e+03   8.39e-01   1.01e+00  2.43e+06        1    1.09e-01    8.87e-01
   6  3.412910e+04    1.44e-01    4.20e+02   1.94e-01   1.01e+00  7.29e+06        1    2.29e-01    1.12e+00
   7  3.412910e+04    1.12e-03    4.28e+01   1.73e-02   1.02e+00  2.19e+07        1    9.03e-02    1.21e+00
   8  3.412910e+04    3.24e-06    2.73e+00   7.62e-04   1.05e+00  6.56e+07        1    1.40e-01    1.35e+00
   9  3.412910e+04    1.06e-08    1.69e-01   3.24e-05   1.05e+00  1.97e+08        1    2.87e-01    1.63e+00
  10  3.412910e+04    1.31e-10    1.04e-02   1.75e-06   2.47e+00  5.90e+08        1    2.53e-01    1.89e+00


Rig Bundle adjustment report
----------------------------
    Residuals : 62918
   Parameters : 24714
   Iterations : 11
         Time : 1.92093 [s]
 Initial cost : 42.8791 [px]
   Final cost : 0.736504 [px]
  Termination : Convergence
```

As we can see that it says that it has **converged**. 

Here's how my `rig.json` file looks => 
```
[
  {
    "ref_camera_id": 1,
    "cameras":
    [
      {
          "camera_id": 1,
          "image_prefix": "left",
          "rel_tvec": [0, 0, 0],
          "rel_qvec": [1, 0, 0, 0]
      },
      {
          "camera_id": 2,
          "image_prefix": "right",
          "rel_tvec": [-0.13, 0, 0],
          "rel_qvec": [1, 0, 0, 0]
      }
    ]
  }
]
``` 

Let me show the relative poses of the two cameras **after** running the `rig_bundle_adjuster` => 
![Screenshot from 2024-02-15 17-10-22](https://github.com/colmap/colmap/assets/135956656/2f2fd79c-1848-47a9-a406-8cec19378234)

As we can see, the `dx`,`dy`,`dz` don't seem to be obeying the constraints. The quaternions `qx`,`qy`,`qz` and `qw` seem to be obeying the constraints though. 

What could the possible issue? 

EDIT ONE =>
Could it be a case of the bundle adjustment getting stuck in a local minima? If so, would seeding the BA with the initial GPS poses help?

**Comment by shubham-monarch** [comment]
@WuKeyu in this particular case, I was passing some wrong parameters to the `rig_bundle_adjuster` api. 

I am attaching the corrected version for your reference — 

```
#You must set $COLMAP_EXE_PATH to
#the directory containing the COLMAP executables
COLMAP_EXE_PATH=/usr/local/bin
INPUT_PATH=$HOME/benchmark_pixSFM/pixsfm_outputs/ref_locked
OUTPUT_PATH=$PWD/output/
RIG_CONFIG_PATH=$PWD/rig.json

echo "INPUT_PATH ===> $INPUT_PATH"
echo "OUTPUT_PATH ===>  $OUTPUT_PATH"
echo "RIG_CONFIG_PATH ===> $RIG_CONFIG_PATH"

rm -rf $OUTPUT_PATH
mkdir -p "$OUTPUT_PATH"

$COLMAP_EXE_PATH/colmap rig_bundle_adjuster \
	--input_path $INPUT_PATH \
	--output_path $OUTPUT_PATH \
	--rig_config_path $RIG_CONFIG_PATH \
	--BundleAdjustment.refine_focal_length 0 \
	--BundleAdjustment.refine_principal_point 0 \
	--BundleAdjustment.refine_extra_params 1 \
	--BundleAdjustment.refine_extrinsics 1 \
	--estimate_rig_relative_poses False

```

It is true that the `rig_bundle_adjuster` doesn't strictly constrain the rig according to the configuration specified in the configuration file. What I did to solve this issue was to play around with different values in the config file.

**Comment by WuKeyu** [comment]
> @WuKeyu in this particular case, I was passing some wrong parameters to the `rig_bundle_adjuster` api.
> 
> I am attaching the corrected version for your reference —
> 
> ```
> #You must set $COLMAP_EXE_PATH to
> #the directory containing the COLMAP executables
> COLMAP_EXE_PATH=/usr/local/bin
> INPUT_PATH=$HOME/benchmark_pixSFM/pixsfm_outputs/ref_locked
> OUTPUT_PATH=$PWD/output/
> RIG_CONFIG_PATH=$PWD/rig.json
> 
> echo "INPUT_PATH ===> $INPUT_PATH"
> echo "OUTPUT_PATH ===>  $OUTPUT_PATH"
> echo "RIG_CONFIG_PATH ===> $RIG_CONFIG_PATH"
> 
> rm -rf $OUTPUT_PATH
> mkdir -p "$OUTPUT_PATH"
> 
> $COLMAP_EXE_PATH/colmap rig_bundle_adjuster \
> 	--input_path $INPUT_PATH \
> 	--output_path $OUTPUT_PATH \
> 	--rig_config_path $RIG_CONFIG_PATH \
> 	--BundleAdjustment.refine_focal_length 0 \
> 	--BundleAdjustment.refine_principal_point 0 \
> 	--BundleAdjustment.refine_extra_params 1 \
> 	--BundleAdjustment.refine_extrinsics 1 \
> 	--estimate_rig_relative_poses False
> ```
> 
> It is true that the `rig_bundle_adjuster` doesn't strictly constrain the rig according to the configuration specified in the configuration file. What I did to solve this issue was to play around with different values in the config file.

thank you very much
