### ISSUE TITLE
perf and accuracy issue using visual index matching

### ISSUE THREAD

**Issue by hiakru** [colmap/colmap#244]
hey,
Try to follow below paper, to get a better perf and accuracy during localization. 
         Schönberger, Price, Sattler, Pollefeys, Frahm. "A Vote-and-Verify Strategy for Fast Spatial Verification in Image Retrieval". ACCV 2016.

Baseline(Perf: 1.2s, Accuracy: 8m): 
                               **Vocabulary tree get the image pairs + GPU get Matches + RANSAC get Inliner** 
I directly removed the last 2 parts, add Vote_and_Verify. Processing like:
                               **Vocabulary tree get the image pairs + VW get matches + Vote_and_verify get inliner**

However,
                the result shows worse perf(2.7s), also accuracy

I did some deep dive, found some reasons, but not very sure:
**1. current colmap using multi-GPU Multi-Thread to speed up (baseline scenario), but Vote_and_verify does not
2. Vote_and_verify will loop num_verifications times, (could some how improved by multi-thread)
3. not very sure about the VoteAndVerifyOptions during vote_and Verify procedure. just used default.(Any suggestions?)**

Your suggestions will be pretty much appreciated~~~

Thanks and best regards,
Wei

**Comment by ahojnnes** [comment]
How do you get the matches from the VW? Note that with the implementation in COLMAP you cannot exactly reproduce the numbers from the paper. The performance (speed, accuracy) also depends on the number of features you use. For fewer features, the VW based matching should be faster.

**Comment by hiakru** [comment]
matches from VW is implemented in QueryWithVerification function:
https://github.com/colmap/colmap/blob/master/src/retrieval/visual_index.h
from line 284~295, each query feature will match to points quantized to same VW.

I use sift d-128 features, which should be common, right?

**Comment by ahojnnes** [comment]
@hiakru Okay, you are right. I forgot that I implemented this. Regarding the features, yes this is common but you can detect fewer features in the images. By default, COLMAP extract a lot of features, which is not necessary for the pure retrieval task. I would limit the maximum number of features to ~1-2k.

**Comment by hiakru** [comment]
Current the implement of the Vote_and_Verify  solution is sequential, without using Multi-CPU or GPU. Will this be update?  Now is slower than GPU Brute force matching + RANSAC filtering.

**Comment by ahojnnes** [comment]
This is not true, as this totally depends on the size of the database and the number of retrieved images.

**Comment by hiakru** [comment]
Yeah, thanks~
One more question, for large-scale localization, Feature Matching and Geometric Verification are most time cost part. except below 2 motheds, is there other fast motheds in colmap?
**Vocabulary tree get the image pairs + GPU get Matches + RANSAC get Inliner**
**Vocabulary tree get the image pairs + VW get matches + Vote_and_verify get inliner**

Thanks
Wei

**Comment by ahojnnes** [comment]
You can combine the two as Vocabulary tree get the image pairs + VW get matches + Vote_and_verify get inliner + Re-ranking + GPU get Matches + RANSAC get Inliner

Otherwise no, not at the moment.

**Comment by ahojnnes** [comment]
Closing this as resolved. Let me know if there are other questions.
