### ISSUE TITLE
Does Multi-GPU feature extraction really works

### ISSUE THREAD

**Issue by hiakru** [colmap/colmap#245]
hey,
From Doc https://github.com/colmap/colmap/blob/master/doc/faq.rst  Multi-GPU support in feature extraction/matching,

but from code side, a little bit diff, line 431 in https://github.com/colmap/colmap/blob/master/src/base/feature_extraction.cc 
CHECK_EQ(gpu_indices.size(), 1) << "SiftGPU can only run on one GPU";

it seems just support CUDA parallel computing on just one GPU, right?

Your suggestions will be much appreciated~
thanks,
Wei

**Comment by ahojnnes** [comment]
You are looking at the function to create a single instance of a feature extractor, which can only run on a single GPU at a time. Using multiple such instances, multi-GPU support is implemented here: https://github.com/colmap/colmap/blob/dev/src/feature/extraction.h#L35 (note that this is the dev branch rather than the master branch that you linked to).

**Comment by hiakru** [comment]
Yeah, but what I mean is,  if I just want to extract one image, it will just employ one gpu, right?

**Comment by ahojnnes** [comment]
Yes, there will not be any benefit doing that on multiple GPUs anyway due to synchronization overhead.

**Comment by hiakru** [comment]
Got it !  Thanks @ahojnnes

**Comment by hiakru** [comment]
Sorry for reopen it!
I found the current SiftGpu extraction is a little faster( for my case, improve 100ms) than previous, still on just one image sift extraction.

is it because of  this improvement?
https://github.com/colmap/colmap/commit/7b2c48ae036dde3876b5554f6d01234289cde65a, which directly copy keypoints?
or because of  
https://github.com/colmap/colmap/commit/a602f8483fd0d66bb14224028516d01196f71012, which change:
![image](https://user-images.githubusercontent.com/33151098/32645700-946daf94-c623-11e7-8fea-e01e8a76da68.png)


I'm not sure, could you give some suggestions?

ps: what's the diff of :
![image](https://user-images.githubusercontent.com/33151098/32645781-f49c4dee-c623-11e7-8863-561b64a42cee.png)


thanks,
Wei

**Comment by hiakru** [comment]
As we discussed, for one image feature extraction, both running on one GPU+ cuda
Recently synced up my colmap code, found some amazing improvement. Previously my version is https://github.com/colmap/colmap/commit/b44473edb70704c5f82a5dd181015d7c5d767f1e, pretty older~

**Comment by ahojnnes** [comment]
@hiakru I am not sure which versions of COLMAP you are comparing, but I recently refactored the feature extraction stage to have full multi-threading/GPU support in all stages (image loading/resizing, descriptor extraction, writing to database). This should have resulted in a large speed improvement. In addition, I suggest to checkout the new `domain_size_pooling` option, which should result in much better features.
