### ISSUE TITLE
What is problem with code?

### ISSUE THREAD

**Issue by yaong23** [colmap/colmap#2452]
HI
I want to make chat program with a server and multiple clients.
But,After I clicked a in-Button on a client window, a server window is closed.
I think there is a problem in a server window's code.

void server::onReadyRead(QTcpSocket *clientSocket) {
    QByteArray packetData = clientSocket->readAll();

    if (packetData.size() < static_cast<int>(sizeof(Packet))) {
        return;
    }

    Packet packet;
    memcpy(&packet, packetData.constData(), sizeof(Packet));

    QString clientName = getClientNameFromPacket(packet);

    saveClientList(clientName);
    updateClientList(clientName);

    connect(clientSocket, &QTcpSocket::disconnected, this, [=]() {
        onClientDisconnected(clientName);
    });

    broadcast(clientSocket, packetData, clientName);
}

QString server::getClientNameFromPacket(const Packet &packet) {
    return QString(packet.header.opcode.sourceCode);
}

specially,  return QString(packet.header.opcode.sourceCode); HERE!!

here is a server and client code.

please help me....

<< SERVER_H>>
#ifndef SERVER_H
#define SERVER_H

#include <QMainWindow>
#include <QTcpServer>
#include <QTcpSocket>
#include <QList>
#include <QTextBrowser>
#include <QListWidget>
#include <QDateTime>
#include <QMap>
#include <QFile>
#include <QTextCursor>
#include <QtEndian> // Added to use Qt endian conversion functions

QT_BEGIN_NAMESPACE
namespace Ui {
class server;
}
QT_END_NAMESPACE

struct Opcode
{
    QString sourceCode; // Sender (server) code. Device sending the message
    char destCode; // Receiver (client) code. Device receiving the message
    short commandCode; // Command code to be executed. Command the receiver should perform
};

struct Header // Commonly included in the message to describe information about the message
{
    Opcode opcode; // Coded command to be executed
    int size; // Size of the data following
};

struct Packet
{
    Header header; // Commonly included in the message to describe information about the message
    QByteArray data; // Data. The size of this data is described in the Data Size above
};

class server : public QMainWindow
{
    Q_OBJECT

public:
    server(QWidget *parent = nullptr);
    ~server();

private slots:
    void start_ui(bool disableWidgets);
    void on_openButton_clicked();
    void on_closeButton_clicked();

    void onReadyRead(QTcpSocket *clientSocket);
    void onNewConnection();
    void onClientDisconnected(const QString &clientName);
    void updateClientList(const QString &clientName);
    void removeClientFromList(const QString &clientName);
    //void removeClientFromIgnoreList(const QString &clientName); // Added: function to remove client from ignoreList

 //   void on_clientList_currentItemChanged(QListWidgetItem *current, QListWidgetItem *previous);
    void on_acceptButton_clicked();
    void on_ignoreButton_clicked();
    void updateIgnoreClientList_UI();
    //void updateClientList_UI();

    void on_kickButton_clicked();
    void removeClientFromIgnoreList_UI(const QString &clientName);
    void updateClientList_UI();
    void saveIgnoreList(const QString &clientName);
    void saveClientList(const QString &clientName);
    // Initially made separate slots, but there must be a way to combine them, right?
    void removeFromIgnoreList(const QString &clientName);
    void removeFromClientList(const QString &clientName);
    void clearFile(const QString &filePath);
    void updateChatHistory();

    void reset_list(bool resetLists);
    void broadcast(QTcpSocket *clientSocket, const QByteArray &Data, const QString &clientName);

private:
    Ui::server *ui;
    QTcpServer *server0;
//  QList<QString> messageHistory;     // Data structure to store messages received from clients
    QMap<QTcpSocket *, QString> clientMap;
    QTcpSocket *getSocketByClientId(const QString &clientName);

    QMap<QTcpSocket*, QString> ignoreList; // List of clients to ignore
    QString clientName;
    QTcpSocket *getSocketByignoredClientId(const QString &clientName);
    //QString getClientNameFromPacket(QTcpSocket *clientSocket);
    QString getClientNameFromPacket(const Packet &packet);
};

<< << SERVER_cpp >>
void server::onReadyRead(QTcpSocket *clientSocket) {
    // Read packet from client socket
    QByteArray packetData = clientSocket->readAll();

    // Compare the size of received data with the size of Packet structure to ensure it's enough
    if (packetData.size() < static_cast<int>(sizeof(Packet))) {
        qDebug() << "Error: Insufficient packetData size";
        return;
    }

    // Convert packet to structure and extract data
    Packet packet;
    memcpy(&packet, packetData.constData(), sizeof(Packet));

    // Extract client name from packet
    QString clientName = getClientNameFromPacket(packet);

    // Save client list and update UI
    saveClientList(clientName);
    updateClientList(clientName);

    // Used when connection is closed, [=]: copy all external variables like clientName so that they can be used
    connect(clientSocket, &QTcpSocket::disconnected, this, [=]() {
        onClientDisconnected(clientName);
    });

    qDebug() << "onReadyRead completed";

    // Perform broadcasting after receiving packet from client
    broadcast(clientSocket, packetData, clientName);
}

QString server::getClientNameFromPacket(const Packet &packet) {
    // Extract client name from the packet's source code
    return QString(packet.header.opcode.sourceCode);
}

< < CLIENT_H > >
#ifndef CLIENT_H
#define CLIENT_H

#include <QMainWindow>
// QTcpServer: newConnection 시그널을 제공하여 클라이언트 연결 감지 가능, 특정 주소 & 포트에서 클라이언트 연결 대기, 수락 가능
#include <QTcpServer>
// QTcpSocket: 클라이언트로 사용될때, 원격 호스트에 연결하고 데이터를 보내고 받는 데 사용/ 서버로 사용될 때, 클이언트의 연결을 수락, 데이터를 주고 받는 데 사용.
#include <QTcpSocket>
#include <QRandomGenerator>
#include <QFile>
#include <QDateTime>
#include <QTextStream>
#include <QtEndian>
#include <QtGlobal>

QT_BEGIN_NAMESPACE
namespace Ui {
class client;
}
QT_END_NAMESPACE

struct Opcode
{
    QString sourceCode; // 송신자(클라이언트) 코드. 메시지를 송신하는 장치
    // 난 이걸 clientName으로 해서 보내고 싶기 때문에 QString으로 변경
    char destCode; // 수신자(서버) 코드. 메시지를 수신하는 장치
    short commandCode; // 수행 명령 코드. 수신자가 수행해야하는 명령
};

struct Header // 메시지에 공통으로 포함되어 메시지에 대한 정보를 기술
{
    Opcode opcode; // 코드화된 수행 명령
    int size; // 뒤따라 오는 데이터의 크기
};

struct Packet
{
    Header header; // 메시지에 공통으로 포함되어 메시지에 대한 정보를 기술
    QByteArray data; // 데이터. 이 데이터의 크기는 상기 Data Size에 기술됨
};

class client : public QMainWindow
{
    Q_OBJECT

public:
    client(QWidget *parent = nullptr);
    ~client();

private slots:
    void start_ui();
    void on_inButton_clicked();
    void on_outButton_clicked();
    void on_sendButton_clicked();
    void onConnected();
    void enableUI();
    void disableUI();
    void sendMessageToServer(const QString &message);
    void onReadyRead();
    void saveChatLog(const QString &message);
    void generateUniqueClientName(); // 중복되지 않는 랜덤한 클라이언트 이름 생성

private:
    Ui::client *ui;
    QTcpSocket *socket;
    QString clientName;
    QSet<QString> usedClientNames; // 사용된 클라이언트 이름을 추적하기 위한 집합

};
#endif // CLIENT_H

<< CLIENT_CPP .>

#include "client.h"
#include "ui_client.h"

client::client(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::client)
{
    ui->setupUi(this);
    start_ui();
    // Disable unnecessary UI elements (only enable in/out buttons)
    ui->outButton->setEnabled(false);
    ui->inputMessage->setEnabled(false);
    ui->sendButton->setEnabled(false);
    ui->chatDisplay->setEnabled(false);
    socket = new QTcpSocket(this);

    // AbstractSocket: TCP connection socket
    connect(socket, &QAbstractSocket::connected, this, &client::onConnected);
    connect(socket, &QAbstractSocket::readyRead, this, &client::onReadyRead);

    // Generate a random client name (user0 ~ user99)
    generateUniqueClientName();
}

void client::start_ui() {
    ui->outButton->setEnabled(false);
    ui->inputMessage->setEnabled(false);
    ui->sendButton->setEnabled(false);
    ui->chatDisplay->setEnabled(false);
}

// Generate a unique random client name
void client::generateUniqueClientName()
{
    // Set the maximum number of attempts (up to 99, so set to 100)
    const int maxAttempts = 100;

    for (int i = 0; i < maxAttempts; ++i) {
        // Generate a random client name
        QString newName = "user" + QString::number(QRandomGenerator::global()->bounded(100));

        // Check for duplicates
        if (!usedClientNames.contains(newName)) {
            // If not duplicated, set the new name and display it in the UI
            clientName = newName;
            ui->label_clientName->setText(clientName);
            usedClientNames.insert(newName); // Add to the list of used names
            return; // Exit as the generation is completed
        }
    }
}

client::~client()
{
    delete ui;
}

// Enter button
void client::on_inButton_clicked() {
    // Attempt to connect to the server
    socket->connectToHost(QHostAddress("127.0.0.1"), 12000);

    if (socket->waitForConnected()) {
        // Connection successful
        onConnected();
        sendMessageToServer("<font color=\"blue\">" + clientName + " has joined.");
    } else {
        // Connection failed
        qDebug() << "(inButton) Connection failed";
    }
}

// Exit button
void client::on_outButton_clicked()
{

    // Disable UI
    disableUI();
    ui->outButton->setEnabled(false); // Disable exit button to prevent double-clicking
    ui->inButton->setEnabled(true);
    ui->chatDisplay->clear();
    // Send exit message to the server
    sendMessageToServer(clientName + " has left.");

    // Disconnect from the server
    socket->disconnectFromHost();
}

// Slot called when the connection is successful
void client::onConnected()
{
    // Code to handle successful connection
    qDebug() << "Connected to server!";
    enableUI();
    ui->outButton->setEnabled(true);
    ui->inButton->setEnabled(false);
}

// Function to enable UI elements
void client::enableUI() {
    ui->inputMessage->setEnabled(true);
    ui->sendButton->setEnabled(true);
    ui->chatDisplay->setEnabled(true);
}

// Function to disable UI elements
void client::disableUI() {
    ui->inputMessage->setEnabled(false);
    ui->sendButton->setEnabled(false);
    ui->chatDisplay->setEnabled(false);
}

// Send button
void client::on_sendButton_clicked()
{
    // Get the input message
    QString message = ui->inputMessage->toPlainText();
    QString timeString = QDateTime::currentDateTime().toString("hh:mm:ss");

    // Create message header...but not sure what this part is doing
    // It's been searched and added, but don't understand what it does..
    // Create message header
    Opcode opcode;
    opcode.sourceCode = clientName; // Set client name as sender code
    opcode.destCode = 'S'; // Set destination code as server
    opcode.commandCode = qToLittleEndian<quint16>(1); // 1: send chat

    Header header;
    header.opcode = opcode;
    header.size = qToLittleEndian<quint32>(message.toUtf8().size()); // Set data size

    Packet packet;
    packet.header = header;
    packet.data = message.toUtf8(); // Set data

    // Send the packet to the server via the socket
    socket->write(reinterpret_cast<const char*>(&packet), sizeof(Packet));

    // Display as [user0~99] message
    QString fullMessage = timeString + " [" + opcode.sourceCode + "] " + packet.data;

    // Check if the client is in the ignoreList, and add "(ignored)" to the message

    // Display the input message in chatDisplay
    ui->chatDisplay->append("<b>(Me)" + fullMessage + "</b>");

    // Send the message to other clients via the server
    sendMessageToServer(fullMessage);

    // Clear the input field
    ui->inputMessage->clear();

    // Save the chat log
    saveChatLog(fullMessage);
}

void client::sendMessageToServer(const QString &fullMessage)
{
    // Send the message to the server via the TCP socket
    if(socket->state() == QAbstractSocket::ConnectedState) {
        QByteArray data = fullMessage.toUtf8();
        socket->write(data);
        qDebug() << "Message sent to server:" << fullMessage;
    } else {
        qDebug() << "Not connected to server!";
    }
}

void client::onReadyRead()
{
    // Read the header
    QByteArray data = socket->readAll();
    QString message = QString::fromUtf8(data);
    /*
    if (static_cast<unsigned int>(headerData.size()) < sizeof(Packet)) {
        // Header data is not fully received, more data reception is needed
        return;
    }

    Packet header;
    // Copy headerData to the header structure in memory
    // Number of bytes to copy is sizeof(header)
    memcpy(&header, headerData.constData(), sizeof(header));

    // Read data
    // This part also requires understanding.
    QByteArray data;
    while (static_cast<unsigned int>(data.size()) < qFromLittleEndian<quint32>(header.header.size)) {
        QByteArray chunk = socket->read(qMin(packetr.header.size - data.size(), static_cast<quint32>(1024))); // Read up to 1024 bytes at a time
        if (chunk.isEmpty()) {
            // No more data to read
            break;
        }
        data.append(chunk);
    }
    if (static_cast<unsigned int>(data.size()) < qFromLittleEndian<quint32>(header.header.size)) {
        // Data is not fully received, more data reception is needed
        return;
    }
*/
    qDebug() << "Message received from server:" << data;

    // Display the received message in the UI
    ui->chatDisplay->append(message);

    // Add the received message to the chat log
    saveChatLog(message);
}

void client::saveChatLog(const QString &message)
{
    // Generate file name based on current date and time
    QString fileName = QDateTime::currentDateTime().toString("yyyy-MM-dd-hh-mm-ss-zzz") + ".log";

    // Set the directory to save the chat log
    QString directory = "C:/Users/User/Documents/chat_program/chat_log"; // Example directory

    // Generate file path
    QString filePath = directory + "/" + fileName;

    // Open the text file (append mode)
    QFile file(filePath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Append | QIODevice::Text)) {
        qDebug() << "Failed to open file for writing:" << file.errorString();
        return;
    }

    // Create a text stream
    QTextStream out(&file);

    // Write the message to the file
    out << message << "\n";

    // Close the file
    file.close();
}
<img width="775" alt="화면 캡처 2024-03-05 172518" src="https://github.com/colmap/colmap/assets/162292840/93dc0bae-e4eb-4e8e-b298-251cf29938eb">

**Comment by FinnT730** [comment]
Uhm... I am failing to see how this is a Colmap issue?

**Comment by MichaelCurrie** [comment]
This seems completely unrelated to colmap.  Where are the repo maintainers?  Close this one!  :D

**Comment by FinnT730** [comment]
@yaong23 any reason?
@ahojnnes possible that this can be closed?
