### ISSUE TITLE
how to perform fast sparse reconstruction using an image set whose rotations are known precisely (with unknown translations)

### ISSUE THREAD

**Issue by Unsigned-Long** [colmap/colmap#2463]
Given a visual-inertial dataset containing both images and inertial measurements, I can compute precise rotations for all images based on the rotations recovered by IMU and extrinsic rotations between IMU and the camera.

So using this prior knowledge, feature match can be accelerated, which allows fast sparse reconstruction. My question is: is there any way to perform such a task in Colmap?

Note that the translations (positions) of images are **unknown** and need to be optimized.

Thanks for your reply!

**Comment by tsattler** [comment]
Colmap does not use known rotations to accelerate the reconstruction process.

**Comment by Unsigned-Long** [comment]
Thanks for your reply!
