### ISSUE TITLE
Compilation error - ld: library not found for -lopengl32

### ISSUE THREAD

**Issue by SchmidL** [colmap/colmap#247]
I try to compile to compile colmap on a Mac (10.11.6). After fixing the cmake file I could start to compile. Unfortunately I get at the "warp_test" following error

`[ 62%] Linking CXX executable warp_test`
`ld: library not found for -lopengl32`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
`make[2]: *** [src/base/warp_test] Error 1`
`make[1]: *** [src/base/CMakeFiles/warp_test.dir/all] Error 2`
`make: *** [all] Error 2`

Unfortunately I'm not really used to compiling errors due to my general work with python. So sorry if it's a easy to solve question

**Comment by lfrschkn** [comment]
might be connected to Qt5:

did you follow the instructions in the [documentation](https://colmap.github.io/install.html)?
specifically this part:

Create the file LocalConfig.cmake in the COLMAP base directory and then insert the following lines into it:

set(Qt5_CMAKE_DIR "/usr/local/opt/qt5/lib/cmake")
set(Qt5Core_DIR ${Qt5_CMAKE_DIR}/Qt5Core)
set(Qt5OpenGL_DIR ${Qt5_CMAKE_DIR}/Qt5OpenGL)

**Comment by SchmidL** [comment]
Yes this I followed. But I had to add the eigen-dir that it worked because i get this error:
`CMake Error at cmake/FindEigen3.cmake:23 (file):`
`  file failed to open for reading (No such file or directory):`
` `
`    /Users/schmidlorenz/Documents/colmap/<Eigen-dir>/Eigen/src/Core/util/Macros.h`
`Call Stack (most recent call first):`
`  cmake/FindEigen3.cmake:46 (_eigen3_check_version)`
`  CMakeLists.txt:66 (find_package)`
` `
` `
`CMake Error at cmake/FindEigen3.cmake:77 (message):`
`  Could not find Eigen3`
`Call Stack (most recent call first):`
`  CMakeLists.txt:66 (find_package)`
` `
` `
`-- Configuring incomplete, errors occurred!`

...

**Comment by ahojnnes** [comment]
How did you install the dependencies? Using homebrew?

**Comment by SchmidL** [comment]
Yes I used homebrew, copy paste from the instructions (first the tap-science and then all the others)

**Comment by ahojnnes** [comment]
What did you fix in the CMake? You mention something like that in the beginning?

**Comment by ahojnnes** [comment]
Which CMake and Visual Studio version do you use?

**Comment by ahojnnes** [comment]
Ah sorry, I thought you were under Windows. Visual Studio is of course not needed under Mac :-)

I am not sure why you are seeing the errors. Are you on the dev or master branch?

**Comment by SchmidL** [comment]
I would say that I'm on the master branch, at least I just cloned from https://github.com/colmap/colmap.git

**Comment by ahojnnes** [comment]
Can you checkout the dev branch and start from a new build folder? The master branch is already a little dated.

**Comment by SchmidL** [comment]
Checked out the dev branch. So far no improvement... keep you updated

**Comment by ahojnnes** [comment]
Seems like you provided the wrong path for Eigen. You can also try to use the automatic python build script on Mac.

**Comment by jvhaarst** [comment]
I have installed all the dependancies with Homebrew.
I have used the dev branch like this:
 
`git clone -b dev https://github.com/colmap/colmap.git colmap_dev`

And then used this for `LocalConfig.cmake`:
```
set(EIGEN3_INCLUDE_DIRS "/usr/local/include/eigen3/" CACHE PATH "" FORCE)
set(Qt5_CMAKE_DIR "/usr/local/opt/qt5/lib/cmake")
set(Qt5Core_DIR ${Qt5_CMAKE_DIR}/Qt5Core)
set(Qt5OpenGL_DIR ${Qt5_CMAKE_DIR}/Qt5OpenGL)
```

And then it compiles without errors on High Sierra.

I have made a pull request for the documentation, the eigen part wasn't there yet.

**Comment by ahojnnes** [comment]
Strange, I am also on High Sierra and did not have to change this. Thanks for the feedback @jvhaarst

**Comment by ahojnnes** [comment]
This might be interesting to poeple who are struggling to install COLMAP under OS X High Sierra: https://github.com/toriiqq/colmap-mac-high-sierra/blob/master/README.md

**Comment by ahojnnes** [comment]
Closing this due to lack of feedback. Feel free to follow up and reopen.
