### ISSUE TITLE
Unsupported gpu arch compute89

### ISSUE THREAD

**Issue by RongKaiWeskerMA** [colmap/colmap#2472]
Build with cuda12.3, 4080 super

FAILED: src/colmap/mvs/CMakeFiles/colmap_mvs_cuda.dir/gpu_mat_prng.cu.o 
/usr/bin/nvcc -forward-unknown-to-host-compiler -ccbin=/usr/bin/g++-10 -DBOOST_ALL_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_GRAPH_DYN_LINK -DBOOST_REGEX_DYN_LINK -DCERES_EXPORT_INTERNAL_SYMBOLS -DCOLMAP_CGAL_ENABLED -DCOLMAP_CUDA_ENABLED -DCOLMAP_GPU_ENABLED -DCOLMAP_GUI_ENABLED -DCOLMAP_OPENGL_ENABLED -DCOLMAP_OPENMP_ENABLED -DGFLAGS_IS_A_DLL=0 -DGLOG_VERSION_MAJOR=0 -DGLOG_VERSION_MINOR=5 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -I/home/wesker/personal/colmap/src -isystem /home/wesker/anaconda3/include -isystem /usr/include/eigen3 -isystem /home/wesker/anaconda3/include/qt -isystem /home/wesker/anaconda3/include/qt/QtCore -isystem /home/wesker/anaconda3/./mkspecs/linux-g++ -isystem /home/wesker/anaconda3/include/qt/QtOpenGL -isystem /home/wesker/anaconda3/include/qt/QtWidgets -isystem /home/wesker/anaconda3/include/qt/QtGui -isystem /usr/local/cuda-12.3/targets/x86_64-linux/include -Wno-deprecated-gpu-targets --compiler-options -fPIC --use_fast_math --default-stream per-thread -Xptxas=-suppress-stack-size-warning -O3 -DNDEBUG -std=c++14 "--generate-code=arch=compute_89,code=[sm_89]" -Xcompiler=-fPIC -MD -MT src/colmap/mvs/CMakeFiles/colmap_mvs_cuda.dir/gpu_mat_prng.cu.o -MF src/colmap/mvs/CMakeFiles/colmap_mvs_cuda.dir/gpu_mat_prng.cu.o.d -x cu -c /home/wesker/personal/colmap/src/colmap/mvs/gpu_mat_prng.cu -o src/colmap/mvs/CMakeFiles/colmap_mvs_cuda.dir/gpu_mat_prng.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_89'

**Comment by Alex-Beh** [comment]
You can try the following steps:
1.  Find your GPU Compute Capability [here](https://developer.nvidia.com/cuda-gpus#compute)
2. `cmake .. -GNinja -DCMAKE_CUDA_ARCHITECTURES=86`

I am using GeForce RTX 3070, so the Compute Capability is 8.6

**Comment by HermasTV** [comment]
same issue with RTX 4070  laptop, compute capability is 8.9 still getting nvcc fatal   : Unsupported gpu architecture 'compute_89' running ninja command

**Comment by yiduohao** [comment]
I also met the same issue with RTX 4070. Do you have any solution? Thx

**Comment by ahojnnes** [comment]
Which cuda version are you using?

**Comment by RongKaiWeskerMA** [comment]
> same issue with RTX 4070 laptop, compute capability is 8.9 still getting nvcc fatal : Unsupported gpu architecture 'compute_89' running ninja command

I solved the problem by reinstalling the nvidia driver and cuda toolkit

**Comment by yiduohao** [comment]
> Which cuda / cmake version are you using?

The issue was resolved by reinstalling the CUDA toolkit, likely due to conflicts from multiple toolkits.

**Comment by lishuai-97** [comment]
> You can try the following steps:
> 
> 1. Find your GPU Compute Capability [here](https://developer.nvidia.com/cuda-gpus#compute)
> 2. `cmake .. -GNinja -DCMAKE_CUDA_ARCHITECTURES=86`
> 
> I am using GeForce RTX 3070, so the Compute Capability is 8.6
> 
> Related issue: #2091

I followed your advice, but it didn't work

**Comment by PannagaS** [comment]
@yiduohao which cuda toolkit version are you finally using to resolve this issue ?
