### ISSUE TITLE
make errors

### ISSUE THREAD

**Issue by naonaomxy** [colmap/colmap#248]
Thank you for your viewing for my question firstly.
When I 'make' colmap in /build, there is something wrong with it as follows:

**In file included from /usr/local/cuda/include/common_functions.h:50:0,
                 from /usr/local/cuda/include/cuda_runtime.h:115,
                 from <command-line>:0:
/usr/local/cuda/include/crt/common_functions.h:64:24: error: token ""__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."" is not valid in preprocessor expressions
 #define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."
                        ^
/usr/include/eigen3/Eigen/src/Core/util/Macros.h:364:33: note: in expansion of macro ‘__CUDACC_VER__’
 #if defined(__CUDACC_VER__) &&  __CUDACC_VER__ >= 70500 && __cplusplus > 199711L
                                 ^
CMake Error at gpu_mat_test_generated_gpu_mat_test.cu.o.cmake:203 (message):
  Error generating
  /home/yang/data/sfm/colmap/colmap/build/src/mvs/CMakeFiles/gpu_mat_test.dir//./gpu_mat_test_generated_gpu_mat_test.cu.o

src/mvs/CMakeFiles/gpu_mat_test.dir/build.make:63: recipe for target 'src/mvs/CMakeFiles/gpu_mat_test.dir/gpu_mat_test_generated_gpu_mat_test.cu.o' failed
make[2]: *** [src/mvs/CMakeFiles/gpu_mat_test.dir/gpu_mat_test_generated_gpu_mat_test.cu.o] Error 1
CMakeFiles/Makefile2:4991: recipe for target 'src/mvs/CMakeFiles/gpu_mat_test.dir/all' failed
make[1]: *** [src/mvs/CMakeFiles/gpu_mat_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....**

Could you help me to deal with it? Thank you very much.
**Ubuntu 16.04
CUDA 9.0
CuDNN 7.0.4
gcc 5.4.0
boost 1.58
Eigen3**

**Comment by ahojnnes** [comment]
Seems like you use an old version of Eigen. Can you try to use a newer version?

**Comment by ahojnnes** [comment]
Closing this due to lack of feedback. Feel free to follow up in case there is another questions.

**Comment by kitizz** [comment]
For anyone having the same issue, it revolves around changes made in CUDA 9 that Eigen releases are yet to catch up with. (My machine's CUDA was upgraded under me)

I had success by
 1. Uninstalling Eigen and Ceres
 2. Cloning Eigen master `hg clone https://bitbucket.org/eigen/eigen`
 3. Following the ol' Cmake, make, install rigmarole for Eigen
 4. Rebuilding, and installing  Ceres
 5. Building COLMAP source

✅ Great success

**Comment by ahojnnes** [comment]
Thanks for the feedback. Glad you could resolve it.
