### ISSUE TITLE
Build in VS2017 and cuda 9

### ISSUE THREAD

**Issue by YuraIU02** [colmap/colmap#249]
Hello. Sorry for my bad english.
I am trying to build in visual studio 2017 with cuda 9 using python script.
There are errors in command prompt:

...

18>CustomBuild:
         CMake Error at mvs_cuda_generated_gpu_mat_prng.cu.obj.Release.cmake:222 (message):
    13>C:\Project\Colmap\Master\colmap\install\__install__\include\glog/logging.h(721): warning C4018: '>=': signed/uns
       igned mismatch [C:\Project\Colmap\Master\colmap\install\colmap-dev\build\src\feature\feature.vcxproj]
       CustomBuild:
           Error generating

...

   18>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targ
       ets(171,5): error MSB6006: "cmd.exe" завершилась с кодом 1. [C:\Project\Colmap\Master\colmap\install\colmap-dev\
       build\src\mvs\mvs_cuda.vcxproj]
       ClCompile:
                     _Iter=std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<size_t>>>
                 ]
    18>Сборка проекта "C:\Project\Colmap\Master\colmap\install\colmap-dev\build\src\mvs\mvs_cuda.vcxproj" завершена (це
       левые объекты по умолчанию) с ошибкой.
	   
	   ...
	   
	     21>CustomBuild:
         CMake Error at pba_generated_ProgramCU.cu.obj.Release.cmake:222 (message):
           Error generating
           C:/Project/Colmap/Master/colmap/install/colmap-dev/build/src/ext/PBA/CMakeFiles/pba.dir//Release/pba_generat
         ed_ProgramCU.cu.obj

    21>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targ
       ets(171,5): error MSB6006: "cmd.exe" завершилась с кодом 1. [C:\Project\Colmap\Master\colmap\install\colmap-dev\
       build\src\ext\PBA\pba.vcxproj]
    21>Сборка проекта "C:\Project\Colmap\Master\colmap\install\colmap-dev\build\src\ext\PBA\pba.vcxproj" завершена (цел
       евые объекты по умолчанию) с ошибкой.
	   ...
       "C:\Project\Colmap\Master\colmap\install\colmap-dev\build\install.vcxproj" (целевой объект по умолчанию) (1) ->
       "C:\Project\Colmap\Master\colmap\install\colmap-dev\build\ALL_BUILD.vcxproj" (целевой объект по умолчанию) (3) -
       >
       "C:\Project\Colmap\Master\colmap\install\colmap-dev\build\src\exe\automatic_reconstructor.vcxproj" (целевой объе
       кт по умолчанию) (9) ->
       "C:\Project\Colmap\Master\colmap\install\colmap-dev\build\src\mvs\mvs_cuda.vcxproj" (целевой объект по умолчанию
       ) (18) ->
       (CustomBuild конечный объект) ->
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.ta
       rgets(171,5): error MSB6006: "cmd.exe" завершилась с кодом 1. [C:\Project\Colmap\Master\colmap\install\colmap-de
       v\build\src\mvs\mvs_cuda.vcxproj]

       "C:\Project\Colmap\Master\colmap\install\colmap-dev\build\install.vcxproj" (целевой объект по умолчанию) (1) ->
       "C:\Project\Colmap\Master\colmap\install\colmap-dev\build\ALL_BUILD.vcxproj" (целевой объект по умолчанию) (3) -
       >
       "C:\Project\Colmap\Master\colmap\install\colmap-dev\build\src\exe\automatic_reconstructor.vcxproj" (целевой объе
       кт по умолчанию) (9) ->
       "C:\Project\Colmap\Master\colmap\install\colmap-dev\build\src\ext\PBA\pba.vcxproj" (целевой объект по умолчанию)
        (21) ->
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.ta
       rgets(171,5): error MSB6006: "cmd.exe" завершилась с кодом 1. [C:\Project\Colmap\Master\colmap\install\colmap-de
       v\build\src\ext\PBA\pba.vcxproj]

       "C:\Project\Colmap\Master\colmap\install\colmap-dev\build\install.vcxproj" (целевой объект по умолчанию) (1) ->
       "C:\Project\Colmap\Master\colmap\install\colmap-dev\build\ALL_BUILD.vcxproj" (целевой объект по умолчанию) (3) -
       >
       "C:\Project\Colmap\Master\colmap\install\colmap-dev\build\src\exe\bundle_adjuster.vcxproj" (целевой объект по ум
       олчанию) (11) ->
       "C:\Project\Colmap\Master\colmap\install\colmap-dev\build\src\ext\SiftGPU\sift_gpu.vcxproj" (целевой объект по у
       молчанию) (34) ->
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.ta
       rgets(171,5): error MSB6006: "cmd.exe" завершилась с кодом 1. [C:\Project\Colmap\Master\colmap\install\colmap-de
       v\build\src\ext\SiftGPU\sift_gpu.vcxproj]

    Предупреждений: 322
    Ошибок: 3 

And when I try to build mvs_cuda project inside Visual Studio, I get

1>------ Build started: Project: mvs_cuda, Configuration: Release x64 ------
1>Building NVCC (Device) object src/mvs/CMakeFiles/mvs_cuda.dir/Release/mvs_cuda_generated_gpu_mat_prng.cu.obj
1>CMake Error at mvs_cuda_generated_gpu_mat_prng.cu.obj.Release.cmake:222 (message):
1>  Error generating
1>  C:/Project/Colmap/Master/colmap/install/colmap-dev/build/src/mvs/CMakeFiles/mvs_cuda.dir//Release/mvs_cuda_generated_gpu_mat_prng.cu.obj
1>
1>
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
1>Done building project "mvs_cuda.vcxproj" -- FAILED.

**Comment by YuraIU02** [comment]
With latest commit Update "CUDA CMake configuration script" still same error in this configuration.

**Comment by ahojnnes** [comment]
Can you change the locale of you Visual stufio environment, such that the errors appear all in English?

**Comment by YuraIU02** [comment]
The first and main error is:
18>CustomBuild:
CMake Error at mvs_cuda_generated_gpu_mat_prng.cu.obj.Release.cmake:222 (message):
18>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targ
ets(171,5): error MSB6006: "cmd.exe" exited with code 1.[C:\Project\Colmap\Master\colmap\install\colmap-dev
build\src\mvs\mvs_cuda.vcxproj]
ClCompile:
_Iter=std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<size_t>>>
]

**Comment by YuraIU02** [comment]
I will try to change locale and translate other errors tomorrow, but they all only say that build is completed with error.

**Comment by ahojnnes** [comment]
Which Cmake version do you use?

**Comment by YuraIU02** [comment]
I tried all versions from 3.6 to 3.10. Maybe problem is in TdrDelay, unfortunately I cant check right now.

**Comment by ahojnnes** [comment]
So, it seems Visual Studio 2017 and CUDA 9 do not work well in conjunction at the moment. If you downgrade to Visual Studio 2015, it should work without a problem. Just confirmed this on my machine. Let me know if there are other issues.
