### ISSUE TITLE
Failed to build Ceres on vs2015 when build COLMAP

### ISSUE THREAD

**Issue by tmac1002** [colmap/colmap#25]
Hi, 
I want to study COLMAP source code on windows but when I built colmap on vs2015, there always occured some errors. It seems that having a difficulty in build ceres in windows. I tried it lots of times but failed. I saw you solved this problem in google group, but it seems complicated. I was just wondering if you could give me some instructions about building ceres in windows so that I can use colmap in windows. Thank you very much.

**Comment by ahojnnes** [comment]
Please, post the errors you see in Visual Studio. Otherwise, it is not possible for me to help.

**Comment by tmac1002** [comment]
Ｈｉ, 
Maybe this question is easy. I want to debug colmap. But when I run the star function, it will run the all remain part. Could you please tell me how I can step into specific function to see how it work. Thank you very much.

**Comment by ahojnnes** [comment]
I don't know what you mean by "the star" function?

**Comment by tmac1002** [comment]
I mean mapper.Start(); and mapper.Wait();, when I debug the code, it can't step into the specific function but run the all part directly. I just was wondering if I could step into its specific steps and see how it work. Thank you!

**Comment by ahojnnes** [comment]
Set a break point and start the executable in debug mode. This should be standard procedure. Not sure how else I can help here?

**Comment by tmac1002** [comment]
Hi,
When I was ready to built ceres in vs2015 so that I can use colmap in windows, there always encounter some error. But I have already generated sln file using cmake. I use the suitesparse-metis-windows solutioon. But when I built ceres, the errors as follows:
I just saw your answer in google group. so could you please help me look at it? Thank you very much.

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageVoidify::LogMessageVoidify(void)" (__imp_??0LogMessageVoidify@google@@QEAA@XZ) referenced in function "bool __cdecl ceres::`anonymous namespace'::LineSearchOptionsAreValid(struct ceres::Solver::Options const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?LineSearchOptionsAreValid@?A0x91b87f78@ceres@@YA_NAEBUOptions@Solver@2@PEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	ceres	D:\Theia\ceres-solver-1.11.0\build\internal\ceres\solver.obj	1	
Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageVoidify::LogMessageVoidify(void)" (__imp_??0LogMessageVoidify@google@@QEAA@XZ)	ceres	D:\Theia\ceres-solver-1.11.0\build\internal\ceres\trust_region_minimizer.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: void __cdecl google::LogMessageVoidify::operator&(class std::basic_ostream<char,struct std::char_traits<char> > &)" (__imp_??ILogMessageVoidify@google@@QEAAXAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z) referenced in function "bool __cdecl ceres::`anonymous namespace'::LineSearchOptionsAreValid(struct ceres::Solver::Options const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?LineSearchOptionsAreValid@?A0x91b87f78@ceres@@YA_NAEBUOptions@Solver@2@PEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	ceres	D:\Theia\ceres-solver-1.11.0\build\internal\ceres\solver.obj	1	
Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: void __cdecl google::LogMessageVoidify::operator&(class std::basic_ostream<char,struct std::char_traits<char> > &)" (__imp_??ILogMessageVoidify@google@@QEAAXAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)	ceres	D:\Theia\ceres-solver-1.11.0\build\internal\ceres\trust_region_minimizer.obj	1	
Error	LNK2019	unresolved external symbol "public: __cdecl google::FlagRegisterer::FlagRegisterer<int>(char const *,char const *,char const *,int *,int *)" (??$?0H@FlagRegisterer@google@@QEAA@PEBD00PEAH1@Z) referenced in function "void __cdecl fLI::`dynamic initializer for 'o_v''(void)" (??__Eo_v@fLI@@YAXXZ)	ceres	D:\Theia\ceres-solver-1.11.0\build\internal\ceres\glog.lib(vlog_is_on.obj)	1	
Error	LNK2001	unresolved external symbol "public: __cdecl google::FlagRegisterer::FlagRegisterer<int>(char const *,char const *,char const *,int *,int *)" (??$?0H@FlagRegisterer@google@@QEAA@PEBD00PEAH1@Z)	ceres	D:\Theia\ceres-solver-1.11.0\build\internal\ceres\glog.lib(logging.obj)	1	
Error	LNK2019	unresolved external symbol "public: __cdecl google::FlagRegisterer::FlagRegisterer<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >(char const *,char const *,char const *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (??$?0V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@FlagRegisterer@google@@QEAA@PEBD00PEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z) referenced in function "void __cdecl fLS::`dynamic initializer for 'o_vmodule''(void)" (??__Eo_vmodule@fLS@@YAXXZ)	ceres	D:\Theia\ceres-solver-1.11.0\build\internal\ceres\glog.lib(vlog_is_on.obj)	1	
Error	LNK2001	unresolved external symbol "public: __cdecl google::FlagRegisterer::FlagRegisterer<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >(char const *,char const *,char const *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (??$?0V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@FlagRegisterer@google@@QEAA@PEBD00PEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z)	ceres	D:\Theia\ceres-solver-1.11.0\build\internal\ceres\glog.lib(logging.obj)	1	
Error	LNK2019	unresolved external symbol "public: __cdecl google::FlagRegisterer::FlagRegisterer<bool>(char const *,char const *,char const *,bool *,bool *)" (??$?0_N@FlagRegisterer@google@@QEAA@PEBD00PEA_N1@Z) referenced in function "void __cdecl fLB::`dynamic initializer for 'o_alsologtostderr''(void)" (??__Eo_alsologtostderr@fLB@@YAXXZ)	ceres	D:\Theia\ceres-solver-1.11.0\build\internal\ceres\glog.lib(logging.obj)	1	
Error	LNK2019	unresolved external symbol METIS_NodeND referenced in function cholmod_l_metis	ceres	D:\Theia\ceres-solver-1.11.0\build\internal\ceres\libcholmod.lib(cholmod_l_metis.o.obj)	1	
Error	LNK2001	unresolved external symbol METIS_NodeND	ceres	D:\Theia\ceres-solver-1.11.0\build\internal\ceres\libcholmod.lib(cholmod_metis.o.obj)	1	
Error	LNK2019	unresolved external symbol METIS_ComputeVertexSeparator referenced in function cholmod_l_metis_bisector	ceres	D:\Theia\ceres-solver-1.11.0\build\internal\ceres\libcholmod.lib(cholmod_l_metis.o.obj)	1	
Error	LNK2001	unresolved external symbol METIS_ComputeVertexSeparator	ceres	D:\Theia\ceres-solver-1.11.0\build\internal\ceres\libcholmod.lib(cholmod_metis.o.obj)	1	
Error	LNK1120	7 unresolved externals	ceres	D:\Theia\ceres-solver-1.11.0\build\bin\Release\ceres.dll	1

**Comment by ahojnnes** [comment]
Have you fixed this problem in the mean time? Unfortunately, I do not have time to help users with individual compilation/linking issues.

**Comment by ahojnnes** [comment]
Closing this issue due to lack of response. Feel free to reopen. Thanks!
