### ISSUE TITLE
COLMAP: Should stereo be taking so long?

### ISSUE THREAD

**Issue by vaqxai** [colmap/colmap#2505]
I have a dataset containing 1353 images and 114210 points. I'm trying to run Stereo on it (on a RTX 3080 Ti with 12GB VRAM)  - It's been going on for a little under 10 hours and I have no idea if its just calculating or if it got stuck or something, neither the GUI nor the cmdline will display any info about progress. Should it be taking so long?

Edit: I clicked cancel and the next option (Fusion) unlocked itself. Running time was 479 min, maybe it's a bug where it will just go on forever unless canceled? Or maybe I don't understand how Stereo works...

**Comment by Goulustis** [comment]
Yes that's normal... With 1000+ images it'll usually take more than 24 hours. It'll be even worse if your image is high resolution

**Comment by vaqxai** [comment]
Thank you for the answer. Do you know what is the primary factor in the computation time? The speed of the GPU or the amount of VRAM? I'd like to know when considering better hardware for future tasks.

**Comment by Joeljensen28** [comment]
I'm also noticing the amount of time this takes. I've got ~300 images, and it's been running for a couple of hours. Is there any way to maybe lower the quality of the reconstruction to speed up the process?
