### ISSUE TITLE
Build vs2015 with cuda 8 problem

### ISSUE THREAD

**Issue by YuraIU02** [colmap/colmap#251]
I am trying to build using python script. And get error:
```
CMake Error at cmake/SelectCudaComputeArch.cmake:172 (message):
  Unknown CUDA Architecture Name nvcc in CUDA_SELECT_NVCC_ARCH_FLAGS
Call Stack (most recent call first):
  CMakeLists.txt:141 (CUDA_SELECT_NVCC_ARCH_FLAGS)

because in colmap-dev\build\CMakeCache.txt on line 680:

//Returned GPU architetures from detect_gpus tool
CUDA_GPU_DETECT_OUTPUT:INTERNAL=nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
detect_cuda_archs.cu
   Создается библиотека a.lib и объект a.exp
6.1
//ADVANCED property for variable: CUDA_HOST_COMPILATION_CPP
CUDA_HOST_COMPILATION_CPP-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CUDA_NVCC_EXECUTABLE
CUDA_NVCC_EXECUTABLE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CUDA_NVCC_FLAGS
```

**Comment by ahojnnes** [comment]
Which GPU do you have?

**Comment by ahojnnes** [comment]
Can you checkout the latest commit on master or dev and check whether that solves your issue?

**Comment by YuraIU02** [comment]
I set --cuda_multi_arch, "-DBOOST_ROOT=C:/local/boost_1_64_0" and -DBOOST_LIBRARYDIR=C:/local/boost_1_64_0/lib64-msvc-14.0 in build.py, and run on cmake 3.7. And build was successful. 
But when I execute colmap, it fails on auto reconstruction and dense reconstruction stereo button. On another windows without cuda 8 sdk installed, dense reconstruction run successful, but auto reconstruction does not work. 
I have msi gp72m notebook with GeForce gtx 1050. I will try to build your last commit on 2017 VS and cuda 9. Cant you tell what cmake version is preferred?

**Comment by ahojnnes** [comment]
You also need to set the ``--cuda_path`` argument in the build script. Otherwise, CUDA is not enabled.

**Comment by ahojnnes** [comment]
Which Cmake version do you use?

**Comment by YuraIU02** [comment]
I tried 3.7 - 3.10. And as I wrote on 3.7 build was successful. Problem with executing solved with tdr delay.
