### ISSUE TITLE
Are there some problems on my images, which are rendered by Blender, to result failure reconstruction?

### ISSUE THREAD

**Issue by Fanqyu** [colmap/colmap#2514]
Hi, thank everyone who would give some suggestions under this question.
I have just started using this tool recently and I am not very familiar with it yet. Consequently, I cannot tell if it is the images I utilized during the process of SfM or MVS leading to the problem. The results show as the following figure:
<img width="1017" alt="46b51f71000aecd9165097dbda792aab" src="https://github.com/colmap/colmap/assets/108654290/322a5caa-7517-4394-8ce8-4166f83c9766">
As shown in the following figures, those are my images rendered by Blender that are used during reconstructing.
![0000](https://github.com/colmap/colmap/assets/108654290/b805959a-d71f-4100-9cfa-d600dc69a717)
![0001](https://github.com/colmap/colmap/assets/108654290/46b57ba2-b9f2-476b-9b46-3d43dc18e4f1)
![0002](https://github.com/colmap/colmap/assets/108654290/618702a8-95ae-4e09-8e5e-8c24ac280155)
![0003](https://github.com/colmap/colmap/assets/108654290/8a39b254-5609-4726-b955-e43093b4461f)
![0004](https://github.com/colmap/colmap/assets/108654290/2f0f3946-6260-450f-863a-170747928461)
![0005](https://github.com/colmap/colmap/assets/108654290/3103bd79-64ad-4db1-b4a8-18d0e6cb314d)
I have a few image groups, and the figures shown above are one of them. However, in some other groups, the reconstruction can be done perfectly. Thus, I wonder if there are a few requirements when picking the images to use. In other words, is the above issue caused by image quality, such as weak texture, different lighting, etc?
By the way, are there some solutions of adjusting parameters during feature extraction and feature matching process instead of selecting images, since the images are rendered randomly.
Thans a lot! Looking forward to some replies

**Comment by sarlinpe** [comment]
These images exhibit some of the challenges that COLMAP (and other similar systems) still struggle with: lack of distinctive texture and reflective objects (specularities). We don't have a good solution to fix this for now.

**Comment by Fanqyu** [comment]
Thank you for answering my question. It helps me a lot.

**Comment by Fanqyu** [comment]
I see. Thank you for answering my question. It helps me a lot.
