### ISSUE TITLE
Error when accessing Reconstruction.Points3D

### ISSUE THREAD

**Issue by versatran01** [colmap/colmap#2522]
**Describe the bug**
Unable to print the points3D field of a Reconstruction
Possibly related to https://github.com/colmap/colmap/pull/2502

**To Reproduce**
1. Load a reconstruction
2. Try to print recon.points3D
3. Error 
```
>>> recon.points3D
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __repr__(): incompatible function arguments. The following argument types are supported:
    1. (self: dict[int, colmap::Point3D]) -> str

Invoked with: <repr raised Error>
```

**Expected behavior**

**Screenshots**
<img width="700" alt="image" src="https://github.com/colmap/colmap/assets/1883423/6bca40aa-3029-4163-99e7-cb491e4a0f7d">

**Environment:**
 - OS: Ubuntu 22.04
 - COLMAP Version master

**Comment by sarlinpe** [comment]
Thanks for reporting this! Will look into this asap. cc @B1ueber2y

**Comment by B1ueber2y** [comment]
Thanks for reporting! This should be fixed here: https://github.com/colmap/colmap/pull/2523 (pybind11 has a weird parsing logic without the header). Sorry for the inconvenience!

**Comment by sarlinpe** [comment]
I confirm that the proposed fix works.

**Comment by versatran01** [comment]
Thanks all. Confirmed working as well. Closing.
