### ISSUE TITLE
Assert failure in UndistortImage()

### ISSUE THREAD

**Issue by asmaloney** [colmap/colmap#253]
- compiled latest git on macOS (5a066b05234bec2cfe853604c7ca25718bb1afc7) (w/CUDA)
- opened old workspace
- tried to run "Automatic Reconstruction"

```
F1123 12:30:07.590147 14434304 undistortion.cc:776] Check failed: distorted_camera.Width() == distorted_bitmap.Width() (4608 vs. 4609)
*** Check failure stack trace: ***
    @        0x10415e0ce  google::LogMessage::Fail()
    @        0x10415d3ad  google::LogMessage::SendToLog()
    @        0x10415dab3  google::LogMessage::Flush()
    @        0x104160d03  google::LogMessageFatal::~LogMessageFatal()
    @        0x10415e3b7  google::LogMessageFatal::~LogMessageFatal()
    @        0x102e5959a  colmap::UndistortImage()
    @        0x102e57df0  colmap::COLMAPUndistorter::Undistort()
    @        0x102e9088c  std::__1::packaged_task<>::operator()()
    @        0x102fc3bbc  colmap::ThreadPool::WorkerFunc()
    @        0x102fc4c58  _ZNSt3__114__thread_proxyINS_5tupleIJNS_8functionIFvvEEEEEEEEPvS6_
    @     0x7fffd60a793b  _pthread_body
    @     0x7fffd60a7887  _pthread_start
    @     0x7fffd60a708d  thread_start
Abort trap: 6
```

macOS 10.12.6
NVIDIA GeForce GTX 780M 4096 MB

**Comment by ahojnnes** [comment]
how old is the workspace?

**Comment by asmaloney** [comment]
It's from July.

Is there a workspace version in there somewhere I can give you?

**Comment by ahojnnes** [comment]
No, can you show me the command, that you are using to produce the error. For the folder paths that you provide, can you also show me the contents?

**Comment by asmaloney** [comment]
For "command" I'm using the GUI, so I don't see the command. I am going to Reconstruction -> Automatic Reconstruction, selecting the workspace folder, selecting the "Images" folder, and clicking "Run".

I am uploading my data to Google Drive. If you want to contact me via email (<my user name>@gmail.com) I'll send you the link.

**Comment by ahojnnes** [comment]
Hi again, I checked the dataset you sent me and I don't know what went wrong. I processed it again from scratch and it worked fine. Since this does not seem to be an issue that other people experienced, I suggest to just re-process it. I will close this issue for now and thanks for the bug report. Feel free to reopen the issue. Best, Johannes

**Comment by alan355** [comment]
It seems to be the undistorted problem.You should use the images that had been distorted rather the images that is undistorted
