### ISSUE TITLE
Pycolmap unable to register more than two images

### ISSUE THREAD

**Issue by royw99** [colmap/colmap#2545]
I hava used `pycolmap.incremental_mapping()` to reconstruct the 3d scene and estimate the pose of the camera. Yet, I can only register 2 cameras among 55 images that constitute the scene. 

More background: I used RoMa (a detector-free matcher) to produce the matches, and it works perfectly fine with detector-and-descriptors based matchers (generate more than 40 images). The issue doesn't seem to stem from the RoMa model itself as its matching result is pretty good. It is probably also not caused by the number of matches in each pair of images or  number of pairs of images that are paired up, because adjusting these details don't give more than 2 camera registered.

**Comment by sarlinpe** [comment]
How did you import the dense, pixel-wise correspondences of RoMa into COLMAP?

**Comment by royw99** [comment]
> How did you import the dense, pixel-wise correspondences of RoMa into COLMAP?

I have exhaustively compared every pair of images, filter out some pairs under confidence threshold, and then take out every pixel coordinate in an image that has a correpondence in the other image and store it as keypoints of that image (So there sometimes could be more than 300,000 keypoints, but the reconstruction still fail despite sampling to roughly 50000 for every image). I only input keypoints of every image, as well as matches and fundamental matrix of every image pair

**Comment by royw99** [comment]
Also, I have seen that RoMa repo use OpenCV to estimate the relative poses of two cameras that corresponds to an image pair. But they have never used pycolmap to reconstruct the whole scene and estimate its performance. It makes me wonder if dense matching involves a different procedure before being applied to `pycolmap.incremental_mapping()`

**Comment by sarlinpe** [comment]
COLMAP requires points to be observed in 3 distinct images but using pixel coordinates as keypoints yields mostly two-view tracks. I recommend trying out hloc's [`match_dense`](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/match_dense.py), which clusters points into longer tracks required for COLMAP.

**Comment by royw99** [comment]
> COLMAP requires points to be observed in 3 distinct images but using pixel coordinates as keypoints yields mostly two-view tracks. I recommend trying out hloc's [`match_dense`](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/match_dense.py), which clusters points into longer tracks required for COLMAP.

Thanks. Do you mind specifying why pixel coordinate in dense matching is not working. In my experiment, I have also tried keynet-affinenet-adalam to match pixel and it works fine in 3d reconstruction phase. Which part of [make_dense](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/match_dense.py) specifically counters this issue associate with dense matching? I sincerely appreciate your patience in answer these questions

**Comment by sarlinpe** [comment]
With dense matches, the pixels coordinates for a given image are different for each image pair with any other image. This makes it unlikely/impossible to have three-view observations. Sparse matches are different: they are constrained to sparse keypoints, whose coordinates are the same of any image pair.

**Comment by royw99** [comment]
> With dense matches, the pixels coordinates for a given image are different for each image pair with any other image. This makes it unlikely/impossible to have three-view observations. Sparse matches are different: they are constrained to sparse keypoints, whose coordinates are the same of any image pair.

In that sense, should we just quantize the diverse pixel coordinates to sparser keypoints? Is that how the pixel coordinates are post-processed?

**Comment by sarlinpe** [comment]
This is exactly what `match_dense` does. See usage at
https://github.com/cvg/Hierarchical-Localization/blob/e3e953f4db00c3b9b14951482349d5ddd9424452/hloc/pipelines/Aachen_v1_1/pipeline_loftr.py#L57-L65

**Comment by royw99** [comment]
> This is exactly what `match_dense` does. See usage at https://github.com/cvg/Hierarchical-Localization/blob/e3e953f4db00c3b9b14951482349d5ddd9424452/hloc/pipelines/Aachen_v1_1/pipeline_loftr.py#L57-L65

Sorry, I have accidentally deleted the comment the quote addresses. For better readership, the question that @sarlinpe has answered is like this - Should we just quantize the pixel coordinates to sparser keypoints? So @sarlinpe is  essentially saying that [make dense](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/match_dense.py) quantize the pixel coordinate. Hope this will make the thread clearer.

**Comment by royw99** [comment]
> This is exactly what `match_dense` does. See usage at https://github.com/cvg/Hierarchical-Localization/blob/e3e953f4db00c3b9b14951482349d5ddd9424452/hloc/pipelines/Aachen_v1_1/pipeline_loftr.py#L57-L65

Thanks a lot!
