### ISSUE TITLE
Failed to build pycolmap

### ISSUE THREAD

**Issue by zyh2023** [colmap/colmap#2552]
**Describe the bug**

**To Reproduce**
1. I successfully install colmap
2. cd pycolmap
3. I use the command 'python3 -m pip install .'

**Expected behavior**
link@link-MS-7D48:~/software/colmap/pycolmap$ python3 -m pip install .
Processing /home/link/software/colmap/pycolmap
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting numpy
  Downloading numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     |████████████████████████████████| 17.3 MB 740 kB/s 
Building wheels for collected packages: pycolmap
  Building wheel for pycolmap (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmp4xzyqa7j build_wheel /tmp/tmpq0mkfbqv
       cwd: /tmp/pip-req-build-7xr2d0gu
  Complete output (100 lines):
  *** scikit-build-core 0.9.3 using CMake 3.16.3 (wheel)
  2024-05-04 18:32:25,090 - scikit_build_core - WARNING - No license files found, set wheel.license-files to [] to suppress this warning
  *** Configuring CMake...
  loading initial cache file /tmp/tmp_a9c0ymw/build/CMakeInit.txt
  -- The C compiler identification is GNU 9.4.0
  -- The CXX compiler identification is GNU 9.4.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: filesystem graph program_options system
  -- Found FreeImage
  --   Includes : /usr/include
  --   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
  -- Found FLANN
  --   Includes : /usr/include
  --   Libraries : /usr/lib/x86_64-linux-gnu/libflann.so
  -- Found LZ4
  --   Includes : /usr/include
  --   Libraries : /usr/lib/x86_64-linux-gnu/liblz4.so
  -- Found Metis
  --   Includes : /usr/include
  --   Libraries : /usr/lib/x86_64-linux-gnu/libmetis.so
  -- Found Glog
  --   Includes : /usr/include
  --   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
  -- Found SQLite3: /usr/include (found version "3.31.1")
  -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so
  -- Found Glew
  --   Includes : /usr/include
  --   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
  -- Found Git: /usr/bin/git (found version "2.25.1")
  -- Found installed version of Eigen: /usr/lib/cmake/eigen3
  -- Found required Ceres dependency: Eigen version 3.3.7 in /usr/include/eigen3
  -- Found required Ceres dependency: glog
  -- Found installed version of gflags: /usr/lib/x86_64-linux-gnu/cmake/gflags
  -- Detected gflags version: 2.2.2
  -- Found required Ceres dependency: gflags
  -- Found Ceres version: 1.14.0 installed in: /usr with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, OpenMP, Multithreading]
  -- Enabling OpenMP support
  -- Using header-only CGAL
  -- Targetting Ninja
  -- Using /usr/bin/c++ compiler.
  -- Found GMP: /usr/lib/x86_64-linux-gnu/libgmp.so
  -- Found MPFR: /usr/lib/x86_64-linux-gnu/libmpfr.so
  -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.48")
  -- Boost include dirs: /usr/include
  -- Boost libraries:
  -- Using gcc version 4 or later. Adding -frounding-math
  -- Found CGAL
  --   Includes : /usr/include
  --   Libraries : CGAL
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE
  -- Found CUDA version 10.1 installed in /usr via legacy CMake (<3.17) module. Using the legacy CMake module means that any installation of COLMAP will require that the CUDA libraries are available under LD_LIBRARY_PATH.
  -- Found CUDA
  --   Includes : /usr/include
  --   Libraries : /usr/lib/x86_64-linux-gnu/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so
  -- The CUDA compiler identification is NVIDIA 10.1.243
  -- Check for working CUDA compiler: /usr/bin/nvcc
  -- Check for working CUDA compiler: /usr/bin/nvcc -- works
  -- Detecting CUDA compiler ABI info
  -- Detecting CUDA compiler ABI info - done
  -- Enabling CUDA support (version: 10.1, archs: native)
  -- Found Qt
  --   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Core
  --   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5OpenGL
  --   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets
  -- Enabling GUI support
  -- Disabling OpenGL support
  -- Enabling GPU support
  CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
    Could NOT find Python (missing: Interpreter Development.Module) (found
    version "3.8.10")
  Call Stack (most recent call first):
    /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
    /usr/share/cmake-3.16/Modules/FindPython.cmake:347 (find_package_handle_standard_args)
    CMakeLists.txt:22 (find_package)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/tmp_a9c0ymw/build/CMakeFiles/CMakeOutput.log".
  See also "/tmp/tmp_a9c0ymw/build/CMakeFiles/CMakeError.log".
  
  *** CMake configuration failed
  ----------------------------------------
  ERROR: Failed building wheel for pycolmap
Failed to build pycolmap
ERROR: Could not build wheels for pycolmap which use PEP 517 and cannot be installed directly

**Screenshots**
If applicable, add screenshots to help explain your problem. Input images and/or output reconstructions are usually helpful.

**Environment:**
 - OS: [ubuntu20.04]
 - COLMAP Version [3.9]

**Comment by jytime** [comment]
I guess you need to run something like:

apt-get install python3-dev

**Comment by zyh2023** [comment]
> I guess you need to run something like:
> 
> apt-get install python3-dev

Thanks so much.I had already done in before.Finally I upgraded cmake to solve this problem
