### ISSUE TITLE
Database format changed for the `keypoints` table? Not documented.

### ISSUE THREAD

**Issue by raaaaaymond** [colmap/colmap#257]
It used to be that the "data" column "keypoints" table in the database contains 4 columns, indicating the horizontal coordinate, vertical coordinate, scale, and orientation of the key points, all stored as float32. Indeed, this is what the documentation says on [the documentation](http://colmap.github.io) But it seems that in recent versions of Colmap, there are now 6 columns in "data". By my inspection, the first two columns are still the coordinates of the key points, but I don't know what the rest 4 columns are, and the documentation doesn't mention this. Could someone tell me what it is, or update the documentation? I'm happy to update the documentation if you tell me what the columns are. Thank you!

**Comment by ahojnnes** [comment]
I documented the new format, see https://github.com/colmap/colmap/commit/fc46589c526bfd8452fea5eb1d421d422b25599b. Thanks for the feedback.

Let me know if there are any other questions.
