### ISSUE TITLE
Stereo can't be done

### ISSUE THREAD

**Issue by piakchu** [colmap/colmap#258]
When I click the 'stereo' for dense pointcloud, the application just quits and gives the following error message:
QObject::~QObject: Timers cannot be stopped from another thread.
How to deal with it?
I use Win10 and my gpu is GTX 1070.

**Comment by ahojnnes** [comment]
Probably caused by GPU timeout, see https://colmap.github.io/faq.html#fix-gpu-freezes-and-timeouts-during-dense-reconstruction

**Comment by juanqui** [comment]
I am having the same issue and it is not TDR. I have increased the timeout and even disabled it with the exact same results. I am using a GTX1050 on a Windows 10 system. Same error as @piakchu reported.

**Comment by ahojnnes** [comment]
How big are your images? Another reason might be that your GPU runs out of memory and crashes.

**Comment by ahojnnes** [comment]
Closing this due to lack of feedback.
