### ISSUE TITLE
Cmake issue related to"CUDA17", using Ubuntu20 and CUDA12.2, cmake 16

### ISSUE THREAD

**Issue by zhexin1904** [colmap/colmap#2581]
jason@jason-Dell-G15-5511:~/DPGO/colmap_stable/build$ cmake .. -GNinja
-- Found Boost: /usr/local/lib/cmake/Boost-1.83.0/BoostConfig.cmake (found version "1.83.0") found components: filesystem graph program_options system 
-- Found FreeImage
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
-- Found FLANN
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libflann.so
-- Found LZ4
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/liblz4.so
-- Found Metis
--   Includes : /usr/include
--   Libraries : /usr/local/lib/libmetis.so
-- Found Glog
--   Target : glog::glog
-- Found Glew
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
-- Found AMD headers in: /usr/include/suitesparse
-- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
-- Found CAMD headers in: /usr/include/suitesparse
-- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
-- Found CCOLAMD headers in: /usr/include/suitesparse
-- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
-- Found CHOLMOD headers in: /usr/include/suitesparse
-- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
-- Found COLAMD headers in: /usr/include/suitesparse
-- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
-- Found SPQR headers in: /usr/include/suitesparse
-- Found SPQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
-- Found Config headers in: /usr/include/suitesparse
-- Found Config library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
-- Found Intel Thread Building Blocks (TBB) library (2020.1 / 11101) include location: . Assuming SuiteSparseQR was compiled with TBB.
-- Adding librt to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Found required Ceres dependency: Eigen version 3.3.7 in /usr/lib/cmake/eigen3
-- Found required Ceres dependency: glog
-- Found required Ceres dependency: gflags
-- Found Ceres version: 2.2.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, SchurSpecializations, Multithreading]
-- Enabling OpenMP support
-- Using header-only CGAL
-- Targetting Ninja
-- Using /usr/bin/c++ compiler.
-- Found Boost: /usr/local/lib/cmake/Boost-1.83.0/BoostConfig.cmake (found suitable version "1.83.0", minimum required is "1.48")  
-- Boost include dirs: /usr/local/include
-- Boost libraries:    
-- Using gcc version 4 or later. Adding -frounding-math
-- Found CGAL
--   Includes : /usr/include
--   Libraries : CGAL
-- Found CUDA version 12.2 installed in /usr/local/cuda-12.2 via legacy CMake (<3.17) module. Using the legacy CMake module means that any installation of COLMAP will require that the CUDA libraries are available under LD_LIBRARY_PATH.
-- Found CUDA 
--   Includes : /usr/local/cuda-12.2/include
--   Libraries : /usr/local/cuda-12.2/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so
-- Enabling CUDA support (version: 12.2, archs: native)
-- Found Qt
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Core
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5OpenGL
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets
-- Enabling GUI support
-- Enabling OpenGL support
-- Enabling GPU support
-- Build type not specified, using Release
-- Enabling SIMD support
-- Disabling interprocedural optimization
-- Disabling ccache support
-- Disabling profiling support
-- Configuring done
CMake Error in CMakeLists.txt:
  Target "colmap_sources" requires the language dialect "CUDA17" (with
  compiler extensions), but CMake does not know the compile flags to use to
  enable it.

CMake Error in src/colmap/mvs/CMakeLists.txt:
  Target "colmap_mvs_cuda" requires the language dialect "CUDA17" (with
  compiler extensions), but CMake does not know the compile flags to use to
  enable it.

CMake Error in src/thirdparty/SiftGPU/CMakeLists.txt:
  Target "colmap_sift_gpu" requires the language dialect "CUDA17" (with
  compiler extensions), but CMake does not know the compile flags to use to
  enable it.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

I tried set :
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CUDA_STANDARD 17)
set(CMAKE_CUDA_STANDARD_REQUIRED ON)
or something like :
target_compile_features(my_cuda_app PUBLIC cxx_std_17)
target_compile_features(my_cuda_app PUBLIC cuda_std_17)

But it is still con't be compiled

**Comment by ahojnnes** [comment]
Which CMake version are you using? CMake 16 is not a valid version. Do you mean CMake 3.16 ?

**Comment by zhexin1904** [comment]
Oh sorry, Yes, it is CMake 3.16.3

**Comment by ahojnnes** [comment]
Looking at the logs, you'll probably be able to solve the issue by upgrading to CMake 3.17 or later:
> -- Found CUDA version 12.2 installed in /usr/local/cuda-12.2 via legacy CMake (<3.17) module. Using the legacy CMake module means that any installation of COLMAP will require that the CUDA libraries are available under LD_LIBRARY_PATH.

**Comment by zhexin1904** [comment]
Sorry for the late reply, it is solved when the CMake upgrading to higher version, appreciate it !
