### ISSUE TITLE
Why not use ClearModifiedPoints3D in the end of IterativeGlobalRefinement?

### ISSUE THREAD

**Issue by Tonsty** [colmap/colmap#2582]
I found that ClearModifiedPoints3D() is invoked in the end of IterativeLocalRefinement, https://github.com/colmap/colmap/blob/dcfd14b300868c7eb1b360ebbca0dc21acd641b6/src/colmap/sfm/incremental_mapper.cc#L780
but it is not the same for IterativeGlobalRefinement.
https://github.com/colmap/colmap/blob/dcfd14b300868c7eb1b360ebbca0dc21acd641b6/src/colmap/sfm/incremental_mapper.cc#L810
Is it expected or just a bug?

**Comment by ahojnnes** [comment]
Thanks, this may have been introduced recently in some of the refactoring. I think you are right that we could clear the points after global bundle adjustment, since everything was fully optimized and doesn't need to be considered in consecutive local bundle adjustments.

**Comment by Tonsty** [comment]
@ahojnnes , so will you add it in the master or develop branch? I advice that some evaluation cloud be done first. I wonder that maybe this mistake could get unexpected benefit.

**Comment by sarlinpe** [comment]
This wasn't introduced in the recent refactorings - this has been like so since at least 3.5. I don't think that this will have much impact on the accuracy, but sure we can update this.
