### ISSUE TITLE
Create a database from COLMAP .bin and .txt files

### ISSUE THREAD

**Issue by deepak046** [colmap/colmap#2583]
I'm trying to create a **database** file from either .bin or .txt files (cameras, images, and points3D respectively). Generally, these files are easier to edit using pycolmap. In my case, I'm trying to inject noise into just my 2D features to generate a noisy reconstruction from the ground truth (with worse camera poses as well). I have described below in detail what I would like to do:

I run an initial colmap reconstruction and get everything (camera poses, 2D features, matches, reconstructed 3D points). Then using the .txt and .bin files generated by COLMAP I try to add noise into the 2D features alone (without affecting the matches) to perform a new reconstruction again using COLMAP (the process is done to inject noise to the reconstruction done on a simulated dataset).

With just the .txt and .bin files I won't be able to perform the new reconstruction as COLMAP expects a database file with newly noise injected features, and the matches. And thus, I'm trying to figure out a way to create a new database from just the .txt and .bin files.

Does COLMAP already provide any functionality to achieve this? I think it would be really beneficial thing to have to directly create a database from the text and binary files, as COLMAP relies on it for the reconstruction. Kindly let me know if I need to elaborate something

**Comment by ahojnnes** [comment]
No, the database and the cameras/images/points contents cannot be converted to each other. The database contains the feature descriptors and raw/inlier matches while the cameras/images/points does not, while the database cannot store the full sparse reconstruction (i.e., point tracks, etc.).

**Comment by deepak046** [comment]
Yeah okay, thank you. I instead just used the database in place to get the information that I needed.

**Comment by antoinebio** [comment]
hello @ahojnnes 
let me open that topic again.
with COLMAP version
`COLMAP 3.12.6 -- Structure-from-Motion and Multi-View Stereo
(Commit 4d5b60e on 2025-09-17 with CUDA)`
When I use the GUI, I've found out that it was possible to import those file,

<img width="175" height="143" alt="Image" src="https://github.com/user-attachments/assets/9a192ea5-f291-43b0-8945-ab2db0981cf6" />

 more precisely if I point the /spares/0 folder

<img width="524" height="202" alt="Image" src="https://github.com/user-attachments/assets/93ee4371-153e-4f9f-9e6d-0a7e3ce196cd" />

And force creation of database.db by selecting again the /images folder.

looks ok then, as the database is reading the TIEPOINTS

<img width="818" height="380" alt="Image" src="https://github.com/user-attachments/assets/90297771-b90c-4de2-8401-a2c93786a72e" />

But if I just want to replay the BBA, no tiepoints is being used for that.

<img width="1906" height="799" alt="Image" src="https://github.com/user-attachments/assets/69d8a8d7-7d72-4c42-b062-99a14dce133c" />

is it the right procedure to recover former COLMAP output data ?

**Comment by antoinebio** [comment]
maybe the easiest way would be to work with pycolmap.Reconstruction(sparse_path)...
https://github.com/colmap/colmap/blob/374128bd6300a29b7fff6a384c6a94eb1c758eff/python/README.md?plain=1#L98
