### ISSUE TITLE
Would reconstructing the same data multiple times yield completely identical results?

### ISSUE THREAD

**Issue by jiangyijin** [colmap/colmap#2592]
I used colmap 3.9.1 to reconstruct the same dataset multiple times. However, why is the number of points cloud obtained in each reconstruction not the same? Would reconstructing the same data multiple times yield completely identical results? If not, what is the reason for this? How can I modify my code? Below is my Python code:

# Feature extraction
subprocess.run([COLMAP_PATH, "feature_extractor",
                "--database_path", os.path.join(DATASET_PATH, "database.db"),
                "--image_path", IMAGE_PATH,
                "--ImageReader.camera_model", "SIMPLE_PINHOLE",
                "--ImageReader.single_camera", "1"])
    # Feature matching
subprocess.run([COLMAP_PATH, "exhaustive_matcher",
                "--database_path", os.path.join(DATASET_PATH, "database.db"),
                "--SiftMatching.guided_matching", "1",
                "--ExhaustiveMatching.block_size", "100",
                "--TwoViewGeometry.multiple_models", "1"])
subprocess.run([COLMAP_PATH, "mapper",
                "--database_path", os.path.join(DATASET_PATH, "database.db"),
                "--image_path", IMAGE_PATH,
                "--output_path", sparse_path]) 

# Export sparse point cloud
subprocess.run([COLMAP_PATH, "model_converter",
                "--input_path", os.path.join(sparse_path, max_images_folder),
                "--output_path", os.path.join(sparse_path, "sparse.ply"),
                "--output_type", "PLY"])

# Export cameras, images, and points3D to text format (while keeping the binary files)
subprocess.run([COLMAP_PATH, "model_converter",
                "--input_path", os.path.join(sparse_path, max_images_folder),
                "--output_path", os.path.join(sparse_path, max_images_folder),
                "--output_type", "TXT"])

subprocess.run([COLMAP_PATH, "image_undistorter",
                "--image_path", IMAGE_PATH,
                "--input_path", os.path.join(sparse_path, max_images_folder),
                "--output_path", dense_path,
                "--output_type", "COLMAP"])

# Dense reconstruction
subprocess.run([COLMAP_PATH, "patch_match_stereo",
                "--workspace_path", dense_path,
                "--workspace_format", "COLMAP"])

# Fusion
fused_path = os.path.join(dense_path, "fused.ply")
subprocess.run([COLMAP_PATH, "stereo_fusion",
                "--workspace_path", dense_path,
                "--workspace_format", "COLMAP",
                "--input_type", "geometric",
                "--output_path", fused_path])

**Environment:**
 - OS: [e.g. Windows 11]
 - COLMAP Version [e.g. 3.9.1]
 - Capture Device [e.g. Blender]

**Comment by tsattler** [comment]
No, there is a certain randomness to the process. You cannot completely eliminate the randomness. E.g., Ceres (used for bundle adjustment) parallelizes things and the order in which threads finish has some impact on the overall result.

**Comment by jiangyijin** [comment]
> No, there is a certain randomness to the process. You cannot completely eliminate the randomness. E.g., Ceres (used for bundle adjustment) parallelizes things and the order in which threads finish has some impact on the overall result.

Thank you very much for your response!
