### ISSUE TITLE
Binding camera positions (constrained bundle adjustment)

### ISSUE THREAD

**Issue by xiaoxiae** [colmap/colmap#2596]
### **Is your feature request related to a problem? Please describe.**
I have an existing reconstruction and a set of new images that I would like to register to this new reconstruction. It is however important that the parameters of the existing reconstruction don't change (they're the ground truth).

Reading through https://colmap.github.io/faq.html#register-localize-new-images-into-an-existing-reconstruction, the suggested solutions either only register the new images without running bundle adjustment (`image_registrator`) and so are not accurate, or run global bundle adjustment and therefore change the original reconstruction (`bundle_adjuster` or `mapper`).

### **Describe the solution you'd like**
I would like to be able to add the images into the reconstruction and then run constrained bundle adjustment (fixing the parameters of the old reconstruction), preferably in Python but any solution would be great.

### **Describe alternatives you've considered**
I've read through https://github.com/colmap/colmap/commit/0ea2d5ceee1360bba427b2ef61f1351e59a46f91, which binds the mapper to be usable in Python, but don't fully understand if/how I can use it to solve the problem.

I also understand that this can be done via manually formulating a custom BA problem (https://github.com/cvg/pyceres/blob/main/examples/test_BA.ipynb), but lack the knowledge to do this.

---

PS: thank you for creating an amazing project.

**Comment by B1ueber2y** [comment]
Hey. Here we provide an equivalent customized bundle adjustment implementation with pyceres. To be able to fix the positions of some images the most straightforward way is to add ``self.problem.set_parameter_block_constant(image.cam_from_world.rotation.quat)`` and ``self.problem.set_parameter_block_constant(image.cam_from_world.translation)`` for each image to be fixed before ``pyceres.solve`` here: https://github.com/colmap/colmap/blob/main/pycolmap/custom_bundle_adjustment.py#L35. Similar practice also applies to camera parameters.

**Comment by xiaoxiae** [comment]
It turns out that what I actually needed was to use `mapper` in a way that fixes the already registered images, which I managed to do by doing `colmap mapper ... --Mapper.fix_existing_images 1` -- running bundle adjustment would make sense if the images are already registered and need to be improved, which was not the case for me.
