### ISSUE TITLE
Incorrect Mask Path Construction in COLMAP

### ISSUE THREAD

**Issue by DeriZSY** [colmap/colmap#2599]
**Describe the bug**
There is an issue with the mask path construction in COLMAP. 

As suggsted here: https://github.com/colmap/colmap/blob/main/src/colmap/controllers/image_reader.cc#L146

The mask path is generated by joining the mask directory path with the image name and appending ".png". However, the image->Name() function already includes the file extension. This results in incorrect mask paths, such as masks/01.jpg.png when the original image is image/01.jpg.

**To Reproduce**
Use images with extensions (e.g., image/01.jpg).
Set the mask path (e.g., masks/).
Observe the mask path construction (e.g., masks/01.jpg.png).

**Expected behavior**
The mask path should correctly match the image name without appending an extra extension.

**Comment by sarlinpe** [comment]
Mask should be binary and stored losslessly so they should always be in PNG format regardless of the format of the original images. So the added suffix is expected and not a bug.

**Comment by DeriZSY** [comment]
> always

Hi, thanks for the reply. But wouldn't it be better if the name of mask is `01.png` given the image is `01.jpg`?  It's just that `01.jpg.png` feels quite counterintuitive to me without specific notification in the documentation. I actually have to read through the code to find out how to use the masks.
