### ISSUE TITLE
Homography decomposition

### ISSUE THREAD

**Issue by nosleduc** [colmap/colmap#26]
In the article "Deeper understanding of the homography decomposition
for vision-based control", the decomposition of the homography matrix has two possible solutions.

In your code PoseFromHomographyMatrix, you keep only the one that provides you more 3D points that respect cheirality. Are you sure that this solution is always the correct one ?

I've implemented the article and I have a case where when I select the solution with the largest number of points that respect the cheirality, the solution is not the best If I'm considering the  reprojection errors of all points. The other solution is better.

When I have a possible solution, I refine it with a bundle adjustment on the motion and I'm computing the reprojection errors after that I can select the correct one

**Comment by ahojnnes** [comment]
Using the cheirality constraint surely does not guarantee global optimality of the solution. Anyway, when you say that another solution gives a better reprojection error, do you make sure that the points are also infront of the camera?

**Comment by nosleduc** [comment]
Yes after refinement I'm keeping the one that have the lowest reprojection errors and respect the cheirality contraints (at least half points)

**Comment by ahojnnes** [comment]
Is the other solution totally implausible? Did you look at the results in 3D?

**Comment by nosleduc** [comment]
No the other solution is acceptable but have higher reprojection errors. It can be a small amount or a more significant.

**Comment by ahojnnes** [comment]
Is this happening consistently in many cases or just for one specific instance?

**Comment by nosleduc** [comment]
In general the reprojection errors are similar. For some cases one solution has a significant lower reprojection errors

**Comment by ahojnnes** [comment]
Do you propose a better strategy than the cheirality check? How similar are the ratios of points that are infront of the camera in these cases?

**Comment by nosleduc** [comment]
I don't know if it is better. The solution normally consists of using a third view to get the correct one.

I'm computing an estimate of the homography. I consider that this homography can be corrupted by small noises which imply noises in the decomposition.
I'm using the cheirality tests to get the two solutions that see the most points in front of the camera.
 In some cases, like when the two solutions have the same number of points in front of the cameras, you cannot decide which one to take. When all the points are correct there is no reason to choose a particular solution. Same thing when the difference of the number of points in front of the cameras is small
I need a second test to select "the correct solution".
For each solution I'm triangulating the points and make a BA on the motion of the second cameras. I'm retriangulating again the points and make a BA on the motion and on the 3D points.
I'm keeping the solution that gives me the lowest sum of the two rms reprojection errors.

**Comment by ahojnnes** [comment]
Interesting. Thanks for sharing your experience! At the moment, I am happy with the current quality of the results using the cheirality check, since it works pretty reliable for me. I will have to dig into this at some point later and will hence keep the issue open for now.
