### ISSUE TITLE
Building without Qt 

### ISSUE THREAD

**Issue by goetzmoritz** [colmap/colmap#261]
Hi there,

I'm able to build a CPU-only version of colmap on my headless ubuntu 16.04.03 machine following the basic compilation procedure.

This machine does not have a display connected. When I want to start the pipeline I get a core dump:
```
$ /usr/local/bin/feature_extractor --database_path project1/database.db --image_path project1/images
QXcbConnection: Could not connect to display 
*** Aborted at 1514006577 (unix time) try "date -d @1514006577" if you are using GNU date ***
PC: @     0x7ff1aa9f3428 gsignal
*** SIGABRT (@0x3e800004e42) received by PID 20034 (TID 0x7ff1ae7de800) from PID 20034; stack trace: ***
    @     0x7ff1ada8c390 (unknown)
    @     0x7ff1aa9f3428 gsignal
    @     0x7ff1aa9f502a abort
    @     0x7ff1ac7dff81 QMessageLogger::fatal()
    @     0x7ff1a0234cd4 QXcbConnection::QXcbConnection()
    @     0x7ff1a0237bad QXcbIntegration::QXcbIntegration()
    @     0x7ff1ae8103ad (unknown)
    @     0x7ff1acd02d92 QPlatformIntegrationFactory::create()
    @     0x7ff1acd0efc4 QGuiApplicationPrivate::createPlatformIntegration()
    @     0x7ff1acd0fecd QGuiApplicationPrivate::createEventDispatcher()
    @     0x7ff1ac9d77e6 QCoreApplication::init()
    @     0x7ff1ac9d7856 QCoreApplication::QCoreApplication()
    @     0x7ff1acd11cc9 QGuiApplication::QGuiApplication()
    @     0x7ff1ad2c8bcd QApplication::QApplication()
    @           0x537876 main
    @     0x7ff1aa9de830 __libc_start_main
    @           0x53aa69 _start
    @                0x0 (unknown)
Aborted (core dumped)

```

Is there any way to build without Qt? I browsed through the cmake-cfg but was not able to find an according option.

**Comment by ahojnnes** [comment]
I guess you don't have a CUDA-enabled GPU, so you have to set ``--SiftExtraction.use_gpu false`` to make it work. Also checkout the FAQ for more information: https://colmap.github.io/faq.html#available-functionality-without-gpu-cuda

Let me know if this worked for you.

**Comment by ToivonenS4** [comment]
Hello, 
I was wondering too if it was possible to compile COLMAP without qt5. 
I'd need to run colmap mapper routine on a machine without a graphic card. Is Qt5 library necessary for GUI and SiftGPU only? or it's needed also for other functions?  
Thanks in advance

**Comment by ahojnnes** [comment]
There is no GPU needed for Qt. Just compile and use it without a GPU. I am doing that as well.
