### ISSUE TITLE
 Could not find FreeImage

### ISSUE THREAD

**Issue by yonelay11** [colmap/colmap#262]
After building colmap with cmake, they show this error message **CMake Error at cmake/FindFreeImage.cmake:53 (message):
  Could not find FreeImage
Call Stack (most recent call first):
  CMakeLists.txt:68 (find_package)
**
I want to know where can I download or find the FreeImage library.?

**Comment by Supremes** [comment]
hey guys,I met same problem with you.
Do you fix it?
