### ISSUE TITLE
Got stuck during compilation (when linking cuda related lib)

### ISSUE THREAD

**Issue by Master-cai** [colmap/colmap#2624]
**Describe the bug**
I followed the [guidelines](https://colmap.github.io/install.html) to compile colmap from source.
But it stuck one during compilation without any error.
The Dependencies are installed following the guidelines. I do not install Ubuntu’s default CUDA  package, because I have installed a cuda (12.1) and camke can find it. I also trys to install Ubuntu’s default CUDA package as described, but it made the GPU unavailable (incompatibility with my own drivers).

**To Reproduce**

```
apt-get install gcc-10 g++-10
export CC=/usr/bin/gcc-10
export CXX=/usr/bin/g++-10
export CUDAHOSTCXX=/usr/bin/g++-10

git clone https://github.com/colmap/colmap.git
cd colmap
mkdir build
cd build
cmake .. -GNinja -DCMAKE_CUDA_ARCHITECTURES=80
ninja
```
4. Got stuck

**Expected behavior**

**Screenshots**
<img width="1440" alt="image" src="https://github.com/colmap/colmap/assets/37432881/58788307-dc5f-470a-b674-120313405149">

**Environment:**
 - OS: Ubuntu 22.04.3 LTS, A100 gpu, cuda 12.1 or cuda 11.7, Driver Version: 470.161.03
  - COLMAP Version 3.9-dev, 0a1ae653d1b0378f0e0de53942967c637b1f9213

Thanks!

cc @ahojnnes

**Comment by ahojnnes** [comment]
Your screenshot only shows a warning and no error. This is an issue with boost's headers from the default ubuntu packages. You can ignore this warning.
