### ISSUE TITLE
add new camera to existing sparse scene 

### ISSUE THREAD

**Issue by Bin-ze** [colmap/colmap#2627]
I used pixsfm to obtain the camera pose of a new image through Ransac+PnP, and the image is exactly the same size and sensor captured as the reconstructed image. How can I add this image to the original sparse scene?

**Comment by jytime** [comment]
Could you elaborate more about "add this image to the original sparse scene"? Do you mean adding this image to the colmap reconstruction output, e.g., images.bin, cameras.bin, and points3D.bin? If so, you can manually do this by pycolmap, e.g., 

```

import pycolmap
reconstruction = pycolmap.Reconstruction("path/to/reconstruction/dir")
print(reconstruction.summary())

for image_id, image in reconstruction.images.items():
    print(image_id, image)

for point3D_id, point3D in reconstruction.points3D.items():
    print(point3D_id, point3D)

for camera_id, camera in reconstruction.cameras.items():
    print(camera_id, camera)

# add your new image and camera here
# just a template here
pycolmap_intri_radial = np.array(
    [intrinsics[fidx][0, 0], intrinsics[fidx][0, 2], intrinsics[fidx][1, 2], 0]
)
camera = pycolmap.Camera(
    model="SIMPLE_RADIAL",
    width=image_size[0],
    height=image_size[1],
    params=pycolmap_intri_radial,
    camera_id=fidx,
)

reconstruction.add_camera(camera)


reconstruction.write("path/to/reconstruction/dir/")


```

**Comment by Bin-ze** [comment]
Thanks, your reply was very helpful. I can now register new images to the known model. Thanks
