### ISSUE TITLE
Issue in ComputeResolutionProb (mvs)

### ISSUE THREAD

**Issue by an-kumar** [colmap/colmap#264]
Hey,

I noticed in ComputeResolutionProb, the homography H is used to warp the corners of the patch as follows:

float src1[2];
const float ref1[2] = {row - kWindowRadius, col - kWindowRadius};
Mat33DotVec3Homogeneous(H, ref1, src1);

In ref1, you're using row as the first coordinate and col as the second coordinate. I think you mean to use col as the first coordinate and row as the second coordinate. Comparing with, for example, in ComposeHomography:

 // Distance to the plane.
const float dist =
      depth * (normal[0] * (ref_inv_K[0] * col + ref_inv_K[1]) +
               normal[1] * (ref_inv_K[2] * row + ref_inv_K[3]) + normal[2]);
const float inv_dist = 1.0f / dist;

As you can see here col is used as the first coordinate and row as the second. This would also make sense to me intuitively as col would be indexing across the width of the image (typically thought of as 'x') and row across the height of the image ('y'). 

What do you think?

Edit: see also here

float tform[9];
ComposeHomography(src_image_id, row, col, depth, normal, tform);

float col_src = tform[0] * col_start + tform[1] * row_start + tform[2];
float row_src = tform[3] * col_start + tform[4] * row_start + tform[5];

where the homography is used to warp the col/row in the iteration. it's using col as the first coordinate as well.

**Comment by ahojnnes** [comment]
This is a bug, thanks very much for reporting. Fixed it here: https://github.com/colmap/colmap/commit/5181500c53aa52436149f033a3a239ce39c30625

**Comment by an-kumar** [comment]
You're sure the src_area calculation that follows is still accurate?

**Comment by ahojnnes** [comment]
I am relatively sure that it is still correct. Do you think it is not?

**Comment by an-kumar** [comment]
It looks right to me. I don't think the abs is necessary (see https://en.wikipedia.org/wiki/Shoelace_formula; you are using coordinates in counter-clockwise direction. Though i guess it's good to have the abs 'just incase').

**Comment by ahojnnes** [comment]
You are right that the abs is not necessary in theory, but due to limited numerical precision, it can sometimes turn negative. I will keep it therefore. Thanks again for the bug report.
