### ISSUE TITLE
vcpkg build fails on harfbuzz package

### ISSUE THREAD

**Issue by tksharpless** [colmap/colmap#2642]
*Trying to build COLMAP with vckpg on win10 with VS 2017 / cuda 11.3.  Build fails with multiple compile errors on a package called harfbuzz.

**To Reproduce**
Make a fresh install of vcpkg. Set its default triplet to build for x64-windows with VS 141.  
Give it the single command 'vcpkg install colmap[cuda,tests]'.  Wait half a day while all the major dependencies build.
Then it crashes.

**Expected behavior**
A working build of COLMAP

**Observed behavior**
Build fails while trying to install package 'harfbuzz' (yes you read that right -- it's Persian).
The error logs show the cause of the failure is a massive series of compile errors, all apparently traceable to an undefined or improperly defined class.  Looks to me like an order-of-includes problem.

**Comment by ahojnnes** [comment]
Thank you for your kind feedback. Nobody on this project is paid to do their work and volunteers their free time. If you spent a few minutes digging into the problem, you would realize that the software includes a GUI component. This component is built on top of Qt, which has a dependency on typographical components. You can even disable the GUI using the -DGUI_ENABLED cmake option.

**Comment by tksharpless** [comment]
Thank you for your restrained and helpful response.  Where can I find the documentation of the cmake options?
