### ISSUE TITLE
Colmap model_aligner function usage issue

### ISSUE THREAD

**Issue by Zihan265** [colmap/colmap#2647]
**Describe the bug**
So when I try to use model aligner to align the world coordinate, I choose the ref_image_path option, and run following line in cmd:
`colmap model_aligner --input_path .\colmap\building\sparse\0\ --output_path .\colmap\building\sparse\gps --ref_images_path .\gps_info.txt --ref_is_gps 1 --robust_alignment 1 --robust_alignment_max_error 3`

And get error:
```
Converting Alignment Coordinates from GPS (lat/lon/alt) to ECEF.

Aligning reconstruction to custom
---------------------------------
 => Using 101 reference images
F20240712 17:10:32.108531 23268 math.h:213] Check failed: !elems.empty()
*** Check failure stack trace: ***
    @   00007FFADCF66E5B  public: void __cdecl google::LogMessage::Flush(void) __ptr64
    @   00007FFADCF65739  public: __cdecl google::LogMessageFatal::~LogMessageFatal(void) __ptr64
    @   00007FF63648466E  (unknown)
    @   00007FF6364938B0  (unknown)
    @   00007FF6364665E6  (unknown)
    @   00007FF636467DEB  (unknown)
    @   00007FF636A543B4  (unknown)
    @   00007FFAEDBB7344  BaseThreadInitThunk
    @   00007FFAEE83CC91  RtlUserThreadStart
```
My gps_info.txt file containing following information as instruction in [https://colmap.github.io/faq.html#geo-registratio](https://colmap.github.io/faq.html#geo-registration) and mentioned in #1628 
```
D:/3DGS/colmap/building_data\DJI_20240428173001_0670_D.JPG 30.408996277777778 104.07706152777777 682.426
D:/3DGS/colmap/building_data\DJI_20240428173004_0671_D.JPG 30.408996388888887 104.07706141666667 682.426
D:/3DGS/colmap/building_data\DJI_20240428173017_0672_D.JPG 30.40898972222222 104.07710294444443 682.426
D:/3DGS/colmap/building_data\DJI_20240428173025_0673_D.JPG 30.408984 104.07712752777778 682.426
D:/3DGS/colmap/building_data\DJI_20240428173036_0674_D.JPG 30.408855416666665 104.07713027777777 682.426
D:/3DGS/colmap/building_data\DJI_20240428173046_0675_D.JPG 30.40886722222222 104.07712766666667 682.426
D:/3DGS/colmap/building_data\DJI_20240428173110_0676_D.JPG 30.40894622222222 104.07741269444445 682.226
D:/3DGS/colmap/building_data\DJI_20240428173115_0677_D.JPG 30.40894022222222 104.07745377777778 682.226
................................................
```
I've searched around and found no instruction for this problem. Could anyone provide some advice related to this issue?

**Environment:**
 - OS: Windows10
 - COLMAP Version 3.9

**Comment by ferreram** [comment]
I think your issue is related to the image "names" in your gps_info.txt file.  The  name of your images should match the name appearing in the database file or in the images.txt file.   As the name is given relative to the image_path that you specified when running the features extraction step, the images' name is usually simply the image file name (DJI_20240XXX_D.JPG in your case).

**Comment by Zihan265** [comment]
Thanks so much. Changing the directory to the filename only solve this issue.
