### ISSUE TITLE
Scale of reconstruction / mvs

### ISSUE THREAD

**Issue by an-kumar** [colmap/colmap#265]
In the MVS part of colmap, the max depth is set to 1.0 by default. I was wondering how this interacts with the scale ambiguity in the reconstruction step. Does colmap somewhere normalize the scale of the reconstruction so that a max depth of 1.0 is reasonable? Otherwise, how is this max depth found?

**Comment by ahojnnes** [comment]
This is just a default value when constructing the object and is overwritten when loading the sparse model. The depth range is computed from the sparse point cloud, see ``src/mvs/model.h``.
