### ISSUE TITLE
How to install latest pycolmap?

### ISSUE THREAD

**Issue by InnovArul** [colmap/colmap#2650]
I have been experimenting wth pycolmap and was looking into one of `pyceres`' tutorial.
https://github.com/cvg/pyceres/blob/main/examples/test_BA.ipynb

```
def define_problem(rec):
     .......
    for im in rec.images.values():
        cam = rec.cameras[im.camera_id]
        for p in im.points2D:
            cost = pycolmap.cost_functions.ReprojErrorCost(
                cam.model, im.cam_from_world, p.xy
            )
     ......

```

There is a point where a Ceres problem is defined. A re-projection cost (via `pycolmap.cost_functions.ReprojErrorCost`) is added for every image.  However I get an error as `AttributeError: module pycolmap has no attribute 'cost_functions'`.
Could someone please let me know whats wrong here?

I installed both colmap and pycolmap from conda.
```
conda install colmap
conda install pycolmap
```
```
>>> pycolmap.__version__
0.6.1

>>> pycolmap.COLMAP_version
COLMAP 3.9.1
```

In my coarse analysis, `pycolmap.cost_functions` seem to have been added 5 months ago?
https://github.com/colmap/colmap/blame/main/src/pycolmap/estimators/cost_functions.cc
However it seems `pycolmap 0.6.1` was released earlier than that. Could you please let me know if a new version of pycolmap will be released anytime soon?

As I am in RedHat Linux, compiling colmap doesn't seem to be as straightforward as in ubuntu:(

**Comment by jytime** [comment]
i think the tutorial was designed for pycolmap 0.4.x. you may need to downgrade pycolmap

**Comment by InnovArul** [comment]
Thanks for taking the time to reply.
As I have seen so far, it looks like `pyceres`, `pycolmap` are in a transition phase. 

I am mainly interested in cost functions such as `ReprojErrorCost()`, `RigReprojErrorCost()`.
They were moved from `pyceres` into `pycolmap` in the PR:
https://github.com/cvg/pyceres/commit/c0028b41b13eb2b3adac4b1f06dbe035b1a0915b

The released versions of `pyceres` (2.0, 2.1, 2.2) already contain this update. 
However, I did not see the recent versions of `pycolmap` containing the moved cost functions. 
So cost functions  `ReprojErrorCost()`, `RigReprojErrorCost()` do not exist in any Python pypi packages.
Please let me know if I misunderstood something here.

**Comment by tom-bola** [comment]
You can download current wheels from here: https://github.com/colmap/colmap/actions/runs/9945395526. Though, I'd also be interested when a new release will be published to pypi.

**Comment by ahojnnes** [comment]
The goal is to male a new release but we wanted it to be automated from CI for thr windows binaries. It will take a little more to get that done.

**Comment by InnovArul** [comment]
Thank you @ahojnnes, @tom-bola.
I got it working by building from source as well.

**Comment by Chim-SO** [comment]
Hi @InnovArul ,
I encountered the same problem and solved it by building from source as you suggested. However, I'm now facing another error:

```
    cost = pycolmap.cost_functions.ReprojErrorCost(
TypeError: Unable to convert function return value to a Python type! The signature was
        (camera_model_id: pycolmap.CameraModelId, point2D: numpy.ndarray[numpy.float64[2, 1]]) -> ceres::CostFunction
```

Have you faced him as well? Do you have any idea how to fix this?

Thanks in advance!

**Comment by InnovArul** [comment]
Hi, could you try using `pycolmap.ListPoint2D` instead of numpy array?
Basically make a list of (x,y) and then wrap with `pycolmap.ListPoint2D(list_xy)`?

**Comment by InnovArul** [comment]
I built both COLMAP and pycolmap from source. 
Colmap has same version as yours. Pycolmap version returns empty string (installed one week ago,  not sure if there are new developments regarding version number)

**Comment by Chim-SO** [comment]
Thank you!
It's working now! I just built them from source: COLMAP, pyColmap and pyceres. I also installed glog [(0.7.0)](https://github.com/google/glog/releases/tag/v0.7.0) and made sure to install it before Colmap to avoid the v_flag problem:

```
>>> import pycolmap
>>> pycolmap.__version__
'3.10'
>>> import pyceres
>>> pyceres.__version__
'2.2'
```
