### ISSUE TITLE
Add some stubs for pycolmap

### ISSUE THREAD

**Issue by Parskatt** [colmap/colmap#2664]
**Is your feature request related to a problem? Please describe.**
Python language servers / Intellisense / Whatever you want to call it, are not able to read from the .so python module, hence they cannot provide hints/autocompletes. This means you either have to call something like help(...) or look manually in the binding code for what is available.

**Describe the solution you'd like**
The standard solution is to provide python stub files (.pyi) that describe the interface in pseudo python code. As far as I'm aware this needs to be done manually. Basically, go through the source code for the python module and translate it to an interface. Actually someone should probably have figured out to automate this translation.

I could do this as a PR if it sounds ok. Otherwise I'll probably just do it on a fork so I don't have to look up the api constantly...

**Comment by ahojnnes** [comment]
Thanks for the suggestion, it makes sense to me. I think we should automate this, otherwise it'll be hard to keep in sync with the real interface. I'll defer to @sarlinpe @mihaidusmanu @B1ueber2y.

**Comment by Parskatt** [comment]
This tool: https://github.com/sizmailov/pybind11-stubgen seems to exist, can't say what the quality would be, but worth a try.

**Comment by sarlinpe** [comment]
The solution is here: https://github.com/colmap/pycolmap/issues/263 I will try integrate this in the CI when I find the time.

**Comment by Parskatt** [comment]
My bad for not checking prev issues :) Funny that its basically the same solution as here.

**Comment by sarlinpe** [comment]
@Parskatt Stubs are available for the latest wheels (obtained [here](https://github.com/colmap/colmap/actions/runs/10513821383)) and, when building from source, after running
```bash
python -m pip install back isort git+https://github.com/sarlinpe/pybind11-stubgen@sarlinpe/fix-2024-08
./pycolmap/generate_stubs.sh $(which python) $(python3 -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')
```
They can be tested by running `python -m mypy --package pycolmap --implicit-optional`. Please let us know if they work as expected. Thanks!

**Comment by Parskatt** [comment]
@sarlinpe awesome, thanks!
