### ISSUE TITLE
[SOLVED} Misaligned Camera Positions and Orientations in COLMAP from custom data.

### ISSUE THREAD

**Issue by MotivaCG** [colmap/colmap#2689]
I am encountering an issue with camera positioning and orientation in COLMAP when importing a model using my custom images.txt and cameras.txt files. 

**Environment:**

COLMAP Version: 3.8
Operating System: Win11

**Steps to Reproduce:**

Create images.txt and cameras.txt files, ensuring they adhere to COLMAP's required format.
Open COLMAP and import model using the provided files.
Observe the misalignment of camera positions and orientations as displayed in COLMAP.
Compare these positions to the expected layout in Blender.

**Expected Behavior:**

The cameras should align and orient correctly according to the parameters defined in images.txt and cameras.txt, consistent with their display in Blender.

**Actual Behavior:**

The camera positions and orientations in COLMAP are incorrect and appear misaligned, as shown in the screenshots.

Colmap:
![Screenshot1](https://github.com/user-attachments/assets/8e7f9f24-81d7-46a7-bb3d-8b024e79efc1)
![Screenshot2](https://github.com/user-attachments/assets/15e490a6-09e4-4892-a8f9-12fa6213bdf3)

Blender:
![blender](https://github.com/user-attachments/assets/0ea78587-25cd-42c4-8ff7-f7668faa2283)

Sample cameras.txt and images.txt attached:
[cameras.txt](https://github.com/user-attachments/files/16520980/cameras.txt)
[images.txt](https://github.com/user-attachments/files/16520981/images.txt)

My intention is to use these cameras in COLMAP to perform fine-tuning calibration and generate a .ply file that can be processed with Gaussian Splatting. Accurate camera alignment is crucial for this.

Regards and thank you in advance!

**Comment by MotivaCG** [comment]
Update, that's weird it seems that it is related to the quaternion, using identity as quaternion the positions seem to be ok.

**Comment by jaco001** [comment]
So you're only missing the "normals"/rotation for the cameras. (or they're locked in one position). Check your data if they have it.

Eg. my colmap cameras.json have that at start
{"id": 0, "img_name": "IMG_20240610_124401", "width": 3195, "height": 2383, "position": [0.14858144674278212, 0.155904636507719, -2.4796169513517317], "rotation": [[-0.9888047755723136, -0.12673685638035936, 0.07875839663306206], [0.1254693245218796, -0.9918781843260388, -0.020859435805022957], [0.08076239477262813, -0.010744146913774231, 0.996675473209653]], "fy": 2687.400336059742, "fx": 2685.509081075047}

**Comment by MotivaCG** [comment]
**For future readers** the order applied in Colmap is counter-intuitive, usually you apply the position and the rotation after that, in colmap things are rotated and translated locally after that.

**Comment by MotivaCG** [comment]
Done

**Comment by MotivaCG** [comment]
For future readers the order applied in Colmap is counter-intuitive, usually you apply the position and the rotation after that, in colmap things are rotated and translated locally after that.
