### ISSUE TITLE
Consistency Graphs Empty

### ISSUE THREAD

**Issue by willjhliang** [colmap/colmap#2694]
**Describe the bug**
After running automatic reconstruction, my consistency graphs directory is empty.

**To Reproduce**
1. Run `Reconstruction > Automatic Reconstruction` with shared intrinsics and video frames.
2. See error

**Expected behavior**
`stereo/consistency_graphs` should contain data as specified in [the documentation](https://github.com/colmap/colmap/issues).

I am trying to associate dense points with the pixels from the original images (ie to highlight pixels that are in the point cloud or to change a pixel color and have it changed in the point cloud). Thank you!

**Screenshots**
<img width="616" alt="image" src="https://github.com/user-attachments/assets/1b438e62-b5d1-472e-afeb-9a21afc229c9">

**Environment:**
 - OS: Ubuntu 20.04 (with CUDA)
 - COLMAP Version: 3.10
 - Capture Device: iPhone video

**Comment by ahojnnes** [comment]
The consistency graph is not written out by default and cannot be activated using the automatic reconstructor. Please perform the patch_match_stereo step manually and enable the respective option. This is because the consistency graphs are rather huge.
