### ISSUE TITLE
Bilateral NCC weights (mvs)

### ISSUE THREAD

**Issue by an-kumar** [colmap/colmap#270]
The bilateral weights computed in the code are different than what is written in the paper -- in the paper, the weights computed use the squared spatial distance (and squared color distance), whereas in the code the spatial distance and color distance is not squared. Is this intended?

**Comment by ahojnnes** [comment]
This was a bug in the code that did not have too much influence in practice though. Thanks for the bug report. It is fixed now in the dev branch.
