### ISSUE TITLE
Why does COLMAP set the Ceres solver tolerance value to 0 in the bundle adjustment option?

### ISSUE THREAD

**Issue by juu-k** [colmap/colmap#2703]
Hello, I was looking at the COLMAP options and noticed that the function_tolerance, gradient_tolerance, and parameter_tolerance values for the Ceres solver used in the Bundle Adjustment step are all set to zero.

![image](https://github.com/user-attachments/assets/de62e0ac-1a9d-4d8a-82d4-a8da2542e1d2)

However, the initial values in the link below have a very small value close to 0 (ex. 1e-6, 1e-10). Why is COLMAP set to 0?

http://ceres-solver.org/nnls_solving.html#_CPPv4N5ceres6Solver7Options18function_toleranceE

**Comment by sarlinpe** [comment]
The gradient and parameter tolerances are overridden for the local and global BA: 
https://github.com/colmap/colmap/blob/6247ca0673b28554cd10b89cbac4dfe0b9ec9837/src/colmap/controllers/incremental_mapper.cc#L104-L105
https://github.com/colmap/colmap/blob/6247ca0673b28554cd10b89cbac4dfe0b9ec9837/src/colmap/controllers/incremental_mapper.cc#L129-L130
Function tolerances are indeed set to zero:
https://github.com/colmap/colmap/blob/6247ca0673b28554cd10b89cbac4dfe0b9ec9837/src/colmap/controllers/incremental_mapper.h#L94
https://github.com/colmap/colmap/blob/6247ca0673b28554cd10b89cbac4dfe0b9ec9837/src/colmap/controllers/incremental_mapper.h#L106

@ahojnnes  I think that we really need a more extensive suite of benchmarks to tune these parameters and make sure that increasing their values reduces the time and doesn't degrade the performance. I suspect that the parameter tolerance could help most.

**Comment by ahojnnes** [comment]
@sarlinpe Agreed that we need such a benchmark. These have all been tuned in a rather empirical manner many years ago, but meanwhile many of the underlying algorithms and implementations have also changed quite drastically. It will be good to revisit these.
