### ISSUE TITLE
Camera / point selection in GUI

### ISSUE THREAD

**Issue by mgprt** [colmap/colmap#272]
On dev branch:
When I try to select a camera or point in the GUI by clicking on it, always the same camera or nothing is selected.
It seems that when the object index is computed from the unique color, it is either 0 or larger than the selection buffer size.
This is introduced in feeab876b53c70998201d6056d9410086de677c5.

**Comment by ahojnnes** [comment]
Thanks for the report. I actually only tested the new implementation on Windows and Mac. Do you have any scaling of the UI enabled in the window manager? You are using GNOME?

**Comment by ahojnnes** [comment]
Which distribution and Qt version are you using?

**Comment by ahojnnes** [comment]
Actually, I just tested on Ubuntu 16.04 with default packages and it works fine on my system...

**Comment by mgprt** [comment]
Thanks for your help. I don't have access to my computer right now, but I will check the exact settings and package versions tomorrow.

**Comment by mgprt** [comment]
I'm using Ubuntu 16.04 with the Unity desktop and Qt 5.5.1 (should be the default).
I'm not aware of any UI scaling and `devicePixelRatio()` returns 1.
For the sake of completeness, although I don''t know if this could have an impact: I ran into some issues today when updating my (NVIDIA) graphics driver to 387.26, so I had to roll back to 384.111.

I could narrow the problem down to `image.pixel(x,y)` returning bad values, but I could not check the internals when debugging. I also don't known how to check if the colors are actually drawn correctly.

**Comment by ahojnnes** [comment]
But the scene is visualized correctly in the viewer otherwise? Just the selection doesn’t work?

**Comment by mgprt** [comment]
Yes, everything else looks fine. I could also verify that there are actually different colors assigned for the selection by not resetting the object colors afterwards.
Right now it looks to me like a problem with Qt, so if I am the only one experiencing this issue I can just use an earlier commit for now.

**Comment by ahojnnes** [comment]
Can you check that Extras/Grab Image produces the correct image? Thanks.

**Comment by mgprt** [comment]
Interestingly, the image is completely broken as well. I didn't check that before.

![colmap_grab](https://user-images.githubusercontent.com/8897542/34955281-0205bcd4-fa24-11e7-993b-1179792aab66.png)

**Comment by mgprt** [comment]
Unfortunately that does not help, the result is still the same. (Sometimes more, sometimes less artefacts in the black image, but I guess thats just reading uninitialized memory.)

**Comment by mgprt** [comment]
Still no change. I will try to upgrade to a newer Qt version tomorrow and see if that helps.

**Comment by ahojnnes** [comment]
Is this on your favorite Alienware machine? :-)

**Comment by mgprt** [comment]
It is. Just one more thing to love about it. ;)

**Comment by ahojnnes** [comment]
@mgprt It should work now if you pull the latest changes from the dev branch. Let me know. Thanks!

**Comment by mgprt** [comment]
Yes, it is fixed now. Thanks a lot for your help!
