### ISSUE TITLE
New directory structure issue.

### ISSUE THREAD

**Issue by bartoszek** [colmap/colmap#273]
New directory structure is somewhat strange a6e809f74f4a020125e5be88ed02559752c697b0 5841a33f0dd1d6968adb66b62dde574a4d947c74.
Normally you won't put binarie in the mix with libraries.
Most distros packaging software will complain about this :/

**Comment by ahojnnes** [comment]
Thanks for the feedback and I agree that it is not nice. I am currently working on a single unified binary that combines all functionality of COLMAP. It should be commuted over the next days. Thanks.

**Comment by ahojnnes** [comment]
@bartoszek I just pushed the latest changes that combine all COLMAP functionality into a single binary. You can now just run ``colmap feature_extractor`` or ``colmap gui``. Let me know what you think. Thanks for the feedback.
