### ISSUE TITLE
pycolmap build from source failed with new stub changes

### ISSUE THREAD

**Issue by B1ueber2y** [colmap/colmap#2736]
Ubuntu 20.04.6 LTS
pycolmap build from source does not work for me since https://github.com/colmap/colmap/commit/5c51ead1454a3b78f26c239316131c931a01e0d9 (https://github.com/colmap/colmap/pull/2721)

Not sure why this was not caught by CI. @sarlinpe 

[LOG]
 -- Build files have been written to: /tmp/tmptqly5k9v/build
  *** Building project with Ninja...
  [1/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/bindings.cc.o
  [2/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/pipeline/bindings.cc.o
  [3/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/manifold.cc.o
  [4/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/geometry/homography_matrix.cc.o
  [5/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/homography_matrix.cc.o
  [6/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/optim/bindings.cc.o
  [7/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/main.cc.o
  [8/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/fundamental_matrix.cc.o
  [9/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/alignment.cc.o
  [10/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/essential_matrix.cc.o
  [11/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/generalized_absolute_pose.cc.o
  [12/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/covariance.cc.o
  [13/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/two_view_geometry.cc.o
  [14/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/triangulation.cc.o
  [15/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/feature/sift.cc.o
  [16/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/absolute_pose.cc.o
  [17/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/bundle_adjustment.cc.o
  [18/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/pipeline/meshing.cc.o
  [19/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/scene/bindings.cc.o
  [20/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/pipeline/extract_features.cc.o
  [21/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/geometry/bindings.cc.o
  [22/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/sfm/bindings.cc.o
  [23/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/scene/correspondence_graph.cc.o
  [24/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/pipeline/sfm.cc.o
  [25/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/scene/database_cache.cc.o
  [26/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/pipeline/images.cc.o
  [27/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/scene/database.cc.o
  [28/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/pipeline/mvs.cc.o
  [29/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/scene/reconstruction_manager.cc.o
  [30/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/scene/track.cc.o
  [31/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/scene/camera.cc.o
  [32/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/pipeline/match_features.cc.o
  [33/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/scene/point2D.cc.o
  [34/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/scene/image.cc.o
  [35/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/scene/reconstruction.cc.o
  [36/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/scene/point3D.cc.o
  [37/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/scene/two_view_geometry.cc.o
  [38/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/sfm/incremental_triangulator.cc.o
  [39/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/sfm/observation_manager.cc.o
  [40/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/sfm/incremental_mapper.cc.o
  [41/42] Building CXX object CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/cost_functions.cc.o
  [42/42] Linking CXX shared module pycolmap.cpython-39-x86_64-linux-gnu.so
  FAILED: pycolmap.cpython-39-x86_64-linux-gnu.so
  : && /usr/bin/g++  -pthread -B /home/shaoliu/anaconda3/envs/colmap/compiler_compat -fPIC -O3 -DNDEBUG  -flto -shared  -o pycolmap.cpython-39-x86_64-linux-gnu.so CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/absolute_pose.cc.o CMakeFile
s/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/alignment.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/bindings.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/bundle_adjust
ment.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/cost_functions.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/covariance.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolma
p/estimators/essential_matrix.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/fundamental_matrix.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/generalized_absolute_pose.cc.o CMakeFiles/pycolmap.di
r/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/homography_matrix.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/manifold.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/triangulation.cc.o
 CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/estimators/two_view_geometry.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/feature/sift.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/geometry/bind
ings.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/geometry/homography_matrix.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/main.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/optim/bindings
.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/pipeline/bindings.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/pipeline/extract_features.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/pipeli
ne/images.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/pipeline/match_features.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/pipeline/meshing.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/
pipeline/mvs.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/pipeline/sfm.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/scene/bindings.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/scene/came
ra.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/scene/correspondence_graph.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/scene/database.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/scene/
database_cache.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/scene/image.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/scene/point2D.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/scene/poin
t3D.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/scene/reconstruction.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/scene/reconstruction_manager.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolm
ap/scene/track.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/scene/two_view_geometry.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/sfm/bindings.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap
/sfm/incremental_mapper.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/sfm/incremental_triangulator.cc.o CMakeFiles/pycolmap.dir/home/shaoliu/myProjects/colmap/src/pycolmap/sfm/observation_manager.cc.o -L/usr/local/cuda-11.3/targets/x86_64-linu
x/lib/stubs   -L/usr/local/cuda-11.3/targets/x86_64-linux/lib -Wl,-rpath,/usr/lib/x86_64-linux-gnu/blas:/usr/lib/x86_64-linux-gnu/lapack:/usr/local/cuda-11.3/lib64:/usr/local/lib:  /usr/local/lib/libceres.a  /usr/local/lib/libcolmap_exe.a  /usr/local/lib/libcolmap_ui.a
 /usr/local/lib/libcolmap_controllers.a  /usr/local/lib/libcolmap_feature.a  /usr/local/lib/libcolmap_retrieval.a  /usr/lib/x86_64-linux-gnu/libflann.so  /usr/lib/x86_64-linux-gnu/liblz4.so  /usr/local/lib/libcolmap_sfm.a  /usr/local/lib/libcolmap_estimators.a  /usr/loc
al/lib/libcolmap_optim.a  /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.71.0  /usr/local/lib/libcolmap_mvs_cuda.a  /usr/local/lib/libcolmap_mvs.a  /usr/local/lib/libcolmap_image.a  /usr/local/lib/libcolmap_lsd.a  /usr/local/lib/libcolmap_scene.a  /usr/local/li
b/libcolmap_feature_types.a  /usr/local/lib/libcolmap_geometry.a  /usr/local/lib/libcolmap_math.a  /usr/lib/x86_64-linux-gnu/libmetis.so  /usr/lib/x86_64-linux-gnu/libboost_graph.so.1.71.0  /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.71.0  /usr/local/lib/libcolmap_sen
sor.a  /usr/local/lib/libceres.a  /usr/lib/x86_64-linux-gnu/libspqr.so  /usr/lib/x86_64-linux-gnu/libcholmod.so  /usr/lib/x86_64-linux-gnu/libmetis.so  /usr/lib/x86_64-linux-gnu/libamd.so  /usr/lib/x86_64-linux-gnu/libcamd.so  /usr/lib/x86_64-linux-gnu/libccolamd.so  /u
sr/lib/x86_64-linux-gnu/libcolamd.so  /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so  -lrt  /usr/lib/x86_64-linux-gnu/blas/libblas.so  /usr/lib/x86_64-linux-gnu/lapack/liblapack.so  /usr/lib/x86_64-linux-gnu/libtbb.so.2  /usr/lib/x86_64-linux-gnu/libcxsparse.so  /usr
/local/cuda-11.3/lib64/libcudart_static.a  -ldl  /usr/lib/x86_64-linux-gnu/librt.so  /usr/local/cuda-11.3/lib64/libcublas.so  /usr/local/cuda-11.3/lib64/libcusolver.so  /usr/local/cuda-11.3/lib64/libcusparse.so  /usr/lib/x86_64-linux-gnu/libopenblas.so  -lm  -ldl  /usr/
local/lib/libcolmap_vlfeat.a  /usr/lib/x86_64-linux-gnu/libfreeimage.so  /usr/local/lib/libcolmap_poisson_recon.a  /usr/lib/gcc/x86_64-linux-gnu/9/libgomp.so  /usr/lib/x86_64-linux-gnu/libmpfr.so  /usr/lib/x86_64-linux-gnu/libgmp.so  /usr/local/lib/libcolmap_util_cuda.a
  /usr/local/lib/libcolmap_util.a  /usr/local/lib/libglog.so.0.6.0  /usr/lib/x86_64-linux-gnu/libgflags.so.2.2.2  -lpthread  /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.71.0  /usr/lib/x86_64-linux-gnu/libsqlite3.so  /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5.12.
8  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.12.8  /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.12.8  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.12.8  /usr/local/lib/libcolmap_sift_gpu.a  /usr/lib/x86_64-linux-gnu/libGLX.so  /usr/lib/x86_64-linux-gnu/libOpenGL.so  /usr/lo
cal/cuda-11.3/lib64/libcudart.so  /usr/local/cuda-11.3/lib64/libcurand.so  /usr/lib/x86_64-linux-gnu/libGLEW.so  -lcudadevrt  -lcudart_static  -lrt  -ldl && cd /tmp/tmptqly5k9v/build && /usr/bin/strip /tmp/tmptqly5k9v/build/pycolmap.cpython-39-x86_64-linux-gnu.so && cd
/tmp/tmptqly5k9v/build && /home/shaoliu/install/cmake-3.24.2/bin/cmake -E env PYTHONPATH=/tmp/tmptqly5k9v/build:/tmp/pip-build-env-nbtpn8ug/site bash /home/shaoliu/myProjects/colmap/pycolmap/generate_stubs.sh /home/shaoliu/anaconda3/envs/colmap/bin/python /tmp/tmptqly5k
9v/build
  /home/shaoliu/myProjects/colmap/pycolmap/../src/pycolmap/pybind11_extension.h:30:8: warning: type ‘struct type_caster’ violates the C++ One Definition Rule [-Wodr]
     30 | struct type_caster<std::string> {
        |        ^
  /tmp/pip-build-env-nbtpn8ug/overlay/lib/python3.9/site-packages/pybind11/include/pybind11/cast.h:517:8: note: a type with different bases is defined in another translation unit
    517 | struct type_caster<std::basic_string<CharT, Traits, Allocator>,
        |        ^
  /home/shaoliu/myProjects/colmap/pycolmap/../src/pycolmap/pybind11_extension.h:30:8: note: type ‘struct type_caster’ itself violates the C++ One Definition Rule
     30 | struct type_caster<std::string> {
        |        ^
  /tmp/pip-build-env-nbtpn8ug/overlay/lib/python3.9/site-packages/pybind11/include/pybind11/cast.h:517:8: note: the incompatible type is defined here
    517 | struct type_caster<std::basic_string<CharT, Traits, Allocator>,
        |        ^
  /usr/include/c++/9/tuple:893:11: note: type ‘struct tuple’ itself violates the C++ One Definition Rule
    893 |     class tuple<_T1, _T2> : public _Tuple_impl<0, _T1, _T2>
        |           ^
  Building stubs with /home/shaoliu/anaconda3/envs/colmap/bin/python to /tmp/tmptqly5k9v/build
  pybind11_stubgen - [  ERROR] In pycolmap.BundleAdjuster.__init__ : Invalid expression 'colmap::BundleAdjustmentOptions'
  pybind11_stubgen - [  ERROR] In pycolmap.BundleAdjuster.options. : Invalid expression 'colmap::BundleAdjustmentOptions'
  pybind11_stubgen - [  ERROR] In pycolmap.CopyType : Invalid identifier 'hard-link' at 'pycolmap.CopyType'
  pybind11_stubgen - [  ERROR] In pycolmap.CopyType : Invalid identifier 'soft-link' at 'pycolmap.CopyType'
  pybind11_stubgen - [  ERROR] In pycolmap.Database.read_two_view_geometries : Invalid expression 'colmap::TwoViewGeometry'
  pybind11_stubgen - [  ERROR] In pycolmap.Database.read_two_view_geometry : Invalid expression 'colmap::TwoViewGeometry'
  pybind11_stubgen - [  ERROR] In pycolmap.Database.write_two_view_geometry : Invalid expression 'colmap::TwoViewGeometry'
  pybind11_stubgen - [  ERROR] In pycolmap.ImportedPairGenerator.__init__ : Invalid expression 'colmap::ImagePairsMatchingOptions'
  pybind11_stubgen - [  ERROR] In pycolmap.IncrementalMapper.adjust_global_bundle : Invalid expression 'colmap::BundleAdjustmentOptions'
  pybind11_stubgen - [  ERROR] In pycolmap.IncrementalMapper.adjust_local_bundle : Invalid expression 'colmap::BundleAdjustmentOptions'
  pybind11_stubgen - [  ERROR] In pycolmap.IncrementalMapper.iterative_global_refinement : Invalid expression 'colmap::BundleAdjustmentOptions'
  pybind11_stubgen - [  ERROR] In pycolmap.IncrementalMapper.iterative_local_refinement : Invalid expression 'colmap::BundleAdjustmentOptions'
  pybind11_stubgen - [  ERROR] In pycolmap.IncrementalMapperController.__init__ : Invalid expression 'colmap::IncrementalMapperOptions'
  pybind11_stubgen - [  ERROR] In pycolmap.IncrementalMapperController.initialize_reconstruction : Invalid expression 'colmap::IncrementalMapper'
  pybind11_stubgen - [  ERROR] In pycolmap.IncrementalMapperController.initialize_reconstruction : Invalid expression 'colmap::IncrementalMapper::Options'
  pybind11_stubgen - [  ERROR] In pycolmap.IncrementalMapperController.options. : Invalid expression 'colmap::IncrementalMapperOptions'
  pybind11_stubgen - [  ERROR] In pycolmap.IncrementalMapperController.reconstruct : Invalid expression 'colmap::IncrementalMapper::Options'
  pybind11_stubgen - [  ERROR] In pycolmap.IncrementalMapperController.reconstruct_sub_model : Invalid expression 'colmap::IncrementalMapper'
  pybind11_stubgen - [  ERROR] In pycolmap.IncrementalMapperController.reconstruct_sub_model : Invalid expression 'colmap::IncrementalMapper::Options'
  pybind11_stubgen - [  ERROR] In pycolmap.IncrementalMapperOptions.image_selection_method. : Invalid expression 'colmap::IncrementalMapper::Options::ImageSelectionMethod'
  pybind11_stubgen - [  ERROR] In pycolmap.IncrementalMapperOptions.image_selection_method. : Invalid expression 'colmap::IncrementalMapper::Options::ImageSelectionMethod'
  pybind11_stubgen - [  ERROR] In pycolmap.IncrementalPipelineOptions.get_global_bundle_adjustment : Invalid expression 'colmap::BundleAdjustmentOptions'
  pybind11_stubgen - [  ERROR] In pycolmap.IncrementalPipelineOptions.get_local_bundle_adjustment : Invalid expression 'colmap::BundleAdjustmentOptions'
  pybind11_stubgen - [  ERROR] In pycolmap.SequentialMatchingOptions.vocab_tree_options : Invalid expression 'colmap::VocabTreeMatchingOptions'
  pybind11_stubgen - [  ERROR] In pycolmap.Sift.__init__ : Invalid expression 'colmap::SiftExtractionOptions'
  pybind11_stubgen - [  ERROR] In pycolmap.Sift.options. : Invalid expression 'colmap::SiftExtractionOptions'
  pybind11_stubgen - [  ERROR] In pycolmap.absolute_pose_estimation : Invalid expression '<pycolmap.AbsolutePoseEstimationOptions object at 0x7f43b3d712f0>'
  pybind11_stubgen - [  ERROR] In pycolmap.absolute_pose_estimation : Invalid expression '<pycolmap.AbsolutePoseRefinementOptions object at 0x7f442d6b09f0>'
  pybind11_stubgen - [  ERROR] In pycolmap.bundle_adjustment : Invalid expression '<pycolmap.BundleAdjustmentOptions object at 0x7f43b389b8b0>'
  pybind11_stubgen - [  ERROR] In pycolmap.dense_delaunay_meshing : Invalid expression '<pycolmap.DelaunayMeshingOptions object at 0x7f43b38b7fb0>'
  pybind11_stubgen - [  ERROR] In pycolmap.essential_matrix_estimation : Invalid expression '<pycolmap.RANSACOptions object at 0x7f43b3d94cf0>'
  pybind11_stubgen - [  ERROR] In pycolmap.estimate_calibrated_two_view_geometry : Invalid expression '<pycolmap.TwoViewGeometryOptions object at 0x7f43b3d93570>'
  pybind11_stubgen - [  ERROR] In pycolmap.estimate_triangulation : Invalid expression '<pycolmap.EstimateTriangulationOptions object at 0x7f43b3d810f0>'
  pybind11_stubgen - [  ERROR] In pycolmap.estimate_two_view_geometry : Invalid expression '<pycolmap.TwoViewGeometryOptions object at 0x7f43b3d81fb0>'
  pybind11_stubgen - [  ERROR] In pycolmap.extract_features : Invalid expression '<pycolmap.ImageReaderOptions object at 0x7f43b385ba70>'
  pybind11_stubgen - [  ERROR] In pycolmap.extract_features : Invalid expression '<pycolmap.SiftExtractionOptions object at 0x7f43b385b9b0>'
  pybind11_stubgen - [  ERROR] In pycolmap.fundamental_matrix_estimation : Invalid expression '<pycolmap.RANSACOptions object at 0x7f43b3d9fef0>'
  pybind11_stubgen - [  ERROR] In pycolmap.homography_matrix_estimation : Invalid expression '<pycolmap.RANSACOptions object at 0x7f43b3d9ff70>'
  pybind11_stubgen - [  ERROR] In pycolmap.import_images : Invalid expression '<pycolmap.ImageReaderOptions object at 0x7f43b3892430>'
  pybind11_stubgen - [  ERROR] In pycolmap.incremental_mapping : Invalid expression '<pycolmap.IncrementalPipelineOptions object at 0x7f43b3d9fcb0>'
  pybind11_stubgen - [  ERROR] In pycolmap.infer_camera_from_image : Invalid expression '<pycolmap.ImageReaderOptions object at 0x7f43b3858bf0>'
  pybind11_stubgen - [  ERROR] In pycolmap.logging.set_log_destination : Invalid expression 'Logging::LogSeverity'
  pybind11_stubgen - [  ERROR] In pycolmap.match_exhaustive : Invalid expression '<pycolmap.SiftMatchingOptions object at 0x7f43b3865970>'
  pybind11_stubgen - [  ERROR] In pycolmap.match_exhaustive : Invalid expression '<pycolmap.ExhaustiveMatchingOptions object at 0x7f43b3865930>'
  pybind11_stubgen - [  ERROR] In pycolmap.match_exhaustive : Invalid expression '<pycolmap.TwoViewGeometryOptions object at 0x7f43b3d84630>'
  pybind11_stubgen - [  ERROR] In pycolmap.match_sequential : Invalid expression '<pycolmap.SiftMatchingOptions object at 0x7f43b3865b30>'
  pybind11_stubgen - [  ERROR] In pycolmap.match_sequential : Invalid expression '<pycolmap.SequentialMatchingOptions object at 0x7f43b3865af0>'
  pybind11_stubgen - [  ERROR] In pycolmap.match_sequential : Invalid expression '<pycolmap.TwoViewGeometryOptions object at 0x7f43b3865ab0>'
  pybind11_stubgen - [  ERROR] In pycolmap.match_spatial : Invalid expression '<pycolmap.SiftMatchingOptions object at 0x7f43b3865c70>'
  pybind11_stubgen - [  ERROR] In pycolmap.match_spatial : Invalid expression '<pycolmap.SpatialMatchingOptions object at 0x7f43b3865c30>'
  pybind11_stubgen - [  ERROR] In pycolmap.match_spatial : Invalid expression '<pycolmap.TwoViewGeometryOptions object at 0x7f43b3865bf0>'
  pybind11_stubgen - [  ERROR] In pycolmap.match_vocabtree : Invalid expression '<pycolmap.SiftMatchingOptions object at 0x7f43b3865df0>'
  pybind11_stubgen - [  ERROR] In pycolmap.match_vocabtree : Invalid expression '<pycolmap.VocabTreeMatchingOptions object at 0x7f43b3865db0>'
  pybind11_stubgen - [  ERROR] In pycolmap.match_vocabtree : Invalid expression '<pycolmap.TwoViewGeometryOptions object at 0x7f43b3865a30>'
  pybind11_stubgen - [  ERROR] In pycolmap.patch_match_stereo : Invalid expression '<pycolmap.PatchMatchOptions object at 0x7f43b3d9f770>'
  pybind11_stubgen - [  ERROR] In pycolmap.poisson_meshing : Invalid expression '<pycolmap.PoissonMeshingOptions object at 0x7f43b3de89b0>'
  pybind11_stubgen - [  ERROR] In pycolmap.pose_refinement : Invalid expression '<pycolmap.AbsolutePoseRefinementOptions object at 0x7f43b3d94570>'
  pybind11_stubgen - [  ERROR] In pycolmap.rig_absolute_pose_estimation : Invalid expression '<pycolmap.RANSACOptions object at 0x7f43b3da3030>'
  pybind11_stubgen - [  ERROR] In pycolmap.rig_absolute_pose_estimation : Invalid expression '<pycolmap.AbsolutePoseRefinementOptions object at 0x7f43b3d9f970>'
  pybind11_stubgen - [  ERROR] In pycolmap.sparse_delaunay_meshing : Invalid expression '<pycolmap.DelaunayMeshingOptions object at 0x7f43b387eaf0>'
  pybind11_stubgen - [  ERROR] In pycolmap.stereo_fusion : Invalid expression '<pycolmap.StereoFusionOptions object at 0x7f43b3d8f2b0>'
  pybind11_stubgen - [  ERROR] In pycolmap.triangulate_points : Invalid expression '<pycolmap.IncrementalPipelineOptions object at 0x7f43b3d78470>'
  pybind11_stubgen - [  ERROR] In pycolmap.undistort_images : Invalid expression '<pycolmap.UndistortCameraOptions object at 0x7f43b3858bb0>'
  pybind11_stubgen - [  ERROR] In pycolmap.verify_matches : Invalid expression '<pycolmap.TwoViewGeometryOptions object at 0x7f43b3865bb0>'
  pybind11_stubgen - [WARNING] Raw C++ types/values were found in signatures extracted from docstrings.
  Please check the corresponding sections of pybind11 documentation to avoid common mistakes in binding code:
   - https://pybind11.readthedocs.io/en/latest/advanced/misc.html#avoiding-cpp-types-in-docstrings
   - https://pybind11.readthedocs.io/en/latest/advanced/functions.html#default-arguments-revisited
  reformatted /tmp/tmptqly5k9v/build/pycolmap-stubs/manifold.pyi
  error: cannot format /tmp/tmptqly5k9v/build/pycolmap-stubs/__init__.pyi: Cannot parse: 150:35:     def __init__(self, arg0: colmap::BundleAdjustmentOptions, arg1: BundleAdjustmentConfig) -> None:
  reformatted /tmp/tmptqly5k9v/build/pycolmap-stubs/cost_functions.pyi

  Oh no! 💥 💔 💥
  2 files reformatted, 1 file failed to reformat.
  ninja: build stopped: subcommand failed.

  *** CMake build failed
  error: subprocess-exited-with-error

  × Building editable for pycolmap (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/shaoliu/anaconda3/envs/colmap/bin/python /home/shaoliu/anaconda3/envs/colmap/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_editable /tmp/tmpalwr2522
  cwd: /home/shaoliu/myProjects/colmap/pycolmap
  Building editable for pycolmap (pyproject.toml) ... error
  ERROR: Failed building editable for pycolmap
Failed to build pycolmap
ERROR: Could not build wheels for pycolmap, which is required to install pyproject.toml-based projects

**Comment by B1ueber2y** [comment]
Not sure if this is the same issue but I also could not make this PR work for the CI here: https://github.com/colmap/colmap/actions/runs/10585622183/job/29332619405?pr=2715

**Comment by sarlinpe** [comment]
As for the issue in https://github.com/colmap/colmap/pull/2715, you need to update the binding code such that `Caméra` is bound before `Image`. 

As for your local errors, I just realized that our CI doesn’t check for CUDA builds. Do the errors still show up if you build without CUDA?

**Comment by B1ueber2y** [comment]
Thanks. However, same error occurs with CUDA disabled for the local issue case.

**Comment by B1ueber2y** [comment]
> As for your local errors, I just realized that our CI doesn’t check for CUDA builds. Do the errors still show up if you build without CUDA?

Thanks. However, same error occurs when I have CUDA disabled.

**Comment by B1ueber2y** [comment]
> As for the issue in #2715, you need to update the binding code such that `Camera` is bound before `Image`.

This seems to be working there. Thanks!

**Comment by sarlinpe** [comment]
On a second look, all these errors have precisely been fixed by https://github.com/colmap/colmap/commit/5c51ead1454a3b78f26c239316131c931a01e0d9. Somehow your build must be based on pycolmap C++ code anterior to this PR.

**Comment by B1ueber2y** [comment]
I m pretty sure i m on the head.

(colmap) shaoliu@cvg-desktop-56:~/myProjects/colmap/pycolmap$ git log
commit 4ccfeb55e6548a2d15636796e42e1df292c073c5 (HEAD -> main, origin/main, origin/HEAD, official/main)
Author: Johannes Schönberger <joschonb@microsoft.com>
Date:   Mon Aug 26 22:06:26 2024 +0200

    Implement transitive matcher with pair generator + tests (#2735)

    * Implement transitive matcher with pair generator + tests

    * d

**Comment by B1ueber2y** [comment]
Disabling the ``GENERATE_STUBS`` in my local development for now to avoid blocking the development. Will try to look into it If more cases of similar issues are reported.

**Comment by B1ueber2y** [comment]
FYI I believe the stub wont work when you have an inconsistent colmap/pycolmap installed. That is to say, when a new feature is developed that can potentially change the pycolmap interface, to build pycolmap from source one needs to first install pycolmap with stub disabled, and then build again with stub enabled afterwards.

**Comment by sarlinpe** [comment]
Python should import the newly-built wheel instead of any existing package:
https://github.com/colmap/colmap/blob/d70edd784808d29c855fff0b4ffc2bdc3ea290f1/pycolmap/CMakeLists.txt#L46
Maybe this doesn't work... Adding this debug statement to generate_stubs.sh would help: `python -c "import pycolmap; print(pycolmap.__file__)"`
