### ISSUE TITLE
Modifying pycolmapReconstruction.points3D using delete_point3D() fails

### ISSUE THREAD

**Issue by ctorti** [colmap/colmap#2754]
**Describe the bug**
`pycolmap.Reconstruction.points3D.delete_point3D()` fails. Possibly related to #2655.

**To Reproduce**
The code below is used to delete points from a `pycolmap.Reconstruction` (`model`) whose error exceeds a threshold value (`max_error`):

```
from copy import deepcopy
from tqdm.auto import tqdm

new = deepcopy(model)

num = len(new.points3D.keys())

for pt_id, pt in tqdm(model.points3D.items(), total=num, desc='Filtering points in Pycolmap model'):
    if pt.error > max_error:
        new.delete_point3D(pt_id)
```

It fails with:

> ** Aborted at 1725517025 (unix time) try "date -d @1725517025" if you are using GNU date ***
>     @     0x7ff8366b4172 log2f
>     @     0x7ff76de31d0c (unknown)
>     @     0x7ff818aee5cf __C_specific_handler
>     @     0x7ff838d9504f __chkstk
>     @     0x7ff838d0e866 RtlFindCharInUnicodeString
>     @     0x7ff838d9403e KiUserExceptionDispatcher
>     @     0x7fff4c9257c6 public: static bool __cdecl embree::TaskScheduler::wait(void)
>     @     0x7fff49f802ae (unknown)
>     @     0x7fff49f82d5d (unknown)
>     @     0x7fff819ce4c5 (unknown)
>     @     0x7fff81f27799 PyInit_pycolmap
>     @     0x7ff818ad4160 __CxxFrameHandler4
>     @     0x7ff818ad2572 (unknown)
>     @     0x7ff838d94896 RtlCaptureContext2
>     @     0x7fff819d0e90 (unknown)
>     @     0x7fff9fda82be _PyObject_MakeTpCall
>     @     0x7fff9fdf5f41 PyIter_Send
>     @     0x7fff9fe33412 _PyLong_New
>     @     0x7fff9fda192c _PyCode_CheckLineNumber
>     @     0x7fff9fdad2b1 _PyEval_EvalFrameDefault
>     @     0x7fff9fde104e _Py_BuildValue_SizeT
>     @     0x7fff9fde0f4e _Py_BuildValue_SizeT
>     @     0x7fff9fdad2b1 _PyEval_EvalFrameDefault
>     @     0x7fff9fd87feb _PyType_CalculateMetaclass
>     @     0x7fff9fe52533 PyEval_EvalCode
>     @     0x7fff9fe50888 PyEval_GetBuiltins
>     @     0x7fff9fe50758 PyEval_GetBuiltins
>     @     0x7fff9fded2ec PyArg_UnpackTuple
>     @     0x7fff9fdac13b PyObject_Vectorcall
>     @     0x7fff9fdad423 _PyEval_EvalFrameDefault
>     @     0x7fff9fdaae64 _PyFunction_Vectorcall
>     @     0x7fff9fe55073 _PyObject_Call

The `pt_id` that it fails at varies from run to run (it's not consistent). I found that by adding a brief pause `time.sleep(0.001)` in the loop allows to complete to 100% but it doesn't stop the failure from occurring (i.e. `tqdm` will report that it has completed the looping but the failure will still occur).

Note: `tqdm` was added to determine whether the failure was occurring for a specific point ID (it isn't). The failure occurs even if `tqdm` isn't used.

**Environment:**
 - OS: Windows 11
 - Python Version 3.11.9
 - pyCOLMAP Version 0.6.1

**Comment by sarlinpe** [comment]
I managed to reproduce the issue at HEAD:
```python
import pycolmap

def fn_1(model, max_error):
    for pt_id, pt in model.points3D.items():
        if pt.error > max_error:
            print("removing", pt_id)
            model.delete_point3D(pt_id)

def fn_2(model, max_error):
    for pt_id in model.points3D.keys():
        if model.point3D(pt_id).error > max_error:
            print("removing", pt_id)
            model.delete_point3D(pt_id)

def fn_3(model, max_error):
    for pt_id in list(model.points3D.keys()):
        if model.point3D(pt_id).error > max_error:
            print("removing", pt_id)
            model.delete_point3D(pt_id)

model = pycolmap.Reconstruction("pycolmap/example/sfm/0/")
fn_3(model, 1.0)
```
Both `fn_1` and `fn_2` yield the following error after deleting the first point:
```
*** Aborted at 1725616555 (unix time) try "date -d @1725616555" if you are using GNU date ***
PC: @     0x7f73e0094210 (.../site-packages/pycolmap.cpython-310-x86_64-linux-gnu.so+0x49420f)
*** SIGSEGV (@0x5b3a2ceee) received by PID 2915389 (TID 0x7f73e2be1000) from PID 18446744072428375790; stack trace: ***
    @     0x7f73e2899ee8 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x99ee7)
    @     0x7f73e01830ed (.../site-packages/pycolmap.cpython-310-x86_64-linux-gnu.so+0x5830ec)
    @     0x7f73e2842520 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x4251f)
    @     0x7f73e0094210 (.../site-packages/pycolmap.cpython-310-x86_64-linux-gnu.so+0x49420f)
    @     0x7f73dfecb6fa (.../site-packages/pycolmap.cpython-310-x86_64-linux-gnu.so+0x2cb6f9)
    @     0x5b3a2bfd5dae (/usr/bin/python3.10+0x15adad)
    @     0x5b3a2bfcc52b _PyObject_MakeTpCall
    @     0x5b3a2bfe452b (/usr/bin/python3.10+0x16952a)
    @     0x5b3a2c03ebf1 (/usr/bin/python3.10+0x1c3bf0)
    @     0x5b3a2c108543 (/usr/bin/python3.10+0x28d542)
    @     0x5b3a2bfbed24 _PyEval_EvalFrameDefault
    @     0x5b3a2bfd66ac _PyFunction_Vectorcall
    @     0x5b3a2bfbe935 _PyEval_EvalFrameDefault
    @     0x5b3a2bfbb096 (/usr/bin/python3.10+0x140095)
    @     0x5b3a2c0b0f66 PyEval_EvalCode
    @     0x5b3a2c0dbe98 (/usr/bin/python3.10+0x260e97)
    @     0x5b3a2c0d579b (/usr/bin/python3.10+0x25a79a)
    @     0x5b3a2c0dbbe5 (/usr/bin/python3.10+0x260be4)
    @     0x5b3a2c0db0c8 _PyRun_SimpleFileObject
    @     0x5b3a2c0dad13 _PyRun_AnyFileObject
    @     0x5b3a2c0cd70e Py_RunMain
    @     0x5b3a2c0a3dfd Py_BytesMain
    @     0x7f73e2829d90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
    @     0x7f73e2829e40 __libc_start_main
    @     0x5b3a2c0a3cf5 _start
Segmentation fault (core dumped)
```
`fn_3` runs without error. This seems to validate my hypothesis: calling `delete_point3D` invalidates the views returned by `.key()` or `.items()` but doesn't affect the copy created by calling `list()`. I think that we can't do much about this.

**Comment by sarlinpe** [comment]
Note that this kind of operation is also not allowed in pure Python:
```python
d = dict(zip(range(10), range(10)))
for k in d.keys():
    if k % 2:
        del d[k]
```
throws: `RuntimeError: dictionary changed size during iteration`

**Comment by ctorti** [comment]
@sarlinpe I'm not sure what's happened to my pycolmap installation. Now I can't even run `pts_ids = list(model.points3D.keys())` without getting the error.

**Comment by sarlinpe** [comment]
Could you try installing pycolmap 3.10.0 or from source at HEAD? I don't have access to a Windows machine so I can't reproduce this.
