### ISSUE TITLE
Could you explain the workings of sequential matching in more detail

### ISSUE THREAD

**Issue by wangjinhoon** [colmap/colmap#2759]
Hello, thank you for providing such excellent code.
I have read about the various image matching techniques in the COLMAP documentation, but I still have difficulty understanding how sequential matching works.
Could you explain the workings of sequential matching in more detail?

Also, when using sequential images as input, does sequential matching generally perform better than exhaustive matching in most cases

**Comment by tsattler** [comment]
>  Could you explain the workings of sequential matching in more detail?

I think the best explanation is given by the code. Did you have a look at the sequential matching code?

> Also, when using sequential images as input, does sequential matching generally perform better than exhaustive matching in most cases

Unless you have scene parts that are very self-similar, where the exhaustive matcher might connect visually similar but physically separated parts, the exhaustive matcher should be better as it matches more image pairs.

**Comment by wangjinhoon** [comment]
@tsattler Thank you for your prompt response. I wanted to find the part where various matching techniques exist, but due to my lack of ability and not fully understanding the structure of the code, I failed. Could you clearly point out the part of the code that explains sequential matching and exhaustive matching in detail?

> > 순차적 매칭의 작업을보다 자세하게 설명 할 수 있습니까?
> 
> 코드에 의해 가장 좋은 설명이 있다고 생각합니다. 순차적 일치 코드를 살펴 보셨습니까?
> 
> > 또한 순차적 이미지를 입력으로 사용할 때 순차적 매칭은 일반적으로 대부분의 경우 철저한 매칭보다 더 잘 수행됩니다.
> 
> 철저한 매처가 시각적으로 유사하지만 물리적으로 분리 된 부품을 연결할 수있는 매우 유사한 장면 부품이 없다면, 더 많은 이미지 쌍과 일치하므로 철저한 매처가 더 좋습니다.

**Comment by tsattler** [comment]
There is a command line command `colmap sequential_matcher`. You can follow this through the code, see which functions it calls and look at these functions.

**Comment by wangjinhoon** [comment]
@tsattler Although I struggled a bit with how to use the COLMAP sequential matcher, I was eventually able to confirm where the matching works. Thank you for kindly guiding me, and once again, I appreciate you providing such a great code.
