### ISSUE TITLE
COLMAP 3.3 crash

### ISSUE THREAD

**Issue by tompollok** [colmap/colmap#276]
COLMAP 3.3 does crash on my Windows 10 machine when i perform feature extraction. The same dataset works with COLMAP 3.2 or earlier.

Is there any way identifying the issue other than compiling and debugging?

**Comment by ahojnnes** [comment]
3.3 or the development version or both?

You could share the image for which it crashes with me?

**Comment by tompollok** [comment]
Oh i thought it was the release version of COLMAP 3.3

But the crash was caused in the latest COLMAP 3.3-dev
![grafik](https://user-images.githubusercontent.com/4457821/35165286-082ddb82-fd4e-11e7-828e-a897f484602c.png)

**Comment by tompollok** [comment]
hmm there is something missing in that red box. It was basically just a standard windows notification that the application has crashed

**Comment by ahojnnes** [comment]
Could you share the images with me?

**Comment by ahojnnes** [comment]
This should be fixed with the latest commit in the dev branch. The pre-compiled binaries on the web page are also updated. Thanks for the bug report.

**Comment by tompollok** [comment]
Thank you for your quick fix :-) works perfectly now.
