### ISSUE TITLE
build.py fails on Windows 10 with Python 3.6

### ISSUE THREAD

**Issue by tompollok** [colmap/colmap#277]
Hello Johannes,

im trying to build colmap-dev on my system but python gives me some FileNotFoundError.
Could you help me with this? Im not sure which file it cant find, because i didnt modify anything with Python36

C:\git-repositories\colmap>python ./scripts/python/build.py --build_path ./build  --colmap_path . --boost_path "C:/local/boost_1_64_0/lib64-msvc-14.0" --qt_path "C:/Qt/5.9.3/msvc2015_64" --cmake_generator "Visual Studio 14"
Traceback (most recent call last):
  File "./scripts/python/build.py", line 467, in <module>
    main()
  File "./scripts/python/build.py", line 448, in main
    build_glog(args)
  File "./scripts/python/build.py", line 308, in build_glog
    build_cmake_project(args, os.path.join(path, "build"))
  File "./scripts/python/build.py", line 162, in build_cmake_project
    return_code = subprocess.call(cmake_command, cwd=path)
  File "C:\Program Files\Python36\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

**Comment by ahojnnes** [comment]
It seems CMake is not in the path?

**Comment by tompollok** [comment]
Oh right, it wasnt in the path... Thank you.

Now the script works  beautifully except that at the end i get:

MD5 mismatch for C:\git-repositories\colmap\build\__download__\suite-sparse.zip: 2cb76bf7a5d566d69e156fbf5eef03d8 == f5a156b8e8e4f70179399dc58ab33b8f

Another question: Shouldnt --cmake_generator "Visual Studio 14  2015 Win64" be instead of --cmake_generator "Visual Studio 14" because in your example you are referring to 64 bit builds and not 32 bit

**Comment by tompollok** [comment]
i modified the MD5 hash in my build.py script locally.

Line 269:    download_zipfile(url, archive_path, args.build_path,
                     "f5a156b8e8e4f70179399dc58ab33b8f")

But you probably need to check whether the script has to be updated or whether the package on your package server is outdated.

**Comment by ahojnnes** [comment]
I updated the SuiteSparse checksum. Thanks.

Regarding "Visual Studio 14" vs "Visual Studio 14 Win64": This should produce equivalent when using the build script, since it will automatically append the 64bit flag. COLMAP is only supported to build on 64bit systems.

**Comment by tompollok** [comment]
Thank you. Build works now properly.
