### ISSUE TITLE
Image viewer improvement

### ISSUE THREAD

**Issue by tompollok** [colmap/colmap#278]
Hello Johannes,

would you mind if i change the image viewer of your gui application such that it resizes the image while keeping the aspect ratio when the image is resized? This would automatically expand the image when you maximize the window.

Cheers,
Tom

**Comment by ahojnnes** [comment]
Sounds like a good idea. Would be happy to merge such a PR.

**Comment by tompollok** [comment]
Ok Ill prepare a PR as soon as i get to compile colmap on my machine.
