### ISSUE TITLE
Feature extractor run on CPU when using estimate affine shape and domain size pooling

### ISSUE THREAD

**Issue by HungNgoCT** [colmap/colmap#2785]
Hi.,

Thank you for your invaluable tool.

I have a question: When I apply feature extractor, the process run on GPU. However, when I use
--SiftExtraction.estimate_affine_shape true 
--SiftExtraction.domain_size_pooling true
Or, even one of them, feature extractor run on CPU. Then after that, matcher also run on CPU.

I am wondering that I was wrong something, or this property does not supper GPU? Is there any way to run this on GPU?

Thank you

**Comment by tsattler** [comment]
This is normal behavior as the SIFT GPU implementation used by Colmap supports none of these two properties. I am not aware of a GPU implementation of SIFT that supports them.

**Comment by HungNgoCT** [comment]
> This is normal behavior as the SIFT GPU implementation used by Colmap supports none of these two properties. I am not aware of a GPU implementation of SIFT that supports them.

Thank you @tsattler 

That is the information I needed. I just suspect I did somethings wrong. We can close here
