### ISSUE TITLE
Mapper and Bundle Adjustment

### ISSUE THREAD

**Issue by HungNgoCT** [colmap/colmap#2787]
Hi.,

Thank you for the work.

May I ask a question which I don't understand.

In colmap process, some code such as 3D Gaussian splatting uses just feature_extractor -> matcher -> mapper.
But Instant-ngp uses an additional step bundle_adjsuter. It means they use feature_extractor -> matcher -> mapper -> bundle_adjuster.

I understood that mapper contains bundle_adjuster already. Is my understanding correct?

Thank you very much for your help and please correct my understanding.

**Comment by ahojnnes** [comment]
The mapper always performs a final global bundle adjustment, so the extra bundle adjustment is likely to be redundant unless there are some custom parameters in either the mapper or bundle adjuster stages.

**Comment by HungNgoCT** [comment]
Thank you @ahojnnes .
That is information I needed. Please close here
