### ISSUE TITLE
Ambiguous database entries between two tables 

### ISSUE THREAD

**Issue by eyildiz-ugoe** [colmap/colmap#2793]
What's the difference between the fields of these two tables: rows of two_view_geometry vs rows of matches

I did a query on an occasion and found out the following:

`select * from two_view_geometries, matches where matches.pair_id = 274877906958 and matches.pair_id = two_view_geometries.pair_id`

and this returned me : 

274877906958 | 785 | 2 |   | 6 |   |   |   |   |   | 274877906958 | 661 | 2 |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

where 785 and 661 are both called "rows". I don't get why there is this discrepancy. I take it as one of them is the raw matches, and other one is ransac matches? Or what is this really, any idea? I could not find much in the docs.

**Comment by sarlinpe** [comment]
`matches` are the raw matches, `two_view_geometries` are matches filtered by RANSAC for two-view geometry estimation (E, F, or H, whichever fits best).

**Comment by eyildiz-ugoe** [comment]
thanks for the reply. in my case the number of matches are less than the number of ransac filtered ones, which made me confused. i've checked the database for an image pair (two_view_geometry and matches tables), and it seems to be the case. no idea why.

**Comment by ahojnnes** [comment]
Did you use guided matching? Then this can happen.

**Comment by eyildiz-ugoe** [comment]
Yes, that was set to true. Thanks for the clarification.
