### ISSUE TITLE
error: no matching function for call to ‘colmap::FeatureMatcherCache::FeatureMatcherCache(int, colmap::Database*)’

### ISSUE THREAD

**Issue by ImOP12138** [colmap/colmap#2794]
My system is ubuntu 22.04
Myproject's Cmake stage is OK , but when i Make  i met these issues have connection with Colmap ,i think it may be version conflict but don't know which version to convert.
 What should I do ?

> /home/op12138/zongshe2/src/incremental_map.cpp:350:84: error: ‘const class colmap::Image’ has no member named ‘NumVisiblePoints3D’
  350 |                                                                         next_image.NumVisiblePoints3D(),
      |                                                                                    ^~~~~~~~~~~~~~~~~~
/home/op12138/zongshe2/src/incremental_map.cpp:351:84: error: ‘const class colmap::Image’ has no member named ‘NumObservations’
  351 |                                                                         next_image.NumObservations());
      |                                                                                    ^~~~~~~~~~~~~~~
/home/op12138/zongshe2/src/incremental_map.cpp: In member function ‘void i2m::IncrementalMapperController::TriangulateReconstruction(const std::shared_ptr<colmap::Reconstruction>&)’:
/home/op12138/zongshe2/src/incremental_map.cpp:518:66: error: ‘const class colmap::Image’ has no member named ‘NumObservations’
  518 |                                                         << image.NumObservations() << " points";
      |                                                                  ^~~~~~~~~~~~~~~
/home/op12138/zongshe2/src/match_feature.cpp: In constructor ‘i2m::{anonymous}::ExhaustiveFeatureMatcher::ExhaustiveFeatureMatcher(const i2m::ExhaustiveMatchingOptions&, const colmap::SiftMatchingOptions&, const colmap::TwoViewGeometryOptions&, const string&)’:
/home/op12138/zongshe2/src/match_feature.cpp:157:25: error: no matching function for call to ‘colmap::FeatureMatcherCache::FeatureMatcherCache(int, colmap::Database*)’
  157 |                         cache_(5 * options_.block_size, &database_),
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/colmap/feature/sift.h:33,
                 from /home/op12138/zongshe2/src/match_feature.h:4,
                 from /home/op12138/zongshe2/src/match_feature.cpp:1:
/usr/local/include/colmap/feature/matcher.h:74:3: note: candidate: ‘colmap::FeatureMatcherCache::FeatureMatcherCache(size_t, std::shared_ptr<colmap::Database>, bool)’
   74 |   FeatureMatcherCache(size_t cache_size,
      |   ^~~~~~~~~~~~~~~~~~~
/usr/local/include/colmap/feature/matcher.h:75:49: note:   no known conversion for argument 2 from ‘colmap::Database*’ to ‘std::shared_ptr<colmap::Database>’
   75 |                       std::shared_ptr<Database> database,
      |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/home/op12138/zongshe2/src/match_feature.cpp: In constructor ‘i2m::{anonymous}::SequentialFeatureMatcher::SequentialFeatureMatcher(const i2m::SequentialMatchingOptions&, const colmap::SiftMatchingOptions&, const colmap::TwoViewGeometryOptions&, const string&)’:
/home/op12138/zongshe2/src/match_feature.cpp:267:33: error: no matching function for call to ‘colmap::FeatureMatcherCache::FeatureMatcherCache(const int&, colmap::Database*)’
  267 |                                 cache_(std::max(5 * options_.loop_detection_num_images,
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  268 |                                                                                                 5 * options_.overlap),
      |                                                                                                 ~~~~~~~~~~~~~~~~~~~~~~
  269 |                                                          &database_),
      |                                                          ~~~~~~~~~~~
In file included from /usr/local/include/colmap/feature/sift.h:33,
                 from /home/op12138/zongshe2/src/match_feature.h:4,
                 from /home/op12138/zongshe2/src/match_feature.cpp:1:
/usr/local/include/colmap/feature/matcher.h:74:3: note: candidate: ‘colmap::FeatureMatcherCache::FeatureMatcherCache(size_t, std::shared_ptr<colmap::Database>, bool)’
   74 |   FeatureMatcherCache(size_t cache_size,
      |   ^~~~~~~~~~~~~~~~~~~
/usr/local/include/colmap/feature/matcher.h:75:49: note:   no known conversion for argument 2 from ‘colmap::Database*’ to ‘std::shared_ptr<colmap::Database>’
   75 |                       std::shared_ptr<Database> database,
      |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/home/op12138/zongshe2/src/match_feature.cpp: In constructor ‘i2m::{anonymous}::SpatialFeatureMatcher::SpatialFeatureMatcher(const i2m::SpatialMatchingOptions&, const colmap::SiftMatchingOptions&, const colmap::TwoViewGeometryOptions&, const string&)’:
/home/op12138/zongshe2/src/match_feature.cpp:442:33: error: no matching function for call to ‘colmap::FeatureMatcherCache::FeatureMatcherCache(int, colmap::Database*)’
  442 |                                 cache_(5 * options_.max_num_neighbors, &database_),
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/colmap/feature/sift.h:33,
                 from /home/op12138/zongshe2/src/match_feature.h:4,
                 from /home/op12138/zongshe2/src/match_feature.cpp:1:
/usr/local/include/colmap/feature/matcher.h:74:3: note: candidate: ‘colmap::FeatureMatcherCache::FeatureMatcherCache(size_t, std::shared_ptr<colmap::Database>, bool)’
   74 |   FeatureMatcherCache(size_t cache_size,
      |   ^~~~~~~~~~~~~~~~~~~
/usr/local/include/colmap/feature/matcher.h:75:49: note:   no known conversion for argument 2 from ‘colmap::Database*’ to ‘std::shared_ptr<colmap::Database>’
   75 |                       std::shared_ptr<Database> database,
      |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
make[2]: *** [CMakeFiles/img2mesh.dir/build.make:118: CMakeFiles/img2mesh.dir/src/incremental_map.cpp.o] Error 1
make[2]: *** [CMakeFiles/img2mesh.dir/build.make:146: CMakeFiles/img2mesh.dir/src/match_feature.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/img2mesh.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by sarlinpe** [comment]
`incremental_map.cpp` isn't a COLMAP source file so I assume that you are building a custom project. Recent refactorings have moved some functions like `Image::NumVisiblePoints3D`, etc. We don't guarantee that COLMAP's C++ API is stable over time.

**Comment by ImOP12138** [comment]
> `incremental_map.cpp` isn't a COLMAP source file so I assume that you are building a custom project. Recent refactorings have moved some functions like `Image::NumVisiblePoints3D`, etc. We don't guarantee that COLMAP's C++ API is stable over time.

Thanks for replying!  That's correct, this is my own project. If so , I am going to fix my own project. 
Thanks again!
