### ISSUE TITLE
Building Error using Ubuntu 14.04

### ISSUE THREAD

**Issue by MrBlubb** [colmap/colmap#28]
When I try to build colmap using Ubuntu 14.04 I receive the following error message:

colmap/src/ext/PoissonRecon/MultiGridOctreeData.inl:227:11: error: expected unqualified-id before ‘(’ token
`if(std::isnan( normalLength ) || !std::isfinite( normalLength ) || normalLength<=EPSILON ) continue;`

colmap/src/ext/PoissonRecon/MultiGridOctreeData.inl:227:42: error: expected unqualified-id before ‘(’ token
`if(std::isnan( normalLength ) || !std::isfinite( normalLength ) || normalLength<=EPSILON ) continue; `

I fixed the problem, by removing the "std::" namespace in front of "isnan" and "isfinite". In this case I guess, the compiler uses the C isnan and isfnite methods. I'm not sure why they are not part of the std namespace. 

Btw: I used CMake 3.2.2. during the building process

**Comment by ahojnnes** [comment]
Fixed in https://github.com/colmap/colmap/commit/20838d0008b231525c42ae7cfdf164dbd4f0237b

Thanks!
