### ISSUE TITLE
Registering a new image to a reconstruction

### ISSUE THREAD

**Issue by tompollok** [colmap/colmap#280]
Hi Johannes,

may I ask if it is easily possible to estimate the pose of a new image to a reconstruction in your tool?
It is just the user interface that has to be extended + some function calls or does it require some extensive refactoring?

Cheers,
Tom

**Comment by ahojnnes** [comment]
See https://colmap.github.io/faq.html#register-localize-new-images-into-an-existing-reconstruction - just have a look in the respective function in ``src/exe/colmap.cc`` to follow the functions.

**Comment by saisharathsadu** [comment]
But, while doing the image registration, it is chaging my points3D.bin. How to avoid the bundle adjustment ? My need is to only estimate poses of new images using the existing reconstrution. When I use the following flags for image_registrator, it is giving me errors.

Flags:
--Mapper.ba_global_max_num_iterations 0 
--Mapper.ba_local_max_num_iterations 0 
--Mapper.ba_global_max_refinements 0 
--Mapper.ba_local_max_refinements 0 

Error: 
[incremental_mapper.cc:288] Check failed: ba_global_max_num_iterations > 0 (0 vs. 0)
ERROR: Invalid options provided.

Can you comment on this
