### ISSUE TITLE
ERROR: Failed to parse options: the option '--database_path' is required but missing.

### ISSUE THREAD

**Issue by InomnipotentComedy** [colmap/colmap#281]
Ambarrassed for my first issue on gitbub. When I  execute the 'colmap gui' on Ubuntu, the error ''Failed to parse options: the option '--database_path' is required but missing ''will come out. I've look up the document and tutorial, but didn't find the solution. How can I do for this? Thanks in advance. Forgive my not-good English.

**Comment by ahojnnes** [comment]
Did you provide an image path or did you just type “colmap gui”?

**Comment by InomnipotentComedy** [comment]
Thank you for reply. The both I've tried.
If typing "colmap gui" in terminal, the error appears. Then I typed "colmap gui --database_path [**images**]", "ERROR: Failed to parse options: the option '--**image_path**' is required but missing"comes out. 
Then I tried typing colmap gui --database_path [project]  --image_path [images], but the options are invalid.
[images] and [project] represent the paths respectively.

**Comment by InomnipotentComedy** [comment]
It’s Ubuntu 16.04lts in Virtualbox. If the environment impacts, I will try to build in true environment on Ubuntu 16.04lts. 
And when execute colmap3.3 with Ceolmap.bat on Win10 system, the program will crash.

**Comment by InomnipotentComedy** [comment]
I've tested in the real environment ubuntu16.04, but the problem still exists.

**Comment by ahojnnes** [comment]
I guess, I know what is going on. Are you in the master or dev branch?

**Comment by InomnipotentComedy** [comment]
I am not sure whether I exactly get the meaning of your comment above. I tried downloading the colmap-3.3 and building just moment ago, the error is displayed below :(
**owen@owen-VirtualBox:~/SfM/colmap-3.3/build$ colmap gui
ERROR: Failed to parse options: the option '--database_path' is required but missing.**

**Comment by ahojnnes** [comment]
The command-line interface changed. In 3.3 you would only run ``colmap --database_path ...`` without the GUI, in the dev branch it is ``colmap gui ...`` - I recommend to checkout the dev branch in any case.

**Comment by InomnipotentComedy** [comment]
Thanks a lot. I tried
`colmap feature_extractor \
   --database_path $DATASET_PATH/database.db \
   --image_path $DATASET_PATH/images`
,the gui popped up. Now I'm reading your papers about SfM. The papers and open-sources are very helpful to my research. Thank you again :)

**Comment by ahojnnes** [comment]
Glad to hear. Let me know if there are other questions.
