### ISSUE TITLE
CUDA support not enabled when Ceres was built

### ISSUE THREAD

**Issue by Joeljensen28** [colmap/colmap#2817]
Hi all, I am trying to build dense reconstructions from the command line interface. After processing for a while, it repeatedly throws this error at me:
```
W20240930 17:48:28.491569 25592 levenberg_marquardt_strategy.cc:123] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
```
After this error appears several dozen times, it finally throws this:
```
E20240930 17:48:32.194454 25592 bundle_adjustment.cc:403] Check failed: solver_options.IsValid(&solver_error) 
Can't use DENSE_SCHUR with dense_linear_algebra_library_type = CUDA because support not enabled when Ceres was built.
```
And then aborts the process.

I am using a VM with an NVIDIA H100 GPU that I know has CUDA installed.

For detailed steps, here is what I am doing:
1. Create a brand new VM droplet
2. Install NVIDIA drivers with `sudo apt install nvidia-driver-515`
3. Install dependencies with the following commands:
```
sudo apt-get install \
    git \
    cmake \
    ninja-build \
    build-essential \
    libboost-program-options-dev \
    libboost-filesystem-dev \
    libboost-graph-dev \
    libboost-system-dev \
    libeigen3-dev \
    libflann-dev \
    libfreeimage-dev \
    libmetis-dev \
    libgoogle-glog-dev \
    libgtest-dev \
    libgmock-dev \
    libsqlite3-dev \
    libglew-dev \
    qtbase5-dev \
    libqt5opengl5-dev \
    libcgal-dev \
    libceres-dev

    sudo apt-get install -y \
    nvidia-cuda-toolkit \
    nvidia-cuda-toolkit-gcc
```
4. Compile COLMAP from source with the following commands:
```
git clone https://github.com/colmap/colmap.git
    cd colmap
    mkdir build
    cd build
    cmake .. -GNinja
    ninja
    sudo ninja install
```
5. Once it compiles without issue, I created a `workspace` directory, moved my image files into it using FileZilla, then ran `automatic_reconstruction` with all needed parameters. The process ran for maybe 5-10 mins before throwing the aforementioned errors at me and aborting the process.

I'm not quite sure what the expected outcome looks like as I haven't been able to successfully create a dense reconstruction yet.

<img width="1000" alt="Screenshot 2024-09-30 at 1 16 21 PM" src="https://github.com/user-attachments/assets/5d9acfe1-15ee-4500-94dd-d987896704b8">

 - OS: Ubuntu 24.04
 - COLMAP Version: Whatever [this](https://colmap.github.io/install.html) is compiling

How do I "compile ceres with CUDA support"?

Thanks in advance!

**Comment by ahojnnes** [comment]
Thank you, I hope this fixes your issue: https://github.com/colmap/colmap/issues/2817. Could you please confirm?
