### ISSUE TITLE
dense stereo configuration has problems

### ISSUE THREAD

**Issue by xwshawn** [colmap/colmap#283]
I'm runing colmap on a Ubuntu 16.04 workstation with NVIDIA Auadro M1000M (Cuda enabled).

I've tried different datasets, it always crushes at the dense stereo step after image undistortion.
Results are the same when using automatic_reconstructor and dense_stereo.

dense_stereo --workspace_path ./dense/0/ --DenseStereo.geom_consistency true --DenseStereo.gpu_index 0

Reading workspace...
Reading configuration...
Configuration has 12 problems... //note: there are 12 images

==============================================================================
Processing view 1 / 12
==============================================================================

Reading inputs...

PatchMatch::Problem
-------------------
ref_image_id: 8
src_image_ids: 9 10 7 6 11 5 3 2 1 4 0

PatchMatchOptions
-----------------
max_image_size: -1
gpu_index: 0
depth_min: 4.22433
depth_max: 15.1033
window_radius: 5
sigma_spatial: 5
sigma_color: 0.2
num_samples: 15
ncc_sigma: 0.6
min_triangulation_angle: 1
incident_angle_sigma: 0.9
num_iterations: 5
geom_consistency: 0
geom_consistency_regularizer: 0.3
geom_consistency_max_cost: 3
filter: 0
filter_min_ncc: 0.1
filter_min_triangulation_angle: 3
filter_min_num_consistent: 2
filter_geom_consistency_max_cost: 1
write_consistency_graph: 0

PatchMatch::Run
---------------
CUDA error at /home/nwx8/Programs/colmap/src/./mvs/gpu_mat.h:152 - out of memory

**Comment by xwshawn** [comment]
If I set the max image size to 10, it still shows configuration has problems, but it can run through to the end.
dense_stereo --workspace_path ./dense/0/  --DenseStereo.max_image_size 10
Reading workspace...
Reading configuration...
Configuration has 12 problems...
==============================================================================
Processing view 1 / 12
==============================================================================

...

Writing geometric output for P1180169.JPG
Elapsed time: 0.595 [minutes]


However, when I run the next step, there isn't any point in the images:

dense_fuser --workspace_path ./dense/0/ --input_type geometric --output_path ./dense/0/fused.ply

StereoFusion::Options
---------------------
max_image_size: -1
min_num_pixels: 5
max_num_pixels: 10000
max_traversal_depth: 100
max_reproj_error: 2
max_depth_error: 0.01
max_normal_error: 10
check_num_images: 50
cache_size: 32

Reading workspace...
Reading configuration...
Fusing image [1/12] in 0.000s (0 points)
Fusing image [2/12] in 0.000s (0 points)
Fusing image [3/12] in 0.000s (0 points)
Fusing image [4/12] in 0.000s (0 points)
Fusing image [5/12] in 0.000s (0 points)
Fusing image [6/12] in 0.000s (0 points)
Fusing image [7/12] in 0.000s (0 points)
Fusing image [8/12] in 0.000s (0 points)
Fusing image [9/12] in 0.000s (0 points)
Fusing image [10/12] in 0.000s (0 points)
Fusing image [11/12] in 0.000s (0 points)
Fusing image [12/12] in 0.000s (0 points)
WARNING: Could not fuse any points. This is likely caused by incorrect settings - filtering must be enabled for the last call to patch match stereo.
Number of fused points: 0
Elapsed time: 0.184 [minutes]
Writing output: ./dense/0/fused.ply

**Comment by ahojnnes** [comment]
Hi,

I guess this error message is pretty self explanatory:

> CUDA error at /home/nwx8/Programs/colmap/src/./mvs/gpu_mat.h:152 - out of memory

Please refer to https://colmap.github.io/faq.html#reduce-memory-usage-during-dense-reconstruction for a solution.

**Comment by xwshawn** [comment]
Thanks a lot for the quick response.
If you see the second post, during the stereofusion step there is no point in images, even the dense_stereo step has gone through by setting max_image_size to 10.

Doesn't work either when I try to reduce the cache_size.

dense_stereo --workspace_path ./dense/0/ --DenseStereo.geom_consistency false --DenseStereo.gpu_index 0 --DenseStereo.cache_size 20 --DenseStereo.max_image_size 10
Reading workspace...
Reading configuration...
Configuration has 12 problems...
Elapsed time: 0.001 [minutes]
