### ISSUE TITLE
model_aligner result is not visible

### ISSUE THREAD

**Issue by yuyunlong2002** [colmap/colmap#2843]
I used colmap to complete SFM and reconstructed a sparse point cloud. **To restore its scale information,** I wanted to use
model_aligner for geographic registration. Based on the EXIF image, I exported the corresponding **GPS coordinates (Lat/Lun/Alt)** and converted them to ECEF coordinates using Python to obtain the registration file **`ecef.txt`**:

```
103_0103_0121.JPG -2850430.6307428973 4651865.005753526 3292932.4731842447
103_0103_0135.JPG -2850441.5355137857 4651816.64551588 3292991.0006551472
103_0103_0109.JPG -2850420.470058512 4651881.385820527 3292918.1398732658
103_0103_0280.JPG -2850445.7640469596 4651839.012149191 3292955.8953820216
103_0103_0257.JPG -2850412.337092797 4651854.874300633 3292962.3959337454
……
```

The command I am using is:
```
colmap model_aligner \
    --input_path "data/sparse/0" \
    --output_path "data/sparse/aligner/" \
    --ref_images_path  "F:\\Work\\ecef.txt" \
    --ref_is_gps 0 \
    --alignment_type ecef \
    --alignment_max_error 3.0
```

The output of the model_aligner command line is:
```
Cartesian Alignment Coordinates extracted (MUST NOT BE GPS coords!).

Aligning reconstruction to ecef
-------------------------------
 => Using 290 reference images
=> Alignment error: 0.049162 (mean), 0.045207 (median)
=> Alignment succeeded
```
But when I imported the model into Colmap for viewing, I found that there was only a blank window and nothing **but the display image and point cloud have already been imported**.
![image](https://github.com/user-attachments/assets/55a272b8-df32-4bbc-8e60-af23828120ee)
**Has anyone encountered the same problem? I urgently need help**

**Comment by ahojnnes** [comment]
The colmap viewer is designed to visualize the SfM reconstruction result (which is always normalized between [-10, 10]). When importing a reconstruction into the viewer, it is not auto-normalized to this range but the viewport is roughly looking at the box [-10, 10]. The reconstruction should appear after selecting `Reconstruction -> Normalize Reconstruction`. However, in this case, when you select an image or a 3D point, its coordinates will not be in ECEF anymore.

**Comment by yuyunlong2002** [comment]
Thank you for your help. I solved the problem by converting the results to `enu-plane`.
