### ISSUE TITLE
How to solve accumulated error

### ISSUE THREAD

**Issue by HungNgoCT** [colmap/colmap#2847]
Hi,
Thank you for great work.

I am trying to divide a big model with many images into smaller models with less images for pose reconstruction. Then I merge smaller models into a merged model.

However, this caused a gap (accumulated error) between the last small model to the first small model as shown in the image below (left side), while there is no gap when using mapper as shown in the image on the right.

I search from google, @ahojnnes said we should do a bundle_adjuster for fine tune. But the result is still the same after running bundle_adjustment.

@ahojnnes : Can you give me an advice how to solve this? What parameters should I use to running bundle_adjuster? I also tried with hierarchical_mapper. But now, I would like to try with model merge.

Thank you

![image](https://github.com/user-attachments/assets/70f5a1d4-52c9-4247-8bc8-6ed7837cbe60)

**Comment by HungNgoCT** [comment]
> How do you merge the models?

Hi @ahojnnes 

Sorry for late reply.

I produced the result like this:
1) I used 360 camera to record my walking path. Converted and rig images into 8 cameras (cam 1, cam 2, ... cam 8)
2) Extracted features for all data with --ImageReader.single_camera_per_folder = 1
3) Matched features
4) Divided path into some segments: A, B, C, D. Each segment include overlap images with previous one. Also, prepare a last segment E which connects between segment D and segment A, as shown in the image below
            
![image](https://github.com/user-attachments/assets/65ba8ccc-7fdf-4ed1-9632-b5eeae0de87b)
                                        
5) Merge: colmap model_merge 
    5.1) Merge segment A to B, then bundle adjustment
          colmap model_merger --input_path1 A --input_path2 B --output_path MergeAB
          colmap bundle_adjuster --input_path MergeAB --output_path BundleAdjAB
    5.2) Similar merge and bundle adjustment BundleAdjAB to segment C, then to segment D, finally to segment E
    5.3) Bundle Adjustment for whole images

Below image is the entire path I walked
![image](https://github.com/user-attachments/assets/601e61a1-e68e-4993-8e80-2137a8e32f12)

Segment E (connected between D to A) is good, as shown in the video below

https://github.com/user-attachments/assets/39dd3875-6250-416d-8746-e8aff7004848

But the final result I got an accumulated error, as shown in the video below. We can see that there are 2 ground surfaces, and double trees produced

https://github.com/user-attachments/assets/d73fe38f-3112-4155-9656-28f7ceaedc60

Please help me to understand this problem and how to reduce accumulated error.

Thank you

**Comment by HungNgoCT** [comment]
> How do you merge the models?

Hi @ahojnnes ,

I can find answer myself. After bundle adjustment several times, then close the gap as shown in the figure below
![image](https://github.com/user-attachments/assets/d892f8c4-2c08-4129-bad8-397b5fba8267)

Maybe the "stitching" segment E  is short, it needs several times to adjust and take very long time.

**Comment by ahojnnes** [comment]
@HungNgoCT This is expected. It can take a long time to distribute drift error along the trajectory. With a custom bundle adjuster and better pre-conditioning of the problem, the convergence could be faster, but this is not supported in ceres and thus by transitivity in colmap.

**Comment by HungNgoCT** [comment]
Completed. I closed it here
