### ISSUE TITLE
Feature Extraction Problem

### ISSUE THREAD

**Issue by jlpoolen** [colmap/colmap#285]
I shot some photos of our house using a Nikon with the 24mm tilt-shift lens (architectural lens), set with no tilting or shifting.  Using a tripod with the lens at F11 and later to F32 to increase the depth of field.   A sample of every 10th JPEG is at: https://www.dropbox.com/sh/iatnmhrn2kwz0mg/AAADX8lpe_moeun6XdRRz7gia?dl=0

Extraction Parameters:
![image](https://user-images.githubusercontent.com/227313/35486089-bc343f42-041d-11e8-9afb-111b2f290ffb.png)

> 

>Extraction Fails:
> ==============================================================================
>Feature extraction
> ==============================================================================

>Processed file [1/60]
>  Name:            DSC_1246.JPG
>  ERROR: Failed to extract features.
....

I had succeeded in extracting features from less dense photo, e.g. extractions from a movie clip.  I do not understand the various parameters of the Extraction Dialog box and wonder where I can learn more about each setting.

My inability to extract features is hampered by my ignorance and of lack of help within the interface.  I realize that takes up developer's time to document and I'm not trying to whine that there should be help.  Is there a definitive source or couple of sources that explain the effects of the variables?  For example, "num_octaves" -- I haven't a clue.  And "upright"?  Is that portrait or landscape mode for a frame?  Does portrait or landscape mode matter to the workflow?  

I shot my photos in sequence, they are numbered based on the order taken.  I simply encircled my house taking about 60 photos.  My distances varied at times as I could not keep a consistent distance from the facade I was shooting given some physical constraints of the property.

**Comment by jlpoolen** [comment]
I forked the project and am digging around in the code where there is further detail documentation.  At this point, I recommend anyone having the same problem as I did above probably should start looking in the code at the comments contained therein.  For example, camera_model.h, has  comments.

**Comment by ahojnnes** [comment]
I guess, you are not using the CUDA version?

**Comment by ahojnnes** [comment]
This comment should have gone to your other issue. Ignore it here.

**Comment by jlpoolen** [comment]
I'm experimenting with different version of my photos, some at 25%, 50%, 75%.  I'm also trying various setting from size of photo to number of threads and either selecting CUDA on or off.  It looks like the problem I encountered concerns CUDA and that I hit a memory limit.  I tried disengaging CUDA and was able to slowly push some large photos through.  I haven't created a reproducible scenario, but I suspect there may be some latent setting that lingers with the CUDA paradigm.  I've found that restarting Colmap causing a process to work using CUDA where on a 2nd try after an error message, it doesn't.  In other words, if I encounter an error and then try with a less aggressive setting, I'll get an error message, whereas if I close down Colmap and start anew, the processing goes through.

**Comment by ahojnnes** [comment]
How much GPU memory do you have?

**Comment by jlpoolen** [comment]
![nvcplui_2018-01-29_20-28-58](https://user-images.githubusercontent.com/227313/35548294-58121b08-0533-11e8-91c2-a3c7734b09c0.png)
![nvcplui_2018-01-29_20-29-25](https://user-images.githubusercontent.com/227313/35548299-5d31e352-0533-11e8-9d88-1a0766a0193b.png)
![nvcplui_2018-01-29_20-31-33](https://user-images.githubusercontent.com/227313/35548342-9f6fe62e-0533-11e8-9115-89b8e83e6dcc.png)

**Comment by martimpassos** [comment]
Hello, 

I see that this issue was concerning colmap 3.5 but I'm running into the same problem on 3.6 (3.5 works fine, but I'm interested in the masking feature). I actually did use 3.6 for a bit but now it is refusing to extract features from any dataset... Tried TIF, JPEG, resizing, nothing seems to work. 8GB GPU here

**Comment by GabbySuwichaya** [comment]
I am also having the same problem. Before this, I remembered that I can just extract the features from the same set of images. Could you provide some update?

**Comment by eyildiz-ugoe** [comment]
Same problem here, using the latest release. An update would be highly appreciated.
