### ISSUE TITLE
How to add stereo camera model and disparity map?

### ISSUE THREAD

**Issue by DaicongChen** [colmap/colmap#2852]
Hi, Thanks for the contribution! I want know how to add Binocular Stereo Vision photo and I already have disparity maps from SGM. And I hope my disparity maps can be used in Colmap to reconstruction.

**Comment by ahojnnes** [comment]
Hi, this type of input is not supported out of the box in colmap. You can certainly leverage the data but it will require manual changes of the reconstruction pipeline. This could be achieved in C++ or Python.
