### ISSUE TITLE
Importing pycolmap doesn't expose pycolmap symbols unless I explicitly import pycolmap._core

### ISSUE THREAD

**Issue by theartful** [colmap/colmap#2856]
**Describe the bug**
This doesn't work:
```python
In [1]: import pycolmap

In [2]: pycolmap.Image
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 pycolmap.Image

AttributeError: module 'pycolmap' has no attribute 'Image'

```
But this does:
```python
In [1]: import pycolmap._core as pycolmap

In [2]: pycolmap.Image
Out[2]: pycolmap._core.Image
```
I think pycolmap is missing an `__init__.py` file that exposes `_core` symbols.

**To Reproduce**
1. Build colmap and install it from source (using cmake and make install).
2. Build pycolmap and install it from source (using cmake and make install).
3. Add `/usr/local` to the PYTHONPATH.
4. Try importing pycolmap symbols from python

**Expected behavior**
I should be able to import pycolmap symbols from `pycolmap` not `pycolmap._core`.

**Comment by sarlinpe** [comment]
Thank you for reporting this issue. Pycolmap should not be installed using cmake & make install but instead with `python -m pip install pycolmap/` (as instructed in the [README](https://github.com/colmap/colmap/tree/main/pycolmap#installation)). The `__init__.py` file that you suggest already exists [here](https://github.com/colmap/colmap/blob/main/pycolmap/pycolmap/__init__.py) and is copied to the appropriate location by pip on install, which vanilla cmake/make cannot take care of.

**Comment by theartful** [comment]
I see. I installed pycolmap using cmake in previous versions, sobI thought this is a regression. Closing the issue, then.

**Comment by antoinebio** [comment]
Hello,
I am opening that issue again as I am facing that issue 
`TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. pycolmap._core.Database()`
on a workstation where I have install
colmap v3.12.6

<img width="218" height="49" alt="Image" src="https://github.com/user-attachments/assets/d436ba2e-f390-4af5-b144-4e6e00b331b8" />

as I am running that script https://github.com/colmap/colmap/blob/release/3.12/python/examples/panorama_sfm.py inside a conda env, I have checked the pycolmap version installed

<img width="646" height="423" alt="Image" src="https://github.com/user-attachments/assets/9f6cfa49-e21e-4e96-9f01-c6baf92e264f" />

please note that script https://github.com/colmap/colmap/blob/release/3.12/python/examples/panorama_sfm.py was working fine on other machine i've tested so far.

The reported issue is occuring only here...
