### ISSUE TITLE
Does COLMAP not like rotation? Need help with tall structures

### ISSUE THREAD

**Issue by Ujjwal-Rohilla** [colmap/colmap#2858]
**Describe the bug**
It appears that COLMAP does not like rotation. How would I then use it for tall structures? Is it just not possible or is there some way?

![image](https://github.com/user-attachments/assets/acf00f39-af2c-4bce-b945-38126dee8cb7)

(In the image the staircase ceiling is high which I would like to capture that as well... is there any way?)

**To Reproduce**
1. Record a video of a tall structure such as a staircase with tall ceiling
2. Run the command as usual
3. COLMAP freaks out and gives a lot of
```
Finding good initial image pair
=> No good initial image pair found.
```
5. If I am to proceed with then gaussian splatting this data, bad quality splats made

**Expected behavior**
—

**Screenshots**
Only two images were used for reconstruction
![image](https://github.com/user-attachments/assets/c454876c-56a5-4c81-b80d-a8a54c169912)

**Environment:**
 - Windows 11
 - I assume it is the latest one (the one from gaussian splatting repo)
 - FUJIFILM DIGITAL CAMERA X-S20

**Comment by sarlinpe** [comment]
Most of your images are textureless, COLMAP is not expected to work on these. You can confirm this by checking the images correspondences in the GUI.
