### ISSUE TITLE
How to accurately measure the distance between generated points?

### ISSUE THREAD

**Issue by Gi-Eufrasio** [colmap/colmap#2859]
I need to measure the components contained in the point clouds. However, after generating the dense cloud, when I try to use programs like CloudCompare, Blender, or Autodesk ReCap, the measurements in meters are significantly larger than the actual size of the component or object. I would like to know how to adjust the measurements to obtain values closer to the real ones with the point cloud generated by COLMAP. 

Example of measuring a door through point distance in a Point Cloud 😕:

![image](https://github.com/user-attachments/assets/626d7886-4e49-459f-9e5b-a42d4696d938)

**Comment by sarlinpe** [comment]
Structure-from-motion estimates camera poses and 3D structure up to a unknown scale factor - they are not metric. The only way to obtain metric scale is to run the `pose_prior_mapper` on images with GPS information in their EXIF (only for outdoor data).

**Comment by Gi-Eufrasio** [comment]
However, how can I obtain precise measurements of things in an indoor environment using COLMAP?

> Estrutura-a-partir-do-movimento estima poses de câmera e estrutura 3D até um fator de escala desconhecido - elas não são métricas. A única maneira de obter escala métrica é executar as `pose_prior_mapper`imagens com informações de GPS em seu EXIF ​​(somente para dados externos).

**Comment by kielnino** [comment]
As already described, structure-from-motion cannot solve this problem. How is colmap supposed to know whether the recordings are from the real world or show a miniature scene?
In order to obtain a metric scaling, one measurement of the distance must be specified. For example, using known poses of the cameras.
You could also reconstruct the scene up-to-scale and scale it afterwards using a known size.

**Comment by Gi-Eufrasio** [comment]
> Como já descrito, uma estrutura a partir do movimento não pode resolver esse problema. Como o colmap realizado sabe se as gravações são do mundo real ou mostram uma cena em miniatura? Para obter uma escala métrica, uma medida de distância deve ser especificada. Por exemplo, usando poses conhecidas das câmeras. Você também pode reconstruir a cena em escala e escalar depois usando um tamanho conhecido.

Thanks!

**Comment by kielnino** [comment]
@Gi-Eufrasio Perfect, would you mind to close the issue then?
