### ISSUE TITLE
Feature Request: Log Output of Dialog Box Variables

### ISSUE THREAD

**Issue by jlpoolen** [colmap/colmap#286]
It would be helpful if the dialog interfaces, e.g. Features Extraction, could output the variables selected by the user into the log so there is a clear record of what the user selected.  Then Issues submitted here could have a written record of variables in play at the time of the problem arises.

**Comment by ahojnnes** [comment]
You can save all options using the File > Save project menu item. You can open the resulting *.ini file in a text editor, which contains all the current options. Would that work for you?

**Comment by jlpoolen** [comment]
It's good to know that the project's *.ini file has everything in it.

I've made a fork, I might try have a method that dumps the variables into the log so there is a self contained record in the log.  When trying different settings, it is cumbersome to have to save the project file, then pull it out and save the snapshot and then correlate the snapshot with the log.  I'd like to see a log file that is self-contained regarding documentation so that the case can be reproduced.

**Comment by jlpoolen** [comment]
I've been running some dense stereo builds and Colmap suddenly crashes.  It seems like it processes about six or seven and then: boom, it disappears.  I've been working with smaller images -- shots from a Nikcon D70 which has about 1/4 the size of the Nikon 750 and I've been able to use TIFF format -- everything appears to go very smoothly.  JPEGs from my 750 took a lot more time and I'm guessing it is because of distortions the conversion from DNG to JPEG created.  Any rate, it would be helpful to have an option of having a log file where everything printed in the window "log" is simultaneously written to a file (with a flush) so when Colmap crashes, I have something tangible to determine at what point.  Since this issue concerned logging, I thought it best to re-open this feature request with this additional consideration.

**Comment by ahojnnes** [comment]
@jlpoolen This is what the command line interface is for. I will keep this open for now, but I don't have the time to implement such a feature in the near future. Thanks for the suggestion.
