### ISSUE TITLE
Reconstruction IO breaks in pycolmap when installing with wheels

### ISSUE THREAD

**Issue by B1ueber2y** [colmap/colmap#2868]
The issue is tracked to be due to https://github.com/colmap/colmap/pull/2809. Building from source works fine. To reproduce:

```
import os
import pycolmap
recon = pycolmap.Reconstruction("./pycolmap/example/sfm/0/") # will throw an error
os.mkdir("tmp")
recon.write("tmp") # will throw an error as well
```

Error message: 
*** Aborted at 1730304332 (unix time) try "date -d @1730304332" if you are using GNU date ***
PC: @     0x7f6553fbc5e9 std::filesystem::__cxx11::path::_List::_Impl_deleter::operator()(std::filesystem::__cxx11::path::_List::_Impl*) const
*** SIGBUS (@0x0) received by PID 1429042 (TID 0x7f657e208280) from PID 0; stack trace: ***
    @     0x7f657e5664df __pthread_once_slow
    @     0x7f6551e5fc7d (/home/shaoliu/anaconda3/envs/test/lib/python3.9/site-packages/pyceres.cpython-39-x86_64-linux-gnu.so+0x123c7c)
    @     0x7f657e569420 (/usr/lib/x86_64-linux-gnu/libpthread-2.31.so+0x1441f)
    @     0x7f6553fbc5e9 std::filesystem::__cxx11::path::_List::_Impl_deleter::operator()(std::filesystem::__cxx11::path::_List::_Impl*) const
    @     0x7f6553027046 std::filesystem::__cxx11::path::~path()
    @     0x7f6553c22bb4 colmap::ExistsFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    @     0x7f655346da03 colmap::Reconstruction::Read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    @     0x7f655307b718 (/home/shaoliu/anaconda3/envs/test/lib/python3.9/site-packages/pycolmap/_core.cpython-39-x86_64-linux-gnu.so+0x4d4717)
    @     0x7f6552e897e8 (/home/shaoliu/anaconda3/envs/test/lib/python3.9/site-packages/pycolmap/_core.cpython-39-x86_64-linux-gnu.so+0x2e27e7)
    @           0x507397 cfunction_call
    @           0x4f065c _PyObject_MakeTpCall
    @           0x505323 method_vectorcall
    @           0x502a82 slot_tp_init
    @           0x4f0b0a type_call
    @     0x7f6552e8723b (/home/shaoliu/anaconda3/envs/test/lib/python3.9/site-packages/pycolmap/_core.cpython-39-x86_64-linux-gnu.so+0x2e023a)
    @           0x4f065c _PyObject_MakeTpCall
    @           0x4ecb4d _PyEval_EvalFrameDefault
    @           0x4e69da _PyEval_EvalCode
    @           0x4e6667 _PyEval_EvalCodeWithName
    @           0x4e6619 PyEval_EvalCodeEx
    @           0x5938eb PyEval_EvalCode
    @           0x5c1157 run_eval_code_obj
    @           0x5bd170 run_mod
    @           0x456423 pyrun_file.cold
    @           0x5b6e52 PyRun_SimpleFileExFlags
    @           0x5b43ce Py_RunMain
    @           0x587999 Py_BytesMain
    @     0x7f657e22d083 __libc_start_main
    @           0x58784e (/home/shaoliu/anaconda3/envs/test/bin/python3.9+0x58784d)
Bus error (core dumped)

cc: @ahojnnes @sarlinpe

**Comment by ahojnnes** [comment]
Cannot reproduce under Mac 15.1:
```
Python 3.12.6 (main, Sep 13 2024, 21:04:31) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycolmap
>>> import os
>>> os.mkdir("tmp")
>>> pycolmap.Reconstruction()
Reconstruction(num_cameras=0, num_images=0, num_reg_images=0, num_points3D=0)
>>> a = pycolmap.Reconstruction()
>>> a.write("tmp")
>>> os.listdir("tmp")
['cameras.bin', 'images.bin', 'points3D.bin']
```

**Comment by B1ueber2y** [comment]
Did you build from wheels? The issue was reproduced in two different Ubuntu 20.04 machines

**Comment by ahojnnes** [comment]
I built from my machine locally. What do you mean by building from wheels? Do you mean installing the CI built wheels using pip?

**Comment by B1ueber2y** [comment]
Yes. pip install from pip wheels. Oh my description is confusing. Let me update it.

**Comment by ahojnnes** [comment]
Also works fine...
```
Python 3.12.6 (main, Sep 13 2024, 21:04:31) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycolmap
>>> import os
>>> pycolmap
<module 'pycolmap' from '/Users/jsch/.pyenv/versions/colmap/lib/python3.12/site-packages/pycolmap/__init__.py'>
>>> pycolmap.__version__
'3.11.0'
>>> import os
>>> os.mkdir("tmp")
>>> a = pycolmap.Reconstruction()
>>> a.write("tmp")
>>> os.listdir("tmp")
['cameras.bin', 'images.bin', 'points3D.bin']
```

**Comment by ahojnnes** [comment]
Agreed on the Python tests. We could for example run the incremental pipeline on a small synthetic scene. The scene synthesis functionality could be wrapped in pycolmap for this purpose.

Regarding linking against `stdc++fs`, it should theoretically already do that: `"$<$<AND:$<CXX_COMPILER_ID:GNU>,$<VERSION_LESS:$<CXX_COMPILER_VERSION>,9.0>>:-lstdc++fs>"`. This possibly doesn't work on the Python CI machines?
