### ISSUE TITLE
Question about convert ENU world coordianates into colmap format.

### ISSUE THREAD

**Issue by anonymouslosty** [colmap/colmap#2883]
I have some cameras positions like this and i try to convert them into quaternions and translations of colmap format. 
The  pos  in ENU coordinates and rotation are below. Images are taken by UAV.
![image](https://github.com/user-attachments/assets/8a74e4ea-cfcd-4b8c-b64b-0207dba47b19)

In the script below i convert  cameras positions and rotations above  to satisfy colmap images.txt format.
![image](https://github.com/user-attachments/assets/0978766d-d500-4f9f-a2ba-2e274fcf951f)

But when i use the scripts/python/visualize_model.py to visualize the cameras in world coordiantes with ENU points i read from a local ply, the outcome seems to be wrong. 
![image](https://github.com/user-attachments/assets/a1c88f1e-a9ba-4552-9a0e-f49c35b959c8)

Is there anything wrong with my conversions？I refered to the issue #434  but the convert still not work.
Please help,thanks a lot.

**Comment by anonymouslosty** [comment]
Should the conversion in image2 be like this?
![image](https://github.com/user-attachments/assets/103f9b53-bf9b-4ea0-af5e-10eae68b963a)
@ahojnnes  Hoping for your reply.

**Comment by ferreram** [comment]
Yes, in the first implementation of the write_new_file function you missed the inversion of the rotation matrix.  Your second implementation is correct (given that your euler_to_rotation_matrix function correctly reconstructs the rotation matrix from your euler angles).

**Comment by anonymouslosty** [comment]
> Yes, in the first implementation of the write_new_file function you missed the inversion of the rotation matrix. Your second implementation is correct (given that your euler_to_rotation_matrix function correctly reconstructs the rotation matrix from your euler angles).

Thank you for your reply. I will close this issue. Have a nice day :)
