### ISSUE TITLE
COLMAP from command line

### ISSUE THREAD

**Issue by JocelynQC** [colmap/colmap#289]
Hi @ahojnnes,

I was having the GPU freezes and timeouts during large-scale dense reconstruction. So I followed your instructions of running the stereo reconstruction from the command-line. However, whatever colmap command I run from terminal,  the GUI popped out, when the X window system is shut down I cannot launch colmap.

Is this normal? I mean the GUI popped out, and any suggestions of running large scale image set with 1 single Nvidia GTX 1070 8GB ?

Thank you so much

**Comment by ahojnnes** [comment]
can you run “colmap -h” and post the output here?

**Comment by JocelynQC** [comment]
Here:

COLMAP 3.3 (Commit Unkown on Unkown with CUDA)

Options can either be specified via command-line or by defining
them in a .ini project file passed to `--project_path`.

  -h [ --help ] 
  --project_path arg
  --log_to_stderr arg (=0)
  --log_level arg (=2)
  --database_path arg
  --image_path arg
  --ImageReader.camera_model arg (=SIMPLE_RADIAL)
  --ImageReader.single_camera arg (=0)
  --ImageReader.camera_params arg
  --ImageReader.default_focal_length_factor arg (=1.2)
  --SiftExtraction.num_threads arg (=-1)
  --SiftExtraction.use_gpu arg (=1)
  --SiftExtraction.gpu_index arg (=-1)
  --SiftExtraction.max_image_size arg (=3200)
  --SiftExtraction.max_num_features arg (=8192)
  --SiftExtraction.first_octave arg (=-1)
  --SiftExtraction.num_octaves arg (=4)
  --SiftExtraction.octave_resolution arg (=3)
  --SiftExtraction.peak_threshold arg (=0.0066666666666666671)
  --SiftExtraction.edge_threshold arg (=10)
  --SiftExtraction.estimate_affine_shape arg (=0)
  --SiftExtraction.max_num_orientations arg (=2)
  --SiftExtraction.upright arg (=0)
  --SiftExtraction.domain_size_pooling arg (=0)
  --SiftExtraction.dsp_min_scale arg (=0.16666666666666666)
  --SiftExtraction.dsp_max_scale arg (=3)
  --SiftExtraction.dsp_num_scales arg (=10)
  --SiftMatching.num_threads arg (=-1)
  --SiftMatching.use_gpu arg (=1)
  --SiftMatching.gpu_index arg (=-1)
  --SiftMatching.max_ratio arg (=0.80000000000000004)
  --SiftMatching.max_distance arg (=0.69999999999999996)
  --SiftMatching.cross_check arg (=1)
  --SiftMatching.max_error arg (=4)
  --SiftMatching.max_num_matches arg (=32768)
  --SiftMatching.confidence arg (=0.999)
  --SiftMatching.max_num_trials arg (=10000)
  --SiftMatching.min_inlier_ratio arg (=0.25)
  --SiftMatching.min_num_inliers arg (=15)
  --SiftMatching.multiple_models arg (=0)
  --SiftMatching.guided_matching arg (=0)
  --ExhaustiveMatching.block_size arg (=50)
  --SequentialMatching.overlap arg (=5)
  --SequentialMatching.quadratic_overlap arg (=1)
  --SequentialMatching.loop_detection arg (=0)
  --SequentialMatching.loop_detection_period arg (=10)
  --SequentialMatching.loop_detection_num_images arg (=30)
  --SequentialMatching.loop_detection_num_verifications arg (=0)
  --SequentialMatching.loop_detection_max_num_features arg (=-1)
  --SequentialMatching.vocab_tree_path arg
  --VocabTreeMatching.num_images arg (=100)
  --VocabTreeMatching.num_verifications arg (=0)
  --VocabTreeMatching.max_num_features arg (=-1)
  --VocabTreeMatching.vocab_tree_path arg
  --VocabTreeMatching.match_list_path arg
  --SpatialMatching.is_gps arg (=1)
  --SpatialMatching.ignore_z arg (=1)
  --SpatialMatching.max_num_neighbors arg (=50)
  --SpatialMatching.max_distance arg (=100)
  --TransitiveMatching.batch_size arg (=1000)
  --TransitiveMatching.num_iterations arg (=3)
  --BundleAdjustment.max_num_iterations arg (=100)
  --BundleAdjustment.max_linear_solver_iterations arg (=200)
  --BundleAdjustment.function_tolerance arg (=0)
  --BundleAdjustment.gradient_tolerance arg (=0)
  --BundleAdjustment.parameter_tolerance arg (=0)
  --BundleAdjustment.refine_focal_length arg (=1)
  --BundleAdjustment.refine_principal_point arg (=0)
  --BundleAdjustment.refine_extra_params arg (=1)
  --Mapper.min_num_matches arg (=15)
  --Mapper.ignore_watermarks arg (=0)
  --Mapper.multiple_models arg (=1)
  --Mapper.max_num_models arg (=50)
  --Mapper.max_model_overlap arg (=20)
  --Mapper.min_model_size arg (=10)
  --Mapper.init_image_id1 arg (=-1)
  --Mapper.init_image_id2 arg (=-1)
  --Mapper.init_num_trials arg (=200)
  --Mapper.extract_colors arg (=1)
  --Mapper.num_threads arg (=-1)
  --Mapper.min_focal_length_ratio arg (=0.10000000000000001)
  --Mapper.max_focal_length_ratio arg (=10)
  --Mapper.max_extra_param arg (=1)
  --Mapper.ba_refine_focal_length arg (=1)
  --Mapper.ba_refine_principal_point arg (=0)
  --Mapper.ba_refine_extra_params arg (=1)
  --Mapper.ba_local_num_images arg (=6)
  --Mapper.ba_local_max_num_iterations arg (=25)
  --Mapper.ba_global_use_pba arg (=1)
  --Mapper.ba_global_pba_gpu_index arg (=-1)
  --Mapper.ba_global_images_ratio arg (=1.1000000000000001)
  --Mapper.ba_global_points_ratio arg (=1.1000000000000001)
  --Mapper.ba_global_images_freq arg (=500)
  --Mapper.ba_global_points_freq arg (=250000)
  --Mapper.ba_global_max_num_iterations arg (=50)
  --Mapper.ba_global_max_refinements arg (=5)
  --Mapper.ba_global_max_refinement_change arg (=0.00050000000000000001)
  --Mapper.ba_local_max_refinements arg (=2)
  --Mapper.ba_local_max_refinement_change arg (=0.001)
  --Mapper.snapshot_path arg
  --Mapper.snapshot_images_freq arg (=0)
  --Mapper.init_min_num_inliers arg (=100)
  --Mapper.init_max_error arg (=4)
  --Mapper.init_max_forward_motion arg (=0.94999999999999996)
  --Mapper.init_min_tri_angle arg (=16)
  --Mapper.init_max_reg_trials arg (=2)
  --Mapper.abs_pose_max_error arg (=12)
  --Mapper.abs_pose_min_num_inliers arg (=30)
  --Mapper.abs_pose_min_inlier_ratio arg (=0.25)
  --Mapper.filter_max_reproj_error arg (=4)
  --Mapper.filter_min_tri_angle arg (=1.5)
  --Mapper.max_reg_trials arg (=3)
  --Mapper.tri_max_transitivity arg (=1)
  --Mapper.tri_create_max_angle_error arg (=2)
  --Mapper.tri_continue_max_angle_error arg (=2)
  --Mapper.tri_merge_max_reproj_error arg (=4)
  --Mapper.tri_complete_max_reproj_error arg (=4)
  --Mapper.tri_complete_max_transitivity arg (=5)
  --Mapper.tri_re_max_angle_error arg (=5)
  --Mapper.tri_re_min_ratio arg (=0.20000000000000001)
  --Mapper.tri_re_max_trials arg (=1)
  --Mapper.tri_min_angle arg (=1.5)
  --Mapper.tri_ignore_two_view_tracks arg (=1)
  --DenseStereo.max_image_size arg (=-1)
  --DenseStereo.gpu_index arg (=-1)
  --DenseStereo.window_radius arg (=5)
  --DenseStereo.sigma_spatial arg (=5)
  --DenseStereo.sigma_color arg (=0.20000000298023224)
  --DenseStereo.num_samples arg (=15)
  --DenseStereo.ncc_sigma arg (=0.60000002384185791)
  --DenseStereo.min_triangulation_angle arg (=1)
  --DenseStereo.incident_angle_sigma arg (=0.89999997615814209)
  --DenseStereo.num_iterations arg (=5)
  --DenseStereo.geom_consistency arg (=1)
  --DenseStereo.geom_consistency_regularizer arg (=0.30000001192092896)
  --DenseStereo.geom_consistency_max_cost arg (=3)
  --DenseStereo.filter arg (=1)
  --DenseStereo.filter_min_ncc arg (=0.10000000149011612)
  --DenseStereo.filter_min_triangulation_angle arg (=3)
  --DenseStereo.filter_min_num_consistent arg (=2)
  --DenseStereo.filter_geom_consistency_max_cost arg (=1)
  --DenseStereo.cache_size arg (=32)
  --DenseStereo.write_consistency_graph arg (=0)
  --DenseFusion.max_image_size arg (=-1)
  --DenseFusion.min_num_pixels arg (=5)
  --DenseFusion.max_num_pixels arg (=10000)
  --DenseFusion.max_traversal_depth arg (=100)
  --DenseFusion.max_reproj_error arg (=2)
  --DenseFusion.max_depth_error arg (=0.0099999997764825821)
  --DenseFusion.max_normal_error arg (=10)
  --DenseFusion.check_num_images arg (=50)
  --DenseFusion.cache_size arg (=32)
  --DenseMeshing.point_weight arg (=1)
  --DenseMeshing.depth arg (=13)
  --DenseMeshing.color arg (=32)
  --DenseMeshing.trim arg (=10)
  --DenseMeshing.num_threads arg (=-1)
  --Render.min_track_len arg (=3)
  --Render.max_error arg (=2)
  --Render.refresh_rate arg (=1)
  --Render.adapt_refresh_rate arg (=1)
  --Render.image_connections arg (=0)
  --Render.projection_type arg (=0)

**Comment by insikk** [comment]
`colmap` is for GUI binary, so it is meant for launching GUI window. 
You can use every step in separated module. You may want to refer `automatic_reconstructor -h`, `dense_stereo -h`, `dense_fuser -h`. They are command line tools. You can make your own pipeline with this. Example is [here](https://github.com/insikk/colmap/blob/tutorial/tutorial/image%20retrieval.ipynb). This example shows how to make own pipeline with given colmap moudles. I used python to execute separate command. You can use bash script instead. 

Also, source code is available. You can follow how these module works by looking into the source code. See `./src/exe/*.c`. At least `exe` source code is very readable. It is almost step-by-step guideline. 

One more thing for GPU freeze and timeout. I experienced it a while ago. I don't know exactly what was the problem. What I did was resize every image into max 1024px, so the program do not use huge image. Also I fixed image filetype to `jpg`. That means convert any other image type such as `.gif`, `.png`.

**Comment by JocelynQC** [comment]
@insikk 
Thank you very much for your information, this is really helpful, now I know what my mistake was.

**Comment by ahojnnes** [comment]
Closing this issue as resolved. Thanks @insikk for the answer.

**Comment by JocelynQC** [comment]
Hi,

I'm reopen this issue,  I've run a few experiments recently, and find that the GPU freeze and timeout happens easier when image size is big, for example 1000 560px by 370px images works fine, but 100 5616px by 3744px (which is provided gerrard-hall dataset) has the problem of:

QObject::~QObject: Timers cannot be stopped from another thread
*** Aborted at 1517428404 (unix time) try "date -d @1517428404" if you are using GNU date ***
PC: @     0x7f9d62ef830b QThreadStorageData::get()
*** SIGSEGV (@0x0) received by PID 19143 (TID 0x7f9d66400900) from PID 0; stack trace: ***
    @     0x7f9d649d7b20 (unknown)
    @     0x7f9d62ef830b QThreadStorageData::get()
    @     0x7f9d62ed08c8 QUnifiedTimer::instance()
    @     0x7f9d62ed0e2e QAnimationDriver::advanceAnimation()
    @     0x7f9d630e6bf4 QObject::event()
    @     0x7f9d63dbc28c QApplicationPrivate::notify_helper()
    @     0x7f9d63dc08ea QApplication::notify()
    @     0x7f9d630bbbe5 QCoreApplication::notifyInternal2()
    @     0x7f9d6310bafe QTimerInfoList::activateTimers()
    @     0x7f9d6310bec1 (unknown)
    @     0x7f9d59449134 g_main_context_dispatch
    @     0x7f9d59449388 (unknown)
    @     0x7f9d5944942c g_main_context_iteration
    @     0x7f9d6310c1ab QEventDispatcherGlib::processEvents()
    @     0x7f9d630b9bfb QEventLoop::exec()
    @     0x7f9d630c1ae6 QCoreApplication::exec()
    @           0x58e406 main
    @     0x7f9d5e3bd6d5 __libc_start_main
    @           0x595c99 _start
Segmentation fault (core dumped)

Is this a GPU freeze and timeout problem?

I don't get a answer from your paper and find this hard to believe.

Thank you.
