### ISSUE TITLE
Google logging still gets initialized twice when importing both pycolmap and pyceres built from source (3.10)

### ISSUE THREAD

**Issue by michael-hoss** [colmap/colmap#2895]
**Describe the bug**

I still experienced the double initialization issue of glog in pycolmap 3.10 with pyceres 2.2. 

A previous fix of this got merged before and is part of 3.10 https://github.com/colmap/colmap/pull/2405. 

**To Reproduce**

1. Install all of the following from source in the given order (after your hint in https://github.com/colmap/colmap/pull/2869)
- ceres 2.2.0
- pyceres 2.2
- colmap 3.10
- pycolmap 3.10 

Then, start a python 3.10 interpreter and run:

```python
import pyceres
import pycolmap  # here, it crashes with the following error message
```

```
F1106 14:55:50.527757  6890 utilities.cc:346] Check failed: !IsGoogleLoggingInitialized() You called InitGoogleLogging() twice!
*** Check failure stack trace: ***

ERROR: C++ code terminated. Kernel Died. See log files for details.

```

When I import pycolmap first, and then pyceres, it crashes with a very similar error.

Note that when I previously had ceres installed from apt and pyceres installed from pip, it worked fine. 

**Expected behavior**

Should only initialize glog once.

**Screenshots**
If applicable, add screenshots to help explain your problem. Input images and/or output reconstructions are usually helpful.

**Environment:**
 - OS: Ubuntu 22.04
 - COLMAP Version 3.10
 - Capture Device [e.g. iPhone X]

Edit:  Just checked also glog versions. I have 0.5.0:
```
libgoogle-glog-dev/jammy,now 0.5.0+really0.4.0-2 amd64 [installed]
libgoogle-glog0v5/jammy,now 0.5.0+really0.4.0-2 amd64 [installed,automatic]
```
Then, again read the description of the other PR:
> Add a fix for glog >=0.6.0. There exists a (hacky) workaround for 0.4.0 but not for 0.5.0.
This PR also adds support for glog 0.7.0

I guess I just got unlucky here with 0.5.0.

**Comment by sarlinpe** [comment]
Which version of glog is used in the build? This should be logged in the cmake step. As mentioned in https://github.com/colmap/colmap/pull/2405, the fix only works for glog >= 0.6 since previous versions do not offer any way of checking whether glog was already initialized.

**Comment by michael-hoss** [comment]
Thanks for your quick reply. Indeed, just added to the issue description that I have 0.5.0. Will make sure to upgrade that :+1:

**Comment by sarlinpe** [comment]
On a second thought, we could make this work for other versions by checking whether pyceres/pycolmap was already imported, e.g. with `py::module_::import("sys").attr("modules").contains("pyceres")` or so.

**Comment by michael-hoss** [comment]
Sounds good! Would import order then matter? If I import pycolmap first, and then pyceres (which is counterintuitive, though), it would still crash as long as pyceres doesn't have this check built in?

**Comment by sarlinpe** [comment]
The same check is implemented in both, so we would need to update both.
