### ISSUE TITLE
Dense-Stereo Crash

### ISSUE THREAD

**Issue by jlpoolen** [colmap/colmap#291]
I created a screen video leading up to a repeatable incident where Colmap, during dense stereo analysis, crashes.   My computer is running Win7, has 25GB ram, and 12 CPUs.  when the crash occurs, there's plenty of available memory and the CPUs are not overloaded.  The System Manager is display to demonstrate the load on the system during this event.

https://youtu.be/_OG7BT-DUIc

Are there any written logs or something I should include which might shed some light on this?

**Comment by jlpoolen** [comment]
Here are the contents of the project's ini file:
> log_to_stderr=false
> log_level=2
> database_path=D:/test3/t1/201801301832.db
> image_path=D:/test3/img/201801301832
> [ImageReader]
> single_camera=false
> default_focal_length_factor=1.2
> camera_model=SIMPLE_RADIAL
> camera_params=
> [SiftExtraction]
> use_gpu=true
> estimate_affine_shape=false
> upright=false
> domain_size_pooling=false
> num_threads=-1
> max_image_size=3200
> max_num_features=8192
> first_octave=-1
> num_octaves=4
> octave_resolution=3
> max_num_orientations=2
> dsp_num_scales=10
> peak_threshold=0.0066699999999999997
> edge_threshold=10
> dsp_min_scale=0.16667000000000001
> dsp_max_scale=3
> gpu_index=-1
> [SiftMatching]
> use_gpu=true
> cross_check=true
> multiple_models=false
> guided_matching=false
> num_threads=-1
> max_num_matches=32768
> max_num_trials=10000
> min_num_inliers=15
> max_ratio=0.80000000000000004
> max_distance=0.69999999999999996
> max_error=4
> confidence=0.999
> min_inlier_ratio=0.25
> gpu_index=-1
> [SequentialMatching]
> quadratic_overlap=true
> loop_detection=false
> overlap=5
> loop_detection_period=10
> loop_detection_num_images=30
> loop_detection_num_verifications=0
> loop_detection_max_num_features=-1
> vocab_tree_path=
> [SpatialMatching]
> is_gps=true
> ignore_z=true
> max_num_neighbors=50
> max_distance=100
> [BundleAdjustment]
> refine_focal_length=true
> refine_principal_point=false
> refine_extra_params=true
> max_num_iterations=100
> max_linear_solver_iterations=200
> function_tolerance=0
> gradient_tolerance=0
> parameter_tolerance=0
> [Mapper]
> ignore_watermarks=false
> multiple_models=true
> extract_colors=true
> ba_refine_focal_length=true
> ba_refine_principal_point=false
> ba_refine_extra_params=true
> ba_global_use_pba=true
> tri_ignore_two_view_tracks=true
> min_num_matches=15
> max_num_models=50
> max_model_overlap=20
> min_model_size=10
> init_image_id1=-1
> init_image_id2=-1
> init_num_trials=200
> num_threads=-1
> ba_local_num_images=6
> ba_local_max_num_iterations=25
> ba_global_pba_gpu_index=-1
> ba_global_images_freq=500
> ba_global_points_freq=250000
> ba_global_max_num_iterations=50
> ba_global_max_refinements=5
> ba_local_max_refinements=2
> snapshot_images_freq=0
> init_min_num_inliers=100
> init_max_reg_trials=2
> abs_pose_min_num_inliers=30
> max_reg_trials=3
> tri_max_transitivity=1
> tri_complete_max_transitivity=5
> tri_re_max_trials=1
> min_focal_length_ratio=0.10000000000000001
> max_focal_length_ratio=10
> max_extra_param=1
> ba_global_images_ratio=1.1000000000000001
> ba_global_points_ratio=1.1000000000000001
> ba_global_max_refinement_change=0.00050000000000000001
> ba_local_max_refinement_change=0.001
> init_max_error=4
> init_max_forward_motion=0.94999999999999996
> init_min_tri_angle=16
> abs_pose_max_error=12
> abs_pose_min_inlier_ratio=0.25
> filter_max_reproj_error=4
> filter_min_tri_angle=1.5
> tri_create_max_angle_error=2
> tri_continue_max_angle_error=2
> tri_merge_max_reproj_error=4
> tri_complete_max_reproj_error=4
> tri_re_max_angle_error=5
> tri_re_min_ratio=0.20000000000000001
> tri_min_angle=1.5
> snapshot_path=
> [DenseStereo]
> geom_consistency=true
> filter=true
> write_consistency_graph=false
> max_image_size=2000
> window_radius=5
> window_step=1
> num_samples=15
> num_iterations=5
> filter_min_num_consistent=2
> depth_min=-1
> depth_max=-1
> sigma_spatial=-1
> sigma_color=0.20000000298023224
> ncc_sigma=0.60000002384185791
> min_triangulation_angle=1
> incident_angle_sigma=0.89999997615814209
> geom_consistency_regularizer=0.30000001192092896
> geom_consistency_max_cost=3
> filter_min_ncc=0.10000000149011612
> filter_min_triangulation_angle=3
> filter_geom_consistency_max_cost=1
> cache_size=32
> gpu_index=-1
> [Render]
> adapt_refresh_rate=true
> image_connections=false
> min_track_len=3
> refresh_rate=1
> projection_type=0
> max_error=2
> [ExhaustiveMatching]
> block_size=50
> [VocabTreeMatching]
> num_images=100
> num_verifications=0
> max_num_features=-1
> vocab_tree_path=
> match_list_path=
> [TransitiveMatching]
> batch_size=1000
> num_iterations=3
> [DenseFusion]
> max_image_size=-1
> min_num_pixels=5
> max_num_pixels=10000
> max_traversal_depth=100
> check_num_images=50
> max_reproj_error=2
> max_depth_error=0.0099999997764825821
> max_normal_error=10
> cache_size=32
> [DenseMeshing]
> depth=13
> num_threads=-1
> point_weight=1
> color=32
> trim=10
>

**Comment by jlpoolen** [comment]
Per the recommendations under "Reduce memory usage during dense reconstruction" under the FAQ, I changed the Dense Stereo->max_image_size=1600 from 2000 and was able to get the last several images processed via stereo.  If I tried stereo after the completion, the crash would occur.  I was able to move onto the next steps: Fusion and Mesh.

**Comment by ahojnnes** [comment]
Have you looked into this: https://colmap.github.io/faq.html#fix-gpu-freezes-and-timeouts-during-dense-reconstruction

**Comment by jlpoolen** [comment]
Yes, I had seen that.  Earlier I had what looked to be problems regarding the timeout for the graphics card, I'd get some warning dialog box or something alerted me there had been a problem.  So I installed NVidia's Nsight and set my timeout to 40.  The value of 40 was in effect during the screen video capture.

![nsight monitor_2018-01-31_04-56-22](https://user-images.githubusercontent.com/227313/35624525-1951b1a0-0644-11e8-9e57-18430ad311de.png)

Your suggestions is to use a longer delay, say, 120?  From your experience with this, what might be the maximum time value to use?

**Comment by jlpoolen** [comment]
Also, I looked into the Registry and could not key named TdrLevel: 
![regedit_2018-01-31_05-10-32](https://user-images.githubusercontent.com/227313/35625065-cf4f301c-0645-11e8-93fe-d0a84b2a6827.png)

Here's my Registry showing the key TdrDelay:
![regedit_2018-01-31_05-11-43](https://user-images.githubusercontent.com/227313/35625080-de1109e0-0645-11e8-93ae-f1a627afc1bf.png)

And Windows PowerShell listing:

> PS C:\Users\jlpoole>  Get-ItemProperty -Path Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrive
> rs
> 
> 
> PSPath         : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDriver
>                  s
> PSParentPath   : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control
> PSChildName    : GraphicsDrivers
> PSProvider     : Microsoft.PowerShell.Core\Registry
> DxgKrnlVersion : 8197
> TdrDelay       : 40
> 
> 
> 
> PS C:\Users\jlpoole>

**Comment by ahojnnes** [comment]
Just add the key, if it does not exist. See https://colmap.github.io/faq.html#fix-gpu-freezes-and-timeouts-during-dense-reconstruction for Powershell commands that automatically set the keys.

**Comment by ahojnnes** [comment]
Don't forget to restart your machine./

**Comment by ahojnnes** [comment]
@Riverhe2014 Most likely because your GPU does not have enough memory. Just set a max_image_size to a smaller value.
