### ISSUE TITLE
Unexpected behavior of (Rig) Bundle Adjustment with PosePrior-mapper 

### ISSUE THREAD

**Issue by mangoschorle** [colmap/colmap#2912]
I have a camera rig with two cameras and I am reconstructing my model with known prior poses (3D positions for one of the cameras).
After the mapper I am using bundle adjustment and rig bundle adjustment, as my hope is that this improves the model.

However, i read in [this comment](https://github.com/colmap/colmap/issues/694#issuecomment-1679697442) by @tsattler that bundle adjustment  normalizes scale.

Therefore, I would expect that my procedure would purge the scale information of the model. However, it does not. Bundle adjustment and rig bundle adjustment are (to my luck but against my intuition) not affecting the scale.

Why is it that (rig) bundle adjustment doesn't normalize the scale of the model? 
And as a followup: What is the correct procedure if I want to:

1. Obtain a model of with real-world scale
2. Optimize it without purging scale information
3. Induce the constraint of a fixed camera rig without purging scale information

This is my attempt:

```shell
colmap pose_prior_mapper --image_path rig --database_path {database_path} --output_path model_sfm --Mapper.multiple_models 0 --Mapper.ba_refine_focal_length 0 --Mapper.ba_refine_extra_params 0 --overwrite_priors_covariance 1 --prior_position_std_x 0.05 --prior_position_std_y 0.05 --prior_position_std_z 0.01"

colmap bundle_adjuster --input_path model_sfm --output_path model_sfm --BundleAdjustment.refine_focal_length 0 --BundleAdjustment.refine_principal_point 0 --BundleAdjustment.refine_extra_params 0

colmap rig_bundle_adjuster --input_path model_sfm --output_path model_sfm --rig_config_path config.json --BundleAdjustment.refine_focal_length 0 --BundleAdjustment.refine_principal_point 0 --BundleAdjustment.refine_extra_params 0
```

**Comment by ahojnnes** [comment]
Only the pose prior mapper performs a normalization of the scene during the optimization, but you should not be able to observe it directly as a user, because the scene is "de-normalized" before returning back to the user. Default and rig bundle adjustment do not normalize the scene. The normalization of the scene is implemented in the "mapper". I hope this helps.

**Comment by mangoschorle** [comment]
It does help indeed!
