### ISSUE TITLE
Backprojection from a point cloud

### ISSUE THREAD

**Issue by Parmisian** [colmap/colmap#2914]
Hello,

I am trying to align the point cloud I get from colmap with a lidar point cloud (acting as the ground truth point cloud). After the alignment, I need to somehow change the images.txt and point3d.txt files so that the aligned point cloud and the corresponding camera poses are correct. Instead of getting into nitty gritty of the text files with python scripts, I was wondering if there is a way for me to backproject the 3d points in the cloud to camera poses, so that the the text files are created automatically and I can export them. Hope I was able to explain it properly :D
Thanks

**Comment by ahojnnes** [comment]
You can write a short pycolmap script to do this (untested but to give an idea)
```
import pycolmap
reconstruction = pycolmap.Reconstruction(input_path)
new_from_old = pycolmap.Sim3d()
new_from_old.scale = 1.23
new_from_old.rotation = ...
new_from_old.translation = ...
reconstruction.transform(new_from_old)
reconstruction.write(output_path)
```

**Comment by Parmisian** [comment]
Cool, I will give it a try, thanks!

**Comment by Parmisian** [comment]
Sorry for reopening, I just wanted to ask if the transform function is accounting for the fact that we have quaternions in the images.txt file and inverting them properly to rotation matrices for me to use?

**Comment by Parmisian** [comment]
Checked the documentation now, the rotation isin quaternion format👍

**Comment by ahojnnes** [comment]
Yes, this is right. Alternatively, with the above sample script, you can do something like:
```
for image in reconstruction.images.values():
    print(image.cam_from_world.matrix())
```

**Comment by LukasPoque** [comment]
@Parmisian this sounds like a cool project :) Can you share more about your idea and if it worked well? Have you used the image point cloud to improve the lidar point cloud (to get it denser), or have you only used it to find the transformation between images/lidar?
