### ISSUE TITLE
 image_undistorter does not update points2D in sparse reconstruction

### ISSUE THREAD

**Issue by xiemeilong** [colmap/colmap#2917]
**Describe the bug**
After using the image_undistorter tool in COLMAP to undistort images and generate a new sparse reconstruction, the 2D point coordinates (points2D) in the resulting sparse model remain the original distorted pixel coordinates instead of being transformed to the undistorted image coordinates. Previously, the image_undistorter correctly updated these 2D point coordinates.

**To Reproduce**
just run `colmap image_undistorter ... --max_image_size 1600`

**Expected behavior**
The points2D coordinates in the new sparse reconstruction generated by image_undistorter should reflect the undistorted pixel locations of the corresponding features. 

**Environment:**
 - OS: ubuntu 24.04
 - COLMAP Version: main branch

**Comment by sarlinpe** [comment]
Thank you for reporting this issue. Did this occur with previous versions? when did this stop working correctly?

**Comment by xiemeilong** [comment]
The last time it was correct was August 4th. The points2D have been wrong since August 17th. However, I don't remember which version I updated from at that time. I'm currently using the main branch.

**Comment by xiemeilong** [comment]
The camera model is opencv， I ran the image_undistorter with `--max_image_size 1600`.

**Comment by B1ueber2y** [comment]
Thanks. I gave some tests and everything works normal in my side. Would you mind to give more details, or if applicable, a test script to reproduce. Or could you provide some logs to help reproduce the issue? Also, given that you said "remain the original distorted pixel", i guess max_image_size does not matter in your case?

**Comment by B1ueber2y** [comment]
> Because the photos I used have very little distortion, I rely mainly on the resolution to judge if the points2d have been converted.
> 
> The photos resized from 5568  to 1600.  This issue can be reproduced on all my three computers.  One ubuntu 22.04 , two ubuntu 24.04. All is the main branch.
> 
> 
> 
> ```
> 
> colmap image_undistorter --input_path distorted/sparse/0 --image_path input --output_path test/ --output_type COLMAP --max_image_size 1600
> 
> ```

And what was the issue? your point2ds were not downsized? This works fine for me with resizing. Could you upload somewhere the reconstruction model before undistortion?

**Comment by ahojnnes** [comment]
> Because the photos I used have very little distortion, I rely mainly on the resolution to judge if the points2d have been converted. The photos resized from 5568 to 1600. This issue can be reproduced on all my three computers. One ubuntu 22.04 , two ubuntu 24.04. All is the main branch.
> 
> ```
> colmap image_undistorter --input_path distorted/sparse/0 --image_path input --output_path test/ --output_type COLMAP --max_image_size 1600
> ```

Are you sure that you are on the latest commit from the main branch? There may have been some fixes in the recent past (in particular on the copy/move constructor of the reconstruction) that fix the issue.

**Comment by xiemeilong** [comment]
@ahojnnes Thanks for reminding me. I pulled the code again and recompiled, and it's working now. I didn't see any issues or fixes about it at first, and since I recalled updating my code recently (though apparently not recently enough),  so I didn't recompile. I didn't realize this was already fixed in a recent commit. Sorry about that. @B1ueber2y
