### ISSUE TITLE
Failed to load libEGL

### ISSUE THREAD

**Issue by zjuzly** [colmap/colmap#292]
The colmap launcher crashed when I run COLMAP.bat, and I get the following error
![image](https://user-images.githubusercontent.com/13957141/35609788-c60eb780-0699-11e8-96c1-5bda0264ae8b.png)

I have placed libEGL.dll and opengl32sw.dll file  into lib directory, but the error remains. Sorry about a stupid problem

**Comment by ahojnnes** [comment]
Are you new to COLMAP or is this a problem with the recent 3.4 version?

**Comment by zjuzly** [comment]
Well, I've been using it for a while. It' OK on my computer and occurs on another with 3.4 version

**Comment by ahojnnes** [comment]
Does it work with 3.3 on the other computer?

**Comment by zjuzly** [comment]
Unfortunately, the error remains
![image](https://user-images.githubusercontent.com/13957141/35621558-b23e9d4e-06bf-11e8-975e-bfab2f2f8239.png)

**Comment by zjuzly** [comment]
The 2.1 version also crashed and report the same information, so I guess it's not about version

**Comment by zjuzly** [comment]
Sorry about that, the problem occurs just when remote operation. So stupid!

**Comment by ZJL-0422** [comment]
你好，请问您还记得这个问题如何解决吗？我在把COLMAP-3.6-windows-cuda拷贝到一个无法联网的电脑时也遇到了同样的问题。
