### ISSUE TITLE
SIFT affine shape estimation breaks rotation invariance

### ISSUE THREAD

**Issue by tom-bola** [colmap/colmap#2928]
I noticed that `--SiftExtraction.estimate_affine_shape 1` yields massively fewer two-view geometries, and thus results in poor reconstructions, when input images have mixed rotations (e.g. portrait, landscape, upside-down). I can reproduce the issue on a subset of the _south-building_ dataset. 

As a baseline I compared against the results without affine shape estimation. To make the results comparable I was using one camera per image (`--camera_mode 3`).

These are the results without affine shape estimation:

<img width="591" alt="image" src="https://github.com/user-attachments/assets/48223d04-71bf-4b60-b70e-623d175051f4">

And with affine shape estimation:

<img width="591" alt="image" src="https://github.com/user-attachments/assets/f141d83b-629c-486c-90c8-9f0a67a1d1c8">

I attached the images+script that I used to create the results.

[AffineTest.zip](https://github.com/user-attachments/files/17846710/AffineTest.zip)

**Comment by ahojnnes** [comment]
Thanks for reporting the issue. Just to double confirm: `--camera_mode` is not an existing option in colmap and should be rejected with an error. Are you using some custom-compiled version of colmap?

**Comment by tom-bola** [comment]
@ahojnnes curious, did this mean that previously affine shape estimation disregarded orientation (basically implied `--SiftExtraction.upright 1`)?
