### ISSUE TITLE
repetitive keypoints in .key file

### ISSUE THREAD

**Issue by logmove** [colmap/colmap#293]
Hi,
I am using colmap to obtain the feature matching for a set of images. I used export_to_bundler.py to transform the .db file to readable file. 

The problem is that I found in the generated .key file, there are some keypoints that have different feature geometry parameters but the same coordinate.  I attach an example from  a .key file below,

![image](https://user-images.githubusercontent.com/29305317/35626355-74e8c332-06d0-11e8-8932-123612fddc53.png)

The corresponding code is below.
for r in range(keypoints.shape[0]):
           fid.write("%f %f %f %f\n" % (keypoints[r, 1], keypoints[r, 0],
                            keypoints[r, 2], keypoints[r, `3])).

My question is, are these identical coordinates a bug?  Should I manually merge them regardless of their difference in feature geometry? Any assistance is highly  appreciated.

**Comment by ahojnnes** [comment]
COLMAP detects multiple orientations per keypoint by default. If this is a problem for your application, please set ``SiftExtraction.max_num_orientations`` to 1.
