### ISSUE TITLE
Compilation failure on CentOS 7.4

### ISSUE THREAD

**Issue by seerdecker** [colmap/colmap#294]
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   regex
--   system
--   unit_test_framework
-- Found Eigen3
--   Includes : /usr/include/eigen3
-- Found FreeImage
--   Includes : /usr/include
--   Libraries : /usr/lib64/libfreeimage.so
-- Found Glog
--   Includes : /usr/include
--   Libraries : /usr/lib64/libglog.so
-- Found required Ceres dependency: Eigen version 3.2.5 in /usr/include/eigen3
-- Found required Ceres dependency: Glog in /usr/include
-- Found Ceres version: 1.11.0 installed in: /usr
-- Found Glew
--   Includes : /usr/include
--   Libraries : /usr/lib64/libGLEW.so
-- Found Qt 5.6.2
-- Build type not specified, using Release
-- Enabling OpenMP support
-- Disabling interprocedural optimization
-- Autodetected CUDA architecture(s): 6.1 
-- Enabling CUDA support (version: 8.0, archs: sm_61)
-- Enabling OpenGL support
-- Disabling profiling support
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lb01/repos/colmap/build
[  0%] Building CXX object src/base/CMakeFiles/base.dir/camera_rig.cc.o
In file included from /usr/include/c++/4.8.2/unordered_map:47:0,
                 from /home/lb01/repos/colmap/src/./base/camera_rig.h:20,
                 from /home/lb01/repos/colmap/src/base/camera_rig.cc:17:
/usr/include/c++/4.8.2/bits/hashtable.h: In instantiation of ‘std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::__node_type* std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::_M_allocate_node(_Args&& ...) [with _Args = {const std::piecewise_construct_t&, std::tuple<unsigned int&&>, std::tuple<>}; _Key = unsigned int; _Value = std::pair<const unsigned int, std::vector<Eigen::Matrix<double, 4, 1>, std::allocator<Eigen::Matrix<double, 4, 1> > > >; _Alloc = Eigen::aligned_allocator<std::pair<const unsigned int, std::vector<Eigen::Matrix<double, 4, 1>, std::allocator<Eigen::Matrix<double, 4, 1> > > > >; _ExtractKey = std::__detail::_Select1st; _Equal = std::equal_to<unsigned int>; _H1 = std::hash<unsigned int>; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<false, false, true>; std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::__node_type = std::__detail::_Hash_node<std::pair<const unsigned int, std::vector<Eigen::Matrix<double, 4, 1>, std::allocator<Eigen::Matrix<double, 4, 1> > > >, false>]’:
/usr/include/c++/4.8.2/bits/hashtable_policy.h:519:8:   required from ‘std::__detail::_Map_base<_Key, _Pair, _Alloc, std::__detail::_Select1st, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits, true>::mapped_type& std::__detail::_Map_base<_Key, _Pair, _Alloc, std::__detail::_Select1st, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits, true>::operator[](std::__detail::_Map_base<_Key, _Pair, _Alloc, std::__detail::_Select1st, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits, true>::key_type&&) [with _Key = unsigned int; _Pair = std::pair<const unsigned int, std::vector<Eigen::Matrix<double, 4, 1>, std::allocator<Eigen::Matrix<double, 4, 1> > > >; _Alloc = Eigen::aligned_allocator<std::pair<const unsigned int, std::vector<Eigen::Matrix<double, 4, 1>, std::allocator<Eigen::Matrix<double, 4, 1> > > > >; _Equal = std::equal_to<unsigned int>; _H1 = std::hash<unsigned int>; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<false, false, true>; std::__detail::_Map_base<_Key, _Pair, _Alloc, std::__detail::_Select1st, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits, true>::mapped_type = std::vector<Eigen::Matrix<double, 4, 1>, std::allocator<Eigen::Matrix<double, 4, 1> > >; std::__detail::_Map_base<_Key, _Pair, _Alloc, std::__detail::_Select1st, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits, true>::key_type = unsigned int]’
/usr/include/c++/4.8.2/bits/unordered_map.h:600:20:   required from ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::mapped_type& std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::operator[](std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_type&&) [with _Key = unsigned int; _Tp = std::vector<Eigen::Matrix<double, 4, 1>, std::allocator<Eigen::Matrix<double, 4, 1> > >; _Hash = std::hash<unsigned int>; _Pred = std::equal_to<unsigned int>; _Alloc = Eigen::aligned_allocator<std::pair<const unsigned int, std::vector<Eigen::Matrix<double, 4, 1>, std::allocator<Eigen::Matrix<double, 4, 1> > > > >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::mapped_type = std::vector<Eigen::Matrix<double, 4, 1>, std::allocator<Eigen::Matrix<double, 4, 1> > >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_type = unsigned int]’
/home/lb01/repos/colmap/src/base/camera_rig.cc:184:35:   required from here
/usr/include/c++/4.8.2/bits/hashtable.h:727:6: error: no matching function for call to ‘Eigen::aligned_allocator<std::__detail::_Hash_node<std::pair<const unsigned int, std::vector<Eigen::Matrix<double, 4, 1>, std::allocator<Eigen::Matrix<double, 4, 1> > > >, false> >::construct(std::_Hashtable<unsigned int, std::pair<const unsigned int, std::vector<Eigen::Matrix<double, 4, 1>, std::allocator<Eigen::Matrix<double, 4, 1> > > >, Eigen::aligned_allocator<std::pair<const unsigned int, std::vector<Eigen::Matrix<double, 4, 1>, std::allocator<Eigen::Matrix<double, 4, 1> > > > >, std::__detail::_Select1st, std::equal_to<unsigned int>, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::__node_type*&, const std::piecewise_construct_t&, std::tuple<unsigned int&&>, std::tuple<>)’
      _M_node_allocator().construct(__n, std::forward<_Args>(__args)...);

Compiling under Linux is hell. Any possibility of having a pre-compiled binary? Thanks!

**Comment by ahojnnes** [comment]
Maybe @insikk can chime in here, since it seems he/she compiled COLMAP successfully on CentOS 7, see https://github.com/colmap/colmap/pull/290

**Comment by insikk** [comment]
Here is my cmake output on CentOS 7. I was able to compile Colmap by following instruction step by step. You can compare the output with yours. 
I think your cmake output is somehow different from mine. 

I suggest you to do follow things in order: 
* Install Eigen 3.3.4. Version matters. 
* Install Ceres 1.13.0. Version matters. 
* Install Colmap from master branch. 

Please keep the version as stated. Once you success on installation, you can experiment with other versions. 

```
$ cmake .. -DBOOST_STATIC=OFF
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Performing Test HAS_SSE_EXTENSION
-- Performing Test HAS_SSE_EXTENSION - Success
-- Performing Test HAS_SSE2_EXTENSION
-- Performing Test HAS_SSE2_EXTENSION - Success
-- Performing Test HAS_SSE3_EXTENSION
-- Performing Test HAS_SSE3_EXTENSION - Success
-- Performing Test HAS_SSE41_EXTENSION
-- Performing Test HAS_SSE41_EXTENSION - Success
-- Performing Test HAS_SSE42_EXTENSION
-- Performing Test HAS_SSE42_EXTENSION - Success
-- Performing Test HAS_AVX_EXTENSION
-- Performing Test HAS_AVX_EXTENSION - Success
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   regex
--   system
--   unit_test_framework
-- Found Eigen3: /usr/local/include/eigen3 (Required is at least version "2.91.0") 
-- Found Eigen3
--   Includes : /usr/local/include/eigen3
-- Found FreeImage
--   Includes : /usr/include
--   Libraries : /usr/lib/libfreeimage.so
-- Found Glog
--   Includes : /usr/include
--   Libraries : /usr/lib64/libglog.so
-- Found installed version of Eigen: /usr/local/share/eigen3/cmake
-- Found required Ceres dependency: Eigen version 3.3.4 in /usr/local/include/eigen3
-- Found required Ceres dependency: glog
-- Found installed version of gflags: /usr/lib64/cmake/gflags
-- Detected broken gflags install in: /usr/lib64/cmake/gflags, version: 2.1.1 <= 2.1.2 which defines gflags_LIBRARIES = gflags which is not an imported CMake target, see: https://github.com/gflags/gflags/issues/110.  Attempting to fix by detecting correct gflags target.
-- Found valid gflags target: gflags-shared, updating gflags_LIBRARIES.
-- Detected gflags version: 2.1.1
-- Found required Ceres dependency: gflags
-- Found Ceres version: 1.13.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SchurSpecializations, OpenMP, Multithreading]
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Found OpenGL: /usr/lib64/libGL.so  
-- Found Glew
--   Includes : /usr/include
--   Libraries : /usr/lib64/libGLEW.so
-- Found Git: /usr/bin/git (found version "1.8.3.1") 
-- Found Qt 5.6.2
-- Build type not specified, using Release
-- Enabling OpenMP support
-- Disabling interprocedural optimization
-- Autodetected CUDA architecture(s): 6.1 6.1 6.1 6.1 6.1 6.1 6.1 6.1 
-- Enabling CUDA support (version: 8.0, archs: sm_61)
-- Enabling OpenGL support
-- Disabling profiling support
-- Configuring done
-- Generating done
```

**Comment by seerdecker** [comment]
Thanks for the fast feedback!

Setting the right versions for eigen and ceres did help. I also had to upgrade FreeImage from 3.10 (system) to 3.17, and update boost to 1.66.

In other words, compilation fails if one uses the CentOS packages to compile Colmap.

Thanks for the help!
