### ISSUE TITLE
Xcode 9.2+CUDA 9.1 compilation error (with fix)

### ISSUE THREAD

**Issue by mabrowning** [colmap/colmap#296]
With Xcode 9.2 and CUDA 9.1 on macOS:

```
$ clang --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
$ /usr/local/cuda/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Tue_Dec_19_21:36:29_CST_2017
Cuda compilation tools, release 9.1, V9.1.128
```

`src/mvs/CMakeLists.txt:52` has `set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} --default-stream per-thread")`, which is causing the following compiler error:

```
colmap/src/./mvs/cuda_flip.h:45:19: error: no member named 'cudaLaunchKernel' in the global namespace
output_pitch) { ::cudaLaunchKernel(0, 0, 0, 0, 0, 0);}
```

I dug into it, and nvcc creates 2 (or more) copies of the code from the `.cu` file. On the post-processed host version (.cpp), setting the `--default-stream per-thread` causes all of the CUDA runtime api to have `_ptsz` appended to their function names and definitions. However, the expansion/callsite is not updated, staying at `::cudaLaunchKernel`. This seems like a nvcc bug.

Deleting that compiler flag results in a successful build, but I don't know the implications at runtime.

**Comment by mabrowning** [comment]
It is due to templated kernels & default-stream per-thread:

`template_fail.cu`:

```
#ifdef TEMPLATE
template<typename T>
__global__ void CudaTestKernel(T* output_data, const T* input_data,
#else
__global__ void CudaTestKernel(float* output_data, const float* input_data,
#endif

                                 const int width, const int height,
                                 const int input_pitch,
                                 const int output_pitch) {

  int input_x = blockDim.x * blockIdx.x + threadIdx.x;
  int input_y = blockDim.y * blockIdx.y + threadIdx.y;

  if (input_x >= width || input_y >= height) {
    return;
  }

  int output_x = input_y;
  int output_y = width - 1 - input_x;

  output_data[output_y * output_pitch + output_x] =
      input_data[input_y * input_pitch + input_x];
}

void CudaTest(const float* input, float* output, const int width, const int height,
                const int pitch_input, const int pitch_output) {
  dim3 block_dim(32, 1, 1);
  dim3 grid_dim;
  grid_dim.x = (width - 1) / 32 + 1;
  grid_dim.y = height;

  CudaTestKernel<<<grid_dim, block_dim>>>(
      output, input, width, height, pitch_input / sizeof(float),
      pitch_output / sizeof(float));
}
```

`nvcc  -c template_fail.cu`: success
`nvcc  -c template_fail.cu -DTEMPLATE`: success
`nvcc  -c template_fail.cu --default-stream per-thread`: success
`nvcc  -c template_fail.cu -DTEMPLATE --default-stream per-thread`:  FAILURE:

```
template_fail.cu:11:19: error: no member named 'cudaLaunchKernel' in the global namespace
output_pitch) { ::cudaLaunchKernel(0, 0, 0, 0, 0, 0);}
                ~~^
```

**Comment by ahojnnes** [comment]
Thanks for investigating. This seems to be a bug in NVCC. Can you try whether setting the template parameter explicitly from the caller fixes the issue?

**Comment by mabrowning** [comment]
Good idea! Unfortunately, explicit template parameterization still fails.

**Comment by mabrowning** [comment]
Template specialization does help!

`template_success.cu`:

```
template<typename T>
__global__ void CudaTestKernel(T* output_data, const T* input_data,
                                 const int width, const int height,
                                 const int input_pitch,
                                 const int output_pitch);
template <>
__global__ void CudaTestKernel<float>(float* output_data, const float* input_data,
                                 const int width, const int height,
                                 const int input_pitch,
                                 const int output_pitch) {

  int input_x = blockDim.x * blockIdx.x + threadIdx.x;
  int input_y = blockDim.y * blockIdx.y + threadIdx.y;

  if (input_x >= width || input_y >= height) {
    return;
  }

  int output_x = input_y;
  int output_y = width - 1 - input_x;

  output_data[output_y * output_pitch + output_x] =
      input_data[input_y * input_pitch + input_x];
}

void CudaTest(const float* input, float* output, const int width, const int height,
                const int pitch_input, const int pitch_output) {
  dim3 block_dim(32, 1, 1);
  dim3 grid_dim;
  grid_dim.x = (width - 1) / 32 + 1;
  grid_dim.y = height;

  CudaTestKernel<<<grid_dim, block_dim>>>(
      output, input, width, height, pitch_input / sizeof(float),
      pitch_output / sizeof(float));
}
```

`nvcc  -c template_success.cu -DTEMPLATE --default-stream per-thread`:  success

----
However, this is only of marginal utility. It works for cuda_rotate, cuda_flip, and cuda_transpose, but I don't think *anyone* wants to specialize this monster at `src/mvs/patch_match_cuda.cu:809`:
```
template <int kWindowSize, int kWindowStep, bool kGeomConsistencyTerm = false,
          bool kFilterPhotoConsistency = false,
          bool kFilterGeomConsistency = false>
__global__ void SweepFromTopToBottom(
    GpuMat<float> global_workspace, GpuMat<curandState> rand_state_map,
    GpuMat<float> cost_map, GpuMat<float> depth_map, GpuMat<float> normal_map,
    GpuMat<uint8_t> consistency_mask, GpuMat<float> sel_prob_map,
    const GpuMat<float> prev_sel_prob_map, const GpuMat<float> ref_sum_image,
    const GpuMat<float> ref_squared_sum_image, const SweepOptions options);
```

Looks like there are 240 different specializations of this template.... no wonder compiling this unit takes awhile!

**Comment by ahojnnes** [comment]
If you know the window size a priori before compilation, you could remove most of the 240 cases. We could probably also make the boolean template parameters normal function parameters without too much performance penalty.

**Comment by mabrowning** [comment]
Ok, I was actually able to work around this nvcc bug... in an awful, awful way.

First, `VERBOSE=1 make`, which prints the nvcc invocation. I repeat the last, failing nvcc, but with `--verbose` and `--keep` nvcc arguments. Turns out, nvcc is emitting a function body for what should just be a stub, so `sed -i "" -e "s/{ ::cudaLaunchKernel(0, 0, 0, 0, 0, 0);}/;/" *cudafe1*` removes the erring code. Then, I repeat the last internal step that nvcc performs (`clang++ ... *cudafe1.cpp`), which produces the .cu.o file the rest of the build system expects.

Repeat for each cuda cu, and voila. Compiles, links, and runs.

Unfortunately, I'm hitting driver bugs during the feature matching step, but it *appears* to work.

**Comment by ahojnnes** [comment]
My own experience tells me to always stay with the previous CUDA version
(in this case 8), since the latest version usually always has lots of
bugs. But this is not always an option if you need some of the most
recent features.

**Comment by Joschka1** [comment]
@mabrowning Cuda is not compatible with XCode9.xx, because cuda is not compatible with the newest version of Apple Clang. You must install and use comandline tools 8.3. That works fine with the newest version of cuda.

**Comment by ahojnnes** [comment]
@Joschka1 Thanks for this information. I am closing this issue now, as this seems to be a bug on NVidia's side, which will hopefully be fixed sometime in the future.

**Comment by mabrowning** [comment]
It was. I actually heard from from them; they've fixed the issue and it will be available in the next CUDA release.
