### ISSUE TITLE
Registering new images into an existing reconstruction based on HLOC

### ISSUE THREAD

**Issue by wangjinhoon** [colmap/colmap#2967]
Hello, thank you for providing such a great code.

I would like to extract various features using HLOC and then proceed with "new images into an existing reconstruction" as described in the COLMAP documentation.

The process involves creating a model using HLOC's pipeline_SfM, then extracting features for additional images with extract_features.py to create a database. Afterward, I plan to use the following COLMAP commands:

```
colmap exhaustive_matcher \
    --database_path $PROJECT_PATH/database.db

colmap image_registrator \
    --database_path $PROJECT_PATH/database.db \
    --input_path /path/to/existing-model \
    --output_path /path/to/model-with-new-images
```
However, my method cannot perform matching using the command

```
colmap exhaustive_matcher \
    --database_path $PROJECT_PATH/database.db
```

as shown in the image below.
![image](https://github.com/user-attachments/assets/e04030a3-b2f1-4b7c-b718-c26c0d2b4a91)

This seems to indicate that the matching accuracy between the additional images and the existing images is zero.

Comparing it with the existing image_registrator documentation, I noticed that the traditional method stores six pieces of information in the columns during feature extraction, whereas HLOC stores only two. I am wondering if this is the reason why the matcher is not working.

![image](https://github.com/user-attachments/assets/aa40c7a2-d776-49f5-aed4-d77e6f0374eb)

Additionally, I would like to know if there is an easier way to register images using HLOC.

Thank you for reading.

**Comment by ahojnnes** [comment]
Here are two facts that maybe help with figuring out the issue:
1. You cannot mix different features in the same database.
2. If you use features other than SIFT, then COLMAP cannot deal with them directly in the matching stage (unless you make them look like SIFT features and adjust the various matching thresholds).

**Comment by sarlinpe** [comment]
Yes, you need to 1) do all the matching in hloc, 2) import the additional features and matches into the same database, 3) only then run the image registrator.

**Comment by wangjinhoon** [comment]
I confirmed that the two_view_geometries data was missing, and after adding it, it worked. Thank you!
