### ISSUE TITLE
pixsfm part of colmap?

### ISSUE THREAD

**Issue by mattiasmar** [colmap/colmap#2969]
Is pixsfm part of colmap or hloc in any way (directly or conceptually)?

**Comment by ahojnnes** [comment]
You can find the pixsfm code here: https://github.com/cvg/pixel-perfect-sfm

**Comment by mattiasmar** [comment]
@ahojnnes do you know if pixsfm has been applied successfully for large scenes with 10K+ images?

**Comment by ahojnnes** [comment]
@sarlinpe @Phil26AT will be the best people to answer this question.

**Comment by sarlinpe** [comment]
> Is pixsfm part of colmap or hloc in any way (directly or conceptually)?

PixSfM is an extension to COLMAP and can optionally rely on hloc for feature detection and matching, but it can also work on top of a standard COLMAP database.

> do you know if pixsfm has been applied successfully for large scenes with 10K+ images?

We have done experiments with 1k+ images but not 10k+, the main limiting factor being, at least in the current implementation, disk space to store the dense feature maps.
