### ISSUE TITLE
dense_stereo reconstruction ignoring all images

### ISSUE THREAD

**Issue by erikstenborg** [colmap/colmap#297]
After having run colmap image_undistorter, and a directory is created with all undistorted images and the sparse model, I try running colmap dense_stereo on it. Then I only get the message that it ignores all my images and it doesn't do anything but create an empty PLY file. Why would it ignore all images? And what does it mean that "it has no source images"?

Message from Colmap (shortened):
Reading workspace...
Reading configuration...
WARNING: Ignoring reference image img_07144_c0_1303399106316091us_rect.jpg, because it has no source images.
[...]
WARNING: Ignoring reference image img_07303_c1_1303399122316223us_rect.jpg, because it has no source images.

Directory structure (also shortened):
.
├── images
│   ├── img_07144_c0_1303399106316091us_rect.jpg
[...]
│   └── img_07304_c0_1303399122516215us_rect.jpg
├── meshed.ply
├── run-colmap-geometric.sh
├── run-colmap-photometric.sh
├── sparse
│   ├── cameras.bin
│   ├── images.bin
│   └── points3D.bin
└── stereo
    ├── consistency_graphs
    ├── depth_maps
    ├── fusion.cfg
    ├── normal_maps
    └── patch-match.cfg

6 directories, 330 files

**Comment by ahojnnes** [comment]
Could it be, that all your images have very narrow baseline? Can you show a screenshot of your sparse model?

**Comment by erikstenborg** [comment]
I forgot to mention that I import the sparse model from another source, and have not included the 3D structure, only the camera trajectory. Then I got some a hint that I need to manually specify the neighbors for each image to be used in the MVS, by filling in the file names in patch-match.cfg. I'll do that according to this instruction, and hope that will solve my problem. 

https://colmap.github.io/faq.html#manual-specification-of-source-images-during-dense-reconstruction

**Comment by erikstenborg** [comment]
Seems to work now, when I specify the neighbour images manually. I also had to provide DenseStereo.depth_min and DenseStereo.depth_max as parameters, which I guess provide limits for possible depth values. Is there any drawback of setting min to 0 and max to some very large value? Do I ruin precision, or just runtime by being unnecessarily conservative with the min and max depths?

Thanks,
Erik

**Comment by erikstenborg** [comment]
I have a second question:
Does the dense_fuser need 3D points from the sparse reconstruction to work? 

I get a warning about no points being fused when I run it now:
WARNING: Could not fuse any points. This is likely caused by incorrect settings - filtering must be enabled for the last call to patch match stereo.
Number of fused points: 0

**Comment by ahojnnes** [comment]
Did you have a look at the depth maps? Are they meaningful? You can look at the in the multi view stereo widget in the GUI.

**Comment by erikstenborg** [comment]
I just realized I could specify the workspace manually in the MVS widget. Quite helpful feature - thanks! 

The photometric depth maps look quite noisy, the geometric are a bit better, but still has some areas which are not perfect. The normal maps look like pure noise, but maybe I just don't interpret the images correctly. I attach a few examples here. Would you say they are meaningful? 

After importing also the 3D points from the source model, I can get the dense_fuser to return a resulting model which looks reasonable, although it has a bit of artifacts such as holes or extra (false) structure.

![c1_geomdepth_07150](https://user-images.githubusercontent.com/25663222/36103971-0ec27db0-1011-11e8-9937-6e8380023acf.png)
![c1_geomdepth_07151](https://user-images.githubusercontent.com/25663222/36103973-0ede7f42-1011-11e8-9caa-ac3110e052b4.png)
![c1_geomdepth_07152](https://user-images.githubusercontent.com/25663222/36103974-0ef94f7a-1011-11e8-9684-b9b4456c3fdb.png)
![c1_geomnorm_07150](https://user-images.githubusercontent.com/25663222/36103976-0f17461a-1011-11e8-8efc-3aa4fadae158.png)
![c1_photodepth_07150](https://user-images.githubusercontent.com/25663222/36103977-0f323d30-1011-11e8-8778-0d6a4c7e47d7.png)
![c1_photodepth_07151](https://user-images.githubusercontent.com/25663222/36103978-0f4e8f94-1011-11e8-9a4c-4ac15d210537.png)
![c1_photodepth_07152](https://user-images.githubusercontent.com/25663222/36103979-0f86da98-1011-11e8-9e44-5b89e5957e77.png)
![c1_photonorm_07150](https://user-images.githubusercontent.com/25663222/36103980-0fa7737a-1011-11e8-9a27-5efcd01ebc22.png)
![img_07150_c1_1303399107049515us_rect](https://user-images.githubusercontent.com/25663222/36103981-0fc735ac-1011-11e8-8af5-e9897b53aab0.jpg)
![img_07151_c1_1303399107116140us_rect](https://user-images.githubusercontent.com/25663222/36103982-0fe33edc-1011-11e8-809c-65f5153de708.jpg)
![img_07152_c1_1303399107249525us_rect](https://user-images.githubusercontent.com/25663222/36103983-0ffdf402-1011-11e8-8897-4e1aebb3d8c8.jpg)

**Comment by ahojnnes** [comment]
The results look reasonable to me, given the rather blurry images. If you have a high frame rate when capturing the images, you might want to increase the minimum triangulation angle option a little bit. In addition, you could use more source images per view, see https://colmap.github.io/faq.html#manual-specification-of-source-images-during-dense-reconstruction

**Comment by SBCV** [comment]
Maybe the error source is the same as in #302

**Comment by erikstenborg** [comment]
Well, I've accepted that I should include the points from the sparse reconstruction in addition to the camera trajectory for best results, so it's not really an issue for me anymore. 

Thanks a lot for the help though!

**Comment by yuancaimaiyi** [comment]
> I have a second question:
> Does the dense_fuser need 3D points from the sparse reconstruction to work?
> 
> I get a warning about no points being fused when I run it now:
> WARNING: Could not fuse any points. This is likely caused by incorrect settings - filtering must be enabled for the last call to patch match stereo.
> Number of fused points: 0

@erikstenborg @ahojnnes @SBCV 
Hi, I Reconstruct sparse/dense model from known camera poses,https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses. the doc said " produce a dense model can  without a sparse mode"
colmap image_undistorter \
    --image_path $PROJECT_PATH/images \
    --input_path path/to/manually/created/sparse/model \
    --output_path path/to/dense/workspace
colmap patch_match_stereo \
    --workspace_path path/to/dense/workspace \
    --PatchMatchStereo.depth_min $MIN_DEPTH \
    --PatchMatchStereo.depth_max $MAX_DEPTH

colmap stereo_fusion \
    --workspace_path path/to/dense/workspace \
    --output_path path/to/dense/workspace/fused.ply
**I modify the patch-match.cfg and min_depth and max_depth,I get a good depth map ,But I fused points,the number is 0. Is code error? thanks !!!!!!!!!!!!!!!!!!!!!**

**Comment by yuancaimaiyi** [comment]
> I have a second question:
> Does the dense_fuser need 3D points from the sparse reconstruction to work?
> 
> I get a warning about no points being fused when I run it now:
> WARNING: Could not fuse any points. This is likely caused by incorrect settings - filtering must be enabled for the last call to patch match stereo.
> Number of fused points: 0

@erikstenborg @ahojnnes @SBCV 
Hi, I Reconstruct sparse/dense model from known camera poses,https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses. the doc said " produce a dense model can  without a sparse mode"
colmap image_undistorter \
    --image_path $PROJECT_PATH/images \
    --input_path path/to/manually/created/sparse/model \
    --output_path path/to/dense/workspace
colmap patch_match_stereo \
    --workspace_path path/to/dense/workspace \
    --PatchMatchStereo.depth_min $MIN_DEPTH \
    --PatchMatchStereo.depth_max $MAX_DEPTH

colmap stereo_fusion \
    --workspace_path path/to/dense/workspace \
    --output_path path/to/dense/workspace/fused.ply
**I modify the patch-match.cfg and min_depth and max_depth,I get a good depth map ,But I fused points,the number is 0. Is code error? thanks !!!!!!!!!!!!!!!!!!!!!**

**Comment by dyy0205** [comment]
> > I have a second question:
> > Does the dense_fuser need 3D points from the sparse reconstruction to work?
> > I get a warning about no points being fused when I run it now:
> > WARNING: Could not fuse any points. This is likely caused by incorrect settings - filtering must be enabled for the last call to patch match stereo.
> > Number of fused points: 0
> 
> @erikstenborg @ahojnnes @SBCV Hi, I Reconstruct sparse/dense model from known camera poses,https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses. the doc said " produce a dense model can without a sparse mode" colmap image_undistorter --image_path $PROJECT_PATH/images --input_path path/to/manually/created/sparse/model --output_path path/to/dense/workspace colmap patch_match_stereo --workspace_path path/to/dense/workspace --PatchMatchStereo.depth_min $MIN_DEPTH --PatchMatchStereo.depth_max $MAX_DEPTH
> 
> colmap stereo_fusion --workspace_path path/to/dense/workspace --output_path path/to/dense/workspace/fused.ply **I modify the patch-match.cfg and min_depth and max_depth,I get a good depth map ,But I fused points,the number is 0. Is code error? thanks !!!!!!!!!!!!!!!!!!!!!**

hi, the problem!! Have you solved it?
