### ISSUE TITLE
[win11&WSL] pip install pycolmap

### ISSUE THREAD

**Issue by mganglb** [colmap/colmap#2972]
**Describe the bug**
- Win11 & WSL
- miniconda
- Pycolmap v 3.11.0

After installing PyColmap using` pip install pycolmap` or `python -m pip install pycolmap` or `pip install pycolmap-3.11.0-cp310-cp310-win_amd64.whl`, an exception is raised when attempting to import pycolmap.

```
Python 3.10.15 | packaged by conda-forge | (main, Oct 16 2024, 01:15:49) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycolmap
Traceback (most recent call last):
  File "C:\*\AppData\Local\miniconda3\envs\py310_all\lib\site-packages\pycolmap\__init__.py", line 18, in <module>
    from . import _core
ImportError: generic_type: type "PositiveExponentialManifold" referenced unknown base type "ceres::Manifold"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\*\AppData\Local\miniconda3\envs\py310_all\lib\site-packages\pycolmap\__init__.py", line 20, in <module>
    raise RuntimeError(
RuntimeError:
Cannot import the C++ backend pycolmap._core.
Make sure that you successfully install the package with
  $ python -m pip install pycolmap/
```

Installing from wheel, leads to the following exception: `pip install pycolmap-3.10.0-cp310-cp310-win_amd64.whl`

```
>>> import pycolmap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed while importing pycolmap: A dynamic link library (DLL) initialization routine failed.
>>>
```

**To Reproduce**
1. install pycolmap 
2. import pycolmap (in python script)

**Environment:**
- Win11
- miniconda (python environment: Python 3.10.15 | packaged by conda-forge | (main, Oct 16 2024, 01:15:49) [MSC v.1941 64 bit (AMD64)] on win32)
- pycolmap v 3.11.0

**possibly related issue**
- https://github.com/colmap/pycolmap/issues/288

Thank you for your support
Markus

**Comment by mganglb** [comment]
Update:
The same issue occurs importing pycolmap on linux (WSL). (pycolmap 3.10.0 was working on my WSL)

```
Python 3.10.15 (main, Oct  3 2024, 07:27:34) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycolmap
Traceback (most recent call last):
  File "*/anaconda3/envs/py310_all/lib/python3.10/site-packages/pycolmap/__init__.py", line 7, in <module>
    from . import _core
ImportError: generic_type: type "PositiveExponentialManifold" referenced unknown base type "ceres::Manifold"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "*anaconda3/envs/py310_all/lib/python3.10/site-packages/pycolmap/__init__.py", line 9, in <module>
    raise RuntimeError(
RuntimeError: 
Cannot import the C++ backend pycolmap._core.
Make sure that you successfully install the package with
  $ python -m pip install pycolmap/
```

**Comment by ahojnnes** [comment]
Do you have pyceres installed? Which version do you have installed?

**Comment by mganglb** [comment]
- on win: pyceres 2.3
- on linux: pyceres 2.3

Updating to pyceres == 2.4 resolves the issue on win11 as well as on linux.

ty
Markus

**Comment by jwd222** [comment]
> * on win: pyceres 2.3
> * on linux: pyceres 2.3
> 
> Updating to pyceres == 2.4 resolves the issue on win11 as well as on linux.
> 
> ty Markus

hi, did you install pyceres through pip? or can we build it from source using our current ceres-solver install?
I'm facing issues while installing pycolmap in wsl as well.
