### ISSUE TITLE
3.11/10 can't debug in Windows,VS2022

### ISSUE THREAD

**Issue by woshizhangbowen** [colmap/colmap#2974]
**Describe the bug**
When i use colmap 3.11  3.10.I can't use debug to build the project in vs2022,Windows10.But i can use Release and successfully run it.
But if I use colmap 3.9. I can use debug/release and build it perfectlly and run them.
So what is happening to the 3.11 and 3.10?These questions I meet but can't solve them bymyself.

**To Reproduce**
1. begin build
![image](https://github.com/user-attachments/assets/084f3110-bd2e-4f4e-bf3a-2aca53967c15)

2.give me the errors:
![image](https://github.com/user-attachments/assets/7382fe69-1736-40fb-8f36-8c6aa60869c0)

**Expected behavior**
Under normal circumstances, this setup would compile successfully in version 3.9. However, in versions 3.10 or 3.11, I encountered issues with "0 and 2" in both Release and Debug modes. I haven't been able to pinpoint the cause of this problem. I reviewed the CMakeLists.txt file but couldn't figure out why the issue with Debug and Release occurs in colmap_scene.

I tried several approaches to resolve it, such as globally setting Debug mode or specifying Debug during the CMake configuration step. However, none of these methods worked, and the issue persists.

Here is the CMake command I used:
cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE=D:\appset\vcpkg\vcpkg-master\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -D CMAKE_CUDA_ARCHITECTURES="86" -D CMAKE_BUILD_TYPE=Debug

**Screenshots**
![image](https://github.com/user-attachments/assets/dceee0cc-60f6-449b-b60d-97dc3d8f9598)

**Environment:**
 - OS: [e.g. Windows 10]
 - COLMAP Version [3.11 3.10 ]

**Comment by ahojnnes** [comment]
I am not sure why Debug mode doesn't work under Windows. It should work under Linux/Mac. However, I suggest compiling in RelWithDebInfo, as Debug will be too slow in practice anyways.

**Comment by tineras** [comment]
Just a note from your screenshot... do not try and build ALL_BUILD. You must build `colmap_main`

Solution Explorer > colmap_targets > exe > colmap_main > Set as Startup Project

**Comment by woshizhangbowen** [comment]
> Just a note from your screenshot... do not try and build ALL_BUILD. You must build `colmap_main`只是从你的截图注意.不要尝试构建ALL_BUILD。您必须构建`colmap_main`
> 
> Solution Explorer > colmap_targets > exe > colmap_main > Set as Startup Project解决方案资源管理器> colmap_targets > exe > colmap_main >设置为启动项目

aha，It doesn't work yet .Still the same questions.Thank you very much.Do you run in Debug model in colmap 3.11or3.10?Maybe you can give me some suggestions.
![image](https://github.com/user-attachments/assets/1133adc7-f612-402e-b33b-2e9ee0ab2e75)

**Comment by woshizhangbowen** [comment]
> > Just a note from your screenshot... do not try and build ALL_BUILD. You must build `colmap_main`只是从你的截图注意.不要尝试构建ALL_BUILD。您必须构建`colmap_main`
> > Solution Explorer > colmap_targets > exe > colmap_main > Set as Startup Project解决方案资源管理器> colmap_targets > exe > colmap_main >设置为启动项目解决方案资源管理器> colmap_targets > exe > colmap_main >设置为启动项目解决方案资源管理器> colmap_targets > exe > colmap_main >设置为启动项目
> 
> aha，It doesn't work yet .Still the same questions.Thank you very much.Do you run in Debug model in colmap 3.11or3.10?Maybe you can give me some suggestions.啊哈，还不能用。还是同样的问题。非常感谢。你在colmap 3.11或3.10中运行的是可扩展模型吗？也许你可以给我一些建议。 ![image](https://private-user-images.githubusercontent.com/127416316/392177744-1133adc7-f612-402e-b33b-2e9ee0ab2e75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNzE2NTYsIm5iZiI6MTczMzI3MTM1NiwicGF0aCI6Ii8xMjc0MTYzMTYvMzkyMTc3NzQ0LTExMzNhZGM3LWY2MTItNDAyZS1iMzNiLTJlOWVlMGFiMmU3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQwMDE1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWJjNjdhNjQ0OTkwZjE5OTI4OWU3MTMzOWI5ZTBjZDYyNmQyMTYxNzQ0YTRjYjI0MDg0NzgxMWUxMGRjMmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Vxbr8ATOC4CUvfVOujLQ8C7uwMZwLTcBrRK0hRkFgT8)

![image](https://github.com/user-attachments/assets/9c785b31-15ac-467d-a1d9-0817f2d8ecf0)
Only this can.Debug is uesless.

**Comment by tineras** [comment]
> > > Just a note from your screenshot... do not try and build ALL_BUILD. You must build `colmap_main`只是从你的截图注意.不要尝试构建ALL_BUILD。您必须构建`colmap_main`
> > > Solution Explorer > colmap_targets > exe > colmap_main > Set as Startup Project解决方案资源管理器> colmap_targets > exe > colmap_main >设置为启动项目解决方案资源管理器> colmap_targets > exe > colmap_main >设置为启动项目解决方案资源管理器> colmap_targets > exe > colmap_main >设置为启动项目
> > 
> > 
> > aha，It doesn't work yet .Still the same questions.Thank you very much.Do you run in Debug model in colmap 3.11or3.10?Maybe you can give me some suggestions.啊哈，还不能用。还是同样的问题。非常感谢。你在colmap 3.11或3.10中运行的是可扩展模型吗？也许你可以给我一些建议。 ![image](https://private-user-images.githubusercontent.com/127416316/392177744-1133adc7-f612-402e-b33b-2e9ee0ab2e75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNzE2NTYsIm5iZiI6MTczMzI3MTM1NiwicGF0aCI6Ii8xMjc0MTYzMTYvMzkyMTc3NzQ0LTExMzNhZGM3LWY2MTItNDAyZS1iMzNiLTJlOWVlMGFiMmU3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQwMDE1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWJjNjdhNjQ0OTkwZjE5OTI4OWU3MTMzOWI5ZTBjZDYyNmQyMTYxNzQ0YTRjYjI0MDg0NzgxMWUxMGRjMmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Vxbr8ATOC4CUvfVOujLQ8C7uwMZwLTcBrRK0hRkFgT8)
> 
> ![image](https://private-user-images.githubusercontent.com/127416316/392177999-9c785b31-15ac-467d-a1d9-0817f2d8ecf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNzU1MzMsIm5iZiI6MTczMzI3NTIzMywicGF0aCI6Ii8xMjc0MTYzMTYvMzkyMTc3OTk5LTljNzg1YjMxLTE1YWMtNDY3ZC1hMWQ5LTA4MTdmMmQ4ZWNmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQwMTIwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWQxNmQ1YzcxZGZlZTM2ZWVlN2M0ZTUzNzY5YzBiYzFjMTI3MmI5NjU5NDZmZTQ2YzRjM2NhZWMyNGZkOTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.twLd5mzPVs8-Bs0w3WYoWYnBrCB051mTyNtWMSbNkRQ) Only this can.Debug is uesless.

I would not run in debug. Run it just like you are in Release with Debug Info as ahojnnes suggested.

**Comment by woshizhangbowen** [comment]
> > > > Just a note from your screenshot... do not try and build ALL_BUILD. You must build `colmap_main`只是从你的截图注意.不要尝试构建ALL_BUILD。您必须构建`colmap_main`
> > > > Solution Explorer > colmap_targets > exe > colmap_main > Set as Startup Project解决方案资源管理器> colmap_targets > exe > colmap_main >设置为启动项目解决方案资源管理器> colmap_targets > exe > colmap_main >设置为启动项目解决方案资源管理器> colmap_targets > exe > colmap_main >设置为启动项目
> > > 
> > > 
> > > aha，It doesn't work yet .Still the same questions.Thank you very much.Do you run in Debug model in colmap 3.11or3.10?Maybe you can give me some suggestions.啊哈，还不能用。还是同样的问题。非常感谢。你在colmap 3.11或3.10中运行的是可扩展模型吗？也许你可以给我一些建议。 ![image](https://private-user-images.githubusercontent.com/127416316/392177744-1133adc7-f612-402e-b33b-2e9ee0ab2e75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNzE2NTYsIm5iZiI6MTczMzI3MTM1NiwicGF0aCI6Ii8xMjc0MTYzMTYvMzkyMTc3NzQ0LTExMzNhZGM3LWY2MTItNDAyZS1iMzNiLTJlOWVlMGFiMmU3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQwMDE1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWJjNjdhNjQ0OTkwZjE5OTI4OWU3MTMzOWI5ZTBjZDYyNmQyMTYxNzQ0YTRjYjI0MDg0NzgxMWUxMGRjMmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Vxbr8ATOC4CUvfVOujLQ8C7uwMZwLTcBrRK0hRkFgT8)
> > 
> > 
> > <img alt="image" width="54.133522033691406" height="21.008522033691406" src="https://private-user-images.githubusercontent.com/127416316/392177999-9c785b31-15ac-467d-a1d9-0817f2d8ecf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNzU1MzMsIm5iZiI6MTczMzI3NTIzMywicGF0aCI6Ii8xMjc0MTYzMTYvMzkyMTc3OTk5LTljNzg1YjMxLTE1YWMtNDY3ZC1hMWQ5LTA4MTdmMmQ4ZWNmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQwMTIwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWQxNmQ1YzcxZGZlZTM2ZWVlN2M0ZTUzNzY5YzBiYzFjMTI3MmI5NjU5NDZmZTQ2YzRjM2NhZWMyNGZkOTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.twLd5mzPVs8-Bs0w3WYoWYnBrCB051mTyNtWMSbNkRQ"> Only this can.Debug is uesless.只有这个可以。这个没用。
> 
> I would not run in debug. Run it just like you are in Release with Debug Info as ahojnnes suggested.我不会在debug中运行。运行它就像你在释放与Ahojnnes建议的PandemInfo。

白让我开心了哈哈
