### ISSUE TITLE
The vocabulary feature matching step seems to have slowed down when changing from version 3.8 to version 3.9.

### ISSUE THREAD

**Issue by ChungJin0301** [colmap/colmap#2977]
As it changed from version 3.8 to version 3.9, the indexing image part of the vocabulary feature matching step seems to have slowed down.
It seems to be the same for versions 3.10 and 3.11.

There are so many changes that it is difficult to find the cause. Are there any related issues?

**Comment by ahojnnes** [comment]
You mean that indexing in the vocabulary tree slowed down from 3.10 to 3.11 as well?

I would need a little more information. Which vocabulary tree are you using? Is this consistent across different datasets? Would you have some side by side log output to share?

**Comment by ChungJin0301** [comment]
thank you for reply!

I used "https://demuc.de/colmap/vocab_tree_flickr100K_words256K.bin" vocabulary tree.
And This was consistent for all data.

I attached the sample dataset and log photos that I used.
<img width="1309" alt="log" src="https://github.com/user-attachments/assets/2e6ea5ba-115e-4b95-92c3-fb6ee06cad48">
left: 3.8 version / right: 3.10 version
https://drive.google.com/file/d/1HsJ-Db52VYBAHdlRUXzB_Ppy5R8OocfO/view?usp=drive_link

**Comment by ahojnnes** [comment]
Something definitely regressed. After a quick diff of the colmap/retrieval folder, it does not seem to be caused by a change to the retrieval engine. The most likely candidates are the revamped feature matching controllers/caches as well as the change from custom compiled FLANN vs. using the preinstalled system FLANN.

**Comment by ahojnnes** [comment]
@ChungJin0301 In 3.10, how did you install FLANN? Are you sure it's compiled with optimization flags, etc.?

**Comment by ChungJin0301** [comment]
I installed using "sudo apt-get install libflann-dev" on Ubuntu-22.04(WSL).
There are differences even though the same flann library is used.

**Comment by ahojnnes** [comment]
Do you have a side-by-side comparison between 3.10 and 3.11 on your system? How large is the difference?

**Comment by ChungJin0301** [comment]
![image](https://github.com/user-attachments/assets/f970f016-3459-4df0-b975-fc97c88c7e67)
left: 3.10 / right: 3.11

There seems to be almost no difference.

**Comment by ahojnnes** [comment]
Thank you. We can then focus our investigation on 3.8 vs 3.10. Another good data point could be a comparison of 3.8 vs. 3.9. :-)

**Comment by ChungJin0301** [comment]
@ahojnnes  Where are the strong candidates?

**Comment by ahojnnes** [comment]
The easiest would be to use git bisect. It should be fairly quick to narrow it down with a specific commit this way.

**Comment by ahojnnes** [comment]
OK, I went ahead myself and found the issue. It is caused by the switch from custom compiled flann inside colmap vs. using system-installed flann. Given your screenshots, I gather that you ran these experiments on Windows with the pre-compiled binaries? In this case, flann is installed by vcpkg, which is compiled without openmp and thus the call to knnSearch is not multi-threaded and thus slow. It probably makes sense to adjust the flann package in vcpkg to support openmp, so at least our vcpkg compiled binaries don't have the issue.

**Comment by ChungJin0301** [comment]
Thank you for reply!

But I built it myself and experimented on Ubuntu with sudo apt-get install libflann-dev.
Both 3.8 and 3.9 version used same flann library but the result is different.

I will try it, referring to your comment.

**Comment by ChungJin0301** [comment]
The same problem occurs when I download flann again from GitHub and install it.
The 3.8 version is clearly faster than the 3.9 version.

But It certainly seems to be a problem with the knnsearch part.
How can I fix this on Ubuntu?

**Comment by ahojnnes** [comment]
Can you try whether adding the following to src/colmap/retrieval/CMakeLists.txt fixes the issue:
```
COLMAP_ADD_LIBRARY(
    NAME colmap_retrieval
    ...
)
if(OPENMP_FOUND)
    target_link_libraries(colmap_retrieval PRIVATE OpenMP::OpenMP_CXX)
endif()
```

**Comment by ChungJin0301** [comment]
Wow PUBLIC work well!!

Thank you for help!

**Comment by ahojnnes** [comment]
Does private also work?

**Comment by ChungJin0301** [comment]
private does not work!

**Comment by ahojnnes** [comment]
Thank you, I'll fix it in the main branch as well then.

**Comment by ahojnnes** [comment]
Yes, that's the plan. I am still stabilizing the release but it is imminent in the next days/weeks.

**Comment by makzsslm** [comment]
I seem to be running into a related on MacOS. While running colmap vocab_tree_matcher, the process seems to be running single-threaded. 
- colmap version 3.12.3 installed from homebrew
- libomp version is 5.0.0
Not sure what more information to provide, but happy to test and report!
