### ISSUE TITLE
The generated 3D points by point_triangulator are very few.

### ISSUE THREAD

**Issue by hm123450** [colmap/colmap#2991]
Hello, I'm back, and I really appreciate your previous answer to my question **"If I already know the camera's intrinsic and extrinsic parameters, how can I use COLMAP to obtain the projects3D.txt file?"** I processed my cameras.txt and images.txt files, successfully ran the command `colmap point_triangulator --database_path database.db --image_path ../train --input_path created/sparse/model --output_path triangulated/sparse/model`, and obtained the points3D.bin file.

**Comment by hm123450** [comment]
![image](https://github.com/user-attachments/assets/dbf5153f-b378-4501-ac8e-d28ee250bd80)

**Comment by hm123450** [comment]
I turn the bin file to txt file and find I only get 1 point. I know there is one reason that I only have 7 pictures.  I will increse the picture numbers. However, I still would like to know if there are any other command-line arguments that could affect the generation of the number of points3D points, such as the "bundle adjuster" parameter you mentioned earlier. I can ensure that the camera's intrinsic and extrinsic parameters are accurate because they were extracted from the ScanNet dataset.

**Comment by hm123450** [comment]
![image](https://github.com/user-attachments/assets/a7fd0721-b60e-434e-801a-70dafb350886)

**Comment by hm123450** [comment]
This is the output

**Comment by hm123450** [comment]
![image](https://github.com/user-attachments/assets/4fc16696-0b29-4ac9-b412-a710cca85597)

**Comment by hm123450** [comment]
Thank you very much if you can help me

**Comment by ahojnnes** [comment]
I would appreciate if you can continue the discussion in the existing issue instead of creating a new one and also possibly not dropping one sentence in each comment. It will also be helpful to provide more information with all commands executed, etc. Your issue description is not actionable. Most likely, there is a bug in how you specify the camera poses. Thank you.

**Comment by hm123450** [comment]
> I would appreciate if you can continue the discussion in the existing issue instead of creating a new one and also possibly not dropping one sentence in each comment. It will also be helpful to provide more information with all commands executed, etc. Your issue description is not actionable. Most likely, there is a bug in how you specify the camera poses. Thank you.

OKK，I will turn to the original question
