### ISSUE TITLE
PosePriorBundleAdjusterOptions::ransac_max_error hasn't been used in PosePriorBundleAdjuster

### ISSUE THREAD

**Issue by StonerLing** [colmap/colmap#2992]
The maximum RANSAC error for Sim3 alignment from reconstruction to pose prior is calculated from average position covariance：
https://github.com/colmap/colmap/blob/290ec62f872260bcbbd44a31155a9f83b4be2fa1/src/colmap/estimators/bundle_adjustment.cc#L1023-L1029

But the member `ransac_max_error`  in `PosePriorBundleAdjusterOptions` isn't taken into consideration.
https://github.com/colmap/colmap/blob/290ec62f872260bcbbd44a31155a9f83b4be2fa1/src/colmap/estimators/bundle_adjustment.h#L200-L210

I think the interface options should have higher priority. It may be modified like this:
```cpp
if (num_covs > 0) { 
   ransac_options.max_error = prior_options_.ransac_max_error > 0. ? 
     prior_options_.ransac_max_error : (3. * (avg_cov / num_covs).cwiseSqrt()).norm(); 
 } 
```

**Comment by ahojnnes** [comment]
Thanks for reporting this bug. Should be fixed in: https://github.com/colmap/colmap/pull/2993
