### ISSUE TITLE
To download the dataset

### ISSUE THREAD

**Issue by amiltonwong** [colmap/colmap#3]
Dear @ahojnnes ,

For the tutorial video: https://www.youtube.com/watch?v=P-EC0DzeVEU , where could I download the dataset used in tutorial video?

Furthmore, for link: https://www.youtube.com/watch?v=xu-nWgjWKI0 , where could I download the dataset "From Dusk till Dawn: Modeling in the Dark"?

THX~
Milton

**Comment by pmoulon** [comment]
As far I remember, the first time I saw this dataset was on the Christopher Zach ETHZ website http://www.cvg.ethz.ch/research/chzach/opensource.html
You will find it here http://www.cvg.ethz.ch/research/chzach/oss/V3D-SfM-data.tar.bz2

**Comment by ahojnnes** [comment]
Thanks @pmoulon! Pierre is right about the dataset, which is the main building at UNC Chapel Hill.

Unfortunately, the datasets for the "Dusk till Dawn: Modeling in the Dark" paper (which are the same as used in this paper: "From Single Image Query to Detailed 3D Reconstruction") are not yet released. But we plan to do so in the near future and I can try to remember to ping you.

Let me know if you have any other question. Otherwise, I'll close this issue.

**Comment by amiltonwong** [comment]
Thanks @pmoulon , @ahojnnes  for your kind help :)

**Comment by ahojnnes** [comment]
@amiltonwong I uploaded a few demo datasets, see https://colmap.github.io/datasets.html, including the one from Christopher. More to follow soon.

**Comment by amiltonwong** [comment]
Dear @ahojnnes ,

The link " https://colmap.github.io/datasets.html" is not working now, could you help to fix it?

THX~

**Comment by ahojnnes** [comment]
Hi,

It should forward you to Google Drive automatically, just checked that and it worked on my machine here.

Best, Johannes

**Comment by ahojnnes** [comment]
Can you confirm that the link is still dead?

**Comment by amiltonwong** [comment]
Thanks @ahojnnes , It works now, I think that's the networking issue in my PC,
Sorry for any inconvenience :)

**Comment by zzxp** [comment]
I can not download the dataset from https://demuc.de/colmap/, is it not working now?
 [图片]

**Comment by ahojnnes** [comment]
The links for the dataset changed. I will update them over the next days.

**Comment by zzxp** [comment]
ok ,Thank you

**Comment by ahojnnes** [comment]
The links to the datasets are now updated.

**Comment by mremreozan** [comment]
It works, thank you

**Comment by yiakwy-xpu-ml-framework-team** [comment]
@ahojnnes Hi, could you updated dataset to dropbox or google driver because we cannot download the images from Linux terminal from oneDrive. Currently I am using http://www.cvg.ethz.ch/research/chzach/oss/V3D-SfM-data.tar.bz2 and some dataset from Nerf porject. Thank you.
