### ISSUE TITLE
Suggestion: Use multiple threads to resize images for feature extraction

### ISSUE THREAD

**Issue by duckblaster** [colmap/colmap#30]

**Comment by ahojnnes** [comment]
Good suggestion. This should be easy. Thanks.

**Comment by duckblaster** [comment]
Just seems a bit wasteful to have gpu and cpu almost idle with large images

**Comment by ahojnnes** [comment]
This is implemented in the latest commits in the dev branch. In addition, feature extraction now runs on multiple GPUs, if available. Thanks for the suggestion.
