### ISSUE TITLE
fails to build on non amd64/i386

### ISSUE THREAD

**Issue by alexmyczko** [colmap/colmap#300]
i didnt check the details, maybe you want to:

https://buildd.debian.org/status/package.php?p=colmap

**Comment by ahojnnes** [comment]
Thanks for the info, but I don't have access to any non-amd64 system and I don't have the time/hardware resources to support these platforms.

**Comment by ahojnnes** [comment]
@alexmyczko The latest commit on the dev branch should now work on ARM. Could you issue another build for Debian to test? Thanks!
