### ISSUE TITLE
sfm bad ;Camera pose error due to similar structure;Can specify the camera pose?

### ISSUE THREAD

**Issue by luocha0107** [colmap/colmap#3001]
Due to the structural similarity of the reconstructed objects, the feature points are similar and the camera pose is calculated incorrectly.
 Is there any good way? Or can we specify the camera pose during reconstruction?
![Weixin Screenshot_20241207203242](https://github.com/user-attachments/assets/a58bf382-adbf-4893-b3e3-14a06b7d4bdf)

**Comment by tsattler** [comment]
If you have the poses and the intrinsics, you can use the `point_triangulator` to get the 3D structure. Otherwise, you will need to carefully ensure that you are not matching images that are taken at different places but show similar structures.

**Comment by luocha0107** [comment]
> If you have the poses and the intrinsics, you can use the `point_triangulator` to get the 3D structure. Otherwise, you will need to carefully ensure that you are not matching images that are taken at different places but show similar structures.

ok,thanks.

**Comment by ferreram** [comment]
If you already have a prior on your images' pose, you could try the spatial matcher instead of the exhaustive matcher in order to limit matching images that do not share a common viewpoint.  Otherwise, you can also try to apply a sequential matching with the same idea in mind.
