### ISSUE TITLE
CUDA not detected, despite 9.1.85 present

### ISSUE THREAD

**Issue by Hibryda** [colmap/colmap#301]
As in the title. I cannot make Colmap accept existence of functional CUDA on my machine. Any steps to take to convince the software to run dense map?

**Comment by ahojnnes** [comment]
Some more information is needed to answer that question. System, CMake version, CMake log output, etc.

**Comment by Hibryda** [comment]
Sorry. Linux, kernel 4.4.0-112, distro ElementaryOS >Loki (derivative of Ubuntu 16.04), CMake 3.5.1.
As to CMake log - pasting whole makes little sense, maybe you'll point me to some specific place to look?

**Comment by Hibryda** [comment]
One thing - upon second try of compiling I got: "nvcc fatal   : Unsupported gpu architecture 'compute_61'" . GPU is Nvidia 1080Ti .

**Comment by Hibryda** [comment]
Further elaboration - it compiled first without a hussle. Now it throws.

**Comment by ahojnnes** [comment]
Can you just delete everything in your build folder and start from scratch? Disunion pull the latest code from GitHub?

**Comment by Hibryda** [comment]
Sure. Will recompile all.
By disunion you mean just fresh?

**Comment by Hibryda** [comment]
Recompiled. Make raised the same error as above.

**Comment by Hibryda** [comment]
Full error:

> [ 41%] Building NVCC (Device) object src/ext/PBA/CMakeFiles/pba.dir/pba_generated_ProgramCU.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_61'
CMake Error at pba_generated_ProgramCU.cu.o.cmake:207 (message):
  Error generating
  /home/*****/temp/colmap/build/src/ext/PBA/CMakeFiles/pba.dir//./pba_generated_ProgramCU.cu.o

**Comment by ahojnnes** [comment]
Are you sure you only have one CUDA version installed? It sounds like you are compiling COLMAP with an older CUDA version that does not yet support the 6.1 architecture.

**Comment by Hibryda** [comment]
In my /usr/local I have:
> bin  cuda-9.1  etc  games  include  lib  man  sbin  share  src  var
Version file shows 9.1.85
But actually nvcc --version shows version 7.5 of compiler tools. Should they match CUDA version?

**Comment by Hibryda** [comment]
So, now everything works as expected. For future reference:
- for unknown reason it failed to detect cuda at all when nvcc wasn't in path (correct me if it matters);
- fail to compile was due to installing nvidia-cuda-toolkit from standard repos as a measure to have nvcc available. But these repos are outdated, thus 7.5.
- the only way was to scrub cuda completely and manually (with remove cuda* it failed to find all components).
The reason for path inconsistency was probably in my past works on cuda kernels, but they worked and still work without a problem.
