### ISSUE TITLE
model align failed,please help!

### ISSUE THREAD

**Issue by 86057757comeon** [colmap/colmap#3016]
my introducation and :

`colmap model_aligner --input_path sparse/0 
--output_path sparse/geo 
--ref_images_path /home/liuez/datas/7scenes_chess/test_sfm/geo_pos.txt 
--alignment_max_error 3`

error message:

`
I20241209 11:40:33.942925 139663198760960 model.cc:125] 
Converting Alignment Coordinates from GPS (lat/lon/alt) to ECEF.
I20241209 11:40:34.323921 139663198760960 misc.cc:51] 
Aligning reconstruction to custom
---------------------------------
I20241209 11:40:34.323953 139663198760960 model.cc:361] => Using 5 reference images
E20241209 11:40:34.339605 139663198760960 model.cc:373] => Alignment failed
`
i also try use more reference images but still error.

geo_pos.txt include:

`seq-03-frame-000000.color.png -0.026059032322689708 -0.7870407505234146 -0.7046216972853898
seq-03-frame-000001.color.png -0.02601891150581413 -0.7847200822231424 -0.7006298207982711
seq-03-frame-000002.color.png -0.024315750930273383 -0.7851880863719621 -0.698982971006862
seq-03-frame-000003.color.png -0.025412814813186187 -0.7861721635650945 -0.6975829604448067
seq-03-frame-000004.color.png -0.023623070187827368 -0.7850813671753869 -0.6950691437447644`
'seq-03-frame-000000.color.png' same as name for images.bin

please help ,thanks!

**Comment by 86057757comeon** [comment]
> Have you tried increasing the alignment error? It may be that either the positions in geo_pos.txt or the reconstructed image poses are not accurate enough for your current setting of 3 meters.
Thanks,it can work,but the outcome is different from my expect.They seem to be in different coordinate systems.How can i align them?
the outcome is  -6070051.5265796892 -1884640.2602518238 -531120.65396663826 for seq-03-frame-000000.color.png , i want like -0.026059032322689708 -0.7870407505234146 -0.7046216972853898.
Thanks!

**Comment by ferreram** [comment]
You need to set the "ref_is_gps" option to false, otherwise your reference positions are expected to be LLA coordinates.

**Comment by 86057757comeon** [comment]
@ferreram thanks,i get it.
