### ISSUE TITLE
WARNING: Ignoring reference image 00000000.jpg, because it has no source images.

### ISSUE THREAD

**Issue by SBCV** [colmap/colmap#302]
// Short description.
Current colmap version (246e8da982db77d4008d11f1d11147e5eacaacd7) produces this warning, older version  (6a6ca807834223341d1451a900b0e16e544fcb95)  does not.

// Longer description.
When running the following command (target is a PMVS folder, which was created using openMVG)

`./dense_stereo --workspace_path path/to/openmvg/exported/pmvs/folder --workspace_format PMVS --pmvs_option_name pmvs_options.txt --DenseStereo.geom_consistency False --DenseStereo.max_image_size 480`

with the latest colmap commit (246e8da982db77d4008d11f1d11147e5eacaacd7) then Colmap throws the following warning 

> Importing PMVS workspace (option pmvs_options.txt)...
Reading configuration...
WARNING: Ignoring reference image 00000000.jpg, because it has no source images.
WARNING: Ignoring reference image 00000001.jpg, because it has no source images.
...
WARNING: Ignoring reference image 00000075.jpg, because it has no source images.
Configuration has 0 problems...
Elapsed time: 0.063 [minutes]

However, when I use the colmap version from 17.10.2017  (6a6ca807834223341d1451a900b0e16e544fcb95) then the MVS computation runs successfully and produces a reasonable output

Edit: The input video is a driving video from cityscapes (i.e. has narrow baselines)

**Comment by SBCV** [comment]
I digged a bit deeper into the code and found the reason why the reconstruction fails.

The "old" colmap version computed in colmap/src/mvs/model.cc in Model::ReadFromPMVS(const std::string& path) the following

```
  points.resize(num_points);
  for (int point_id = 0; point_id < num_points; ++point_id) {
    auto& point = points[point_id];

    file >> point.x >> point.y >> point.z;

    int color[3];
    file >> color[0] >> color[1] >> color[2];

    int track_len;
    file >> track_len;
    point.track.resize(track_len);

    for (int i = 0; i < track_len; ++i) {
      int feature_idx;
      float imx, imy;
      file >> point.track[i] >> feature_idx >> imx >> imy;
      CHECK_LT(point.track[i], images.size());
    }
  }
```

In the current version this part is removed, therefore  points is empty.
Therefore
`shared_num_points = model.ComputeSharedPoints();`
 in colmap/src/patch_match.cc in PatchMatchController::ReadProblems() returns an empty list.

Is this change intended? After readding the code, Colmap computes the dense point cloud.

**Comment by ahojnnes** [comment]
Thanks, that was indeed a bug. Fixed it and pushed the change to the dev branch.
