### ISSUE TITLE
Map pixels on 2D image to 3D Coordinate

### ISSUE THREAD

**Issue by bellqlz** [colmap/colmap#303]
Hi,

I would like to map one pixel on the 2D Image to the 3D global coordinate system using R& T matrix in the "images.txt" file and intrinsic parameters in "cameras.txt" file. But the result seems not corrected. Can anyone introduce me how colmap calculate this transformation? Thank you so much.

Fangwen

**Comment by ahojnnes** [comment]
Without a depth, you cannot mal a pixel to a 3D point. Can you describe more precisely what you want to do?

**Comment by ahojnnes** [comment]
Closing this due to lack of feedback. Feel free to follow up and reopen.

**Comment by SarveshRobotics** [comment]
Hello,

I have a similar problem in hand. I have COLMAP for sparse reconstruction of a building. I have camera poses determined from "images.txt". Intrinsics are available in cameras.txt. I want to project some selected 2D points in a 3D world. I do not want to overlay texture over existing 3d point cloud. Hence here is what I was thinking should be enough:

1. Select cameras of interest from "images.txt".
2. Select 2d points in these image that I want to project.
3. Project the 3d point given through:
 let p_2d represent homogeneous 2d coordinate from step 2. and p_3d a homogeneous 3d coordinate:
 so, **`T_inv * K_inv * p_2d = p_3d`** 
 where T_inv is the inverse of the transformation T(transformation from world to specific camera coordinate, obtained from "images.txt")
 
I am not sure why depth information would be needed to transform a 2D point to 3D. What am I missing here?

**Comment by eyildiz-ugoe** [comment]
This feature is quite needed tbh. Colmap should have a facility that allows users to correlate a pixel from a sample image to its projected point in the pointcloud and vice versa. If the camera parameters are figured out anyway, this must be definitely possible.

**Comment by ThakurSarveshGit** [comment]
Hi,

I had documented my approach here: https://math.stackexchange.com/a/4405154
I am using a constant depth scale factor instead of the actual depth provided by COLMAP.

Check issue  #1476
