### ISSUE TITLE
Does multi-GPU feature matching work on Windows?

### ISSUE THREAD

**Issue by tesparrow** [colmap/colmap#304]
I am trying to use vocabtree feature matching with around 12k of images and have 3 x 1080ti's runnig on a win10 system and only one GPU seems to be used, is this normal? 

Seems one one card is used in any process, the 1080ti's are installed as single cards with no SLI bridge. 

Tried using -1 and 0,1,2 via the GUI in the gpu_index field with -1 and 3 num_threads. 

Is there any other options to get the GPU's to work, or is it a Windows issue, or a CUDA issue?

**Comment by ahojnnes** [comment]
Are you on thenlatest COLMAP dev version? How are you measuring the GPU load?

**Comment by tesparrow** [comment]
Yes, I am using the pre-built dev binaries, downloaded yesterday  - currently looking at the GPU load in Task Manager - GPU0,1 and 2 are listed, with usage around 25-40 on only one card. GPU Shark lists the same.

**Comment by ahojnnes** [comment]
Okay, looking at your initial post again, it seems that you limited the processing to 3 threads. Seems like this is not enough to do geometric verification at the same speed as feature matching. Hence, all the matching simply happens on the first GPU. I suggest, you just keep num_threads at -1 as well, since that will use all available threads.

**Comment by tesparrow** [comment]
Thanks, Johannes, I have tried -1 on threads and GPU, and only 1 GPU seems to be used with either -1 or 3 on the threads and -1 or 0,1,2 on GPU options.

I will try accessing my GPU's via python to check if not windows or CUDA causing the problems

**Comment by ahojnnes** [comment]
Can you run nvidia-smi.exe to check whether the GPUs are at least allocated by the COLMAP process?

**Comment by ahojnnes** [comment]
Closing this due to lack of feedback. Feel free to follow up and reopen.

**Comment by tesparrow** [comment]
Sorry - been running tests,  I have updated the CUDA drivers and toolkit and now seems to be working with 2 cards, I have been running the tests using 2 of the 3 cards (I took one out as I thought it may be a power issue, so will add the 3rd card back in and see if all 3 are being used)

**Comment by ahojnnes** [comment]
Great to hear, keep me updated.
