### ISSUE TITLE
Issue when missing curl or OpenSSL

### ISSUE THREAD

**Issue by lkneip-bdai** [colmap/colmap#3052]
When missing curl or OpenSSL, DOWNLOAD_ENABLED is automatically set to OFF and COLMAP_DOWNLOAD_ENABLED will not be defined. This should simply build Colmap without download functionality. Instead, it raises a compiler error because the guards in util/file.cc are misplaced. Notably, it will still try to compile function "DownloadAndCacheFile" (line 380), which depends on ComputeSHA256() and DownloadFile(url).

**Comment by ahojnnes** [comment]
Thanks Laurent. Fixed here: https://github.com/colmap/colmap/pull/3053
