### ISSUE TITLE
Compiling Colmap on Nvidia Jetson TX2

### ISSUE THREAD

**Issue by KarimHassanieh** [colmap/colmap#306]
Hi has anyone tried compiling COLMAP on the NVIDIA JETSON TX2 with sucucess ? I have tried doing so but keep getting this error when compiling " cc: error: unrecognized command line option ‘-mfpmath=sse’ " 
regards

**Comment by ahojnnes** [comment]
Did you checkout this post on Google Groups: https://groups.google.com/forum/#!topic/colmap/UVxRoU3ggBE ?

**Comment by KarimHassanieh** [comment]
Hi Mr. Johannes 
Thanks for the tip but its a bit confusing to the specific  steps I need to do to particularly resolve the issue.Its not that clear to me

**Comment by KarimHassanieh** [comment]
ok got it to work its working now with some changes  :D

**Comment by ahojnnes** [comment]
Would you be able to share those changes with me and other people please? You could either send a PR or send me instructions here that I will incorporate. Thanks!

**Comment by KarimHassanieh** [comment]
Hi Johannes 
Ofcourse I'd like to share them,I did a fork on the changes done as there were some lines i deleted  (  https://github.com/KarimHassanieh/JetsonTX2-COLMAP-Structure-From-Motion-Library) , so im afraid if this will impact compiling the orginal source code.. however consider me at full disposal to assist based on your advice and how to proceed .
thanks

**Comment by ahojnnes** [comment]
Would you mind squashing all your commits into one commit, so I can have a better overview of your changes? Thanks!
