### ISSUE TITLE
pycolmap: Point2D.point3D_id cannot be assigned

### ISSUE THREAD

**Issue by ahojnnes** [colmap/colmap#3070]
```
>>> import pycolmap
>>> p = pycolmap.Point2D()
>>> p.point3D_id = -1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (self: pycolmap._core.Point2D, arg0: int) -> None

Invoked with: Point2D(xy=[0, 0], point3D_id=-1), -1
```

**Comment by B1ueber2y** [comment]
This was a long-standing issue not only for point2d but also for ``camera.camera_id``, ``image.image_id``, etc. The reason is that Pybind11 does not support auto casting from int to uint. Yes we should fix it.

**Comment by B1ueber2y** [comment]
A temporary workaround could be:
```
import pycolmap
import ctypes
p = pycolmap.Point2D()
p.point3D_id = ctypes.c_uint32(-1).value
```

**Comment by B1ueber2y** [comment]
> A temporary workaround could be:
> 
> ```
> import pycolmap
> import ctypes
> p = pycolmap.Point2D()
> p.point3D_id = ctypes.c_uint32(-1).value
> ```

Update: this is not correct, as point3D_id is uint64_t rather than uint32_t. However,  ``p.point3D_id = ctypes.c_uint64(-1).value`` does not seem to work.

**Comment by B1ueber2y** [comment]
Another update (sorry): something messed up in my Python environment. After fixing it ``p.point3D_id = ctypes.c_uint64(-1).value`` does work for me.
