### ISSUE TITLE
Compilation problem in Debug on VS2017

### ISSUE THREAD

**Issue by kahlan78** [colmap/colmap#308]
Hi,
i tried to build colmap in debug x64 using vs2017. I get this error:

> 1>------ Inizio compilazione: Progetto: ZERO_CHECK, Configurazione: Debug x64 ------
> 1>Checking Build System
> 1>CMake does not need to re-run because D:/Progetti/PV-INSPECTOR/TEST/COLMAP/CODE/build/CMakeFiles/generate.stamp is up-to-date.
> 1>CMake does not need to re-run because D:/Progetti/PV-INSPECTOR/TEST/COLMAP/CODE/build/src/CMakeFiles/generate.stamp is up-to-date.
> 1>CMake does not need to re-run because D:/Progetti/PV-INSPECTOR/TEST/COLMAP/CODE/build/src/base/CMakeFiles/generate.stamp is up-to-date.
> 1>CMake does not need to re-run because D:/Progetti/PV-INSPECTOR/TEST/COLMAP/CODE/build/src/controllers/CMakeFiles/generate.stamp is up-to-date.
> 1>CMake does not need to re-run because D:/Progetti/PV-INSPECTOR/TEST/COLMAP/CODE/build/src/estimators/CMakeFiles/generate.stamp is up-to-date.
> 1>CMake does not need to re-run because D:/Progetti/PV-INSPECTOR/TEST/COLMAP/CODE/build/src/exe/CMakeFiles/generate.stamp is up-to-date.
> 1>CMake does not need to re-run because D:/Progetti/PV-INSPECTOR/TEST/COLMAP/CODE/build/src/ext/CMakeFiles/generate.stamp is up-to-date.
> 1>CMake does not need to re-run because D:/Progetti/PV-INSPECTOR/TEST/COLMAP/CODE/build/src/ext/FLANN/CMakeFiles/generate.stamp is up-to-date.
> 1>CMake does not need to re-run because D:/Progetti/PV-INSPECTOR/TEST/COLMAP/CODE/build/src/ext/Graclus/CMakeFiles/generate.stamp is up-to-date.
> 1>CMake does not need to re-run because D:/Progetti/PV-INSPECTOR/TEST/COLMAP/CODE/build/src/ext/LSD/CMakeFiles/generate.stamp is up-to-date.
> 1>CMake does not need to re-run because D:/Progetti/PV-INSPECTOR/TEST/COLMAP/CODE/build/src/ext/PBA/CMakeFiles/generate.stamp is up-to-date.
> 1>CMake does not need to re-run because D:/Progetti/PV-INSPECTOR/TEST/COLMAP/CODE/build/src/ext/PoissonRecon/CMakeFiles/generate.stamp is up-to-date.
> 1>CMake does not need to re-run because D:/Progetti/PV-INSPECTOR/TEST/COLMAP/CODE/build/src/ext/SiftGPU/CMakeFiles/generate.stamp is up-to-date.
> 1>CMake does not need to re-run because D:/Progetti/PV-INSPECTOR/TEST/COLMAP/CODE/build/src/ext/SQLite/CMakeFiles/generate.stamp is up-to-date.
> 1>CMake does not need to re-run because D:/Progetti/PV-INSPECTOR/TEST/COLMAP/CODE/build/src/ext/VLFeat/CMakeFiles/generate.stamp is up-to-date.
> 1>CMake does not need to re-run because D:/Progetti/PV-INSPECTOR/TEST/COLMAP/CODE/build/src/feature/CMakeFiles/generate.stamp is up-to-date.
> 1>CMake does not need to re-run because D:/Progetti/PV-INSPECTOR/TEST/COLMAP/CODE/build/src/mvs/CMakeFiles/generate.stamp is up-to-date.
> 1>CMake does not need to re-run because D:/Progetti/PV-INSPECTOR/TEST/COLMAP/CODE/build/src/optim/CMakeFiles/generate.stamp is up-to-date.
> 1>CMake does not need to re-run because D:/Progetti/PV-INSPECTOR/TEST/COLMAP/CODE/build/src/retrieval/CMakeFiles/generate.stamp is up-to-date.
> 1>CMake does not need to re-run because D:/Progetti/PV-INSPECTOR/TEST/COLMAP/CODE/build/src/sfm/CMakeFiles/generate.stamp is up-to-date.
> 1>CMake does not need to re-run because D:/Progetti/PV-INSPECTOR/TEST/COLMAP/CODE/build/src/tools/CMakeFiles/generate.stamp is up-to-date.
> 1>CMake does not need to re-run because D:/Progetti/PV-INSPECTOR/TEST/COLMAP/CODE/build/src/ui/CMakeFiles/generate.stamp is up-to-date.
> 1>CMake does not need to re-run because D:/Progetti/PV-INSPECTOR/TEST/COLMAP/CODE/build/src/util/CMakeFiles/generate.stamp is up-to-date.
> 2>------ Compilazione ignorata: Progetto: uninstall, Configurazione: Debug x64 ------
> 2>Progetto non selezionato da compilare per la configurazione della soluzione. 
> 3>------ Compilazione ignorata: Progetto: colmap_src, Configurazione: Debug x64 ------
> 3>Progetto non selezionato da compilare per la configurazione della soluzione. 
> 4>------ Inizio compilazione: Progetto: colmap, Configurazione: Debug x64 ------
> 4>controllers.lib(automatic_reconstruction.obj) : error LNK2019: riferimento al simbolo esterno "public: __cdecl colmap::mvs::PatchMatchController::PatchMatchController(struct colmap::mvs::PatchMatchOptions const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0PatchMatchController@mvs@colmap@@QEAA@AEBUPatchMatchOptions@12@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@11@Z) non risolto nella funzione "private: void __cdecl colmap::AutomaticReconstructionController::RunDenseMapper(void)" (?RunDenseMapper@AutomaticReconstructionController@colmap@@AEAAXXZ)
> 4>D:\Progetti\PV-INSPECTOR\TEST\COLMAP\CODE\build\src\exe\Debug\colmap.exe : fatal error LNK1120: 1 esterni non risolti
> 4>Compilazione progetto "colmap.vcxproj" NON COMPLETATA.
> 5>------ Compilazione ignorata: Progetto: INSTALL, Configurazione: Debug x64 ------
> 5>Progetto non selezionato da compilare per la configurazione della soluzione. 
> ========== Compilazione: 1 completate, 1 non riuscite, 19 aggiornate, 3 ignorate ==========

Any ideas? 
Tks

**Comment by ahojnnes** [comment]
I do not speak Italian. I can try and check compilation under VS2017 later this week. It works for sure under VS2013 and VS2015.

**Comment by ahojnnes** [comment]
This is a bug in CMake and is addressed in https://gitlab.kitware.com/cmake/cmake/merge_requests/1631

**Comment by kahlan78** [comment]
Sorry, but the problem is not with CMake and Cuda (because i disabled the cuda features). 
The problem is during the linking step of the "colmap" project. 

> 4>controllers.lib(automatic_reconstruction.obj) : error LNK2019: riferimento al simbolo esterno "public: __cdecl colmap::mvs::PatchMatchController::PatchMatchController(struct colmap::mvs::PatchMatchOptions const &,class std::basic_string<char,struct std::char_traits,class std::allocator > const &,class std::basic_string<char,struct std::char_traits,class std::allocator > const &,class std::basic_string<char,struct std::char_traits,class std::allocator > const &)" (??0PatchMatchController@mvs@colmap@@qeaa@AEBUPatchMatchOptions@12@AEBV?$basic_string@DU?$char_traits@D@std@@v?$allocator@D@2@@std@@11@Z) non risolto nella funzione "private: void __cdecl colmap::AutomaticReconstructionController::RunDenseMapper(void)" (?RunDenseMapper@AutomaticReconstructionController@colmap@@aeaaxxz)
> 4>D:\Progetti\PV-INSPECTOR\TEST\COLMAP\CODE\build\src\exe\Debug\colmap.exe : fatal error LNK1120: 1 esterni non risolti

**Comment by lvyv** [comment]
I’ve got the same problem. 
You should check the file: colmap\src\mvs\CMakeLists.txt, and 
add the required cc file to the COLMAP_ADD_LIBRARY section, maybe the patch_match.cc .

**Comment by kahlan78** [comment]
Because i disabled cuda, i cannot add the patch_match.cc (this file include the the patch_match_cuda.h).
The strange behavoir is that in Release x64 configuration the solution is built without errors.

**Comment by lvyv** [comment]
I have spent quite some days on it, finished following works.
1. download the prebuilt COLMAP-3.4-windows-no-cuda.zip, unzip it and run it according to the [article](https://pfalkingham.wordpress.com/2017/04/04/photogrammetry-testing-8-colmap/). But colmap.exe crashed when i Head to Processing->feature extraction. 
2. git clone the project and make a x64 Release build(msvc 2015+win7,no cuda). Yet colmap crashed at the same point.
3. build a debug version(msvc 2015+win7,no cuda), crashed too!
now, i am stepping into the source code to check.
To make the linker go through, I comment following lines in "colmap\src\controllers\automatic_reconstruction.cc"

#if 0
    {
      mvs::PatchMatchController patch_match_controller(
          *option_manager_.dense_stereo, dense_path, "COLMAP", "");
      active_thread_ = &patch_match_controller;
      patch_match_controller.Start();
      patch_match_controller.Wait();
      active_thread_ = nullptr;
    }
#endif
