### ISSUE TITLE
Was unable to run windows binary (w/CUDA) on remote machine connected via RDP.

### ISSUE THREAD

**Issue by spon000** [colmap/colmap#309]
Works fine if I run it on the machine directly,

Here are the messages. It's something with OpenGL.

> Failed to load libEGL (The specified module could not be found.)
> QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
> Failed to load opengl32sw.dll (The specified module could not be found.)
> Failed to load and resolve WGL/OpenGL functions
> Failed to load libEGL (The specified module could not be found.)
> QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
> Failed to load opengl32sw.dll (The specified module could not be found.)
> Failed to load and resolve WGL/OpenGL functions
> QOpenGLWidget: Failed to create context
> Failed to load libEGL (The specified module could not be found.)
> QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
> Failed to load opengl32sw.dll (The specified module could not be found.)
> Failed to load and resolve WGL/OpenGL functions
> QOpenGLWidget: Failed to create context
> Failed to load libEGL (The specified module could not be found.)
> QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
> Failed to load opengl32sw.dll (The specified module could not be found.)
> Failed to load and resolve WGL/OpenGL functions
> QOpenGLWidget: Failed to create context
> composeAndFlush: makeCurrent() failed
> composeAndFlush: makeCurrent() failed
> composeAndFlush: makeCurrent() failed
> composeAndFlush: makeCurrent() failed

**Comment by ahojnnes** [comment]
Windows remote desktop only allows for the most basic OpenGL functionality and you thus cannot open the GUI. The command line functionality should be fully functional though.

**Comment by spon000** [comment]
Thanks for the information.

Have a great day,
Patrick
