### ISSUE TITLE
Error on running MVS

### ISSUE THREAD

**Issue by saedrna** [colmap/colmap#31]
Hi,

Colmap is awesome, especially in the SFM accuracy! However, MVS is not quite stable. And I have encountered quite often termination without warning.

After undistortion and click the Stereo Button, the program is terminated occasionally with the following log on console, (using 2,0 binaries in Windows X64, downloaded from your homepage)

```
Initialization: 0.2078s
 Sweep 1: 2.4169s
cudaCheckError() with sync failed at C:/Users/jschoenb/Development/colmap/src/.\mvs/gpu_mat.h:324 : unknown error
QObject::~QObject: Timers cannot be stopped from another thread
```

Any ideas on how to solve that? The problem is quite common when stereo is running and I switch to other program.

Han

**Comment by ahojnnes** [comment]
Hi,

This might be caused by the automatic GPU timeout in Windows. Are you using the same GPU for your display and the computation?

Thanks,
Johannes

**Comment by ahojnnes** [comment]
@saedrna Please check if this helps: https://colmap.github.io/faq.html#fix-gpu-freezes-and-timeouts-during-dense-reconstruction and let me know. Thanks!

**Comment by saedrna** [comment]
@ahojnnes , thanks, I think the problem is related to TDR. My hardware configuration is an Nvidia and an Intel card.
I think the general display from the main monitor is using Intel card, and any interaction in the main monitor is fast and fluent withoud causing any problem. 
But the second monitor is using the Nvidia card, and operation on it is spiky and sometimes causes the problem.

**Comment by ahojnnes** [comment]
Thanks for the feedback, let me know if anything else is unclear.
