### ISSUE TITLE
`download_zipfile()` missing 1 required positional argument: `md5_hash` in `scripts/python/build.py`

### ISSUE THREAD

**Issue by shwina** [colmap/colmap#311]
Missing argument in call to function `download_zipfile`:

https://github.com/colmap/colmap/blob/dev/scripts/python/build.py#L217

**Comment by ahojnnes** [comment]
Fixed with https://github.com/colmap/colmap/commit/6e71494270efd5b525d42338e43a58ce13ed3ace

Thanks for the bug report.
