### ISSUE TITLE
"CUDA not available" on macOS 10.13. with CUDA 387.128

### ISSUE THREAD

**Issue by Joschka1** [colmap/colmap#312]
Hi, 
on my macOS 10.13 with CUDA 387.128 with an Geforce GTX 1060, the stable and the dev build of colmap always throws an warning to me. 
`WARNING: Skipping dense reconstruction because CUDA is not available`
And reconstruct a dense cloud is not possible. 

best, 
Joschka

**Comment by ahojnnes** [comment]
Can you show the output of CMake in the build folder?

**Comment by Joschka1** [comment]
I just downloaded the executables. But i will try to build and test it again.

**Comment by ahojnnes** [comment]
@Joschka1 The builds on the website for Mac are without CUDA. I will add a notice there to avoid confusion in the future. For you to get CUDA support on Mac, you would have to compile yourself.

**Comment by Joschka1** [comment]
ohhh, ok. :D
