### ISSUE TITLE
Colmap pipeline not runnig on ATI video card

### ISSUE THREAD

**Issue by kahlan78** [colmap/colmap#313]
Hi,
i built successfully Colmap disabling CUDA support on Win 10 using VS2017 in Release config.
Using a PC with ATI video card (AMD HD 6900), the pipeline doesn't work because the shading language version. So i edited the class ProgramGLSL adding the correct GLSL version in the fragment shaders code. Thanks to this change, the features extraction runs but no features are detected (without any errors).
Any ideas? 
Using the same exe and the same dataset on several PC with NVIDIA video cards, it works fine.
Tks

**Comment by ahojnnes** [comment]
I don't know what "the correct GLSL version" is and what changes you made. For the worst, you can disable GPU feature extraction and run it on the CPU.

**Comment by kahlan78** [comment]
Hi @ahojnnes,
on my ATI video card, if i run the github master code enabling the GPU feature, I get the following error for the feature step:

> WARNING: 0:1: warning(#437) Extension GL_ARB_texture_rectangle or version 1.10 is requried'by sampler2DRect'.
> ERROR: error(#272) Implicit version number 110 not supported by GL3 forward compatible context
> ERROR: error(#273) 1 compilation errors.  No code generated   

This error occurs because the shaders used in colmap doesn't contain a version declaration. So, the #version​ directive must appear before anything else in a shader, save for whitespace and comments. If a #version​ directive does not appear at the top, then it assumes 1.10, which is almost certainly not what you want (https://www.opengl.org/wiki/Core_Language_%28GLSL%29#Version).
I changed the code inserting the glsl version read from my video card (4.40). In this way, the features extractor runs but no features are detected. I prefer to use GPU features of colmap instead of CPU (too slow).

Any ideas? Tks

**Comment by ahojnnes** [comment]
No ideas from my side for this issue. Could you resolve it in the meantime?

**Comment by ahojnnes** [comment]
Closing this due to lack of feedback. Feel free to reopen.

**Comment by DavidBoxall** [comment]
I'm getting similar errors when running RUN_TESTS.bat under Windows 10 v.1909 (build 8363.900) on a machine with a Radeon HD 6450:
[errors.txt](https://github.com/colmap/colmap/files/4784049/errors.txt)
Is there a fix?
