### ISSUE TITLE
Map pixels from 2D images to 3D point clouds

### ISSUE THREAD

**Issue by ColeKOP** [colmap/colmap#316]
hi, 
I would like to map one pixel on the 2D Image to the 3D global coordinate system using R& T matrix in the "images.txt" file and intrinsic parameters in "cameras.txt" file as well as the depth map in the stereo folder. 
For example, if I know the coordinate of one pixel on 2D image, how can I calculate the corresponding coordinate on 3D point cloud (the meshed.ply file) in world frame?

Thank you ahead.

**Comment by ahojnnes** [comment]
See https://github.com/colmap/colmap/blob/dev/src/mvs/fusion.cc#L351
