### ISSUE TITLE
Building from source fails on Ubuntu 16.04.3 LTS

### ISSUE THREAD

**Issue by nerdgilbert** [colmap/colmap#318]
Hi all,

I am attempting to build from source following the description [here](https://colmap.github.io/install.html).

The result of `mkdir build && cd build && cmake ..` is (emphasis mine):
<pre><code>
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAS_SSE_EXTENSION
-- Performing Test HAS_SSE_EXTENSION - Success
-- Performing Test HAS_SSE2_EXTENSION
-- Performing Test HAS_SSE2_EXTENSION - Success
-- Performing Test HAS_SSE3_EXTENSION
-- Performing Test HAS_SSE3_EXTENSION - Success
-- Performing Test HAS_SSE41_EXTENSION
-- Performing Test HAS_SSE41_EXTENSION - Success
-- Performing Test HAS_SSE42_EXTENSION
-- Performing Test HAS_SSE42_EXTENSION - Success
-- Performing Test HAS_AVX_EXTENSION
-- Performing Test HAS_AVX_EXTENSION - Success
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   regex
--   system
--   unit_test_framework
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0") 
-- Found Eigen3
--   Includes : /usr/include/eigen3
-- Found FreeImage
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
-- Found Glog
--   Includes : /usr/local/include
--   Libraries : /usr/local/lib/libglog.so
-- Found installed version of Eigen: /usr/lib/cmake/eigen3
-- Found required Ceres dependency: Eigen version 3.2.92 in /usr/include/eigen3
-- Found installed version of glog: /home/gilbert/workspace/personal/pbrt-v3/build/src/ext/glog
-- Detected glog version: 0.3.4
-- Found required Ceres dependency: glog
-- Performing Test GFLAGS_IN_GOOGLE_NAMESPACE
-- Performing Test GFLAGS_IN_GOOGLE_NAMESPACE - Success
-- Found required Ceres dependency: gflags
-- Found Ceres version: 1.13.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, OpenMP, Multithreading]
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so   
-- Found Glew
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- Found Threads: TRUE  
-- Found Qt 5.5.1
-- Build type not specified, using Release
-- Enabling OpenMP support
-- Disabling interprocedural optimization
-- Autodetected CUDA architecture(s): 6.1 
-- Enabling CUDA support (version: 8.0, archs: sm_61)
-- Enabling OpenGL support
-- Disabling profiling support
-- Found Glog
--   Includes : /usr/local/include
--   Libraries : glog::glog
-- Configuring done
CMake Warning (dev) at cmake/CMakeHelper.cmake:198 (add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  <b>Target "colmap" links to target "glog::glog" but the target was not found.</b>
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
Call Stack (most recent call first):
  src/exe/CMakeLists.txt:3 (COLMAP_ADD_EXECUTABLE)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/CMakeHelper.cmake:198 (add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  <b>Target "colmap" links to target "glog::glog" but the target was not found.</b>
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
Call Stack (most recent call first):
  src/exe/CMakeLists.txt:3 (COLMAP_ADD_EXECUTABLE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/gilbert/workspace/third_party/libs/colmap/build
</pre></code>

It seems that CMake is able to find Glog just fine, but for some reason is trying to link to a library called `glog::glog` (which I can't find anywhere in the source tree).

The result of `ldconfig -p | grep glog` is:
```
	libglog.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libglog.so.0
	libglog.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libglog.so
```

Any thoughts? It is late, so it is perfectly possible that I am missing something silly. I am looking at it now and could this be a CMake error? Specifically, I am intrigued by these lines from the `cmake ..` output:
```
-- Found Glog
--   Includes : /usr/local/include
--   Libraries : glog::glog
-- Configuring done
CMake Warning (dev) at cmake/CMakeHelper.cmake:198 (add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.
```
@ahojnnes which CMake version do you require? I didn't quite see any version requirements. I do see you recommend installing using `sudo apt-get install cmake` and that implies that you are using cmake version 3.5.1, as indicated from [here](https://packages.ubuntu.com/xenial/cmake). 

For reference: 

| Program | Version |
| --- | --- |
| CMake | 3.10.1 |
| glog | 0.3.4 |

Please let me know if you require any further information, or if I can test anything on my machine.

**Comment by ahojnnes** [comment]
I didn't test with CMake 3.10.X. Could you resolve the issue already? Did you install ceres-solver with miniglog support or full glog?

**Comment by nerdgilbert** [comment]
Not fixed, but it seems to be an issue with my glog install.

Thanks for the reply. Closing.
