### ISSUE TITLE
Enforce geometric reconstruction with dense_stereo

### ISSUE THREAD

**Issue by gT-mike** [colmap/colmap#319]
Hi guys,

I wondered if there is a way to force geometric reconstruction for the depth maps of all images passed to colmap for reconstruction. I set "--DenseStereo.geom_consistency true" but only for the first 90 images of the 900 that I used as input I had a *geometric.bin in the depth_maps folder.

Thanks,
mike

**Comment by ahojnnes** [comment]
That can only happen if the reconstruction was not finished or it crashed due to insufficient GPU memory, etc.

**Comment by gT-mike** [comment]
Thanks for the info, yip that's actually what happened .. fixed :)

**Comment by runa91** [comment]
Hi, I have some reconstruction results and would like to calculate depth maps including masks for where the predictions are good. How can I take the *geometric.bin (not photometric.bin) and obtain the corresponding depth map?

**Comment by ahojnnes** [comment]
What do you mean by “obtain”? If you mean reading the in Python or Matlab, please have a look at the documentation or scripts/python/read_dense.py or scripts/Matlab/read_dense.m
