### ISSUE TITLE
Database widget display error

### ISSUE THREAD

**Issue by json87** [colmap/colmap#32]
Hi, 

There is a database display error  in file database_management_widget.cc  
line number 333

    table_widget_->setItem(
        i, 6, new QTableWidgetItem(QString::number(image.QvecPrior(2))));

**Comment by ahojnnes** [comment]
Fixed in https://github.com/colmap/colmap/commit/f8f4bce69e740efa7a8e3dde99b9818addb9d57c

Thanks!
