### ISSUE TITLE
Relationship Between Point3D and Final Output

### ISSUE THREAD

**Issue by ColeKOP** [colmap/colmap#321]
Hi,

Can anyone help to explain the relationship between the points in Point3D.txt in Sparse folder and those in the final ply file (meshed.ply)? 

Thanks ahead.

**Comment by ahojnnes** [comment]
``points3D.txt`` are from the sparse reconstruction, ``fused.ply`` from multi-view stereo fusion, and ``meshed.ply`` from meshing the ``fused.ply``. Is that clear enough?

**Comment by ColeKOP** [comment]
HI,

May i know how can i derive the points meshed file from the ones in points3d.txt file?

thank you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ColeKOP** [comment]
I mean how can i relate the points in Point3D.txt file to the final point clouds? Any equations? Thank you.

**Comment by ahojnnes** [comment]
No equations needed, they are in the same coordinate system. Just extract X, Y, Z in points3D.txt.

**Comment by ColeKOP** [comment]
Thank you for the clarification. It means every point in the meshed model can be found in point3D.txt file, right?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ahojnnes** [comment]
No, as mentioned above. ``points3D.txt`` corresponds to the sparse reconstruction and ``meshed.ply`` corresponds to the meshed dense model. I suggest to read through if you are not familiar with these terms: https://colmap.github.io/tutorial.html

**Comment by ColeKOP** [comment]
I will check. Thank you for your insight.
