### ISSUE TITLE
Colmap closes itself

### ISSUE THREAD

**Issue by blackpottery** [colmap/colmap#322]
Hello, 
Firstly I would like to say I'm completely new using this software and not good at all with computers, so I beg for your patience if I don't understand much of the things you ask me for. 
After some years using Photoscan I wanted to try COLMAP. Once I get to the dense reconstruction it simply closes itself... no explanation, no info about the problem (that I'm able to see). 
I tried changing parameters in the firt steps of the proccess -as the max_num_feature-, but nothing changes. 
I tried also to verify if my dedicated GPU is working for the software but here I had troubles: I have an nvidia GTX940m, but when I try to select it for the program, I cannot make the assignment. It doesn't appear in the list, eventhough I tried to find it through mi folders. 
Could you please help me? I feel really lost

**Comment by ahojnnes** [comment]
This is probably caused by this https://colmap.github.io/faq.html#fix-gpu-freezes-and-timeouts-during-dense-reconstruction or https://colmap.github.io/faq.html#reduce-memory-usage-during-dense-reconstruction

**Comment by blackpottery** [comment]
Thanks for your response, but as I said, I already tried those. Even the automathic process doesn't work on my laptop. And the instructions to increase the delay of the gpu don't work on mine. It's windows 10, the only options it gives me is changing the configuration for some programs... but only if they are .exe, so it doesn't even recognize Colmap... I'm absolutely lost... I've never have problems with Photoscan, even with hundreds of pictures, and here with ten pictures it is impossible to keep from stereo step

**Comment by ahojnnes** [comment]
I don't know the reason for the failure. Can you run the pipeline from the command-line and post the output? This would give me some more information about potential failure reasons.

**Comment by blackpottery** [comment]
I'm so sorry and I beg your pardon because I don't even know how to do it... so sorry. 
Where can I learn how to do it as you say?
I'm not nearly a programmer... Don't even know what to write

**Comment by ahojnnes** [comment]
The command-line interface is documented here: https://colmap.github.io/cli.html

**Comment by blackpottery** [comment]
Thanks for your patience again... 
I I guess the command-line interface is the right part full of text in the colmap screen, or the black window that opens when I run it. None of them even allow me to write... I'm sorry this surely is upsetting to you... but I literally have no clue
