### ISSUE TITLE
Using the geo-registration

### ISSUE THREAD

**Issue by gT-mike** [colmap/colmap#325]
Dear Johannes,

I just wanted to check shortly if I'm using the Geo-registration option correctly:
Suppose I have some 6DOF GT data for each image. Then the x1, y1, z1 values that have to be provided in the text-file are the translation vectors (41, 42, 43 elements of the corresponding transformation matrix) for each image?

Thanks,
mike

**Comment by ahojnnes** [comment]
X, Y, Z should be the location of the camera centers, i.e. the translational part of the camera-to-world transformation.
