### ISSUE TITLE
Reconstruction fails with 7scene examples

### ISSUE THREAD

**Issue by gT-mike** [colmap/colmap#326]
Dear Johannes,

I'm trying to run COLMAP on 7scenes and unfortunately can get no meaningful results on the extracte depth maps.

I run the following commands consequently on seq1 of chess using every fifth frame of the sequence with default COLMAP settings:

a) colmap feature_extractor
b) colmap exhaustive matcher
c) colmap mapper
d) colmap image_undistorter
e) colmap dense_stereo

For reconstruction I manually write the patch-match.cfg as description in the FAQ, so that for every 2d image the previous and following frame of the sequence are used. Afterwards I extract the depth maps from the "../dense/stereo/depth_maps" folder with the python scripts which are provided with COLMAP.

However, the resulting depth maps look completely noisy. Here is an example:

Any idea why the pipeline seems to fail completely in this case?

Thanks,
mike

![image](https://user-images.githubusercontent.com/37045813/37282689-9c255066-25f5-11e8-99cf-79d2e340bfbc.png)

**Comment by ahojnnes** [comment]
As far as I remember, the 7scenes dataset is a video, so consecutive frames will have too small of a baseline. Also, COLMAP works best if you provide it with many images. So, just add T+-20 images or so. However many you can fit into GPU memory.

**Comment by gT-mike** [comment]
Thanks for the quick reply. In order to understand your answer correctly:

a) regarding your first sence:
What would you recommand as good base value for the number of images to use for the full scene ~100, ~200, ~500, ~1000, ~2000 or more? 
Is it better for COLMAP to have unordered images or could one make use of the consecutive frame structure (like it is given in a video)?

b) regarding your second sentence:
You suggest that for each image that should be reconstructed in the patch-match.cfg file I should have something like:
" ...
frame 20
frame0, frame1, .., frame19, frame20, frame21, frame39, frame40
..."
Is that correct?

Thank you!
mike

**Comment by ahojnnes** [comment]
~30 images per reference image should be fine. I don't know the frame-rate of the dataset but it might make sense to not use the direct neighbors but skip some in between in order to get larger baselines.

**Comment by gT-mike** [comment]
Thank you very much. It seems to work now. However, although during dense_stereo the "--DenseStereo.filter" parameter is true (as per default) there are still regions where no filtering is happening (also for the south building dataset as in your paper). Is the filtering only a "on/off" parameter or can one tune the filtering somehow with the other parameters related to filtering? 

here is an example:
![image](https://user-images.githubusercontent.com/37045813/37494402-f19f762e-28a8-11e8-9ddd-b71e4cdd5a3b.png)

**Comment by ahojnnes** [comment]
Can you post the filename for the image that you show as an example? Is it the photometric or the geometric output?

**Comment by gT-mike** [comment]
Sure: It is P1180141 and the output was photometric. Thanks for the point. I checked the geometric output and it is actually pretty much noise free (execept for the trees) - see below. Nonetheless, going back to the chess example, for instance the display of the monitor or the single colored gray area of the table below the chessboard still come out rather noise (s. attached fotos) - and yes, I just checked, it is the geometric output. Is there a good way to deal with that?
![image](https://user-images.githubusercontent.com/37045813/37514464-46cb303e-2908-11e8-851c-f85e5cf8614b.png)

![image](https://user-images.githubusercontent.com/37045813/37514404-2406d6fc-2908-11e8-8781-d87597e4d4e1.png)

![image](https://user-images.githubusercontent.com/37045813/37514387-19e88a62-2908-11e8-8709-3b3cb404569b.png)

**Comment by ahojnnes** [comment]
Check the following options:
```
  --DenseStereo.filter arg (=1)
  --DenseStereo.filter_min_ncc arg (=0.10000000149011612)
  --DenseStereo.filter_min_triangulation_angle arg (=3)
  --DenseStereo.filter_min_num_consistent arg (=2)
  --DenseStereo.filter_geom_consistency_max_cost arg (=1)
```

If you use the ``dense_fuser`` those noisy areas should mostly disappear in the final 3D point cloud and the filtering does not need to be perfect initially.

**Comment by gT-mike** [comment]
Thanks you! Are there reasonable ranges concerning the parameters? I would run a sweep then and see what combination give me the best results.

Will the dense_fuser also affect the depth_maps? I am mainly intersted in the depth maps not in the final 3D point cloud - can the depth maps also be reconstructed from the point cloud after running the fuser?

**Comment by ahojnnes** [comment]
The dense_fuser does not change the depth maps. The depth maps could be recovered from the fused point cloud using the consistency graph that is exported using ``--DenseStereo.write_consistency_graph``.

**Comment by gT-mike** [comment]
Thanks, I will try and see if it works

**Comment by gT-mike** [comment]
So, do I understand it right?

a) I run dense_stereo (with --DenseStereo.write_consistency_graph 0)
b)  Than I run dense_fuser 
c)  At last, I run dense_stereo with -DenseStereo.write_consistency_graph 1 and have to look at the consistency graphs? Is it required to fuse the depth maps with the information from the consistency graphs?

Thanks!

**Comment by ahojnnes** [comment]
No, you would have to extract the fused depth maps manually by writing your own code. This is not implemented. It is probably easiest to modify the ``dense_fuser`` code to store only fused point clouds in a new set of depth maps.

**Comment by ahojnnes** [comment]
Closing this, feel free to reopen if there are other questions.
