### ISSUE TITLE
Share the intrinsic and extrinsic camera parameter at every reconstruction.

### ISSUE THREAD

**Issue by Gorokke** [colmap/colmap#327]
Hi,
we are using fixed cameras, and sometimes we want to fix all the intrinsic and extrinsic camera parameters and re-run the reconstruction.

Is there any methods to share all the intrinsic and extrinsic parameters at every reconstruction using command line? (I mean automatically?)

Thanks for your comments and ideas, in advance.

**Comment by ahojnnes** [comment]
I don't quite understand what you mean by sharing intrinsic and extrinsic parameters. Sharing and fixing intrinsics is described here: https://colmap.github.io/faq.html#share-intrinsics

Sharing extrinsics doesn't make sense to me at the moment, unless you give more details. Fix the intrinsics means you would only recover the 3D structure from given camera poses?

**Comment by Gorokke** [comment]
Hi,

Yes, " only recover the 3D structure from given camera poses (extrinsic and intrinsic)" is what exactly I meant, thanks. In our system, we can fix the intrinsic and extrinsic parameter because the cameras' location is fixed.

For example, after obtaining extrinsic and intrinsic parameter using COLMAP, we save that parameter and close the colmap. And then, can we reconstruct sparse 3D, dense 3D and dense mesh with exactly same intrinsic and extrinsic parameters for the different set of images? (again, the camera location is fixed)

I really really appreciate your help, and hopefully, there is a solution.

Thanks!!

**Comment by ahojnnes** [comment]
Checkout the ``image_triangulator`` command, which does exactly what you want. It recovers a sparse model from given intrinsics/extrinsics. Afterwards you can run ``dense_stereo`` as usual.

**Comment by Gorokke** [comment]
Thank you very much!

I could do that with 'point_triangulator'. !!!  thank you!
