### ISSUE TITLE
Colmap latest dev cuda or cpu dense problem

### ISSUE THREAD

**Issue by lowkickfighter** [colmap/colmap#328]
Hello everyone. I would like to thank you for your beatifull program.

Two questions and problems until now.

1) why there are two versions of colmap (with or without cuda) even if you cannot run dense in non cuda version?  Isnt a little uselless??
2) I have cuda6 (my graphic card support only this) with latest drivers on and checked that plays good on several software. Colmap cant run cuda on my system..  So this is the paradox. If i run non cuda version cant dense because there is not cuda...  If run cuda version cant work properly (shuts down) because of a message "Cuda isnt install in your system"...  i have some screenshots but cant upload here.

so what info do you need to help me a little bit?

Any help guys?   Thank you!

**Comment by ahojnnes** [comment]
1. Not everyone is interested in dense reconstruction but only requires the output of earlier steps in the pipeline. This software is mostly for research purposes in the end. Hence, the different versions.
2. You need at least CUDA 7 and a relatively strong GPU -- there is not hard limit but I recommend at least 2GB of GPU memory to do useful things in the dense stage. If you don't have access to a required device, you can use alternative dense reconstruction software based on COLMAP's sparse reconstruction, see https://colmap.github.io/tutorial.html#dense-reconstruction
