### ISSUE TITLE
Geo registration provides unsatisfactory results 

### ISSUE THREAD

**Issue by timcoolmode** [colmap/colmap#329]
Model align has a .3 error and with a total size of 4 (-2 to 2) as you can assume this provides results that aren't great. I currently have created a scrip that pulls every camera's locational information in and that didn't help. Would scaling up the entire scene help Or how do I get better accuracy?

**Comment by timcoolmode** [comment]
So the full process I'm doing is the following

Feature Extractor - feature_extractor  --database_path %sdatabase.db --image_path %s
Exhaustive matcher - exhaustive_matcher --database_path %sdatabase.db
mapper - mapper --database_path %sdatabase.db --image_path %s --export_path %ssparse
mesh aligner - model_aligner --input_path %s --output_path %s --ref_images_path %s --robust_alignment_max_error=1

I've tried to decrease the max error and it doesn't seem to do much if not make things worse.

**Comment by timcoolmode** [comment]
Here is the camera info

01.png 2.10585 -0.903953 2.71948
12.png -3.10922 -1.65491 4.07629
07.png -2.91777 -0.549923 3.73743
02.png 3.0762 -1.0765 4.80244
06.png 2.98062 -1.41523 3.75966
14.png 1.29615 -0.761421 2.35385
10.png -1.66874 -1.24084 2.46644
13.png 0.563222 -0.816436 1.87316
09.png -1.20348 -0.723503 2.07848
11.png -2.3992 -1.62673 3.28604
15.png -0.229744 -0.531058 1.88999
03.png 2.46125 -0.973614 3.13779
08.png -3.41273 -1.39403 5.45097

**Comment by ahojnnes** [comment]
You also have to set ``--robust_alignment 1``, otherwise the alignment is not robustified.

**Comment by ahojnnes** [comment]
Note that the alignment error is still computed over all images, so a single outlier might result in a large alignment error.

**Comment by timcoolmode** [comment]
The issue of the alignment number isn't as bothersome as the results. Maybe I tell you what I'm looking to do and you can point me in the right direction?

I made a camera rig to capture my children as they grow. My youngest daughter is about 1.5 years old and I want to show this to her when she gets to be 18 of how she grew up. So what I've done is created a pipeline and I have an area in my office where I want to mark where she needs to put her head so that it's in the middle of the arched array. (think of a bunch of webcams all pointed toward one area) I would like to place her in the exact same place every day so that when she grows the doesn't bounce around everywhere. The cameras are taped to the ground and we can assume they will never move and any direction or angle. How do I share the information from the first set of images to the other set of images other than with the use of the alignment tool you provided(which has non exact results) Can I feed the initial results into the database or prior to point generation?
