### ISSUE TITLE
Error when run matches computing

### ISSUE THREAD

**Issue by chuqiaodev** [colmap/colmap#33]
Hi, thank you for providing this useful open source. When I perform matches computing I faced errors shown below:

Matching image [1/8]*** Aborted at 1474416078 (unix time) try "date -d @1474416078" if you are using GNU date ***
PC: @           0x5166f6 colmap::SiftGPUFeatureMatcher::MatchImagePairs()
*** SIGSEGV (@0x0) received by PID 4069 (TID 0x7f190d62c700) from PID 0; stack trace: ***
    @     0x7f193edea3d0 (unknown)
    @           0x5166f6 colmap::SiftGPUFeatureMatcher::MatchImagePairs()
    @           0x517674 colmap::SequentialFeatureMatcher::RunSequentialMatching()
    @           0x5193d6 colmap::SequentialFeatureMatcher::Run()
    @           0x590e2c colmap::Thread::RunFunc()
    @     0x7f193c49bc80 (unknown)
    @     0x7f193ede06fa start_thread
    @     0x7f193bc01b5d clone
    @                0x0 (unknown)

I am wondering without CUDA support, can I run this library? I run the command-line on oracle VM with ubuntu 16.04, the GPU on Host Mac is Intel Iris Pro.

Thank you.

**Comment by ahojnnes** [comment]
You shouldn't run the feature extraction (GPU)/matching in a virtual machine. The library needs a dedicated GPU.  Have you tried running it on your host Mac directly?

**Comment by chuqiaodev** [comment]
OK, thanks, will try on my host Mac later to see what happens.

**Comment by chuqiaodev** [comment]
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   system
--   regex
--   unit_test_framework
-- Found Eigen3: /usr/local/include/eigen3 (Required is at least version "2.91.0")
-- Found Eigen3
--   Includes : /usr/local/include/eigen3
-- Found FreeImage
--   Includes : /usr/local/include
--   Libraries : /usr/local/lib/libfreeimage.dylib
-- Found Glog
--   Includes : /usr/local/include
--   Libraries : /usr/local/lib/libglog.dylib
CMake Error at /usr/local/share/Ceres/CeresConfig.cmake:88 (message):
  Failed to find Ceres - Missing required Ceres dependency: Eigen version
  3.2.9, please set EIGEN_INCLUDE_DIR.
Call Stack (most recent call first):
  /usr/local/share/Ceres/CeresConfig.cmake:214 (ceres_report_not_found)
  CMakeLists.txt:66 (find_package)


CMake Error at CMakeLists.txt:66 (find_package):
  Found package configuration file:

    /usr/local/share/Ceres/CeresConfig.cmake

  but it set Ceres_FOUND to FALSE so package "Ceres" is considered to be NOT
  FOUND.

Build in Mac has this cmake error

**Comment by ahojnnes** [comment]
That means you built Ceres with a different version than what is used by COLMAP. Make sure both use the same version.

**Comment by chuqiaodev** [comment]
fix it by update the eigen verison

**Comment by ahojnnes** [comment]
I interpret this as "fixed it by updating the Eigen version" and assume the issue is resolved.

**Comment by chuqiaodev** [comment]
it works on Mac,  MVS step needs CUDA?

**Comment by ahojnnes** [comment]
Yes.

**Comment by chuqiaodev** [comment]
OK, gotcha. I really appreciate your quick reply. Will try it later on the computer supporting CUDA.
