### ISSUE TITLE
Command line for converting fused.ply to .txt

### ISSUE THREAD

**Issue by Gorokke** [colmap/colmap#330]
Hi,

Is there a command line to convert .ply file (such as fused.ply) to .txt? 
Now, I can convert using user interface by "importing the model as .ply" as "export the model as .txt".
I really appreciate your help if there is a method for converting using command line.

**Comment by ahojnnes** [comment]
No, there is no automated way of converting from PLY to .txt. The workaround you describe loses most information (e.g. normals, visibility, etc.). The PLY file is the output of the dense reconstruction stage while ``points3D.txt`` is the output of the sparse reconstruction stage.

**Comment by Gorokke** [comment]
hmm...Then, is there any your recommendation to convert binary .ply file to ascii .ply file?

**Comment by Gorokke** [comment]
Maybe I should parse, by my self.
