### ISSUE TITLE
Share camera poses

### ISSUE THREAD

**Issue by timcoolmode** [colmap/colmap#332]
I need my models in the exact same area and facing the exact same direction every single time. My cameras will not be moving in any way Is there a way I can share camera poses from one reconstruction to another? I've used the Geo regrestration (even made sure that the images were in ascending order .. Don't think that helped)  and model orientation aligner( tried feeding the first image set in and also the image set that was constructing the mesh as well) The results are incosistant. It will at times do 3 or 4 exactly one on top of each other but out of 10 tries I'll get on average 4 separate results. Things like openmvg have camera poses that (from what I can tell) can be shared. I know reality capture has a feature with things called ground control points where you tell the system 3 separate points from at least 3 separate images and it perfectly aligns the meshes within the same exact space every single time. Is there a way I can do this with your software? By the way I really love working with it and it does an amazing job this is just killing me trying to figure it out sadly :(

**Comment by ahojnnes** [comment]
Are you interested in the sparse and/or dense reconstruction?

**Comment by timcoolmode** [comment]
Directly to the question. Yes I do eventually do dense point cloud and even make meshes.

**Comment by timcoolmode** [comment]
Doesn't the dense point cloud just build off the sparse and the sparse tell the system where the points are?

**Comment by ahojnnes** [comment]
The sparse point cloud is only used to determine the overlap of images and the depth search range. You can specify both manually. Just use the same sparse reconstruction but replace the previous images and either keep the depth search range the same or manually set it using ``--DenseStereo.depth_min`` and ``--DenseStereo.depth_max``. Manually specifying overlapping images is described here: https://colmap.github.io/faq.html#manual-specification-of-source-images-during-dense-reconstruction

**Comment by timcoolmode** [comment]
Ok... I'm a bit lost here. How do I save and share the camera poses from a previously generated model so that my mesh is always in the same place with the same rotation? As described above I've already tried model aligner and model orientation aligner.

**Comment by timcoolmode** [comment]
I do want a system that does dense point clouds and meshes to be able to do above

**Comment by ahojnnes** [comment]
Okay, let me expand a little on this:

1. Run the sparse reconstruction stage on an initial set of images to obtain the camera locations (that will not change later).
2. Undistort the images in the COLMAP format, which will give you a "dense" workspace folder, which serves as the input to the ``dense_stereo`` command. In the following, we will use this folder as a template for future reconstructions.
3. Copy the template folder and replace the initial images with the images of a new capture with the same cameras (the location of the cameras in the room should not change). Make sure, the images of the same camera have exactly the same file name.
4. Run ``dense_stereo`` and ``dense_fuser`` on the copied template with the images replaced.
5. Repeat steps 3-4 for each new capture.

The outputs of step 4 should be consistent reconstructions, all in the same coordinate system.

**Comment by timcoolmode** [comment]
That's awesome! I was also looking at the "point_triangulator" feature. What's the negative of doing it in the sparse vs the dense construction step as I'm doing my dense construction through openmvs?

**Comment by timcoolmode** [comment]
Very cool thanks for the help!
