### ISSUE TITLE
feature extraction does not work for binary 3.4, it does work for 3.3 Win10/64/nocuda

### ISSUE THREAD

**Issue by Sprk-nl** [colmap/colmap#333]
I've downloaded the stable 3.4 and dev version for windows 10 no cuda.
Tried different settings with and without GPU, but no features where extracted.

Then I've tested an older release version 3.3, which found > 10000 feature for each image.
Checking the database / show matches gave me a good overview version 3.3 works and 3.4 does not.

**Comment by ahojnnes** [comment]
I will check this on my machine. Did you make any changes to the settings? Which GPU do you have?

**Comment by ahojnnes** [comment]
@Sprk-nl I cannot reproduce this issue on my machine. Which GPU are you using?
