### ISSUE TITLE
Wrong camera pose even after SfM process

### ISSUE THREAD

**Issue by Gorokke** [colmap/colmap#334]
Hi,
I am having problem with camera poses.

If I reproject the 3D points (both from sparse and dense reconstruction) to the 2D images, for some cameras, it shows large displacement from original feature point (high reprojection error.. which means wrong camera pose) But the dense point cloud and mesh itself is quite nice. 

I tried many many parameters to get the best camera pose but still, the reprojection results are not good.

 Are there any tips to get good camera pose so that the reprojection error becomes small?

by the way,
- I am using around 70 images,
- I manually undistorted and now I am using pinhole model.

Always, thanks for your help!!!

**Comment by ahojnnes** [comment]
How do you project the points to the cameras? Are you accounting for distortion?

**Comment by Gorokke** [comment]
I really appreciate your prompt response!!!!!!!

All the case, I have used, P=K*[R T]*(XYZ)-> P=P./P(3) (normalize).
But I didn't consider the distortion coefficient. Do I need to consider that for the following scenarios? 

I checked two scenarios. 
1. When I use the 'RADIAL' model: Using original images (still distorted), I reproject the dense point cloud after undistort process. So, I thought I don't need to consider the distortion parameter after I undistort.
2. When I use the 'Pinhole' model: Using manually undistorted images, I reproject the sparse or dense point cloud. Also for this case, I thought I don't need to consider distortion because I am using 'Pinhole' model.

Do I still need to account for the distortion?? 

I really really appreciate your help..!!!

**Comment by Gorokke** [comment]
<img width="253" alt="clearly_reconstructed_camera" src="https://user-images.githubusercontent.com/37383608/37975094-289d917a-31a4-11e8-99f2-1a24b77b3892.PNG">
It shows camera poses are clearly reconstructed.

but if I reproject to the images,
<img width="140" alt="good" src="https://user-images.githubusercontent.com/37383608/37975124-3cbdb2fc-31a4-11e8-8f17-b5c4f5892e71.PNG">
some camera poses are good,

<img width="166" alt="slightly_off" src="https://user-images.githubusercontent.com/37383608/37975159-4b923956-31a4-11e8-9cf8-539ca11224ba.PNG">
some camera poses are slightly off,

<img width="164" alt="completely_off" src="https://user-images.githubusercontent.com/37383608/37975179-557e209c-31a4-11e8-85c9-a13168ea76c1.PNG">
some camera poses are completely off like this,

do you think, this could be happening??

thanks!

**Comment by Gorokke** [comment]
<img width="166" alt="slightly_off" src="https://user-images.githubusercontent.com/37383608/37975437-eabd908e-31a4-11e8-9746-c92686272073.PNG">

This is an example.

Blue is the reprojected results.
Many cameras are slightly off, and one camera is completely off with different scale.

**Comment by Gorokke** [comment]
For the double check,,until now, given 4 vectors of quaternion and 3 vectors of translation,

I converted quaternion to 3x3 rotation, and then I just concatenate with translation for projection matrix, like this, [R T].. 

I am really thankful, if you have any idea!!

**Comment by Gorokke** [comment]
Hi, I found the issue.

I mixed up the camera and image id, when I parse the data.

now it is correct.

Sorry for bothering you

**Comment by ahojnnes** [comment]
No problem, glad it was resolved. Let me know if there are other questions.
