### ISSUE TITLE
Colmap doesn't start

### ISSUE THREAD

**Issue by Insaisissable** [colmap/colmap#335]
Hi,

I installed the Colmap Stable (Version 3.4) for Mac and it doesn't start. I have an Mac 5.1 2x2,6 GhHz quad-core Intel Xeon /128 GB ram and NVIDIA Quadro K5000 4GB graphic card.
Any thoughts?

Raoul

**Comment by Insaisissable** [comment]
... using MacOS X El Capitan 10.11.6. system.

**Comment by ahojnnes** [comment]
What do you mean by install? Compiled yourself?

**Comment by Insaisissable** [comment]
I mean that I downloaded on my Mac and clicked on the application's icon an this doesn't work ... as usual staff get installed on a computer ...

**Comment by ahojnnes** [comment]
The binaries were compiled under 10.13.X and I have not tested them under 10.11.X. It would be easiest if you just compiled COLMAP from source on your system. It should work without a problem.
