### ISSUE TITLE
Assertion failed about Eigen file

### ISSUE THREAD

**Issue by hushanming** [colmap/colmap#336]
Hi,
I compile the code on VisualStudio2013 and it successed,but I got this error when run colmap.exe:
"Assertion failed:",It shows the some Eigen file ,and I debug the code found the bug is "abort()..." at this [code](https://github.com/colmap/colmap/blob/dev/src/feature/matching.cc#L802),I have no idea about this bug,what do you think about this bug?

**Comment by ahojnnes** [comment]
Can you post the full traceback that you see? It seems you compiled in debug mode, which will be horribly slow. Make sure to select Release or RelWithDebInfo in VS2013.

**Comment by hushanming** [comment]
Hi
thank you for your replay.
I run the feature matching function on the debug model ,and then i got this error 

![default](https://user-images.githubusercontent.com/18521469/38029472-82f2a550-32c8-11e8-8f30-1925573f1df1.png)
if i run the function on release model,then the software exit with no informations.

**Comment by hushanming** [comment]
Hi
I debug this code and found the bug are all about the Eigen Structure. Such as I start the function "reconstruction" and found the error at this [code](https://github.com/colmap/colmap/blob/dev/src/base/camera.cc#L191),then I got this [link](http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html),and i think it may be the reason about the bug I got,I try to define EIGEN_DONT_ALIGN in eigen/src/core/util/Macro.h but it show the same bug in this [code](https://github.com/colmap/colmap/blob/dev/src/base/database_cache.cc#L136). Would  you give me some  suggestions about this problem?Thank you very much.

**Comment by ahojnnes** [comment]
I honestly don't see how there could be an alignment issue in the code you referenced. I can also not reproduce that error and I also use VS2013. Did you compile COLMAP using the Python script or completely from scratch?

**Comment by hushanming** [comment]
Hi,
Thank you for your reply.The ceres library I used was wrong cause I am not used the suitesparse,so the problem on my PC was solved. I'm sorry for my mistake.Thank you very much again!
