### ISSUE TITLE
Crash during stereo part of dense reconstruction

### ISSUE THREAD

**Issue by ahjulstad** [colmap/colmap#337]
I am consistently experiencing crashes during the stereo part of dense reconstruction. I have tested with dev and 3.4 downloads, on Windows 7 (laptop with Quadro M5000M, Nvidia driver version 373.06) and Windows 10 (laptop with GTX 860M Nvidia 388.43) .  

It starts (some output is briefly shown in the log window), but then crashes. On the Windows 7 computer the system tells me the display driver has stopped responding.

The following screenshot is taken just before the crash (on the Win 7 computer):

![image](https://user-images.githubusercontent.com/6638265/38025882-4fc077fe-328a-11e8-8aad-540c3a880c4a.png)

**Comment by ahojnnes** [comment]
Please see https://colmap.github.io/faq.html#fix-gpu-freezes-and-timeouts-during-dense-reconstruction

**Comment by ahjulstad** [comment]
I changed settings as suggested. On the Windows 7 computer everything works fine, but on the Windows 10 computer with the 860M card the computer bluescreens near the end of the stereo phase, or at least after running through the views once. Related?
