### ISSUE TITLE
Question concerning geo-registration

### ISSUE THREAD

**Issue by gT-mike** [colmap/colmap#339]
I wanted to make use of the geo-registration step as described in the FAQ.

After which step do I have to run the model_aligner? After the exhaustive_matcher or after the mapper?

Thanks!

**Comment by ahojnnes** [comment]
After the mapper.

**Comment by gT-mike** [comment]
sorry, but I can't run it properly, I get the following error:

ERROR: You must provide a maximum alignment error > 0

I use the points3D.bin in ../sparse/0 as the input to the --input_path parameter. Is that correct or do I have something else. Sorry, but it is not clear to me from the FAQ what is supposed to be used here.

Thanks!

**Comment by ahojnnes** [comment]
No, the input paths should point to the folder with the *.bin files. The output path to a new folder with the merged output model. The other error message is pretty clear: set a maximum robust alignment error threshold. You can see all available options of a command using the -h argument.

**Comment by gT-mike** [comment]
could you tell me a good value for the threshold?

**Comment by gT-mike** [comment]
Tried it out with different parameters but the only thing I get is unfortunately


Aligning reconstruction
-----------------------
 => Using 100 reference images
 => Alignment failed


My reference file looks like:

"
seq01_frame-000000.color.png -0.12323361 -1.1206967 -0.98870575
seq01_frame-000010.color.png -0.1391464 -1.1227895 -0.98805392
seq01_frame-000020.color.png -0.13108535 -1.1230452 -0.9564172
seq01_frame-000030.color.png -0.13357243 -1.1270621 -0.88781369
...
"

I start the model_aligner with the following command:

colmap model_aligner --input_path /sparse/0/ --output_path /sparse/1/ --robust_alignment 1 --robust_alignment_max_error 0.01 --ref_images_path /sparse/images_poses_correspondence_list.txt > outputlog_colmap_model_aligner.log

All folders and files do actually exist. In /sparse/0 are a cameras.bin, images.bin and points3D.bin file, generated previously by running the feature_extractor, the exhaustive_matcher and the mapper.

Any ideas? Thanks!
