### ISSUE TITLE
What's the best CUDA version for COLMAP ?

### ISSUE THREAD

**Issue by json87** [colmap/colmap#34]
Hi, 
   
I have built colmap with CUDA 7.5  on windows 7 platform using VS 2013. However, the mvs_cuda project could not be compiled successfully with following errors.

patch_match_cuda.cu
1>

1>D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\concrt.h(5658): error C2015: too many characters in constant
1>

1>D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\concrt.h(5658): error C2146: syntax error : missing ')' before identifier 'q'
1>

1>D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\concrt.h(5658): error C2001: newline in constant
1>

1>D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\concrt.h(5671): error C2143: syntax error : missing ';' before '{'
1>

1>D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\concrt.h(5671): error C2143: syntax error : missing ')' before ';'

**Comment by ahojnnes** [comment]
Did you install all the latest Visual Studio 2013 Updates? I cannot check at the moment. It I think I am on Update 5 and Microsoft usually fixes many compiler bugs with their Updates.

**Comment by json87** [comment]
Yes, I just update my Visual Studio 2013 to update 5. However, the same issues are existed. I will keep up with this issue. Thanks for your help!

**Comment by ahojnnes** [comment]
I have no idea what is going on in your case. I can only say that I compile COLMAP regularly under Windows/MSVC 2013 and 2015 without any problems. Let me know if and how you fixed the problem. Thanks!

**Comment by json87** [comment]
OK. By the way, what's your CUDA's version ?

**Comment by ahojnnes** [comment]
7.5

**Comment by XYue** [comment]
I have the same problem as @json87. And I also use cuda 7.5 and MSVC 2013.

By the way, as i remember, cuda 7.5 does not support MSVC 2015. So, @ahojnnes , how do u compile COLMAP with cuda 7.5 under MSVC 2015?

**Comment by ahojnnes** [comment]
For MSVC 2015, I use CUDA 8 RC1. When looking at your errors above again, I suspect you are trying to compile in 32bit mode?

**Comment by ahojnnes** [comment]
Can you check whether the proposed patch in https://github.com/colmap/colmap/issues/29 fixes the problem?

**Comment by XYue** [comment]
@ahojnnes 
I compiled in 64bit mode.
Yes, #29 fixes my problem, thank you very much.

**Comment by ahojnnes** [comment]
It is now fixed in the master branch. Thanks for testing!
