### ISSUE TITLE
QT Bug with menubar and combobox

### ISSUE THREAD

**Issue by tompollok** [colmap/colmap#341]
Does your application ui on your machine also sometimes not correctly open the menubar and combobox?

See video:  https://www.youtube.com/watch?v=SZuQNbiA5qo

It happens when the window is opened for a while. I havent figured out the reason yet

**Comment by ahojnnes** [comment]
No, I have not seen this problem on any system. You are on Windows 10? Did you download the pre-built binaries or did you compile yourself?
