### ISSUE TITLE
Model aligner not working

### ISSUE THREAD

**Issue by gT-mike** [colmap/colmap#344]
Hi,

as my last post concerning the model aligner was closed and I can't reopen it, here a new one.

Tried it out to run the model_algienr with different parameters but the only thing I get is unfortunately

Aligning reconstruction
=> Using 100 reference images
=> Alignment failed

My reference file looks like:

"
seq01_frame-000000.color.png -0.12323361 -1.1206967 -0.98870575
seq01_frame-000010.color.png -0.1391464 -1.1227895 -0.98805392
seq01_frame-000020.color.png -0.13108535 -1.1230452 -0.9564172
seq01_frame-000030.color.png -0.13357243 -1.1270621 -0.88781369
...
"

I start the model_aligner with the following command:

colmap model_aligner --input_path /sparse/0/ --output_path /sparse/1/ --robust_alignment 1 --robust_alignment_max_error 0.01 --ref_images_path /sparse/images_poses_correspondence_list.txt > outputlog_colmap_model_aligner.log

All folders and files do actually exist. In /sparse/0 are a cameras.bin, images.bin and points3D.bin file, generated previously by running the feature_extractor, the exhaustive_matcher and the mapper.

Any ideas? Thanks!

**Comment by ahojnnes** [comment]
Are you sure those images are actually reconstructed in the model? Are the image names exactly the same?

**Comment by gT-mike** [comment]
hi, turns out there was actually a problem with the details of syntax, thanks!

I am however confused with the output. If read the poses after the alignment from the images.bin file the position (x,y,z) in the pose is not exactly the same as provided in the images_poses_correspondence file.

**Comment by ahojnnes** [comment]
@gT-mike The XYZ coordinates in the images.bin is not the camera location. QVEC, TVEC defines transformation from world to camera coordinate system, see https://colmap.github.io/format.html

**Comment by janryan6** [comment]
The file and image are named correctly and exist, but it doesn't work, please help me
![Uploading 03c4ad87b9e2a9b61d3fc5ca04d4473.png…]()
！

**Comment by janryan6** [comment]
The file and image are named correctly and exist, but it doesn't work, please help me！
![03c4ad87b9e2a9b61d3fc5ca04d4473](https://github.com/colmap/colmap/assets/108948633/3b66e0e5-f86a-4b4a-8069-171c8d00b221)
