### ISSUE TITLE
Keep/import same intrinsics

### ISSUE THREAD

**Issue by franex** [colmap/colmap#345]
Hi,
I'm running a sort of "sequential" approach. Given n images:
1) I orient a first sub block
2) then I add new images and orient them in the same project.
3) etc.
I'm trying to have just one set of intrinsics, but I noticed that for each sub-block I generate a new set of parameters (even if I use --ImageReader.single_camera 1) even if a new BA is run with the old and the new images together -> In practice, I still have one set of intrinsics for each sub-block. 
I would like to have a single set of intrinsics for all the images (given that I estimate it in the BA and I do not have it in advance). 

Here the code I use after the first block to iteratively add the new images:

`
%colDir%\feature_extractor --database_path E:\ColMap\Output\database.db --image_path E:\ColMap\Images\images --image_list_path E:\ColMap\Images\images\image-list.txt --ImageReader.camera_model OPENCV --ImageReader.single_camera 1 --SiftExtraction.use_gpu=1 --SiftExtraction.gpu_index=0 

%colDir%\spatial_matcher --database_path database.db --SiftMatching.use_gpu 1 --SiftMatching.gpu_index=0 --SpatialMatching.is_gps 1 --SpatialMatching.max_num_neighbors 10 --SpatialMatching.max_distance 50

%colDir%\mapper --database_path E:\ColMap\Output\database.db --image_path E:\ColMap\Images\images --import_path E:\ColMap\Output\sparse\0 --export_path E:\ColMap\Output\sparse\0 
`
How can I do that?

I have other two questions: 
1) I use the image geotag but I noticed that output orientations refer to a relative coordinate system and not to a GPS coordinate system. I assume GPS is only used to guide the spatial_matcher. Is there a way to provide the camera positions using the GPS information or I need to do that later? A very rough rotation and translation would be enough. 
2) Is there a way to export quickly the P matrix or we need to compute it?

Thank you in advance for the answer.

**Comment by ahojnnes** [comment]
0. You would have to write a small SQL script that sets the camera_id of the newly added images to the same camera_id of the initial set of images.
1. You are right, the orientation/location in the database is only used for the ``spatial_matcher``. You could use the ``model_aligner`` to align the reconstruction to your GPS coordinates, see https://colmap.github.io/faq.html#geo-registration
2. You could either read the sparse models with Python/Matlab (see https://colmap.github.io/format.html#sparse-reconstruction). In the Python case, you can obtain the projection matrix as ``np.column_stack([qvec2rotmat(image.qvec), image.tvec])``. If you also need undistorted images in any case, you could simply undistort the images to the PMVS format, which exports the projection matrix (with undistorted intrinsics) into the "txt" folder.

**Comment by ahojnnes** [comment]
The ``tvec`` in images.txt is not the location of the camera. Instead it defines the transformation from world to camera coordinates. Please see here: https://colmap.github.io/format.html

**Comment by franex** [comment]
Hi,
Yes, you are right, I wrote in the wrong way the equation...there was a transpose more...
Thank you again and nice weekend
