### ISSUE TITLE
Issue about InterpolatePose

### ISSUE THREAD

**Issue by is03wlei** [colmap/colmap#346]
InterpolatePose(const Eigen::Vector4d& qvec1, const Eigen::Vector3d& tvec1,
                     const Eigen::Vector4d& qvec2, const Eigen::Vector3d& tvec2,
                     const double t, Eigen::Vector4d* qveci,
                     Eigen::Vector3d* tveci)

Here I transformed qvec and tvec to ProjectionCenter.
I passed 0.5 to t.

pose1 -2.16521e+06
 4.38402e+06
 4.08181e+06
pose2 -2.16521e+06
 4.38402e+06
 4.08181e+06

pose12 -2.16515e+06
 4.38394e+06
 4.08172e+06

The problem is pose1 and pose2 are very near to each other. But the result pose12 is quite far.
Does it make sense? 
What does InterpolatePose do?

**Comment by ahojnnes** [comment]
Thanks for reporting this issue. I would expect this is a numerical issue. Is this still an issue for you? To avoid the problem, we should probably check if the difference between the two input poses to the the ``InterpolatePose`` function is very small.
