### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by ZagadkaTeg** [colmap/colmap#347]
I've tried dev and 3.4 versions of Win64 Colmap both with and without Cuda (I do have a Cuda GPU and 64 bit win10) with two separate sets of images but get no output files at all, both rendered in the GUI nor in the created sparse and dense folders. This is using auto-reconstruction.
However I have discovered that if I cancel the processing part-way through I do get some images and points both in the render window and folders, but obviously they're incomplete.
Any ideas/pointers gratefully received and if I've done something outrageously stupid apologies in advance!

**Comment by ZagadkaTeg** [comment]
Andres,
Thank you very much. That does make sense with what I'm seeing. I'll have a
play with the min model size and suggesting initial pairs. Much obliged!

Kev

**Comment by ahojnnes** [comment]
Closing this issue as resolved but feel free to follow up if something is still unclear.
