### ISSUE TITLE
Model aligner not working - continuation

### ISSUE THREAD

**Issue by gT-mike** [colmap/colmap#349]
>> XYZ coordinates in the images.bin is not the camera location. QVEC, TVEC defines transformation from world to camera coordinate system, see https://colmap.github.io/format.html

You are right - I forgot that we have a transformation matrix and therefore a translation vector not the x,y,z coordinates.

Following this topic: Suppose that I know not only the x,y,z position of the image but actually the real pose (including rotation) - e.g. like it is the case in the 7scenes dataset. Is there a way to feed not only the x,y,z coordinates but the full pose into colmap so that the mapper can make use of it?

Thanks again!

**Comment by ahojnnes** [comment]
No, this is currently not implemented.

**Comment by gT-mike** [comment]
Ahh okay, that could be a interesting thing to test. Could you outline how this can be done? It is not obvious to me neither from the FAQ nor from the --help of colmap dense_stereo.

Many thanks!

**Comment by ahojnnes** [comment]
You would have to construct a cameras.txt, images.txt, and empty points3D.txt, then do the undistorion (even if you use a pinhole camera model), and then run dense stereo with a manual min/max depth range (alternatively, you could perform feature extraction/matching and use the ``point_triangulator`` to produce a sparse point cloud, which can then be used to automatically determine the depth range).

**Comment by ahojnnes** [comment]
This is now also described here: file:///Users/jsch/Development/colmap/doc/_build/html/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses

**Comment by gT-mike** [comment]
Alright, I will try and let you know if I'm (probably) too stupid to make the *.txt files manually. Please leave the issue open for the moment. I will refer back here once I tried to follow your instruction.

Thanks!

**Comment by gT-mike** [comment]
Tried to follow the FAQ and need some little help for understanding rightaway. Please correct me if the steps that I listed bellow are wrong:

1) Run Feature Extractor
2) Run Exhaustive Matcher
3) Create a sparse folder where I manually insert a cameras.txt file and a images.txt file similar to how they are usually created by the mapper
4) Run point_triangulator (in this step the sparse model is computed from the known poses that were put in before manually into the images.txt and cameras.txt file
5) run image undistorter
6) run dense stereo 
7) run dense fuser

The alternative way would work like with the following steps:

1) Create a "../sparse" folder and put in there an empty points3d.txt file and the manually created images.txt and cameras.txt.
2) Run image undistorter
3) Create the patch-match.cfg file in the "../dense" folder
4) Run dense_stereo
5) Run dense_fuser

Is this supposed to produse the same result? If not, what additional information does one acquire following the first way?

Sorry for going into particular details, just super interesting to understand how the magic is actually happening :)

Tried to follow the FAQ and need some little help for understanding rightaway. Please correct me if the steps that I listed bellow are wrong:

1) Run Feature Extractor
2) Run Exhaustive Matcher
3) Create a sparse folder where I manually insert a cameras.txt file and a images.txt file similar to how they are usually created by the mapper
4) Run point_triangulator (in this step the sparse model is computed from the known poses that were put in before manually into the images.txt and cameras.txt file
5) run image undistorter
6) run dense stereo 
7) run dense fuser

The alternative way would work like with the following steps:

1) Create a "../sparse" folder and put in there an empty points3d.txt file and the manually created images.txt and cameras.txt.
2) Run image undistorter
3) Create the patch-match.cfg file in the "../dense" folder
4) Run dense_stereo
5) Run dense_fuser

Is this supposed to produse the same result? If not, what additional information does one acquire following the first way?

Sorry for going into particular details, just super interesting to understand how the magic is actually happening :)

**Comment by ahojnnes** [comment]
The first one has the advantage that you get a sparse model, which you would not in the second stage. This is useful for some applications. The other advantage is that you don't have to manually specify the depth range and the source images in the patch match configuration.

**Comment by gT-mike** [comment]
Short file concerning the *.txt files:

1) Is there a parameter to force the mapper to write txt files instead of binaries? They are all binaries in my case. Or is it hard coded to binaries and I have to recompile and change 

void Reconstruction::Write(const std::string& path) const { WriteBinary(path); } 

to 

void Reconstruction::Write(const std::string& path) const { WriteText(path); }

in the code of reconstruction.cc?

2) As I have not run the mapper but have to construct the images.text file manually, what is the right approach to do so? Should I leave the second line for each image blank (i.e. just a newline) or insert a random number?


Many thanks

**Comment by gT-mike** [comment]
Thanks, so far. Concerning point 2, I still need some clarification. I see two options here:

a) As after running the exhaustive matcher no images.txt file is produced, the features have to be extracted directly from the database.db. Is there a way to do this with one of the scripts that come with COLMAP or how you would suggest to do that?

b) I run the mapper that will produce a cameras.bin and a images.bin, change the QVEC and TVEC in the images.bin file and then run the point_triangulator. Is that a possible way as well?

**Comment by ahojnnes** [comment]
a) You would have to read the SQLite database to extract the number of features.
b) Yes, this is also possible.

**Comment by gT-mike** [comment]
I tried way b) and the outcome did not quite look what it should (hardly any point constructed). Do I have to run the point_triangulator after I changed the poses manually in the images.txt created by running the mapper?

**Comment by ahojnnes** [comment]
Yes, the point_triangulator should be executed after modifying the images.txt

**Comment by gT-mike** [comment]
I have tried the point_triangulator and the last thing that I get as an output is

==============================================================================
Extracting colors
==============================================================================

Is that correct or does that mean that the triangulator got stuck somewhere on the way? Usually the last lime is "Elapsed time ... " for many of the other functions. 

I would also expect to run it is almost as long as the mapper but it finished pretty quickly. Is it normal that it runs significantly faster than the mapper?

**Comment by gT-mike** [comment]
alright great, I will then try to re-run the dense stereo and see what happens .. stay tuned, I will keep you updated:)

**Comment by gT-mike** [comment]
I got the following result from running the point_triangulator:


Bundle adjustment report
------------------------
    Residuals : 190676
   Parameters : 35019
   Iterations : 51
         Time : 6.10938 [s]
 Initial cost : 6.041e+10 [px]
   Final cost : 6.3586e+06 [px]
  Termination : No convergence

  => Merged observations: 1
  => Completed observations: 0
  => Filtered observations: 95221
  => Changed observations: 0.998783

I understand therefore, that it did not really work out ?

**Comment by gT-mike** [comment]
Additional I have to state that for most images it actually triangulated 0 points when at the same time it found ~ 1000 points, e.g. 

==============================================================================
Triangulating image #94
==============================================================================

  => Image has 724 / 977 points
  => Triangulated 0 points

Have you tried to do it this way? Do you have a clue what the problem might be?

**Comment by ahojnnes** [comment]
Probably incorrect camera poses. Make sure they make sense visually when you load the model in COLMAP.
