### ISSUE TITLE
cudaCheckError() with sync failed at patch_match_cuda.cu:1320 : unknown error

### ISSUE THREAD

**Issue by bjornpiltz** [colmap/colmap#35]
Stereo matching crashes for me with the above error. I have MSVC 2013, CUDA 7.5 and an NVIDIA GTX 980. It's the line after '#undef CALL_SWEEP_FUNC'.

**Comment by ahojnnes** [comment]
Does this help: https://colmap.github.io/faq.html#fix-gpu-freezes-and-timeouts-during-dense-reconstruction ?

**Comment by bjornpiltz** [comment]
'fraid not. I increased the time out, but the screen only freezes for a fraction of a second before colmap crashes. I have attached a log:
[colmap_cuda_error.txt](https://github.com/colmap/colmap/files/497988/colmap_cuda_error.txt)

**Comment by ahojnnes** [comment]
Can you share the workspace with me (Dropbox, Google Drive, whatever...)?

**Comment by bjornpiltz** [comment]
Seems increasing the timeout helped after all. Perhaps all that was needed was a reboot after I changed it. Thanks for the help.

**Comment by ahojnnes** [comment]
Yes, you must reboot after changing the timeout. Thanks for the feedback!
