### ISSUE TITLE
Database file has NULL q{w,x,y,z} and t{x,y,z} values but GUI does not.

### ISSUE THREAD

**Issue by mitch-karch** [colmap/colmap#350]
i'm trying to get the extrinsic positions of the image from the database but i'm getting null values when exploring the sqlite database file.

Here's the GUI
![image](https://user-images.githubusercontent.com/1393562/39026250-e8866dea-4400-11e8-8f3a-88ca7315cb95.png)

and here's the databse viewed in a DB browser.
![image](https://user-images.githubusercontent.com/1393562/39026288-223105be-4401-11e8-979d-25d00a6f9dbd.png)

**Comment by ahojnnes** [comment]
The database does not contain the reconstructed poses but priors. You should inspect the sparse model files, as described here: https://colmap.github.io/format.html
