### ISSUE TITLE
Does anybody have a precompiled binary with CUDA for MacOS Sierra?

### ISSUE THREAD

**Issue by cesss** [colmap/colmap#351]
I know compiling it is easy, but I prefer to avoid installing the CUDA SDK for the moment, so getting a precompiled colmap binary would be of great help. Is there any site or contributor that kindly offers precompiled MacOS binaries (>=10.12) of colmap with CUDA?

**Comment by ahojnnes** [comment]
I would be happy to provide the binary but I don't have a Mac with a CUDA GPU. If anyone could provide binaries, I could also host them on my server for download.

**Comment by cesss** [comment]
Thanks a lot for your prompt reply. My preference for avoiding installing the CUDA SDK is that it's shipped as a package installer, and I always try to keep my system directories as intact as possible. But I'll study it more deeply: maybe there's a way of extracting the needed headers and tools (if it's only a matter of headers is should be easy... if some tools are also needed it might be harder).

Anyway, if anybody has a precompiled binary with CUDA for MacOS >=10.12, please consider uploading it, as it would be very helpful.

**Comment by fschwaiger** [comment]
Compiled with CUDA 9.1 on a MBP2012 on 10.13.4 with the Command Line Tools 9.0 https://drive.google.com/file/d/1xkDFY82JZBMKfewMQYAazkABdsIwWfeB/view?usp=sharing

Also I used this workaround: https://github.com/colmap/colmap/issues/296#issuecomment-363549242

```
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.5.0
```

**Comment by ahojnnes** [comment]
Great, thanks for providing the binary.

**Comment by cesss** [comment]
Thanks a lot, although I'm on 10.12.6 and I guess you used the default deployment version (10.13 in your case). I was planning to build my own anyway.

BTW, what's the minimum CUDA version for building colmap? I couldn't find it in the website.

**Comment by ahojnnes** [comment]
CUDA 7.
