### ISSUE TITLE
Building `master` fails against latest `ceres-solver`

### ISSUE THREAD

**Issue by regularfry** [colmap/colmap#353]
The instructions [here](https://colmap.github.io/install.html) pull the latest `master` from `ceres-solver`, but it appears that [this patch](https://ceres-solver.googlesource.com/ceres-solver/+/cfdc2af28b400a921d7465ab066656d5fafccc7a) causes a build failure in `colmap`:

```
$ make
...
[ 10%] Built target base
Scanning dependencies of target controllers
[ 10%] Building CXX object src/controllers/CMakeFiles/controllers.dir/automatic_reconstruction.cc.o
In file included from /home/alex/src/tanks/tools/colmap/src/./sfm/incremental_mapper.h:23:0,
                 from /home/alex/src/tanks/tools/colmap/src/./controllers/incremental_mapper.h:21,
                 from /home/alex/src/tanks/tools/colmap/src/controllers/automatic_reconstruction.cc:20:
/home/alex/src/tanks/tools/colmap/src/./optim/bundle_adjustment.h: In constructor ‘colmap::BundleAdjustmentOptions::BundleAdjustmentOptions()’:
/home/alex/src/tanks/tools/colmap/src/./optim/bundle_adjustment.h:67:20: error: ‘struct ceres::Solver::Options’ has no member named ‘num_linear_solver_threads’
     solver_options.num_linear_solver_threads = -1;
                    ^
src/controllers/CMakeFiles/controllers.dir/build.make:62: recipe for target 'src/controllers/CMakeFiles/controllers.dir/automatic_reconstruction.cc.o' failed
make[2]: *** [src/controllers/CMakeFiles/controllers.dir/automatic_reconstruction.cc.o] Error 1
CMakeFiles/Makefile2:259: recipe for target 'src/controllers/CMakeFiles/controllers.dir/all' failed
make[1]: *** [src/controllers/CMakeFiles/controllers.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by regularfry** [comment]
The `colmap` build succeeds against the `1.14.0` `ceres-solver` tag.

**Comment by ahojnnes** [comment]
Thanks, I will have a look. I haven’t updated to the latest version.

**Comment by sandwichmaker** [comment]
Solver::Options::num_linear_solver_threads is deprecated at head in ceres solver.

**Comment by GitHubrist** [comment]
I'm having the same trouble. This is my first attempt to take a look at colmap/ceres-solver. I'm following instructions from the [same link](https://colmap.github.io/install.html) which does not mention version-dependence.

It's not clear to me from the comments what I need to do now. Having successfully installed ceres-solver:
1. How do I determine what version it is?
2. How do I "build against the 1.14.0 ceres-solver tag"?

The comment that num_linear_solver_threads is deprecated in ceres-solver, suggests that colmap needs to be updated, but that seems to contradict the earlier suggestion that colmap needs to be updated.
3. ?

**Comment by InnovArul** [comment]
Just came across your question @GitHubrist. 

To install ceres-solver specific to the tag 1.14.x, clone the ceres-solver repo as below:

`git clone **-b 1.14.x**  https://ceres-solver.googlesource.com/ceres-solver` 

Now do the same procedure to install this ceres-solver and colmap as mentioned [here](https://colmap.github.io/install.html#linux).

Hope it helps!

**Comment by GitHubrist** [comment]
@InnovArul  Did as you directed, got the 1.14.x version of ceres-solver and everything went smoothly in the steps in your link.

% colmap -h
works, but
% colmap gui
coredumps.
% colmap gui -h
works too, making me think the instruction in the link to run colmap gui without other arguments might be a typo?
I suspect I'll be able to run colmap from the command-line to do what I want anyway.

Thank you. (I'm actually quite fatalistic about getting help whenever I report trouble building-from-source. Maybe my tables are turning. :^) )

**Comment by ahojnnes** [comment]
@GitHubrist The GUI needs a proper GPU attached to your system. It will not work from a remote machine.

**Comment by ahojnnes** [comment]
Please pull the latest commits from the `dev` branch. It should now work with the latest Ceres-Solver version 2.x.

**Comment by InnovArul** [comment]
@GitHubrist : In my case, I had to add the lib path of Qt in LD_LIBRARY_PATH env variable to get the GUI working.

`export LD_LIBRARY_PATH=/opt/Qt/5.10.1/gcc_64/lib:$LD_LIBRARY_PATH`

I am not sure if this is the issue in your case or the GPU as pointed out by @ahojnnes .
Hope it helps!

**Comment by GitHubrist** [comment]
@ahojnnes  I don't have a GPU in my desktop.  Still, I'd think it would fail gracefully without a segfault.

@InnovArul  I'm running Ubuntu here. I don't have an /opt/ directory, and although I have found qt4/ and qt5/ in the /usr/ tree, neither has, for example, a gcc_64/ folder beneath it. Also my $LD_LIBRARY_PATH is empty.   Thank you both.

**Comment by GitHubrist** [comment]
Capping this off:
% glxinfo|grep "OpenGL version"
OpenGL version string: 2.1 Mesa 17.2.8

My computer is too old I think.
