### ISSUE TITLE
Wrong depth estimation at image edge

### ISSUE THREAD

**Issue by odiseo123** [colmap/colmap#354]
Hi @ahojnnes.
I have been using recently your great software. I am observing a systematic incorrect depth estimation at the image edge:
![image](https://user-images.githubusercontent.com/18690090/39498662-c0394f92-4dec-11e8-98e0-b617064416de.png)
Note the red "lines" at the top, right and (partially) bottom of the image.

This causes later a "square/pyramidal" boundary of noisy points in the dense reconstruction:
![untitled 2](https://user-images.githubusercontent.com/18690090/39499096-573684ee-4def-11e8-8702-2d294b457246.png)

Here the actual 3D model is encircled in green. Zooming out quite a lot reveals a noisy points in a pyramidal shape (I have drawn some lines in red to try to better visualize the 3D effect). I believe this corresponds to the four image edges being backprojected with deficient depth estimation.

Typically patches or descriptors are created by keeping a safe boundary of few pixels with respect to the closest image border. This prevents adding black pixels (i.e. pixels outside the image size) to the descriptor/patch. I am wondering if such a check is implemented and if not, would you mind giving me a hint of the functions I should probably refactor?   

Thanks a lot for any help.

Andres

**Comment by ahojnnes** [comment]
You could manually post-process the depth maps after the ``dense_stereo`` stage. Remove the image borders, write the depth maps to disk again and then run the ``dense_fuser``. You can find more information about the dense reconstruction file formats here: https://colmap.github.io/format.html#dense-reconstruction

**Comment by odiseo123** [comment]
Hi @ahojnnes Thanks for the prompt reply.
Any tips on how to avoid this altogether? Based on your knowledge and experience, would you say this is indeed an issue related to the handling of the image borders or is it exclusive of my dataset somehow?
I have already cropped my images due to other image artifacts and would prefer not to further discard pixels if there is a principle solution. 
Cheers.

**Comment by ahojnnes** [comment]
There is no way to avoid this altogether. The reason for the wrong estimates is the patch window size and artifacts at the border. In many times you can still get reasonable depth estimates there but in your case it seems not. Maybe due to inaccurate camera calibration at the borders. I don’t know though.

**Comment by amitabe** [comment]
@ahojnnes I wonder if you managed to solve this issue, as I'm tackling the same issue myself.
