### ISSUE TITLE
Proposed enhancement: (GUI) Feedback on camera properties (intrinsics/extrinsics)

### ISSUE THREAD

**Issue by odiseo123** [colmap/colmap#355]
Using the software I have missed a functionality. Once the sparse reconstruction finishes it would be very useful to be able to click on a reconstructed camera and get some basic information about it: camera id, associated image name, estimated intrinsic parameters, estimated extrinsic parameters, etc. This information could be shown as a pop-up menu or be redirected to the console.
Happy to hear some ideas around this.

**Comment by ahojnnes** [comment]
This feature is already implemented. Double-click on a camera and exactly this information will be shown. A similar feature exists for all sparse 3D points.

**Comment by odiseo123** [comment]
Indeed. Very useful. Thanks and sorry for the miss.
