### ISSUE TITLE
Input Multiple Camera Parameter in Feature Extraction

### ISSUE THREAD

**Issue by resindraburiza** [colmap/colmap#356]
Hi,

first of all, thank you for your software. It is amazingly good.

I want to ask a question: is it possible to input multiple camera intrinsic parameters during feature extraction? For example, I have images of an object taken with 3 different cameras. How do I input 3 different camera params into COLMAP pipeline in the process? 

Thank you very much.

**Comment by ahojnnes** [comment]
You cannot do this in feature extraction, but changing all camera parameters/models and sharing parameters between multiple images can be done in the Processing > Database Management widget.

**Comment by resindraburiza** [comment]
Aha! Thank you very much for the answer.

**Comment by alexs7** [comment]
@ahojnnes hello! just wondering if there is support for this now ? I am using COLMAP from the command line, on a remote server with no display capabilities. I have 3 cameras too, so normally I have to run the feature extraction 3 times ?
