### ISSUE TITLE
Weird problem with dense_stereo

### ISSUE THREAD

**Issue by gT-mike** [colmap/colmap#358]
Hi,

I am encountering a weird problem with dense_stereo. I have a dataset with of ~ 800 images with a resolution of 720x1280. When I run the dense_stereo, the photometric depth maps are extracted well but the geometric output is not completely finished. The output says at some point:

==============================================================================
Processing view 217 / 736
==============================================================================

Reading inputs...

PatchMatch::Problem
-------------------
ref_image_id: 593
src_image_ids: 592 591 408 409 410 590 624 626 322 192 197 323 325 191 407 321 324 194 628 193

PatchMatchOptions
-----------------
max_image_size: -1
gpu_index: 0
depth_min: 0.671197
depth_max: 3.08484
window_radius: 7
window_step: 1
sigma_spatial: 7
sigma_color: 0.2
num_samples: 15
ncc_sigma: 0.6
min_triangulation_angle: 1
incident_angle_sigma: 0.9
num_iterations: 5
geom_consistency: 1
geom_consistency_regularizer: 0.01
geom_consistency_max_cost: 3
filter: 1
filter_min_ncc: 0.1
filter_min_triangulation_angle: 3
filter_min_num_consistent: 2
filter_geom_consistency_max_cost: 1
write_consistency_graph: 0

PatchMatch::Run
---------------
Initialization: 0.6841s
 Sweep 1: 3.4685s
 Sweep 2: 2.2162s
 Sweep 3: 3.4689s
 Sweep 4: 2.2142s
Iteration 1: 11.3680s
 Sweep 1: 3.4332s
 Sweep 2: 2.1873s
 Sweep 3: 3.4351s
 Sweep 4: 2.1662s
Iteration 2: 11.2221s
 Sweep 1: 3.3880s
 Sweep 2: 2.1254s
 Sweep 3: 3.4169s
 Sweep 4: 2.1071s
Iteration 3: 11.0378s
 Sweep 1: 3.3627s
 Sweep 2: 2.0789s
 Sweep 3: 3.3861s
 Sweep 4: 2.0648s
Iteration 4: 10.8928s
 Sweep 1: 3.3465s
 Sweep 2: 2.0388s
 Sweep 3: 3.3619s
 Sweep 4: 1.9880s
Iteration 5: 10.7354s
Total: 55.9403s

Writing geometric output for frame_00951.color.png

==============================================================================
Processing view 218 / 736
==============================================================================

Reading inputs...

PatchMatch::Problem
-------------------
ref_image_id: 594
src_image_ids: 595 596 597 410 325 621 326 619 411 324 727 623 323 419 420 322 327 643 617 613

PatchMatchOptions
-----------------
max_image_size: -1
gpu_index: 0
depth_min: 0.624623
depth_max: 1.72132
window_radius: 7
window_step: 1
sigma_spatial: 7
sigma_color: 0.2
num_samples: 15
ncc_sigma: 0.6
min_triangulation_angle: 1
incident_angle_sigma: 0.9
num_iterations: 5
geom_consistency: 1
geom_consistency_regularizer: 0.01
geom_consistency_max_cost: 3
filter: 1
filter_min_ncc: 0.1
filter_min_triangulation_angle: 3
filter_min_num_consistent: 2
filter_geom_consistency_max_cost: 1
write_consistency_graph: 0

PatchMatch::Run
---------------

==============================================================================
Processing view 219 / 736
==============================================================================

Reading inputs...

==============================================================================
Processing view 220 / 736
==============================================================================

Reading inputs...

Could you imagine what the problem could be? Once I had the problem that the HDD was full but then the runner just stopped to write any output at all (since there was no more free space available). This problem seems to be different as I made sure that the HDD has sufficient space available.

Many thanks,
Mike

**Comment by odiseo123** [comment]
Have you re-started the dense reconstruction from scratch? I had also unexpected issues after a full hard drive.  Probably something gets corrupted along the way. For me erasing the dense folder and restarting the dense reconstruction solved the issue.

**Comment by gT-mike** [comment]
Ok, I'm pretty sure now that it was due to problem with RAM full .. @ahojnnes : Maybe you could look at which point you could free up some memory space..? Or does geometric reconstruction require all photometric results to be in the memory?

**Comment by gT-mike** [comment]
ah okay, that is what I suspected .. the size has to be specified in mb or gb?

**Comment by ahojnnes** [comment]
GB

**Comment by gT-mike** [comment]
Thanks, now it works perfectly. We can close the issue :)
