### ISSUE TITLE
Can't load model generated in Linux to Windows installation

### ISSUE THREAD

**Issue by danilnagy** [colmap/colmap#359]
Hi, thanks for the great software. I am having an issue where if I reconstruct a model on a Linux machine, when I load that model into an installation an a Windows machine it looks very strange. Here is a screenshot of the model on Linux:

<img width="1185" alt="capture_16" src="https://user-images.githubusercontent.com/4085524/39591532-05b62e9c-4ed2-11e8-844e-4b20c7dd8685.PNG">

and here is the same model loaded on the Windows machine:

<img width="891" alt="capture_20" src="https://user-images.githubusercontent.com/4085524/39591544-14ea5fb4-4ed2-11e8-995c-e8666852d655.PNG">

Do you know why this might be happening?

Thanks!

**Comment by danilnagy** [comment]
Thanks for the response! I am running without GPU on the Windows machine. Do I need GPU to load the model?

**Comment by ahojnnes** [comment]
Yes, software OpenGL usually leads to these kind of artifacts in the viewer. Closing this issue as resolved then.
