### ISSUE TITLE
prior focal length

### ISSUE THREAD

**Issue by logmove** [colmap/colmap#361]
Hi,

In the featuring matching step, I set custom parameters and set the prior_focal_length to 1. I found that even if I randomly set the focal length that deviate from the true value largely, the output of feature matching still return a valid E and the config is 2.  For example. I set simple_pinhole model sharing for all images, of which the true focal length is around 400, but when I set it as either 10 or 10000000000, the config returned can be 2 for some pairs. This means colmap think the prior calibration is correct。 How this is possible? Thanks!

**Comment by ahojnnes** [comment]
Would you be able to share the two images with me?

**Comment by logmove** [comment]
I attach a few image for you. i am using colmap gui in windows. 
Thanks!
[images1.zip](https://github.com/colmap/colmap/files/1983819/images1.zip)

**Comment by ahojnnes** [comment]
Essential matrix estimation is typically very robust against changes in the calibration and the approach in COLMAP to detect a wrong calibration only works for large changes in the distortion parameters. If you want to be stricter on the decision, you could try altering the following parameters: https://github.com/colmap/colmap/blob/dev/src/estimators/two_view_geometry.h#L59 Closing this issue as resolved but feel free to follow up in case of further questions.

**Comment by logmove** [comment]
It happens even when I use some models with distortion parameters like simple_radial or radial. The most wired case is that it still happens when the opencv model is used with all the parameters randomly set. 
But this does not happen when a fisheye model is used. Can you provide any explanation? Thanks!

**Comment by logmove** [comment]
Hi Johannes,

Can you kindly respond to my further questions on the github page? Your
assistance is highly appreciated.

Best regards,
Bingbing Zhuang

2018-05-08 22:36 GMT+08:00 Johannes Schönberger <notifications@github.com>:
