### ISSUE TITLE
Question around "Reconstruct sparse/dense model from known camera poses"

### ISSUE THREAD

**Issue by odiseo123** [colmap/colmap#363]
Hi again @ahojnnes,
More than an issue is a question of understanding around the FAQ section "Reconstruct sparse/dense model from known camera poses".
In my application I use the same camera (several video sequences) with known intrinsics. I give the camera priors to COLMAP and also subsample the videos to maximize baseline while maintaining overlap in the image content.
As an example, I am obtaining a sparse point cloud of 12501 points from 1250 images. Naturally poses and 3D points are defined up-to scale.
I have exported the images.txt file and modify it to include a known scale factor (plus initial translation/rotation). When I re-import the images.txt files I can see in COLMAP the cameras reoriented in a way consistent with my world reference frame. By double-clicking the camera widgets I can see that the camera pose information is consistent with my world/application frame (details on the conversion process below). 
Now I attempt to recreate the 3D points from the new camera poses using:
colmap point_triangulator \
    --database_path $PROJECT_PATH/database.db \
    --image_path $PROJECT_PATH/images
    --import_path path/to/manually/created/sparse/model \
    --export_path path/to/triangulated/sparse/model
I use the same parameters as logged in the project.ini - "Mapper" section.

The resulting sparse model (with scale and orientation) features now only 1114 points from the same 1250 images. This is about 10% of the original (up-to-scale) point cloud.

*I do not understand why I am getting only 10% of the 3D points if all camera poses have been transformed with the same similarity matrix.*
My only guess at the moment is that the automated process uses colmap_mapper (which uses colmap_point_triangulator plus several other functions) while my manual process is using only the colmap_point_triangulator. Maybe these other functions assist adding/keeping track of triangulated points?
I am still able to proceed and generate the depth maps and dense reconstruction. Nonetheless I am worried that by losing 90% of the original 3D points, the dense reconstruction would not be as accurate as it could.

Details on my creation of the modified images.txt file:
-Get all COLMAP quaternions/translation vectors.
-Convert them in 4x4 transformation matrices.
-Premultiply all by a known and constant 4x4 similarity transformation.
-Revert to quaternion/translation notation.
-Recreate images.txt file.

The appropriate quaternion/hamiltonean/camera-centered conversion has been verified using the Matlab scripts.

**Comment by ahojnnes** [comment]
I can only guess that your similarity transformation is applied incorrectly. Can you try to replicate the following code in your code: https://github.com/colmap/colmap/blob/dev/src/base/similarity_transform.cc#L61

**Comment by odiseo123** [comment]
Hi @ahojnnes
As I mentioned at the end of the post the conversions/transformation were already verified to be correct by comparing them to your Matlab scripts. 
Thanks for the prompt suggestion in any case. I have found the root of the issue. I leave it here for future reference:

In my case I use the sparse reconstruction to get the camera poses up-to-scale. Since I require a metric reconstruction I proceed to apply a similarity transform and update/overwrite the camera poses in the images.txt file before moving to the dense reconstruction. Unknowingly I was letting the 2D feature data unchanged:
%   IMAGE_ID, QW, QX, QY, QZ, TX, TY, TZ, CAMERA_ID, NAME
%   POINTS2D[] as (X, Y, POINT3D_ID)
Note that POINTS2D array contains valid indices for 3D points of the original sparse cloud.
**The solution is to set all indices to -1 and clear all data in the file points3D.txt**

Some caveats:
-Do not simply delete the file points3D.txt, just clear the data in it. Deleting the file will cause this error at the end of the triangulation:

Bundle adjustment report
------------------------
    Residuals : 423094
   Parameters : 45939
   Iterations : 6
         Time : 21.756 [s]
 Initial cost : 0.904805 [px]
   Final cost : 0.716459 [px]
  Termination : Convergence

  => Merged observations: 167
  => Completed observations: 14415
F0512 17:16:58.847370 58527 reconstruction.cc:1925] Check failed: point2D.HasPoint3D()

-If you do not set all POINT3D_ID to -1, the program will look for the valid indices in the Points3D.txt file. If the file has been cleared, an out_of_range error will be issued:
==============================================================================
Triangulating image #1
==============================================================================

  => Image has 747 / 1025 points
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at

-If you do not set all POINT3D_ID to -1, the program will look for the valid indices in the Points3D.txt file. If the file has NOT been cleared, the triangulation will only be attempted for those points with index -1. These are generally bad points which were not triangulated in the original sparse reconstruction. My guess is that the old 3D points (the ones with a valid index) are ignored altogether since the BA still converges. Overall this leads to a very sparse point cloud. Note that this corresponds to the original issue that motivated this thread.

**Comment by Poutsh** [comment]
Hi, I update this issue to ask for some clarifications.

What do you mean @odiseo123 by "clearing" Points3D.txt? Do you mean deleting all the lines in the file?
Because when I do that, alongside replacing the poses in images.txt and giving -1 as id for all the points, when I use patch_match_stereo, I get this for all the images : 
```
WARNING: Ignoring reference image im_000065.png, because it has no source images
```

Thank you in advance.

**Comment by ahojnnes** [comment]
@Poutsh If you don’t provide any 3D points the visibility cannot be determined from the sparse model. Either explicitly set the source images for each reference view or use all source images. Please see here for more details: https://colmap.github.io/faq.html#manual-specification-of-source-images-during-dense-reconstruction

**Comment by Poutsh** [comment]
@ahojnnes I followed the tutorial but I don't get a good mesh in the end, I guess that's because my poses aren't good enough, I had the same problem with OpenMVG. Is there a way to just give an initial pair of poses and baseline in order to have the scale I want?

**Comment by ahojnnes** [comment]
Which mesher did you use? Can you show an example screenshot of the sparse/dense/mesh?

**Comment by Poutsh** [comment]
@ahojnnes I finally fixed my issue it was a problem with my quaternion/rotation matrix that needed to be inversed

**Comment by Dragoncatinjapan** [comment]
@ahojnnes Hello, ahojnnes. I have some questions about the "Reconstruct sparse/dense model from known camera poses".
1) In the images.txt, where should I set the coordinate system for these points?
2) In the outpu images.txt from colmap, where is the coordinate system?
Overall, I want to know the difitition of coordinate system in COLMAP.
