### ISSUE TITLE
reproducing the results in the paper

### ISSUE THREAD

**Issue by logmove** [colmap/colmap#364]
Hi Johannes,

I wonder how to reproduce the results you presented in the Tab.1 of your "structure from motion revisied" paper. I have tried the automatic reconstruction, where each image is matched against its 100 nearest neighbours according the given vocabulary tree. In this setting, the reconstructed cameras are much more than shown in Tab.1. For example, NYC_Library reconstruct 649 cameras and Alamo 943 cameras, while in the paper they are 453 and 666 respectively. Looking forward to your reply. Thanks.

**Comment by ahojnnes** [comment]
Hi,

The results from the paper are not produced with the current COLMAP version on Github but a much older version, that predates the Github release. As you can see, the pipeline got quite a bit better in the meantime. Would you need those exact models for a paper submission or are you just interested in the best possible results?

Cheers,
Johannes

**Comment by logmove** [comment]
Hi Johannes,

Thanks for the reply. I am just interested. Can you comment on what is the main reasons leading to such  big improvements compared to the results in the paper? Thanks.

**Comment by ahojnnes** [comment]
It's a combination of improvements of the incremental reconstruction algorithm, bug fixes, improvements of the local feature extractor/matcher, and a better implementation of the vocabulary tree. So, in the end, not a single reason that made it better but many small things.
