### ISSUE TITLE
single_camera = 1 results in principal point being at (0, 0)

### ISSUE THREAD

**Issue by fishcu** [colmap/colmap#365]
Hi, I am running colmap built from latest source. OS is Ubuntu 16.04. GPU computation is enabled.

I am running colmap through the CLI with the following commands, on a small testing dataset:
1. feature_extractor with single_camera=1 and camera_model=OPENCV
2. exhaustive_matcher
3. mapper
4. model_converter with output_type=TXT

When looking at the generated cameras.txt, I notice an output like the following:
`1 OPENCV 1280 720 1600.09 948.289 0 0 -0.529335 0.146421 0.104783 0.0186571`

Note that the principal point is (0, 0). This happens with all distortion models (SIMPLE_RADIAL, RADIAL, OPENCV) that I tested.

When I set single_camera = 0 (default), I have a single camera which has (0, 0) as principal point, with the others having reasonable values. 

I was not able to find in the source code how single_camera would have an impact on the principal point.

**Does (0, 0) as principal point indicate some kind of failure? I notice that I always get this result with single_camera=1, and I get it for very few cameras in the single_camera=0 configuration.**

**Or is there some other bug?** If anything, I would expect the optimizer to have a more stable result, since there are far less parameters to optimize over.

I have also exported the SfM result to NVM and PLY, and I can confirm that the output is reasonable even with the reported (0, 0).

**Comment by fishcu** [comment]
I have confirmed that the same behaviour happens with the fully automatic reconstruction, which also provides a "shared intrinsics" checkbox.

**Comment by ahojnnes** [comment]
Can you share one of the images with me for which this happens?

**Comment by fishcu** [comment]
I have attached a small dataset. SfM converges fine with the "RADIAL" model. 

Actually I think there is generally a bug in the software that affects the principal point of the very first camera.
You can see that when using single_camera = 0, the principal point of the first camera is (0, 0), whereas all the others have "normal" principal points (resolution / 2). Of course, when using single_camera = 1, there is only the first camera, and the principal point is as we observe.

I have noticed a similar strange behaviour when exporting to NVM (VisualSFM) format. The principal point of the first camera will be correct in this case, because VSFM has the quirk of using (0, 0) as a reference for all calculations. However, in that case all the other cameras will be wrong (as can be confirmed by calculating reprojection errors, for example).

Could you maybe please check if such a bug is plausible?
I can work out a better bug report, but not before next week, as I am busy right now.


[images.zip](https://github.com/colmap/colmap/files/2012674/images.zip)

**Comment by fishcu** [comment]
FYI, here's the cameras.txt extracted from the above dataset. Clearly, camera #1 is an outlier in terms of the principal point.

```# Camera list with one line of data per camera:
#   CAMERA_ID, MODEL, WIDTH, HEIGHT, PARAMS[]
# Number of cameras: 8
8 RADIAL 1280 720 705.044 640 360 -0.175866 0.0321891
7 RADIAL 1280 720 706.611 640 360 -0.171427 0.0279206
6 RADIAL 1280 720 711.744 640 360 -0.16106 0.0212942
5 RADIAL 1280 720 718.013 640 360 -0.162642 0.0191932
1 RADIAL 1280 720 2494.6 0 0 -0.250865 0.041294
2 RADIAL 1280 720 733.584 640 360 -0.14921 0.0141329
3 RADIAL 1280 720 734.488 640 360 -0.1615 0.0213787
4 RADIAL 1280 720 725.893 640 360 -0.165237 0.0218121
```

**Comment by veloman-yunkan** [comment]
I have a fix for this issue. Will submit a pull request tomorrow.

**Comment by veloman-yunkan** [comment]
https://github.com/colmap/colmap/pull/367

**Comment by ahojnnes** [comment]
Thanks for the fix, considering this as resolved.
