### ISSUE TITLE
Automatically generating a scaling factor

### ISSUE THREAD

**Issue by cpederkoff** [colmap/colmap#368]
What you would recommend for automatically generating a scaling factor, assuming I could put something of known size in the scene to be reconstructed?

**Comment by ahojnnes** [comment]
You could try to use a marker and then detect it automatically later in the images. OpenCV should have all the necessary functions for this. This could be done as a post processing step after COLMAP.

**Comment by cpederkoff** [comment]
Sounds good. How would you suggest I associate 2d locations on an input image with 3d locations in the output?
