### ISSUE TITLE
Mapper not working

### ISSUE THREAD

**Issue by aditya9211** [colmap/colmap#369]
colmap mapper \
    --database_path $DATASET_PATH/database.db \
    --image_path $DATASET_PATH/images \
    --export_path $DATASET_PATH/sparse

![image](https://user-images.githubusercontent.com/22274190/40277665-7fded518-5c40-11e8-9c14-13f48a0b0d9f.png)

> No initial good image pair found
How to resolve it as exhaustive matcher API ran well

**Comment by ahojnnes** [comment]
As the log suggests, the software couldn’t find a suitable initial image pair. Without seeing the images or other I formation, it is not possible for me to give any reason or advice.

**Comment by aditya9211** [comment]
Kindly find the images below

And what's settings should be imparted
 Set2.zip
<https://drive.google.com/file/d/19sBEibd5r0oHKY0-KE1iWHy7GJPWNmGg/view?usp=drive_web>
​



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&>

**Comment by ahojnnes** [comment]
The images have very small baseline, so you have to reduce the minimum triangulation angle. You can find a reconstruction of the scene here: https://drive.google.com/open?id=18UgpFrqS0OAGtZIDxM492YY-qNX5UHkY

I set the following options to improve the results:
```
[SiftExtraction]
estimate_affine_shape=true
domain_size_pooling=true

[SiftMatching]
guided_matching=true

[Mapper]
init_min_tri_angle=4
```

**Comment by aditya9211** [comment]
Hi Johannes,

I have applied the dense reconstruction (colmap dense_stereo) on my
datasets, and it produces depth_maps and normal_maps folder.
However, I do not know how to get a disparity map from these folders. Can
you kindly suggest me away or does colmap GUI provides disparity map from
these folders?

Thanks,
Aditya




‌
[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&>
