### ISSUE TITLE
Host Binaries w/ Github Releases

### ISSUE THREAD

**Issue by nikhiljha** [colmap/colmap#372]
The binary downloads from `https://demuc.de/colmap/#download` are really slow for me.

Hosting them on GitHub (upload the file when a new release tag is made) would make it faster.

**Comment by ahojnnes** [comment]
That's a good idea. I will also host them there in parallel (starting sometime next week).

**Comment by ahojnnes** [comment]
This is now done and implemented at https://demuc.de/colmap/ and https://github.com/colmap/colmap/releases

Thanks for the suggestion.
