### ISSUE TITLE
Registaring photos during reconstruction.

### ISSUE THREAD

**Issue by Sebhenth** [colmap/colmap#373]
Hi,

I am reconstructing an object by using several 360 loops with a dslr, (120 photos). After exhaustive matching, each photo has multiple matches, yet during reconstruction only ~30% fov is being covered as the rest of the images aren't being registered. I have tried choosing initial pairs on the side that was covered by it would not accept them, despite the pairs have 30+ matches. Is there something I'm missing? what can i do to lower the constraints of the reconstruction?

**Comment by Sebhenth** [comment]
Hi thanks,

 

https://drive.google.com/drive/folders/1ePffdFumTUBpN_BkFmXbjlBVKAdrDv_E?usp=sharing

 

There is 120 photos. Would greatly appreciate you taking a look! 

 

Like I said the problem is that the reconstruction is incomplete.

 

Regards,

 

Daniel

**Comment by Sebhenth** [comment]
Appologies, I had to give you explicit access. You have it now. I really appreciate the help

**Comment by ahojnnes** [comment]
I had a look at the images. You barely have any texture in those images. Rather than using white background, I suggest to use something with more texture. Later you could carve out the object of interest eg using Meshlab.

**Comment by Sebhenth** [comment]
Hi, thanks for looking. I originally took the pictures without the white backround, but to a similar effect, but I suppose you are also referring to the plain texture of the object itself also. I have tried now with a different endoscope and added stickers on plain areas, and it seems to be working much better.

**Comment by ahojnnes** [comment]
Sounds great. If there is not much texture in the images, I also suggest to use the following options:
```
[SiftExtraction]
estimate_affine_shape=true
domain_size_pooling=true

[SiftMatching]
guided_matching=true
```

**Comment by Sebhenth** [comment]
Okay, I will try this. May I ask, in your experience, do you think that an accurate model (~1mm) is a possibility considering the shape of the object? There have been people try to model this scope using depth cameras and even a CT scan and the results haven’t been so great. I am hoping this method will be more accurate, from what I’ve seen it can be. Do you think this to be the case? Thanks again.

**Comment by ahojnnes** [comment]
I don't know the true size of the object and your camera, but I don't think 1mm is something you can achieve from those images.

**Comment by Sebhenth** [comment]
Hi Johannes,

 

I ended up putting a powder on a different and re-took the photos. The results after some time in meshlabs are brilliant. (After some time debugging crashes at stereo). Thank you for having your software open.
