### ISSUE TITLE
Crash Colmap on Stereo

### ISSUE THREAD

**Issue by TeraBite93** [colmap/colmap#374]
Hi, as soon as I push "Stereo" the program will close after a few seconds. I tried to change the registry but it does not change anything. I tried both with the stable version and with the recommended one.

**Comment by ahojnnes** [comment]
Might be that you do not have sufficient GPU memory. How big are your images? How much memory do you have?

**Comment by ahojnnes** [comment]
Closing due to lack of feedback.
