### ISSUE TITLE
feature_extractor error：invalid device function

### ISSUE THREAD

**Issue by laixiaodong** [colmap/colmap#375]
Hello, sorry to disturb
I compiled colmap on my own computer after downloading the source code. When I run colmap feature_extractor, I get an error as follows.
filterH: invalid device function
filterV: invalid device function
....
PyramidCU::generateFeatureList: invalid device function

My CUDA version is 8.0
But when I directly download the colmap.exe that you have compiled and it works fine, can you tell me what the problem might be? Thank you, looking forward to your answer

**Comment by laixiaodong** [comment]
It is worth noting that the normal operation of the desktop, but not normal in the notebook, is the reason for the dual graphics card

**Comment by ahojnnes** [comment]
I don’t know what the issue is to be honest. Did you compile eight OpenGL/CUDA support?

**Comment by ahojnnes** [comment]
What platform are you on?

**Comment by laixiaodong** [comment]
YES, and my platform is win7, vs2015

**Comment by laixiaodong** [comment]
I got the reason，because I didn't check CUDA_MULTI_ARCH due to a GPU version issue. Same thanks

**Comment by laixiaodong** [comment]
@ahojnnes I got the reason，because I didn't check CUDA_MULTI_ARCH due to a GPU version issue. Same thanks

**Comment by ahojnnes** [comment]
Great you resolved the issue, thanks for posting the solution.

**Comment by cnpanda-1** [comment]
> @ahojnnes I got the reason，because I didn't check CUDA_MULTI_ARCH due to a GPU version issue. Same thanks

I have encountered the same problem. Could you talk more in detail?Thanks
