### ISSUE TITLE
Speed up colmap mapper

### ISSUE THREAD

**Issue by gT-mike** [colmap/colmap#376]
Hi, 

sorry - again me. This time about the mapper: Is there a way to speed up the mapper? Can it run on GPU to go quicker? As far as I can see, if I ran the mapper on default parameters the GPU of my machine is not used at all.

Many thanks,
Mike

**Comment by ahojnnes** [comment]
No, it cannot be speeded up using the GPU. You can try to use fewer features / matches in the reconstruction stage or reduce the number of bundle adjustment iterations, frequency of global bundle adjustment, etc.

**Comment by ahojnnes** [comment]
There is also a `hierarchical_mapper` in the latest dev version. It is not as robust yet for complex scenes, but it will speed up the process for large reconstructions.

**Comment by ahojnnes** [comment]
The hierarchical mapper partitions the scene into separate clusters, reconstructs them separately and then finally merges them together. The merging implementation is not too robust at the moment and can potentially fail.

**Comment by isolin** [comment]
Hi Johannes! The hierarchical mapper sounds very exciting. I hope to find time to test it next week. Does it help only with the sparse reconstruction stage, or is it possible to postpone the merging after the dense stage?

**Comment by gT-mike** [comment]
Failed in my case a couple of times but I will keep in mind that there is somthing there.

Thanks

**Comment by hariharan1412** [comment]
Is `hierarchical_mapper` good now? because when I try to generate spare, the output is only half as good as the original mapper. What can I do to improve the output?

**Comment by xiemeilong** [comment]
@ahojnnes Do you have any ideas on how to improve the robustness of the merging implementation? I would like to give it a try.
