### ISSUE TITLE
how to parse the ini file to linux script

### ISSUE THREAD

**Issue by perthvr** [colmap/colmap#378]
Hi Thanks again for great software
I am trying to parse the ini file into my linux script .
What command do  I associate  the  --project_path path/to/project.ini argument with for instance it doesnt work if I add it as an argument to feature_extractor.
thanks Sally

**Comment by ahojnnes** [comment]
Can you show the ini file that you pass to the feature extractor and the exact command and output you see? Thanks.

**Comment by perthvr** [comment]
HI 
thanks for getting back to me. THis is my linux code it works fine BUT the ini file paramaters dont get used.

#!/bin/bash
PATH=$PATH:=/home/sally/bin
CURRDIR=$PWD
COLDIR=/home/sally/colmap/build/src/exe
OMVS=/home/sally/openMVS_build/bin
cat $OMVS
WORKDIR=/home/sally/monkeymelb2
echo $WORKDIR
echo $CURRDIR
mkdir -p $WORKDIR
cp  /home/sally/monkeymelb/images*.JPG $WORKDIR
cp  /home/sally/monkeymelb/projectnew2.ini  $WORKDIR

cd $WORKDIR

$COLDIR/feature_extractor --project_path projectnew2.ini --database_path database.db --image_path $WORKDIR 	
$COLDIR/exhaustive_matcher  --database_path database.db
mkdir sparse
$COLDIR/mapper --database_path $WORKDIR/database.db \
  --image_path $WORKDIR  \
  --export_path $WORKDIR/sparse
echo MODELCONVERTER


and the first part of my ini file
log_to_stderr=false
log_level=2
database_path=/home/sally/monkeymelb2/database.db
image_path=/home/sally/monkeymelb2
[ImageReader]
single_camera=true
default_focal_length_factor=1.2
camera_model=PINHOLE
camera_params=
[SiftExtraction]
use_gpu=true
estimate_affine_shape=false
upright=false
domain_size_pooling=false
num_threads=-1
max_image_size=3200
max_num_features=8192

**Comment by ahojnnes** [comment]
``$COLDIR/feature_extractor --project_path projectnew2.ini --database_path database.db --image_path $WORKDIR``

Probably because you provide both the ``--project_path`` and other parameters from the command line. You should do one or the other but not both at the same time.

**Comment by perthvr** [comment]
hi so I have seperated -- project_path from --database_path like so

$COLDIR/database_creator --database_path $WORKDIR/database.db
$COLDIR/feature_extractor --project_path $WORKDIR/projectnew2.ini --image_path $WORKDIR

 however feature_extractor doesnt work because it does not point to database.db. so what command should I use so that the  ini file can be seen. is there a command called project_creator  
cheers and thanks sally

**Comment by ahojnnes** [comment]
Well, I guess the error message is pretty clear. The project.ini contains log_to_stderr but it is not an accepted option by the executable?

**Comment by perthvr** [comment]
but so I take that off and then I get the next line as the error so on and so forth so there is something wrong with my ini file or the way it is being parsed.  I have run it about 40 times with different configurations of project path etc taking lines of the ini and different ways to point to the ini file. it works as long as i dont use the ini file.

**Comment by perthvr** [comment]
Hi
perhaps there is a special way to write the ini file at this stage I have used the ini file created from the gui application. here is an example of the first 20 or so lines  (I have cut the first 8  lines trying to get it to work)
 database_path=/home/sally/monkeymelb2/database.db
[ImageReader]
camera_model=PINHOLE
camera_params=
[SiftExtraction]
use_gpu=true
estimate_affine_shape=false
upright=false
domain_size_pooling=false
num_threads=-1
max_image_size=3200
max_num_features=8192
first_octave=-1
num_octaves=4
octave_resolution=3
max_num_orientations=2
dsp_num_scales=10
peak_threshold=0.0066699999999999997
edge_threshold=10
dsp_min_scale=0.16667000000000001
dsp_max_scale=3
gpu_index=-1
[SiftMatching]
use_gpu=true
cross_check=true
multiple_models=false
guided_matching=true
num_threads=-1
max_num_matches=32768
max_num_trials=12000
min_num_inliers=6
max_ratio=0.80000000000000004
max_distance=0.69999999999999996
max_error=4
confidence=0.999
min_inlier_ratio=0.20000000000000001 

here is the most recent error  ERROR: Failed to parse options unrecognised option 'ImageReader.camera_model'.
thanks sally

**Comment by FelixEickeler** [comment]
Actually I faced the same problem. You can remove the problmatic lines but the next error will just pop up. After I encountered an option that was really needed, I stoped trying . If I can help improve this, please let me know.

**Comment by ahojnnes** [comment]
``SiftMatching`` is not an option for the feature extractor but for the feature matchers. It works perfectly well for me with this command ``colmap feature_extractor --project_path ~/Desktop/project.ini`` and these options:

```
database_path=/Users/username/Desktop/database.db
image_path=/Users/username/Desktop/
[ImageReader]
single_camera=false
single_camera_per_folder=false
existing_camera_id=-1
default_focal_length_factor=1.2
camera_model=SIMPLE_RADIAL
camera_params=
[SiftExtraction]
use_gpu=true
estimate_affine_shape=false
upright=false
domain_size_pooling=false
num_threads=-1
max_image_size=3200
max_num_features=8192
first_octave=-1
num_octaves=4
octave_resolution=3
max_num_orientations=2
dsp_num_scales=10
peak_threshold=0.0066666666666666671
edge_threshold=10
dsp_min_scale=0.16666666666666666
dsp_max_scale=3
gpu_index=-1
```

**Comment by ferreram** [comment]
I had the same problem and I found a workaround.

It seems that the commands cannot use the full .ini file, if more options than the ones they need are given it will fail.  For example, if you try performing the feature extraction step with the options of [SiftMatching] it will fail but if you only let the right options it will run correctly.  Performing "exhaustive_matcher" with a ".ini" containing "image_path" or [ImageReader] will fail as well as "exhaustive_matcher" only reads the database_path and [SiftMatching] options

So my workaround is to write one ".ini" file per step with the right options given for each.  It is not very practical but it works.

**Comment by ahojnnes** [comment]
Each module only takes its specific arguments and it will fail, if there is an unrecognized option. You will have to split up the full project.ini into the different parts used by each module.
