### ISSUE TITLE
Problem with Dense Stereo with parallelization on GPUs

### ISSUE THREAD

**Issue by gT-mike** [colmap/colmap#379]
Hi Johannes,

I recently encountered the following problem with running Dense Stereo. I wanted to speed up Dense Stereo by running on multiple GPUs but ran into the following problem: When I run dense stereo on 1 GPU I get the following result (chess as an example here):

![image](https://user-images.githubusercontent.com/37045813/41142229-427f2894-6af5-11e8-938d-91ecc859e7b2.png)

So things are fine, everything is good. When I start running it on multiple GPUs (2 threads per GPU), i.e. with the following parameter "--DenseStereo.gpu_index=0,0,1,1" the result is the following:

![image](https://user-images.githubusercontent.com/37045813/41142290-6f73a6d6-6af5-11e8-8f8a-1c7bb5efeded.png)

**UPDATE:**

I just tried to run with one thread per GPU (i.e. with --DenseStereo.gpu_index=0,1) and then things are fine, so clearly this seem to be an issue with multiple threads per GPU.

Is this a know problem? Any quick fix?

Many thanks!
Mike

**Comment by ahojnnes** [comment]
Not sure what is going on. Multi-threading on one GPU should work. However, typically you do not gain from running multiple instances on the same GPU, since one instance occupies all resources.

**Comment by ahojnnes** [comment]
You could also start separate ``colmap dense_stereo`` processes on the same GPU. Each process would get a different patch-match.cfg with different views (non-overlapping). From an implementation standpoint, you could do something like this:
```
cp path/to/workspace/stereo/patch-match.cfg path/to/workspace/stereo/patch-match-backup.cfg
num_patch_match_cfg_lines=$(wc -l path/to/workspace/stereo/patch-match.cfg)
cat path/to/workspace/stereo/patch-match-backup.cfg | head -n $((num_patch_match_cfg_lines / 2) > path/to/workspace/stereo/patch-match.cfg
colmap dense_stereo ... --DenseStereo.gpu_index 0
cat path/to/workspace/stereo/patch-match-backup.cfg | tail -n $((num_patch_match_cfg_lines / 2) > path/to/workspace/stereo/patch-match.cfg
colmap dense_stereo ... --DenseStereo.gpu_index 0
...
```

**Comment by gT-mike** [comment]
Thanks, this is an intersting idea worth trying. I will do and keep you updated if you like.  If you tried - could you reproduce the problem on your machine?

**Comment by ahojnnes** [comment]
I did not explicitly try now but did in the past and it worked back then.

**Comment by ahojnnes** [comment]
Closing this as resolved for now. Please follow up in case you have more questions.
