### ISSUE TITLE
CUDA_VERSION_MAJOR in CMAKE

### ISSUE THREAD

**Issue by flm8620** [colmap/colmap#38]
In [here](https://github.com/colmap/colmap/blob/d8d6f9aa445c637d29d0414f0c0f8d5afab0dd83/src/ext/PBA/CMakeLists.txt#L18) and [here](https://github.com/colmap/colmap/blob/d8d6f9aa445c637d29d0414f0c0f8d5afab0dd83/src/ext/SiftGPU/CMakeLists.txt#L78)

`elseif(CUDA_VERSION_MAJOR LESS 7)`

should be replaced by 

`elseif(CUDA_VERSION_MAJOR GREATER 7)`

I think that's why I have error "invalid device function" with  GTX 1070 and CUDA 8.0 when running sparse reconstruction.

**Comment by ahojnnes** [comment]
You are absolutely right, this is fixed in https://github.com/colmap/colmap/commit/15dfbaeea7e7c1bb77d19863e6588a792355da04

Thanks for the bug report!
