### ISSUE TITLE
Question:how to get camera center coordination?

### ISSUE THREAD

**Issue by smeeteday** [colmap/colmap#381]
Thank you very much for the wonderful software. We are using it conveniently.

Well, I'm happy if I can export the coordinates of the camera position of each recognized image.

Can anyone tell me how to retrieve the camera center coordinates?

**Comment by ahojnnes** [comment]
See https://colmap.github.io/format.html#images-txt

**Comment by ahojnnes** [comment]
Marking this as resolved. Feel free to follow up in case there are any additional questions.

**Comment by smeeteday** [comment]
Thank you,so much.
