### ISSUE TITLE
Error compiling in Antergos

### ISSUE THREAD

**Issue by cabezacabra** [colmap/colmap#382]
Hi, i'm trying to compile colmap in antergos and when it is almost done i get this error, can you help me please?
<pre>[100%] <font color="#8AE234"><b>Linking CXX executable colmap</b></font>
/usr/lib/libjxrglue.so: referencia a `WMPAlloc&apos; sin definir
/usr/lib/libjxrglue.so: referencia a `ImageStrDecTerm&apos; sin definir
/usr/lib/libjxrglue.so: referencia a `WMPhotoTranscode&apos; sin definir
/usr/lib/libjxrglue.so: referencia a `ImageStrDecGetInfo&apos; sin definir
/usr/lib/libjxrglue.so: referencia a `ImageStrDecInit&apos; sin definir
/usr/lib/libjxrglue.so: referencia a `ImageStrEncTerm&apos; sin definir
/usr/lib/libjxrglue.so: referencia a `WMPFree&apos; sin definir
/usr/lib/libjxrglue.so: referencia a `ImageStrEncInit&apos; sin definir
/usr/lib/libjxrglue.so: referencia a `CreateWS_File&apos; sin definir
/usr/lib/libjxrglue.so: referencia a `ImageStrDecDecode&apos; sin definir
/usr/lib/libjxrglue.so: referencia a `CreateWS_Memory&apos; sin definir
/usr/lib/libjxrglue.so: referencia a `ImageStrEncEncode&apos; sin definir
collect2: error: ld devolvió el estado de salida 1
make[2]: *** [src/exe/CMakeFiles/colmap_exe.dir/build.make:136: src/exe/colmap] Error 1
make[1]: *** [CMakeFiles/Makefile2:781: src/exe/CMakeFiles/colmap_exe.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
</pre>

**Comment by ahojnnes** [comment]
Not sue what is going on on your machine and I have also never used Antergos. Seems like there are missing libraries in the linking process. This seems to be related to the FreeImage library, see https://github.com/leapmotion/FreeImage/blob/master/Source/LibJXR/image/sys/strcodec.c where I found the ``WMPAlloc`` function.

**Comment by cabezacabra** [comment]
Ok, this morning freeimage just updated so i tried to compile again and it did it. Ty for everything. I guess is all :D
