### ISSUE TITLE
No good initial image pair found

### ISSUE THREAD

**Issue by laixiaodong** [colmap/colmap#385]
Hello, sorry to disturb
When I test the same set of data, sometimes there will be "No good initial image pair found", resulting in sparse reconstruction result is wrong, sometimes it does not, display the correct result, is this normal?
I tested on win7, the version is not the latest, last year's source code, thank you answer ~

**Comment by ahojnnes** [comment]
Is there any reason not to try the latest version?

**Comment by laixiaodong** [comment]
It may be, but what I want to understand is whether there is a randomness that causes failure when selecting the initial matching pair.

**Comment by ahojnnes** [comment]
There are my randomized algorithms in the overall pipeline, so you will not see consistent results between different runs, especially when the solution is unstable.

**Comment by laixiaodong** [comment]
thanks！i got another problem"The Nvidia Geforce xxxx device is not removable and cannot be ejected or unplugged"，Is it because my driver is so new? There has been no such problem in the original version。

**Comment by ahojnnes** [comment]
This problem does not seem directly related to COLMAP. Could you resolve this issue in the meantime?

**Comment by FengLQy** [comment]
Hello, when I fixed the camera and the human body rotated, there was also a problem that the initialization image pair could not be found. How can I solve this problem?
