### ISSUE TITLE
Redundant View Mining?

### ISSUE THREAD

**Issue by XieDufang** [colmap/colmap#386]
Hello Johannes,

I have read your "SfM revisited" paper recently. There is a strategy called "Redundant View Mining" to group highly redundant images. And all images in a group will be parameterized as one in the BA.

I just want to make sure if this strategy is really implemented in the current COLMAP version.
Because I didn't find any parameters or codes related to this strategy. Did I miss it?

Vielen Dank im Voraus!
Xie Dufang

**Comment by ahojnnes** [comment]
No, I didn't maintain the code anymore and removed it from the source code. It really also just makes sense for very large-scale problems with many thousand images.

**Comment by XieDufang** [comment]
Thank you for the answer ^_^
