### ISSUE TITLE
[SOLVED] colmap  just crash with multi angle 

### ISSUE THREAD

**Issue by greatAznur** [colmap/colmap#387]
**Describe the bug**
i  creat my project and import photo no problem
i  start reconstruction  and all camera are ok for all photo 
i  create dense reconstruction  i create worspace and  i click in undistortion ik good to
and i click in sterero and after 10 -15min colmap crash  
 
in stereo  colmap crash with 78 image 
if the image have an angle 

if pictures have a different angle of inclination i have 32 image with 0degree angle and aproximatively with 20-30 degree from high to low 

if I do 78 photos with the same angle of view the software does not crash

 - OS: window 10

 - colmap 3.4 or 3.5dev1

thx for help

**Comment by ahojnnes** [comment]
See https://colmap.github.io/faq.html#fix-gpu-freezes-and-timeouts-during-dense-reconstruction
