### ISSUE TITLE
Best settings for GoPro Hero Session 5

### ISSUE THREAD

**Issue by tiralonghipol** [colmap/colmap#388]
Hi! 
I don't know if this is the right place for a request like this, but what I'd like to achieve is basically a 3D reconstruction from a gopro Hero Session 5 Video (with frames extraction) in an indoor environment.

I would like to know if there are some crucial parameters to take into account in video recording with this camera, because until now the obtained results are pretty bad.
I'm talking abount FoV, protune, iso regulation, frame rate/ resolution... what are the best settings in order to reconstruct, for example, an office corridor ?

Any suggestion would be appreciated!
Thanks

**Comment by ahojnnes** [comment]
The reconstruction will most likely be better if you don't extract every video frame but when you sub-sample the video. In addition, set shared intrinsics and use a more complex camera model like OPENCV or OPENCV_FISHEYE, since the gopro cameras have pretty wide field of view. If the self-calibration fails, try to get an offline calibration of the camera.

**Comment by tiralonghipol** [comment]
Let's make an example: 
- recording in 4K , 30fps
- a video of 60 sec would make 60*30 = 180 frames

what do you mean by 'sub-sample' ? what ratio do you suggest?

**Comment by tiralonghipol** [comment]
Thank you so much!
Another thing: I noticed that in the extraction phase of the frames from the video, that some of them are not completely on focus.. Is this a big issue for the feature extraction ?
What is the impact of the images quality on the behaviour of the algorithm?

**Comment by tiralonghipol** [comment]
ok.. I have to dive into specs because I just got it as a present, I still have to look at each parameter (like the 'protune' function, still a little bit confused on what is it) 
anyway, I'll also try to make a comparison between a cheaper (but global shutter) camera and this gopro that I have
thank you again for your time!
