### ISSUE TITLE
Dense reconstruction after clustering fails

### ISSUE THREAD

**Issue by isolin** [colmap/colmap#389]
Hi, I discovered Colmap a few weeks ago and I fell in love with it. It provides great overview and full control of the 3D reconstruction + it uses GPU which is absolutely awesome! 

I have a dataset with 6400 photos. Sparse reconstruction works fine within 24h, but then after the patchmatch phase it gets stuck at **dense_fuser** with a processing time of ~8h per image, in sum that would be 6 years for all the images. My HW is the most recent Ryzen 2700X with 32Gb RAM and 1080 Ti, not bad I think. So I started to look for a solution to the problem and in the FAQ I found the suggestion to use the undistorter to export the sparse data into the CMVS/PMVS format using:

`"%SCRIPT_PATH%\bin\colmap" image_undistorter --input_path %DIRSPARSE% --image_path %DIRIMG% --output_path %DIRSPARSE% --output_type PMVS`

I started the first clustering tests with a smaller dataset of 194 photos. Using the following commands it creates six clusters option-0000 to option-0005:

```
"%CMVSDIR%\cmvs" %CMVSDATA% 50 16
"%CMVSDIR%\genOption" %CMVSDATA% 0 2 0.7 7 3 16 
```

This is an example of the generated option file:
```
# generated by genOption. mode 1. cluster: 1
level 1
csize 2
threshold 0.7
wsize 7
minImageNum 3
CPU 16
setEdge 0
useBound 0
useVisData 1
sequence -1
maxAngle 10
quad 2.0
timages 45 12 18 21 23 30 31 42 44 53 60 62 63 65 69 76 82 83 85 86 88 89 91 92 94 96 100 109 112 113 114 115 116 117 119 136 138 139 142 158 177 178 179 180 186 189 
oimages 0 
```

Following the .sh scripts generated by image_undistorter I then call:
```
"%SCRIPT_PATH%\bin\colmap" dense_stereo --workspace_path %CMVSDATA% --workspace_format PMVS --pmvs_option_name option-%OPT% --DenseStereo.max_image_size 2048 --DenseStereo.geom_consistency true
"%SCRIPT_PATH%\bin\colmap" dense_fuser --workspace_path %CMVSDATA% --workspace_format PMVS --pmvs_option_name option-%OPT% --input_type geometric --output_path %CMVSDATA%option-%OPT%-fused.ply
"%SCRIPT_PATH%\bin\colmap" dense_mesher --input_path %CMVSDATA%option-%OPT%-fused.ply --output_path %CMVSDATA%option-%OPT%-meshed.ply
```

**Here the problems arise.** The console output for **dense_stereo** starts with a bunch of lines like this one:
`WARNING: Ignoring reference image 00000012.jpg, because it has no source images.`

Concluding with:
`Configuration has 0 problems...`

The warnings relate exactly to the images listed as the `timages` in the option files. I tried various hacks like renaming all the input images to the given pattern of 8-digit integers (of course I created a new database for them), changing the directory from where I call the script both to the images folder and to the pmvs subfolder but none did help. I would appreciate suggestions how to solve this step of feeding the clusters to the **dense_stereo** to be able to continue with the reconstruction. **Dense_fuser** and **dense_mesher** of course crash due to missing input data from the **dense_stereo**.

**Comment by ahojnnes** [comment]
Can you share the whole dense workspace folder (or the sparse reconstruction + original images) with me and I could have a look?
