### ISSUE TITLE
Building error on vs2015

### ISSUE THREAD

**Issue by tmac1002** [colmap/colmap#39]

**Comment by ahojnnes** [comment]
Hm, this issue is empty. Could you please fill your post with content? Thanks.

**Comment by tmac1002** [comment]
Hi,
Before when I build colmap I encountered some errors but in the end I solved it on vs2015. I modified some code. Then when I run the program, some problems has emerged. I've uploaded some snapshot.
![1](https://cloud.githubusercontent.com/assets/11924213/19461311/40bffd00-9516-11e6-9c27-b851558d01d0.JPG)
![2](https://cloud.githubusercontent.com/assets/11924213/19461320/4f37a874-9516-11e6-9967-9fc8925600d9.JPG)

I just was wondering if because I comment some code in the serialization.h, because there is an error when I build it so I comment it.
#ifdef _MSC_VER
// unsigned __int64 ~= unsigned long long
// Will throw error on VS2013
#if _MSC_VER != 1800
//BASIC_TYPE_SERIALIZER(unsigned __int64);
#endif
#endif

**Comment by ahojnnes** [comment]
Can you check in Visual Studio which branch is taken in this Macro here: https://github.com/colmap/colmap/blob/master/src/ext/VLFeat/generic.c#L1653 ? Specifically, is `vl_constructor` executed before feature extraction?

**Comment by tmac1002** [comment]
I copied the newest code and solved the problem, thank you!
