### ISSUE TITLE
Image Index VS Image ID

### ISSUE THREAD

**Issue by XieDufang** [colmap/colmap#392]
Hi Johannes,

the recently added function "dense point cloud visibility export" must be very useful for the following mesh refinement and/or texture mapping. It's a wonderful new feature.

In the comments you wrote that the "image index" is used instead of the original "image id" in the fusion step.

Actually, I found that the zero-based contiguous index is used in the whole mvs module (e.g. mvs::Model, mvs::Workspace, mvs::PatchMatch) for efficient data access. But in many variable names or function names the concept "image_id" is still being used.

To avoid confusion, I would like to fix the related variable naming in my fork. Can I create a pull request then?

Mit freundlichen Gruessen!
Xie Dufang

**Comment by ahojnnes** [comment]
Sounds like a good proposal. Thanks for the suggestion, I'd be happy to merge such a pull request.
