### ISSUE TITLE
Command Line Acess to TwoViewGeometry::Estimate

### ISSUE THREAD

**Issue by SBCV** [colmap/colmap#394]
Hi Johannes, 

the recently added Python script for working with the database is really awesome! 

I used the script to add feature matches to the database (i.e. raw matches)
As far as I see, there is no possibility to call TwoViewGeometry::Estimate in two_view_geometry.cc from the command line to compute geometrically verified matches using raw matches (which are already contained in the database file).

I'm aware of ./colmap matches_importer --match_type 'raw', but in this case the python database interface can not be used.

Am I mistaken here? Is the access already possible? 
Do you intend to add this functionality? 

I can create a PR if you like. In this case it would be nice, if you can give me some advice, e.g. where to add the command line functionality (I guess ./colmap matches_importer is not the right place?)

Cheers,
Sebastian

**Comment by ahojnnes** [comment]
Depending on whether you exhaustively wrote matches for all image pairs to the database, you could just run the ``exhaustive_matcher``, which will only perform geometric verification, if the matches already exist. If you only wrote a subset of the matches to the database, then you would have to use the ``matches_importer`` and use the ``--match_type pairs`` and explicitly provide the list of image pairs to verify. Again, matching will be skipped if they are already in the database and only geometric verification is performed.

**Comment by SBCV** [comment]
Perfect! Thank you!
I think it would be helpful to add an appropriate comment in the python script - others will probably stumble over this as well.
If you want me to add some comments just let me know.

**Comment by zhaoyu199201** [comment]
> Depending on whether you exhaustively wrote matches for all image pairs to the database, you could just run the `exhaustive_matcher`, which will only perform geometric verification, if the matches already exist. If you only wrote a subset of the matches to the database, then you would have to use the `matches_importer` and use the `--match_type pairs` and explicitly provide the list of image pairs to verify. Again, matching will be skipped if they are already in the database and only geometric verification is performed.

Hi,  I read the source code here 
` std::unique_ptr<Thread> feature_matcher;
  if (match_type == "pairs") {
    ImagePairsMatchingOptions matcher_options;
    matcher_options.match_list_path = match_list_path;
    feature_matcher.reset(new ImagePairsFeatureMatcher(
        matcher_options, *options.sift_matching, *options.database_path));
  } else if (match_type == "raw" || match_type == "inliers") {
    FeaturePairsMatchingOptions matcher_options;
    matcher_options.match_list_path = match_list_path;
    matcher_options.verify_matches = match_type == "raw";
    feature_matcher.reset(new FeaturePairsFeatureMatcher(
        matcher_options, *options.sift_matching, *options.database_path));
  } else {
    std::cerr << "ERROR: Invalid `match_type`";
    return EXIT_FAILURE;
  }
`
and found
--match_type=pairs will not perform geometric verification, maybe should set  --match_type=raw ?
