### ISSUE TITLE
Output Dense Result Too Noisy

### ISSUE THREAD

**Issue by CorneliusHsiao** [colmap/colmap#395]
Hello,
I used a set of 116 images of a chair as input, but the final meshes generated is too noisy beneath the top surface. Here two screenshots are sparse and the final result.
![imageedit_3_9610341947](https://user-images.githubusercontent.com/23747905/41667366-c4891cc6-747a-11e8-805a-b2d083c3b57c.png)
**(Figure above)** The points in red circles are noise. The small amount of them seem to have great effect in the output below.
![noisy chair 2](https://user-images.githubusercontent.com/23747905/41667380-d1f36f1a-747a-11e8-8319-9e2765dcae0b.png)
I guess I can adjust some of the settings in stereo, fusion, or meshes to eliminate some extra meshes. Could someone provide a way to solve the issue? Much thanks.

**Comment by fishcu** [comment]
I would look at meshlab's point cloud cleaning functions, separately from colmap. Several tutorials for this also on youtube.

**Comment by ahojnnes** [comment]
There is also a trimming option in the meager, that you could tune to improve the results. Alternatively, I suggest to cleanup the point cloud manually before the meshing step.

**Comment by CorneliusHsiao** [comment]
Thank you for both suggestions. I am looking for a relatively automatic way to clean up the mesh. Cleaning sparse point cloud seems better since it can improve the efficiency of the following steps and point deleting is easier than triangle mesh. I am curious if there are some settings which can be adjusted so that algorithm can identify and neglect noisy point cloud by itself.
