### ISSUE TITLE
How to run SfM on images from stereo camera rig?

### ISSUE THREAD

**Issue by fishcu** [colmap/colmap#397]
I am trying to run colmap on a dataset of (synchronized) stereo images. The images are from a video stream, and there is a pre-processing step to subsample the number of images fed into SfM. However, I am unsure on what is the best way to approach the problem overall.

- One option is to force single camera = true to achieve better intrinsics optimization. However, there will be a slight error as the left and right cameras don't share exactly the same intrinsics.
- Another option is to have one intrinsics (+ distortion) estimation for every single image. This gets rid of the first option's problem, but will waste a lot of ressources estimating the same intrinsics again and again. Also, it will be potentially robust for the same reason.

Is there a 3rd option? 

**Can I pre-calibrate left and right cameras, then apply one calibration to one set of images, and another calibration to another set of images?** 

Ideally, I would like to do this through the CLI, or with some light scripting, without diving into colmap's source code.

**Another thing I would like to do is to fix the relative transform (extrinsics) between the stereo cameras. Is it possible?**

I have come across "RunRigBundleAdjuster" which seems to be intended for a similar problem as mine. However, there is no documentation on how to use it. Can it only be run after regular SfM has already finished?

**Comment by fishcu** [comment]
#59 seems relevant. Can I just add the "single_camera_per_folder" option during feature_extraction to solve my first problem?

For the second problem, it seems that RunRigBundleAdjuster is the way to go. I cannot find any documention. Is it just supposed to be run after running the regular "colmap mapper"?

**Comment by fishcu** [comment]
Thanks.

I am still wondering:
- In what way does the rig BA work? Is the rig really static, or is it just a "suggestion" for the BA solver to keep them at fixed relative poses?
- Since I have extrinsic calibration available, I would like to supply it to the rig BA. Is it not possible at all?

**Comment by ahojnnes** [comment]
The rig is really static and is enforced as a hard constraint. It is not implemented conveniently at the moment to supply the rig parameters but, in theory, it is possible to inject the data with a few code changes.

**Comment by fishcu** [comment]
Thank you, the distinction of "soft" vs "hard" constraints is what I was looking for.

What code changes would that be? From what I've gathered, it currently works by getting the average relative pose between rig cameras, then using that as extrinsics everywhere (`colmap.cc:1348`).
So, to implement reading extrinsics, could `ComputeRelativePoses()` be replaced by a similar function that fills out the rig from the json?

**Comment by ahojnnes** [comment]
@fishcu You are on the right track. ``ComputeRelativePoses()`` would have to be changed or a similar function has to be created. In addition, the scale of the reconstruction would have to be adapted with respect to the prior scale of the rig constraints. In case you implement such a function, it would be great, if you would submit a pull request. This would be a very useful feature. I suggest to extend the JSON rig configuration with a qvec/tvec entry, which determines the relative transformations in the camera rig.

**Comment by fishcu** [comment]
I will look into it. I'm currently slowly moving towards bigger reconstructions. I only have a stereo setup to test. Do you have other (smaller) datasets that would allow testing for bigger rigs (>2 cameras)?

About the scale: What would have to be done about it? Is there a utility function that can scale the reconstruction and will take care of updating all necessary data structures?
I see that there is an estimate scale function, but I haven't looked into it further.

**Comment by ahojnnes** [comment]
There is a ``Reconstruction::Transform`` method that allows you to apply a similarity transformation to an entire reconstruction.

**Comment by fishcu** [comment]
So what would the new workflow be like? Something like this?
1. Read config from json, get rig inter-camera distances
2. Estimate inter-camera distances present in map (using `ComputeRelativePoses`)
3. Apply scaling transform proportional to `true_scale / est_scale`
4. ???
5. Profit (run BA solver)

**Comment by ahojnnes** [comment]
4. Set the prior camera rig extrinsics to the array.

**Comment by fishcu** [comment]
I'm not completely clear if/why the scaling transform is needed. As I understood, it would be applied before running BA. Is it to get closer to the optimal solution, so as to increase chances of convergence of the BA? Or are there other benefits?

**Comment by ahojnnes** [comment]
No, but the scale of the extrinsics of the rig must be in agreement with the global reconstruction scale, otherwise the projection from world to image coordinates will be wrong.

**Comment by fishcu** [comment]
I have started implementing this. I have found the `boost::property_tree` downright terrible to use; Would you accept the addition of a proper JSON library (e.g., RapidJSON or https://github.com/nlohmann/json) in a pull request? I could add these header-only libraries in a separate `external` or similar folder.

**Comment by ahojnnes** [comment]
I would prefer not to pull in an extra dependency, if not necessary. What is the problem with boost? I know its interface is a little complicated but it should support all necessary functionality.

**Comment by fishcu** [comment]
I was unable to get boost's json parsing to run in the ~4 hours I tried. The syntax is overly verbose, there is little documentation, and there are few tutorials on google. I was able to get it to run right away with nlohmann's json library (matter of 30 minutes).

**Comment by fishcu** [comment]
Implementation is basically done, still testing.

One thing I'm not yet sure about is the pose of the non-reference camera.
If the calibration gives me `R`, `T`, so that the position of the second camera is `x2 = R*x1 + T`, does that mean that the second camera's rig pose would be `R^t`, `-R^t * T`?

Empirically, it seems correct that way, but it would be helpful to get confirmation from your side. :)

**Comment by ahojnnes** [comment]
The terminology "pose" is always dangerous. What do you mean by it? The world to camera or camera to world transformation.

**Comment by fishcu** [comment]
Neither, as it's a floating reference frame (calibration gives pose relative to first camera). In that case, `R`, `T` would be the transformation from the first camera to the second camera.

**Comment by fishcu** [comment]
I guess my question is if the camera rig **data structure** should contain transformations from the reference camera to the other rig cameras, or vice versa.

**Comment by ahojnnes** [comment]
From reference to any other camera.

**Comment by fishcu** [comment]
I see. I think I made a mistake and got it backwards before. For example, in a perfect stereo setup with baseline b, you would receive from the stereo calibration the relative `R` and `T` as:
`R = I_3`; `T = (b, 0, 0)^t`.
In that case, this will actually correspond to the mapping from the second camera (usually, the right camera), to the reference camera (left). So to feed this into COLMAP, it would need to be inverted, so that:
`R' = I_3`; `T' = (-b, 0, 0)^t`.
Correct?

Could you also please take a look at:
https://github.com/fishcu/colmap/commit/4ab28be5fb0fb7b9f06c50f0a3aee5a5bd9b888f ,
and check for correctness of the approach? I often get "no convergence" for the rig BA, even though the final cost is substantially lower than the initial cost. Maybe my calibration is just not very good, I will try improving that next.

**Comment by powderluv** [comment]
Is the implementation correct?

**Comment by noamholz** [comment]
@fishcu , I'm also interested in a solution for a stereo camera rig - did your implementation eventually work for you? if so, are there any specific guidelines / tips for working with it?
Thanks!
