### ISSUE TITLE
Why do we only set the first dimension as constant for constant tvec

### ISSUE THREAD

**Issue by is03wlei** [colmap/colmap#400]
https://github.com/colmap/colmap/blob/dev/src/sfm/incremental_mapper.cc#L654

ba_config.SetConstantTvec(reg_image_ids[1], {0});

Shouldn't it be ba_config.SetConstantTvec(reg_image_ids[1], {0, 1, 2});

**Comment by ahojnnes** [comment]
Only 7 degrees of freedom must be fixed, which is the case by fixing one pose completely and another single parameter of another pose. I don’t do anything smart in terms of checking for degeneracies here though, which could be improved. Makes sense?
