### ISSUE TITLE
Questions about loransac

### ISSUE THREAD

**Issue by is03wlei** [colmap/colmap#401]
https://github.com/colmap/colmap/blob/dev/src/optim/loransac.h#L180

          for (const auto& local_model : local_models) {
            local_estimator.Residuals(X, Y, local_model, &residuals);
            CHECK_EQ(residuals.size(), X.size());

            const auto local_support =
                support_measurer.Evaluate(residuals, max_residual);

            // Check if non-locally optimized model is better.
            if (support_measurer.Compare(local_support, support)) {
              best_support = local_support;
              best_model = local_model;
              best_model_is_local = true;
            }
          }

Why not compare local_support with best_support?

**Comment by is03wlei** [comment]
In this case, we couldn't pick up best model from local_models.

I looked up several local estimators. Most of them return only one model. So it works.
But if there is one local estimator returns multiple models. Then this is a issue.

**Comment by ahojnnes** [comment]
That is a valid point and it should be fixed. I will do so in a few days. Thanks!
