### ISSUE TITLE
vocab_tree_matcher crashes instead of demanding "--VocabTreeMatching.vocab_tree_path" as required

### ISSUE THREAD

**Issue by fishcu** [colmap/colmap#403]
As the title says. It works fine when specifying the vocabulary tree path, but it will crash when not specifying it. It should shut down gracefully like when not supplying database_path.

**Comment by fishcu** [comment]
That's exactly what it produces. If I leave out `database_path`, the error instead is:
`ERROR: Failed to parse options: the option '--database_path' is required but missing.`

**Comment by ahojnnes** [comment]
That is indeed inconsistent. I’ll have a look later and will keep this issue open as a reminder. Thanks.

**Comment by ahojnnes** [comment]
Fixed in the latest commit. Thanks again.

**Comment by fishcu** [comment]
Thank you!
