### ISSUE TITLE
Ordering of points in .vis file

### ISSUE THREAD

**Issue by maunzzz** [colmap/colmap#405]
Hi!
I've created a dense model using the following commands

```
workspace_path="./Data/CMU/colmap"
colmap image_undistorter --image_path ./Data/CMU//imgs --input_path ${workspace_path} --output_path ${workspace_path}/dense --output_type COLMAP --max_image_size 2000
colmap dense_stereo --workspace_path ${workspace_path}/dense --workspace_format COLMAP --DenseStereo.geom_consistency true --DenseStereo.write_consistency_graph true
colmap dense_fuser --workspace_path ${workspace_path}/dense --workspace_format COLMAP --input_type geometric --output_path ${workspace_path}/dense/fused.ply
```
Afterwards I'm trying to analyze the data. The goal is to find points from the dense reconstruction that can be seen in several images. I've managed to extract the data from the fused.ply and the fused.ply.vis file, as well as the camera matrices for the images included. However it seems that the order of the points in fused.ply and fused.ply.vis are different. After some testing I've come to the conclusion that the order of the points might not be the same. Is it?

Below I've plotted the points extracted from the .ply file. I've also plotted the cameras (red circles) where point with index 14 should be visible according to the .ply.vis data. I've also plotted the point with index 14 read from the .ply file (green dot). In the second image the images corresponding to the cameras plotted is shown. Am I missing something here? How is the data in the .ply and the .ply.vis file related? Are they in the same order?

![model](https://user-images.githubusercontent.com/6471357/41916686-df9e184e-7958-11e8-88e3-5e652a9b148f.png)
![ims](https://user-images.githubusercontent.com/6471357/41916685-df7ebd32-7958-11e8-9fce-76c5c5b0aef9.png)

I've also attached the files used for reading .ply and .ply.vis (they are .mat files originally)

[read_ply_file.txt](https://github.com/colmap/colmap/files/2137425/read_ply_file.txt)
[read_visibility_file.txt](https://github.com/colmap/colmap/files/2137426/read_visibility_file.txt)

Thank you!

**Comment by ahojnnes** [comment]
Did you check out the latest commit in the dev branch? There was a small bug in the original implementation.

**Comment by maunzzz** [comment]
I tried it now and still get the same result. I might be getting something wrong though. Are the image indices in the visibility file the same as those in the camera.txt file?

**Comment by maunzzz** [comment]
Ok, that solved it! Thank you!

**Comment by isht7** [comment]
@ahojnnes I noticed that the ordering of images in images.bin is different than the ordering of images in images.txt. By projecting images to image from the point cloud(using the visibility matrix), I figured that the ordering of images in images.txt is correct.

In the below screenshot, it is seen that the first image in images.txt is 770.png (at the end of the 4th line). 
![image](https://user-images.githubusercontent.com/21278652/95868695-608e0700-0d1f-11eb-9f01-a1c38b47e88a.png)
In the below screenshot, it is seen that the first image in images.bin is 1000.png
![image](https://user-images.githubusercontent.com/21278652/95868780-78fe2180-0d1f-11eb-8443-63fa407db9f3.png)

Am I doing something wrong? Why am I seeing different ordering of images in these 2 files?

**Comment by isht7** [comment]
@ahojnnes I noticed that the ordering of images in images.bin is different than the ordering of images in images.txt. By projecting some selected points to image(using the visibility file), I noticed that the ordering in images.txt is correct. Why could this be happening?
First image is 770.png as seen in the screenshot of images.txt below - 
![image](https://user-images.githubusercontent.com/21278652/95870160-0b52f500-0d21-11eb-981a-167d3949b676.png)


I added the highlighted line(at line 22) to the function `read_images_binary` as seen below - 
![image](https://user-images.githubusercontent.com/21278652/95870856-d4c9aa00-0d21-11eb-90cd-272bbfbc8cb5.png)
Now, the function should print the the order of images in images.bin. 
These are the first few images printed - 
![image](https://user-images.githubusercontent.com/21278652/95870986-fe82d100-0d21-11eb-9da4-2834c3616a53.png)


The ordering of images in the dictionary is different too: 
![image](https://user-images.githubusercontent.com/21278652/95871152-2f630600-0d22-11eb-8764-0a9a1453ba30.png)

**Comment by fclairec** [comment]
@ahojnnes @maunzzz I found the same as @isht7. 
I am looking to do the same (take the image indices from .vis file and find the corresponding image paths in the images.xxx. 
Depending on if I take images.txt or images.bin I will have a different result. Can you specify in which of both I can find the correct ordering needed?
Also I do not find all the images from .vis (images idx ranging from 0 to 252) in the images.txt (len = 238). I suppose that is due to filtering, is that correct?

**Comment by apurvazaveri** [comment]
I am also looking to do the same. Does anyone have any update?
