### ISSUE TITLE
Crash During Dense Reconstruction - Fusion Process

### ISSUE THREAD

**Issue by fasterthan** [colmap/colmap#409]
**Nature of bug**
I believe it is just the GUI that is crashing though I'm not sure if the fusion process crashes along with it. During fusion reconstruction the GUI simply disappears but the process is still running. I may not have a good grasp on how to adjust fusion settings to accommodate for my machine and I couldn't find anything in the **Reduce memory usage during dense reconstruction** section of the documentation. I adjusted the following settings to try and get a complete run of fusion:

- max_num_pixels: 6000
- max_traversal_depth 80
- check_num_images 30
- cache_size 24

I don't know what effect changing any of these settings had. I'm trying to crunch a batch of 329 JPG images with a resolution of 4k x 3k. Fusing some images took as little as ~23 seconds, while some took up to ~410 seconds.

**Desktop:**  
 - OS: Fedora 27
 - Browser firefox
- COLMAP: 3.4

**Comment by ahojnnes** [comment]
How much RAM do you have in your machine?

**Comment by fasterthan** [comment]
8 GB

**Comment by ahojnnes** [comment]
Set cache_size to something like 7 (it is the memory limit that is used during fusion in GB).

**Comment by fasterthan** [comment]
@ahojnnes That did the trick, thank you for your help 🙂.
