### ISSUE TITLE
Help- Reconstruction Problems because system is out of memory

### ISSUE THREAD

**Issue by Mia423** [colmap/colmap#410]
Hi Johannes

I have a question. I am currently working on my bachelor thesis
in which I create a 3D reconstruction of a castle with Colmap. 

There are 650 images all with the same camera parameters and one
Size of 6000 x 4000 pixels. The computer available to me is
an Aspire V15 Nitro with a NVIDIA GeForce GTX 950 with 4GB VRAM and
8GB DDR4 memory. Installed is a Linux on which I only work with the Command Line Interface. Unfortunately I come with the computer again and again to the
Performance limit.  Latest at the Dense Fusion. Also before that I have to
Reduce maximum image size by more than half.

Now I read that you can divide the whole in sub-models.
Unfortunately, I found nothing like it works.
Can you help me?
Maybe you can also give me some tips on how to get a good result despite the computer performance?

Thank you
Maria

**Comment by ahojnnes** [comment]
- Clustering the scene using PMVS will not really reduce the required GPU memory that you need during dense reconstruction, but it can significantly speedup the reconstruction. CMVS usage is roughly described here: https://colmap.github.io/faq.html#reduce-memory-usage-during-dense-reconstruction -- after running CMVS, you would have to simply specify the result ``option-XXXX`` file name as ``colmap dense_stereo ... --pmvs_option_name``. Let me know if something is unclear here.

- Reducing the image size is the way to go to reduce the memory usage. Alternatively, you could also try to reduce the number of source images in the dense reconstruction stage, as described here: https://colmap.github.io/faq.html#manual-specification-of-source-images-during-dense-reconstruction -- this will reduce the memory requirements.

**Comment by isolin** [comment]
Hi Maria & Johannes,

I am fighting the same problem, but with a larger dataset. Colmap is insanely fast! It beats any commercial solution I've tried so far, mainly in the sparse reconstruction phase. However, I can't pass the dense_fusion step.

I have a 1080 Ti, Ryzen 2700X and 32Gb memory trying to process a sparse reconstructed cluster of 7200 photos. As suggested, I tries to take advantage of the CMVS. It works well for some datasets, but fails for others. By failing I mean absolutely wrong results with fictious photoIDs and thousands of options. I suspect some memory leak in array indexing there. In general, I must consider CMVS as unstable as a russian roulette. Having a viable solution for dense fusion of really large datasets within Colmap would be awesome. Of course without reducing the quality by lowering the max_image_size. Would it be possible to have some hierarchical clustering employed similar to the new mapper? Is there actually any theory/literature I could look up to understand the fusion process better?

**Comment by ahojnnes** [comment]
Indeed, CMVS oftentimes does have problems and also some hidden bugs. But I am not aware of an alternative open source implementation at the moment.
