### ISSUE TITLE
Problem with poses after mapper

### ISSUE THREAD

**Issue by gT-mike** [colmap/colmap#411]
Dear Johannes,

it seems that I encountered another problem with the mapper. I wanted to verify the quality of pose reconstruction therefore recorded a dataset where GT poses are recorded together with the images. After running the mapper I see the following results (consequently the xz position of the pose is shown for frame 0-500, 500-1000, 1000-1500 and 1500-2000)

![image](https://user-images.githubusercontent.com/37045813/42189462-9ec8c4c2-7e58-11e8-8ee5-c3268cf8927b.png)

You can see that parts are reconstructed correctly while other flip completely. It seems that after ~ 400 frames the coordinate system flips by 90° (whereas the part before the flip and the part after the flip are correct within itselves). Later it flips back. Comparing the eukledian distance of two consecutive poses for GT data and for COLMAP data, the following result can be seen (note the log scale):

![image](https://user-images.githubusercontent.com/37045813/42189371-41376ca0-7e58-11e8-8b1c-7711acde8d66.png)

There are many more jumps over > 1 m in the COLMAP data which are rather unphysical (probably related to the flips).  Comparing the poses to the actual images it can be seen that the pose obviously  cannot differ by more then ~10 cm.

Could you help to tackle this?

Short Update: I calculated depth maps for all registered images and the depth maps seem to be all okay. This actually does not make a lot of sense to me as I would assume that you need correct poses to calculate correct depth maps for a given images with MVS.

Mike

**Comment by gT-mike** [comment]
No Idea :/?

**Comment by ahojnnes** [comment]
How are you plotting the data? Is this just the XYZ from the images.txt/bin?

**Comment by gT-mike** [comment]
I extract the full pose, transform it to a 4x4 matrix, invert it (as the GT data that I compare it to is in C2W coordinates) and then plot the coordinates X and Z coordinate of the pose.

**Comment by ahojnnes** [comment]
I assume you align the two trajectories before plotting them?

**Comment by ahojnnes** [comment]
Okay, just wanted to make sure. This seems all right and the source of error seems to be that colmap makes a mistake in the reconstruction. In general, colmap does not perform very well for video-type data. If you can share the images with me, I could have a look and give recommendations on parameter settings.

**Comment by gT-mike** [comment]
okay, that's interesting .. is there a reason that COLMAP is not doing very well with video-type data? BTW I used the exhaustive matcher, maybe the sequential matcher would give better results?

Thanks for the offer! Can I sent you a link for data download via mail?

**Comment by ahojnnes** [comment]
Because COLMAP is optimized for unstructured and not sequential imagery. You could send me the data via email as a Dropbox/Google Drive/etc. link.

**Comment by ahojnnes** [comment]
Okay, for other readers: we took this issue offline, since @gT-mike sent me his datasets. The datasets reconstructed fine with the following settings: sequential matching + loop detection + shared intrinsics + OPENCV camera model.

**Comment by gT-mike** [comment]
Hi there,

I'm trying to rerun it on my machine and get the following error:

Matching image [16/127]SQLite error [/home/romy_common/COLMAP/colmap/src/base/database.cc, line 435]: database disk image is malformed

It seems that somebody had this issue previously:

https://github.com/colmap/colmap/issues/222


Interestingly this error appears sometimes and sometimes not. Any idea what could be the cause?

Mike

**Comment by ahojnnes** [comment]
Are you running this on a network drive or are you using the database from multiple processes at the same time?

**Comment by ahojnnes** [comment]
Shouldn’t be a problem, but then I have never used it inside GCE so far. Not sure what is going on.

**Comment by gT-mike** [comment]
hmm okay, another issue popped up. When I use shared instrinsics the mapper seems to take much longer than before, i.e. when I run the feature extractor with

        --ImageReader.camera_model SIMPLE_PINHOLE
        --ImageReader.camera_params 310,160,140 
        --ImageReader.single_camera 1

Had any issue with that? Could that happen if the camera_params are wrong or have the settings in the mapper to be changed if --ImageReader.single_camera 1 is used?

**Comment by ahojnnes** [comment]
For SIMPLE_RADIAL and non-shared intrinsics, PBA is used for bundle adjustment, which is much faster than Ceres Solver. This is the reason you see the slow down.

**Comment by gT-mike** [comment]
Ah okay, interesting. Is there any way to speed up ceres?

I could image two options:

a) Use sequential mapper, but not shared intrisics and SIMPLE_RADIAL. Thus, mapper will use PDA.
b) Use shared intrinsics and nonetheless use PBA instead of ceres.

Would either of both work? What would probably be better in performance/speed?

**Comment by ahojnnes** [comment]
Only option a) would work.

**Comment by gT-mike** [comment]
Alright, thanks .. coming "from the other side": Can colmap roughly estimate the required time before actually running the step?

**Comment by ahojnnes** [comment]
No.

**Comment by gT-mike** [comment]
had anothe rinteresting issue during a try run today: A video where the illumination changes suddenly during the recording (hit photosensor and light went on ..). The mapper could hardly register any image. Had any experience with that?

**Comment by ahojnnes** [comment]
I am happy to provide support for general issues with the software but unfortunately I don’t have the time to comment on every dataset specific issue. Sorry, this shouldn’t sound impolite. I suggest to do some more study in the vision research literature, e.g., a standard computer vision book to learn more about common problems. Sudden changes in illumination are problematic due to limited robustness in the feature extraction/matching stages. Probably some better auto exposure setting in the camera or a feature tracker would improve the results.

**Comment by gT-mike** [comment]
That's alright. I understand that, just thought that you might be interested in discussing this issue further that appeared in practise.

**Comment by ahojnnes** [comment]
I am aware of this issue, and while it could probably be solved specifically for your case, it is hard to implement a general purpose solution that works reliably in all cases (or at least, I don’t have the time to do so).

**Comment by gT-mike** [comment]
I guess some brightness filter (create the histogram and adjust it to some mean value over all frames) would do the job in first order. Is the code open source so that we would add it to the existing version if it works? Maybe I will have a try if you give me suggestion where's the best entry point to put that in. I assumed that the image data is saved as a part of the Image class but I actually can't find where the rgb values for each pixel are saved.
