### ISSUE TITLE
Reading code have problem

### ISSUE THREAD

**Issue by Riverhe2014** [colmap/colmap#412]
Dear Johannes,
     hello,I am interested in your paper and read your code.However I have some problem:

     First: I do not understand the function with propagateDepth() which is in patch_match_cuda.cu file ,do you have some reference paper.  

    Second:the dense stereo don't include rectify
    
    Third:Does this code speed up,I will take 5-6 hour when  running  this code .The number of  image is 
             200 and image resolution is 8000*6000.

    Forth: Is it important to select views for stereo 

    Fifth:Is it relative to Belief Propagation？

    Sixth: Can We dynamicly control the number of  iterative when Propagation. 
  

  RiverHe

**Comment by Riverhe2014** [comment]
Seventh: is it similar to EM algorithm when predicting depth

**Comment by ahojnnes** [comment]
1. Described on page 5 in my paper.
2. This is a multi-view stereo approach and hence no rectification is computed but the patches are warped on the fly using local homographies.
3. See the FAQ in the documentation on how to speedup the computation: https://colmap.github.io/faq.html
4. Yes, it is important and it is done per-pixel, please also see my paper for a motivation and explanation.
5. Belief propagation is message passing and the propagation step in patch-match could be seen as a form of message passing as well in the broader sense.
6. I don't understand your question.
7. I don't understand your question.
