### ISSUE TITLE
Post-BA re-triangulation

### ISSUE THREAD

**Issue by imkaywu** [colmap/colmap#414]
Hello,

I read in your paper "Structure from Motion Revisited" that it would help improve the drifting issue by extending the pre-BA re-triangulation to an additional post-BA re-triangulation. However, I'm not sure why this isn't reflected in the current implementation of colmap as only a pre-BA re-triangulation is present in [line 111](https://github.com/colmap/colmap/blob/e56279daf01f41ddebea20821939ffc1ac05fd6c/src/controllers/incremental_mapper.cc#L111). Is there any particular reason that you decided to leave it out?

**Comment by is03wlei** [comment]
@ahojnnes 
I noticed in Retriangulate you will create new points3D.
But in CompleteAndMergeTracks, it only expand track of existing points3D.

Does it cause loss of points3D?

**Comment by YRstronger** [comment]
@is03wlei I am confused by this same question. Do you find a proper answer?
