### ISSUE TITLE
Filter outlier reconstructed points?

### ISSUE THREAD

**Issue by fishcu** [colmap/colmap#416]
I am running an automated reconstruction script, followed by export to .ply.

The problem I have is that for some reconstructions and some (sub-)models, some points are incredibly far away from the rest of the model. When viewing the models with meshlab, it will automatically scale the view to fit all points, resulting in the actual model being shrunk to a single point, seemingly.
Viewing the model in colmap itself circumvents this issue, as colmap seems to scale the view to the cameras instead.

Besides the visualization problem, these points are obviously outliers. It would be nice to have a feature (maybe in the mapper itself?) to remove such points. A simple measure like "point is more than N=20 standard deviations away from the point center of mass" could work for these extremely far out points.

I have attached a sample .ply that shows the problem I described.

**Comment by ahojnnes** [comment]
Right now, you can click individual points and delete them. But this will obviously be tedious if there are many such points. I guess you could run such a manual filtering easily with a little Python scripts or so that reads in, filters, and writes out the filtered point cloud?

**Comment by fishcu** [comment]
Thank you for the reply!

Yes, a script could fix this "symptom".
OTOH, do you agree that these points are probably detrimental for the BA and could move cameras, pull out other points, and distort distortion and other camera parameters?

**Comment by ahojnnes** [comment]
They shouldn't have any significant impact. They were probably triangulated from cameras with very similar projection center and my bundle adjustment parameterization does not handle points at infinity. The reprojection error should be very small for those points but the points might be useful to constrain the rotation of those cameras.

**Comment by MarcelloAgostini** [comment]
You could try the PCL library there are interesting filters for Point cloud. I use it to filter dense Point clouds, but it should be suitable also for sparse ones. The statistical filter should be ok for your purposes.
http://pointclouds.org/documentation/tutorials/statistical_outlier.php#statistical-outlier-removal

Cheers,
Marcello

**Comment by ahojnnes** [comment]
That is certainly a good recommendation. Thanks, Marcello.

**Comment by kaiyi98** [comment]
> You could try the PCL library there are interesting filters for Point cloud. I use it to filter dense Point clouds, but it should be suitable also for sparse ones. The statistical filter should be ok for your purposes. http://pointclouds.org/documentation/tutorials/statistical_outlier.php#statistical-outlier-removal
> 
> Cheers, Marcello

Thanks for your suggestion, do you mean that I can process the point3D.bin files with PCL library?

**Comment by prasadvagdargi** [comment]
I exported the point clouds as ply files and used CloudCompare (Statistical Outlier Filtering) to filter the points.
