### ISSUE TITLE
Question about parameters used for Middlebury and ETH3D 

### ISSUE THREAD

**Issue by kristinpro** [colmap/colmap#417]
Hello,

Sorry to post it as a bug report but I didn't figure out how to correctly register a question over here.

I was wondering if you can reveal the set of parameters that was used for the results reported in Middlebury and ETH3D benchmarks for COLMAP?

I am trying to reproduce the results for the Dino and Temple (Middlebury) and Office and Pipes (ETH3D). 

Thank you

**Comment by ahojnnes** [comment]
The submissions for those benchmarks were based on an old commit and there was some post filtering applied in both cases. This post filtering didn’t change much in the case of ETH3D, so you should get to very similar results by just running the standard pipeline. Is it important for you to reproduce the exact results or is similar sufficient?

**Comment by kristinpro** [comment]
It is important for me to reproduce rather the ranking of COLMAP with respect to other methods because when I do evaluation on my data, the ranking is very different. Precisely, in my evaluation, OpenMVS is on the top of the list while it is generally behind of the COLMAP in both Midllebury and ETH3D. 

So, I would like to understand why this happens. Is the data I work with really challenging for COLMAP? Is the SfM part cannot really handle it so it affects directly the dense result? Can the parameter set be arranged to acheave better results?

Thus, I thought if I can reproduce the reconstruction of the sequences from the benchmarks and assess it visually with wahat I see in the MIddlebury (and ETH3D) then I can at least make some conclusion regarding parameters used for that type of data. 

So I started with Dino sequence from Middlebury. I tried to run the standard pipeline on the Dino - 16 views and Dino - 363 views. In both cases I cannot reach the dense part of the COLMAP because the SfM part fails to initialize the reconstruction ending up with no input to the dense part. I tried the 'automatic reconstruction' option as well as every step manually. 
- The feature extraction part seems to work fine with defaults and PINHOLE camera with parameters provided with the Dino sequence which are shared for all images. 
- I tried the feature matching with defaults of 'exhaustive' and 'sequential' options and didn't notice significant difference between them so I opted for  'exhaustive'.
- The SfM part with defaults, however, runs out of trials to find the inital pair to start the process. 

 
Note:  in my work I deal with a reconstruction of human baby mannequin -  a weakly textured object.

**Comment by ahojnnes** [comment]
1. Middlebury provides ground-truth poses, which you should also use when running COLMAP.
2. If you provide your images, I can try to help with parameter recommendations.

**Comment by kristinpro** [comment]
1. I see, I should prepare the triplet of files 'camera.txt; images.txt; points3D.txt' using the data from the benchmark. Thus, in the 'images.txt' I should convert the the poses to quaternion representation and leave the an empty line for the 2D point?

2. I can show here one sample from my data. The mannequin is surrounded by 'helper' objects so to facilitate reconstruction by providing supportive features. 

![img_0030](https://user-images.githubusercontent.com/40892103/42441221-0d95096a-8368-11e8-9062-c34e9d1fc944.png)

**Comment by kristinpro** [comment]
Hi @ahojnnes , could you, please, explain how did you obtain the dense point cloud on the Dino sequence with 16 views ?

If I try to invoke fusion with default parameters right after I've got depth and normal maps for all the 16 views using ground truth poses, it creates an empty .ply file. 

Do I have to obtain the sparse point cloud prior the dense reconstruction in this case? If this is necessary for the fuser than could you, please, give me some insights on how to do it using the ground truth poses?

I have tried to run SfM on the Dino model imported from manually constructed triplet: cameras.txt + images.txt + points3D.txt. After the feature extraction and matching the reconstruction ends with nothing. Precisely, it finishes in less than 2 seconds and does not produce neither error messages/warnings nor the visual output.
