### ISSUE TITLE
Some oordinates are negative in images.txt and  keypoints' coordinates in images.txt are different from coordinates in database 

### ISSUE THREAD

**Issue by jsstt** [colmap/colmap#419]
In images.txt, some  keypoints' 2D coordinates are negative, for example, 477.578 -2.86246 -1 . In my case, the first keypoint's coordinate is 3692.48 1.664 in images.txt , but in the database , the first keypoint's coordinate is 3716.38 4.324  in the same image.

**Comment by ahojnnes** [comment]
Are you sure you are not looking at an undistorted reconstruction and comparing it to the distorted coordinates in the database?

**Comment by jsstt** [comment]
Thank you very much, I get it.
