### ISSUE TITLE
Hello, I`ve seen some previous questions about panoramic image support.

### ISSUE THREAD

**Issue by raehyuk** [colmap/colmap#422]
Hi ahojnnes
First , Thank you for great code !
Is reconstruction from panoramic images integrated in current version ?

**Comment by ahojnnes** [comment]
This is not integrated and the source code in the two branches deviated too much for them to be merged at this point. You could checkout the branch with the panoramic image support, but be aware that the COLMAP code base improved a lot in the meantime and the branch might be a little buggy.
