### ISSUE TITLE
contribute clomp using Xcode on Mac 

### ISSUE THREAD

**Issue by amirhosseingholami** [colmap/colmap#423]
Hi, i sucsussfully compiled "hello_world.cc" using cmake using this guide https://colmap.github.io/install.html#library , here are the results  
[hello_world_terminal_log.txt](https://github.com/colmap/colmap/files/2193076/hello_world_terminal_log.txt)
but unfortunately I can't run this simple code in my Xcode IDE , can you please help me ? how should I configure my Xcode environment to compile "hello_world.cc" code? of course I installed colmap using cmake and here is the results! 
[colmap-instalation.txt](https://github.com/colmap/colmap/files/2193073/colmap-instalation.txt)

**Comment by ahojnnes** [comment]
I don’t quite see what the issue is? It seems like the hello_world executable ran successfully. It printed out the Hello World message.
