### ISSUE TITLE
Automatic Reconstruction on Windows 7 Colmap 3.4 causing high memory RAM and crash

### ISSUE THREAD

**Issue by enzyme69** [colmap/colmap#424]
**Describe the bug**
RAM High Memory Usage for no reason

**To Reproduce**
1. Go to Auto Reconstruction
2. See RAM goes up high until 20+ GB and crash computer.

**Expected behavior**
This should not happen....

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7

**Additional context**

**Comment by ahojnnes** [comment]
Please see: https://colmap.github.io/faq.html#speedup-dense-reconstruction

You might want to reduce the ``--StereoFusion.cache_size`` to a lower value, depending on how much RAM your machine has.
