### ISSUE TITLE
fusion slows exponentially

### ISSUE THREAD

**Issue by KevinCain** [colmap/colmap#425]
With a set of 1,467 32MP images running on Ubuntu 18.04 with CUDA, fusion runs at the normal speed for the first 40 images (~30 seconds each), however frame 41 then takes ~310 seconds and frame 42 ~9,403 seconds, as follows:

Fusing image [38 from 1467 total] in 25.428s (14888937 points)
Fusing image [39 from 1467 total] in 25.362s (15148501 points)
Fusing image [40 from 1467 total] in 33.794s (15533176 points)
Fusing image [41 from 1467 total] in 309.029s (15797180 points)
Fusing image [42 from 1467 total] in 9403.215s (16300886 points)
Fusing image [43 from 1467 total

The invocation is:

colmap dense_fuser --workspace_path _{PATH}_ --workspace_format COLMAP --input_type geometric --output_path _{OUTPUT PATH}_ --DenseFusion.min_num_pixels 5 --DenseFusion.max_num_pixels 40000

This seems to be the same issue as [https://github.com/colmap/colmap/issues/183](url), but as I'm using the dev branch and July 1 current commit, it seems this behavior is unexpected.

I've tried '--DenseFusion.cache_size 100', with similar results.  Any suggestions?

**Comment by ahojnnes** [comment]
The speed of the fusion depends on how connected the image is with the rest of the scene. Individual images can take much longer than others. This is expected behavior.
