### ISSUE TITLE
Crash starting reconstruction with GPU checked on OS X (Quartz / AppKit?)

### ISSUE THREAD

**Issue by johncronan** [colmap/colmap#426]
**Describe the bug**
I get a segmentation fault when I try to start automatic reconstruction, but only if GPU is checked.

**To Reproduce**
Compiled dev tree according to OS X installation instructions. I installed the CUDA tools beforehand and CUDA was enabled by CMake.

In the application, I was following the steps here: https://www.prusaprinters.org/photogrammetry-3d-scanning-just-phone-camera/

**Desktop (please complete the following information):**
 - OS: 10.12.5
 - Version 3.4

**Additional context**
Crash log is attached.

**Comment by johncronan** [comment]
[log.txt](https://github.com/colmap/colmap/files/2195328/log.txt)

**Comment by ahojnnes** [comment]
I assume you don't have a CUDA-enabled NVidia GPU? Which GPU do you have?

**Comment by johncronan** [comment]
I do. It's a GTX 1080.

**Comment by ahojnnes** [comment]
Can run the latest dev version and, in case it still fails, please run the executable from the commandline as ``colmap automatic_reconstructor ...`` and post the output.

**Comment by ahojnnes** [comment]
You can pass a specific CUDA architecture to compile as ``cmake -DCUDA_ARCHS=Maxwell ..`` or in your case probably ``cmake -DCUDA_ARCHS=Pascal ..``.

**Comment by johncronan** [comment]
Thanks! I'm up and running now.
