### ISSUE TITLE
Question: How to format `cameras.txt` for Reconstruct sparse/dense model from known camera poses

### ISSUE THREAD

**Issue by snowzurfer** [colmap/colmap#428]
I have a series of images with relative intrinsics and extrinsics and I would like to use them to calculate a sparse model.

I have read the documentation and the FAQ, which say I need to prepare a `cameras.txt` and `images.txt` file, but from the documentation it is not clear to me how the `cameras.txt` should be formatted.

In the example given here https://colmap.github.io/format.html#cameras-txt , it is not shown in which order and how one should input the data if one has the full intrinsics matrix. I have, per image, the full K matrix, with 6 values. How should I enter them in each row? The `parameters` part doesn't make this clear. From what I gather, I should also use the OPENCV_FULL type for the camera.

Finally, since from the extrinsics the `images.txt`file can only contain those and not the points, should one interveal the lines in the file as such:

```
# Image list with two lines of data per image:
#   IMAGE_ID, QW, QX, QY, QZ, TX, TY, TZ, CAMERA_ID, NAME
#   POINTS2D[] as (X, Y, POINT3D_ID)
# Number of images: 2, mean observations per image: 2
1 0.851773 0.0165051 0.503764 -0.142941 -0.737434 1.02973 3.74354 1 P1180141.JPG

2 0.851773 0.0165051 0.503764 -0.142941 -0.737434 1.02973 3.74354 1 P1180142.JPG

...
```
or as such:

```
# Image list with two lines of data per image:
#   IMAGE_ID, QW, QX, QY, QZ, TX, TY, TZ, CAMERA_ID, NAME
#   POINTS2D[] as (X, Y, POINT3D_ID)
# Number of images: 2, mean observations per image: 2
1 0.851773 0.0165051 0.503764 -0.142941 -0.737434 1.02973 3.74354 1 P1180141.JPG
2 0.851773 0.0165051 0.503764 -0.142941 -0.737434 1.02973 3.74354 1 P1180142.JPG
...
```
?

Thanks in advance.

**Comment by snowzurfer** [comment]
@ahojnnes thanks for the reply; I have created a `cameras.txt` with the OPENCV camera model and have double checked that it is correct, but when I run the command

```
colmap feature_extractor \
    --database_path $PROJECT_PATH/database.db \
    --image_path $PROJECT_PATH/images
```

with the files `cameras.txt`, `images.txt` and `points3D.txt` in the `images` folder, it doesn't pick up that there are the text files there, and doesn't use the camera settings in `cameras.txt`.

The output shows that it uses a PINHOLE camera and not the OPENCV one as listed in the files.

My project folder is as such:
```
project_folder/
  images/
    images.txt
    cameras.txt
    points3D.txt
```

My `points3D.txt` is empty. How can I make it pick up those files?

**Comment by ahojnnes** [comment]
Ah okay, in this case, you would have to supply the camera parameters using the ``--ImageReader.camera_*`` option of the ``feature_extractor``.

**Comment by snowzurfer** [comment]
@ahojnnes Thanks for the reply; there are different options there:
```
  --ImageReader.camera_model arg (=SIMPLE_RADIAL)
  --ImageReader.single_camera arg (=0)
  --ImageReader.single_camera_per_folder arg (=0)
  --ImageReader.existing_camera_id arg (=-1)
  --ImageReader.camera_params arg
  --ImageReader.default_focal_length_factor arg (=1.2)
```

Which one should I use to pass it my `cameras.txt` file? I can't use them because I have different cameras with different intrinsics, and the parameters allow only to pass one from what I can tell.

Here is what my file looks like, and I would like it to use those:
```
1 OPENCV 1920 1080 0.8310232162475586 0.8310232162475586 0.4997396171092987 0.2809895873069763 0 0 0 0
2 OPENCV 1920 1080 0.8247257471084595 0.8247257471084595 0.4997396171092987 0.2809895873069763 0 0 0 0
3 OPENCV 1920 1080 0.8224358558654785 0.8224358558654785 0.4997396171092987 0.2809895873069763 0 0 0 0
4 OPENCV 1920 1080 0.8218633532524109 0.8218633532524109 0.4997396171092987 0.2809895873069763 0 0 0 0
5 OPENCV 1920 1080 0.8221495747566223 0.8221495747566223 0.4997396171092987 0.2809895873069763 0 0 0 0
6 OPENCV 1920 1080 0.8187816143035889 0.8187816143035889 0.4997396171092987 0.2809895873069763 0 0 0 0
7 OPENCV 1920 1080 0.817855954170227 0.817855954170227 0.4997396171092987 0.2809895873069763 0 0 0 0
8 OPENCV 1920 1080 0.8184283971786499 0.8184283971786499 0.4997396171092987 0.2809895873069763 0 0 0 0
9 OPENCV 1920 1080 0.8230082988739014 0.8230082988739014 0.4997396171092987 0.2809895873069763 0 0 0 0
10 OPENCV 1920 1080 0.823580801486969 0.823580801486969 0.4997396171092987 0.2809895873069763 0 0 0 0
11 OPENCV 1920 1080 0.8227220177650452 0.8227220177650452 0.4997396171092987 0.2809895873069763 0 0 0 0
12 OPENCV 1920 1080 0.8261570334434509 0.8261570334434509 0.4997396171092987 0.2809895873069763 0 0 0 0
13 OPENCV 1920 1080 0.8273019790649414 0.8273019790649414 0.4997396171092987 0.2809895873069763 0 0 0 0
14 OPENCV 1920 1080 0.8252983093261719 0.8252983093261719 0.4997396171092987 0.2809895873069763 0 0 0 0
15 OPENCV 1920 1080 0.8215771317481995 0.8215771317481995 0.4997396171092987 0.2809895873069763 0 0 0 0
```

**Comment by snowzurfer** [comment]
@ahojnnes I see, thanks; then I suggest updating the docs to show this requirement. The docs say that you can reconstruct a sparse model from known camera poses by creating those files, which instead are not used by the FeatureExtraction as it is. I'll create a PR once I have modified the script.

Should I then feed the modified database to the feature extractor? If so, how?

**Comment by ahojnnes** [comment]
Have a look at the updated documentation and let me know if this description is sufficient.

**Comment by snowzurfer** [comment]
@ahojnnes thanks a lot, it does. I will use that and if I find any other issues, report.

**Comment by ahojnnes** [comment]
Thanks for the feedback.

**Comment by shreshtashetty** [comment]
Hi,
How did you feed the new database to the feature extractor from the command line? I've looked through the documentation and #433 but I've not been able to figure it out.

**Comment by shoang22** [comment]
> The image reader can only take the parameters for a single camera. If you want to specify the parameters for multiple cameras, you would have to modify the SQLite database directly. This should be easy by modifying the `scripts/python/database.py` script.

is this script still available? not seeing it in the codebase.
