### ISSUE TITLE
What is time complexity of bundle adjustment in COLMAP

### ISSUE THREAD

**Issue by is03wlei** [colmap/colmap#429]

**Comment by ahojnnes** [comment]
You can analyze the time complexity of bundle adjustment by following my description in my SfM revisited paper at https://demuc.de/papers/schoenberger2016sfm.pdf and by following the references there. Short answer: it depends on the dataset and the chosen settings.

**Comment by olestole** [comment]
Adding a reference to this issue #1706, where @tsattler provided an excellent answer on the topic.

**Comment by tsattler** [comment]
The referenced thread is about feature matching complexity, not about the complexity of bundle adjustment. No answer about the time complexity of bundle adjustment is given.

**Comment by olestole** [comment]
My bad. Do you have any elaboration on the time and memory complexity of bundle adjustment in general?

**Comment by tsattler** [comment]
I recommend to read through the paper Johannes provided and from there follow-up on related work.
