### ISSUE TITLE
question about convert pixel position while converting model to bundler format

### ISSUE THREAD

**Issue by hiakru** [colmap/colmap#432]
When convert model to bundler, we need to convert each pixel to bundler format, code in below:
https://github.com/colmap/colmap/blob/dev/src/base/reconstruction.cc#L968

the comments show colmap origin is at upper left, but (0.5,0.5)
so the result should be : 
      line << point2D.X()-0.5 - camera.PrincipalPointX() << " ";
      line << camera.PrincipalPointY() - point2D.Y()+0.5 << " ";
not :
      line << point2D.X() - camera.PrincipalPointX() << " ";
      line << camera.PrincipalPointY() - point2D.Y() << " ";

right?

Thanks and best regards,
Wei

**Comment by ahojnnes** [comment]
It shouldn't matter for pure geometric operations as long as the camera intrinsics are consistent. It will only matter for interpolating colors in the image, which will be shifted by 0.5px. In any case, your concern is correct and this should be fixed. Thanks for the bug report.

**Comment by ahojnnes** [comment]
Actually, I rechecked and I think, the current implementation is correct. Note that the principal point is already shifted by 0.5px, so the difference between the two values is what we want. Do you agree?

**Comment by hiakru** [comment]
I don't think so, the principle point were init by:
https://github.com/colmap/colmap/blob/dev/src/base/camera_models.h#L778
so the principle x = width / 2.0, principle y = height / 2.0
if principle point shifted, should be x = width / 2.0 + 0.5, principle y = height / 2.0 + 0.5.

Thanks,
Wei

**Comment by ahojnnes** [comment]
No, in COLMAP convention, the principal point of an image is at (1, 2) if the image size is (2, 4). Imagine single pixels as having an area.

**Comment by hiakru** [comment]
Yes, I know your meaning, if the image size is (2,4), the pp(principal point) is (1,2), but the origin is (0.5,0.5).
So for the conversion:

>       line << point2D.X() - camera.PrincipalPointX() << " ";
>       line << camera.PrincipalPointY() - point2D.Y() << " ";
the origin point will be (0.5-1,2-0.5)=(-0.5,1.5), after conversion.
But I think the correct result is (-1,2), are you agree?

Thanks,
Wei

**Comment by ahojnnes** [comment]
I think, ``(-0.5, 1.5)`` should be the coordinate of the origin in Bundler coordinates. Principal point in Bundler coordinates is ``(0.5, 1.5)`` (assuming an image size of ``(2, 4)``.

**Comment by hiakru** [comment]
After deep dive, I got the reason, thanks for your reply.  0.5 is to shif each pixel coordinate to pixel center.

Thanks,
Wei

**Comment by hiakru** [comment]
close it
