### ISSUE TITLE
How to use pre-constructed DB for reconstruction from known poses

### ISSUE THREAD

**Issue by snowzurfer** [colmap/colmap#433]
Following the issue reported here https://github.com/colmap/colmap/issues/428

I have managed to produce a DB containing the camera poses, intrinsics, extrinsics and images.

I have imported it the colmap GUI to check it, and it has the right data:

![screen shot 2018-07-20 at 20 27 59](https://user-images.githubusercontent.com/6337894/43021409-7406041e-8c5b-11e8-9bb8-2be684eee536.png)
![screen shot 2018-07-20 at 20 28 08](https://user-images.githubusercontent.com/6337894/43021411-7427e3a4-8c5b-11e8-9888-8514a32cd28d.png)

However, when running `Feature extraction`, it does not let me use the data for the cameras and images from the DB, although it is definitely in the loaded DB.

This is the output of the console within the GUI if I run `feature extraction`:
```
...
Processed file [42/133]
  Name:            A476A93E-6606-486E-A7A0-C0D658E7AE62.jpg
  Dimensions:      1920 x 1080
  Camera:          67 (OPENCV)
  Focal Length:    2304.00px (Default)
  Features:        287
Processed file [43/133]
  Name:            A81FBC68-2B12-4D3A-8F2E-DC8CBD853A05.jpg
  Dimensions:      1920 x 1080
  Camera:          68 (OPENCV)
  Focal Length:    2304.00px (Default)
  Features:        866
...
```

As you can see, it's using default settings rather than the ones I showed above.
How can I tell it to use the ones in the DB? Thanks.

**Comment by snowzurfer** [comment]
I figured this one out.

**Comment by ahojnnes** [comment]
Just to clarify for future people that might read this thread: The pose parameters in the database are only used for the ``spatial_matcher`` and not during the reconstruction. You have to write the known pose parameters to the ``images.txt/bin``.
