### ISSUE TITLE
How to calculate the Quaternion and Position of `images.txt` from known camera extrinsics?

### ISSUE THREAD

**Issue by snowzurfer** [colmap/colmap#434]
I have a series of camera extrinsics for my images: each camera's position vector (in world coordinates) and rotation matrix (in the camera's coordinates), the latter described as a 3x3 matrix.

If I simply transform the Rot matrix to a quaternion and save it in the file, along with the point, the result is not what I expect:

![screen shot 2018-07-21 at 17 47 28](https://user-images.githubusercontent.com/6337894/43038268-3ca9ca60-8d0e-11e8-9c63-1d01348205c8.png)

The cameras are all over the place, and I have figured out it's because my rotation matrix is with respect to the world's origin, *before* translation, whereas it looks like colmap first translates and then rotates.

Basically in my system I'd calculate a point with respect to the camera as `T * R * p`, whereas colmap does `R * T * p`.
Could you confirm that that's the case?

If I let colmap figure out the camera's positions itself, it looks like it does it correctly and this screenshot shows the positions I'd expect, as calculated from colmap without mines:

![screen shot 2018-07-21 at 17 48 02](https://user-images.githubusercontent.com/6337894/43038306-b178d430-8d0e-11e8-881f-c3aba325b8f8.png)

How can I go about putting the right values in `images.txt`, given I have a position and a rotation matrix per camera? Again, my rotation matrix is local, i.e. it represents the rotation of the camera as if it were at the world origin *before* translation, but it looks like colmap uses a different multiplication order.

**Comment by ahojnnes** [comment]
Just invert your known parameters and write the inverted parameters to the ``images.txt``? In other words, write the Quaternion parameters of ``transpose(R)`` and ``-transpose(R) * T`` (assuming ``R`` and ``T`` are given in your convention).

**Comment by snowzurfer** [comment]
@ahojnnes I'll try that, thanks for the reply; should I not invert rather than transpose them?

**Comment by ahojnnes** [comment]
The transpose of a rotation matrix is the inverse, since it is an orthonormal matrix.

**Comment by snowzurfer** [comment]
Thanks.

**Comment by reallingchen** [comment]
@ahojnnes 

I have a similar issue and pls help at your convenience.

I have norminal ground truth of camera poses, represented in the format as below:

QW, QX, QY, QZ, TX, TY, TZ,

Shown below is the correct visualization of their positions and orientations. The orientations of the camera are roughly tangent to the trajectory of the vehicle, compliant to the camera's forward looking mounting
![poses1](https://user-images.githubusercontent.com/17305471/100995317-94084780-3592-11eb-8296-fac501b613fc.png)

When write the pose info into images.txt and import to COLMAP GUI, there are something wrong with the orientations, as shown below, i.e., the orientations of the cameras are not tangent to the trajectory anymore.
<img width="554" alt="pose2" src="https://user-images.githubusercontent.com/17305471/100996930-a6838080-3594-11eb-9169-4993ec72af07.png">

Later I changed the quaternion info in images.txt to their conjugates to give the inverse of the rotations, i.e., 

a + bi + cj +dk    ---->     a - bi - cj - dk

but the results shown in COLMAP is still wrong, as shown below.
<img width="488" alt="pose3" src="https://user-images.githubusercontent.com/17305471/100997747-a33cc480-3595-11eb-9ddf-37519de42066.png">

Can you pls comment on this? Thanks a lot.

**Comment by reallingchen** [comment]
Please ignore my earlier comment. Earlier the modification was only done to the rotation R, i.e., R -> R', but not the translation t. After make t -> -R't, the result looks right.
