### ISSUE TITLE
Old-style parameters naming in generated scripts

### ISSUE THREAD

**Issue by isolin** [colmap/colmap#436]
Hi!

In the most recent release, come of the command-line functions were renamed. After running image_undistorter it creates two `.sh` scripts: `run-colmap-geometric.sh` and `run-colmap-photometric.sh` which both contain `DenseStereo.option_name` options instead of the new naming `PatchMatchStereo.option_name`.

**Comment by ahojnnes** [comment]
Thanks for the bug report, fixed in the latest commit.
