### ISSUE TITLE
Newly registered images with their features and matches do not show up on the DB management GUI.

### ISSUE THREAD

**Issue by h12sawhney** [colmap/colmap#440]
**Describe the bug**
I created a Model using about 400 images.
Captured new images of the same scene. Reduced size of the new images and the registered these
to the model. The process goes through and new images are listed in the DB management GUI.
However, Features and Matches for the new images do not display.

**To Reproduce**
1. Create a model with image set.
2. Capture new images of the same scene with say a mobile device.
3. Optionally reduce image sizes.
4. Run image_registrator using the guide.

**Expected behavior**
That the newly registered images will also display features and matches as the original images do from which the model was created.

**Desktop (please complete the following information):**
 Windows 10
COLMAP 3.4

**Comment by ahojnnes** [comment]
You will have to run feature extraction and matching for the new images. Did you do that? Note sure if you already looked at this: https://colmap.github.io/faq.html#register-localize-new-images-into-an-existing-reconstruction, but it describes the process of registering new images into an existing model. Let me know if you have questions.

**Comment by h12sawhney** [comment]
Hi Johannes,

I exactly followed the
Feature Extraction
Matching
Registrator

Pipeline described in your documentation.

It seems that all the steps work and the DB GUI shows that new images with features are there
but the actual images, features and matches do not get rendered?

Regards,
Harpreet
========

**Comment by ahojnnes** [comment]
Okay, I think, I know what is happening: To render the model with the new images, you would have to File > Import the model that you created and saved to ``--output_path /path/to/model-with-new-images`` in the image registration step. Note that the database just contains cameras, images, features, matches, etc. but not the actual reconstructions. They are separate and are stored in a folder with cameras.bin/txt, images.bin/txt, and points3D.bin/txt.
