### ISSUE TITLE
Command line output verbosity

### ISSUE THREAD

**Issue by isolin** [colmap/colmap#441]
In the documentation I found a mention that 

> it is recommended to run the executables (including the GUI) from the command-line, where you can define various levels of logging verbosity.

but that is the only mention. Is there please a way to set maximum verbosity?

`colmap path_match_stereo` terminates on my dataset right after `Reading workspace...` without any further output and I would like to find out why and fix it.

**Comment by ahojnnes** [comment]
Colmap uses glog under the hood, so you can use the same logging configuration. When you run it from the command line it should also show you a trace back in case of a crash.

**Comment by isolin** [comment]
I found the following [instructions](http://rpg.ifi.uzh.ch/docs/glog.html) stating that I should either run it as

>    ./your_application --logtostderr=1

for which I get `ERROR: Failed to parse options - unrecognized option '--log tostderr'`

or as

>GLOG_logtostderr=1 ./your_application

which doesn't work in windows command line, but I replaced it by 
```
set GLOG_logtostderr=1
set SCRIPT_PATH=<path to COLMAP-dev-windows folder>
set PATH=%SCRIPT_PATH%\lib;%PATH%
"%SCRIPT_PATH%\bin\colmap" path_match_stereo --workspace_path <my data path>--workspace_format COLMAP --PatchMatchStereo.geom_consistency true --PatchMatchStereo.max_image_size 2000
```
that runs, but it terminates without any output as reported before. So I doubt the logging got enabled that way. An hour of further googling didn't bring me any more information how to enable glog in windows command line or powershell.

So how to enable glog when runing COLMAP in command line?

**Comment by ahojnnes** [comment]
The trace back functionality under Windows is disabled because last time I checked it was broken under windows. It only works under Linux/Mac/...

**Comment by isolin** [comment]
I will try to install and run it from a Linux under the Windows subsystem, but not sure if I get GPU access. Otherwise that would be a dead-end for me.

**Comment by isolin** [comment]
So I installed Ubuntu under my Windows and installed COLMAP successfully, but there is no CUDA device in the emulator so `dense_stereo` won't run :(

**Comment by ahojnnes** [comment]
If you want to debug under Windows, I suggest to use he build script and compile colmap in RelWithDebInfo build type. Then you can debut in visual studio or your favorite environment.

**Comment by isolin** [comment]
Over 90% of my colleagues use Win + Visual Studio, but today I found one of the few who has Linux + CUDA installed. We were able to compile and run Colmap but the error message gave no hint. It is a out_of_range in a Map object. The stack trace didn't give any further hint, just a soup of useless addresses. So my questions would be:
* I saw that in Colmap.cc the argv gets passed to the glog initializer. Yet, I was unable to enable it using the `--logtostderr` Colmap considers it an unknown option on Linux as well. So is there a way to enable it, or is the stack trace already the log?
* The compilation on Linux is really easy. On Win I spent almost a day fighting with dependencies just to pass through CMAKE. The resulting VS solution had several hundreds of errors. At that point I gave up. This is actually no question :)
* To recall the problem: I created a sparse reconstruction, exported it to the `txt` format, threw out some points, images and cameras and using `image_undistorter` I implicitly created back the `bin` files. Is there another way of converting the `txt` files to `bin` files, possibly with some verbose consistency checking?
* `points3D.txt` has this `POINT2D_IDX` is that really an index to the features list in the `images.txt` or is it an `ID`?

**Comment by ahojnnes** [comment]
1. This is a bug and it shouldn’t be listed as an unknown option. Thanks for the hint. 
2. In Windows, you should use the scripts/python/build.pu script, which should make it pretty easy to compile under Windows as well. 
3. There is a model_converter command which allows you to convert from txt to bin and vice versa. 
4. POINT2D_IDX is an Index into the features listed in the images.txt. Note that those features should also be present in the database in case you use an existing reconstruction and provide it as an input to the mapper (if you continue a reconstruction process to e.g. add new images).

**Comment by ahojnnes** [comment]
The database is only used for the mapper not for the patch match step, since you also correctly noted that it is not passed to that command. If you remove individual features, then you need to shift/reindex.

**Comment by isolin** [comment]
The reindexing might be the problem I am facing. I will keep you updated.

**Comment by isolin** [comment]
Finally, I found the my error and the import of the clusters to the Colmap dense pipeline works now 😃 
Nevertheless, it I hope the log option will be available once fixed. Could have saved me a few days. 

Nevertheless, Colmap is a great library and I absolutely love it! Thank you for creating it.
