### ISSUE TITLE
How to improve smoothness of Delaunay mesher

### ISSUE THREAD

**Issue by snowzurfer** [colmap/colmap#446]
The result of my delaunay meshing are very jaggy:

![screen shot 2018-07-29 at 14 43 52](https://user-images.githubusercontent.com/6337894/43367005-153d9ffc-933e-11e8-9833-ebf9ecea208e.png)

![screen shot 2018-07-29 at 14 44 00](https://user-images.githubusercontent.com/6337894/43367006-1569a200-933e-11e8-96f0-68f9f17e7155.png)

The fusion result, on the other hand, seems good:

![screen shot 2018-07-29 at 14 48 42](https://user-images.githubusercontent.com/6337894/43367024-961cf848-933e-11e8-8fb7-a8e59dbf95a3.png)

I run the command as such:
```
colmap delaunay_mesher --input_path /opt/work_dir/colmap_dense --input_type dense --output_path /opt/outputs/delaunay.ply
```

How can I smooth it out? Also, how can I transfer the colour from the `fused.ply` model to the Delaunay triangulated mesh? I am aware that it will only be vertex-coloured. Thanks!

**Comment by snowzurfer** [comment]
I have experimented with the various parameters as explained here: https://colmap.github.io/faq.html#improving-dense-reconstruction-results-for-weakly-textured-surfaces and in the rest of the FAQ, but without much improvement.

The poisson output is very noisy:
![screen shot 2018-07-30 at 19 39 08](https://user-images.githubusercontent.com/6337894/43416659-d44cbd5e-9430-11e8-9028-0f559050dafd.png)

and I have experimented with the `trim` option, but without success.

I have done a test run with OpenMVS for densification + reconstruction + refinement, and the result is much better; this is the final output when using OpenMVS to do the above steps:
![screen shot 2018-07-30 at 19 41 12](https://user-images.githubusercontent.com/6337894/43416719-fe35ee7e-9430-11e8-9828-26d71921aae4.png)

And comparing OpenMVS's dense point cloud vs colmap's, shows that OpenMVS's one is much denser; OpenMVS:
![screen shot 2018-07-30 at 19 40 12](https://user-images.githubusercontent.com/6337894/43416770-1f758a40-9431-11e8-914a-05274144cf10.png)
Colmap:
![screen shot 2018-07-30 at 19 40 22](https://user-images.githubusercontent.com/6337894/43416781-26f4f396-9431-11e8-90cd-6eaa9393cf9e.png)

Any ideas as to how I could improve the final reconstruction via a full colmap pipeline?

**Comment by ahojnnes** [comment]
The reason seems to be the incomplete dense point cloud. Try increasing the patch size in the stereo step or reduce the image resolution in the stereo step.

**Comment by snowzurfer** [comment]
Thanks @ahojnnes , I will give it a go and let you know

**Comment by ahojnnes** [comment]
You could also use Laplacian smoothing as a post processing step to the meager, eg as implemented in Meshlab. But this will not fix big holes but just make the surface smoother.

**Comment by snowzurfer** [comment]
@ahojnnes sorry, I was busy at work and couldn't try it. I will soon!

**Comment by ahojnnes** [comment]
Closing this issue as resolved for now, but feel free to follow up in case of remaining questions.

**Comment by claudito1991** [comment]
> The reason seems to be the incomplete dense point cloud. Try increasing the patch size in the stereo step or reduce the image resolution in the stereo step.

@ahojnnes i have  a doubt. If the point is to increase the dense point cloud, why would you reduce the image resolution in the stereo step?
