### ISSUE TITLE
Missing definition of sse_sum(__m256)

### ISSUE THREAD

**Issue by wavexx** [colmap/colmap#447]
The current master fails to build on linux without GPU support.
There's likely a typo in colmap/lib/PBA/SparseBundleCPU.cpp:357 where sse_sum is redefined for __m128 instead of being specialized for __m256 as done for the _WIN32 just some lines above.

**Comment by ahojnnes** [comment]
Can you please post the error message you see during compilation?

**Comment by mgprt** [comment]
I can confirm this for the `dev` branch, built on Linux with the `--without_cuda` flag.
The error message is 
```
/colmap/lib/PBA/SparseBundleCPU.cpp: In function ‘double pba::MYAVX::sse_dot(__m256d, __m256d)’:
/colmap/lib/PBA/SparseBundleCPU.cpp:372:33: error: no matching function for call to ‘sse_sum(__m256d)’
   return sse_sum(sse_mul(s1, s2));
                                 ^
/colmap/lib/PBA/SparseBundleCPU.cpp:372:33: note: candidates are:
colmap/lib/PBA/SparseBundleCPU.cpp:357:14: note: float pba::MYAVX::sse_sum(__m128)
 inline float sse_sum(__m128 s) {
              ^
/colmap/lib/PBA/SparseBundleCPU.cpp:357:14: note:   no known conversion for argument 1 from ‘__m256d {aka __vector(4) double}’ to ‘__m128 {aka __vector(4) float}’
/colmap/lib/PBA/SparseBundleCPU.cpp:361:15: note: double pba::MYAVX::sse_sum(__m128d)
 inline double sse_sum(__m128d s) {
               ^
/colmap/lib/PBA/SparseBundleCPU.cpp:361:15: note:   no known conversion for argument 1 from ‘__m256d {aka __vector(4) double}’ to ‘__m128d {aka __vector(2) double}’

[...]
```

The function tries to cast the 128 bit register to a float array of size 8 which doesn't make sense.
Simply changing the argument from __m128 to __m256 fixes the compilation error for me.

**Comment by ahojnnes** [comment]
Should be fixed with the latest commit. Let me know if it works for you. Thanks.
