### ISSUE TITLE
[colmap in docker] cannot to connect to display

### ISSUE THREAD

**Issue by ling49043171** [colmap/colmap#45]
I'm buiding integration system, in one step using the colmap. The colmap buiding result seams all is ok, but when I run it in my nvidia-docker container, got the title error. 

I want to opt-in off display setting in the colmap. But I don't know where I can turn off it in colmap.
Is there anyone guys could kindly tell me the method?

**Comment by ahojnnes** [comment]
Are you trying to start the GUI in the virtual machine? You would have to use the command line functionality probably: https://colmap.github.io/cli.html

**Comment by ling49043171** [comment]
Is there any method to use GPU and not use display?
I'm so trouble in it.

**Comment by ahojnnes** [comment]
Feature extraction provides a CPU only version and the feature matching part uses CUDA if you specify a GPU index.

**Comment by ling49043171** [comment]
thanks for your answer. I used [--use_gpu=0] in Feature exetractor, and it worked well.
The rest steps all [exhaustive_matcher, mapper, model_converter,image_undistorter] also worked, in gpu mode.

In the step Feature exetractor, If I still want to use gpu, I have to change the Using method of QApplication, because it was the connecting display reason. Or I set up one X-server in use of display.

In Qt4, there is GUIEnabled flag in the constructor of class QApplication, but after Qt5 the flag has been removed.  Refers the uri:[https://forum.qt.io/topic/30138/qt-5-1-qapplication-without-display-qxcbconnection-could-not-connect-to-display/2].

I don't know If I don't  use the QApplication, witch part I have to fix.

**Comment by gesong1982** [comment]
Hi @ahojnnes
Thank you for providing the open source, really appreciate it. 
I have the similar issues, when run COLMAP command line on headless AWS instance under GPU mode. Currently under the X-server, I have warnings shown below:

QXcbConnection: XCB error: 148 (Unknown), sequence: 178, resource id: 0, major code: 140 (Unknown), minor code: 20

With this warning feature_extractor could pass but in exhaustive_matcher it got error shown below:

*** Aborted at 1480544505 (unix time) try "date -d @1480544505" if you are using GNU date ***
PC: @           0x52b416 colmap::SiftGPUFeatureMatcher::MatchImagePairs()
*** SIGSEGV (@0x0) received by PID 2250 (TID 0x7fdced498700) from PID 0; stack trace: ***
    @     0x7fdd0d1513e0 (unknown)
    @           0x52b416 colmap::SiftGPUFeatureMatcher::MatchImagePairs()
    @           0x52eb9f colmap::ExhaustiveFeatureMatcher::Run()
    @           0x5a67dc colmap::Thread::RunFunc()
    @     0x7fdd0a5fbc80 (unknown)
    @     0x7fdd0d14770a start_thread
    @     0x7fdd09d6182d clone
    @                0x0 (unknown)

Any idea about these warning and errors? @ling49043171 how do you make exhaustive_matcher, mapper, model_converter, image_undistorter steps worked in GPU mode?

Thanks

**Comment by gesong1982** [comment]
Also if used [--use_gpu=0] in Feature exetractor, and it worked well. But exhaustive_matcher with "-[-no_opengl", "1"] still has error shown below:
Matching block [1/1, 1/1]
MultiplyDescriptor:	invalid device function
*** Aborted at 1480548746 (unix time) try "date -d @1480548746" if you are using GNU date ***
PC: @           0x7999db SiftMatchCU::GetBestMatch()
*** SIGSEGV (@0x7f050dc24930) received by PID 4479 (TID 0x7f0417583700) from PID 230836528; stack trace: ***
    @     0x7f043b2403e0 (unknown)
    @           0x7999db SiftMatchCU::GetBestMatch()
    @           0x52506b colmap::MatchSiftFeaturesGPU()
    @           0x52ae94 colmap::SiftGPUFeatureMatcher::MatchImagePairs()
    @           0x52eb9f colmap::ExhaustiveFeatureMatcher::Run()
    @           0x5a67dc colmap::Thread::RunFunc()
    @     0x7f04386eac80 (unknown)
    @     0x7f043b23670a start_thread
    @     0x7f0437e5082d clone
    @                0x0 (unknown)

**Comment by ahojnnes** [comment]
You cannot use the feature extractor in GPU mode without an attached display. Closing this issue for now and feel free to reopen the issue if you have additional questions regarding this issue.

**Comment by ahojnnes** [comment]
@ling49043171 FYI. The matcher now supports CPU-based matching.

**Comment by cebe** [comment]
In case someone is interested in this: It is possible to run colmap on a server without a display by simulating a display via [xvfb](https://en.wikipedia.org/wiki/Xvfb):

```
xvfb-run -s "+extension GLX -screen 0 1024x768x24" ./exhaustive_matcher --General.database_path $PROJECT_PATH/database.db
```

**Comment by ahojnnes** [comment]
@cebe This is very useful, thanks!

**Comment by placeforyiming** [comment]
> In case someone is interested in this: It is possible to run colmap on a server without a display by simulating a display via [xvfb](https://en.wikipedia.org/wiki/Xvfb):
> 
> ```
> xvfb-run -s "+extension GLX -screen 0 1024x768x24" ./exhaustive_matcher --General.database_path $PROJECT_PATH/database.db
> ```

Looks like it can't let docker allow hardware GPU acceleration, still can't solve this problem. 
Curious any new solutions?

**Comment by tjdahlke** [comment]
> You cannot use the feature extractor in GPU mode without an attached display. Closing this issue for now and feel free to reopen the issue if you have additional questions regarding this issue.

Why is that?

**Comment by beedawg1985** [comment]
+ 1

**Comment by beedawg1985** [comment]
> > You cannot use the feature extractor in GPU mode without an attached display. Closing this issue for now and feel free to reopen the issue if you have additional questions regarding this issue.
> 
> Why can't someone use the feature extractor in GPU mode without an attached display?

+ 1 for this!

**Comment by kwea123** [comment]
in my case `exhaustive_matcher` doesn't work without display either.
