### ISSUE TITLE
Use CMAKE_CURRENT_SOURCE_DIR instead of CMAKE_SOURCE_DIR?

### ISSUE THREAD

**Issue by apbodnar** [colmap/colmap#450]
I'm trying to use colmap as a static library by building it in the source tree of a different CMake project.

I've added `add_subdirectory(dep/colmap)` to the top level CMakeLists.txt, but cmake throws an error because it's looking for CMakeHelper.cmake in the parent project rather than the colmap repo.

Changing all instances of `CMAKE_SOURCE_DIR` to `CMAKE_CURRENT_SOURCE_DIR` seems to get cmake to stop complaining. Is there a reason for not using CMAKE_CURRENT_SOURCE_DIR?

**Comment by ahojnnes** [comment]
There is no reason for this, but I haven’t encountered this issue so far since I never included COLMAP into an another CMake project.

**Comment by ahojnnes** [comment]
Would you like to submit a pull request to fix this issue? Thanks.

**Comment by ahojnnes** [comment]
Okay, this is fixed in the latest commit. Thanks for the suggestion.
