### ISSUE TITLE
LORANSAC compiler error

### ISSUE THREAD

**Issue by mgprt** [colmap/colmap#452]
**Describe the bug**
When compiling on the Euler cluster I get an error
```
In file included from /colmap/src/base/similarity_transform.cc:38:0:
/colmap/src/optim/loransac.h:92:1: error: prototype for ‘typename colmap::LORANSAC<Estimator, LocalEstimator, SupportMeasurer, Sampler>::Report colmap::LORANSAC<Estimator, LocalEstimator, SupportMeasurer, Sampler>::Estimate(const std::vector<typename Estimator::X_t>&, const std::vector<typename Estimator::Y_t>&)’ does not match any in class ‘colmap::LORANSAC<Estimator, LocalEstimator, SupportMeasurer, Sampler>’
 LORANSAC<Estimator, LocalEstimator, SupportMeasurer, Sampler>::Estimate(
 ^
/colmap/src/optim/loransac.h:66:10: error: candidate is: typename colmap::RANSAC<Estimator, SupportMeasurer, Sampler>::Report colmap::LORANSAC<Estimator, LocalEstimator, SupportMeasurer, Sampler>::Estimate(const std::vector<typename Estimator::X_t>&, const std::vector<typename Estimator::Y_t>&)
   Report Estimate(const std::vector<typename Estimator::X_t>& X,

```

The code compiles fine on all other machines I tested.

**To Reproduce**
On Euler
1. Clone COLMAP repo
2. Load modules new, cmake 3.5, qt 5.5, python 3.6
3. Run build script (`build.py`)

Tested with gcc 4.8.2 and 5.2.0.

Changing the return type of `Estimate` to `typename RANSAC<Estimator, SupportMeasurer, Sampler>::Report` fixes the error for me.

**Comment by ahojnnes** [comment]
Can you submit a fix as a pull request? Thanks.

**Comment by mgprt** [comment]
It seems just changing the return type breaks compilation on Windows.
I'll try to look into that.

**Comment by ahojnnes** [comment]
Sounds good, thanks.

**Comment by mgprt** [comment]
I couldn't find a fix that works on all my systems and a minimal example of the problem compiles fine on Euler. I guess the error depends on my specific setup and shouldn't be an issue for other people. I'll just work around it.

**Comment by RayShark0605** [comment]
> 

Have you solved this problem? I have the same problem on Windows...
