### ISSUE TITLE
Feature matching too slow even with GPU

### ISSUE THREAD

**Issue by bbzh** [colmap/colmap#455]
Hi, 
I am running feature extratction and matching on the Internet photo collection (http://www.cs.cornell.edu/projects/1dsfm/). I find that even with GPU the matching is still very slow, e.g. 376 images can take around 1.5 hour. Using Vocabularty tree does not speed up. May I check with you whether this is the normal speed to be expected? How to speed up it? Thanks!

**Comment by fishcu** [comment]
These speeds are normal. You can speed it up by getting "smarter" about the matching. For example, if you have sequential images, e.g., from a video stream, you should use the sequential matcher instead of brute force.
