### ISSUE TITLE
feature matching in automatic reconstruction is serveral times faster than runing individual matcher

### ISSUE THREAD

**Issue by bbzh** [colmap/colmap#456]
Hi,

I observed that when running automatic reconstruction, the feature matching inside it is serveral (e.g. 3-10) times faster than running the individual matcher on the features, e.g. exhaustive_matcher or vocab_tree_matcher. I check the code and seems that the automatic reconstruction are using all the default parameters for both feature extraction and matching. So the speed should be similar to run individual extratction and matcihing sequentially that also use default parameters. I am curious what make this difference. Can anyone give explanation? Thanks.

**Comment by bbzh** [comment]
I find the number of features in automatic reconstrution is much smaller than running feature extraction along (on the same data). Also there seems to be a bug that the number of features is not up bounded by max_num_features (default as 8192). It is sometimes higher than 8192. Why?

**Comment by ahojnnes** [comment]
There are different quality settings in the automatic reconstructor. If you set the quality settings to "high" or "extreme" it should be roughly equivalent to the default settings and hence take the same time.
