### ISSUE TITLE
Most convenient way to use another feature type?

### ISSUE THREAD

**Issue by fishcu** [colmap/colmap#458]
It seems there are multiple ways to replace the standard SIFT descriptor with something of your own.
1. Inject into database directly using, e.g., sqlite modules with python
2. Similar to 1., but use the provided python script (combination of `add_keypoints` and `add_matches`) -- the syntax here is not 100% clear for me, how to use these functions?
3. Use `matches_importer`. It seems that keypoints need to be injected into the database anyway through a procedure similar to 1. or 2.
4. Replace calls to GPU-SIFT with whatever you want to use. I guess this would require a lot of hacks as the descriptor size, distance and matching functions are probably all hardcoded. I haven't looked into this at all.

Some questions:
- Are these approaches valid?
- For approaches 1. and 2., how can geometric validation / match filtering be achieved? I only have "raw" matches available.
- In general, can descriptors be absent from the database? In this case, it seems they are never used (as I would provide all feature points, descriptors, and matches myself).
- Thus, what is the most convenient/recommended way to replace SIFT?

**Comment by fishcu** [comment]
Thank you very much, that link is supremely helpful! Also your comments :)
Planning to use ORB.

**Comment by ahojnnes** [comment]
It would be great to see how ORB fares on the feature evaluation benchmark. From my own experience on a few small datasets, the performance of ORB is much worse than SIFT and on the GPU it has limited runtime benefits (maybe 2-4x faster).

**Comment by ahojnnes** [comment]
In other words, it would be great to have a submission for ORB in the feature evaluation benchmark, if you have time for that.

**Comment by fishcu** [comment]
Sure. This problem is currently low priority for me (the stereo rig implementation would be higher priority).
Using ORB at this stage might have some benefits later in the pipeline (which will include real-time applications), but need more experiments to verify that. :)

**Comment by GabbySuwichaya** [comment]
Hello. I find this conversation interesting, as my current task is also about comparing and using other feature extraction methods. 

What I wonder about is if I gives `matches_importer` the descriptors and image-pairs (only) and without matches, then which _feature matching_ methods will `matches_importer` use ?

**Comment by jhaggle** [comment]
Assume SIFT finds too few interest points and you want more points. Assume you therefore externally find interest points with e.g. FAST and use the SIFT descriptor for those interest points. How can you then combine those external keypoints with keypoints found by Colmap's SIFT?
