### ISSUE TITLE
"filter_min_triangulation_angle" appears two times in UI

### ISSUE THREAD

**Issue by flm8620** [colmap/colmap#46]
Option "filter_min_triangulation_angle" appears two times in Window "multi-view stereo options"
should delete this [line](https://github.com/colmap/colmap/blob/d8d6f9aa445c637d29d0414f0c0f8d5afab0dd83/src/ui/multi_view_stereo_widget.cc#L81).

**Comment by ahojnnes** [comment]
Fixed in https://github.com/colmap/colmap/commit/facf7229ca8843cb2340a09c2fc88480f69987fa, thanks for the bug report.
