### ISSUE TITLE
Latest pre release version does not generate fused.ply and meshed.ply in MacOS High Sierra

### ISSUE THREAD

**Issue by roichu** [colmap/colmap#460]
**Describe the bug**
On the latest MacOS version, using clomp latest pre-release, no stl files are generated inside "sparse".

**To Reproduce**
1. Start automatic reconstruction 
2. Click on run
3. Once finished, you can see the layout of the camera angles, but no files were generated (cameras.bin, images.bin, points3D.bin and project.ini were created, but no .stl or .ply)

**Expected behavior**
After an automatic reconstruction, fused.ply and meshed.ply should be generated inside project folder, but they are not generated.

**Screenshots**
<img width="1035" alt="captura de pantalla 2018-08-21 a las 11 02 29" src="https://user-images.githubusercontent.com/42570563/44392160-de846800-a531-11e8-9f33-4793d5eed048.png">
<img width="778" alt="captura de pantalla 2018-08-21 a las 11 02 47" src="https://user-images.githubusercontent.com/42570563/44392176-e8a66680-a531-11e8-9c06-083aad665b19.png">

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra (10.13.6)
 - Version: Latest pre-release

**Latest log**
[log.log](https://github.com/colmap/colmap/files/2305588/log.log)

**Comment by ahojnnes** [comment]
If you downloaded the precompiled binaries from the website, then they do not have CUDA support, which is necessary to produce dense models (the output of the dense stage is stored as a PLY file). If you want to convert the sparse model to a PLY file, then simply import the model into COLMAP and pick File > Export as... or alternatively use the ``model_converter`` command.
