### ISSUE TITLE
Unable to visualize large dense point cloud (~104 million points)

### ISSUE THREAD

**Issue by sberryman** [colmap/colmap#461]
**Describe the bug**
Unable to visualize a large dense point cloud. It seems like it crashes when the COLMAP process approaches 16 GB of memory utilization. I also tried to do a DEBUG build to get a better stack trace but that didn't help. CMAKE log at the bottom of this issue.

```shell
*** Aborted at 1534873640 (unix time) try "date -d @1534873640" if you are using GNU date ***
PC: @         0x41001e85 (/tmp/.glpOhhqu (deleted)+0x1e84)
*** SIGSEGV (@0x0) received by PID 77340 (TID 0x7f0aaed4b800) from PID 0; stack trace: ***
    @     0x7f0aaa7ee4b0 (unknown)
    @         0x41001e85 (/tmp/.glpOhhqu (deleted)+0x1e84)
Segmentation fault (core dumped)
```

**To Reproduce**
I've provided a large dense reconstruction which I'm able to visualize in MeshLab and pcd_viewer (after converting pcl -> pcd)
Dropbox: https://www.dropbox.com/s/nra2ap3cncl2zow/fused.ply?dl=0 (~2.81 GB)

**Desktop:**
 - OS: Linux 4.4.0-133-generic #159-Ubuntu SMP Fri Aug 10 07:31:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux (64 GB RAM)
 - COLMAP Version: Git SHA fadc0202cefb68856d415dec3c148611f885c494

**Additional context**
On a side note, when doing stereo fusion in the GUI, there is the potential to lose the work. You present a dialog box upon completion asking if you would like to visualize the dense reconstruction. If you say "yes", you attempt to show the dense cloud in the GUI BEFORE saving. If the point cloud is too large, COLMAP will crash and you have to start the fusion process over. I would expect you to save the pcl and pcl.vis file BEFORE attempting to visualize within the GUI. 

CMAKE Output:
```shell
> cmake -DCMAKE_BUILD_TYPE=DEBUG ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found installed version of Eigen: /usr/lib/cmake/eigen3
-- Found required Ceres dependency: Eigen version 3.2.92 in /usr/include/eigen3
-- Found required Ceres dependency: glog
-- Performing Test GFLAGS_IN_GOOGLE_NAMESPACE
-- Performing Test GFLAGS_IN_GOOGLE_NAMESPACE - Success
-- Found required Ceres dependency: gflags
-- Found Ceres version: 1.14.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, OpenMP, Multithreading]
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   graph
--   regex
--   system
--   unit_test_framework
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0") 
-- Found Eigen
--   Includes : /usr/include/eigen3
-- Found FreeImage
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
-- Found Glog
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found Glew
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- Found Threads: TRUE  
-- Found Qt
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Core
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5OpenGL
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets
-- Found CGAL
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libCGAL.so.11.0.1
-- Build type specified as DEBUG
-- Enabling SIMD support
-- Enabling OpenMP support
-- Disabling interprocedural optimization
-- Autodetected CUDA architecture(s):  6.1 6.1
-- Enabling CUDA support (version: 8.0, archs: sm_61)
-- Enabling OpenGL support
-- Disabling profiling support
-- Enabling CGAL support
-- Configuring done
-- Generating done
-- Build files have been written to: /home/development/colmap/build
```

**Comment by sberryman** [comment]
Note: This is a bad reconstruction due to the massive amount of noise but it still crashes.

**Comment by ahojnnes** [comment]
104M points is a massive point cloud. COLMAP’s current model viewer is not implemented in a memory efficient manner. There is a lot of overhead when loading simple point clouds. I suggest to load the model in an external viewer such as Meshlab (note that the beta version of meshlab should be more efficient in loading large models).

**Comment by sberryman** [comment]
Good to know that is considered massive. Closing as you have no expectation of a point cloud that size loading in COLMAP. On a side note I have been able to visualize a point cloud of roughly 60M points within COLMAP.

**Comment by ahojnnes** [comment]
It depends on the amount of memory you have in your system. It can well be that you can load models of more than 100m points on some systems.
