### ISSUE TITLE
Rig BA and ComputeScale(): Bug with incomplete rig config / incomplete reconstruction?

### ISSUE THREAD

**Issue by fishcu** [colmap/colmap#462]
I've run into a crash when using rig BA and the `ComputeScale()` function:
At the lowest level, the crash is because some snapshots may not contain the complete rig config (for example, snapshot contains reference camera only, but rig is actually stereo cameras).
The line:
```const auto& image = reconstruction.Image(snapshot[i]);```
Will then crash with out of bounds error, as `i` goes from `0` to `NumCameras()-1`, however `snapshot` has a smaller size.

Fixing this bug is easy; However, at several places in the code, there seem to be assumptions that incomplete given rigs, or incomplete reconstructions are fine. This even includes one of the unit tests.

In order to proceed with the implementation of feeding extrinsics from JSON, I have fixed all occurences of "passing incomplete rig is fine". The commit can be found here:
https://github.com/fishcu/colmap/commit/ae2acc920a9c0c4ae6e1b3915904f61ba52d6b2c

Note that the commit probably does not compile if pulled like that, as I was unable to perfectly split the commit from the rest of my ongoing implementation. I will push the remainder of the implementation, which can then compile, ASAP. The only offending line is probably this one:
https://github.com/fishcu/colmap/commit/ae2acc920a9c0c4ae6e1b3915904f61ba52d6b2c#diff-c7202e7799dcbaf736804e1db33b92e5R1311
But it's possible that it doesn't compile for other reasons as well.

This leaves me with several questions:
- I can't think of a use case where incomplete rigs are given (neither in the JSON input, nor when doing rig BA for an incomplete reconstruction). Am I missing any use cases? 
- Did I miss any places in the source code regarding this behavior?

**Comment by ahojnnes** [comment]
Regarding your two questions: 1) I agree, that there shouldn’t be a reason for an incomplete specification of the camera rig. 2) looks good to me.

**Comment by fishcu** [comment]
Great, thanks for checking! :)
