### ISSUE TITLE
All memory is consumed on feature extraction, then the program crashes

### ISSUE THREAD

**Issue by Darker** [colmap/colmap#464]
**Describe the bug**
I had no success getting this program to do anything. I selected dataset of 800 pictures, which I previously used with VisualSFM. 
I created the database and project. When I decided to run the feature extraction step using GPU, program froze. It then went ahead to consume 6GB of memory (all that was available). Then it dug into virtual memory. Eventually, programs started crashing, including COLMAP.

I had similar results with CPU mode too.

**To Reproduce**
1. Create project with at least 800 images
2. Save any work you have in other programs
3. Start feature extraction
4. Watch the system collapse

**Expected behavior**
I expected what I saw in the instruction video.

**Desktop (please complete the following information):**
 - OS: Windows 7 x64
 - OLMAP 3.5 (Commit a6a8f35 on 2018-08-23 with CUDA)
 - RAM: 8GB
 - NVidia: NVS 5400M
 - CUDA: 6.5.44 driver

**Additional context**
I can provide the dataset, but I doubt this behavior would be specific to just one dataset.

**Comment by Darker** [comment]
I now reproduced the same behavior with different dataset of 200 pictures. The consumption of memory was 6.5GB physical and 5GB virtual from what I saw in task manager.

**Comment by ahojnnes** [comment]
Set the number of threads in the feature extraction stage to a lower value. I suggest 1 in this case.

**Comment by LindyBalboa** [comment]
I ran into the same issue and reducing the threads from max (-1 = 4) to 1 or 2 allowed it to continue. This only happened with running the Extract step manually. I did not have it happen during Auto-Reconstruction. Any input on that?

**Comment by ahojnnes** [comment]
What quality did you specify during automatic reconstruction>
