### ISSUE TITLE
patch_match_stereo silently crashes the GUI when out of memory

### ISSUE THREAD

**Issue by fishcu** [colmap/colmap#465]
**Describe the bug**
Running dense reconstructions can result in out-of-memory error on the GPU, indicated as follows when running on the command line:
```CUDA error at /home/user/dev/forked/colmap/src/mvs/gpu_mat.h:167 - out of memory```
When doing dense reconstructions using the Colmap GUI on such datasets, the application will crash without warning or error.

**To Reproduce**
Do a dense reconstruction with large images that use more memory than your GPU has.

**Expected behavior**
It would be better if the GUI could issue a warning or error, saying that `--PatchMatchStereo.max_image_size` has to be reduced (or will be reduced automatically).

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Colmap from my fork
 - latest nvidia driver

**Comment by ahojnnes** [comment]
I know, this is not implemented very user friendly at the moment, but it is rather difficult to pre-calculate the required GPU memory and to determine the amount of available system memory across multiple platforms. I would very much appreciate if someone has the time to improve the behavior here, but I don’t have time for this unfortunately.

**Comment by fishcu** [comment]
Since there is a limited amount of different GPU RAM configurations available, a simple table could be sufficient for triggering a warning at least. Something like:
Picture is 1024 px or more on longest side => need at least 2 GB
2000px => 4 GB
3000px => 6 GB
(bogus numbers, just to show the concept)
