### ISSUE TITLE
COLMAP sutdown suddenly "Timers cannot be stoped from another thread"

### ISSUE THREAD

**Issue by aConar** [colmap/colmap#466]
COLMAP V.3.4 and COLMAP 3.5 (legacy CUDA) suddenly shutdown in the middle of auto-reconstruction. The only line of error showed in console in both versions is:
"QObject::~QObject: Timers cannot be stoped from another thread"

OS Windows 10
i7 16GB RAM laptop with Nividia 740M 2GB GPU.
Auto reconstruction from 80 photographs from cel phone.

**To Reproduce**
1. Select auto reconstruction
2. Select working and pictures folders
3. All options left default
4. clic RUN

**Comment by aConar** [comment]
Hi Johannes, it happens after 2 - 3 minutes run in both versions. I tried with a smaller number of images (50 instead of 80) and same error happens.

**Comment by ahojnnes** [comment]
Can you run the reconstruction steps individually and figure out which of the steps cause the crash? (Feature extraction, matching, sparse reconstruction, dense reconstruction)

**Comment by aConar** [comment]
Hi, running the reconstruction manually the error shows up in the dense reconstructions, after undistortion step. Clic on stereo and about a few secons of running stops suddenly with the same error mentioned above.

**Comment by ahojnnes** [comment]
See https://colmap.github.io/faq.html#fix-gpu-freezes-and-timeouts-during-dense-reconstruction
