### ISSUE TITLE
settings for reproducing result in the paper

### ISSUE THREAD

**Issue by bbzh** [colmap/colmap#467]
Hi Johannes,
Could you share the parameters you used to generate the result in the Table.1 of  "structure from motion revisited"? We would like to compare with it in a paper. Thanks.

**Comment by ahojnnes** [comment]
The comparison was done with a very old code base and is not possible with the current system. You can run the pipeline with default parameters for comparison. If you want to boost the performance, you should enable affine features and guided matching. For matching I used the vocabulary tree option with 100 nearest neighbors, which you could also increase for better performance.

**Comment by ahojnnes** [comment]
Let me know if you have other questions.

**Comment by bbzh** [comment]
When I set --SiftExtraction.estimate_affine_shape=true, --SiftExtraction.domain_size_pooling=true, --SiftMatching.guided_matching=true. The reconstruced point clouds contains a lot more clutterrd points and seems the quality is slower. I think the guided_matching introduces wrong matches. If I just want to make the two view geometry more accurate. Can I just switch on the first two options? Can you give more comments? Thanks!
