### ISSUE TITLE
why not split point cloud into small tile in fusion stage？

### ISSUE THREAD

**Issue by TMwhuhan** [colmap/colmap#468]
Hello, 
    Delaunay_mesher product a nice mesh, it's a great tool.  After laplace filter the mesh have more border than poisson result.  But It need huge size memory at graph-cut.   In my test it need more than 32Gb RAM when fused.ply large than 200 Mb.
    
    I think maybe we can split point cloud and the vis file into small tie, and run Delaunay_mesher    several times. I don't read all Delaunay_mesher  code, so I want to know is this solution practicable before modify fusion function.

**Comment by ahojnnes** [comment]
You should be able to reduce the memory consumption by increasing the value of the max_proj_dist option. Let me know how this works for you, thanks!

**Comment by ahojnnes** [comment]
Regarding your actual question, splitting the model into smaller sub models for the meshing should work, but it will likely not result in a consisten/watertight surface. There will be artifacts at the seams of the sub models.

**Comment by TMwhuhan** [comment]
I  tried increasing "max_proj_dist" value. It work and the ram used less than 25Gb, but the structure of mesh is  a little bit blur than before.  Thank you for your help.  I will open this iusse again if there is something new .

**Comment by ahojnnes** [comment]
This is expected, since it reduces the number of points in the mesh. You can play with the quality regularization parameter to reduce the amount of blur.
