### ISSUE TITLE
Can't reconstruct dense model on AMD GPU, even after disabling GPU

### ISSUE THREAD

**Issue by nikolaydyankov** [colmap/colmap#469]
With the following settings I'm getting this error:

`WARNING: Skipping dense reconstruction because CUDA is not available.`

- Low quality
- Dense model - ON
- Sparse model - OFF
- GPU - OFF
- rest defaults

I'm confused because the program is complaining about CUDA, even though I disabled the GPU option. Is this a bug, or there's simply no way to generate dense model on CPU?

**Comment by ahojnnes** [comment]
Dense reconstruction requires CUDA.
