### ISSUE TITLE
"feature extraction"  has  a  problem

### ISSUE THREAD

**Issue by Beannn** [colmap/colmap#47]
when  I   make Feature extraction， I  select  cpu， then I  click the  extract, the program will  be  stopped.I don't know why,can you give me some advice?

**Comment by ahojnnes** [comment]
@Beannn Please, provide some more details on your system (OS, CPU, GPU, etc.).

**Comment by ahojnnes** [comment]
Closing this issue for now. Feel free to reopen with additional details or questions.
