### ISSUE TITLE
make install missing FLANN/flann.hpp file

### ISSUE THREAD

**Issue by zw-ruan** [colmap/colmap#470]
Hi, 

I installed colmap as a library, but when I do something like this:
```c++
#include "colmap/retrieval/visual_index.h"

using namespace colmap;

int main(int argc, char** argv) {
retrieval::VisualIndex<> visual_index;
...
}
```
The compiler complains that can not find FLANN/flann.hpp.  The CMakeLists.txt in the colmap , has the following snippet：
```cmake
install(DIRECTORY lib/
        DESTINATION include/colmap/lib
        FILES_MATCHING PATTERN "*.h")
```
Is it necessary to add one more pattern to inlcude the *.hpp files?

**Comment by ahojnnes** [comment]
Yes, this seems to be a bug. Thanks for reporting. If you want, you could submit a pull request with a bug fix, otherwise I will fix it once I am back from my travel.

**Comment by ahojnnes** [comment]
Should be fixed. Again, thanks for the bug report.
