### ISSUE TITLE
two bugs in export_to_bundler.py

### ISSUE THREAD

**Issue by bbzh** [colmap/colmap#477]
Hi,
 keypoints = np.fromstring(row[0], dtype=np.float32).reshape(-1, 4)
(1) This line gives error like "ValueError: cannot reshape array of size 14730 into shape (4) ". I check that keypoints always have 6 cols. Changing 4 to 6 works.
(2) When the images has no keypoints (which happens when the image is distoryed), it gives the error:
TypeError: fromstring() argument 1 must be string or read-only buffer, not None.
Can you confirm these?

**Comment by ahojnnes** [comment]
Thanks, should be fixed now.
