### ISSUE TITLE
timing for the results in the paper

### ISSUE THREAD

**Issue by bbzh** [colmap/colmap#478]
Hi Johannes,

I am trying to run Colmap in Internet dataset as you did in Table.1 of "Structure from motion revisited". I think the timings you reported there is only the mapper step, not including the feature extraction and matching times. I find the matching is quite slow, e.g. 2000 images may take one whole day in a GTX 960M GPU, even though vocabulary tree is used to match against only 100 images using plain SIFT in default setting.
Can you roughly elaborate how much time you need to do the matching ans suggest how to speed up? 
Thanks!

**Comment by ahojnnes** [comment]
The timings only include the mapping step and note that the parameters and the code used to produce the reconstructions in the paper are different from the current code in the repository. You will likely obtain more complete/accurate reconstructions but at slower run times. You can speed up the matching with a better CPU/GPU or multiple CPUs/GPUs or by decreasing the number of extracted features. The 960M is comparatively quite slow.

**Comment by bbzh** [comment]
Could you roughly estimate the time needed for this dataset so that I can have an idea what is a reasonable time? Just use the latest version with plain SIFT in default setting. Thanks!

**Comment by ahojnnes** [comment]
I don’t know how fast the 960M is in practice and I don’t know your settings. Typically, you can linearly extrapolate the timing from matching one/few image to multiple images in the exhaustive/vocabtree matchers.
