### ISSUE TITLE
colmap failed on ICL-NUIM dataset

### ISSUE THREAD

**Issue by jyiyang** [colmap/colmap#479]
**Problem Description**

Trying to run colmap on [ICL-NUIM](https://www.doc.ic.ac.uk/~ahanda/VaFRIC/iclnuim.html) dataset, but seem to fail on the lr_kt1 and the lr_kt3 sequence. Many registered camera poses are wrong, and dense reconstruction fails with no good initial pairs of images. I have tried down-sampling the frame to 1/4 or 1/10 of its original number of frames, but with no luck. Also tried both exhaustive and sequential matching with loop closure detection turned on, but also not working. Have fixed intrinsic camera parameters as: fx:481.2, fy:480, cx: 319.5, cy: 239.5. Since colmap does not seem to work with negative intrinsics, I change the original fy from -480 to 480. 

**Screenshots**
![exp](https://user-images.githubusercontent.com/8824979/45261968-9fcc2a00-b3da-11e8-801a-0a84c02af2e2.png)
This is a screenshot on the result on lr_kt3 dataset, where there is a loop for camera motion.

I am wondering if the lack of scene texture has caused this problem. Would you mind offering some suggestions or comments?

**Comment by ahojnnes** [comment]
I haven’t tried to reconstruct this dataset yet, but I will try to have a look over the next days.
