### ISSUE TITLE
How to make Colmap work on a AWS instance?

### ISSUE THREAD

**Issue by gesong1982** [colmap/colmap#48]
Hi @ahojnnes
Thank you for providing the open source, really appreciate it.
I face the problem when I try to run COLMAP command line on AWS instance. 

SYSTEM: ubuntu 16.04 
GPU: NVIDIA Tesla K80
NVIDIA driver: nvidia-375.20 
CUDA: 8.0
X-server 

Feature_extractor cloud pass with the error message: 
QXcbConnection: XCB error: 148 (Unknown), sequence: 178, resource id: 0, major code: 140 (Unknown), minor code: 20

exhaustive_matcher does not work with error (assgin the GPU index: "--MatchOptions.gpu_index", "0"):
Matching block [1/1, 1/1]

MultiplyDescriptor:	invalid device function

*** Aborted at 1480548746 (unix time) try "date -d @1480548" if you are using GNU date ***
PC: @ 0x7999db SiftMatchCU::GetBestMatch()
*** SIGSEGV (@0x7f050dc24930) received by PID 4479 (TID 0x7f0417583700) from PID 230836528; stack trace: ***
@ 0x7f043b2403e0 (unknown)
@ 0x7999db SiftMatchCU::GetBestMatch()
@ 0x52506b colmap::MatchSiftFeaturesGPU()
@ 0x52ae94 colmap::SiftGPUFeatureMatcher::MatchImagePairs()
@ 0x52eb9f colmap::ExhaustiveFeatureMatcher::Run()
@ 0x5a67dc colmap::Thread::RunFunc()
@ 0x7f04386eac80 (unknown)
@ 0x7f043b23670a start_thread
@ 0x7f0437e5082d clone
@ 0x0 (unknown)

Could you please help with this? What these errors mean and how can I make the COLMAP work on headless AWS instance?

Thanks

**Comment by hheijnen** [comment]
I came across this error also. I didn't truly look at the root of this problem when I faced it, but if you'd like a quick fix; switch to CUDA 7.5 and rebuild COLMAP.

**Comment by gesong1982** [comment]
@hheijnen 
Thanks for your information. I will try it.

**Comment by davidmarianovak** [comment]
We had the same problem with a nVidia 1080 GPU. Try to add '--gpu-architecture compute_52' in the CUDA->CUDA_NVCC_FLAGS entry in cmake. This solved the feature-matching crash for us.

**Comment by gesong1982** [comment]
@davidmarianovak thank you for your suggestion. Follow your idea I could make the feature-mathcing work, but bundle-adjustment has problem. By replacing CUDA 8.0 with CUDA 7.5 like @hheijnen said, SFM part of COLMAP running no problem.

**Comment by ahojnnes** [comment]
Thanks to everyone for investigating this issue. It seems like, we should wait for CUDA version 8.1+ for Nvidia to fix some bugs as usual...

**Comment by ahojnnes** [comment]
Can you please retry with the latest commit and report back whether it works now? Thanks!

**Comment by ahojnnes** [comment]
This should be fixed now. Thanks everyone. Feel free to reopen if necessary!
