### ISSUE TITLE
The output of depth map is not what I expected

### ISSUE THREAD

**Issue by keishatsai** [colmap/colmap#480]
Hi,
I am new to Colmap. I have several images with different camera pose, intrinsic and extrinsic.
At first, I did feature extraction, matching, reconstruction.... then I did undistortion.

Following is what I got after depth stereo step.
Original Image:
![e78_o](https://user-images.githubusercontent.com/8175070/45275624-4d7d2d00-b4f0-11e8-958e-3ff2b55ab3f7.png)
Depth Map:
![e78_d](https://user-images.githubusercontent.com/8175070/45275626-5241e100-b4f0-11e8-8afe-844ba698e213.png)
Normal Map:
![e78_n](https://user-images.githubusercontent.com/8175070/45275633-566dfe80-b4f0-11e8-997c-02ba7160c297.png)

As you can see, the map have a lot of outliers(?). Apparently, it is not a proper depth map.
Can anyone tell me why this is happened?
Thank you.

**Comment by ahojnnes** [comment]
This is not the final result. You probably either look at the “photometric” result while there is also a “geometric” result. Or you disabled filtering manually. Most of the sly poxel should turn into black after filtering.

**Comment by keishatsai** [comment]
Thank you, @ahojnnes. It is photometric result indeed.
How to achieve geometric result since the program doesn't allow me to press?
![dense_depth_map](https://user-images.githubusercontent.com/8175070/45278552-38a89580-b500-11e8-8a02-5e9304fe0469.png)

**Comment by ahojnnes** [comment]
Click Stereo again.

**Comment by keishatsai** [comment]
Thank you. I will try it later.

**Comment by keishatsai** [comment]
@ahojnnes , thank you.
It seems work, but the project closed itself unexpectedly.
However, the work seems to be done after I reopened the project, I have no idea how it finally achieved.
![1_geo_depth](https://user-images.githubusercontent.com/8175070/45609561-14fac780-ba8b-11e8-8f64-4ff37cb0a837.png)

One last question, can I get to know the metric depth from COLMAP or how to transform the depth map into metric depth?
Thank you.

**Comment by ClaudioCimarelli** [comment]
@ahojnnes how is possible to read depth and normal maps in bin format?
I am not able to reload the project on windows, and there is apparently no option to import with the gui (or CLI) the single image like frameXXXX.jpg.geometric.bin

Thanks

**Comment by ahojnnes** [comment]
By metric depth you mean the distance in eg meters or centimeters? For this, you would have to scale the reconstruction first, eg using ground control points or a known distance in the world.

**Comment by ahojnnes** [comment]
If you don’t know, for example, the distance between some objects or the location of a few points in the scene, then you will not be able to perform “metric” measurements. Image based 3D reconstruction is always up to an arbitrary 3D similarity transformation without any prior scene knowledge.

**Comment by keishatsai** [comment]
Thank you, @ahojnnes.
Just one last question, if every depth map generated from COLMAP has different scale, how can I transform them into distance map (depth in meter)? Do I need to have the groundtruth map with meter for every image first? Or the depth map scale of every image from COLMAP are the same?

**Comment by ahojnnes** [comment]
Just find the scaling factor of the scene wrt to the metric world and then scale all the depth maps by that scaling factor.

**Comment by keishatsai** [comment]
I see. Thank you so much for the help.

**Comment by WiktorLigeza** [comment]
What would be a command for getting nice and sifted depth maps?

colmap automatic_reconstructor --image_path ./images --workspace_path . --quality medium
