### ISSUE TITLE
Poisson after Delaunay reconstruction: NX property missing in PLY

### ISSUE THREAD

**Issue by ClaudioCimarelli** [colmap/colmap#482]
Hello,

I read on your documentation that for the mesh reconstruction Delaunay is more robust to outliers with respect to Poisson, but it gives less smooth surface. 

In the same section of the FAQ: "Surface mesh reconstruction" you state that is possible to combine the two methods:

>Note that the two algorithms can also be combined by first running the Delaunay meshing to robustly filter outliers from the sparse or dense point cloud and then, in the second step, performing Poisson surface reconstruction to obtain a smooth surface.
>

So, I tried generating the Delaunay mesh .ply file and use that as an input file for the Poisson algorithm. Unfortunately, I receive the following error:

    [ERROR] Failed to find property in ply file: nx
    
So, the question is: how you meant to use Delaunay to improve Poisson results? 
If you have any reading resource to know more feel free to share, please.

Thanks for your help,
Claudio

**Comment by ahojnnes** [comment]
That's not built in at the moment. You could use Meshlab to compute normals for the mesh before running Poisson (which requires normals).

**Comment by ClaudioCimarelli** [comment]
> That's not built in at the moment.

Do you have any hint on what should I implement for that? I thought Poisson could be applied to point cloud, is not that right?

>  You could use Meshlab to compute normals for the mesh before running Poisson (which requires normals) 

Is not Colmap doing that already? In the Stereo fusion step you do calculate normals and depth maps, right?

Thanks again!

**Comment by ahojnnes** [comment]
The Delaunay mesher does not output normals for nodes in the mesh. What you could do alternatively is to filter points in the fuses result that are not close to the Delaunay mesh. Then you only run Poisson reconstruction on the filtered point cloud.

**Comment by ClaudioCimarelli** [comment]
Okay, I will try some alternatives. Thank you very much.
