### ISSUE TITLE
Internationalization of the COLMAP toolkit

### ISSUE THREAD

**Issue by json87** [colmap/colmap#483]
Thanks for providing the excellent toolkit for SfM. Recently, I have tried to translate the English UI into some other languages, such as Chinese Simplification, by using the internationalization feature of Qt. however, the test shows that the current UI framework does not work well with my tranlation file, as following,

		// install translator for Chinese Simplification.
		QTranslator qTranslator;
		if (qTranslator.load("language/ui.qm"))
			app.installTranslator(&qTranslator);

		MainWindow main_window(options);
		main_window.show();

Then, I wonder whether the current UI framework of the COLMAP supports the above-mentioned way for language translation.

**Comment by ahojnnes** [comment]
I never tried to translate COLMAP and have no experience with Qt and internationalization. I also didn’t program the GUI with translation in mind. I am sure there is detailed documentation for this on the Qt website, but I am not planning to integrate/maintain multiple languages in this repository.
