### ISSUE TITLE
Principal point variance

### ISSUE THREAD

**Issue by KevinCain** [colmap/colmap#485]
Here's a sample line from 'cameras.txt', showing principal point in bold:

> 1 SIMPLE_RADIAL 801 1200 938.299 **400.5 600** 0.0178674
> 2 SIMPLE_RADIAL 801 1200 934.559 **400.5 600** 0.0114291
> 3 SIMPLE_RADIAL 801 1200 934.456 **400.5 600** 0.00456024

The same cameras, after bundle adjustment:

> 1 SIMPLE_RADIAL 801 1200 923.144 **398.753 574.343** 0.0283349
> 2 SIMPLE_RADIAL 801 1200 920.359 **402.846 577.478** 0.0212726
> 3 SIMPLE_RADIAL 801 1200 918.351 **404.686 581.318** 0.0145342

Since these lines relate to images from the same camera with identical extrinsics, in a perfect world the computed principal point would, of course, be invariant.  The above variance in principal point over the cameras in the scene is within ~10 pixels, which is quite good in my experience, considering the difficulty of determining principal point from uncalibrated images.

Is a variance of this kind (~10 pixels for images with 1,200 pixels on the longest axis, or ~0.0083 as a ratio) considered reasonable?  That is, should we consider this a minor issue or is this variance in principal point position meaningful?

**Comment by ahojnnes** [comment]
It is hard for me to judge this without knowing all the details. If you know the intrinsics don’t change, why don’t you share them across the different images? Please have a look at the documentation at https://colmap.github.io/faq.html#share-intrinsics

**Comment by KevinCain** [comment]
Thanks for your reply; yes, I agree that it would help to calibrate the camera to begin, then insert the known camera intrinsics and appreciate the link which is characteristically clean, and clear.

I know that a strong research interest of yours is working with images in the wild, where we can't gather explicit calibration data.  Given that case, it seems that we have a few options when it comes to deducing the principal point.  For instance, we can iterate bundle adjustment to estimate the pp, then insert the mean from the resulting values to each participating camera we know has the same pp at capture.  Alternatively, we could keep the idealized pp values from the first bundle adjustment, consult some existing database if available for the value, or require Bouget-style camera calibration before.

I'll do a bit of comparison and check back if I learn anything interesting.  Thanks again.
