### ISSUE TITLE
Issue with merged background and face

### ISSUE THREAD

**Issue by FelipeCrispim** [colmap/colmap#488]
Hi, I have faced some problems when I'm reconstructing people's face. Basically, when I make dense reconstruct, the program keeps parts of the background connected to the faces. I'm sending some attached examples.
I'd like to know if it's possible to fix that by adjustment from some params, something like threshold or similar thing...

![untitled](https://user-images.githubusercontent.com/4063852/46305536-1f878780-c588-11e8-973c-e543a03b9a38.png)
![untitled3](https://user-images.githubusercontent.com/4063852/46305545-257d6880-c588-11e8-92d4-36cc87ac8f43.png)
![untitled2](https://user-images.githubusercontent.com/4063852/46305550-2910ef80-c588-11e8-9a3f-78bbdf6b5558.png)

Thanks in advance.

**Comment by ahojnnes** [comment]
This is a known issue and is caused by big patch match window sizes. You could reduce the effect by reducing the patch match window radius but this will increase other problems. Another options would be to segment the background and filter the depth maps according to that segmentation.
