### ISSUE TITLE
Specify patch match problems to process in PatchMatchController?

### ISSUE THREAD

**Issue by apbodnar** [colmap/colmap#489]
While COLMAP is great at utilizing multi-GPU system configurations, there are only so many PCIe slots/lanes available on a single machine, which limits the scalability of a single reconstruction.

I'm writing a service to distribute very large reconstructions across many machines, which requires performing depth map calculation on multiple machines.

It seems that specifying the indices for patch match problem configurations to process is the easiest way to achieve this.  Is there an existing/better way of partially processing a list of problem configurations in the `PatchMatchController`?

**Comment by ahojnnes** [comment]
Specifying different problems in the configuration file is the way to go. There will just be a slight overhead in terms of loading the sparse reconstruction / images from disk, so it is advisable not to run just a single image as one job on each node on a cluster.

**Comment by apbodnar** [comment]
Great, I'll investigate doing what you suggested. Thanks
