### ISSUE TITLE
is it possible to adjust the skew parameter in camera intrinsic

### ISSUE THREAD

**Issue by Kai-46** [colmap/colmap#490]
Hi all,

I've noticed that the camera models supported by colmap set the skew parameter to be zero by default. However, I'm having a camera with a big skew in hand, so I'm wondering if it's possible to add this value to the camera model. Thanks in advance.

**Comment by ahojnnes** [comment]
It is possible to model skew. You would have to create a new camera model for this and add it as a new parameter.

**Comment by Kai-46** [comment]
Thanks @ahojnnes. Can you please give some hint about how to implement the new camera model in colmap?

**Comment by ahojnnes** [comment]
Have a look at ``colmap/src/base/camera_models.h``. Everything should be documented there.

**Comment by ahojnnes** [comment]
Let me know if there are any further specific questions. Closing this as resolved in the meantime.
