### ISSUE TITLE
How to use colmap for 3D reconstruction when all the camera parameters (both intrinsic and extrinsic) are known?

### ISSUE THREAD

**Issue by Kai-46** [colmap/colmap#491]
Hi all, 

I've been having some trouble using colmap to do 3D reconstruction. In my case, I have a couple of images of the same scene at different view angles, and **the camera intrinsic and extrinsic for each image is already known to me; each image has its own intrinsic.** My goal is to use colmap to do feature extraction and matching, then triangulation, and then followed by a global bundle adjustment step, and finally PMVS.

I understand that colmap was mostly designed for SfM purpose; but I feel like it should be easily adapted to my case. Anyone has any suggestions how to do it? I'm a little bit confused by the section in FAQ 'Reconstruct sparse/dense model from known camera poses'; especially it did not explain clearly how to specify the type of the camera model, and input the known camera parameters, so that the feature_extractor and exhaustive_matcher can use the camera parameters.  

Thanks in advance.

**Comment by robertguetzkow** [comment]
I might be mistaken, but you should be able to configure the parameters in the "Database management" menu.

**Comment by ahojnnes** [comment]
The database is the right place to provide the feature extractor and matchers with the intrinsic/extrinsic parameters. If your problem is how to specify the data in the format of the cameras.txt, images.txt, and points3D.txt, that is referred to in the FAQ under "Reconstruct sparse/dense model from known camera poses",  then have a look here: https://colmap.github.io/format.html

**Comment by NagabhushanSN95** [comment]
https://colmap.github.io/format.html doesn't provide what are the parameters and their order. For example, in my intrinsics, I have 3 parameters: focal length (normalized to [0,1] range) and principal points. How should I specify these parameters? Should I explicitly compute focal length in `x` and `y ` by multiplying with width and height respectively?
