### ISSUE TITLE
Use prior GPS in structure from motion to reduce drift

### ISSUE THREAD

**Issue by is03wlei** [colmap/colmap#493]
In my scenario. Reconstruction is based on street video. Prior GPS is necessary to regulate geometry.
Or it is easy to get broken models.

In openMVG, it uses similarity transform between model coordinates and GPS coordinates. And also optimize error between them. But it needs a parameter to combine re-projection error and GPS fitting error. Hope there is a better solution.

**Comment by ahojnnes** [comment]
There is no option to enforce GPS priors at the moment, but this should be easily possible by adding additional cost terms in the bundle adjustment and pre-aligning the reconstruction.

**Comment by shubham-monarch** [comment]
Could you please throw some more light on what do you mean by pre-aligning the construction?
