### ISSUE TITLE
Install-/ buildproblem under Fedora-Linux (wrong librarynames)

### ISSUE THREAD

**Issue by Nos-** [colmap/colmap#494]
**Description**
During installation of Colmap under Fedora Linux 28 I get an error message about missing dependencies (some libs). The required libs are already installed but have different names (instead of '_' are '-' used in the names).

**Expected behavior**
The install-/ buildscript should check for this.

**Comment by ahojnnes** [comment]
Can you post the specific output from the command line please? Thanks.

**Comment by ahojnnes** [comment]
Closing due to lack of feedback. Feel free to reopen at a later point.
