### ISSUE TITLE
Focal length by axis

### ISSUE THREAD

**Issue by KevinCain** [colmap/colmap#496]
I see that FocalLengthX, FocalLengthY is included in Colmap's camera class, but that Colmap doesn't set these, for any camera model.  That is, it seems that in all cases Colmap tests for and uses a single FocalLength value rather than two.

Is it true that Colmap always sets a single value for focal length, or am I missing something?

A final, related question:  what is the best (the most Colmap-native) way to access camera parameters while iterating through all images?  Currently I'm simply using a reference to the current image's camera, e.g.:
`auto& camera = cameras_.at(image.second.CameraId());`

**Comment by ahojnnes** [comment]
No, COLMAP supports multiple focal length values. It just depends on the camera model that you choose, please have a look at https://colmap.github.io/cameras.html and https://github.com/colmap/colmap/blob/dev/src/base/camera_models.h for more details. Your way of iterating over images/cameras seems like a good approach.
