### ISSUE TITLE
Provide known intrinsics

### ISSUE THREAD

**Issue by msieb1** [colmap/colmap#498]
Hello,

I instantiate a database. object and add all cameras with their respective IDs and intrinsics, as well as all images with the matched camera ID. However, once I start feature matching, COLMAP instantiates new intrinsics and does not use my provided intrinsics. Where do pass those options in within the command line interface?

**Comment by ahojnnes** [comment]
I suggest to first perform feature extraction and then modify the database with your intrinsics.

**Comment by ahojnnes** [comment]
Since there was no further follow up from your side, considering this as resolved. Feel free to reopen.

**Comment by dwangxxx** [comment]
> Since there was no further follow up from your side, considering this as resolved. Feel free to reopen.

Hello, I followed the mentioned steps. I first preform feature and then modify the database with my own intrinsics. But when the reconstruction is completed, the output intrinsics changed. Could you provide me more details? Thank you very much!

**Comment by taeyeop-lee** [comment]
@dwangxxx @ahojnnes I have a similar observation. Can you explain how did you solve this problem?
