### ISSUE TITLE
speed of matches_importer for raw matches

### ISSUE THREAD

**Issue by dymczykm** [colmap/colmap#499]
Hi @ahojnnes,

first of all, thanks for the great framework with thorough documentation, it comes very handy for large-scale 3D models and localization evaluation :) 

We are using colmap to evaluate a custom feature type. We are therefore importing both feature detections using ``feature_importer`` and raw feature matches using ``matches_importer``. This all works fine, but ``matches_importer`` feels somewhat slow (for 131k image pairs it takes around 20hrs). I understand this is because it has to solve the two-view geometry for each pair of frames. I wanted to ask:
* Are there any parameters we could tweak to save compute in this match import step? (obviously, we can also lower the number of image pairs, that's clear)
* ``matches_importer`` seems to be single-threaded, is that right? How much effort would it be to parallelize it?
* GPU is not used by ``matches_importer``, correct?

Thanks for your help!

Cheers,
Marcin

**Comment by ahojnnes** [comment]
Hi Marcin,

Glad to hear it’s useful for your problems!

The matches_importer is indeed not very fast. I recommend to write the raw matches directly into the COLMAP database using SQLite. This should be very fast. You can find an example in the scripts/python/database.py script or in my local feature evaluation benchmark repository: https://github.com/ahojnnes/local-feature-evaluation which should have some useful scripts for your task anyway. After writing the matches, you can verify the matches using the matches_importer again but this time you provide a list of image pairs that you also imported with your E.g. Python script. The matches_importer will automatically skip already computed raw matches in the database and only do geometric verification.

Hope that helps and let me know if you have questions.

**Comment by ahojnnes** [comment]
Considering this as resolved.

**Comment by dymczykm** [comment]
@ahojnnes just as a follow-up, it turned out that some of our matches were of low (random) quality. With more inliers, the two-view verification process is actually much faster.

Thanks for your help!
