### ISSUE TITLE
Cannot import custom features

### ISSUE THREAD

**Issue by meder411** [colmap/colmap#5]
Using the pre-built Windows binary, I am unable to load my custom features into the project. Regardless of the path entered, it gives a "Path is a not a directory" error on pressing "Extract." However, if I switch between the 'extract' and 'import' tabs and then try to press the "Extract" button, it begins to run, but then colmap stops responding and shuts down.

My images are in a dataset_root/images folder (e.g. dataset_root/images/_MG_9859.JPG).
My features are 4096 dimensional and formatted according to the documentation (x y scale orientation dim_1 ...dim_4096) and located in dataset_root/features (e.g. dataset_root/images/_MG_9859.JPG.txt).

![colmap](https://cloud.githubusercontent.com/assets/6818607/14930962/bd8eb046-0e35-11e6-86de-4f62286c1a40.png)

**Comment by ahojnnes** [comment]
Hi Marc,

Thanks for the report. The feature import is fixed now, but you would have to recompile yourself for now.

At this point, COLMAP only supports 128-dimensional features, since the matching is based on SiftGPU. To use 4096-dimensional features, do the matching yourself and write the `inlier_matches` to the database manually. Should be relatively easy to do. Let me know if you need help.

Cheers, Johannes

**Comment by meder411** [comment]
Hey Johannes,

Sounds good. Thanks for the quick repair. I was looking through the 'base' directory source code but couldn't find where it was restricted. Either way, I too figured that writing directly to the DB might circumvent the issue and am working on that now.

Thanks again!

Marc

**Comment by ahojnnes** [comment]
That requirement is imposed by SiftGPU, see `base/feature.h` and `base/feature_matching.h`. A CPU matcher could solve the problem, but for any non-standard feature type, it's not clear what distance metric to use anyway. So, it will be hard to generalize for features other than SURF/SIFT or binary features. I suggest to simply write to `inlier_matches` in the database.

**Comment by meder411** [comment]
That's what I thought. It might be worth adding functionality for users to provide their own matching function as well. Basically just have a user provide a function handle. This way people can use Colmap for evaluating different metrics for SfM. Perhaps for version 2.0...?

**Comment by ahojnnes** [comment]
Hi Marc, if you need this feature and want to contribute, I am happy to accept a PR. Otherwise, I'll be closing this issue as fixed for now. Feel free to reopen if you disagree :-)
Cheers, Johannes

**Comment by MarcelloAgostini** [comment]
Hello Marc and Johannes,
I'm also interested in importing my own matching points. I'm making a comparison between different feature extraction/matching algorithms, show how the SFM results can differ using SIFT, SURF and others from Opencv.
How did you manage to write the inlier_matches in the database? My matching points are structured as the following example.

      DJI1.jpg        DJI2.jpg       DJI3.jpg        DJI4.jpg        .............................  DJIn.jpg
id   x        y          x        y          x        y        x        y       .............................   x        y
0   1245  545     2000   745      -        -        3450  900     ............................   .          .
1   1404  304     3012   546    4014   890      -        -       ..............................   .          .
2   1305  2004       -       -       2005  3405   3003 4568   ..............................   .          .
3   1405  4005   4013  3005      -        -         -        -       ............................    .          .
4    4501 3210      -        -       4012 3503    5003  4560  ............................    .          .
.        .        .           .         .          .         .         .           .               .               .          .
.        .        .           .         .          .         .         .          .                 .              .          .    
n       .        .           .         .          .         .         .          .                .              .          .

Points with same id can be visible in multiple images, x and y are pixel coordinates.
Is it somehow feasible to fill in the database with these points and run the SFM?

Cheers, Marcello

**Comment by ahojnnes** [comment]
@MarcelloAgostini Please have a look here for an example on how to write matches to the database: https://github.com/colmap/colmap/blob/dev/scripts/python/database.py#L196 - other than that, there is also the ``matches_importer`` command, which allows you to import raw or inlier matches.

**Comment by MarcelloAgostini** [comment]
Thanks Johannes, I'll try these solutions.

**Comment by BrianG13** [comment]
@MarcelloAgostini Did u wrote any code to add the matches like you have?

Sorry for raising an old issue, but I am looking for a piece of code that adds manually the 2d keypoints matches between images.
Thanks!
