### ISSUE TITLE
similarity calculation for one image pair by using vocabulary tree

### ISSUE THREAD

**Issue by json87** [colmap/colmap#502]
thanks for providing the good toolset. the current version provides the ability to search the similarity images for any query image. however, I'm interesting to calcualting the visual similarity for one input image pairs. so, I wonder there is exsting tools to achieve it.  thanks!

**Comment by ahojnnes** [comment]
Considering this issue as resolved.

**Comment by json87** [comment]
Thanks for your advice. According to your suggestion, I have done some tests and some other issues can be found. When the number of database images used for indexing is at least two, the similairy score would be correct; otherwise, i.g., only one image indexed, the similarity score of one query image is zero, even though the same image is adopted for indexing and query images.

with one images used for indexing
![default](https://user-images.githubusercontent.com/17582213/47965813-bb744980-e086-11e8-9b52-bdfeac98f00e.png)

with two images used for indexing
![default](https://user-images.githubusercontent.com/17582213/47965803-9c75b780-e086-11e8-9ca5-6ce22d1f84c0.png)
