### ISSUE TITLE
Starting a new project in Colmap

### ISSUE THREAD

**Issue by estachew** [colmap/colmap#505]
I am following the step-by-step procedure shown in the YouTube tutorial to start a new project in Colmap: https://www.youtube.com/watch?v=P-EC0DzeVEU 

I downloaded Colmap-3.5 for Windows. After clicking File --> New Project, I create a name for a new database by clicking 'New' and I select the single folder with my images by clicking 'Select.' After I click 'Save', an error message displays "Invalid paths." It doesn't matter what I call the database, if the database is stored on the desktop, in a folder called colmap-demo with the images in a separate folder, in the folder with the Colmap program, etc. etc. or where the images are stored.

When I click the Run Tests application (which I imagine is some diagnostic tool), it displays "'C:\Users\EStachew\OneDrive' is not recognized as an internal or external command,
operable program or batch file."

For example, the file names displayed for Database and Images before I click 'Save' are:
Database: C:/Users/EStachew/OneDrive - Biohabitats, Inc/Desktop/colmap-demo/database.db
Images: C:/Users/EStachew/OneDrive - Biohabitats, Inc/Desktop/colmap-demo/images
The error message is displayed after I click 'Save.'

Thanks for any help any individual can provide. This seems really basic, but I can't even get past the first step! I am using a company laptop and I am not sure if that is the reason.

**Comment by ahojnnes** [comment]
Might be that there is a problem with the “,” in your path. Did you try somewhere else than your OneDrive folder?

**Comment by estachew** [comment]
Thanks - Yes I tried that and it worked. When I try Feature Extraction, the program keeps crashing, so I don't think I have a large enough graphics card to handle the program. I'll try another computer. Thanks!

**Comment by ahojnnes** [comment]
Alternatively you can use CPU based feature extraction/matching.

**Comment by estachew** [comment]
CPU based feature extraction/matching works. Thanks! I have a separate issue now which I will post.
