### ISSUE TITLE
what to do when error occors while running RUN_TESTS.bat ?

### ISSUE THREAD

**Issue by axel-seins** [colmap/colmap#508]
I downloaded  COLMAP-3.5-windows-no-cuda.zip and extracted.
After starting RUN_TESTS.bat I see the following in the cmd window:

[...]
> gl_FragColor = result;}
c:/users/joschonb/development/colmap/src/feature/sift_test.cc(212): error: in "TestExtractSiftFeaturesGPU": check CreateSiftGPUExtractor(SiftExtractionOptions(), &sift_gpu) has failed
c:/users/joschonb/development/colmap/src/feature/sift_test.cc(219): error: in "TestExtractSiftFeaturesGPU": check keypoints.size() == 24 has failed [0 != 24]
c:/users/joschonb/development/colmap/src/feature/sift_test.cc(230): error: in "TestExtractSiftFeaturesGPU": check descriptors.rows() == 24 has failed [0 != 24]
Compile Log
ERROR: 0:2: '' : syntax error: #version directive must occur in a shader before anything else
ERROR: 0:2: '' : illegal order of preprocessor directives 

[...]

I expected to see the tests passed, but obviously there were errors reported (in red letters, continuing).

Windows 10
Firefox
63.0.1

no crash, but running for hours now...

What can I do?

[2018-11-04 colmap test run with errors.txt](https://github.com/colmap/colmap/files/2545492/2018-11-04.colmap.test.run.with.errors.txt)

And I need to add one more expectation: If the zip file is named "COLMAP-3.5-windows-no-cuda.zip" then I expected it could run without CUDA. At least I am quite sure that my Dell XPS13 9350 cannot handle CUDA, so might this be the reason for abovementioned errors?

**Comment by ahojnnes** [comment]
What GPU do you have in your laptop?

**Comment by axel-seins** [comment]
GPU is Intel HD 520

**Comment by axel-seins** [comment]
with Thunderbolt-3 so I might need an eGPU :(
