### ISSUE TITLE
similarity calculation for one image pair by using vocabulary tree

### ISSUE THREAD

**Issue by json87** [colmap/colmap#509]
Thanks for your advice. According to your suggestion, I have done some tests and some other issues can be found. When the number of database images used for indexing is at least two, the similairy score would be correct; otherwise, i.g., only one image indexed, the similarity score of one query image is zero, even though the same image is adopted for indexing and query images.

with one images used for indexing
![default](https://user-images.githubusercontent.com/17582213/47985025-60d4ff00-e113-11e8-8a9d-9163e4865b3e.png)

with at least two images used for indexing
![default](https://user-images.githubusercontent.com/17582213/47985045-71857500-e113-11e8-9057-cf12fbdc380c.png)

**Comment by ahojnnes** [comment]
The score is computed using TF-IDF voting, so I think, this makes sense to me if the the database contains only one image, which is exactly the same as the query. If you want a different scoring, then you would have to modify the TF-IDF voting with something else.

**Comment by json87** [comment]
Yes, the score with value zero is caused by th TF-IDF weighting strategy when only one image is indexed in the vocabulary tree, because the IDF is always zero for log(dn / di) for all inverted files. thanks for your help.
