### ISSUE TITLE
feature_extraction can't read txt file

### ISSUE THREAD

**Issue by flm8620** [colmap/colmap#51]
`std::getline (istream& is, string& str, char delim);`
This function will not remove whitespace automatically, il will only discard it and wait you to call it again to read next word.

So, should add 
`header_line_stream >> std::ws;` before [this](https://github.com/colmap/colmap/blob/55fbe10ccc2de84c458b4cc7e9c940a6617be1b6/src/base/feature_extraction.cc#L828)

and add `feature_line_stream >> std::ws;` before all following std::getline

**Comment by ahojnnes** [comment]
Thanks for reporting this, should be fixed in: https://github.com/colmap/colmap/commit/c4c3852d06e421f47defdde5b59f4a9b6c6d6592
