### ISSUE TITLE
Issue for FeatureGeometry

### ISSUE THREAD

**Issue by Jchtaylor** [colmap/colmap#510]
Sorry to bother you. But I might have found a problem in your code, which I have different opinion. So I wonder if I have the chance to discuss with you about it.
      It is in function "TransformMatrixFromMatch" of src/retrieval/geometry.cc
     As we know, for scaled 2d-2d feature transformation, x2 = sRx1 + t, (s for scale), so t = x2-sRx1, but in your code, s is multiplied two times.
     1.T.leftCols<2>() *= scale;
     2. T.rightCols<1>() =
      Eigen::Vector2f(feature2.x, feature2.y) -
      scale * T.leftCols<2>() * Eigen::Vector2f(feature1.x, feature1.y);
     I am not sure whether  I am right.  I would really appreciate your sparing time on this. Thank you.

**Comment by ahojnnes** [comment]
Indeed, you are right. This was a bug in the code and is fixed in the latest commit in the master branch. Luckily this code was not used in any of the actual retrieval pipeline, so it shouldn't have any impact on the results. Thanks for your bug report!

**Comment by Jchtaylor** [comment]
You are welcome. Indeed it is not used currently.
