### ISSUE TITLE
terminate called without an active exception

### ISSUE THREAD

**Issue by erikstenborg** [colmap/colmap#511]
I get an error message that I don't quite understand when trying to run the patch_match_stereo. Any ideas for what might have gone wrong? 

I've tried dev-branch (6fd1fe055721b23c0548d1f1b72d554de662d9ea) and master (b7ce38ff276228b8aff7186f6abd99b463ede10d) with the same result. I'm suspecting some library to be messed up, but I don't really have a clue to which I should look into. I'm using Ubuntu 16.04, CUDA 10.0.

$ colmap patch_match_stereo --workspace_path ${workspace_path}/dense --workspace_format COLMAP --PatchMatchStereo.geom_consistency true --PatchMatchStereo.write_consistency_graph true
Reading workspace...
Reading configuration...
Configuration has 438 problems...
terminate called without an active exception
*** Aborted at 1541460535 (unix time) try "date -d @1541460535" if you are using GNU date ***
PC: @     0x7f74baf22428 gsignal
*** SIGABRT (@0x3e9000007ba) received by PID 1978 (TID 0x7f74b1236700) from PID 1978; stack trace: ***
    @     0x7f74baf224b0 (unknown)
    @     0x7f74baf22428 gsignal
    @     0x7f74baf2402a abort
    @     0x7f74bb86584d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f74bb8636b6 (unknown)
    @     0x7f74bb863701 std::terminate()
    @           0x804d7d colmap::ThreadPool::ThreadPool()
    @           0xd4aef5 colmap::mvs::PatchMatchController::Run()
    @           0x80464c colmap::Thread::RunFunc()
    @     0x7f74bb88ec80 (unknown)
    @     0x7f74be0656ba start_thread
    @     0x7f74baff441d clone
    @                0x0 (unknown)
Aborted (core dumped)
bash: fork: retry: No child processes

**Comment by erikstenborg** [comment]
After cleaning up libraries (had e.g. both CUDA 9.0 and 10.0 at the same time), I get a different message which makes some kind of sense: Check failed: width_ == bitmap_.Width() (1188 vs. 0) 

The true width of the images is 1188, so where does the 0 come from? Does it mean it fails to read either the images or the camera calibration file?

colmap patch_match_stereo --workspace_path ${workspace_path}/dense --workspace_format COLMAP --PatchMatchStereo.geom_consistency true --PatchMatchStereo.write_consistency_graph true
Reading workspace...
Reading configuration...
Configuration has 438 problems...

==============================================================================
Processing view 1 / 438
==============================================================================

Reading inputs...
F1107 08:37:02.840899  6053 image.cc:56] Check failed: width_ == bitmap_.Width() (1188 vs. 0) 
*** Check failure stack trace: ***
    @     0x7f809be305cd  google::LogMessage::Fail()
    @     0x7f809be32433  google::LogMessage::SendToLog()
    @     0x7f809be3015b  google::LogMessage::Flush()
    @     0x7f809be32e1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x713f54  colmap::mvs::Image::SetBitmap()
    @           0xd8b91a  colmap::mvs::PatchMatchController::ProcessProblem()
    @           0xd8e64c  std::_Function_handler<>::_M_invoke()
    @           0x6a55e9  std::__future_base::_State_baseV2::_M_do_set()
    @     0x7f809a93aa99  __pthread_once_slow
    @           0xd8edf2  _ZNSt17_Function_handlerIFvvEZN6colmap10ThreadPool7AddTaskIMNS1_3mvs20PatchMatchControllerEFvRKNS4_17PatchMatchOptionsEmEJPS5_RS6_RmEEESt6futureINSt9result_ofIFT_DpT0_EE4typeEEOSG_DpOSH_EUlvE_E9_M_invokeERKSt9_Any_data
    @           0x848cfc  colmap::ThreadPool::WorkerFunc()
    @     0x7f809815cc80  (unknown)
    @     0x7f809a9336ba  start_thread
    @     0x7f80978c241d  clone
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by ahojnnes** [comment]
Glad to hear the initial problem was resolved. Regarding the second issue, it seems like there is a problem with reading one of the images from disk. To debug this and find the image that causes problems, you can print out the value of ``GetBitmapPath(image_idx)`` in ``src/mvs/workspace.cc``, line 90. Otherwise, you could just see whether there is any broken image in your workspace_path.

**Comment by erikstenborg** [comment]
Thanks!
Turned out a few of the image files were missing, and the first one to be processed just happened to be one of them. When I knew which file it was looking for it was much easier to figure that out. :-)

**Comment by whubaichuan** [comment]
@erikstenborg It confused me.
When two folders named 'image' and 'images' in the workspace_path, I set the image_path to ./image and the colmap checks failed: width_ == bitmap_.Width() (1188 vs. 0).

But when I delete the folder 'images' and rename another folder from 'image' to 'images', the image _path is set to ./images at the same time. Fortunately, I made it.

But why?
