### ISSUE TITLE
Issue on vote_and_verify

### ISSUE THREAD

**Issue by Jchtaylor** [colmap/colmap#515]
In flie /src/retrieval/vote_and_verify.cc

#391, Code should be changed from
     ComputeInlier(tform, matches, options.max_transfer_error,
                        options.max_scale_error, &inlier_idxs); 
to
    ComputeInlier(local_tform, matches, options.max_transfer_error,
                        options.max_scale_error, &inlier_idxs);

I would really appreciate your sparing time on this. Thank you.

**Comment by ahojnnes** [comment]
Done and fixed in latest commit in dev branch. Thanks for the bug report.
