### ISSUE TITLE
fails to build from source on debian gnu/linux

### ISSUE THREAD

**Issue by alexmyczko** [colmap/colmap#524]
**Describe the bug**
Fails with this message:
done -- Found installed version of Eigen: /usr/lib/cmake/eigen3 CMake Error at /usr/lib/cmake/Ceres/CeresConfig.cmake:88 (message): Failed to find Ceres - Found Eigen dependency, but the version of Eigen found (3.3.5) does not exactly match the version of Eigen Ceres was compiled with (3.3.4). This can cause subtle bugs by triggering violations of the One Definition Rule. See the Wikipedia article http://en.wikipedia.org/wiki/One_Definition_Rule for more details Call Stack (most recent call first): /usr/lib/cmake/Ceres/CeresConfig.cmake:223 (ceres_report_not_found) CMakeLists.txt:87 (find_package)
>

**To Reproduce**
1. Grab source (3.5 or 3.6dev)
2. unpack
3. build

**Expected behavior**
Build without error

**Screenshots**
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908833
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913325

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux (sid/unstable)

**Comment by ahojnnes** [comment]
This seems to be caused by a mismatch in which version has been used to compile Ceres and what is installed on the system. This does not seem related to COLMAP.
