### ISSUE TITLE
intrinsic parameters

### ISSUE THREAD

**Issue by zyxrrr** [colmap/colmap#525]
Hello,
In Tutorial, I see "If an image has partial EXIF information, COLMAP tries to find the missing camera specifications in a large database of camera models automatically. "
Could you talk it in detail？Or suppose a focal length and refine it in BA?
Thanks!

**Comment by ahojnnes** [comment]
What do you mean by “talk in detail”. I also don’t understand the second part of you question.

**Comment by zyxrrr** [comment]
@ahojnnes 
I mean explain in detail how to get the intrinsic parameters, for example, the focal length.
The second part is first assume a focal length then optimize in BA, get focal length in this way.
Sorry, my English is not good.Thanks for reply!
