### ISSUE TITLE
What's the difference of sparse model in dense/sparse and sparse?

### ISSUE THREAD

**Issue by icyhearts** [colmap/colmap#526]
After 3d reconstruction with colmap, there are sparse/0/points3D.bin sparse/0/images.bin sparse/0/cameras.bin,  there are also dense/sparse/points3D.bin dense/sparse/images.bin dense/sparse/cameras.bin, would you please tell me what's the difference between points3D.bin,images.bin,cameras.bin in sparse/0 and in dense/sparse? Thanks.

**Comment by ahojnnes** [comment]
The one in dense has the parameters for the undistorted cameras and images. No change for the 3D points.

**Comment by eric-yyjau** [comment]
I found a mismatch of points and images from 'dense' folder. If I plot from 'dense/sparse/images.bin' on 'dense/images', the points couldn't match the image. However, if I plot 'dense/sparse/images.bin' on original images, it looks ok. Why is that?
![Uploading image.png…](mismatched points)
