### ISSUE TITLE
Multi GPU Vocab tree matcher corrupts SQLite database

### ISSUE THREAD

**Issue by Tezirg-Wrld3D** [colmap/colmap#527]
On a large dataset of ~25k images, after running Sift features extraction successfully and using the provided 1M words vocabulary tree. After ~100 Sift matches the SQLite database seems to get corrupted. `SQLite error [/home/ubuntu/colmap/src/base/database.cc, line 687]: database disk image is malformed` And then becomes unusable. 

The hardware where this occurs is an AWS p2.8x large instance with 8 K80 GPU
Here is the .ini configuration file used for `vocab_tree_matcher`: 
```
database_path=/home/ubuntu/data/database.db
[SiftMatching]
use_gpu=true
gpu_index=0,1,2,3,4,5,6,7
min_num_inliers=36
min_inlier_ratio=0.50
max_num_matches=32768
[VocabTreeMatching]
vocab_tree_path=/home/ubuntu/data/vocab_tree_1M.bin
```
And here is the .ini for `feature_extractor`:
```
database_path=/home/ubuntu/data/database.db
image_path=/home/ubuntu/data/images/
[SiftExtraction]
use_gpu=true
gpu_index=0,1,2,3,4,5,6,7
estimate_affine_shape=false
domain_size_pooling=false
max_num_features=8192
num_octaves=4
octave_resolution=3
```

Thanks for the good work

**Comment by ahojnnes** [comment]
Is the database stored on a network drive? I remember having troubles in the past with that. Is this a reproducible error or it just happened once?

**Comment by Tezirg-Wrld3D** [comment]
No, the database is on the local SSD, next to the images. It is reproducible, 100%. I also tried with the medium vocab_tree; same issue

**Comment by Tezirg-Wrld3D** [comment]
Hello, after checking with management that is possible. I have to share it privately and make sure it'll be deleted when this issue is closed. I'd be happy to send you a public s3 url if you contact me using my profile's email.

**Comment by trueprice** [comment]
@ahojnnes I've also run into this problem a few times, lately. I think the issue comes from other threads trying to [read from the database](https://github.com/colmap/colmap/blob/dev/src/feature/matching.cc#L110) while the matcher is [executing a transaction](https://github.com/colmap/colmap/blob/dev/src/feature/matching.cc#L756). Commenting out the transaction line seems to fix the problem. (At least, it worked for matching 8000 images.)

I think this is only an issue for the vocab tree matcher and loop detection; for methods like exhaustive feature matching that don't have other threads trying to access the database, the transaction could be placed [right before](https://github.com/colmap/colmap/blob/dev/src/feature/matching.cc#L906) the call to matcher_.Match().

**Comment by ahojnnes** [comment]
That makes sense. @trueprice Would you be able to setup a pull request with those changes? Thanks!

**Comment by ahojnnes** [comment]
@trueprice fixed the issue in the most recent commits on the dev branch.

**Comment by is03wlei** [comment]
I have also run into problem when using spatial feature matcher.
It reported "database disk image is malformed" on the following line.
https://github.com/colmap/colmap/blob/dev/src/base/database.cc#L448

**Comment by maher1337** [comment]
@ahojnnes This issue is still ocurring

**Comment by shankar-anantak** [comment]
```
I0819 20:29:11.205657 54135 pairing.cc:318] Matching image [135/872]
E0819 20:29:11.213613 54135 database.cc:749] SQLite error: database disk image is malformed
terminate called after throwing an instance of 'std::runtime_error'
  what():  [database.cc:749] SQLite error: database disk image is malformed
*** Aborted at 1724099351 (unix time) try "date -d @1724099351" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x3eb0000d372) received by PID 54130 (TID 0x7948d5583000) from PID 54130; stack trace: ***
    @     0x7948de66e046 (unknown)
    @     0x7948dc042520 (unknown)
    @     0x7948dc0969fc pthread_kill
    @     0x7948dc042476 raise
    @     0x7948dc0287f3 abort
    @     0x7948dc4a2b9e (unknown)
    @     0x7948dc4ae20c (unknown)
    @     0x7948dc4ae277 std::terminate()
    @     0x7948dc4ae4d8 __cxa_throw
    @     0x59ca366d998e colmap::SQLite3CallHelper()
    @     0x59ca366d05c1 colmap::Database::WriteMatches()
    @     0x59ca366d08c7 colmap::Database::WriteMatches()
    @     0x59ca36b67388 colmap::FeatureMatcherCache::WriteMatches()
    @     0x59ca36695b6f colmap::FeatureMatcherController::Match()
    @     0x59ca3668b628 colmap::(anonymous namespace)::GenericFeatureMatcher<>::Run()
    @     0x59ca36736516 colmap::Thread::RunFunc()
    @     0x7948dc4dc253 (unknown)
    @     0x7948dc094ac3 (unknown)
    @     0x7948dc126850 (unknown)
Aborted (core dumped)
```

Same issue

**Comment by DuVogel87** [comment]
Can someone help here? I still get the SQLite error with Colmap Version 3.12.1

https://github.com/colmap/glomap/issues/204#issuecomment-3171354302
