### ISSUE TITLE
The written project.ini can‘t be read

### ISSUE THREAD

**Issue by is03wlei** [colmap/colmap#531]
[BundleAdjustment]
...
function_tolerance=0
gradient_tolerance=0
parameter_tolerance=0
database_path=xxx
image_path=./

When I call OptionManager.Read(database_path) or ReRead(database_path), it reports the following error.

ERROR: Failed to parse options unrecognised option 'BundleAdjustment.database_path'.

database_path is incorrectly considered to be part of BundleAdjustment.

**Comment by ahojnnes** [comment]
Did you manually modify the project settings in any way or this was the output of File > save project?

**Comment by is03wlei** [comment]
It was generated by mapper.
database is top level keys. It should be written on top of the file according to write_ini.
But it was written on bottom here.

**Comment by is03wlei** [comment]
I think that is due to my old version of boost. Thanks.
