### ISSUE TITLE
Pre-compute patch match problems?

### ISSUE THREAD

**Issue by apbodnar** [colmap/colmap#532]
I'm working on distributing depth map computation to multiple machines. It's working fine by sending all undistorted images to each node and then creating (per your advice) a patch-match.cfg that specifies problems for a subset of the image set.  In the worst case this can lead to an egregious over-usage of bandwidth.  

It appears that the patch match problems are computed in `PatchMatchController::ReadProblems` right before depth maps are computed. I'd like to be able to generate a patch-match.cfg after sparse mapping + undistortion so that I can send only the images that are necessary for processing a given problem.

Is there an existing way of doing this?

Thanks

**Comment by ahojnnes** [comment]
No, you would have to write a little script that parses the config and splits the images into different subsets.
