### ISSUE TITLE
Disabling CUDA support (already dev branch)

### ISSUE THREAD

**Issue by cogitas3d** [colmap/colmap#533]
Hey there!

I install al dependencies and the "dev" branch of Colmap.
I used the `cmake` .. and `CC=/usr/bin/gcc-6 CXX=/usr/bin/g++-6 cmake ..` options to build, but in all attempts appear:

-- Disabling CUDA support

The pack "nvidia-cuda-dev" was already installed.

I'm trying to reconstruct dense point cloud but is not possible, because the .sh file use "stereo" option, and this call CUDA.

Can you help me with this? Thanks for the attention!

**Comment by ahojnnes** [comment]
I assume, CUDA could not be found. Which version of CUDA/Ubuntu are you using?

**Comment by cogitas3d** [comment]
Ubuntu 18.04 with CUDA 10.

**Comment by ahojnnes** [comment]
Have you tried installing the official CUDA package from NVidia rather than the one in the Ubuntu repositories?

**Comment by cogitas3d** [comment]
I tryied with the two. The Ubuntu pack and the nVidia.

**Comment by ahojnnes** [comment]
Did you somewhere overwrite CMAKE_PREFIX_PATH or other related variables? Did you try to start from a fresh build directory?

**Comment by cogitas3d** [comment]
I created a build directory. Have a way to inform where is the CUDA libs?

**Comment by cogitas3d** [comment]
Hi @ahojnnes !

I solve it reconstructing dense point cloud with openMVS:

![captura de tela de 2018-12-16 14-42-30](https://user-images.githubusercontent.com/2422483/50056820-e00d1800-0140-11e9-88be-b5d56a419455.png)

Thank you very much!

**Comment by alexmyczko** [comment]
adding these to cmake worked for me
`-DCUDA_SDK_ROOT_DIR=/usr/local/cuda-10.0 -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-10.0`

or via debian/rules
```
# with cuda-10-0
override_dh_auto_configure:
        dh_auto_configure -- -DCUDA_SDK_ROOT_DIR=/usr/local/cuda-10.0 -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-10.0
```

(use cuda-10-1 if you have that)

**Comment by longjiangmm** [comment]
> Hi @ahojnnes !
> 
> I solve it reconstructing dense point cloud with openMVS:
> 
> ![captura de tela de 2018-12-16 14-42-30](https://user-images.githubusercontent.com/2422483/50056820-e00d1800-0140-11e9-88be-b5d56a419455.png)
> 
> Thank you very much!

hi @cogitas3d 
What software is this? Is it a 3D model created by Colmap? How many images have I used? The feeling I have created now is very rough and cannot be used
