### ISSUE TITLE
Image coordinates in dense matcher

### ISSUE THREAD

**Issue by mcphatty** [colmap/colmap#534]
Hey,

first: Great work!

While trying to understand your dense code, I came upon something I do not understand. I do not know if it is a matter of understanding or an issue though, but it would be really kind if you could explain it to me.

You stated in another post that in Colmap the image coordinates are all aligned to the image  boundary, and not to the pixel centers (which would mean an origin at (0.5,0.5)). I could verify that, since you added an offset to the vlfeat features and not to the SiftGPU features (which should by default generate points in the „correct“ coordinate frame). To me it seems that inside camera alignment it should not matter how you define the origin, as long as you stay consistent.

So if you calibrate cameras using features in one coordinate frame, you should get a principal point in the same frame. In this case the frame aligned with the pixel borders.

But in the PatchMatch code on the other hand, you directly use integer image coordinates to warp the pixel via the homography into the other image. If you relate the pixel coordinate to your principal point, aren‘t they in different coordinate frames? In my opinion one should add 0.5 to the pixel coordinate (row,col) when generating the homography?

Thank you and kind regards,
Phil

**Comment by ahojnnes** [comment]
You are right by all your observations. However, note that in patch match, I use a specific coordinate addressing mode in the textures, where 0.5, 0.5 is the pixel center. Hope this clarifies the issue.

**Comment by mcphatty** [comment]
Thank you for your answer!

Hmmm...

With the view vector for an image position being generated like this:
vx = ( col  - ppx ) / fx
vy = ( row - ppy ) / fy
vz = 1

Here (col,row) are integer pixel coordinates, but (ppx,ppy) is measured to the image corner.
Shouldn't it be

vx = ( col  + 0.5 - ppx ) / fx
vy = ( row + 0.5 - ppy ) / fy
vz = 1

in order to have the same type of coordinate system _before_ the warp?

I'm not sure if the offset applied _after_ the warp in the texture access makes up for the missing offset in the homography, since the homography warp might distort that missing (0.5,0.5) substantially.

Excuse me if I'm totally off here.
