### ISSUE TITLE
qwindows.dll in windows no cuda version under platforms causing qwiundows errors

### ISSUE THREAD

**Issue by Darrencwood** [colmap/colmap#535]
qwindows.dll in subfolder \lib\platforms instead of \lib
colmat.bat script doesn't look in this folder so this .dll needs moving up one folder level to prevent errors when not using GPU.

COLMAP-dev-windows-no-cuda\lib\platforms\qwindows.dll move to 
COLMAP-dev-windows-no-cuda\lib\qwindows.dll

**Comment by ahojnnes** [comment]
Thanks for reporting the issue, but I am surprised by this. Are you sure you didnt modify the .bat script? What version of Windows and COLMAP are you on?
