### ISSUE TITLE
Rig bundle adjuster

### ISSUE THREAD

**Issue by davidmarianovak** [colmap/colmap#54]
I was wondering if the rig bundle adjuster works, and if so, if there's a manual for it? When I try to run it with: 

`rig_bundle_adjuster.exe --input_path ..\ --output_path ..\ --rig_config_path rig.json`

The whole thing crashes with the following error:

```
F1222 16:49:06.157029  6376 reconstruction.cc:1593] Check failed: file.is_open()
*** Check failure stack trace: ***
```

I took the instructions from the comments in colmap/src/exe/rig_bundle_adjuster.cc - but it seems that I am missing something.

**Comment by ahojnnes** [comment]
It should work, but there is no specific documentation for it. What are the contents of the `..\` folder?

**Comment by davidmarianovak** [comment]
The folder contains both image folders named `left1_image` and `right1_image` as well as the database file. Do I need to put anything else into it?

**Comment by ahojnnes** [comment]
The folder should contain `images.txt`, 'cameras.txt` and `points3D.txt`. In other words, the folder should contain an existing sparse reconstruction produced by the normal incremental reconstruction pipeline. The bundle adjuster then simply enforces the rig constraints in a final global bundle adjustment. Does that make sense?

**Comment by davidmarianovak** [comment]
Thanks for help (and happy new year :) ). It makes sense, although it is a bit tedious because you cannot define a project with only two cameras (either a new camera for each image or one camera for all) so you end up editing the file `images.txt` a lot.

**Comment by ahojnnes** [comment]
I don't understand your problem. Can you give an example why it is tedious?

**Comment by davidmarianovak** [comment]
I have a project which was acquired with two cameras. The images are in seperate folders `left1_image` and `right1_image`. When I extract features, I have to set, whether I want one camera for all images or an unique camera for each image (which then sets the according ID for each image). After the reconstruction process, I have to edit the `images.txt` to set a unique camera ID for all left / right images (which are then specified in the json-file). I suppose I could also do this with an sql-statement. 

Does it make sense what I'm saying? :) If not I can explain it further.

**Comment by ahojnnes** [comment]
I suggest to extract a unique camera per image. Then before feature matching and the reconstruction, open the database manager and select all the images in one folder and set the camera_id to one value. But I agree that it would be nice to have an option that sets the camera_id per sub-folder. I create a new issue for this: https://github.com/colmap/colmap/issues/59

Thanks and let me know if there are any other issues.

**Comment by davidmarianovak** [comment]
Cheers for all the help :) I've solved it by simply calling this sql-statement (with SQLiteStudio or similar):

```
UPDATE images
SET camera_id=2
WHERE name LIKE '%right%'
```

And `id=1` and `%left%` since I had the images in these folders.

**Comment by DimitrisKatsatos** [comment]
> Cheers for all the help :) I've solved it by simply calling this sql-statement (with SQLiteStudio or similar):
> 
> ```
> UPDATE images
> SET camera_id=2
> WHERE name LIKE '%right%'
> ```
> 
> And `id=1` and `%left%` since I had the images in these folders.

hey @davidmarianovak 
A bit late to the party, but after you modify the database with the above query, how were you able to run rig-bundle-adjuster without editing the images.txt file?
