### ISSUE TITLE
entry point not found

### ISSUE THREAD

**Issue by aombk** [colmap/colmap#543]
when i execute colmap.bat i get this error:

![colmap](https://user-images.githubusercontent.com/8765458/50375519-311c8080-0607-11e9-8865-4efc3ad3cd18.JPG)

i tried this on 3.6-dev.1 , 3.5, both cuda and no cuda versions
i have no idea what could be causing this

**Desktop (please complete the following information):**
 - OS: windows 10 64bit
 - Browser: firefox
 - Version: 64
i wonder, is the browser information useful?

**Comment by aombk** [comment]
hi, thanks. tried it but nothing changed

**Comment by aombk** [comment]
i downloaded the prebuilt windows binaries. no i dont have Qt installed, should i install it? i still cant understand what this error message means.

**Comment by ahojnnes** [comment]
No, you shouldn’t have to download Qt. But it seems it cannot find some symbols in the Qt library. How are you starting colmap? Through the batch script in the root folder?

**Comment by aombk** [comment]
yes i run COLMAP.bat
RUN_TESTS.bat is running ok, doesnt seem to return any errors

**Comment by ahojnnes** [comment]
That is quite strange. Not sure how to help at the moment. Did you try to search online for that specific error message?

**Comment by yoko3d** [comment]
Is it possible you have 2 GPUs? If so making a new system variable "CUDA_VISIBLE_DEVICES" and setting the value to 0 fixed it for me
![image](https://user-images.githubusercontent.com/11289588/184466736-ac7bc708-4157-4416-9340-9be112732105.png)

**Comment by cvachha** [comment]
I also had a similar issue and was able to fix it by copying the colmap.exe from the bin folder under the main colmap folder to the lib folder, and then changing the path variable to point to the lib folder under the main colmap folder. 
The issue seemed like the colmap.exe file could not find the required dlls which were located under the lib folder.

**Comment by tianhan-zhang** [comment]
> I also had a similar issue and was able to fix it by copying the colmap.exe from the bin folder under the main colmap folder to the lib folder, and then changing the path variable to point to the lib folder under the main colmap folder. The issue seemed like the colmap.exe file could not find the required dlls which were located under the lib folder.

THANKS!!!!! Copy colmap.exe file from bin to lib, and edit the colmap.bat file(change the path), it finally works!!!

**Comment by ChinaShrimp** [comment]
> I also had a similar issue and was able to fix it by copying the colmap.exe from the bin folder under the main colmap folder to the lib folder, and then changing the path variable to point to the lib folder under the main colmap folder. The issue seemed like the colmap.exe file could not find the required dlls which were located under the lib folder.

Really appreciate! It stopped me for two days, thanks again.

**Comment by GGuussss** [comment]
Hi 
I had the same issue, and solve it.
I had add colmap /bin and /lib in the environment PATH variable that was the mistake !
I change  the environment PATH variable to the folder where is colmap.bat

**Comment by ChiuJill** [comment]
i fixed this issus by enable "Run this programe as an administrator" in Properties

**Comment by xiuyueChan** [comment]
I had the same issues when I only add InstallFolder/COLMAP-3.8-windows-cuda/bin and InstallFolder/COLMAP-3.8-windows-cuda/lib two paths to the Environment Variables; And after i add InstallFolder/COLMAP-3.8-windows-cuda also to Environment Variables, it solved.
