### ISSUE TITLE
Build fails for Debug

### ISSUE THREAD

**Issue by rishi-rranjan** [colmap/colmap#547]
**Describe the bug**
Building with `--build_type Debug` fails. 

**To Reproduce**
Compile with `--build_type Debug`

**Expected behavior**
A debug version should compile but it fails. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: SDK 17763

**Smartphone (please complete the following information):**

**Additional context**
Opening this as a placeholder. I have fixed all the errors except following one. Once I fix this, I will upload the changes here. 

`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol dsyrk_ referenced in function "public: static void __cdecl ceres::internal::BLAS::SymmetricRankKUpdate(int,int,double const *,bool,double,double,double *)" (?SymmetricRankKUpdate@BLAS@internal@ceres@@SAXHHPEBN_NNNPEAN@Z)	colmap_exe	C:\sw\Temp\colmap\colmap\build\colmap\__build__\src\exe\ceres-debug.lib(blas.obj)	1	
`

**Comment by ahojnnes** [comment]
@rishi-rranjan Thanks, closing this in the meantime, but please add details for the fix.

**Comment by chris1248** [comment]
This has nothing to do with Cuda. I was able to reproduce this too.

**Comment by ishipachev** [comment]
Had the same problem. Wasn't able to solve. Seems like some problem with linking blas libraries on win10 for Debut build. Tried to copy libs to different folders, but didn't help.
