### ISSUE TITLE
RotationMatrixToEulerAngles

### ISSUE THREAD

**Issue by Jchtaylor** [colmap/colmap#550]
Excuse me, I have a question
In your codes, Euler angles from rotation matrix 
rx = atan2(-R(1,2), R(2,2))
ry = asin(R(0,2))
rz = atan2(-R(0, 1), R(0, 0))
But I see the other form from many other materials
rx = atan2(R(2,1) , R(2,2));
ry = atan2(-R(2,0), sy);
rz = atan2(R(1,0), R(0,0));

I don't know why  is it that

**Comment by ahojnnes** [comment]
Not sure where you got this from, but my guess is that this used a different coordinate axis convention or a different order in which rotations along the respective axes are applied.

**Comment by pknmax** [comment]
Is this one correct for RotationMatrixToEulerAngles:
rx = atan2(R(2,1) , R(2,2));
ry = atan2(-R(2,0), sy);
rz = atan2(R(1,0), R(0,0));
