### ISSUE TITLE
Why tvec.z() need to be small when finding initial pair ?

### ISSUE THREAD

**Issue by fishmarch** [colmap/colmap#551]
Excuse me, I have a question.
```
if (static_cast<int>(two_view_geometry.inlier_matches.size()) >=
          options.init_min_num_inliers &&
      std::abs(two_view_geometry.tvec.z()) < options.init_max_forward_motion &&
      two_view_geometry.tri_angle > DegToRad(options.init_min_tri_angle)) 
```
In the EstimateInitialTwoViewGeometry( ) function, we need to make sure the initial pair is good enough. The number of inliers can tell us whether the pose estimate is good. And the tri_ange tell us whether the 3D point is good. But **I wonder what tvec.z() works for**. Maybe the other two constraints are enough.

**Comment by ahojnnes** [comment]
To avoid pure forward motion cases, which are generally difficult to initialize from. Note that the camera coordinate system is oriented with the Z axis to the front with respect to the first camera. I ensure this in the essential matrix decomposition code.
