### ISSUE TITLE
Texture COLMAP's dense point cloud with openMVS or mvs-texturing

### ISSUE THREAD

**Issue by fishcu** [colmap/colmap#557]
**Is your feature request related to a problem? Please describe.**
COLMAP offers great dense point cloud output, but only simplistic texture generation.

**Describe the solution you'd like**
I would like to generate better textures using mvs-texturing, or maybe openMVS, from COLMAP's output dense point cloud.

**Describe alternatives you've considered**
If exporting the sparse model to openMVS, its dense point cloud is very noisy. As a general problem, the resulting texture map is very "shredded" and not most efficient (packed rectangles instead of UV-unwrapping).

Is there a possible interface combination that allows export of the dense point cloud, and import of the dense point cloud, meshing, and texturing in another software?
Related: #227, #157

**Comment by fishcu** [comment]
I realized that mvs-texturing can use NVM scene descriptions. I'll try to feed a converted one from colmap, plus the mesh colmap generates, into it to see if it works.

**Comment by fishcu** [comment]
I tried the above. While I got pretty far, it will always crash with an `std::bad_alloc`. Here's the last part of its output:
```
Reading PLY: 6437959 verts... 12863752 faces... done.
Warning: Zero-length normals detected: 1923 face normals, 1 vertex normals
Generating texture views: 
NVM: Loading file...
NVM: Number of views: 41
NVM: Number of features: 44140
        Loading 100%... done. (Took 34.286s)                                    
Building adjacency graph: 
        Adding edges 100%... done. (Took 22.497s)                               
	19289687 total edges.
View selection:
	Building BVH from 12863752 faces... done. (Took: 11618 ms)
        Calculating face qualities 100%... done. (Took 102.004s)                
        Postprocessing face infos 100%... done. (Took 1.085s)                   
	Maximum quality of a face within an image: 60.3781
	Clamping qualities to 1.75114 within normalization.
	Writing data cost file... done.
	Optimizing:
		Time[s]	Energy
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

I'm pretty sure I got the image paths correct, but I will need to check again.
I realize this is probably not a colmap issue -- unless the NVM it outputs is somehow not according to the standard. I will probably follow up on the mvs-texturing repo.

**Comment by ahojnnes** [comment]
The meshing in COLMAP is based on poisson meshing. Not sure if it might produce zero length normals. Maybe you can parse through the mesh file and patch any of the zero length normals?

**Comment by fishcu** [comment]
Thank you Johannes!
It turns out I was indeed running out of RAM for the above texturing process. I was able to do the texturing fine with `mvs-texturing` after increasing the swap size.

It's weird that I'm getting the "0 length normals" error, but it does not seem to cause further issue at this point. I can make a filtering script if it turns out to be an issue.

Could you explain the folder structure of the "dense" subfolder colmap creates when using automatic reconstruction?
- Does the "image" folder contain undistorted images? I'm guessing yes. :) 
- If yes, are the 2D feature coordinates and the camera intrinsics corrected to account for the undistortion? Speaking about the "dense/sparse/*.bin" files.
- Are there other differences between the "sparse" folder inside the "dense" folder and the one outside?

**Comment by ahojnnes** [comment]
dense/images are undistorted, dense/sparse is the undistorted sparse reconstruction with undistorted image observations and cameras.

**Comment by fishcu** [comment]
Great, thanks for confirmation!
Closing as the combo of colmap + mvs-texturing indeed seems straightforward. Thanks again!

**Comment by fishcu** [comment]
Hi @CanCanZeng 
I have not looked into meshing & texturing with openMVS only. The only straightforward way to use openMVS is to start at the sparse point cloud. For that I used `InterfaceCOLMAP`, exactly.
In my experiments, mvs-texturing gave better results anyway.

**Comment by CanCanZeng** [comment]
Thank you for your prompt replay @fishcu 
But I don't understand, which one do you choose to create the dense point cloud, colmap or openMVS? I found that the dense point cloud created by colmap is more clean, but the mesh it generates not so good, and openMVS has meshRefine module, so I want to use colmap's dense cloud and openMVS's mesh module. 
You mentioned mvs-texturing, their demo video is really appealing, also I will try it.

**Comment by fishcu** [comment]
I was not able to use colmap's dense point cloud in openMVS. Sparse only. I agree with your findings.

**Comment by 2d3** [comment]
Hello all! I also want to use the dense cloud of colmap to generate texture with openMVS. Has anyone managed to do so? Until now I can only use the sparse cloud (as .nvm by using colmaps modelconverter) to start the openMVS pipeline with densifyPointCloud. Is there a way to export colmaps dense-cloud so it can be used with openMVS? greets

**Comment by CanCanZeng** [comment]
@2d3 Do do find yet, I think the only way to do this is get all the information openMVS needs and write them to a nvm file or mvs file by yourself

**Comment by CanCanZeng** [comment]
Hi  @2d3 @fishcu , I find the right way to combine the dense result of COLMAP with openMVS, the solution is here: https://github.com/cdcseacave/openMVS/issues/360#issuecomment-463257412

**Comment by 2d3** [comment]
Hi @CanCanZeng, in the meantime i managed it by using COLMAPInterface of OpenMVS. It basically uses the COLMAP format. The only thing to do is converting the bin-files in the sparse folder to txt-files by using colmaps modelconverter. The rest is pretty straight forward. This pipeline (Colmaps dense model + meshing and texturing in openMVS) combines the best of both worlds and resolves the tradeoff of quality and time, at least for my purpose.

**Comment by oryxlynx** [comment]
For those who have the same issue as mine and in this topic to use dense point cloud of Colmap and then do the meshing in OpenMVS, 
To sum up for you, the function "InterfaceCOLMAP" is able to import the dense point cloud of Colmap and convert it to .mvs format
Method and command are the same as when you import and convert the sparse point cloud but after finish densifying.

The main difference is that after you finish the densify, fuse.ply and fuse.ply.vis (output of densifying) will be created. The function will automatically check and do its work
if there is no fuse.ply and fuse.ply.vis , it will import and convert out the sparse points
However, if there are fuse.ply and fuse.ply.vis , it will import and convert out the dense points

Thank you all contributors of Colmap and OpenMVS


I have quote the reply of cdcseacave here
> 
> 
> after COLMAP undistorts the images, it saves a new scene with PINHOLE cameras, you have to use that one instead
> 
> InterfaceCOLMAP is already able to import dense point cloud from COLMAP, exactly the same way as you do it for sparse, but once the dense one computed and saved

Relate issues
https://github.com/cdcseacave/openMVS/issues/360
https://github.com/colmap/colmap/issues/557

**Comment by KunB-Fighting** [comment]
> Thank you Johannes!
> It turns out I was indeed running out of RAM for the above texturing process. I was able to do the texturing fine with `mvs-texturing` after increasing the swap size.
> 
> It's weird that I'm getting the "0 length normals" error, but it does not seem to cause further issue at this point. I can make a filtering script if it turns out to be an issue.
> 
> Could you explain the folder structure of the "dense" subfolder colmap creates when using automatic reconstruction?
> 
> * Does the "image" folder contain undistorted images? I'm guessing yes. :)
> * If yes, are the 2D feature coordinates and the camera intrinsics corrected to account for the undistortion? Speaking about the "dense/sparse/*.bin" files.
> * Are there other differences between the "sparse" folder inside the "dense" folder and the one outside?

So could you please tell me how to use mvs-texturing with the dense pointcloud output by colmap? The instruction of mvs-texturing is really confusing

**Comment by GraphOpti** [comment]
Follow the bash blow, config the $working_folder and $colmap_bin_path. It will use colmap for sparse modling and openmvs for texture model(obj file).


```
#!/bin/bash
working_folder=..../
images_folder=$working_folder/images
database_folder=$working_folder/database.db
output_folder=$working_folder/sparse/
colmap_bin_path=...../openMVS/build/bin
use_gpu=1
mkdir -p $output_folder
mkdir -p $output_folder/0
echo ">>>>>>>>>>>>>>Starting colmap feature extraction"
colmap feature_extractor \
--SiftExtraction.use_gpu $use_gpu \
--ImageReader.camera_model OPENCV \
--database_path $database_folder \
--image_path $images_folder \
echo ">>>>>>>>>>>>>>Starting colmap exhaustive matching"
colmap exhaustive_matcher \
--SiftMatching.use_gpu $use_gpu \
--database_path $database_folder \
echo ">>>>>>>>>>>>>>Starting colmap mapping"
colmap mapper \
--database_path $database_folder \
--image_path $images_folder \
--output_path $output_folder \
echo "image undistort"
sudo colmap image_undistorter \
--image_path $images_folder \
--input_path $output_folder/0 \
--output_path $working_folder/dense \
--output_type COLMAP \
echo ">>>>>>>>>>>>>>Start colmap model_converter"
colmap model_converter \
--input_path $working_folder/dense/sparse \
--output_path $working_folder/dense/sparse \
--output_type TXT
echo ">>>>>>>>>>>>>>Starting InterfaceCOLMAP"
echo $working_folder/dense
cd $colmap_bin_path
sudo ./InterfaceCOLMAP \
--working-folder $working_folder \
-i $working_folder/dense/ \
--output-file $working_folder/model_colmap.mvs \
echo ">>>>>>>>>>>>>>>Starting DensifyPointCloud"
echo $working_folder/model_colmap.mvs
cd $colmap_bin_path
sudo ./DensifyPointCloud \
--input-file $working_folder/model_colmap.mvs \
--working-folder $working_folder \
--output-file $working_folder/model_dense.mvs \
#--archive-type -1\
echo ">>>>>>>>>>>>>>>>Starting ReconstructMesh"
cd $colmap_bin_path
sudo ./ReconstructMesh \
--input-file $working_folder/model_dense.mvs \
--working-folder $working_folder \
--output-file $working_folder/model_dense_mesh.mvs
echo ">>>>>>>>>>>Refine mesh"
cd $colmap_bin_path
sudo ./RefineMesh \
--resolution-level 1 \
--input-file $working_folder/model_dense_mesh.mvs \
--working-folder $working_folder \
--output-file $working_folder/model_dense_mesh_refine.mvs
echo ">>>>>>>>>> Texture mesh"
sudo ./TextureMesh \
--export-type obj \
--output-file $working_folder/openmvs_model.obj \
--working-folder $working_folder/ \
--input-file $working_folder/model_dense_mesh_refine.mvs
echo "Finishing script. The final model is locate at"
echo $working_folder
echo "/model.obj"
```
