### ISSUE TITLE
problems reading tiff metadata

### ISSUE THREAD

**Issue by srs7** [colmap/colmap#558]
I am using images with tiff extension which have EXIF info. The images are processed (I can obtain a dense model) but I would like to use the EXIF focal length info and the GPS to run the spatial matcher. 

As an example, when I run the feature extractor this is what I obtain: 

`colmap feature_extractor --database_path database.db --image_path im`

==============================================================================
Feature extraction
==============================================================================

TIFFReadDirectory: Warning, Unknown field with tag 33918 (0x847e) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 37395 (0x9213) encountered.
TIFFFieldWithTag: Internal error, unknown tag 0x829a.
TIFFFieldWithTag: Internal error, unknown tag 0x829d.
TIFFFieldWithTag: Internal error, unknown tag 0x8822.
...
TIFFFieldWithTag: Internal error, unknown tag 0xa407.
TIFFFieldWithTag: Internal error, unknown tag 0xa420.
Processed file [1/1]
  Name:            imagen.tif
  Dimensions:      9000 x 6732
  Camera:          #1 - SIMPLE_RADIAL
  Focal Length:    10800.00px
  Features:        9337

Does colmap support reading EXIF with TIFF format? Any suggestion to been able to use the EXIF info?

Thank you in advance!

**Comment by ahojnnes** [comment]
I am using FreeImage to parse the EXIF data, etc. So, COLMAP can read whatever FreeImage supports. Not sure about your specific data format. I have not really worked with TIFF in the past.
