### ISSUE TITLE
Using fixed (pre-computed) camera poses for sparse/dense mapping

### ISSUE THREAD

**Issue by byungsoo-motion** [colmap/colmap#559]
Sorry if it is a redundant question, but I wasn't able to find it.

In my case, I have a separate VIO algorithm which produces pretty accurate camera poses, so I'm trying to use COLMAP just to get sparse/dense map with fixed camera poses.

While the instruction (https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses) explains how to do it, I have some missing points. Here's what I've done:

1. (SUCCESS) `colmap feature_extractor --database_path $PROJECT_PATH/database.db --image_path $PROJECT_PATH/images`
2. (SUCCESS) Used `scripts/python/database.py` to encode camera intrinsics and camera poses per image into the database.
3. (SUCCESS) `colmap exhaustive_matcher --database_path $PROJECT_PATH/database.db`
4. (???) 
```
colmap point_triangulator \
    --database_path $PROJECT_PATH/database.db \
    --image_path $PROJECT_PATH/images
    --input_path path/to/manually/created/sparse/model \
    --output_path path/to/triangulated/sparse/model
```
I got lost what is `path/to/manually/created/sparse/model`. Where am I supposed to get it through command line? Should I use GUI to get the sparse model?

**Comment by byungsoo-motion** [comment]
Updates : 

Now I tried ./colmap mapper to get the initial sparse model. (The dataset is supposed to close the loop at the end with 90 degree turns for corners)
![image](https://user-images.githubusercontent.com/28695105/51791978-2dc56900-2160-11e9-85b8-41627ab21dcc.png)

I further tried `./colmap point_triangulator`, but it doesn't help in terms of loop closure.

While the data is collected from the closed loop dataset and the camera poses are provided to `database.db` (which is double-checked through GUI), the results are not using the camera poses in the database, and seems like it still estimate the poses through BA.

Anything I'm missing to use fixed camera poses??

**Comment by ahojnnes** [comment]
For triangulation from existing camera poses, you must generate a cameras.bin/txt, images.bin/txt, points3D.bin/txt and not fill the values in the database. The pose values in the database are only used for the spatial_matcher. Let me know if things are not clear yet.

**Comment by CanCanZeng** [comment]
Hi @byungsoo-motion , I also trying to reconstruct from pre-computed camera poses, and I get it done from your guide. But I find that the output is not good, very few points are renconstructed in dense reconstruction stage, I don't know why. Maybe the pre-computed poses are not so precise, or I get some other mistakes. Below is the comparision of the dense output from COLMAP GUI with default parameters and from pre-computed poses.(It's a cluttered desk)
![screenshot from 2019-02-15 15-24-58](https://user-images.githubusercontent.com/26817559/52840974-e403e900-3135-11e9-91ec-6cccaa4b2fac.png)

Is it possible to use roughtly pre-computed poses but not fixed poses to do reconstruction? I think they are usefull because the pre-computed poses are roughtly right and without any outlier pose, thet resolve the ambiguity in many low textured or repeated scenes.

I have tried bundle adjustment after sparse reconstruction from fixed poses, but the scale of the result changes dramatically, it cannot be accepted, how to set parameters to make bundle adjustment change the poses slightly? @ahojnnes

**Comment by CanCanZeng** [comment]
The following is the comparision of the sparse model before and after bundle adjustment.  The red is before BA and yellow is after. They are  resemble each other and with largely the same direction but totally different scale(or translation).

![screenshot from 2019-02-15 17-06-06](https://user-images.githubusercontent.com/26817559/52846462-a3f83280-3144-11e9-88a6-dd99e6c27a30.png)

**Comment by ahojnnes** [comment]
@CanCanZeng First run the `point_triangulator` then run the `bundle_adjuster`. The scale of the scene shouldn't be changed using this sequence, but it will be changed if you run the `mapper`.

**Comment by CanCanZeng** [comment]
Yes, I did exactly what you said, and I repeated the result once again, also tested on another dataset. May be the  pre-computed pose is too bad? @ahojnnes

**Comment by CanCanZeng** [comment]
I use these steps to reconstruct:

# define path
```
database_path=/home/zcc/Dataset/SfM/TUM/rgbd_dataset_freiburg3_long_office_household_validation
image_path=/home/zcc/Dataset/SfM/TUM/rgbd_dataset_freiburg3_long_office_household_validation/images
model_path_precomputed=/home/zcc/Dataset/SfM/TUM/rgbd_dataset_freiburg3_long_office_household_validation/sparse
model_path_triangulated=/home/zcc/Dataset/SfM/TUM/rgbd_dataset_freiburg3_long_office_household_validation/triangulated
model_path_bundled=/home/zcc/Dataset/SfM/TUM/rgbd_dataset_freiburg3_long_office_household_validation/bundled
```

# reconstruct
```
colmap feature_extractor --database_path $database_path/database.db --image_path $image_path
colmap exhaustive_matcher --database_path $database_path/database.db
colmap point_triangulator --database_path $database_path/database.db --image_path $image_path --input_path $model_path_precomputed --output_path $model_path_triangulated
```
# BA
`colmap bundle_adjuster --input_path $model_path_triangulated --output_path $model_path_bundled
`
# convert
```
colmap model_converter --input_path $model_path_bundled --output_path $model_path_bundled/bundled.ply --output_type PLY 
colmap model_converter --input_path $model_path_triangulated --output_path $model_path_triangulated/triangulated.ply --output_type PLY 
```

I use the TUM rgbd_dataset_freiburg3_long_office_household_validation dataset and the pose is ground truth, the sparse result is :
![1341848235 103022](https://user-images.githubusercontent.com/26817559/52935046-3c83f200-3393-11e9-8030-6ee4404c1cd4.png)
![screenshot from 2019-02-18 15-36-52](https://user-images.githubusercontent.com/26817559/52935058-47d71d80-3393-11e9-9a1f-67f8175d92ee.png)


Obviously the result is right and almost acceptable. But after BA the result's scale still changed.
![screenshot from 2019-02-18 15-34-45](https://user-images.githubusercontent.com/26817559/52935032-3261f380-3393-11e9-8271-5d5a22b5b539.png)

**Comment by yuancaimaiyi** [comment]
> Hi @byungsoo-motion , I also trying to reconstruct from pre-computed camera poses, and I get it done from your guide. But I find that the output is not good, very few points are renconstructed in dense reconstruction stage, I don't know why. Maybe the pre-computed poses are not so precise, or I get some other mistakes. Below is the comparision of the dense output from COLMAP GUI with default parameters and from pre-computed poses.(It's a cluttered desk)
> ![screenshot from 2019-02-15 15-24-58](https://user-images.githubusercontent.com/26817559/52840974-e403e900-3135-11e9-91ec-6cccaa4b2fac.png)
> 
> Is it possible to use roughtly pre-computed poses but not fixed poses to do reconstruction? I think they are usefull because the pre-computed poses are roughtly right and without any outlier pose, thet resolve the ambiguity in many low textured or repeated scenes.
> 
> I have tried bundle adjustment after sparse reconstruction from fixed poses, but the scale of the result changes dramatically, it cannot be accepted, how to set parameters to make bundle adjustment change the poses slightly? @ahojnnes
Hello,sorry to bother you! I meat some problem with you,I use known camera poses reconstruction ,but the result loss many of points!!!!!,but the colmap directly result is very good! I am confused one weekend,can you solve it ,Looking forward to your early reply。 my weichat is yuancaimaiyi.wo can discuss about colmap and deeply learn it

**Comment by yuancaimaiyi** [comment]
> Hi @byungsoo-motion , I also trying to reconstruct from pre-computed camera poses, and I get it done from your guide. But I find that the output is not good, very few points are renconstructed in dense reconstruction stage, I don't know why. Maybe the pre-computed poses are not so precise, or I get some other mistakes. Below is the comparision of the dense output from COLMAP GUI with default parameters and from pre-computed poses.(It's a cluttered desk)
> ![screenshot from 2019-02-15 15-24-58](https://user-images.githubusercontent.com/26817559/52840974-e403e900-3135-11e9-91ec-6cccaa4b2fac.png)
> 
> Is it possible to use roughtly pre-computed poses but not fixed poses to do reconstruction? I think they are usefull because the pre-computed poses are roughtly right and without any outlier pose, thet resolve the ambiguity in many low textured or repeated scenes.
> 
> I have tried bundle adjustment after sparse reconstruction from fixed poses, but the scale of the result changes dramatically, it cannot be accepted, how to set parameters to make bundle adjustment change the poses slightly? @ahojnnes

Hello,sorry to bother you! I meat some problem with you,I use known camera poses reconstruction ,but the result loss many of points!!!!!,but the colmap directly result is very good! I am confused one weekend,can you solve it ,Looking forward to your early reply。 my weichat is yuancaimaiyi.wo can discuss about colmap and deeply learn it
my script:
DATASET_PATH=/traffic1_1/prior200
COLMAP=/root/colmap/build/src/exe/colmap
MIN_DEPTH=0
MAX_DEPTH=20
GPU_IDX=0
if [ ! -d $DATASET_PATH/dense1 ]
then
    mkdir $DATASET_PATH/dense1
fi

if [ ! -d $DATASET_PATH/sparse ]
then
    mkdir $DATASET_PATH/sparse
fi

$COLMAP feature_extractor \
    --database_path $DATASET_PATH/database.db \
    --image_path $DATASET_PATH/image \
    --SiftExtraction.estimate_affine_shape 1 \
    --SiftExtraction.domain_size_pooling 1 \
    --SiftExtraction.gpu_index $GPU_IDX
$COLMAP sequential_matcher \
    --database_path $DATASET_PATH/database.db \
    --SiftMatching.max_error 10 \
    --SiftMatching.max_distance  1.0 \
    --SiftMatching.max_ratio 0.9 \
    --SequentialMatching.overlap 10 \
    --SiftMatching.guided_matching 1
python $DATASET_PATH/qt_to_eu.py \
    --database_path $DATASET_PATH/database.db \
    --vslamFile $DATASET_PATH/L1_clock_outer_alone_test_pn.pn \
    --output_path $DATASET_PATH/model 

$COLMAP point_triangulator \
    --database_path $DATASET_PATH/database.db \
    --image_path  $DATASET_PATH/image \
    --input_path $DATASET_PATH/model \
    --output_path $DATASET_PATH/sparse
$COLMAP image_undistorter --image_path $DATASET_PATH/image \
    --input_path $DATASET_PATH/sparse \
    --output_path $DATASET_PATH/dense1 \
    --output_type COLMAP \
    --max_image_size 2000
$COLMAP patch_match_stereo \
    --workspace_path $DATASET_PATH/dense1 \
    --workspace_format COLMAP \
    --PatchMatchStereo.geom_consistency true \
    --PatchMatchStereo.gpu_index $GPU_IDX \
    #--PatchMatchStereo.depth_min 0 \
    #--PatchMatchStereo.depth_max 20 \
    --PatchMatchStereo.filter_min_ncc 0.01

$COLMAP stereo_fusion \
    --workspace_path $DATASET_PATH/dense1 \
    --workspace_format COLMAP \
    --input_type geometric \
    --output_path $DATASET_PATH/dense1/fused.ply
$DATASET_PATH/model  is know pose!

**Comment by yuancaimaiyi** [comment]
> Hi @byungsoo-motion , I also trying to reconstruct from pre-computed camera poses, and I get it done from your guide. But I find that the output is not good, very few points are renconstructed in dense reconstruction stage, I don't know why. Maybe the pre-computed poses are not so precise, or I get some other mistakes. Below is the comparision of the dense output from COLMAP GUI with default parameters and from pre-computed poses.(It's a cluttered desk)
> ![screenshot from 2019-02-15 15-24-58](https://user-images.githubusercontent.com/26817559/52840974-e403e900-3135-11e9-91ec-6cccaa4b2fac.png)
> 
> Is it possible to use roughtly pre-computed poses but not fixed poses to do reconstruction? I think they are usefull because the pre-computed poses are roughtly right and without any outlier pose, thet resolve the ambiguity in many low textured or repeated scenes.
> 
> I have tried bundle adjustment after sparse reconstruction from fixed poses, but the scale of the result changes dramatically, it cannot be accepted, how to set parameters to make bundle adjustment change the poses slightly? @aho
