### ISSUE TITLE
Full body reconstruction

### ISSUE THREAD

**Issue by 2d3** [colmap/colmap#560]
Hi! I want to create 3d models of humans. I have 80 images with 8 MegaPixel each. The camera-positions are fixed. I struggle with the settings. The final meshes always have a lot background (surrounding) structures and false detections between cameras and the actual object. I managed to get rid of most of that unwanted structure by tweaking the parameters but at the same time loosing important information of the actual object. I either have to implement background-subtraction in preprocessing or do a lot of cleaning up afterwards. The best of course would be a parameter setting, that helps reducing or minimizing the problem.  Has anyone experience in full body scans and or parameter-settings? Is there a deeper documentation on the parameters and their usage, meaning?
Thx for reply!

**Comment by ahojnnes** [comment]
There is nothing built in but I suggest to perform your own background subtraction in the original images. Then apply this background mask to the depth and normal maps before running fusion. The depth and normal map format is documented in the online documentation.
