### ISSUE TITLE
Reconstruction SetUp failed when starting mapper from image_list and existing model

### ISSUE THREAD

**Issue by is03wlei** [colmap/colmap#562]
**Describe the bug**
Only images from image_list are loaded into scene graph.
https://github.com/colmap/colmap/blob/dev/src/base/database_cache.cc#L121
https://github.com/colmap/colmap/blob/dev/src/base/database_cache.cc#L181

But all registered images from existing model are accessed.
https://github.com/colmap/colmap/blob/dev/src/base/reconstruction.cc#L1881
https://github.com/colmap/colmap/blob/d3a29e203ab69e91eda938d6e56e1c7339d62a99/src/base/correspondence_graph.h#L200

```
bool CorrespondenceGraph::HasCorrespondences(
    const image_t image_id, const point2D_t point2D_idx) const {
  return !images_.at(image_id).corrs.at(point2D_idx).empty();
}
```
Finally crashed at corrs.at(point2D_idx).

**To Reproduce**
colmap mapper --database_path ./database.db --image_list_path ./new_images.txt --input_path ./sparse/0 --image_path / --output_path ./new_sparse

==============================================================================
Loading database
==============================================================================

Loading cameras... 2 in 0.001s
Loading matches... 58195 in 0.378s
Loading images... 3038 in 0.352s (connected 252)
Building correspondence graph... in 0.286s (ignored 55134)

Elapsed time: 0.017 [minutes]

terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
*** Aborted at 1548728202 (unix time) try "date -d @1548728202" if you are using GNU date ***
PC: @     0x7f56bbd741f7 __GI_raise
*** SIGABRT (@0x3e900000fef) received by PID 4079 (TID 0x7f56b60ec700) from PID 4079; stack trace: ***
    @     0x7f56bdbd45e0 (unknown)
    @     0x7f56bbd741f7 __GI_raise
    @     0x7f56bbd758e8 __GI_abort
    @     0x7f56bc67aac5 (unknown)
    @     0x7f56bc678a36 (unknown)
    @     0x7f56bc678a63 (unknown)
    @     0x7f56bc6cf345 (unknown)
    @     0x7f56bdbcce25 start_thread
    @     0x7f56bbe3734d __clone
Aborted (core dumped)

**Comment by ahojnnes** [comment]
This should be fixed now. Checkout the latest commit in the dev branch.
