### ISSUE TITLE
Why doesn't focal length change after images are undistorted and resized?

### ISSUE THREAD

**Issue by FlakPacket** [colmap/colmap#564]
I am running the COLMAP reconstruction pipeline on a set of images, all of which were created with the same camera, using the `OPENCV` camera calibration model. The input images have size 1920x1080 pixels, and after I run the `colmap mapper` step, the camera calibration parameters output in `cameras.bin` look reasonable.

When I then run `colmap image_undistorter`, the images are transformed to a new size of 1962x1091 pixels (slightly larger). When I examine the images, I can see that small portions of the scene that were previously visible on the edges of the images are now cropped away, so the FOV has become slightly smaller than in the original photos. However, the camera focal length in the new `cameras.bin` file (now using `PINHOLE` model) is still exactly the same as it was before. The principal point (cx, cy) values have increased slightly, as I would expect them to due to the image resizing.

Why don't the focal length values change when the images are transformed and resized by the `image_undistorter` step, given that the resulting FOV is visibly different?

**Comment by ahojnnes** [comment]
COLMAP by default undistorted such that there are no black regions in the undistorted image. There are two ways to achieve this: changing the focal length or adjusting the image size. COLMAP uses the latter and in your case the images seem to have pincushion distortion, which causes the corners to be cropped. You can change the behavior by changing the “blank_pixels” parameter to 1.
