### ISSUE TITLE
Extend colmap like visual odometry

### ISSUE THREAD

**Issue by CanCanZeng** [colmap/colmap#568]
**Is your feature request related to a problem? Please describe.**
I find that for a video with many ambiguous scene and little texture, colmap may fail in reconstruction. Some picture are wrongly positioned.

**Describe the solution you'd like**
I think visual odometry is a good solution for ambiguity. I have tried sequential matching, it reduces wrong watch, but can not eliminate. Is there any way to force colmap reconstruct sequtially like visual odometry?  Is there any guide for extending colmap?

**Describe alternatives you've considered**
not yet

**Additional context**
no

**Comment by CanCanZeng** [comment]
Is it possible to initialize images from a video that the camera is moving strait forward with little rotation or sidesway? I tried to set some parameters including using sequential matching and decreasing the `init_min_tri_angle`, but the reconstruction still failed, any suggest for this kind of problem is appreciated!

**Comment by ahojnnes** [comment]
You might have to change the code for that. Have a look at src/sfm/incremental_mapper.cc:FindInitialPair... there should be a forward motion threshold on the z coordinate of the initial two view geometry. Set it to 1 and also change the initial triangulation angle, as you already suggested in your post.

**Comment by CanCanZeng** [comment]
Thank you for your help! The result seems much better when I set z coordinate to 1.00 and initial triangulation angle to 1.0. But still some images are rejected even there are many overlap regions. I wonder if I can use COLMAP as a third lib like opencv, and rearrange the mapping procedure, the source code of COLMAP seems too complicated for me. 
What I think is like this: 
1. for the first image, extract its feature points
2. for the second image also do feature extraction, matching with the first image, test if the disparity is enough, if so, do triangulation and bundle adjustment, otherwise, do the same thing for next image, still matching with first image untill successfully initialized.
3. then for one incoming image, first extract its feature points, then register it to the previous model, then do bundle adjustment.
Is there an easy way to do this?

**Comment by ahojnnes** [comment]
You can use COLMAP as a third-party library and extend it based on your needs. Please refer to the documentation for details on how to do that: https://colmap.github.io/install.html
