### ISSUE TITLE
Questions about developing with colmap

### ISSUE THREAD

**Issue by yingliangzh** [colmap/colmap#57]
Hi, all, I'm a freshman to github. I want to develop with colmap, and I know it's a Cmake-based project. I just want to know how to develop this Cmake project? Generally which editor and compiler do you use mostly? I just use Clion for now, but I think it's a little not efficient.

**Comment by ahojnnes** [comment]
Which platform are you on? I recommend to use Linux, but any platform here should work: https://colmap.github.io/install.html

**Comment by yingliangzh** [comment]
Hi, @ahojnnes , I'm on linux, too. I like the project. And I'm curious about how to develop a cmake-based project like Colmap piece by piece. Is there any advice?

**Comment by ahojnnes** [comment]
I am using a simple text editor for development, but CLion is good as well. Giving general development advice is out of scope here, but I suggest to start with some basic CMake tutorial. I am sure a search engine of your choice will be useful to get started. Closing this issue for now, but feel free to reopen, if you have specific questions related to COLMAP.
