### ISSUE TITLE
Headless colmap

### ISSUE THREAD

**Issue by isolin** [colmap/colmap#570]
I am trying to get colmap running within an LXC container. It has Ubuntu 18.10 with the NVidia 390 headless driver and CUDA 8.0. I first tried to compile colmap, but I was not able to come over the errros. So I installed it via 'apt install'. the repository contains the 3.5.1 version of Colmap.

Since it is just a container without X display access, I tried to test whether Colmap is running by
```
colmap automatic_reconstructor --worksapce_path . --image_path=../dji/DJI_0005/
```
and to my surprise it requires Qt even in the command line mode!
```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-ubuntu'
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
```
I also tried feature extraction only, but the error was the same. Looking at command line options does not seem to provide any solution. So I would like to ask **how to run shell-only headless Colmap without Qt asking for a viewport**?

**Comment by ahojnnes** [comment]
Check the travis.yml in the repository, where I set an environment variable for X. Maybe this fixes the issue?

**Comment by isolin** [comment]
Ok, I will have a look on that...
In the meanwhile I at least managed to get it running using the standard nvidia driver with graphics forwarded from the container to the host machine.

**Comment by ahojnnes** [comment]
Assuming this is resolved and therefore closing it. Feel free to reopen if there are additional questions.

**Comment by ahong007007** [comment]
I have the same question. and I don't find the file "travis.yml"
![image](https://user-images.githubusercontent.com/22077027/62635968-4910fc80-b96b-11e9-980d-441c05a88771.png)

**Comment by ahojnnes** [comment]
This only works if you have a CUDA enabled GPU or explicitly set to use CPU based feature extract/matching.

**Comment by buithuytien** [comment]
I am facing a similar issue with XDG_RUNTIME_DIR when running `colmap automatic_reconstructor` :

```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-bui.thuy'
This plugin does not support createPlatformOpenGLContext!
F20220220 01:06:58.282294 23628 opengl_utils.cc:56] Check failed: context_.create()
```

details here https://github.com/colmap/colmap/issues/1433

**Comment by XinyueZ** [comment]
> This only works if you have a CUDA enabled GPU or explicitly set to use CPU based feature extract/matching.

I see this issue even when I was working in Colab, a GPU+CUDA., do you have any idea?
I installed via `apt install colmap`.

I guess the issue should be solved when we build from the source and somehow set CUDA+GPU. right?

**Comment by doubleZ0108** [comment]
I also run into these problems, here's some help info.

1. Do not use `apt install colmap` in Ubuntu
    > This will lead to some issues about `GUI` / `X display`.
2. Do not build from the source of the latest Colmap code.
    > This will lead to some very complex issues about `freeimages?`
3. Please try the following:
    ```bash
    git clone --branch 3.6 --single-branch https://github.com/colmap/colmap.git
    
    mkdir build && cd build
    cmake ..
    make -j8
    make install
    ```

    Dependencies you may use:
    ```bash
    apt install libboost-all-dev
    ```

Please let me know if you have solved the problem this way as well.

**Comment by marcovega** [comment]
Ubuntu 22.04.1, CUDA 11.8, GCC 11.2.0.

If you experience an error with the steps above:

```cmake -DCUDA_NVCC_FLAGS="--std c++14" ..```

**Comment by alancneves** [comment]
> ahojnnes

I've followed that and it worked!
