### ISSUE TITLE
Please add panoramic camera model，thanks！

### ISSUE THREAD

**Issue by billcamel** [colmap/colmap#571]
Please add panoramic camera model，thanks！

**Comment by ahojnnes** [comment]
There is an open PR that implements panoramic camera model support. However, it is unlikely that I have time to incorporate that into COLMAP directly. Note that the PR is also based on a relatively old version of COLMAP and the general reconstruction performance will be significantly worse than the current version in the dev/master branch.

**Comment by ahojnnes** [comment]
For your reference, the PR is here: https://github.com/colmap/colmap/pull/9

**Comment by DHNicoles** [comment]
@ahojnnes @tsattler ,this PR [#9](https://github.com/colmap/colmap/pull/9)  is too old, and it is different from the current version in many places！
So，do you have plans to expand the camera model to support spherical cameras?  Thanks!

**Comment by tsattler** [comment]
@DHNicoles I am for now not planning to add support for spherical cameras.
