### ISSUE TITLE
Projection of the 3D pointcloud to 2D has a drift

### ISSUE THREAD

**Issue by hosseinjavidnia** [colmap/colmap#572]
Hi all,
First of all thanks for the wonderful tool. It works perfectly. I have a small issue which is probably related to coordinate systems. It's not COLMAP's issue. Sorry for asking here :)

I ran COLMAP on a sequence of images and got the camera pose and pointcloud which look reasonable (image below)
![colmap_map](https://user-images.githubusercontent.com/36445139/52630115-41d4ce80-2eb3-11e9-8dae-1348aa6736af.png)

Now, I want to project the 3D points onto the 2D images using the poses calculated by COLMAP.
For some reason the projected 2D points are shifted. Here is an example result where I am using the pose provided by COLMAP. You will see the amount of the shift in reprojection when zoomed out.
![colmap](https://user-images.githubusercontent.com/36445139/52630187-7cd70200-2eb3-11e9-9380-aa6afd8a0bf3.png)

Even if I consider the camera pose an identity, the same problem exists (following image):
![eye](https://user-images.githubusercontent.com/36445139/52630270-b27beb00-2eb3-11e9-8338-29aae3338f0d.png)

I am using MATLAB for this and using the focal length which is refined by COLMAP.
Here is the piece of code that I am using.
```
% Convert quaternion to rotation matrix
rotationMat = quat2rotm([0.998084000000000,0.0396575000000000,0.0469763000000000,0.00694158000000000]);

% Translation vector from colmap
translation = [-0.278161000000000,0.574928000000000,0.436330000000000];
translation = -translation * rotationMat;

K = cameraParams.IntrinsicMatrix;
K(1,1) = 1043.38; K(2,2) = 1043.38; % This is the refined focal length by colmap

cameraMatrix = [rotationMat; translation] * K; % Generate projection matrix

pts3D (:,4) = 1; % Colmap pointcloud to homogeneous coordinate

% Calculate 2D projection
imagePoints = pts3D * cameraMatrix;
imagePoints(:,1) = imagePoints(:,1) ./ imagePoints(:,3);
imagePoints(:,2) = imagePoints(:,2) ./ imagePoints(:,3);
imagePoints(:,3) = imagePoints(:,3) ./ imagePoints(:,3);
imagePoints(:,3) = [];
```
I checked this code with the data from ORB SLAM and it seems to be fine.
Any hint or comment would be appreciated. Thanks

**Comment by ahojnnes** [comment]
This should work:
```
% Convert quaternion to rotation matrix
rotationMat = quat2rotm([0.998084000000000,0.0396575000000000,0.0469763000000000,0.00694158000000000]);

% Translation vector from colmap
translation = [-0.278161000000000,0.574928000000000,0.436330000000000];

K = cameraParams.IntrinsicMatrix;
K(1,1) = 1043.38; K(2,2) = 1043.38; % This is the refined focal length by colmap

cameraMatrix = K * [rotationMat, translation']; % Generate projection matrix

pts3D (:,4) = 1; % Colmap pointcloud to homogeneous coordinate

% Calculate 2D projection
imagePoints = cameraMatrix * pts3D;
imagePoints  = imagePoints';
imagePoints(:,1) = imagePoints(:,1) ./ imagePoints(:,3);
imagePoints(:,2) = imagePoints(:,2) ./ imagePoints(:,3);
imagePoints(:,3) = imagePoints(:,3) ./ imagePoints(:,3);
imagePoints(:,3) = [];
```

**Comment by hosseinjavidnia** [comment]
Thank you very much for the hint.
Some small changes had to be applied to your modification to fix the matrix multiplication. I'll leave here the final code in case if someone wants to use:
```
% Convert quaternion to rotation matrix
rotationMat = quat2rotm([0.998084000000000,0.0396575000000000,0.0469763000000000,0.00694158000000000]);

% Translation vector from colmap
translation = [-0.278161000000000,0.574928000000000,0.436330000000000];

K = cameraParams.IntrinsicMatrix;
K(1,1) = 1043.38; K(2,2) = 1043.38; % This is the refined focal length by colmap

cameraMatrix = K' * [rotationMat, translation']; % Generate projection matrix

pts3D (:,4) = 1; % Colmap pointcloud to homogeneous coordinate

% Calculate 2D projection
imagePoints = cameraMatrix * pts3D';
imagePoints = imagePoints';
imagePoints(:,1) = imagePoints(:,1) ./ imagePoints(:,3);
imagePoints(:,2) = imagePoints(:,2) ./ imagePoints(:,3);
imagePoints(:,3) = imagePoints(:,3) ./ imagePoints(:,3);
imagePoints(:,3) = [];
```
