### ISSUE TITLE
Why doesn't the 'PropagateDepth' function in 'src/mvs/patch_match_cuda.cu' takes as input the current column index?

### ISSUE THREAD

**Issue by Kai-46** [colmap/colmap#573]
Am I missing something? I feel like this function should take as input the current column that's being considered.

**Comment by ahojnnes** [comment]
`PropagateDepth` proagates the depth from one row to the next in the same column, so there is no need to know the column in which we are in.

**Comment by Kai-46** [comment]
I'm a little confused. It seems to me that the column also affects the depth value, right?
