### ISSUE TITLE
Reproducing GUI results with command-line

### ISSUE THREAD

**Issue by 2d3** [colmap/colmap#574]
Hi! Using the gui it is possible to set predefined quality-settings (low, medium, high). I preset medium quality and changed a few settings afterwards. want to reproduce the resulting dense cloud using command-line but it is impossible. I examined the project.ini of the gui-project and tried to manually set same parameters. I dont get same dense point cloud. Is there a possibility to do this task?

**Comment by ahojnnes** [comment]
Set the parameters in the GUI, then select File > Save project and use the saved project as a configuration for the command-line. Note that the command-line can directly take a project file as an input as well.

**Comment by 2d3** [comment]
@ahojnnes Thx for reply! 
I already tried to do so. The command 
`colmap automated_reconstructor --project_path c:\...\project.ini `
gave me the error
`ERROR: Failed to parse options unrecognised option 'database_path'`
The first lines of the saved project .ini:
`log_to_stderr=false
log_level=2
database_path=C:/.../database.db
image_path=C:/.../images
[ImageReader]
...`
Have no idea how to solve this... Maybe you have a hint. Thank you very much.

Note: I also found a similar issue: https://github.com/colmap/colmap/issues/378

**Comment by ahojnnes** [comment]
You have to strip down unnecessary options from the project file for the specific command that you are executing. Have a look at the output of “-h” to see the accepted options of each command.

**Comment by 2d3** [comment]
Still get `ERROR: Failed to parse options unrecognised option 'database_path'`,prettty anoying. Can i skip the meshing-part when doing automatic reconstruction by setting --mesher 0? It seems to only allow Delauney and  Poisson. Its not possible to reproduce the the dense-cloud generated by gui with medium setting and some additional changes. I manually set all parameters given in the ini generated within gui-project, but outcome is different (worse). Sry to bother you further ...

**Comment by ahojnnes** [comment]
Paste your project.ini here please and I can adapt it accordingly for you.
