### ISSUE TITLE
Question about image retrieval

### ISSUE THREAD

**Issue by KristianZarn** [colmap/colmap#576]
I have a question about image retrieval. I just want to make sure I understand things correctly. So using the `visual_index.h` class, if the `num_images_after_verification` is set to `0` in the `QueryOptions`, then no spatial verification will be performed and just the vocabulary tree will be used to retrieve the similar images?

I have another quick question. I am implementing a SfM pipeline (incremental). When adding new image to reconstruction I do the matching in the following way: First I find the candidate images based on your image retrieval class (with `num_images_after_verification = 0`). Then I take top `n` images, use feature matching (with RANSAC) and discard images with too few matches (implementation of _Fast and accurate image matching with cascade hashing for 3d reconstruction_). So in my case is the spatial verification unneccessary, since I do feature matching in the next step and get rid of false matches in this way?

**Comment by ahojnnes** [comment]
a) Yes, if ``num_images_after_verification`` is 0 then no spatial verification is performed.

b) No, it wouldn't be unnecessary, because the spatial verification is mainly there to rerank the top images for better retrieval performance. You will likely get more relevant images in the top `n` images when enabling spatial verification. Still, you should perform full geometric verification in the feature matching step later.

Hope that answers your questions.

**Comment by KristianZarn** [comment]
Thank you very much for your answers.

**Comment by KristianZarn** [comment]
I have a followup question. I would like to read more about the details of the vocabulary tree building and querying. The Vote-and-Verify paper seems to focus on verification part mostly. I have seen some references in the paper and the code, but what would be the most appropriate?

**Comment by RuibinMa** [comment]
I have a question regarding the scores returned by vocab_tree_retriever when num_images_after_verification > 0. It seems like the number of inliers of each image, but why are they float numbers rather than integers? Thanks a lot!

**Comment by ahojnnes** [comment]
The scores are floats because they are computed as num_inliers + TF-IDF score. The former are integer values, the latter are in [0,1]. If two images have the same number of inliers, then the visually more similar one is ranked first.
