### ISSUE TITLE
Model Scale Problem

### ISSUE THREAD

**Issue by yingliangzh** [colmap/colmap#58]
Hi, all, I used the colmap to reconstruct some objects, there is a scale problem. 
1. Which coordinates system is used in the Colmap ?
2. May I input the focal length (mm) to get the model which is at the same scale compared with the real object? Or I need to write my own code.

Thanks!

**Comment by ahojnnes** [comment]
1. The coordinate system is initialized wrt. the first two registered images.
2. You can geo-register the model (scale and align the coordinate axis) using the procedure described here: https://colmap.github.io/faq.html#geo-registration

**Comment by yingliangzh** [comment]
Hi, @ahojnnes, thanks for your kind reply. The geo-register can't solve my problem. I just used one Canon Camera whoes pixel size (mm) I know. So maybe I need to modify the first two images registering part.

**Comment by ahojnnes** [comment]
Closing this for now as resolved, but feel free to reopen in case you have more questions regarding this issue.

**Comment by yuancaimaiyi** [comment]
@ahojnnes 
I don't know whether I'm right, but I think the scale problem doesn't need to change any code. If we have the prior pose(imu or otherways), for example, we have the absolute coordinate of camera position (GCP,utm coordnates), and the 3d point coordinate calculated by colmap, the position of camera can be obtained by -R.t *t(in colmap).
In fact, the colmap result is the result of relative orientation in photogrammetry. Finally, we need absolute orientation. If we have prior information, we just estimate a similar transform(3 rotation ,3 translation and 1 scale). Do you think I am right?

**Comment by ahojnnes** [comment]
You can do it like that, but you could achieve better results by enforcing these priors during bundle adjustment. Nevertheless, your simple approach should also work.

**Comment by yuancaimaiyi** [comment]
@ahojnnes  thanks .
I found myself thinking model_aligner in your program, and I was foolish. However, your suggestion is very good. I will try later to add the prior knowledge to make a BA
