### ISSUE TITLE
About poisson_mesher

### ISSUE THREAD

**Issue by KeoChi** [colmap/colmap#580]
Hello! I used the [Sceaux Castle](https://github.com/openMVG/ImageDataset_SceauxCastle) images to test the openMVG and colmap. I only used colmap to recover camera positions and the sparse point-cloud, then patch_match_stereo and stereo_fusion，result of poisson_mesher is good:
fused:
![colmap_fused](https://user-images.githubusercontent.com/9250491/53235641-4bd5a900-36cd-11e9-8d1e-ab4af1990316.png)

meshed-poisson:
![colmap_meshed-poisson](https://user-images.githubusercontent.com/9250491/53235657-555f1100-36cd-11e9-9c94-2aa7613afa76.png)

meshed-delaunay:
![colmap_meshed-delaunay](https://user-images.githubusercontent.com/9250491/53235673-5ee87900-36cd-11e9-86d8-d6c631754c29.png)

  If I used OpenMVG pipeline to recover camera positions, and colmap computed density cloud and mesh. I found the meshed-poisson is so bad. The result:
fused:
![mvg_fused](https://user-images.githubusercontent.com/9250491/53235694-69a30e00-36cd-11e9-8b5e-41af8f306e10.png)

meshed-poisson:
![mvg_meshed-poisson](https://user-images.githubusercontent.com/9250491/53235713-77589380-36cd-11e9-974f-37b0083043b0.png)

meshed-delaunay:
![mvg_meshed-delaunay](https://user-images.githubusercontent.com/9250491/53235720-7c1d4780-36cd-11e9-94ce-b1cdd4a0971c.png)
 I use south-building dataset to test the openMVG pipeline and colmap. The meshed-poisson is also so bad. Nothing:
![nothing](https://user-images.githubusercontent.com/9250491/53239807-f226ac00-36d7-11e9-8132-39247cf857c9.png)

  I hope that you can give some advices. Thank you!

**Comment by ahojnnes** [comment]
Not sure what is going on here. The delaunay mesher in COLMAP generally needs parameter tuning to get good results. It is mostly good for getting an initial mesh from a sparse point cloud.

**Comment by KeoChi** [comment]
I found that I set this parameter "--PoissonMeshing.trim" to a smaller value. The result of poisson_mesher is complete.

**Comment by ahojnnes** [comment]
Yes, this parameter is crucial and must be tuned per scene typically.
