### ISSUE TITLE
About the 'quality' of the automatic reconstruction

### ISSUE THREAD

**Issue by dnzzcn** [colmap/colmap#583]
What does the 'quality' parameter of the automatic reconstructor exactly corresponds to? I couldn't find a parameter for any intermediate algorithm step that takes an input called 'quality'. So, I suppose it is rather a collection of parameters that change with the choice of the quality.

The default pipeline takes too much time to complete, so I would like to manually set the parameters that are in effect when the quality of the automatic reconstructor is changed. Unfortunately, I couldn't find any info on this on the documentation either. Could you please specify the names of these parameters? Thank you.

**Comment by ahojnnes** [comment]
Your understanding is correct that the quality option just changes some of the parameters during reconstruction. For understanding the parameters, please check here and following lines: https://github.com/colmap/colmap/blob/dev/src/util/option_manager.cc#L81

**Comment by ahojnnes** [comment]
https://colmap.github.io/faq.html#adjusting-the-options-for-different-reconstruction-scenarios-and-output-quality
