### ISSUE TITLE
Add point3D_id to modified_point3D_ids_ in RegisterNextImage

### ISSUE THREAD

**Issue by imkaywu** [colmap/colmap#584]
**Describe the bug**
As I understand it, the member variable `modified_point3D_ids_` stores point3D ids that have been newly completed/continued/created/merged. However, in the RegisterNextImage method in sfm/incremental_mapper.cc, the current code fails to add the newly triangulated point3D to this variable. The problem is that these completed point3D might have reprojection error that exceeds the threshold, and LBA wouldn't be able to filter those observations.

**To Reproduce**
1. Print the maximum reprojection error after each iteration of LBA, check if it's larger than the pre-defined threshold.

**Expected behavior**
If the point filtering in LBA doesn't do a good job filtering observations with large re-projection error, it is possible that the LBA will mess up the camera intrinsics, and later, a large portion of registered images will get filtered in GBA

**Screenshots**
Large re-projection error after point filtering
<img width="1208" alt="screen shot 2019-02-23 at 8 29 55 pm" src="https://user-images.githubusercontent.com/4964910/53311942-017f4280-38ee-11e9-99b7-844922c723ef.png">

Invalid camera intrinsics 
![screen shot 2019-02-25 at 11 13 13 am](https://user-images.githubusercontent.com/4964910/53312054-76527c80-38ee-11e9-8dba-c7a73067563f.png)

**Desktop (please complete the following information):**
 - OS: CentOS 7

**Smartphone (please complete the following information):**
NAN

**Comment by ahojnnes** [comment]
Indeed, this can be problematic. This should be fixed with the following change: https://github.com/colmap/colmap/commit/16a5323cd7dab0418e3c1c4462e94866a7711feb - Can you please confirm that this fixes the issue? Thanks for your bug report.
