### ISSUE TITLE
Wrongly initializing a camera "corrupts" database

### ISSUE THREAD

**Issue by tsattler** [colmap/colmap#587]
In the gui, I added a new camera. I filled out the parameter list with too few parameters and got a error message (popup window) in the gui. I was able to close the database management window. When I open the window again, COLMAP crashes with this error message on the console:

F0304 17:30:25.696103 2321957760 database.cc:207] Check failed: num_params == camera.NumParams() (5 vs. 8) 
*** Check failure stack trace: ***
    @        0x1038fcefd  google::LogMessage::SendToLog()
    @        0x1038fd677  google::LogMessage::Flush()
    @        0x103900bf7  google::LogMessageFatal::~LogMessageFatal()
    @        0x1038fdf89  google::LogMessageFatal::~LogMessageFatal()
    @        0x102dcfb1d  colmap::(anonymous namespace)::ReadCameraRow()
    @        0x102dcfc89  colmap::Database::ReadAllCameras()
    @        0x103058005  colmap::CameraTab::Reload()
    @        0x1041df15f  QWidget::event()
    @        0x1041a32ed  QApplicationPrivate::notify_helper()
    @        0x1041a46f2  QApplication::notify()
    @        0x104f84fa4  QCoreApplication::notifyInternal2()
    @        0x1041ddead  QWidgetPrivate::show_helper()
    @        0x1041deb13  QWidget::setVisible()
    @        0x10307fc62  colmap::MainWindow::DatabaseManagement()
    @        0x104fb5e1b  QMetaObject::activate()
    @        0x104199c65  QAction::activate()
    @        0x10428d063  QAbstractButton::isCheckable()
    @        0x10428e1ef  QAbstractButton::mouseReleaseEvent()
    @        0x10438589f  QToolButton::mouseReleaseEvent()
    @        0x1041dee8d  QWidget::event()
    @        0x104385e2f  QToolButton::event()
    @        0x1041a32ed  QApplicationPrivate::notify_helper()
    @        0x1041a6148  QApplication::notify()
    @        0x104f84fa4  QCoreApplication::notifyInternal2()
    @        0x1041a3c10  QApplicationPrivate::sendMouseEvent()
    @        0x1041fe33e  QDesktopWidget::qt_metacall()
    @        0x1041fd025  QDesktopWidget::qt_metacall()
    @        0x1041a32ed  QApplicationPrivate::notify_helper()
    @        0x1041a46f2  QApplication::notify()
    @        0x104f84fa4  QCoreApplication::notifyInternal2()
    @        0x104889a2c  QGuiApplicationPrivate::processMouseEvent()
    @        0x104870d5b  QWindowSystemInterface::sendWindowSystemEvents()

It should be relatively easy to fix this issue and its is just a borderline case. I'll have a go at it once I find some time.

Here is data to reproduce the error: https://drive.google.com/open?id=1hrgyICXl_z_Hx-k2OIMUytxSwg1MYdOZ

**Comment by ahojnnes** [comment]
Fixed, thanks.
