### ISSUE TITLE
Question: getting geometric depth maps using python's script

### ISSUE THREAD

**Issue by uros171513** [colmap/colmap#588]
Hi, how to get the exact geometric depth maps with python like those we can get using matlab's scripts that you provided?

Am i missing something, or this really can't be done with existing python's scripts?

Thanks for your attention. I’m looking forward to your reply.

**Comment by assiaben** [comment]
I think what you are looking for is `colmap/scripts/python/read_dense.py`

**Comment by uros171513** [comment]
Hi @assiaben, I am aware of read_dense.py script, but when I use it, I don't get the same results as I get with the read_depth_map.m script.

**Comment by ahojnnes** [comment]
@uros171513 The result should be exactly the same. What differences do you see when reading in Matlab vs. Python?

**Comment by uros171513** [comment]
@ahojnnes When reading in MATLAB, for example, geometric depth maps are with much more color intensity(or depth intensity) and they have black background (my input images are images of  people just standing, one image - one person), but geometric depth maps read in Python have purple background and less color intensity where the object (human in my case) in the image is.

I cannot publish the results here, so i hope the explanation is clear enough.

**Comment by ahojnnes** [comment]
Seems like the difference is purely a visualization issue and the actual depth maps are the same. This is expected.

**Comment by uros171513** [comment]
@ahojnnes Yes, the problem is when I am trying to get .jpg images from the obtained .bin depth maps and that results in two different depth maps depends on which script I am using (MATLAB or Python).
