### ISSUE TITLE
Domain Size Pooling crashing

### ISSUE THREAD

**Issue by isolin** [colmap/colmap#589]
**Describe the bug**
Feature extraction crashes right away when domain size pooling is enabled.

**To Reproduce**
I am using the most recent dev version (as of March 6th 2019) compiled in Ubuntu.
`colmap feature_extraction ... --SiftExtraction.domain_size_pooling=true`

The very same dataset with domain size pooling enabled works fine with Colmap 3.5 which I upgraded to 3.6 yesterday.

**Error message**
With GPU enabled there is just `Killed` notification. But disabling GPU allows the stack trace to appear:
```
PC: @ 0x55b07f9317fd vl_scalespace_get_octave_geometry
*** SIGSEGV (@0x0) received by PID 4472 (TID 0x7f10d2ff5700) from PID 0; stack trace: ***
    @ 0x7f10e6b7bdd0 (unknown)
    @ 0x55b07f9317fd vl_scalespace_get_octave_geometry
    @ 0x55b07f925c25 cl_covdet_detect
    @ 0x55b07f2e78c4 colmap::ExtractCovariantSiftFeaturesCPU()
    ...
```

**Configuration**
 - Ubuntu Server 18.10
 - nightly colmap build
 - gcc8, CUDA 10.1
 - Intel i7-2600K @ 3.4 GHz
 - GTX 1070 with 8 GB

**Comment by isolin** [comment]
I just tested the Windows 3.6.1 no-CUDA pre-build version and it works without crashing.

**Comment by ahojnnes** [comment]
Not sure what is happening. Is it happening for all images or a specific image?

**Comment by tworkool** [comment]
It is quite a bit later but maybe it will help. I had the same problem when Domain Size Pooling was enabled where the process was just killed without info. For me setting `--SiftExtraction.num_threads` to 8 instead of 16 was the solution! Here is my whole config:

```
colmap feature_extractor \
    --database_path="${db_path}" \
    --image_path="${image_path}" \
    --ImageReader.camera_model=SIMPLE_RADIAL \
    --ImageReader.single_camera=false \
    --SiftExtraction.use_gpu=1 \
    --SiftExtraction.num_threads=8 \
    --SiftExtraction.max_image_size=5000 \
    --SiftExtraction.max_num_features=10000 \
    --SiftExtraction.estimate_affine_shape=1 \
    --SiftExtraction.domain_size_pooling=1
```
