### ISSUE TITLE
Modify dense cloud

### ISSUE THREAD

**Issue by 2d3** [colmap/colmap#592]
Hi @ahojnnes!
I have a camera setup of 100 cameras positioned in a cylidric arrangement, diameter 2m. Its kid of a photogrammetry-booth. The camera positions are fixed in different hight-levels. I want to reconstruct a single object in the booth. Using colmaps standard-settings for medium quality, the dense cloud shows a lot of the rig-structure and background being reconstructed. Thats normal. But now i want to reduce the points to be meshed to the ones of the designated object. In a first naive approach, i wrote a cpp-function to delete points out of range in fused.ply. It works so far, but poisson meshing does not work after modifying only fused.ply, colmap simply crashes. There must be dependencies on fused.ply.vis. Do i have to change fused.ply.vis to match up with modified fused.ply or perform other tasks to make meshing possible again? Thx a lot

**Comment by ahojnnes** [comment]
No, there shouldn't be any dependency on the .vis file in the Poisson mesher, only the Delaunay mesher relies on the .vis file. Are writing out XYZ+RGB+normal again? All of these are needed for Poisson.

**Comment by 2d3** [comment]
Thx for reply! I still dont get expected result. This is what i do:

1. Convert fused.ply to ascii-format.

2. Delete all points outside the unity ball using cpp-function (rest exactly the same as before (format, decimals, etc.)).

3. Save file fused.ply in ascii format. (The displayed result in colmap looks like expected. )

4. Poisson meshing fused.ply (in ascii format).

Poisson meshing generates empty mesh. Output states: `Value Range: [4.555194,8.198765]`. But, meshing works when simply deleting first 50% of points with text editor. So either, somethings wrong with cpp-function, or there are some issues with Range values or so. I am helpless at this point. Maybe you have a hint. Thx for helping.

**Comment by 2d3** [comment]
Poisson meshing works now by adding 8 points that define the original range.

**Comment by 2d3** [comment]
OK, now i know how to do it. First had to understand vis file.
