### ISSUE TITLE
Fails to build with GCC-9

### ISSUE THREAD

**Issue by alexmyczko** [colmap/colmap#597]
**Describe the bug**
Forwarding a build problem with GCC-9

**To Reproduce**
For details, please see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=925655

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux, unstable/sid+experimental

**Comment by ahojnnes** [comment]
Thanks Alex, I hope I can look into this at some point soon. I don’t have a machine GCC 9 right now, so it will take a while.

**Comment by alexmyczko** [comment]
a later version (master checkout) fixes this problem, see http://phd-sid.ethz.ch/debian/colmap/cm36d2/test/
