### ISSUE TITLE
How to evaluate COLMAP model with others (position error) 

### ISSUE THREAD

**Issue by Merlinfang** [colmap/colmap#598]
Hello, 
I have some models, which reconstructed from COLMAP. If I want to evaluate accuracy (position error not reprojection error) by taking Bundler-model as ground truth.

Is that right, using the **reconstruction.Align_Robust()** to align these two models and then calculate mean and median error?

Thank you very much!!

**Comment by ahojnnes** [comment]
Sounds like the right approach, but it requires an overlapping set of images to be reconstructed in both models.

**Comment by Merlinfang** [comment]
Thank you very much!

**Comment by saikumar96** [comment]
Similar to this, given poses for a set of images, how can one quantify the correctness of these poses, using reprojection error in COLMAP?
