### ISSUE TITLE
No GPU utilization in feature-extraction/-matching 

### ISSUE THREAD

**Issue by 2d3** [colmap/colmap#599]
Hi!
I have installed two NVIDIA Geforce GTX 1070TI graphic cards on a win10 maschine. I am using the latest release, colmap 3.5. Somehow GPU acceleration is not utilized in feature/matching stage and in mapper stage (global bundle adjustment), but it is in the dense reconstruction stage. Global bundle adjustment with cpu double precision solver takes very long. Anyone experienced that behavior? Appreciate any hints on how to get gpu acceleration working in sparse stage.  Of course i `use_gpu true` and `gpu_index -1` everywhere needed.

**Comment by ahojnnes** [comment]
How do you determine that the GPU is not used? The task manager is not a good tool for this and will always show low utilization. Use a tool like GPU-Z or NVIDIA-smi.

**Comment by 2d3** [comment]
Ok, thank you very much!
