### ISSUE TITLE
Rig-adjustment does not parse options

### ISSUE THREAD

**Issue by davidmarianovak** [colmap/colmap#60]
I seem to have found another issue with the rig adjustment. When I start it from the command line, it does not parse the options `--BundleAdjustmentOptions.refine_focal_length` or similar - only the necessary input options. Because of that, the rig adjustment never converged (we have a forward-motion setup with unfavourable geometry but ok-isch intrinsics - hence we don't need to adjust the focal-length, principal point and additional parameters). A quick fix in `rig_bundle_adjuster.cc` by adding

` ba_options.refine_focal_length = false;
  ba_options.refine_extra_params = false;
  ba_options.refine_principal_point = false;`

allowed it to converge.

Additionally it seems that the rig is not enforced. When checking the euclidean distances between image pairs, the distance changes by a factor of 2. Do you, by chance, have some example data where the rig adjustment works?

**Comment by ahojnnes** [comment]
The bug with the options should be fixed in https://github.com/colmap/colmap/commit/8f65e0942eb990f215676d89982910781e67097f

I used the rig bundle adjuster for multiple datasets and it works. Unfortunately, I cannot share any of the datasets due to legal agreements. I could have a look at your data, if you can share the images.txt, cameras.txt, points3D.txt and the rig configuration?

**Comment by davidmarianovak** [comment]
Cheers for the fix. I'll send you the link to the data by mail shortly.

**Comment by ahojnnes** [comment]
The rig constraint is correctly enforced. I assume you extract the camera poses incorrectly from the `images.txt`. The camera center in the world coordinate system can be extracted as  ``- qvec^-1 * tvec``. If you use the matlab function from https://github.com/colmap/colmap/blob/master/scripts/matlab/read_model.m, the camera center would be ``camera_center = -image.R' * image.t``.

**Comment by davidmarianovak** [comment]
It was indeed a problem with the wrong conversion. It is now more consistent. My bad.
