### ISSUE TITLE
The difference scale of camera pose and the depth map?

### ISSUE THREAD

**Issue by Aceralon** [colmap/colmap#600]
Rcently I ran colmap reconstructing an object using the pohtos taking around it. And I get the result of camera pose as below:
![批注 2019-04-03 145313.png](https://i.loli.net/2019/04/03/5ca4587197e9b.png)
Since the photos are taking in circle, the distance between the camera and the object is the radius of the track which is around 1.5.
But then I read the generated depth map in stereo/depth_map/*.png.photometric.bin using the provided matlab scripts and I found the depth value of depth map is between 3.5 to 4.5 which is lager than 1.5. 
Is this normal or there is some different scale in the ?  Thank you!

**Comment by ahojnnes** [comment]
3D reconstruction from images is up to scale. You would have to rescale the reconstruction yourself.

**Comment by Aceralon** [comment]
Thank you. The problem is solved.
