### ISSUE TITLE
Multiple camera parameters from command line

### ISSUE THREAD

**Issue by jrterven** [colmap/colmap#602]
Awesome work. I normally use the GUI but I want to use the command line to speed up the process. However, I need to set known camera parameters that could be different for multiple cameras. Is it possible to do this from the command line?

**Comment by ahojnnes** [comment]
Not easily at the moment, but you can easily modify the database after extracting features for all images. Please have a look at the scripts/python/database.db scripts for an example or use your favorite SQLite client. Let me know if something is unclear.

**Comment by jrterven** [comment]
Thank you. This is what I needed. Another quick question. Is there a way to get the model statistics from the database using Python or from the command line?

**Comment by ahojnnes** [comment]
There is the model_statistics command that you can use, which prints a few basic stats. If you need more detailed stats you can load the model in Python as well, see scripts/python/read_model.py
