### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version on 3.6-dev.2

### ISSUE THREAD

**Issue by VictoriousRaptor** [colmap/colmap#603]
**Describe the bug**
While running tests, the following error occurs:
> D:\COLMAP-dev-windows\\bin\sift_test.exe
 if 0 NEQ 0 goto end
)
Running 13 test cases...
CheckCudaDevice:        CUDA driver version is insufficient for CUDA runtime version
Switch from CUDA to OpenGL
CheckCudaDevice:        CUDA driver version is insufficient for CUDA runtime version
CheckCudaDevice:        CUDA driver version is insufficient for CUDA runtime version
ERROR: Not enough GPU memory to match 1000 features. Reduce the maximum number of matches.
c:/users/joschonb/development/colmap/src/feature/sift_test.cc(296): error: in "TestCreateSiftGPUMatcherCUDA": check CreateSiftGPUMatcher(match_options, &sift_match_gpu) has failed
CheckCudaDevice:        CUDA driver version is insufficient for CUDA runtime version
CheckCudaDevice:        CUDA driver version is insufficient for CUDA runtime version
CheckCudaDevice:        CUDA driver version is insufficient for CUDA runtime version

Seems like COLMAP cannot correctly detect my GPU, but I'm pretty sure my GPU is fine. This error can be reproduced on another computer. Version 3.6-dev.1 works fine on my computer.

**To Reproduce**
1. Run `RUN_TEST.bat` on Windows

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 10 1809
 - COLMAP 3.6-dev.2
 - CUDA 9.0
 - NVIDIA 399.24 driver

**Comment by ahojnnes** [comment]
Try and update your NVIDIA driver. The 3.6-dev2 version is compiled with CUDA 10.

**Comment by taiya** [comment]
I was getting this error:
```
ERROR: SiftGPU not fully supported
CheckCudaDevice:        CUDA driver version is insufficient for CUDA runtime version
```

And this was **regardless** of whether I was running `--SiftExtraction.use_gpu 1` or `--SiftExtraction.use_gpu 0` and `–-SiftMatching.use_gpu 1` or `–-SiftMatching.use_gpu 1`.

The issue was a lot simpler:
`docker run --rm -ti ....` → does not work :(
`nvidia-docker run --rm -ti` → **working**

Hope this might save you some time
