### ISSUE TITLE
PatchMatchStereo.cache_size not taken into account on Ubuntu 18.04

### ISSUE THREAD

**Issue by lannoyma** [colmap/colmap#604]
Hi,
I'm currently using COLMAP on Ubuntu 18.04 with 30Go RAM.

COLMAP works fine but a little bit slow for my use case. 
I had a look at the RAM used by colmat during patch_match_stereao and I got surprised. Only 500M of RAM is used...

So I decided to increase the RAM allocated to colmap during patch_match_stereo.
I set PatchMatchStereo.cache_size as explained in the documentation but it has no effect. Here is my command:
 sudo colmap patch_match_stereo \
    --workspace_path /home/maxom93/boite-2/dense \
    --workspace_format COLMAP \
	--PatchMatchStereo.cache_size 25 \

Is it a normal case? Am I missing something?

Thanks for your help

**Comment by ahojnnes** [comment]
If your image collection is small, then the cache is not used completely anyway. This only has effect if you are dealing with large image collections (thousands of images).
