### ISSUE TITLE
SIFT RANSC match option

### ISSUE THREAD

**Issue by zyxrrr** [colmap/colmap#605]
Hello!
I study your code, and meet some problems, could you help me?
1.  I don't konw confidence in RANSC, how does it work? It use in initial pair?
  // Confidence threshold for geometric verification.
  double confidence = 0.999;
2. Is it means if the inliers number more than 25%, the RANSC stop?
  // A priori assumed minimum inlier ratio, which determines the maximum
  // number of iterations.
  double min_inlier_ratio = 0.25;

Thank you so much!

**Comment by ahojnnes** [comment]
Please study the original RAMSAC paper by Fischler and Bolles for a derivation of the meaning of these parameters.
