### ISSUE TITLE
[Question] Units of image transforms

### ISSUE THREAD

**Issue by iBicha** [colmap/colmap#606]
Looking at the documentation here:
https://colmap.github.io/format.html#images-txt

I'm trying to figure out what are the units of the position of the camera.
e.g.
```
# Image list with two lines of data per image:
#   IMAGE_ID, QW, QX, QY, QZ, TX, TY, TZ, CAMERA_ID, NAME
#   POINTS2D[] as (X, Y, POINT3D_ID)
# Number of images: 2, mean observations per image: 2
1 0.851773 0.0165051 0.503764 -0.142941 -0.737434 1.02973 3.74354 1 P1180141.JPG
2362.39 248.498 58396 1784.7 268.254 59027 1784.7 268.254 -1
2 0.851773 0.0165051 0.503764 -0.142941 -0.737434 1.02973 3.74354 1 P1180142.JPG
1190.83 663.957 23056 1258.77 640.354 59070
```
Is the translation values in meters for example? Is it an arbitrary unit? Or is there additional calibration to do to get accurate relative values?

Thank you.

**Comment by ahojnnes** [comment]
Note that these are not the positions of the cameras, but the translation defines the transformation from world to camera coordinate system. See the documentation for how to obtain the location of the camera: https://colmap.github.io/format.html. The reconstruction has an arbitrary scale, which is an inherent property of image-based 3D reconstruction without any priors.

**Comment by iBicha** [comment]
Thank you for the response! I am trying to figure out, what other information I can add to the equation so I get a correctly scaled values of the camera positions. How can I approach this problem?

**Comment by ahojnnes** [comment]
If you know the distance of some object in the scene or if you know the positions of some cameras, you can scale your model accordingly.
