### ISSUE TITLE
Fail to compile for CUDA architecture 7.5

### ISSUE THREAD

**Issue by os-gabe** [colmap/colmap#613]
**Describe the bug**
```
$ cmake ..
-- Found installed version of Eigen: /usr/lib/cmake/eigen3
-- Found required Ceres dependency: Eigen version 3.3.4 in /usr/include/eigen3
-- Found required Ceres dependency: glog
-- Found installed version of gflags: /usr/lib/x86_64-linux-gnu/cmake/gflags
-- Detected gflags version: 2.2.1
-- Found required Ceres dependency: gflags
-- Found Ceres version: 2.0.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations]
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   graph
--   regex
--   system
--   unit_test_framework
-- Found Eigen
--   Includes : /usr/include/eigen3
-- Found FreeImage
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
-- Found Glog
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
-- Found Glew
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
-- Found Qt
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Core
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5OpenGL
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets
-- Found CGAL
--   Includes : /usr//include
--   Libraries : /usr/lib/x86_64-linux-gnu/libCGAL.so.13.0.1
-- Build type not specified, using Release
-- Enabling SIMD support
-- Enabling OpenMP support
-- Disabling interprocedural optimization
-- Autodetected CUDA architecture(s):  7.5
-- Enabling CUDA support (version: 9.1, archs: sm_75)
-- Enabling OpenGL support
-- Disabling profiling support
-- Enabling CGAL support
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gabe/code/colmap/build
```

```
$ make
[  0%] Automatic RCC for target flann
[  0%] Built target flann_autogen
[  1%] Built target flann
[  1%] Automatic RCC for target graclus
[  1%] Built target graclus_autogen
[ 23%] Built target graclus
[ 25%] Automatic RCC for target lsd
[ 25%] Built target lsd_autogen
[ 25%] Built target lsd
[ 25%] Automatic RCC for target pba
[ 25%] Built target pba_autogen
[ 25%] Building NVCC (Device) object lib/PBA/CMakeFiles/pba.dir/pba_generated_ProgramCU.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_75'
CMake Error at pba_generated_ProgramCU.cu.o.Release.cmake:219 (message):
  Error generating
  /home/gabe/code/colmap/build/lib/PBA/CMakeFiles/pba.dir//./pba_generated_ProgramCU.cu.o


lib/PBA/CMakeFiles/pba.dir/build.make:63: recipe for target 'lib/PBA/CMakeFiles/pba.dir/pba_generated_ProgramCU.cu.o' failed
make[2]: *** [lib/PBA/CMakeFiles/pba.dir/pba_generated_ProgramCU.cu.o] Error 1
CMakeFiles/Makefile2:485: recipe for target 'lib/PBA/CMakeFiles/pba.dir/all' failed
make[1]: *** [lib/PBA/CMakeFiles/pba.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

`$ uname -a
Linux os-sim 4.18.0-18-generic #19~18.04.1-Ubuntu SMP Fri Apr 5 10:22:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

Using proprietary NVIDIA driver version 415 

Clean checkout from dev branch
```
commit 8d67bb7a1fa6337bbd9c7b1c53d139b609c79c90 (HEAD -> dev, origin/dev, origin/HEAD)
Author: Johannes Schönberger <johannes.schonberger@microsoft.com>
Date:   Mon Apr 22 10:03:52 2019 +0200

    Do not overwrite invalid parameters when set from string
```
Using a Titan RTX graphics card

**Comment by ahojnnes** [comment]
To compile for compute capability 7.5, you need at least CUDA 10 as far as I know.

**Comment by os-gabe** [comment]
Ahh, thanks. I see now this isn't really a COLMAP specific issue but I appreciate the help. Is the 7.5 architecture dictated by my graphics card hardware or is this from other system software stuff?

**Comment by os-gabe** [comment]
This issue was resolved by first installing CUDA 10 as @ahojnnes suggested. Thanks for the help!

**Comment by stone100010** [comment]
cuda 10.1 ，rtx 2080ti ， same error .....

**Comment by lsx1980** [comment]
-- Found required Ceres dependency: Eigen version 3.3.7 in /usr/include/eigen3
-- Found required Ceres dependency: glog
-- Found required Ceres dependency: gflags
-- Found Ceres version: 2.0.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, Multithreading]
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: program_options filesystem graph system unit_test_framework 
-- Found Eigen
--   Includes : /usr/include/eigen3
-- Found FreeImage
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
-- Found Glog
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
-- Found Glew
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /usr/bin/g++-9 compiler.
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.48")  
-- Boost include dirs: /usr/include
-- Boost libraries:    
-- Using gcc version 4 or later. Adding -frounding-math
-- Found Qt
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Core
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5OpenGL
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets
-- Found CGAL
--   Includes : /usr/include
--   Libraries : CGAL
-- Build type not specified, using Release
-- Enabling SIMD support
-- Enabling OpenMP support
-- Disabling interprocedural optimization
-- Autodetected CUDA architecture(s):  7.5
-- Enabling CUDA support (version: 10.1, archs: sm_75)
-- Enabling OpenGL support
-- Disabling profiling support
-- Enabling CGAL support
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/colmap/build

Cuda 10.1, rtx 2080, same error

**Comment by lsx1980** [comment]
opt/colmap/build$ sudo make -j8
[  4%] Building NVCC (Device) object lib/PBA/CMakeFiles/pba.dir/pba_generated_ProgramCU.cu.o
[  4%] Building NVCC (Device) object lib/SiftGPU/CMakeFiles/sift_gpu.dir/sift_gpu_generated_ProgramCU.cu.o
[  4%] Built target lsd
[  6%] Built target sqlite3
[  8%] Built target flann
[ 10%] Built target poisson_recon
[ 24%] Built target vlfeat
[ 46%] Built target graclus
In file included from /usr/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
  138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
      |  ^~~~~
In file included from /usr/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
  138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
      |  ^~~~~
CMake Error at pba_generated_ProgramCU.cu.o.Release.cmake:220 (message):
  Error generating
  /opt/colmap/build/lib/PBA/CMakeFiles/pba.dir//./pba_generated_ProgramCU.cu.o


make[2]: *** [lib/PBA/CMakeFiles/pba.dir/build.make:65: lib/PBA/CMakeFiles/pba.dir/pba_generated_ProgramCU.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:669: lib/PBA/CMakeFiles/pba.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMake Error at sift_gpu_generated_ProgramCU.cu.o.Release.cmake:220 (message):
  Error generating
  /opt/colmap/build/lib/SiftGPU/CMakeFiles/sift_gpu.dir//./sift_gpu_generated_ProgramCU.cu.o


make[2]: *** [lib/SiftGPU/CMakeFiles/sift_gpu.dir/build.make:65: lib/SiftGPU/CMakeFiles/sift_gpu.dir/sift_gpu_generated_ProgramCU.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:723: lib/SiftGPU/CMakeFiles/sift_gpu.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by Eckert-ZJB** [comment]
> cuda 10.1 ，rtx 2080ti ， same error

@stone100010 Did you solve it? I meet the same issue. Thanks~

**Comment by hop-soellingeraj** [comment]
```
:~/code/colmap/build$ nvidia-smi
Tue Nov  9 20:03:05 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.82.00    Driver Version: 470.82.00    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro M4000        Off  | 00000000:05:00.0  On |                  N/A |
| 46%   34C    P8    14W / 120W |    249MiB /  8124MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```
Same error:
```
[ 37%] Building C object lib/Graclus/CMakeFiles/graclus.dir/multilevelLib/wkkm.c.o
[ 39%] Building C object lib/Graclus/CMakeFiles/graclus.dir/metisLib/subdomains.c.o
[ 39%] Building CXX object lib/PoissonRecon/CMakeFiles/poisson_recon.dir/PlyFile.cpp.o
[ 41%] Building C object lib/Graclus/CMakeFiles/graclus.dir/metisLib/timing.c.o
[ 43%] Building CXX object lib/PoissonRecon/CMakeFiles/poisson_recon.dir/SurfaceTrimmer.cpp.o
[ 43%] Building C object lib/Graclus/CMakeFiles/graclus.dir/metisLib/refine.c.o
[ 43%] Building C object lib/SQLite/CMakeFiles/sqlite3.dir/sqlite3.c.o
[ 43%] Building C object lib/Graclus/CMakeFiles/graclus.dir/multilevelLib/mlkkm.c.o
CMake Error at pba_generated_ProgramCU.cu.o.Release.cmake:219 (message):
  Error generating
  /home/fortville/code/colmap/build/lib/PBA/CMakeFiles/pba.dir//./pba_generated_ProgramCU.cu.o


lib/PBA/CMakeFiles/pba.dir/build.make:63: recipe for target 'lib/PBA/CMakeFiles/pba.dir/pba_generated_ProgramCU.cu.o' failed
make[2]: *** [lib/PBA/CMakeFiles/pba.dir/pba_generated_ProgramCU.cu.o] Error 1
CMakeFiles/Makefile2:485: recipe for target 'lib/PBA/CMakeFiles/pba.dir/all' failed
make[1]: *** [lib/PBA/CMakeFiles/pba.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMake Error at sift_gpu_generated_ProgramCU.cu.o.Release.cmake:219 (message):
  Error generating
  /home/fortville/code/colmap/build/lib/SiftGPU/CMakeFiles/sift_gpu.dir//./sift_gpu_generated_ProgramCU.cu.o


lib/SiftGPU/CMakeFiles/sift_gpu.dir/build.make:63: recipe for target 'lib/SiftGPU/CMakeFiles/sift_gpu.dir/sift_gpu_generated_ProgramCU.cu.o' failed
make[2]: *** [lib/SiftGPU/CMakeFiles/sift_gpu.dir/sift_gpu_generated_ProgramCU.cu.o] Error 1
CMakeFiles/Makefile2:661: recipe for target 'lib/SiftGPU/CMakeFiles/sift_gpu.dir/all' failed
make[1]: *** [lib/SiftGPU/CMakeFiles/sift_gpu.dir/all] Error 2

```
I am also getting errors about the gcc version earlier in the build.  My CUDA version doesn't work with gcc < 6.  Maybe this is the root cause?
```
[ 19%] Building C object lib/VLFeat/CMakeFiles/vlfeat.dir/mathop_avx.c.o
In file included from /usr/include/host_config.h:50:0,
                 from /usr/include/cuda_runtime.h:78,
                 from <command-line>:0:
/usr/include/crt/host_config.h:121:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!
 #error -- unsupported GNU version! gcc versions later than 6 are not supported!
  ^~~~~
```
and
```
[  9%] Building C object lib/VLFeat/CMakeFiles/vlfeat.dir/mser.c.o
In file included from /usr/include/host_config.h:50:0,
                 from /usr/include/cuda_runtime.h:78,
                 from <command-line>:0:
/usr/include/crt/host_config.h:121:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!
 #error -- unsupported GNU version! gcc versions later than 6 are not supported!
  ^~~~~
```

**Comment by novasky0709** [comment]
Same error
