### ISSUE TITLE
dense reconstruction with spherical images whose camera parameters are estimated by OpenMVG

### ISSUE THREAD

**Issue by tdsuper** [colmap/colmap#615]
Hi @ahojnnes , currently I used OpenMVG to estimate the camera parameters of a collection of spherical images. After that, I converted each spherical image into six perspective images in the format of cube map. Then the camera parameters for the perspective images are exported to COLMAP and I followed the steps in the [document](https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses) to do dense reconstruction. 
However the colmap program ignored some reference images, as they have no source images. From some closed issues, I found I should manually specify the source images like [this](https://colmap.github.io/faq.html#manual-specification-of-source-images-during-dense-reconstruction), then I chose to use all other images as source images. Although the program did not ignore any images, the resulting depth maps were not correct. 
I have also tested to export the camera parameters for the perspective images into PMVS format and feed them to COLMAP. I got the same problem.
Could you please provide some suggestion or help? Thanks!

**Comment by ahojnnes** [comment]
Can you provide a few example screenshots of the reconstruction and the resulting depth maps?

**Comment by tdsuper** [comment]
Here I give one input image, the photometric depth map and the geometric  depth map. The depth maps seem to be incorrect.

![img](https://user-images.githubusercontent.com/213596/57593256-36a24500-756d-11e9-8dc6-83bb1c63e69d.png)

![depth1](https://user-images.githubusercontent.com/213596/57593263-3a35cc00-756d-11e9-80cc-6f5e1f725944.png)

![depth2](https://user-images.githubusercontent.com/213596/57593264-3b66f900-756d-11e9-99ed-3c0a304d4abf.png)

**Comment by whuwuteng** [comment]
Do you solve this problem? I export cameras.txt, images.txt, and points3D.txt from another software. After dense reconstruction, the photometric depth map, the geometric depth map look correct like yours, and the depth maps have the same problem with you. @tdsuper 
By the way, I have also done this experiment, first export the model result into text using spare reconstruction in "colmap", and then import the text into "colmap", the depth maps have the same problem, do you know the reason? @ahojnnes

**Comment by tdsuper** [comment]
@whuwuteng You can export SfM result with PMVS format and load the result with COLMAP.
