### ISSUE TITLE
Code style URL is broken

### ISSUE THREAD

**Issue by soupault** [colmap/colmap#62]
File: https://github.com/colmap/colmap/blob/master/doc/contribution.rst
URL (current): http://google-styleguide.googlecode.com/svn/trunk/cppguide.html

URL (working): https://google.github.io/styleguide/cppguide.html

**Comment by ahojnnes** [comment]
Fixed, thanks.

**Comment by soupault** [comment]
@ahojnnes There is one more in https://github.com/colmap/colmap/blob/master/README.md.

**Comment by ahojnnes** [comment]
Thanks, also fixed :-)
