### ISSUE TITLE
Number of point clouds

### ISSUE THREAD

**Issue by neverwalkingalone** [colmap/colmap#621]
How can I know the number of points?
and How to know the average reprojection error，thx

**Comment by whuaegeanse** [comment]
In the class of Reconstruction, you can  get information of points ， cameras , images ...
call the function named ComputeMeanReprojectionError in the class of Reconstruction, you can get the average  reprojection error.

**Comment by ahojnnes** [comment]
There is also a command-line argument model_statistics or in the GUI, click Extras > Statistics
