### ISSUE TITLE
Documentation for model_orientation_aligner algorithm?

### ISSUE THREAD

**Issue by meder411** [colmap/colmap#625]
Is there any documentation concerning the algorithm used for the `model_orientation_aligner` outside of [coordinate_frame.h](https://github.com/colmap/colmap/blob/dev/src/estimators/coordinate_frame.h)? Is it from a specific paper?

**Comment by ahojnnes** [comment]
No, there is no further documentation or a specific paper. It’s just a basic vanishing point alignment and (inherently also) Manhattan word alignment, if the scene has Manhattan word structure.

**Comment by meder411** [comment]
Ok, thanks
