### ISSUE TITLE
Which command lines should I use to do sfm with stereo images?

### ISSUE THREAD

**Issue by JHzss** [colmap/colmap#626]
I have seen [#397 ](https://github.com/colmap/colmap/issues/397) but I still don't know how to do it.

**Comment by JHzss** [comment]
If I want to run this code with KITTI (stereo images) database, if I can do with the following step:
1. add prefix to left images and right images(because the left image and right image pair in KITTI database have the same image name )
2. put them in one folder (if I run 'colmap gui' to new a project, I only can choose one floder with images)
3. 'Feature extraction' and select 'Shared for all images' and 'Extract' (the left camera and right camera is the same)
4. 'Feature matching' and select 'Sequential' + ' loop_detection' and set 'vocab_tree_path' you have given. and 'Run'
5. 'Reconstruction' -> ' Start reconstruction'

I wonder if I can do this if I want to reconstruct with stereo images or I should change the way in above steps? Thanks very much. @ahojnnes

**Comment by ahojnnes** [comment]
That sounds right. You could run a final rig bundle adjustment to enforce the stereo constraint.

**Comment by JHzss** [comment]
Thank you, I wonder if the matching method 'Sequential'  in setp 4 is suitable for stereo images because if I add prefix to them,  all left images will be at the front of the right images. I try to run the code with dataset KITTI06, but the result is not so good . I evaluate the pose using evo and the result is :
![KITTI06colmap](https://user-images.githubusercontent.com/24726020/59916274-4a38a980-9451-11e9-9a33-b7e605e7cbe4.png) .

**Comment by iamwangyabin** [comment]
Sorry,I just wondering how to run a final rig bundle adjustment ? I didn't see this button in Colmap Gui, Is it a command ?

**Comment by iamwangyabin** [comment]
I read a lot issue but how to write` rig_config `to run a final rig BA ? The code annotation in `colmap.cc` is hard to understand........
My problem is I only have one camera ,but it's a panorama camera ,so I split photo into five small pinhole image to run reconstruct (Colmap now don't support Spherical camera model) . The most important thing is that I want to fix five image center at one point. 
Thanks a lot @ahojnnes

**Comment by JHzss** [comment]
It works with the solution of #397 , thanks for the Wonderful tool !

**Comment by yuancaimaiyi** [comment]
@JHzss  how to solve the stereo image ,your estimate the camera pose like this ?
![stereo](https://user-images.githubusercontent.com/28293910/71152738-33dda000-2272-11ea-9678-0c803b4c27bc.png)

**Comment by kevinchan04** [comment]
Hi @JHzss , I am still confuse on the solution of #397 after reading lots of issues related to it.  Could you share more your experience on how to use #397? Thanks!
