### ISSUE TITLE
Synthetic data : no convergence

### ISSUE THREAD

**Issue by thunders82** [colmap/colmap#628]
Hi,

I'm currently doing some tests to see how accurate a reconstruction can be. To do so I created some synthetic data coming from a 3D software which at the end should ease the comparison process. 
The current problem is I can't achieve the sparse reconstruction step. It's probably more a user issue than a software issue as I can make everything work with real pictures/images. 

The synthetic data is : 
- a 360degree camera movement around a CG head. 
- using the normals output as texture on the CG head.
- using an orthographic camera and is probably not containing the EXIF data. 

Those 3 points can potentially be the issue I guess ?

Here is a link to the images and the alpha I'm using : https://we.tl/t-HDiZxmQ2dc
And here is a zip file including the database and project file.
[proj.zip](https://github.com/colmap/colmap/files/3281356/proj.zip)

Thank you,

Geoffrey

**Comment by ahojnnes** [comment]
You need realistic texturing of the 3D model, otherwise there is no hope to successfully match features in different images.

**Comment by thunders82** [comment]
Thank you for the answer. I thought having an (almost unique) RGB value per pixel would help but I guess the soft transition could be interpreted by the software as a lighting falloff and not a texture feature. Does it mean the texture needs a high contrast ? If yes, is the software evaluating the contrast as a greyscale value per channel or all together ? 

While I'd like to see how far the reconstruction can be pushed I'm wondering if I could input manually my own higher resolution photometric normal map for the dense reconstruction and benefit from higher details/accuracy ?

Thank you,

Geoffrey

**Comment by ahojnnes** [comment]
Some random pattern should do fine. Ideally nothing repetitive.

**Comment by thunders82** [comment]
That worked great ! Thanks for that. 

I have now 2 other issues. I'll run more tests but let me know if I need to create new tickets :

1) while using the 'high' preset I noticed some issues with normals on the model (visible in photometric and geometric maps too). Therefore I tried to use the 'extreme' preset but it crashed filling up the RAM and swap disk during the 'feature extraction' stage. I wasn't expecting such a difference in memory usage. Is it expected ? If yes, is there an easy way to know/calculate the required memory ? I currently use a computer with 32G of ram and 2xTi1080. The current project is using 30 images 4096*4096.

2) I tired to mesh the fused ptc with the 2 available methods. Delaunay seems to work fine but Poisson creates an 'empty' file (just few Ko). I coudn't find anything in the log (I'm using the gui). I'll try the command line in case I can increase the verbosity. And I'll try to recompile colmap and see if it helps as we changed few libraries on the computer...

Thank you,

Geoffrey

**Comment by thunders82** [comment]
Hi @ahojnnes ,

I was wondering if you had a chance to look at my last message ?

Thank you,
Geoffrey

**Comment by ahojnnes** [comment]
1. It’s not easy to predict the required memory usage. In you specific case, it seems like the machine is running out of GPU memory. You could have a look at the source code at src/util/option_manager.cc to check which options are set in extreme mode. Then, just ignore the max_image_size ones and try again. Otherwise, there shouldn’t be much difference between high and extreme. 
2. I can only imagine that Poisson crashed due to too many points. You could try to sub sample the point Cloud first on Meshlab or PCL and then feed the resulting point cloud to Poisson.

**Comment by thunders82** [comment]
Hi @ahojnnes ,
I'm back from holidays. Thank you for the answers. Regarding the accuracy is it better to use estimate_affine_shape and domaine_size_pooling with a low max_image_size ? Or using high max_image_size without those 2 options? I did a quick test with 2400 as max_image_size but I didn't see any load on the GPU for the 'feature extraction' stage... I ll run more tests lowering max_image_size until it kicks in and report here to see if looks normal to you or not.

Cheers,
Geoffrey.

**Comment by ahojnnes** [comment]
The affine and domain size pooling SIFT versions run on the GPU.

**Comment by ahojnnes** [comment]
Sorry, they run on the CPU and not the GPU.

**Comment by thunders82** [comment]
Haaa! That makes more sense. Thanks
