### ISSUE TITLE
Clearing inlier matches during MatchSiftFeaturesGPU is causing a lot of my images to fail registration during sparse reconstruction

### ISSUE THREAD

**Issue by sbarkby** [colmap/colmap#63]
My issue refers to the commit "Add functions to match features on the CPU" (commit ID: b8de6abd7dac59541710ffb1bae1b8957781b8f1 ) and to the following code snippet where an additional line of code was added to clear the inlier_matches list:

_void MatchSiftFeaturesGPU(const SiftMatchOptions& match_options,
                            const FeatureDescriptors* descriptors1,
                            const FeatureDescriptors* descriptors2,
 @@ -1429,6 +1681,7 @@ void MatchGuidedSiftFeaturesGPU(const SiftMatchOptions& match_options,
      H = two_view_geometry->H.cast<float>();
      H_ptr = H.data();
    } else {
 +    two_view_geometry->inlier_matches.clear();
      return;
    }_

Basically I have 60 images from a hemisphere of camera poses around an object of interest. Before this commit all 60 images were registering fine during sparse reconstruction, resulting in a good sparse point cloud. After the above commit it was then only capable of registering 50-55 of the 60 images, resulting in large gaps in the point cloud. Upon further investigation the images were failing registration because some of them were not passing the min_abs_pose_inliers threshold test.

I have since commented out the  "two_view_geometry->inlier_matches.clear();" addition and am back to being able to register all of my images again. However I am assuming that commenting this piece of code out will cause me problems further down the track when the reason for it becomes apparent. As such an explanation of why this piece of code is needed would really help me out!

Cheers

Stephen

**Comment by ahojnnes** [comment]
Hi,

thanks for reporting the bug. Are you using the option: "multiple"?

Best,
Johannes

**Comment by sbarkby** [comment]
Hi Johannes

Yes, guided matching and multiple models

Stephen

**Comment by ahojnnes** [comment]
Guided matching has no meaning with multiple_models enabled. I suggest to disable the multiple_models option.

**Comment by ahojnnes** [comment]
I deleted the code lines anyway to fix this corner case in commit https://github.com/colmap/colmap/commit/0a25983257f5abfa693739d1a06cd8b033fac4fc

**Comment by ahojnnes** [comment]
Closing and thanks for reporting. Feel free to follow up, if you have additional questions.

**Comment by sbarkby** [comment]
Brilliant, thanks for clearing that up, no problem at all!

Stephen
