### ISSUE TITLE
Colmap option_manager conflict with flann

### ISSUE THREAD

**Issue by Andreachen0707** [colmap/colmap#631]
Hi,
This is a weird problem I encounter when I'm trying to use both Open3D and Colmap, with flann error.
**Describe the bug**
If I initialize colmap::OptionManager, further flann::Index<>::Index() won't work.

**Error Info**

*** Aborted at 1560535234 (unix time) try "date -d @1560535234" if you are using GNU date ***
PC: @     0x5576893f4820 (unknown)
*** SIGSEGV (@0x9) received by PID 45035 (TID 0x7f62bde4a900) from PID 9; stack trace: ***
    @     0x7f62bb2100e0 (unknown)
    @     0x5576893f4820 (unknown)
    @     0x5576893fa650 flann::create_index_by_type<>()
    @     0x5576893fac00 flann::Index<>::Index()
    @     0x5576893f236e open3d::geometry::KDTreeFlann::SetRawData()
    @     0x5576893f263d open3d::geometry::KDTreeFlann::SetGeometry()
    @     0x5576893f1298 open3d::geometry::PointCloud::EstimateNormals()
    @     0x557688b72837 imagex::modelbuilder::PointCloudRegist::PointToPlaneICP()
    @     0x557688b6f95a main
    @     0x7f62b6b3d2e1 __libc_start_main
    @     0x557688b6f54a _start
    @                0x0 (unknown)

**Desktop:**
 - OS: linux
-gcc:
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) 

**Additional context**
This seems to be a weird place to ask this question, but if I discard colmap::OptionManager, the flann will back to work and program will produce correct result. If anyone has the experience with option_manager conflict with flann, please kindly share the solution. 

Many thanks in advance!

-Andrea

**Comment by ahojnnes** [comment]
From the information you provide, I cannot tell what you are actually doing. Are you compiling your own code that uses both Open3D and COLMAP in C++?

**Comment by Andreachen0707** [comment]
> From the information you provide, I cannot tell what you are actually doing. Are you compiling your own code that uses both Open3D and COLMAP in C++?

Yes. I'm compiling my own code which use both Open3D and colmap in C++. Not sure which library cause the problem...

**Comment by ahojnnes** [comment]
Then I assume that open3d was compiled with a different FLANN version and you therefore see the conflicts.
