### ISSUE TITLE
Getting SIFT features data

### ISSUE THREAD

**Issue by alexs7** [colmap/colmap#632]
Hello,

Along with the data that Colmap can export, can it export aswell the 2D points (which it already does) and their SIFT descriptor vectors ?

Thanks

**Comment by ahojnnes** [comment]
Have a look at the scripts/python/export_*.py scripts. You might have to modify them a little to your specific needs, but it should be pretty simple.

**Comment by Beniko95J** [comment]
Hi, I am wondering is that the row number (zero based) of keypoint in the "keypoints" table in the database the feature id (zero based) obtained from the "matches" table?

**Comment by ahojnnes** [comment]
Yes.
