### ISSUE TITLE
Better accuracy for trajectory estimation

### ISSUE THREAD

**Issue by giwrgosg** [colmap/colmap#633]
I have read in some papers that they utilized colmap to estimate the groundtruth trajectory of a robot. I tried the same with my HW setup, doing a small circle trajectory around a table with my camera. The colmap captures the general concept of the trajectory I did, however it deviates a lot from the actual traversed trajectory.
1) Do you have any advise to increase the accuracy, I would like to use the derived trajectory as groundtruth, so it has to be as accurate as it gets.
2) Also for just the camera trajectory I need only the sparse model, or the dense offers higher accuracy for the trajectory?

**Comment by ahojnnes** [comment]
1. If you capture a video, try to avoid using every frame at high frame rate. I suggest to downsample the video. Otherwise, I need more info on how you currently use COLMAP, to provide further recommendations. 
2. You only need the sparse model. The dense modeling stage does not change the camera trajectory.

**Comment by giwrgosg** [comment]
@ahojnnes Thank you for your recommendation. My video has been recorded at 9 fps. However, the movements are slow and smooth. Should I still subsample the frames?

I am using COLMAP straightforward, I  just feed the frames I have in COLMAP with the default settings, choosing the automatic reconstruction. What other information may I provide you to give you an insight?

**Comment by giwrgosg** [comment]
I reduced the number of my acquired images in half, by subsampling every two images and I got a descent result.
