### ISSUE TITLE
Overlap parameter doesn't work?

### ISSUE THREAD

**Issue by Beniko95J** [colmap/colmap#636]
For sequential matching, even I have set "overlap" parameter to 10, there are still matches whose indices differ by more than 10.

I use this command for sequential matching.

***
colmap sequential_matcher --database_path colmap/database.db --SiftMatching.use_gpu=false
***

I hope that when I set "overlap" to 10, there will be no matches whose indices differ by more than 10.

![image](https://user-images.githubusercontent.com/30772597/59963756-8859ca00-9532-11e9-82aa-2d7d3eeacc73.png)
![image](https://user-images.githubusercontent.com/30772597/59963760-9d365d80-9532-11e9-8b31-16580b563636.png)

 - OS: WSL Windows10
 - Version 3.6.2

Thanks!

**Comment by Beniko95J** [comment]
The first screenshot is the matches of the first image. (whose index is 1)

**Comment by ahojnnes** [comment]
Disable the quadratic option, otherwise it will attempt to match over larger temporal windows. This is expected behavior.

**Comment by Beniko95J** [comment]
Thank you for the quick reply. It solved my problem, thanks!

**Comment by wcochran** [comment]
I don't even understand the quadratic overlap option -- it select images that are a "power of 2" away?
`const size_t image_idx2_quadratic = image_idx1 + (1 << i);`
First, how is this quadratic? Second why grab an image that is a "power of 2 away"? There will be big gaps between powers of 2. Mystified by this.

**Comment by ahojnnes** [comment]
The intent is to get both nearby and further away matches. Note that colmap will only attempt to triangulate points from direct and not from transitive matches, so depending on the frame rate of your image sequence, it can help to use the quadratic option.
