### ISSUE TITLE
Running on Google Cloud

### ISSUE THREAD

**Issue by tkhan1994** [colmap/colmap#638]
Hi, 

I'm trying to run the COLMAP pipeline on google cloud through the command-line interface. However, I get an error saying that "no display found". Can someone please explain why this is happening? I'm not even running the command "colmap gui".

Thanks

**Comment by ahojnnes** [comment]
You cannot use the GUI and must use the pipeline from the command line. Please refer to the documentation for more info.

**Comment by tkhan1994** [comment]
I am using it from the pipeline. Take a look at the screenshot attached below.

<img width="1006" alt="Screen Shot 2019-06-25 at 1 15 15 AM" src="https://user-images.githubusercontent.com/34044382/60081556-df080500-96e6-11e9-8bc4-c776d209f9ae.png">

**Comment by tkhan1994** [comment]
I got it to work apparently CUDA was not installed and that was the problem.

I have one more question though, In my sparse directory I get more than one folder, can you please explain why that is the case? Thanks

**Comment by ahojnnes** [comment]
It happens when COLMAP cannot reconstruct all images into the same connected component due to insufficient visual overlap or other reasons.
