### ISSUE TITLE
Windows binaries not working

### ISSUE THREAD

**Issue by zwn** [colmap/colmap#64]
The binaries available at http://people.inf.ethz.ch/jschoenb/colmap/2.1/COLMAP-2.1-windows-no-cuda.zip seem to be not working. Running any exe I get this error:

![image](https://cloud.githubusercontent.com/assets/1130051/22036964/a4247ed0-dcf5-11e6-9d86-3ba42d188ccd.png)

Inspecting the exe with _depends_ I get some errors reported as well. For one, it seems to be linked with the visual studio runtime - but the x86 version instead of x64 (all other linked dlls are x64).

I am on Win7 x64.

**Comment by ahojnnes** [comment]
I accidentally shipped the wrong version of the MSVC12 DLLs. This should be fixed now. Can you please re-download and report back whether it works for you now?

Thanks!

**Comment by ahojnnes** [comment]
I tested this on three independent machines and the issue should be resolved. Closing this for now, but feel free to reopen if the problem still exists for you.

**Comment by zwn** [comment]
I can confirm it works. Thanks.

**Comment by ahojnnes** [comment]
Thanks for the feedback!
