### ISSUE TITLE
Camera being ignore

### ISSUE THREAD

**Issue by jrterven** [colmap/colmap#644]
Hi, I am using Colmap to calibrate multiple cameras, I am more interested in getting all the cameras than the 3D reconstruction. I am running colmap with 39 cameras but at the last iteration, it removes 1 leaving the results with 38. 
What parameters can I change to keep all the cameras?  

At some point, it gets all the cameras  
![image](https://user-images.githubusercontent.com/3149608/60761691-99aad800-a002-11e9-8242-180a70092805.png)

Finally it removes one  
![image](https://user-images.githubusercontent.com/3149608/60761693-a7605d80-a002-11e9-99dc-2d6e83943d3e.png)

**Comment by ahojnnes** [comment]
Check the max_extra_param setting and set it to a large value.

**Comment by apurvazaveri** [comment]
I had a similar issue to me increasing the "options.init_max_error" resolved it.
