### ISSUE TITLE
Can i use other method to extract feature?

### ISSUE THREAD

**Issue by lfydegithub** [colmap/colmap#649]
I got descriptors by other method, not SIFT. And I import .db file into COLMAP.  I make sure that keypoints is right, because i saw the right img and keypoints by "database management" gui, and I have convert my description to [0, 255]. That's no problem.
But, when i do "Feature matching", got 0 matches. I saw the modify .db file, which changed by COLMAP. But all in "matches" table are 0.  My .db file contain "cameras", "descriptors", "images", "keypoints".

**Comment by ahojnnes** [comment]
For feature matching, COLMAP assumes normalized descriptor vectors, because it uses the dot product for similarity computation. Are your descriptors normalized, I.e. all have the same length?

**Comment by lfydegithub** [comment]
> For feature matching, COLMAP assumes normalized descriptor vectors, because it uses the dot product for similarity computation. Are your descriptors normalized, I.e. all have the same length?

Yes, every feature vector's length is 1. and we changed "Cosine distance " to "L2 distance", it works.

**Comment by ahojnnes** [comment]
Maybe the distance thresholds are too tight?

**Comment by eddienewton** [comment]
@ahojnnes what was the resolution for this?  I'm facing the same issue.  I'm importing custom descriptors and get 0 matches.  Like @lfydegithub, each of my vectors is L2 normalized and then converted to 0-255 range.  

I verified my import script by importing Opencv SIFT descriptors.  I get matches in this case, but not when I use my custom descriptor.  The custom descriptor works using OpenCV BruteForce.

Thanks

**Comment by x1597275** [comment]
> I got descriptors by other method, not SIFT. And I import .db file into COLMAP. I make sure that keypoints is right, because i saw the right img and keypoints by "database management" gui, and I have convert my description to [0, 255]. That's no problem.
> But, when i do "Feature matching", got 0 matches. I saw the modify .db file, which changed by COLMAP. But all in "matches" table are 0. My .db file contain "cameras", "descriptors", "images", "keypoints".

hello,can you tell me how to use my own keypoints and descriptor in colmap ?I 'm a beginner
