### ISSUE TITLE
COLMAP 2.1 - Sequential Matcher Error

### ISSUE THREAD

**Issue by pogilon** [colmap/colmap#65]
Hello,

I am getting the error below when running the sequential matcher in COLMAP 2.1. Any ideas what could be the cause? Thank you for all your support. I am running CUDA 8.0, UBUNTU 16.04 with a nvidia GTX1080.

F0118 21:41:15.792867 27956 feature_matching.cc:981] Check failed: loop_detection_max_num_features > 0 (-1 vs. 0)
*** Check failure stack trace: ***
    @     0x7f94c737f5cd  google::LogMessage::Fail()
    @     0x7f94c7381433  google::LogMessage::SendToLog()
    @     0x7f94c737f15b  google::LogMessage::Flush()
    @     0x7f94c7381e1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x50c2e0  colmap::SequentialFeatureMatcher::Options::Check()
    @           0x50f717  colmap::SequentialFeatureMatcher::SequentialFeatureMatcher()
    @           0x4f5bd1  main
    @     0x7f94c3a01830  __libc_start_main
    @           0x4f9fe9  _start
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by ahojnnes** [comment]
Should be fixed in https://github.com/colmap/colmap/commit/769483273f4554cd6f0be20e39544f11eb8e5efe

Thanks for reporting!
