### ISSUE TITLE
What is the command argument for a shared/fixed instrinsic case ?

### ISSUE THREAD

**Issue by thezest76** [colmap/colmap#650]
Hello

Thanks for the nice SW.
Could you please tell me what is the command line arguments for fixed/shared intrinsic case ? I have a reconstruction problems in which all intrinsic parameters are known.
It seems that there is an explanation for GUI case. But, is there a way to add a command line argument or file to  do the same job ?

Best

**Comment by ahojnnes** [comment]
In the feature extraction stage explicitly set the camera parameters using —ImageReader.camera_params. In the “mapper” stage, set —Mapper.refine_focal_length 0 set —Mapper.refine_principal_point 0 set —Mapper.refine_extra_params 0.

**Comment by thezest76** [comment]
Dear ahojnnes,

Thank you for the quick response.
It appears to me that those flag are used to prevent optimizing intrinsic parameters.
But, I still need to provide actual intrinsic parameters (fx, fy, cx, cy) to the system, at least a focal length, so it doesn't need to guess one, don't I ?
 
Thanks,

**Comment by thezest76** [comment]
That solved my issue. Thanks
