### ISSUE TITLE
OpenCV's SIFT and COLMAP's SIFT

### ISSUE THREAD

**Issue by alexs7** [colmap/colmap#652]
I am trying to match some SIFT feature descriptors I extract from a "query image" using OpenCV with a similar image used for pose estimation in COLMAP.

When I loop through COLMAP's SIFT feature descriptors and try to find a match with my OpenCV feature descriptors it returns nothing..

Does COLMAP uses a different version of SIFT ? Can I replicate that with OpenCV ?

**Comment by tsattler** [comment]
In my experience, the descriptors computed by different SIFT implementations are often not comparable. I assume that this is due to a different ordering of histograms when constructing the descriptor.

COLMAP uses SiftGPU from Changchang Wu. I'd be surprised if it is compatible with OpenCV SIFT.

**Comment by alexs7** [comment]
Ok thanks. I will need to use the SIFT data from COLMAP as I am trying to create a correspondence from SIFT features of a similar image (let's call it query image) to 3D points. I need the data from COLMAP to do that.. 

So if OpenCV's descriptors are not comparable my other option is to use COLMAP's feature extraction on a single image (that is my query image)... That should work 🤔

**Comment by tsattler** [comment]
Note that the ```image_registrator``` functionality provided by COLMAP can also localize novel images against an existing 3D model.

**Comment by alexs7** [comment]
I have been working more than 2 months trying to implement mine.. good to know that there was one along there.. minor detail I missed.. 🤦 Well anyway..
Quick question: does ```image_registrator``` assumes that the new image was taken with the same camera that took the images that were used in the reconstruction ? Also does it output the pose [R|t] matrix ?

**Comment by tsattler** [comment]
How ```image_registrator``` (to the best of my knowledge) works is this:
It uses feature matches between the new images and the images in the 3D model to generate 2D-3D matches. These matches are then used for pose estimation. The new image is added to the model (and a new model is written to a specified output path), but no new 3D points are created and no existing 3D points are modified. The new image needs to be contained in the database used by COLMAP and the intrinsics stored in this model are used for pose estimation. So you can use any camera you want as long as COLMAP supports the corresponding projection model.

**Comment by alexs7** [comment]
Ok this helps. The intrinsics part confuses me a bit. There should be 2 intrinsics matrices. One from the camera that was used to initially create the model, and another one from the new image (given it is from another camera) - which is unknown since we only input 1 (or N) images to the ```image_registrator```. 
If using the intrinsics that are already in the COLMAP model, then that should return bad results (or maybe I got this wrong) ?
Also I assume that a new camera row is added in the camera table ?

**Comment by tsattler** [comment]
For all images that are in the model loaded by the ```image_registrator```, the intrinsics that are stored in the model will be used. For the new image, the intrinsics stored in the database file should be used.

**Comment by alexs7** [comment]
Oh ok I get it now, because the feature extractor in COLMAP also calculates the intrinsics for the new image. Thanks again!

**Comment by ahojnnes** [comment]
Thanks @tsattler for the help!
