### ISSUE TITLE
Option to enforce a single camera per subfolder in the image directory

### ISSUE THREAD

**Issue by meder411** [colmap/colmap#653]
**Is your feature request related to a problem? Please describe.**
I have had a few cases where I've been trying to reconstruct a model from a few different capture sources, but they're not completely random. A typical organization would be a top-level `images` folder with each camera source as it's own folder underneath.

**Describe the solution you'd like**
A flag that, if switched on, affixes the "single camera constraint" to the contents of each subdirectory within the images folder.

**Describe alternatives you've considered**
Currently, it works just fine to just let colmap estimate a camera per image, as they end up converging to the same parameters for images from the same camera, but I do end up with a lot of redundant cameras and there's always the concern that a handful of images may not converge to the right parameters.

**Comment by moepforfreedom** [comment]
i think this is available already, the camera model section in the feature matching dialog has an option called "shared per subfolder"

**Comment by meder411** [comment]
Ah I missed that parameter. Thank you.
