### ISSUE TITLE
Accessing raw depth data

### ISSUE THREAD

**Issue by meder411** [colmap/colmap#66]
Hi Johannes,

After the running the dense  mapper, how can one access the pixel-wise depth estimates per image. I imaging they are found in the 0000xxx.depth_map.txt files in the dense folder, but when I `cat` the file, I see gibberish. I suppose they are stored as uchars, no?

Assuming I can read the raw files into my program, how is the depth info stored in them? Does it contain the image dimensions and such as well?

Thanks!

Marc

**Comment by ahojnnes** [comment]
There are Matlab scripts in `scripts/matlab/read_{depth/normal}_map.m`.
