### ISSUE TITLE
the result of dense reconstruction is bad after model_aligner

### ISSUE THREAD

**Issue by zjbaby** [colmap/colmap#669]
**Describe the bug**
 I use colmap model_aligner command in sparse model, and then I do the dense reconstruction with the model after model_aligner, but I get a terrible results that It only contains 125 points in fused.ply. My reconstruction pipeline is as follows:

1.$ DATASET_PATH=/home

2.$ colmap feature_extractor 
 --database_path $DATASET_PATH/database.db 
 --image_path $DATASET_PATH/images

3.$ colmap exhaustive_matcher 
 --database_path $DATASET_PATH/database.db

4.$ mkdir $DATASET_PATH/sparse

5.$ colmap mapper 
 --database_path $DATASET_PATH/database.db 
 --image_path $DATASET_PATH/images 
 --output_path $DATASET_PATH/sparse

6.$ mkdir $DATASET_PATH/sparse/1

7.$ **colmap model_aligner** 
 --input_path $DATASET_PATH/sparse/0 
**--output_path $DATASET_PATH/sparse/1**
 --ref_images_path $DATASET_PATH/pos.txt

8.$ mkdir $DATASET_PATH/dense

9.$ colmap image_undistorter 
 --image_path $DATASET_PATH/images 
**--input_path $DATASET_PATH/sparse/1** 
 --output_path $DATASET_PATH/dense 
 --output_type COLMAP 
 --max_image_size 4000

10.$ colmap patch_match_stereo 
 --workspace_path $DATASET_PATH/dense 
 --workspace_format COLMAP 
 --PatchMatchStereo.geom_consistency true

11.$ colmap stereo_fusion 
 --workspace_path $DATASET_PATH/dense 
 --workspace_format COLMAP 
 --input_type geometric 
 --output_path $DATASET_PATH/dense/fused.ply

**The fused.ply is bad**, it only have 125 points, **Why? Are my pipeline wrong?**
 if I do dense reconstruction with model before model_aligner(use $DATASET_PATH/sparse/0), I can get a good fused.ply. but I really need the the 3d points' absolute coordinate, so I need do the geo-registration. **What I should do to get a accurate dense cloud point in absolute coordinate system?**

**To Reproduce**
1.$ DATASET_PATH=/home

2.$ colmap feature_extractor 
 --database_path $DATASET_PATH/database.db 
 --image_path $DATASET_PATH/images

3.$ colmap exhaustive_matcher 
 --database_path $DATASET_PATH/database.db

4.$ mkdir $DATASET_PATH/sparse

5.$ colmap mapper 
 --database_path $DATASET_PATH/database.db 
 --image_path $DATASET_PATH/images 
 --output_path $DATASET_PATH/sparse

6.$ mkdir $DATASET_PATH/sparse/1

7.$ colmap model_aligner 
 --input_path $DATASET_PATH/sparse/0 
--output_path $DATASET_PATH/sparse/1
 --ref_images_path $DATASET_PATH/pos.txt

8.$ mkdir $DATASET_PATH/dense

9.$ colmap image_undistorter 
 --image_path $DATASET_PATH/images 
--input_path $DATASET_PATH/sparse/1 
 --output_path $DATASET_PATH/dense 
 --output_type COLMAP 
 --max_image_size 4000

10.$ colmap patch_match_stereo 
 --workspace_path $DATASET_PATH/dense 
 --workspace_format COLMAP 
 --PatchMatchStereo.geom_consistency true

11.$ colmap stereo_fusion 
 --workspace_path $DATASET_PATH/dense 
 --workspace_format COLMAP 
 --input_type geometric 
 --output_path $DATASET_PATH/dense/fused.ply

**Expected behavior**
a good reconstruction result

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zjbaby** [comment]
Does anybody know about this problem?
I also wondering if there is any way to know the transformation matrix between SfM coordinate system and ECEF coordinate system, If there is, can I build the good dense reconstruction model with sparse model in SfM coordinate system firtly,  then do the transformation to convert the fused.ply from SfM coordinate to ECEF coordinate?

**Comment by ahojnnes** [comment]
Yes, you should first compute the dense reconstruction in the SFM coordinate system and then transform the result into ECEF or whatever other target system.

**Comment by zjbaby** [comment]
@ahojnnes 
Hi, I found a transform matrix in model_aligner module: Eigen::Transform<double, 3, Eigen::Affine> transform_  in src/base/similarity_transform.cc . It converts SfM coorinate to ECEF or whatever other target system. Firstly, I record this transform matrix,  then use it to dense reconstruction's coordinate conversion, but i have a question:  I run colmap model_aligner command many time, but I got different transform matrix every time with the same input and  command option, this is Why?

**Comment by ahojnnes** [comment]
Because it uses RANSAC in the robustified cersion, which is a randomized algorithm. You could make it deterministic by setting the SetPRNGSeed function.

**Comment by zjbaby** [comment]
I see, thank you  very much~~~
