### ISSUE TITLE
Segmentation fault when start reconstruction

### ISSUE THREAD

**Issue by zw-ruan** [colmap/colmap#67]
I built the project in Ubuntu 16.04 with cuda 8, when I start reconstruct, get following message:
>  *** Aborted at 1484912515 (unix time) try "date -d @1484912515" if you are using GNU date ***
PC: @           0x82b7b0 Eigen::internal::call_assignment_no_alias<>()
*** SIGSEGV (@0x0) received by PID 2246 (TID 0x7f3f31fb1700) from PID 0; stack trace: ***
    @     0x7f3f5d423390 (unknown)
    @           0x82b7b0 Eigen::internal::call_assignment_no_alias<>()
    @           0xd0d371 ceres::internal::TrustRegionMinimizer::ComputeTrustRegionStep()
    @           0xd0ebf0 ceres::internal::TrustRegionMinimizer::Minimize()
    @           0xce438f ceres::Solver::Solve()
    @           0xce5259 ceres::Solve()
    @           0x852757 colmap::BundleAdjuster::Solve()
    @           0x6a9ccc colmap::IncrementalMapper::AdjustGlobalBundle()
    @           0x6a1dac colmap::(anonymous namespace)::AdjustGlobalBundle()
    @           0x6a3c93 colmap::IncrementalMapperController::Reconstruct()
    @           0x6a42da colmap::IncrementalMapperController::Run()
    @           0x79590c colmap::Thread::RunFunc()
    @     0x7f3f5a8ccc80 (unknown)
    @     0x7f3f5d4196ba start_thread
    @     0x7f3f5a03282d clone
    @                0x0 (unknown)
Segmentation fault (core dumped)

The reconstruction process is fine in Windows 10 with pre-built binary and I tested with South Building dataset.

**Comment by sbarkby** [comment]
I had a similar problem with an Eigen library call failing during reconstruction. Try adding the following line of code to your CMakeLists.txt:

add_definitions(-DEIGEN_DONT_ALIGN)

This disables an optimisation in the eigen library that was causing things to go screwy. Everything seemed to work fine after I did this.

Cheers

Steve

**Comment by ahojnnes** [comment]
Try to downgrade to Eigen 3.2.10. Ubuntu 16.04 ships with 3.3-beta which causes problems. Does that help?

**Comment by zw-ruan** [comment]
I downgraded Eigen to 3.2.10, this time the reconstruction process runs a while, however it aborts after about 10 seconds. I also tried to add following line to  CMakeLists.txt, but it makes no difference. 
> add_definitions(-DEIGEN_DONT_ALIGN)

By the way, I got the following message in terminal:
>ComputeProjection:	invalid device function(8)
terminate called after throwing an instance of 'char const*'
*** Aborted at 1484989195 (unix time) try "date -d @1484989195" if you are using GNU date ***
PC: @     0x7f29278b7428 gsignal
*** SIGABRT (@0x3e800000ac8) received by PID 2760 (TID 0x7f28ff97d700) from PID 2760; stack trace: ***
    @     0x7f292ad79390 (unknown)
    @     0x7f29278b7428 gsignal
    @     0x7f29278b902a abort
    @     0x7f29281f984d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f29281f76b6 (unknown)
    @     0x7f29281f7701 std::terminate()
    @     0x7f2928222d38 (unknown)
    @     0x7f292ad6f6ba start_thread
    @     0x7f292798882d clone
    @                0x0 (unknown)
Aborted (core dumped)

**Comment by ahojnnes** [comment]
Can you try to disable `use_pba` in the reconstruction options?

**Comment by zw-ruan** [comment]
Yes, disabling `use_pba` option do work. Now, I can run reconstruction process completely. Thank you very much.
