### ISSUE TITLE
COLMAP: undistortion button in dense reconstruction greyed out after a successful  sparse reconstruction.

### ISSUE THREAD

**Issue by claudito1991** [colmap/colmap#671]
hello I want to create a cloud of points to try in CLOUD COMPARE and measure distances in it. For this I am doing different tests, in this I filmed a video from which I then took 913 frames (and later reduced to 460). i've loaded these images in COLMAP, I did the feature detection step, the matching, the sparse reconstruction and then when I try to do the dense reconstruction in the window that opens (after having loaded the name of the project and selected the folder) it doesn't let me touch the button "undistortion" because it appears greyed out as if there was nothing loaded to do the reconstruction.

The only thing I can think of is that when I installed CUDA the installer told me that it was not detecting the Visual Studio and therefore I was not going to install anything related to that (then I've downloaded visual studio 2019 from the microsoft page, the free version and the installer still doesn't detect it) but I'm not sure that has to do with this problem

**Desktop (please complete the following information):**
 - OS: Windows 10 - 64 bit
 - 8gb RAM
 - Nvidia GTX 750ti 2gb

**Comment by ahojnnes** [comment]
Any reason you are not downloading the precompiled binaries from the website?

**Comment by claudito1991** [comment]
HI @ahojnnes.Thanks for your answear. I've only downloaded the 'COLMAP -dev-windows.zip' from GitHub. I immersed myself in the forums and saw that the problem was probably a bad installation of CUDA and not of COLMAP. I downloaded several add-ons from MSVS 2019 until CUDA was 'working'. Now my problem is the one I published with the number # 676. If you could help me on that I would appreciate it very much (I'd like to know if it has to do with the binaries you're telling me now)
