### ISSUE TITLE
Database always show nan for pose

### ISSUE THREAD

**Issue by placeforyiming** [colmap/colmap#674]
colmap feature_extractor 
--database_path ./colmap_output/database.db 
--image_path ./rgb --ImageReader.camera_model PINHOLE 
--ImageReader.single_camera 1 
--ImageReader.default_focal_length_factor 0.5

colmap exhaustive_matcher 
--database_path ./colmap_output/database.db

colmap point_triangulator 
--database_path ./colmap_output/database.db 
--image_path ./rgb 
--input_path ./prepare_data_for_colmap 
--output_path ./triang

**Additional context**
![image](https://user-images.githubusercontent.com/22132384/64369324-17329a80-cfea-11e9-9cdb-e95206991abb.png)

**Comment by placeforyiming** [comment]
colmap feature_extractor 
--database_path ./colmap_output/database.db 
--image_path ./rgb 
--ImageReader.camera_model PINHOLE 
--ImageReader.single_camera 1 
--ImageReader.default_focal_length_factor 0.5

**Comment by tsattler** [comment]
@placeforyiming The database does not get updated after a reconstruction. All parameters computed during the reconstruction process are only stored in the output files.

**Comment by placeforyiming** [comment]
> @placeforyiming The database does not get updated after a reconstruction. All parameters computed during the reconstruction process are only stored in the output files.

You mean the sparse folder under workspace? But I still got nan after reading data from images.bin

![image](https://user-images.githubusercontent.com/22132384/64441016-0a21b400-d09b-11e9-861e-3e3c3b7590ef.png)

**Comment by tsattler** [comment]
@placeforyiming I'd assume this is due to the way that you load the `images.bin` file. I doubt that `fromfile` handles the custom format of the `images.bin` file (which does not only contain numbers but also strings). Colmap provides python scripts for loading reconstructions.

**Comment by placeforyiming** [comment]
> @placeforyiming I'd assume this is due to the way that you load the `images.bin` file. I doubt that `fromfile` handles the custom format of the `images.bin` file (which does not only contain numbers but also strings). Colmap provides python scripts for loading reconstructions.

Thanks!
I found the script and read the data. It looks good!
But after reconstruction, I found only one image get a good depth map, and all the other images perform very bad. Do you have any clues how this happened?

Good one (image, gt, reconstruction result):

![3](https://user-images.githubusercontent.com/22132384/64445438-7ead2080-d0a4-11e9-8573-bc3cddb8451a.png)
![2](https://user-images.githubusercontent.com/22132384/64445443-8240a780-d0a4-11e9-930f-72fcac219aa4.png)
![1](https://user-images.githubusercontent.com/22132384/64445446-840a6b00-d0a4-11e9-8bb2-d7e3814bf26c.png)

Bad others:

![6](https://user-images.githubusercontent.com/22132384/64445559-c633ac80-d0a4-11e9-98a2-89e31d239a27.png)
![5](https://user-images.githubusercontent.com/22132384/64445563-c7fd7000-d0a4-11e9-8313-a9dc8f507ac9.png)
![4](https://user-images.githubusercontent.com/22132384/64445568-c9c73380-d0a4-11e9-99a1-0ab7be903709.png)


![9](https://user-images.githubusercontent.com/22132384/64445574-cd5aba80-d0a4-11e9-9e4f-497a337161b6.png)
![8](https://user-images.githubusercontent.com/22132384/64445577-cf247e00-d0a4-11e9-9160-2cefdf9d7298.png)
![7](https://user-images.githubusercontent.com/22132384/64445581-d0ee4180-d0a4-11e9-9bb6-0199fe8cdc3d.png)

**Comment by tsattler** [comment]
@placeforyiming Looks like the other two images are rather weakly textured. Recovering a good depth map from such images is hard when using only photometric stereo. Might also be that their corresponding poses are bad.

**Comment by placeforyiming** [comment]
@tsattler   Here is my findings after trying different options provided by colmap:

1. Blindly choose automatic reconstruction
     Can get much more depth values, however colmap will seperate images into different scenes and assign different camera parameters even all those images are captured in one room. I compared the depth map with ground truth, then found I need to give a scale factor (around 5 in my case) for each scene to make it closer to gt (not very close).  

2. Manually provide camera parameters and pose.
    If colmap can successfully predict a depth map, it would be very accurate(very). However, for my 193 images, colmap only gave me 3 depth map with rich depth value.

**Comment by placeforyiming** [comment]
@tsattler  And I also check the predicted camera pose by automatic reconstruction, then found it's around 1m between two images, but it should be around 10cm.

Should I open a new issue for this?

**Comment by placeforyiming** [comment]
@tsattler  So I don't think this poor performance is because of textureless region, but more like because of the small relative motion.

**Comment by tsattler** [comment]
@placeforyiming Please note that the units in a Colmap model have no physical meaning (i.e., they do not correspond to meters, centimeters, etc.). Without any additional information, e.g., the distance between two cameras or points in a scene, the absolute scale of a scene cannot be recovered from images alone as scaling the scene does not change the reprojection error that is minimized during the reconstruction process.

**Comment by placeforyiming** [comment]
> @placeforyiming Please note that the units in a Colmap model have no physical meaning (i.e., they do not correspond to meters, centimeters, etc.). Without any additional information, e.g., the distance between two cameras or points in a scene, the absolute scale of a scene cannot be recovered from images alone as scaling the scene does not change the reprojection error that is minimized during the reconstruction process.

Yes, I understand this. I mean it looks like the backend algorithm of colmap prefer a large relative camera pose which is reasonable for outdoor. For my indoor case, I provide the pose for each image, but it can't grasp consistent features  just like automatic reconstruction. 

I think the ratio between depth range and relative pose may be the problem. For my case, the depth range is from 0.2m to 10m, but the relative pose is around 0.1m. Maybe this is the reason?

**Comment by tsattler** [comment]
@placeforyiming Relative baseline can indeed be an issue. In order to initialize a 3D reconstruction, Colmap requires sufficient parallax in the initial pair is chooses. This is tested by checking if the feature matches can be described by a homography. If your baseline is small wrt. the scene, this check might fail.
3D points are triangulated only if the angle between the two rays is large enough (since the resulting 3D point is ill-localized otherwise). If the baseline is too small wrt. the depth of the point, this will be the case. I'd assume that the same holds during the dense reconstruction phase. 
For dense reconstruction, there is a relationship between disparity, depth, and baseline (slide 16 from http://www.cs.toronto.edu/~fidler/slides/2015/CSC420/lecture12_hres.pdf has the formula for a pair of parallel cameras). If the baseline is too small wrt. the depth, it can be impossible to triangulate the 3D point.

**Comment by placeforyiming** [comment]
> @placeforyiming Relative baseline can indeed be an issue. In order to initialize a 3D reconstruction, Colmap requires sufficient parallax in the initial pair is chooses. This is tested by checking if the feature matches can be described by a homography. If your baseline is small wrt. the scene, this check might fail.
> 3D points are triangulated only if the angle between the two rays is large enough (since the resulting 3D point is ill-localized otherwise). If the baseline is too small wrt. the depth of the point, this will be the case. I'd assume that the same holds during the dense reconstruction phase.
> For dense reconstruction, there is a relationship between disparity, depth, and baseline (slide 16 from http://www.cs.toronto.edu/~fidler/slides/2015/CSC420/lecture12_hres.pdf has the formula for a pair of parallel cameras). If the baseline is too small wrt. the depth, it can be impossible to triangulate the 3D point.

@tsattler 
Very helpful information, Thanks!
