### ISSUE TITLE
COLMAP: Dense reconstruction taking too long

### ISSUE THREAD

**Issue by claudito1991** [colmap/colmap#676]
Hi, after a lot of installing and unistalling and re installing again CUDA, MSVS 2019, the complements, the compiler, etc. i finally managed to get my COLMAP up and running, that meaning that now my 'undistortion' button and 'stero' button doesn''t appear greyed out. i have changed the registry too to avoid having a crash of the program because the timeouts of the GPU. 

i have exctracted all the frames of a HD video (mp4 format) of 240mb with GIMP, of a total of 913 images i have lowered the density to 460 and get COLMAP running. I know that my RIG ins't the most appropiate for the task at hand but it's been 10 hours of proccessing and it's still computing the dense model. It seems very slow to me but it didn't crash and i want to know if this is normal in this case with this equipment.

Windows 10 64 bit
8 GB RAM
Nvidia Geforce 750 Ti 2gb
CUDA 10.1
MSVS 2019

Any help would be much appreciated

**Comment by tsattler** [comment]
@claudito1991 On a GeForce RTX 2080 with 8GB, depth map estimation takes multiple seconds for me (on Ubuntu 18.04 with 64GB of RAM). The exact time depends on the image resolution. In my experience, the dense reconstruction part is very time consuming.

**Comment by claudito1991** [comment]
Well, an update. Yesterday I did a test. Take 22 photos of 3.5mb each. And I loaded them into COLMAP, again, I successfully completed the following steps:
-Feature extraction
-Feature matching
-Sparse reconstruction
-undistortion
and i have a crash in this step:
-Dense reconstruction. The program worked here for 50 minutes doing the different sweeps and the "processing views" advanced from 0 to 22. When it reached 22 it returned to 1 and then it  shut it down for it's own

I took the same 22 photos and took them to VisualSFM, all the steps were successful and the dense reconstruction lasted 5.55 minutes

I am definitely doing something very wrong in COLMAP but I can't find what, and in the issues I didn't see any similar.

Help.

**Comment by tsattler** [comment]
@claudito1991 Colmap performs two passes over the data when computing depth maps, this is why you had the impression that it would return to 1. The second pass typically improves the depth map quality significantly.

If Colmap crashes, could it be that it is running out of memory? Did you had a look [here](https://colmap.github.io/faq.html#reduce-memory-usage-during-dense-reconstruction) and [here](https://colmap.github.io/faq.html#speedup-dense-reconstruction)?

VisualSFM's dense reconstruction part is indeed faster (and does not use a GPU). However, the results are typically less good than Colmap's.

**Comment by claudito1991** [comment]
@tsattler Thanks for time man. I certainly looked at those sections in the documentation and it's a bit embarrassing to say but I don't know where to change those parameters in COLMAP. I understand that they cannot be changed from the GUI and must be changed with the command-line but I don't know how to do it and I didn't see it explained anywhere. If you could help me do it I would appreciate it very much

**Comment by claudito1991** [comment]
Solved. Thank you very much guys. I've changed 'cache-size' of stereo and fussion from 32 to 8gb and max-image-size of patch_match_stereo from 2000 to 1000. And got the model complete.
![image](https://user-images.githubusercontent.com/30451301/64494470-b7dfbf00-d263-11e9-8c28-62fc5de2ed3d.png)

**Comment by Oreobun** [comment]
@claudito1991  do you mind sharing how you change  '**cache-size' of stereo and fussion from 32 to 8gb and max-image-size of patch_match_stereo from 2000 to 1000** using the command prompt? I am facing the same issue right now. Thanks in advance ^^

**Comment by ahojnnes** [comment]
`--PatchMatchStereo.max_image_size 1000 --PatchMatchStereo.cache_size 8`
