### ISSUE TITLE
How to apply colmap on forward moving videos?

### ISSUE THREAD

**Issue by placeforyiming** [colmap/colmap#677]
The forward baseline is different with parallel cameras, so what should I do if I have a video with forward moving images?

**Comment by ahojnnes** [comment]
Forward motion is typically a difficult scenario for SFM, because features in the center of the image are at infinity and side features move fast out of the field of view, meaning there are relatively short track lengths. 

Regarding your specific issue: it seems like you a interpreting the database entries as the output of the reconstruction. This is not correct, as the sparse reconstruction results are written to the cameras/images/points3D.bin/txt. Please refer to the documentation for more details.

**Comment by placeforyiming** [comment]
> Forward motion is typically a difficult scenario for SFM, because features in the center of the image are at infinity and side features move fast out of the field of view, meaning there are relatively short track lengths.
> 
> Regarding your specific issue: it seems like you a interpreting the database entries as the output of the reconstruction. This is not correct, as the sparse reconstruction results are written to the cameras/images/points3D.bin/txt. Please refer to the documentation for more details.

@ahojnnes  I got the value from points3D.bin, it looks good.
Actually, I have all the poses, but after feeding them into the reconstruction part, I found only very few images got a pretty good results(3/193). Most of the others failed. After discussing with @tsattler in #674 , I got the message that this may because the small baseline of forward moving, so if I have all the poses and camera parameters, how should I choose the settings to make colmap can reconstruct depth map better?

Just address my problem here from #674 :

I tried two mode:

1. Blindly choose automatic reconstruction
Can get much more depth values, however colmap will seperate images into different scenes and assign different camera parameters even all those images are captured in one room. I compared the depth map with ground truth, then found I need to give a scale factor (around 5 in my case) for each scene to make it closer to gt (not very close). The predicted relative pose is also much larger than gt.

2. Manually provide camera parameters and pose.
If colmap can successfully predict a depth map, it would be very accurate(very). However, for my 193 images, colmap only gave me 3 depth map with rich depth value.

**Comment by tsattler** [comment]
@placeforyiming The issue you are running into is more one of properly capturing data than with Colmap. If your baseline is too small with respect to the depth of the scene, then it is nearly impossible to get depth from stereo methods. Forward motion will compound the problem.

**Comment by placeforyiming** [comment]
@tsattler 
The curious part is the automatic reconstruction mode can predict depth value for much more pixels, that's why I'm trying to find if there are some parts I can manually tune under the colmap framework with known poses.

Also, is there any paper about manually selecting source images for each target by using proper relative pose? In colmap, the sparse model is used to automatically select neighboring images, so I'm thinking if I skip this step and manually select source images  with relative large baseline for each target, the result may could be better.
