### ISSUE TITLE
COLMAP: List of parameters or variables

### ISSUE THREAD

**Issue by claudito1991** [colmap/colmap#684]
Hello, I was looking for somewhere to read what each parameter of COLMAP does to learn more about which one should modify when it comes to obtaining cleaner and more accurate models. Is there any place where this can be found?

**Comment by tsattler** [comment]
To the best of my knowledge, there is no such documentation.

In my experience, most parameters are rather self-explanatory if you are familiar with how Structure-from-Motion, feature matching, dense reconstruction, etc. work. For parameters that I do not understand, I typically look at the code to determine what they do.

**Comment by claudito1991** [comment]
Hello, thanks for answering me. I understand, could you recommend me any bibliography to get my hands to those topics? I do understand how the program works, but just on the surface.

**Comment by tsattler** [comment]
I think the "Structure-from-Motion Revisited" paper which describes the Structure-from-Motion part of Colmap and the "Pixelwise View Selection for Unstructured Multi-View Stereo" paper that describes the dense reconstruction part are good starting points for technical details (see https://colmap.github.io/). If you want to have a general overview, I recommend this book: http://szeliski.org/Book/

**Comment by claudito1991** [comment]
Very grateful for your help. I will read that material!
