### ISSUE TITLE
Dense sterio reconstruction requires CUDA (Ubuntu 18.04, CUDA 10.0 , nvidia-driver 418)

### ISSUE THREAD

**Issue by GabbySuwichaya** [colmap/colmap#685]
**Describe the bug**

> Dense sterio reconstruction requires CUDA which does not detect on your computer. 

**My system**

Ubuntu 18.04, 
CUDA 10.0.  
nvidia-driver 418

I don't know why COLMAP cannot detect the CUDA. 
PS. I tried running this on **gerrard-hall** dataset. 

**To Reproduce**

1. I follow the guidance about the command-line  [https://colmap.github.io/cli.html](url)
2. I got the error after running the following commands: 
 
colmap image_undistorter \
    --image_path $DATASET_PATH/images \
    --input_path $DATASET_PATH/sparse/0 \
    --output_path $DATASET_PATH/dense \
    --output_type COLMAP \
    --max_image_size 2000

and 

colmap patch_match_stereo \
    --workspace_path $DATASET_PATH/dense \
    --workspace_format COLMAP \
    --PatchMatchStereo.geom_consistency true 

 
**Screenshots**

![Screenshot from 2019-09-19 09-26-21](https://user-images.githubusercontent.com/49115268/65198845-9da5ac80-dabf-11e9-82b7-2cfc064ca504.png)
 

**Additional context**
 

=========================================================================== 

Image undistortion

=========================================================================== 

Undistorting image [1/100]
Undistorting image [2/100]
Undistorting image [3/100]
Undistorting image [4/100]
...
.

..
Undistorting image [97/100]
Undistorting image [98/100]
Undistorting image [99/100]
Undistorting image [100/100]
Writing reconstruction...
Writing configuration...
Writing scripts...
Elapsed time: 0.775 [minutes]
ERROR: Dense stereo reconstruction requires CUDA, which is not available on your system.

StereoFusion::Options

max_image_size: -1
min_num_pixels: 5
max_num_pixels: 10000
max_traversal_depth: 100
max_reproj_error: 2
max_depth_error: 0.01
max_normal_error: 10
check_num_images: 50
cache_size: 32

Reading workspace...
Reading configuration...
WARNING: Ignoring image IMG_2387.JPG, because input does not exist.
WARNING: Ignoring image IMG_2401.JPG, because input does not exist.
WARNING: Ignoring image IMG_2383.JPG, because input does not exist.
WARNING: Ignoring image IMG_2341.JPG, because input does not exist.
WARNING: Ignoring image IMG_2336.JPG, because input does not exist.
WARNING: Ignoring image IMG_2422.JPG, because input does not exist.
WARNING: Ignoring image IMG_2402.JPG, because input does not exist.
...
...
..

WARNING: Ignoring image IMG_2403.JPG, because input does not exist.
WARNING: Ignoring image IMG_2407.JPG, because input does not exist.
WARNING: Ignoring image IMG_2390.JPG, because input does not exist.
WARNING: Ignoring image IMG_2348.JPG, because input does not exist.
Fusing image [1/100] in 0.000s (0 points)
WARNING: Could not fuse any points. This is likely caused by incorrect settings - filtering must be enabled for the last call to patch match stereo.
Number of fused points: 0
Elapsed time: 0.003 [minutes]
 
============================================================

**Comment by ahojnnes** [comment]
Can you show the whole script? It seems like you are providing the wrong paths.

**Comment by GabbySuwichaya** [comment]
Here is the script file that I used. It is the modified version of the one that you provided on the tutorial cite (). However, I actually avoid this problem in a hard way, because I thought that the problem was caused by the graphical card and CUDA version. That is, I reinstall my laptop to Ubuntu 16.04, as well as reinstall CUDA 9.0 and NVIDIA 384. It seems that with the newly reinstalled laptop, I can run the shell script just fine. Anyway, please feel free to give me comments on my script file.         

`echo =+++++ We are executing "$0" on "$1"  ++++=

DATASET_PATH=$1
Dataset=$(basename "$DATASET_PATH" )
COUNT=$2

echo ==================== "$COUNT".1 Feature extraction "$Dataset"====================

colmap feature_extractor \
   --database_path $DATASET_PATH/database.db \
   --image_path $DATASET_PATH/images

echo ==================== "$COUNT".2 Exhausive matching "$Dataset" ====================

colmap exhaustive_matcher \
   --database_path $DATASET_PATH/database.db

mkdir $DATASET_PATH/sparse

echo ==================== "$COUNT".3 Mapper "$Dataset" ====================

colmap mapper \
    --database_path $DATASET_PATH/database.db \
    --image_path $DATASET_PATH/images \
    --output_path $DATASET_PATH/sparse

mkdir $DATASET_PATH/dense

echo ==================== "$COUNT".4 Image Undistorter "$Dataset" ====================

colmap image_undistorter \
    --image_path $DATASET_PATH/images \
    --input_path $DATASET_PATH/sparse/0 \
    --output_path $DATASET_PATH/dense \
    --output_type COLMAP \
    --max_image_size 2000

echo ====================  "$COUNT".5  Patch match stereo "$Dataset"====================

colmap patch_match_stereo \
    --workspace_path $DATASET_PATH/dense \
    --workspace_format COLMAP \
    --PatchMatchStereo.geom_consistency true

echo ==================== "$COUNT".6 Stereo Fusion "$Dataset"====================

colmap stereo_fusion \
    --workspace_path $DATASET_PATH/dense \
    --workspace_format COLMAP \
    --input_type geometric \
    --output_path $DATASET_PATH/dense/fused.ply

echo ==================== "$COUNT".7  Poisson Mesher "$Dataset" ====================

colmap poisson_mesher \
    --input_path $DATASET_PATH/dense/fused.ply \
    --output_path $DATASET_PATH/dense/meshed-poisson.ply

echo ==================== "$COUNT".8   Delaunay Mesher "$Dataset" ====================

colmap delaunay_mesher \
    --input_path $DATASET_PATH/dense \
    --output_path $DATASET_PATH/dense/meshed-delaunay.ply`

**Comment by wanfengkai** [comment]
Hi, I just have the same issue: CUDA, nvidia are all properly installed on my Ubuntu 18 VM. Also, executing *nvcc -V*  and *nvidia-smi* work fine(Which means your CUDA configuration is fine) but colmap keeps raise the same error message. 

Just post it here in case anyone may come across it later. 

My solution,
You do not need to downgrade your OS version actually. You just need to re-install colmap as mentioned here: https://colmap.github.io/install.html#linux

Reason: sometimes it could be that when you install colmap you didn't install CUDA first.

**Comment by libing64** [comment]
problem fixed  by reinstalling colmap from source(with CUDA enabled)

**Comment by lucascassiano** [comment]
I used neuralangelo's colmap docker image:

FROM nvcr.io/nvidia/cuda:11.8.0-devel-ubuntu20.04
ARG DEBIAN_FRONTEND=noninteractive

# colmap dependencies
RUN apt-get update && apt-get install -y \
    git \
    cmake \
    ninja-build \
    build-essential \
    libboost-program-options-dev \
    libboost-filesystem-dev \
    libboost-graph-dev \
    libboost-system-dev \
    libboost-test-dev \
    libeigen3-dev \
    libflann-dev \
    libfreeimage-dev \
    libmetis-dev \
    libgoogle-glog-dev \
    libgflags-dev \
    libsqlite3-dev \
    libglew-dev \
    qtbase5-dev \
    libqt5opengl5-dev \
    libcgal-dev \
    libceres-dev
# headless servers
RUN apt-get update && apt-get install -y \
    xvfb
# Colmap
RUN git clone https://github.com/colmap/colmap.git && cd colmap && git checkout 3.8
RUN cd colmap && mkdir build && cd build && cmake .. -DCUDA_ENABLED=ON -DCMAKE_CUDA_ARCHITECTURES="70;72;75;80;86" -GNinja
RUN cd colmap/build && ninja && ninja install

# additional python packages
RUN apt-get update && apt-get install -y \
    pip \
    ffmpeg
RUN pip install \
    addict \
    k3d \
    opencv-python-headless \
    pillow \
    plotly \
    pyyaml \
    trimesh

#rest of your docker image
