### ISSUE TITLE
Headless install mode for docker

### ISSUE THREAD

**Issue by placeforyiming** [colmap/colmap#689]
The command line mode of colmap in docker still needs display, including X server and graphical GPU acceleration. 

Find two similar issues:

#570  But I can't find X in travis.yml script

#45  But xvfb only provides a virtual X server which can't enable GPU hardware acceleration.

Now, I'm trying to build a docker with virtualgl+turboVNC for colmap, just curious is there any simpler solution to enable colmap work with GPU in docker or server without display?

**Comment by ahojnnes** [comment]
Use CUDA which doesn't require OpenGL.

**Comment by placeforyiming** [comment]
> Use CUDA which doesn't require OpenGL.

Yes, I can run GPU version of tensorflow in my docker, but  colmap still can't take use GPU. The error message is the same as :

qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.

**Comment by placeforyiming** [comment]
The command line mode should can avoid display, but it seems still using display somewhere.

**Comment by placeforyiming** [comment]
Updated : 
virtalgl can allow colmap use gpu in docker: 
`vglrun colmap feature_extractor --database_path  --ImageReader.camera_model=PINHOLE  --ImageReader.single_camera=1 --SiftExtraction.use_gpu=1`

but met a new problem with cuda

> ERROR: Dense stereo reconstruction requires CUDA, which is not available on your system.

although nvidia-smi showed 

> CUDA Version: 10.0

to me

**Comment by ahojnnes** [comment]
You need to make sure that CUDA is detected when running the CMake command. Can you show the output of CMake?

**Comment by placeforyiming** [comment]
> You need to make sure that CUDA is detected when running the CMake command. Can you show the output of CMake?

CMake works well

Have no idea why strange things happen

But it's fine now, I found this docker  https://hub.docker.com/r/geki/colmap
which works pretty well.

So just decide to use this docker.

Thanks for the discussion!
