### ISSUE TITLE
Error importing features: variable NUM_FEATURES

### ISSUE THREAD

**Issue by pogilon** [colmap/colmap#69]
When I try to import my features and run "exhaustive matching" I get the error below. I can see that the variable NUM_FEATURES from the format file is being read both as the "number of features" and as the "number of dimensions" for each feature. Therefore, if I specify NUM_FEATURES=1000 I get a dimensionality check error (1000>=128). However, if I set NUM_FEATURES=128 only 128 features are read. Also, what would be the best practice to incorporate feature descriptors with less than 128 dimensions into COLMAP? Should we specify the remaining features as "0"? Are you adding this capability soon? Thank you.

-------------------------------------------------------------------------------------------------------------
Format file
--------------------------------------------------------------------------------------------------------------
"NUM_FEATURES 128
X Y SCALE ORIENTATION D_1 D_2 D_3 ... D_128
...
X Y SCALE ORIENTATION D_1 D_2 D_3 ... D_128

-------------------------------------------------------------------------------------------------------------
ERROR
--------------------------------------------------------------------------------------------------------------

Matching block [1/1, 1/1]F0124 23:07:31.995400 24767 feature_matching.cc:1721] Check failed: descriptors1->cols() == 128 (1000 vs. 128) 
*** Check failure stack trace: ***
    @     0x7f67252ee5cd  google::LogMessage::Fail()
    @     0x7f67252f0433  google::LogMessage::SendToLog()
    @     0x7f67252ee15b  google::LogMessage::Flush()
    @     0x7f67252f0e1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x50d448  colmap::MatchSiftFeaturesGPU()
    @           0x5134c3  colmap::SiftFeatureMatcher::MatchImagePairsGPU()
    @           0x514959  colmap::SiftFeatureMatcher::MatchImagePairs()
    @           0x519c3f  colmap::ExhaustiveFeatureMatcher::Run()
    @           0x592a6c  colmap::Thread::RunFunc()
    @     0x7f67222f0c80  (unknown)
    @     0x7f6724e3d6ba  start_thread
    @     0x7f6721a5682d  clone
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by pogilon** [comment]
if NUM Features==128 and there are 1000 features with 128 Dimensions
      sqlite3 output for descriptors table:
      128|128|

if NUM Features==1000 and there are 1000 features with 128 Dimensions
      sqlite3 output for descriptors table:
      1000|1000|

**Comment by ahojnnes** [comment]
I am not sure if I understand. SIFT features always must have 128 dimensions and NUM_FEATURES must equal the number of lines in the text file. Can you post an example?

**Comment by pogilon** [comment]
Please see attached for a sample of a feature text file. If I import a file like this one with NUM_FEATURES=1000, it gives me the error below. It looks like it is comparing with the 128 dimensions of the SIFT. However, if I set NUM_FEATURES=128, this error does not occur, but only 128 features are added to the database.Thank you.
[P1180141.JPG.txt](https://github.com/colmap/colmap/files/743748/P1180141.JPG.txt)

Matching block [1/1, 1/1]F0124 23:07:31.995400 24767 feature_matching.cc:1721] Check failed: descriptors1->cols() == 128 (1000 vs. 128)
*** Check failure stack trace: ***
@ 0x7f67252ee5cd google::LogMessage::Fail()
@ 0x7f67252f0433 google::LogMessage::SendToLog()
@ 0x7f67252ee15b google::LogMessage::Flush()
@ 0x7f67252f0e1e google::LogMessageFatal::~LogMessageFatal()
@ 0x50d448 colmap::MatchSiftFeaturesGPU()
@ 0x5134c3 colmap::SiftFeatureMatcher::MatchImagePairsGPU()
@ 0x514959 colmap::SiftFeatureMatcher::MatchImagePairs()
@ 0x519c3f colmap::ExhaustiveFeatureMatcher::Run()
@ 0x592a6c colmap::Thread::RunFunc()
@ 0x7f67222f0c80 (unknown)
@ 0x7f6724e3d6ba start_thread
@ 0x7f6721a5682d clone
@ (nil) (unknown)
Aborted (core dumped)

**Comment by ahojnnes** [comment]
The first two lines must be:

```
1000 128
2433.0 1208.0 31.0 220.837127686 73 68 21 103 53 62 70 48 101 170 107 68 255 113 25 246 16 100 108 46 201 176 121 13 165 255 64 16 74 243 64 40  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
...
```

You must provide both the number of features and the dimensionality. It's the standard SIFT feature file format. I'll close as resolved, feel free to reopen if the issue still remains.
