### ISSUE TITLE
Check failed: num_params == camera.NumParams() (3 vs. 8)

### ISSUE THREAD

**Issue by GabbySuwichaya** [colmap/colmap#690]
**Describe the bug**
I have tried using other feature extraction, descritors, and matching method on Gerrard Hall dataset which leads me to create a new database.db for COLMAP to perform sparse reconstruction. 

However, I get the following errors after using my new dababase.db (I think). 

![NewDatabase_error](https://user-images.githubusercontent.com/49115268/65505175-95a49d00-df03-11e9-9a2f-3fa78455cae2.png)

**To Reproduce**
Please try using my new database:  
https://drive.google.com/file/d/1vVa0e1vBd-vJvBobXBUtk2x2rYcNjJCb/view?usp=sharing

And here is my shell script I used to execute COLMAP: https://drive.google.com/file/d/1B8MJBi_mHkGTfVZV_017OhAOn0vZ7h6P/view?usp=sharing

**Comment by tsattler** [comment]
Looking at the console output, you seem to be using an existing database which already contains features for the images. My guess is that this database uses a different camera model and something goes wrong when you are running the feature extractor again.
I would suggest to start with a new database from scratch.

**Comment by GabbySuwichaya** [comment]
Hi, tsattler. Your analysis is right. I copied the camera setting (manually) from the database.db that came with Gerrard Hall dataset. And I used the key points and descriptors extracted by D2-Net. I just wanted to figure out a way to reproduce the results in the D2-Net's paper. 

Since you already mentioned this, could you please recommend how to use the key points and descriptors extracted from other packages such as D2-Net for the sparse reconstruction? The database.db and the directory of the images are the required input for reconstruction.

**Comment by tsattler** [comment]
You can have a look here: https://github.com/tsattler/visuallocalizationbenchmark/tree/master/local_feature_evaluation

**Comment by GabbySuwichaya** [comment]
Hi tsattler, thanks so much  :D. 
Will not forget to refer to your work when it's done.
