### ISSUE TITLE
corresponding pixels for fused dense 3D points  

### ISSUE THREAD

**Issue by bbzh** [colmap/colmap#696]
Hi, I would like to ask if it is possible to get the 2D pixes whose 3D points are used for fusing a point in the fusion step? In other words, for each 3D points in the final dense point clouds, how to retrive its corrsponding 2D/3D points used to fuse the point? Thanks!

**Comment by tsattler** [comment]
The `.vis` file created by the fusion process should give you the information from which images which 3D point was created. Projecting the points into the corresponding images gives you the pixel coordinates.
I recommend looking at the code to figure out what exactly the format of the `.vis` file is.
