### ISSUE TITLE
Output txt format from command line directly?

### ISSUE THREAD

**Issue by Yuliang-Zou** [colmap/colmap#697]
Hi, I wonder if I can get txt format output (instead of bin) directly when I use `automatic_reconstructor`. I did not find this option in the command line.

**Comment by mihaidusmanu** [comment]
Hello. You can use the `model_converter` utility to conver a binary reconstruction to raw text. 

```
colmap model_converter \
    --input_path path-to-binary-reconstruction \
    --output_path path-to-txt-reconstruction \
    --output_type TXT
```

**Comment by Yuliang-Zou** [comment]
Thanks @mihaidusmanu . I also wonder why there could be multiple folders under `sparse` and `dense` (for example, 0, 1, 2, ..., etc.). Will the `Point3D_ID` be overlapping in those folders? Is the same id means the same point?

Thank you and look forward to your response.

**Comment by mihaidusmanu** [comment]
Multiple folders under `sparse` means that there were multiple (isolated) reconstructions - generally the first reconstruction is the one containing most images (`sparse/0`), but you might want to double check this.

To my knowledge, the same `point3D_id` can appear in multiple reconstructions, but it corresponds to a different 3D point - the `point3D_id` start from scratch for each model. 

Maybe somebody else can join in and give you a more complete answer.
