### ISSUE TITLE
SetConstantTvec() doesn't work properly

### ISSUE THREAD

**Issue by Beniko95J** [colmap/colmap#699]
Hi, I used to report an issue about the scale drifting in COLMAP here #670.  Now I have gone through the code for the bundle adjustment in incremental mapping and I wonder that the problem is in the SetConstantTvec() function. The code for fixing the 7-DoFs of the bundle adjustment problem is as follows in COLMAP:

```cpp
  // Fix 7-DOFs of the bundle adjustment problem.
  ba_config.SetConstantPose(reg_image_ids[0]);
  if (!options.fix_existing_images ||
      !existing_image_ids_.count(reg_image_ids[1])) {
    ba_config.SetConstantTvec(reg_image_ids[1], {0});
  }
```

The second parameter of SetConstantTvec is a vector, and is used as the variable constant_tvec_idxs in the following codes in bundle_adjustment.cc

```cpp
      if (config_.HasConstantTvec(image_id)) {
        const std::vector<int>& constant_tvec_idxs =
            config_.ConstantTvec(image_id);
        ceres::SubsetParameterization* tvec_parameterization =
            new ceres::SubsetParameterization(3, constant_tvec_idxs);
        problem_->SetParameterization(tvec_data, tvec_parameterization);
```

I have searched the usage of ceres::SubsetParameterization in the Internet:

1. https://imkaywu.github.io/blog/2017/09/sfm-bundle-adjustment/
2. https://groups.google.com/forum/#!topic/ceres-solver/T_1hm-UNvJs

and I think the constant_tvec_idxs means which index of dimension you want to fix, e.g the tvec here has 3 dimensions, and I want to fix all of them, then I should give the vector {0, 1, 2} to it. However, as the first code block shows, COLMAP gives the vector {0}, which I think it only fix the first dimension of tvec.

And I have done an experiment that I let COLMAP print the image id and the corresponding tvec and qvec of the image set in the SetConstantTvec() function, where I found that only the first dimension of the tvec if fixed.

```
Before iterative global refinement
Image_id1 = 1
Image_id1's qvec = 1 0 0 0
Image_id1's tvec = 0 0 0
Image_id2 = 683
Image_id2's qvec =    0.968989 -0.00810138   -0.236397  -0.0714941
Image_id2's tvec =  -0.138398 -0.0668607  -0.147347

After iterative global refinement
Image_id1 = 1
Image_id1's qvec = 1 0 0 0
Image_id1's tvec = 0 0 0
Image_id2 = 683
Image_id2's qvec =    0.970948 -0.00545753   -0.216007   -0.102812
Image_id2's tvec =  -0.138398 -0.0946807    0.10381
```

I think this may be the core of my problem, so I modified the {0} to {0,1,2}, while I get an error message when running

```
==============================================================================
Global bundle adjustment
==============================================================================

F0930 18:33:27.830612 10863 parameter_block.h:193] Check failed: new_parameterization->LocalSize() > 0 (0 vs. 0) Invalid parameterization. Parameterizations must have a positive dimensional tangent space.
```

Would you please give me some ideas about whether COLMAP has a mistake in fixing the 7DoF of the model and the reason for this error message? 

Thanks!

**Comment by ahojnnes** [comment]
Use SetParameterBlockConstant instead.

**Comment by yuancaimaiyi** [comment]
@Beniko95J  Do you solve it? I also want to fix the translation of all .I meet same problem
