### ISSUE TITLE
Default max error setting in model aligner gives error

### ISSUE THREAD

**Issue by meder411** [colmap/colmap#70]
When running the `model_aligner` binary from the command-line, the default value for the `robust_alignment_max_error` parameter is 0. However, in src/optim/ransac.h:50 the check is for strictly greater than 0. This appears  to cause an error when that parameter is left to the default

```
>> model_aligner --input_path ~/1 --ref_images_path ~/1_ref_imgs --output_path ~

Aligning reconstruction
-----------------------
 => Using 5 reference images
F0128 14:22:51.003433 32359 ransac.h:50] Check failed: max_error > 0 (0 vs. 0) 
*** Check failure stack trace: ***
    @     0x7f3f7d94bdaa  (unknown)
    @     0x7f3f7d94bce4  (unknown)
    @     0x7f3f7d94b6e6  (unknown)
    @     0x7f3f7d94e687  (unknown)
    @           0x507196  colmap::Reconstruction::AlignRobust()
    @           0x4e448b  main
    @     0x7f3f7b7e1f45  (unknown)
    @           0x4e5b97  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
```

The obvious solution is to set that parameter with a positive value (e.g. `--robust_alignmen_max_error 1`), but as it's not a required setting, I presume you want the default not to error out.

**Comment by ahojnnes** [comment]
Hi Marc,

This is intentional, since the user should provide a value, since it is impossible to guess the scale of the model a priori. A more informative error message should now be printed.
