### ISSUE TITLE
What feature matching is used in matches_importer ?

### ISSUE THREAD

**Issue by GabbySuwichaya** [colmap/colmap#700]
Hi. I am trying to compare the performance of different types of features, aside from SIFT in performing 3D reconstruction. 

If I provide the descriptors, keypoints, and a list of image pairs (without feature matching) into  COLMAP's **matches_importer** , I notice that I can create a complete database.db (matches, keypoints, and descriptors). 

However, I wonder how the feature matches is done at the background ?

**Comment by tsattler** [comment]
I would recommend looking at the code: https://github.com/colmap/colmap/blob/dev/src/exe/colmap.cc#L1077

**Comment by GabbySuwichaya** [comment]
Thanks, tsattler. :)
