### ISSUE TITLE
Fusion with a manually generated sparse model generates no points

### ISSUE THREAD

**Issue by martinVyoo** [colmap/colmap#705]
It is mentionned in the documentation [https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses](Reconstruct sparse/dense model from known camera poses)
that you can do dense reconstruction on a manually generated sparse model.
```
Alternatively, you can also produce a dense model without a sparse model as:

colmap image_undistorter \
    --image_path $PROJECT_PATH/images \
    --input_path path/to/manually/created/sparse/model \
    --output_path path/to/dense/workspace
```

Does that sparse model need to have 3D points in it for the fusion to work, or does it only need the camera positions?

My manual sparse model consists only of camera positions

I provide my own patch-match.cfg and the depthmaps are generated as well as if I had done a sparse reconstruction and used the generated patch-match.cfg

**Comment by ahojnnes** [comment]
You might have to specify min_depth/max_depth and also manually specify the source images, not sure anymore.

**Comment by martinVyoo** [comment]
I am doing all of this already, the depthmaps generate as I expect them to.

**Comment by ahojnnes** [comment]
Fusion doesn’t need sparse points. Just camera positions.

**Comment by martinVyoo** [comment]
So is there something I'm missing?

I give it the camera positions, and the corresponding images, with appropriate settings for the patch_match_stereo step, yet when I run stereo_fusion I still get no points

**Comment by ahojnnes** [comment]
Can you show some depth maps?

**Comment by martinVyoo** [comment]
> Any luck here? I have the same issue

Hi @miangoleh , it has been a while since I've worked on this and move on to other things

However someone has taken over my code and told me my poses were not done right and they were able to make it work.

The method we were using to generate the sparse point cloud was not good however so we dropped that course althogether. 

Hope it helps, I will close this issue
