### ISSUE TITLE
How to use Shared intrinsic option in the command link

### ISSUE THREAD

**Issue by YoussephAhmed** [colmap/colmap#706]
First, thank you for the amazing tool.. Second I am just bit confused how to give the option of all images have the same intrinsic parameter (camera) although the parameters not known using the command line is it only about give the option --ImageReader.single_camera 1 cause I checked once the .init file for a gui run with checked box on the shared intrinsic option and it was equal 0?

**Comment by tsattler** [comment]
--ImageReader.single_camera 1 is the option you need.

**Comment by YoussephAhmed** [comment]
Thank you.
