### ISSUE TITLE
patch_match_cuda.cu:1351 - unspecified launch failure 

### ISSUE THREAD

**Issue by VisionTekF** [colmap/colmap#709]
run :

>colmap patch_match_stereo --workspace_path dense --workspace_format COLMAP --PatchMatchStereo.geom_consistency true

error:

```

PatchMatch::Run
---------------
Initialization: 2.0834s
CUDA error at C:/Users/joschonb/Development/colmap/src/mvs/patch_match_cuda.cu:1351 - unspecified launch failure
This error is likely caused by the graphics card timeout detection mechanism of your operating system. Please refer to the FAQ in the documentation on how to solve this problem.
```

system ver: win10 x64  10.0.17763.107
gpu:NVIDIA Quadro K2000
CUDA ver: cuda_10.0.130_411.31
colmap ver: 3.6-dev.2(https://github.com/colmap/colmap/releases/download/3.6-dev.2/COLMAP-dev-windows.zip)

**Comment by ahojnnes** [comment]
https://colmap.github.io/faq.html#fix-gpu-freezes-and-timeouts-during-dense-reconstruction
