### ISSUE TITLE
Reduced Quality after Geo-Registration (Stripes in Point Cloud)

### ISSUE THREAD

**Issue by khyaph** [colmap/colmap#711]
Hello,
I have problems with the output of the model aligner. After Geo-registration the dense model I get „stripes“ in my point cloud. I include images at the end of my post.
I have around 300 UTM-coordinates oft the camera positions as the input data and in total around 700 images, which results in a point cloud of 7206088 points.

I used the command; running on Windows 10:
colmap model_aligner \ --input_path D:\Colmap\Model_Dense \ --output_path D:\Colmap\Model_Dense_UTM \ --ref_images_path D:\Colmap\GPS_Koord_UTM.txt \  --robust_alignment 1 --robust_alignment_max_error 0.04

cameras and images.txt are from the sparse model because they where empty in the dense model. The points3D.txt are from the dense model. 

Output:
Aligning reconstruction
 => Using 328 reference images
 => Alignment succeeded
 => Alignment error: 2.200048 (mean), 2.062051 (median)

Afterwards I visualized the data in cloudcompare due to the different scaling after the geo-registration. I was expecting the same point cloud, just with UTM coordinates.
How can I get geo-registrated data in the same quality as the unregistered dense model?
And another question which is the unit of the alignment error?

**Screenshots**
Dense Model without geo-referencing
![Ohne Georef](https://user-images.githubusercontent.com/26249005/66813471-19670d80-ef35-11e9-9856-eae6a98c4f90.jpg)
Dense Model with geo-referencing: Stripes in one direction
![MitGeoref](https://user-images.githubusercontent.com/26249005/66813472-19670d80-ef35-11e9-9c35-eb415f95d174.jpg)

**Comment by tsattler** [comment]
Based on past experience, I'd assume that this is a problem with the precision of the floating point representation used to store the 3D points. Limited precision leads to rounding, which means that nearby points are snapped to the same coordinate. This would explain the lines you are seeing.

**Comment by khyaph** [comment]
I see, thank you for your explanation. I will try with different parameters.

**Comment by yuancaimaiyi** [comment]
@khyaph @tsattler 
I meet same problem,can you help me?how I solve this ,can you provide same advices

**Comment by tsattler** [comment]
As I said, I assume it is a problem of the precision of the floating point data type used. It is either on the point cloud side or maybe on the viewer you are using to display the point cloud. If the problem is on the point cloud side, you can try to use a floating point representation that has higher precision, e.g., double instead of floating point. If it is on the viewer side, you might be able to find a viewer that loads point clouds in a higher precision. 
You can have a look at Colmap's source code to figure out whether the point clouds are stored as floats or doubles. If it is the former, you could modify the code to use doubles instead.

**Comment by yuancaimaiyi** [comment]
@tsattler thanks .
I have model_alignered ，and convert the result into TXT(like this), indeed, x,y coordinates into an integer, resulting in precision loss, but I looked at the source code, indeed it is a double type, I do not know how to do
 **-197163 3.40931e+06 6.80342 
 -197163 3.40931e+06 6.79568 
-197163 3.40931e+06 6.79413**

**Comment by tsattler** [comment]
@yuancaimaiyi You could either use a binary file where the coordinates are stored in doubles or you could export it to a text file with higher precision. In the latter case, you will need to modify the source code.

**Comment by yuancaimaiyi** [comment]
@tsattler thanks .I solved it .I modify the code(colmap/base/reconstruction.cc)
all ofstream file,I add a line "file.precision(17)"
  std::ofstream file(path, std::ios::trunc);
  file.precision(17);

**Comment by ahojnnes** [comment]
@yuancaimaiyi That's a good suggestion. I incorporated file.precision(17) into the code.

**Comment by yuancaimaiyi** [comment]
@khyaph 
can you provide your model aligner script?Command line script for the entire program

**Comment by yuancaimaiyi** [comment]
@khyaph 
can you provide your fuse.ply geo-register script pipeline?
my script as follows,do you think right? 
$ DATASET_PATH=/path/to/dataset
$ colmap feature_extractor
--database_path $DATASET_PATH/database.db
--image_path $DATASET_PATH/images

$ colmap exhaustive_matcher
--database_path $DATASET_PATH/database.db

$ mkdir $DATASET_PATH/sparse

$ colmap mapper
--database_path $DATASET_PATH/database.db
--image_path $DATASET_PATH/images
--output_path $DATASET_PATH/sparse
$ mkdir $DATASET_PATH/sparse/sparse_geo

$ colmap model_aligner
--input_path $DATASET_PATH/sparse/0
--output_path $DATASET_PATH/sparse/sparse_geo
--ref_images_path $DATASET_PATH/cameraCenterUTM.txt
--robust_alignment 1
--robust_alignment_max_error 0.3

$ mkdir $DATASET_PATH/dense
after model_aligner ,this moment all sparse points become UTM coordinates.

$ colmap image_undistorter
--image_path $DATASET_PATH/images
--input_path $DATASET_PATH/sparse/sparse_geo \
--output_path $DATASET_PATH/dense
--output_type COLMAP
--max_image_size 2000

$ colmap patch_match_stereo
--workspace_path $DATASET_PATH/dense
--workspace_format COLMAP
--PatchMatchStereo.geom_consistency true

$ colmap stereo_fusion
--workspace_path $DATASET_PATH/dense
--workspace_format COLMAP
--input_type geometric
--output_path $DATASET_PATH/dense/fused.ply
