### ISSUE TITLE
build.py: certificate verify failed

### ISSUE THREAD

**Issue by Voleuro** [colmap/colmap#714]
**Description**
When trying to build colmap from sources using the given build.py build script the error `urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>` occurs. Apparently the website's certificate where the dependencies are downloaded has expired. This happens for all links in the build script that point to sourceforge.

If I open one of the sourceforge links inside the build script in chrome I get this message:
![CertificateError](https://user-images.githubusercontent.com/4070456/67159558-6fc5b900-f346-11e9-94d8-7624e342e658.PNG)

**To Reproduce**
1. Start the build.py in a console with paths to your source code and required dependencies. I used `python "C:\\test\\build.py" --build_path C:\\test\\build --colmap_path C:\\colmap-dev --boost_path "C:\\boost_1_71_0\\lib64-msvc-14.1\\" --qt_path "C:\\Qt\\Qt5.13.1\\5.13.1\\msvc2017_64" --cuda_path "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1" --cgal_path "C:\\CGAL\\build" --cmake_generator "Visual Studio 15"`
2. Wait until the script tries to download freeimage
3. Observe the error

**Expected behavior**
Instead of failing when downloading the dependencies the build script should download and compile the necessary dependencies.

**Temporary Fix**
Replace all links that point to sourceforge in the way "https://kent.dl.sourceforge.net/..." by links that start like this: "https://sourceforge.net/..."

I'm not sure what the prefix "kent.dl." is meant to do, but for me this seems to cause the cerificate error.

Best,
Kai

**Comment by ahojnnes** [comment]
Pass --no_ssl_verification to the build script.
