### ISSUE TITLE
A problem when import model from .txt

### ISSUE THREAD

**Issue by ffrivera0** [colmap/colmap#715]
Hi,

I got a problem when importing the sparse model from .txt files. Here is the model I reconstructed from images, it's quite good.
![Screenshot from 2019-10-20 21-12-57](https://user-images.githubusercontent.com/47051889/67164010-acada200-f37e-11e9-8e3f-b5b64e2c10c7.png)

However, when I exported the model as text and imported it again by the .txt files, it looked like this,
![Screenshot from 2019-10-20 21-17-21](https://user-images.githubusercontent.com/47051889/67164069-0e6e0c00-f37f-11e9-9b31-d60455fa6290.png)

Shouldn't the model import from .txt files and .bin files be the same or are there some steps I do wrong?

**Comment by ahojnnes** [comment]
Looks like you have an issue with your locale, which sometimes messes up `,` and `.` which then messes up how COLMAP interpretes the input. Can you export as .bin instead?

**Comment by ffrivera0** [comment]
Thank you so much. I solved the problem by changing the locale setting to LC_NUMERIC=en_US.UTF-8 in locale
