### ISSUE TITLE
prior Intrinsic parameters 

### ISSUE THREAD

**Issue by YoussephAhmed** [colmap/colmap#717]
What is the right way to pass the values of the camera parameters in the option as for example
--ImageReader.camera_params [ 411.965 357.804 960 540 0.479502 0.129811 -0.0489444 0.066348 ] 
or simply could you add one right example on how to call it from the command line? and thank you.

**Comment by yuancaimaiyi** [comment]
@YoussephAhmed
CAM_MODEL=$(awk '{print $1}' $DATASET_PATH/cam_para)
CAM_PARAS=$(awk '{print $2}' $DATASET_PATH/cam_para)
    --ImageReader.camera_model $CAM_MODEL \
    --ImageReader.camera_params $CAM_PARAS \
    --ImageReader.single_camera 1 \ 
write a txt.like this 
OPENCV 9.6482978858098329e+02,9.6482978858098329e+02,6.2381029640612985e+02,3.4403188522281874e+02,-3.9429318799558871e-01,2.0975570195486784e-01, 6.9104055647051352e-04,-8.5162632913388381e-02

**Comment by tsattler** [comment]
On Linux and Mac, using `" "` to pass multiple numbers (separated by commas) as a single string parameter works.

**Comment by nimafo** [comment]
What are the eight parameters and the correct order to import them to the model?

**Comment by tsattler** [comment]
You can find the parameter lists for the different camera models here: https://github.com/colmap/colmap/blob/master/src/base/camera_models.h

**Comment by amballa** [comment]
> On Linux and Mac, using `" "` to pass multiple numbers (separated by commas) as a single string parameter works.

Having trouble on Powershell getting this to work

**Comment by janblumenkamp** [comment]
The parameter lists can now be found here:
https://github.com/colmap/colmap/blob/23084663dbfb5c413ed386534f3ab89cf6a5b5c0/src/colmap/sensor/models.h#L217

**Comment by DebaoHuang** [comment]
I have figured out, you need to run colmap.exe instead of COLMAP.bat

**Comment by lcmrl** [comment]
This was the only format that worked for me on Ubuntu 22.04 and COLMAP 3.9
![image](https://github.com/colmap/colmap/assets/93863149/f74c466a-ff04-4c1f-9f16-c76641e41f5b)
