### ISSUE TITLE
Will the dense reconstruction modify the camera pose further?

### ISSUE THREAD

**Issue by placeforyiming** [colmap/colmap#718]
feature_extractor  + exhaustive_matcher + mapper can estimate a sparse model, then will patch_match_stereo modify the pose further for the dense reconstructing?

Since I extracted the colmap estimated poses from workspace/dense/0/sparse/images.bin , and compare them with the ground truth poses, found they are not close. But the estimated depth maps look pretty good. So I guess the dense reconstruction modify the pose further? Can I access those poses if so?

I didn't align the coordinate, so only the relative shape matters

 Colmap poses:
![image](https://user-images.githubusercontent.com/22132384/67322097-7d15ab80-f4de-11e9-90ad-1ba6305f7bc4.png)

ground truth poses:
![image](https://user-images.githubusercontent.com/22132384/67322154-974f8980-f4de-11e9-887e-38d19985a351.png)

estimated depth map:
![000020](https://user-images.githubusercontent.com/22132384/67322247-bf3eed00-f4de-11e9-9470-c2ecb927315a.jpg)

**Comment by tsattler** [comment]
It does not change the camera poses, just undistorts the images and the 2D measurements (see https://github.com/colmap/colmap/blob/6b6e825c135b699f770d4cccc43ac365182fe6c8/src/base/undistortion.cc#L922). You can check this by comparing the poses in the sparse/ directory of the dense reconstruction with the poses you obtain after sparse reconstruction.

**Comment by placeforyiming** [comment]
Got you, thanks!
