### ISSUE TITLE
Reconstruct sparse/dense model from known camera poses?I meet some problem

### ISSUE THREAD

**Issue by yuancaimaiyi** [colmap/colmap#719]
@tsattler 
Sorry to bother you again!  I meet two problems
**ploblem one:**
According to the official tutorial, I have a prior pose. Skip sparse reconstruction and directly dense reconstruction. Here is my script
`COLMAP=/home/colmap/build/src/exe/colmap
MIN_DEPTH=0
MAX_DEPTH=20
DATAPATH=/home/colmap/build/src/exe
$mkdir $DATAPATH/dense
$COLMAP image_undistorter --image_path $DATAPATH/right1 \
    --input_path $DATAPATH/manual \
    --output_path $DATAPATH/dense
$COLMAP patch_match_stereo --workspace_path  $DATASET_PATH/dense\
    --PatchMatchStereo.depth_min $MIN_DEPTH \
    --PatchMatchStereo.depth_max $MAX_DEPTH

$COLMAP stereo_fusion --workspace_path $DATASET_PATH/dense \
    --output_path $DATASET_PATH/dense/fused.ply`
manul file
 ----cameras.txt 
 ----images.txt
 ----points3D.txt
The script runs as follows：
==============================================================================
Image undistortion
==============================================================================

Undistorting image [1/300]
Undistorting image [2/300]
Undistorting image [3/300]
Undistorting image [4/300]
Undistorting image [5/300]
Undistorting image [6/300]
Undistorting image [7/300]
Undistorting image [8/300]
Undistorting image [9/300]
Undistorting image [10/300]
Undistorting image [11/300]
.......
Writing reconstruction...
Writing configuration...
Writing scripts...
Elapsed time: 0.891 [minutes]
then patch_match_stere,but meet mistake
**cameras, images, points3D files do not exist at /dense/sparse**
I check the dense(I mkdir it on my script)folder. The three of them are under the /dense/sparse, but why does the program report an error-can not find the three files.?
I am fused! can you help me ?
**problem two**
Can model_aligner only handle sparse?I want to model_aligner the final result,that is fuse.ply.how I can do it ?
I follow this reconstruction pipeline:
`$ DATASET_PATH=/path/to/dataset

$ colmap feature_extractor \
   --database_path $DATASET_PATH/database.db \
   --image_path $DATASET_PATH/images

$ colmap exhaustive_matcher \
   --database_path $DATASET_PATH/database.db

$ mkdir $DATASET_PATH/sparse

$ colmap mapper \
    --database_path $DATASET_PATH/database.db \
    --image_path $DATASET_PATH/images \
    --output_path $DATASET_PATH/sparse
$ mkdir $DATASET_PATH/sparse/sparse_geo
_$ colmap model_aligner
--input_path $DATASET_PATH/sparse/0
--output_path $DATASET_PATH/sparse/sparse_geo
--ref_images_path $DATASET_PATH/cameraCenterUTM.txt
 --robust_alignment 1
--robust_alignment_max_error 0.3_

$ mkdir $DATASET_PATH/dense
# after model_aligner ,this moment  all sparse points become UTM coordinates.
$ colmap image_undistorter \
    --image_path $DATASET_PATH/images \
    --input_path $DATASET_PATH/sparse/sparse_geo \ 
    --output_path $DATASET_PATH/dense \
    --output_type COLMAP \
    --max_image_size 2000

$ colmap patch_match_stereo \
    --workspace_path $DATASET_PATH/dense \
    --workspace_format COLMAP \
    --PatchMatchStereo.geom_consistency true

$ colmap stereo_fusion \
    --workspace_path $DATASET_PATH/dense \
    --workspace_format COLMAP \
    --input_type geometric \
    --output_path $DATASET_PATH/dense/fused.ply

$ colmap poisson_mesher \
    --input_path $DATASET_PATH/dense/fused.ply \
    --output_path $DATASET_PATH/dense/meshed-poisson.ply

$ colmap delaunay_mesher \
    --input_path $DATASET_PATH/dense \
    --output_path $DATASET_PATH/dense/meshed-delaunay.ply`
but last result  fused.ply is bad, it only have 125 points, Why?

**Comment by tsattler** [comment]
In this line `$COLMAP patch_match_stereo --workspace_path $DATASET_PATH/dense`, did you define `DATASET_PATH`? Seems like you only define `DATAPATH`.

**Comment by tsattler** [comment]
`cameras, images, points3D files do not exist at /dense/sparse` seems to indicate that Colmap is looking for the `sparse/` directory in the directory `/dense`, which is a subdirectory of the root (`/`) directory. Are you sure you are passing in the right directory path?

For the second problem: I'd suggest to either first align the sparse reconstruction to the UTM coordinates before running dense reconstruction or to write out the transformation estimated by the model_aligner for the sparse point cloud and apply it to the dense point cloud. The latter requires to modify Colmap's source code.

**Comment by yuancaimaiyi** [comment]
@tsattler as you said ,I model_aligner the sparse reconstrution to utm ,and then dense reconstrution ,the fused.ply is only 7.7 M size.But I directly sparse reconstrution(no model_aligner),and dense reconstrution the fused.ply size is 70M ,so after model_aligner loss many points,but model_aligner report error is 0.07,is very nice .is colmap problem?
next step .I will use you model_aligner get a transform matrix,and then I will write a python script read the fused.ply and use the transform matrix to transform the points of fused.ply. Do you think ?

**Comment by tsattler** [comment]
I'd assume the loss in dense points is a problem of floating point precision as UTM coordinates tend to correspond to very large numbers.

**Comment by yuancaimaiyi** [comment]
I output model_aligner transform matrix :
scale 20.001022192759077
w x y z
0.70344334374105566
-0.68915158707374968
-0.12532302410326876
0.12054746703994426
translation
-173677.08913099344
3462268.2337030983
6.3241683860213715
if I have a point,is this scale*R*point+translation ? right? ,But I find result is error
this is a reconstruction.cc code ,I output it!
  Transform(SimilarityTransform3(report.model));
  std::ofstream file("transformMatrix.txt", std::ios::trunc);
  file.precision(17);
  file<<"scale"<<" " <<SimilarityTransform3(report.model).Scale()<<std::endl;
  file<<"w"<<" "<<"x"<<" "<<"y"<<" "<<"z"<<std::endl;
  file<<SimilarityTransform3(report.model).Rotation()<<std::endl;
  file<<"translation"<<std::endl;
  file<<SimilarityTransform3(report.model).Translation()<<std::endl;

**Comment by tsattler** [comment]
I don't know how the transformation is exactly defined. Please have a look at the source code doing the transformation.

**Comment by khyaph** [comment]
First I had the same loss of data as you @yuancaimaiyi  when I applied the geo-registration on the sparse reconstruction.
My work around was using the the cameras and images file from the sparse reconstruction and the points3D from the dense reconstruction as input data for the geo-registration.

**Comment by yuancaimaiyi** [comment]
@khyaph  thanks ,I solve it ,first of all.I use colmap estimate a similar transform matrix,and then I write a python script read the final result--fuse.ply ,point by point transform using I recoding the similar transform matrix.can you leave some contact information? like weichat ,we can talk about colmap
