### ISSUE TITLE
ExportNVM done incorrectly

### ISSUE THREAD

**Issue by monodavids** [colmap/colmap#72]
Working with @rafapages at the moment and using colmap.
We noticed that the Reconstruction::ExportNVM method in reconstruction.cc is not correct. 

Colmap saves the value k to the NVM file as the distortion coefficient r, whereas in fact VSFM NVM format saves rn = r * f * f.  (http://ccwu.me/vsfm/doc.html)

This should be a simple change to fix:
Lines 1068 in reconstruction.cc 
change from:
const double k =
        camera.Params(SimpleRadialCameraModel::extra_params_idxs[0]);

to 
const double k =
        camera.Params(SimpleRadialCameraModel::extra_params_idxs[0]) * f * f;

as f is defined in the line previous (1066).

dave and rafa

**Comment by ahojnnes** [comment]
Thanks, should be fixed!

**Comment by rafapages** [comment]
Hi!

Sorry to bring this thread back to life but after re-analyzing the issue with the radial distortion model in VisualSfM, we've discovered that they are expecting a normalized value as input. This means that we were mistaken to assume that you needed to write rn = r*f*f. 

However, as you can see here: http://grail.cs.washington.edu/projects/mcba/manual.pdf, at least it is necessary to multiply the distortion parameter you were exporting by -1. So:

const double k = -1 *
camera.Params(SimpleRadialCameraModel::extra_params_idxs[0]);

We've performed several tests undistorting images with this -k1 parameter using colmap and other projects that accept nvm files and results are ok now.

Sorry again!

@monodavids and rafa

**Comment by ahojnnes** [comment]
Thanks, should be fixed now.
