### ISSUE TITLE
cannot find newly registered images in model

### ISSUE THREAD

**Issue by gkahn13** [colmap/colmap#722]
**Describe the bug**
I am trying to register new images into an existing model (following the [FAQ](https://colmap.github.io/faq.html#register-localize-new-images-into-an-existing-reconstruction)). I can find the registered images in the database, but I cannot find the newly registered images in the outputted txt model. I need this because I want the pose of the newly registered images. Related to #440.

**To Reproduce**
Download the files ([link here](https://drive.google.com/open?id=1ghdwzTc6KjZTR2HsV1j0aM-xWcWS8Yyt)).

Steps to create these files:
1. `colmap feature_extractor --database_path database.db --image_path images/  --ImageReader.camera_model OPENCV_FISHEYE --ImageReader.single_camera 1` (note that images/ includes both the reconstruction images and the registering images)
2. `colmap vocab_tree_matcher --database_path database.db --VocabTreeMatching.vocab_tree_path vocab_tree_flickr100K_words256K.bin`
3. `colmap mapper --database_path database.db --image_path images --output_path sparse/ --image_list_path image-list-reconstruction.txt`
4. `colmap image_registrator --database_path database.db --input_path sparse/ --output_path sparse_registered/` ([output is here](http://txt.do/1kutk))
5. `colmap model_converter --input_path sparse_registered/ --output_path sparse_registered_txt/ --output_type TXT`

Steps to show the registered images (i.e., images/jackal*.jpg) are not showing up:
1. `cat sparse_registered_txt/images.txt | grep jackal` is empty

**Expected behavior**
The newly registered images to show up in the new model (i.e., sparse_registered_txt/images.txt).

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Colmap 3.6

**Comment by tsattler** [comment]
For me, registered images were always included in the new model. Are you sure that the images are registered in the first place?

**Comment by gkahn13** [comment]
I now believe the images are not being registered. I compared the output of running image_registrator on my data ([link here](https://textuploader.com/1kutk)) versus on the Gerrard hall dataset ([link here]( http://txt.do/1kpqj)). For the Gerrard hall output, I ran the same commands in my original post, but excluded 10% of the images from the sparse reconstruction and then registered those images afterwards.

The Gerrard hall registration succeeded, meaning that the new model has the newly registered images. The difference in output seems to be that an image is only successfully registered if it prints the "Pose refinement report"; running image_registrator on my data does not seem to have these printouts.

Does this indicate that image_registrator is failing on my data? And if so, are there any command line arguments I can pass in to increase the chance of successfully registering? Or print out additional debug information?

**Comment by tsattler** [comment]
You can get the parameters of a command line tool via `--help`.
Since you are using fisheye images and not passing any calibration parameters, I could imagine that COLMAP has problems determining the intrinsic calibration during image registration. Putting the intrinsic parameters estimated during the reconstruction process into the database might help.

**Comment by gkahn13** [comment]
Good idea! I tried it, but unfortunately it didn't work.

I dug a bit deeper and found that the image registration was failing due to bogus parameters. Following #20, I was able to pass in looser values for `min_focal_length_ratio`, `max_focal_length_ratio`, and `max_extra_param`. And that worked!

Thanks again for helping me debug this.

**Comment by samuelyutt** [comment]
Hi @gkahn13,
I think I'm having similar issue. Would you please provide the values you passed during `image_registrator`, please?
