### ISSUE TITLE
Reconstruct dense model from known camera poses---(depthmap very good ,but fused points number is 0)

### ISSUE THREAD

**Issue by yuancaimaiyi** [colmap/colmap#725]

**Comment by ahojnnes** [comment]
What do you set for MIN_DEPTH/MAX_DEPTH?

**Comment by yuancaimaiyi** [comment]
@ahojnnes  of course .thank you for your answer .I set MIN_DEPTH AND MAX_DEPTH ,I set min_depth is 0 and set max_depth is 20. I try many times!!!!!

**Comment by laoyandujiang** [comment]
Have you ever check the setting of gpu_id? Dense sterio reconstruction requires CUDA, and I met the same problem because set a non-existing gpu.

**Comment by yuancaimaiyi** [comment]
@laoyandujiang  my gpu_id is ok .And I found stereo_fusion must need sparse model (I add sparse model ,the code works).thanks

**Comment by dyy0205** [comment]
> @laoyandujiang my gpu_id is ok .And I found stereo_fusion must need sparse model (I add sparse model ,the code works).thanks

sorry to bother you! I am facing the same problem...I have known camera poses, depth maps and normal maps, just want to use stereo fusion to get dense point clouds. It indeed needs a sparse model, but I don't know how to get it? In other words, how to write cameras.txt, images.txt and points3D.txt？Look forward to your reply !

**Comment by dyy0205** [comment]
@ahojnnes @yuancaimaiyi please help!!!
