### ISSUE TITLE
Photometric Vs geometric maps

### ISSUE THREAD

**Issue by thunders82** [colmap/colmap#728]
Hi,
It's not a request or an issue. I'd like more information regarding the way those maps are working and helping the reconstruction.
My final goal is to improve the details and final quality of the reconstruction.

From what I understand the photometric depth and normals are used to improve the lack of details of the geometric maps? Is it correct?

From this assomption, would it be correct to say I could use highly detailed normal map from photometric stereo and replace those computed by colmap? (As soon as resolution and undistort is matching)

Would it be correct for the depth too? Knowing the depth from photometric stereo is far from accurate would the geometric depth help and correct the low frequency of the photometric stereo's?

Thank you

**Comment by ahojnnes** [comment]
Please refer to the following paper to get more details on the difference: https://demuc.de/papers/schoenberger2016mvs.pdf

**Comment by thunders82** [comment]
Hi @ahojnnes 
Thank you for the link. I've read the paper 2 times and there is still a lot of information to ingest. It's a bit complicated when the reader is not from the same field or same academic level. Loads of references and techniques I don't know about.

If you don't mind I'd like to contact you via email regarding my current project. That will probably help me to achieve a correct reconstruction.

Thank you

**Comment by thunders82** [comment]
closing this ticket and creating a new one:

https://github.com/colmap/colmap/issues/734
