### ISSUE TITLE
Dense Mapper Error for PMVS Workspace Format

### ISSUE THREAD

**Issue by resindraburiza** [colmap/colmap#73]
Hello,

Colmap is very useful for me recently. Thank you very much.
I read from the documentation that the dense mapper could work with PMVS format. I tried to undistort to PMVS format, run CMVS to cluster the images, and run the dense mapper. But I got this error:

> Reading model...
> Reading configuration...
> F0206 02:57:41.581185 18412 patch_match.cc:42] Check failed: file.is_open()
> *** Check failure stack trace: ***

and this is the command i ran:

> dense_mapper.exe --workspace_format PMVS --workspace_path "E:\pmvs\\\\\"

Is there anything wrong with my command? Thank you very much.

**Comment by ahojnnes** [comment]
It seems there is some problem with the PMVS import in the dense mapper. I will try to fix it and in the mean time, I suggest to use PMVS to do the dense reconstruction, see https://colmap.github.io/tutorial.html#dense-reconstruction

Thanks for reporting and I will notify you here when I fixed the problem.

**Comment by resindraburiza** [comment]
Thank you very much for your response. I hope there is a way to fix the problem. Good luck.

**Comment by ahojnnes** [comment]
This is fixed in the latest commits now. Please, re-read https://colmap.github.io/tutorial.html#dense-reconstruction and https://colmap.github.io/faq.html#reduce-memory-usage-during-dense-reconstruction

Feedback whether it works for you, would be more than welcome. Thanks for reporting the bug.
