### ISSUE TITLE
colmap bundle_ajustmenter Interface .(I only want to optimized rotation,fix translation x,y,z)

### ISSUE THREAD

**Issue by yuancaimaiyi** [colmap/colmap#731]
@ahojnnes @tsattler  I am very sorry to bother you again!
for the colmap , bundle_ajustmenter . I modify the code (controllers/bundle_adjustment.cc) ,I  want to fix the translation of camera pose .And I found in the colmap .
```
BundleAdjustmentConfig ba_config;
  for (const image_t image_id : reg_image_ids) {
    ba_config.AddImage(image_id);
  }
  //********************original write**************************************
  // ba_config.SetConstantPose(reg_image_ids[0]); //fix the first frame  colmap original write
  // ba_config.SetConstantTvec(reg_image_ids[1], {0}); // fix the second frame translation X,only ```
optimize roll,pitch,yaw and Y and Z . 
  //************************************************************************
  for(int i=0;i<reg_image_ids.size();++i)
  {
    ba_config.SetConstantTvec(reg_image_ids[i],{0,1,2});
  }

  // Run bundle adjustment.
  BundleAdjuster bundle_adjuster(ba_options, ba_config);
  bundle_adjuster.Solve(reconstruction_);

```
I simple modify ,but ba not SetConstantTvec (X,Y,Z),3 translation. it return error,like :

`F1105 19:55:08.385177  1856 local_parameterization.cc:104] Check failed: constant_parameters.size() < size (3 vs. 3) Number of parameters held constant should be less than the size of the parameter block. If you wish to hold the entire parameter block constant, then a efficient way is to directly mark it as constant instead of using a LocalParameterization to do so.`
but I set the  ba_config.SetConstantTvec(reg_image_ids[i],{0,1}) or  ba_config.SetConstantTvec(reg_image_ids[i],{0}) one or two idxs.size ,code return right .
can you give some  advise？ And how can I modify it ? Thank you very much. I look forward to your early reply（In addition, I'm confused about why BA  be designed to fix only one translation or two translations, instead of three translations being set as constants
）

**Comment by tsattler** [comment]
This is an error message from the Ceres solver, which is used by Colmap for bundle adjustment in most cases. I'd suggest to have a look at their tutorial (http://ceres-solver.org/nnls_tutorial.html#), which should explain the issue that you are running into if I remember correctly.

**Comment by yuancaimaiyi** [comment]
@tsattler thanks.

At present, I haven't solved this problem yet（fix  pose tanslation x,y,z). Let me have a look again. I want to ask you another question. When I rebuild with known poses, I always lose a lot of point clouds. Is it related to the accuracy of my known poses?
thanks!!!!!!!!!!!!!!!!!!!!!!

**Comment by tsattler** [comment]
I'd assume it is related to the accuracy of your known poses. Really accurate poses are needed to triangulate a scene.

**Comment by yuancaimaiyi** [comment]
@tsattler Isn't triangulation just about determining the maximum and minimum depth of a patch match。
If I have a known pose, the next step is dense reconstruction, that is, the patch match and stereo fusion links. I still don't understand why a large number of point clouds are lost in the known pose during dense reconstruction

**Comment by tsattler** [comment]
Patch matching is restricted to pixels close to the epipolar line. If the epipolar line is not close enough to the correct match, then you start loosing points.
