### ISSUE TITLE
colmap stereo_fusion bug (killed)

### ISSUE THREAD

**Issue by yuancaimaiyi** [colmap/colmap#732]
@ahojnnes @tsattler 
Hi,  I have 1607 images,and Patch match success! but in stereo_fusion process,always killed
![35956377-5cb5-440c-a7c4-fd85c6bfffdc](https://user-images.githubusercontent.com/28293910/68287552-d9bbbd80-00bd-11ea-98c0-8c76cf32bf7a.jpg)

**Comment by tsattler** [comment]
Are you running out of memory? Did you try this? https://colmap.github.io/faq.html#reduce-memory-usage-during-dense-reconstruction

**Comment by yuancaimaiyi** [comment]
@tsattler Thanks for your reply, I set these parameters, but still kill.

**Comment by tsattler** [comment]
Are you running out of memory when the process is killed?

**Comment by yuancaimaiyi** [comment]
@tsattler  no,when the process is killed .is not out of memory.Maybe it's my machine?

**Comment by tsattler** [comment]
I don't know. Hard to tell from afar.

**Comment by pierotofy** [comment]
Yes, you're running out of memory. Add more RAM or try lowering the resolution of your images.
