### ISSUE TITLE
I use the Colmap output to run CMVS , the result is incomplete。

### ISSUE THREAD

**Issue by rock0201** [colmap/colmap#736]
Hi! I use the EXTRA -> UNDISTORAION, and choose the PMVS. But when I run CMVS to seperate them, the result of CMVS only contains camera classification,without point classification.  I have ran CMVS, set maximages to 30, a total of 110 pictures, but only output the three files centers-0000.ply, centers-0000.ply, centers-0000.ply, I want to know how to get the information of pictures and the 3D points which are separated.

**Comment by ahojnnes** [comment]
I can only refer you to the CMVS code base, as far as I know, this is not written as a standard output.
