### ISSUE TITLE
Multiple 2D features correspdond to one 3D point

### ISSUE THREAD

**Issue by lixx2938** [colmap/colmap#74]
Hi,

I just found sometimes, for a single 3D point, the number of features that can see this 3D point in one image can be more than 1 even though they are very close to each other. Is it possible to enable unique matching for each 2D/3D feature (i.e. one 3D point in 3D space at most corresponds to one 2D point in one image) ?

Thanks

**Comment by ahojnnes** [comment]
No, this is not easily possible. You could write a simple post-processing script, that removes the observation that is farther away from the projection of the 3D point. Closing this issue but feel free to reopen.
