### ISSUE TITLE
WARNING: Ignoring reference image (lost many images)

### ISSUE THREAD

**Issue by yuancaimaiyi** [colmap/colmap#741]
@ahojnnes @tsattler 
I have changed the image fps .but always Ignoring reference image ,2000's images ,ignoring 1000's images,I check the overlap images ,is ok.I do not known where i am wrong

**Comment by tsattler** [comment]
I am sorry, I am not sure what your question is. Are you saying that there is enough overlap between images and colmap still does not reconstruct all images?
If this is the question:
* Did you match each image against each other image?
* Do you have situations where you are rotation on the spot without any translation? Such cases cannot be handled as there is insufficient baseline to continue the reconstruction.

**Comment by yuancaimaiyi** [comment]
thanks for your reply! my problem is ,when I use patch_match_stereo,it always Ignoring reference image.like this
![Screenshot from 2019-11-26 18-19-36](https://user-images.githubusercontent.com/28293910/69621149-82d05500-1079-11ea-8c31-9735a2fbebe9.png)
I check the overlapping images,it matching nice .I am confused .Also ,I look through the patch_match.cc
and  I modified the following parts, but still didn't solve my problem. Is there a problem with my matching (for image matching, I tried sequential_matcher and vocab_tree_matcher,should I use Exhaustive Matching?(I have 3000's images)
`      src_images.reserve(overlapping_images.size());
      for (const auto& image : overlapping_images) {
        //if (ref_image_idxs.count(image.first) &&
         //   overlapping_triangulation_angles.at(image.first) >=
            //    min_triangulation_angle_rad) {
          src_images.emplace_back(image.first, image.second);
       // }
      }`

**Comment by tsattler** [comment]
Colmap determines which other images to consider for Patch Match based on the sparse 3D reconstruction. If an image has no source images, then this likely means that the image is not part of the reconstruction. If they are contained in the reconstruction, it likely means that they do not have any reconstructed sparse 3D points (which I guess can happen in you specify the poses, it should not happen during reconstruction from scratch). You can manually specify which other images should be used for Patch Match. You can find more details in the frequently asked question section here: https://colmap.github.io/faq.html#

**Comment by yuancaimaiyi** [comment]
@tsattler  Thanks for your reply. it is , I reconstruction by know pose ,and I follow the docs of colmap,I manually specify which other images be used for Patch Match(about 30),but in the end,the specify the reference image can not fused any points.but the the docs of colmap said " produce a dense model without a sparse model ", I am confused it ,I try many times! thanks !
 Sorry bother you !

**Comment by tsattler** [comment]
I am sorry, but you will need to provide a bit more information, otherwise it is hard to help you:
* What is the exact problem you are running into?
* Do some images get fused while others do not?
* Where do you get the camera poses from? Are they accurate enough for patch match stereo (do you get reasonably looking depth maps)?

**Comment by yuancaimaiyi** [comment]
sorry .It is my fault . I should provide more information.
First of all, I reconstruction from known pose(IMU+GPS posetion,Relative accuracy）。I follow the https://colmap.github.io/faq.html ,Reconstruct sparse/dense model from known camera poses.
colmap docs script as follow:
colmap feature_extractor \
    --database_path $PROJECT_PATH/database.db \
    --image_path $PROJECT_PATH/images
colmap exhaustive_matcher \ # or alternatively any other matcher
    --database_path $PROJECT_PATH/database.db 
colmap point_triangulator \
    --database_path $PROJECT_PATH/database.db \
    --image_path $PROJECT_PATH/images
    --input_path path/to/manually/created/sparse/model \
    --output_path path/to/triangulated/sparse/model
colmap image_undistorter \
    --image_path $PROJECT_PATH/images \
    --input_path path/to/triangulated/sparse/model \
    --output_path path/to/dense/workspace
colmap patch_match_stereo \
    --workspace_path path/to/dense/workspace
colmap stereo_fusion \
    --workspace_path path/to/dense/workspace \
    --output_path path/to/dense/workspace/fused.ply

I have tested a lot of data. There is no problem with the previous data, but in the latest data, patch match began to ignore the some reference image(2000images,500images lost), and the program reported an error and could not find the source image（As shown in the screenshot above
![Screenshot from 2019-12-04 17-16-16](https://user-images.githubusercontent.com/28293910/70129535-e41ba800-16b9-11ea-8495-e770a6e54a8f.png)
）。
So ,I follow your advice, I check the point_triangulator 's result ,lost images(ignored reference images) don't triangulate any points,in deed. To deal with it ,So,for the ignored reference images ,I manual add the source image for reference image ,and I set the patch match min_depth and max_depth , the program normally operate. In the end .I check the depth map ,is  reasonable.but in the fusion,the lost images still hasn't contributed anything.
the colmap docs said,"you can also produce a dense model without a sparse model "
the colmap docs script as follow:
colmap image_undistorter \
    --image_path $PROJECT_PATH/images \
    --input_path path/to/manually/created/sparse/model \
    --output_path path/to/dense/workspace
colmap patch_match_stereo \
    --workspace_path path/to/dense/workspace \
    --PatchMatchStereo.depth_min $MIN_DEPTH \
    --PatchMatchStereo.depth_max $MAX_DEPTH
colmap stereo_fusion \
    --workspace_path path/to/dense/workspace \
    --output_path path/to/dense/workspace/fused.ply
I also try this ,but it is a pity. do not fuse any points,I use the colmap gui show the depth map is meaningful,so now I wonder if I'm reconstructing from a known pose must need a sparse model?
These are my questions. This time, I think I have explained them clearly

**Comment by tsattler** [comment]
As mentioned in the FAQ, you don't need a sparse 3D model for dense reconstruction.

Are you certain that your camera poses for the "missing" images are accurate enough? Since there are no 3D points triangulated from these images, maybe the poses are not accurate enough?

**Comment by yuancaimaiyi** [comment]
@tsattler  thanks ! I solve it . thanks
