### ISSUE TITLE
Bug in gpu_mat_test.cu?

### ISSUE THREAD

**Issue by nghiaho12** [colmap/colmap#742]
All the test cases in this file use this pattern

```
  GpuMat<T> array(width, height, depth);
  std::vector<T> array_host(...)
  ...
  (do stuff)
   ...
  array.CopyToDevice(array_host.data(), ...);
```
Checks are then done on array_host.data(). 

But shouldn't that be **array.CopyToHost()** in the above?

**Comment by ahojnnes** [comment]
This is a bug. Are you willing to fix this I’m a PR?

**Comment by ahojnnes** [comment]
Fixed it myself. Thanks for the report.
