### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by tub-sgg** [colmap/colmap#748]
my OS is MacOS, when I installed this, so sad that error occurred in the last step.
How can I solve the problem???

[100%] Linking CXX executable colmap
ld: warning: text-based stub file /System/Library/Frameworks//OpenGL.framework/OpenGL.tbd and library file /System/Library/Frameworks//OpenGL.framework/OpenGL are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.tbd and library file /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.tbd and library file /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib are out of sync. Falling back to library file for linking.
Undefined symbols for architecture x86_64:
  "___kmpc_barrier", referenced from:
      _.omp_outlined. in colmap.cc.o
      _.omp_outlined..370 in colmap.cc.o
      _.omp_outlined..420 in colmap.cc.o
      _.omp_outlined..422 in colmap.cc.o
      _.omp_outlined..103 in libcolmap.a(matching.cc.o)
      _.omp_outlined..104 in libcolmap.a(matching.cc.o)
      _.omp_outlined..155 in libcolmap.a(matching.cc.o)
      ...
  "___kmpc_critical", referenced from:
      _.omp_outlined..189 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..217 in libpoisson_recon.a(PoissonRecon.cpp.o)
      CoredFileMeshData<PlyColorAndValueVertex<float> >::addOutOfCorePoint_s(PlyColorAndValueVertex<float> const&) in libpoisson_recon.a(PoissonRecon.cpp.o)
      CoredFileMeshData<PlyColorAndValueVertex<float> >::addPolygon_s(std::__1::vector<int, std::__1::allocator<int> > const&) in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..237 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..239 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..244 in libpoisson_recon.a(PoissonRecon.cpp.o)
      ...
  "___kmpc_dispatch_init_4", referenced from:
      _.omp_outlined. in colmap.cc.o
      _.omp_outlined..370 in colmap.cc.o
      _.omp_outlined..420 in colmap.cc.o
      _.omp_outlined..422 in colmap.cc.o
      _.omp_outlined..103 in libcolmap.a(matching.cc.o)
      _.omp_outlined..104 in libcolmap.a(matching.cc.o)
      _.omp_outlined..155 in libcolmap.a(matching.cc.o)
      ...
  "___kmpc_dispatch_next_4", referenced from:
      _.omp_outlined. in colmap.cc.o
      _.omp_outlined..370 in colmap.cc.o
      _.omp_outlined..420 in colmap.cc.o
      _.omp_outlined..422 in colmap.cc.o
      _.omp_outlined..103 in libcolmap.a(matching.cc.o)
      _.omp_outlined..104 in libcolmap.a(matching.cc.o)
      _.omp_outlined..155 in libcolmap.a(matching.cc.o)
      ...
  "___kmpc_end_critical", referenced from:
      _.omp_outlined..189 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..217 in libpoisson_recon.a(PoissonRecon.cpp.o)
      CoredFileMeshData<PlyColorAndValueVertex<float> >::addOutOfCorePoint_s(PlyColorAndValueVertex<float> const&) in libpoisson_recon.a(PoissonRecon.cpp.o)
      CoredFileMeshData<PlyColorAndValueVertex<float> >::addPolygon_s(std::__1::vector<int, std::__1::allocator<int> > const&) in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..237 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..239 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..244 in libpoisson_recon.a(PoissonRecon.cpp.o)
      ...
  "___kmpc_end_reduce", referenced from:
      _.omp_outlined. in colmap.cc.o
      _.omp_outlined..370 in colmap.cc.o
      _.omp_outlined..420 in colmap.cc.o
      _.omp_outlined..422 in colmap.cc.o
      _.omp_outlined..103 in libcolmap.a(matching.cc.o)
      _.omp_outlined..104 in libcolmap.a(matching.cc.o)
      _.omp_outlined..155 in libcolmap.a(matching.cc.o)
      ...
  "___kmpc_end_reduce_nowait", referenced from:
      _.omp_outlined..175 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..177 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..180 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..195 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..197 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..199 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..202 in libpoisson_recon.a(PoissonRecon.cpp.o)
      ...
  "___kmpc_for_static_fini", referenced from:
      _.omp_outlined. in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..161 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..162 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..163 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..166 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..167 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..174 in libpoisson_recon.a(PoissonRecon.cpp.o)
      ...
  "___kmpc_for_static_init_4", referenced from:
      _.omp_outlined. in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..161 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..162 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..163 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..166 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..167 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..174 in libpoisson_recon.a(PoissonRecon.cpp.o)
      ...
  "___kmpc_fork_call", referenced from:
      flann::NNIndex<flann::L2<unsigned char> >::knnSearch(flann::Matrix<unsigned char> const&, flann::Matrix<unsigned long>&, flann::Matrix<float>&, unsigned long, flann::SearchParams const&) const in colmap.cc.o
      flann::LshIndex<flann::L2<unsigned char> >::knnSearch(flann::Matrix<unsigned char> const&, flann::Matrix<unsigned long>&, flann::Matrix<float>&, unsigned long, flann::SearchParams const&) const in colmap.cc.o
      void Eigen::internal::parallelize_gemm<true, Eigen::internal::gemm_functor<float, long, Eigen::internal::general_matrix_matrix_product<long, float, 0, false, float, 0, false, 0>, Eigen::Matrix<float, -1, 128, 0, -1, 128>, Eigen::Matrix<float, 128, -1, 0, 128, -1>, Eigen::Matrix<float, -1, 1, 0, -1, 1>, Eigen::internal::gemm_blocking_space<0, float, float, -1, 1, 128, 1, false> >, long>(Eigen::internal::gemm_functor<float, long, Eigen::internal::general_matrix_matrix_product<long, float, 0, false, float, 0, false, 0>, Eigen::Matrix<float, -1, 128, 0, -1, 128>, Eigen::Matrix<float, 128, -1, 0, 128, -1>, Eigen::Matrix<float, -1, 1, 0, -1, 1>, Eigen::internal::gemm_blocking_space<0, float, float, -1, 1, 128, 1, false> > const&, long, long, long, bool) in colmap.cc.o
      colmap::SpatialFeatureMatcher::Run() in libcolmap.a(matching.cc.o)
      flann::NNIndex<flann::L2<float> >::knnSearch(flann::Matrix<float> const&, flann::Matrix<unsigned long>&, flann::Matrix<float>&, unsigned long, flann::SearchParams const&) const in libcolmap.a(matching.cc.o)
      void Eigen::internal::parallelize_gemm<true, Eigen::internal::gemm_functor<float, long, Eigen::internal::general_matrix_matrix_product<long, float, 0, false, float, 0, false, 0>, Eigen::Matrix<float, -1, 128, 0, -1, 128>, Eigen::Matrix<float, 128, -1, 0, 128, -1>, Eigen::Matrix<float, -1, 1, 0, -1, 1>, Eigen::internal::gemm_blocking_space<0, float, float, -1, 1, 128, 1, false> >, long>(Eigen::internal::gemm_functor<float, long, Eigen::internal::general_matrix_matrix_product<long, float, 0, false, float, 0, false, 0>, Eigen::Matrix<float, -1, 128, 0, -1, 128>, Eigen::Matrix<float, 128, -1, 0, 128, -1>, Eigen::Matrix<float, -1, 1, 0, -1, 1>, Eigen::internal::gemm_blocking_space<0, float, float, -1, 1, 128, 1, false> > const&, long, long, long, bool) in libcolmap.a(matching.cc.o)
      flann::NNIndex<flann::L2<unsigned char> >::knnSearch(flann::Matrix<unsigned char> const&, flann::Matrix<unsigned long>&, flann::Matrix<float>&, unsigned long, flann::SearchParams const&) const in libcolmap.a(matching.cc.o)
      ...
  "___kmpc_global_thread_num", referenced from:
      flann::NNIndex<flann::L2<unsigned char> >::knnSearch(flann::Matrix<unsigned char> const&, flann::Matrix<unsigned long>&, flann::Matrix<float>&, unsigned long, flann::SearchParams const&) const in colmap.cc.o
      _.omp_outlined. in colmap.cc.o
      _.omp_outlined..370 in colmap.cc.o
      flann::LshIndex<flann::L2<unsigned char> >::knnSearch(flann::Matrix<unsigned char> const&, flann::Matrix<unsigned long>&, flann::Matrix<float>&, unsigned long, flann::SearchParams const&) const in colmap.cc.o
      _.omp_outlined..420 in colmap.cc.o
      _.omp_outlined..422 in colmap.cc.o
      void Eigen::internal::parallelize_gemm<true, Eigen::internal::gemm_functor<float, long, Eigen::internal::general_matrix_matrix_product<long, float, 0, false, float, 0, false, 0>, Eigen::Matrix<float, -1, 128, 0, -1, 128>, Eigen::Matrix<float, 128, -1, 0, 128, -1>, Eigen::Matrix<float, -1, 1, 0, -1, 1>, Eigen::internal::gemm_blocking_space<0, float, float, -1, 1, 128, 1, false> >, long>(Eigen::internal::gemm_functor<float, long, Eigen::internal::general_matrix_matrix_product<long, float, 0, false, float, 0, false, 0>, Eigen::Matrix<float, -1, 128, 0, -1, 128>, Eigen::Matrix<float, 128, -1, 0, 128, -1>, Eigen::Matrix<float, -1, 1, 0, -1, 1>, Eigen::internal::gemm_blocking_space<0, float, float, -1, 1, 128, 1, false> > const&, long, long, long, bool) in colmap.cc.o
      ...
  "___kmpc_push_num_threads", referenced from:
      flann::NNIndex<flann::L2<unsigned char> >::knnSearch(flann::Matrix<unsigned char> const&, flann::Matrix<unsigned long>&, flann::Matrix<float>&, unsigned long, flann::SearchParams const&) const in colmap.cc.o
      flann::LshIndex<flann::L2<unsigned char> >::knnSearch(flann::Matrix<unsigned char> const&, flann::Matrix<unsigned long>&, flann::Matrix<float>&, unsigned long, flann::SearchParams const&) const in colmap.cc.o
      void Eigen::internal::parallelize_gemm<true, Eigen::internal::gemm_functor<float, long, Eigen::internal::general_matrix_matrix_product<long, float, 0, false, float, 0, false, 0>, Eigen::Matrix<float, -1, 128, 0, -1, 128>, Eigen::Matrix<float, 128, -1, 0, 128, -1>, Eigen::Matrix<float, -1, 1, 0, -1, 1>, Eigen::internal::gemm_blocking_space<0, float, float, -1, 1, 128, 1, false> >, long>(Eigen::internal::gemm_functor<float, long, Eigen::internal::general_matrix_matrix_product<long, float, 0, false, float, 0, false, 0>, Eigen::Matrix<float, -1, 128, 0, -1, 128>, Eigen::Matrix<float, 128, -1, 0, 128, -1>, Eigen::Matrix<float, -1, 1, 0, -1, 1>, Eigen::internal::gemm_blocking_space<0, float, float, -1, 1, 128, 1, false> > const&, long, long, long, bool) in colmap.cc.o
      colmap::SpatialFeatureMatcher::Run() in libcolmap.a(matching.cc.o)
      flann::NNIndex<flann::L2<float> >::knnSearch(flann::Matrix<float> const&, flann::Matrix<unsigned long>&, flann::Matrix<float>&, unsigned long, flann::SearchParams const&) const in libcolmap.a(matching.cc.o)
      void Eigen::internal::parallelize_gemm<true, Eigen::internal::gemm_functor<float, long, Eigen::internal::general_matrix_matrix_product<long, float, 0, false, float, 0, false, 0>, Eigen::Matrix<float, -1, 128, 0, -1, 128>, Eigen::Matrix<float, 128, -1, 0, 128, -1>, Eigen::Matrix<float, -1, 1, 0, -1, 1>, Eigen::internal::gemm_blocking_space<0, float, float, -1, 1, 128, 1, false> >, long>(Eigen::internal::gemm_functor<float, long, Eigen::internal::general_matrix_matrix_product<long, float, 0, false, float, 0, false, 0>, Eigen::Matrix<float, -1, 128, 0, -1, 128>, Eigen::Matrix<float, 128, -1, 0, 128, -1>, Eigen::Matrix<float, -1, 1, 0, -1, 1>, Eigen::internal::gemm_blocking_space<0, float, float, -1, 1, 128, 1, false> > const&, long, long, long, bool) in libcolmap.a(matching.cc.o)
      flann::NNIndex<flann::L2<unsigned char> >::knnSearch(flann::Matrix<unsigned char> const&, flann::Matrix<unsigned long>&, flann::Matrix<float>&, unsigned long, flann::SearchParams const&) const in libcolmap.a(matching.cc.o)
      ...
  "___kmpc_reduce", referenced from:
      _.omp_outlined. in colmap.cc.o
      _.omp_outlined..370 in colmap.cc.o
      _.omp_outlined..420 in colmap.cc.o
      _.omp_outlined..422 in colmap.cc.o
      _.omp_outlined..103 in libcolmap.a(matching.cc.o)
      _.omp_outlined..104 in libcolmap.a(matching.cc.o)
      _.omp_outlined..155 in libcolmap.a(matching.cc.o)
      ...
  "___kmpc_reduce_nowait", referenced from:
      _.omp_outlined..175 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..177 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..180 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..195 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..197 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..199 in libpoisson_recon.a(PoissonRecon.cpp.o)
      _.omp_outlined..202 in libpoisson_recon.a(PoissonRecon.cpp.o)
      ...
  "_omp_get_max_threads", referenced from:
      void Eigen::internal::parallelize_gemm<true, Eigen::internal::gemm_functor<float, long, Eigen::internal::general_matrix_matrix_product<long, float, 0, false, float, 0, false, 0>, Eigen::Matrix<float, -1, 128, 0, -1, 128>, Eigen::Matrix<float, 128, -1, 0, 128, -1>, Eigen::Matrix<float, -1, 1, 0, -1, 1>, Eigen::internal::gemm_blocking_space<0, float, float, -1, 1, 128, 1, false> >, long>(Eigen::internal::gemm_functor<float, long, Eigen::internal::general_matrix_matrix_product<long, float, 0, false, float, 0, false, 0>, Eigen::Matrix<float, -1, 128, 0, -1, 128>, Eigen::Matrix<float, 128, -1, 0, 128, -1>, Eigen::Matrix<float, -1, 1, 0, -1, 1>, Eigen::internal::gemm_blocking_space<0, float, float, -1, 1, 128, 1, false> > const&, long, long, long, bool) in colmap.cc.o
      void Eigen::internal::generic_product_impl<Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<double, double>, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, 3, -1, 0, 3, -1> const> const, Eigen::Matrix<double, 3, -1, 0, 3, -1> const>, Eigen::Transpose<Eigen::Matrix<double, 3, -1, 0, 3, -1> const>, Eigen::DenseShape, Eigen::DenseShape, 8>::scaleAndAddTo<Eigen::Matrix<double, 3, 3, 0, 3, 3> >(Eigen::Matrix<double, 3, 3, 0, 3, 3>&, Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<double, double>, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, 3, -1, 0, 3, -1> const> const, Eigen::Matrix<double, 3, -1, 0, 3, -1> const> const&, Eigen::Transpose<Eigen::Matrix<double, 3, -1, 0, 3, -1> const> const&, double const&) in libcolmap.a(reconstruction.cc.o)
      void Eigen::internal::parallelize_gemm<true, Eigen::internal::gemm_functor<float, long, Eigen::internal::general_matrix_matrix_product<long, float, 0, false, float, 0, false, 0>, Eigen::Matrix<float, -1, 128, 0, -1, 128>, Eigen::Matrix<float, 128, -1, 0, 128, -1>, Eigen::Matrix<float, -1, 1, 0, -1, 1>, Eigen::internal::gemm_blocking_space<0, float, float, -1, 1, 128, 1, false> >, long>(Eigen::internal::gemm_functor<float, long, Eigen::internal::general_matrix_matrix_product<long, float, 0, false, float, 0, false, 0>, Eigen::Matrix<float, -1, 128, 0, -1, 128>, Eigen::Matrix<float, 128, -1, 0, 128, -1>, Eigen::Matrix<float, -1, 1, 0, -1, 1>, Eigen::internal::gemm_blocking_space<0, float, float, -1, 1, 128, 1, false> > const&, long, long, long, bool) in libcolmap.a(matching.cc.o)
      void Eigen::internal::generic_product_impl<Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<double, double>, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, 3, -1, 0, 3, -1> const> const, Eigen::Matrix<double, 3, -1, 0, 3, -1> const>, Eigen::Transpose<Eigen::Matrix<double, 3, -1, 0, 3, -1> const>, Eigen::DenseShape, Eigen::DenseShape, 8>::scaleAndAddTo<Eigen::Matrix<double, 3, 3, 0, 3, 3> >(Eigen::Matrix<double, 3, 3, 0, 3, 3>&, Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<double, double>, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, 3, -1, 0, 3, -1> const> const, Eigen::Matrix<double, 3, -1, 0, 3, -1> const> const&, Eigen::Transpose<Eigen::Matrix<double, 3, -1, 0, 3, -1> const> const&, double const&) in libcolmap.a(similarity_transform.cc.o)
      void Eigen::internal::generic_product_impl<Eigen::Transpose<Eigen::Matrix<double, -1, 12, 0, -1, 12> const>, Eigen::Matrix<double, -1, 12, 0, -1, 12>, Eigen::DenseShape, Eigen::DenseShape, 8>::scaleAndAddTo<Eigen::Matrix<double, 12, 12, 0, 12, 12> >(Eigen::Matrix<double, 12, 12, 0, 12, 12>&, Eigen::Transpose<Eigen::Matrix<double, -1, 12, 0, -1, 12> const> const&, Eigen::Matrix<double, -1, 12, 0, -1, 12> const&, double const&) in libcolmap.a(absolute_pose.cc.o)
      void Eigen::internal::generic_product_impl<Eigen::Transpose<Eigen::Matrix<double, -1, 3, 0, -1, 3> >, Eigen::Matrix<double, -1, 3, 0, -1, 3>, Eigen::DenseShape, Eigen::DenseShape, 8>::scaleAndAddTo<Eigen::Matrix<double, 3, 3, 0, 3, 3> >(Eigen::Matrix<double, 3, 3, 0, 3, 3>&, Eigen::Transpose<Eigen::Matrix<double, -1, 3, 0, -1, 3> > const&, Eigen::Matrix<double, -1, 3, 0, -1, 3> const&, double const&) in libcolmap.a(absolute_pose.cc.o)
      void Eigen::internal::parallelize_gemm<true, Eigen::internal::gemm_functor<double, long, Eigen::internal::general_matrix_matrix_product<long, double, 0, false, double, 0, false, 0>, Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, Eigen::internal::gemm_blocking_space<0, double, double, -1, -1, -1, 1, false> >, long>(Eigen::internal::gemm_functor<double, long, Eigen::internal::general_matrix_matrix_product<long, double, 0, false, double, 0, false, 0>, Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, Eigen::internal::gemm_blocking_space<0, double, double, -1, -1, -1, 1, false> > const&, long, long, long, bool) in libcolmap.a(essential_matrix.cc.o)
      ...
  "_omp_get_num_procs", referenced from:
      __GLOBAL__sub_I_PoissonRecon.cpp in libpoisson_recon.a(PoissonRecon.cpp.o)
  "_omp_get_num_threads", referenced from:
      void Eigen::internal::parallelize_gemm<true, Eigen::internal::gemm_functor<float, long, Eigen::internal::general_matrix_matrix_product<long, float, 0, false, float, 0, false, 0>, Eigen::Matrix<float, -1, 128, 0, -1, 128>, Eigen::Matrix<float, 128, -1, 0, 128, -1>, Eigen::Matrix<float, -1, 1, 0, -1, 1>, Eigen::internal::gemm_blocking_space<0, float, float, -1, 1, 128, 1, false> >, long>(Eigen::internal::gemm_functor<float, long, Eigen::internal::general_matrix_matrix_product<long, float, 0, false, float, 0, false, 0>, Eigen::Matrix<float, -1, 128, 0, -1, 128>, Eigen::Matrix<float, 128, -1, 0, 128, -1>, Eigen::Matrix<float, -1, 1, 0, -1, 1>, Eigen::internal::gemm_blocking_space<0, float, float, -1, 1, 128, 1, false> > const&, long, long, long, bool) in colmap.cc.o
      _.omp_outlined..486 in colmap.cc.o
      Eigen::internal::general_matrix_matrix_product<long, float, 0, false, float, 0, false, 0>::run(long, long, long, float const*, long, float const*, long, float*, long, float, Eigen::internal::level3_blocking<float, float>&, Eigen::internal::GemmParallelInfo<long>*) in colmap.cc.o
      Eigen::internal::general_matrix_matrix_product<long, double, 0, false, double, 1, false, 0>::run(long, long, long, double const*, long, double const*, long, double*, long, double, Eigen::internal::level3_blocking<double, double>&, Eigen::internal::GemmParallelInfo<long>*) in libcolmap.a(reconstruction.cc.o)
      void Eigen::internal::parallelize_gemm<true, Eigen::internal::gemm_functor<float, long, Eigen::internal::general_matrix_matrix_product<long, float, 0, false, float, 0, false, 0>, Eigen::Matrix<float, -1, 128, 0, -1, 128>, Eigen::Matrix<float, 128, -1, 0, 128, -1>, Eigen::Matrix<float, -1, 1, 0, -1, 1>, Eigen::internal::gemm_blocking_space<0, float, float, -1, 1, 128, 1, false> >, long>(Eigen::internal::gemm_functor<float, long, Eigen::internal::general_matrix_matrix_product<long, float, 0, false, float, 0, false, 0>, Eigen::Matrix<float, -1, 128, 0, -1, 128>, Eigen::Matrix<float, 128, -1, 0, 128, -1>, Eigen::Matrix<float, -1, 1, 0, -1, 1>, Eigen::internal::gemm_blocking_space<0, float, float, -1, 1, 128, 1, false> > const&, long, long, long, bool) in libcolmap.a(matching.cc.o)
      _.omp_outlined. in libcolmap.a(matching.cc.o)
      Eigen::internal::general_matrix_matrix_product<long, float, 0, false, float, 0, false, 0>::run(long, long, long, float const*, long, float const*, long, float*, long, float, Eigen::internal::level3_blocking<float, float>&, Eigen::internal::GemmParallelInfo<long>*) in libcolmap.a(matching.cc.o)
      ...
  "_omp_get_thread_limit", referenced from:
      _vl_get_thread_limit in libvlfeat.a(generic.c.o)
  "_omp_get_thread_num", referenced from:
      _.omp_outlined..486 in colmap.cc.o
      Eigen::internal::general_matrix_matrix_product<long, float, 0, false, float, 0, false, 0>::run(long, long, long, float const*, long, float const*, long, float*, long, float, Eigen::internal::level3_blocking<float, float>&, Eigen::internal::GemmParallelInfo<long>*) in colmap.cc.o
      Eigen::internal::general_matrix_matrix_product<long, double, 0, false, double, 1, false, 0>::run(long, long, long, double const*, long, double const*, long, double*, long, double, Eigen::internal::level3_blocking<double, double>&, Eigen::internal::GemmParallelInfo<long>*) in libcolmap.a(reconstruction.cc.o)
      _.omp_outlined. in libcolmap.a(matching.cc.o)
      Eigen::internal::general_matrix_matrix_product<long, float, 0, false, float, 0, false, 0>::run(long, long, long, float const*, long, float const*, long, float*, long, float, Eigen::internal::level3_blocking<float, float>&, Eigen::internal::GemmParallelInfo<long>*) in libcolmap.a(matching.cc.o)
      Eigen::internal::general_matrix_matrix_product<long, double, 0, false, double, 1, false, 0>::run(long, long, long, double const*, long, double const*, long, double*, long, double, Eigen::internal::level3_blocking<double, double>&, Eigen::internal::GemmParallelInfo<long>*) in libcolmap.a(similarity_transform.cc.o)
      _.omp_outlined. in libpoisson_recon.a(PoissonRecon.cpp.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/exe/colmap] Error 1
make[1]: *** [src/exe/CMakeFiles/colmap_exe.dir/all] Error 2
make: *** [all] Error 2
 @ahojnnes @cebe @gerardobort @omigeot @sniklaus

**Comment by cebe** [comment]
looks like some of your libraries are installed for a different architecture?

A similar issue is here: https://stackoverflow.com/a/30582528/1106908

**Comment by tub-sgg** [comment]
what kind of libraries you refer to? @cebe

**Comment by tub-sgg** [comment]
only xcode can succeed to compile this on MacOS:
cmake -DCMAKE_BUILD_TYPE=RELEASE -G "Xcode" ..       xcodebuild -configuration Release


HOPE THIS CAN HELP SOMEONE IF ENCOUNTER THE SAME PROBLEM

THEN I CLOSE THIS ISSUE

**Comment by sbahir** [comment]
@tub-sgg I had a similar issue but when running `cmake -DCMAKE_BUILD_TYPE=RELEASE -G "Xcode" .. xcodebuild -configuration Release` 

I got this error 

```CMake Error: The source directory "/Users/saad/Desktop/AiFi/3_tools/colmap/build/Release" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```
Did you get the same ?

**Comment by sbahir** [comment]
@tub-sgg Which version of XCode did you use ?
