### ISSUE TITLE
Help - QOpenGLWidget: failed to create context

### ISSUE THREAD

**Issue by MarcWong** [colmap/colmap#749]
**Describe the bug**
Actually it is not a bug, but an annoying environmental problem I've encountered these days...

**To Reproduce**
1. install Colmap 3.6, everything works well
2. install python-pcl by anaconda (this repo would install another qt in my conda env)
3. enter Colmap gui, see a totally black window with console errors (see Screenshot 1):
```
QOpenGLWidget: failed to create context
QOpenGLWidget: failed to create context
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
```
clicking generates more lines of ```composeAndFlush: makeCurrent() failed```,
and sometimes it leads to segmentation fault (see Screenshot 2)

4. I tried ```qmake -v```, it gives out I'm using qt 5.9.7 automatically installed by anaconda. I thought that the overwrite of qt paths was to blame. I removed all of my qt envs, and reinstalled qt 5.9.5 by apt install. I tested ```qmake -v```, it found the one in ```/usr/lib/x86_64-linux-gnu```
5. I rebuilt colmap by typing ```make clean, make, make install```, everything succeeded.
6. But the error in step 3 just won't disappear...

**Expected behavior**
I simply wanted to use colmap GUI, can anyone give me suggestions for my situation?

**Screenshots**
![image](https://user-images.githubusercontent.com/8611784/70124212-35726a00-16af-11ea-9412-847dbe752faf.png)

![image](https://user-images.githubusercontent.com/8611784/70125537-f1cd2f80-16b1-11ea-884f-417bb5d09366.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version:
     - colmap: 3.6
     - qt: 5.9.5 / 5.9.7

**Comment by MarcWong** [comment]
fixed it by adding "export QT_SELECTION=path/to/qmake" and restarting...

**Comment by Hiusam** [comment]
I have the same problem as you. I am using colmap on my remote server which runs:
OS:Ubuntu 18.04
colmap:3.7
And I use my MacBook with XQuartz to open colmap gui on remote server. But it doesn't work and the behavior is the same as you. Actually, I succeeded at first but after I restarted my MacBook, it failed. 
I have tried your method both on my Mac and my remote server, but nothing changes. Can you tell me what I can do and what do you mean by "adding "export QT_SELECTION=path/to/qmake" and restarting..."?
![Screen Shot 2020-11-23 at 23 28 57](https://user-images.githubusercontent.com/43744525/99982208-40a13700-2de5-11eb-9b37-5d160b47e641.png)
![image](https://user-images.githubusercontent.com/43744525/99982286-54e53400-2de5-11eb-8226-4ecdd58a632d.png)

**Comment by MarcWong** [comment]
You need to specify your qmake path by adding `export QT_SELECTION=path/to/qmake` to your shell profile, or it will use a false version of qt by default

**Comment by SBCV** [comment]
I received the same error messages, i.e. 
```
QOpenGLWidget: failed to create context
composeAndFlush: makeCurrent() failed
```

However in my case (also Ubuntu 18.04) `qmake -v` produced the following output: `qmake: could not find a Qt installation of ''`
I fixed it with `sudo apt-get install qt5-default` and a restart.
