### ISSUE TITLE
Is there an easy way to get the pose for new registered images ?

### ISSUE THREAD

**Issue by alexs7** [colmap/colmap#750]
I am using this to register new images in the model, 

https://colmap.github.io/faq.html#register-localize-new-images-into-an-existing-reconstruction

The problem is that the images tables values for _prior_qw, prior_qx,..._ are just null. So I have to use _model_converter_ to get the _images.txt_ file and then read the poses.. But that adds time. Is there a way to populate the values in the _images_ table ?

**Comment by tsattler** [comment]
The results of the reconstruction process are never written to the prior values in the tables. If you need this, I assume that you would need to write code for this yourself.

**Comment by alexs7** [comment]
@tsattler Ok thanks! I could just use the _images.txt_ file for now.
