### ISSUE TITLE
Clarify license status

### ISSUE THREAD

**Issue by rkern** [colmap/colmap#752]
Your `COPYING.txt` refers to various "optional dependencies" that may have different licenses. However, I do not see any optional dependencies, only required dependencies. Graclus and PBA are GPLed, and LSD is AGPLed. Given the copyleft nature of these licenses, Colmap, when built into a binary, is necessarily GPLed (with AGPL obligations for the LSD library itself). Your source code in `src/` is BSD-licensed, but the assembled binary is not.

The AGPL is quite an extreme version of copyleft and imposes a number of obligations that even the GPL does not. ~There are other BSD-licensed implementations of the LSD out there. [OpenCV has one](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/lsd.cpp).~ (edit: looks like the actual implementation was removed, presumably because it copied from the same sources as yours. Alas.)

But even if you do not replace the LSD code, I do recommend correcting `COPYING.txt` to note that you have required GPL and AGPL dependencies, and that Colmap as a whole is licensed under the GPL even if the parts in `src/` are also licensed as BSD.

Thank you.

**Comment by ahojnnes** [comment]
Thanks, the "optional" is indeed not reflecting the latest state of the system anymore. I pushed a commit to fix the formulation.

**Comment by cuixinye** [comment]
@rkern @ahojnnes Could you please re-open the issue to update LSD part to permission license.
Refer to [opencv_contrib/issues/2524](https://github.com/opencv/opencv_contrib/issues/2524), it's resolved in opencv project. 
I would be great if the whole colmap work could remove AGPL code.
Other reference: https://github.com/rafael-grompone-von-gioi/binomial_nfa/tree/main

**Comment by ahojnnes** [comment]
@cuixinye As of this PR, colmap can be built without LSD: https://github.com/colmap/colmap/pull/2578
