### ISSUE TITLE
stereo fusion  report a bug -----Check failed: width_ > 0 (0 vs. 0)

### ISSUE THREAD

**Issue by yuancaimaiyi** [colmap/colmap#778]
@ahojnnes @tsattler 
Hi ,when I run stere fusion .I meet this error(never met before).
I check the depth map and normal map,no image broken!
I am confused,thanks !
![fusion](https://user-images.githubusercontent.com/28293910/71572417-f43c7100-2b19-11ea-9abb-dd7d879b8a69.png)

**Comment by NGeorgescu** [comment]
I am running into the exact same issue.  Was there a fix?

**Comment by Techhooli** [comment]
How to fix it?  So confusing.

**Comment by NGeorgescu** [comment]
Hmm try removing the image mentioned in the error and run again

**Comment by tsattler** [comment]
I had the same problem at some point. I think there were some issues where a depth map was not properly computed. Re-running the dense reconstruction pipeline solved the issue for me.

**Comment by prototrash** [comment]
Is there a good way to find where the problem map is? will it be visible while looking at the image properties or by viewing the maps in colmap? Sometimes I get this issue with sets that take several days to compute on a very noisy machine... would be much better to only recompute what is necessary
