### ISSUE TITLE
Possible to parallelize dense mapping?

### ISSUE THREAD

**Issue by lixx2938** [colmap/colmap#78]
Hi,

Is it possible to parallelize CUDA dense mapping for large scale dataset? Or it is impossible because there is dependence between each image ? Because I tried to use OpenMP to paralleize the outermost for loop in patchmatch.cc but I got a bunch of weird results in the end.

**Comment by ahojnnes** [comment]
Yes, it is possible to parallelize. There is a parallelized version implemented at https://github.com/bennihepp/colmap but I haven't had time to integrate it yet.

**Comment by ahojnnes** [comment]
This is implemented in the latest commit now and documented here: file:///Users/jsch/Development/colmap/doc/_build/html/faq.html#multi-gpu-support-in-dense-reconstruction

Thanks for your input.
