### ISSUE TITLE
Register a new image in realtime.

### ISSUE THREAD

**Issue by SkyRiderMike** [colmap/colmap#780]
I read the colmap FAQ and using the registration method describe as: 
https://colmap.github.io/faq.html#register-localize-new-images-into-an-existing-reconstruction

However, the vocab_tree_matcher seems not able to run in real-time, it costs almost 500 seconds to form the visual index. Is there any colmap tools to register a new image in real-time ?

**Comment by ahojnnes** [comment]
You would have to write your own custom matcher (as a server) that loads and builds the index only once and then takes registration requests.

**Comment by SkyRiderMike** [comment]
Thanks so much for your reply!  
    I know the paper describe the  visual index, which is also your an amazing work("A Vote-and-Verify Strategy for Fast Spatial Verification in Image Retrieval" )  
   However, I don't know the theory about visual index for now. Is that possible to build the index only once?  If that is possible in theory, i will do that myself.

**Comment by tsattler** [comment]
@SkyRiderMike Yes, you can build the index once offline if the set of database images that you want to match against remains the same. Things get a bit more complex if you want to add images to the index as you register them.

You can find more on the theory (and pointers to related work) behind visual indices in the paper you mentioned.

**Comment by SkyRiderMike** [comment]
@tsattler  Thank you so much!

**Comment by SkyRiderMike** [comment]
@tsattler Now i implement the real-time implementation. The 3D-2D matches are found by following steps:
1. found the similar image in the database through vocabulary tree with visual index.
2. perform 2D-2D matches and geometry vertification.
3. then get 3D-2D matches through 2D-2D matches

I realized that there might be an more direct way to get 3D-2D matches. And I also found your paper 
1. "Fast Image-Based Localization using Direct 2D-to-3D Matching."
2. Efficient & effective Prioritized Matching for Large-Scale Image-Based Localization.

And there is an open-source code : https://github.com/alexs7/ACG_Localizer  for ACG implementation.

Is that possible to use ACG search to archive a faster implementation than I have done as above ?
If yes, is that easy to re-implement ACG search code in colmap's framework ?

**Comment by tsattler** [comment]
I am planning to release a newer version of Active Search that supports Colmap models, but am currently not having enough time to work on this (due to the upcoming ECCV deadline and teaching).
I would assume that it is possible to get faster search times using Active Search, but this strongly depends on the model size as well.

**Comment by alexs7** [comment]
@SkyRiderMike Hello! I am working on a similar project. If I understood correctly you want to realtime localise images in a colmap map ? I think that is still an open research area, to achieve realtime performance ? Or maybe I didn't get your problem ?

**Comment by Asherchi** [comment]
> Active Search
hi, would you mind tell me what is Active Search? and I am not find in the paper or colmap projects.

**Comment by Asherchi** [comment]
> > Active Search
> > hi, would you mind tell me what is Active Search? and I am not find in the paper or colmap projects.

solved. Improving Image-Based Localization by Active Correspondence Search

**Comment by eltitano** [comment]
> > > Active Search
> > > hi, would you mind tell me what is Active Search? and I am not find in the paper or colmap projects.
> 
> solved. Improving Image-Based Localization by Active Correspondence Search

I assume further details are just too large to fit in the margin.
