### ISSUE TITLE
A point misplaced bug found in export model as other format

### ISSUE THREAD

**Issue by TroiiF** [colmap/colmap#781]
**Describe the bug**
I finished  some reconstruction in COLMAP-windows-3.5, when I tried to export model as .nvm, some points of this model have been misplaced. Then I tried to export .ply, the same thing happened. Again, I tried another data, the same. Then I tried to import the misplaced point cloud to COLMAP, the points are still misplaced.

I don't have any clue why this happens. Any idea?

**Screenshots**
![1](https://user-images.githubusercontent.com/23192308/72068756-c082f780-3320-11ea-9e01-77699923a13e.jpg)
![2](https://user-images.githubusercontent.com/23192308/72068758-c082f780-3320-11ea-9a0e-99d73aa949aa.jpg)
![3](https://user-images.githubusercontent.com/23192308/72068754-bfea6100-3320-11ea-9976-fe7db502ca81.jpg)

Another one:
![4](https://user-images.githubusercontent.com/23192308/72068908-017b0c00-3321-11ea-8e2b-7ac2c4294040.jpg)
![5](https://user-images.githubusercontent.com/23192308/72068905-00e27580-3321-11ea-95f8-6cd571a5edc3.jpg)
![6](https://user-images.githubusercontent.com/23192308/72068906-00e27580-3321-11ea-9c03-4c058247d247.jpg)

**Comment by tsattler** [comment]
Per default, COLMAPs gui only shows 3D points that have been triangulated from at least 3 cameras. You can control this in the rendering options.
When exporting a model, all 3D points are exported. This includes points triangulated from only 2 cameras, which are typically more noisy. 

I assume that the other renderers show all points, which seems to cause the confusion.

**Comment by TroiiF** [comment]
> Per default, COLMAPs gui only shows 3D points that have been triangulated from at least 3 cameras. You can control this in the rendering options.
> When exporting a model, all 3D points are exported. This includes points triangulated from only 2 cameras, which are typically more noisy.
> 
> I assume that the other renderers show all points, which seems to cause the confusion.

Hey tsattler, Thanks a lot! 
maybe I can use a filter to disable these 2-view points then.
