### ISSUE TITLE
Support multi-camera

### ISSUE THREAD

**Issue by SkyRiderMike** [colmap/colmap#782]
Does colmap support stereo camera for reconstruction?

reconstruction with single camera cannot recover the scale of the scene. Wish the reconstruction by stereo camera can take care of this

**Comment by tsattler** [comment]
At the moment, there is no possibility to enforce the stereo constraint during the reconstruction process. It is only possible to treat each image individually. You can enforce a global scale as a post-processing step (including the use of the `rig_bundle_adjuster` to enforce consistent relative poses). You can have a look here #626 #397
