### ISSUE TITLE
incremental mapper crashes when localizing new images from list

### ISSUE THREAD

**Issue by zAdamFox** [colmap/colmap#784]
Hello, I'm trying to localize some new images on existing model as described here https://colmap.github.io/faq.html#register-localize-new-images-into-an-existing-reconstruction

3-rd step command: 
**colmap mapper --database_path photos.db --image_path ../imgs/ --input_path . --output_path ../newmodel/**

output:

> ==============================================================================
> Loading database
> ==============================================================================
> 
> Loading cameras... 3 in 0.000s
> Loading matches... 2492 in 0.019s
> Loading images... 167 in 0.218s (connected 167)
> Building correspondence graph... in 0.182s (ignored 0)
> 
> Elapsed time: 0.007 [minutes]
> 
> 
> ==============================================================================
> Registering image #179 (141)
> ==============================================================================
> 
>   => Image sees 178 / 780 points
> 
> Pose refinement report
> ----------------------
>     Residuals : 368
>    Parameters : 8
>    Iterations : 8
>          Time : 0.00239396 [s]
>  Initial cost : 0.419616 [px]
>    Final cost : 0.35849 [px]
>   Termination : Convergence
> 
>   => Continued observations: 176
>   => Added observations: 387
> terminate called after throwing an instance of 'std::out_of_range'
>   what():  _Map_base::at
> *** Aborted at 1579105299 (unix time) try "date -d @1579105299" if you are using GNU date ***
> PC: @     0x7f1d73d3ee97 gsignal
> *** SIGABRT (@0x3e80000468b) received by PID 18059 (TID 0x7f1d6a1e7700) from PID 18059; stack trace: ***
>     @     0x7f1d7507d890 (unknown)
>     @     0x7f1d73d3ee97 gsignal
>     @     0x7f1d73d40801 abort
>     @     0x7f1d74962957 (unknown)
>     @     0x7f1d74968ab6 (unknown)
>     @     0x7f1d74968af1 std::terminate()
>     @     0x7f1d74968d24 __cxa_throw
>     @     0x7f1d7496482f (unknown)
>     @     0x55edeb2a3c44 (unknown)
>     @     0x55edeb17a682 (unknown)
>     @     0x55edeb17c40b (unknown)
>     @     0x55edeb31177c (unknown)
>     @     0x7f1d7499366f (unknown)
>     @     0x7f1d750726db start_thread
>     @     0x7f1d73e2188f clone
> Aborted (core dumped)

Debugging reveals that problem is on https://github.com/colmap/colmap/blob/dev/src/sfm/incremental_mapper.cc#L596 
here is the stack:
![stack](https://user-images.githubusercontent.com/59929623/72454666-1ce38c80-37e3-11ea-8ce5-689e15e40bb8.png)

Are there any fast fixes?

Thanks in advance!

**Comment by ahojnnes** [comment]
Indeed, this is a bug introduced by the most recent commit. It is fixed now in the develop branch. Thanks for reporting.

**Comment by zAdamFox** [comment]
Thank you, it's working fine now!
