### ISSUE TITLE
Application won't open on Mac (Version 10.11.6)

### ISSUE THREAD

**Issue by chrisscarffe** [colmap/colmap#786]
Hi, I'm trying to download COLMAP for a university project and I'm completely new to this so any help is greatly appreciated!

I have downloaded the following version:

https://github.com/colmap/colmap/releases/tag/3.6-dev.3

clicked: COLMAP-dev-mac-no-cuda.zip

Once the application has installed I right-clicked and opened the application and the following dialogue box popped up:

“COLMAP” is from an unidentified developer. Are you sure you want to open it?
Opening “COLMAP” will always allow it to run on this Mac.

I clicked "Open"

The icon then disappears from the dock and nothing happens. 

Now when I double click the application/right-click and open nothing happens.

I have tried redownloading the files a number of times but nothing happens!

Please help!

Thanks, 

Chris

**Comment by chrisscarffe** [comment]
Managed to get around this by doing the following:

Turn off firewall
Download the 'Release Version' instead: https://github.com/colmap/colmap/releases/tag/3.5

**Comment by tsattler** [comment]
I recommend having a look here: https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

**Comment by robclouth** [comment]
@chrisscarffe how did you fix this? I've tried different versions, they all just close immediately. It's nothing to do with the unidentified developer stuff, I've already done that.

**Comment by connellybarnes** [comment]
I confirm that the 3.7 and 3.5 official release versions of Colmap do not work on my Mac 10.15.7, also after following the suggestions of @tsattler .
Given that there are 10 thumbs up to the previous question from @robclouth , this thread appears to have been closed incorrectly by @chrisscarffe . I wonder whether anyone has been able to get the official Colmap releases running on their Mac? If not perhaps the maintainer should just delete the Mac releases and ask people to build from source.

**Comment by matyasszanto** [comment]
Just tried it, the workoraround recommended by chriscarffe works for me, too!

I'm on MacOS Monterey v.12.4, Intel MacMini

> Managed to get around this by doing the following:
> 
> Turn off firewall Download the 'Release Version' instead: https://github.com/colmap/colmap/releases/tag/3.5

**Comment by psandovalsegura** [comment]
[COLMAP v3.5](https://github.com/colmap/colmap/releases/tag/3.5) is working for me on:
- macOS Monterey 12.5.1
- M1 Pro

However, the current release version (3.7) https://github.com/colmap/colmap/releases/tag/3.7, and the previous release version (3.6) didn't work for me.
