### ISSUE TITLE
Is there any method to improve with 3D gt, rotation matrix & GPU?

### ISSUE THREAD

**Issue by ComputerMath** [colmap/colmap#796]
**Describe the bug**
1) 
I have a dataset in which it has images and its camera intrinsic matrx & Rotation matrix & 3D pose information.
From https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.html
I could make quaternion vector using above python library 
And made the translation vector using the fact that rotation matirx is orthogonal and 3D pose data.

But by making above information & using the **Reconstruct sparse/dense model from known camera poses** in https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses 's command

the result was weird (up: my result, below: true camera postiion)
![image](https://user-images.githubusercontent.com/29303833/74013736-7ac55780-49d0-11ea-9d04-2f179a124960.png)

![image](https://user-images.githubusercontent.com/29303833/74014602-5e2a1f00-49d2-11ea-826d-b62d110ff143.png)

Is there something wrong for what i did?

2)
since 1) was failed, I did the automatic reconstruction to make sparse reconstruction map.
And, to apply the 3D pose data I have (Not translation vector elements)
I did the Geo registration using 'colmap model_aligner~'  and put the 3D data into txt fie with image name

the result shape was quite great, but when I took the result's translation vector & quaternion vector 
and convert to 3D pose data, the result was not same as the information I gave into model_aligner.

Is there any problem in what i did?

3)
Is there any method to make use of GPU to make 'exhaustive_matcher' and 'mapper' phase faster?
I have 4 GPUs but it seems it does not fully use gpu and too rely on CPU.
When I apply to 'exhaustive_matcher' with about 9,000 data, it too about 24 hours to be done.

Thanks for future reply.

**Desktop (please complete the following information):**
 - OS: Ubuntu16

**Comment by tsattler** [comment]
@ComputerMath 
1. Are you sure you are providing the camera poses as `R`, `t` (i.e., a rotation `R` and translation `t` from world to camera coordinates, transforming a point `X_world` in world coordinates to a point in camera coordinates as `X_cam = R * X_world + t`), where `R` is represented by a unit quaternion. Looking at the poses you show, I would assume that either the rotation or translation (or both) are performing a transformation into the wrong direction. 

2. What you wrote in 2. seems to confirm the view that your input transformation was (partially) in the wrong direction. Also note that 3D reconstruction from images is only able to reconstruct the scene up to an unknown scaling factor, i.e., the camera poses you get from the automatic reconstruction pipeline will differ from your poses by some scaling factor.

3. The feature matcher already uses the GPU, although only a single GPU. Colmap's matcher is based on SiftGPU, which (if I remember correctly) supports the use of multiple GPUs. I would assume that you could modify Colmap's code such as to make use of multiple GPUs during matching (there might be an open or closed issue for this already). 
The mapper phase can make use of the GPU during bundle adjustment if you are using the SIMPLE_RADIAL model and if you do not share a camera model between multiple images. This is based on the PBA library, which however also only supports a single GPU (if I remember correctly). There might be bundle adjustment libraries out there that support multiple GPUs. In that case, you could integrate them into Colmap. Bundle adjustment is probably the most time-consuming part of the reconstruction process, so improving this stage should improve efficiency.
You can also try out the experimental hierarchical mapper (`colmap hierarchical_mapper`), which should be able to handle larger datasets more efficiently.

**Comment by ComputerMath** [comment]
Thanks for fast answering.

I may sure that my quat vector is not wrong because i'm using many library to change rotation matrix to quat vector but all of results are same.

It may be my translation vector being wrong.
I have 3D pose data which may be xyz coordinates.
The github.io says that
```
The local camera coordinate system of an image is defined in a way that the X axis points to the right, the Y axis to the bottom, and the Z axis to the front as seen from the image.
```

Then should I change xyz's elements by transforming into (-y)(z)(x) as seen below?

![image](https://user-images.githubusercontent.com/29303833/74088919-c6febd80-4ade-11ea-8f34-380ef27c4237.png)


Thank you in advance.

**Comment by tsattler** [comment]
I don't understand why you would want to -y,z,x as this does not seem to be the coordinate system to be used by ZED (and it is not the coordinate system used by Colmap).

Note that the transformation from rotation matrix to quaternion might be correct, but the rotation might still transform in the opposite direction of what colmap is expecting.

**Comment by ComputerMath** [comment]
I gained translation vector as the top image of my result  by equation below

I have center of projection/camera of 3D vector (camera pose) (let it be called ```p``` )
And in github.io, coordinates of the projection/camera center be given by ``` R^t * t ```
where R is rotation matrix and t is translation vector
So, by using orthogonality of R, I got ```t``` by ``` - R * p ```
is there any wrong thing?

**Comment by tsattler** [comment]
This is not fully correct.
If the projection center in world coordinates is given by `p`, then the relation to the translation `t` and the rotation `R` is given by `p = -R^t * t`. This is of course assuming that the rotation is from world to camera coordinates. As such, you get the translation vector as `t = -R * t`. Again, this assumes that `R` is a rotation from world to camera coordinates.

**Comment by ComputerMath** [comment]
Can you tell me more precisely What you are saying in ```t = -R * t```?
I have 3 by 3 camera matrix ```K``` and ```R and cop(center of projection)``` which define camera pose.
I think I do not have anything that changes world to camera coordinates, right?
Sorry for bothering because of my lack of knowledge

**Comment by tsattler** [comment]
Sorry, I meant `t = -R * p`. Typo from my side.

If you have a rotation matrix, then this will transform from one coordinate system to another. If it transforms from a global coordinate system into the local camera coordinate system, then you can use it. If it transforms from the camera coordinate system to a global coordinate system, you have to use its transpose. What I am recommending is to determine in which coordinate system all the information that you have is given.

**Comment by ComputerMath** [comment]
Thanks for long reply.
I think I have to investigate or study about my Rotation matrix...

**Comment by ahojnnes** [comment]
Just to clarify, colmap will use all GPUs in your system automatically, if available. Each GPU is used in a separate extraction and matching thread (This only works with CUDA).
