### ISSUE TITLE
Issue in two_view_geometry.cc

### ISSUE THREAD

**Issue by daleydeng** [colmap/colmap#8]
I think there is a bug in two_view_geometry.cc: 159->174,

 PoseFromHomographyMatrix need the normlized world points due to the call chain:

 PoseFromHomographyMatrix -> CheckCheirality -> TriangulatePoint (this needs the normalized world points)

\+    // Extract normalized inlier points.
\+  std::vector<Eigen::Vector3d> inlier_points1_N;
\+  inlier_points1_N.reserve(inlier_matches.size());
\+  std::vector<Eigen::Vector3d> inlier_points2_N;
\+  inlier_points2_N.reserve(inlier_matches.size());
\+  for (const auto& match : inlier_matches) {
\+    const point2D_t idx1 = match.point2D_idx1;
\+    const point2D_t idx2 = match.point2D_idx2;
\+    inlier_points1_N.push_back(camera1.ImageToWorld(points1[idx1]));
\+    inlier_points2_N.push_back(camera2.ImageToWorld(points2[idx2]));
\+  }

\-     // Extract inlier points.
\-    std::vector<Eigen::Vector2d> inlier_points1;
\-    inlier_points1.reserve(inlier_matches.size());
\-    std::vector<Eigen::Vector2d> inlier_points2;
\-    inlier_points2.reserve(inlier_matches.size());
\-    for (const auto& match : inlier_matches) {
\-      inlier_points1.push_back(points1[match.point2D_idx1]);
\-      inlier_points2.push_back(points2[match.point2D_idx2]);
 \-}
     Eigen::Vector3d n;
     PoseFromHomographyMatrix(H, camera1.CalibrationMatrix(),
\-                             camera2.CalibrationMatrix(), inlier_points1,
\-                             inlier_points2, &R, &tvec, &n, &points3D);
\+                             camera2.CalibrationMatrix(), inlier_points1_N,
\+                             inlier_points2_N, &R, &tvec, &n, &points3D);
   }

**Comment by ahojnnes** [comment]
You are absolutely right. I did some restructuring before publishing the code and it seems I introduced this bug here. Thanks for reporting! Fixed in https://github.com/colmap/colmap/commit/9871baae8d954e57a1b52b560e4a9382dbc6e0e6

**Comment by ahojnnes** [comment]
Closing this as fixed, feel free to reopen if necessary.
