### ISSUE TITLE
Redundant 3D points with different IDs in points3D.txt

### ISSUE THREAD

**Issue by meder411** [colmap/colmap#80]
I've been using the raw Colmap pointcloud data, and I'm finding that 3D point IDs do not always necessarily map to unique points. I've only noticed this phenomenon with consecutively numbers 3D point IDs, and I have yet to see anything larger than pairs of redundant points, but here's an example of two identical points from a `points3D.txt` file.

```
28871 0.46874 4.27221 6.06381 90 90 87 1.03738 122 7837 123 9491 125 8552
28872 0.46874 4.27221 6.06381 90 90 87 1.03738 122 7838 123 9492 125 8553
```

Despite being the same exact 3D point, they differ slightly in the 2D points they track to in images 123 and 125. I suspect these 3D points are treated as separate because their tracks differ, and there is a constraint that each 3D point can only track to a single 2D point per image. Nevertheless, I'd suppose that those adjacent 2D point IDs (123:9491 -- 123:9492 and 125:8552 -- 125:8553) are either the same SIFT descriptor or the same point at a different scale perhaps.

This isn't an urgent issue by any means, but it seems there ought to be a way to merge those tracks to keep 3D points uniquely identified.

**Comment by ahojnnes** [comment]
You are right with your observations. This is intended and shouldn't be a problem in practice. Thanks for reporting anyway. I will close this for now. Feel free to reopen if questions remain.
