### ISSUE TITLE
Quality information for image_registrator

### ISSUE THREAD

**Issue by jonasmeyer1** [colmap/colmap#800]
Hi, 
We use colmap to register new images into an existing reconstruction as discribed in FAQ.
Is there a possibility to get additional quality information about the image registration (e.g. reprojection error, local reliability)?

**Comment by tsattler** [comment]
The output file of the image_registrator will contain the poses of the new images, as well as which points are seen by them (as the ids of the new images are added to the track list of the existing 3D points, even though no new points are triangulated). This should allow you to compute the information you are looking for.
