### ISSUE TITLE
Point triangulator can't get points

### ISSUE THREAD

**Issue by ComputerMath** [colmap/colmap#802]
**Describe the bug**
I'm now doing a ```point_triangulated``` from known 6DOF pose.
The matching was great & I think points were quite great as bellow image
But, the all images' the number of the triangulated point has 0 points in log, so it can't do merge & retriangulation.
![image](https://user-images.githubusercontent.com/29303833/74526399-af07bd80-4f66-11ea-91ef-e2d15ad5bb12.png)

When I see the matching table, there seems to many matching images of one image (not only one).

![image](https://user-images.githubusercontent.com/29303833/74526345-88498700-4f66-11ea-961a-6c1f5b579137.png)

The Data Image has many overlapping sequential images so i think the table seems reasonable.
Is there solution by making or editting options?

Thank you in advance.

**Comment by tsattler** [comment]
Are you sure that your known poses are accurate and that the input file you create is correct (poses in the correct format, image ids in the file match those in the database, etc.)?

**Comment by ComputerMath** [comment]
Thanks for reply.
Ids seems correct and i have 3 dof of poses and unknown additional 3dof (total 6 dof).
I did all things i could do about latter 3dof by seeing it as rotational vector or euler vector  using scipy python library.

Earlier I used another small dataset using rotation matrix and although the coordination was wrong the image register was done (of course wrong reconstruction shape).
But in this dataset any coordinate and calculation have no reconstruction shape 
(0 images registered out of 8300)

Should I add or fix the dafault command options???

**Comment by tsattler** [comment]
I am not sure that I understand what you are doing. You have 3 dof of the poses, but how do you get the others? How do you ensure that the poses that you feed into the point triangulator are accurate enough to allow triangulation?

**Comment by ComputerMath** [comment]
Sorry for not enough explanation
I have 3 dof camera pose and additional 3 dof which are roll, pitch, yaw.

I saw it as euler vector So i transformed it to rotation matrix and quanterion vector using scipy library.

Maybe because of my lack of knowledge, i dont know it is camera coordinate or world coordinate. So i did experiments using both matrix which are transposed and the raw way. BUT I couldn't get any reconstructed image.

**Comment by tsattler** [comment]
I'd recommend to determine what the pose information is and in what format it is given. Without it, it becomes quite impossible to debug. I also recommend to visualize the camera poses you feed into colmap to see whether they are meaningful.

**Comment by ComputerMath** [comment]
I confirmed what I have but it didn't work though.
I have quanterion vector (4 dimension which is ordered of QW QX QY QZ, so i just type this to images.txt which will be used by point_triangulator) and 3D camera pose.

I got translation vector by Rotation matrix (from quanterion vector) and camera pose also.


![image](https://user-images.githubusercontent.com/29303833/74609949-1887f780-5132-11ea-9d53-426831cb70c6.png)

In the database, the matching seems quite great. But, the point_triangulator still cannot get any triangulated point like below image.
![image](https://user-images.githubusercontent.com/29303833/74609977-5a18a280-5132-11ea-96fc-027556a1e6d8.png)

**Comment by tsattler** [comment]
Are you sure your rotation is from world to camera coordinates, i.e., in the right direction?
Are you sure your poses are accurate enough to allow triangulation?

**Comment by ComputerMath** [comment]
I suspect that whether it is from world to camera or vice versa, so that I did both experiments for transposed rotation matrix and raw rotation matrix but couldn't do make it.

Also, I think poses seems quite accurate when I used point of X,Y from camera pose using matplot.

**Comment by ComputerMath** [comment]
When I used smaller data (this is more than 8000 images, but I used 600 images), although rotation is reversed (not from world to camera), Although the shape was wrong and # of 3D points are small, the model reconstruction by point_triangulator was done.

I didn't gave any options for both experiments but the smaller data was done but this(larger) is not made.

**Comment by ComputerMath** [comment]
Surprisingly and Strangely, When I opened DB as upper images, it does not seem to be any error.
But when i redo all of feature extraction & match, it was done even though there isn't any change of images.txt.
Thank you for care about my Problem.

**Comment by shuttworth** [comment]
I met this problem just day ago. I handle this in the case of "Reconstruct sparse/dense model from known camera poses". My pose is camera to world, not world to camera. So i just get a inverse matrix, then it's OK!

**Comment by antoinekeller** [comment]
Exact same problem here:

```
==============================================================================
Triangulating image #1 (0)
==============================================================================

  => Image sees 0 / 305 points
  => Triangulated 0 points

==============================================================================
Triangulating image #11 (1)
==============================================================================

  => Image sees 0 / 0 points
  => Triangulated 0 points

==============================================================================
Triangulating image #21 (2)
==============================================================================

  => Image sees 0 / 0 points
  => Triangulated 0 points

==============================================================================
Triangulating image #31 (3)
==============================================================================

  => Image sees 0 / 0 points
  => Triangulated 0 points

==============================================================================
Triangulating image #41 (4)
==============================================================================

  => Image sees 0 / 0 points
  => Triangulated 0 points

==============================================================================
Triangulating image #51 (5)
==============================================================================

  => Image sees 0 / 0 points
  => Triangulated 0 points

==============================================================================
Retriangulation
==============================================================================

  => Completed observations: 0
  => Merged observations: 0

==============================================================================
Bundle adjustment
==============================================================================

F20230629 16:50:38.419976 2852250 sfm.cc:482] Check failed: bundle_adjuster.Solve(&reconstruction) 
*** Check failure stack trace: ***
    @        0x1034b3304  google::LogMessage::Flush()
    @        0x1034b6c9c  google::LogMessageFatal::~LogMessageFatal()
    @        0x1034b4070  google::LogMessageFatal::~LogMessageFatal()
    @        0x102c5be10  colmap::RunPointTriangulatorImpl()
    @        0x102c5b378  colmap::RunPointTriangulator()
    @        0x102c247b0  main
```

while I do have many features and many matches across the images, and my poses are correct since there were computed by COLMAP in another context.

Any idea on how to solve this?

**Comment by HongxiZhao** [comment]
> I met this problem just day ago. I handle this in the case of "Reconstruct sparse/dense model from known camera poses". My pose is camera to world, not world to camera. So i just get a inverse matrix, then it's OK!

May I ask which matrix in the source code you are taking the inverse of? Is that the correct sentence
![Uploading image.png…]()

**Comment by HongxiZhao** [comment]
<img width="412" alt="微信图片_20240119191011" src="https://github.com/colmap/colmap/assets/113981066/3cf13d90-0d74-42c8-b744-2c4a4789ef26">
May I ask which matrix in the source code you are taking the inverse of? Is that the correct sentence of the picture?
