### ISSUE TITLE
Write Depth and Normal Maps

### ISSUE THREAD

**Issue by EugenioTL** [colmap/colmap#805]
Hi, 
I want to ask if there exists the complementary function located in path scripts/python/read_dense.py and called read_array().
The reason why I am asking for this, is because I noticed there is an header in depth maps, so it is not immediate doing something like .bin -> .jpg -> elaborate(.jpg) -> .bin.

What I am actually trying to use is something like this:

def write_array(path, dmap):
-----with open(path, "wb")  as outfile:
----------dmap = dmap.reshape((dmap.shape[0], dmap.shape[1], 1))
----------transposed = np.transpose(dmap, (1,0,2))
----------transposed = transposed.reshape((transposed.shape[0]*transposed.shape[1]), order="F")
----------transposed.tofile(path)

The problem is that, while reading back its output, width, height and channels are equal to -1 and i get the following error at this line:

line: array = array.reshape((width, height, channels), order="F")
error: ValueError: can only specify one unknown dimension

If you can help me I will be grateful.
Thanks.

**Comment by yuancaimaiyi** [comment]
@EugenioTL  Do you solve it ?

**Comment by EugenioTL** [comment]
Yes, this is the correct solution:

def write_array(array, filename):
    # add one dimension -> unsqueeze
    array_unsqueeze = np.expand_dims(array, axis=2)
    # transpose
    array_t = np.transpose(array_unsqueeze, (1, 0, 2))
    # reshape the array to a one dimension
    new_dim = np.prod(array_t.shape)
    array_reshape = array_t.reshape(np.prod(array_t.shape), order="F")
    # save file
    sh = '&'.join([str(x) for x in array_t.shape]) + '&'
    with open(f'{filename}', 'wb') as f:
        f.write(str.encode(sh))  # write array dimensions at the top file
        f.write(array_reshape)  # write array
    return array_reshape

I authorize the authors and everyone else to use this code in the case it would be useful.

**Comment by yuancaimaiyi** [comment]
@EugenioTL thanks
