### ISSUE TITLE
Sift feature size and angle

### ISSUE THREAD

**Issue by gaosanyuan** [colmap/colmap#806]
How can I get the sift feature size and angle? Thanks

**Comment by ahojnnes** [comment]
It is stored in the database in the keypoints table. Please refer to the documentation for how to read the data from the database.

**Comment by farhadinima75** [comment]
Hi @ahojnnes 
Colmap saves keypoints with the shape of [N, 6] (in Affine format) by default.

How can we change it to SIFT format ([N, 4] which axis 4 is x, y, scale, angle respectively)?
Thanks in advance.

**Comment by DubovitskyDenis** [comment]
I think @ahojnnes, you can close this issue as the answer can be found here https://github.com/colmap/colmap/issues/1295.
