### ISSUE TITLE
window-no-cuda    VS     linux

### ISSUE THREAD

**Issue by wolf943134497** [colmap/colmap#807]
Hi @ahojnnes  Thanks for your great works!

window-no-cuda  version can get dense reconstruction output? I build colmap from source code, dense reconstruction is only implemented on the GPU using CUDA.  How to implement  the dense reconstruction of window-no-cuda  version? 

Thanks!

**Comment by KhaledSharif** [comment]
As far as I know COLMAP cannot perform dense reconstruction without CUDA.

**Comment by Nosenzor** [comment]
The Dense part would be so long to run without a GPU.... IMHO a CPU only is not sustainable. If we have some volounteers we could port the CUDA part to SYCL, but it's not an easy task.

**Comment by wolf943134497** [comment]
Hi @KhaledSharif  @KhaledSharif  Thanks for yourquick reply !
