### ISSUE TITLE
about hierarchical

### ISSUE THREAD

**Issue by SkyRiderMike** [colmap/colmap#811]
I wish i can improve the reconstruction speed in large scene. And i try to use hierarchical_mapper but get an incomplete result. 

Could you give me some papers about your hierarchical implementation? I wish i can understand them well. Thanks

**Comment by SkyRiderMike** [comment]
@ahojnnes Could you share some details please?

**Comment by ahojnnes** [comment]
There is no real citation for this, but rather my own take on it. The hierarchical mapper is very experimental at the moment, because I never had time to properly test and tune it. I am sure it needs more tweaks to make it work robustly.

**Comment by ahojnnes** [comment]
There are some papers on hierarchical SFM that inspires the approach. A web search should give you a bunch of references for the topic.

**Comment by SkyRiderMike** [comment]
OK, Thanks!

**Comment by SkyRiderMike** [comment]
@ahojnnes BTW， i use it to reconstruct a large scene. but this program generate several reconstructions, and all of them can be opened by colmap. How can i merge them into one reconstruction?
