### ISSUE TITLE
How can I extract extrinsic camera parameters?

### ISSUE THREAD

**Issue by SherifShawkat** [colmap/colmap#812]
Hello, I have a set of images for a building for example, I use Automatic reconstruction, after it finishes, I want to extract the extrinsic camera parameters but I can't find it. Where can I find it please?

**Comment by ahojnnes** [comment]
It's in the images.bin/.txt, please see documentation for details on the output format.

**Comment by SherifShawkat** [comment]
File --> Export model as text
