### ISSUE TITLE
what is the self-calibration algorithm of colmap

### ISSUE THREAD

**Issue by YRstronger** [colmap/colmap#813]
Hi, I noted that colmap can autocalibrate the intrinics of camera including focal length, and radial distortion. What is the algorithm? could you give me reference for the detail of those?

**Comment by SkyRiderMike** [comment]
Ｗow, such a good question but there is still no answer.. I wonder to know also. See the code from EstimateAbsolutePose function for more details.

**Comment by YRstronger** [comment]
Oh, Thanks for reminding me this function. I take a look at those lines of code. 

In this function, the author has used a method called p3pf solver. I have read some part of code of that, which could be found in GitHub( Sorry I forget where I read those).
The name of paper is "On Sampling Focal Length Values to Solve the Absolute Pose Problem".

It almost seems like the answer to my previous question. If I get some chances to look carefully through the code of Colmap, I will try to find whether it is the only "auto-calibra" method used or others exist.

**Comment by SkyRiderMike** [comment]
Thanks for the paper! We can discuss more if we meet this kind of problem
