### ISSUE TITLE
[Can't find database_create.cc in /src/exe/...]how to create a new database with command-line Interface?

### ISSUE THREAD

**Issue by ckLibra** [colmap/colmap#815]
just as topic says.I build the project successfully on Ubuntu 18.04,but i can't run the colmap command-line.It says can't find database.So how can i init the new project from command-line,since i can't find the database_create.cc in /src/exe/database_create.cc where document says.

**Comment by tsattler** [comment]
Did you read this: https://colmap.github.io/cli.html ?

**Comment by ckLibra** [comment]
> Did you read this: https://colmap.github.io/cli.html ?

Thanks for replying.I have read it and I tried the automatic reconstruction command,but it failed because of the lack of database.I want to know how to create database?btw,I also tried the database_creator command .

**Comment by tsattler** [comment]
Did `colmap database_creator` work? Why does the automatic reconstruction command fail?

**Comment by ckLibra** [comment]
> Did `colmap database_creator` work? Why does the automatic reconstruction command fail?

sorry,I made a stupid mistake.It's about the writing permission.I add sudo and it solves.Thanks for your patience.
