### ISSUE TITLE
Some Question about PBA

### ISSUE THREAD

**Issue by SkyRiderMike** [colmap/colmap#816]
I noticed that there is also an GPU BA implementation(Parallel Bundle Adjustment， PBA) instead of ceres which is only CPU implementation. 

Will the PBA be definitely faster than ceres under large scenes ? I know it doesn't support camera sharing, but still curious to know that.

And, as far as i know, in order to keep consistency, there must be at least two poses fixed when running bundle adjustment. I found the code for setting poses constant when calling ceres-solver . However, i can't find the corresponding code for fixing poses when running Parallel Bunde Adjustment. 

Could you tell me how it can solve the BA when there is no pose to set constant ? 

Sincerely  THanks.

**Comment by SkyRiderMike** [comment]
@ahojnnes can you give me some insight about how the pba solves a bundle adjust without fixing any pose ? I can't find the any code about fixing poses under the pba code. https://github.com/cbalint13/pba

**Comment by ahojnnes** [comment]
Fixing the poses is only used as a hack to make sure the model doesn't arbitrarily rotate in the viewer. Otherwise, you can also let the gauge be unconstrained. If you want to know more, please read up on the term "gauge freedom" in bundle adjustment.

**Comment by SkyRiderMike** [comment]
Thanks. I will read them
