### ISSUE TITLE
Building Colmap dc2a6012049d6b23b70d3b8d4bda8c9cbbf23b83 using Ubuntu 14.04

### ISSUE THREAD

**Issue by SBCV** [colmap/colmap#82]
Hi Johannes,

I am not able to build the latest Colmap version (dc2a6012049d6b23b70d3b8d4bda8c9cbbf23b83). Make fails to compile "coordinate_frame.cc.o". The error message is contained in the attached file. However, I can build a commit from the previous day (effdf7bd477f134456474875966ae9e4e5289f7a). 

[error message.txt](https://github.com/colmap/colmap/files/796422/error.message.txt)

Regards,
Sebastian

**Comment by ahojnnes** [comment]
Which Eigen version and system are you on?

**Comment by ahojnnes** [comment]
You could try to add a `#include <Eigen/Geometry>` to the top of the `coordinate_frame.cc` file and let me know whether that fixes the problem. Thanks.

**Comment by SBCV** [comment]
Unfortunately, adding "#include <Eigen/Geometry>" does not fix the issue. 
My Eigen version is 3.2.0. Which one are you using?

**Comment by ahojnnes** [comment]
Seems like older Eigen versions have problems with some of the expressions. Can you try the latest commit on master?

**Comment by SBCV** [comment]
This has fixed the issue - nice! Thank you!
