### ISSUE TITLE
Best way to add images and feature matches sequentially

### ISSUE THREAD

**Issue by tudipffmgt** [colmap/colmap#826]
I have 34 different images from a internet collection. Matches are very hard to find but COLMAP 3.5 manages to create a (correct) sparse model using 18 of the 34 images. At the moment I am mainly working in the GUI. 
I am working on special feature matchers appropriate for these kind of images so I am able to get matches for 10 more images. My methods take a very long time so at the moment I do not want to run them on every possible image pair combination. That is why I am using COLMAP for a initial reconstruction.

How can I integrate 10 more images with their calculated feature matches into the existing model?
Can I use the GUI for this? Is it useful to directly rename the images to 1.jpg 2.jpg ... and write my feature matches as standard SIFT matches like proposed in the FAQ?

**Comment by tsattler** [comment]
You can use the `mapper` functionality from the command line to continue an existing reconstruction with images not yet in the model (using the `--input_path` option). However, all images (the ones already in the model and the ones that should be added) need to be all in a single database that also needs to contain the feature matches that should be used to continue the reconstruction. Also, the existing model has to be build using the same database.

**Comment by tudipffmgt** [comment]
Sorry, for the late reply. I understand how to save the database and export the reconstruction. Then I could use to mapper functionality like explained in the FAQ:
`       colmap mapper \    
    --database_path $PROJECT_PATH/database.db \     
    --image_path $PROJECT_PATH/images \     
    --input_path /path/to/existing-model \     
    --output_path /path/to/model-with-new-images`
But how would I add my feature matches to the database? Could you give me an example?

**Comment by tsattler** [comment]
You can use existing functionality. There is an explanation of the format here: https://colmap.github.io/tutorial.html#feature-matching-and-geometric-verification and the `feature_importer` can do this operation from the command line.

**Comment by tudipffmgt** [comment]
Ah nice, I wasn't aware of the `feature_importer`! So I don't need to work with the python scripts (I am not a programmer ;)). If I am having further problems after importing I would open a new issue but for now I am satisfied :D. Thanks for helping!

**Comment by alexs7** [comment]
@tsattler Can colmap manage other descs other than SIFT ? For example when using `feature_importer` the desc have to be SIFT or can we use any descriptor-size ?

**Comment by tsattler** [comment]
@alexs7 I guess it should be possible to use other descriptors if they have 128 dimensions, have unit norm, and can be quantized similar to SIFT descriptors. @ahojnnes should know better than me.
The alternative is to do matching outside of colmap and then import dummy features and the matches. You can have a look here: https://github.com/tsattler/visuallocalizationbenchmark/tree/master/local_feature_evaluation

**Comment by tudipffmgt** [comment]
> @alexs7 I guess it should be possible to use other descriptors if they have 128 dimensions, have unit norm, and can be quantized similar to SIFT descriptors. @ahojnnes should know better than me.
> The alternative is to do matching outside of colmap and then import dummy features and the matches. You can have a look here: https://github.com/tsattler/visuallocalizationbenchmark/tree/master/local_feature_evaluation

I used the local_feature_evaluation for my purpose and it worked. Best regards

**Comment by alexs7** [comment]
@tsattler Just wondering about the pairs here: [https://github.com/tsattler/visuallocalizationbenchmark/blob/master/local_feature_evaluation/modify_database_with_custom_features_and_matches.py](https://github.com/tsattler/visuallocalizationbenchmark/blob/master/local_feature_evaluation/modify_database_with_custom_features_and_matches.py)

The `match_features(images, paths, args)` requires a pairs file. If I only have N images, and nothing else, I have to define the pairs myself ? In what format the pairs files does it come ?

**Comment by tsattler** [comment]
Yes, you will have to create the pairs file yourself. Matching each image against each other image is an option, or you could use image retrieval to find pairs of similar images.
