### ISSUE TITLE
 point cloud has serious front and back ghosting

### ISSUE THREAD

**Issue by yuancaimaiyi** [colmap/colmap#827]
@ahojnnes @tsattler hello ,sorry to bother you .
I meet some problem,that is :+1: 
I  3D reconstruction from the known poses ,my pose's position is obtained by RTK（The position of the optical center of the camera is based on the external parameters of GPS and the camera）,my pose's rotation is obtained by vslam .
 the data is a positive and negative road, but the final dense point cloud has serious front and back ghosting, , there is almost no ghosting left and right, about 70cm of front and back ghosting, so I separate the forward and reverse directions to generate point clouds, where the error between the forward direction and the ground truth is within 30cm, and the error between the reverse direction and the ground truth is greater than 40cm. What is the cause of this kind of front and back ghosting? Is that the pose's position or pitch angle?
thanks

**Comment by tsattler** [comment]
@yuancaimaiyi Can you show screenshots of the problem here? It is hard to give you advice without having a look at the problem.

**Comment by yuancaimaiyi** [comment]
@tsattler 
![企业微信截图_15840662788865](https://user-images.githubusercontent.com/28293910/76585413-45ed7880-6519-11ea-81c9-334dff728a7d.png)

**Comment by tsattler** [comment]
Are all these artifacts on the road surface? Could there be drift between the two trajectories?

**Comment by yuancaimaiyi** [comment]
@tsattler tthanks for your reply.Because my position is by RTK（3D reconstruction from the known poses），So there's no drift

**Comment by tsattler** [comment]
I don't think that RTK guarantees that it is 100% accurate. Looking at the screenshot you shared, the easiest explanation would be that there is some small shift between the forward and backward trajectories.

**Comment by yuancaimaiyi** [comment]
@tsattler Thank you very much. camera center loaction is by orb-slam fusion rtk's position.
I think the reason for this is either the wrong position or the pitching angle. But I saw the height change of this section of road. The difference between the maximum height and the minimum height is 10cm,so the pitching angle will not cause  big shift between the forward and backward . I will check the pitching angle again
I will share any progress in time
 thanks !
