### ISSUE TITLE
image_undistorter.exe crash on windows (precompiled colmap 2.1 with CUDA)

### ISSUE THREAD

**Issue by albjoao** [colmap/colmap#83]
I am having same issue as this [user](https://github.com/colmap/colmap/issues/50). I commented in that thread, but think it will be better to open a new issue for visibility. 

I've been having the same problem as the other user, however, I believe that I have chosen model "0". Inside this directory I have 3 files, cameras.txt, images.txt, and points3D.txt

the following is the command line script I am using:

`d:\ColMAp_2.1_CUDA\bin\feature_extractor.exe --General.database_path d:\ColMAp_2.1_CUDA\test.db --General.image_path d:\ColMAp_2.1_CUDA\run\images d:\ColMAp_2.1_CUDA\bin\exhaustive_matcher --General.database_path d:\ColMAp_2.1_CUDA\test.db --ExhaustiveMatchOptions.block_size 10 mkdir d:\ColMAp_2.1_CUDA\run\sparse d:\ColMAp_2.1_CUDA\bin\mapper.exe --General.database_path d:\ColMAp_2.1_CUDA\test.db --General.image_path d:\ColMAp_2.1_CUDA\run\images --export_path d:\ColMAp_2.1_CUDA\run\sparse mkdir d:\ColMAp_2.1_CUDA\run\dense d:\ColMAp_2.1_CUDA\bin\image_undistorter.exe --General.image_path d:\ColMAp_2.1_CUDA\run\images --input_path d:\ColMAp_2.1_CUDA\bin\run\sparse\0 --output_path d:\ColMAp_2.1_CUDA\run\dense --output_type COLMAP --max_image_size 2000 PAUSE`

**Comment by ahojnnes** [comment]
Can you please post the complete output of the image_undistorter?

**Comment by albjoao** [comment]
After running it, I get the following error:
`F0224 09:02:47.385334 13216 reconstruction.cc:1593] Check failed: file.is_open()
*** Check failure stack trace: ***`

Visual Studio then gives me 
`Unhandled exception at 0x00007FFEA2584A30 (msvcr120.dll) in image_undistorter.exe: Fatal program exit requested. `

**Comment by ahojnnes** [comment]
Then, there is no cameras.txt in the --input_path that you provided.

**Comment by albjoao** [comment]
Thank you! I've found the mistake.
