### ISSUE TITLE
Why does the descriptors table row have more values than max_num_features ?

### ISSUE THREAD

**Issue by alexs7** [colmap/colmap#831]
The _descriptors table_ row column should show the number of descriptors for each keypoint detected in an image? If I set `max_num_features`  to 550, then I get more than 550 in that column. 

If it is set to 550 then 550 keypoints at max should be detected in an image and that would give a maximum of 550 descriptors?

**Comment by tsattler** [comment]
The way the SIFT feature extractor is extracted, it uses `max_num_features` as an indicator for the desired number of features. However, it can return slightly more features (as to avoid discarding a complete scale). As such, there can be more than 550 descriptors if `max_num_features` is set to 550.

**Comment by alexs7** [comment]
@tsattler Ok thanks!
