### ISSUE TITLE
What is the max_image_size exactly ?

### ISSUE THREAD

**Issue by alexs7** [colmap/colmap#833]
In my case it is set to 3200. But what does it stand for ?

**Comment by ahojnnes** [comment]
It means the image will be down scaled such that neither width or height exceed 3200 pixels.

**Comment by alexs7** [comment]
Ok thank!

**Comment by Todd-Qi** [comment]
Hello, @ahojnnes 
My images are in the resolution of 1440×1080, and the `max_image_size` is set to 2000.
But after the `image_undistorter`, the image resolution has been changed. Such as 1426×1069, 1435×1076 and others.
In my experiment, I want to keep the resolution **fixed**. Is there any cmd to keep the image resolution?

Many Thanks!!!
Looking forward to your reply.

**Comment by Todd-Qi** [comment]
I got it!
https://github.com/colmap/colmap/issues/390#issuecomment-401177607
