### ISSUE TITLE
What exactly are point2D_idxs and image_ids for 3D points data ?

### ISSUE THREAD

**Issue by alexs7** [colmap/colmap#835]
I am using the scripts to read the point3D.bin

Now for a sample point I get this:

`Point3D(id=10159, xyz=array([-4.24454832,  4.27783529,  7.79460184]), rgb=array([239, 225, 198]), error=array(3.15012219), image_ids=array([6, 7, 2, 1, 4, 2, 7, 1]), point2D_idxs=array([813, 818, 762, 801, 901, 759, 758, 678]))`

So I get the image_ids, and fetch the descriptors for that image from the database. 
Now the descriptors _rows_ column indicates the number of descriptors for that image.
So if the value is 900 that means that there are 900 descriptors for that image.

In my case this is how I interpret this data. So I take from the _image_ids_ array value 6. 
Then I get the data from the descriptors table that corresponds to _image_id = 6_.

Then from _point2D_idxs_ I get 813 that corresponds to _image_id = 6_ right ?
that 813 is a zero-based index for the descriptor for that point from that image right ?

My problem is that the descriptors for that image are less than 813... and I get an error:

`IndexError: index 813 is out of bounds for axis 0 with size 780`

So is this a bug ?

I have used the tips from here: https://colmap.github.io/faq.html#increase-number-of-matches-sparse-3d-points

I am not sure if that affects it.

**Comment by tsattler** [comment]
You can find a definition here: https://colmap.github.io/format.html 

Are you sure you are accessing the image with image_id 6 rather than the 6th image added to the reconstruction?

**Comment by alexs7** [comment]
@tsattler It seems that my code was using all of `point2D_idxs` instead of `point2D_idxs[i]` where `i` is the `image_id` to get the descriptor from that image for that point.. fixed now! thanks for your reply!
