### ISSUE TITLE
Core Dump during sparse reconstruction

### ISSUE THREAD

**Issue by jzubizarreta** [colmap/colmap#839]
I am executing a basic SfM pipeline with around 480 images. Feature extraction and matching are successfully executed. However, when I start the reconstruction part, I get a core dump from cholmod with around 50 used images. Currently I am using Suitesparse 5.4 from https://github.com/jlblancoc/suitesparse-metis-for-windows and the colmap-gui option. Any idea of what could be happening? Here is the output log:

> CHOLMOD version 3.0.13, Dec 20, 2018: Symbolic Analysis: status: OK
>   Architecture: Linux
>     sizeof(int):      4
>     sizeof(SuiteSparse_long):  8
>     sizeof(void *):   8
>     sizeof(double):   8
>     sizeof(Int):      4 (CHOLMOD's basic integer)
>     sizeof(BLAS_INT): 4 (integer used in the BLAS)
>   Results from most recent analysis:
>     Cholesky flop count: 1,0792e+06
>     Nonzeros in L:       16917
>   memory blocks in use:          11
>   memory in use (MB):           0,0
>   peak memory usage (MB):       0,1
>   maxrank:    update/downdate rank:   8
>   supernodal control: 1 40 (supernodal if flops/lnz >= 40)
>   nmethods:   number of ordering methods to try: 1
>     method 0: natural
>         flop count: 1,0792e+06
>         nnz(L):     16917
>   OK
> ** On entry to DPOTRF, parameter number  4 had an illegal value
> *** Aborted at 1586353158 (unix time) try "date -d @1586353158" if you are using GNU date ***
> PC: @     0x7fe24c91b3ff cholmod_free_dense
> *** SIGSEGV (@0x7fe20000002f) received by PID 14879 (TID 0x7fe1feffd700) from PID 47; stack trace: ***
>     @     0x7fe24ce5b890 (unknown)
>     @     0x7fe24c91b3ff cholmod_free_dense
>     @     0x7fe24c9a1d91 cholmod_super_numeric
>     @     0x7fe24c921b3c cholmod_factorize_p
>     @     0x7fe24c92217e cholmod_factorize
>     @     0x561cc4e08e99 ceres::internal::SuiteSparse::Cholesky()
>     @     0x561cc4e0984d ceres::internal::SuiteSparseCholesky::Factorize()
>     @     0x561cc4e071f5 ceres::internal::SparseCholesky::FactorAndSolve()
>     @     0x561cc4dff239 ceres::internal::SparseSchurComplementSolver::SolveReducedLinearSystem()
>     @     0x561cc4dfdab7 ceres::internal::SchurComplementSolver::SolveImpl()
>     @     0x561cc4ddf545 ceres::internal::TypedLinearSolver<>::Solve()
>     @     0x561cc4dc9fea ceres::internal::LevenbergMarquardtStrategy::ComputeStep()
>     @     0x561cc4da3585 ceres::internal::TrustRegionMinimizer::ComputeTrustRegionStep()
>     @     0x561cc4da7ed5 ceres::internal::TrustRegionMinimizer::Minimize()
>     @     0x561cc4d78666 ceres::Solver::Solve()
>     @     0x561cc4d79219 ceres::Solve()
>     @     0x561cc4369fd1 colmap::BundleAdjuster::Solve()
>     @     0x561cc43f53c3 colmap::IncrementalMapper::AdjustGlobalBundle()
>     @     0x561cc42fa5c5 colmap::(anonymous namespace)::AdjustGlobalBundle()
>     @     0x561cc42fa9cf colmap::(anonymous namespace)::IterativeGlobalRefinement()
>     @     0x561cc42fb40b colmap::IncrementalMapperController::Reconstruct()
>     @     0x561cc42fcefb colmap::IncrementalMapperController::Run()
>     @     0x561cc446662c colmap::Thread::RunFunc()
>     @     0x7fe24b22d6df (unknown)
>     @     0x7fe24ce506db start_thread
>     @     0x7fe24a6bb88f clone
> Segmentation fault (core dumped)

Thanks in advance :)

**Comment by DongDongXA** [comment]
I didn't try to compile and run this project, but it seems that the problem
 "On entry to DPOTRF, parameter number 4 had an illegal value" 
happened within a piece of lapacke code. Have u ever tried to compile this project not by the self-compiled suitesparse  but by the pre-compiled package offered by official ubuntu source, suitesparse is so unstable when u try to compile all by urself. 

If official ubuntu's source didn't work, I recommends u switch to another computer to compile this project.

**Comment by jzubizarreta** [comment]
Thanks! The issue was from lapack. Recompiling it solved the problem.
