### ISSUE TITLE
Work with KITTI Mono Sequence

### ISSUE THREAD

**Issue by qiaochudev** [colmap/colmap#84]
Hi @ahojnnes 

I try to perform the 3D reconstruction on the image dataset captured by single car-mounted camera with the GPS location using COLMAP. I used KITTI  dataset as a test, however the results are very unstable and the PMVS results even sparse than the COLMAP SfM outputs. Do you have any suggestion for parameters setting in this sequential case, e.g. sequential matching or spatial matching, do we need key_frame selection, ... , for a robust results? I also see a close loop option, how can I use it?

Thank you very much!

Regards

**Comment by ahojnnes** [comment]
You should share the intrinsics between all cameras (possible in feature extraction, see https://colmap.github.io/faq.html#share-intrinsics). You should use sequential matching and you should increase the overlap for a better reconstruction. In addition, you should enable the loop detection checkbox. You can download vocabulary trees from here http://people.inf.ethz.ch/jschoenb/colmap/

**Comment by qiaochudev** [comment]
Cool, Thanks for you quick reply. Will try your suggestion later. Another question, If for each image, I have the corresponding camera location write in metadata, is this helpful for a robust reconstruction? I mean if the COLMAP use camera location as a constraint during the bundle adjustment?

Thanks again.

Regards

**Comment by ahojnnes** [comment]
Currently, COLMAP does not support to enforce location constraints in bundle adjustment, but this should be easy to add in by yourself. At the moment, you can only use the location constraints for faster matching using the "Spatial Matching" feature.

**Comment by franex** [comment]
Does the Spatial_matching support latitude and longitude instead of East and North coordinates? If not, is it possible to set a very little threshold, equivalent (in degrees) to 100 m (default value)?
Thank you in advance for your answer!

**Comment by ahojnnes** [comment]
This option is named confusingly, but just set ``--SpatialMatching.is_gps 1``.

**Comment by franex** [comment]
ok, I checked it seems that it reads my latittude and longitude in degrees and convert them in meters. 
Thanks
