### ISSUE TITLE
Is there a way to get the scale from 2 different COLMAP reconstructions of the same place ?

### ISSUE THREAD

**Issue by alexs7** [colmap/colmap#841]
I have reconstructed 2 models of the same scene. Same `project.ini ` used to generate them and obviously different images. Is there a way to take the 2 point clouds and align them ? I have tried ICP in matlab but I think that does not take care of scale, so the result does not look great.

**Comment by tsattler** [comment]
Do your two models share some images or are the two sets of images completely disjoint.

**Comment by alexs7** [comment]
@tsattler The set of images are completely disjoint as they were taken at different times. I could try and localise from one dataset to another and vice versa. I think COLMAP can still localise given some changes in the scene. If I do will that help ? I could get the scale at least ?

**Comment by tsattler** [comment]
If you have common images in both models, you can use the model_aligner or model_merger to compute an alignment.

**Comment by alexs7** [comment]
@tsattler Perfect it worked great! Thanks

**Comment by alexs7** [comment]
@tsattler is there an easy way to extract that transformation ? Or do I have two take the common camera centers from model 1 or model 2, and the camera centers from the resulting aligned model and run something like Procrustes Analysis ?

**Comment by tsattler** [comment]
The model_aligner will take care of the alignment if you provide it with a list of reference poses. It should ignore images in that list that are not in the reconstruction.

**Comment by alexs7** [comment]
Yes makes sense. That transformation is a rotation and translation (and scale I assume). I got the aligner working, but for my case I need the `[R | t]` (and scale) that is used to align model1 to model2. I guess at this point I will have to look in the code for that ?

The output of the aligner is usually something like this:

> Aligning reconstruction
> -----------------------
>  => Using 7 reference images
>  => Alignment succeeded
>  => Alignment error: 0.117336 (mean), 0.099764 (median)

**Comment by tsattler** [comment]
Yes, you will have to look at the code and modify it to return the transformation.

**Comment by alexs7** [comment]
@tsattler ok thanks!
