### ISSUE TITLE
How to get camera pose information from UI?

### ISSUE THREAD

**Issue by antithing** [colmap/colmap#843]
Hi, I am using the binaries to test my own images, the result looks good, but I would like to view the camera poses translation / rotation.

In the database management window, the values for tx, ty, tz, qx etc are all nan. But the viewport cameras look correct. How can I see the pose information?

Thanks!

**Comment by tsattler** [comment]
The database is not updated with the computed camera poses. You can double click on the images in the 3D model viewer to see the camera parameters, including the pose. Otherwise, you can export the computed model and read the poses from it.

**Comment by antithing** [comment]
Thank you!
