### ISSUE TITLE
Small error in export to bundler python script

### ISSUE THREAD

**Issue by tsattler** [colmap/colmap#85]
Hi,

there seems to be a small bug in exporting the features to the keypoint file format used by bundler. Currently, each keypoint is exported as x, y, scale, orientation (see https://github.com/colmap/colmap/blob/master/scripts/python/export_to_bundler.py#L97), but Bundler uses y, x, scale, orientation .

Best,
Torsten

**Comment by ahojnnes** [comment]
Fixed in https://github.com/colmap/colmap/commit/e7f3a9f4c356b2ac58724d5f38ed546a735ded58
