### ISSUE TITLE
How to project the sparse 3D points to pixel coordinate?

### ISSUE THREAD

**Issue by Todd-Qi** [colmap/colmap#850]

**Comment by tsattler** [comment]
You can have a look at the projection functions of the different camera models here: https://github.com/colmap/colmap/blob/master/src/base/camera_models.h

**Comment by Todd-Qi** [comment]
Thanks for your prompt reply.

**Comment by Todd-Qi** [comment]
Could you tell me how to run the `EXAMPLE_test.cc`, such as `camera_models_test.cc`?
I haven't found the code entrance yet.

**Comment by tsattler** [comment]
I think you need to pass a flag to compile the tests, but I am not sure. You can have a look at the CMake files that are responsible for building the test.

**Comment by Todd-Qi** [comment]
Thank you. I'll have a try.

**Comment by Todd-Qi** [comment]
Hello @tsattler 
I want to project the sparse model to the 2D pixel cooridinate. But now I feel confused.
Why the pixel coordinate of keypoints is not in the format of interger, in file `images.txt` ?

Looking forward to your reply.
Best Regard.

**Comment by tsattler** [comment]
SIFT features are detected with sub-pixel precision.

**Comment by Todd-Qi** [comment]
The following is my pipeline.
1. For each image in `images.txt` file, get all the visible keypoints, i.e. remove the keypoints whose `POINT3D_ID` is `-1`.
2. Get the corresponding 3D points of the visible keypoints from `points3D.txt` file, named `XYZ_world` 
3. Transform the `XYZ_world` from world to the camera coordinate system by using this formulation: `XYZ_cam = R * XYZ_world + t`. Then the third part of `XYZ_cam` is what we need, i.e. the `depth`.

But I wonder the `depth` value is just a relative value, or the real metrics(e.g. meter or centimeter)

**Comment by tsattler** [comment]
Without any additional information, i.e., known absolute distances in a scene, it is not possible to recover the scale of a scene from RGB images alone. As such, distances in the reconstruction do not have a physical meaning, i.e., one unit corresponds to some arbitrary distance.

**Comment by Todd-Qi** [comment]
I think, if the camera intrinsics are known, we can get the absolute distance.

**Comment by tsattler** [comment]
No, you cannot. You can prove that scaling the scene (i.e., the 3D point positions and camera positions) has no impact on the reprojection error, which is what is optimized in Structure-from-Motion.

**Comment by rebecca0011** [comment]
Have you sovel this problem? I met a same question.

**Comment by XYZ-qiyh** [comment]
> > > Have you sovel this problem? I met a same question.
> > 
> > 
> > Hello, @rebecca0011 you can refer to the code in this repo https://github.com/XYZ-qiyh/colmap_sparse_recon
> 
> Hi, I'd like to project the reconstructed 3D model on the 2D image plane to see if they actually correspond or not. Is this achievable using your repository?

Hello, @eyildiz-ugoe 
sparse model or dense model? [This repo](https://github.com/XYZ-qiyh/colmap_sparse_recon) is suitable for the sparse model.

As for the dense model, the processing pipeline is the same. But you should get the visibility information, which 3D point is visible for the specific view.

**Comment by theAdityaRamesh** [comment]
> You can have a look at the projection functions of the different camera models here: https://github.com/colmap/colmap/blob/master/src/base/camera_models.h

This link is dead, @tsattler can you update the link? Thanks!

**Comment by tsattler** [comment]
https://github.com/colmap/colmap/blob/main/src/colmap/sensor/models.h
