### ISSUE TITLE
Same point 3D viewed by the same image multiple times ?

### ISSUE THREAD

**Issue by alexs7** [colmap/colmap#854]
I am trying to get the 3D points that an image looks at but `image_ids` array of a 3D point can look like this in my model:

```
[122 124 123 125 128  16 129 126 127 130  16 128 129 126 127 130  29  16
 123  15 129  27  27  29  13  13  25  24  62  62  54  56  51  51  51  61
  61  14  14   2   2  18  50  50  19  48   1   1   1  20  20  44  44  45
  45  53  30  49  49  63  63  22  22  46  23  47  21  43  43  41  42  42
  65  38 121  28]
```

So why is image 1  for example repeated 3 times ? that means that this point is viewed 3 times from the same image ? This doesn't make sense...

**Comment by tsattler** [comment]
Please have a look here: #832

**Comment by alexs7** [comment]
ok thanks!
