### ISSUE TITLE
Feature Matching does not work

### ISSUE THREAD

**Issue by AminSarafraz** [colmap/colmap#86]
In my first experiment with Colmap, I'm able to extract features. However, the feature matching does not work at all. It does not give any error but it does not find any matches either. The images are sequential and I have used both Sequential and Exhaustive feature matching. I followed the instruction in the tutorial video. Is there any way that I could see a more detailed log than the one shown on the right hand side of the GUI? Thanks!

**Comment by donlk** [comment]
I second this, the app hangs when invoking Feature Matching on both Linux and Windows.

**Comment by ahojnnes** [comment]
Could you share a small subset of three of your images with me?

**Comment by HUSTyanchao** [comment]
I also experimented on both Linux and Windows. It works fine on Linux. However, the feature matching does not work on my Windows 10 64-bit machine.

**Comment by HUSTyanchao** [comment]
I rebuild the source code on Linux with the latest code. It does not work anymore on neither Linux or Windows.

**Comment by AminSarafraz** [comment]
@ahojnnes It probably does not work on any sets of images, but if you need my images, I might be able to share a few with you, what is the best way to share them with you?

**Comment by ahojnnes** [comment]
I confirmed that this should be fixed now. Please download the latest source code and/or "unstable" Windows binaries on the website.

**Comment by HUSTyanchao** [comment]
Thanks a lot, it works now.
