### ISSUE TITLE
Is any way to restrict the feature matching among epipolar line?

### ISSUE THREAD

**Issue by yangfengt123** [colmap/colmap#860]
Hi, 

The colmap is amazing. I am working on a multi-view stereo problem, but the known pose is not very accurate. I found there are a tutorial and a few issues about reconstruction from the known pose. But the result I got is not ideal. 

I am thinking it may be helpful to restrict the feature matching among the epipolar line, just like something that PMVS did, and then refine the pose from there.  May I ask if there is any available API to restrict the feature matching, or if not, any suggestions for me to implement that? 

Thank you in advance.

**Comment by tsattler** [comment]
SiftGPU, which is used by Colmap for matching, implements epipolar-guided matching. You could have a look at that.

**Comment by yangfengt123** [comment]
Thank you. I will take a look at that.
