### ISSUE TITLE
Fusion stuck at image 1 since an hour

### ISSUE THREAD

**Issue by Florenzius** [colmap/colmap#863]
Is it normal that the fusion of my source files is stuck at the first image? It's been like that for an hour.
![image](https://user-images.githubusercontent.com/12108718/81325588-e040e700-9098-11ea-8b04-bb47fb096c20.png)
Thanks in advance

**Comment by ClaudioCimarelli** [comment]
Hi @Florenzius, did you solved the issue or understood the reason behind this? I am encountering the same problem and would like to understand how to deal with it. 
I found in another issue #425 that this could be improved with ``--StereoFusion.check_num_images`` option but it does not seem to work much. Also, on a different dataset, I managed to get the fusion run smoothly and complete in less than an hour without a particular tuning. Could you provide a little help maybe @ahojnnes?

Always many thanks for your work.
