### ISSUE TITLE
sparse reconstruction show is not normal when i use amd r5 3500u , but in nvida is normal 

### ISSUE THREAD

**Issue by pdycp3** [colmap/colmap#865]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tsattler** [comment]
The description that you provide is not detailed enough to determine what the problem is. Please be more precise. Ideally, show the two reconstructions.

**Comment by pdycp3** [comment]
thanks for your comment, I use south building dataset, doing reconstruction in colmap, the sparse model look like a wrong model, i convert this model into .ply format, check it in other software,and it look like a right model ,i don't know why

**Comment by tsattler** [comment]
This is still not sufficient information to determine what might be the problem. Can you describe how the model looks wrong? Or even better, post a screenshot here?

**Comment by pdycp3** [comment]
![image](https://user-images.githubusercontent.com/45677507/81407241-a1309580-916d-11ea-8d1e-b2b13d54d114.png)

**Comment by pdycp3** [comment]
![image](https://user-images.githubusercontent.com/45677507/81407502-17cd9300-916e-11ea-8bc2-b0c7fd08a1fe.png)
ply in other software

**Comment by tsattler** [comment]
If you are loading a model in the text format, please have a look at this issue: #766

**Comment by pdycp3** [comment]
![image](https://user-images.githubusercontent.com/45677507/81407836-a7734180-916e-11ea-9bc6-c659e35e6b3d.png)
thanks for your help,this is my gpu information ,I don't know wether  it can help you locate the problem

**Comment by schizz99** [comment]
I have the same problem and it appears to be the same as the unresolved issue #218. Only seems to happen with AMD cards, and does occur with updated drivers. The corrupted rendering occurs during any reconstruction, including original reconstruction and when opening existing reconstructions.
