### ISSUE TITLE
How do I train the vocabulary tree and use it in colmap

### ISSUE THREAD

**Issue by pdycp3** [colmap/colmap#866]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tsattler** [comment]
You can train a vocabulary with the `vocab_tree_builder` and use it with the `vocab_tree_matcher`, both are available from the command line (see https://colmap.github.io/cli.html#commands).

**Comment by tsattler** [comment]
@ahojnnes I think this issue can be closed.

**Comment by ahojnnes** [comment]
Thanks @tsattler !
