### ISSUE TITLE
Use other feature extraction algorithm like deep learning based methods(superpoint\D2-net)

### ISSUE THREAD

**Issue by zxp771** [colmap/colmap#871]
Thanks for your sharing.
I wondering that if I can use the feature extraction result(from different algorithms not only the SIFT you provide)to do the reconstruction. 
I noticed that the SIFT's results have been stored in the db file but I couldn't find any interface in the "extraction.cc" to store the result and I couldn't find the data format of the results.
Could you give me some suggestion to add our feature extraction results into your reconstruction work.

**Comment by tsattler** [comment]
Here is some code and information on how to import features and matches: https://github.com/tsattler/visuallocalizationbenchmark

Note that the matching is done externally here as Colmap's matching pipeline is specialized to 128D SIFT descriptors.

**Comment by zxp771** [comment]
@tsattler Thanks for your suggestion.

**Comment by HarshilNaikk** [comment]
@tsattler how do I generate the match_list file required for the d2-net features? I read in another issue that the person was using the SIFT feature extractor in COLMAP itself to do this. I couldnt find this in the current implementation. 
Would love some help on this. 

Thanks again!

**Comment by tsattler** [comment]
The list encodes which pairs of images likely have overlap. You can generate it, for example, using image retrieval.
