### ISSUE TITLE
A way to apply SfM from frames belonging to Multi-camera with shared FoV?

### ISSUE THREAD

**Issue by Sentient07** [colmap/colmap#875]
Hi,

I am trying to understand whether it is possible to run SfM for a scene involving moving targets, but static multi-view cameras. (Initial pose of the camera wouldn't change with time). I don't plan to use it for real-time but as a post-processing step. How can I pass multiple-images(frames) from the same camera, which are temporally aligned? (in other words, a video stream from multiple cameras).

Furthermore, once the a) Focal length of the camera, b) Relative poses of the cameras are obtained, I would like to use this information to sequentially compute features, reconstruct them with new targets in the frame, and obtain depth maps. Is there a stand-alone script to perform this? 

Thank you in advance for your time and response.

Regards,

**Comment by tsattler** [comment]
Structure-from-Motion systems such as Colmap assume that the scene is static and use this to track the motion of the camera(s). They will be able to produce a 3D model in the case that the scene moves rigidly and the cameras are fixed as this case is indistinguishable from having moving cameras in a static scene. The resulting 3D model will thus have cameras at different positions. Of course, there are degenerate cases (just as in the case where the scene is static).

If you have multiple images taken by different cameras at exactly the same time, you should be able to reconstruct the scene at this point in time, no matter whether the scene changes rigidly or non-rigidly over time. Of course, this requires enough visual overlap between the cameras to enable feature matching and pose estimation.
If the scene moves non-rigidly between the frames, you will most likely get a non-consistent reconstruction.

**Comment by Sentient07** [comment]
Hi Torsten @tsattler . Thank you for your quick response, much appreciated. Your answer is quite elaborate. In my case, I can make a fair assumption on the temporal rigidity for the target's motion. Does this mean that my case is equivalent to estimate the pose of the object with respect to the camera, in a temporal manner? If not an SfM approach, could you please suggest an alternative that would benefit from my Multi-view setup? 

Finally, if I am interested only in the object's location in the Camera coordinates across time, would it be better to perform Correspondence search + Reconstruction steps only on first frames from my three cameras, to obtain the Pose of camera + Intrinsics? Then for subsequent frames(from t+1 ..), can I use an MVS Depth estimation approach to get Z, with X, Y derived from Camera Matrix? 

Thank you once again for your time and efforts. 

Best Regards,

**Comment by tsattler** [comment]
If your target is mostly rigid, you can try running SfM on it and see how the output looks like. If you reconstruct the scene at a single point in time, you should get the poses of the camera with respect to the object.

If you are only interested in the object coordinates in 2D, why not try to do tracking in 2D? Do you need the camera poses for this?

Do you know the camera poses of your cameras?

**Comment by Sentient07** [comment]
Hi @tsattler thank you again for your time and response. I've done tracking in 2D, however, I'd like to obtain 3D trajectories of the moving targets in the scene. For which, my approach is to currently 

1) Estimate Intrinsics + Pose only for the first frame from Multiple views using SfM.
2) Estimate MVS depth maps for each frame of the video. 
3) Obtain 3D coordinates at an arbitrary scaling factor.

I aim to use the 3D trajectories for simulation purposes and hence scale is not an important factor to estimate from the scene. My issue here is, I've to compute depth maps at every frame, which is costly.

Instead, is it possible to perform PNP only in the first frame, with respect to static objects in the scene,(by assigning them arbitrary 3D coordinates), then use the new Pose matrix to estimate 3D locations of objects in the scene? 

Thank you once again!

**Comment by tsattler** [comment]
I am not sure whether I understand your question. How would you obtain the 3D coordinates without a second view?

**Comment by Sentient07** [comment]
Hi @tsattler. I have three static cameras capturing a moving scene. My goal here is to obtain the 3D coordinates of the moving object, given its position in 3 images which captured from adjacent cameras. Now, for the single object case, I understand how to use colmap to obtain the coordinates. My question is, how can I extend this for the case of multiple images(subsequent frames) from the same three cameras?

**Comment by tsattler** [comment]
Since the cameras are static, you could reconstruct each time instance individually and then register all reconstructions onto each other using the camera positions.

**Comment by Sentient07** [comment]
Hi @tsattler  Could you please share an example of how this is performed in colmap? I could see many examples with camera moving and that iterative reconstruction is perhaps different from the iterative I'm looking for.

Thank you again!

**Comment by tsattler** [comment]
Once you have individual reconstructions, you can align them using `colmap model_aligner` from the command line.

**Comment by Sentient07** [comment]
Thank you very much for your prompt responses @tsattler . As the question is answered, I'm closing the issue
