### ISSUE TITLE
A bug in similarity_transform.cc

### ISSUE THREAD

**Issue by wangyuanbiubiubiu** [colmap/colmap#877]
![a](https://user-images.githubusercontent.com/42170618/82173937-9dd1a280-9901-11ea-9eaf-8238d4c6c599.png)
I found a bug when I was using the code. I think code should change 3 to images1.size(). Because in ransac   `local_estimator.estimate (X_inlier, Y_inlier)`,images1.size() may be greater than 3. At this point, passing in the `tform12.estimate (proj_centers1, proj_centers2)` will cause sim3 to solve for NAN.And it leads to hierarchical_mapper error.

**Comment by ahojnnes** [comment]
Thanks, fixed in the latest commit in the master branch.
