### ISSUE TITLE
The print log is confusing me for long time in CompleteAndMergeTracks

### ISSUE THREAD

**Issue by hiakru** [colmap/colmap#878]
**Describe the bug**
Currently I'm debugging the oberservation number for my scenario, found the result is not as expected for "Merged observations" and "Completed observations" during mapping.

please take a look at this part:
https://github.com/colmap/colmap/blob/1432f0048699b8088fcd6c73a7a234b99bb5914c/src/controllers/incremental_mapper.cc#L177

I thinks the below 2 line should be exchanged:
line 185:  std::cout << "  => Completed observations: " << num_merged_observations
            << std::endl;
line 181:  std::cout << "  => Merged observations: " << num_completed_observations
            << std::endl;

**Expected behavior**
Merge number should follow against tri_merge_max_reproj_error

**Comment by ahojnnes** [comment]
Fixed in the latest commit in the master branch.
