### ISSUE TITLE
Which database.db for registering images ?

### ISSUE THREAD

**Issue by alexs7** [colmap/colmap#883]
When a new model is reconstructed a `database.db` is created. 

If I want to register images on the model should I be using that `database.db` or pass a new one? 

It seems it works with both cases, but in the first case it creates an index with also the first model images.

**Comment by tsattler** [comment]
Did you had a look at this: https://colmap.github.io/faq.html#register-localize-new-images-into-an-existing-reconstruction ?

**Comment by alexs7** [comment]
Yes, for param: `--database_path $PROJECT_PATH/database.db` it seems that if I don't have a database and still pass that it works and creates a new database.db, which I found a bit weird.

My localization script uses _feature_extractor_, _vocab_tree_matcher_, _image_registrator_.
