### ISSUE TITLE
colmap gui error

### ISSUE THREAD

**Issue by fantuslk** [colmap/colmap#884]
as follow:

**Comment by fantuslk** [comment]
(base) @vipadm3-PR4768GW-Invalid-entry-length-16-Fixed-up-to-11:~$ colmap gui
QXcbConnection: Failed to initialize XRandr
Qt: XKEYBOARD extension not present on the X server.
QOpenGLWidget: Failed to make context current
QOpenGLWidget: Failed to make context current
[xcb] Too much data requested from _XRead
[xcb] This is most likely caused by a broken X extension library
[xcb] Aborting, sorry about that.
colmap: ../../src/xcb_io.c:736: _XRead: Assertion `!xcb_xlib_too_much_data_requested' failed.
*** Aborted at 1590587436 (unix time) try "date -d @1590587436" if you are using GNU date ***
PC: @     0x7f3ac86a2428 gsignal
*** SIGABRT (@0x3ef000056f3) received by PID 22259 (TID 0x7f3acde5a800) from PID 22259; stack trace: ***
    @     0x7f3ac998f390 (unknown)
    @     0x7f3ac86a2428 gsignal
    @     0x7f3ac86a402a abort
    @     0x7f3ac869abd7 (unknown)
    @     0x7f3ac869ac82 __assert_fail
    @     0x7f3ac2918fe2 _XRead
    @     0x7f3acacb712d (unknown)
Aborted (core dumped)

**Comment by tsattler** [comment]
This seems more of an issue with the X-server on your system than with Colmap.

**Comment by fantuslk** [comment]
Hi,tsattler.Can I use the colmap without gui?such as in the experiment of https://github.com/tsattler/visuallocalizationbenchmark.I can't solve the  problem about gui for the moment.

**Comment by fantuslk** [comment]
@tsattler

**Comment by tsattler** [comment]
Yes, it is possible. Please read the documentation: https://colmap.github.io/cli.html

**Comment by fantuslk** [comment]
@tsattler .OK.Thank you.Let me try it on.

**Comment by fangxu622** [comment]
@fantuslk  Did you fixed? I have the same questions. Maybe because we use the remote connect。

**Comment by fantuslk** [comment]
Instead of graphical interfaces,use the cli.@fangxu622

**Comment by tsattler** [comment]
The gui requires a display. X-forwarding could help. But I would recommend running the command line tools instead of the gui if you are remote.
