### ISSUE TITLE
Register/localize new images into an existing reconstruction

### ISSUE THREAD

**Issue by Juuustin** [colmap/colmap#885]
Hi, I'd like to register/localize new images into an existing reconstruction, and I read the tutorial, there is an error when I test it.

**'Processed file [1/56]
  Name:            /COLMAP_OUTPUT/P2_0058_RESIZE/IMAGES/0073.jpg
  ERROR: Failed to read image file format.'**

The tutorial said that:

**'colmap feature_extractor \
    --database_path $PROJECT_PATH/database.db \
    --image_path $PROJECT_PATH/images \
    --image_list_path /path/to/image-list.txt'**

I am wondering the image path is for previously used images or new images?
my second question is that the image name in image-list.txt should contain the path or not?

Looking forward to hearing from you soon:)

**Comment by tsattler** [comment]
`$PROJECT_PATH/images` is the image path for the images already stored in the database. `/path/to/image-list.txt` contains the file names for the images for which features should be extracted. These file names are given relative to `$PROJECT_PATH/images`.

**Comment by Juuustin** [comment]
> `$PROJECT_PATH/images` is the image path for the images already stored in the database. `/path/to/image-list.txt` contains the file names for the images for which features should be extracted. These file names are given relative to `$PROJECT_PATH/images`.

Make sense, is it possible to use **shared intrinsics** to add new images? I tried it, but found that new images had different intrinsics, and I want to use only one shared intrinsics for all images.

**Comment by tsattler** [comment]
Yes, it is possible. See `colmap feature_extractor --help` for options.

**Comment by Juuustin** [comment]
> Yes, it is possible. See `colmap feature_extractor --help` for options.

Great! Thank you very very much!
