### ISSUE TITLE
Save project results in empty file.

### ISSUE THREAD

**Issue by bartoszek** [colmap/colmap#89]
Why trying saving project file (File>SaveProject) I always get empty file as result.
Took a quick look through `OptionManager::Write` an found out that all vectors (option_bool_, option_int_, etc.) are empty ( `gdb > print options_.options_bool_ $5 = std::vector of length 0, capacity 0` )
Looks like `OptionManager::RegisterOption` is never called (or I'm misreading something).
```
sys-info: arch-linux(4.10), gcc-6.3, qt-5.8, cuda-8.0)
ide: eclipse-gdb
colmap: current master
```

**Comment by ahojnnes** [comment]
Thanks, should be fixed with the latest commits.
