### ISSUE TITLE
How to use the rigbundleAdjuster(too less  documentation)

### ISSUE THREAD

**Issue by yuancaimaiyi** [colmap/colmap#891]
@ahojnnes  @tsattler @fishcu 
First of all,I have precise relative pose between the two two frames(like the first and second frames, the second and third frames...),So, I want to use rigbundleadjuster to limit relative pose, I've looked at a lot of issues , and there isn't a final version .And  the source code(comap.cc) is also very obscure and difficult to understand, can you produce a more detailed documentation about this ?
I think a lot of people are concerned about that too.
thanks very mush

**Comment by tsattler** [comment]
Did you had a look at the documentation provided in the code: https://github.com/colmap/colmap/blob/dev/src/exe/colmap.cc#L1598 ?

**Comment by yuancaimaiyi** [comment]
@tsattler 
Thank you very much for your answer.
I looked at the code in colmap.cc and I'm confused on two points.
First, is this separating reference and soure based on camera id?
Second, what does snapshot stand for? For example, if I define it like this, snapshot is {1,2}, {3,4}, 1 and 3 are reference camera ,does it mean that {1,2} represents the relative pose from 1 to 2, {3, 4} represents a relative pose of 3 to 4. I actually want to constrain two frames using rig_bundle_adjuster between VO (similar to graph optimization)

**Comment by tsattler** [comment]
What the rig bundle adjuster does is it takes a 3D reconstruction as input and performs some form of constrained bundle adjustment. The constraint here comes from using a multi-camera rig. During reconstruction, Colmap does not enforce relative pose constraints between images taken at the same point in time by the different cameras in the multi-camera rig. This is done as a post-processing step by the rig bundle adjuster.
To this end, you first need to define the multi-camera rig (as explained in the documentation starting in the above code snippet).

Note that the purpose of the rig bundle adjuster is not pose graph optimization. Rather it tries to ensure a rigid movement of the multi-camera rig, i.e., the relative pose between two cameras in the rig should stay the same over all snapshots (images taken by the multi-camera rig at the same point in time). 
This is not the same as pose graph optimization, where relative poses between images are used as measurements.

**Comment by yuancaimaiyi** [comment]
@tsattler
sorry to bother you again! about the optim/bundle_adjustment_test.cc ,I am very confused .
![1](https://user-images.githubusercontent.com/28293910/84254878-65119b80-ab44-11ea-8b8e-98d8105addef.png)
![2](https://user-images.githubusercontent.com/28293910/84254888-6a6ee600-ab44-11ea-9704-d8e70883a14c.png)
**As for the second picture ,I am confused by the contents of the red box.**
2 x 6 pose parameters for camera rig represents the Snapshot({2, 3} ,the pose of imageid(2) and imageid(3)?? 1 x 6 relative pose parameters for camera rig  represents the relative pose of imageid(2) and imageid(3)??
I think the answer is 4 x 6 pose parameters for camera rig(the pose of imageid(0),imageid(1),imageid(2),imageid(3),2 x 6 relative pose parameters for camera rig(imageid(0) to imageid(1) and imageid(2) to imageid(3),the imageid(0) and imageid(2) is the reference camera).
Do you think it's right? Can you give me the right answer? Thank you

**Comment by tsattler** [comment]
There are two snapshots, i.e., two pairs of images taken at the same time with the rig. For both time instances, you have one rig pose, resulting in 2 x 6 parameters. Inside the rig, you have the relative pose between one image (defining the rig coordinate system) and the other camera, resulting in 1 x 6 relative pose parameters.

**Comment by yuancaimaiyi** [comment]
@tsattler @runzh61 I use the rigBundleAdjuster to constraint  inter-frame motion estimation。Because I have the initial trajectory of vSLAM(Monocular), but the initial trajectory  is not correct, but I have the accurate relative pose between two frames obtained by other sensor, so I want to use the rigBundleAdjuster to constrain the motion between frames (set the relative pose between frames as constant), which is equivalent to the post-processing method.
@runzh61  my weichat is :yuancaimaiyi ,we can discuss about it ! If successful,we can  write a detailed document(git a branch to colmap) about rigBundleAdjuster to help more people.

**Comment by runzh61** [comment]
@tsattler Thank you!I'm sorry for not replying in time, a little busy these days.
@yuancaimaiyi OK, I have a similar problem.

**Comment by runzh61** [comment]
@ahojnnes @tsattler I wrote the rig_config json file according to your previous instructions, but still get an error.  I checked it several times and still don't know where is the problem.I enter the command in the command line and the following result appears
![image](https://user-images.githubusercontent.com/60417250/84912203-c4931c80-b0eb-11ea-9c62-283a40582ad2.png)
According to the error message "!VectorContainsDuplicateValues", I think there may be a wrong line 82 in the json file, that is, there seems to be a problem with frame028.jpg
![image](https://user-images.githubusercontent.com/60417250/84913238-e5a83d00-b0ec-11ea-8e6d-6658c9acaf8a.png)
Or maybe my input and output file address is wrong?
Here is my input_path(F:\COLMAP\video\)
![image](https://user-images.githubusercontent.com/60417250/84913885-9282ba00-b0ed-11ea-86f6-821bd33e52df.png)
The images folder contains two subfolders
![image](https://user-images.githubusercontent.com/60417250/84914023-b7772d00-b0ed-11ea-8da2-81ca6b551140.png)
The pictures in each subfolder are named according to the instructions
![image](https://user-images.githubusercontent.com/60417250/84914256-fdcc8c00-b0ed-11ea-9ff0-66f0f3bc1894.png)
Below is the json file I wrote
[
   {
     "ref_camera_id": 1,
     "cameras":
     [
       {
           "camera_id": 1,
           "image_prefix": [
			  "left1_image/frame000.jpg",
			  "left1_image/frame001.jpg",
			  "left1_image/frame002.jpg",
			  "left1_image/frame003.jpg",
			  "left1_image/frame004.jpg",
			  "left1_image/frame005.jpg",
			  "left1_image/frame006.jpg",
			  "left1_image/frame007.jpg",
			  "left1_image/frame008.jpg",
			  "left1_image/frame009.jpg",
			  "left1_image/frame010.jpg",
			  "left1_image/frame011.jpg",
			  "left1_image/frame012.jpg",
			  "left1_image/frame013.jpg",
			  "left1_image/frame014.jpg",
			  "left1_image/frame015.jpg",
			  "left1_image/frame016.jpg",
			  "left1_image/frame017.jpg",
			  "left1_image/frame018.jpg",
			  "left1_image/frame019.jpg",
			  "left1_image/frame020.jpg",
			  "left1_image/frame021.jpg",
			  "left1_image/frame022.jpg",
			  "left1_image/frame023.jpg",
			  "left1_image/frame024.jpg",
			  "left1_image/frame025.jpg",
			  "left1_image/frame026.jpg",
			  "left1_image/frame027.jpg",
			  "left1_image/frame028.jpg",
			  "left1_image/frame029.jpg",
			  "left1_image/frame030.jpg",
			  "left1_image/frame031.jpg",
			  "left1_image/frame032.jpg",
			  "left1_image/frame033.jpg",
			  "left1_image/frame034.jpg",
			  "left1_image/frame035.jpg",
			  "left1_image/frame036.jpg",
			  "left1_image/frame037.jpg",
			  "left1_image/frame038.jpg"
		   ]
       },
       {
           "camera_id": 2,
           "image_prefix": 
		   [
			  "right1_image/frame000.jpg",
			  "right1_image/frame001.jpg",
			  "right1_image/frame002.jpg",
			  "right1_image/frame003.jpg",
			  "right1_image/frame004.jpg",
			  "right1_image/frame005.jpg",
			  "right1_image/frame006.jpg",
			  "right1_image/frame007.jpg",
			  "right1_image/frame008.jpg",
			  "right1_image/frame009.jpg",
			  "right1_image/frame010.jpg",
			  "right1_image/frame011.jpg",
			  "right1_image/frame012.jpg",
			  "right1_image/frame013.jpg",
			  "right1_image/frame014.jpg",
			  "right1_image/frame015.jpg",
			  "right1_image/frame016.jpg",
			  "right1_image/frame017.jpg",
			  "right1_image/frame018.jpg",
			  "right1_image/frame019.jpg",
			  "right1_image/frame020.jpg",
			  "right1_image/frame021.jpg",
			  "right1_image/frame022.jpg",
			  "right1_image/frame023.jpg",
			  "right1_image/frame024.jpg",
			  "right1_image/frame025.jpg",
			  "right1_image/frame026.jpg",
			  "right1_image/frame027.jpg",
			  "right1_image/frame028.jpg",
			  "right1_image/frame029.jpg",
			  "right1_image/frame030.jpg",
			  "right1_image/frame031.jpg",
			  "right1_image/frame032.jpg",
			  "right1_image/frame033.jpg",
			  "right1_image/frame034.jpg",
			  "right1_image/frame035.jpg",
			  "right1_image/frame036.jpg",
			  "right1_image/frame037.jpg",
			  "right1_image/frame038.jpg"
		  ]
       }
     ]
   }
]
Hope you can give me some suggestions, thank you！

**Comment by tsattler** [comment]
Since you opened an issue on the topic, there is no need to discuss it here.

**Comment by davidjevans** [comment]
The link @tsattler originally posted is broken, and it took me a sec to find where the documentation now exists. Here's a permalink for other weary internet travelers: https://github.com/colmap/colmap/blob/a692b6813ce76c3bffc60db067435bc80c71488f/src/colmap/exe/sfm.cc#L536

**Comment by randomEetu** [comment]
> The link [@tsattler](https://github.com/tsattler) originally posted is broken, and it took me a sec to find where the documentation now exists. Here's a permalink for other weary internet travelers:
> 
> [colmap/src/colmap/exe/sfm.cc](https://github.com/colmap/colmap/blob/a692b6813ce76c3bffc60db067435bc80c71488f/src/colmap/exe/sfm.cc#L536)
> 
> Line 536 in [a692b68](/colmap/colmap/commit/a692b6813ce76c3bffc60db067435bc80c71488f)
>  // Read the configuration of the camera rigs from a JSON file. The input images

FYI, the new JSON format may be found in
https://github.com/colmap/colmap/blob/557ff9b13ac9e50570096ce2d37594da16f977da/src/colmap/scene/rig.h
The format with attribute `"ref_camera_id"` is now deprecated and will lead in
`Check failed: has_ref_sensor Rig must have one reference sensor`
