### ISSUE TITLE
16bit tiff issue.

### ISSUE THREAD

**Issue by bartoszek** [colmap/colmap#90]
When loading 16bit tiffs, image size gets incorrectly reported as '0', those preventing feature extractor from work.

**Comment by ahojnnes** [comment]
Could you please share an example picture?

**Comment by bartoszek** [comment]
https://www.dropbox.com/sh/xgabja7ropfwu22/AAD3ho94AXbFH1oayQ3J3zgha?dl=0

**Comment by ahojnnes** [comment]
COLMAP does not support 16bit images for now and these images are ignored now by default with the latest commit. Thanks for the bug report!

**Comment by pogilon** [comment]
@ahojnnes. This would be a great feature, especially for people like me who are looking for ways to increase the SNR. Any recommendations on how to help you add it to the project? Thanks.

**Comment by ahojnnes** [comment]
This would involve many changes to the pipeline. Most importantly SIFT has to be reimplemented for 16bit images. I don't think there is a great benefit in using 16bit images. How about you convert your images to 8bit before processing them with Colmap?

**Comment by pogilon** [comment]
@ahojnnes I am mostly interested in them for the MVS part. I am happy with converting them to 8bit for SfM. How hard would it be to incorporate it in the Stereo process?

**Comment by strarsis** [comment]
+1, 16bit information from multiple exposures would be too valuable to be just discarded.
