### ISSUE TITLE
Could not find Qt5 but qt5-default is installed

### ISSUE THREAD

**Issue by pascalenderli** [colmap/colmap#91]
I have installed with apt-get
qt5-default
qtbase5-dev
qtchooser
qt5-qmake
qtbase5-dev-tools

when building COLMAP i get the error:
```
[...]
CMake Error at cmake/FindQt5.cmake:23 (message):
  Could not find Qt5
Call Stack (most recent call first):
  CMakeLists.txt:80 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/MYUSERNAME/Downloads/colmap-master/build/CMakeFiles/CMakeOutput.log".
```

Where the /FindQt5.cmake files does the following thing:

```
find_package(Qt5Core QUIET)
find_package(Qt5OpenGL QUIET)

if(Qt5Core_FOUND AND Qt5OpenGL_FOUND)
    set(Qt5_FOUND TRUE)
    set(Qt5_INCLUDE_DIRS "${Qt5Core_INCLUDE_DIRS} ${Qt5OpenGL_INCLUDE_DIRS}")
    set(Qt5_LIBRARIES "${Qt5Core_LIBRARIES} ${Qt5OpenGL_LIBRARIES}")
endif()

if(Qt5_FOUND)
    message(STATUS "Found Qt ${Qt5Core_VERSION_STRING}")
else()
    if(Qt5_FIND_REQUIRED)
        message(FATAL_ERROR "Could not find Qt5")
    endif()
endif()
```

in the built CMakeCache.txt file it is written:
```
//The directory containing a CMake configuration file for Qt5Core.
Qt5Core_DIR:PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5Core

//The directory containing a CMake configuration file for Qt5OpenGL.
Qt5OpenGL_DIR:PATH=Qt5OpenGL_DIR-NOTFOUND`
```

So just the config file for  Qt5OpenGL is missing.

How can I install COLMAP then?

The CMakeOutput.log is attached here:
[CMakeOutput.log.tar.gz](https://github.com/colmap/colmap/files/864338/CMakeOutput.log.tar.gz)

**Comment by ahojnnes** [comment]
Would you please post your solution to the problem? Even if it is just a brief summary, it might help others in the future.

**Comment by pascalenderli** [comment]
I solved the problem by replacing my Linux Mint Serena 18.1 Distro by Ubuntu 16.04.
I don't know what exactly the problem was, since Ubuntu and Mint are not that different.
With Ubuntu I did the same instalation process as before and the Qt5OpenGL config file was properly installed. Nevertheless, this does not mean that just Mint as such was the main problem.
