### ISSUE TITLE
Image Registration in COLMAP does it also consider new localised images ?

### ISSUE THREAD

**Issue by alexs7** [colmap/colmap#913]
Hello,

Is the image registration from [here](https://colmap.github.io/faq.html#register-localize-new-images-into-an-existing-reconstruction) using also the new images ?

What I mean is that if I have a model with 100 images and I want to localise 50 new ones.

So I localise 1, and 49 remaining. The next one (no. 2) will it use descriptors from the 100 images or descriptors from the 101 (+1 localised) images ?

I mean do new descriptors get picked up as new images are localised ?

EDIT: docs says, _"... and finally registers them into the model."_ so I assume it only uses the 100 images ?

**Comment by tsattler** [comment]
The image registrator tries to localize all images in the database that are not in the model. However, it does not extend the model by new points or new observations.

In the case of your 100 images, only 100 images would contribute to the model.

**Comment by alexs7** [comment]
@tsattler Ok thanks!
