### ISSUE TITLE
Dense reconstruction depth images look noisy

### ISSUE THREAD

**Issue by shamitlal** [colmap/colmap#914]
Hi,
I tried running colmap automatic reconstruction on 7 multiview images from gerrard-hall dataset.
I used the following command:

`colmap automatic_reconstructor     --workspace_path $DATASET_PATH     --image_path $DATASET_PATH/images --single_camera 1 --camera_model PINHOLE`

Below you can see the RGB, generated depth, and generated pointcloud for that depth image.
As can be seen, the pointcloud looks too noisy with wall and half the door far from camera (orange) and other half near the camera (blue).
Is this expected? Or is there any other step that I should have followed to get both the door and wall at similar depth ranges?

<img width="1256" alt="Screenshot 2020-06-22 at 12 09 05 PM" src="https://user-images.githubusercontent.com/9249746/85310592-2e138200-b482-11ea-8822-7d4f07b63346.png">

Thanks

**Comment by tsattler** [comment]
This is to be expected. As the doors are nearly uniformly colored, it is very hard to get good depth estimates for them. Fusing multiple depth maps (Colmap provides functionality for this) will improve the results.

**Comment by shamitlal** [comment]
Thanks for the quick reply. 
Do you think providing depth range might improve the results?
Will the depth values always be within the provided range, i.e. is it a hard constraint?

**Comment by tsattler** [comment]
Providing a depth range will likely not solve the problem, but just reduce the error range.

I don't know whether it is a hard constraint. I recommend looking into the source code to answer that question.

**Comment by shamitlal** [comment]
Thanks for the help.
Closing the issue.
