### ISSUE TITLE
Nvm export - full patch to image.

### ISSUE THREAD

**Issue by bartoszek** [colmap/colmap#92]
I menage to get [hpmvs](https://github.com/alexlocher/hpmvs) working with colmaps exported nvm models.
Single alteration, including full patch to the image in nvm exported model, was needed.
Sadly that still weren't  enough for meshlab to load nvm exported model.

**Comment by chrmertz** [comment]
I had to edit the colmaps nvm model for meshlab to load it. I had to add a space after "NVM_V3", one space in the following line and two spaces after the number of points ("*" signifies an empty space):

NVM_V3**
*
94**

I tested this in Ubuntu 16.04, 64 bit.

**Comment by chrmertz** [comment]
typo, one "*" too many, should be:
NVM_V3*
*
94**

**Comment by chrmertz** [comment]
NVM_V3*

**Comment by ahojnnes** [comment]
Should be fixed with the latest commits in the dev branch. Thanks!
