### ISSUE TITLE
What will happen if a 3d point is associated not only by the local_bundle but also by other images?

### ISSUE THREAD

**Issue by Tonsty** [colmap/colmap#920]
In the local bundle adjustment, when one image is added, only the reprojection error (of the visible 3d points) on this image  is added to the loss, but the reprojection error on images outside the local bundle (freezed images) is ignored. The position of the 3d points will change during local BA, so I wonder whether the reprojection error on the freezed images should also be added to the loss.

https://github.com/colmap/colmap/blob/07b46598471e8bd2185c843dd6450e3108aaa640/src/sfm/incremental_mapper.cc#L572

**Comment by ahojnnes** [comment]
Any 3D points not fully observed in the local bundle are kept fixed. You can find the logic in the optim/bundle_adjustment.cc.

**Comment by Tonsty** [comment]
@ahojnnes ，thanks，yes，I have found it  in  BundleAdjuster::ParameterizePoints
https://github.com/colmap/colmap/blob/12e9ff6922d4bdf4a86135c372a4d66a9fa8f750/src/optim/bundle_adjustment.cc#L525
