### ISSUE TITLE
Hi, Some questions about parameters

### ISSUE THREAD

**Issue by superminghui** [colmap/colmap#926]
Hi, I am using colmap gui to process some data.
But I am confused about the role of many of these parameters, and I have not found a relevant explanation. So let me ask, I hope to get the answer.
In Feature Extraction,
        • Parameters “first_octave” = -1, “num_octaves” = 4, “octave_resolution” = 3
	• Parameters “peak_threshold” = 0.00667, “edge_threshold” = 10.00
	• Parameter “estimate_affine_shape”
	• Parameter “max_num_orientations” = 2
	• Parameter “upright”
	• Parameter “domain_size_pooling”
	• Parameter “dsp_min_scale” = 0.16667
	• Parameter “dsp_max_scale” = 3.00000
	• Parameter “dsp_num_scales” = 10
	• Parameter “num_threads” = -1
So what is the meaning of these parameters? I want to understand their role and observe these changes by modifying these parameters later.
I hope to get your reply, or tell me where I can find the relevant explanation

THX！

**Comment by tsattler** [comment]
The parameters “first_octave” = -1, “num_octaves” = 4, “octave_resolution” = 3, “peak_threshold” = 0.00667, “edge_threshold” = 10.00, and “max_num_orientations” = 2 specify the behavior of the SIFT feature extractor. I would recommend reading the SIFT paper by Lowe or the VLFeat tutorials to understand their meaning.

"estimate_affine_shape" defines whether to use standard DoG detections or affine-covariant detections. I recommend having a look at the VLFeat tutorials for details.

"upright" specifies whether the keypoint detector should estimate the orientation of each keypoint or whether it should be fixed (value 1).

"num_threads" should be self-explanatory.

The remaining parameters are related to DSP SIFT. You can find more details in the paper describing the method.

**Comment by superminghui** [comment]
> The parameters “first_octave” = -1, “num_octaves” = 4, “octave_resolution” = 3, “peak_threshold” = 0.00667, “edge_threshold” = 10.00, and “max_num_orientations” = 2 specify the behavior of the SIFT feature extractor. I would recommend reading the SIFT paper by Lowe or the VLFeat tutorials to understand their meaning.
> 
> "estimate_affine_shape" defines whether to use standard DoG detections or affine-covariant detections. I recommend having a look at the VLFeat tutorials for details.
> 
> "upright" specifies whether the keypoint detector should estimate the orientation of each keypoint or whether it should be fixed (value 1).
> 
> "num_threads" should be self-explanatory.
> 
> The remaining parameters are related to DSP SIFT. You can find more details in the paper describing the method.

Thank u so much.  This helps me a lot.
