### ISSUE TITLE
Is there any way to use the geometric filter after some operation on the colmap stereo output geometric depth

### ISSUE THREAD

**Issue by philleer** [colmap/colmap#929]
Hi there @ahojnnes 

As shown in the title, I get the photometric and geometric depth map using colmap patch_match_stereo module. 
And then I do some filling opertaion on the output geo depth, but such operation may introduce some other noise, so I want to do geometric check again on the operated result.

What I find in the colmap source code is geom_consistency filtering in the patch_match_cuda.cu file, so I must run the pipeline as patch_match_stereo again? Or is there any way to use the filtering part only?

Any suggestion would be appreciated! Thanks in advance.

**Comment by ahojnnes** [comment]
The stereo fusion will also perform multi-view geometric consistency filtering similar to the patch match step. In the former, it's a hard filtering, in the latter a regularization of the photo consistency cost.

**Comment by philleer** [comment]
Okay, thanks for your advice. I would try it now.
