### ISSUE TITLE
Script CMVS/COLMAP missing

### ISSUE THREAD

**Issue by pogilon** [colmap/colmap#93]
In the COLMAP documentation it states that "Please, refer to the sample shell scripts on how to run CMVS in combination with COLMAP or PMVS2". However, I can't find it. I believe it is missing. Thanks!

**Comment by ahojnnes** [comment]
They are in the output folder of the undistortion.

**Comment by ClaudioCimarelli** [comment]
@ahojnnes Did you remove those script? There are only examples of how to run the last step of the pipeline in COLMAP.

Thank in advance.
