### ISSUE TITLE
sparse  reconstruction generate multiple folder

### ISSUE THREAD

**Issue by wolf943134497** [colmap/colmap#931]
Hi @ahojnnes  Thanks for your great works!
in some case, run command 'colmap automatic_reconstructor', sparse  reconstruction generate multiple folder, folder 0 and foler 1, dense reconstruction can not get the ply 3d model file.
any suggestions?  because of dataset problem?  Thanks!

**Comment by ahojnnes** [comment]
Multiple sparse folders mean that not all images have sufficient visual overlap and hence COLMAP cannot reconstruct all the images into the same connected component.

**Comment by wolf943134497** [comment]
Thanks for your quick reply ! Thank you again for your great work ! @ahojnnes
