### ISSUE TITLE
colmap command not found on Ubuntu 18.04

### ISSUE THREAD

**Issue by jeremyxie712** [colmap/colmap#933]
**Describe the bug**
I have successfully built everything following the guide in the documentation where after all the processes, when I tried to test using `colmap -h`, I received 

"_Command 'colmap' not found, but can be installed with: apt install colmap Please ask your administrator.
You will have to enable the component called 'universe_'"

Due to the fact that I have ssh-ed into an educational server and I am not an administrator, I do not have the clearance of using apt command to install pretty much anything. I wonder if there is any other way to fix this? Much obliged to anyone who can help me on this. 

**Screenshots**
This is my make 
<img width="740" alt="Screenshot 2020-07-27 at 11 31 31" src="https://user-images.githubusercontent.com/33794901/88501008-c5797100-cffc-11ea-9976-087cc44dcbfe.png">

And this is make install 
<img width="744" alt="Screenshot 2020-07-27 at 11 14 20" src="https://user-images.githubusercontent.com/33794901/88500843-69aee800-cffc-11ea-8c93-9032f7f55813.png">

The command not found is below: 
<img width="459" alt="Screenshot 2020-07-27 at 11 29 54" src="https://user-images.githubusercontent.com/33794901/88500944-9a8f1d00-cffc-11ea-9f95-513486cb27cc.png">

**Comment by tsattler** [comment]
Is the directory with the executable (src/exe/ in the build directory or the place where you installed the binary) in your PATH? Otherwise, the OS will not be able to find the executable.

**Comment by jeremyxie712** [comment]
> Is the directory with the executable (src/exe/ in the build directory or the place where you installed the binary) in your PATH? Otherwise, the OS will not be able to find the executable.

Thank you! I did forget that. I used 'export PATH=${PATH}:/vol/bitbucket/lx219/colmap/bin' to solve this issue.
