### ISSUE TITLE
 image_registrator 

### ISSUE THREAD

**Issue by Juuustin** [colmap/colmap#939]
Hi, I want to do [https://colmap.github.io/faq.html#register-localize-new-images-into-an-existing-reconstruction](url), and the third step is
**colmap image_registrator \
    --database_path $PROJECT_PATH/database.db \
    --input_path /path/to/existing-model \
    --output_path /path/to/model-with-new-images**
I am confused with the difference of 'existing-model ' and 'model-with-new-images', and what should those paths contain, thank you very much!

**Comment by tsattler** [comment]
The image registrator tries to add new images against an existing 3D model. The new images will not be used to create new 3D points and the results will be written into a model that contains the original model with the new images.

**Comment by Juuustin** [comment]
Make sense, and thank you very much!

**Comment by saisharathsadu** [comment]
@tsattler 

But when I check my points3d.bin before and after executing the image_registartor, there is a change. Especially it shows the camer_id of new cameras, which ideally should npt happen. The nu,ber of 3dpoints are remaining same, but the other values are changing.

Can you comment on this?

**Comment by tsattler** [comment]
Not unless you are more specific.
