### ISSUE TITLE
feature matching runs very very slow on CPU only mode.

### ISSUE THREAD

**Issue by HUSTyanchao** [colmap/colmap#94]
My computer has a GTX1080. I experiment with the supplied south-building dataset. It works fine with GPU. However, it runs very very slow without using GPU. What is the matter?

**Comment by cebe** [comment]
What do you mean with "very very slow". GPU is expected to be way faster than CPU because it can parallelize a lot more operations than CPU.

**Comment by HUSTyanchao** [comment]
Well, I have 20 images in total，all images are about 3000*2000 in size. It cost about an hour to matching the first image! I think there must be something wrong.

**Comment by ahojnnes** [comment]
Did you build in Debug mode?

**Comment by HUSTyanchao** [comment]
No. I download the pre-built binaries from the project website and work on Windows 10  x64 machine.

**Comment by ahojnnes** [comment]
It is expected that CPU matching is very slow. Closing this issue for now. Feel free to reopen.
