### ISSUE TITLE
Sparse reconstruction considering only one camera

### ISSUE THREAD

**Issue by vinayver198** [colmap/colmap#940]
Hi, 
In my experiment I have images of 3 cameras taken in sequence. 
For eg : camera1,camera2 and camera3 . I have arranged the images in this order 
images 
  - camera1 
      ............ images in this folder of camera1
- camera2 
      .............images in this folder of camera2
- camera3 
      .............images in this folder of camera3

Now after doing sparse reconstruction and after undistorting the images only one camera images appear for dense process.
How to make sure that all images or some images from the three cameras are used ?

Please find the steps  : 

colmap feature_extractor --ImageReader.single_camera_per_folder=1   --database_path $DATASET_PATH/database.db    --image_path $DATASET_PATH/images    --SiftExtraction.use_gpu 1 

colmap sequential_matcher --database_path $DATASET_PATH/database.db --SiftMatching.guided_matching=1 --SequentialMatching.overlap=10 --SequentialMatching.vocab_tree_path ~/Desktop/pcd_development/data/Gaze/vocab_tree_flickr100K_words256K.bin
Elapsed time: 26.766 [minutes]

colmap mapper --database_path $DATASET_PATH/database.db --image_path $DATASET_PATH/images --output_path $DATASET_PATH/sparse --log_to_stderr=1 --Mapper.ignore_watermarks=1 --Mapper.multiple_models=0 --Mapper.ba_local_max_num_iterations=5 --Mapper.ba_global_use_pba=1 --Mapper.ba_global_max_num_iterations=5

 colmap image_undistorter     --image_path $DATASET_PATH/images     --input_path $DATASET_PATH/sparse/0     --output_path $DATASET_PATH/dense     --output_type COLMAP

**Comment by tsattler** [comment]
I would assume that by using the sequential matcher, you do not get many matches between images taken with different cameras. If this is the case, it would be natural that you get a reconstruction from only one camera (since you explicitly disallowed multiple models). The alternative is that there is not enough visual overlap between the cameras.
You can check which images have matches through the database management in the gui.

**Comment by vinayver198** [comment]
@tsattler  Thanks for reply.
I tried multiple models as True . Still the same issue exists. 
Also I have a query is it possible to have my reconstruction growth for all the images in my dataset . My dataset has got images of a street taken sequentially.

**Comment by tsattler** [comment]
Allowing multiple models as output will not solve the issue that you will get separate models if you do not have matches between images taken with different cameras.

Colmap can continue reconstruction from an existing 3D model.

**Comment by vinayver198** [comment]
@tsattler this issue got resolved after using spatial matcher.

**Comment by tsattler** [comment]
@vinayver198 Great to hear. Do you want to close this issue?
