### ISSUE TITLE
How to do dense reconstruction with customized sparse SfM?

### ISSUE THREAD

**Issue by oblime** [colmap/colmap#941]
Hello, I'm trying to use the colmap to reconstruct a dense model from a sparse model that I computed using my own SfM method. I have special need for the sparse model so I cannot directly use the sparse construction from colmap. 

In order to do so, I follow the document and generate the needed files (cameras.txt, images.txt, points3d.txt) from my sparse model. The colmap gui successfully imported and displayed my sparse model, and I create an new project and database. However, it seems that I cannot run dense reconstruction because currently the database is still empty. 

I got all the thing needed for dense reconstruction (camera poses, intrinsics, image feature points, matches...). So I was wondering if there are simple method to convert sparse model to database. Or what can I do to run a dense reconstruction given the sparse model?

**Comment by tsattler** [comment]
You should not need a database for dense reconstruction. A sparse model in COLMAP's format should be all that is necessary.

**Comment by oblime** [comment]
Thank you very much for your quick reply! I just find I should do it using the dense reconstruction API instead of the auto reconstruction. Sorry for the simple question
