### ISSUE TITLE
Reconstruct sparse/dense model from known camera intrinsics

### ISSUE THREAD

**Issue by Juuustin** [colmap/colmap#942]
Hi, Recently I use the same camera to do  3D reconstruction, while the scenarios are different. After I use automatic reconstruction, I find that the camera intrinsics change obviously between different scenarios, while it should be the same since I use the same camera.

I'd like to try automatic reconstruction from known camera intrinsics, but I only find a link: [Fix intrinsics](https://colmap.github.io/faq.html#fix-intrinsics), and it seems there is no input for the known camera intrinsics. So could I do automatic reconstruction with known camera intrinsics? Looking forward to hearing from you soon!

**Comment by tsattler** [comment]
You can specify the intrinsics when extracting features (I am not sure whether this also works for the automated pipeline, never used that) or you can modify the database.

**Comment by Juuustin** [comment]
Hi @tsattler thank you for your reply, and I will have a try now
