### ISSUE TITLE
acquire geometric.bin only

### ISSUE THREAD

**Issue by littlebirdicy** [colmap/colmap#945]
Dear sir, now I need colmap to acquire geometric.bin for another project, but I've noticed that photometric.bin is generated first.
Might I acquire geometric.bin only? Looking forward to your reply.

**Comment by tsattler** [comment]
As I understand the code, the photometric depth maps need to be computed before the geometric depth maps can be computed: https://github.com/colmap/colmap/blob/d3a29e203ab69e91eda938d6e56e1c7339d62a99/src/mvs/patch_match.cc#L201

**Comment by littlebirdicy** [comment]
My sincerely thanks for your reply!
