### ISSUE TITLE
COLMAP "No convergence and No good initial image pair found" Problems

### ISSUE THREAD

**Issue by jgranda19** [colmap/colmap#952]
Hi everyone, 
When using COLMAP's Automatic Reconstruction, every time I run the program, I get the following message on the right of my screen: 
 Termination: No convergence

  => Filtered observations: 0
  => Filtered images: 0
  => No good initial image pair found.

Also, nothing on my screen appears beside the there vector axis. I am sure I downloaded COLMAP correctly and have enough images to create a point-cloud and mesh. Please feel free to respond back to me as soon as possible. Thank you so much!

**Comment by jgranda19** [comment]
Here is the full Log.  Thank you in advance. 

[Toy Car log 1.log](https://github.com/colmap/colmap/files/5064831/Toy.Car.log.1.log)

**Comment by tsattler** [comment]
Hard to guess without having any look at the dataset.
Might be a lack of sufficiently many matches. Another option could be that you have mostly forward motion, which is not stable enough to initialize a reconstruction.

**Comment by jgranda19** [comment]
> Hard to guess without having any look at the dataset.
> Might be a lack of sufficiently many matches. Another option could be that you have mostly forward motion, which is not stable enough to initialize a reconstr

**Comment by jgranda19** [comment]
> Hard to guess without having any look at the dataset.
> Might be a lack of sufficiently many matches. Another option could be that you have mostly forward motion, which is not stable enough to initialize a reconstruction.

Thank you for the information. Here are the pictures in my dataset. 

![IMG-3498](https://user-images.githubusercontent.com/69336720/90052008-90307c80-dca6-11ea-8024-6a4d198d1f2b.jpg)
![IMG-3512](https://user-images.githubusercontent.com/69336720/90052011-90c91300-dca6-11ea-9541-f81fe93e36d2.jpg)
![IMG-3513](https://user-images.githubusercontent.com/69336720/90052012-90c91300-dca6-11ea-80f9-c0c10e6d5495.jpg)
![IMG-3514](https://user-images.githubusercontent.com/69336720/90052014-9161a980-dca6-11ea-81c0-60b3c6318981.jpg)
![IMG-3515](https://user-images.githubusercontent.com/69336720/90052017-9161a980-dca6-11ea-894a-6bb8f4caf76d.jpg)
![IMG-3516](https://user-images.githubusercontent.com/69336720/90052020-91fa4000-dca6-11ea-8831-e33eaa7a6278.jpg)
![IMG-3517](https://user-images.githubusercontent.com/69336720/90052021-91fa4000-dca6-11ea-900a-27b58998ec6e.jpg)
![IMG-3518](https://user-images.githubusercontent.com/69336720/90052022-9292d680-dca6-11ea-84cb-f1ad2d6fcba3.jpg)
![IMG-3519](https://user-images.githubusercontent.com/69336720/90052024-9292d680-dca6-11ea-93ed-d6d2122fb00f.jpg)
![IMG-3520](https://user-images.githubusercontent.com/69336720/90052026-9292d680-dca6-11ea-8212-f50b394d9d03.jpg)
![IMG-3523](https://user-images.githubusercontent.com/69336720/90052028-932b6d00-dca6-11ea-9c64-a5a5173f19d5.jpg)
![IMG-3525](https://user-images.githubusercontent.com/69336720/90052029-932b6d00-dca6-11ea-9d7c-f8c659ce3c45.jpg)
![IMG-3543](https://user-images.githubusercontent.com/69336720/90052030-932b6d00-dca6-11ea-8687-a31eb70df018.jpg)
![IMG-3545](https://user-images.githubusercontent.com/69336720/90052031-93c40380-dca6-11ea-8fe8-33a05618daa0.jpg)
![IMG-3546](https://user-images.githubusercontent.com/69336720/90052034-93c40380-dca6-11ea-8a23-1bbb983b16df.jpg)
![IMG-3547](https://user-images.githubusercontent.com/69336720/90052036-945c9a00-dca6-11ea-8b16-b0e272f53bd6.jpg)
![IMG-3548](https://user-images.githubusercontent.com/69336720/90052037-945c9a00-dca6-11ea-9b34-bac69e824f98.jpg)
![IMG-3549](https://user-images.githubusercontent.com/69336720/90052039-94f53080-dca6-11ea-8c92-dca652e9e9b8.jpg)
![IMG-3550](https://user-images.githubusercontent.com/69336720/90052042-94f53080-dca6-11ea-8634-f3ea8c11ed63.jpg)
![IMG-3551](https://user-images.githubusercontent.com/69336720/90052044-958dc700-dca6-11ea-850a-448275c030ac.jpg)
![IMG-3553](https://user-images.githubusercontent.com/69336720/90052047-958dc700-dca6-11ea-8351-c558b10ac9ef.jpg)

**Comment by tsattler** [comment]
Looking at the dataset, I would assume you run into some of the following problems:
* Few features are detected due to a lack of texture in the scene.
* There is rather large blur in some of the images.
* The viewpoint changes are rather large with respect to the depth of the scene. This makes feature matching hard.

Did you check visually (you can do this in the gui) how the matches you get look like?

**Comment by jgranda19** [comment]
> Looking at the dataset, I would assume you run into some of the following problems:
> 
> * Few features are detected due to a lack of texture in the scene.
> * There is rather large blur in some of the images.
> * The viewpoint changes are rather large with respect to the depth of the scene. This makes feature matching hard.
> 
> Did you check visually (you can do this in the gui) how the matches you get look like?
