### ISSUE TITLE
Export dense PCD as .bin camera model issue

### ISSUE THREAD

**Issue by vinayver198** [colmap/colmap#961]
Hi, 
I have used default camera model for calibration in COLMAP . However when I run this command

colmap stereo_fusion --workspace_path $DATASET_PATH/dense --workspace_format COLMAP --input_type photometric --output_path $DATASET_PATH/fusion  --StereoFusion.cache_size=8 --StereoFusion.max_image_size=1000 --output_type BIN

I am receiving camera model as PINHOLE . It should be SIMPLE_RADIAL. 

Sparse Model Output for cameras
# Number of cameras: 3
3 SIMPLE_RADIAL 1920 1080 1395.39 960 540 -0.149021
1 SIMPLE_RADIAL 1920 1080 1409.84 960 540 -0.154182
2 SIMPLE_RADIAL 1920 1080 1421.07 960 540 -0.157166

Dense Model Output for Cameras
# Number of cameras: 3
3 PINHOLE 1000 527 666.376 666.097 500 263.5
1 PINHOLE 1000 527 671.993 672.386 500 263.5
2 PINHOLE 1000 527 677.345 677.741 500 263.5

Also I have scaled the images in dense reconstruction with max image size as 1000.

**Comment by tsattler** [comment]
Prior to depth map estimation, Colmap undistorts the images, i.e., removes radial distortion, thus resulting in images taken by pinhole cameras. This is done as estimating depth maps for pinhole camera images is significantly easier.
During the image undistortion process, Colmap creates a sparse 3D model that is used for the reconstruction, where each image uses the pinhole model. Thus, it is to be expected that pinhole cameras are used for the fusion of the depth maps as they were used to create the depth maps in the first space.

**Comment by vinayver198** [comment]
Thanks
