### ISSUE TITLE
Check failed: max_error > 0 (-17.3032 vs. 0) 

### ISSUE THREAD

**Issue by GabbySuwichaya** [colmap/colmap#962]
**Describe the bug**
Get  ...check failed: max_error > 0 (-17.3032 vs. 0)  then it goes on. 
My screen captured is below: 

![ORG_R2Crash_Gendarmenmrk](https://user-images.githubusercontent.com/49115268/91595372-65c90980-e99e-11ea-865d-0499a08c7c76.png)

**To Reproduce**
1. Test a published local features on  https://github.com/ahojnnes/local-feature-evaluation
2. Use Gendarmenmarkt (But I can run the Tower of London.)
3. Then, after started running the 3D recon. script (offline) for a while (registering image 695/1065). I get the above error. 

   
**Expected behavior**

I noticed that I get the fail recon. with this dataset (Gendarmenmarkt) very often. Except if I use some image retrieval, then, I can avoid the problem. So, if you know what could have cost the problem, please let me know. 

 
**Desktop (please complete the following information):**

- OS: [Ubuntu 18.04]

- COLMAP - Dev branch (the last commit on 2020/06/16.... parallel complete #899 )

- Ceres solver - master (the last commit on 2020/06/16 Add a missing term and remove superfluous...) 

 **Additional context**

I noticed that you also take care of https://github.com/ahojnnes/local-feature-evaluation as well, so I am not sure which place should I contact you. But I hope it is ok to post the problem here.

**Comment by ahojnnes** [comment]
That's strange. Did you adjust any parameters manually?

**Comment by ahojnnes** [comment]
Okay, I can only see this happening when there is a negative focal length value stored in the database or an optimization step inside COLMAP produces negative values due to some degeneracies.

**Comment by GabbySuwichaya** [comment]
Which one are you referring to? 

I did not touch anything with the COLMAP. 
However,  as a process of testing, I somehow have to provide the database file, so I have made some changes in the database file.

**Comment by ahojnnes** [comment]
Can you share the database with ne?

**Comment by GabbySuwichaya** [comment]
Ok, the database file is here. 

https://drive.google.com/file/d/1-2PBzi5tppJrr6qXlGDLVbsHo8yQF_Mh/view?usp=sharing

**Comment by ahojnnes** [comment]
Thanks, but I cannot reproduce the issue on my machine using the following command: `./src/exe/colmap mapper --database_path database.db --image_path . --output_path test`

**Comment by GabbySuwichaya** [comment]
I see. I will try with the latest commit id of COLMAP Master branch and will keep you update. 

Also, I have noticed that this [Local-feature-evaluation repo](https://github.com/ahojnnes/local-feature-evaluation) seems to depends on a commit id ([58d966c](https://github.com/ahojnnes/local-feature-evaluation/blob/master/INSTRUCTIONS.md#instructions)) which is referring to an old version of COLMAP. 

However, recently there seems to be a lot of changes in Ceres (master branch). 
So, could you please point out the **commit id of the Ceres solver** associated with the COLMAP commit id ([58d966c](https://github.com/ahojnnes/local-feature-evaluation/blob/master/INSTRUCTIONS.md#instructions))?

**Comment by Tonsty** [comment]
@GabbySuwichaya @ahojnnes ，I found one possible solution is to add the following code
“camera.SetParams(database_cache_->Camera(image.CameraId()).Params());”  
at
https://github.com/colmap/colmap/blob/e3948b2098b73ae080b97901c3a1f9065b976a45/src/sfm/incremental_mapper.cc#L470，
this is because some cameras are optimized to be bogus (negative focal length lead to ransac max_error < 0 in pose 
estimation) and then removed in num_reg_images_per_camera_ by bogus params check.

**Comment by GabbySuwichaya** [comment]
Hi @Tonsty  I am going to try it. But which line in the script to remove **num_reg_images_per_camera_ by bogus params check** ?

**Comment by Tonsty** [comment]
@GabbySuwichaya , there is no need to modifty any code about num_reg_images_per_camera or bogus params check, adding the code I mentioned above should be enough.

**Comment by ahojnnes** [comment]
@GabbySuwichaya Thanks very much for your suggested fix. I studied the code again and can confirm that this is the correct fix. I applied it in the dev branch.
