### ISSUE TITLE
 can not build glog

### ISSUE THREAD

**Issue by gaqiang** [colmap/colmap#975]
Host Environment

    OS: Windows10 x64 professional 10.0.18362
    Compiler: Visual Studio Professional 2017 15.9.11Windows 10 SDK (10.0.17763.0)

To Reproduce
python G:/vc/colmap-3.6/scripts/python/build.py --build_path "G:/vc/colmap-3.6/Release"  --colmap_path "G:/vc/colmap-3.6"  --boost_path "E:/vs_library/boost_1_70_0" --qt_path "E:/Qt/Qt5.12.3/5.12.3/msvc2017_64" --cuda_path "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1" --cgal_path "C:/dev/CGAL-4.13.1/build" --cmake_generator "Visual Studio 15"

Failure logs
G:\vc\colmap-3.6\Release\glog\src\logging.cc(1439): warning C4267: “参数”: 从“size_t”转换到“unsigned int”，可能丢 失数据 [G:\vc\colma
p-3.6\Release\glog\__build__\glog.vcxproj]
G:\vc\colmap-3.6\Release\glog\src\logging.cc(1517): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据 [G:\vc\colmap-3.6\Re
lease\glog\__build__\glog.vcxproj]
G:\vc\colmap-3.6\Release\glog\src\logging.cc(1530): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据 [G:\vc\colmap-3.6\Re
lease\glog\__build__\glog.vcxproj]
G:\vc\colmap-3.6\Release\glog\src\logging.cc(1868): error C3861: “truncate”: 找不到标识符 [G:\vc\colmap-3.6\Release\glog\__bu
ild__\glog.vcxproj]
G:\vc\colmap-3.6\Release\glog\src\logging.cc(1886): error C3861: “S_ISREG”: 找不到标识符 [G:\vc\colmap-3.6\Release\glog\__bui
ld__\glog.vcxproj]
G:\vc\colmap-3.6\Release\glog\src\logging.cc(1913): error C3861: “ftruncate”: 找不到标识符 [G:\vc\colmap-3.6\Release\glog\__b
uild__\glog.vcxproj]
  raw_logging.cc
G:\vc\colmap-3.6\Release\glog\src\raw_logging.cc(153): warning C4267: “参数”: 从“size_t”转换到“unsigned int”，可能丢失数据 [G:\vc\co
lmap-3.6\Release\glog\__build__\glog.vcxproj]
  symbolize.cc
  utilities.cc
  vlog_is_on.cc
G:\vc\colmap-3.6\Release\glog\src\vlog_is_on.cc(163): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据 [G:\vc\colmap-3.6\
Release\glog\__build__\glog.vcxproj]
G:\vc\colmap-3.6\Release\glog\src\vlog_is_on.cc(163): warning C4267: “初始化”: 从“size_t”转换到“const int”，可能丢失数据 [G:\vc\colma
p-3.6\Release\glog\__build__\glog.vcxproj]
  正在生成代码...
Command failed: cmake --build . --target install --config Release -- /maxcpucount:8
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by ahojnnes** [comment]
I highly recommend using vcpkg to build under Windows, see: http://colmap.github.io/install.html#id3

**Comment by gaqiang** [comment]
> 
> 
> I highly recommend using vcpkg to build under Windows, see: http://colmap.github.io/install.html#id3

I have tried to build colmap serveral times using vcpk but failed to buid glob all the time.The seem thing happens when I tries to reinstall the colmap 3.5 which I used to install successfully.But I have solved the prolem by skip glog and moving the old version of libs of glog to the right place.But I still wonder why I can not build glog now.

**Comment by ahojnnes** [comment]
I cannot really help here to be honest. It seems specific to your machine setup and I also cannot read your language, so it's hard to gain any insight on your compiler output above.

**Comment by gaqiang** [comment]
@ahojnnes I agree with you.Maybe just something wrong with my system or machine.And thanks for your suggestion.And by the way,the "找不到标识符"in part of error C3861 means “The identifier could not be found”.I think these three errors are the key of the problem.I also tries to seek helps from VCPKG.But the suggestions from them just make me more believe there are something witn my computer.And thanks for the time you took to help me again.
