### ISSUE TITLE
when I do feature extraction,my PC is crashed

### ISSUE THREAD

**Issue by gotoBAT** [colmap/colmap#979]
I download COLMAP-3.6-windows-cuda,when I do feature extraction,my PC is crashed!
I try to solve this problem,but have no result.
Looking forward to your reply. Thank you.

**Comment by ahojnnes** [comment]
Which GPU does your system have?

**Comment by gotoBAT** [comment]
@ahojnnes 
GeForce RTX 2060
I try to run this software in ubuntu 18.04，unfortunately ，it also has  the same problem.
In my laptop，GPU is GTX 950M，it can run SFM without this problem.
Now，I think the main reason is GPU.

**Comment by pdycp3** [comment]
suggest you to run runtest.bat,see which error occurred

**Comment by gotoBAT** [comment]
> suggest you to run runtest.bat,see which error occurred

Thank you!
I will try this way later.

**Comment by gotoBAT** [comment]
@ahojnnes  @pdycp3  
I have found this error,a Low-level error!
Thank you!
