### ISSUE TITLE
Possible to fuse GPS information as prior into SfM?

### ISSUE THREAD

**Issue by lixx2938** [colmap/colmap#98]
Hi,

Is it possible to fuse GPS information of subsets of images as prior before doing SfM. Note that this is not the same as estimating similarity transformation that Colmap provides, all GPS might be noisy and I do want to refine all these camera poses after BA in SfM (i.e. provide GPS prior as initialization for subsets of images in SfM).

**Comment by ahojnnes** [comment]
It's not the same, but there is a ``--robust_alignment`` option for the ``model_aligner``, which should handle outliers in your GPS measurements. Note that the ``model_aligner`` does not modify the relative orientation/position of images in a reconstruction. It simply aligns the entire reconstruction by applying a similarity transformation to the images and points. At the moment, the only way to make use of GPS priors is for image matching, using the ``spatial_matcher``. Let me know if you have any other questions.

**Comment by ahojnnes** [comment]
Closing this issue for now as resolved, feel free to reopen in case you have more questions.

**Comment by is03wlei** [comment]
This function is needed.
