### ISSUE TITLE
Is there a way to import nvm file into colmap for patch_match_stereo?

### ISSUE THREAD

**Issue by chaoji90** [colmap/colmap#983]
**Describe the bug**
Hi,
Is there any way to import the nvm file to the patch_match_stereo process, or any script or tool to convert the nvm file format to the bins?

**Comment by ahojnnes** [comment]
No out of the box solution but it should be relatively straightforward to write an importer from NVM. You can get inspired by the Reconstruction::ExportNVM method on which fields have to be populated. If you wrote such a method, it would be great to contribute it back to the repository for the benefit of others.

**Comment by chaoji90** [comment]
> No out of the box solution but it should be relatively straightforward to write an importer from NVM. You can get inspired by the Reconstruction::ExportNVM method on which fields have to be populated. If you wrote such a method, it would be great to contribute it back to the repository for the benefit of others.

Thanks a lot for your suggestion, I will try to figure this out.

**Comment by henrypearce4D** [comment]
@chaoji90 Did you ever figure this out?
