### ISSUE TITLE
Does not recognize CUDA

### ISSUE THREAD

**Issue by koz7** [colmap/colmap#987]
Thank you for your great project.
I installed COLMAP following the instruction, but CUDA does not work.

>> nvidia-smi 
returns:
$NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1   

but, 
>> colmap
says:
$COLMAP 3.7 -- Structure-from-Motion and Multi-View Stereo
 (Commit af40e1a on 2020-09-21 without CUDA)

and 
>> colmap patch_match_stereo \
--workspace_path ~/colmap_result/models/dense \
--workspace_format COLMAP \
--PatchMatchStereo.geom_considtency true
returns:
$ERROR: Dense stereo reconstruction requires CUDA, which is not available on your system.

Now it seems that I have CUDA, why the installation does not recognize it?

Thank you bery much.

**Comment by ahojnnes** [comment]
Because you must compile COLMAP with CUDA support. Make sure that the CMake output shows successfully detected CUDA on your system.

**Comment by koz7** [comment]
@ahojnnes
Thank you for your reply and sorry for my late reply.
When I run cmake, it returns
-- Autodetected CUDA architecture(s):  7.5 6.1
-- Enabling CUDA support (version: 9.1, archs: sm_75 sm_61)
and clomap will be built without CUDA.
Is there anything wrong?

Thank you.

**Comment by koz7** [comment]
I solved this problem with reboot.
Thank you for your support!
