### ISSUE TITLE
Mac install failed with errors from Qt5

### ISSUE THREAD

**Issue by xiaofeiwu** [colmap/colmap#99]
I'm trying to install colmap on my Mac, however there are errors with Qt5. My mac version is Mac El Caption 10.11.6, and the Qt5 version is 5.8.0_1, which installed by _brew install qt5_. I have also added the configuration for my LocalConfig.cmake. The errors are:

In file included from /Users/xfwu/Documents/myWork/colmap/src/exe/spatial_matcher.cc:17:
In file included from /usr/local/opt/qt5/lib/QtWidgets.framework/Headers/QApplication:1:
In file included from /usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qapplication.h:52:
In file included from /usr/local/opt/qt5/lib/QtGui.framework/Headers/qguiapplication.h:46:
/usr/local/opt/qt5/lib/QtGui.framework/Headers/qinputmethod.h:87:5: error: unknown type name 'Q_ENUM'
    Q_ENUM(Action)
    ^
/usr/local/opt/qt5/lib/QtGui.framework/Headers/qinputmethod.h:87:19: error: expected ';' at end of
      declaration list
    Q_ENUM(Action)
                  ^
/usr/local/opt/qt5/lib/QtGui.framework/Headers/qinputmethod.h:94:5: error: unknown type name 'QLocale'
    QLocale locale() const;
    ^
In file included from /Users/xfwu/Documents/myWork/colmap/src/exe/feature_extractor.cc:17:
In file included from /usr/local/opt/qt5/lib/QtWidgets.framework/Headers/QApplication:1:
In file included from /usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qapplication.h:52:
In file included from /usr/local/opt/qt5/lib/QtGui.framework/Headers/qguiapplication.h:46:
/usr/local/opt/qt5/lib/QtGui.framework/Headers/qinputmethod.h:87:5: error: unknown type name 'Q_ENUM'
    Q_ENUM(Action)

....

The installation continues but finally it fails. It would be appreciated if there is any cue to solve it.

**Comment by ahojnnes** [comment]
Do you have different version of Qt installed? E.g. Qt4 and Qt5 or Qt5 through homebrew and another Qt5 but maybe through Python etc.?

**Comment by xiaofeiwu** [comment]
I don't think so. I check my brew again with _brew list_, and I can only find qt and qt5. By the way, I put LocalConfig.cmake in the colmap folder, and I also tried to put it in the cmake folder. Neither worked.

**Comment by xiaofeiwu** [comment]
Finally I found it is true that qt4 is installed in my Mac. I removed it and now colmap is successfully built. The issue can be closed.

**Comment by petioptrv** [comment]
@xiaofeiwu, how did you discover the other installation?
