### ISSUE TITLE
2D Pixel of Image to 3D Point of .ply 

### ISSUE THREAD

**Issue by andreas-at-talon** [colmap/colmap#991]
Hi everyone, hope you are doing well.

The problem that I am facing is a clean conversion between 2D Image to the Point Cloud. Meaning, I can pick any pixel of an image and get the corresponding 3D Point in the .ply file. If there are multiple, then I can just get the multiple and I can just pick the closest one.

What I have done so far:
Let's assume that the camera for the image we are evaluating is PINHOLE and we have camera.txt and images.txt. That means that the extra params of that camera will be of size 4, and we have the evaluated image params as well (QW, QX, QY, QZ, TX, TY, TZ). 

These are the steps I have followed so far:
# Image params
Reference: /base/pose.cc Line: 75
T = [TX, TY, TZ]
Q = [QW, QX, QY, QZ] and normalize Q
R = RotationMatrixfromQuart(Q)
R_T = append(R, T) (R being first 3 columns and T being 4th column)

# Camera params, assuming only PINHOLE camera
Reference: /base/camera.cc Line: 75
K = IdentityMatrix(3) # K: Callibration Matrix
K[0, 0] = params[0]
K[1, 1] = params[1]
K[0, 2] = params[2]
K[1, 2] = params[3]

# So now we can get our Projection Matrix:
Reference: /mvs/image.cc Line: 106
P_m = K x R_T

# Now we need our Inverse Projection Matrix:
Reference: /mvs/image.cc Line: 115
P_m = append(P_m, [0, 0, 0, 1]) (append [0, 0, 0, 1] as a last row to P_m)
inv_P_temp = inverse(P_m)
inv_P = only top 3 rows of inv_P_temp

# Now that we have our inverse projection matrix, lets assume we have the row and column of the pixel we are trying to convert to 3D Point. 
Reference: /mvs/fusion.cc Line: 373
depth = depthmap[row, col]
3D Point(in XYZ) = inv_P x [col * depth, row * depth, depth, 1]

Unfortunately, The calculated 3D point in the end does not match the real 3D Pt value found in the .ply file.
I have spent many hours reading src code to try and figure out this math. If the math is incorrect at any point or I am not following the right steps, please let me know.

Thank you for your time and patience.

**Comment by andreas-at-talon** [comment]
All this math was correct in the end, just had a bug. Thank you

**Comment by adizhol** [comment]
Hi @andreas-at-talon 
Why is projection matrix using R_T and not R?
isn't R the transform from world to frame?

Thanks!

**Comment by adizhol** [comment]
Ok, thanks. Also this helped:

https://github.com/colmap/colmap/issues/797#issuecomment-583592418

**Comment by ZhixiongSun** [comment]
> All this math was correct in the end, just had a bug. Thank you

Hi, May I ask you how you fix your bugs. Because I am trying to reconstrut a 3D ponit clouds from 2d depth image get from colmap. And I use the script in colmap project  read_write_dense.py to get depth image.
Could you please tell me how you use depth information to reconstruct the 3D ponit clouds
Thanks,

**Comment by shivaniraochepuri21** [comment]
> Hi everyone, hope you are doing well.
> 
> The problem that I am facing is a clean conversion between 2D Image to the Point Cloud. Meaning, I can pick any pixel of an image and get the corresponding 3D Point in the .ply file. If there are multiple, then I can just get the multiple and I can just pick the closest one.
> 
> What I have done so far: Let's assume that the camera for the image we are evaluating is PINHOLE and we have camera.txt and images.txt. That means that the extra params of that camera will be of size 4, and we have the evaluated image params as well (QW, QX, QY, QZ, TX, TY, TZ).
> 
> These are the steps I have followed so far:
> 
> # Image params
> Reference: /base/pose.cc Line: 75 T = [TX, TY, TZ] Q = [QW, QX, QY, QZ] and normalize Q R = RotationMatrixfromQuart(Q) R_T = append(R, T) (R being first 3 columns and T being 4th column)
> 
> # Camera params, assuming only PINHOLE camera
> Reference: /base/camera.cc Line: 75 K = IdentityMatrix(3) # K: Callibration Matrix K[0, 0] = params[0] K[1, 1] = params[1] K[0, 2] = params[2] K[1, 2] = params[3]
> 
> # So now we can get our Projection Matrix:
> Reference: /mvs/image.cc Line: 106 P_m = K x R_T
> 
> # Now we need our Inverse Projection Matrix:
> Reference: /mvs/image.cc Line: 115 P_m = append(P_m, [0, 0, 0, 1]) (append [0, 0, 0, 1] as a last row to P_m) inv_P_temp = inverse(P_m) inv_P = only top 3 rows of inv_P_temp
> 
> # Now that we have our inverse projection matrix, lets assume we have the row and column of the pixel we are trying to convert to 3D Point.
> Reference: /mvs/fusion.cc Line: 373 depth = depthmap[row, col] 3D Point(in XYZ) = inv_P x [col * depth, row * depth, depth, 1]
> 
> Unfortunately, The calculated 3D point in the end does not match the real 3D Pt value found in the .ply file. I have spent many hours reading src code to try and figure out this math. If the math is incorrect at any point or I am not following the right steps, please let me know.
> 
> Thank you for your time and patience.

Hi. It is mentioned in colmap documentation that the camera ids, image ids and 3d points ids (from cameras.txt, images.txt and points3D.txt respectively) are all unordered. From the sparse reconstruction itself, is there any way we can get 2d pixel to 3d point correspondences using math as you described? I basically want to give 2d pixel coordinates from an image and plot the corresponding 3d points. Does projecting the point cloud onto a 2d image help? Thanks IA.

**Comment by shivaniraochepuri21** [comment]
> All this math was correct in the end, just had a bug. Thank you

Hi could you please let me know what was the error? I have a similar issue. I got 3d points from points3D and their correspoing pixels in the 2d image. When I reproject these 3d points, there is a huge reprojection error between obtained 2d points and those in images.txt. I followed the same math as suggested in this thread. Thanks IA.
