### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by qingjiuling** [colmap/colmap#994]
HI,Thank` for this project,but I have some problem

my eigen is 3.2.10 and ceres is 1.14.0,received this error report

/home/magus/colmap/src/estimators/similarity_transform.h:115:3: error: ‘const class Eigen::ArrayWrapper<const Eigen::Block<Eigen::Matrix<double, 4, 4>, -1, -1, false> >’ has no member named ‘isNaN’
   if (model.array().isNaN().any()) {
   ^
/home/magus/colmap/src/feature/sift.cc: In function ‘std::size_t colmap::{anonymous}::FindBestMatchesOneWayBruteForce(const MatrixXi&, float, float, std::vector<int>*)’:
/home/magus/colmap/src/feature/sift.cc:62:8: error: ‘Index’ is not a member of ‘Eigen’
   for (Eigen::Index i1 = 0; i1 < dists.rows(); ++i1) {
        ^
/home/magus/colmap/src/feature/sift.cc:62:8: note: suggested alternative:
In file included from /home/magus/colmap/src/feature/sift.cc:38:0:
/home/magus/colmap/lib/FLANN/flann.hpp:76:7: note:   ‘flann::Index’
 class Index
       ^
/home/magus/colmap/src/feature/sift.cc:62:29: error: ‘i1’ was not declared in this scope
   for (Eigen::Index i1 = 0; i1 < dists.rows(); ++i1) {
                             ^
/home/magus/colmap/src/feature/sift.cc:66:10: error: ‘Index’ is not a member of ‘Eigen’
     for (Eigen::Index i2 = 0; i2 < dists.cols(); ++i2) {
          ^
/home/magus/colmap/src/feature/sift.cc:66:10: note: suggested alternative:
In file included from /home/magus/colmap/src/feature/sift.cc:38:0:
/home/magus/colmap/lib/FLANN/flann.hpp:76:7: note:   ‘flann::Index’
 class Index
       ^
/home/magus/colmap/src/feature/sift.cc:66:31: error: ‘i2’ was not declared in this scope
     for (Eigen::Index i2 = 0; i2 < dists.cols(); ++i2) {
                               ^
/home/magus/colmap/src/base/reconstruction.cc: In member function ‘void colmap::Reconstruction::ExtractColorsForAllImages(const string&)’:
/home/magus/colmap/src/base/reconstruction.cc:1255:12: error: ‘Index’ is not a member of ‘Eigen’
       for (Eigen::Index i = 0; i < color.size(); ++i) {
            ^
/home/magus/colmap/src/base/reconstruction.cc:1255:32: error: ‘i’ was not declared in this scope
       for (Eigen::Index i = 0; i < color.size(); ++i) {
                                ^
/home/magus/colmap/src/feature/sift.cc: In function ‘void colmap::{anonymous}::FindNearestNeighborsFLANN(const FeatureDescriptors&, const FeatureDescriptors&, Eigen::Matrix<int, -1, -1, 1, -1, -1>*, Eigen::Matrix<int, -1, -1, 1, -1, -1>*)’:
/home/magus/colmap/src/feature/sift.cc:237:8: error: ‘Index’ is not a member of ‘Eigen’
   for (Eigen::Index query_index = 0; query_index < indices->rows();
        ^
/home/magus/colmap/src/feature/sift.cc:237:8: note: suggested alternative:
In file included from /home/magus/colmap/src/feature/sift.cc:38:0:
/home/magus/colmap/lib/FLANN/flann.hpp:76:7: note:   ‘flann::Index’
 class Index
       ^
/home/magus/colmap/src/feature/sift.cc:237:38: error: ‘query_index’ was not declared in this scope
   for (Eigen::Index query_index = 0; query_index < indices->rows();
                                      ^
/home/magus/colmap/src/feature/sift.cc:239:10: error: ‘Index’ is not a member of ‘Eigen’
     for (Eigen::Index k = 0; k < indices->cols(); ++k) {
          ^
/home/magus/colmap/src/feature/sift.cc:239:10: note: suggested alternative:
In file included from /home/magus/colmap/src/feature/sift.cc:38:0:
/home/magus/colmap/lib/FLANN/flann.hpp:76:7: note:   ‘flann::Index’
 class Index
       ^
/home/magus/colmap/src/feature/sift.cc:239:30: error: ‘k’ was not declared in this scope
     for (Eigen::Index k = 0; k < indices->cols(); ++k) {
                              ^
/home/magus/colmap/src/feature/sift.cc:240:20: error: ‘Index’ in namespace ‘Eigen’ does not name a type
       const Eigen::Index database_index = indices->coeff(query_index, k);
                    ^
/home/magus/colmap/src/feature/sift.cc:243:21: error: expected primary-expression before ‘int’
               .cast<int>()
                     ^
In file included from /usr/include/CGAL/Triangulation_3.h:57:0,
                 from /usr/include/CGAL/Delaunay_triangulation_3.h:37,
                 from /home/magus/colmap/src/mvs/meshing.cc:39:
/usr/local/include/boost/bind.hpp:41:265: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
In file included from /home/magus/colmap/src/base/reconstruction.cc:41:0:
/home/magus/colmap/src/estimators/similarity_transform.h: In instantiation of ‘static std::vector<Eigen::Matrix<double, kDim, (kDim + 1)> > colmap::SimilarityTransformEstimator<kDim, kEstimateScale>::Estimate(const std::vector<Eigen::Matrix<double, num_rows, 1> >&, const std::vector<Eigen::Matrix<double, num_rows, 1> >&) [with int kDim = 3; bool kEstimateScale = true]’:
/home/magus/colmap/src/optim/loransac.h:141:42:   required from ‘typename colmap::RANSAC<Estimator, SupportMeasurer, Sampler>::Report colmap::LORANSAC<Estimator, LocalEstimator, SupportMeasurer, Sampler>::Estimate(const std::vector<typename Estimator::X_t>&, const std::vector<typename Estimator::Y_t>&) [with Estimator = colmap::SimilarityTransformEstimator<3>; LocalEstimator = colmap::SimilarityTransformEstimator<3>; SupportMeasurer = colmap::InlierSupportMeasurer; Sampler = colmap::RandomSampler; typename colmap::RANSAC<Estimator, SupportMeasurer, Sampler>::Report = colmap::RANSAC<colmap::SimilarityTransformEstimator<3>, colmap::InlierSupportMeasurer, colmap::RandomSampler>::Report; typename Estimator::X_t = Eigen::Matrix<double, 3, 1>; typename Estimator::Y_t = Eigen::Matrix<double, 3, 1>]’
/home/magus/colmap/src/base/reconstruction.cc:606:47:   required from here
/home/magus/colmap/src/estimators/similarity_transform.h:115:3: error: ‘const class Eigen::ArrayWrapper<const Eigen::Block<Eigen::Matrix<double, 4, 4>, -1, -1, false> >’ has no member named ‘isNaN’
   if (model.array().isNaN().any()) {
   ^

How can I solve this problem?

**Comment by qingjiuling** [comment]
now i know this is eigen3.2.10 to blame

**Comment by elliestath** [comment]
hey, what version did you use instead? I got the same problem on Ubuntu 18.04 and Eigen 3.2.10

**Comment by qingjiuling** [comment]
@elliestath Ubuntu16.04

**Comment by elliestath** [comment]
> @elliestath Ubuntu16.04
and what about Eigen?

**Comment by qingjiuling** [comment]
I'm not sure, because it's an automatic download
My solution is to directly uninstall the previous eigen, and then use sudo apt get install libeigen3-dev

> > @elliestath Ubuntu16.04
> > and what about Eigen?
